### ISSUE TITLE
lru_cache issue TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by lichla1988** [pydantic/pydantic#10022]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

pydantic             2.8.2
I have a class called class XYZQuery(BaseModel, frozen=True):
...
    @functools.lru_cache(maxsize=100)
    def get_person(self, id: int) 

TypeError: unhashable type: 'dict'

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/williamhart/Documents/IdeaProjects/IFRely/venv_3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @lichla1988,

Please attach a reproducible code snippet. Thanks!

**Comment by lichla1988** [comment]
from functools import lru_cache

from pydantic import BaseModel

"""

This represents 100's of complex python classes,  moving the cache methods outside 
of the class is not an option.

If you comment out the @lru_cache decorators this will run fine.

Notice: sum_it does run even as the other throw TypeError: unhashable type: 'CacheTest'

"""

class CacheTest(BaseModel):


    def sum_it(self, max_no:int) -> int:
        total = 0
        for i in range(max_no):
            total += i
        return total

    @lru_cache(maxsize=1024)
    def sum_it2(self, max_no:int) -> int:
        total = 0
        for i in range(max_no):
            total += i
        return total

    @lru_cache
    def sum_it3(self, max_no:int) -> int:
        total = 0
        for i in range(max_no):
            total += i
        return total

if __name__ == "__main__":
    ct = CacheTest()
    print(ct.sum_it(100))
    print(ct.sum_it2(1000))
    print(ct.sum_it3(1000))

**Comment by sydney-runkle** [comment]
Gotcha. You can set `frozen=True` in the model config to ensure that the model is hashable.

```py
from functools import lru_cache

from pydantic import BaseModel, ConfigDict

class CacheTest(BaseModel):

    def sum_it(self, max_no:int) -> int:
        total = 0
        for i in range(max_no):
            total += i
        return total

    @lru_cache(maxsize=1024)
    def sum_it2(self, max_no:int) -> int:
        total = 0
        for i in range(max_no):
            total += i
        return total

    @lru_cache
    def sum_it3(self, max_no:int) -> int:
        total = 0
        for i in range(max_no):
            total += i
        return total
    
    model_config = ConfigDict(frozen=True)

if __name__ == "__main__":
    ct = CacheTest()
    print(ct.sum_it(100))
    print(ct.sum_it2(1000))
    print(ct.sum_it3(1000))

"""
4950
499500
499500
"""
```

See [the docs](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.frozen) on this subject.
