### ISSUE TITLE
Support discarding nullable discriminated fields if discriminator match is not found

### ISSUE THREAD

**Issue by lijok** [pydantic/pydantic#10025]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I have an app config which is basically a list of configs, which will get matched up to some workflows that will get run when a CLI command is executed:

```py
# Reduced example

class ToolsCLIConfig(BaseModel):
    config_targets: list[Annotated[ConfigTargetConfig, Field(..., discriminator="type")]]
    
ConfigTargetConfig: TypeAlias = (
    AWSCodeArtifactPIPConfigTarget
    | AWSCodeArtifactNPMConfigTarget
)

class AWSCodeArtifactPIPConfigTarget(BaseModel):
    type: Literal["AWS_CODEARTIFACT_PIP"] = "AWS_CODEARTIFACT_PIP"
    authenticator: AWSCodeArtifactAuthenticatorConfig
    repository: str

class AWSCodeArtifactNPMConfigTarget(BaseModel):
    type: Literal["AWS_CODEARTIFACT_NPM"] = "AWS_CODEARTIFACT_NPM"
    authenticator: AWSCodeArtifactAuthenticatorConfig
    repository: str
```

The current situation is, if we add a new ConfigTargetConfig (say `AWSCodeArtifactYarnConfigTarget`), and push the updated config to the clients, clients running on the older version will break, effectively rendering a new capability as a breaking change.
What we want to happen, is for the new ConfigTargetConfig whose `type` doesn't match any of the available types, to be discarded and not appear in the list.

Perhaps a different form of `types.Discriminator` could be added which would allow the callable to return a sentinel value indicating the field should be dropped, and only allow that discriminator to be used as part of nullable fields?

If there already is a way to achieve this, please do tell me.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hmm, this reminds me a bit of https://github.com/pydantic/pydantic/issues/8394

**Comment by sydney-runkle** [comment]
Going to close this as a duplicate, as I think this is basically asking for an omittable annotation as explained in the other issue. That being said, I'll come up with a workaround for you in the meantime 👍

**Comment by sydney-runkle** [comment]
I think this example might be somewhat helpful, but I'd agree there's no clean way to achieve this right now: https://docs.pydantic.dev/latest/concepts/json/#partial-json-parsing

**Comment by sydney-runkle** [comment]
```py
from pydantic import BaseModel, ValidationError, field_validator, Field, WrapValidator
from pydantic_core import PydanticUseDefault
from typing import Literal, TypeAlias, Any, final
from typing_extensions import Annotated


class Dog(BaseModel):
    type: Literal['dog'] = 'dog'


class Cat(BaseModel):
    type: Literal['cat'] = 'cat'


Pet: TypeAlias = Dog | Cat


# new type
class Fish(BaseModel):
    type: Literal['fish'] = 'fish'


def default_on_error(v, handler) -> Any:
    try:
        return handler(v)
    except ValidationError:
        raise PydanticUseDefault()


@final
class _UnrecognizedType: ...


_UnrecognizedTypeDefault: Any = _UnrecognizedType()


class Model(BaseModel):
    pets: list[
        Annotated[Pet, Field(default=_UnrecognizedTypeDefault, discriminator='type'), WrapValidator(default_on_error)]
    ]

    @field_validator('pets', mode='after')
    def remove_nulls(cls, v) -> list[Pet]:
        return [x for x in v if x is not _UnrecognizedTypeDefault]


print(repr(Model(pets=[Cat(), Dog(), Fish()])))
#> Model(pets=[Cat(type='cat'), Dog(type='dog')])
```

**Comment by lijok** [comment]
Hey @sydney-runkle, thanks for looking into this. Agreed, the proposal you linked to would solve this issue.

Here's what we ended up going with in the meantime after discussing internally:
```py
class ToolsCLIConfig(BaseModel, extra="ignore"):
    aws_codeartifact_pip_config_targets: list[AWSCodeArtifactPIPConfigTarget]
    aws_codeartifact_npm_config_targets: list[AWSCodeArtifactNPMConfigTarget]

    @property
    def config_targets(self: Self) -> list[ConfigTargetConfig]:
        return self.aws_codeartifact_pip_config_targets + self.aws_codeartifact_npm_config_targets
    
ConfigTargetConfig: TypeAlias = (
    AWSCodeArtifactPIPConfigTarget
    | AWSCodeArtifactNPMConfigTarget
)

class AWSCodeArtifactPIPConfigTarget(BaseModel):
    type: Literal["AWS_CODEARTIFACT_PIP"] = "AWS_CODEARTIFACT_PIP"
    authenticator: AWSCodeArtifactAuthenticatorConfig
    repository: str

class AWSCodeArtifactNPMConfigTarget(BaseModel):
    type: Literal["AWS_CODEARTIFACT_NPM"] = "AWS_CODEARTIFACT_NPM"
    authenticator: AWSCodeArtifactAuthenticatorConfig
    repository: str
```
