### ISSUE TITLE
Nested generic inheritance

### ISSUE THREAD

**Issue by rubenbriones** [pydantic/pydantic#10039]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Is there a way for `MyClassSubBool` to be recognized as an instance of `MyClass[bool]` , apart from inheriting the functionality from `MyClassSub`?

If I use multiple inheritance in `class MyClassSubBool(MyClassSub, MyClass[bool])` I do get the example to work, but it doesn't seem the most pythonic way.

Thanks for your help.

### Example Code

```Python
from typing import Generic, TypeVar

from pydantic import BaseModel

T = TypeVar('T')


class MyClass(BaseModel, Generic[T]):
    pass


class MyClassSub(MyClass[T]):
    pass


class MyClassSubBool(MyClassSub[bool]):
    pass


class Model(BaseModel):
    input_bool: MyClass[bool]


if __name__ == '__main__':
    instance_fails = Model(input_bool=MyClassSubBool())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.3
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
               python version: 3.11.4 (main, Sep 12 2023, 11:07:53) [GCC 11.4.0]
                     platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by Viicos** [comment]
I simplified your example code to make it easier to understand. Overall I think this is a reasonable request, it is accepted from a type checking perspective.
