### ISSUE TITLE
Inconsistent documentation of `field_serializer` method signature error

### ISSUE THREAD

**Issue by menzenski** [pydantic/pydantic#10034]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm trying to implement a custom field serializer for the first time. I have a model with an `Optional[set[str]]` field that I want to serialize as a list. My model raised an error during serialization. The error message included the text `For further information visit https://errors.pydantic.dev/2.8/u/field-serializer-signature`.

That section of the docs ("Unrecognized `field_serializer` signature")  has a subsection with "Valid serializer signatures are:" but that list only includes _model_ serializer methods, not field serializer methods. The next section of the docs is "Unrecognized `model_serializer` signature",, but it has no examples section at all.

I wonder if the examples currently under the field serializer section  (again, they all seem to be examples of model serializers) should be moved under the next section, and new examples of field serializers added to the field serializers section.

The https://docs.pydantic.dev/latest/api/functional_serializers/#pydantic.functional_serializers.field_serializer section of the docs seems to have the actual data that I was looking for - the four allowed signatures for a `field_serializer` method. Maybe this could be added to the page linked in the error message?

### Python, Pydantic & OS Version

```Text
poetry run python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/matt/Library/Caches/pypoetry/virtualenvs/mypackage-K-xaVXW7-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-13.6.6-x86_64-i386-64bit
             related packages: typing_extensions-4.12.2 pydantic-settings-2.4.0 mypy-1.11.1
                       commit: unknown
```

**Comment by Viicos** [comment]
Thanks for the issue, seems like this is a duplicate as it was recently fixed by https://github.com/pydantic/pydantic/pull/10006!
