### ISSUE TITLE
Field typed as BaseModel for polymorphism serializes as an empty dict

### ISSUE THREAD

**Issue by JPK314** [pydantic/pydantic#10044]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I would like to use polymorphism in my typing definitions for a model as shown in the example. In practice, I have a dict of arbitrary models that all inherit from BaseModel, but the example is simplified as much as possible to demonstrate the issue.

The expected result is the following:
`{"internal":{"field1":1}}`

The actual result is the following:
`{"internal":{}}`

### Example Code

```Python
from pydantic import BaseModel


class InternalModel(BaseModel):
    field1: int = 1


class MyModel(BaseModel):
    internal: BaseModel

my_model = MyModel(internal=InternalModel())
print(my_model.model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\User\miniconda3\envs\strikoid\Lib\site-packages\pydantic
               python version: 3.9.19 (main, May  6 2024, 20:12:36) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: typing_extensions-4.12.0
                       commit: unknown
```

**Comment by Gu-f** [comment]
It looks like you need to specify the type of internal as `InternalModel`  
```
class MyModel(BaseModel):
    internal: InternalModel
```

**Comment by JPK314** [comment]
I don't want to do that because that doesn't allow for polymorphism (multiple different child classes of BaseModel being used for `internal`. I think maybe the intention isn't for the types inside a Model to be used for polymorphism, and instead the type you put is the strict type required (not allowing subclasses). But then I would expect that the validation would fail on the constructor call to MyModel, so something is wrong either way.

**Comment by Gu-f** [comment]
I'm not sure if BaseModel is limiting this. For root objects, you can try using `RootModel`  
See if you can solve your problem.
```python
class MyModel(BaseModel):
    internal: RootModel
```

**Comment by JPK314** [comment]
Using RootModel worked. I'm not sure why this behavior is like this though, can you explain?

**Comment by kc0506** [comment]
It seems that you can use [`SerializeAsAny`](https://docs.pydantic.dev/latest/concepts/serialization/#serializing-with-duck-typing) to dump all fields of a model. 
```py
class MyModel(BaseModel):
    internal: SerializeAsAny[BaseModel]
```
By default `model_dump_json` only dump the fields of **annoated** model (i.e. `BaseModel`, which doesn't have any field), not actual model (`InternalModel`), I guess.

**Comment by Gu-f** [comment]
> Using RootModel worked. I'm not sure why this behavior is like this though, can you explain?

I can't explain exactly, RootModel inherits BaseModel and has arbitrary types of fields, so it works. However, this may not be standard usage and does not meet the module authors' expectations.

**Comment by Viicos** [comment]
> It seems that you can use [`SerializeAsAny`](https://docs.pydantic.dev/latest/concepts/serialization/#serializing-with-duck-typing) to dump all fields of a model.
> 
> ```python
> class MyModel(BaseModel):
>     internal: SerializeAsAny[BaseModel]
> ```
> 
> By default `model_dump_json` only dump the fields of **annotated** model (i.e. `BaseModel`, which doesn't have any field), not actual model (`InternalModel`), I guess.

`SerializeAsAny` is the correct way to handle your use case (explanation can be found in the linked docs). Thanks @kc0506 for the answer
