### ISSUE TITLE
Pass self instance or it type into functional validators.

### ISSUE THREAD

**Issue by heckad** [pydantic/pydantic#10045]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Now if you use `field_validator` you can get a class but in functional validators you are deprived of this opportunity. It would be nice to add the class itself or its instance to the info.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
I think I understand the question - things like `PlainValidator` and `WrapValidator` don't support a `cls` reference, whereas the `field_validator` supports decorating a function that is a class method.

This isn't something we plan to support in the short term. Given that there's the easy alternative of using a validation decorator if you want access to `cls`, I'm going to mark this as not planned. You can further explore allowed signatures in this file: https://github.com/pydantic/pydantic/blob/main/pydantic/functional_validators.py

**Comment by heckad** [comment]
Then that makes functional validators absolutely useless for cases [like this](https://github.com/pydantic/pydantic-settings/issues/169). It would be nice to write something like 
```python
class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_nested_delimiter="__")

    db: IfEnabled[DbSettings]
```
instead of 
```python
class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_nested_delimiter="__")

    db: Optional[DbSettings] = None

    @field_validator('db', mode='before')
    def load_if_env_available(cls, v):
        if os.environ.get('DB_ENABLED'):
            print(v)
            return v
        return None
```

**Comment by Viicos** [comment]
What prevents you from doing:

```python
import os
from typing import Annotated, Any

from pydantic import BaseModel, BeforeValidator


def load_if_enabled(value: Any) -> Any | None:
    if os.environ.get('DB_ENABLED'):
        return value


class Db(BaseModel):
    host: str


class Settings(BaseModel):
    db: Annotated[Db | None, BeforeValidator(load_if_enabled)]
```

You can also define your `IfEnabled` with the following:

```python
import os
from typing import Annotated, Any, TypeVar

from pydantic import BaseModel, BeforeValidator


def load_if_enabled(value: Any) -> Any | None:
    if os.environ.get('DB_ENABLED'):
        return value


T = TypeVar("T")

IfEnabled = Annotated[T | None, BeforeValidator(load_if_enabled)]


class Db(BaseModel):
    host: str


class Settings(BaseModel):
    db: IfEnabled[Db]
```

**Comment by heckad** [comment]
If `DB_ENABLED` is not set the host can be not set in env. For example db not required for this service. In that case we got validation error: `Field required`. We should construct Db class only if `DB_ENABLED` presents in environmental.
