### ISSUE TITLE
(🎁) ability to inherit field config

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10046]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

in this case i would like to specify a different type for a field in a subclass, but i would like to preserve/inherit the fields configuration (alias etc)

```py
from pydantic import BaseModel, Field


class A(BaseModel):
    a: object = Field(alias="b")


class B(A):
    a: bool


print(B(b=True))  # erm, fail...
```

# desired outcome 😄
```py
print(B(b=True))  # a=True
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@KotlinIsland,

Good question. I'd say the best solution for this with our current patterns is to use `create_model`:

```py
from pydantic import BaseModel, Field, create_model


class A(BaseModel):
    a: object = Field(alias='b')


B = create_model('B', __base__=A, a=(bool, A.model_fields['a']))

print(B(b=True))
#> a=True
from pydantic import BaseModel, Field, create_model


class A(BaseModel):
    a: object = Field(alias='b')


B = create_model('B', __base__=A, a=(bool, A.model_fields['a']))

print(B(b=True))
#> a=True
```

I don't anticipate supporting cherry picking field configs, so going to close this as resolved. In general, I think it makes sense that we don't preserve `Field(...)` specifications if a type is overridden, as that would result in failure for a variety of situations, and would be a breaking change. I'm not inclined to support an opt in version of this either, when the `create_model` approach works well enough for this type of reuse.

This also works, but is super type unsafe for a variety of reasons:

```py
from pydantic import BaseModel, Field, create_model


class A(BaseModel):
    a: object = Field(alias='b')


class B(A):
    a: bool = A.model_fields['a']

print(B(b=True))
#> a=True
```
