### ISSUE TITLE
中文文档上线了 🎉 🎉 🎉 原汁原味的中文

### ISSUE THREAD

**Issue by horizon365** [pydantic/pydantic#10068]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

[中文文档上线了](https://pydantic.com.cn/) 🎉 🎉 🎉 
原汁原味的中文 https://pydantic.com.cn/

**Comment by sydney-runkle** [comment]
Hi @horizon365,

Happy to consider your feature request, but please write it out in English. Going to close this for now. Thanks!
