### ISSUE TITLE
Pydantic is unable to serialize due to unknown type

### ISSUE THREAD

**Issue by lmores** [pydantic/pydantic#10060]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I need to serialize a pydantic dataclass (`MainObj` in the example below) which contains other plain nested objects, however an exception is raised during serialization as the `MyObj` type is unknown to pydantic.

If I run `python example.py`, at line `j = MAIN_OBJ_TA.dump_json(obj)` I get
```python
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class '__main__.MyObj'>
```

However, if I turn `MyObj` into a python dataclass (remove the comment before its definition), it works and I see

```python
b'{"a":1,"b":"asd","c":{"x":10,"y":"lol"}}'
```

Is this the intended behaviour? I would like to be able to serialize objects like `MyObj` without turning them into dataclasses (nor `BaseModel`s) as in my real use case I have no control over some of them (but I do know that each of them is fully typed).

### Example Code

```Python
from dataclasses import dataclass as python_dataclass

from pydantic import TypeAdapter
from pydantic.dataclasses import dataclass as pydantic_dataclass


# @python_dataclass
class MyObj:
    x: int
    y: str

    def __init__(self, x, y):
        self.x = x
        self.y = y


@pydantic_dataclass(config={'arbitrary_types_allowed': True})
class MainObj:
    a: int
    b: str
    c: MyObj


MAIN_OBJ_TA = TypeAdapter(MainObj)


if __name__ == '__main__':
    obj = MainObj(a=1, b="asd", c=MyObj(x=10, y="lol"))
    j = MAIN_OBJ_TA.dump_json(obj)
    print(j)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=false
                 install path: **OMISSIS**/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:48) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-10.13.6-x86_64-i386-64bit
             related packages: typing_extensions-4.12.1
                       commit: unknown
```

_NOTE: this is a (edited) duplicate of this stackoverflow [question](https://stackoverflow.com/questions/78825070/pydantic-unknown-type-during-serialization)._

**Comment by sydney-runkle** [comment]
Hi @lmores,

Indeed. This is expected. You'll have to clue `pydantic` in on how to serialize that type of object. Here's a simple example:

```py
from pydantic import TypeAdapter, ConfigDict, PlainSerializer
from typing_extensions import Annotated


class MyObj:
    x: int
    y: str

    def __init__(self, x, y):
        self.x = x
        self.y = y

MAIN_OBJ_TA = TypeAdapter(
    Annotated[MyObj, PlainSerializer(lambda o: {'x': o.x, 'y': o.y})], 
    config=ConfigDict(arbitrary_types_allowed=True)
)


j = MAIN_OBJ_TA.dump_json(MyObj(x=10, y="lol"))
print(j)
"""b'{"x":10,"y":"lol"}'"""
```
