### ISSUE TITLE
Support for Snowflake DSN format

### ISSUE THREAD

**Issue by menzenski** [pydantic/pydantic#10079]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Pydantic's [Network Types](https://docs.pydantic.dev/latest/api/networks/) includes a number of database-specific types: PostgresDsn, MongoDsn, etc.

There is no DSN type for [Snowflake](https://www.snowflake.com/en/), and I have recently run into a need for one. So I am logging this feature request in case this is something with broader appeal to the community.

Snowflake's documentation includes references to a DSN format with a `snowflake://` scheme, for example: https://docs.snowflake.com/en/developer-guide/python-connector/sqlalchemy#verifying-your-installation shows:

```python
engine = create_engine(
    'snowflake://{user}:{password}@{account_identifier}/'.format(
        user='<user_login_name>',
        password='<password>',
        account_identifier='<account_identifier>',
    )
)
```

It seems like this is something that is straightforward to define within my project, so if this doesn't make sense to add to Pydantic I have no concerns - I assume I would start from something like this:

```python
SnowflakeDsn = Annotated[
    Url,
    UrlConstraints(
        host_required=True,
        allowed_schemes=[
            'snowflake',
        ],
    ),
]
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Sounds great, PRs welcome!

**Comment by aditkumar72** [comment]
@sydney-runkle if no one is working on it, Could you please assign this to me ?

**Comment by Vasanth-96** [comment]
Hi @aditkumar72  are you still working on it? i have my PR ready if youre not then let me know thanks.

**Comment by sydney-runkle** [comment]
@Vasanth-96, go ahead and submit your PR, I can review tomorrow :)

**Comment by menzenski** [comment]
Thank you @aditkumar72 !
