### ISSUE TITLE
Refactor how we handle parent namespaces for model construction

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10074]
Right now, we store a `__pydantic_parent_namespace__` attribute on each model when we build the core schema. This cache is used for model rebuilds, resolving forwardrefs, and typevar substitution.

This is fine enough for small namespaces, but quickly becomes very problematic for those with hundreds or thousands of models, both from a memory perspective + a build time perspective.

We've introduced an experimental opt in config setting here: https://github.com/pydantic/pydantic/pull/10064 that skips the parent namespace logic all together.

Long term, I'd love to move away from this pattern because of the aforementioned costs. I think the first step here will be refactoring how we generate generic schemas, as suggested by @adriangb in https://github.com/pydantic/pydantic-core/issues/1371.

I think @dmontagu also had some good ideas about looking ahead at annotations to filter down what references we do retain, if any, in a local namespace cache. Also in David's words, I think we should try to avoid "pathological manipulation" of the namespace when possible 😓.

**Comment by Viicos** [comment]
One idea was to skip building the types namespace (and getting the parent namespace as well) if no stringified annotations are present. Something like:

```python
if any(isinstance(ann, str) for ann in cls.__annotations__.values()):
    # Only build types namespace if they are stringified annotations
    if __pydantic_reset_parent_namespace__:
        cls.__pydantic_parent_namespace__ = build_lenient_weakvaluedict(parent_frame_namespace())
    parent_namespace = getattr(cls, '__pydantic_parent_namespace__', None)
    if isinstance(parent_namespace, dict):
        parent_namespace = unpack_lenient_weakvaluedict(parent_namespace)

    types_namespace = get_cls_types_namespace(cls, parent_namespace)
else:
    types_namespace = {}
```

This brings a 2s improvement on a large file originally taking 15s. However, string literals as part of a type hint can be used, e.g. `list['int']`. This makes things harder to handle, it is more involved than a simple `isinstance(ann, str)`.

**Comment by sydney-runkle** [comment]
@Viicos, could you push your branch with these changes? I'd love to take a look!

Great work here, I think this is worth pursing, but perhaps not with high urgency.

**Comment by sydney-runkle** [comment]
Going to move this to `done` in regards to our v2.9 work - feels like it's not worth addressing the "edge cases of edge cases" here with any particular urgency.

**Comment by sydney-runkle** [comment]
One other thing I'd like to reconsider here is if we can restructure some of the namespace fetching functions so that they serve more independent use cases, and use each only when needed.

**Comment by sydney-runkle** [comment]
A few other things I'd like to consider here:

- [ ] avoid copying + reallocating space for namespaces when that has already been done, see https://github.com/pydantic/pydantic/pull/10261 for example.
- [ ] can we use some sort of global namespace cache to improve performance?
- [ ] can we avoid all of the copying with the push operation in the types namespace stack in `_generate_schema.py`?

One idea that I had:

```py
@lru_cache(maxsize=None)
def get_module_ns(module_name: str) -> dict[str, Any]:
    try:
        return sys.modules[module_name].__dict__.copy()
    except KeyError:
        return {}
```

I think this runs into problems with generics and forwardrefs.

**Comment by sydney-runkle** [comment]
I'm happy to close this given @Viicos' work in https://github.com/pydantic/pydantic/pull/10530.

I think we should probably put a significant pause on any further namespace management work for now, and pivot to more of a core schema building performance focus.
