### ISSUE TITLE
Make opt-in fast build a global setting

### ISSUE THREAD

**Issue by michaelgmiller1** [pydantic/pydantic#10076]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

In https://github.com/pydantic/pydantic/pull/10064, a new flag was added for an experimental setting to enable fast build.

There is no way our app can migrate without this fix. But annotating every single one of the models would be very cumbersome. Can you add a mechanism to enable fast-build globally for all models?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
We discussed about defining an environment variable, but this would enable the flag for every model, even the ones you don't own defined in external libraries.

Perhaps you could define your own base `BaseModel`, and update the imports throughout your code base?

Alternatively you can do the following:

```python
BaseModel.model_config = {"experimental_fast_build": True}
```

As soon as you import your codebase.

**Comment by michaelgmiller1** [comment]
Subclassing all models would be tedious, but I think your suggestion of setting a global model config would work. Will give it a try when 2.9 is released.

**Comment by Viicos** [comment]
Of course we can still revisit (cc @sydney-runkle), but if it does work by globally mutating the `BaseModel.model_config` attribute, then I think we could keep it as is.

**Comment by sydney-runkle** [comment]
Yeah, we'd recommend something like:

```py
from pydantic import BaseModel as BM, ConfigDict

class BaseModel(BM):
    model_config = ConfigDict(experimental_fast_build=True)
```

Going to close this as resolved for now - we're planning on making this speedup apply in all cases, as explained here: https://github.com/pydantic/pydantic/issues/10074
