### ISSUE TITLE
Improve `pyright` test suite

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#10078]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

With [PEP 747: TypeExpr](https://discuss.python.org/t/pep-747-typeexpr-type-hint-for-a-type-expression/55984) hopefully just around the corner, we will be able to update our type hints related to `TypeAdapter`, and perhaps in other places as well.

While we currently have `mypy` tests running, we use `pyright` as a type checker. It would thus be great to add tests to assert that our type hints behave as expected. We should get inspired by how tests are [setup in typeshed](https://github.com/python/typeshed/tree/main/stdlib/%40tests/test_cases), namely using [`assert_type`](https://docs.python.org/3/library/typing.html#typing.assert_type).

Tasks:
- Add type checking tests. We should run `pyright` and `mypy` on it.
- Move the existing mypy tests that don't relate to the plugin.
- Document that we support `mypy` and `pyright` as type checkers. It might be that some features we use are unsupported by `mypy`, we do our best on that end.
- Drop some old mypy versions in the test suite.
- Maybe rework the test logic?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@Viicos,

We have a few - https://github.com/pydantic/pydantic/tree/main/tests/pyright

**Comment by Viicos** [comment]
Ah nice! Will continue working on this then
