### ISSUE TITLE
New type for attachable properties 

### ISSUE THREAD

**Issue by MirS0bhan** [pydantic/pydantic#10089]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

In my project, I have some properties that are necessary, but I can't set them during the initialization of the model. I use models to gather data about an operation at distinct levels, so I need a type in addition to Optional that indicates the property is required but cannot be set at this moment. I will attach it later.

like this
```python
class X(BaseModel):
    x:Optional[int]
    y:Pending[str]
    z:int


a = X(x=7,z=2)        # we didn't get any error
a.model_dump()        # here we gonna get an error because y is not attached yet
a.y = "miao"          #  
a.model_dump()        # every thing is fine
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Closing as a dupe of https://github.com/pydantic/pydantic/issues/8394

**Comment by MirS0bhan** [comment]
@sydney-runkle i can't see any common between their. what should i do ?

**Comment by sydney-runkle** [comment]
@MirS0bhan, I'll reopen, I agree, this is a bit of a different request. Common thread through.

**Comment by MirS0bhan** [comment]
i figured out I can do that with Lazy type and I proposed it in #10032
