### ISSUE TITLE
Recursively update schemas when a referenced type's schema is updated

### ISSUE THREAD

**Issue by DiamondJoseph** [pydantic/pydantic#10091]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When making a discriminated union which may have additional entries created at runtime, the schema of the union must be updated, and the update propagated into any schemas that reference it. In turn, those schemas may be referenced from other schemas, which are now outdated.

I propose that the functions rebuild_dataclass and BaseModel.model_rebuild take a parameter `recursive`, and that dataclass and BaseModel keep a record of all models where they are used as fields. When rebuild is called with recursive=True, a directed acyclic graph is created and iterated through, calling rebuild again recursively for all related models.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by DiamondJoseph** [comment]
For my use case (in the PR mentioned above), having a tagged union that has members added at run time, `super_cls.__init_subclass__` adds `sub_cls` to `_members` then calls `rebuild_schema(super_cls, recursive=True, force=True)` and `__get_pydantic_core_schema__` for `super_cls` is:
 
```
        return tagged_union_schema(
            make_schema(tuple(self._members), handler),
            discriminator=self._discriminator,
            ref=self._base_class.__name__,
        )
```

**Comment by sydney-runkle** [comment]
Hi @DiamondJoseph,

Thanks for the detailed feature request. I think this would introduce a lot of overhead + performance challenges. I think something like this could belong in user code by customizing the `__new__` method or something similar, but I don't see us implementing support for this in the `pydantic` codebase in the short term.

I'll try to come up with a MRE for you regarding how you could implement this in your own code.

**Comment by sydney-runkle** [comment]
This doesn't exactly work, but here's the idea:

```py
from pydantic import BaseModel as BM, ConfigDict
from pydantic._internal._core_utils import pretty_print_core_schema

global_rebuild_cache = []

class BaseModel(BM):
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

        print(cls.__annotations__)
        for annotation in cls.__annotations__.values():
            if annotation.__name__ == 'InnerModel':
                global_rebuild_cache.append(cls)

class InnerModel(BaseModel):
    foo: str

class Model1(BaseModel):
    inner: InnerModel

class Model2(BaseModel):
    inner: InnerModel

print(global_rebuild_cache)
pretty_print_core_schema(Model1.__pydantic_core_schema__)

# redefine InnerModel to simulate some sort of dynamic update
# with defer_build set to true to similate a manual update for the schema
class InnerModel(BaseModel):
    model_config = ConfigDict(defer_build=True)

    foo: str
    bar: str

InnerModel.model_rebuild()

for dependent_model in global_rebuild_cache:
    dependent_model.model_rebuild(force=True)

pretty_print_core_schema(Model1.__pydantic_core_schema__)
```

You'll probably need to figure out how to avoid caching the namespace.
