### ISSUE TITLE
Schema generation with `by_alias=False` and an aliased discriminator field causes alias to be used instead of field name

### ISSUE THREAD

**Issue by exs-dwoodward** [pydantic/pydantic#10131]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hi pydantic devs, I believe I've spotted a bug in `pydantic~=1.*`, whereby if a model has a field that is a discriminated union type, discriminator field with an alias, if the schema of the overarching model is created with `by_alias=False` then the `schema[...]["discriminator"]["propertyName"]` is the discriminator *alias* rather than the discriminator field name. 

I believe this to be a bug, as one would expect the property name to relate to the discriminator name with `by_alias=False`. 

For example: 
```python
from pydantic import BaseModel, Field
from typing import Literal, Union


class Model1(BaseModel):
    type_: Literal["model1"] = Field(alias="name")


class Model2(BaseModel):
    type_: Literal["model2"] = Field(alias="name")


class Parent(BaseModel):
    model: Union[Model1, Model2] = Field(discriminator="type_")


Parent.schema(by_alias=False)
``` 
provides:
```python
{'title': 'Parent',
 'type': 'object',
 'properties': {'model': {'title': 'Model',
   'discriminator': {**'propertyName': 'name',**
    'mapping': {'model1': '#/definitions/Model1',
     'model2': '#/definitions/Model2'}},
   'oneOf': [{'$ref': '#/definitions/Model1'},
    {'$ref': '#/definitions/Model2'}]}},
 'required': ['model'],
 'definitions': {'Model1': {'title': 'Model1',
   'type': 'object',
   'properties': {'type_': {'title': 'Name',
     'enum': ['model1'],
     'type': 'string'}},
   'required': ['type_']},
  'Model2': {'title': 'Model2',
   'type': 'object',
   'properties': {'type_': {'title': 'Name',
     'enum': ['model2'],
     'type': 'string'}},
   'required': ['type_']}}}
``` 

Note I think this is a one-line change from [here](https://github.com/pydantic/pydantic/blob/1.10.X-fixes/pydantic/schema.py#L741) to:
```python
"propertyName": field.discriminator_alias if by_alias else field.discriminator_key
``` 

Happy to make the PR myself if need be!

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Literal, Union


class Model1(BaseModel):
    type_: Literal["model1"] = Field(alias="name")


class Model2(BaseModel):
    type_: Literal["model2"] = Field(alias="name")


class Parent(BaseModel):
    model: Union[Model1, Model2] = Field(discriminator="type_")


Parent.schema(by_alias=False)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.17
pydantic compiled: True
python version: 3.11.9
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@exs-dwoodward,

Good call. Feel free to open a PR, I'll review, and we can include this in the next v1 release. Thanks!

**Comment by sydney-runkle** [comment]
Fixed by #10146 :)

**Comment by exs-dwoodward** [comment]
> @exs-dwoodward,
> 
> Good call. Feel free to open a PR, I'll review, and we can include this in the next v1 release. Thanks!

Q: what would be the timeline for the next v1 bugfix release out of interest? 🙏

**Comment by sydney-runkle** [comment]
@exs-dwoodward, will do in a week or so with the v2.9 beta release!
