### ISSUE TITLE
model_validator mode="before" applied in the wrong order (from current class to base)

### ISSUE THREAD

**Issue by MrNaif2018** [pydantic/pydantic#10135]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In pydantic v1, if we declared a root_validator with pre=True in Base model and in a subclass, it would first call the base root validator, and then the subclass one. It makes sense to e.g. customize some logic in all models

```python
from pydantic import BaseModel, root_validator


class Base(BaseModel):
    x: int
    y: str

    @root_validator(pre=True)
    @classmethod
    def base_validator(cls, values):
        print("CALL 1")
        values["x"] = 1
        return values


class Model(Base):

    @root_validator(pre=True)
    @classmethod
    def model_validator(cls, values):
        print("CALL 2")
        values["x"] = 2
        return values


model = Model(x=3, y="a")

print(model)
```

Outputs first CALL 1, then CALL 2, as expected

But in pydantic v2, it's vice versa: first the subclass model_validator is called, and only then in BaseModel. It's counter-intuitive

Maybe there's a way to workaround this, but I was using it to workaround another issue: when using from_attributes=True, `model_validator` with `mode="before"` receives a model object instead of a dictionary, so my custom logic doesn't expect this and I need to make the same conversions pydantic-core does here: https://github.com/pydantic/pydantic-core/blob/bb67044c67b705d3ac7990ef067deb786e8d5afe/src/input/return_enums.rs#L293-L331

### Example Code

```Python
from pydantic import BaseModel, model_validator


class Base(BaseModel):
    x: int
    y: str

    @model_validator(mode="before")
    @classmethod
    def base_validator(cls, values):
        print("CALL 1")
        values["x"] = 1
        return values


class Model(Base):

    @model_validator(mode="before")
    @classmethod
    def model_validator(cls, values):
        print("CALL 2")
        values["x"] = 2
        return values


model = Model(x=3, y="a")

print(model)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/alex/envs/bitcart/lib/python3.9/site-packages/pydantic
               python version: 3.9.19 (main, Apr  6 2024, 17:57:55)  [GCC 11.4.0]
                     platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
             related packages: fastapi-0.110.3 pydantic-settings-2.4.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by MrNaif2018** [comment]
@sydney-runkle but isn't it considered a regression that validation call order changed (without using wrap validators, just 2 before validators)? When would it make sense to call first before validators of the actual class, and before validators of the base class as the last validator? Could this maybe be reconsidered for v3?
I got around the issue using wrap validators, but it was just a lucky coincidence due to how those validators are called in rust

**Comment by sydney-runkle** [comment]
Hmm, I wouldn't necessarily call this a regression, just a change in v2 that could be better documented. I'll sync with the team early next week to make sure...
