### ISSUE TITLE
`use_enum_values=True` with an Enum Literal

### ISSUE THREAD

**Issue by tomhamiltonstubber** [pydantic/pydantic#10133]
### Discussed in https://github.com/pydantic/pydantic/discussions/8684

Is this desired behaviour? IMO `model_dump` should return the Enum's value?

----
<div type='discussions-op-text'>

<sup>Originally posted by **MacHankus** January 30, 2024</sup>
Hi,
I want to build model with literal value of my enum, so that field could accept only one possible value based on enum value.
But when I built this I found that model_dump is not converting my literal enum to string value.

The code:
```
from pydantic import BaseModel
from enum import StrEnum

class SomeEnum(StrEnum):
    ONE = "one"
    TWO = "two"

from pydantic import BaseModel, ConfigDict
from typing import Literal

class SomeModel(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    literal_enum: Literal[SomeEnum.ONE]
    value: int = 1

model = SomeModel(literal_enum=SomeEnum.ONE)
model.model_dump()
``` 
The output
```
{'literal_enum': <SomeEnum.ONE: 'one'>, 'value': 1}
```

Is it possible to create field based on literal enum value like that and still convert enum to string value ? 
</div>

**Comment by sydney-runkle** [comment]
Hi! This is fixed on `main`, and will be released in v2.9 later this month:

```py
from pydantic import BaseModel
from enum import Enum

class SomeEnum(str, Enum):
    ONE = "one"
    TWO = "two"

from pydantic import BaseModel, ConfigDict
from typing import Literal

class SomeModel(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    literal_enum: Literal[SomeEnum.ONE]
    value: int = 1

model = SomeModel(literal_enum=SomeEnum.ONE)
print(model.model_dump())
#> {'literal_enum': 'one', 'value': 1}
```
