### ISSUE TITLE
Lazy Import for Field Types

### ISSUE THREAD

**Issue by atodniAr** [pydantic/pydantic#10147]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently if you do:
```python
from typing import TYPE_CHECKING
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from somelib import SomeClass

class A(BaseModel, arbitrary_types_allowed=True):
    a: "SomeClass | None" = None

A()
```
This will raise:
```python
PydanticUserError: `A` is not fully defined; you should define `SomeClass`, then call `A.model_rebuild()`.
```

You will then have to do:
```python
from somelib import SomeClass
A.model_rebuild()
A()
```

I'm wondering if it's possible to define the depending import statement for the model, so that I can still use string type hint for defining model and only actually import it when the model is imported somewhere.

The main benefit of this is avoiding a very long import time when you have defined a lot of models with custom classes as field types which have to be imported from some other packages.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
> and only actually import it when the model is imported somewhere.

There's no way for us to know when a model (or any object for that matter) is imported somewhere. `model_rebuild` will have to be called at some point. However, you can make use of the `_types_namespace` argument to avoid having to `from somelib import SomeClass` in the other module where you are also importing your model.

Maybe something like this could work for you:

```python
from importlib import import_module
from functools import partial
from typing import Any, ClassVar

from pydantic import BaseModel

def _import(spec: str) -> Any:
    module_path, obj = spec.rsplit(".", 1)
    module = import_module(module_path)
    return getattr(module, obj)

class A(BaseModel):
    build_imports: ClassVar[dict[str, Any]] = {
        "SomeClass": partial(_import, "somelib.SomeClass"),
    }

    @classmethod
    def model_rebuild(
        cls,
        *,
        force: bool = False,
        raise_errors: bool = True,
        _parent_namespace_depth: int = 2,
        _types_namespace: dict[str, Any] | None = None,
    ) -> bool | None:
        _types_namespace = _types_namespace or {}
        _types_namespace.update({k: imp() for k, imp in cls.build_imports.items()})
        return super().model_rebuild(force=force, raise_errors=raise_errors, _parent_namespace_depth=_parent_namespace_depth, _types_namespace=_types_namespace)

```

**Comment by sydney-runkle** [comment]
Hi @atodniAr,

You can use the `defer_build` config setting on your models, which defers the build until the first validation / serialization call. You can read more about that here: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.defer_build.

Going to close this as resolved for now, given that I think this config setting meets your needs.

**Comment by atodniAr** [comment]
> Hi @atodniAr,
> 
> You can use the `defer_build` config setting on your models, which defers the build until the first validation / serialization call. You can read more about that here: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.defer_build.
> 
> Going to close this as resolved for now, given that I think this config setting meets your needs.

Sorry for a late reply as I was too busy to fully test the `defer_build` option you recommended.

To further clarify my need, I want to have the behavior of instantiation time import in pydantic model, e.g. in a normal class:

```python
class A:
    def __init__(self):
        from alib import ADep
        self.a = ADep()

class B:
    def __init__(self):
        from blib import BDep
        self.b = BDep()
```

now you can do:
```python
from schema import A
a_cls = A()
```
without wasting time on importing `blib`.

In the initial description of this issue I tried to replicate similar behavior in pydantic (without defer build), which caused `PydanticUserError` asking me to manually reimport those dependencies and run model rebuild, which is not what I want.

Following your suggestion, I tried add/not add `defer_build`. I found even without `defer_build`, the following code works:
```python
from pydantic import BaseModel, Field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from torch import dtype

class A(BaseModel, arbitrary_types_allowed=True):
    a: 'dtype | None' = Field(None)

# Where A is imported
from torch import dtype
A()
```
I.e. `A.model_rebuild()` doesn't have to be manually excuted, nor does `defer_build` flag has to be added. In the meantime, adding `defer_build` flag doesn't remove the neccessity of `from torch import dtype` line, which is expected as there is no way Python can figure what `dtype` is.

I however found a way (coverage and performance not tested or optimized) to work it around, defining:
```python
from pydantic import BaseModel
from typing import TYPE_CHECKING, get_args, get_origin, Union
from types import UnionType

model_namespace = {}

class AutoRebuildModel(BaseModel, arbitrary_types_allowed=True):
    """Inherit this class and implement necessary __setup_dependencies__ to automatically rebuild the model namespace without worrying about ForwardRef rebuild."""

    def __init__(self, *args, **kwargs):
        if TYPE_CHECKING:
            return super().__init__(*args, **kwargs)
        for field_name, field_info in self.model_fields.items():
            field_type = field_info.annotation
            if get_origin(field_type) is Union or get_origin(field_type) is UnionType:
                for sub_field_type in get_args(field_type):
                    if isinstance(sub_field_type, type) and issubclass(
                        sub_field_type, AutoRebuildModel
                    ):
                        model_namespace.update(sub_field_type.__setup_dependencies__())
            elif isinstance(field_type, type) and issubclass(
                field_type, AutoRebuildModel
            ):
                model_namespace.update(field_type.__setup_dependencies__())

        model_namespace.update(self.__setup_dependencies__())
        # print(model_namespace)
        # for k, v in model_namespace.items():
        #     globals()[k] = v
        self.model_rebuild(_types_namespace=model_namespace)
        super().__init__(*args, **kwargs)

    @staticmethod
    def __setup_dependencies__() -> dict:
        return dict()
```

Now I can do:
```python
if TYPE_CHECKING:
    from torch import dtype

class Z(AutoRebuildModel):
    z: 'dtype | None' = Field(None)
    
    @staticmethod
    def __setup_dependencies__() -> dict:
        from torch import dtype
        return {"dtype": dtype}
    

class A(AutoRebuildModel):
    z: "Z | None" = Field(
        None,
    )

class B(Z):
    some_field: str = Field(
        ...,
        description="Some field",
    )

class C(A):
    some_field: str = Field(
        ...,
        description="Some field",
    )
```
I tested above examples, all work as expected (fast import, resolving dependency in instantiation time). The only extra work needed in model definition is defining __setup_dependencies__ if present
