### ISSUE TITLE
(🐞) no invalid schema error when `pattern` applied to something that's not `str`

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10151]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

as per title

### Example Code

```Python
from pydantic import BaseModel, Field
class A(BaseModel):
    data: int = Field(pattern="1")

A(data=1)
# or
A(data="1")
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for A
data
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
"""

class B(BaseModel):
    data: list[int] = Field(pattern="1")  # TypeError: The following constraints cannot be applied to list[int]: 'pattern'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Just a side note also, on `main` now, this doesn't error:

```py
from pydantic import BaseModel, Field

class B(BaseModel):
    data: list[int] = Field(pattern="1")
```

But instead:

```py
b = B(data=[1, 2, 3])
"""
data
  Input should be a valid string [type=string_type, input_value=[1, 2, 3], input_type=list]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
"""
```

We attempt to be pretty lax about constraints to schema + enforce them at runtime, but this doesn't work well with the schemas that are enforced via `chain_schema`

**Comment by KotlinIsland** [comment]
Thanks, I'm not familiar with the subclass use case, but in my use case I was very confused when I accidentally applied a `pattern` to a `list[str]` field and received a very cryptic error message

**Comment by sydney-runkle** [comment]
Yeah, it's a fair concern. I might close this issue as a `dupe`, as I think the above linked issue covers most of the concerns. I'll chat with @adriangb about some short term next steps here.

To sum up the challenge, basically we're trying to balance the tradeoff between strictness at build time (that might not support some intuitive cases) vs more flexibility at runtime, with (sometimes cryptic) enforcement at runtime.

**Comment by KotlinIsland** [comment]
Perhaps there could be a compromise? allow the class definition but during construction describe the situation that the constraint doesn't match the type

**Comment by sydney-runkle** [comment]
We tried that, and that is the case for some of the more lax validators, but not for the ones applied as chain schemas. For example:

```py
from pydantic import BaseModel, Field

class A(BaseModel):
    data: list[int] = Field(gt=0)

a = A(data=[1, 2, 3])
"""
Traceback (most recent call last):
  File "/Users/programming/pydantic_work/pydantic/pydantic/_internal/_validators.py", line 265, in validator
    if not predicate(x, constraint_value):
  File "/Users/programming/pydantic_work/pydantic/pydantic/_internal/_validators.py", line 277, in <lambda>
    'gt': create_constraint_validator('gt', lambda x, gt: x > gt, 'greater_than'),
TypeError: '>' not supported between instances of 'list' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/programming/pydantic_work/pydantic/test.py", line 6, in <module>
    a = A(data=[1, 2, 3])
  File "/Users/programming/pydantic_work/pydantic/pydantic/main.py", line 195, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "/Users/programming/pydantic_work/pydantic/pydantic/_internal/_validators.py", line 270, in validator
    raise TypeError(f"Unable to apply constraint '{constraint_id}' to supplied value {x}")
TypeError: Unable to apply constraint 'gt' to supplied value [1, 2, 3]
"""
```

**Comment by sydney-runkle** [comment]
I guess we could try to customize the errors for the chain schema validators, but I'm not sure of an easy way to do that...

**Comment by sydney-runkle** [comment]
Ah yes, the functional validators. Good point! I'll dig into a more helpful error message for the chain schema validation steps 👍. Thanks @adriangb!

**Comment by sydney-runkle** [comment]
I've opened #10158 to try to improve this. Note, there was a test marked as `xfail` that's now passing with these changes (granted, with a runtime check, not a build time check).
