### ISSUE TITLE
Cannot implement custom `__iter__` in RootModel

### ISSUE THREAD

**Issue by gerhardadler** [pydantic/pydantic#10156]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I was implementing a subclass of RootModel to let me use it like a MutableMapping.

An example of something like this was showcased in the documentation (https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types), so I expected it to be possible.

However, I faced the issue of my implementation of `__iter__` being incompatible with `__iter__` in BaseModel.

Here is the warning from mypy:
```
Mypy: Return type "Iterator[str]" of "__iter__" incompatible with return type "Generator[tuple[str, Any], None, None]" in supertype "BaseModel" [override]
```

The `__iter__` behaviour of a BaseModel is quite useful for looping over keys and values. However for a RootModel, I think it would be more useful having the option to create custom implementations.

But I understand how this is difficult when RootModel inherits from BaseModel.

I would at least suggest changing the example in the documentation.

### Example Code

```Python
from typing import Iterator, MutableMapping
from pydantic import RootModel

class PydanticMutableMapping[K, V](MutableMapping[K, V], RootModel[MutableMapping[K, V]]):
    def __getitem__(self, key: K) -> V:
        return self.root[key]

    def __delitem__(self, key: K) -> None:
        del self.root[key]

    def __setitem__(self, key: K, value: V) -> None:
        self.root[key] = value

    def __iter__(self) -> Iterator[K]: # Mypy: Return type "Iterator[str]" of "__iter__" incompatible with return type "Generator[tuple[str, Any], None, None]" in supertype "BaseModel" [override]
        return iter(self.root)

    def __len__(self) -> int:
        return len(self.root)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/gerhard/Documents/programming/test/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr 10 2024, 14:51:56) [GCC]
                     platform: Linux-6.10.3-1-default-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2 fastapi-0.112.1 typing_extensions-4.12.2 fastapi-0.112.1
                       commit: unknown
```

**Comment by Viicos** [comment]
This is one of the downsides of having `RootModel` inherit from `BaseModel`. Internally, we use `type: ignore` comments on some methods we override (e.g. `model_construct`). I suggest you do the same in your case. Regarding the example, I plan on moving it somewhere else.
