### ISSUE TITLE
Protobuf Enum not supported

### ISSUE THREAD

**Issue by Ryang20718** [pydantic/pydantic#10162]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

if you have an enum in a proto file and try to limit the enum to the actual value in the pydantic class, you hit an error

    raise AttributeError('Enum {} has no value defined for name {!r}'.format(
AttributeError: Enum TurnSignal has no value defined for name 'V'

```
enum Emotion {
    HAPPY = 0;  
    SAD = 1;  
}
```

ProtoEnum(t=<google.protobuf.internal.enum_type_wrapper.EnumTypeWrapper object at 0x7fa9e4891990>)

### Example Code

```Python
from proto.emotions_pb2 import Emotion
from pydantic.dataclasses import dataclass as dataclass_with_validation
from pydantic import ConfigDict

@dataclass_with_validation(config=ConfigDict(arbitrary_types_allowed=True))
class ProtoEnum:
    t: Emotion.V
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/ryang/.cache/bazel/_bazel_ryang/7071f3e24af240fa9a28f67dc16192b3/external/pip_pydantic/site-packages/pydantic
               python version: 3.10.7 (main, Sep  9 2022, 04:02:34) [GCC 9.4.0]
                     platform: Linux-5.15.0-113-generic-x86_64-with-glibc2.31
             related packages: mypy-1.10.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Protobuf objects differs from the std ones. Pydantic offers no support for protobuf types. This can be done in a separate package (by following [the docs](https://docs.pydantic.dev/latest/concepts/types/#custom-types)), or perhaps in the [`pydantic-extra-types`](https://github.com/pydantic/pydantic-extra-types) repo.
