### ISSUE TITLE
JSON Schema serialization of FloatEnums incorrectly assigns type 'numeric'

### ISSUE THREAD

**Issue by 3XJuli** [pydantic/pydantic#10163]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using float enums within some `BaseModel`, and afterwards serializing as json_schema (e. g. using `ParamClass.model_json_schema()`), the output correctly contains the enum values, but incorrectly assigns the type `'numeric'` instead of `'number'`, which to my understanding is not conform with the [JsonSchema 2020-12 draft on numbers](https://json-schema.org/understanding-json-schema/reference/numeric#number) (in conflict with https://docs.pydantic.dev/latest/concepts/json_schema/).

The issue can be traced back to `enum_schema()`-method in the `GenerateJsonSchema`-class (see [Permalink](https://github.com/pydantic/pydantic/blob/823d51f92f544614bca556076e27dbacd1298491/pydantic/json_schema.py#L789C1-L790C39)) which should assign type `'number'` instead of type `'numeric'`

This causes issue with downstream tasks, where correct Json Schemas are expected. If I have misunderstood / misplaced the cause, I'm sorry! :sweat_smile: 

### Example Code

```Python
from enum import Enum
import pprint
from pydantic import BaseModel


class FloatEnum(float, Enum):
    A = 0.1
    B = 0.2


class Param(BaseModel):
    score_threshold: FloatEnum


pprint.pprint(Param.model_json_schema())

# Outputs:
# {'$defs': {'FloatEnum': {'enum': [0.1, 0.2],
#                          'title': 'FloatEnum',
#                          'type': 'numeric'}},
#  'properties': {'score_threshold': {'$ref': '#/$defs/FloatEnum'}},
#  'required': ['score_threshold'],
#  'title': 'Param',
#  'type': 'object'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/julian/deep-forestry/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
             related packages: mypy-1.10.1 typing_extensions-4.12.2 pydantic-settings-2.4.0 pydantic-extra-types-2.9.0 fastapi-0.112.1
                       commit: unknown
```

**Comment by Viicos** [comment]
Thanks for the clear example. This will be fixed in https://github.com/pydantic/pydantic/pull/10172.
