### ISSUE TITLE
ConfigDict setting ser_json_bytes not working as expected

### ISSUE THREAD

**Issue by BEG-Katzenberger** [pydantic/pydantic#10178]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Due to I receive UTF-8 encoding error during saving my Pydantic object to file which contains a `bytes` field, I stumbled over the `ser_json_bytes` configuration setting.

Fortunately, if I set `ser_json_bytes` from the default value **utf8** to **base64**, the save error goes away, but when I load the object back from file the `bytes` field **is not decoded automatically** as it is encoded during storing.

output of the code below:

```bash
pydantic version: 2.8.2
original:
name='my-item' id=123 data=b'\xff\xaaU\x01'
ffaa5501
{"name":"my-item","id":123,"data":"_6pVAQ=="}
read back:
name='my-item' id=123 data=b'_6pVAQ=='
5f36705641513d3d
```

After read back the object: when the data field is accessed it contains the **base64 string** and not the decoded data itself!
Do I something missing ?

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, version


class Base64Test(BaseModel):
    model_config = ConfigDict(ser_json_bytes='base64')

    name: str = ''
    id: int
    data: bytes


if __name__ == '__main__':

    base64_test = Base64Test(name='my-item', id=123, data=bytes([0xFF, 0xAA, 0x55, 0x01]))

    print(f'pydantic version: {version.VERSION}')

    print('original:')
    print(base64_test)
    print(base64_test.data.hex())

    json_string = base64_test.model_dump_json()
    print(json_string)

    print('read back:')
    read_back = base64_test.model_validate_json(json_string)
    print(read_back)
    print(read_back.data.hex())
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/ ... /lib-c5Oc5WvZ-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
                     platform: Linux-6.5.0-45-generic-x86_64-with-glibc2.38
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Great question! We just added a `val_json_bytes` config flag. You can use it like this:

```py
from pydantic import BaseModel, ConfigDict, version


class Base64Test(BaseModel):
    model_config = ConfigDict(val_json_bytes='base64', ser_json_bytes='base64')

    name: str = ''
    id: int
    data: bytes


base64_test = Base64Test(name='my-item', id=123, data=bytes([0xFF, 0xAA, 0x55, 0x01]))

print(f'pydantic version: {version.VERSION}')

print('original:')
print(base64_test)
print(base64_test.data.hex())

json_string = base64_test.model_dump_json()
print(json_string)

print('read back:')
read_back = base64_test.model_validate_json(json_string)
print(read_back)
print(read_back.data.hex())
```

This will be available in v2.9, released in a week or two. You can access it from `main` with v2.22.0 of `pydantic-core`!

**Comment by BEG-Katzenberger** [comment]
Thanks a lot for the quick answer! With v 2.9 I get the expected behavior - thanks!
```bash
pydantic version: 2.9.0a1
original:
name='my-item' id=123 data=b'\xff\xaaU\x01'
ffaa5501
{"name":"my-item","id":123,"data":"_6pVAQ=="}
read back:
name='my-item' id=123 data=b'\xff\xaaU\x01'
ffaa5501
```
only a question: why do split the json encoding/decoding into two separate configuration settings?
I can't think of any use case that requires a different setting here.

**Comment by sydney-runkle** [comment]
> only a question: why do you split the json encoding/decoding into two separate configuration settings?

Good question - you can see related discussion on this PR: https://github.com/pydantic/pydantic-core/pull/1308.

My general impression is - backwards compatibility :).

**Comment by BEG-Katzenberger** [comment]
ok - thanks for the "clarification" :smile:
