### ISSUE TITLE
Mutating `model_fields` and calling `model_rebuild` does not work as expected

### ISSUE THREAD

**Issue by svantesorberg** [pydantic/pydantic#10198]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Was expecting dynamic updates made to `model_fields` to carry over to a child class.

### Example Code

```Python
from pydantic import BaseModel
from pydantic.fields import FieldInfo

class Parent(BaseModel):
    foo: str

# Dynamically add field to Parent model
Parent.model_fields["bar"] = FieldInfo(annotation=str)
Parent.model_rebuild(force=True)

class Child(Parent):
    pass

Parent(foo="foo") # Validation error, Field 'bar' required
Child(foo="foo") # Works

print(Parent.model_fields) # {'foo': FieldInfo(annotation=str, required=True), 'bar': FieldInfo(annotation=str, required=True)}
print(Child.model_fields) # {'foo': FieldInfo(annotation=str, required=True)}
```
<details>

<summary>Original issue:</summary>

Was expecting dynamic updates made to `model_fields` to carry over to a child class when using `create_model()` in conjunction with the `__base__` argument. Seems this is not the case. Would have expected `model_fields` to be identical for the base and child class.

A working alternative is to iterate over `Parent.model_fields.items()` and pass as `**field_definitions` to `create_model()`

### Example Code

```Python
from pydantic import BaseModel, create_model
from pydantic.fields import FieldInfo

class Parent(BaseModel):
    foo: str

# Dynamically add field to Parent model
Parent.model_fields["bar"] = FieldInfo(annotation=str)
Parent.model_rebuild(force=True)

# Expecting Child to inherit from Parent
Child = create_model("Child", __base__=Parent)

Parent(foo="foo") # Validation error, Field 'bar' required
Child(foo="foo") # Works

print(Parent.model_fields) # {'foo': FieldInfo(annotation=str, required=True), 'bar': FieldInfo(annotation=str, required=True)}
print(Child.model_fields) # {'foo': FieldInfo(annotation=str, required=True)}
```

</details>

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
               python version: 3.10.13 (main, Jan 23 2024, 20:34:07) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: fastapi-0.109.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Ah, interesting. This is because we don't update `Parent.__annotations__` when we do the model rebuild.

**Comment by sydney-runkle** [comment]
Alright, after chatting with the team, we've decided:

We don't explicitly support dynamically updating model fields, then calling `model_rebuild` to update the schema - though this works partially, we (clearly, given the above issue) don't fully support this, and don't plan to.

As a substitute, I'd encourage you to use `create_model` to dynamically create a new model (with some new fields), while also inheriting fields from existing models.

For example:

```py
from pydantic import BaseModel, create_model

class Parent(BaseModel):
    foo: str

Parent2 = create_model("Parent2", bar=(str, ...), __base__=(Parent,))

class Child(Parent2):
    pass

# Parent2(foo="foo") # Validation error, Field 'bar' required
# Child(foo="foo") # Validation error, Field 'bar' required

print(Parent2.model_fields) # {'foo': FieldInfo(annotation=str, required=True), 'bar': FieldInfo(annotation=str, required=True)}
print(Child.model_fields) # {'foo': FieldInfo(annotation=str, required=True), 'bar': FieldInfo(annotation=str, required=True)}
```

Feel free to follow up if you have any additional questions :).
