### ISSUE TITLE
Make sure model core schemas aren't mutated by other definitions

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#10191]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

https://github.com/pydantic/pydantic/issues/9319 demonstrated that it was possible to have a model core schema mutated by other model definitions. This is because we forgot to copy the relevant core schema when trying to simplify it:

https://github.com/pydantic/pydantic/blob/cfeecd7a0d81ee51649fd814fca73b6954fdb262/pydantic/_internal/_core_utils.py#L212-L219

To prevent this, I have a draft implementation of a `pytest` fixture ensuring schemas aren't mutated:

```python
from copy import _deepcopy_dict

from pydantic._internal._model_construction import ModelMetaclass

class LockedSchema(dict[str, Any]):
    def __setitem__(self, key: str, value: Any) -> None:
        pytest.fail(f'Trying to mutate schema key {key!r} with value {value!r}')

    def __deepcopy__(self, memo: dict[int, Any]):
        return _deepcopy_dict(self, memo)

def locked_schema(val: dict[str, Any] | Any) -> LockedSchema:
    if not isinstance(val, dict):
        return val
    return LockedSchema({k: locked_schema(v) for k, v in val.items()})


@pytest.fixture(scope='function', autouse=True)
def disable_core_schema_mutations(monkeypatch: pytest.MonkeyPatch) -> None:

    def locked_getter(self):
        return self.__locked_pydantic_core_schema__

    def locked_setter(self, value):
        if isinstance(value, dict):
            self.__locked_pydantic_core_schema__ = locked_schema(value)
        else:
            # For MockCoreSchema instances:
            self.__locked_pydantic_core_schema__ = value

    def locked_deleter(self):
        del self.__locked_pydantic_core_schema__

    monkeypatch.setattr(
        ModelMetaclass,
        '__pydantic_core_schema__',
        property(fget=locked_getter, fset=locked_setter, fdel=locked_deleter),
        raising=False,
    )
```

The implementation is a bit naive and hard to get right. With the fixture enabled, some tests are failing because the defined class property (a.k.a. property on the metaclass) isn't exactly equivalent to an attribute set on the model classes' `__dict__`.

Other than that, some tests are failing because:
- `CoreMetataHandler` (used during JSON Schema generation) [mutates](https://github.com/pydantic/pydantic/blob/5d99a659c8f4d593b9fafd3cf1a69d5f32b7d8dd/pydantic/_internal/_core_metadata.py#L34-L48) the core schema. Not sure if this is desirable but doesn't truly affect the core schema, at least parts used by `pydantic-core`.
- Pickling makes it so that the core schema is manually built, so our `__setitem__` is called and fails.

But otherwise, no real issue like https://github.com/pydantic/pydantic/issues/9319. Considering the complexity of the fixture, it won't be included in the test suite, but this serves as good documentation tracker for such a check. 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
> CoreMetataHandler (used during JSON Schema generation) [mutates](https://github.com/pydantic/pydantic/blob/5d99a659c8f4d593b9fafd3cf1a69d5f32b7d8dd/pydantic/_internal/_core_metadata.py#L34-L48) the core schema. Not sure if this is desirable but doesn't truly affect the core schema, at least parts used by pydantic-core.

Ah yes, this makes sense. Happy to defer this for now, but thanks for shining light on this as an issue that has been traced as a source of multiple bugs.
