### ISSUE TITLE
Update supported `mypy` versions for the Pydantic plugin

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#10197]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The latest `mypy` version tested in CI was released a year ago ans the oldest was released almost 2 years ago. We should:
- [x] Add a supported versions policy: 6 months of support https://github.com/pydantic/pydantic/pull/10650
- [x] Adapt CI matrix https://github.com/pydantic/pydantic/pull/10623
- [ ] Adapt plugin for specific version checks. https://github.com/pydantic/pydantic/pull/10669
- ~Test on `mypy` master~
- [x] Better document and cleanup the `test_mypy.py` test file https://github.com/pydantic/pydantic/pull/10612

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [x] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by DanielNoord** [comment]
Giving feedback as a random passerby: for downstream users it would be easier to have a time window of supported versions as `mypy` doesn't have a set release cadence. If they suddenly decide to release 5 versions in a month (I know exaggeration) you force downstream users to update much quicker than they are used to. A year of support seems like a good middle ground?

**Comment by Viicos** [comment]
Seems like a safer approach, thanks for the suggestion!
