### ISSUE TITLE
AliasGenerator not found 

### ISSUE THREAD

**Issue by YuqingCC** [pydantic/pydantic#10201]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to import AliasGenerator from pydantic, add it shows me [module 'pydantic' has no attribute 'AliasGenerator']

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[12], [line 1](vscode-notebook-cell:?execution_count=12&line=1)
----> [1](vscode-notebook-cell:?execution_count=12&line=1) from pydantic import AliasGenerator

ImportError: cannot import name 'AliasGenerator' from 'pydantic' (/opt/anaconda3/envs/GenAI/lib/python3.12/site-packages/pydantic/__init__.py)

### Example Code

```Python
from pydantic import AliasGenerator
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
pydantic-core version: 2.20.1
pydantic-core build: profile=release pgo=true
install path: /opt/anaconda3/envs/GenAI/lib/python3.12/site-packages/pydantic
python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
platform: macOS-14.6.1-arm64-arm-64bit
related packages: typing_extensions-4.11.0
```

**Comment by sydney-runkle** [comment]
Hmm, we're not able to repro this issue - `AliasGenerator` is present in `__init__.py` as expected.

Going to mark as resolved for now - perhaps reinstall `pydantic`?

**Comment by YuqingCC** [comment]
Yay, problem solved after reinstall
