### ISSUE TITLE
TypedDict for Field

### ISSUE THREAD

**Issue by ProJoelVik** [pydantic/pydantic#10222]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Greetings Pydantic devs,

Both the function `Field` and the various ways to instantiate `FieldInfo` have quite a few parameters. Depending on how you instantiate `FieldInfo`, these parameters are either described in `TypedDict`s or in docstrings. For example, the typed dicts `_FieldInfoInputs`, `_FromFieldInfoInputs` and `_EmptyKwargs` are used to describe the parameters

```python
class _FromFieldInfoInputs(typing_extensions.TypedDict, total=False):  
    """This class exists solely to add type checking for the `**kwargs` in `FieldInfo.from_field`."""  
...

  
class _FieldInfoInputs(_FromFieldInfoInputs, total=False):  
    """This class exists solely to add type checking for the `**kwargs` in `FieldInfo.__init__`."""  
...


class _EmptyKwargs(typing_extensions.TypedDict):  
    """This class exists solely to ensure that type checking warns about passing `**extra` in `Field`."""
...
```

which are then used in `FieldInfo` and `Field`:
```python
class FieldInfo(_repr.Representation):
...

def __init__(self, **kwargs: Unpack[_FieldInfoInputs]) -> None:
...

def from_field(default: Any = PydanticUndefined, **kwargs: Unpack[_FromFieldInfoInputs]) -> FieldInfo:
...


def Field(
...
    **extra: Unpack[_EmptyKwargs],
) -> Any:
...
```
#### Use case / Demo:

When creating custom fields by wrapping `Field`, a `TypedDict` would make it easy to type hint wrapped functions. Since the parameters for `Field` and `FieldInfo` differ slightly, the currently existing `TypedDict`s can't be used.

Given a `TypedDict` exists for the input parameters of `Field`, an extended `Field` could then be created like this without losing the type hinting for the arguments passed on to `Field`. In this example, a custom error function is added with a custom error message:
```python
class FieldInputs(TypedDict, total=False):
    """
    A TypedDict for the input parameters of the Field function.
    """
...

class ExtendedFieldInputs(FieldInputs, total=False):
    validation_error_message: str

def CustomField(
    **kwargs: Unpack[ExtendedFieldInputs],
) -> FieldInfo:
    """
    A custom Pydantic.Field that takes
    an additional parameter.
    :return: A :class:`FieldInfo` object.
    """
    validation_error_message = kwargs.pop("validation_error_message")
    field_kwargs: FieldInputs = kwargs
    field_info: FieldInfo = Field(**field_kwargs)  # type: ignore[pydantic-field]
    field_info.metadata.append(validate_with_message(validation_error_message))
    return field_info
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@Viicos, wdyt?

**Comment by Viicos** [comment]
This unfortunately won't be possible as this would introduce a breaking change in the `Field` signature. The [`default`](https://github.com/pydantic/pydantic/blob/0672da169cb11816080ad724ff012966d67e9f4b/pydantic/fields.py#L686) argument is marked as a positional or keyword argument. Using `**kwargs` would enforce the argument to be keyword only.

Ideally it should be made a keyword argument, primarily because the `dataclass_transform()` semantics https://typing.readthedocs.io/en/latest/spec/dataclasses.html#field-specifier-parameters arguments to be kw only, but the Pydantic's `Field` function predates the PEP that introduced this pattern.

I'll note that defining a custom field function won't play well with type checkers, as they won't be recognized as being a field specifier. Supporting classes could solve the issue, as type checkers could assume subclasses are valid specifiers as well. Some discussion can be found [here](https://discuss.python.org/t/using-classes-as-dataclass-transform-field-specifiers/46459).

**Comment by ProJoelVik** [comment]
Thanks for the reply,

Maybe we have to pass on type checking in this case then and just reference `Field` in the docstring of our custom field. An alternative could perhaps be to use instantiate `FieldInfo` directly without first using `Field`, but I'm guessing `Field` is there for good reasons. 

---

`_FieldInfoInputs ` has `annotation: type[Any] | None`, which `Field` doesn't seem to have/use. `FieldInfo.from_field` raises if annotation is provided, so it feels a bit misleading to use `_FieldInfoInputs ` when not all parameters are the same:
```python
if 'annotation' in kwargs:
            raise TypeError('"annotation" is not permitted as a Field keyword argument')
```

`**extra: Unpack[_EmptyKwargs]` doesn't really matter for us since it's deprecated and nothing we use.
