### ISSUE TITLE
Strict broken for floats

### ISSUE THREAD

**Issue by Mardoxx** [pydantic/pydantic#10220]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A strict mode model will accept integers into float fields.

The opposite /does/ work however (fails when inserting a float into an int field)

### Example Code

```Python
from pydantic import BaseModel, ConfigDict


class Test(BaseModel):
  model_config = ConfigDict(strict=True)
  a: float

x: int = int(1)
assert type(x) is not float
assert type(x) is int
assert not issubclass(float, int)
assert not issubclass(float, int)

Test(a = x) # should fail
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/owner/code/codewars/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Feb 11 2024, 14:54:11) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-13.5-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Mardoxx,

Thanks for your question. Though this seems counterintuitive at first, we've sourced this logic / behavior from [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower). Specifically:

> when an argument is annotated as having type float, an argument of type int is acceptable

**Comment by Mardoxx** [comment]
Also worth adding for anyone else reading: JSON does not have distinct types for ints and floats. So this follows also.
