### ISSUE TITLE
Missing Section in Pydantic Documentation

### ISSUE THREAD

**Issue by insumanth** [pydantic/pydantic#10230]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Some section of the documentation that is present in github docs files is missing in pydantic docs website.

Here, the below section that explains the behavior from the above code example as a list is missing from docs' website. I believe this is an issue in docs generation from markdown.

https://docs.pydantic.dev/latest/#pydantic-examples

```

1. `id` is of type `int`; the annotation-only declaration tells Pydantic that this field is required. Strings,
   bytes, or floats will be coerced to integers if possible; otherwise an exception will be raised.
2. `name` is a string; because it has a default, it is not required.
3. `signup_ts` is a [`datetime`][datetime.datetime] field that is required, but the value `None` may be provided;
   Pydantic will process either a [Unix timestamp](https://en.wikipedia.org/wiki/Unix_time) integer (e.g. `1496498400`)
   or a string representing the date and time.
4. `tastes` is a dictionary with string keys and positive integer values. The `PositiveInt` type is
   shorthand for `Annotated[int, annotated_types.Gt(0)]`.
5. The input here is an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) formatted datetime, but Pydantic will
   convert it to a [`datetime`][datetime.datetime] object.
6. The key here is `bytes`, but Pydantic will take care of coercing it to a string.
7. Similarly, Pydantic will coerce the string `'1'` to the integer `1`.
8. We create instance of `User` by passing our external data to `User` as keyword arguments.
9. We can access fields as attributes of the model.
10. We can convert the model to a dictionary with [`model_dump()`][pydantic.BaseModel.model_dump].


```

| Github Docs index.md | Pydantic Website |
|----------------------|-------------------|
| ![image](https://github.com/user-attachments/assets/61a30838-b7f2-49c4-9560-6d734886dad1) | ![image](https://github.com/user-attachments/assets/87886926-235d-4281-9b6f-d45b1e6405cc) |

-------------------------------

Similarly another section is also missing in the next code example

```
1. The input data is wrong here &mdash; `id` is not a valid integer, and `signup_ts` is missing.
2. Trying to instantiate `User` will raise a [`ValidationError`][pydantic_core.ValidationError] with a list of errors.
``` 

| Github Docs index.md | Pydantic Website |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/99f3aedd-18dc-4ae6-a72b-44abaac763d7) | ![image](https://github.com/user-attachments/assets/2d1c9a09-a604-4664-9990-88a061df3407)  |

-------------------------------

Found this issue when creating PR #10229 to enhance documentation.
Please add the label as `documentation` to this issue. I could not add it.

### Example Code

```Python
Not required. Issue with documentation
```

### Python, Pydantic & OS Version

```Text
Not required. Issue with documentation
```

**Comment by Viicos** [comment]
We are making use of [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) to attach extra content to the code examples. You can then click on the <kbd>+</kbd> sign to see the added content.
