### ISSUE TITLE
Mypy: `EmailStr` is typed as `str` during type checking

### ISSUE THREAD

**Issue by flaeppe** [pydantic/pydantic#10237]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

During type checking (with `mypy`) `EmailStr` is typed as `str` instead of a more specific type e.g. `EmailStr`.

While this isn't really a runtime problem a lot of type information is lost by having `EmailStr` simply become `str`. Type checking wouldn't signal mismatches of a validated vs. non validated value.

### Example Code

```Python
from pydantic import EmailStr, BaseModel


def func(arg: EmailStr) -> None:
    return None


class A(BaseModel):
    email: EmailStr
    notanemail: str


a = A(email="someone@example.com", notanemail="notanemail")
func(a.email)
# It would be great if the below 2 emitted an error during type checking
func(a.notanemail)
func("abc123")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: [...]/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 16.0.6 ]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: mypy-1.11.2 pydantic-extra-types-2.9.0 typing_extensions-4.12.2 pydantic-settings-2.4.0
                       commit: unknown
```

**Comment by flaeppe** [comment]
Looks like the `Annotated` version during type checking tracks back to #4516 

https://github.com/pydantic/pydantic/blob/714c0df09f48cd24579dd2b1c744d9b5da4f2911/pydantic/networks.py#L426-L431

**Comment by flaeppe** [comment]
I'm really curious what happens if it's swapped to a `NewType`. Could that work as a solution here?

```diff
 if TYPE_CHECKING: 
-     EmailStr = Annotated[str, ...] 
+     EmailStr = NewType("EmailStr", str)
 else: 
  
     class EmailStr: 
         """ 
```

**Comment by flaeppe** [comment]
A quick check reveals there might be a couple of other types in a similar situation

```
➤ git grep "= Annotated\[.*, \.\.\.\]" -- pydantic/
pydantic/functional_serializers.py:    SerializeAsAny = Annotated[AnyType, ...]  # SerializeAsAny[list[str]] will be treated by type checkers as list[str]
pydantic/functional_validators.py:    InstanceOf = Annotated[AnyType, ...]  # `IsInstance[Sequence]` will be recognized by type checkers as `Sequence`
pydantic/functional_validators.py:    SkipValidation = Annotated[AnyType, ...]  # SkipValidation[list[str]] will be treated by type checkers as list[str]
pydantic/json_schema.py:    SkipJsonSchema = Annotated[AnyType, ...]
pydantic/types.py:    ImportString = Annotated[AnyType, ...]
pydantic/types.py:    Json = Annotated[AnyType, ...]
pydantic/types.py:    PastDate = Annotated[date, ...]
pydantic/types.py:    FutureDate = Annotated[date, ...]
pydantic/types.py:    AwareDatetime = Annotated[datetime, ...]
pydantic/types.py:    NaiveDatetime = Annotated[datetime, ...]
pydantic/types.py:    PastDatetime = Annotated[datetime, ...]
pydantic/types.py:    FutureDatetime = Annotated[datetime, ...]
pydantic/v1/types.py:    Json = Annotated[T, ...]  # Json[list[str]] will be recognized by type checkers as list[str]
```

**Comment by mpkocher** [comment]
It's probably a good idea to try to have parity with the typing checking if-block. (It's not clear that this is making things better or perhaps creating more of a disconnect?).

With your proposed changes, does Pydantic raise an error when configured in strict mode? 

```python
from pydantic import EmailStr, BaseModel, ConfigDict

class A(BaseModel):
    model_config = ConfigDict(strict=True)
    name: EmailStr

ax = A(name="a@a.com")
```

**Comment by flaeppe** [comment]
With or without my proposed changes Pydantic raises no error for your snippet during runtime.

While `mypy` yields the following error with my proposed changes:

```
7: error: Argument "name" to "A" has incompatible type "str"; expected "EmailStr"  [arg-type]
```

I think we need to keep in mind that `init_typed` mypy configuration setting is probably involved here too: https://docs.pydantic.dev/latest/integrations/mypy/#generate-a-signature-for-model__init__

And also that anything inside of an `if TYPE_CHECKING:` can't execute during runtime (ref https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING)

**Comment by mpkocher** [comment]
A bit of context from the docs that might be useful.

https://docs.pydantic.dev/2.1/usage/types/custom/#composing-types-via-annotated

".... to create types that are **identical** to the original type as far as type checkers are concerned, but add validation, serialize differently, etc."

I somewhat understand the basic thought process, however, it seems like you should still be able to define a new type in some (or many?) cases. In specific contexts, the annotation could have semantic meaning that results in the type having a different fundamental meaning. This isn't really an edge case or esoteric use case, for example `PositiveInt` is an obvious example.

**Comment by Viicos** [comment]
I guess there's a tradeoff between the two solutions:

- With `EmailStr = Annotated[str, ...]`, type checkers allow a `str` instance to be used during instantiation:
```py
EmailStr = Annotated[str, ...]

class Model(BaseModel):
    email: EmailStr

Model(email="...")  # OK
```

But as you mentioned there's no way to enforce the `EmailStr` type elsewhere.
With the `Annotated` form, type checkers will also complain when trying to instantiate `EmailStr`, as `Annotated` forms can't be instantiated (which is good, we don't want users doing so).

- With `EmailStr = NewType('EmailStr', str)`, type checkers will **not** allow a `str` instance to be used during instantiation:
```py
EmailStr = NewType('EmailStr', str)

class Model(BaseModel):
    email: EmailStr

Model(email="...")  # Type checker error
```
Imo this is pretty bad especially considering that users may try to fix this by first creating an instance of `EmailStr`, which is perfectly valid from a type checker's perspective (unlike with `Annotated`), even though it will fail at runtime.

---

While `NewType` is usually the way to go to support your use case, it is a bit different in this context. At runtime, `EmailStr` isn't a `NewType`, and it isn't really meant to be used outside model annotations. We'll discuss this today.

**Comment by kjagiello** [comment]
> With `EmailStr = NewType('EmailStr', str)` type checkers will not allow a str instance to be used during instantiation:

Interestingly enough it seems like there are already some types, i.e. `IPvAny*`, that validate themselves upon Instantiation. 

(A sidenote, but the example in the docstring on `IPvAnyAddress` fails type checking)

**Comment by flaeppe** [comment]
I see that it'd be dangerous to allow instantiation `EmailStr` via a checker (which for example would happen via `EmailStr = NewType("EmailStr", str)`) since it's illegal in runtime.

It's a little bit confusing when there are _some_ types that validate on instantiation and some doesn't. But at least I suppose that one can assume that all types that allow instantiation would be validated.

I also want to note/mention that `mypy` doesn't seem to have implemented full support for `Annotated` since `mypy` allows for:

```python
EmailStr = Annotated[str, ...]
EmailStr("anything")
```

Without any errors.

---

It's unfortunate that the `Annotated` interface is quite deceiving as these kind of builtin/predeclared "types", I suppose they are validators(or similar) and not types, for example `EmailStr` very much looks like and attaches like a type. But it's some kind of "a type validated by pydantic" and it's only that under the pydantic domain, so one should _never_ use these as a type when pydantic isn't involved. e.g. `func` in my reported case:

```python
from pydantic import EmailStr
# I shouldn't do this, pydantic isn't involved here
def func(arg: EmailStr) -> None: ...
```

I suppose this is simply a revelation for me as I assumed these builtins shipped with pydantic were specific types, or at least intended to be.

**Comment by mpkocher** [comment]
> It's a little bit confusing when there are _some_ types that validate on instantiation and some doesn't. But at least I suppose that one can assume that all types that allow instantiation would be validated.

It's very surprising to me that this is even allowed. 

```bash
In [1]: from pydantic import PositiveInt
In [2]: i = PositiveInt(-1)
In [3]: i
Out[3]: -1

In [4]: from pydantic import NameEmail
In [5]: n = NameEmail("a", "b")
In [6]: n
Out[6]: NameEmail(name='a', email='b')
```

The entire point of using types like `PositiveInt` is to fundamentally prevent an invalid instance from being created and to avoid an entire class of errors (e.g. `ZeroDivisionError`).

**Comment by flaeppe** [comment]
I found some kind of alternative approach that seem to work, not sure what to make of it, but it involves multiple types:


```python
from typing import Annotated, NewType

_EmailStr = NewType("_EmailStr", str)

EmailStr = Annotated[_EmailStr, ...]
EmailStr("a@example.com")  # Not allowed (by pyright)
a: EmailStr  # this is fine, but reveal_type(a) will display '_EmailStr' as a type
```

**Comment by flaeppe** [comment]
> It's very surprising to me that this is even allowed.
> 
> ```shell
> In [1]: from pydantic import PositiveInt
> In [2]: i = PositiveInt(-1)
> In [3]: i
> Out[3]: -1
> 
> In [4]: from pydantic import NameEmail
> In [5]: n = NameEmail("a", "b")
> In [6]: n
> Out[6]: NameEmail(name='a', email='b')
> ```
> 
> The entire point of using types like `PositiveInt` is to fundamentally prevent an invalid instance from being created and to avoid an entire class of errors (e.g. `ZeroDivisionError`).

@mpkocher Since we're outside of the "pydantic scope" in this example, the only one that can "stop" you is a type checker that forbids instantiation of `Annotated` (e.g. mypy doesn't do this yet, but pyright does), the runtime isn't involved here because `PositiveInt` isn't a regular runtime type it's just an `int` until you use it within the pydantic domain.

When put out of context, I agree your example doesn't make much sense. But a pydantic user have to keep in mind that it's not possible to use any of these kind of imports without additional pydantic tooling (read: `BaseModel`, `TypeAdapter`, etc.)

**Comment by Viicos** [comment]
> This applies to the aforementioned types as well. Take a look at the example in the docstring of `IPvAnyAddress`. It does not pass type checking.

This is a broader issue and a limitation of `dataclass_transform`, as type checker can't understand the coercion rules of Pydantic (same happens if you pass a string `"1"` for an `int` type). But what matters the most is that the type hint represents the final value correctly. In the case of IP addresses, even if you pass a string, it ends up being a proper instance of `IPvxAddress`.

Same goes for `EmailStr`, it ends up being a string. 

> I also want to note/mention that `mypy` doesn't seem to have implemented full support for `Annotated` since `mypy` allows for:

I think the [spec about `Annotated`](https://typing.readthedocs.io/en/latest/spec/qualifiers.html#annotated) recently got updated, and `mypy` did not have time to comply to it yet. 

---

Overall I agree the behavior with `Annotated` can be confusing. Even more when we define things only in `if TYPE_CHECKING` blocks, as we lie about the real runtime object. 

I agree `NewType` is a nice way to support constraints on values in the type system and it could work in theory. But because of how `EmailStr` is defined at runtime/for type checkers, we can't really go this way for now.
