### ISSUE TITLE
v2.9.0b1 is breaking napari

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#10239]
See [napari's CI](https://github.com/napari/napari/actions/runs/10567191832/job/29275631436?pr=7217), output:

```
    File "/tmp/.tox/py312-linux-pyqt5-no_cov/lib/python3.12/site-packages/pydantic_compat/_v2/mixin.py", line 58, in <module>
      class PydanticCompatMixin(metaclass=_MixinMeta):
    File "/tmp/.tox/py312-linux-pyqt5-no_cov/lib/python3.12/site-packages/pydantic_compat/_v2/mixin.py", line 55, in __new__
      return super().__new__(cls, name, bases, namespace, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/.tox/py312-linux-pyqt5-no_cov/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 246, in __new__
      del namespace[instance_slot]
          ~~~~~~~~~^^^^^^^^^^^^^^^
  KeyError: '__pydantic_fields_set__'
```

It looks like this was caused by #10110, here:

https://github.com/pydantic/pydantic/blob/714c0df09f48cd24579dd2b1c744d9b5da4f2911/pydantic/_internal/_model_construction.py#L245-L246

**Comment by Viicos** [comment]
`pydantic-compat` is doing pretty unusual things (subclassing our metaclass). I pushed a fix and checked that `pydantic-compat` tests are passing with the fix.

**Comment by Czaki** [comment]
> `pydantic-compat` is doing pretty unusual things (subclassing our metaclass). I pushed a fix and checked that `pydantic-compat` tests are passing with the fix.

`napari` also subclassing the metaclass. There is no other option to do metaclass programming without this.

**Comment by tlambert03** [comment]
Yes, sorry for the deep pydantic-compat magic.  It was not on a whim, but after a lot of thought, it was the only way we could achieve the ecosystem compatibility we desired when pydantic v2 was released.  I don't imagine it will be needed forever, but I do appreciate you pushing a fix @Viicos

**Comment by Viicos** [comment]
Yes indeed no one is to blame here, compat libraries such as `pydantic-compat` have to use private stuff in some way :)
