### ISSUE TITLE
2.9.0b1 breaks discriminator on list tupe, still works with 2.8.2

### ISSUE THREAD

**Issue by eavanvalkenburg** [pydantic/pydantic#10243]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a model with a field `items: list[ITEM_TYPES] = Field(default_factory=list, discriminator=DISCRIMINATOR_FIELD)` with ITEM_TYPES a union of different types, each with a field name `content_type` which is what DISCRIMANTOR_FIELD has as well.

When importing this class using pydantic 2.9.0b1 it throws a error: `TypeError: 'list' is not a valid discriminated union variant; should be a `BaseModel` or `dataclass`` This does not happen with 2.8.2

### Python, Pydantic & OS Version

```Text
pydantic 2.9.0b1
WSL ubuntu
```

**Comment by sydney-runkle** [comment]
Hi @eavanvalkenburg, could you please provide a reproducible example? Thanks for the bug report!

**Comment by sydney-runkle** [comment]
If it looks something like this:

```py
from pydantic import BaseModel, Field
from typing import Literal

class A(BaseModel):
    content_type: Literal['a'] = 'a'

class B(BaseModel):
    content_type: Literal['b'] = 'b'

class C(BaseModel):
    content_type: Literal['c'] = 'c'


ITEM_TYPES = A | B | C
DISCRIMINATOR_FIELD = 'content_type'

class Model(BaseModel):
    data: list[ITEM_TYPES] = Field(..., discriminator=DISCRIMINATOR_FIELD)
```

That's wrong - you want to apply the discriminator info directly to the union, like so:

```py
from pydantic import BaseModel, Field
from typing import Literal
from typing_extensions import Annotated

class A(BaseModel):
    content_type: Literal['a'] = 'a'

class B(BaseModel):
    content_type: Literal['b'] = 'b'

class C(BaseModel):
    content_type: Literal['c'] = 'c'


ITEM_TYPES = A | B | C
DISCRIMINATOR_FIELD = 'content_type'

class Model(BaseModel):
    data: list[Annotated[ITEM_TYPES, Field(..., discriminator=DISCRIMINATOR_FIELD)]]

m = Model(data=[A(content_type='a'), B(content_type='b'), C(content_type='c')])
print(repr(m))
#> Model(data=[A(content_type='a'), B(content_type='b'), C(content_type='c')])
```

**Comment by sydney-runkle** [comment]
Marking as resolved for now, but feel free to ping me if you're looking for more info here or think something is still wrong. Thanks!

**Comment by eavanvalkenburg** [comment]
@sydney-runkle thanks for this suggestion, but good to call out that this is a breaking change with that beta version, since the first syntax you showed is indeed what I use and that suddenly raises a very cryptic error message when used with that beta!

**Comment by sydney-runkle** [comment]
@eavanvalkenburg,

Did the first snippet work for you in v2.8.2?

**Comment by eavanvalkenburg** [comment]
> @eavanvalkenburg,
> 
> 
> 
> Did the first snippet work for you in v2.8.2?

Yep, which is why I was so surprised it broke!

**Comment by eavanvalkenburg** [comment]
For future reference, I had a default_factory assigned as well and the syntax for that is a bit weird, but it makes sense when you think about it, so good to have here:
`items: list[Annotated[ITEM_TYPES, Field(..., discriminator=DISCRIMINATOR_FIELD)]] = Field(default_factory=list)`

**Comment by eavanvalkenburg** [comment]
@sydney-runkle I just made this change and added a bunch of additional tests to my project, I am now doubting if this ever worked as intended, or it just happened to work for 99% of cases, but the difference is that this error had not been raised before, while it is now.
