### ISSUE TITLE
Add a "millisecond" option to ser_json_timedelta config parameter

### ISSUE THREAD

**Issue by benjsec** [pydantic/pydantic#10256]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently the ConfigDict `ser_json_timedelta` parameter can return data in ISO format or as a second timestamp; it would be very useful if there could be an option that would allow returning a millisecond timestamp instead.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
PRs welcome!

**Comment by ollz272** [comment]
PR is open for the pydantic core side of things, once thats done i'll open a PR to make that available in pydantic

**Comment by sydney-runkle** [comment]
@ollz272,

Amazing, thanks so much! Releasing v2.9 tomorrow (so can't add in new features at this point), but will give this a thorough review once that's done. Excited to include this in v2.10!!
