### ISSUE TITLE
validate_call doesn't convert ValueError to ValidationError

### ISSUE THREAD

**Issue by dvarrazzo** [pydantic/pydantic#10275]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to use `@validate_call` to provide an alternative constructor to a model, which should have custom validation.

My expectation is that a function wrapped with `@validate_call` would behave like other validators. However exceptions raised from the function are not converted to validation error.

The output of the program below is:

```
data='foo'
1 validation error for MyModel
data
  Value error, no tests please [type=value_error, input_value='test', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
Traceback (most recent call last):
  ...
    raise ValueError("not even foos!")
ValueError: not even foos!
```

my expectation is to get a validation error there too.

Is there another way to provide the equivalent of a `@model_validator` but invoked on a classmethod or a generic function rather than the constructor?

### Example Code

```Python
from pydantic import BaseModel, field_validator, ValidationError, validate_call
from typing_extensions import Self

class MyModel(BaseModel):
    data: str

    @field_validator("data")
    @classmethod
    def check_not_test(cls, v: str) -> str:
        if v == "test":
            raise ValueError("no tests please")
        return v

    @classmethod
    @validate_call
    def build_from_stuff(cls, data: str) -> Self:
        if data == "foo":
            raise ValueError("not even foos!")
        return cls(data=data)

print(MyModel(data="foo"))
try:
    print(MyModel(data="test"))
except ValidationError as e:
    print(e)

try:
    print(MyModel.build_from_stuff(data="foo"))
except ValidationError as e:
    print(e)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/piro/.../.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
                     platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
             related packages: mypy-1.5.1 pydantic-settings-2.2.1 typing_extensions-4.7.1 fastapi-0.103.0
                       commit: unknown
```

**Comment by Viicos** [comment]
`validate_call` only performs validation on the provided arguments (so that they match the type annotations), and optionally the return type when setting `validate_return` to `True`.

I'm not entirely sure I understand your use case, but you can provide extra validation logic with `Annotated`:

```python

def validate_data(value):
    if data == "foo":
        raise ValueError("not even foos!")
    return data

    @classmethod
    @validate_call
    def build_from_stuff(cls, data: Annotated[str, BeforeValidator(validate_data)]) -> Self:
        return cls(data=data)
```

**Comment by dvarrazzo** [comment]
@Viicos thank you for your input. `Annotated` can only validate a single value. My use case requires a more complex validation.

The case is:

- a `Resource` is a thing that can be sold along different pricing models;
- a `PricingModel` is a set of rules to give resources a price. A `PricingModel` may take parameters, for instance a flat price may include parameters "currency" and "price"
- a `ResourcePrice` combines a resource and a pricing model, and gives values to the model's parameters.

For instance, objects may be:

- `Resource(id=123)`
- `PriceModel(id=456, name="flat_price", params=["currency", "price"])`
- `ResourcePrice(resource_id=123, model_id=456, param_values={"currency": "USD", "price": 9.99})`

What I would like to add is a method to create a resource price from a resource and a price model, passing param values, and verifying, among the other things, that the param values provided are consistent with the requested params. The attempt is so:

```python
class ResourcePrice(BaseModel):
    resource_id: int
    model_id: int
    param_values: dict[str, Any]

    @classmethod
    def from_models(
        cls, resource: Resource, model: PriceModel, param_values: dict[str, Any]
    ) -> Self:
        if set(param_values) != set(model.params):
            raise ValueError("inconsistent params")
        return cls(resource_id=resource.id, model_id=model.id, param_values=param_values)
```

What I have ended up doing so far is to add a support model:

```python
class ResourcePriceFromModels(BaseModel):
    """Factory object to validate the objects building the price.
    """
    model: PriceModel
    resource: Resource
    price: ResourcePrice | None = None
    param_values: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def check_parameters(self) -> Self:
        if set(self.param_values) != set(self.model.params):
            raise ValueError("inconsistent params")
        self.price = ResourcePrice(
            model_id=self.model.id,
            resource_id=self.resource.id,
            param_values=self.param_values,
        )
        return self
```

but I wonder if the same can be done with a class method or a generic factory function rather than with a class.

**Comment by Viicos** [comment]
I see. Because an instance of `PriceModel` (or at least the `params` attribute) must be provided anyway, maybe you can leverage the `context` argument:

```python
from pydantic import ValidationInfo, model_validator

class ResourcePrice(BaseModel):
    resource_id: int
    model_id: int
    param_values: dict[str, Any]

    @model_validator(mode="after")
    def validate_model(self, info: ValidationInfo):
        model_params = info.context.get("model_params")
        if model_params and set(self.param_values) != set(model_params):
            raise ValueError("inconsistent params")
        return self

ResourcePrice.model_validate(
    {"resource_id": 123, "model_id": 456, "param_values": {"currency": "USD", "price": 9.99}},
    context={"model_params": ["currency", "price"]},
)
```

**Comment by dvarrazzo** [comment]
Thank you, this is an useful tip. The following works more or less as expected:

```python
class ResourcePrice(BaseModel, Generic[Res]):
    id: UUID = Field(default_factory=uuid4)
    model_id: UUID
    resource_id: UUID
    status: ResourcePriceStatus = ResourcePriceStatus.draft
    param_values: dict[str, Any] = Field(default_factory=dict)

    @classmethod
    def from_model_and_resource(
        cls,
        resource: Resource,
        model: PriceModel,
        *,
        status: ResourcePriceStatus = ResourcePriceStatus.draft,
        param_values: dict[str, Any] | None = None,
    ) -> Self:
        args = {
            "model_id": model.id,
            "resource_id": resource.id,
            "param_values": param_values or {},
            "status": status,
        }
        obj = cls.model_validate(args, context={"model": model})
        return obj

    @field_validator("param_values")
    @classmethod
    def check_parameters(
        cls, param_values: dict[str, Any], info: ValidationInfo
    ) -> dict[str, Any]:
        if info.context and "model" in info.context:
            model = info.context["model"]
            if diff := set(model.params) - set(param_values):
                raise ValueError(
                    f"required parameters not provided: {', '.join(sorted(diff))}"
                )
            if diff := set(param_values) - set(model.params):
                raise ValueError(f"unexpected parameters: {', '.join(sorted(diff))}")
        return param_values
```

And it behaves like:

```python
pm = PriceModel(id=uuid4(), key="x", label="hey", params=["foo"])
res = Resource(...)
try:
    rp = ResourcePrice.from_model_and_resource(
        model=pm, resource=res, param_values={"foo": 10, "bar": 20}
    )
except ValidationError as ex:
    print(ex)
```

```
1 validation error for ResourcePrice
param_values
  Value error, unexpected parameters: bar [type=value_error, input_value={'foo': 10, 'bar': 20}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
```

So there is a workaround, and doesn't really require validate_call.

It still feels to me that `validate_call` doesn't exactly provide a behaviour matching the one of validation methods. However this setup is even better because at most the validate call check could return the equivalent of a method-level error, whereas using the context, field-level errors can be returned.

I have personally learned a lot from this. If there is no use case that you consider worth implementing, this ticket can be closed here.

**Comment by Viicos** [comment]
> It still feels to me that `validate_call` doesn't exactly provide a behaviour matching the one of validation methods.

`validate_call` reproduces the same semantics as Pydantic models, that is when you define a function:

```python
@validate_call
def func(a: int):
    # a is guaranteed to be an `int`, at runtime.
```

You can be assured arguments match the provided type hints at runtime. Same goes for a Pydantic model, when instantiated, guarantees the correctness of attributes with respect to the type hints. So I think having an API matching validation models wouldn't be related to `validate_call`.

Thanks for the clear repro steps and happy to know the solution fits your needs!
