### ISSUE TITLE
Type Checker error when allowing extra fields

### ISSUE THREAD

**Issue by vikigenius** [pydantic/pydantic#10278]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Allowing extra fields causes issues with pyright type checker showing error on those extra fields.

### Example Code

```Python
class AgentResponse(BaseModel):
    response_message: str
    model_config = ConfigDict(extra='allow')

def test_response_construction():
    agent_response = AgentResponse(response_message='Hi', response_category='text') # Type checker complains about no parameter named response_category [reportCallIssue]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/void/Projects/Research/******/*******/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.14 (main, Jul 13 2024, 23:51:03) [Clang 17.0.6 ]
                     platform: Linux-6.6.47_1-x86_64-with-glibc2.39
             related packages: fastapi-0.112.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
This is a limitation of the [`dataclass_transform`](https://typing.readthedocs.io/en/latest/spec/dataclasses.html#the-dataclass-transform-decorator) typing construct, which Pydantic uses to make type checkers understand `BaseModel` acts as dataclasses. `pyright` does not special case the Pydantic library and does not provide any plugin functionality so nothing can really be done for now.
