### ISSUE TITLE
__pydantic_complete__ is not updated when rebuilding dataclass

### ISSUE THREAD

**Issue by AdrienVannson** [pydantic/pydantic#10284]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A pydantic dataclass has a `__pydantic_complete__ ` field, which is a boolean indicating if the dataclass has been successfully built. The value of the field is set when the dataclass is first built.

However, its value is not updated after a call to `rebuild_dataclass`: even if the call is successful, `__pydantic_complete__ ` remains set to `False`, as shown in the example. A consequence is that if `rebuild_dataclass` is called several times, each call will lead to a rebuilding of the dataclass, even when it is not necessary.

This works correctly when using `BaseModel`.

### Example Code

```Python
from pydantic.dataclasses import dataclass, rebuild_dataclass

@dataclass
class Point:
    x: float
    y: float
    color: 'Color'

print(Point.__pydantic_complete__)  # False: Color is not known yet

print(rebuild_dataclass(Point, raise_errors=False))  # False: the dataclass can't be rebuilt

# Now, we define color
@dataclass
class Color:
    name: str

print(rebuild_dataclass(Point))  # True: the dataclass has been rebuilt!

print(Point(x=12, y=-2, color={"name": "red"}))  # Check that the dataclass works correctly

# This should be True now that the dataclass has been rebuilt
# However, it is still False
print(Point.__pydantic_complete__)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0b2
        pydantic-core version: 2.23.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/avannson_gcp/pydantic/bug_pydantic/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Thanks for the bug report, pushing a fix.
