### ISSUE TITLE
Relax default `protected_namespaces` config setting (remove `model_`)

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10315]
Taking inspiration from https://github.com/pydantic/pydantic/issues/7031, https://github.com/pydantic/pydantic/issues/9177, and lots of other user feedback, we've decided to relax restrictions on the [`protected_namespaces`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.protected_namespaces) config setting.

Many users have reported the fact that it's frustrating to get warnings whenever `model_` is used as a field prefix. This is especially prevalent in AI/ML contexts - it's frequent to have fields like `model_id`, etc.

For reference, this is the current behavior:

```py

from pydantic import BaseModel

class Model(BaseModel):
    model_id: str

"""
UserWarning: Field "model_id" in Model has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
"""
```

We think the best way forward is to change the default `protected_namespaces` to an empty tuple, rather than the current default, which is `('model_', )`

As noted in #9177, setting `protected_namespaces=()` - which will be the new default, removes errors associated with collisions against pydantic fields (like `model_fields_set` or similar).

So, with `protected_namespaces=('model_',)`, we get a `NameError`:

```py

from pydantic import BaseModel

class Model(BaseModel):
    model_dump: dict

"""
NameError: Field "model_dump" conflicts with member <function BaseModel.model_dump at 0x10360c5e0> of protected namespace "model_".
"""
```

And with `protected_namespaces=()`, we get a `UserWarning`:

```py

from pydantic import BaseModel, ConfigDict

class Model(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    model_dump: dict

"""
UserWarning: Field name "model_dump" in "Model" shadows an attribute in parent "BaseModel"
"""
```

It's still up for debate whether or not this behavior should occur.

We're looking to get some feedback from the community on this change before we implement it.

**Comment by sydney-runkle** [comment]
cc @jimkring @antoine-lizee, making some forward progress with this issue :).

**Comment by antoine-lizee** [comment]
The proposal looks good !

Thank you for tackling this!!

If I rephrase the changes:
 - a/ if the namespace is protected, remove the annoying warnings whenever the prefix is used, but keep the error on attribute name collision. That's my proposal 2/ in #9177
 - b/ default to warnings on collision instead of error.

I'm in favor of a/, not in favor of b/. I think throwing an error by default is sane (with a redirection to the setting in the error)

**Comment by samuelcolvin** [comment]
A few thoughts here:
* I think setting a field name to match any of our existing methods should raise an Exception, rather than relying on warnings and type checking
* I think we should add `model_validate_` and `model_dump_` to the protected namespaces so we're "free" to add other methods in there without the risk of clashes with fields on existing models

**Comment by eyurtsev** [comment]
`model_validate_` and `model_dump_` in the protected namespaces should be fine -- they're long enough that collisions will be rare. The most common patterns we've seen in the LangChain code base are `model_id`, `model_name`, `model_kwargs`, `model_uri`, `model_url`

**Comment by sydney-runkle** [comment]
Thanks for the feedback, folks! I'll implement this next week.

**Comment by jimkring** [comment]
For what it’s worth, the use case is generally model_NOUN_WORDS for field names (names of data elements in a schema).  model_VERB_WORDS are generally used for methods which a developer has a lot more control over. Point being: model_dump_* and model_validate_* are not likely to ever appear in a data schema.

Thanks for working on this @sydney-runkle @samuelcolvin  and team!

**Comment by adriangb** [comment]
Not sure how much we are thinking about short term vs long term but I think we've discussed in the past:
- using `pydantic_` as the namespace. IMO this should make it rare enough for a collision to happen that we could remove the configurability and complexity
- offering a `BareModel` with no methods on it to be used via `TypeAdapter` primarily. Do dataclasses already serve this purpose?

**Comment by cdwilson** [comment]
It seems like what's being discussed here is how to avoid conflicts between pydantic-defined fields (e.g. `model_config`) and user-defined fields in the `model_` namespace.

I'm not sure if this question is in scope for this discussion, but I was curious how someone might use `protected_namespaces` after the default is changed to an empty tuple. I tried searching around for some existing examples of how this is used today, but didn't find any good examples.

You could imagine one potential use case is a library that provides a base model intended to be subclassed by users of that library. The library author might want to reserve a namespace so that when users subclass a base model provided by the library, they don't accidentally define fields that may conflict with future fields added to the base model:

```python
class FruitBase(BaseModel):
    model_config = {
        "protected_namespaces": ("fruit_",),
    }

class Apple(FruitBase):
    fruit_count: int  # show a warning to prevent fields starting with fruit_
```

However, if the library author wanted to actually add a new field that uses this namespace at some point later on, it doesn't seem like this is possible:

```python
class FruitBase(BaseModel):
    model_config = {
        "protected_namespaces": ("fruit_",),
    }
    fruit_count: int  # try to add a new field into the reserved namespace for the base model
```

Raises `UserWarning: Field "fruit_count" in FruitBase has conflict with protected namespace "fruit_".`

Just trying to understand some use cases where a user of Pydantic would set `protected_namespaces` after this change is made.

**Comment by sydney-runkle** [comment]
@adriangb,

> using pydantic_ as the namespace. IMO this should make it rare enough for a collision to happen that we could remove the configurability and complexity

I believe the verdict here was that we can't have a breaking change of this nature again (even in v3) due to the annoyance that all of the method renaming caused folks in v2.

Re `BareModel`, I think perhaps dataclasses fit that niche for now?

**Comment by samuelcolvin** [comment]
@cdwilson I think the main purpose would be to add methods, not fields, e.g. you could imagine an ORM called `fruit_salad`, that used protected namespaces to allow them to add more methods without the risk of conflicts, e.g.

```py
class FruitModel(BaseModel):
    """Base model for defining tables, similar to `django.db.models.Model`"""
    def fruit_get(self, id):
        ...

    def fruit_all(self):
        ...

    def fruit_filter(self, **query):
        ...
```

AFAIK no one has done this, and I don't promise it would work perfectly, but I think that was the original idea.

**Comment by cdwilson** [comment]
@samuelcolvin makes sense, thx for the insight.

> you could imagine an ORM

Just FYI, my question above was inspired thinking about an ORM-type case where you might want to have a custom config var for the ORM stored on the model (e.g. `myorm_config`), but also reserve the namespace (`myorm_`) for future use.

One example from https://collerek.github.io/ormar/latest/models/#model-class:

```python
class Course(ormar.Model):
    ormar_config = ormar.OrmarConfig(
        database=database,
        metadata=metadata,
    )

```

In this case, it wasn't obvious to me how you'd reserve the `ormar_` namespace via `protected_namespaces` but also allow `ormar_config` on the model. From your reply, it sounds like this just wasn't an intended use case for `protected_namespaces`.

(I just tried to do something similar to this recently and ran across this issue trying to make it work with `protected_namespaces`, so I just figured I'd mention the use case.)

**Comment by sydney-runkle** [comment]
Hey folks, I've opened a PR to address this issue. Let me know what you think of the current approach!

**Comment by sydney-runkle** [comment]
@alexlatif,

Sure thing! Indeed, you should still get warnings if there are conflicts with pydantic fields.

**Comment by sydney-runkle** [comment]
You can try things out on `main` if you're curious!

**Comment by jimkring** [comment]
A BIG thank you from all of us in the _modeling_ industry ✨

![image](https://github.com/user-attachments/assets/60ff882b-889c-4214-8a8e-a4794c73a6d3)

**Comment by samuelcolvin** [comment]
Thanks @jimkring.

Two terrible jokes about Pydantic I have (so far avoided) using:
* "I work with lots of models"
* "Samuel Colvin — desperately seeking validation"

**Comment by psychedelicious** [comment]
@sydney-runkle Forgive me if this has been discussed - I have a feeling the pydantic team is way ahead of me here - but I wonder if using unique identifiers for pydantic's reserved/protected namespaces is an option.

In Javascript, there is a `Symbol` primitive which is a unique value. They can be used for object keys. Symbols are handy for situations like this, where we want to give consumers 100% flexibility with the shape of some data ,but still reserve "space" for our own purposes. [contrived example on the typescript playground](https://www.typescriptlang.org/play/?#code/PTAECUFMAcCdIM6QHYBcGgIbIJ6gK5KwC0cA9gG4CWAJpDaPAMZmwM2aqagAUVAdJH6gaVJqiplkmWDgCUAKFQ5okCJBZsAqsgDWyMgHdkoALzrNNADwJUsKsgDmoAD6gEOALYAjMgBsAGgI9A2MAPgUFEFAtJCx3L18-UAAzVkZ8NCpPNQ4uUGVVUBZkFNoUJjViAoALKgwPH39QetA4KgpOSABuUABBAAUASWKpBHwc2AwmbANULCZKhAwqVAUS2xFOTF1IPHMAZUT-HgByXZxTuW7I6IARbdBPQnmazAo1VBq1C-dIedQZAKsHwkCUKjUDy4VgAKqBIAAPVAoGgYKCWHT6Iwmczo1g0TGhZBhMygADeClAoAA2nkdnsALoALmBoJuAF9QAAyUAwm5RMAw76gKR+PCGTB4QHFeBdeJQ7itQgOZxfVopTLiSTIIKGOpMGotZBEdC1NSNJKgC4C3nCwiQEjkah0diPGYmbxqbB4Zj4oJfXLbADSewSTWShiofmSyEgH1go1KfjEaw280c-wVpNh8KRKLRGnxhOxYR4dJZAHlPKtYf6IWQUlsuBcwnIWQrYSTTCSKVT4Kh8LATL2qTS6RdmazIAFKaP+PO6TOqZzMBgOzCwhz+dEAEIaTD2s1W0OtRx+MjeTDRvCZKgAR1BQSojYDx7wrSQqF1andoE9ibKOg0FqTgm0VDBuAVdYxnmeos3MHNEWRZBUQsIsQhLMtthZGE2zAlo122TszBJHcyH8SBsCwrhaW2CdrkiNMnhweDQAzVAFR4MlUnIllTkvWBTlAdlFA2Cj+HPRweAAIk8FjtmkoI5IVUSxnEySZLghSnwQTjlO2ORFBtWIvTDS00gTbhyGRcR6DaWAyFUWBlFAao1QaLwL2SVp2k6ZFekGEYNgmB1plmMh5kwRZEBWVMYKef5MDpEN9lAI5wzOHIuDpK5wSKABZRK6VJEcmFlZEaD6VB2y6BR2RtIU1CypLtiCJ1ygYbwpWFQKdLfOyuqPC1-DytQAFFkHsA16HXXNkNQvFtAw4xSUWglluJErZ2pZrksZFlCuy7YOW5Xlt0FYVRXFSUCiBMrKORLATAmqbvhoLMlQQFVanVTUJCkXV9UNJLUNfXbtgau0iFIBznTs4rf3-b1GELNh-WFcGuBSszmkjaNQFjeMAOTcRoONdN-hesQ3tYxC8xQgsMQ20ty1AKsaxhOtVAbBKjqxvZWxZKnpveoiNxI8lZ37Qdh1nKkdqK4N9sl0dR3urpKuqgnIEMUAoUgHhFFV9klznBdWtnFcMGFmmxc3OqbmiAB1H5QiPYrWmwUAbZmx49RQI9McwbGP3+MnNnqH3RfyBC4SQ-M0KWrFwmozAcLwj3rcm6nfehcXuxVlGByHUAyIoqi6QVvng8ZRR6udn8vaipYMFfayNAq-DlScI9rSY9jDpamPeFZqOVIOxWY57KX-hlsCq6HmucAZOrGPiuSx8ecx2M3rguL-TAAC8+IfBEhJE8P1LIKTZJwXfMEU5j79U40r5vyPs5FvT5K4ORH4-16udMA8H0r-F+CA36aQQPfEBd9P621-v-aB8CgGwOfuAyB0kB6T2ARvFB0dMB-yCNg6uaD8EqTkEAA).

One potentially awkward catch is consumers must use the same symbol object for index access to the protected properties.

I don't know if python supports this kinda thing, but I figured I'd mention it as I find the pattern very useful.

**Comment by sydney-runkle** [comment]
@psychedelicious,

Interesting idea. Not sure if I completely follow. That being said, I think the relaxed default above plus the added flexibility of regex support for protected namespaces should offer much more flexibility for users than we had previously.

**Comment by psychedelicious** [comment]
@sydney-runkle Yes, the changes to namespaces are very welcome and improve flexibility, thanks for working on those changes!
