### ISSUE TITLE
Known v2.9 bugs / issues

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10326]
We'll release a patch with fixes for these by the end of the week!

Included in v2.9.1:

* https://github.com/pydantic/pydantic/issues/10319
* https://github.com/pydantic/pydantic/issues/10323
* #10328 
* https://github.com/pydantic/pydantic/issues/10333
* https://github.com/pydantic/pydantic/issues/10336
* https://github.com/pydantic/pydantic/issues/10334
* https://github.com/pydantic/pydantic/issues/10345

Resolved questions:

* https://github.com/pydantic/pydantic/issues/10330

To be included in v2.9.2:

* https://github.com/pydantic/pydantic/issues/10357
* https://github.com/pydantic/pydantic/issues/10355
* https://github.com/pydantic/pydantic/issues/10385
* https://github.com/pydantic/pydantic/issues/10363
* https://github.com/pydantic/pydantic/issues/10344
* https://github.com/pydantic/pydantic/issues/10395
* https://github.com/pydantic/pydantic/issues/10407
* https://github.com/pydantic/pydantic/issues/10357

**Comment by jakob-keller** [comment]
How about #10328?

**Comment by PaarthShah** [comment]
I'd like to submit #10330 for consideration

**Comment by sydney-runkle** [comment]
We're delaying the v2.9.2 release until early next week to make sure we can get in fixes for all of the above.

**Comment by sydney-runkle** [comment]
I'm about to release v2.9.2 with all of the above listed fixes!
