### ISSUE TITLE
`tzdata` install dependency should be optional, conditional or removed

### ISSUE THREAD

**Issue by jakob-keller** [pydantic/pydantic#10328]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`pydantic==2.9.0` introduces support for `ZoneInfo`, curtesy of #9896. To ensure an IANA timezone database is available, pydantic now includes an install dependency on `tzdata`. This is arguably not required, since most non-Windows systems already ship that database by default.

I recommend looking at the approach taken by other projects, such as:
* Django: make the install requirement conditional, i.e. only require tzdata on win32
* polars: offer a `timezone` extra that can be selected by users that need to ensure tzdata is installed along with pydantic

**Comment by sydney-runkle** [comment]
@jakob-keller, 

Thanks for the report. Not sure if that qualifies as a bug, but we can certainly consider making this optional! Would very much appreciate a PR with a fix - happy to consider with higher priority in that case :).

**Comment by jakob-keller** [comment]
OK, I'll give it a shot! Should I follow the `polars` example then?

**Comment by sydney-runkle** [comment]
Yep, that works. You can treat it like we do for the `[email]` add-on for email validator.
