### ISSUE TITLE
Unable to evaluate type annotation 'ClassVar[str]' error when creating BaseModel with ClassVar using from __future__ import annotations

### ISSUE THREAD

**Issue by GDYendell** [pydantic/pydantic#10345]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This changed in 2.9.0, possibly due to #10157. Pinning to 2.8.2 fixes it.

Now, if a `ClassVar` attribute is defined on a `BaseModel` with `from __future__ import annotations`, `inspect_namespace` calls `eval_type_backport` with a `ForwardRef(..., is_class=False)`, which calls `typing._type_check` with `allow_special_forms=False`. Perhaps `is_classvar` should to catch this case in the for loop in `inspect_namespace` to skip this check?

Is this expected? Should I not be using `from __future__ import annotations`?

### Example Code

```Python
from __future__ import annotations

from typing import ClassVar

from pydantic import BaseModel


class MyModel(BaseModel):
    _x: ClassVar[str]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0
        pydantic-core version: 2.23.2
          pydantic-core build: profile=release pgo=false
                 install path: /venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Jul 23 2024, 07:22:22) [GCC 12.2.0]
                     platform: Linux-4.18.0-513.24.1.el8_9.x86_64-x86_64-with-glibc2.36
             related packages: mypy-1.11.2 typing_extensions-4.12.2 pyright-1.1.378
                       commit: unknown
```

**Comment by willbakst** [comment]
I am running into the same issue here in version `2.9`

**Comment by Viicos** [comment]
Thanks for the bug report, that's on me. class vars should indeed be evaluated with `is_class` set to `True`.

**Comment by Viicos** [comment]
@atti92, see https://github.com/pydantic/pydantic/issues/2363.
