### ISSUE TITLE
Interaction between `model_construct` and `model_dump` for discriminated unions

### ISSUE THREAD

**Issue by bruno-f-cruz** [pydantic/pydantic#10344]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am a bit confused by this interaction. I understand that this should not be taken as a great pattern to use, but I still don't understand why the `bar` instance is correctly deserialized, but the same behavior is not reproduced when nesting it inside a container with a discriminated union.

I get how I could go around it by using `exclude_unset`, but shouldn't this also throw outside the discriminated union? There seems to be a weird asymmetry in this behavior.

### Example Code

```Python
from typing import Annotated, List, Literal, Union

from pydantic import BaseModel, Field


class Bar(BaseModel):
    discriminator_key: Literal["Bar"] = "Bar"
    name: str


class Foo(BaseModel):
    discriminator_key: Literal["Foo"] = "Foo"


class Container(BaseModel):
    prop: Bar


foo_child = Foo()
bar = Bar.model_construct()
container = Container.model_construct(prop=bar)
print(bar.model_dump())  # {'discriminator_key': 'Bar'}
print(container.model_dump()) # {'prop': {'discriminator_key': 'Bar'}}

##

class Container(BaseModel):

    prop: Annotated[Union[Bar, Foo], Field(..., discriminator="discriminator_key")]


bar = Bar.model_construct()
foo_child = Foo()
container = Container.model_construct(prop=bar)
print(bar.model_dump())  # {'discriminator_key': 'Bar'}
print(container.model_dump()) #throws error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0
        pydantic-core version: 2.23.2
          pydantic-core build: profile=release pgo=false
                 install path: (...)\.venv\Lib\site-packages\pydantic    
               python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
@sydney-runkle, probably related to the tagged union serializer changes. I think you are hitting undefined behavior here, so I don't know if we can do much about it.

**Comment by sydney-runkle** [comment]
Will take a look today, agreed probably related.

**Comment by sydney-runkle** [comment]
Will likely chat about this on our open source sync tomorrow + get back to you after that 👍

**Comment by sydney-runkle** [comment]
Verdict here was - let's warn (not error), and do it consistently for models + unions of models.

**Comment by sydney-runkle** [comment]
Sigh, maybe we shouldn't warn for all models here. I need to circle back with the team again - sort of goes against the current `SerCheck` philosophy.

```
#[derive(Clone, Copy, PartialEq, Eq)]
#[cfg_attr(debug_assertions, derive(Debug))]
pub(crate) enum SerCheck {
    // no checks, used everywhere except in union choices
    None,
    // strict means subclasses are not allowed
    Strict,
    // check but allow subclasses
    Lax,
}
```

I agree that we should be erroring, but rather warning, though.

**Comment by sydney-runkle** [comment]
I don't think we can add warnings for all models in a patch release...
