### ISSUE TITLE
Race condition causes occasional crash with V1 Generics

### ISSUE THREAD

**Issue by alangpierce** [pydantic/pydantic#10351]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I was using a separate library that was using Pydantic in a multithreaded context for a long-running operation, and I was sometimes seeing the operation crash after running for a few minutes. The crash was of the form `'dict' object has no attribute 'x'`, meaning some JSON object was remaining a `dict` when it should have been parsed. I managed to track it down to what I think is a race condition in `GenericModel.__class_getitem__`:

https://github.com/pydantic/pydantic/blob/cdca7aebba33770416c260335e914c1755c48f13/pydantic/v1/generics.py#L166

The code is putting `created_model` in the `_generic_types_cache` on line 160, and then calling `_prepare_model_fields` afterward. My theory is the bug happens if we switch to another thread before `_prepare_model_fields` has been called, and the other thread pulls the not-yet-initialized value from cache and tries to use it before it's initialized. The issue is extra rare because usually the value remains cached, and in my case I believe it was only happening right after a GC (since `_generic_types_cache` is a `WeakValueDictionary`).

In the example code below, I have a script that fails most of the time for me. For some reason, increasing the number of loop iterations didn't get it crash reliably; I needed to run the whole script a few times. As written, it crashes most of the time for me. (I believe I could get it to crash more often by adding a `sleep` to the start of `_prepare_model_fields` to specifically exercise the race condition.)

This is the most common crash:
```
  File "/Users/alan/code/pydantic-test/main.py", line 16, in try_parse
    return WrapperModel[Point](value={"x": 1}).value.x
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'x'
```

and this crash also happens occasionally:
```
  File "/Users/alan/code/pydantic-test/main.py", line 16, in try_parse
    return WrapperModel[Point](value={"x": 1}).value.x
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/code/pydantic-test/venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/code/pydantic-test/venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 1074, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=cls_)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/code/pydantic-test/venv/lib/python3.12/site-packages/pydantic/v1/fields.py", line 853, in validate
    assert self.type_.__class__ is not DeferredType
AssertionError
```

I've been able to work around the issue by patching `GenericModel.__class_getitem__` to wrap it in a `threading.RLock`. With that patch, the code snippet consistently succeeds. Unclear if that's the best fix here or if there's a way to fully initialize the model before adding to the cache, or some other fix.

Thanks!

### Example Code

```Python
import gc
from concurrent.futures import ThreadPoolExecutor
from typing import Generic, TypeVar

from pydantic.v1 import BaseModel
from pydantic.v1.generics import GenericModel

class Point(BaseModel):
    x: int

T = TypeVar("T")
class WrapperModel(GenericModel, Generic[T]):
    value: T

def try_parse():
    return WrapperModel[Point](value={"x": 1}).value.x

def run_task():
    for _ in range(10000):
        try_parse()
        gc.collect(0)

def main():
    with ThreadPoolExecutor(max_workers=4) as executor:
        futures = [executor.submit(run_task) for _ in range(4)]
        for future in futures:
            future.result()

main()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0
        pydantic-core version: 2.23.2
          pydantic-core build: profile=release pgo=false
                 install path: /Users/alan/code/pydantic-test/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Apr 28 2024, 16:26:09) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
Thanks for the clear reproduction script, opened a patch.

**Comment by sydney-runkle** [comment]
For now, I don't think we're going to prioritize work on this fix for v1. Happy to review PRs from contributors with a solution, though! Thanks for reporting this issue.

**Comment by Viicos** [comment]
@alangpierce if you'd like to, you can take a look at https://github.com/pydantic/pydantic/pull/10365, fixes the issue but creates new test failures.

**Comment by sydney-runkle** [comment]
Going to close for now, I don't see us working on this realistically.
