### ISSUE TITLE
False positive validation error on nested generic `BaseModel`

### ISSUE THREAD

**Issue by bluenote10** [pydantic/pydantic#10359]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following example produces a false positive `ValidationError` depending on how exactly the `InnerModel` instance was constructed.

Note that this example reproduces how [`pydantic_geojson` models the relationship of a `FeatureCollection` and a `Feature`](https://github.com/developmentseed/geojson-pydantic/blob/b3cf3f9476484e1d6692ce4a08a75e56143cad73/geojson_pydantic/features.py#L10-L52) according to the GeoJson specification. The issue in pydantic makes working with `pydantic_geojson` currently rather error prone, because sensible looking code like the following crashes at runtime due to the same false positive `ValidationError`:

```py
def create_feature_collection() -> FeatureCollection[Feature[Geometry, Property]]:
    return FeatureCollection[Feature[Geometry, Property]](
        type="FeatureCollection",
        features=[
            Feature(
                type="Feature",
                geometry=Point(type="Point", coordinates=Position2D(10.0, 11.0)),
                properties={"foo": 42},
            )
        ],
    )
```

I've searched the issue tracker for a while to find an existing issue for that. I came up with a few issues that manifest themselves differently, but may have a similar underlying cause:

- #9414
- #10039

### Example Code

```Python
from typing import Generic, TypeVar
from pydantic import BaseModel

# Library side:

M = TypeVar("M", bound=BaseModel)

class InnerModel(BaseModel, Generic[M]):
    model: M

I = TypeVar("I", bound=InnerModel)

class OuterModel(BaseModel, Generic[I]):
    inner: I

# User side:

class MyModel(BaseModel):
    foo: int

# Construct two instances, with and without generic annotation in the constructor:
inner1 = InnerModel[MyModel](model=MyModel(foo=42))
inner2 = InnerModel(model=MyModel(foo=42))

# Everything suggests the two are exactly the same, even the `__eq__` assertion passes:
print(inner1)  # -> model=MyModel(foo=42)
print(inner2)  # -> model=MyModel(foo=42)
assert inner1 == inner2

# However, one of them fails to validate within the outer model!
outer1 = OuterModel[InnerModel[MyModel]](inner=inner1)  # works
outer2 = OuterModel[InnerModel[MyModel]](inner=inner2)  # fails!
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/me/venvs/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.4.0-186-generic-x86_64-with-glibc2.31
             related packages: typing_extensions-4.12.2 fastapi-0.112.2 mypy-1.11.2
                       commit: unknown
```

**Comment by Viicos** [comment]
I believe this is currently expected. Static type checkers can infer type variables from the `__init__` method:

```python
class Model(BaseModel, Generic[T]):
    a: T

m = Model(a=1)
reveal_type(m)  # Model[int]
```

On the other hand, when leaving model classes unparametrized, Pydantic will default to `Any`, meaning `Model(a=1)` is equivalent to `Model[Any](a=1)` ([see more](https://docs.pydantic.dev/latest/concepts/models/#validation-of-unparametrized-type-variables)).

When `outer2` is being constructed, it fails as it expects "instances" of `InnerModel[MyModel]` to be passed, not `InnerModel[Any]`.

We might consider changing the current behavior to match static type checkers semantics, @sydney-runkle wdyt?

**Comment by bluenote10** [comment]
> Pydantic will default to Any, meaning `Model(a=1)` is equivalent to `Model[Any](a=1)`

Just to clarify: In the original example `InnerModel(...)` is actually not the same as `InnerModel[Any](...)` due to the involvement of bounds. To recap:

```py
In [1]: from typing import Any, TypeVar, Generic

In [2]: from pydantic import BaseModel

In [3]: T = TypeVar("T", bound=int)

In [4]: class Model(BaseModel, Generic[T]):
   ...:     x: T
   ...: 

In [5]: Model[Any](x="not_an_int")
Out[5]: Model[Any](x='not_an_int')

In [6]: Model(x="not_an_int")
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[6], line 1
----> 1 Model(x="not_an_int")

File ~/git/immoscrape/venv/lib/python3.10/site-packages/pydantic/main.py:193, in BaseModel.__init__(self, **data)
    191 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    192 __tracebackhide__ = True
--> 193 self.__pydantic_validator__.validate_python(data, self_instance=self)

ValidationError: 1 validation error for Model
x
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='not_an_int', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/int_parsing
```

But of course validation against the bound is not the same as validating against a _specific_ `T`.

What's problematic about the current behavior:
- There can be `ValidationError`'s  in cases where the data is technically valid. In particular, it would be possible to `.model_dump()` on a the inner level, and `model_validate()` on the outer level, and the data would validate, but the current logic erroneously rejects such valid data.
- It seems to attach hidden information to instances. In the example, from a user perspective instances `inner1` and `inner2` are indistinguishable for each other, so it makes no sense why one of them is valid, and the other is invalid.

**Comment by sydney-runkle** [comment]
> We might consider changing the current behavior to match static type checkers semantics, @sydney-runkle wdyt?

Yes, I think this is reasonable. Potential approaches to fixing this problem are linked in the above issues. I'll be designing our v2.10 sprint shortly, and I'd like to include a generic validation behavior overhaul.
