### ISSUE TITLE
Validation of subclasses of built-in types

### ISSUE THREAD

**Issue by JoelGotsch** [pydantic/pydantic#10373]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It seems to me that pydantic v2 is not respecting https://peps.python.org/pep-0253/

What does work as expected:

```python
from pydantic import BaseModel, Field, ConfigDict, __version__

print("pydantic version:", __version__)
#  -> pydantic version: 2.9.1

class Parent:
    def __init__(self, a: str):
        self.a = a

class Child(Parent):
    def __init__(self, a: str, b: str):
        super().__init__(a)
        self.b = b

class MyModel(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    p: Parent

ch = Child(a="a", b="b")
m = MyModel(p=ch)
try:
    print("Attribute b is accessible:", m.p.b)
except AttributeError as e:
    print(e)
# -> Attribute b is accessible: b
print(f"{isinstance(m.p, Child)=}")
# -> isinstance(m.p, Child)=True
```

I would expect the same behaviour for Parent = str, int,...

### Example Code

```Python
from pydantic import BaseModel, Field, ConfigDict, __version__
from datetime import datetime, UTC

class ChildStr(str):
    """This class is a dynamic string, changing over time."""
    
    def __new__(cls, *args, **kwargs):
        # Create a new instance of str (the base class)
        instance = super(ChildStr, cls).__new__(cls, "new_string")
        return instance
    
    def __str__(self):
        return datetime.now(UTC).isoformat()


class MyModel(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    my_string: str = Field(default="my_default")

s = ChildStr()
my_model = MyModel(my_string=s)
print(f"{my_model.my_string=}")
# -> my_model.my_string='new_string'
print(f"{isinstance(my_model.my_string, ChildStr)=}")
# -> isinstance(my_model.my_string, ChildStr)=False
print(f"Expected behaviour: {s}")
# -> Expected behaviour: 2024-09-10T20:23:13.751105+00:00
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: <censored>
               python version: 3.11.2 (main, Mar 28 2023, 21:21:40) [GCC 11.3.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: fastapi-0.104.1 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by JoelGotsch** [comment]
I traced the issue to the following line in BaseModel.__init__:

`validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)`

**Comment by sydney-runkle** [comment]
Hi @JoelGotsch,

I think you can understand this behavior better via this documentation - https://docs.pydantic.dev/latest/concepts/serialization/#subclasses-of-standard-types.

Basically, we don't really support subclasses of std types as arbitrary types, but you instead must define a custom core schema in order to get the behavior you expect.

**Comment by JoelGotsch** [comment]
Hi @sydney-runkle , thanks for the quick reply and the linked sources! :)

The issue is, that compared to the linked cases, I don't have "MyModel" under control, it comes from an external library that expects a str attribute. I can only modify the MyStr class, so the workaround in #9006 doesn't work in my case.

The same issue holds for using  `__get_pydantic_core_schema__`: This method is not called when `MyModel` is validating my ChildStr s for the my_string attribute (which is typed as str) validation. If I understand correctly, the method would only be called, if an attribute in a BaseModel was typed as MyStr?

**Comment by sydney-runkle** [comment]
> If I understand correctly, the method would only be called, if an attribute in a BaseModel was typed as MyStr?

Correct.

Hmm, I understand your concern, though I don't think this is likely to change, as we've got pretty set in stone behavior for stdlib classes. Let me consult with the team and get back to you early next week.

**Comment by JoelGotsch** [comment]
@sydney-runkle any news on the topic?

**Comment by sydney-runkle** [comment]
Indeed, this isn't something we plan on supporting for now.
