### ISSUE TITLE
pyright `reportUninitializedInstanceVariable` false positive in pyright 1.1.380 on `BaseModel` decorated with `@final`

### ISSUE THREAD

**Issue by DetachHead** [pydantic/pydantic#10377]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

[pyright 1.1.380](https://github.com/microsoft/pyright/releases/tag/1.1.380) added support for abstract metaclasses:

> - Added support for custom metaclasses that derive from `ABCMeta`. Classes instantiated from such metaclasses are now treated as abstract.

since `BaseModel`'s metaclass, `ModelMetaclass` extends `ABCMeta`, pyright now treats all of the `ClassVar`s in `BaseModel` as uninitialized attributes when a class is decorated with `@final`:

```
Variables defined in abstract base class are not initialized in final class "Bar"
  Instance variable "__class_vars__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__private_attributes__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__signature__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__pydantic_core_schema__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__pydantic_custom_init__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__pydantic_generic_metadata__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__pydantic_post_init__" is defined in abstract base class "BaseModel" but not initialized
  Instance variable "__pydantic_serializer__" is defined in abstract base class "BaseModel" but not initialized
```

pyright config:
```toml
[tool.pyright]
typeCheckingMode = "strict"
reportUninitializedInstanceVariable = true
```

### Example Code

```Python
from typing import final

from pydantic import BaseModel


@final
class Bar(BaseModel): # error: reportUninitializedInstanceVariable
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\user\project\.venv\Lib\site-packages\pydantic
               python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-11-10.0.22621-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
This is an unfortunate but really uncommon issue. You have to use `@final` on one of your models and enable `reportUninitializedInstanceVariable` (which isn't even enabled when using the pyright `strict` preset). Nothing we can do to trivially fix this; you can maybe raise an issue or question on the pyright repository to have such errors ignored when (and only when) using a custom metaclass, as it is a common pattern to have such class variables added by the metaclass.
