### ISSUE TITLE
List and Sequence fail to validate against various list-like types

### ISSUE THREAD

**Issue by sm-Fifteen** [pydantic/pydantic#1038]
# Bug

Pydantic's List and Sequence validators fail to validate valid Sequences such as `range` as well as other more complex list-like types.

```py
from pydantic import BaseModel
from typing import List, Sequence

class TestRange(BaseModel):
    foo: Sequence

test_range = range(5)
print(f'test_range: {type(test_range)}') # <class 'range'>
print(f'test_range is Sequence: {isinstance(test_range, Sequence)}') # True
print(TestRange(foo=test_range))
```

The check against `typing.Sequence` works because `range` is registered as a subclass of `abc.collections.Sequence` (`Sequence`, unlike `Collection`, doesn't define its subclasses via duck-typing):

https://github.com/python/cpython/blob/ea9835c5d154ab6a54eed627958473b6768b28cc/Lib/_collections_abc.py#L917-L920

Pydantic fails to validate it because it uses a hardcoded set of classes to match against when testing to see if the validated field is sequence-like.

https://github.com/samuelcolvin/pydantic/blob/643266944cd249419e2671348160714fcf7b97a0/pydantic/utils.py#L68-L69

Besides `range`, however, this can be a problem for other custom list-like classes, like SQLAlchemy's associationproxy (which can map a relationship towards another table to a single column). This is the problem I was running into when I started looking at this more in-depth:

<details>
<summary>Lengthy code sample</summary>

```py
from sqlalchemy import Table, Column, Integer, ForeignKey, create_engine
from sqlalchemy.orm import relationship, Session
from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy.ext.associationproxy import association_proxy, _AssociationList

engine = create_engine('sqlite:///:memory:', echo=True)
Base = declarative_base()

association_table = Table('association', Base.metadata,
    Column('left_id', Integer, ForeignKey('left.id')),
    Column('right_id', Integer, ForeignKey('right.id'))
)

class Parent(Base):
    __tablename__ = 'left'
    id = Column(Integer, primary_key=True)
    children = relationship("Child", secondary=association_table)
    child_ids = association_proxy('children', 'id')

class Child(Base):
    __tablename__ = 'right'
    id = Column(Integer, primary_key=True)

Base.metadata.create_all(engine)

sess = Session(bind=engine)
p1 = Parent()
p1.children.append(Child())
p1.children.append(Child())
sess.add(p1)
sess.flush()

from pydantic import BaseModel, validator
import pydantic
from typing import Sequence

from collections.abc import Sequence as ABCSequence, Hashable, Iterable, Sized, Container, MutableSequence, Collection

#MutableSequence.register(type(p1.child_ids))

print(f"Hashable: {isinstance(p1.child_ids, Hashable)}") # True
print(f"Iterable: {isinstance(p1.child_ids, Iterable)}") # True
print(f"Sized: {isinstance(p1.child_ids, Sized)}") # True
print(f"Container: {isinstance(p1.child_ids, Container)}") # True
print(f"Collection: {isinstance(p1.child_ids, Collection)}") # True
print(f"Sequence: {isinstance(p1.child_ids, ABCSequence)}") # False
print(f"MutableSequence: {isinstance(p1.child_ids, MutableSequence)}") # False

print(type(p1.child_ids)) # _AssociationList
print(p1.child_ids)

class ParentModel(BaseModel):
    id: int
    child_ids: Sequence[int]

    # @validator('child_ids', pre=True, whole=True)
    # def check_roles(cls, v):
    #     if type(v) is _AssociationList or issubclass(cls, Sequence):
    #         return set(v)
    #     raise ValueError('not a valid sequence')

    class Config:
        orm_mode = True

print(ParentModel.from_orm(p1).dict())
```

</details>

[`_AssociationList` is meant to emulate `list`'s API](https://github.com/sqlalchemy/sqlalchemy/blob/06b0892da049a995ee4cd1e7cc3c1eb68f3dde64/lib/sqlalchemy/ext/associationproxy.py#L985), and would work just fine if no type checking was being done, but it also does not register as a `Sequence` as far as Pydantic is concerned. Unlike `range`, however, it dies not match as an instance of `abc.Sequence` either because, like I said earlier, those have to be explicitly registered.

Ideally, both examples should be recognized as valid sequences and be converted as if they were ordinary lists, though I recognize that the second example might prove much trickier, especially since it's an edge case to the already edge-case-y first example.

----

* OS: Windows
* Python version: 3.7.5
* Pydantic version: 0.32.2 (Pretty old, I know, it's the version FastAPI ships with)

**Comment by samuelcolvin** [comment]
I would say this is more of a feature request than bug. It's just not something yet implemented.

We can't allow any sequence since for example `str` wouldn't make sense as an input to List even though `list('foobar')` "works". 

Is there some other high-level type like `Collection` or `Sequence` we could check for that would cover these cases?

**Comment by sm-Fifteen** [comment]
Looking at [the full list](https://docs.python.org/3/library/collections.abc.html), I  don't know if it's actually possible to match this with the ABCs without doing something like `if isinstance(v, Sequence) and not isinstance(v, (str, bytes))`.

We could just make our own ABC with a custom `__subclasshook__` if none of the default ones do the trick, it's not like it's some interpreter-only Python magic after all:

https://github.com/python/cpython/blob/ea9835c5d154ab6a54eed627958473b6768b28cc/Lib/_collections_abc.py#L388-L396

...but I don't know if it would help since I'm not aware of any way to tell strings appart from arrays by using duck-typing alone, without a type check.

**Comment by samuelcolvin** [comment]
I'd be willing to try a blacklist instead of a whitelist, but I would need
to wait until v2.

**Comment by bcb** [comment]
+1 to accepting `_AssociationList` 🙏

**Comment by sm-Fifteen** [comment]
The way strings are in Python just makes them behaviorally indistinguishable from "real" collections. Since the Typing module in Python is mainly a way to codify otherwise duck-typed methods and properties into a progressive type system, unless you explicitly check for str and byte objects, you have no way of telling them apart either ([along with a slew of other unfortunate issues](https://www.xanthir.com/b4wJ1) related to strings being treated as arrays), so I don't think there would be any alternatives to specifically blacklisting strings.

**Comment by cdpath** [comment]
For new comers, OP already offered a workaround to *solve* this issue (under `Lengthy code sample`):

```python
class ParentModel(BaseModel):
    id: int
    child_ids: Sequence[int]

    @validator('child_ids', pre=True, whole=True)
    def check_roles(cls, v):
        if type(v) is _AssociationList or issubclass(cls, Sequence):
            return set(v)
        raise ValueError('not a valid sequence')

    class Config:
        orm_mode = True
```

The main idea is to override the default validator.

**Comment by Kludex** [comment]
I'll close this issue, since the example provided in the OP is already working on v2. 🙏

```py
from pydantic import BaseModel
from typing import Sequence

class TestRange(BaseModel):
    foo: Sequence

test_range = range(5)
print(f'test_range: {type(test_range)}') # <class 'range'>
print(f'test_range is Sequence: {isinstance(test_range, Sequence)}') # True
print(TestRange(foo=test_range))
```

**Comment by svili** [comment]
SQLAlchemy AssociationList is still not being recognized as list by Pydantic.
