### ISSUE TITLE
`typing.Type` and `type` handled differently in nested `NamedTuple`

### ISSUE THREAD

**Issue by woodyza** [pydantic/pydantic#10381]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I noticed when we updated to v2.9(.0 and.1) that a particular nested model we have in one of our codebases started causing an error of the form:

```
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for _tuplegetter(0, 'Alias for field number 0'). Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```

The model itself has many attributes but I narrowed it down to an attribute which is a `NamedTuple`, itself having an attribute of type `type`, and with a little more fiddling uncovered something that is really strange.

We use `from __future__ import annotations` in the module this type is defined in, and just importing that appears to cause this error when instantiating the model. Two things (well, three) resolve the error:
* don't import `__future__` -> it works as before with the `type` annotation
* still import `__future__`, but use `typing.Type` rather than `type` in the annotation
* the third is to use `arbitrary_types_allowed=True` like the error says, but this wasn't required before

I honestly have no idea whether this is a pydantic issue or not, but it definitely only happens on 2.9.x

### Example Code

```Python
from __future__ import annotations # see below

import typing

from pydantic import BaseModel


class MyTuple(typing.NamedTuple):
    # type:typing.Type # this works
    type:type # this doesn't, but does if you don't import __future__

class MyModel(BaseModel):
    # model_config = ConfigDict(arbitrary_types_allowed=True) # Adding this makes both work, but wasn't required before
    tuple: MyTuple


def test_types():
    MyModel(tuple=MyTuple(type=int))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/xxx/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
You are hitting a limitation of the runtime type checking logic of Pydantic.

When analyzing the `MyTuple` class, Pydantic will try to evaluate forward annotations, such as `type: 'type'`.

To do so, we use the [`typing._eval_type`](https://github.com/python/cpython/blob/00ffdf27367fb9aef247644a96f1a9ffb5be1efe/Lib/typing.py#L465-L466) function, by passing the forward annotation and the namespaces. Here is a canonical example:

```python
MyType = int

class SomeClass:
    MyType = str

    field: 'MyType'

typing._eval_type(
    typing.ForwardRef(SomeClass.__annotations__['field']),
    globals(),  # module globals {"MyType": int, ...}
    vars(SomeClass),  # `SomeClass` locals  {"MyType": str}
)
#> str
```

In your case, the locals of `MyTuple` are a bit different: the `NamedTuple` class dynamically add some members. In particular, attribute getters are being added for each type. When calling `typing._eval_type`, the module globals will contain the builtin [`type`](https://docs.python.org/3/library/functions.html#type), but `vars(MyTuple)` will take priority and will contain the attribute getter named `'type'`.

This was unexpectedly working before 2.9 as we changed how namespaces are fetched.

---

In general, it is recommended to avoid having the same field names and types. As a workaround, you can import `Type` from `typing`.

**Comment by woodyza** [comment]
Thanks @Viicos! THat's super interesting, I had a suspicion we might have had an accidentally working configuration before.

It's easy enough for me to work around. Should I close this issue, or is there any possible mitigation (even with a clearer error message, if possible) for this edge case?
