### ISSUE TITLE
alias can't work

### ISSUE THREAD

**Issue by cjdxhjj** [pydantic/pydantic#10382]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

i have defined an model like that
class Env(BaseModel):
    user_id: Annotated[int, Field(alias='userId', description='用户id')]
    enterprise_id: Annotated[int, Field(alias='enterpriseId', description='企业id')]
    group_id: Annotated[int, Field(alias='groupId', description='集团id')]
    location_info: Annotated[str, Field(description='当前城市')]
    pig_farm_id: Annotated[int, Field(alias='pigFarmId', description='猪场id')]
    farm_name: Annotated[Optional[str], Field(description='猪场名称', default=None)]

the use send me a json like 
```json
{
		"userId": "3463429",
		"enterpriseId": "2404981",
		"groupId": "2379608",
		"location_info": "北京市",
		"pigFarmId": "2103231752110001077"
	}
```
the userid map to user_id, that good.
and then i store it in db, use model_dump_json the result is 
```json
{"user_id":3463429,"enterprise_id":2404981,"group_id":2379608,"location_info":"北京市","pig_farm_id":2103231752110001077,"farm_name":null}
```
and can't restore it from model_validate_json method
![image](https://github.com/user-attachments/assets/baead13f-c588-4fa0-9a04-104c016bd5fb)
and i have to use alias to new the object by code
i can't use env = Env(user_id=1, enterprise_id=1, group_id=1, location_info='', pig_farm_id=1, farm_name='')
must use Env(userId=1, enterpriseId=1, groupId=1, location_info='', pigFarmId=1, farm_name='')

### Python, Pydantic & OS Version

```Text
python 3.12
pydantic 2.5.0
```

**Comment by cjdxhjj** [comment]
i have try to use serialization_alias
```python
class Env(BaseModel):
    user_id: Annotated[int, Field(serialization_alias='userId', description='用户id')]
    enterprise_id: Annotated[int, Field(serialization_alias='enterpriseId', description='企业id')]
    group_id: Annotated[int, Field(serialization_alias='groupId', description='集团id')]
    location_info: Annotated[str, Field(description='当前城市')]
    pig_farm_id: Annotated[int, Field(serialization_alias='pigFarmId', description='猪场id')]
    farm_name: Annotated[Optional[str], Field(description='猪场名称', default=None)]
```

but it can't resolve from json
```json
{
		"userId": "3463429",
		"enterpriseId": "2404981",
		"groupId": "2379608",
		"location_info": "北京市",
		"pigFarmId": "2103231752110001077"
	}
```

**Comment by cjdxhjj** [comment]
or stop to use alias, accept the camel case name?

**Comment by cjdxhjj** [comment]
why it can't serialize according to the alias, the new instance by field name not the alias name

**Comment by Viicos** [comment]
You need to use `by_alias=True` when using `model_dump_json`.

Docs:

- https://docs.pydantic.dev/latest/concepts/fields/#field-aliases
- https://docs.pydantic.dev/latest/concepts/alias/

**Comment by cjdxhjj** [comment]
@Viicos but when i new an instance by code, i must special with alias.
the decode method use alias by default, but serialize must special by_alias=True

**Comment by Viicos** [comment]
This is being discussed at https://github.com/pydantic/pydantic/issues/8379.
