### ISSUE TITLE
Implementing Discriminated Unions without using Nested Models

### ISSUE THREAD

**Issue by rahulgupta-nnamu** [pydantic/pydantic#10409]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm trying to implement discriminated unions in Pydantic to dynamically select the correct class based on user input using the `discriminator` parameter. While the [documentation](https://docs.pydantic.dev/latest/concepts/unions/#discriminated-unions-with-str-discriminators) suggests creating a nested model class to handle this easily, but I want to avoid introducing additional nested models and instead maintain a flat structure similar to a standard `BaseModel`.

I'm not sure if I'm using the discriminated union functionality correctly in this context. I have tried the below approaches where using a `TypeAdapter` comes closest to what I want. 

Is there any better way to do this?

### Main Code

```Python
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, RootModel, TypeAdapter


class Cat(BaseModel):
    pet_type: Literal["cat"]
    meows: int


class Dog(BaseModel):
    pet_type: Literal["dog"]
    barks: float


class Lizard(BaseModel):
    pet_type: Literal["reptile", "lizard"]
    scales: bool

Animal = Union[Cat, Dog, Lizard]
```

### Approach - 1  (using RootModel)

I tried to use `RootModel` but the resulting object is encapsulated within the `.root` property. I am able to access all the methods of a `BaseModel` but I cannot directly access the attributes.  

```Python
AnnotatedAnimal = Annotated[Animal, Field(discriminator="pet_type")]
AnimalModel = RootModel[AnnotatedAnimal]
animal = AnimalModel.model_validate({"pet_type": "cat", "meows": 3})  # Ok
animal.model_dump()  # Ok
try:
    print(animal.pet_type)  # Not Ok
except AttributeError as e:
    print(e)
    # > "RootModel[Annotated[Union[Cat, Dog, Lizard], FieldInfo(annotation=NoneType, required=True, discriminator='pet_type')]]" object has no attribute 'pet_type'

print(animal.root.pet_type)
# > cat
```

### Approach - 2 (using Nested model)
A nested model works as expected, but introduces additional hierarchy, which I would prefer to avoid.

```Python
class Pet(BaseModel):
    animal: Animal


pet = Pet.model_validate({"animal": {"pet_type": "cat", "meows": 3}})  # Ok
pet.model_dump()  # Ok
print(pet.animal.pet_type)  # Ok
# > cat
```

### Approach-3 (using TypeAdapter)

With TypeAdapter, I can validate the input, but I lose the some of the benefits of `BaseModel` methods like for e.g. `model_validate`.
```Python
AnimalTypeAdapter = TypeAdapter(Animal)
animal = AnimalTypeAdapter.validate_python(
    {"pet_type": "cat", "meows": 3}
)
animal.model_dump()  # Ok

try:
    # cannot use .model_validate() as it does not have all methods of BaseModel instances
    AnimalTypeAdapter.model_validate({"pet_type": "cat", "meows": 3})  # Not Ok
except AttributeError as e:
    print(e)
    # > 'TypeAdapter' object has no attribute 'model_validate'

print(animal.pet_type)  # Ok
# > cat
```

### Python, Pydantic & OS Version

```Text

             pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/rahul/anaconda3/envs/projects/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: mypy-1.11.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Yep `TypeAdapter` is great here!

```py
from typing import Annotated, Literal, Union

from pydantic import BaseModel, TypeAdapter, Field


class Cat(BaseModel):
    pet_type: Literal["cat"]
    meows: int


class Dog(BaseModel):
    pet_type: Literal["dog"]
    barks: float


class Lizard(BaseModel):
    pet_type: Literal["reptile", "lizard"]
    scales: bool

AnimalAdapter = TypeAdapter(Annotated[Union[Cat, Dog, Lizard], Field(discriminator='pet_type')])
```

**Comment by tonyyzy** [comment]
Hi @sydney-runkle is there any way to make TypeAapter to behaviour more similar to a BaseModel?

**Comment by sydney-runkle** [comment]
@tonyyzy, in what sense?

**Comment by tonyyzy** [comment]
@sydney-runkle as in you can not construct it like a model

**Comment by subsurfaceiodev** [comment]
Hi there! we are also facing the same interest in the sense of having discriminated unions without nested models, how would the approach look like for cases like for a class Animals() that stores animals in a list which should also assign appropriate classes when using model_validate
