### ISSUE TITLE
Field parsing order is not taken into account for Decimal | str

### ISSUE THREAD

**Issue by olivierdolle** [pydantic/pydantic#10413]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

First of all thanks for the amazing library 👏 

I have observed a change in behavior confirmed in 2.9.0 and 2.9.1 compared to 2.8.2.

The type order for Decimal and string in not taken into account. I haven't checked for other types that could behave the same.

# How it used to behave
Having a field annotated `Decimal | str` used to first try to parse to `Decimal` in `2.8.2` then to `str` if the string was not a valid Decimal (e.g. `"5%"`) .

# How it now behaves
In 2.9.0 and 2.9.1, it does not try to parse to Decimal, or at least it always parses to str if the input is a string.

# Changelog
I checked the changelog for 2.9.0 and didn't see anything directly mentioning this change but may have missed something 😕 

There is a tiny change mentionning `Decimal` but it does not look related.
> Move decimal.Decimal validation to _generate_schema.py by @sydney-runkle in https://github.com/pydantic/pydantic/pull/9977

With a little guidance, I'm up to try and fix this 🙂 

### Example Code

```Python
from decimal import Decimal

from pydantic import BaseModel

class Cover(BaseModel):
  deductible: Decimal | str

cover = Cover.model_validate({"deductible": "0"})

assert isinstance(cover.deductible, Decimal) # evaluates to "False"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/olivier/dev/test/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @olivierdolle,

Thanks for your question. This is the correct behavior - "0" validates in strict mode as a `str`, but only in `lax` mode as a `Decimal`, and so `str` is the "smarter" decision here (you're using smart mode for unions by default). If you'd like to prefer `Decimal` here, you can use `Field(union_mode='left_to_right')`:

```py
from decimal import Decimal

from pydantic import BaseModel, Field

class Cover(BaseModel):
  deductible: Decimal | str = Field(union_mode='left_to_right')

cover = Cover.model_validate({"deductible": "0"})

assert isinstance(cover.deductible, Decimal)
```

**Comment by olivierdolle** [comment]
Thanks a lot 🙏 , I must have missed it.
