### ISSUE TITLE
Support  `alias_generator` callable to return an instance of `AliasChoices`

### ISSUE THREAD

**Issue by andlogreg** [pydantic/pydantic#10424]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

**Context**

_Relates to https://github.com/pydantic/pydantic-settings/issues/406_

When setting individual fields aliases, one can use `AliasChoices` to specify multiple alternatives (for an example, see this [comment](https://github.com/pydantic/pydantic-settings/issues/406#issuecomment-2352788218))

But when using a callable as an `alias_generator`, the callable must return a `str`.

**Feature request** 

can   `alias_generator` be modified to also support Callables which return `AliasChoices`?

**My current use case** 

It would be as described in the linked pydantic-settings issue:

> When using multi-word named settings, I would like to:
> 
> 1. for CLI, use dashes for word separation, as it is the most common approach I've seen in CLI programs
> 2. for ENV variables, use underscores for word separation as it is the standard (and dashes are not supported anyway)

Although I managed to achieve this by [setting AliasChoices for each individual field](https://github.com/pydantic/pydantic-settings/issues/406#issuecomment-2352788218), it would be great to remove so much repetition.

**Code example**

I would like to avoid repetition and be able to simply set an alias_generator like so:

```python
    model_config = SettingsConfigDict(
        cli_parse_args=True,
        env_nested_delimiter="__",
        alias_generator=lambda x: AliasChoices(x, x.replace('_','-'))
    )
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
I think it'd be reasonable to support this in [`AliasGenerator`](https://docs.pydantic.dev/latest/concepts/alias/#using-an-aliasgenerator) for the `validation_alias` argument.

PRs welcome - this is a great first issue :).

**Comment by andlogreg** [comment]
> I think it'd be reasonable to support this in [`AliasGenerator`](https://docs.pydantic.dev/latest/concepts/alias/#using-an-aliasgenerator) for the `validation_alias` argument.
> 
> PRs welcome - this is a great first issue :).

I will try to have a look at it tomorrow and assess if I understand it well enough for submitting a PR

**Comment by andlogreg** [comment]
@sydney-runkle while starting working on the PR... I learned that this use-case is in fact already covered in AliasGenerator. It already [accepts Callables which return objects of type AliasChoices as the validation_alias](https://github.com/pydantic/pydantic/blob/main/pydantic/aliases.py#L99).

So the use-case I was seeking is already supported as I show [here](https://github.com/pydantic/pydantic-settings/issues/406#issuecomment-2358019805) and I believe there's no need for a PR :) 

thank you for the support!

**Comment by sydney-runkle** [comment]
@andlogreg, hah - nice! I forgot we added support there. Great!
