### ISSUE TITLE
Suprising behavior for Pydantic + Werkzeug MultiDict

### ISSUE THREAD

**Issue by afallou** [pydantic/pydantic#10446]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm using Pydantic with Flask. I was looking at using Pydantic schemas for query string parameters, and found out that `MySchema.model_validate(request.args)` behaves surprisingly; by default it will get values as a list. The reason I find it surprising is that `werkzeug.datastructures.MultiDict` (the underlying data structure for query params in Flask) has a dictionary interface. Why would Pydantic not get field values through that dictionary interface?

I'm guessing the answer is in the validation logic in pydantic-core, which I've started looking through (slowly, as I'm not proficient at Rust).

### Example Code

```Python
from pydantic import BaseModel
from werkzeug.datastructures import MultiDict


class QueryString(BaseModel):
    offset: int = 0


input_query_string = MultiDict({"offset": "10"})

# MultiDict has a dictionary interface, I'd expect Pydantic to be accessing values more or less this way.
print(input_query_string["offset"])
#> 10
# It allows duplicate keys, the values for which can be retrieved as a list
print(input_query_string.getlist("offset"))
#> ['10']

QueryString.model_validate(input_query_string)
# pydantic_core._pydantic_core.ValidationError: 1 validation error for QueryString
# offset
#   Input should be a valid integer [type=int_type, input_value=['10'], input_type=list]

# This works, but would require ugly wrangling to make it work with lists e.g. ?foo=1&foo=2
# such as the logic in https://github.com/adamsussman/flask-pydantic-api/blob/main/flask_pydantic_api/api_wrapper.py#L88-L94
output = QueryString.model_validate(input_query_string.to_dict())
print(output.offset)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0
        pydantic-core version: 2.23.2
          pydantic-core build: profile=release pgo=false
                 install path: /Users/adrienfallou/.virtualenvs/quaero-api/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Dec 19 2023, 13:06:19) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.7.6-x86_64-i386-64bit
             related packages: mypy-1.10.1 pydantic-settings-2.3.4 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Huh, this is surprising. Not sure at a first glance - will take some rust digging to find out. Maybe @davidhewitt has some good intuition here...

**Comment by davidhewitt** [comment]
This is because `MultiDict` is implemented as a subclass of `dict` where the values are stored as lists. The `__getitem__` and `__setitem__` methods then override this to retrieve the first item / append to the list.

PyO3 / `pydantic-core` see a `dict` and look directly at it, so the fact that `__getitem__` and `__setitem__` are overridden is ignored.

Related: https://github.com/PyO3/pyo3/issues/4490
