### ISSUE TITLE
validate_strings does not validate an arbitrary string that is a dict

### ISSUE THREAD

**Issue by craigcrawfordcts** [pydantic/pydantic#10465]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The documentation for TypeAdapter validate_strings, would suggest it takes an arbitrary string: https://docs.pydantic.dev/latest/api/type_adapter/#pydantic.type_adapter.TypeAdapter.validate_strings

Additionally, this also seems to reference that it is possible to take an arbitrary string: https://github.com/pydantic/pydantic/issues/7549

The implementation code seems to test arbitrary strings where they are values of a dict, but not where the input "object" is a string itself and is a dict: https://github.com/pydantic/pydantic/pull/7552/files

Meaning pydantic does not parse this correctly, but I feel it should...

### Example Code

```Python
from pydantic import ConfigDict, TypeAdapter
import typing as T


pydantic_config = ConfigDict(frozen=True, extra="forbid")

MyAdapter: TypeAdapter[T.Dict[str, str]] = TypeAdapter(T.Dict[str, str], config=pydantic_config)

def test_my_adapter() -> None:
    assert MyAdapter.validate_strings('{"a": "b"}') == {"a": "b"}

"""
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for dict[str,str]
E         Input should be an object [type=dict_type, input_value='{"a": "b"}', input_type=str]
E           For further information visit https://errors.pydantic.dev/2.8/v/dict_type
"""
```

If the method is changed to `validate_json` and the string changed to bytes... it passes the test.
```Python
from pydantic import ConfigDict, TypeAdapter
import typing as T


pydantic_config = ConfigDict(frozen=True, extra="forbid")

MyAdapter: TypeAdapter[T.Dict[str, str]] = TypeAdapter(T.Dict[str, str], config=pydantic_config)

def test_my_adapter() -> None:
    assert MyAdapter.validate_json(b'{"a": "b"}') == {"a": "b"}

"""
tests/unit/models/test_pydantic.py::test_my_adapter PASSED
"""
```

However, there is no way to test the following scenario with validate_json and the dict is treated as "OK" even though it has duplicate keys...
```Python
from pydantic import ConfigDict, TypeAdapter
import typing as T

from pydantic_core import ValidationError
import pytest


pydantic_config = ConfigDict(frozen=True, extra="forbid")

MyAdapter: TypeAdapter[T.Dict[str, str]] = TypeAdapter(T.Dict[str, str], config=pydantic_config)

def test_duplicate_keys() -> None:
    with pytest.raises(ValidationError):
        MyAdapter.validate_json(b'{"a": "b", "a": "b"}')

"""
>       with pytest.raises(ValidationError):
E       Failed: DID NOT RAISE <class 'pydantic_core._pydantic_core.ValidationError'>

tests/unit/models/test_pydantic.py:13: Failed
============================================================== short test summary info ==============================================================
FAILED tests/unit/models/test_pydantic.py::test_duplicate_keys - Failed: DID NOT RAISE <class 'pydantic_core._pydantic_core.ValidationError'>
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/user/source/eclips-auth-service/src/before-signon/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Jul 29 2024, 15:17:50) [GCC 11.4.0]
                     platform: Linux-6.1.100+-x86_64-with-glibc2.35
             related packages: mypy-1.11.1 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hmm @samuelcolvin, what was the intent here?

**Comment by samuelcolvin** [comment]
`MyAdapter.validate_strings('{"a": "b"}')` was never supposed to work.

`validate_strings` is designed (as the name suggests) for scenarios where the input must always be strings (or objects where all values are strings), e.g:
* env variables
* URL arguments
* HTTP headers
* form plain `inputs`s

if you want `{"a": "b", "a": "b"}` to raise an error, that's a separate issue, as of https://github.com/pydantic/jiter/pull/81 jiter already supports it, so it's "just" implementing the logic in pydantic-core I guess.

**Comment by craigcrawfordcts** [comment]
But the input is a string of an object containing strings, so `validate_strings` does not validate strings of an object contained as a string...

The functionality is confusing comparing to validate_json, since I can give it a byte string of the same thing and it just works.

**Comment by Viicos** [comment]
This is tracked as a feature request in https://github.com/pydantic/pydantic/issues/12717 -- although this doesn't mean we necessarily want to implement it, rather we are tracking demand for this.
