### ISSUE TITLE
Crash with recursive `repr`/`str`/`print`

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10463]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

in python, the std types like `list` have special casing for recursive stringification, it would be logical if pydantic followed this convention

### Example Code

```Python
from pydantic import BaseModel

l = []
l.append(l)
print(l)  # [[...]]


class A(BaseModel):
    a: object = None


a = A()
a.a = a
print(a)  # crash
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
PRs welcome with a fix, I think this is a good idea!

**Comment by JHON12091986** [comment]
I'll work on this bounty. I have strong experience with Python async/await and Pydantic.

Plan:
1. Modify `@validate_call` to support async functions
2. Add tests for async validation
3. Update documentation

ETA: 2-3 days.
