### ISSUE TITLE
(🐞) false positive mypy error "Only `root` is allowed as a field of a `RootModel`"

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10474]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

a `Final` with a default value is not a field, it's a `ClassVar`, and pydantic correctly handles this at runtime, but the mypy plugin is incorrect here

### Example Code

```Python
from typing import Final

from pydantic import RootModel


class A(RootModel[str]):
    a: Final = 1  # error: Only `root` is allowed as a field of a `RootModel`  [pydantic-field]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: mypy-1.11.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Indeed, looks like a bug. Fixing is relatively low priority, but PRs welcome!

**Comment by Viicos** [comment]
The typing specification regarding `Final` was [updated this year](https://github.com/python/typing/pull/1669), and it seems that we don't apply the same semantics, but we probably should. For `a` to be considered a class variable, it should explicitly be wrapped inside the `ClassVar` special form.

Pending clarification as well: https://github.com/microsoft/pyright/issues/9468

**Comment by Viicos** [comment]
This will be fixed in https://github.com/pydantic/pydantic/pull/11121. However, I've raised https://github.com/pydantic/pydantic/issues/11119: in V3, the behavior is going to change and final fields with a default value will no longer be considered a class variable. @KotlinIsland, I recommend changing your code to:

```python
from typing import ClassVar

from pydantic import RootModel


class A(RootModel[str]):
    a: ClassVar[int] = 1
```
