### ISSUE TITLE
mypy complains about the `computed_field` decorator

### ISSUE THREAD

**Issue by Ravencentric** [pydantic/pydantic#10481]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The [docs](https://docs.pydantic.dev/latest/concepts/fields/#the-computed_field-decorator) state:
> If not specified, [computed_field](https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.computed_field) will implicitly convert the method to a [property](https://docs.python.org/3/library/functions.html#property). However, it is preferable to explicitly use the [@property](https://docs.python.org/3/library/functions.html#property) decorator for type checking purposes.

But using the example from the docs:
![image](https://github.com/user-attachments/assets/466fa544-e2c9-4023-a171-bfabf81540fb)
```powershell
❯ mypy --version
mypy 1.11.2 (compiled: yes)

❯ mypy .\test.py --strict
test.py:9: error: Decorators on top of @property are not supported  [prop-decorator]
Found 1 error in 1 file (checked 1 source file)
```

### Example Code

```Python
from pydantic import BaseModel, computed_field


class Box(BaseModel):
    width: float
    height: float
    depth: float

    @computed_field
    @property
    def volume(self) -> float:
        return self.width * self.height * self.depth


b = Box(width=1, height=2, depth=3)
print(b.model_dump())
# > {'width': 1.0, 'height': 2.0, 'depth': 3.0, 'volume': 6.0}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\raven\Documents\GitHub\toolbox\.venv\Lib\site-packages\pydantic
               python version: 3.12.6 (main, Sep  9 2024, 20:50:27) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: mypy-1.11.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
This is a mypy limitation. See https://mypy.readthedocs.io/en/stable/error_code_list.html#decorator-preceding-property-not-supported-prop-decorator.

**Comment by Ravencentric** [comment]
Okay, thank you. Would it be possible to add a note mentioning this in the docs?

**Comment by Viicos** [comment]
I'm generally not really in favor of adding something related to an issue that might be fixed at some point (and docs become outdated). However, we'll still accept PRs adding a note to the mypy issue/error code in the popup box:

![image](https://github.com/user-attachments/assets/879ddb32-ef1b-44f9-bb72-ec93f54c9863)
