### ISSUE TITLE
Mypy Syntax Error Python 3.8

### ISSUE THREAD

**Issue by pythonweb2** [pydantic/pydantic#10492]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The issue is explained in https://github.com/python/mypy/issues/17768, but the author closed the issue with no indication it had been resolved or even reported.

Error Message: `error: X | Y syntax for unions requires Python 3.10`

### Example Code

```Python
See related issue
```

### Python, Pydantic & OS Version

```Text
OS: Ubuntu 20.04
Python: 3.8.10 (Version that ships with Ubuntu 20.04)
Pydantic: 2.9.2
```

**Comment by Viicos** [comment]
Well the error message is pretty clear? You are on Python 3.8, and this syntax was [introduced in 3.10](https://docs.python.org/3/library/stdtypes.html#types-union).

Pydantic will still be able to evaluate such expressions thanks to the [`eval_type_backport`](https://pypi.org/project/eval-type-backport/) package, which needs to be manually installed.
