### ISSUE TITLE
Internal Pydantic code issuing warnings

### ISSUE THREAD

**Issue by alicederyn** [pydantic/pydantic#10497]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm running my tests with `pytest -W error` and found a place where Pydantic is issuing deprecation warnings against its own code. As a user, I can't really fix this, as I'm not calling any deprecated functions myself, and I'd rather not have to suppress warnings for code I don't own. Specifically, if I do `isinstance(v2_instance, v1.BaseModel)`, I get

```text
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    isinstance(foo, pydantic.v1.BaseModel)
  File "pydantic/v1/main.py", line 304, in __instancecheck__
    return hasattr(instance, '__fields__') and super().__instancecheck__(instance)
  File "pydantic/main.py", line 1090, in __fields__
    warnings.warn(
pydantic.warnings.PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
```

Would it be ok to fix this? ~One option would be to wrap this `hasattr` call in a `catch_warnings` block and ignore this warning.~ _Edit: not an option; see below._ Alternatively, perhaps we could check a different attribute? Or check a V2 attribute first then fall back to a V1 one?

### Example Code

```Python
import pydantic, pydantic.v1, warnings

class Foo(pydantic.BaseModel):
  bar: str

foo = Foo(bar="txt")

warnings.simplefilter("error")
isinstance(foo, pydantic.v1.BaseModel)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/apurcell14/code/hera/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, Mar  4 2024, 14:30:04)  [GCC 11.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 mypy-1.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Yep, we can definitely fix this.

Would you be willing to submit a PR with a fix? Thanks for catching this!

**Comment by alicederyn** [comment]
Which of the three options for fixing it would you suggest I try?

**Comment by sydney-runkle** [comment]
> One option would be to wrap this hasattr call in a catch_warnings block and ignore this warning.

Let's do this, and catch the deprecation warning.

**Comment by alicederyn** [comment]
The only downside is, I'm not sure how expensive that is, and I think the point of this callsite was to be fast.

**Comment by alicederyn** [comment]
Oh, wait, this option is a no-go:

> Note: this can only be guaranteed in a single-threaded application. If two or more threads use the [catch_warnings](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings) context manager at the same time, the behavior is undefined.

**Comment by sydney-runkle** [comment]
Really? Why not something like:

```py
import warnings

with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=DeprecationWarning)
```

Let's just do some profiling + see how things compare for the instance check with and without that context manager...

**Comment by alicederyn** [comment]
I assume we raced in replying? I think the undefined behaviour is a definite no-go.

**Comment by sydney-runkle** [comment]
Hmm, let's try `__post_root_validators__` or something else like that which isn't present on v2 models, so doesn't carry with it the burden of a deprecation warning...

**Comment by sydney-runkle** [comment]
@alicederyn,

Would you be able to open a PR to help with this issue? Thanks!

**Comment by alicederyn** [comment]
Yep, just need to find time to prioritise it.
