### ISSUE TITLE
model_dump by_title

### ISSUE THREAD

**Issue by LucienShui** [pydantic/pydantic#10502]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Now user can using `model_dump` with `by_alias`, sometimes I want to export an object to LLM prompt by its field title, so maybe a parameter like `by_title` is better.

```python
from pydantic import BaseModel, Field, ConfigDict


class Foo(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    a: int = Field(alias="alias_a", title="title_a")
    b: str = Field(alias="alias_b", title="title_b")


def main():
    foo = Foo(a=1, b="2")
    print(foo.model_dump_json())  # output: {"a":1,"b":"2"}
    print(foo.model_dump_json(by_alias=True))  # output: {"alias_a":1,"alias_b":"2"}
    # print(foo.model_dump_json(by_title=True))  # expect: {"title_a":1,"title_b":"2"}


if __name__ == '__main__':
    main()

```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@LucienShui,

Thanks for your question!

Hmm, `title` is just a JSON schema thing. Going to close as not planned for now, happy to reconsider if this request gets a lot of traction.

**Comment by sydney-runkle** [comment]
You can also use `serialization_alias` to further customize this. https://docs.pydantic.dev/latest/concepts/fields/#field-aliases
