### ISSUE TITLE
Field metadata from Annotated is lost after a call to update_forward_refs

### ISSUE THREAD

**Issue by AntonOvsyannikov** [pydantic/pydantic#10509]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

please see #3282 , reproduced both with pydantic 1.10.18 and 2.9.2 (v1 mode)

works well w/o `from __future__ import annotations`

### Example Code

```Python
from __future__ import annotations

from typing import Annotated

from pydantic.v1 import BaseModel, Field


class Foo(BaseModel):
    bar1: "Bar" = Field(extra=True)
    bar2: Annotated["Bar", Field(extra=True)]


class Bar(BaseModel):
    ...


Foo.update_forward_refs()

print(Foo.__fields__["bar1"].field_info.extra)  # {'extra': True}
print(Foo.__fields__["bar2"].field_info.extra)  # {}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: ...site-packages\pydantic
               python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: fastapi-0.95.0 mypy-1.1.1 typing_extensions-4.12.2
                       commit: unknown
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
`ModelField.prepare` should probably be tweaked to incorporate some logic from `ModelField.infer`. PRs welcome.

**Comment by sydney-runkle** [comment]
V1 issues like this one are generally low priority though, so I wouldn't expect much work from our team here.

**Comment by sydney-runkle** [comment]
Going to close this for now, as we're not working on V1 issues like this one. If someone is interested in opening a PR though, I'd be happy to review.
