### ISSUE TITLE
include= and exclude= parameters for `model_dump` could usefully accept frozenset

### ISSUE THREAD

**Issue by steve-mavens** [pydantic/pydantic#10517]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently the type `IncEx` includes `Set[str]` in the union, but that's `typing.Set`, not `collections.abc.Set`. Therefore it accepts mutable sets, but not immutable frozensets. Immutable collections are useful to protect shared data (such as global constants) from accidental modification by functions that mutate their parameters. In that context, `model_dump` in effect is type hinting that it might modify the include/exclude arguments, and therefore you shouldn't pass in a shared value!

```python

from collections.abc import Set
from pydantic.main import IncEx

# Global fields to exclude
foo = frozenset({'foo'})


def bar(fields: Set[str]) -> int:
    return len(fields)

bar(foo)  # OK: collections.abc.Set accepts frozenset


def baz(fields: IncEx) -> int:
    return 0

baz(foo)  # error: Argument 1 to "baz" has incompatible type "frozenset[str]"; expected "IncEx"  [arg-type]
```

Unless `model_dump` actually does mutate this argument (which the docs don't say it does), then I think it would be desirable to accept `frozenset[str]` in particular, and `collections.abc.Set[str]` in general.

You could perhaps even accept `collections.abc.Container[str]`, if all you need is to check membership of each field in the argument, or `Collection[str]` if you also iterate over the argument. The possibility of accepting sequences is discussed a little in https://github.com/pydantic/pydantic/issues/10010: this isn't a dupe because frozenset isn't a sequence, but the two requests are related.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
We decided to allow any collection to be used, and internally we will call `set` on the passed object. Going to close as we are tracking progress on https://github.com/pydantic/pydantic/issues/10010. Thanks for the report!
