### ISSUE TITLE
Pydantic handling of timestamps possibly incorrect

### ISSUE THREAD

**Issue by wezham** [pydantic/pydantic#10512]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am passing the output from a database to a model. Snowflake timestamp_tz format outputs a date in the format `2024-09-30 01:40:10.069 +0000` 

When passing this as input to a model:

```python
from pydantic import AwareDatetime, BaseModel

class Tester(BaseModel):
    created: AwareDatetime


print(Tester.model_validate({"created": "2024-09-30 01:40:10.069 +0000"}))
```

I get:

```
  Input should be a valid datetime or date, unexpected extra characters at the end of the input [type=datetime_from_date_parsing, input_value='2024-09-30 01:40:10.069 +0000', input_type=str]
```

However, if I remove the extra whitespace as below there is no problem in the output:

```python
from pydantic import AwareDatetime, BaseModel

class Tester(BaseModel):
    created: AwareDatetime


print(Tester.model_validate({"created": "2024-09-30 01:40:10.069+0000"}))
```

Looking at a few different databases it seems that its common for the string representation to have a space before the + sign. In the absence of pydantic supporting this, we'd have to add a custom validator to transform the input before its parsed in pydantic which seems counter productive. 

### Example Code

```Python
from pydantic import AwareDatetime, BaseModel

class Tester(BaseModel):
    created: AwareDatetime


print(Tester.model_validate({"created": "2024-09-30 01:40:10.069 +0000"}))
```

### Python, Pydantic & OS Version

```Text
2.7.4
```

**Comment by sydney-runkle** [comment]
Hmm, it makes sense to me that this format isn't accepted given our [datetime docs](https://docs.pydantic.dev/latest/api/standard_library_types/#datetime-types).

Will chat with the team to see if we'd consider adding support for this.

**Comment by sydney-runkle** [comment]
Following up here - looks like that whitespace isn't RFC3339 nor ISO 8601 compliant (i.e. it's nonstandard), so we don't intend to support this. The right approach here for your use case is the custom validator 👍

**Comment by wezham** [comment]
Thanks @sydney-runkle appreciate you checking up on this
