### ISSUE TITLE
pydantic.validate_call makes a copy of the list in order to validate it?

### ISSUE THREAD

**Issue by xyshell** [pydantic/pydantic#10511]
This is new to me. Could someone help me understand why pydantic has to make a copy of the list in order to validate it? 

If so, does it mean `pydantic.validate_call` is not supposed to be used for any function that does in-place operation inside? Is the behavior mentioned somewhere in the doc?

Thanks,

_Originally posted by @xyshell in https://github.com/pydantic/pydantic/issues/8165#issuecomment-2381601386_

**Comment by sydney-runkle** [comment]
Hi @xyshell,

Thanks for the question. From our [migration guide](https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel):

> In many cases, arguments passed to the constructor will be copied in order to perform validation and, where necessary, coercion. This is notable in the case of passing mutable objects as arguments to a constructor. You can see an example + more detail [here](https://docs.pydantic.dev/latest/concepts/models/#attribute-copies).

This applies to `validate_call` as well. I would say if you do want to do in place mutation of a type, but still want to validate said value, you'd be best suited to use a custom validator for said type to avoid the copying.

**Comment by xyshell** [comment]
@sydney-runkle got it. thanks for the speedy response. ;）
