### ISSUE TITLE
Annotated field schemas broken after v2.9.0

### ISSUE THREAD

**Issue by MarkusSintonen** [pydantic/pydantic#10528]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Following example shows how `Annotated` fields lost their schema `type` and `format` after v2.9.0

I can not see a mention of a such breaking change in changelog.

### Example Code

```Python
from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, PlainValidator

class Model(BaseModel):
    my_field: Annotated[datetime, PlainValidator(lambda v: v)]

# In v2.8.2 this is correct
# {'format': 'date-time', 'title': 'My Field', 'type': 'string'}
# In v2.9.0 type information is lost. Also in latest v2.9.2
# {'title': 'My Field'}
print(Model.model_json_schema()["properties"]["my_field"])
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.12.4 (main, Jun 18 2024, 13:47:41) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: fastapi-0.115.0 mypy-1.11.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Hi @MarkusSintonen,

Turns out this was an oversight when we implemented https://github.com/pydantic/pydantic/issues/8208 through https://github.com/pydantic/pydantic/pull/10094.

We expected JSON Schemas for fields with `PlainValidator` to _not_ work until today. For instance, the following was failing (see https://github.com/pydantic/pydantic/issues/7957):

```python
from typing_extensions import Annotated

from pydantic import BaseModel, PlainValidator

MyInt = Annotated[int, PlainValidator(lambda v: int(v) + 1)]

class Model(BaseModel):
    a: MyInt

print(Model(a='1').a)
print(Model(a='1').model_json_schema())  # error
```

However, given your example, it seems that some specific types (`datetime`, probably `pathlib.Path`) had custom json schema update functions injected in the core schema, meaning it would not fail.

In 2.9, all the validator classes (except `AfterValidator`) gained a new `json_schema_input_type` parameter. Because `PlainValidator` is the only one not caring about the annotated type, this parameter defaults to `Any`, so that you can still generate a JSON Schema.

Given that Sydney also did changes in the json schema update functions for 2.9, trying to fix the breaking change is going to be tricky. I assume your plain validator function is doing more complex stuff than a noop operation; you can use the `json_schema_input_type` to describe the types it is supposed to take:

```python
class Model(BaseModel):
    my_field: Annotated[datetime, PlainValidator(lambda v: v, json_schema_input_type=datetime)]
```

**Comment by MarkusSintonen** [comment]
> In 2.9, all the validator classes (except AfterValidator) gained a new json_schema_input_type parameter. Because PlainValidator is the only one not caring about the annotated type, this parameter defaults to Any, so that you can still generate a JSON Schema.

@Viicos can not it take the type from the Annotated type given by the user? So we wouldnt need to double define the types?

**Comment by MarkusSintonen** [comment]
Should be probably somehow better documented or deprecated the implicit Any usage with the PlainValidator. I don't think that implicit behavior makes much sense

**Comment by sydney-runkle** [comment]
> @Viicos can not it take the type from the Annotated type given by the user? 

The idea here is that many users use before validator functions to transform a type into the annotated type (think, custom `str` -> `datetime` logic), and thus it doesn't make sense to infer the input type if a before or wrap validator is used.

> But interesting that datetime just happened to work....

Yeah, we had some poor schema building practices internally for a few types that we attempted to clean up for v2.9. That came at the cost of this one unexpected JSON schema behavior, I suppose.

**Comment by Viicos** [comment]
> @Viicos can not it take the type from the Annotated type given by the user? So we wouldnt need to double define the types? Thats quite a boilerplate there. But interesting that datetime just happened to work....

Indeed although in most cases I assume you are not using plain validators with noop functions (as Sydney mentioned you usually cast from one type to another).

**Comment by MarkusSintonen** [comment]
> Indeed although in most cases I assume you are not using plain validators with noop functions

Nooo, it was just an example. In reality there were additional checks eg to see that datetimes were nothing non sensical (eg data from 1970)

**Comment by Viicos** [comment]
> Nooo, it was just an example. In reality there were additional checks eg to see that datetimes were nothing non sensical (eg data from 1970), etc etc checks

In that case, is there a reason not to use `AfterValidator`? You let Pydantic validate the type, and you perform additional validation (without having to worry about the fact that the input type might not be a `datetime`, or it might even be a string that will be coerced to a `datetime` by [`speedate`](https://github.com/pydantic/speedate), etc).

**Comment by MarkusSintonen** [comment]
> In that case, is there a reason not to use AfterValidator?

It wouldnt work IIRC as Pydantic would allow dates (`YYYY-MM-DD`) which we dont want in this case

**Comment by Viicos** [comment]
Hum I see, a `WrapValidator` could be useful in that case I believe.

**Comment by MarkusSintonen** [comment]
> Hum I see, a `WrapValidator` could be useful in that case I believe.

I see, I'll try that later! Does it then work better with json schemas without having to separately define the type?

**Comment by sydney-runkle** [comment]
It should :)

```py
from datetime import datetime
from typing import Annotated
from pydantic import BaseModel, WrapValidator

class Model(BaseModel):
    my_field: Annotated[datetime, WrapValidator(lambda v, h: h(v))]

print(Model.model_json_schema()["properties"]["my_field"])
#> {'format': 'date-time', 'title': 'My Field', 'type': 'string'}
```

**Comment by MarkusSintonen** [comment]
> It should :)

Thanks it works, changed to using WrapValidator instead. Good to document or fix the weird inconsistency with the PlainValidator.
