### ISSUE TITLE
BaseModel.construct slower than doing validation

### ISSUE THREAD

**Issue by basnijholt** [pydantic/pydantic#10536]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Turns out that validation in our code base is taking a signification chunk of the time, so I proposed to use `.model_construct(...)` whenever validation is not needed. Surprisingly, after doing some simple benchmarks, it seems construct is actually slower.

In the docs I read:

> pydantic also provides the construct() method which allows models to be created without validation this can be useful when data has already been validated or comes from a trusted source and you want to create a model as efficiently as possible (construct() is generally around 30x faster than creating a model with full validation).

I am observing that it is 5x slower in a micro benchmark (below).

### Example Code

```Python
from dataclasses import dataclass

@dataclass
class A:
    x: int
    y: int

from pydantic import BaseModel

class B(BaseModel):
    x: int
    y: int

%timeit A(x=1, y=2)
%timeit B(x=1, y=2)
%timeit B.model_construct(x=1, y=2)
```
which prints:
```
136 ns ± 3.77 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
549 ns ± 27.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.54 μs ± 19.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

### Python, Pydantic & OS Version

```Text
at 10:25:23 ❯ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/bas.nijholt/micromamba/envs/myenv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: fastapi-0.113.0 typing_extensions-4.12.2
                       commit: unknown
```
```

**Comment by Viicos** [comment]
You are mixing V1 documentation with V2 code. See the updated [docs section](https://docs.pydantic.dev/dev/concepts/models/#creating-models-without-validation) for V2.
