### ISSUE TITLE
✨ Add IDE support for autocompletion of fields created by `create_model`

### ISSUE THREAD

**Issue by jd-solanki** [pydantic/pydantic#10540]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hi 👋🏻 

I'm building lib for FastAPI users that goes over SQLAlchemy model and generates [Pydantic model for query params](https://fastapi.tiangolo.com/tutorial/query-param-models/). However, When I generate model using `create_model` and try to access the params my IDE (VSCode) is not aware of such fields like with static model.

Here's minimal example from docs:
```py
from pydantic import create_model

DynamicFoobarModel = create_model("DynamicFoobarModel", foo=(str, ...), bar=(int, 123))

foo_bar = DynamicFoobarModel(foo="hello", bar=123)
print(foo_bar.__annotations__)
print(foo_bar.foo) # 🚨 Cannot access attribute "foo" for class "BaseModel"
```

![image](https://github.com/user-attachments/assets/c668db47-7e3d-4da3-a8d3-c6e84972aa17)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
This won't be possible with the existing typing constructs as of today. Pyright (the type checker used by Pylance) does not provide any plugin functionality so we can't do much here.
