### ISSUE TITLE
Type IPv4Address not json dumped if in dict

### ISSUE THREAD

**Issue by FedericoHeichou** [pydantic/pydantic#10559]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If the IP is inside a dict, when you try to dump it to json it will raise:  
`pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'ipaddress.IPv4Address'>`.

I found out trying to dump a dict in a model with fastapi's `jsonable_encoder`.  
Related to #8942

### Example Code

```Python
from ipaddress import IPv4Address

from pydantic import BaseModel
from pydantic.networks import IPvAnyAddress


class IpModel(BaseModel):
    ip: IPvAnyAddress = IPv4Address("127.0.0.1")


class Dicted(BaseModel):
    some_dict: dict


print('Works: ',  IpModel().model_dump(mode='json'))
print('Does not: ', Dicted(some_dict={'ip': IPv4Address("127.0.0.1")}).model_dump(mode='json'))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/user/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
                     platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2 pydantic-settings-2.5.2 fastapi-0.115.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @FedericoHeichou,

You can do the following:

```py
class Dicted(BaseModel):
    some_dict: dict[str, IPv4Address]
```

To ensure that the data is dumped correctly. `pydantic-core` inference doesn't handle IP types, so you'll have to clue the model into the type that you're trying to dump here. Going to mark as resolved for now.

**Comment by FedericoHeichou** [comment]
I think I will go with 
```
class Dicted(BaseModel):
    some_dict: dict[Any, Any | IPvAnyAddress]
```

It is strange because in old versions it worked... Maybe it was in the v1

**Comment by FedericoHeichou** [comment]
Just for an update: I changed the type
```
class Dicted(BaseModel):
    some_dict: dict[Any, Any | str | int | float | IPvAnyAddress]
```
Because if you pass an int it will be converted in an IP.  
For example `503` become `0.0.1.247`
