### ISSUE TITLE
Add 'validate_assignment' context manager to BaseModel for on demand validation of assignments

### ISSUE THREAD

**Issue by mee7ya** [pydantic/pydantic#10563]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It's possible that models are stored in separate library, potentially auto generated (hence, we try to avoid adding manual code to models), shared across multiple services. In that case, if you're in need of assignments' validation it'd require you to set the flag globally, which potentially could break other services, or override config locally, which is not "beautiful" solution. It's possible to add context manager to temporarily switch `'validate_assignment'` to true, perform assignments that require validation, and switch back.

```python
from contextlib import contextmanager
from typing import TYPE_CHECKING

from pydantic import BaseModel, ValidationError

if TYPE_CHECKING:
    from typing import ContextManager


class MyModel(BaseModel):
    this_is_integer: int

    @contextmanager
    def validate_assign(self) -> 'ContextManager[MyModel]':
        old_value = self.model_config.get('validate_assignment', False)
        self.model_config['validate_assignment'] = True
        yield self
        self.model_config['validate_assignment'] = old_value


my_model = MyModel(
    this_is_integer=1
)

my_model.this_is_integer = 'a'
# No raise

with my_model.validate_assign():
    try:
        my_model.this_is_integer = 'b'
    except ValidationError:
        pass
        # pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
        # this_is_integer
        #   Input should be a valid integer, unable to parse string as an integer
        #   [type=int_parsing, input_value='not integer', input_type=str]

my_model.this_is_integer = 'c'
# No raise
```
Could be helpful for https://github.com/pydantic/pydantic/issues/1864#issuecomment-2145539155

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [x] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @mee7ya,

Thanks for your question.

I think this is probably a pattern that belongs in user code. You might even consider generalizing this context manager to something like the following:

```py
from contextlib import contextmanager
from typing import TYPE_CHECKING, Generator, Type

from pydantic import BaseModel, ValidationError

if TYPE_CHECKING:
    pass


class MyModel(BaseModel):
    this_is_integer: int


@contextmanager
def set_class_config(cls: Type[BaseModel], setting_name: str, new_value: bool) -> Generator[None, None, None]:
    """Context manager to temporarily set a config setting on the class."""
    old_value = getattr(cls.model_config, setting_name, None)
    cls.model_config[setting_name] = new_value
    yield
    cls.model_config[setting_name] = old_value


# Testing the validation behavior
my_model = MyModel(this_is_integer=1)

my_model.this_is_integer = 'a'  # No raise

with set_class_config(MyModel, 'validate_assignment', True):
    try:
        my_model.this_is_integer = 'b'
    except ValidationError:
        pass
        # ValidationError will be raised here

my_model.this_is_integer = 'c'  # No raise
```

I'll note, you probably want to handle the getattrs (with defaults) and setattrs more carefully in the context manager, but this general pattern should work ok.

I wouldn't say I'd necessarily endorse this (hence my hesitance to have us support this within the lib), though hopefully this serves as a satisfactory workaround for you.
