### ISSUE TITLE
some the type annotations in `_typing_extra` are wrong

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10577]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

there are a lot of `type_params: tuple[Any]` which should be `type_params: tuple[Any, ...]`

### Python, Pydantic & OS Version

```Text
main branch
```

**Comment by sydney-runkle** [comment]
@Viicos is fixing these in https://github.com/pydantic/pydantic/pull/10530.

Thanks for pointing this out!
