### ISSUE TITLE
`dict(model)` errors when field name `keys` exists

### ISSUE THREAD

**Issue by zzstoatzz** [pydantic/pydantic#10575]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A user of ours opened [this](https://github.com/PrefectHQ/prefect/issues/15610) issue, which appeared to show that dumping a model with `dict(...)` breaks if you have field on the model whose name is literally `keys` - which I was able to reproduce.

This error was certainly unexpected to me - I couldn't find an open or closed related issue, but apologies if I'm missing something. I couldn't immediately find a fix for this looking at `BaseModel.__iter__` and a bit elsewhere, but will come back to this to try and add a fix later.

### Example Code

```Python
from pydantic import BaseModel

errored = False


class A(BaseModel):
    keys: str


a = A(keys="hello")

assert a.model_dump() == {"keys": "hello"}

try:
    dict(a)
except TypeError as exc:
    errored = True
    assert "'str' object is not callable" in str(exc)
    print(f"`dict(A(keys='hello'))` errored with {exc}")

assert errored
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/nate/github.com/prefecthq/prefect/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: fastapi-0.115.0 mypy-1.11.2 pydantic-extra-types-2.9.0 pydantic-settings-2.5.2 typing_extensions-4.12.2
                       commit: unknown

```

**Comment by Viicos** [comment]
Hello @zzstoatzz,

you are hitting an annoying Python behavior reported [here](https://github.com/python/cpython/issues/116938). I'm going to try to update the Python documentation because the behavior is probably going to stay the same.

As a workaround (which I'm going to document in the Pydantic documentation), you can call `dict(iter(model))`.

**Comment by sydney-runkle** [comment]
Closing for now, I think this issue represents good enough documentation of this problem + workaround. Thanks @Viicos!

**Comment by zzstoatzz** [comment]
thanks for the info @Viicos - sounds good! 👍

**Comment by Viicos** [comment]
Docs PR, hopefully this will be clarified: https://github.com/python/cpython/pull/125213
