### ISSUE TITLE
Misleading behavior using `exclude_unset=True` option

### ISSUE THREAD

**Issue by jotare** [pydantic/pydantic#10574]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! I recently found a weird behavior while serializing a model with and without `exclude_unset=True`.

According to the docs, `exclude_unset` decides "whether fields which were not explicitly set when creating the model should be excluded from the returned dictionary". But the real condition for a field to be set/unset is a field assignment (at any moment).

As an example, given the following model:
```python
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    field: list[int] = Field(default_factory=list)
```
one can set `field` in three different ways: 

On initialization:
```python
model = MyModel(field=[1])
print(model.model_dump(exclude_unset=True))
# > {'field': [1]}
```

Using an assignment:
```python
model = MyModel()
model.field = [1]
print(model.model_dump(exclude_unset=True))
# > {'field': [1]}
```

Or modifying the list in place:
```python
model = MyModel()
model.field.append(1)
print(model.model_dump(exclude_unset=True))
# > {}
```

Why does the modification in place hide `field`, while an assignment doesn't? If the criteria to be set/unset is to be set in the model creation, the assignment shouldn't serialize the field. But if set/unset is any modification of the field, the 3rd snipped should also serialize the value.

I've created this as a bug but maybe it's not. At least, I think documentation could be more clear around this.

Thanks for your time!

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /tmp/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
                     platform: Linux-6.1.0-23-amd64-x86_64-with-glibc2.36
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hmm, definitely a bit inconsistent here. Will chat with the team and see if this has to wait until V3.

**Comment by jotare** [comment]
Okay, thanks! Let me know if I can contribute to the changes, I'm looking forward to help :)

**Comment by sydney-runkle** [comment]
Chatted with the team - this would require creating new wrappers for mutable types, which doesn't fall under the scope of our work. The maintenance burden is too high here.

If you are seeking a bit more consistency here, I'd recommend just making sure you use `setattr` which will trigger the `model_fields_set` update that guides the behavior of `exclude_unset`.

**Comment by sydney-runkle** [comment]
See https://github.com/pydantic/pydantic/issues/496 for some more historical context :)

**Comment by jotare** [comment]
Thanks @sydney-runkle, make sense not to implement a fix for it.

However, do you think we could change a bit the doc to be more clear? Changing the current 
"whether fields which were not explicitly set _when creating the model_ should be excluded from the returned dictionary" 
to something like:
"whether fields which where not explicitly set _at any time_, should be excluded from the returned dictionary"

I can do the change if you want
