### ISSUE TITLE
Support Python 3.13's new `__replace__` protocol.

### ISSUE THREAD

**Issue by theacodes** [pydantic/pydantic#10573]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hello! Python 3.13 added [new features](https://docs.python.org/3.13/whatsnew/3.13.html#copy) to the `copy` module, specifically `copy.replace()` and the *replace protocol*.

It would be lovely to see Pydantic implement the `__replace__` method for `BaseModel`, allowing models to be used with `copy.replace()`. Pydantic already supports `copy.copy()` (via `BaseModel.__copy__`) and `copy.deepcopy()` (via `BaseModel.__deepcopy__`). This would largely be an alias to `model_copy()`.

Example usage:

```python
import copy
from pydantic import BaseModel

class MyModel(BaseModel):
    name: str
    color: str


a = MyModel(name="a", color="blue")
b = copy.replace(a, color="red')

print(a)
# MyModel(name='a', color='blue')

print(b)
# MyModel(name='a', color='red')

```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
I've opened a PR adding support for this that'll land in v2.10!

**Comment by theacodes** [comment]
Awesome, thank you!
