### ISSUE TITLE
(🐞) implementing an abstract property results in a couple of issues

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#10587]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

i want to make abstract base classes for models, but it doesn't integrate smoothly

i use an abstract property, because type checkers don't have any methodology to declare abstract attributes

### Example Code

```Python
from abc import ABC, abstractmethod

from pydantic import BaseModel


class A(BaseModel, ABC):
    @property
    @abstractmethod
    def f(self) -> int: ...


class B(A):
    f: int  # UserWarning: Field name "f" in "B" shadows an attribute in parent "A"

B(f=1)  # TypeError: Can't instantiate abstract class B without an implementation for abstract method 'f'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by KotlinIsland** [comment]
> This is also going against the type checker which errors on the f field.

huh? no it doesn't

**Comment by Viicos** [comment]
![image](https://github.com/user-attachments/assets/c26a683a-c195-4892-95da-d6a68be51c11)

**Comment by KotlinIsland** [comment]
ahh I understand, I think that's where pyright and mypy differ. I understand that there isn't a typing consensus on the topic of abstract classes/attributes, so your position is fair

**Comment by Viicos** [comment]
Yeah I'm wondering if this is described in the spec or not. But I doubt such a use case will be supported, properties don't behave the same as normal attributes (setters/deleters can be present, class access returns the underlying property descriptor instance, etc) so the following becomes unsafe:

```python

class A(BaseModel, ABC):
    @property
    @abstractmethod
    def f(self) -> int: ...

def func(a: type[A]):
    a.f.fget

class B(A):
    f: int  # UserWarning: Field name "f" in "B" shadows an attribute in parent "A"

func(B)
```

**Comment by KotlinIsland** [comment]
yeah, it's an absolute nightmare, were doing a lot of work in basedpyright to address the shortcomings of `abc`

**Comment by KotlinIsland** [comment]
# Workaround
```py
class Interface(ABC):
    if TYPE_CHECKING:
        @property
        def f() -> str: ...
class Implementation(BaseModel, Interface):
    f: str
```
