### ISSUE TITLE
model_validate using Generic BaseModel with TypeVar

### ISSUE THREAD

**Issue by jrs53** [pydantic/pydantic#10583]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm working on a class (`PayloadWrapper`) that essentially wraps a series of Pydantic model (`Payload` in my example) inside another Pydantic model (`WrappedPayload`). I'm trying to make this generic by providing the type of the model to be wrapped (`T`). 

Wrapping the model (`PayloadWrapper.wrap`) seems to work fine, but when I try to unwrap (`PayloadWrapper.unwrap`) if I use the type parameter (`T`) to `model_validate`, I find the output is a plain Dict, not of the specified type. If I specify the correct concrete type (`Payload`) I get the expected result, but of course I won't know this concrete type in the generic class.

I can pass the concrete class as a param (which seems to work) but not sure that's the best approach.

Any help much appreciated.

### Example Code

```Python
from pydantic import BaseModel
from typing import Generic, TypeVar
 
T = TypeVar("T")
# T = TypeVar("T", bound=BaseModel) 

class WrappedPayload(BaseModel, Generic[T]):
    payload: T 

class Payload(BaseModel):
    name: str

class PayloadWrapper(Generic[T]):
 
    def wrap(self, payload: T): 
        wp = WrappedPayload[T](payload = payload)
        print(wp.model_dump())

    def unwrap(self, data: dict, payload_model: BaseModel):
        print(WrappedPayload[T].model_validate(data))
        print(WrappedPayload[Payload].model_validate(data))
        print(WrappedPayload[payload_model].model_validate(data))

p = Payload(name="James")
pw = PayloadWrapper[Payload]()
pw.wrap(p)

# {'payload': {'name': 'James'}}

data = {'payload': {'name': 'James'}}
pw.unwrap(data)
# payload={'name': 'James'} OR payload=BaseModel() if T bound to BaseModel
# payload=Payload(name='James')
# payload=Payload(name='James')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
pydantic-core version: 2.23.4
pydantic-core build: profile=release pgo=false
install path: /opt/anaconda3/envs/jupyter/lib/python3.11/site-packages/pydantic
python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:10:28) [Clang 15.0.7 ]
platform: macOS-14.7-x86_64-i386-64bit
related packages: typing_extensions-4.7.1
commit: unknown
```

**Comment by Viicos** [comment]
Your code example is invalid as is: it is missing the `payload` argument, but I assume you meant to pass the `Payload` class.

---

Generics and type vars are primarily designed for static type checking purposes. When you do the following:

```python
class PayloadWrapper(Generic[T]):
    def meth(self):
        print(T)

PayloadWrapper[int]().meth()
```
it doesn't print `int` but `T`, unchanged. This means that at runtime, `WrappedPayload[T]` inside `wrap()` is still `WrappedPayload[T]`, not `WrappedPayload[int]` as your type checker infers.

Related thread: https://github.com/python/typing/issues/629.

**Comment by jrs53** [comment]
Sorry, I was copying between systems and forgot to update the code sample - you are correct, `Payload` should have been passed to the `unwrap` call (edited now).

Thanks very much for the explanation
