### ISSUE TITLE
model_dump() does not include Python object for IP addresses

### ISSUE THREAD

**Issue by jderuiter** [pydantic/pydantic#10589]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Since version 2.9.0, model_dump() does not seem to include a Python object for IP addresses anymore but instead includes the string representation.

### Example Code

```Python
import ipaddress
from pydantic import BaseModel

class Address(BaseModel):
    ip: ipaddress.IPv4Address

a = Address(ip="127.0.0.1")
print(a.model_dump())

# 2.8.2: {'ip': IPv4Address('127.0.0.1')}
# 2.9.2: {'ip': '127.0.0.1'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
                     platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.39
             related packages: mypy-1.11.2 pydantic-settings-2.5.2 typing_extensions-4.12.2 fastapi-0.115.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @jderuiter,

Thanks for your question. Looks like this changed in https://github.com/pydantic/pydantic/pull/10112. Looking into a fix now.

**Comment by sydney-runkle** [comment]
Opened a PR with a fix :).

**Comment by jderuiter** [comment]
Great! That was fast :)

**Comment by sydney-runkle** [comment]
We can probably do a patch release with this fix (v2.9.3), or if you're in no rush, we could wait until v2.10, which we'll do in a few weeks. Can also install from `main` in the meantime once we merge.

**Comment by jderuiter** [comment]
There is no rush for me, so whatever works best for you. I'll just stick with v2.8.2 until the fix is released.

**Comment by sydney-runkle** [comment]
Awesome, we'll include with v2.10 then. Thanks for reporting this!
