### ISSUE TITLE
Defining `Pydantic` model examples in `model_config` significantly slows down `MyPy` runs for complicated models

### ISSUE THREAD

**Issue by adam-sikora** [pydantic/pydantic#10580]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Running `MyPy` on the script provided below is taking ~32s on my machine. This is simply a ridiculously long time and it seems to be caused by the deeply nested example. When I leave the `examples` array empty then the run takes ~6s which is understandable as `MyPy` has to understand entire `Pydantic` package. When the example is less complicated (meaning less deeply nested) then the slow down is not as extensive.

Command used to run the script: `mypy --no-incremental --config-file="" script.py`

Any idea why this slow down happens and how to mitigate it? We recently started using examples for our APIs and this made our `MyPy` runs unbearably slow.

### Example Code

```Python
from pydantic import BaseModel


class A(BaseModel):
    model_config = {
        "json_schema_extra": {
            "examples": [{"a": {"b": {"c": {"d": [[[[[[[], [], [], []]]]]]]}}}}]
        }
    }
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
                     platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
             related packages: fastapi-0.115.0 mypy-1.11.2 typing_extensions-4.10.0
```

**Comment by Viicos** [comment]
The above code is equivalent to:

```python
from typing import Any, Callable, ClassVar, Dict, List, Type, TypeAlias, TypedDict, Union

JsonValue: TypeAlias = Union[int, float, str, bool, None, List['JsonValue'], 'JsonDict']
JsonDict: TypeAlias = Dict[str, JsonValue]

JsonSchemaExtraCallable: TypeAlias = Union[
    Callable[[JsonDict], None],
    Callable[[JsonDict, Type[Any]], None],
]


class ConfigDict(TypedDict, total=False):
    json_schema_extra: JsonDict | JsonSchemaExtraCallable | None


class BaseModel:
    model_config: ClassVar[ConfigDict]


class A(BaseModel):
    model_config = {'json_schema_extra': {'examples': [{'a': {'b': {'c': {'d': [[[[[[[], [], [], []]]]]]]}}}}]}}
```

The reason it takes so much time to type check is that `json_schema_extra` is defined as a recursive union type, and mypy struggles to type check efficiently.

Alternatively, you can define the examples separately:

```python
my_examples: JsonValue = [{'a': {'b': {'c': {'d': [[[[[[[], [], [], []]]]]]]}}}}]

class A(BaseModel):
    model_config = {'json_schema_extra': {'examples': my_example}}
```

**Comment by adam-sikora** [comment]
@Viicos thanks for the explanation and for providing the workaround.

The workaround works fine, however it is a little inconvenient having to define the examples outside of the class definition. Can you think of a way how to keep it inside the class?

```
class MyModel(BaseModel):
    examples: ClassVar[list[JsonValue]] = []
    model_config = {
        'json_schema_extra': {
            'examples': cls.examples  # This obviously does not work, but is there a way how to achieve this?
        }
    }

class A(MyModel):
     examples = [{'a': {'b': {'c': {'d': [[[[[[[], [], [], []]]]]]]}}}}]
```

**Comment by Viicos** [comment]
`json_schema_extra` can be a callable:

```python
def get_extra(schema, cls):
    schema['examples'] = cls.examples

class MyModel(BaseModel):
    examples: ClassVar[list[JsonValue]] = []
    model_config = {
        'json_schema_extra': get_extra
    }

class A(MyModel):
     examples = [{'a': {'b': {'c': {'d': [[[[[[[], [], [], []]]]]]]}}}}]
```

Let me know if this works, I haven't tested it.

Closing for now, thanks for reporting!

**Comment by adam-sikora** [comment]
@Viicos the suggested workaround with callable inside `json_schema_extra` works well for us. Thanks for the help
