### ISSUE TITLE
[Docs] Page on postponed annotations is confusing (example doesn't actually contain postponed annotations?)

### ISSUE THREAD

**Issue by ldorigo** [pydantic/pydantic#10591]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

https://docs.pydantic.dev/latest/concepts/postponed_annotations/ This doc page is a bit confusing - I might be confused, but the initial section doesn't actually contain anything that requires postponed annotations? What is it trying to show? 

### Python, Pydantic & OS Version

```Text
Irrelevant
```

**Comment by Viicos** [comment]
The example is pretty contrived as it indeed does not require stringified annotations to work. I'm in the process of writing docs for our forward annotations evaluation logic, so I'm going to tackle this at the same time (https://github.com/pydantic/pydantic/pull/10592).
