### ISSUE TITLE
When overriding __init__ with enclosed generic classes pydantic raises spurious validation errors

### ISSUE THREAD

**Issue by reversefold** [pydantic/pydantic#10598]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a use case where I'm using python generics (`typing.Generic`) with pydantic models which are nested and where the nesting model has a custom `__init__` function which instantiates the nested model. I think the issue may somehow be with the generic code using the generic `typing.TypeVar` to instantiate rather than the concrete class, but I have been unable to figure out how to debug this as the traceback never actually goes down to the place where the exception is raised. This will be easier to explain with a working example, I think:
```python
import typing

import pydantic


GC = typing.TypeVar("GC", bound=pydantic.BaseModel)


class EnclosedGeneric(pydantic.BaseModel, typing.Generic[GC]):
    version: int
    model: GC


class EnclosingGeneric(pydantic.BaseModel, typing.Generic[GC]):
    enclosed: EnclosedGeneric[GC]


class EnclosingGenericWithInit(pydantic.BaseModel, typing.Generic[GC]):
    def __init__(self, version: int, model: GC):
        super().__init__(enclosed=EnclosedGeneric[GC](version=version, model=model))

    enclosed: EnclosedGeneric[GC]
```
When using `EnclosingGeneric` everything works as expected.
```python
class ConcreteModel(pydantic.BaseModel):
    field: str

EnclosingGeneric[ConcreteModel](
    enclosed=EnclosedGeneric[ConcreteModel](version=1, model=ConcreteModel(field="val"))
)
```
However, when using `EnclosingGenericWithInit`:
```python
EnclosingGenericWithInit[ConcreteModel](version=1, model=ConcreteModel(field="val"))
```
I get the following exception:
```
Traceback (most recent call last):
  File "/Users/julia.patrin/src/sa-8078-solution-accelerator-framework/pydantic-generics.py", line 32, in <module>
    EnclosingGenericWithInit[ConcreteModel](version=1, model=ConcreteModel(field="val"))
  File "/Users/julia.patrin/src/sa-8078-solution-accelerator-framework/pydantic-generics.py", line 20, in __init__
    super().__init__(enclosed=EnclosedGeneric[GC](version=version, model=model))
  File "/Users/julia.patrin/src/sa-8078-solution-accelerator-framework/.venv/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for EnclosingGenericWithInit[ConcreteModel]
enclosed
  Input should be a valid dictionary or instance of EnclosedGeneric[ConcreteModel] [type=model_type, input_value=EnclosedGeneric(version=1...creteModel(field='val')), input_type=EnclosedGeneric]
```

If I remove the generics entirely everything works fine:
```python
class Enclosed(pydantic.BaseModel):
    version: int
    model: pydantic.BaseModel


class Enclosing(pydantic.BaseModel):
    enclosed: Enclosed


class EnclosingWithInit(pydantic.BaseModel):
    def __init__(self, version: int, model: pydantic.BaseModel):
        super().__init__(enclosed=Enclosed(version=version, model=model))

    enclosed: Enclosed


Enclosing(enclosed=Enclosed(version=1, model=ConcreteModel(field="val")))
EnclosingWithInit(version=1, model=ConcreteModel(field="val"))
```

I did find a workaround which works with the generics, and that is passing in a dictionary instead of a concrete class in the custom `__init__` method, but that seems like a hack:
```python
class EnclosingGenericWithInitWorkaround(pydantic.BaseModel, typing.Generic[GC]):
    def __init__(self, version: int, model: GC):
        super().__init__(enclosed={"version": version, "model": model})

    enclosed: EnclosedGeneric[GC]

EnclosingGenericWithInitWorkaround[ConcreteModel](version=1, model=ConcreteModel(field="val"))
```

### Example Code

```Python
import typing

import pydantic


GC = typing.TypeVar("GC", bound=pydantic.BaseModel)


class EnclosedGeneric(pydantic.BaseModel, typing.Generic[GC]):
    version: int
    model: GC

class EnclosingGenericWithInit(pydantic.BaseModel, typing.Generic[GC]):
    def __init__(self, version: int, model: GC):
        super().__init__(enclosed=EnclosedGeneric[GC](version=version, model=model))

    enclosed: EnclosedGeneric[GC]


class ConcreteModel(pydantic.BaseModel):
    field: str


EnclosingGenericWithInit[ConcreteModel](version=1, model=ConcreteModel(field="val"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/.../.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Sep 19 2023, 17:11:25) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-15.0-arm64-arm-64bit
             related packages: mypy-1.11.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by kosiew** [comment]
hi @reversefold ,

> pydantic models which are nested and where the nesting model has a custom __init__ function which instantiates the nested model

Have you considered using [__post_init__](https://docs.pydantic.dev/latest/concepts/dataclasses/#initialization-hooks)?

**Comment by Viicos** [comment]
Hi @reversefold,

See https://github.com/pydantic/pydantic/issues/10583 for an explanation of why this fails.

**Comment by reversefold** [comment]
I'm not sure what `post_init` would have to do with this, this is a simple matter of instantiating an enclosed class in an init method.

#10583 Only gives a pointer, it doesn't really explain the problem or the solution. The really confusing part of all of this is that the code as given above passes all type checks but only fails *at runtime* in pydantic validation. It's not clear what the correct course of action is here.

It appears that changing the init method to refer to the type of the passed in model object makes pydantic happy but type checkers now fail, which is the whole point of using generics:
```python
class EnclosingGenericWithInit(pydantic.BaseModel, typing.Generic[GC]):
    def __init__(self, version: int, model: GC):
        super().__init__(enclosed=EnclosedGeneric[type(model)](version=version, model=model))

    enclosed: EnclosedGeneric[GC]
```
mypy fails with an error about the value in the square brackets not being a type, necessitating adding `# type: ignore` to force static type checkers to be happy.

It seems like there should be a solution here that works for both static type checking and for pydantic.

**Comment by Viicos** [comment]
The runtime behavior does not always reflect the static type checking mechanisms.

Taking a simpler example:

```python
from typing import Generic, TypeVar

T = TypeVar("T")

class Class(Generic[T]):
    def __init__(self):
        print(T)
```

What you expected here is that doing `Class[str]()` will print `<class 'str'>`, but you instead get the `T` type var instance printed out. Python does not "replace" type vars instances inside the body of the class when parametrized (and it can't do so anyway).

using `type(model)` is the way to go, but you'll have to ignore the type checker error here unfortunately.

**Comment by reversefold** [comment]
I'm not necessarily expecting Python to print out the class that the generic TypeVar is standing in for in that case, I do understand that Python's type hinting and Generics are not a full runtime type system like in, say, Java. What I do expect is for the type checking tools to work properly with these mechanisms. Which is does. Take the example of these non-pydantic classes:
```python
import typing

GCP = typing.TypeVar("GCP")

class ConcreteModelPy:
    def __init__(self, field: str):
        self.field: str = field

class EnclosedGenericPy(typing.Generic[GCP]):
    def __init__(self, version: int, model: GCP):
        self.version: int = version
        self.model: GCP = model

class EnclosingGenericWithInitPy(typing.Generic[GCP]):
    def __init__(self, version: int, model: GCP):
        self.enclosed: EnclosedGenericPy[GCP] = EnclosedGenericPy[GCP](version=version, model=model)

EnclosingGenericWithInitPy[ConcreteModelPy](version=1, model=ConcreteModelPy(field="val"))
EnclosingGenericWithInitPy(version=1, model=ConcreteModelPy(field="val"))
```
mypy and python are both perfectly happy with this code. It passes static type checks and runs at runtime with no issues. The issue is that pydantic is not accepting something that mypy does accept and that seems like a violation of the contract that pydantic makes with the typing system. Instead of allowing code to pass static type checks we are required in this case to silence the static type check to make pydantic happy.

How is pydantic introspecting the type that has replaced the Generic at runtime? How does it know whether it's a TypeVar or not? Couldn't pydantic be modified to allow for a use-case like this which leaves the type checkers happy and still works at runtime fine?

**Comment by Viicos** [comment]
Ok I'm going to give you some technical details but I would suggest digging more on your side as well.

When doing `super().__init__(enclosed=EnclosedGeneric[GC](version=version, model=model))` _at runtime_, Python calls the `__class_getitem__` class method of `EnclosedGeneric`.

[`__class_getitem__`](https://docs.python.org/3/reference/datamodel.html#object.__class_getitem__) was originally designed for `typing.Generic` (and naturally `Generic` implements this method). Pydantic defines a custom `__class_getitem__` implementation so that whenever you parametrize a Pydantic model (i.e. doing `MyModel[SomeType]`), we actually create a new class and manually replace every type variable present in the class annotations.

The `__class_getitem__` method takes a single `key` argument, which may be a `tuple` if you parametrize a class with multiple arguments (e.g. `MyModel[int, str]`). In your case, we are calling `EnclosedGeneric[GC]`, so `key` will be the `GC` type variable instance, no matter if the parent class where this is happening (`EnclosingGenericWithInit`) was parametrized or not. This equivalent example might make things clearer:

```python
class EnclosingGenericWithInit(pydantic.BaseModel, typing.Generic[GC]):
    def __init__(self, version: int, model: GC):
        ParametrizedEnclosedGeneric = EnclosedGeneric.__class_getitem__(GC)
```

It's the same thing as calling a regular method.
