### ISSUE TITLE
Bump pydantic-core from v2.24.0 to v2.24.1 

### ISSUE THREAD

**Issue by return42** [pydantic/pydantic#10605]
@davidhewitt thanks for https://github.com/pydantic/pydantic-core/pull/1477 .. can we bump pydantic-core dependency to v2.24.1 

https://github.com/pydantic/pydantic/blob/76222d2e7ed90c13816dff1b71bc0f3cf3d7c018/pyproject.toml#L54

**Comment by sydney-runkle** [comment]
Working on it here: https://github.com/pydantic/pydantic/pull/10523
