### ISSUE TITLE
Upgrade to `uv` instead of `pdm`

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10637]
See references: https://github.com/astral-sh/uv

Also: https://github.com/pydantic/logfire/pull/480

**Comment by frfahim** [comment]
Hi @sydney-runkle I would like to work on this issue.

**Comment by purepani** [comment]
That was a pretty short wait

**Comment by frfahim** [comment]
Thanks for pointing it out, I was following the issue. It’s now released. Will continue the work.

**Comment by sydney-runkle** [comment]
@frfahim, any interest in helping us to do the same on `pydantic-core`?

**Comment by frfahim** [comment]
Yeah sure
