### ISSUE TITLE
add environment option to disable disable Pydantic validations

### ISSUE THREAD

**Issue by thomas-paul-ohara** [pydantic/pydantic#10641]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be good for the ability to disable Pydantic validations, such as via an environment setting. 

A lot of time can be spent tracking down Pydantic issues when upgrading code. Moreover, this places a burden when testing, such as when upgrading from version 1 to version 2. Although ultimately the code should be fixed, sometimes the code just needs to run.

This can be implemented transparently as sketched here:
```
$ git diff pydantic/main.py | grep '[+-]'
diff --git a/pydantic/main.py b/pydantic/main.py
--- a/pydantic/main.py
+++ b/pydantic/main.py
@@ -25,6 +25,8 @@ from typing import (
+from mezcla import debug, system
+
@@ -68,6 +70,8 @@ else:
     # and https://youtrack.jetbrains.com/issue/PY-51428
+IGNORE_PYDANTIC_ERRORS = system.getenv_bool("IGNORE_PYDANTIC_ERRORS", False)
+
@@ -210,7 +214,9 @@ class BaseModel(metaclass=_model_construction.ModelMetaclass):
-        validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
+        validated_self = self
+        if not IGNORE_PYDANTIC_ERRORS:
+            validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
@@ -970,7 +976,10 @@ class BaseModel(metaclass=_model_construction.ModelMetaclass):
-        raise pydantic_core.ValidationError.from_exception_data(self.__class__.__name__, [error])
+        if IGNORE_PYDANTIC_ERRORS:
+            debug.trace(2, f"Warning: validation error in {__pydantic_self__}")
+        else:
+            raise pydantic_core.ValidationError.from_exception_data(self.__class__.__name__, [error])
     def __getstate__(self) -> dict[Any, Any]:
@@ -1260,7 +1269,10 @@ class BaseModel(metaclass=_model_construction.ModelMetaclass):
-            raise pydantic_core.ValidationError.from_exception_data(cls.__name__, [error])
+            if IGNORE_PYDANTIC_ERRORS:
+                debug.trace(2, f"Warning: validation error in {__pydantic_self__}")
+            else:
+                raise pydantic_core.ValidationError.from_exception_data(self.__class__.__name__, [error])
```

A simple example follows:
```
$ simple_pydantic_example.py
...
         u2 = User(id="two", name="Jane Doe")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
...

$ IGNORE_PYDANTIC_ERRORS=1 python 
u1=User()
u2=User()
```
[simple_pydantic_example.py.txt](https://github.com/user-attachments/files/17406123/simple_pydantic_example.py.txt)

```
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/joe/virtual-environments/agvisor-py-3-12/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.7-arm64-arm-64bit
             related packages: typing_extensions-4.12.0 pydantic-settings-2.5.2 fastapi-0.104.1
                       commit: unknown
```

Of course, other changes would be needed to be complete. This is just to illustrate that it can be readily implemented.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
This won't play well if you use `.model_validate[_json]()`, because the data is a `dict`/string. If you are only using `BaseModel.__init__`, you can probably monkeypatch it:

```python

def new_init(self, /, **data):
    self.__dict__.update(data)

BaseModel.__init__ = new_init
```

**Comment by sydney-runkle** [comment]
I definitely agree with the decision to close this issue 👍

**Comment by thomas-paul-ohara** [comment]
An explicit model validation could generate an error if IGNORE_PYDANTIC_ERRORS is defined.

A monkey patch doesn't seem good, because it requires modifying the code. An environment variable is convenient, especially because this flag is only meant for adhoc usage.

Anyway, it seems better to close this as not-planned rather than completed.
