### ISSUE TITLE
Unstable behavior for warning `Failed to get discriminator value for tagged union serialization` ?

### ISSUE THREAD

**Issue by Danipulok** [pydantic/pydantic#10657]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

So after upgrading to `pydantic==2.9.2` we started getting `Failed to get discriminator value for tagged union serialization` warning.
I found the issue #10355 and that it was resolved by #10400.

But I have decided to open a new issue, since:
1. we don't use raw discriminator function as in #10355, we use `Field(discriminator="type")`
2. if we change the order of field types, we do not get a warning (please see example code below)

I just find it kinda strange that there's a warning depending on the field types order. 
Maybe remove warning at all or add to the documentation notes about the difference when changing type order?

### Example Code

```Python
from typing import Annotated, Literal
from pydantic import BaseModel, Field

class Cat(BaseModel):
    type: Literal["cat"]
    name: str

class Dog(BaseModel):
    type: Literal["dog"]
    name: str

type Pet = Annotated[Cat | Dog, Field(discriminator="type")]

class Foo(BaseModel):
    maybe_pet: Pet | str | None = None  # like this we get a warning
    # maybe_pet: str | Pet | None = None  # like this there's no warning

foo = Foo.model_validate({"maybe_pet": "hi"})
print(foo)
dumped = foo.model_dump()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: D:\Code\project\.venv\Lib\site-packages\pydantic
               python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.112.1 mypy-1.11.1 pydantic-settings-2.4.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Yeah, we should fix this. Thanks for bringing to our attention.

**Comment by sydney-runkle** [comment]
If anyone wants to get their hands dirty with some rust, this would be a good issue.

**Comment by sydney-runkle** [comment]
This has been partially resolved by https://github.com/pydantic/pydantic-core/pull/1513/files

**Comment by sydney-runkle** [comment]
Working on fixing fully in another PR now.
