### ISSUE TITLE
Add a config option to skip validation on certain types/fields

### ISSUE THREAD

**Issue by kc0506** [pydantic/pydantic#10663]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently, when users use a type annotation unsupported by Pydantic, they have to either give up annotating with that type or give up validating the whole model with Pydantic. The former will let them lose the powerful static analysis feature by language servers, and the latter will let them lose the runtime validation **completely**. There can be a compromise to this: why don't let users specify certain types/fields to be skipped during validation, and left the rest be validated normally?

For example, 
```py
class A[*T](BaseModel):
    model_config = {'skipped_fields': {'a'}}

    a: tuple[*T]  # currently unsupported

    ...  # other fields
```
This way users still gain benefits from type-checkers, and the other fields can still be validated.

Another example will be
```py
class A(BaseModel):
    @validate_call(config={'skipped_fields': 'other'})
    def merge(self, other: Self, data: list[str]) -> Self: ...
```
If the user is quite confident that `other` does not need to be validated while `data` requires validation, this usage pattern might be helpful.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@kc0506, thoughts on using [`SkipValidation`](https://docs.pydantic.dev/latest/api/functional_validators/#pydantic.functional_validators.SkipValidation)?

**Comment by kc0506** [comment]
Ah yes, it does look like what I am talking about. Thanks!

**Comment by sydney-runkle** [comment]
@kc0506, why did you reopen here?
