### ISSUE TITLE
Secret with None : TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sylvainmouquet** [pydantic/pydantic#10673]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

SecretStr allows to set a None value. But when we check the variable we get an error. If we check with the method `get_secret_value()`, the result is correct

### Example Code

```Python
from pydantic import SecretStr

secret: SecretStr = SecretStr(None)
if secret:
    print('here')

--> TypeError: object of type 'NoneType' has no len()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: <...>/.venv/lib/python3.13/site-packages/pydantic
               python version: 3.13.0 (main, Oct  7 2024, 23:47:22) [Clang 18.1.8 ]
                     platform: macOS-15.0.1-arm64-arm-64bit-Mach-O
             related packages: pydantic-settings-2.6.0 fastapi-0.115.2 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
What's your use case? `None` is not valid as an argument for `SecretStr` (you'll get a type checker error).

**Comment by sylvainmouquet** [comment]
i get the secrets from the env variable : `secret: SecretStr = SecretStr(os.getenv("MY_SECRET"))`

**Comment by Viicos** [comment]
What should happen if there's no `MY_SECRET` envvar set? You can either do:

```python
secret: SecretStr = SecretStr(os.getenv("MY_SECRET") or "")
secret: SecretStr | None = SecretStr(os.environ["MY_SECRET"]) if "MY_SECRET" in os.environ else None
```

Although I wouldn't recommend setting defaults dynamically based on the state of the environment. Perhaps using [pydantic-settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/) can help.

**Comment by sylvainmouquet** [comment]
When the secret is displayed, there is no error but it's displayed with `''` but when we use it in the if condition it generates an error message :
```
>>> from pydantic import SecretStr
>>> secret: SecretStr = SecretStr(None)
>>> secret
SecretStr('')
>>> if secret:
...     print('ok')
...     
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    if secret:
       ^^^^^^
  File ".venv/lib/python3.13/site-packages/pydantic/types.py", line 1710, in __len__
    return len(self._secret_value)
TypeError: object of type 'NoneType' has no len()
```
the fact to have different results is not weird ?

**Comment by mpkocher** [comment]
```bash
In [1]: from pydantic import SecretStr
In [2]: s0 = SecretStr(124)
In [3]: s1 = SecretStr([1,2,3])
In [4]: for i in (s1, s0): print(i, bool(i))
********** True
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 for i in (s1, s0): print(i, bool(i))

File ~/miniconda3/envs/DRAGONS/lib/python3.12/site-packages/pydantic/types.py:1679, in SecretStr.__len__(self)
   1678 def __len__(self) -> int:
-> 1679     return len(self._secret_value)

TypeError: object of type 'int' has no len()
```

There doesn't appear to be any type checking to enforce that the value is a string. 

The truthy check will look for `__bool__` (if it exists), or default back to `__len__`. Hence the TypeError.

Also, the explicit choice to leak the truthiness of the Secret ("" vs "*******")  in `repr` is a bit odd to me.

```python
    def _display(self) -> str | bytes:
        return '**********' if self.get_secret_value() else ''
```

**Comment by samuelcolvin** [comment]
> Also, the explicit choice to leak the truthiness of the Secret ("" vs "*******") in repr is a bit odd to me.

@mpkocher it might look a bit odd, but it's been like that since we first implemented `SecretStr` in pyantic 0.x, and it's helped me many times. I think we would need a very good reason to change it now, and I don't think there is one.

I'm strongly in favour of making the pragmatic, helpful choice, rather than the CS correct choice in cases like this.

**Comment by Viicos** [comment]
@sylvainmouquet closing for now but feel free to ping me if https://github.com/pydantic/pydantic/issues/10673#issuecomment-2426781540 doesn't suit you.
