### ISSUE TITLE
Better document Pydantic dataclasses configuration

### ISSUE THREAD

**Issue by RajatRajdeep** [pydantic/pydantic#10679]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I reviewed the documentation, and Pydantic currently offers two methods for passing the Dataclass configuration:

- Apply the config to the dataclass decorator as a dictionary.
- Pass a `ConfigDict` to the dataclass decorator.

In both cases, the configuration must be applied via the decorator. I propose allowing the `model_config` to be defined directly within the dataclass, similar to how it's done with `BaseModel`. If there's a specific reason against this approach, an exception should be raised when the `model_config` field is used incorrectly. While the code below runs, it doesn't apply the Dataclass configuration properly.

### Example Code

```Python
from pydantic import ConfigDict
from pydantic.dataclasses import dataclass

@dataclass
class TestDC:
    model_config = ConfigDict(extra="forbid")
    a: int
    b: int
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0a1
        pydantic-core version: 2.24.2
          pydantic-core build: profile=release pgo=false
                 install path: /Users/rajatrajdeep/Desktop/projects/pydantic/pydantic
               python version: 3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: pydantic-extra-types-2.10.0 pydantic-settings-2.5.2 mypy-1.12.0 typing_extensions-4.12.2
                       commit: 06a04b59
```

**Comment by Viicos** [comment]
The `__pydantic_config__` attribute can be used for this. It wasn't properly documented, so I tackled in https://github.com/pydantic/pydantic/pull/10686.

**Comment by RajatRajdeep** [comment]
Go it. However, I believe that in this example, if Pydantic could issue a warning, it would alert users that the model_config won't be applied, helping to prevent any potential oversight.

**Comment by Viicos** [comment]
> Go it. However, I believe that in this example, if Pydantic could issue a warning, it would alert users that the model_config won't be applied, helping to prevent any potential oversight.

It would be great indeed, however it will not be easy to implement this properly. While it is possible to emit a warning for Pydantic dataclasses, it is different for stdlib dataclasses, as the only way would be to emit the warning during core schema generation, meaning the warning will be emitted twice here:

```python
@dataclass
class A:
    pass


class Model(BaseModel):
    a1: A
    a2: A
```

I'm hoping the documentation update will reduce confusion. We'll reconsider if we get new reports.
