### ISSUE TITLE
Private attribute values are retrieved differently in instance or class methods

### ISSUE THREAD

**Issue by ldouteau** [pydantic/pydantic#10685]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi ! Thanks a lot for Pydantic
There is a difference in the way `PrivateAttr` is treated between instance methods and class methods.

* instance methods access private attributes seamlessly. On the minimal example `_float` can be casted to float
* class methods don't work with the same piece of code. `_float` is now retrieved as a `PrivateAttr`, and the value must be accessed through `PrivateAttr.default`

I wouldn't expect that behavior, but i must admit i don't know Pydantic that well

### Example Code

```Python
from pydantic import BaseModel


class Model(BaseModel):
    _float = 2.1

    @classmethod
    def f(cls) -> None:
        float(cls._float)  # Failing

    def g(self) -> None:
        float(self._float)  # Passes


Model().g()  # Passes
Model.f()  # Failing
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\XXX\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by mpkocher** [comment]
- https://docs.pydantic.dev/latest/concepts/models/#class-vars
- https://docs.python.org/3/library/typing.html#typing.ClassVar

```bash
In [7]: from typing import ClassVar
   ...: from pydantic import BaseModel
   ...: class Model(BaseModel):
   ...:     _float:ClassVar[float] = 2.1
   ...: 
   ...:     @classmethod
   ...:     def f(cls) -> float:
   ...:         return float(cls._float)  # Failing
   ...: 
   ...:     def g(self) -> float:
   ...:         return(self._float)  # Passes
   ...: 
   ...: 
   ...: Model().g(), Model.f()
Out[7]: (2.1, 2.1)
```

Note that there's some sharp edges when trying to combine ClassVar with Field.

**Comment by ldouteau** [comment]
Oh great, wasn't aware of this one. Thanks a lot

**Comment by sydney-runkle** [comment]
Hi @ldouteau,

You can use a `ClassVar` annotation if you'd like to be able to access `_float` from the `cls` seamlessly:

```py
from pydantic import BaseModel
from typing import ClassVar


class Model(BaseModel):
    _float: ClassVar = 2.1

    @classmethod
    def f(cls) -> None:
        float(cls._float)  # Failing

    def g(self) -> None:
        float(self._float)  # Passes


Model().g()  # Passes
Model.f()  # Failing
```

Going to close as resolved for now. Basically, it's inferred that `_float` is an instance attribute unless you specify otherwise.
