### ISSUE TITLE
`exclude_defaults` is broken for Optional fields with `default_factory` when set to `None`

### ISSUE THREAD

**Issue by z-tux-mind** [pydantic/pydantic#10683]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hello! First of all thank you for this fantastic framework and for maintaining the old version.

When having a model with an `Optional` field that has a `default_factory`, when that field is set to `None`, the resulting serialisation of that model lacks that field, instead of including it with the `None` value.

I've attached a test case inspired by the [official](https://github.com/pydantic/pydantic/blob/5ebcdc13b83fba5da34ad9b0f008f7b4faf89396/tests/test_main.py#L1106) one.

I believe that somewhere during the model creation, the `ModelField.default` is set to `None` instead of `Undefined`, breaking the exclude_defaults check at this [line](https://github.com/pydantic/pydantic/blob/5ebcdc13b83fba5da34ad9b0f008f7b4faf89396/pydantic/main.py#L857).

### Example Code

```Python
def test_exclude_defaults():
    class Model(BaseModel):
        nullable_default_factory: Optional[str] = Field(default_factory=lambda: "a")
    
    m = Model(nullable_default_factory=None)
    assert m.dict(exclude_defaults=True) == {
        'nullable_default_factory': None,
    }
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.18
            pydantic compiled: True
                 install path: /tmp/latest-pydantic1.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0]
                     platform: Linux-6.1.0-25-amd64-x86_64-with-glibc2.36
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Closing as not planned for now, but as @Viicos said, happy to consider a PR with a fix.
