### ISSUE TITLE
list Field with min_length and default_factory does not validate min_length

### ISSUE THREAD

**Issue by mschoettle** [pydantic/pydantic#10714]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I created a model where I have a field of type `list[SomeOtherModel]`. I want to enforce that a list is provided with at least one element and defined it as `some_field_list: list[SomeOtherModel] = Field(default_factory=list, min_length=1)`.

However, the min_length is not validated. Only when I remove the `default_factory` argument.

Having thought a bit about it I think that this makes sense but it was not immediately obvious. If this is as intended, would it be worth mentioning this in the docs?

### Example Code

```Python
from pydantic import BaseModel, Field


class TestModel(BaseModel):
    some_list: list[str] = Field(default_factory=list, min_length=1)


TestModel.model_validate({})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /path/to/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.10 (main, Sep  7 2024, 01:03:31) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-13.7-arm64-arm-64bit
             related packages: mypy-1.13.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @mschoettle,

You can use the `validate_default` setting to get the expected behavior here:

```py
from pydantic import BaseModel, Field


class TestModel(BaseModel):
    some_list: list[str] = Field(default_factory=list, min_length=1, validate_default=True)


TestModel.model_validate({})
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for TestModel
some_list
  List should have at least 1 item after validation, not 0 [type=too_short, input_value=[], input_type=list]
    For further information visit https://errors.pydantic.dev/2.10/v/too_shor
"""
```
