### ISSUE TITLE
Add a version info tuple?

### ISSUE THREAD

**Issue by alicederyn** [pydantic/pydantic#10710]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Please add a namedtuple containing the version in the form `(major, minor, micro, releaselevel, serial)`, matching the structure returned by [`sys.version_info`](https://docs.python.org/3/library/sys.html#sys.version_info).

This would allow library authors to easily write different code for different Pydantic versions, in a way that is understood and validated by static type checkers, much as is currently possible for Python versions:

```python
if pydantic.version_info >= (3,):  # Understood by static type checkers!
    model.some_v3_function(...)  # Type-checked if pydantic v3 is installed
else:
    model.some_v2_function(...)  # Type-checked if pydantic v2 is installed
```

As far as I am aware, this integration with static type checkers is not possible currently, as there isn't a way to write an equivalent statically-understood check against the version information string.

It would be ideal if this could also be backported to v1, for libraries that support both v1 and v2.

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
Unlike `sys.version_info` (refer to the relevant [specification section](https://typing.readthedocs.io/en/latest/spec/directives.html#version-and-platform-checking)), type checkers currently don't understand such checks for library versions. For libraries, this was briefly discussed [here](https://github.com/python/typing/issues/693).

Considering the lack of typing support, are you still willing to have such a feature? We currently provide `pydantic.VERSION`, `pydantic.version_short()`, and users can also use [`importlib.metadata.version()`](https://docs.python.org/3/library/importlib.metadata.html#importlib.metadata.version) and the [`packaging`](https://packaging.pypa.io/en/stable/version.html) library can also be used.

**Comment by sydney-runkle** [comment]
I agree with @Viicos' analysis here - I think we provide a sufficient amount of version info with `pydantic.VERSION`, and that can be easily parsed.

**Comment by alicederyn** [comment]
Well, despite having a firm memory of getting this to work by declaring it of type `Tuple[Literal[2], Literal[...`, I can't get that to work now. (In fact, I think I found a bug in pyright.) Sorry for the noise. Maybe I'll raise an issue on pyright and see if it's something that the type-checker community might consider adding.

**Comment by Viicos** [comment]
Yes, I also tried defining the following:

```python
version_info: tuple[Literal[2], Literal[9], Literal[0]] = (2, 9, 0)

if version_info > (2, 0, 0): ...
```

and I get a pyright error on the comparison. This might be the bug you are referring to, but it is actually expected. While pyright special cases the `tuple` parametrization, it relies on the [`typeshed` definition](https://github.com/python/typeshed/blob/355abb197eeabc406c3d03b65ff23245e6a38b4e/stdlib/builtins.pyi#L970-L994) for the rest, meaning we get the following:

```python
version_info: tuple[Literal[2], Literal[9], Literal[0]] = (2, 9, 0)
reveal_type(version_info)  # tuple[Literal[2], Literal[9], Literal[0]]
reveal_type(version_info.__le__)  # (value: tuple[Literal[2, 9, 0], ...], /) -> bool"
```

Meaning `version_info` can only be compared with other values of type `tuple[Literal[2, 9, 0], ...]`, which is incompatible (unless I'm mistaken) with `tuple[Literal[2], Literal[9], Literal[0]]`.

**Comment by alicederyn** [comment]
`tuple[Literal[2, 9, 0], ...]` *should* be compatible with `tuple[Literal[2], Literal[9], Literal[0]]`, since tuples are not mutable. I can't replicate your result &mdash; your code passes pyright for me. However, it starts erroring if I change your example to `if version_info >= (2, 1): ...` because there's a `1` in there. Alternatively, changing `version_info` to `(2, 9, 1`) also causes an error because the `0` has been removed.

I agree that the typeshed definition is the root cause of the problem. Not the first time I've hit issues with typeshed being unable to adequately express the real type constraints of Python 😢 Not sure why mypy has no issue with it.

**Comment by Viicos** [comment]
> `tuple[Literal[2, 9, 0], ...]` _should_ be compatible with `tuple[Literal[2], Literal[9], Literal[0]]`, since tuples are not mutable. I can't replicate your result — your code passes pyright for me. However, it starts erroring if I change your example to `if version_info >= (2, 1): ...` because there's a `1` in there (`error: Operator ">" not supported for types "tuple[Literal[2], Literal[9], Literal[0]]" and "tuple[Literal[2], Literal[1]]"`). Alternatively, changing `version_info` to `(2, 9, 1`) also causes an error because the `0` has been removed.

Ah yes sorry, it is compatible indeed but as you mentioned it starts erroring when you use different values (although fine at runtime).

> Not sure why mypy has no issue with it.

iirc mypy special cases tuples for this use case. Although it will probably not mark one of the `if...else` branches as unreachable (which is the wanted effect)
