### ISSUE TITLE
`model_dump` dict stays attached to the model's references for custom classes

### ISSUE THREAD

**Issue by alexhroom** [pydantic/pydantic#10735]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It appears that `model_dump` creates a 'shallow' dump of the model: if one of the model attributes is a custom class containing mutable data, then changing the data in a dump of the model will also change it in the original model.

This feels unexpected as one would expect a 'dump' to be a record (e.g. [core dump](https://en.wikipedia.org/wiki/Core_dump), or [database dump](https://en.wikipedia.org/wiki/Database_dump)) of the model at the time of the dump, and changing that record should not change the original model. I think that either `model_dump` should do 'deep' dumps by default to actually create a dictionary record (and `vars(model)` can be used for `shallow` dumps) or `model_dump` should have an optional `deep` parameter.

A current workaround for this is if you use `model.model_copy(deep=True).model_dump()`, then it works as expected.

### Example Code

```Python
from pydantic import BaseModel

class MyClass:
    def __init__(self, data):
        self.data = data

class Model(BaseModel, arbitrary_types_allowed=True):
    var: MyClass

m = Model(var=MyClass([1, 2, 3]))
md = m.model_dump()
md['var'].data.pop()

# will give a result of [1, 2], so 3 has been popped from the model as well
print(m.var.data)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/rec93639/Code/RasCAL-2/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (main, Jul 25 2024, 22:42:01) [Clang 18.1.8 ]
                     platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2
                       commit: unknown

```

**Comment by sydney-runkle** [comment]
Hi @alexhroom,

Thanks so much for your question. This is a consequence of the fact that you're using an arbitrary type, we simply dump the instance. If you'd like different behavior here, I'd recommend using a custom serializer, like follows:

```py
from pydantic import BaseModel, PlainSerializer
from typing import Annotated
from copy import deepcopy

class MyClass:
    def __init__(self, data):
        self.data = data

class Model(BaseModel, arbitrary_types_allowed=True):
    var: Annotated[MyClass, PlainSerializer(lambda x: deepcopy(x))]

m = Model(var=MyClass([1, 2, 3]))
md = m.model_dump()
md['var'].data.pop()

# will give a result of [1, 2, 3]
print(m.var.data)
```

We offer much more intuitive support for `BaseModel` subclasses (nested models). Let me know if you have any other questions :).
