### ISSUE TITLE
Firebase Geopoint serialization

### ISSUE THREAD

**Issue by hectordufau** [pydantic/pydantic#10733]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I got this error message: 

`pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'google.cloud.firestore_v1._helpers.GeoPoint'>`

When I use this class

```
from typing import Optional

from google.cloud.firestore import GeoPoint
from pydantic import BaseModel


class RegisterAddress(BaseModel):
    registerID: Optional[str] = ""
    address: Optional[str] = ""
    numberaddress: Optional[str] = ""
    district: Optional[str] = ""
    city: Optional[str] = ""
    state: Optional[str] = ""
    zipCode: Optional[str] = ""
    country: Optional[str] = ""
    location: Optional[GeoPoint] = None
```

This class is used to get data from 'registerAddress' Firebase Collection and one of their data is 'location' as Firebase GeoPoint type.

I guess it could be a Pydantic new feature, however, if it is a bug, how can I solve it?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
See https://docs.pydantic.dev/latest/concepts/types/#custom-types on how to define custom types.

**Comment by hectordufau** [comment]
@Viicos unfortunatelly I disagree with this Closed issue status. 

How to solve it using a Pydantic Custom Type? Really I've tried using it with no success.

Firebase GeoPoint type is in google.cloud.firestore_v1._helpers

**Comment by hectordufau** [comment]
I did.

```
from typing import Annotated

from pydantic import BaseModel, Field


class GeoPointModel(BaseModel):
    latitude: Annotated[float, Field(ge=-90, le=90)]
    longitude: Annotated[float, Field(ge=-180, le=180)]
```
After...

```
from typing import Optional

from google.cloud.firestore_v1 import GeoPoint
from pydantic import BaseModel, field_validator

from models.geopoint import GeoPointModel


class RegisterAddress(BaseModel):
    registerID: Optional[str] = ""
    address: Optional[str] = ""
    numberaddress: Optional[str] = ""
    district: Optional[str] = ""
    city: Optional[str] = ""
    state: Optional[str] = ""
    zipCode: Optional[str] = ""
    country: Optional[str] = ""
    location: Optional[GeoPointModel] = None
    addressType: Optional[str] = ""
    status: Optional[bool] = False
    billing: Optional[bool] = False

    def __str__(self):
        return str("registerAddress")

    class Config:
        arbitrary_types_allowed = True

    @field_validator("location", mode="before")
    @classmethod
    def validate_location(cls, value):
        if isinstance(value, GeoPoint):
            return {"latitude": value.latitude, "longitude": value.longitude}
        return value
```

field_validator is the key.

Problem solved
