### ISSUE TITLE
No validation of timezone when using annotated datetime with annotated-types

### ISSUE THREAD

**Issue by Nagasaki45** [pydantic/pydantic#10743]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a datetime that I want to be validated as aware and in UTC. I'm following the docs [here](https://docs.pydantic.dev/latest/concepts/types/#composing-types-via-annotated) to annotate the datetime as such. I expect the initialization of the model to fail, but it succeeds. When I try a similar approach by annotating an integer as greater than a value the validation works as expected.

I hope this is clear enough, and that I'm using the library correctly.

I'm on `annotated-types==0.7.0` if it matters.

Thanks for this great library by the way. Excellent stuff!

### Example Code

```Python
from datetime import datetime, timezone
from typing import Annotated

from annotated_types import Gt, Timezone
from pydantic import BaseModel, ValidationError


class Event(BaseModel):
    date: Annotated[datetime, Timezone(timezone.utc)]


class Adult(BaseModel):
    age: Annotated[int, Gt(18)]


try:
    Adult(age=12)
except ValidationError:
    pass  # This is expected


try:
    Event(date=datetime(2024, 1, 1, 12, 0, 0))
except ValidationError:
    pass  # This is expected
else:
    raise Exception("No validation error 😢")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/tgurion/code/pydantic-annotated-types/.venv/lib/python3.13/site-packages/pydantic
               python version: 3.13.0rc2 (main, Sep  9 2024, 22:13:26) [Clang 18.1.8 ]
                     platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by mpkocher** [comment]
Using `AwareDatetime` might help, but it won't solve your fundamental issue of enforcing a specific TZ.

https://docs.pydantic.dev/latest/api/types/#pydantic.types.AwareDatetime

(Also, you probably want to use Strict mode. The non-strict mode (e.g., `Event(date=1)` might be a bit surprising.)

Here's a workaround. 

```python
from zoneinfo import ZoneInfo
from datetime import datetime, timezone
from typing import Annotated

from annotated_types import Gt, Timezone
from pydantic import BaseModel, ValidationError, AwareDatetime, Strict, AfterValidator

ZI_UTC = ZoneInfo("UTC")

def require_utc(dt: AwareDatetime) -> AwareDatetime:
    assert dt.tzinfo == ZI_UTC, f"Datetime must be provided in UTC. Got {dt.tzinfo}"
    return dt


class Event(BaseModel):
    date: Annotated[AwareDatetime, Strict(), AfterValidator(require_utc)]
```

In REPL.

```bash
In [2]: Event(date=datetime.now().astimezone(ZI_UTC))
Out[2]: Event(date=datetime.datetime(2024, 10, 31, 0, 23, 34, 692493, tzinfo=zoneinfo.ZoneInfo(key='UTC')))

In [3]: Event(date=datetime.now().astimezone(ZoneInfo("Africa/Accra")))
ValidationError: 1 validation error for Event
date
  Assertion failed, Datetime must be provided in UTC. Got Africa/Accra [type=assertion_error, input_value=datetime.datetime(2024, 1...nfo(key='Africa/Accra')), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.9/v/assertion_error

In [4]: Event(date=1)
ValidationError: 1 validation error for Event
date
  Input should be a valid datetime [type=datetime_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.9/v/datetime_type

In [5]: Event(date=datetime.now())
ValidationError: 1 validation error for Event
date
  Input should have timezone info [type=timezone_aware, input_value=datetime.datetime(2024, 1... 30, 17, 26, 29, 170166), input_type=datetime]
    For further information visit https://errors.pydantic.dev/2.9/v/timezone_aware
```

Also, note that the `Timezone` in `Annotated` doesn't appear to be checked or validated. 

```bash
In [6]: class A(BaseModel):
   ...:     t0: Annotated[datetime, Timezone("DRAGONS")]
   ...: 

In [7]: A(t0=1)
Out[7]: A(t0=datetime.datetime(1970, 1, 1, 0, 0, 1, tzinfo=TzInfo(UTC)))
```

**Comment by Nagasaki45** [comment]
Thank you very much for the response @mpkocher!

I totally missed the `AwareDatetime` type. This, and your suggestions, completely solve my problem. I still think the behaviour in my example is confusing, so maybe there's an action there (potentially just docs update). If you agree I'm happy to help and contribute an improvement. Otherwise, feel free to close the case.

**Comment by sydney-runkle** [comment]
@Nagasaki45,

Thanks for your question!

We actually have a pretty detailed example in the [docs](https://docs.pydantic.dev/latest/examples/custom_validators/#custom-datetime-validator-via-annotated-metadata) showing how to do validation with a constrained timezone.

I'm hoping that helps to clarify the issue here. That being said, if you think an additional docs update would be helpful here, feel free to open a PR and I'd be happy to review!

One other point - we don't support `Timezone` as a constraint at the moment, hence your initial example not working :)

**Comment by sydney-runkle** [comment]
That could probably be added as a separate feature request, though if I recall correctly, we ran into some difficulties with that in the past. Doesn't mean it can't be done!

**Comment by Nagasaki45** [comment]
Hi @sydney-runkle,

Thank you for your comments. I should better familiar myself with the docs, I guess. It sounds like @mpkocher and yourself don't see any problem with the current behaviour nor the docs, and my problem is solved (thanks again @mpkocher!), so I'm happy closing the case.
