### ISSUE TITLE
`model_json_schema` not including `computed_field`

### ISSUE THREAD

**Issue by ollyhensby** [pydantic/pydantic#10768]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The `model_json_schema` method does not include fields decorated with `@computed_field`.

According to the [Pydantic documentation](https://docs.pydantic.dev/2.9/concepts/fields/#the-computed_field-decorator):

_"The [computed_field](https://docs.pydantic.dev/2.9/api/fields/#pydantic.fields.computed_field) decorator can be used to include [property](https://docs.python.org/3/library/functions.html#property) or [cached_property](https://docs.python.org/3/library/functools.html#functools.cached_property) attributes when serializing a model or dataclass. The property will also be taken into account in the JSON Schema."_

However, when using `model_json_schema`, the computed field does not appear in the output. This behaviour is inconsistent with the documentation.

### Expected Behaviour:
The `computed_field` should be included in the output schema when using `model_json_schema`.

### Example Code

```Python
from pydantic import BaseModel, computed_field


class Box(BaseModel):
    width: float
    height: float
    depth: float

    @computed_field
    @property  
    def volume(self) -> float:
        return self.width * self.height * self.depth

Box.model_json_schema()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
pydantic-core version: 2.23.4
pydantic-core build: profile=release pgo=false
install path: /home/jovyan/miniforge3/envs/document-issue-dev/lib/python3.11/site-packages/pydantic
python version: 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0]
platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
related packages: pydantic-settings-2.6.1 pydantic-extra-types-2.10.0 typing_extensions-4.11.0 fastapi-0.115.4
commit: unknown
```

**Comment by ollyhensby** [comment]
Just to follow this up, I have realised that the `computed_field` only appears if `mode="serialization"`. Maybe this could be clearer in that section of the documentation: https://docs.pydantic.dev/2.9/concepts/fields/#the-computed_field-decorator

I am happy to add an example!

**Comment by sydney-runkle** [comment]
Ping me when you're ready for a review :)

**Comment by Viicos** [comment]
Maybe changing the sentence to:

> The [computed_field](https://docs.pydantic.dev/2.9/api/fields/#pydantic.fields.computed_field) decorator can be used to include [property](https://docs.python.org/3/library/functions.html#property) or [cached_property](https://docs.python.org/3/library/functools.html#functools.cached_property) attributes when serializing a model or dataclass. The property will also be taken into account in the JSON Schema (in serialization mode).

is enough? Perhaps with a link to a specific section.
