### ISSUE TITLE
Alias Generator Not Converting Field Names to CamelCase with .model_dump(by_alias=True)

### ISSUE THREAD

**Issue by Ben621** [pydantic/pydantic#10764]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hey,

I'm trying to use `Field` and `alias_generator` in Pydantic, but it doesn't seem to affect the field names when I use `.model_dump(by_alias=True)`. The fields remain in `snake_case` instead of being converted to camelCase.

The output I get is `{'current_account': '12345'}`

The expected output is `{'currentAccount': '12345'}`

Could you please help me resolve this issue?

Thanks!

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel

class Account(BaseModel):
    model_config = ConfigDict(populate_by_name=True, alias_generator=to_camel)
    my_account: str = Field(serialization_alias="current_account")

class Account_2(BaseModel):
    model_config = ConfigDict(populate_by_name=True, alias_generator=to_camel)
    my_account: str

if __name__ == '__main__':
    a = Account(my_account="12345")
    print(a.model_dump())
    print(a.model_dump(by_alias=True))
    a_2 = Account_2(my_account="6789")
    print(a_2.model_dump())
    print(a_2.model_dump(by_alias=True))

# output

{'my_account': '12345'}
{'current_account': '12345'}  # expected `{'currentAccount': '12345'}`
{'my_account': '6789'}
{'myAccount': '6789'}

`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
pydantic-core version: 2.23.4
pydantic-core build: profile=release pgo=false
install path: C:\Users\MYUSER\PycharmProjects\INTERPRETER\gw\Lib\site-packages\pydantic
python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
related packages: fastapi-0.115.0 mypy-1.11.2 pydantic-extra-types-2.9.0 pydantic-settings-2.5.2 typing_extensions-4.12.2
commit: unknown
```

**Comment by Viicos** [comment]
As per [the documentation](https://docs.pydantic.dev/dev/concepts/alias/#using-an-aliasgenerator), the `serialization_alias` takes precedence over the `alias_generator`, unless you change the alias priority. If you want the `serialization_alias` to be converted using `to_camel`, this is not possible. What prevents you from doing `my_account: str = Field(serialization_alias="currentAccount")`?
