### ISSUE TITLE
Pylance complains about parameters provided to Field

### ISSUE THREAD

**Issue by drorata** [pydantic/pydantic#10773]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When defining a model and specifying parameters of the Field details, Pylance complains about them. Specifically about `help` and `env` (the latter relates to `pydantic-settings`).

<img width="580" alt="image" src="https://github.com/user-attachments/assets/f913f0ab-5e3d-4842-aeb1-7789a671fae4">

The error raised by Pylance is:

```
No parameter named "help"Pylance[reportCallIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportCallIssue)
(function) help: Unknown
```

### Example Code

```Python
class GeneralSettings(BaseSettings):
    environment_letter: Literal["d", "i", "p",] = Field(  # DEV  # INT  # PRD
        help="Environment letter", env="ENVIRONMENT_LETTER", default="d"
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/DATARIA/poetry-envs/mam-config-OAUIYoDV-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 16.0.0 (clang-1600.0.26.3)]
                     platform: macOS-15.1-arm64-arm-64bit
             related packages: pydantic-settings-2.6.0 typing_extensions-4.12.2
                       commit: unknown


In addition, I'm using VScode 1.95.1 and Pylance `v2024.11.1`
```

**Comment by Viicos** [comment]
What you are trying to do is not supported. Can you link an example of where you saw such an example?

**Comment by drorata** [comment]
I guess I ran into some confusion. Instead of `help` key I probably wanted to used `description` and as for the `env` key... I'm not sure. In By default, if I get it right, `BaseSettings` looks for environment variables with the same names like the fields of the class (only capitalized). Right? I thought I can use the `env` key to tell the settings to look for an environment variable of the provided name instead of the default one. Is it possible?

Otherwise, I think this issue can be closed.

**Comment by sydney-runkle** [comment]
Hi!

I think you can use the `alias` key to tell the settings to look for the data under a specific environment variable. See the [docs here](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#usage) for more info!

Going to mark as resolved for now, but feel free to follow up with questions regarding how to make this work.
