### ISSUE TITLE
Union validation fails with AttributeError on types that aren't first in the union

### ISSUE THREAD

**Issue by jlowin** [pydantic/pydantic#10770]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We first noticed an issue where Union validation wasn't being applied to nested LangChain models in an expected way, calling the nested model's validator in a way that raised an AttributeError and stopped model creation entirely (simple fix to remove typing on ControlFlow repo is [here](https://github.com/PrefectHQ/ControlFlow/pull/376)). 

However, I created an MRE that demonstrates the behavior without any of our logic. The code is below. We create a BaseModel with a single `model` field that is a union of the ChatOpenAI and AzureChatOpenAI langchain models. In one BaseModel, the OpenAI model is listed first in the union; in the other, the Azure model is listed first. 

When you instantiate the BaseModels, whichever langchain model was listed first in the union can be loaded successfully; whichever one is listed second fails. 

Note that this is using default union logic; setting to `left_to_right` doesnt seem to make a difference.

### Example Code

```Python
import controlflow as cf
from langchain_openai import AzureChatOpenAI, ChatOpenAI
from pydantic import BaseModel, Field
from typing import Union

azure = AzureChatOpenAI(api_version='1', azure_endpoint='2')
openai = ChatOpenAI(model="gpt-4o")


class OpenAIFirst(BaseModel):
    model: Union[ChatOpenAI, AzureChatOpenAI]

class AzureFirst(BaseModel):
    model: Union[AzureChatOpenAI, ChatOpenAI]



# when chatopenai is on the left, azure fails     


OpenAIFirst(model=openai)
print("openai passed")

try:
    OpenAIFirst(model=azure)
except Exception as e:
    print(e)


# when azure is on the left, openai fails


AzureFirst(model=azure)
print("azure passed")

try:
    AzureFirst(model=openai)
except Exception as e:
    print(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jlowin/Developer/controlflow/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb 25 2024, 03:55:42) [Clang 17.0.6 ]
                     platform: macOS-15.1-arm64-arm-64bit
             related packages: pydantic-settings-2.6.1 mypy-1.13.0 fastapi-0.115.4 pydantic-extra-types-2.10.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@jlowin,

What error are you getting? Can you show the `print(e)` output?

**Comment by sydney-runkle** [comment]
If you could send a repro with solely `pydantic` as a dependency, that would be great.

**Comment by sydney-runkle** [comment]
Going to close for now until we have an MRE, happy to reopen with that :).

**Comment by mpkocher** [comment]
Perhaps try investigating the usage of `model_validator` with `mode=before`.

https://github.com/langchain-ai/langchain/blob/master/libs/partners/openai/langchain_openai/chat_models/base.py#L496C4-L503C22

```python
    @model_validator(mode="before")
    @classmethod
    def validate_temperature(cls, values: Dict[str, Any]) -> Any:
        """Currently o1 models only allow temperature=1."""
        model = values.get("model_name") or values.get("model") or ""
        if model.startswith("o1") and "temperature" not in values:
            values["temperature"] = 1
        return values
```

I believe this might need to have an `isinstance(values, dict)` check. This assumption that the input is `dict[str, Any]` appears to be the source of the attribute `get` error. 

The docs have more details on the specifics:

> Before model validators are passed the raw input which is often a dict[str, Any] but could also be an instance of the model itself (e.g. if UserModel.model_validate(UserModel.construct(...)) is called) or anything else since you can pass arbitrary objects into model_validate. Because of this mode='before' validators are extremely flexible and powerful but can be cumbersome and error prone to implement.

https://docs.pydantic.dev/latest/concepts/validators/#model-validators

I'm not a Pydantic expert, however the usage of `model_validator` did seem like a good place to start debugging.
