### ISSUE TITLE
pylance autoimport suggests pydantic.v1 for importing BaseModel

### ISSUE THREAD

**Issue by jscheel** [pydantic/pydantic#10791]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using pydantic 2.9.2. When I try to auto-import BaseModel in vscode/cursor, pylance suggests `from pydantic.v1 import BaseModel`. Other exports in the root __init__.py work fine.

<img width="715" alt="Screenshot_2024-11-07_at_5 35 06_PM" src="https://github.com/user-attachments/assets/8edf776f-c0cf-4463-ad8a-a8929edae8bf">

### Example Code

```Python
class Foo(BaseModel):
    ...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /***/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.11 (main, May  7 2023, 18:32:37) [Clang 16.0.3 ]
                     platform: macOS-14.7-x86_64-i386-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Thanks for reporting this. Unfortunately, I'm not able to reproduce this issue in vscode:

<img width="593" alt="Screenshot 2024-11-08 at 9 26 16 AM" src="https://github.com/user-attachments/assets/3b0caf3f-5555-4555-9eb1-0839243b9457">

Not sure why this is happening. Could you try with `v2.10.0b1` and see if you're still getting this issue? Thanks!

**Comment by Viicos** [comment]
I don't know how Pylance suggests the imports, probably best to ask on https://github.com/microsoft/pylance-release/ instead. It might be that some exported objects in `__init__.py` can change the result, but we didn't have anything changed related to this recently.

**Comment by sydney-runkle** [comment]
Going to close for now, as I don't think we'll change something on our end here to resolve this, but happy to keep iterating to help you figure this out :).

**Comment by jscheel** [comment]
It looks like this is indeed pylance related: https://github.com/microsoft/pylance-release/issues/6209
