### ISSUE TITLE
pydantic_core.from_json() does not support line breaks in string

### ISSUE THREAD

**Issue by lucaslulucaslu** [pydantic/pydantic#10804]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I tried to use new partial json parseing support from_json() to parse LLM tokens, however, when there is a line break in llm response, pydantic will raise a ValueError: control character (\u0000-\u001F) found while parsing a string at

### Example Code

```Python
from pydantic_core  import from_json

json_string="""{"a":1,"b":"123\n123"}"""

json_result=from_json(json_string)

print(json_result)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
pydantic-core version: 2.23.4
python: 3.12
```

**Comment by sydney-runkle** [comment]
cc @samuelcolvin, do we want to support this?

**Comment by sydney-runkle** [comment]
I don't think this is something we plan to support - I'd recommend a custom `BeforeValidator` if you'd like to parse json with line breaks like that 👍
