### ISSUE TITLE
@property above @computed_field raises TypeError: 'PydanticDescriptorProxy' object is not callable

### ISSUE THREAD

**Issue by arseru** [pydantic/pydantic#10805]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using computed fields, if I take the example from [pydantic's documentation](https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.computed_field), but I place `@property` above `@computed_field`, and I try to print the computed field `area`, I get the following error:

```
Traceback (most recent call last):
  File "tmp.py", line 12, in <module>
    print(Rectangle(width=3, length=2).area)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'PydanticDescriptorProxy' object is not callable
```

I just wanted to report it because it looked like unexpected behaviour from placing the decorators in the "wrong" order.

### Example Code

```Python
from pydantic import BaseModel, computed_field

class Rectangle(BaseModel):
    width: int
    length: int

    @property
    @computed_field
    def area(self) -> int:
        return self.width * self.length

print(Rectangle(width=3, length=2).area)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: .venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.10 (main, Oct 16 2024, 04:38:48) [Clang 18.1.8 ]
                     platform: Linux-6.11.5-arch1-1-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2 mypy-1.13.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Indeed, this isn't supported. You should use the order shown in the docs, with `@computed_field`, then `@property`.
