### ISSUE TITLE
Allow partial needs `'trailing-strings'` mode, same as `pydantic_core.from_json`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#10806]
I think I was safe to skip `'trailing-strings'` mode when introducing allow partial #10748.

I was wrong, there are definitely cases where disabling support for trailing strings would be useful.

Even though it's a change of behaviour,I think we should change the signature to match `pydantic_core.from_json`.

@sydney-runkle should we do this in the beta or in 2.11?

**Comment by sydney-runkle** [comment]
@samuelcolvin,

We can do this in the beta. I think we should release a `v2.10.0b2` early this week (there are a few other core fixes that would be good to get in, and I think we need to get https://github.com/pydantic/pydantic/issues/10632 across as well in v2.10).
