### ISSUE TITLE
Avoid Models Field Caching

### ISSUE THREAD

**Issue by scaui0** [pydantic/pydantic#10803]
The TestModel does not refresh the `ModelStack` instance whenever the `current_model` changes. As a result, the `TestModel` fails to validate input data correctly when `current_model` is dynamically updated. Specifically, updating `current_model` from `Model` to `Model2` should allow the `TestModel` to use `Model2` for validation, but it continues to reference `Model1`.

**Code to reproduce:**
```python
from pydantic import BaseModel

class Model1(BaseModel):
    name: str

class Model2(BaseModel):
    numbers: list[int]

current_model = Model1

class ModelStack:
    def __getattr__(self, item):
        return getattr(current_model, item)

class TestModel(BaseModel):
    submodel: ModelStack()

print(TestModel.model_validate({"submodel": {"name": "John Doe"}}))  # Expected: submodel=Model1(name='John Doe')

current_model = Model2
print(TestModel.model_validate({"submodel": {"numbers": [1, 2, 3]}}))  # Expected: submodel=Model2(numbers=[1, 2, 3])
# Actual output:
# 
# pydantic_core._pydantic_core.ValidationError: 1 validation error for TestModel
# submodel.name
#   Field required [type=missing, input_value={'numbers': [1, 2, 3]}, input_type=dict]
#     For further information visit https://errors.pydantic.dev/2.9/v/missing
```

**Expected Behavior:** The `TestModel` should refresh its `ModelStack` submodel whenever `current_model` is updated. Therefore, after updating `current_model` to `Model2`, `TestModel` should recognize it and validate `{"submodel": {"numbers": [1, 2, 3]}}` correctly.

**Actual Behavior:** The `TestModel` does not refresh the submodel and continues to expect the fields defined in `Model1`, resulting in a validation error.

**Environment (if needed):** 
Python: 3.12.1
Pydantic: 2.9.2

**Comment by sydney-runkle** [comment]
Hi @scaui0,

Thanks for your question. Indeed, you need to do a manual schema rebuild to get the desired behavior here. See:

```py
from pydantic import BaseModel

class Model1(BaseModel):
    name: str

class Model2(BaseModel):
    numbers: list[int]

current_model = Model1

class ModelStack:
    def __getattr__(self, item):
        return getattr(current_model, item)
    
class TestModel(BaseModel):
    submodel: ModelStack()

print(TestModel.model_validate({"submodel": {"name": "John Doe"}}))  # Expected: submodel=Model1(name='John Doe')

current_model = Model2
TestModel.model_rebuild(force=True)

print(TestModel.model_validate({"submodel": {"numbers": [1, 2, 3]}}))  # Expected: submodel=Model2(numbers=[1, 2, 3])
```
