### ISSUE TITLE
coerce_numbers_to_str doesn't work with IntEnum

### ISSUE THREAD

**Issue by subnix** [pydantic/pydantic#10808]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When an `IntEnum` instance is dumped with the enabled `coerce_numbers_to_str` option, it produces a stringified enum name (`FooEnum.FOO`) instead of a stringified integer value (`"1"`).
It appears that pydantic calls `str` on enum instance instead of calling `str` on instance’s value.

### Example Code

```Python
import enum
import pydantic


class FooEnum(enum.IntEnum):
    FOO = 1


class FooModel(pydantic.BaseModel):
    field: FooEnum = pydantic.Field(coerce_numbers_to_str=True)


if __name__ == "__main__":
    model = FooModel(field=FooEnum.FOO)
    # {'field': 'FooEnum.FOO'}
    print(model.model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
pydantic-core version: 2.23.4
pydantic-core build: profile=release pgo=false
install path: ...
python version: 3.9.6 (default, Oct  4 2024, 08:01:31)  [Clang 16.0.0 (clang-1600.0.26.4)]
platform: macOS-15.1-arm64-arm-64bit
related packages: typing_extensions-4.12.2
commit: unknown
```

**Comment by aberenda-optifino** [comment]
I just checked this code

```python
import enum
import pydantic


class FooEnum(enum.IntEnum):
    FOO = 1


class FooModel(pydantic.BaseModel):
    field: FooEnum

# Without coerce_numbers_to_str I see enum
assert FooModel(field=FooEnum.FOO).model_dump() == {'field': FooEnum.FOO}


class FooModel(pydantic.BaseModel):
    field: FooEnum = pydantic.Field(coerce_numbers_to_str=True)

# with coerce_numbers_to_str I see '1'
assert FooModel(field=FooEnum.FOO).model_dump() == {'field': '1'}
```

It seems everything works well
or did I do something wrong?


```
pydantic version: 2.9.2
pydantic-core version: 2.23.4
pydantic-core build: profile=release pgo=false
install path: /Users/aberenda/projects/optifino/optifino/.venv/lib/python3.12/site-packages/pydantic
python version: 3.12.6 (main, Oct  3 2024, 00:52:54) [Clang 16.0.0 (clang-1600.0.26.3)]
platform: macOS-15.1-arm64-arm-64bit
related packages: typing_extensions-4.12.0 mypy-1.13.0 pydantic-extra-types-2.9.0 fastapi-0.115.4 pydantic-settings-2.4.0
commit: unknown
```

**Comment by aberenda-optifino** [comment]
I see that I used python3.12 not python3.9
I need to check on python3.9

**Comment by subnix** [comment]
From the [IntEnum docs](https://docs.python.org/3/library/enum.html#enum.IntEnum):
> Changed in version 3.11: [__str__()](https://docs.python.org/3/reference/datamodel.html#object.__str__) is now int.__str__() to better support the replacement of existing constants use-case. [__format__()](https://docs.python.org/3/reference/datamodel.html#object.__format__) was already int.__format__() for that same reason.

So the problem affects only `python<3.11`.

**Comment by Viicos** [comment]
The logic for `coerce_numbers_to_str` during validation is to call `str(...)` on the validated data, and I don't think we want to introduce extra complexity with version checks and `IntEnum` in `pydantic-core`. The `enum` module has undergone multiple changes across Python versions and we'd like to avoid special casing as much as possible.

Alternatively, you can customize the `__str__` method of the enum:

```python
class FooEnum(enum.IntEnum):
    FOO = 1

    # if sys.version_info < (3, 11):
    def __str__(self) -> str:
        return str(self.value)
```
