### ISSUE TITLE
AttributeError raised in property as masked and reported as a pydantic error instead

### ISSUE THREAD

**Issue by jmassucco17** [pydantic/pydantic#10821]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a pydantic model has property attributes that do computation, and any of those computations may result in an `AttributeError`, this error is masked as if it is a pydantic `__getattr__` error. This is a confusing result mainly because the actual cause of the `AttributeError` becomes extremely opaque and hard to chase down.

This issue was uncovered in #10810 after much goose chasing. It would be good if pydantic were able to distinguish between `AttributeErrors` caused by actual inability to access the model attribute vs `AttributeErrors` raised from within a calculated field.

### Example Code

```Python
import traceback

import pydantic


class Model(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(extra='allow')

    main: str

    @property
    def something(self) -> str:
        raise AttributeError


instance = Model.model_validate(dict(main='test'))
try:
    instance.something
except AttributeError:
    traceback.print_exc()

instance = Model.model_validate(dict(main='test', another='test'))
try:
    instance.something
except AttributeError:
    traceback.print_exc()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /home/jmassucco/devel/monorepo/dist/export/python/virtualenvs/python-default/3.8.16/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, Jun  5 2024, 17:31:41)  [GCC 9.4.0]
                     platform: Linux-5.4.0-195-generic-x86_64-with-glibc2.2.5
             related packages: fastapi-0.115.2 pydantic-extra-types-2.9.0 mypy-1.12.0 pydantic-settings-2.6.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Thanks for investigating further. While the traceback can be confusing, there's nothing we can really do on our end. Raising an `AttributeError` will be used to signal `object.__getattribute__` that it should default to `__getattr__`. The exception is lost but this is how Python works in this case.

I assume the `AttributeError` from `something` is probably raised with a more complex scenario, but I would try to avoid having this exception raised inside properties.

Further reading:
https://stackoverflow.com/a/32191487
https://stackoverflow.com/a/52732020

**Comment by Viicos** [comment]
However, we can avoid raising the `AttributeError` from the `KeyError` inside `BaseModel.__getattr__`. PRs welcomed, or I can handle it tomorrow.
