### ISSUE TITLE
enum fields different behavior in a python versions

### ISSUE THREAD

**Issue by KonstantinKlepikov** [pydantic/pydantic#10830]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

is that expected behavior&

### Example Code

```Python
class LoggerLevels(str, enum):
    INFO = 'INFO'


class LoggingSettings(BaseModel):
    """Logging settings"""

    log_level: LoggerLevels = LoggerLevels.INFO
    model_config = ConfigDict(use_enum_values=True)

settings = LoggingSettings()

# in a python 3.11.9
# settings.log_level -> LoggerLevels.INFO a enum class

# in a python 3.12.5
# settings.log_level -> LoggerLevels.INFO.value a enum value
```

### Python, Pydantic & OS Version

```Text
debian, ubuntu 22.04
3.11.9, 3.12.5
pydantic = "^2.4.2"
pydantic-settings = "^2.5.2"
pydantic-core = "^2.23.4"
```

**Comment by Viicos** [comment]
I can't reproduce: I get `<LoggerLevels.INFO: 'INFO'>` in both versions. Note that you'll want to use [`validate_default`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.validate_default) so that `use_enum_values` applies when not providing any value for `log_level`.
