### ISSUE TITLE
Allow local variables that are outside of the schema

### ISSUE THREAD

**Issue by ValentinCalomme** [pydantic/pydantic#1084]
# Feature Request

* OS: **Windows**
* Python version: **3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]**
* Pydantic version : **1.2**

There is currently the possibility to make use of class variables inside a model, for instance:

```py
class Foo(pydantic.BaseModel):
    
    x: str = "hello world"
        
    def foo(self):
        self.class_variables.y = "bye mars"
        
    class class_variables:
        pass
```

This is neat as these variables are not part of the Schema. Would it be possible to add the possibility to do the same thing but with local variables? Perhaps add this as a config parameter? For instance:

```py
class Foo(pydantic.BaseModel):
    
    x: str = "hello world"
        
    def foo(self):
        self._.y = "bye mars"
        
    class Config:
        allow_local = True
```

**Comment by samuelcolvin** [comment]
I'm not clear on the use case for this. Probably best to implement it yourself as you do in the first example.

**Comment by ValentinCalomme** [comment]
If I'm not mistaken, this would raise an error since "_" isn't part of the model

```python
class Foo(pydantic.BaseModel):
    
    x: str = "hello world"
        
    def foo(self):
        self._.y = "bye mars"
        
    class Config:
        allow_local = True
``` 

And using values stored in "Config" is not an option because they are class variables. I'm looking for variables that are proper to the instance they are in

**Comment by samuelcolvin** [comment]
I'm still not clear why you want this?

**Comment by ValentinCalomme** [comment]
Let's assume I have some object storing a list of floats. For convenience, I might want to create a few properties such as max, min, std, mean, etc. What if:

* the properties are slow to compute but only need to be computed once
* there are too many properties to simply pre-compute all of them at instance creation
* I never want these properties to be part of the schema

I would like to do something like this:
```
from typing import List

import pydantic

class Foo(pydantic.BaseModel):
    
    x: List[float]
      
    @property
    def slow_property(self):
        if not hasattr(self, "_.max_x"):
            self._.max_x = max(x)
        return self._.max_x

    class Config:
        allow_local = True
```

This way, once the property is accessed, its result can be stored. As far as I know, this isn't yet possible in Pydantic, but I might be mistaken.

One solution could be to add fields that should always be excluded, however, this doesn't allow for dynamically named variables.

Hope this clarifies it!

**Comment by dmontagu** [comment]
Something that confused me about this question at first — “class variables” usually means something different than the way you seem to be using the term — it means variables that are attributes of the `class` rather than specific to instances.

One thing that might cover some of your desired usage is to use `cached_property` in python 3.8, which is like `property`, but caches the computed value. (In python <3.8 you can `pip install cached_property` and `from cached_property import cached_property`).

**Comment by dmontagu** [comment]
@samuelcolvin I have found myself wanting this on occasion as well; I think it is sort of the inverse issue to the problem of having serializable properties. It seems similar to me to the idea of setting attributes in the `__post_init__` of a dataclass. That said, I don’t think I’ve ever found a circumstance where I felt like having non-field instance variables on a pydantic mode was the *best*, or even a clean solution to a problem I faced. Usually when I’ve accomplished workarounds that achieve this effect, I eventually come up with a refactored way of achieving the goal that is preferable. (In particular, I do use `cached_property` with some frequency, and I think that usually does the job.)

**Comment by ValentinCalomme** [comment]
@dmontagu thanks for taking the time to try to understand what I struggled to express. I will definitely check out cached_property!

I think your assessment is fair enough, there is typically always a better way to solve the problem

**Comment by samuelcolvin** [comment]
Also see #1035

**Comment by dmontagu** [comment]
We have better support for cached_property and computed_fields by default in v2, which may help address this, and there are other approaches now that may be better (e.g., private attributes). If anyone has similar questions in the future, we can re-open this issue then.
