### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by gsakkis** [pydantic/pydantic#10854]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I ran into an obscure edge case when defining a model field as `date: date | None = None`. Other variations work; see example.

### Example Code

```Python
from __future__ import annotations

import datetime
from dataclasses import dataclass
from datetime import date
from typing import Optional

from pydantic import BaseModel

datetype = date


@dataclass
class FooDataclass:
    date: date | None = None


class FooModel(BaseModel):
    # works
    # date: date | None

    # works
    # date: datetime.date | None = None

    # works
    # date: date = None

    # works
    # date: Optional[date] = None

    # works
    # date: datetype | None = None

    # works
    # start_date: date | None = None

    # raises TypeError
    date: date | None = None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
               python version: 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:26:25) [Clang 17.0.6 ]
                     platform: macOS-15.1-arm64-arm-64bit
             related packages: typing_extensions-4.12.2 pydantic-settings-2.4.0
                       commit: unknown
```

**Comment by Viicos** [comment]
See the warning in: https://docs.pydantic.dev/dev/concepts/models/#basic-model-usage. The description of the [`PYD005`](https://github.com/Viicos/flake8-pydantic?tab=readme-ov-file#pyd005---field-name-overrides-annotation) rule from `flake8-pydantic` gives more context.

**Comment by gsakkis** [comment]
That's a bit unfortunate, the warning is not quite accurate (at least in the context `from __future__ import annotations`):
> Because of how Python evaluates [annotated assignment statements](https://docs.python.org/3/reference/simple_stmts.html#annassign)

This is not a Python issue, it's a Pydantic issue; the dataclass example works just fine.

**Comment by Viicos** [comment]
> This is not a Python issue, it's a Pydantic issue; the dataclass example works just fine.

The dataclass example works fine with `from __future__ import annotations`, which is equivalent to:

```python
@dataclass
class FooDataclass:
    date: "date | None" = None
```

And stdlib dataclasses don't perform any type annotation evaluation. But without stringified annotations, you get the same error (or if you call `typing.get_type_hints(FooDataclass, globals())`).

**Comment by Viicos** [comment]
It's even more unfortunate for these ones. Taking `date: Optional[date] = None` as an example:

the `date` symbol inside `Optional[...]` will resolve to the same assignment. In our case, the `date` field is assigned a default value of `None`. We thus end up with something equivalent to `date: Optional[None] = None`, or, simplified: `date: None = None`.

We don't get any runtime error as it is perfectly fine for `Optional` to be parametrized with `None`. However, Pydantic will think that the `date` field can only be `None`, which isn't the case.

**Comment by gsakkis** [comment]
Oh wow, indeed that's even worse. Thanks for the explanation!
