### ISSUE TITLE
`TypeAdapter` should have a nice repr

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#10870]
This is very poor `<pydantic.type_adapter.TypeAdapter object at 0x1030ec2f0>`.

it should show the type as prettily as we can.

**Comment by Viicos** [comment]
@sydney-runkle, relates to https://github.com/pydantic/pydantic/pull/10537/files#r1837161007. Although we have our `display_as_type` function, might be good to check how [Sphinx does it](https://github.com/sphinx-doc/sphinx/blob/80ed1b4cd1a5290106f2bff528b27f0bf16fb32a/sphinx/util/typing.py#L381).

**Comment by sydney-runkle** [comment]
Working on this now.
