### ISSUE TITLE
Wrong parent namespace fetched when using an explicitly parametrized `TypeAdapter`

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#10892]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

From https://github.com/pydantic/pydantic/issues/10889:

Because `TypeAdapter` is generic, parametrizing the class results in an instance of a `typing._GenericAlias`:

```python
from pydantic import TypeAdapter

TAInt = TypeAdapter[int]
TAInt.__class__
#> typing._GenericAlias
```

`_GenericAlias` proxies almost everything to it's origin, including `__call__`, so that the following works:

```python
ta = TypeAdapter[int](int)
ta.__class__
#> TypeAdapter
```

However, inside `TypeAdapter.__init__`, we use the parent frame (supposedly the one where the `TypeAdapter` instance was created) to grab the namespaces for type evaluation. Because `_GenericAlias` acts as a proxy, it adds an extra frame in the call stack: calling `TypeAdapter[int]` actually calls `_GenericAlias.__call__`, which then calls `self.__origin__(...)`.

When fetching the namespaces, we end up in the `_GenericAlias.__call__` frame, thus pulling everything from the `typing` module.

The following test is thus failing currently:

```python
from pydantic import TypeAdapter

Text = int

assert TypeAdapter[int]('Text').core_schema == {'type': 'int'}
#> AssertionError: core_schema == {'type': 'str'}, because `typing.Text` is defined as `str`
```

### Python, Pydantic & OS Version

```Text
main
```

**Comment by mpkocher** [comment]
This is a nice write up to clarify the core issue. 

When the parameterized type is inconsistent, is a runtime error raised? Or is this error mode on the static analysis tools side of the fence? 

For example,

```python
T = TypeAdapter[int](str)
```

**Comment by Viicos** [comment]
> When the parameterized type is inconsistent, is a runtime error raised? Or is this error mode on the static analysis tools side of the fence?

No runtime error is raised as it would require implementing static type checking semantics in Pydantic which is out of scope (and I'm not sure the runtime implementation of `_GenericAlias` would allow this). The type checker will error on it though.
