### ISSUE TITLE
Broken Link V1.10 Docs

### ISSUE THREAD

**Issue by jaredenorris** [pydantic/pydantic#10908]
In the version 1.10 Docs there is a broken link in the overview section. If you click on the link for the open source project stepmex it will take you to a Github 404 not found page. Perhaps this link should be removed?

```
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.10.0b2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jared/pydantic_repo/pydantic/pydantic
               python version: 3.9.13 (main, Aug 25 2022, 18:29:29)  [Clang 12.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.12.2
                       commit: 81b886c2```

**Comment by sydney-runkle** [comment]
@jaredenorris,

Thanks for the report! Yep, we'll fix that broken link.

**Comment by jaredenorris** [comment]
You're welcome. Can you please assign me the issue?

**Comment by sydney-runkle** [comment]
@jaredenorris, sure - can you please open a PR against `1.10.X-fixes`?

**Comment by jaredenorris** [comment]
@sydney-runkle I'm having trouble finding the V1.10 docs within the repo. Can you please point me in the right direction?

**Comment by Joshualover** [comment]
Great find! The link to stepmex in the overview section is indeed broken (404).

This is a small but important fix - broken links hurt the user experience and can confuse contributors.

**Suggestion**: Remove the broken link or update it to the correct repository if stepmex still exists.

Would be happy to help verify and fix this! 🚀
