### ISSUE TITLE
2.10: AnyHttpUrl is no longer subclass of pydantic_core.Url (according to mypy)

### ISSUE THREAD

**Issue by mjuhlin1** [pydantic/pydantic#10920]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using pydantic<2.10.0, mypy says AnyHttpUrl is subclass of Url. With pydantic 2.10.0, it's not anymore.
Is that intended?

### Example Code

```Python
from pydantic import AnyHttpUrl
from pydantic_core import Url

foo = AnyHttpUrl("https://www.google.com/")

print(isinstance(foo, Url))
# True in 2.9
# False in 2.10
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0
        pydantic-core version: 2.27.0
          pydantic-core build: profile=release pgo=false
                 install path: /home/userx/proj/internal/task_runner/.virtualenv/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Oct 10 2023, 11:46:07) [GCC 9.4.0]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: mypy-1.6.1 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi!

Thanks for your question. This is indeed intended. All single host url variants are now subclasses of `AnyUrl`, and the `pydantic_core` `Url` structure will just be used internally.

You can [read more here](https://pydantic.dev/articles/pydantic-v2-10-release#migrate-to-subclassing-instead-of-annotated-approach-for-pydantic-url-types) about the URL changes 👍
