### ISSUE TITLE
"le" and "ge" date values for date fields although they should float

### ISSUE THREAD

**Issue by zopyx** [pydantic/pydantic#10923]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The "le" and "ge" properties of the Field class are annotated as "float".
However, it is possible to define a date field and assign a date instance for "le" or "ge" (and it is working fine).
Is this an implementation invariant or just a documentation failure? 
It appears that "le" and "ge" are accepted in general values of the same type as the field value and standard comparison is applied. 

### Example Code

```Python
from pydantic import BaseModel, Field

from datetime import date

class Foo(BaseModel):

    d: date = Field(..., ge=date(2024, 1, 1), le=date(2024,12,31))

f = Foo(d=date(2025, 1, 1))
```

### Python, Pydantic & OS Version

```Text
backend) ➜  backend git:(main) ✗ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/ajung/src/eon/GEP/backend/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Oct  8 2024, 00:20:25) [Clang 18.1.8 ]
                     platform: Linux-6.8.0-48-generic-x86_64-with-glibc2.39
             related packages: pydantic-settings-2.2.1 fastapi-0.111.0 mypy-1.13.0 pyright-1.1.389 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Fixed on v2.10 :)

See https://github.com/pydantic/pydantic/blob/a5d5c237fe99f24d32afbb591e17c876ab258d98/pydantic/fields.py#L63-L66
