### ISSUE TITLE
tool for creating validation errors more easily

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#1094]
Currently "synthetically" creating `ValidationError`s isn't that easy.

It's useful when you want your error to end up in standard format (e.g. standard JSON in a response) but the error requires db lookups etc. which can't be done in validators

maybe something like:
```py
def create_validation_error(errors: Sequence[Tuple[Union[Exception, str], Loc]], model: BaseModel) -> ValidationError:
   ...
```
Perhaps with easy route to create for just one error.

**Comment by dmontagu** [comment]
In v2, you can now use `ValidationError.__init__` to create these errors. Please reopen if the current functionality is not sufficient for some reason.
