### ISSUE TITLE
PrivateAttr not working when using it in dataclasses in python 3.11

### ISSUE THREAD

**Issue by Estebanrg21** [pydantic/pydantic#10951]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When trying to use `PrivateAttr` as a value to specify private fields, an exception is raised.
The exception message is the following:
```
ValueError: mutable default <class 'pydantic.fields.ModelPrivateAttr'> for field _pv_prop is not allowed: use default_factory
```
Checking the [python documentation](https://docs.python.org/3.11/library/dataclasses.html#mutable-default-values), it says that in version 3.11, I quote ,`unhashable objects are now not allowed` therefore, I think, the issue shown in this ticket.

Thanks in advance!

### Example Code

```Python
from pydantic import PrivateAttr
from pydantic.dataclasses import dataclass

@dataclass
class MyClass:
    name:str
    _pv_prop: str = PrivateAttr()

    def __post_init__(self):
        self._pv_prop = "test"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0
        pydantic-core version: 2.27.0
          pydantic-core build: profile=release pgo=false
                 install path: /usr/local/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Sep 11 2024, 00:00:00) [GCC 11.5.0]
                     platform: Linux-6.6.41-0-virt-x86_64-with-glibc2.34
             related packages: typing_extensions-4.12.2 fastapi-0.115.5
                       commit: unknown
```

**Comment by Viicos** [comment]
Private attributes were never explicitly supported, I'm opening https://github.com/pydantic/pydantic/issues/10985 to discuss it further.

**Comment by Estebanrg21** [comment]
@Viicos Excellent!! Is it possible to specify in the documentation that private attributes are not supported for dataclasses?

**Comment by Viicos** [comment]
Depending on the outcome of https://github.com/pydantic/pydantic/issues/10985, yes this may be documented as being (un)supported.
