### ISSUE TITLE
Signature of "__replace__" incompatible - RootModel

### ISSUE THREAD

**Issue by jorgebodega** [pydantic/pydantic#10970]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi!

I'm trying to update some projects where I'm using `RootModel`, and found some problems with the new `__replace__` protocol and `mypy`.

With a simple configuration on `mypy.ini` like this:

```
[mypy]
plugins = pydantic.mypy
python_version = 3.13
strict = True
```

It's raising an error like this:

```
Signature of "__replace__" incompatible with supertype "BaseModel"
     Superclass:
         def __replace__(self, **changes: Any) -> Pets
     Subclass:
         def __replace__(*, root: list[str] = ...) -> Pets
```

[The basic example from the documentation](https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types) is also raising this error:

```
class Pets(RootModel[list[str]]):
    def describe(self) -> str:
        return f'Pets: {", ".join(self.root)}'
```

Thank you in advance!

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.1
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: <...>/.venv/lib/python3.13/site-packages/pydantic
               python version: 3.13.0 (main, Oct  8 2024, 01:04:00) [Clang 18.1.8 ]
                     platform: Linux-6.6.62-1-lts-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2 mypy-1.13.0
                       commit: unknown
```

**Comment by mpkocher** [comment]
If the core issue is specific to `RootModel`, perhaps consider updating the title of the issue.
