### ISSUE TITLE
'Url' type casts left around when serializing model to a dictionary

### ISSUE THREAD

**Issue by eskultety** [pydantic/pydantic#10998]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When serializing a model using URLs back to a dictionary, provided the URLs are properly represented, and validated using any of the network URL types, `Url/AnyUrl/HttpUrl` are explicitly formatted as type casts to the serialized dictionary  (depending on the exact pydantic v2 release)  which makes it hard to deterministically compare data as plain dictionaries in unit tests.
I used the word "deterministically" because prior pydantic  2.10.2 it seems like all URL types where formatted as `Url(<url>)`, but after **2.10.2** where there were adjustments to the URL validation constraints the actual types are honored in the serialized dictionary.
I don't think the type casts should be dumped to a serialized dictionary once a model has been successfully validated, making it completely transparent to the user what the model does/did in the background.

[1] https://docs.pydantic.dev/latest/concepts/serialization/#modelmodel_dump

### Example Code

```Python
from typing import Optional
from pydantic import BaseModel, AnyUrl
from pprint import pprint


class SubModel(BaseModel):
    bar: AnyUrl
    baz: int = 1


class MainModel(BaseModel):
    foo: Optional[str] = None
    submodels: list[SubModel] = []


m = {
    "foo": "foo",
    "submodels":
        [
            {"bar": "https://example.com"},
            {"bar": "http://www.example.com/path", "baz": 2}
        ],
}

pprint(MainModel.model_validate(m).model_dump())


>>> python3 test.py
{'foo': 'foo',
 'submodels': [{'bar': AnyUrl('https://example.com/'), 'baz': 1},
               {'bar': AnyUrl('http://www.example.com/path'), 'baz': 2}]}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
pydantic-core version: 2.27.1
pydantic-core build: profile=release pgo=false
python version: 3.12.7 (main, Oct  1 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
platform: Linux-6.11.5-200.fc40.x86_64-x86_64-with-glibc2.39
related packages: mypy-1.13.0 typing_extensions-4.12.2 mypy-1.13.0 typing_extensions-4.12.2
```

**Comment by sydney-runkle** [comment]
Hi!

Thanks for your question. I don't think this is something we're going to change now - we're trying to reduce further churn on the url front, and this behavior is much more like that which you'd expect from other concrete python classes.

That being said, one of the following solutions might be helpful to you:

```py
class SubModel(BaseModel):
    bar: Annotated[AnyUrl, PlainSerializer(lambda x: x._url)]
    baz: int = 1
```

```py
class SubModel(BaseModel):
    bar: Annotated[AnyUrl, PlainSerializer(lambda x: str(x))]
    baz: int = 1
```

I'd recommend the second approach, as it makes deterministic comparisons easier, and it doesn't depend on internal implementation details of the url class variations.

Hope this helps. Happy to chat more if you have questions!

**Comment by sydney-runkle** [comment]
A bit of further explanation - here's some [motivation](https://pydantic.dev/articles/pydantic-v2-10-release#migrate-to-subclassing-instead-of-annotated-approach-for-pydantic-url-types) regarding why we changed behavior!

**Comment by eskultety** [comment]
> Hi!
> 
> Thanks for your question. I don't think this is something we're going to change now - we're trying to reduce further churn on the url front, and this behavior is much more like that which you'd expect from other concrete python classes.
> 

@sydney-runkle thank you for the answer. My bad for not reading https://docs.pydantic.dev/latest/concepts/serialization thoroughly, more specifically https://docs.pydantic.dev/latest/concepts/serialization/#dictmodel-and-iteration which would have not led me to creating this issue.

> ```python
> class SubModel(BaseModel):
>     bar: Annotated[AnyUrl, PlainSerializer(lambda x: str(x))]
>     baz: int = 1
> ```

Is ^this somehow preferable (or more recommended) over
```python
class Submodel(BaseModel):
   bar: AnyUrl

   @field_serializer('bar', when_used='always')
    def serialize_url(self, bar: AnyUrl):
        return str(bar)
```
Is there a practical difference other than being less verbose?
