### ISSUE TITLE
Validators are applied to empty optional fields

### ISSUE THREAD

**Issue by daninfpj** [pydantic/pydantic#1099]
# Bug

Please complete:
* OS: **macOS 10.14.6**
* Python version `import sys; print(sys.version)`: **3.7.4**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **1.3a1**

Where possible please include a self-contained code snippet describing your bug:

```py
from typing import Optional

from pydantic import validator
from pydantic.dataclasses import dataclass

@dataclass
class MyDataclass:
    a: str
    b: Optional[str] = None

    @validator('a', 'b')
    def must_include_space(cls, v):
        if ' ' not in v:
            raise ValueError('must contain space')
        return v

MyDataclass(a='With space')
```

Since `b` is `Optional` and has a default value of `None`, you’d expect `MyDataclass(a='With space')` to be valid, but the code above fails with:

```
pydantic.error_wrappers.ValidationError: 1 validation error for MyDataclass
b
  argument of type 'NoneType' is not iterable (type=type_error)
```

IMO, the expected behavior is that validators are not applied to empty optional fields.

**Comment by dmontagu** [comment]
It looks like this is specific to pydantic dataclasses, and is happening due to this line:

https://github.com/samuelcolvin/pydantic/blob/5510a13f6ce2b3909aced8e1ae6a23fea4484862/pydantic/dataclasses.py#L80

The problem as I understand it is that 3.7 dataclasses don't give you a way to tell whether an attribute was obtained via a default value or via passing the argument. So when pydantic goes to do validation, there is no way for it to realize that it should ignore the un-provided default.

@samuelcolvin Any ideas here? One approach would be to just raise a warning/exception for dataclasses with validators on fields with default values that don't have `always=True`.

Maybe it would be possible to override the `__init__` to track which fields were provided vs. not? Sounds like maybe more pain than its worth though; not sure.

**Comment by samuelcolvin** [comment]
@daninfpj thanks so much for reporting this.

@dmontagu I've just read through `dataclasses._init_fn`. yuk. We definitely don't want to implement our own `__init__`.  I think your warning/exception approach is the only option.

**Comment by daninfpj** [comment]
I’m not sure the difference lies in whether the value was provided vs. not.

The way most common validators work (i.e. Rails Active Record Validations) is that the only validate optional fields against other rules if a value is present (regardless of if it was provided).

In my example above, this should also be valid:

```python
values = {'a': 'With space'}
MyDataclass(a=values.get('a'), b=values.get('b'))
```

A case that comes to mind is the values coming from GET or POST parameters.

[My current workaround](https://github.com/Fondeadora/stpmex-python/commit/be0ebc6afc662b818be0210be4e57a72a138a60f#diff-80888d6646e8046e4e4a0c73780e7ad9R9) for this is skipping the validators if the field allows None (`field.allow_none`) and its value is None.

**Comment by samuelcolvin** [comment]
> I’m not sure the difference lies in whether the value was provided vs. not.

It does. That's how pydantic works. It's the intended (and I would argue correct) behaviour.

> My current workaround for this is skipping the validators if the field allows None

Looks good to me, you could also just do `if value is None: return` in each validator which would be more explicit.

**Comment by adriangb** [comment]
I think this is resolved in Pydantic V2. That said, you should still handle the 

```python
from typing import Optional

from pydantic import field_validator
from pydantic.dataclasses import dataclass


@dataclass
class MyDataclass:
    a: str
    b: Optional[str] = None

    @field_validator('a', 'b')
    def must_include_space(cls, v: Optional[str]):
        if v is None:
            return v
        if ' ' not in v:
            raise ValueError('must contain space')
        return v

MyDataclass(a='With space')  # this works even without the `if v is None` because defaults are not validated
MyDataclass(a=' ', b=None)  # adding `if v is None` makes this work, as discussed above this is how it is going to be
```
