### ISSUE TITLE
Unexpected value on setting default 

### ISSUE THREAD

**Issue by khaled-ha** [pydantic/pydantic#10999]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```
class Data(BaseModel): 
    id: int = Field(default="")
```
![Capture d'écran 2024-11-28 170513](https://github.com/user-attachments/assets/5d791343-c282-4113-bdbc-274f00b8953f)

Setting type for property id doesn't is not working properly , in case there are no values it will set the default to "" , it seems that there is a missing validation for default value on pydantic .

### Example Code

```Python
from pydatic import BaseModel, Field

class Data(BaseModel): 
    id: int = Field(default="")

data = Data()
data.id

data2 = Data(id='')
```

### Python, Pydantic & OS Version

```Text
i'm using ubuntu 22, python 3.12 and pydantic =>2 .
```

**Comment by mpkocher** [comment]
I believe you might want to set `validate_default=True`.

`id: int = Field(default="", validate_default=True)`

https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.validate_default

**Comment by khaled-ha** [comment]
thx for your response .

**Comment by Viicos** [comment]
Thanks @mpkocher.
