### ISSUE TITLE
pydantic.networks.KafkaDsn type prohibits a valid bootstrap.servers values

### ISSUE THREAD

**Issue by alexkudryavtsev88** [pydantic/pydantic#10996]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! 

I use `pydantic.networks.KafkaDsn` type to validate `bootstrap_servers` value in my Kafka ProducerSettings / ConsumerSettings classes (derived from the `pydantic.BaseSettings`).

My `bootstrap_servers` values stored in ENV variables has the following format:
- "vm-kafka-envname-0.company_name.cloud:9093"
- "vm-kafka-envname-1.company_name.cloud:9093"
e.t.c

Today I've updated Pydantic version to 2.10.2, and after that I've faced with `pydantic.ValidationError`, raised upon my service's start:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for function-wrap[wrap_val()]
  URL scheme should be 'kafka' [type=url_scheme, input_value='vm-kafka-envname-0.company_name.cloud:9093', input_type=str]
```

When I try to set `bootstrap_servers` value as "localhost:9093" - I've got the same `ValidationError`.

### Example Code

```Python
from pydantic import KafkaDsn

bootstrap_servers_raw = "vm-kafka-envname-0.company_name.cloud:9093,vm-kafka-envname-1.company_name.cloud:9093"

# the line bellow worked fine in pydantic 2.9.2, but raises ValidationError in pydantic 2.10.2
bootstrap_servers_validated = [KafkaDsn(url=url) for url in bootstrap_servers_raw.split(",")]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/al.n.kudryavtsev/Projects/recsys-gp-stocks/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Mar 18 2024, 20:12:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: pydantic-settings-2.6.1 mypy-1.12.0 fastapi-0.115.5 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by alexkudryavtsev88** [comment]
@mpkocher thank you for the answer. I've checked the source code and it looks like for now (from the 2.10 version), `KafkaDsn` works similar to another `pydantic.network` types (`RedisDsn`, `MongoDsn`, e.t.c.) and now it validates does the passed Url start with the `kafka://`

Adding the `kafka://` to my Url's head leads to the following error: 
`%4|1733124761.741|BROKER|rdkafka#consumer-1| [thrd:app]: Broker name "kafka://vm-kafka-envname-0.company_name.cloud:9093" parse error: unsupported protocol "KAFKA"`

I used `confluent_kafka` lib, and when I check logs, I see that used Security Protocol name is added automatically to the passed `bootstrap.servers` Url's Head (as `sasl_ssl://vm-kafka-envname-0.company_name.cloud:9093` or `plaintext://vm-kafka-envname-0.company_name.cloud:9093`). 
So, when my `bootstrap.servers` Url (in ENV variables) starts with `kafka://` that leads to constructing the Url that's incorrect at all: `sasl_ssl://kafka://vm-kafka-envname-0.company_name.cloud:9093`

**Comment by mpkocher** [comment]
@alexkudryavtsev88 Perhaps consider using `AnyUrl`. It looks like there's a fundamental friction point here when configuring kafka in a TLS setting with the current implementation of `KakfaDsn`. 

The underlying lib (`confluent_kafka`)  is the fundamental source of truth for the definition of what URL/DSN is supported in your application. Not sure if the `KakfaDsn` layer is really adding a lot here. Validating that the URL is valid at the Pydantic layer is probably good enough.

**Comment by alexkudryavtsev88** [comment]
@mpkocher  yes, using `AnyUrl` is a solution, because the `confluent_kafka` client (producer or consumer) expects `bootstrap.servers` as just `$host:$port` and there are no any another constraints for the `bootstrap.servers` value.  
But, being a `pydantic` lib User, it's insteresting for me, what the `KafkaDsn` type should be used for? Maybe I don't get some case(s) when it's usable for validation.
