### ISSUE TITLE
support multiple Field in Annotated for create_model()

### ISSUE THREAD

**Issue by dlax** [pydantic/pydantic#11005]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

For field definitions passed to `create_model()` as `Annotated` values, only the first `FieldInfo` value is used. This is fine and documented, but it's on the other hand surprising as other annotations, especially other `FieldInfo` values, are silently ignored: 
```python
>>> d = pydantic.create_model(
...     'DynamicModel',
...     f=Annotated[
...         int,
...         pydantic.Field(default=0, title='titled'),
...         pydantic.Field(default=1, description='described'),
...     ],
... )
... 
>>> json.dumps(d.model_json_schema(), indent=2)
{
  "properties": {
    "f": {
      "default": 0,
      "title": "titled",
      "type": "integer"
    }
  },
  "title": "DynamicModel",
  "type": "object"
}
```
The behaviour is different from "static" definitions:
```python
>>> class StaticModel(pydantic.BaseModel):
...     f: Annotated[
...         int,
...         pydantic.Field(default=0, title='titled'),
...         pydantic.Field(default=1, description='described'),
...     ]
... 
>>> print(json.dumps(StaticModel.model_json_schema(), indent=2))
{
  "properties": {
    "f": {
      "default": 1,
      "description": "described",
      "title": "titled",
      "type": "integer"
    }
  },
  "title": "StaticModel",
  "type": "object"
}
```
I'm suggesting to add support for multiple `Field` values in `Annotated` for `create_model()` such as the first example about would work the same as the second one; I think we should also emit a warning about other annotations that are ignored.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
@sydney-runkle I find the `create_model` API related to to field specification quite flawed. Currently, it is not possible to:
- provide more than one metadata attribute when using the `Annotated` form (as per this feature request).
- provide something else than `Field` as a metadata.

Meaning we can't do:

```python
create_model(
    'Model',
    f1=Annotated[int, BeforeValidator(some_val)],
    f2=Annotated[int, Field(...), Field(...)],
)
```

Instead, I think we should just allow two forms:
- a two-tuple, the first element being the type annotation, the second one the default value (~ to `f: <typ> = <default>`)
- a single element, representing the type annotation (~ to `f: <typ>`).

This way, we support the same features than normal class definition, and this removes a bunch of checks in the `create_model` implementation. Hopefully this can be done without introducing breaking changes.
