### ISSUE TITLE
mypy fails to typecheck inherited model with a field alias

### ISSUE THREAD

**Issue by koterpillar** [pydantic/pydantic#11009]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a model:
* Inherits another model
* Overrides a field
* Sets an alias for it

mypy fails to typecheck the result complaining about `__replace__` taking the _aliased_ field name but not the _original_ field name.

I have found this issue updating a project for Python 3.13, there might be other issues with replace functionality but I'll open them separately.

### Example Code

```Python
from pydantic import BaseModel, Field


class One(BaseModel):
    foo: str


class Two(One):
    foo: str = Field(..., alias="bar")

# Signature of "__replace__" incompatible with supertype "One"  [override]
#     Superclass:
#         def __replace__(*, <SNIP>, foo: str = ...) -> One
#     Subclass:
#         def __replace__(*, <SNIP>, bar: str = ...) -> Two
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/alex/.cache/pypoetry/virtualenvs/mybox-YUnsYrZx-py3.13/lib/python3.13/site-packages/pydantic
               python version: 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
                     platform: Linux-6.11.8-300.fc41.x86_64-x86_64-with-glibc2.40
             related packages: mypy-1.13.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
While your code is technically unsafe, reported LSP violations by mypy can be annoying. Because this is not the first report we had related to `__replace__`, I've raised https://github.com/python/mypy/issues/18216. You can subscribe to this issue to be updated.

**Comment by Viicos** [comment]
Fixed in https://github.com/python/mypy/pull/18464.
