### ISSUE TITLE
Can't override constraints with annotations in version 2.10

### ISSUE THREAD

**Issue by abompard** [pydantic/pydantic#11007]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In pydantic 2.9 I could use annotations to override constraints in types. In 2.10 it doesn't work anymore but the docs still mention that is should be possible.

### Example Code

```Python
from pydantic import AnyUrl, UrlConstraints
from typing_extensions import Annotated

DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]

print(DbUrl("sqlite:///:memory:"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/abompard/Fedora/libs/sqlalchemy-helpers/.tox/py312-sqla2/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Oct  1 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
                     platform: Linux-6.11.6-300.fc41.x86_64-x86_64-with-glibc2.40
             related packages: typing_extensions-4.12.2 pydantic-settings-2.6.1
                       commit: unknown
```

**Comment by mpkocher** [comment]
The validation mechanism only works within the context of BaseModel or TypeAdapter. 

https://docs.pydantic.dev/latest/api/type_adapter/

```python
from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel
from typing_extensions import Annotated

DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
class A(BaseModel):
    x: DbUrl
print((A(x="sqlite:///:memory:"),))
```

Outs:

```bash
(A(x=AnyUrl('sqlite:///:memory:')),)
```

Or

```python
print((TypeAdapter(DbUrl).validate_python("sqlite:///:memory:"),))
```

Outs:

```bash
(AnyUrl('sqlite:///:memory:'),)
```

Another example:

```bash
In [14]: from pydantic import PositiveInt, TypeAdapter

In [15]: PositiveInt(-7)
Out[15]: -7

In [16]: TypeAdapter(PositiveInt).validate_python(-1)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)

ValidationError: 1 validation error for constrained-int
  Input should be greater than 0 [type=greater_than, input_value=-1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.10/v/greater_than
```

**Comment by abompard** [comment]
> The validation mechanism only works within the context of BaseModel or TypeAdapter.

Thanks for the explanation! Then how do I set defaut values? I'm trying to do something like:

```python
from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel
from typing_extensions import Annotated

DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
class A(BaseModel):
    x: DbUrl = DbUrl("sqlite:///:memory:"))
print(A())
```

This fails when the module is parsed because, I suppose, of the instanciation of DbUrl as a default value.

**Comment by mpkocher** [comment]
> ```python
> from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel
> from typing_extensions import Annotated
> 
> DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
> class A(BaseModel):
>     x: DbUrl = DbUrl("sqlite:///:memory:"))
> print(A())
> ```
> 
> This fails when the module is parsed because, I suppose, of the instanciation of DbUrl as a default value.

I think you have an extra `)`. 

```python
from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel
from typing_extensions import Annotated

DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
class A(BaseModel):
    x: DbUrl = DbUrl("sqlite:///:memory:")
print(A())
```

Outs:

```bash
In [2]: from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel
   ...: from typing_extensions import Annotated
   ...: 
   ...: DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
   ...: class A(BaseModel):
   ...:     x: DbUrl = DbUrl("sqlite:///:memory:")
   ...: print(A())
x=Url('sqlite:///:memory:')
```

But I don't think this works as expected. There's a subtle issue here with validating the default value. 

I believe it should be:

```python
from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel, Field
from typing_extensions import Annotated

DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
class A(BaseModel):
    x: DbUrl = Field(default=DbUrl("sqlite:///:memory:"), validate_default=True)
print(A())
```

https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.validate_default

**Comment by abompard** [comment]
Hey! Thanks again. The code you proposed errors out with a traceback here:

```
$ cat testanyurl.py
from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel, Field
from typing_extensions import Annotated

DbUrl = Annotated[AnyUrl, UrlConstraints(host_required=False)]
class A(BaseModel):
    x: DbUrl = DbUrl("sqlite:///:memory:")
print(A())

$ .tox/py312-sqla2/bin/python testanyurl.py 
Traceback (most recent call last):
  File ".../testanyurl.py", line 5, in <module>
    class A(BaseModel):
  File ".../testanyurl.py", line 6, in A
    x: DbUrl = DbUrl("sqlite:///:memory:")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/typing.py", line 1184, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.tox/py312-sqla2/lib/python3.12/site-packages/pydantic/networks.py", line 122, in __init__
    self._url = _build_type_adapter(self.__class__).validate_python(url)._url
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.tox/py312-sqla2/lib/python3.12/site-packages/pydantic/type_adapter.py", line 412, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for function-wrap[wrap_val()]
  Input should be a valid URL, empty host [type=url_parsing, input_value='sqlite:///:memory:', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/url_parsing

$ .tox/py312-sqla2/bin/pip freeze | grep pydantic
pydantic==2.10.2
pydantic-settings==2.6.1
pydantic_core==2.27.1
```

Am I not using the right version?

**Comment by Viicos** [comment]
The URL types API is still not ideal, and hopefully could be reworked in the future but this is tricky without having to rethink the whole design and thus breaking existing usage.

@abompard, in 2.10.3 (planned today), you will be able to do the following:

```python
from pydantic import AnyUrl, UrlConstraints, TypeAdapter, BaseModel
from typing_extensions import Annotated

class A(BaseModel):
    x: AnyUrl = AnyUrl("sqlite:///:memory:")
```

`AnyUrl` will not have the host required, as it was previously in 2.9. Setting `validate_default=True` is also unnecessary, as instantiating `AnyUrl` will also perform validation.

**Comment by mpkocher** [comment]
@Viicos @sydney-runkle 

It looks like the current design means that the `UrlConstraints` can only be applied in one place using a subclassing mechanism? The `TypeAdapter` call in `__init__` is applying the constraints.  Using Annotation (or combining a subclass+annotation) can yield an inconsistent set of constraints. They aren't composeable because of that validation call within `__init__`. 

A contrived example. 

```python
A = Annotated[AnyUrl, UrlConstraints(host_required=True)]
B = Annotated[A, UrlConstraints(host_required=False)]
```

Or 

```python
class A(AnyUrl):
    _constraints =  UrlConstraints(host_required=True)

B = Annotated[A, UrlConstraints(host_required=False)]
```

If you want everything to be done via subclassing, that's fine. However, it's seems stylistically a bit different than other types  defined within pydantic. When you define constraints on an `int`, pydantic will collapse the constraints into a single value. For example, defining `Annotated[Annotated[int, Gt(0)], Gt(1)]` will yield `Gt(1)` as the constraint. 

There's also this other issue where the constraints can fundamentally change the type from `None | str` to `str` (e.g, `host_required=True`).  This easier to solve in the subclassing approach (but will be slightly verbose to write these methods/property out).
