### ISSUE TITLE
🐞 `type` doesn't work for aliased type

### ISSUE THREAD

**Issue by jd-solanki** [pydantic/pydantic#11011]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi 👋🏻 

I think this is related to #8984 #9782

I'm building complex system and for that I had to properly name things and due to that I wrote code like below snippet.

In below syntax if I directly use `JSONType` in model it works however when I alias `JSONType` and assign it to `WorkflowItem` and then use it inside model then it fails with error:
```shell
pydantic_core._pydantic_core.SchemaError: Definitions error: definition `__main__.JSONType:128842577850624` was never filled
```

### Example Code

```Python
from pydantic import BaseModel

type JSONType = str | int | float | bool | None | dict[str, "JSONType"] | list["JSONType"]

type WorkflowItem = JSONType


class Works(BaseModel):
    data: list[JSONType]


class Fails(BaseModel):
    data: list[WorkflowItem]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.1
        pydantic-core version: 2.23.3
          pydantic-core build: profile=release pgo=false
                 install path: /home/jd/Projects/mine/wrapwithai/backend/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.7 (main, Nov  6 2024, 18:29:01) [GCC 14.2.0]
                     platform: Linux-6.11.0-8-generic-x86_64-with-glibc2.40
             related packages: fastapi-0.114.0 typing_extensions-4.12.2 pydantic-settings-2.4.0
                       commit: unknown
```

**Comment by Viicos** [comment]
Fixed in 2.10.

Side note: if you make use of the new `type` syntax, you don't need to use stringified annotations, the alias is lazily evaluated. Instead you can use:

```python
type JSONType = str | int | float | bool | None | dict[str, JSONType] | list[JSONType]
```
