### ISSUE TITLE
Field aliases don't work with replace

### ISSUE THREAD

**Issue by koterpillar** [pydantic/pydantic#11010]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Generalized `replace` doesn't take into account field aliases.

When a field has an alias, generated `__replace__` (and therefore `copy.replace` in Python 3.13) only recognizes the original field name and not the alias.

I expect parity between constructor (accepts the alias), attribute access (accepts the alias) and replace (only accepts the original name).

See also #11009.

### Example Code

```Python
from copy import replace
from pydantic import BaseModel, Field


class One(BaseModel):
    foo: str = Field(..., alias="bar")


one = One(bar="a")
print(one)
one1 = replace(one, foo="b")
print(one1)  # replaced
one2 = replace(one, bar="c")
print(one2)  # not replaced

print(one.foo)  # AttributeError as expected
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/alex/.cache/pypoetry/virtualenvs/mybox-YUnsYrZx-py3.13/lib/python3.13/site-packages/pydantic
               python version: 3.13.0 (main, Oct  8 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
                     platform: Linux-6.11.8-300.fc41.x86_64-x86_64-with-glibc2.40
             related packages: mypy-1.13.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Internally, `BaseModel.__replace__` forwards the call to [`model_copy`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_copy). Pydantic does not perform any validation with the provided data, and the alias logic is part of the validation process. As such, you should provide the original field name.

The behavior is debatable (maybe in particular regarding `copy.replace`), but I believe most of the `model_copy`/`copy.replace` calls are performed using data you know about.

Besides, invalid [identifiers](https://docs.python.org/3/reference/lexical_analysis.html#identifiers) can be used in aliases:

```python
class Model(BaseModel):
    a: int = Field(alias='invalid-id')
```

If we were to use aliases, you'd have to call `replace` this way: `copy.replace(model_inst, **{'invalid-id': 1})`.
