### ISSUE TITLE
ValidationError thrown with Nested Optional BaseModel if key and class name are the same

### ISSUE THREAD

**Issue by bertoneone** [pydantic/pydantic#11030]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Validation error when:
- Nesting BaseModel classes in combination with not required `Optional[] = None` fields
- Using a BaseModel class name as the type for the Optional field identical to the key of field itself
- Providing a Record with the field inside

Expected result:
- No validation error since a "Not required, can be None, is None by default" field can be provided with the format specified by the BaseModel subclass used as type in the Optional field.

It's way easier to show an example rather than to describe this, but in short:

```py
class Fails(BaseModel):
    not_important: int

class Element(BaseModel):
    Fails: Optional[Fails] = None  # doesn't fail if we rename the field key
```

This will fail as long as the field key "Fails" equals the class name "Fails" and is used in the `Optional[Fails] = None` notation for not required fields.

### Example Code

```Python
from pydantic import BaseModel
from typing import Optional

class TEST1(BaseModel):
    a: int 

class TEST2(BaseModel):
    b: int 

class OVER(BaseModel):
    c: Optional[TEST1] = None
    d: Optional[TEST2] = None
 
ok = b'{"c":{"a":0},"d":{"b":0}}'
OVER.model_validate_json(ok)
# OK -> Out[19]: OVER(c=TEST1(a=0), d=TEST2(b=0))

class OVER2(BaseModel):
    TEST1: Optional[TEST1] = None
    d: Optional[TEST2] = None 

not_ok = b'{"TEST1":{"a":0},"d":{"b":0}}'
OVER2.model_validate_json(not_ok)
# VALIDATION ERROR
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.2
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /home/kb/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Oct 27 2023, 12:18:15) [GCC 12.2.0]
                     platform: Linux-6.1.0-26-amd64-x86_64-with-glibc2.36
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
See the warning in https://docs.pydantic.dev/latest/concepts/models/#basic-model-usage.
