### ISSUE TITLE
model_construct in combination with AliasChoice in model's fields raises Error

### ISSUE THREAD

**Issue by cspisla** [pydantic/pydantic#11046]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When you have a model that uses AliasChoice, the model_construct function raises an error on this line:
pydantic/main.py, line 216, in model_construct:
 ```
for name, field in cls.model_fields.items():
            if field.alias and field.alias in values:
                fields_values[name] = values.pop(field.alias)
```

because field.alias is an Instance of AliasChoice and not string (I guess).
I didn't find any note that you can't use both together.
Thank you.

### Example Code

```Python
from pydantic import BaseModel, Field, AliasChoices
    class ExampleModel(BaseModel):
        some_field:int = Field(alias=AliasChoices('alias_1', 'alias_2'))
    ExampleModel.model_construct(alias_1=1)
```

### Python, Pydantic & OS Version

```Text
python3 -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/cs/miniconda3/envs/show_business/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0]
                     platform: Linux-6.5.0-45-generic-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.0.3 fastapi-0.104.0 typing_extensions-4.12.2
```

**Comment by Viicos** [comment]
`alias` can only be a string (as it is used for serialization as well, it doesn't make sense to have `AliasChoices` for serialization). Instead, you will have to use `validation_alias` (see [docs](https://docs.pydantic.dev/latest/concepts/alias/)).
