### ISSUE TITLE
OpenAPI 3.1.1 Annotated Enumerations support

### ISSUE THREAD

**Issue by while0pass** [pydantic/pydantic#11050]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be great if `enum.Enum` objects can be represented as a set of annotated values in the UI of API docs.

Please, see:
- https://spec.openapis.org/oas/v3.1.1.html#annotated-enumerations
- https://spec.openapis.org/oas/v3.1.1.html#model-with-annotated-enumeration

An example of possible coding experience:
```python
import enum
from typing import Annotated
from pydantic import json_schema_description, json_schema_title, BaseModel, Field

class ColorModel(enum.StrEnum):
  RGB: Annotated[
    str, json_schema_description('Specify colors with the red, green, and blue additive color model'),
    json_schema_title('RGB')
  ] = 'RGB'
  CMYK: Annotated[
    str, json_schema_description('Specify colors with the cyan, magenta, yellow, and black subtractive color model')
  ] = 'CMYK'

class Form(BaseModel):
  colorModel: ColorModel = Field(default=ColorModel.RGB, description='Color model')
```

An example of sort of matching UI experience (made with https://editor-next.swagger.io/ ):

![image](https://github.com/user-attachments/assets/64fbf053-c778-4d47-984c-303e2de098f2)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi,

Thanks for your feature request! At the moment, Python doesn't support annotations for enum members.

I might recommend you follow the [customizing json schema](https://docs.pydantic.dev/latest/concepts/json_schema/#customizing-json-schema) docs if you'd like this custom behavior!

Specifically, you might try this approach: https://github.com/pydantic/pydantic/pull/9029#issuecomment-2155012411.

Going to close for now :)
