### ISSUE TITLE
[v2.10] No overloads for `Field` match the provided arguments

### ISSUE THREAD

**Issue by Pwuts** [pydantic/pydantic#11052]
The added overload of #10781 + #10972 seems to cause type errors with this `Field` wrapper:
```py
def SchemaField(
    default: T | PydanticUndefinedType = PydanticUndefined,
    *args,
    default_factory: Optional[Callable[[], T]] = None,
    title: Optional[str] = None,
    description: Optional[str] = None,
    placeholder: Optional[str] = None,
    advanced: Optional[bool] = False,
    secret: bool = False,
    exclude: bool = False,
    hidden: Optional[bool] = None,
    **kwargs,
) -> T:
    json_extra = {
        k: v
        for k, v in {
            "placeholder": placeholder,
            "secret": secret,
            "advanced": advanced,
            "hidden": hidden,
        }.items()
        if v is not None
    }

    return Field(
        default,
        *args,
        default_factory=default_factory,
        title=title,
        description=description,
        exclude=exclude,
        json_schema_extra=json_extra,
        **kwargs,
    )
```
<details>
<summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/79fe187a-307a-4be9-9b39-baacec236ef0)
</details>

```
No overloads for "Field" match the provided arguments
  Argument types: (T@SchemaField | PydanticUndefinedType, *tuple[Unknown, ...], (() -> T@SchemaField) | None, str | None, str | None, bool, dict[str, Unknown], **dict[str, Unknown])
```

This error does not occur with Pydantic v2.9.2.

I have tried a few things (removing `*args`, passing `default` as a kwarg, removing the type annotations for `default` and the return type) but none of that resolved the error for me.

_Originally posted by @Pwuts in https://github.com/pydantic/pydantic/issues/10781#issuecomment-2520955981_

**Comment by Viicos** [comment]
This is expected. Pydantic does not provide support for external libraries extending our `Field` function/`FieldInfo` class. We know some libraries do (e.g. FastAPI), but we don't recommend doing so.

In 2.10, we added overloads to the `Field` function to better type check the following:

```python
class Model(BaseModel):
    a: int = Field(default="string")  # type checker error
    b: str = Field(default_factory=lambda: 1)  # type checker error
```

The path of least resistance would be to either:
- update your `SchemaField` signature to be up to date with Pydantic (note that we also modified the `default_factory` type hint, it is now `Callable[[], T] - Callable[[dict[str, Any]], T]`). But I'm not sure this will solve the typing issues.
- Add a type ignore comment.

**Comment by Pwuts** [comment]
It's expected that a minor version update breaks existing code? That isn't clear from the release notes or docs as far as I can tell.

**Comment by Viicos** [comment]
This is not a breaking change: as I mentioned, you are wrapping a call to the Pydantic `Field` function, and we never explicitly supported this. We added mutually exclusive overloads to the function so that `default` and `default_factory` provided at the same time results in a type checking error. This is an improvement and not a breaking change, as providing both already raised a runtime error. As a consequence, any wrapped call to the function will have to add a `type: ignore` comment because type checkers can't assume that `default` and `default_factory` are mutually from the caller's side.

**Comment by Pwuts** [comment]
> We added mutually exclusive overloads to the function so that `default` and `default_factory` provided at the same time results in a type checking error. This is an improvement and not a breaking change, as providing both already raised a runtime error.

Ah, that's fair. Thank you for the context!
