### ISSUE TITLE
Model docstring/description dropped for generic models

### ISSUE THREAD

**Issue by flxdot** [pydantic/pydantic#11058]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

First of all, I'm not 100% sure if that is the intended behavior, but it was a surprise to me.

Whenever a generic model gets an actual type, it suddenly loses its docstring and therefore its `description` attribute in the resulting JSON schema.

I noticed that the generated OpenAPI specification was missing the documentation of our generic classes.

The change could be as easy as adding one line

```diff
    created_model = meta(
        model_name,
        bases,
        namespace,
        __pydantic_generic_metadata__={
            'origin': origin,
            'args': args,
            'parameters': params,
        },
        __pydantic_reset_parent_namespace__=False,
        **kwds,
    )    
+   created_model.__doc__ = origin.__doc__

    model_module, called_globally = _get_caller_frame_info(depth=3)
```

after the creation of the new model at 
https://github.com/pydantic/pydantic/blob/32f405bcf6171602ffe754f1fca1681c5ddee96e/pydantic/_internal/_generics.py#L137-L150

### Example Code

```Python
from pydantic import BaseModel
from typing import TypeVar, Generic

Item = TypeVar("Item")


class Pagination(BaseModel, Generic[Item]):
    """Some description"""

    page: int
    page_cnt: int
    page_size: int
    items: list[Item]


assert "description" in Pagination.model_json_schema()
assert "description" in Pagination[str].model_json_schema()  # <-- this fails
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: .../.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.6.1-arm64-arm-64bit
             related packages: fastapi-0.115.6 pydantic-settings-2.6.1 mypy-1.13.0 pydantic-extra-types-2.10.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@flxdot,

Thanks for bringing this to our attention! Let me chat with our team and see if this is intentional. I'll get back to you shortly!

**Comment by sydney-runkle** [comment]
Hey! Following up on this - chatted with the team, we don't think it makes sense to carry over the docstring for this case, as you might have a docstring that describes the generic class (unparametrized) that doesn't make sense to port to a parametrized subclass.

That being said, you can manually fix this with something like:

```py
from pydantic import BaseModel
from typing import TypeVar, Generic

Item = TypeVar('Item')


class Pagination(BaseModel, Generic[Item]):
    """A generic Pagination class."""

    page: int
    items: list[Item]


class PaginationInt(Pagination[int]):
    """Pagination for ints."""

    pass


assert 'description' in Pagination.model_json_schema()
assert 'description' in PaginationInt.model_json_schema()
```

Or, with 

```py
PaginationInt = Pagination[Int]
PaginationInt.__doc__ = '...'
```

**Comment by channingko-madden** [comment]
For anyone coming across this like me, a workaround I found is to add the description to the model_config.

```python
class Pagination(BaseModel, Generic[Item]):
    """A generic Pagination class."""

    page: int
    items: list[Item]

    model_config = ConfigDict(
        json_schema_extra={
            "description": "Some description"
        }
    )
```

Just be careful that a class which inherits `Pagination` and also defines its own `model_config["json_schema_extra"]`, it will override the one in `Pagination` when the two classes' `model_config` is merged and the description will be lost.
