### ISSUE TITLE
Pydantic 2.10.x not installable from Azure devops due to description size

### ISSUE THREAD

**Issue by lexnicolaes** [pydantic/pydantic#11071]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm using a custom PyPi feed on Azure DevOps to download and install Pydantic. Currently version 2.9.2 resolves just fine, but when attempting to dowload a 2.10 version, the request fails due to the project description being too large.

`  ERROR: HTTP error 400 while getting http://devops.mycompany.com/tfs/Company/_packaging/8cd5f6a9-9d7f-4a2e-bee1-ff8af1230f15/pypi/download/pydantic/2.10.3/pydantic-2.10.3-py3-none-any.whl#sha256=be04d85bbc7b65651c5f8e6b9976ed9c6f41782a55524cef079a34a0bb82144d (from http://devops.mycompany.com/tfs/Company/_packaging/OSSUpstream/pypi/simple/pydantic/) (requires-python:>=3.8)
ERROR: Could not install requirement pydantic from http://devops.mycompany.com/tfs/Company/_packaging/8cd5f6a9-9d7f-4a2e-bee1-ff8af1230f15/pypi/download/pydantic/2.10.3/pydantic-2.10.3-py3-none-any.whl#sha256=be04d85bbc7b65651c5f8e6b9976ed9c6f41782a55524cef079a34a0bb82144d because of HTTP error 400 Client Error: Bad Request - The package description exceeds the maximum length of 324608 bytes. (DevOps Activity ID: AE586E5D-7BD2-4ECE-861A-5972364FDA12) for url: http://devops.mycompany.com/tfs/Company/_packaging/8cd5f6a9-9d7f-4a2e-bee1-ff8af1230f15/pypi/download/pydantic/2.10.3/pydantic-2.10.3-py3-none-any.whl for URL http://devops.mycompany.com/tfs/Company/_packaging/8cd5f6a9-9d7f-4a2e-bee1-ff8af1230f15/pypi/download/pydantic/2.10.3/pydantic-2.10.3-py3-none-any.whl#sha256=be04d85bbc7b65651c5f8e6b9976ed9c6f41782a55524cef079a34a0bb82144d (from http://devops.mycompany.com/tfs/Company/_packaging/OSSUpstream/pypi/simple/pydantic/) (requires-python:>=3.8)`

Having a look at older issues I can see that many before encountered the same problem, eg in #8148, #8136, #8105,#8125 and seems to been previously been fixed in version 2.5.1. Is there a known regression?

Looking at the PyPi, the description indeed contains the FULL 2.x change history. Is it an idea to only include the relevant changes to the current version in the release description, or simply referring to the HISTORY.md file, which was created for this purpose? 

### Python, Pydantic & OS Version

```Text
N/A
```

**Comment by sydney-runkle** [comment]
@lexnicolaes,

Thanks for reporting. I can fix this for v2.10.4!

**Comment by lexnicolaes** [comment]
Thank you, much appreciated! 😄
