### ISSUE TITLE
multiple test failures 2.5.3

### ISSUE THREAD

**Issue by Apteryks** [pydantic/pydantic#11086]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The test suite fails like:

```
Hi,

Running the test suite of pydantic 2.5.3, I see:
```
[...]
tests/test_validators.py:588: Failed
____________________________________ test_assert_raises_validation_error _____________________________________

    def test_assert_raises_validation_error():
        class Model(BaseModel):
            a: str
    
            @field_validator('a')
            @classmethod
            def check_a(cls, v: Any):
                assert v == 'a', 'invalid a'
                return v
    
        Model(a='a')
    
        with pytest.raises(ValidationError) as exc_info:
            Model(a='snap')
        injected_by_pytest = "assert 'snap' == 'a'\n  - a\n  + snap"
>       assert exc_info.value.errors(include_url=False) == [
            {
                'ctx': {'error': HasRepr(repr(AssertionError("invalid a\nassert 'snap' == 'a'\n  - a\n  + snap")))},
                'input': 'snap',
                'loc': ('a',),
                'msg': f'Assertion failed, invalid a\n{injected_by_pytest}',
                'type': 'assertion_error',
            }
        ]
E       assert [{'type': 'assertion_error', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap", 'input': 'snap', 'ctx': {'error': AssertionError("invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap")}}] == [{'ctx': {'error': HasRepr('AssertionError("invalid a\\nassert \'snap\' == \'a\'\\n  - a\\n  + snap")')}, 'input': 'snap', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  - a\n  + snap", 'type': 'assertion_error'}]
E         
E         At index 0 diff: {'type': 'assertion_error', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap", 'input': 'snap', 'ctx': {'error': AssertionError("invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap")}} != {'ctx': {'error': HasRepr('AssertionError("invalid a\\nassert \'snap\' == \'a\'\\n  - a\\n  + snap")')}, 'input': 'snap', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  - a\n  + snap", 'type': 'assertion_error'}
E         
E         Full diff:
E           [
E               {
E                   'ctx': {
E         -             'error': HasRepr('AssertionError("invalid a\\nassert \'snap\' == \'a\'\\n  - a\\n  + snap")'),
E         ?                      ---------                         -         -     -     -  -          -           --
E         +             'error': AssertionError("invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap"),
E         ?                                                                      +++
E                   },
E                   'input': 'snap',
E                   'loc': (
E                       'a',
E                   ),
E                   'msg': 'Assertion failed, invalid a\n'
E                   "assert 'snap' == 'a'\n"
E         +         '  \n'
E                   '  - a\n'
E                   '  + snap',
E                   'type': 'assertion_error',
E               },
E           ]

tests/test_validators.py:1309: AssertionError
_________________________________ test_root_validator_allow_reuse_same_field _________________________________

    def test_root_validator_allow_reuse_same_field():
>       with pytest.warns(UserWarning, match='`root_val` overrides an existing Pydantic `@root_validator` decorator'):
E       pydantic.warnings.PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/

tests/test_validators.py:2514: PydanticDeprecatedSince20
============================================ slowest 10 durations ============================================
0.46s call     tests/test_generics.py::test_generics_work_with_many_parametrized_base_models
0.35s call     tests/test_json_schema.py::test_multiple_parametrization_of_generic_model
0.20s call     tests/test_generics.py::test_caches_get_cleaned_up
0.10s call     tests/test_pickle.py::test_pickle_pydantic_weakref
0.08s call     tests/test_generics.py::test_partial_specification_instantiation
0.07s call     tests/test_exports.py::test_dataclass_import
0.07s call     tests/test_exports.py::test_dataclass_import2
0.07s call     tests/test_types_typeddict.py::test_grandparent_config
0.06s call     tests/test_generics.py::test_caches_get_cleaned_up_with_aliased_parametrized_bases
0.05s call     tests/test_main.py::test_arbitrary_type_allowed_validation_success
========================================== short test summary info ===========================================
FAILED tests/test_config.py::TestsBaseConfig::test_config_class_is_deprecated - pydantic.warnings.PydanticDeprecatedSince20: BaseConfig is deprecated. Use the `pydantic.ConfigDict` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_config.py::TestsBaseConfig::test_config_class_attributes_are_deprecated - pydantic.warnings.PydanticDeprecatedSince20: BaseConfig is deprecated. Use the `pydantic.ConfigDict` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_simple_copy[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_deep_copy[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_exclude - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_include - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_include_exclude - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_advanced_exclude - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_advanced_include - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_advanced_include_exclude - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_update[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_update_unset[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_deep_extra[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_set_fields[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_undefined[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_immutable_copy_with_frozen[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_update_exclude - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_shallow_copy_modify[copy] - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_construction.py::test_copy_with_excluded_fields - pydantic.warnings.PydanticDeprecatedSince20: The copy method is deprecated; use `model_copy` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_from_attributes_root - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_from_attributes - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_not_from_attributes - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_object_with_getattr - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_properties - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_extra_allow_from_orm[ignore] - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_extra_allow_from_orm[forbid] - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_extra_allow_from_orm[allow] - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_root_validator - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_nested_orm - pydantic.warnings.PydanticDeprecatedSince20: The `from_orm` method is deprecated; set `model_config['from_attributes']=True` and use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_parse_raw_pass - pydantic.warnings.PydanticDeprecatedSince20: load_str_bytes is deprecated. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_parse_raw_pass_fail - pydantic.warnings.PydanticDeprecatedSince20: load_str_bytes is deprecated. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_field_include_deprecation - pydantic.warnings.PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'include'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_parse_file - pydantic.warnings.PydanticDeprecatedSince20: load_file is deprecated. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_copy_and_set_values - pydantic.warnings.PydanticDeprecatedSince20: The private method `_copy_and_set_values` will be removed and should no longer be used. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_get_value - pydantic.warnings.PydanticDeprecatedSince20: The private method `_get_value` will be removed and should no longer be used. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_deprecated.py::test_deprecated_module - pydantic.warnings.PydanticDeprecatedSince20: schema_of is deprecated. Use pydantic.TypeAdapter.json_schema instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
FAILED tests/test_generics.py::test_serialize_unsubstituted_typevars_bound_default_supported - NotImplementedError: Pydantic does not support mixing more than one of TypeVar bounds, constraints and defaults
FAILED tests/test_json_schema.py::test_callable_fallback_with_non_serializable_default[Cannot generate a JsonSchema for core_schema.CallableSchema \\[skipped-choice\\]] - pydantic.json_schema.PydanticJsonSchemaWarning: Default value <function test_callable_fallback_with_non_serializable_default.<locals>.Model.<lambda> at 0x7f5f4b600e50> is not JSON serializable; excluding default from JSON schema [non-serializable-default]
FAILED tests/test_json_schema.py::test_callable_fallback_with_non_serializable_default[Default value .* is not JSON serializable; excluding default from JSON schema \\[non-serializable-default\\]] - pydantic.json_schema.PydanticJsonSchemaWarning: Cannot generate a JsonSchema for core_schema.CallableSchema [skipped-choice]
FAILED tests/test_validators.py::test_use_bare - Failed: DID NOT WARN. No warnings of type (<class 'pydantic.warnings.PydanticDeprecatedSince20'>,) were emitted.
 Emitted warnings: [].
FAILED tests/test_validators.py::test_use_no_fields - Failed: DID NOT WARN. No warnings of type (<class 'pydantic.warnings.PydanticDeprecatedSince20'>,) were emitted.
 Emitted warnings: [].
FAILED tests/test_validators.py::test_validator_bad_fields_throws_configerror - Failed: DID NOT WARN. No warnings of type (<class 'pydantic.warnings.PydanticDeprecatedSince20'>,) were emitted.
 Emitted warnings: [].
FAILED tests/test_validators.py::test_assert_raises_validation_error - assert [{'type': 'assertion_error', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap", 'input': 'snap', 'ctx': {'error': AssertionError("invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap")}}] == [{'ctx': {'error': HasRepr('AssertionError("invalid a\\nassert \'snap\' == \'a\'\\n  - a\\n  + snap")')}, 'input': 'snap', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  - a\n  + snap", 'type': 'assertion_error'}]
  
  At index 0 diff: {'type': 'assertion_error', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap", 'input': 'snap', 'ctx': {'error': AssertionError("invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap")}} != {'ctx': {'error': HasRepr('AssertionError("invalid a\\nassert \'snap\' == \'a\'\\n  - a\\n  + snap")')}, 'input': 'snap', 'loc': ('a',), 'msg': "Assertion failed, invalid a\nassert 'snap' == 'a'\n  - a\n  + snap", 'type': 'assertion_error'}
  
  Full diff:
    [
        {
            'ctx': {
  -             'error': HasRepr('AssertionError("invalid a\\nassert \'snap\' == \'a\'\\n  - a\\n  + snap")'),
  ?                      ---------                         -         -     -     -  -          -           --
  +             'error': AssertionError("invalid a\nassert 'snap' == 'a'\n  \n  - a\n  + snap"),
  ?                                                                      +++
            },
            'input': 'snap',
            'loc': (
                'a',
            ),
            'msg': 'Assertion failed, invalid a\n'
            "assert 'snap' == 'a'\n"
  +         '  \n'
            '  - a\n'
            '  + snap',
            'type': 'assertion_error',
        },
    ]
FAILED tests/test_validators.py::test_root_validator_allow_reuse_same_field - pydantic.warnings.PydanticDeprecatedSince20: Pydantic V1 style `@root_validator` validators are deprecated. You should migrate to Pydantic V2 style `@model_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
=================== 44 failed, 4023 passed, 187 skipped, 2 deselected, 7 xfailed in 11.18s ===================
```
I'm not sure, but perhaps the deprecation warnings are causing the tests to fail? This is using Python 3.10.7 and the following direct inputs:
```
python-annotated-types@0.6.0 python-cloudpickle@3.1.0 python-dirty-equals@0.8.0
+ python-faker@33.1.0 python-hatch-fancy-pypi-readme@24.1.0 python-hatchling@1.26.3
+ python-pydantic-core@2.14.6 python-pytest-benchmark@4.0.0 python-pytest-mock@3.14.0 python-pytest@8.3.3
+ python-typing-extensions@4.12.2
```

### Example Code

```Python
N/A
```

### Python, Pydantic & OS Version

```Text
2.5.3

Python is at 3.10.7.  Other direct dependencies used:

python-annotated-types@0.6.0 python-cloudpickle@3.1.0 python-dirty-equals@0.8.0
+ python-faker@33.1.0 python-hatch-fancy-pypi-readme@24.1.0 python-hatchling@1.26.3
+ python-pydantic-core@2.14.6 python-pytest-benchmark@4.0.0 python-pytest-mock@3.14.0 python-pytest@8.3.3
+ python-typing-extensions@4.12.2
```
```

**Comment by Apteryks** [comment]
I coudn't show most of the errors in the main message due to length restriction; please see the complete build log output in the previous message; thanks!

**Comment by Viicos** [comment]
You should use the provided versions in the `pdm.lock` lockfile. pytest 8 had breaking changes that were addressed in later Pydantic versions.

Out of curiosity, why are you trying to run tests on your own? On such an old Pydantic version?

**Comment by Apteryks** [comment]
> Out of curiosity, why are you trying to run tests on your own? On such an old Pydantic version?

Hi, that's the current version of Pydantic we carry in Guix; we should update it!  Thanks for letting me know there are fixes for the problem I reported in newer versions; I'm not sure why I didn't try it before reporting these (I usually would, as reporting bugs against old versions is rarely useful).

Per our packaging policy we try to have the test suites run successfully, which provides some reassurance that the components work together/basic quality check.
