### ISSUE TITLE
ValidationInfo returns a dict without `data` key? 

### ISSUE THREAD

**Issue by AHJiapengZhang** [pydantic/pydantic#11084]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/e6d6ec0b-f094-4b50-a6e7-f5655036a356">

I followed the document and use `info: ValidationInfo ` to handle other fields in the class. But some unit tests failed and when I debugged, I found this info was a dict instead of `ValidationInfo` and didn't have `data` attribute at all. 

### Example Code

```Python
from humps import camelize
from pydantic import BaseModel, ConfigDict
from datetime import datetime

class CamelCaseAliasModel(BaseModel):
    model_config = ConfigDict(alias_generator=camelize, populate_by_name=True)

class ForecastRequestDTO(CamelCaseAliasModel):
    promotion_id: str
    is_cumulative_promotion: bool
    start_date_time: datetime
    end_date_time: datetime

    @field_validator('end_date_time')
    @classmethod
    def check_enddate_after_startdate(
        cls, end_date_time: datetime, info: ValidationInfo
    ) -> datetime:
        start_date_time = info.data['start_date_time']
        if end_date_time.date() >= start_date_time.date():
            return end_date_time

        raise ValueError("The Startdate of the promotion can not be after the Enddate")

def test_check_enddate_after_startdate():
    end_date = datetime.strptime("2021-07-12T00:00:00Z", '%Y-%m-%dT%H:%M:%SZ')

    values = {'start_date_time': datetime.strptime("2021-08-10T00:00:00Z", '%Y-%m-%dT%H:%M:%SZ')}
    
    # Act, Assert
    with pytest.raises(
        ValueError, match="The Startdate of the promotion can not be after the Enddate"
    ):
        ForecastRequestDTO.check_enddate_after_startdate(end_date, values)
        
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/username/Library/Caches/pypoetry/virtualenvs/project/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Dec  2 2024, 14:36:53) [Clang 16.0.0 (clang-1600.0.26.4)]
                     platform: macOS-15.1.1-arm64-arm-64bit
             related packages: fastapi-0.115.6 pydantic-settings-2.6.1 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Why are you calling your `check_enddate_after_startdate` validator method directly?

**Comment by mpkocher** [comment]
Maybe a `model_validator` approach would be better? 

```python
from typing import Self
from pydantic import BaseModel, ConfigDict, model_validator
from datetime import datetime

class CamelCaseAliasModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True, validate_assignment=True)

class ForecastRequestDTO(CamelCaseAliasModel):
    promotion_id: str
    is_cumulative_promotion: bool
    start_date_time: datetime
    end_date_time: datetime

    @model_validator(mode="after")
    def check_enddate_after_startdate(self) -> Self:
        if self.end_date_time  >= self.start_date_time:
            return self
        raise ValueError(f"start ({self.start_date_time}) of the promotion can not be after the end ({self.end_date_time})")
```

Also:

- Maybe need to set `frozen=True`, or `validate_assignment=True`, otherwise, end/start time can be set without validation and your model will be fundamentally inconsistent. 
- Often TimeZone information is useful to require at the type level. `AwareDatetime` might be useful to consider. 

Docs:
- https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.validate_assignment
- https://docs.pydantic.dev/latest/api/functional_validators/#pydantic.functional_validators.model_validator
- https://docs.pydantic.dev/latest/api/types/#pydantic.types.AwareDatetime

**Comment by Viicos** [comment]
Well your test also needs to be updated to work for V2 as well. In V1, validators could take a `values` extra argument (see [docs](https://docs.pydantic.dev/1.10/usage/validators/)). in V2, this was changed as the second parameter is now a `ValidationInfo` instance. If you take a look at your test code, you are still passing a dictionary to the `info` argument.

Directly calling validators is not explicitly documented as being supported. I wouldn't suggest doing so. Instead, your test should instantiate the `ForecastRequestDTO` model (with a dummy `promotion_id` and `is_cumulative_promotion`), and assert that a `ValidationError` is raised if `end_date_time > start_date_time`.
