### ISSUE TITLE
Outdated documentation or unexpected behavior in use of `Field` with `Annotated`

### ISSUE THREAD

**Issue by candleindark** [pydantic/pydantic#11096]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This issue is related to #11095. The note in the ["Using `Annotated`"](https://docs.pydantic.dev/latest/concepts/fields/#default-values) section states that "the `Field.default` argument is not supported inside `Annotated`". However, I found this to be, no longer, true. The following code works as expected.

```python
from typing import Annotated

from pydantic import BaseModel, Field


class User(BaseModel):
    id: Annotated[str, Field(default="42")]

print(User().id)
"""
42
"""
```

### Python, Pydantic & OS Version

```Text
▶ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/isaac/Library/Application Support/hatch/env/virtual/dandisets-linkml-status-tools/lEMG0Emx/dandisets-linkml-status-tools/lib/python3.10/site-packages/pydantic
               python version: 3.10.15 (main, Nov 22 2024, 12:40:20) [Clang 16.0.0 (clang-1600.0.26.4)]
                     platform: macOS-15.1.1-arm64-arm-64bit
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@candleindark,

Thanks for the report. This is fixed on our most [recent](https://docs.pydantic.dev/dev/concepts/fields/#the-annotated-pattern) docs page, and will update when we release v2.10.4 :)
