### ISSUE TITLE
Memory leak with `issubclass(x, BaseModel)`

### ISSUE THREAD

**Issue by AdrienBM** [pydantic/pydantic#11100]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We ran into memory leaks while using pydantic, going up to 30GB+ of memory usage and crashing the process at this stage.

We investigated using memray, it comes from calls to `issubclass(x, BaseModel)` inside `create_model` (the 30GB+ usage is reached after ~5k calls to `create_model`)

Here is the stack trace of function calls inside pydantic that end up leaking memory, starting from `create_model`:
![Screenshot from 2024-12-12 12-49-19](https://github.com/user-attachments/assets/826b2091-1f19-4261-aaf7-4284d9e508f9)

It seems related to https://github.com/pydantic/pydantic/issues/3829 and https://github.com/python/cpython/issues/92810

We fixed it on our side by slightly modifying the `lenient_issubclass` definition in pydantic to add a specific path using MRO for `BaseModel` checks specifically:
```py
def lenient_issubclass(cls: Any, class_or_tuple: Any) -> bool:  # pragma: no cover
    from pydantic import BaseModel
    try:
        return isinstance(cls, type) and (any(supertype == BaseModel for supertype in cls.__mro__) if class_or_tuple == BaseModel else issubclass(cls, class_or_tuple))
    except TypeError:
        if isinstance(cls, _typing_extra.WithArgsTypes):
            return False
        raise  # pragma: no cover
``` 
instead of the original:
```py
def lenient_issubclass(cls: Any, class_or_tuple: Any) -> bool:  # pragma: no cover
    try:
        return isinstance(cls, type) and issubclass(cls, class_or_tuple)
    except TypeError:
        if isinstance(cls, _typing_extra.WithArgsTypes):
            return False
        raise  # pragma: no cover
``` 

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.0b1
pydantic-core version: 2.26.0
pydantic-core build: profile=release pgo=false
install path: /home/adrien/.pyenv/versions/3.12.3/envs/backend/lib/python3.12/site-packages/pydantic
python version: 3.12.3 (main, Jun 10 2024, 11:29:36) [GCC 9.4.0]
platform: Linux-5.15.0-125-generic-x86_64-with-glibc2.31
related packages: pydantic-settings-2.6.1 fastapi-0.115.5 typing_extensions-4.12.2
commit: unknown
```

**Comment by Viicos** [comment]
As I mentioned in https://github.com/python/cpython/issues/92810#issuecomment-2543828485, creating a subclass of the relevant ABC (in our case, `BaseModel`) is necessary. Thus, I managed to create the following MRE:

```python
from pydantic import BaseModel


for _ in range(5000):
    class Model(BaseModel):
        pass

    class Arbitrary:
        pass

    issubclass(Arbitrary, BaseModel)
```

Unlike bare classes, Pydantic models hold more memory (mostly taken by the `__pydantic_validator__`, `__pydantic_serializer__` and `__pydantic_core_schema__` attributes). With a slightly different example, I end up with ~2.5GiB of memory:

```python
from pydantic import BaseModel, create_model


for _ in range(5000):
    class Model(BaseModel):
        pass

    class Arbitrary:
        pass

    Model2 = create_model(
        'Model2',
        f1=Arbitrary,
        __config__={'arbitrary_types_allowed': True}
    )
```

Anyway, seems like in reality this was never really fixed in Pydantic, as https://github.com/pydantic/pydantic/pull/4081 implemented the wrong method (we need `__subclasscheck__`, not `__instancecheck__`).

**Comment by Viicos** [comment]
Just curious, are you creating models (using either `create_model` or "normal" subclass creation) when your application is running? Or only on startup? If the former, you might want to make sure models are properly gc'ed to avoid memory leaks (unrelated to the ABC usage).

**Comment by AdrienBM** [comment]
Thanks for the quick investigation!
We use `create_model` while the application is running. We don't keep any references to them currently, so they should be GC'ed normally, but thanks for the heads up, it's definitely something that we could do without realizing.
