### ISSUE TITLE
@validate_call decorator compatibility with async function 

### ISSUE THREAD

**Issue by royp-nrd** [pydantic/pydantic#11123]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Before @validate_call: inspect.iscoroutinefunction(foo) -> true
After @validate_call:inspect.iscoroutinefunction(foo) -> false
Expected behavior: @validate_call:inspect.iscoroutinefunction(foo) -> true

Not sure about the right solution here, it is a bit tricky, what do you think?

### Example Code

```Python
import inspect
from pydantic import validate_call


@validate_call
async def foo(x: int) -> int:
    return x + 1

print(inspect.iscoroutinefunction(foo))
```
Output: False

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.2
        pydantic-core version: 2.23.4
          pydantic-core build: profile=release pgo=false
                           python version: 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.4-arm64-arm-64bit
             related packages: pydantic-settings-2.6.1 fastapi-0.115.5 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Fixed in 2.10.
