### ISSUE TITLE
field shape wrong for native sequence types

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#1112]
Please complete:
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **master**

While working on #1111 I noticed that `field.shape` is not set correctly for native sequence types:

```py
from pydantic import BaseModel


class Model(BaseModel):
    a: list
    b: set
    c: frozenset
    d: dict
    e: tuple


for name, field in Model.__fields__.items():
    debug(name, field, field.shape)

"""
test.py:13 <module>
    name: 'a' (str) len=1
    field: ModelField(
        name='a',
        type=list,
        required=True,
    ) (ModelField)
    field.shape: 1 (int)
test.py:13 <module>
    name: 'b' (str) len=1
    field: ModelField(
        name='b',
        type=set,
        required=True,
    ) (ModelField)
    field.shape: 1 (int)
test.py:13 <module>
    name: 'c' (str) len=1
    field: ModelField(
        name='c',
        type=frozenset,
        required=True,
    ) (ModelField)
    field.shape: 1 (int)
test.py:13 <module>
    name: 'd' (str) len=1
    field: ModelField(
        name='d',
        type=dict,
        required=True,
    ) (ModelField)
    field.shape: 1 (int)
test.py:13 <module>
    name: 'e' (str) len=1
    field: ModelField(
        name='e',
        type=tuple,
        required=True,
    ) (ModelField)
    field.shape: 1 (int)
"""
```

Currently the only known consequence of this is that the schema will be wrong, I guess `per_item` also won't work.

Should be possible to fix without breaking other functionality.

**Comment by kousikmitra** [comment]
@samuelcolvin I would like to work on the issue. As I have understood that `field.shape` is not having the correct value as the type defined in the model.

**Comment by samuelcolvin** [comment]
Great, yes please. Good luck!

**Comment by kousikmitra** [comment]
@samuelcolvin I found the issue. In `pydantic/fields.py:ModelField._type_analysis()` where the `field.shape`  field get assign depending on the `field` type. `getattr(self.type_, '__origin__', None)` is returning `None` so the function is getting returned from there without assigning the value to `field.shape` variable.

https://github.com/samuelcolvin/pydantic/blob/e65d11240a6febcd569ad44a61e2374eb00b9ba6/pydantic/fields.py#L355-L358

**Comment by dmontagu** [comment]
It looks like if you just convert the various checks from lines ~382 - ~420 into a separate function, you could call that function on `self.type_` when `origin` is `None`, and otherwise on `origin`, and get the right behavior.

@kousikmitra Would you like to submit a PR fixing this?

**Comment by kousikmitra** [comment]
@dmontagu Yes i will open a PR. Thanks

**Comment by dmontagu** [comment]
The field.shape property is now removed in v2 and there is nothing similar, so I'm going to close this issue.
