### ISSUE TITLE
Use of numpy DTypeLike as a typehint results in PydanticUserError

### ISSUE THREAD

**Issue by samimia-swks** [pydantic/pydantic#11120]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Python 3.11.10 (main, Oct 16 2024, 04:38:48) [Clang 18.1.8 ] on linux
pydantic v2.10.3
pydantic-core v2.27.1

On python 3.11 the following code results in 
```
pydantic.errors.PydanticUserError: Please use `typing_extensions.TypedDict` instead of `typing.TypedDict` on Python < 3.12.` 
```

Changing the `dtype: DTypeLike = np.float32` line to say `dtype: type[np.float32] = np.float32` gets rid of the error. 

The issue does not exist on 3.12.

DTypeLike is explained here: https://numpy.org/devdocs/reference/typing.html#numpy.typing.DTypeLike

### Example Code

```Python
import numpy as np
from numpy.typing import DTypeLike
from pydantic import BaseModel, ConfigDict

class Coeff(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    num: int = 1
    dtype: DTypeLike = np.float32
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.10.3
        pydantic-core version: 2.27.1
          pydantic-core build: profile=release pgo=false
                 install path: .direnv/python-3.11.10/lib/python3.11/site-packages/pydantic
               python version: 3.11.10 (main, Oct 16 2024, 04:38:48) [Clang 18.1.8 ]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: mypy-1.13.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
This is due to the fact that `DypeLike` is defined as a (very complex) union, with one of the members of the union defined as a `TypedDict` (and we enforce `typing_extensions.TypedDict` to be used on Python < 3.12 for runtime introspection reasons).

Because you want to treat `DTypeLike` as an arbitrary type anyway, I would suggest doing the following:

```python
from typing import TYPE_CHECKING, Any

import numpy as np
from pydantic import BaseModel, ConfigDict

if TYPE_CHECKING:
    from numpy.typing import DTypeLike
else:
    DTypeLike = Any

class Coeff(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    num: int = 1
    dtype: DTypeLike = np.float32
```
