### ISSUE TITLE
Documentation: adding explanation on how to add custom pickling of Pydantic BaseModels

### ISSUE THREAD

**Issue by ValentinCalomme** [pydantic/pydantic#1116]
* OS: **Windows**
* Python version: **3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]**
* Pydantic version : **1.2**

# Feature Request

In my project, I needed to serialize an object using pickle, due to some problems with pickle's basic implementation with that particular object, I needed to customize the pickling process. Typically, this happens simply by implementing `__getstate__(self)` and `__setstate__(self, state)`. Sadly, at first, it didn't work and I didn't understand why. After searching through Pydantic's source code I saw that pickling was implemented as follows:

```py
    def __getstate__(self) -> 'DictAny':
        return {'__dict__': self.__dict__, '__fields_set__': self.__fields_set__}

    def __setstate__(self, state: 'DictAny') -> None:
        object.__setattr__(self, '__dict__', state['__dict__'])
        object.__setattr__(self, '__fields_set__', state['__fields_set__'])
```

I then changed my own implementation to fit this and it worked like a charm.

Hence my request. Should this be mentioned in any way in the documentation? So that others who may want to implement custom `__getstate__(self)` and `__setstate__(self, state)` don't run into the same errors I did?

**Comment by samuelcolvin** [comment]
Absolutely, pr welcome.

**Comment by mg3146** [comment]
Hi - I just stumbled on this after spending a few hours trying to solve the exact same problem.  I found the docs fairly useless when it came to using pickle.   In my use case, I have a couple of fields that have to be excluded from the dumps, and reconstructed in loads.  I'd recommend adding something to do the docs.

**Comment by WenbinHou** [comment]
+1 for this one

**Comment by domef** [comment]
I had to use ChatGPT to find out how to this :sweat_smile:. I think it would be very useful to put this example in the official docs.
Does this work also with pydantic v2?
