### ISSUE TITLE
Compatibility Issue: Pydantic[email] (or email-validator) with Python 3.12

### ISSUE THREAD

**Issue by NaveenHyniva** [pydantic/pydantic#11173]
**Description Template**:
_Summary_:
I encountered an ImportError when using pydantic[email] on Python 3.12. The error states that email-validator is not installed, despite it being installed.

**Steps to Reproduce**:

Install Python 3.12.
Create a new virtual environment:

**bash**:
python -m venv myenv
source myenv/bin/activate  # or `myenv\Scripts\activate` on Windows
Install pydantic[email]:

**bash**:
pip install pydantic[email]
Run the following script:

from pydantic import BaseModel, EmailStr

class User(BaseModel):
    email: EmailStr

user = User(email="test@example.com")
print(user)

**Observed Behavior**:
The script fails with the following error:
ImportError: email-validator is not installed, run `pip install pydantic[email]`
_Expected Behavior_:
The script should run without errors, and the email field should be validated.

**Environment**:
Python Version: Python 3.12
Pydantic Version: 2.10.4
Email-validator Version: 2.2.0
Operating System: Windows
Additional Notes:
It seems related to Python 3.12 compatibility.

**Comment by Viicos** [comment]
I can't reproduce. Without any additional info, I won't be able to provide more help.

**Comment by Viicos** [comment]
`C:\Users\Hyniva-User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\networks.py` shows that pydantic is installed in the system Python packages.

You can follow https://docs.python.org/3/tutorial/venv.html to get more info on how to manages virtual environments.
