### ISSUE TITLE
improved alias generation

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#1186]
As per #1178 alias generation is currently pretty ugly.

In v2 we should have a classmethod on `Config`:

```py
class Config(BaseConfig):
    @classmethod
    def generate_alias(cls, field_name: str, field_alias: Optional[str]) -> Optional[str]:
        return field_alias
```

This is the default, but obviously it would be trivial to overwrite this to do custom stuff.

This may also relate to #1092 and improvements to the way config inheritance works

**Comment by skewty** [comment]
perhaps it also makes sense to offer the same for title?

**Comment by samuelcolvin** [comment]
Different issue please.

**Comment by samuelcolvin** [comment]
This is fixed on main and will be included in V2, you can try it now on the alpha release.
