### ISSUE TITLE
Generic dataclass support

### ISSUE THREAD

**Issue by gsakkis** [pydantic/pydantic#1256]
It would be nice to support validation for generic dataclasses; in this case the `Response` class in the [documentation example](https://pydantic-docs.helpmanual.io/usage/models/#generic-models) could be written as (or something similar to):
```py
@dataclass
class Response(Generic[DataT]):
    data: Optional[DataT] = None
    error: Optional[Error] = None
```
In the meantime, a note should be added to the [pydantic dataclasses docs](https://pydantic-docs.helpmanual.io/usage/dataclasses/) that generic dataclasses aren't supported (yet).

**Comment by samuelcolvin** [comment]
I think it's beyond the expectations of the docs to list everything we don't do, and issue explaining it is generally enough.

PR welcome implement this, I'm not clear yet how much work it would be.

**Comment by samuelcolvin** [comment]
See if we cant get generic dataclasses to work in V2, no guarantee though.

**Comment by Kludex** [comment]
- Generic improvements such as dataclass support are being tracked on #5351.
