### ISSUE TITLE
JSON Schema Nullable Required Syntax?

### ISSUE THREAD

**Issue by demospace** [pydantic/pydantic#1270]
# Question

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: C:\Users\Work\Envs\songspace\Lib\site-packages\pydantic
               python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

I would expect the code below to generate something like:
```"foo": {"title": "Foo", "type": ["string", "null"]}``` for one of the permutations attempted. Is there a way to do this without creating a custom nullable datatype for each type? The goal is to telegraph something like what is under discussion in https://github.com/samuelcolvin/pydantic/issues/990 to consumers of the schema. Generally, I find that `type: [type1, type2]` is the syntax with the broadest support.

I see that Union[str, int] will give an AnyOf syntax in the schema, but I can't find a way to get even that to work with null?

I'm probably missing something?

```py
from typing import Union, List, Optional
from pydantic import BaseModel, Field

class Widget(BaseModel):
    """A Widget"""
    foo: Optional[str] = None
    bar: Union[str, None] = None
    baz: Optional[str] = Field(
        '...',
    )
    quux: Union[str, None] = Field(
        None,
    )

print(Widget.schema_json())
```

**Comment by demospace** [comment]
I run into a similar issue when I use inspect.signature():

```
import inspect
from typing import Union, List, Optional
from pydantic import BaseModel, Field

class Widget(BaseModel):
    """A Widget"""
    foo: Optional[str] = None
    bar: Union[str, None] = None
    baz: Optional[str] = Field(
        ...,
    )
    quux: Union[str, int] = Field(
        None,
    )
    barbq: Union[None, str] = ...
    barbbq: Optional[str] = ...

print(inspect.signature(Widget))
```
I would have expected the signature to explicitly allow null for one of these the parameters eg Union[str, None]

Actual result:
```(*, foo: str = None, bar: str = None, baz: str, quux: Union[str, int] = None, barbq: str, barbbq: str) -> None```

I suppose it's implicit in the signatures with default=None that None is allowed, but I suspect I'm missing something here?

**Comment by yoricksijsling** [comment]
I ran into the same issue, here is my test case:

```python
from pydantic import BaseModel
from typing import Optional

class Foo(BaseModel):
    # This field must be set, but can be None
    optional_int: Optional[int] = ...

# The schema says that the type of optional_int is 'integer'
assert Foo.schema() == {
    'title': 'Foo',
    'type': 'object',
    'properties': {'optional_int': {'title': 'Optional Int', 'type': 'integer'}},
    'required': ['optional_int'],
}

# This works:
foo_json = '{"optional_int": null}'
foo_object = Foo(optional_int=None)
assert(Foo.parse_raw(foo_json) == foo_object)
assert(foo_object.json() == foo_json)
```

The json is exactly as I expected it to be. However, when I try to validate the json string `{"optional_int": null}` with the generated schema (I used jsonschemavalidator.net), it will complain that it expected an integer but got null.

I would have expected the properties of `optional_int` to be `{'title': 'Optional Int', 'type': ['integer', 'null']}`.

**Comment by thearrow** [comment]
Agreed - would love to see `field: Optional[str]` or `field: Optional[str] = None` map to json schema of `'type': ['string', 'null']`. Was a deal-breaker for adopting pydantic in a project today.

How are others working around this limitation currently? Custom field types with `__modify_schema__`?

**Comment by NoAnyLove** [comment]
Having the same issue, any update?

**Comment by nicobako** [comment]
Yes, I am having this exact same issue. It would be really nice if the generated json schema could accept 'null' as a value for optional types.

**Comment by samuelcolvin** [comment]
Please no more "me too" comments, use the emoji reactions.

I acknowledge the problem, sorry for the slow response, see #1340.

I agree the that the correct solution would be to use `AnyOf` in the schema, and `Optional[foo]` or `Union[None, foo, bar]` in the signature.

PR welcome to fix this, otherwise I'll work on it when I get a chance.

**Comment by matpuk** [comment]
Hello!

Here is my attempt to fix the problem and produce proper JSON Schema for a model with nullables.
It's not perfect. Ideally pydantic should treat NoneType as a valid property type and get rid of ModelField.allow_none property, IMO.

If the fix is ok, then I need to fix fastapi tests somehow.

**Comment by matpuk** [comment]
Note that this PR do not fix Model.__init__() signature due to #1055 .

**Comment by samuelcolvin** [comment]
I've reviewed the PR #1611, and broadly it looks good, just a few things to fix.

The biggest question is about whether this is a breaking change and needs to wait until v2? I know what's proposed is more correct for JSON schema, but I know many people (myself included) have written code to use the scheme that would break with this change.

> Ideally pydantic should treat NoneType as a valid property type and get rid of ModelField.allow_none property, IMO.

Agreed, I hope we can make that change in v2.

> I suppose it's implicit in the signatures with `default=None` that None is allowed

I think it's fair to expect that - even with mypy you have to switch on a flag for `foobar: int = None` to be invalid and require `foobar: Optional[int] = None` to be used instead.

**Comment by brot** [comment]
@samuelcolvin Since you keep referring to v2 here, what are the plans for v2? Is there a roadmap?

I would really need this feature/bugfix to be able to use pydantic for my current project (which relies on existing JSON schema validation)

**Comment by StephenBrown2** [comment]
@brot if what you mean by a Roadmap is "Things that will probably change in Version 2", @samuelcolvin has created a milestone with related issues for v2 here: https://github.com/samuelcolvin/pydantic/milestone/2
Unfortunately there is no scheduled release date that I'm aware of, this is a more organic project than that, dependent on unpaid off-hours availability.

**Comment by krisztianpinter** [comment]
is there any workarounds you guys know of?

**Comment by matt2000** [comment]
The workaround is to add this method to your Model's Config Class:

```python
class YourModel(BaseModel):
    required_foo: int
    nullable_bar: Optional[str]
    nullable_other: Optional[int]

    class Config:
        @staticmethod
         def schema_extra(schema, model):
            for prop, value in schema.get('properties', {}).items():
               if prop in ["nullable_bar", "nullable_other"]:  # Your actual nullable fields go in this list.
                    was = value["type"]
                    value["type"] = [was, "null"]
```

**Comment by PrettyWood** [comment]
Hi everyone
A generic workaround in the meantime could be

```python
from typing import Optional, Union

from pydantic import BaseModel as PydanticBaseModel


class BaseModel(PydanticBaseModel):
    """Same as regular BaseModel but with support of `type: 'null'` in generated schema"""
    class Config:
        @staticmethod
        def schema_extra(schema, model):
            for prop, value in schema.get('properties', {}).items():
                field = model.__fields__[prop]
                if field.allow_none:
                    # only one type e.g. {'type': 'integer'}
                    if 'type' in value:
                        value['anyOf'] = [{'type': value.pop('type')}]
                    value['anyOf'].append({'type': 'null'})


class YourModel(BaseModel):
    int_foo: int
    str_foo: str
    opt_str_foo: Optional[str]
    union_foo: Union[int, str]
    opt_union_foo: Union[int, str] = None
    opt_union_foo2: Optional[Union[int, str]]


assert YourModel.schema() == {
    'type': 'object',
    'title': 'YourModel',
    'properties': {
        'int_foo': {
          'title': 'Int Foo',
          'type': 'integer',
        },
        'str_foo': {
            'title': 'Str Foo',
            'type': 'string',
        },
        'opt_str_foo': {
            'title': 'Opt Str Foo',
            'anyOf': [{'type': 'string'}, {'type': 'null'}],
        },
        'union_foo': {
            'title': 'Union Foo',
            'anyOf': [{'type': 'integer'}, {'type': 'string'}],
        },
        'opt_union_foo': {
            'title': 'Opt Union Foo',
            'anyOf': [{'type': 'integer'}, {'type': 'string'}, {'type': 'null'}],
        },
        'opt_union_foo2': {
            'title': 'Opt Union Foo2',
            'anyOf': [{'type': 'integer'}, {'type': 'string'}, {'type': 'null'}],
        },
    },
    'required': ['int_foo', 'str_foo', 'union_foo'],
}
```

**Comment by HacKanCuBa** [comment]
> Hi everyone
> A generic workaround in the meantime could be
> 
> ```python
> from typing import Optional, Union
> 
> from pydantic import BaseModel as PydanticBaseModel, Field
> 
> 
> class BaseModel(PydanticBaseModel):
>     class Config:
>         @staticmethod
>         def schema_extra(schema, model):
>             for prop, value in schema.get('properties', {}).items():
>                 # retrieve right field from alias or name
>                 field = [x for x in model.__fields__.values() if x.alias == prop][0]
>                 if field.allow_none:
>                     # only one type e.g. {'type': 'integer'}
>                     if 'type' in value:
>                         value['anyOf'] = [{'type': value.pop('type')}]
>                     value['anyOf'].append({'type': 'null'})

Hi @PrettyWood, I tried your code but it raises `KeyError: 'anyOf'` so it seems to be an issue with the logic appending the null value (around the `if`)

**Comment by PrettyWood** [comment]
Hello @HacKanCuBa 
Which version of _pydantic_ do you use? Could you please provide a `gist` or something to help me understand

**Comment by HacKanCuBa** [comment]
> Hello @HacKanCuBa
> Which version of _pydantic_ do you use? Could you please provide a `gist` or something to help me understand

Sure! Is there any way to chat this somewhere else? :P I don't want to flood this thread so much (you can find me on twitter or telegram with the same username)

```
In [8]: import pydantic

In [9]: pydantic.version.VERSION
Out[9]: '1.6.1'
```
Apparently it fails on a model relating another model:

```python
class SomeModel(BaseModel):

    field1: int
    field2: str


class RelatedModel(BaseModel):

    field1: int
    related: typing.Optional[SomeModel]
```

**Comment by PrettyWood** [comment]
Hi @HacKanCuBa 
I just updated my answer with the generic version to add the case of `$ref` when we have a `BaseModel` in the schema.
Please tell me if it solves your problem!
If yes, I'll just hide all our conversation to keep this issue readable ;)

**Comment by HacKanCuBa** [comment]
> Hi @HacKanCuBa
> I just updated my answer with the generic version to add the case of `$ref` when we have a `BaseModel` in the schema.
> Please tell me if it solves your problem!
> If yes, I'll just hide all our conversation to keep this issue readable ;)

It certainly seems to work but something seemed off. After a while I noticed that there's a typo in this line: `value['anyOf'] = [{'ref': value.pop('$ref')}]` should be `value['anyOf'] = [{'$ref': value.pop('$ref')}]` (note the `$ref` as key where the symbol `$` is missing)

**Comment by HacKanCuBa** [comment]
@PrettyWood I found another issue with your solution: `'null'` becomes a string `"null"` in the OpenAPI schema and not the correct JSON value `null`. On several validators this produces:
```
Structural error at components.schemas.RelatedModel.properties.related.anyOf.1.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
```

I tried with `None` but it doesn't work. I'm currently researching and will come back here if I find a solution.

**Comment by PrettyWood** [comment]
@HacKanCuBa Glad you could test it and catch new errors! It means https://github.com/samuelcolvin/pydantic/pull/1611 will need some changes!

**Comment by HacKanCuBa** [comment]
I was checking that, too

**Comment by krisztianpinter** [comment]
i don't want to ruin the party with bad news. but the sad situation is that openapi 3 deviates from jsonschema. it does not recognise _null_ as a type, but rather, it insists on a boolean field _nullable_. openapi 3.1 will go fully jsonschema compatible.

nullable is actually easier to fake in:

`email: Optional[str] = Field(..., nullable=True)`

**Comment by PrettyWood** [comment]
So basically we could have an enum option in the config like `extra`. IMO it makes no sense to put it at field level as you either want your schema with or without nullables.
```python
class Config:
    schema_nullable = 'hidden' / '3.0' / '3.1'
```
By default we would keep the 'hidden' behaviour so nothing so the feature wouldn't break anything and wouldn't require a v2 as it's currently the case for the open PR.
If 3.0 is chosen we add `nullable: true` for the nullables fields in the schema.
If 3.1 is chosen we add `type: 'null'` in the `anyOf` part.
Maybe we should add also a `'both'` in the enum as they don't have conflict. It would probably make things easier for people working with different tools.
WDYT?

**Comment by HacKanCuBa** [comment]
That sounds plausible, I like the idea. Is it possible to set said config "externally", as in i.e. FastAPI setting the correct value for the in-use OpenAPI spec version? If we can do that, then the problem would be mostly solved.

This would mean having a model like this:

```python
class MyModel(BaseModel):
    field1: int
    field2: str

...

MyModel.Config.schema_nullable = '3.0'  # or '3.1'
```

Does that sound *sane*? I mean, I think we need to figure a solution that allows the user and/or the framework to set the right value.

**Comment by PrettyWood** [comment]
You could just do
```
from pydantic import BaseConfig

BaseConfig.schema_nullable = '...'
```
or define your own custom `BaseModel` since `Config` is inherited from parent classes

**Comment by davidhewitt** [comment]
> So basically we could have an enum option in the config like extra. IMO it makes no sense to put it at field level as you either want your schema with or without nullables.

I disagree with this; I would love to be able to write the following model:

```python
class MyModel(BaseModel):
    required_nullable_field: Optional[str]
    optional_field: Optional[str] = Field(None, nullable=False)
```

where the schema would be something like this:

```
{
    "properties": {
        "required_nullable_field": { "type": ["string", "null"] },
        "optional_field": { "type": "string" },
    },
}
```

Doing that seems to necessarily make `nullable` a field-level choice. Sadly I think it only applies to `Optional[]` fields, so perhaps a better way is to have an `OptionalDisallowNone[]` type as proposed in https://github.com/samuelcolvin/pydantic/discussions/2353#discussioncomment-367950

**Comment by PrettyWood** [comment]
Hmm but that's not the same problem.
My point was: you probably either want "nullable" to be set in the schema or not. But you don't want to set it only for some fields. And I feel like now we should not have this enum and probably just add `null` in the type as explained in [this comment](https://github.com/samuelcolvin/pydantic/pull/1611#issuecomment-817250421).

Your point @davidhewitt is to differentiate not required fields and nullable fields. The name `Optional` in typing is missleading when you think about JSON. And on this matter I totally agree and hope the pydantic API can be changed in v2 to [support properly this](https://github.com/samuelcolvin/pydantic/discussions/2353).
Your feedback is more than welcome

**Comment by davidhewitt** [comment]
> My point was: you probably either want "nullable" to be set in the schema or not. But you don't want to set it only for some fields.

Ah, understood. Thanks for clarifying.

**Comment by wouterdb** [comment]
release 1.9.0a1  breaks this work around completely:

```python
.../inmanta/data/model.py", line 34, in <module>
    old_field_type_schema = pydantic.schema.field_type_schema
AttributeError: 'cython_function_or_method' object has no attribute 'field_type_schema'
```

**Comment by samuelcolvin** [comment]
Hi @wouterdb please can you create a new issue with a self contained example. I'll look at it, and hopefully fix it before release.

**Comment by jony89** [comment]
Thanks @edvgui .

This will also handle non primitive types :

```

import pydantic.schema
from pydantic.fields import ModelField


# This reference to the actual pydantic field_type_schema method is only loaded once
old_field_type_schema = pydantic.schema.field_type_schema


def patch_pydantic_field_type_schema() -> None:
    """
    This ugly patch fixes the serialization of models containing Optional in them.
    https://github.com/samuelcolvin/pydantic/issues/1270
    """

    def patch_nullable(field: ModelField, **kwargs):
        f_schema, definitions, nested_models = old_field_type_schema(field, **kwargs)
        if field.allow_none:
            f_schema["nullable"] = True
        if f_schema.get("$ref"):
            f_schema["allOf"] = [{"$ref": f_schema["$ref"]}]
            del f_schema["$ref"]
        return f_schema, definitions, nested_models

    pydantic.schema.field_type_schema = patch_nullable
```

**Comment by stur86** [comment]
Has there been any change on this? I still have the same issue. Do I need to implement one of the workarounds above or is there a more elegant solution?

**Comment by HacKanCuBa** [comment]
> Has there been any change on this? I still have the same issue. Do I need to implement one of the workarounds above or is there a more elegant solution?

Prob gonna be solved in v2 due to the solution being a breaking change. Additionally, I remember we were also waiting for an update of the official JSON schema, but this statement may not be true anymore.

Feel free to adopt any of the solutions mentioned in this thread, the one that works the better for you, in the meantime :)

**Comment by PrettyWood** [comment]
Yes it will be in v2 for sure. And v2 will have better separation of concerns: validation vs JSON schema generation for example

**Comment by ar45** [comment]
This is what I came up with to workaround

```python3
# This reference to the actual pydantic field_type_schema method is only loaded once
pydantic_field_type_schema = pydantic.schema.field_type_schema


def patch_pydantic_field_type_schema() -> None:
    """
    This ugly patch fixes the serialization of models containing Optional in them.
    https://github.com/samuelcolvin/pydantic/issues/1270
    """
    warnings.warn("Patching fastapi.applications.get_openapi")
    import fastapi.applications
    from app.openapi.utils import get_openapi
    fastapi.applications.get_openapi = get_openapi

    warnings.warn("Patching pydantic.schema.field_type_schema")

    def field_type_schema(field: ModelField, **kwargs):
        f_schema, definitions, nested_models = pydantic_field_type_schema(field, **kwargs)
        if field.allow_none:
            s_type = f_schema.get('type')
            if s_type:
                # Hack to detect whether we are generating for openapi
                # fastapi sets the ref_prefix to '#/components/schemas/'.
                # When using for openapi, swagger does not seem to support an array
                # for type, so use anyOf instead.
                if kwargs.get('ref_prefix') == '#/components/schemas/':
                    f_schema = {'anyOf': [f_schema, {"type": "null"}]}
                else:
                    if not isinstance(s_type, list):
                        f_schema['type'] = [s_type]
                    f_schema['type'].append("null")
            elif "$ref" in f_schema:
                f_schema["anyOf"] = [
                    {**f_schema},
                    {"type": "null"},
                ]
                del f_schema["$ref"]

            elif "allOf" in f_schema:
                f_schema['anyOf'] = f_schema['allOf']
                del f_schema['allOf']
                f_schema['anyOf'].append({"type": "null"})

            elif "anyOf" in f_schema or "oneOf" in f_schema:
                one_or_any = f_schema.get('anyOf') or f_schema.get('oneOf')
                for item in one_or_any:
                    if item.get('type') == 'null':
                        break
                else:
                    one_or_any.append({"type": "null"})

        return f_schema, definitions, nested_models

    pydantic.schema.field_type_schema = field_type_schema


patch_pydantic_field_type_schema()

```

**Comment by csm10495** [comment]
Could a patch like the one in https://github.com/pydantic/pydantic/issues/1270#issuecomment-1209704699 be added upstream? At least until 2.0.

**Comment by realitycheck** [comment]
I've found this do the job: using special enum to introduce null option in schema

{code}
import enum
from pydantic import BaseModel

class Nullable(enum.Enum):
    null = None

class Widget(BaseModel):
    """A Widget"""
    foo: str | Nullable
    bar: str | Nullable


print(Widget.schema_json())
{code}

**Comment by HacKanCuBa** [comment]
> I've found this do the job: using special enum to introduce null option in schema
> 
> ```
> import enum
> from pydantic import BaseModel
> 
> class Nullable(enum.Enum):
>     null = None
> 
> class Widget(BaseModel):
>     """A Widget"""
>     foo: str | Nullable | None
>     bar: str | Nullable | None
> 
> 
> print(Widget.schema_json())
> ```

Here's the output for anyone curious:

```json
{
  "title": "Widget",
  "description": "A Widget",
  "type": "object",
  "properties": {
    "foo": {
      "title": "Foo",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/Nullable"
        }
      ]
    },
    "bar": {
      "title": "Bar",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/Nullable"
        }
      ]
    }
  },
  "definitions": {
    "Nullable": {
      "title": "Nullable",
      "description": "An enumeration.",
      "enum": [
        null
      ]
    }
  }
}
```

It does look good, but it's still not technically nullable as in the specs :P

**Comment by samuelcolvin** [comment]
Any one interested in this, it might be valuable to get your input on #4666 and the choice between JSON Schema and OpenAPI.

**Comment by dmontagu** [comment]
I'm having trouble deciphering exactly what the goal was here, but now that we have merged #5029 is this resolved? Here is  a test demonstrating the current behavior:

https://github.com/pydantic/pydantic/blob/73373c3e08fe5fe23e4b05f549ea34e0da6a16b7/tests/test_json_schema.py#L529-L538

**Comment by HacKanCuBa** [comment]
> I'm having trouble deciphering exactly what the goal was here, but now that we have merged #5029 is this resolved? That is, can this issue be closed?
> 
> Here is a test demonstrating the current behavior:
> 
> https://github.com/pydantic/pydantic/blob/73373c3e08fe5fe23e4b05f549ea34e0da6a16b7/tests/test_json_schema.py#L529-L538

I'm pretty sure that certainly works for me :)

**Comment by samuelcolvin** [comment]
fixed by #5029.

**Comment by henriklindgren** [comment]
Hi, sorry to wake up an old thread, I stumbled upon something not mentioned, possibly more a fastapi thing.

If the pydantic model containing the nullables is in itself optional, nullables get broken regardless of fixes mentioned in this thread.
``` python
class Variant32(object):
    def __init__(
            self,
            field1: Optional[str] = Query(None, nullable=True),
            field2: Optional[int] = Query(None, nullable=True),
            field3: Optional[bool] = Query(None, nullable=True),
    ):
        self.field1 = field1
        self.field2 = field2
        self.field3 = field3

app = FastAPI()

# nullable true in schema for model's fields
@app.get('/variant32')
def variant32(variant32: Variant32 = Depends()):
    pass


# no nullable field for model's fields in schema
@app.get('/optional-variant32')
def optional_variant32(variant32: Optional[Variant32] = Depends()):
    pass
```

This is regardless if using pydantic or plain objects with FastAPI Depends, you can simply replace the model in the example above with any of these alternatives
``` python
class Variant12Model(BaseModel):
    """
    Variant 1-2
    Using @krisztianpinter's solution

    see https://github.com/pydantic/pydantic/issues/1270#issuecomment-734467055
    """
    field1: Optional[str] = Field(None, nullable=True)
    field2: Optional[int] = Field(None, nullable=True)
    field3: Optional[bool] = Field(None, nullable=True)

class Variant22Model(BaseModel):
    """Variant 2-2"""
    field1: Optional[str] = Field(None, nullable=True)
    field2: Optional[int] = Field(None, nullable=True)
    field3: Optional[bool] = Field(None, nullable=True)

    class Config:
        @staticmethod
        def schema_extra(schema, model):
            """Fixes nullable fields in OpenApi v3+ generator"""
            for prop, value in schema.get('properties', {}).items():
                # retrieve right field from alias or name
                field = [x for x in model.__fields__.values() if x.alias == prop][0]
                if field.allow_none:
                    if '$ref' in value:
                        if issubclass(field.type_, BaseModel):
                            # add 'title' in schema to have the exact same behaviour as the rest
                            value['title'] = field.type_.__config__.title or field.type_.__name__
                        value['anyOf'] = [{'$ref': value.pop('$ref')}]
                    value['nullable'] = True

```

Made a repo to experiment with fastapi+pydantic behaviour for this ticket: https://github.com/henriklindgren/investigate-fastapi-nullables

**Comment by Krzysiek555** [comment]
> I've found this do the job: using special enum to introduce null option in schema
> 
> ```
> import enum
> from pydantic import BaseModel
> 
> class Nullable(enum.Enum):
>     null = None
> 
> class Widget(BaseModel):
>     """A Widget"""
>     foo: str | Nullable | None
>     bar: str | Nullable | None
> 
> 
> print(Widget.schema_json())
> ```

Brilliant solution! Works as a gold ⭐

**Comment by speedplane** [comment]
For me, the following monkey-patch did the trick, replacing the nullable_schema function.

```
def patch_pydantic_nullable_schema(self, schema):
    """Use 'nullable: true' instead of 'anyOf' for nullable fields, #619."""
    inner_json_schema = self.generate_inner(schema['schema'])
    if inner_json_schema == {'type': 'null'}:
        return {'type': 'null'}

    # Instead of `anyOf`, we set `nullable: true`
    inner_json_schema['nullable'] = True
    return inner_json_schema

from pydantic.json_schema import GenerateJsonSchema
GenerateJsonSchema.nullable_schema = patch_pydantic_nullable_schema
logging.info("Patched Pydantic to use 'nullable: true' for nullable fields.")
```
