### ISSUE TITLE
Error unclear for redefining default value for type List[str]

### ISSUE THREAD

**Issue by tomhamiltonstubber** [pydantic/pydantic#1296]
The error is quite unclear when redefining the default value for `file_paths` in the example below:

```py
class BaseSettings:
    file_paths: List[str] = []


class Settings(BaseSettings):
    file_paths = ['/usr/files/']
```

If we create a `Settings` object here, we'll get the following error:
`TypeError: The type of Settings.patch_paths differs from the new default value; if you wish to change the type of this field, please use a type annotation`

The short-term solution is just to use a type annotation when redefining `file_paths`:

```py
class Settings(BaseSettings):
    file_paths: List(str) = ['/usr/files/']
```

The long-term solution is being discussed [here](https://github.com/samuelcolvin/pydantic/issues/782).

**Comment by samuelcolvin** [comment]
Discussed in much detail on #757.

Let's update the error message to:
1. explain that you simply need to add a type annotation
2. link to #757 for a full discussion.

**Comment by dmontagu** [comment]
Closing this as we have updated the relevant error messages to be more clear in v2.
