### ISSUE TITLE
Generic `conlist`?

### ISSUE THREAD

**Issue by vegarsti** [pydantic/pydantic#1309]
First, thanks a lot for such a great library!

# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/vegardstikbakke/Library/Caches/pypoetry/virtualenvs/unstructured-search-SHdVRZ3t-py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Sep 17 2019, 13:58:56)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

The feature I'm requesting is that I would love to be able to make a generic model where a field is a `conlist` of a generic type.

In an API I working on, I have a JSON object that specifies a filter.
In this we want to support predicates, such as `in`, where one can give a list and if the field matches anything in the list, it is a match.
I want to do this for several types of fields.
E.g.

```
{"string": {"in": ["a", "b", "c"]}, "integer": {"in": [1, 2, 3]}}
```

I also want to have the nice functionality of `conlist`, in that I can specify the length of the array.

In the snippet below, I try to create such a model, where I try to make a generic `conlist`, namely `conlist(DataT, ...)`.
The code runs without problems, but the generic type is not enforced, in that the `in` list contains elements of type `DataT`; all values are accepted.
```py
from typing import Generic, TypeVar

from pydantic import conlist
from pydantic.generics import GenericModel

DataT = TypeVar("DataT")


class A(GenericModel, Generic[DataT]):
    in_: conlist(DataT, min_items=1, max_items=10) = Field(default=..., alias="in")


a = A[int].parse_obj({"in": ["a"]})
print(a)  # a=['a']
```

The functionality that I want is that the `parse_obj` call would raise a `ValidationError` here, saying that `"a"` is not an `int`. To be clear, the below does raise an error:

```py
from typing import Generic, TypeVar, List

from pydantic.generics import GenericModel

DataT = TypeVar("DataT")


class A(GenericModel, Generic[DataT]):
    a: List[DataT]


a = A[int].parse_obj({"a": ["a"]})
```

Would it be possible to make this verify that elements are of the type that is specified?
Am I using `conlist` and/or `GenericModel` wrong? If I am using it correctly, I guess this is a bug instead.

I apologize if this has already almost been answered in other issues.
I tried finding similar issues, but couldn't.

Also, I would love to help in implementing this, if possible and wanted.

**Comment by samuelcolvin** [comment]
I guess in theory there's nothing to stop

```py
DataT = TypeVar("DataT")

class A(GenericModel, Generic[DataT]):
    in_: conlist(DataT, min_items=1, max_items=10) = Field(default=..., alias="in")
```

From working, though @dmontagu is the expert on`GenericModel`. But I think it's more a feature request than a bug.

I'd be happy to support it, but don't have time to work on it myself right now. If you're happy to have a go and submit a PR if you have any luck that would be great.

**Comment by vegarsti** [comment]
Alright! Thanks for the quick reply! I'll see what I can do

**Comment by bkis** [comment]
How could I do this if the generic is not used in a `class` context?

```py
from typing import Literal, TypeVar, get_args
from pydantic import BaseModel

type TranslationLocaleKey = Literal["deDE", "enUS", "*"]

class TranslationBase(TypedDict):
    locale: TranslationLocaleKey

class TextTitleTranslation(TranslationBase):
    translation: Annotated[str, Field(description="Specific translation of a text title")]

T = TypeVar("T", bound=TranslationBase)
Translations = conlist(
    T,  # ty error: Argument to function `conlist` is incorrect: Expected `type[Unknown]`, found `TypeVar`ty[invalid-argument-type](https://ty.dev/rules#invalid-argument-type)
    max_length=len(get_args(TranslationLocaleKey.__value__)),
)

class Text(BaseModel):
    title: Annotated[
        Translations[TextTitleTranslation],  # ty error: Invalid subscript of object of type `type[list[TypeVar]]` in type expression
        Field(description="Translated text title"),
    ]
```

**Comment by Viicos** [comment]
@bkis the `con*()`functions shouldn't be used anymore. In your case, you can do:

```python
from annotated_types import MaxLen

T = TypeVar("T", bound=TranslationBase)

Translations = Annotated[T, MaxLen(...)]
```

**Comment by bkis** [comment]
@Viicos Perfect! Thank you! I needed `Annotated[list[T], MaxLen(...)]`, because the constrained `Translations` type is supposed to represent a list of translations, but otherwise your proposal is very valid!

BTW I knew `constr` was deprecated for `StringConstraints`, as it's clearly stated in the docs (and code comments!), but this is **not the case** with `conlist` – or did I miss anything?
