### ISSUE TITLE
Better error reporting for Union 

### ISSUE THREAD

**Issue by stereobutter** [pydantic/pydantic#1357]
I mainly use pydantic for settings management and I want to be able to provide multiple ways to configure some parts of my application for ease of use. Take as an minimal example 

```python
class BaseUrlWithUris(BaseModel):
    url: AnyHttpUrl
    uris: List[str]
    method: Literal['get', 'post']
        
class ListOfUrls(BaseModel):
    urls: List[AnyHttpUrl]
    method: Literal['get', 'post']
        
class Settings(BaseSettings):
    endpoints: Union[BaseUrlWithUris, ListOfUrls]
        
    @validator('endpoints', pre=True)
    def parse_objects(cls, value: str) -> Union[list, dict]:
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            raise TypeError("cannot be loaded from environment")
```

Now the configuration for `endpoints` can be done in two ways; either by providing a configuration like:

```
{
  "urls": ["http://www.example.com/1", "http://www.example.com/2"],
  "method": "get"
}
```
or alternatively (when there are many resources that all share the same base url)

```
{
  "url": "http://www.example.com/",
  "uris": [1,2]
  "method": "get"
}
```

What I couldn't figure out is an elegant way to get intuitive error reporting. Currently the error message for the following incomplete configuration

```
{
  "url": "http://www.example.com/",
  "uris": [1,2]
}
```

is 

```
ValidationError: 3 validation errors for Settings
endpoints -> method
  field required (type=value_error.missing)
endpoints -> urls
  field required (type=value_error.missing)
endpoints -> method
  field required (type=value_error.missing)
```

which is not very intuitive. Ideally for the  union `Union[BaseUrlWithUris, ListOfUrls]` the individual error messages for `BaseUrlWithUris` and `ListOfUrls` were preserved and presented in the error message for the field i.e. something like 

```
ValidationError: 1 validation errors for Settings
endpoints
  1 validation error for BaseUrlWithUris
    method
      field required (type=value_error.missing)
  2 validation errors for ListOfUrls
    urls
      field required (type=value_error.missing)
    method
      field required (type=value_error.missing)
```

or even something more descriptive and well formatted:

```
ValidationError: 1 validation errors for Settings
endpoints
  validation errors for members in Union[BaseUrlWithUris, ListOfUrls]:

    1 validation error for BaseUrlWithUris
      method
        field required (type=value_error.missing)

    2 validation errors for ListOfUrls
      urls
        field required (type=value_error.missing)
      method
        field required (type=value_error.missing)
```

**Comment by samuelcolvin** [comment]
Regarding multiple errors, this will be improved by #619.

Regarding how errors are displayed, you can change it yourself.

I guess there's a possibility to change the default `__str__` method on errors from `BaseSettings`, but best if we can do so without changing what's stored on errors.

**Comment by SaschaSchlemmer** [comment]
A flexible solution would be something similar to `validator` were one can intercept error messages per field or similar to `root_validator` intercept all errors that have been collected for the model. 

Also can you point me at some example of how I can change the display of errors?

**Comment by samuelcolvin** [comment]
There's currently no way to customise what error is raised, however once you get a `ValidationError`, you can use `validation_error.errors()` to get a list of dicts representing the errors. You can then render that however you like.

**Comment by SaschaSchlemmer** [comment]
I've investigated a bit and what I found very limiting for customizing error reporting is that the values for an errors `loc` only contain the names of fields on sub-models and not the sub-model the field is from.

**Comment by dmontagu** [comment]
Discriminated union support has been added since this issue was created, and in v2, you can now do more flexible error manipulation by instantiating `ValidationError` with the `loc` set to what you want, and discriminated unions are more powerful and have had some bugs fixed while handling certain edge cases.
