### ISSUE TITLE
Exclude_unset option removing dynamic default setted on a validator

### ISSUE THREAD

**Issue by hellocoldworld** [pydantic/pydantic#1399]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /home/nico/.local/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
                     platform: Linux-5.3.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions', 'email-validator']
```

```py
import pydantic
from typing import Optional


class Foo(pydantic.BaseModel):
    foo: str = pydantic.Field(...)
    bar: str = pydantic.Field(...)
    baz: Optional[str] = pydantic.Field(None)

    @pydantic.validator("baz", always=True, pre=True)
    @classmethod
    def set_baz(cls, v, values):
        """sets dynamic default for baz"""
        if v:
            return v
        return values["foo"] + " " + values["bar"]


a = Foo(foo="foo", bar="bar")
print(a.dict())  # prints {'foo': 'foo', 'bar': 'bar', 'baz': 'foo bar'}
print(a.dict(exclude_unset=True))  # prints {'foo': 'foo', 'bar': 'bar'}

...
```

Is this behaviour the desired? I don't know if call this issue a bug or a feature request. 
I would expect baz field to be included, since it was setted on creation (even though not explictly).

Can I hope better behaviour when using default_factory when it's avaible (v1.5)?

**Comment by samuelcolvin** [comment]
Difficult one, you could call it a bug or a feature request.

I think, long term the proper solution is computed fields, this is not described well anywhere but problably https://github.com/samuelcolvin/pydantic/issues/935#issuecomment-555036039 is the nearest.

I suspect `default_factory` won't help, but by all means give it a try - you can always install pydantic@master from git.

**Comment by hellocoldworld** [comment]
Closing this issue to favour discussion in #935

**Comment by giacomomarchioro** [comment]
I think you should keep it open. The discussion is quite broad.

**Comment by linpan** [comment]
I think you should keep it open. The discussion is quite broad.

**Comment by Bobspadger** [comment]
I've also just run into this issue where I am using computed values to via the validators to set an attribute.
This works great until I use the `exclude_unset=True` to remove empty attributes, and it removes those that have been set by the validators themselves.

Just taken me a couple of hours to work out why I was getting different data!

Is this truly the expected result of `exclude_unset?`

**Comment by adg-mh** [comment]
I just ran into this as well. Has anyone come up with a work around?

**Comment by dmontagu** [comment]
If a validator is setting the attribute by default, it seems to me that you'd want the value included when `exclude_unset=True` no matter what. If that's right, you can override the `__init__` to always add the specific field to the `__fields_set__` attribute. This will cause it to be included even if you use `exclude_unset=True`:

```python
from typing import Optional, Any

import pydantic


class Foo(pydantic.BaseModel):
    foo: str = pydantic.Field(...)
    bar: str = pydantic.Field(...)
    baz: Optional[str] = pydantic.Field(None)

    def __init__(__pydantic_self__, **data: Any) -> None:
        super().__init__(**data)
        __pydantic_self__.__fields_set__.add('baz')

    @pydantic.validator("baz", always=True, pre=True)
    @classmethod
    def set_baz(cls, v, values):
        """sets dynamic default for baz"""
        if v:
            return v
        return values["foo"] + " " + values["bar"]


a = Foo(foo="foo", bar="bar")
print(a.dict())  # prints {'foo': 'foo', 'bar': 'bar', 'baz': 'foo bar'}
print(a.dict(exclude_unset=True))  # prints {'foo': 'foo', 'bar': 'bar', 'baz': 'foo bar'}
```

**Comment by hellocoldworld** [comment]
Thanks @dmontagu 
Looking forward for v2 <3

**Comment by divad1196** [comment]
@dmontagu Thank you for your response that saved me a lot of time

I made a generic version if that helps anybody:
```python
class MyBaseModel(BaseModel):
    def __init__(self, **data) -> None:
        res = super().__init__(**data)
        fields = self.__pydantic_core_schema__["schema"]["fields"]
        fields_with_default = (
            f for f, d in fields.items()
            if "default" in d["schema"]
        )
        self.model_fields_set.update(fields_with_default)
        return res
```

I think we could add an option that would be `exclude_strict_unset` (or a variation) that would solve this issue without breaking anycode. This option would still be compatible with other option.
Is there a reason for not making that?
