### ISSUE TITLE
How to associate text labels with choice values in schemas

### ISSUE THREAD

**Issue by dodumosu** [pydantic/pydantic#1401]
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.4
            pydantic compiled: True
            python version: 3.8.2 (default, Apr 16 2020, 05:44:45)  [GCC 7.5.0]
            platform: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.27
            optional deps. installed: ['email-validator']
```

From the documentation, pydantic uses enums for choices. I haven't been able to determine how to link a value with a label, which might be useful for an application consuming a pydantic-powered API.

For example:

```python
import enum
import pydantic


class Apple(enum.IntEnum):
    RED_DELICIOUS = 1
    GOLDEN_DELICIOUS = 2
    MCINTOSH = 3
    FUJI = 4 


class AppleModel(pydantic.BaseModel):
    variety: Apple


ApplePieModel.schema()
# {'title': 'AppleModel', 'type': 'object', 'properties': {'variety': {'title': 'Variety', 'enum': [1, 2, 3, 4], 'type': 'integer'}}, 'required': ['variety']}
```

From the documentation, it is possible to use enums that subclass `str`, but that seems a less than ideal solution to my mind.

For contrast, something like Django or WTForms allows you specify choices in [value], [label] pairs:

```python
APPLE_CHOICES = (
    (1, 'Red Delicious'),
    (2, 'Golden Delicious'),
    (3, 'McIntosh'),
    (4, 'Fuji'),
)
```

I'm not saying this is _how_ it should be done, just trying to find out if there's a way it _can_ be done.

**Comment by dodumosu** [comment]
From [this issue](https://github.com/json-schema-org/json-schema-spec/issues/57), it looks like `oneOf` is the accepted way of doing this in JSON Schema land, but pydantic doesn't generate that particular JSON Schema type.

**Comment by Atheuz** [comment]
Here's something I tried, I was unable to tie a secondary value to it though:

```from pydantic import BaseModel
from typing_extensions import Literal
from typing import Union, Tuple


Variety = Union[
    Literal["Red Delicious"],
    Literal["Golden Delicious"],
    Literal["McIntosh"],
    Literal["Fuji"],
]


class AppleModel(BaseModel):
    variety: Variety


def main():
    print(AppleModel.schema())


if __name__ == "__main__":
    main()```

Produces =>

```
{
	"title": "AppleModel",
	"type": "object",
	"properties":
	{
		"variety":
		{
			"title": "Variety",
			"anyOf": [
				{
					"const": "Red Delicious",
					"type": "string"
				},
				{
					"const": "Golden Delicious",
					"type": "string"
				},
				{
					"const": "McIntosh",
					"type": "string"
				},
				{
					"const": "Fuji",
					"type": "string"
				}
			]
		}
	},
	"required": ["variety"]
}
```

**Comment by dodumosu** [comment]
That's interesting. The (untested) concept I came up with is using the
`aenum` package to create enumerations that can have a `label` field, then
creating a class method `__modify_schema__` to customise the schema
generation.

Cheers

**Comment by samuelcolvin** [comment]
@dodumosu can you explain more how `aenum` worked? I too really want something like this.

I think we should add some standard way to achieve this in pydantic.

**Comment by dodumosu** [comment]
so here's what i cooked up:

```python
# -*- coding: utf-8 -*-
from typing import Optional

import aenum
import pydantic


class AppleVariety(aenum.Enum):
    _init_ = "value label"

    FUJI = 1, "Fuji"
    GOLDEN_DELICIOUS = 2, "Golden Delicious"
    MCINTOSH = 3, "McIntosh"
    RED_DELICIOUS = 4, "Red Delicious"

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def __modify_schema__(cls, field_schema):
        # see notes below
        field_schema.pop("enum")
        field_schema.update(
            {
                "oneOf": [
                    {"const": choice.value, "title": choice.label}
                    for choice in cls
                ]
            }
        )

    @classmethod
    def validate(cls, v):
        try:
            new_v = cls(int(v))
        except (TypeError, ValueError):
            raise

        return new_v


class Apple(pydantic.BaseModel):
    variety: Optional[AppleVariety] = None
```

Notes:
- you don't have to use `aenum`, i just like how i can use it relatively cleanly (imo). alternatives can be found [here](https://stackoverflow.com/questions/43862184/associating-string-representations-with-an-enum-that-uses-integer-values/)
- the `field_schema` parameter to `__modify_schema__` must be modified in-place.

**Comment by hacktivista** [comment]
Just connected to say I've been looking for something like this integrated into pydantic for several months... I'll be waiting for it :D

**Comment by selimb** [comment]
> For contrast, something like Django or WTForms allows you specify choices in [value], [label] pairs

This can also be done using the new [django.db.models.enums.Choices](https://github.com/django/django/blob/0a306f7da668e53af2516bfad759b52d6c650b69/django/db/models/enums.py#L62) class, which actually uses `enum.Enum` under the hood. Turns out this *just works* with pydantic, too:
```python
from django.db.models import TextChoices
import pydantic

class RunnerType(TextChoices):
    LOCALFS = "localfs", "Local FS"
    SGE = "sge", "SGE"

class Job(pydantic.BaseModel):
    runner_type: RunnerType

print("schema", Job.schema())
job = Job(runner_type="localfs")
print("job", job)
print("json", job.json())

# OUTPUT:
schema {'title': 'Job', 'type': 'object', 'properties': {'runner_type': {'title': 'Runner Type', 'enum': ['localfs', 'sge'], 'type': 'string'}}, 'required': ['runner_type']}
job runner_type=<RunnerType.LOCALFS: 'localfs'>
json {"runner_type": "localfs"}
```
If `oneOf` is desired over `enum` in the schema, @dodumosu's [__modify_schema__](https://github.com/samuelcolvin/pydantic/issues/1401#issuecomment-617874722) method can be simply copy-pasted into a subclass of `TextChoices`:
```python
from django.db.models import TextChoices
import pydantic

class Choices(TextChoices):  # new
    @classmethod
    def __modify_schema__(cls, field_schema):
        # see notes below
        field_schema.pop("enum")
        field_schema.update({"oneOf": [{"const": choice.value, "title": choice.label} for choice in cls]})

class RunnerType(Choices):  # modified
    LOCALFS = "localfs", "Local FS"
    SGE = "sge", "SGE"

class Job(pydantic.BaseModel):
    runner_type: RunnerType

print("schema", Job.schema())
job = Job(runner_type="localfs")
print("job", job)
print("json", job.json())

# OUTPUT:
schema {'title': 'Job', 'type': 'object', 'properties': {'runner_type': {'title': 'Runner Type', 'type': 'string', 'oneOf': [{'const': 'localfs', 'title': 'Local FS'}, {'const': 'sge', 'title': 'SGE'}]}}, 'required': ['runner_type']}
job runner_type=<RunnerType.LOCALFS: 'localfs'>
json {"runner_type": "localfs"}
```
I mention this because the code for [django.db.models.enums.Choices](https://github.com/django/django/blob/0a306f7da668e53af2516bfad759b52d6c650b69/django/db/models/enums.py#L62) is pretty lightweight (especially compared to `aenum`). Would it make sense to simply vendor that code (plus `__modify_schema__`) with `pydantic`?

**Comment by selimb** [comment]
Actually, this minimal code does the trick for my (limited) use case, and it correctly type-checks `.value` and `.label`:
```python
# labelled_enum.py
"""
A special Enum that plays well with ``pydantic`` and ``mypy``, while allowing human-readable
labels similarly to ``django.db.models.enums.Choices``.
"""
from typing import TypeVar, Type
import enum

T = TypeVar("T")


class LabelledEnum(enum.Enum):
    """Enum with labels. Assumes both the value and label are strings."""

    def __new__(cls: Type[T], value: str, label: str) -> T:
        obj = object.__new__(cls)
        obj._value_ = value
        obj.label = label
        return obj
```
```python
# labelled_enum.pyi
import enum

class LabelledEnum(enum.Enum):
    @property
    def label(self) -> str: ...
    @property
    def value(self) -> str: ...
```
```python
# example usage
class RunnerType(LabelledEnum):
    LOCALFS = "localfs", "Local FS"
    SGE = "sge", "SGE"
```
Again, `__modify_schema__` can easily be defined in `LabelledEnum` if desired -- I don't personally need it.

Hope this helps.

**Comment by jokull** [comment]
Adapted the Django code and combined with pieces from above ^ and [it works quite well](https://gist.github.com/jokull/be49fb8ea7b4043cae10a04f239e9513).

**Comment by elonzh** [comment]
> From [this issue](https://github.com/json-schema-org/json-schema-spec/issues/57), it looks like `oneOf` is the accepted way of doing this in JSON Schema land, but pedantic doesn't generate that particular JSON Schema type.

Considering the role of text labels is just describing values. I think maybe we can generate a `description` for an enum field like https://github.com/tfranzel/drf-spectacular/blob/0.26.2/drf_spectacular/hooks.py#L123-L128.


### Combine `oneOf` and `const` for [django.db.models.enums.Choices](https://github.com/django/django/blob/0a306f7da668e53af2516bfad759b52d6c650b69/django/db/models/enums.py#L62)

![image](https://user-images.githubusercontent.com/8749411/236772562-e47aa8a9-7c6f-45bf-a6e9-b9457e6ac902.png)

### drf-spectacular approach

![image](https://user-images.githubusercontent.com/8749411/236772605-88bea056-ccbb-45f0-8951-4134ffc9b3af.png)

**Comment by adriangb** [comment]
Would something like this work?

<img width="682" alt="image" src="https://github.com/pydantic/pydantic/assets/1755071/a514651f-1677-41de-933b-d36ceabaff95">

I would like that to be generatable using:

```python
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field

Apple = Union[
    Annotated[
        Literal[1],
        Field(title='Red Delicious'),
    ],
    Annotated[
        Literal[2],
        Field(title='Cosmic Crisp'),
    ]
]


class Model(BaseModel):
    apple: Apple


print(Model.model_json_schema())
"""
{"type": "object", "properties": {"apple": {"anyOf": [{"const": 1}, {"const": 2}], "title": "Apple"}}, "required": ["apple"], "title": "Model"}
"""
```

But unfortunately the `title` gets dropped at the moment, which I would call a bug. But I'd like to know if this is even what all of you want before trying to fix this bug (if it is a bug at all).

**Comment by dodumosu** [comment]
> Actually, this minimal code does the trick for my (limited) use case, and it correctly type-checks `.value` and `.label`:
> 
> ```python
> # labelled_enum.py
> """
> A special Enum that plays well with ``pydantic`` and ``mypy``, while allowing human-readable
> labels similarly to ``django.db.models.enums.Choices``.
> """
> from typing import TypeVar, Type
> import enum
> 
> T = TypeVar("T")
> 
> 
> class LabelledEnum(enum.Enum):
>     """Enum with labels. Assumes both the value and label are strings."""
> 
>     def __new__(cls: Type[T], value: str, label: str) -> T:
>         obj = object.__new__(cls)
>         obj._value_ = value
>         obj.label = label
>         return obj
> ```
> 
> ```python
> # labelled_enum.pyi
> import enum
> 
> class LabelledEnum(enum.Enum):
>     @property
>     def label(self) -> str: ...
>     @property
>     def value(self) -> str: ...
> ```
> 
> ```python
> # example usage
> class RunnerType(LabelledEnum):
>     LOCALFS = "localfs", "Local FS"
>     SGE = "sge", "SGE"
> ```
> 
> Again, `__modify_schema__` can easily be defined in `LabelledEnum` if desired -- I don't personally need it.
> 
> Hope this helps.

it's been a while since I opened this issue :) just wanted to say that in the Python standard library, something like this is used for `httplib.HTTPStatus`. it's actually an `enum.IntEnum` subclass with extra data associated with each member.

**Comment by akvadrako** [comment]
How was this solved? I cannot find documentation on how to use it.
