### ISSUE TITLE
BaseSettings subclass which automatically sets env_prefix and instantiates

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/pydantic#1450]
I recently wrote this package: https://github.com/alexmojaki/dryenv

Copying from the docs:

---

`DryEnv` is simply a thin wrapper around [`pydantic.BaseSettings`](https://pydantic-docs.helpmanual.io/usage/settings/), which does most of the heavy lifting. `DryEnv` just makes things a little neater and more convenient by automatically:

1. Setting `env_prefix` based on the class name.
2. Instantiating the class to trigger the environment lookups.
 
For example, this:

```python
from dryenv import DryEnv

class DATABASE(DryEnv):
    HOST = "localhost"
    USERNAME = "admin"
    PASSWORD = "secretpassword"
```

is roughly equivalent to:

```python
from pydantic import BaseSettings

class DATABASE(BaseSettings):
    class Config:
        env_prefix = "DATABASE_"

    HOST = "localhost"
    USERNAME = "admin"
    PASSWORD = "secretpassword"

DATABASE = DATABASE()
```

---

It occurs to me now that there's not really much reason for this to be a separate package, it could easily be in pydantic itself. `BaseSettings` obviously can't be changed like this for compatibility, but a new class would be fine.

What do you think? Should I make a PR, or keep this as a separate package?

**Comment by samuelcolvin** [comment]
personally I don't think I would use it.

But if there's sufficient interest in the feature I would accept it since it would be pretty self contained.

Shall we say 10 upvotes on the issue?

**Comment by alexmojaki** [comment]
Sounds like a good plan. I'll release the package and link to this issue. I don't really mind either way.

**Comment by dmontagu** [comment]
We're moving `BaseSettings` into [pydantic-settings](https://github.com/pydantic/pydantic-settings); I think our preference will be to keep this as a separate package, but if this becomes a more desired feature request again, feel free to open a new issue there.
