### ISSUE TITLE
Reusable pydantic models: the same model with different constraints

### ISSUE THREAD

**Issue by ka-zo** [pydantic/pydantic#1462]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: False
                 install path: D:\<my path>\venv\Lib\site-packages\pydantic
               python version: 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10 <my win version>
     optional deps. installed: ['email-validator']
```

This Feature Request is a follow-up of the Question  #1365 . It is more and more obvious to me, that it causes a lot of headache that there is no way to reuse a model with different constraints. Your suggestion in Question  #1365 was to sub-class a certain model and redefine the class fields with different constraints, in case I wanted to change them. This is ok in exceptional cases, but not as a best practice, which should be used on a daily basis. Imagine the following use case: I want to define a percentile class, something like the following class:

```py
from pydantic import BaseModel, Field

class PercentileValueIn(BaseModel):
    unit: PercentileUnit = Field(...)
    value: float = Field(
        ...,
        description="Value of the percentile.",
        ge=3,
        le=97,
    )
...
```

Now, the interesting part is the value field, where we have the constraints. Imagine, that I want to use this model to represent body height percentile, body blood pressure percentile, body weight percentile, and there are even more different body parameters, for which we can further use this model. However during a body property measurement campaign, the resulting data tables for each body property show a specific percentile range. For example the weight percentile is defined between 3% and 97%, the blood pressure percentile is defined between 50% and 99%, the height percentile - relative to which the blood pressure percentile defined - is defined between 5% and 95%. Your suggestion according to Question  #1365 would result in many redundant percentile models (many percentile class definition, for which you need to find a proper name, you need to maintain them, etc.). However, they are logically the same models reused multiple times, with different constraints.

So my feature request is to allow users to redefine the constraints on the fly, without the need of sub-classing.

Thank you for considering my feature request.

**Comment by samuelcolvin** [comment]
You don't need to define every possible submodel, just create it dynamically with the range you want when you want to do validation.

That said, I do see some cases where a feature like this would be useful, e.g. when selecting a choice `int` corresponding to a foreign key, where the choices are dynamically set based on which uses is using the form, e.g.:

```py
class Message(BaseModel):
    str: message
    friend_id: int  # <-- this should be choice based on who the current user's friends are
```

I'll think more about how best to achieve this.

**Comment by ka-zo** [comment]
Can you please point me to that part of the pydantic documentation, which explains this in more details:

> just create it dynamically with the range you want when you want to do validation.

Concerning the rest of your comment, some dynamic model behavior would be indeed nice to have.

**Comment by xgenvn** [comment]
@ka-zo perhaps `validators` documentation is what you are looking for.
https://pydantic-docs.helpmanual.io/usage/validators/

However, I can see the benefits of using dynamic field value validation. I'm just not seeing how things work since almost the types are using in the parameter declaration, I don't know if we can declare a type with initial method to pass the dynamic values in. The possible way I can think of is adding a decorator, but well is it just over-engineering? Subclasses should be reasonable due to `separation of concerns` imo.

**Comment by samuelcolvin** [comment]
this is generics, it works great on main and in V2.
