### ISSUE TITLE
`validate_arguments` skip arguments.

### ISSUE THREAD

**Issue by juan-carlos-calvo** [pydantic/pydantic#1465]
# Feature Request

`validate_arguments` validates all arguments by default. I would love to be able to choose which ones to validate, e.g.:
```
@validate_arguments(['arg2', 'arg3'])
def myfunc(arg1: int, arg2: float, arg3: MyType):

```

**Comment by samuelcolvin** [comment]
happy to consider this, question is how complicated it would be to implement.

**Comment by juan-carlos-calvo** [comment]
probably not that complicated. I'm writing this decorator myself right now. I'm basically applying `validate_arguments` on a partial version of the decorated function which only takes as input the arguments of interest. The only "challenging" part is to parse the arguments of the function to do so.

**Comment by yosoycentli** [comment]
Hi there, I would like to know how this issue was going.
Maybe I can contribute.

**Comment by smhavens** [comment]
Is this issue still open to work on? I would be interested if so!

**Comment by ybressler** [comment]
I've taken a look at where I think changes would need to be introduced to make this happen, specifically: [pydantic/decorator.py](https://github.com/pydantic/pydantic/blob/2e17c85810fd7e335422dcbf2525d019cfeb5d8c/pydantic/decorator.py#L225)

Introducing this new behavior introduces some ambiguity, for example, say I have a function with required positional arguments:
```
def do_things(required_field: str, optional_field: Optional[str] = None):
    pass
```
Applying the following values: `@validate_arguments(['optional_field'])` basically means I'm turning my `required_field` into an optional one, which may validate an invalid function. (Meaning, the validator will pass but the function will encounter a `TypeError` Unless this is desired?)

**Comment by ybressler** [comment]
AHA. I'm reading a bit further, perhaps the correct place to override this behavior is within the `config` argument of the validator! https://docs.pydantic.dev/usage/validation_decorator/#custom-config

I'll go deeper here. This is fun.

**Comment by dmontagu** [comment]
In v2, the right way to do this would be to create an annotation that causes it to skip validation by using a pydantic core any schema. This would be done via:

```python
from typing import Any, Annotated

from pydantic_core import core_schema

from pydantic import validate_call


class SkipValidation:
    @classmethod
    def __get_pydantic_core_schema__(self, _source: Any, _handler: Any) -> core_schema.CoreSchema:
        return core_schema.any_schema()


@validate_call
def my_function(x: int, y: Annotated[int, SkipValidation]) -> None:
    print(repr(x), repr(y))


my_function('1', '2')  # validation will be done to x, but not to y
#> 1 '2'
```

Actually I will just open a PR adding this type to pydantic proper.
