### ISSUE TITLE
potential DOS risk with pydantic - fix pending

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#1477]
I have been made aware of a potential DOS attack risk in pydantic.

The fix I believe is relatively trivial, I will release:
* `v1.5.2` based of the current `v1.5.1` tag
* `v1.4.1` based of the current `v1.4` tag

These releases will be made just after **1pm UTC** on **2020/5/11**, that's next Monday.

If you require a fix to any other version, please let me know on this issue.

**Comment by samuelcolvin** [comment]
To wait for potential upstream fixes to this issue, these releases have been delayed.

I'll comment here as soon as I know when a fix can be released for pydantic.

**Comment by PrettyWood** [comment]
Is this issue still necessary?

**Comment by samuelcolvin** [comment]
The python security team are refusing to fix the the upstream error (because it would be complex, and I think a little because they're embarrassed) but have ask packages not to mitigate the problem in libraries to avoid making public.

The whole situation is extremely frustrating.

**Comment by mruser** [comment]
Hi Samuel, is the underlying vulnerability still present in the upstream such that the DOS risk survives in the current version of the library? If not, what version was the issue resolved in? Thank you.

Also, I believe we are _well_ into responsible disclosure territory with respect to the upstream, given the time period that has elapsed.

**Comment by malipek** [comment]
Is the vulnerability somehow connected to the [well known issues with NaN implementation](https://blog.bitdiscovery.com/2021/12/python-nan-injection/)? If so, the issue should be closed, in my opinion.

**Comment by samuelcolvin** [comment]
No

**Comment by dmkr** [comment]
Is this issue on all versions of Pydantic, on version 1.4 and beyond, or only on 1.4 and 1.5.1?

**Comment by samuelcolvin** [comment]
This has now been made public and it seems a fix will be out soon.

https://github.com/python/cpython/issues/95778

If you're parsing, JSON the simplest solution is to use ujson which doesn't suffer from this problem.

I'll see if I can get a fix it which limits input to ints soon.
