### ISSUE TITLE
Improve BaseModel.__eq__ performance

### ISSUE THREAD

**Issue by zoopp** [pydantic/pydantic#1494]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/mihai/.local/share/virtualenvs/vmcs-smsc-nYWUkkuU/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Apr  8 2020, 14:31:25)  [GCC 9.3.0]
                     platform: Linux-5.5.19-1-ck-x86_64-with-glibc2.2.5
     optional deps. installed: ['devtools']

```
I've been trying out pydantic in one of my projects and came across a serious performance issue that unfortunately I am not able to reproduce in isolation. At this point I'm unsure if I am doing something wrong or if there is an issue in pydantic.

Essentially, I have the following class declared in my project that I was initially using with standard dataclasses:

```python
import pydantic
from pydantic import dataclasses

#@dataclasses.dataclass
#class ProtocolValue:
class ProtocolValue(pydantic.BaseModel):
    type: str
    value: Any

#    @classmethod
#    def construct(cls, **kwargs):
#        return cls(**kwargs)
```

This class is used extensively. Instances are created, passed around and destroyed heavily and because of this, I made sure to use `construct` everywhere.

I have a couple of unit tests that simulate heavy workload which when I run them with the class deriving from `pydantic.BaseModel` they take around 3 minutes to run. If I use the `dataclass` form by removing the comment markers and fixing up the code above the the total time drops down to about 44 seconds.

By looking over some profiling data that I captured using `pytest-profile` the following two entries seem suspicious (they are in 2nd and 3rd place sorted by total time; 1st and 2nd sorted by total number of calls):
```
 ncalls          tottime    percall cumtime  percall filename:lineno(function)
 54371496   21.687    0.000   42.711    0.000   /usr/lib/python3.8/abc.py:96(__instancecheck__)
 54371496   21.023    0.000   21.024    0.000   {built-in method _abc._abc_instancecheck}
```

In comparison to pydantic.BaseModel, the dataclass variant has an insignificant number of calls:
```
      126    0.000    0.000    0.001    0.000 /usr/lib/python3.8/abc.py:96(__instancecheck__)
      126    0.000    0.000    0.000    0.000 {built-in method _abc._abc_instancecheck} 
 ```

I'm a bit lost right now and unsure what to make out of it. Does anyone have any idea on how to follow up on this?

**Comment by zoopp** [comment]
Upon further investigation I figured out how to reproduce the issue in isolation. In my unit tests I do a lot of `x in <very_big_list_of_items>` checks and this is where the delay is coming from.

Bellow is a self-contained piece of code that shows the behavior I'm talking about:

```python
import dataclasses
import random
import string
import timeit
from typing import Any

import pydantic

random.seed(1)  # Always generate the same 'random' values


def random_string(length):
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(length))


class PydanticObject(pydantic.BaseModel):
    type: str
    value: Any


@pydantic.dataclasses.dataclass
class PydanticDataclassObject:
    type: str
    value: Any


@dataclasses.dataclass
class StdDataclassObject:
    type: str
    value: Any


pydantic_list = [
    PydanticObject.construct(
        type=random_string(6),
        value=random.randint(1, 1000)
    )
    for i in range(10000)
]
pydantic_dataclass_list = [
    PydanticDataclassObject(type=o.type, value=o.value)
    for o in pydantic_list
]
std_dataclass_list = [
    StdDataclassObject(o.type, o.value)
    for o in pydantic_list
]


std_dataclass_list = 'std_dataclass_list[-1] in std_dataclass_list'
pydatic_dataclass_test = 'pydantic_dataclass_list[-1] in pydantic_dataclass_list'
pydantic_model_test = 'pydantic_list[-1] in pydantic_list'

print(
    'dataclasses.dataclass: ',
    timeit.timeit(std_dataclass_list, number=200, globals=globals())
)
print(
    'pydantic.dataclasses.dataclass: ',
    timeit.timeit(pydatic_dataclass_test, number=200, globals=globals())
)
print(
    'pydantic.BaseModel: ',
    timeit.timeit(pydantic_model_test, number=200, globals=globals())
)
```

On my machine I get the following results:
```
dataclasses.dataclass:  3.961700713261962e-05
pydantic.dataclasses.dataclass:  1.3102007849956863
pydantic.BaseModel:  28.17944354697829
```
- `pydantic.dataclasses.dataclass` is 33071x (!!) slower than `dataclasses.dataclass`
- `pydantic.BaseModel` is 711296x (!!!) slower than `dataclasses.dataclass`
- `pydantic.BaseModel` is 21.5x slower than `pydantic.dataclasses.dataclass`

**Comment by zoopp** [comment]
This difference in performance in my particular case is caused by the generic way in which `BaseModel.__eq__` is implemented. At the moment, it works by doing a hidden conversion to `dict` on both objects being compared and then comparing the resulting dicts for equality.

In contrast, standard dataclasses build the `__eq__` function (among other things) for each dataclass to do direct field by field comparisons. For example, in case of:
```py
@dataclass
class TestModel:
    a: int
    b: int
```

The body of `TestModel.__eq__` will literally be implemented as:
```py
def __eq__(self, other):
    if other.__class__ is self.__class__:
        return (self.a, self.b) == (other.a, other.b)
    raise NotImplemented
````

Would there be any issues if pydantic adopts the same strategy of generating some of the functions instead of relying on generic expensive behavior?

**Comment by samuelcolvin** [comment]
I'd be very happy to see a performance improvement in `__eq__`, my concerns are:
* how do we make it reliable
* what do we do about backward compatibility

I think we can drop the conversion to dict and accept a breaking change that 'dict(a=1, b=2) != MyModel(a=1, b2)` in v2, where in v1 I think they were equal.

Obviously pydantic is call `eval` to generate models, so we can't just synthesise a simple and fast `__eq__` method as I guess dataclasses do.

could we do something as simple as:

``py
    def __eq__(self, other: Any) -> bool:
        return other.__class__ == self.__class__ and self.__dict__ == other.__dict__
```
?

Should we also include `and self.__fields_set__ == other.__fields_set__`?

**Comment by zoopp** [comment]
Hey @samuelcolvin, I haven't forgotten about this issue but I'm somewhat short on time these days and wasn't able to look too much into it.

I worked around my original issue by manually implementing  `__eq__` where I had to like this (the main focus being on eliminating as much overhead as possible):
```py
    def __eq__(self, other: Any) -> bool:
        if isinstance(other, MyClass):
            return (self.a, self.b) == (other.a, other.b)
        return super().__eq__(other)
```

I realise this approach might not hold for the general case given the way pydantic is currently implemented but then again I still have some way to go with familiarizing myself with pydantic's implementation. 

Regarding this comment:

> Obviously pydantic is call eval to generate models, so we can't just synthesise a simple and fast __eq__ method as I guess dataclasses do.

Dataclasses do synthesise class methods using `eval`. E.g. take a look at https://github.com/python/cpython/blob/e005ead49b1ee2b1507ceea94e6f89c28ecf1f81/Lib/dataclasses.py#L946, especially the implementation of `_cmp_fn` and `_create_fn` .

Do you think we would be able to use this somehow in pydantic to make some functions faster?

**Comment by samuelcolvin** [comment]
I've updated my comment above to make sense and be correct (it had so many typos it made no sense).

The point is that dataclasses uses `eval` while pydantic does not. Pydantic can't use `eval` since it's compiled with cython which clearly can't support code generated from `eval()`. Thus we have to something completely different.

**Comment by tstorek** [comment]
If '__eq__' would be refactored it would be also nice to introduce an kwarg in Field in order to add it to compare or not with default true. 
I think that in that case for eq we could use the Model.dict(exclude={all field that have compare=false}). As it is also possible in pydantic.dataclasses.field().
At the moment I do not understand why this not possible.

**Comment by adriangb** [comment]
We've changed this in V2 and no longer convert the model to a dict. For the benchmarks in https://github.com/pydantic/pydantic/issues/1494#issuecomment-626303816 I get:

```
dataclasses.dataclass:  0.2761917499592528
pydantic.dataclasses.dataclass:  0.27540237503126264
pydantic.BaseModel:  0.9767189580015838
```

Still slower than dataclasses, but still much faster than V1!
