### ISSUE TITLE
Allow BaseSettings to accept multiple `.env` files in Config as a list

### ISSUE THREAD

**Issue by autoferrit** [pydantic/pydantic#1497]
# Feature Request
From an existing app structure we used internally prior to starting a new project using pydantic, we had some of our ENV variables for our app in multiple env files. with a layout as follows
`.envs/[ENVIRONMENT]/.env` and `.envs/[ENVIRONMENT]/.env.database`

We mostly did this simply to keep concerns separated and most of the .env parsing libraies can't handle a line of code that is not setting an env such as `. .env.production` to source another env file from the existing one.

So my request is that the `BaseSettings.Config.env_file` setting is able to take a list of strings/Path objects. I suppose this would make the type something like
```python
Config:
    env_file: Optional[Union[Path, str, List[Union[Path, str]]]]
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```bash
❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/shawn/.cache/pypoetry/virtualenvs/bohemian-UricMOIx-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.1 (default, Mar  3 2020, 18:39:00)  [GCC 9.2.1 20200130]
                     platform: Linux-5.4.35-1-MANJARO-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions', 'email-validator']
```

**Comment by samuelcolvin** [comment]
Yes, I want this too.

PR welcome.

Priority is important and needs to be explicit, see [how CRA handles this](https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used).

**Comment by autoferrit** [comment]
Reading that, it might also be nice to be able to point simply to a directory. I have a dir setup like so:
```bash
deployment
├── __pycache__
│  └── gunicorn_conf.cpython-38.pyc
├── base
│  └── Dockerfile
├── development
│  ├── .env.database
│  └── .env
├── production
│  ├── .env.database
│  ├── .env
│  ├── docker-compose.yml
│  └── Dockerfile
├── testing
│  └── .env
├── docker-compose.override.yml
├── docker-compose.yml
├── Dockerfile
├── gunicorn_conf.py
├── prestart.sh
├── start-reload.sh
└── start.sh
```
and it would be pretty great, if we could point to a directory, and it could load `.env`'s based on env name (I have an env: `APP_ENVIRONMENT: Literal["development", "production", "testing"]`) and if we pointed to a dir, it would look for, in order based on your link
```
ENV_DIR/[ENVIRONMENT]/.env.local
ENV_DIR/[ENVIRONMENT]/.env
```
I like to split out my database env in its own file. so maybe it will look for `.env` files and anything other than `.local` could be loaded in as a different config. Which means it would change to
```
ENV_DIR/[ENVIRONMENT]/.env.local
ENV_DIR/[ENVIRONMENT]/.env
ENV_DIR/[ENVIRONMENT]/.env[.name].local
ENV_DIR/[ENVIRONMENT]/.env[.name]
```
Though, that might be harder to do. Not many probably do that so maybe not worth it. 
Maybe we keep `_env_file` as it is but also allow a list of them, and also add `_env_dir` for the `auto discovery` of files.

**Comment by samuelcolvin** [comment]
Let's just go with `env_file` allowing a list (first value takes priority over second etc.).

Pydantic already has a complicated system for priority: init arguments, env vars, .env, field defaults. 

Adding a list of files names with priorities might blow my mind, let alone casual users of pydantic.

**Comment by rockallite** [comment]
Here's my effort to support `.local.env` files overriding `.env` files by subclassing `BaseSettings`:

```python3
import os

from pydantic import BaseSettings

default_env_ext = ".env"
local_env_ext = ".local.env"


class LocalEnvSettings(BaseSettings):
    def __init__(self, *args, **kwargs):
        default_kws = {}
        env_file = self.__config__.env_file
        if env_file is not None and env_file.endswith(default_env_ext):
            local_env_file = env_file[:-len(default_env_ext)] + local_env_ext
            if os.path.exists(local_env_file):
                default_kws["_env_file"] = local_env_file
        default_kws.update(kwargs)
        super().__init__(*args, **default_kws)
```

You can easily make your own version to fit your business logic.

**Comment by charlax** [comment]
Here's another way to achieve this, following serverless' logic (e.g. for `prod`: load `.env` first, then `.env.prod`, then `.env.prod.local`).

```python
import os
from pathlib import Path

from dotenv import load_dotenv
from pydantic import BaseSettings


ENV_FILENAME = os.environ.get("DOTENV", ".env")

class Config(BaseSettings):
    pass


def get_config() -> Config:
    """Get the config."""
    # We follow serverless's dotenv plugin's behavior here:
    # https://www.npmjs.com/package/serverless-dotenv-plugin

    # First load .env
    load_dotenv(dotenv_path=".env")

    if not Path(ENV_FILENAME).exists():  # nocov
        raise ValueError(f"Config file {ENV_FILENAME} does not exist.")

    if ENV_FILENAME.endswith(".local"):  # nocov
        raise ValueError(
            "Expected env filename like '.env.dev', "
            f"got override ending with .local instead: {ENV_FILENAME!r}. "
            f" Try with {ENV_FILENAME.replace('.local', '')!r}"
        )

    # Then load .env.{env}
    load_dotenv(dotenv_path=ENV_FILENAME)

    # Then load .env.{env}.local if it exists
    override = ENV_FILENAME + ".local"
    if Path(override).exists():  # pragma: no cover
        load_dotenv(dotenv_path=override)

    return Config()
```

**Comment by GussSoares** [comment]
I tried to use multiple inheritance with a `BaseSettings` for each file and at the end, a `Settings` inheriting from all, but it seems to me that the `class Config` of the first inherited class is the one that prevails ...
```python
class BackendSettings(BaseSettings):
    # api
    API_V1_STR: str = '/api/v1'
    ...

    class Config:
        env_file = 'env-backend.env'

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)
        ...


class PostgresSettings(BaseSettings):
    # PG
    PGHOSTADDR: str = None
    PGPORT: int = None
    PGUSER: str = None
    PGPASSWORD: str = None
    PGAPPNAME: str = None
    PGCONNECT_TIMEOUT: int = None

    class Config:
        env_file = 'env-postgres.env'

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)


class Settings(PostgresSettings, BackendSettings):
    pass
```
and as I said, doing it this way, it seems that the `env_file` of the first inherited class is what prevails...

**Comment by gerazenobi** [comment]
Hi there 

I just wanted to ask, what is the "workaround" today to being able to use 1 `env` file by environment? E.g.

```
.env   # "default"  always loaded.

.env.development    # overrides/adds to `env`
.env.staging              # overrides/adds to `env`
.env.production        # overrides/adds to `env`
```

I feel this issue is somewhat also related to #2106 and its PR #2107. E.g. in staging / production we might want a different source to override `.env` and `.env.production`

All of the above driven for instance by the presence of a simple OS environment variable like  `ENVIRONMENT_PROFILE=production` then in order app would load `.env` as always, then adds to it and/or overrides with `.env.production` and if so on if an additional source is configured to take precedence...

Any insights are appreciated 👍

**Comment by bkis** [comment]
Isn't this one obsolete since #3222 got merged?

**Comment by dmontagu** [comment]
I believe this has been implemented in the BaseSettings now included in [`pydantic-settings`](https://github.com/pydantic/pydantic-settings) for use with v2, @hramezani can you confirm? If so, please close this issue.

**Comment by hramezani** [comment]
@dmontagu you are right
