### ISSUE TITLE
datetime validation is less strict than the documentation suggests

### ISSUE THREAD

**Issue by pganssle** [pydantic/pydantic#1573]
# Bug
The documentation for [datetime types](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) suggests the following string types are acceptable:

- `YYYY-MM-DD[T]HH:MM[:SS[.ffffff]][Z[±]HH[:]MM]]]`
- `int` or `float` as a string (assumed as Unix time)

But the actual parser accepts much looser formats, including some pretty funky ones, because month, day, hour, minute and second are all allowed to be 1 digit:

```python
>>> from pydantic.datetime_parse import parse_datetime
>>> parse_datetime('1915-5-9T14:1:2')
datetime.datetime(1915, 5, 9, 14, 1, 2)
```

I suppose the easy thing to do would be to update the documentation to reflect this, but I think the *right* thing to do would be to deprecate those unusual formats or put them behind a flag of some sort. They're not formats that are in common use.

**Comment by samuelcolvin** [comment]
Thanks for reporting. Let's fix in V2, we should also double check documentation exactly matches logic then.

Happy to accept a PR now to correct docs.

**Comment by samuelcolvin** [comment]
This is fixed in pydantic-core I believe using [speedate](https://github.com/samuelcolvin/speedate), will be released in V2.

Let me know if the rules applied by `speedate` are not satisfactory.
