### ISSUE TITLE
Document Field(...) properly

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#1664]
Currently there's no real documentation for `Field(...)` it's used in many places but there's no properly documentation for what it can do and why you might use it.

It probably deserves it's own page.

This should be easy if anyone wants to start helping pydantic.

**Comment by eb538** [comment]
Hi @samuelcolvin im interested in starting to help pydantic and this seems like a great place as i use `Field` all the time (though im not yet framiliar with all the options). it does seem like there is some existing documentation on the available parameters [here](https://github.com/samuelcolvin/pydantic/blob/259a1a0ff8eb9a0c4450331b9bae6730d55b9124/docs/usage/schema.md#field-customisation): 

When you say it "probably deserves its own page" would you image its a heading in the "Usage" section directly after 'Schema' like 'Field' or 'Field Specification' or as a subsection of Schema.

Happy to take this on and just submit an example PR if that's easier than discussion in the issue.

**Comment by Ronserruya** [comment]
I assume this can be closed? 
This looks like enough
https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation
