### ISSUE TITLE
Alias documentation

### ISSUE THREAD

**Issue by daturkel** [pydantic/pydantic#1681]
# Question / Suggestion

Hi Samuel, thanks for your work on the great library! I had a thought about the documentation regarding `alias`.

The [schema documentation section on field customization](https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation) describes alias as:
> alias: the public name of the field

However, I find this somewhat ambiguous. My first impression upon reading the above was this:
```python
class Foo(BaseModel):
    private_name: int = Field(0, alias="public_name")

foo = Foo()

# I thought that this would work, though it does not:
foo.public_name

# I wasn't sure which of these would work:
foo2 = Foo(public_name=1)
foo3 = Foo(private_name=1)
```

I'm not suggesting changing the behavior, but simply clarifying the documentation. Something along the lines of:
> alias: The name which maps to a field during population/initialization.

Or even just adding a **Note** block below to clarify what "public name" means here (namely, that it's _not_ the name used to _access_ the field.

Thanks!

**Comment by samuelcolvin** [comment]
I agree, very poor description. 

PR welcome to correct it.

**Comment by adriangb** [comment]
I'm closing this since we'll be rewriting all of these docs for V2
