### ISSUE TITLE
Explicit `required` declarations

### ISSUE THREAD

**Issue by ccrvlh** [pydantic/pydantic#1769]
# Feature Request

First, would like to give a big thank you for the library, which has been working flawlessly w/ FastAPI.
I'm pretty sure this has been given a lot of though, given how well though the library is.

I've been missing an explicit way of declaring `required` fields.
I can see the upside of using native type declarations, but for me, personally, the cost seems just too high.
SQLAlchemy, eg, has been using "custom" type declarations, and it seems something pretty easy for people to get a hold on of.

The thing that bothers me the most is the way `required` is treated.
`class Schema(BaseModel):
    myfield: str
`
is implicitly saying the field is required. When working with large data models (50+ JSON Fields), my experience is that most of the fields are not required, while normally very specific fields are required, so in my mind would make more sense to make the default optional, and then pass a (required=True) if that's the case. I personally prefer the explicit way of declaring it.

On top of that, Union[str, None], is tricky, since it will fill optional fields with None, which will directly affect update operations. Having to add `exclude_unset` seems a bit odd.

Anyways, I'm sure this has been given a lot of though, since I'm guessing this was a design choice, but I just wonted to expose my 2c on this matter.

One way of still enjoying the current behaviour while giving extra flexibility for the end user, would be allow for a parameter to be `set`, something like `defaults: {required=True}` or `defaults: {required=False}`. For `required = False`, the user would have to use custom type variables, but would have greater flexibility.

Still, great lib, and thanks a lot for sharing it.
Best,

**Comment by Kludex** [comment]
On Pydantic V2, the behavior on `Optional` fields changed. When you have an `Optional[T]` field, it will actually mean that it accepts either `None` or `T`.

I hope the above helps. If don't, please open a new issue. 🙏
