### ISSUE TITLE
json_encoders for objects that serialize down to a json string does not work

### ISSUE THREAD

**Issue by davidolrik** [pydantic/pydantic#1778]
# Feature Request

I have an object with a few properties that I want to serialize down to a string, but as the sub-models are already converted to dicts when the data is passed to `json.dumps` my own overridden `.json()` method is never called.
(This might be related to #252)

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jun 24 2020, 17:19:11)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: []
```

Here is an example that illustrates the issue:

```py
from pydantic import BaseModel


class Foo(BaseModel):
    p1: str
    p2: str

    def json(self):
        return f'"{self.p1}{self.p2}"'


class Bar(BaseModel):
    foo: Foo


if __name__ == "__main__":
    foo = Foo(p1="a", p2="b")
    print(foo.json())

    bar = Bar(foo=foo)
    print(bar.json())
```

This small program outputs the following:
```
"ab"
{"foo": {"p1": "a", "p2": "b"}}
```

But I would like it to output the following:

```
"ab"
{"foo": "ab"}
```

**Comment by davidolrik** [comment]
I figured out that I could override ` .dict()` as follows:

```py
def dict(self, by_alias=None, exclude_unset=None, exclude_defaults=None, include=None, exclude=None, exclude_none=None):
        return f'{self.p1}{self.p2}'
```

But that seems like the wrong way to do it, as I would give up the dict() functionality for something that only relates to json.

**Comment by cryptonoel** [comment]
@davidolrik Did you manage to find a "neater" solution other than overriding the `dict` function?

**Comment by samuelcolvin** [comment]
The new serialisation logic to should solve this.

This is fixed on main and will be included in V2, you can try it now on the alpha release.
