### ISSUE TITLE
Treat NaN as None/null

### ISSUE THREAD

**Issue by vkolotov** [pydantic/pydantic#1779]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/*/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Apr  1 2020, 05:50:17)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

On our project we have to deal with pandas. Pandas treats "non existing values" (nulls) as NaN (which is weird in the first instance, nevertheless we have to live with that). We use pydantic to validate data that is generated by pandas, in order to do this we convert pandas DataFrame to dictionary (or list of dictionaries) and then convert dictionaries to pydantic dataclasses. The resulted dataclasses are serialised into json (then stored in DB or in Elasticsearch). 

The problem here is, DataFrame's may contain NaN values, they get transferred to pydantic dataclasses without any error (as NaN is an instance of float), then those NaNs get serialised into json as nulls (which is not correct, they are not optional). 

We would like to catch this "nullability" issue as a part of the normal pydantic validation, e.g. if a float field that is not Optional gets assigned with NaN, we would like to get a validation error (e.g. None is not allowed value). 

Providing custom validators via `@validator` or via `__get_validators__ ` is not an option as we don't want to specify all these for each dataclass. What would be great if we could:
1. Either specify a replacement for `pydantic.validators.float_validator` and make it global/default.
2. Or "configure" somehow pydantic so that the existing `validators.float_validator` correctly handles NaNs.

There is another solution that we currently use - defining custom type for float, but this requires using this type in each dataclass. It is a viable solution, but still not great.

**Comment by PrettyWood** [comment]
Hello @vkolotov
Thank you for you feedback and for having thought about different solutions. But your usecase seems very precise and I'm afraid the desired feature would add a lot of complexity for no real benefit.
A solution like this one doesn't help at all ?

```python
from math import isnan

from pydantic import BaseModel as PydanticBaseModel, validator


class BaseModel(PydanticBaseModel):
    @validator('*')
    def change_nan_to_none(cls, v, values, field):
        if field.outer_type_ is float and isnan(v):
            return None
        return v


class Model(BaseModel):
    a: float
    b: float


class Model2(BaseModel):
    m: Model
    n: float


model = Model(a=float('nan'), b=3.1)
print(repr(model))
print(repr(Model2(m=model, n=float('nan'))))
```

```bash
Model(a=None, b=3.1)
Model2(m=Model(a=None, b=3.1), n=None)
```

**Comment by Djeramon** [comment]
In case someone else wants to use the code sample above. There is an error in the signature of change_nan_to_none, which will cause an error. The correct signature is:

`def change_nan_to_none(cls, v, values, config, field):`

**Comment by ToddG** [comment]
> I think there is an error in the signature of change_nan_to_none, which will cause an error. The correct signature should be:
> 
> `def change_nan_to_none(cls, v, values, config, field):`

According to the docs, the original method signature is correct, and your additions are also correct, but optional:

```
A few things to note on validators:

    validators are "class methods", so the first argument value they receive is the UserModel class, not an instance of UserModel.
    the second argument is always the field value to validate; it can be named as you please
    you can also add any subset of the following arguments to the signature (the names must match):
        values: a dict containing the name-to-value mapping of any previously-validated fields
        config: the model config
        field: the field being validated. Type of object is pydantic.fields.ModelField.
        **kwargs: if provided, this will include the arguments above not explicitly listed in the signature
```

See: https://pydantic-docs.helpmanual.io/usage/validators/

**Comment by Moisan** [comment]
It seems like the root issue is the inability of Pydantic to refuse NaN without a field specific validation. I think it would be useful to have a specific [constrained type](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types) for floats that accepts all floats except NaN.

**Comment by adriangb** [comment]
I think this workaround will be easier in V2 because you can create a "constrained type" much easier and integrate it with type checkers, IDEs, etc.

```python
from math import isnan
from typing import Annotated, Any, Optional, TypeVar

from pydantic import BaseModel
from pydantic.annotated_arguments import BeforeValidator


def coerce_nan_to_none(x: Any) -> Any:
    if isnan(x):
        return None
    return x

T = TypeVar('T')

NoneOrNan = Annotated[Optional[T], BeforeValidator(coerce_nan_to_none)]


class Model(BaseModel):
    a: NoneOrNan[float]
    b: NoneOrNan[float]


m = Model(a=float('nan'), b=3.1)
assert m.a is None
assert m.b == 3.1
```
