### ISSUE TITLE
Raise exception or warning when importing pydantic.typing.Literal if typing_extensions is not found

### ISSUE THREAD

**Issue by hkennyv** [pydantic/pydantic#1819]
Is it possible to add some kind of exception or warning in L71-72 of this snippet? The current behavior silently sets `Literal` to `None`, which could cause problems.

IMO, raising an [ImportWarning](https://docs.python.org/3/library/exceptions.html#ImportWarning) sounds appropriate here.

https://github.com/samuelcolvin/pydantic/blob/44616e35cb0ddd97af07b95d7209176a29bfea49/pydantic/typing.py#L65-L74

Happy to submit a PR once I understand the intended behavior. Thanks for the great package!

**Comment by Kludex** [comment]
`typing-extensions` is now included as dependency, so the problem is solved. 🙏
