### ISSUE TITLE
add better support for custom types

### ISSUE THREAD

**Issue by mortezaPRK** [pydantic/pydantic#1829]
# Feature Request
right now, to add a new type to pydantic, we have to create a custom class and add validation logic to it.

this has some drawbacks.
* there is no simple way to add json representation to a type. (or is it?)
* we have to create a wrapper class for third-party types.

let's say, I want to use `ObjectId` from `pymongo` package. right now, I have to create a wrapper class for it. which make my app more complex. so, my current approach is to monkey patch stuff:)
```python
def _patch_object_id():
    @classmethod
    def _gv(cls):
        yield cls.validate

    @classmethod
    def _v(cls, value):
        try:
            return cls(value)
        except InvalidId:
            raise TypeError('Invalid ObjectID')

    @classmethod
    def _ms(cls, field_schema: dict):
        field_schema['type'] = 'string'

    ObjectID.__get_validators__ = _gv
    ObjectID.validate = _v
    ObjectID.__modify_schema__ = _ms
    ENCODERS_BY_TYPE[ObjectID] = str
```

this is ugly.

I think it's better to have to type of `custom type` in pydantic.
first type is what is currently implemented in library (name it `bound` types)
second type is added to library in runtime (name it `unbound` types)

for example:
```python
from bson.objectid import ObjectId
import phonenumbers
import pydantic

pydantic.types.add_type(
   ObjectId,
   to_json=lambda o: str(o),
   from_json=lambda o: ObjectId(o),
   validators=[ObjectId.validate]
   representation=dict(type='string', example='597215645434223165')
)

pydantic.types.add_type(
   phonenumbers.PhoneNumer,
   to_json=lambda o: phonenumbers.format_number(o, phonenumbers.PhoneNumberFormat.INTERNATIONAL),
   from_json=lambda o: phonenumbers.parse(o),
   validators=[phonenumbers.is_valid_number]
   representation=dict(type='string', example='+4 13 12 6932')
)
```

**Comment by samuelcolvin** [comment]
V2 support for custom types is much improved.
