### ISSUE TITLE
Field with const kwarg allows empty value 

### ISSUE THREAD

**Issue by perminovs** [pydantic/pydantic#1835]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: .../.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Oct 28 2019, 16:14:01)  [GCC 8.3.0]
                     platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel, Field

class SomeModel(BaseModel):
    type: str = Field('set', const=True)
    value: str

def try_parse(json_statham):
    try:
        SomeModel.parse_obj(json_statham)
        print('success')
    except ValueError:
        print('cannot parse')

try_parse({'type': 'set', 'value': 'some value'})
try_parse({'type': 'lol', 'value': 'some value'})
try_parse({'value': 'some value'})
```
The result will be:
```
success
cannot parse
success
```
It looks pretty strange, I expect the last one will be `cannot parse` because field 'type' is **required** and I provide no value. Doc says:
```
:param const: this field is required and *must* take it's default value
```

There is a workaround:
```py
from typing import Literal
from pydantic import BaseModel

class SomeModel(BaseModel):
    type: Literal['set']
    value: str
```
but first example looks like bug.

**Comment by PrettyWood** [comment]
Hi @perminovs 
You're right it looks like a bug according to the documentation. In the tests we actually have [one](https://github.com/samuelcolvin/pydantic/blob/e2fcab52b9075826c4a22cc5e8b1502b95d043b8/tests/test_main.py#L384) where default value is expected to be used.
Fixing this would be trivial but IMO it's very weird to write `Field('a', ...)` (so writing a default value) but still expect it to be required.
The `Literal` approach seems like the way to go and maybe we should just
- update the documentation for `const=True`
- deprecate this option
I would be in favor of second option as I can't see what it brings to the table compared to `Literal`. It has been added for schema generation but it just makes things messy. @samuelcolvin WDYT ?

**Comment by perminovs** [comment]
> Fixing this would be trivial but IMO it's very weird to write Field('a', ...) (so writing a default value) but still expect it to be required.

Yes, I'll show our use case for clarifying why we want to use Field with both default and const.
We have json messages with the same structure. While processing we want to hold it as different classes instance, which depends on 'type' value. So we have something like that:
```py
from pydantic import BaseModel, Field

class CreateSomeEntity(BaseModel):
    type: str = Field('create', const=True)
    id: int
    value: str

class UpdateSomeEntity(BaseModel):
    type: str = Field('update', const=True)
    id: int
    value: str

def deserialize(raw):
    for klass in (CreateSomeEntity, UpdateSomeEntity):
        try:
            return klass.parse_obj(raw)
        except ValueError:
            pass
    raise ValueError(f'cannot parse\n{raw}')

invalid_input = {'id': 1, 'value': 'value'}
model = deserialize(invalid_input)
```

That's why successful parsing of `{'id': 1, 'value': 'value'}` is confusing. May be I should provided this example when I had opened the issue :smile:

**Comment by PrettyWood** [comment]
> Yes, I'll show our use case for clarifying why we want to use Field with both default and const.
Doesn't `Literal` work in your case ? It is more explicit and work as expected.
Or do you have a precise example where `const=True` is useful and does something that `Literal` does not

**Comment by perminovs** [comment]
Yep, `Literal` works fine, and we will use it for fix now. But I have learned aboit `Literal` just today. Before we used `Field('set', const=True)` and expected that it raise an error on empty value.
I cannot imagine example when `Literal` does not help. So I think the issue is more about inconsistency between documentation and real behavior.

**Comment by PrettyWood** [comment]
Yep. I'm really in favor of simply deprecating the `const` option since `Literal` has been supported after. IMO it should be the only way to go. Let's wait for @samuelcolvin opinion

**Comment by PrettyWood** [comment]
I added the deprecation of `const` in favor of `Literal` for v2

**Comment by jklaise** [comment]
Perhaps not the right place to ask, but I've failed to find the accepted way of defining _literal collections_. I.e. if I want a constant list `["foo", "bar"]` I could write it like this:

```python
class Model(BaseModel):
    literal_list = Field(["foo", "bar"], const=True)
```
(Note that the original problem still persists, but at least we can define this - though not clear how to type this).

Whereas if `const` is deprecated in favour of `Literal` then it's not clear to me how to achieve the above as `Literal` can't be used to specify literal collections afaik.

**Comment by dmontagu** [comment]
Because we have removed the `const` argument to `Field` in V2, and `Literal` is handled properly, I'm going to consider this issue completed and will close it.

Regarding how to annotate a field as a list of a few allowed literal values — you can actually put multiple items in a literal:

```python
class Model(BaseModel):
    literal_json_list: List[Literal["foo", "bar"]]
```
You won't be able to enforce the order of the items or length of them like this, but it will at least require that it be a list of just those two literal strings.

**Comment by adriangb** [comment]
> You won't be able to enforce the order of the items or length of them like this, but it will at least require that it be a list of just those two literal strings.

To be clear, if you want to enforce the length you can do `Annotated[List[Literal[...]], Field(max_length=10)]`.
If you want to enforce the length _and_ position then you're right, a tuple is your only option, that's just how Python's type system works.
