### ISSUE TITLE
Support skipping default field values

### ISSUE THREAD

**Issue by saulshanabrook** [pydantic/pydantic#1846]
Hello!

I have some models which use the `default_factory` to set the value as a dict or list. Then, in the course of processing them, I mutate that field, then I export them.

I want to not include any fields in the export which don't have any items present, because it's a waste of JSON space, since we have a default set.

I wanted to create an issue, not so much to ask for this feature, but to drop some code as a workaround that I am using in case anyone else has the same problem:

```python
class BaseModel(pydantic.BaseModel):
    # Set fields set to be all those that are truthy, so only those are expoed with `skip_defaults`
    @property  # type: ignore
    def __fields_set__(self) -> typing.Set[str]:  # type: ignore
        s = set()
        for k, v in self.__values__.items():
            if v:
                s.add(k)
        return s

    @__fields_set__.setter
    def __fields_set__(self, val: typing.Set[str]) -> None:
        pass

    def json(self, **kwargs) -> str:
        return super().json(skip_defaults=True, **kwargs)
```

I reused the `__fields_set__` feature to override it with a value that is dynamically computed based on which fields are truthy. Anyways, if anyone else needs to implement custom logic on which fields to serialize and which not to, I suspect you can use a similar method!

Thanks again for this library.

**Comment by Kludex** [comment]
I don't think that logic is needed. You can use the `exclude_defaults` parameter, can't you?

See the code below:

```py
from pydantic import BaseModel, Field


class Model(BaseModel):
    foo: str
    bar: int
    pta: str = Field(default_factory=lambda: "default")


model = Model(foo="a", bar=1)
print(model.json(exclude_defaults=True))
# print(model.model_dump_json(exclude_defaults=True))  # On V2 use `model_dump_json`
```

If I got it wrong, please let me know so I can reopen this issue. 🙏
