### ISSUE TITLE
mypy (as of 0.780) doesn't like passing a Union to parse_obj_as

### ISSUE THREAD

**Issue by brianmaissy** [pydantic/pydantic#1847]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/.../venv/lib/python3.6/site-packages/pydantic
               python version: 3.6.9 (default, Jul 17 2020, 12:50:27)  [GCC 8.4.0]
                     platform: Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions', 'email-validator']
```

contents of `test.py`:
```py
from typing import Union

from pydantic import parse_obj_as

parse_obj_as(Union[float, int], 3.14)
```
```shell
$ mypy test.py
test.py:5: error: Argument 1 to "parse_obj_as" has incompatible type "object"; expected "Type[<nothing>]"
Found 1 error in 1 file (checked 1 source file)
```

I don't know if this is a problem with the type annotation on `parse_obj_as` (maybe the generic type of the first argument) or maybe with the pydantic mypy plugin.

It doesn't happen with mypy 0.770, maybe it is caused by [this change](https://github.com/python/mypy/pull/8779) in mypy 0.780. Apparently before that change `Union` was of type `Any` in a runtime context, but now it is of type `object`.

**Comment by PrettyWood** [comment]
Things are starting to move on mypy side https://github.com/python/mypy/issues/9773 :)

**Comment by manassra** [comment]
I am also running into this issue. Is there a recommended way around it?

**Comment by samuelcolvin** [comment]
I believe this is fixed by `AnalysedType` (might be renamed, see #5580).

**Comment by dmontagu** [comment]
More explicitly, the right way to do this with `AnalyzedType` is the following:

```python
from typing import Union

from pydantic import AnalyzedType

my_analyzed_type: AnalyzedType[Union[float, int]] = AnalyzedType(Union[float, int])
my_analyzed_type.validate_python(3.14)
```
Note in particular that you still awkwardly need the annotation `my_analyzed_type: AnalyzedType[Union[float, int]]` — this is for precisely the same reasons that `parse_obj_as` raised a mypy error. Instead, we do a catch-all when attempting to infer the generic parameter (`Union[float, int]`) that causes it to be treated as Any, but explicitly specifying the annotation will ensure it is treated by typecheckers properly.
