### ISSUE TITLE
Alias is dropped on inheritance if set via Field (other fields, e.g. extra are dropped too)

### ISSUE THREAD

**Issue by Drino** [pydantic/pydantic#1869]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/abodrov/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
                     platform: Linux-5.7.4-050704-generic-x86_64-with-glibc2.29
     optional deps. installed: []
```

It seems like according to https://pydantic-docs.helpmanual.io/usage/model_config/#alias-precedence I should get alias from parent class in my child class:

```py
from pydantic import BaseModel, Field, ValidationError

ALIAS = 'my-alias'
FIELD_NAME = 'field'

class Parent(BaseModel):
    field: str = Field(..., alias=ALIAS, **{'my_extra': 'my_extra_value'})

class Child(Parent):
    field = 'default'

print(Parent.__fields__[FIELD_NAME].field_info.alias)
# class
print(Parent.__fields__[FIELD_NAME].field_info.extra)
# {'my_extra': 'my_extra_value'}
print(Child.__fields__[FIELD_NAME].field_info.alias)
# None
print(Child.__fields__[FIELD_NAME].field_info.extra)
# {}
# Seems like extra is not inherited too :(

print(inspect.signature(Parent))
# (**extra_data: Any) -> None
print(inspect.signature(Child))
# (*, field: str = 'default') -> None
```

This snippet can be fixed by setting `Parent.Config.fields['field']` instead

**Comment by PrettyWood** [comment]
Hello @Drino 
You actually overwrite the whole field `field` in the child model so yes everything is replaced.
By default pydantic doesn't do magic by merging field's information. I think it would be very confusing in most cases

**Comment by Drino** [comment]
Current behaviour is fully understandable, but the alias-precendence section of the documentation gives a small hope that if I do not set alias via `Field(..., alias=<alias>)` _directly on the model_ pydantic will search for `Field(..., alias=<alias>)` _on a parent model_:

> 1.    Set via Field(..., alias=<alias>), directly on the model
> 2.    Defined in Config.fields, directly on the model
> 3.    Set via Field(..., alias=<alias>), on a parent model
> 4.    Defined in Config.fields, on a parent model
> 5.    Generated by alias_generator, regardless of whether it's on the model or a parent

It actually does what described in points 2 and 4, even if I do some override:

```py
from pydantic import BaseModel, Field, ValidationError

ALIAS = 'my-alias'
FIELD_NAME = 'field'

class Parent(BaseModel):
    field: str = Field(alias=ALIAS)

    class Config:
        fields = {
            'field': {'alias': ALIAS, 'test_me': True}
        }


class Child(Parent):
    field = 'default'

    class Config:
        pass

print(Parent.__fields__[FIELD_NAME].field_info.alias)
# my-alias
print(Child.__fields__[FIELD_NAME].field_info.alias)
# my-alias


# extra arguments handling on inheritance also seems very broken:
print(Parent.__fields__[FIELD_NAME].field_info.extra)
# {}
print(Child.__fields__[FIELD_NAME].field_info.extra)
# {'test_me': True}
```

From my perspective it seems like a bug caused by using `Field(..., alias=None)` default instead of `Field(..., alias=Undefined)` default.

**Comment by dmontagu** [comment]
I think we've decided to keep the behavior that you have to redeclare the Field in full if you want to override on a child class, and we have dropped Model.Config.fields, so that is no longer a possible source of inconsistent behavior.

If this is still a point of contention please message here and/or create a new issue and we can revisit/reopen the issue.
