### ISSUE TITLE
numpy.float64 is not converted to float

### ISSUE THREAD

**Issue by dewolfarno** [pydantic/pydantic#1879]
```python
import pydantic.utils
print(pydantic.utils.version_info())
```

    pydantic version: 1.6.1
    pydantic compiled: True
    install path: /usr/local/lib/python3.7/site-packages/pydantic
    python version: 3.7.7 (default, Jun  9 2020, 17:58:51)  [GCC 8.3.0]
    platform: Linux-4.19.76-linuxkit-x86_64-with-debian-10.4
    optional deps. installed: ['email-validator']

In the code below, I would expect the `numpy.float64` to be converted to a `float` by the `Foo` pydantic object.

```python
from pydantic import BaseModel
import numpy as np
```

```python
class Foo(BaseModel):
    x: float
```

```python
value = np.float64(13)
print(type(value))
```

    <class 'numpy.float64'>

```python
foo = Foo(x=value)
print(type(foo.x))
```

    <class 'numpy.float64'>

Note that for `numpy.int64` and `int` this works as expected:

```python
class Bar(BaseModel):
    x: int
```

```python
value = np.int64(13)
print(type(value))
```

    <class 'numpy.int64'>

```python
bar = Bar(x=value)
print(type(bar.x))
```

    <class 'int'>

**Comment by PrettyWood** [comment]
Hello @dewolfarno 
The issue comes from [numpy](https://github.com/numpy/issues/2951)
```python
>>> isinstance(np.float(13), float)
True
>>> isinstance (np.int64(13), int)
False
```
And we don't want to add an extra dependency in pydantic to support this.
In the meantime you can just add a validator to support this

**Comment by dewolfarno** [comment]
Thanks for you reply @PrettyWood, we will indeed add a validator to force coercion of the fields to float.

There is a way to check the other way around, but that requires a dependency on numpy:
```python
>>> isinstance(np.float64(13), np.floating)
True
>>> isinstance(float(13), np.floating)
False
```

**Comment by PrettyWood** [comment]
The thing is that by default the value is not changed if it's an instance of `int` (or `float`). So this is why `float64` are not converted into a regular `float`.
I don't know if we expect a subclass of int to be converted into a regular int. If that's the case we can just change the check into `if type(v) is int: return v` and for all other cases we try to convert.

**Comment by dewolfarno** [comment]
Good question. In our case we were expecting pydantic to be pretty strict in the sense that the returned type would be exactly the regular `float` as defined in the model object. On the other hand, as a subclass has the same attributes and methods as the parent class, you could argue that that is sufficient.

Maybe some additional context for our specific case might help:
We built an algorithm in Python and defined the output model with pydantic. Several of the output fields were defined as `float`. The algorithm is run in production inside of a Spark UDF. We ran into various errors as Spark is unable to handle `np.float` in the output, and only works with regular `float`. As stated above, the fix was relatively easy with an extra validator that converts the respective fields to `float`.

**Comment by Kludex** [comment]
To support `numpy.float64` you should implement the following idea: https://github.com/pydantic/pydantic/issues/2189#issuecomment-1522491646.

- Given the popularity of `numpy`, I've opened https://github.com/pydantic/pydantic-extra-types/issues/31.

**Comment by caniko** [comment]
If you have an array, it is better to use the `.tolist()` method. This should map the numpy types to Python primitives. I would avoid type-conversion in pure Python.

If there is enough demand for direct type conversion: Make a PR on [`pydantic-numpy`](https://github.com/caniko/pydantic-numpy), I will review it.
