### ISSUE TITLE
"Unset Field" information is lost when instantiating Model with nested model of "wrong" type

### ISSUE THREAD

**Issue by nayaverdier** [pydantic/pydantic#1914]
# Bug

This may not actually be a bug, but the behavior seemed a bit unexpected. When unset fields are copied from an instantiated model into the expected nested model class, the information that they are unset is lost.

Perhaps best shown with a test case:

```py
from pydantic import BaseModel

def test_unset_fields_maintained():
    class Child(BaseModel):
        a: str
        class Config:
            extra = "allow"

    # if this is a subclass of Child, all assertions succeed
    class ChildWithNone(BaseModel):
        a: str
        b: str = None

    class Parent(BaseModel):
        child: Child

    # data2 uses an "invalid" model with a superset of fields
    data = Parent(child=Child(a="hi"))
    data2 = Parent(child=ChildWithNone(a="hi"))

    expected = {"child": {"a": "hi"}}
    expected_with_none = {"child": {"a": "hi", "b": None}}

    assert data.dict() == expected
    assert data.dict(exclude_unset=True) == expected
    assert data2.dict() == expected_with_none

    # `b` was not set in ChildWithNone, but that information is lost
    # when copied into a Child instance
    assert data2.dict(exclude_unset=True) == expected
    # actual result is expected_with_none
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: False
                 install path: /home/test/.venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Aug  7 2019, 15:06:22)  [GCC 5.4.0 20160609]
                     platform: Linux-4.15.0-72-generic-x86_64-with-debian-stretch-sid
     optional deps. installed: ['typing-extensions']
```

**Comment by PrettyWood** [comment]
Hello @nayaverdier 

It is unfortunately a recurring question (type coercion) and the thing is that here when you do
```python
data2 = Parent(child=ChildWithNone(a="hi"))
```
*pydantic* tries to coerce it as a `Child`, which is valid because of the `extra = "allow"`
So you end up with
```python
data2.child == Child(a='hi', b=None)
```
and that's why it is `b` is still here when you dump it with `exclude_unset=True`.

**Comment by nayaverdier** [comment]
Hello,

Thanks for the explanation. With `extra = "allow"` it does make sense to include those extra fields.

Still, it would be nice to keep track of unset fields even after type coercions. I'm not sure if there are any reasons against doing it by default , but if one pydantic model is being coerced into another, is there any ability to copy `__fields_set__` with it?

**Comment by mrlubos** [comment]
Hey all, I think I might be running into the same issue, or perhaps it's a different flavour of this problem?

I have a "main" object that you can think of as a mixture of multiple objects.

```py
class Parent(BaseModel):
        a: str = None
        b: str = None

class ChildOne(BaseModel):
        a: str = None

class ChildTwo(BaseModel):
        b: str = None
```

Normally, when I need to pass `ChildOne` to a function, I do this:

```py
def foo(parent: Parent):
    child_one = ChildOne.parse_obj(parent)
```

Now, if calling `parent.dict(exclude_unset=True)` returns an empty dictionary, I'd expect calling `child_one.dict(exclude_unset=True)` to also return an empty dictionary. But that's not what happens, I get `{"a": None}`.

Is there currently a way to get the behaviour I describe above? In my example, I guess I could make `Parent` simply extend `ChildOne` and `ChildTwo`, but that's not always going to work when my models get more complex.

**Comment by nayaverdier** [comment]
@mrlubos You can use `ChildOne(**parent.dict(exclude_unset=True))` to retain the unset fields as you'd expect. Not as elegant, but behaves more as you'd expect here.

**Comment by mrlubos** [comment]
That makes sense. Thank you @nayaverdier!

**Comment by dmontagu** [comment]
In v2, we no longer automatically coerce unrelated models from one type to the other, so the code above will now produce a ValidationError rather than setting the `__fields_set__` in a surprising way.

Given that, I'm going to close this now, but message here if you want it reopened.
