### ISSUE TITLE
Pydantic benchmark should not use average time

### ISSUE THREAD

**Issue by wyfo** [pydantic/pydantic#1915]
According to [timeit documentation](https://docs.python.org/3/library/timeit.html#timeit.Timer.repeat)

> It’s tempting to calculate mean and standard deviation from the result vector and report these. However, this is not very useful. In a typical case, the lowest value gives a lower bound for how fast your machine can run the given code snippet; higher values in the result vector are typically not caused by variability in Python’s speed, but by other processes interfering with your timing accuracy. So the min() of the result is probably the only number you should be interested in. After that, you should look at the entire vector and apply common sense rather than statistics.

The average time should not even be displayed — actually, only the best of the 5 repetitions, should be displayed.

This issue is especially important when it comes to Pypy. Indeed, Pypy JIT compilation gives results like this:
```
                apischema (1/5) time=1.470s, success=47.85%
                apischema (2/5) time=0.465s, success=47.85%
                apischema (3/5) time=0.320s, success=47.85%
                apischema (4/5) time=0.295s, success=47.85%
                apischema (5/5) time=0.286s, success=47.85%
                apischema best=0.286s, avg=0.567s, stdev=0.510s
```
The first time is always way slower than the others (in my case, it's slower than the sum of the others!) and the average is then "corrupted".

**Comment by Kludex** [comment]
That benchmark was removed from the documentation.
