### ISSUE TITLE
`use_enum_values` but only on `.dict()`

### ISSUE THREAD

**Issue by ThibaultLemaire** [pydantic/pydantic#1917]
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/████████/███/████████/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 20 2020, 13:26:22)  [GCC 9.3.0]
                     platform: Linux-5.4.59-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions', 'email-validator']
```

The `use_enum_values` config option is indeed nice when serializing. But it's not so nice when working with the model in the code. Having a true instance of `Enum` would be better to work with.

Here is what I mean:

```py
import pydantic
import enum

class LightColor(enum.Enum):
  Red = "#FF0000"
  Yellow = "#FFFF00"
  Green = "#00FF00"

class TrafficLight(pydantic.BaseModel):
  color: LightColor
  address: str

  class Config:
    use_enum_values = True
#   output_enum_values = True ?

traffic_light = TrafficLight(color=LightColor.Yellow, address="Python Street, Biltmore Beach")

# Currently, the following line won't work
# if traffic_light.color == LightColor.Green:
# You have to do this
if traffic_light.color == LightColor.Green.value:
  print("Go!")

# And if I want to print a friendlier name for the color using the enum variant's name
print(LightColor(traffic_light.color).name)  # Yellow
# Instead of
# print(traffic_light.color.name)

# Not to mention mypy doesn't like it
traffic_light.color = LightColor.Red.value  # Incompatible types in assignment (expression has type "str", variable has type "LightColor")

# But when serializing, I still want it to be
print(traffic_light.dict())  # {'color': '#FF0000', 'address': 'Python Street, Biltmore Beach'}
```

**Comment by wozniakty** [comment]
This is somewhat related to the challenges here: #1409 

`.dict()` is expected to return plain old python types.  Relatedly, the
```
class Config:
    use_enum_values = True
```

Is essentially saying that you want the plain old python type to _be_ a string, but you want it constrained to an enum, and want it to accept an enum value in deserialization.

So, really, this leads to the above issue.  If you're looking to just _serialize_ to a regular value, that's not exactly what `.dict()` is for.   `.json()` is for a serialized type, and currently there's no in-between.

Common recommendation right now is to do:
```
import json

json.loads(traffic_light.json())
```
to get the dictionary you're looking for

**Comment by ThibaultLemaire** [comment]
Indeed, I believe #1409, if implemented, would solve my use-case. (And would effectively render `use_enum_values` obsolete IMO, but that's an other issue.)

Thanks for pointing that out

**Comment by liminspace** [comment]
@wozniakty is `json.loads(traffic_light.json())` really nice code for you?) how about `json.loads(json.dumps(json.loads(traffic_light.json())))`? especially if your models is really big and deep)

**Comment by Norbo11** [comment]
I think it's cleaner to do:

```python
from fastapi.encoders import jsonable_encoder

jsonable_encoder(traffic_light)
```

This returns a dictionary in a json-serialisable format, e.g. with enum values used instead of objects.

**Comment by a5r0n** [comment]
why don't add some parameter to `dict` function `by_enum_values` like we already have `by_alias`?

**Comment by damjankuznar** [comment]
I second this proposal as it's really forcing devs to do hacky or suboptimal things to get serializable dict from Pydantic model and it really should not be this hard.

**Comment by myjniak** [comment]
You definitely have my sword and my axe here.

use_enum_values itself would be very handy, but:

- Enum values are still considered as Enums in static analysis tools (mypy, Pycharm interpreter etc)
- People also intuitively think Enum should be an Enum, and can run into misunderstandings

Having this Enum evaluation to its value only inside pydantic_obj.dict() sounds like an elegant solution ^_^

**Comment by eshgovil** [comment]
Second this issue - native pydantic validation against the enum only happens during model instantiation and nowhere else, meaning it's easy to insert an incorrect value (e.g. assigning some bad string to the field after instantiation, or during `.copy(update=)`). So to be careful, I have to use `.value` of my enum class everywhere during checks and reassignment, which is a bit annoying and leaves opportunity for bugs.

It'll be nice to get the native enum type within the pydantic model, and the string value within `.dict`, to get the best of both worlds. I also don't use `.json` in my usage, just `.dict`.

**Comment by a5r0n** [comment]
> why don't add some parameter to `dict` function `by_enum_values` like we already have `by_alias`?

@samuelcolvin @PrettyWood 
what do u think?
if u are ok with that, i'd love to open PR for this.

**Comment by samuelcolvin** [comment]
If we went to this level of change, we'd end up with literally hundreds of arguments to `.dict` which would eventually make the code very slow and would be hard to manage.

This would make everyone's experience of using pydantic worse.

As described in the blog for V2, serialisation will have to change a lot in V2. I need to sit down and write a comprehensive plan for this.

Until then I don't want to make lots of changes in v1.10, and I don't want to waste people's time creating PRs which just get closed.

**Comment by spumer** [comment]
@samuelcolvin you have a conceptual understanding how it should works?

For serialization i think the native way is use `__str__` and any user can implement it on their Enum (sub-)classes.

This allow control behavior more accurate and for any case.
Need a different behavior for output? Subclass and re-implement `__str__`.

IMHO

**Comment by samuelcolvin** [comment]
This is fixed I believe by `mode='json'` on `model_dump`.
