### ISSUE TITLE
Separate the concepts of constructors and validators

### ISSUE THREAD

**Issue by otistamp** [pydantic/pydantic#1926]
I really like the idea of having a way to load unsafe data and a way to load safe data (`Model(**unsafe)` and `Model.construct(**safe)`), but in practical use it has come to my attention that construct might be a bit of a half measure.

What I would like to be able to explicitly control is whether defaults are loaded, validators are run and perhaps a new concept of constructors that always run regardless of whether the data is safe or unsafe. For instance, nested models do not get parsed and instantiated when loaded via `Model.construct`, so code that relies on those being objects instead of dictionaries will break. Basically anytime you would want mutating functions run on fields loaded into the model regardless of data cleanliness, you would define a constructor and those would always be run and not raise errors.

A good example of a type that could do for a construct function instead of validate is SecretStr. The value is simply mutated and should happen regardless of data cleanliness.

```python

class SecretStr:

    # the current method that needs to be run through validation to occur
    @classmethod
    def validate(cls, value: Any) -> 'SecretStr':
        if isinstance(value, cls):
            return value
        value = str_validator(value)
        return cls(value)

    # potential method that would always run
    @classmethod
    def construct(cls, value: Any) -> 'SecretStr':
        if isinstance(value, cls):
            return value
        return cls(value)
```

Instead of the construct method on the model, I propose keyword arguments to `__init__` that would enable/disable validation and defaults but never allow disabling constructors. e.g. `Model(**data, run_validation=False, set_defaults=True)`.

**Comment by mhadam** [comment]
I think this also touches on something that was brought up in #221, but apparently closed w/o implementation.

**Comment by Kludex** [comment]
On v2, I think the new `model_construct` satisfies your needs.

If that's not the case, please let me know, so I can reopen this issue. 🙏

**Comment by dmontagu** [comment]
@otistamp We have added the concept of "validation context" in v2; if you look at the implementation of `model_validate`, it accepts an argument called context, and that will be accessible in validators via `info.context`, see here for an example: https://github.com/pydantic/pydantic/blob/34a1c02277140551e6c90dd7241ceb0c1b638353/tests/test_main.py#L2192-L2205

The main issue remaining is how to set validation context when creating the class via the `__init__` api (i.e., `MyModel(**kwargs)`), which we currently don't have a great solution to (though I would like to come up with a solution for this before the official release of v2).

That said, if you want more fine-grained control over how validation is done, the use of the context argument to model_validate may work for you.

I think if you need more control than that, I would recommend overriding `model_construct`, or creating a custom method that functions similarly but with the tweaks you need. If you still need this capability but find yourself unable to implement what you need to implement with context or method overrides, please create a new issue and we will be happy to go into more detail about how to address your use case, or consider adding/modifying functionality to better support it.
