### ISSUE TITLE
Validate Model defaults when the Model is created

### ISSUE THREAD

**Issue by art049** [pydantic/pydantic#1936]
# Feature Request
Currently, we can validate the default values when creating instances of the model (using the `validate_all` config flag).
I think it might be interesting to be able to raise a Validation Error when defining the Model class directly.

Current behavior
```py
from pydantic import BaseModel
class M(BaseModel): 
    field: int = "a string" 
    class Config: 
        validate_all = True
# The model is created but trying to instantiate M with its default values will raise a validation error later
M()
ValidationError: 1 validation error for M
field
  value is not a valid integer (type=type_error.integer)
```

Suggested behavior
```py
from pydantic import BaseModel
class M(BaseModel): 
    field: int = "a string" 
    class Config: 
        validate_all = True
ValidationError: 1 validation error for M
field
  default value is not a valid integer (type=type_error.integer)
# The error is raised while the Model is being created
```

Maybe a new configuration flag should be added to enable this behavior with backward compatibility.

**Comment by wozniakty** [comment]
I'd like if it did this even without a Config defined as it without catch errors as quickly as possible, but then I prefer statically typed languages so I may not be the most "pythonic" perspective.

The one problem I foresee, however, with actually changing this is that it's not actually compatible, on principle, from the way optional fields can be defined.

`some: str = None` is considered a valid way to specify an optional string field by pydantic, when _technically_ it'd be more correct to have an `Optional[str]`.  But breaking that would be potentially breaking the interface as expected by lots of users, so it'd have to be a breaking version.

You might even argue it's inconsistent that a default None allows a None value but a default string on an int does not allow a string value, though I wouldn't say it'd be a good idea to implement that way. Just reinforces the inconsistency.

We could maybe implement a behavior like you're suggesting, but keep a special check in for None applied to non Optional types, and maybe warn for a deprecation in the future. That seems not too unreasonable.

All of this to say, I agree it'd be best for all default values to entirely match the type definition *and* be checked as early as class definition.  Not sure how it would be best handled though.

**Comment by dmontagu** [comment]
I think this is implemented now, so

```python
from pydantic import BaseModel


class M(BaseModel):
    field: int = "a string"

    class Config:
        validate_all = True


M()
"""
pydantic.error_wrappers.ValidationError: 1 validation error for M
field
  value is not a valid integer (type=type_error.integer)
"""
```
This changed slightly in v2:
```python
from pydantic import BaseModel


class M(BaseModel):
    field: int = "a string"
    model_config = dict(validate_default=True)

M()
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for M
field
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='a string', input_type=str]
"""
```
Regarding the point above related to `some: str = None` and `Optional[str]`, now in v2, we officially expect you to write `some: Optional[str] = None` if you want to accept None.
