### ISSUE TITLE
Changing path of AnyUrl does not change the url but only the path property

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#1945]
# Bug

Updating the `path` property of an `AnyUrl` instance does not correctly modify the path in the representation of the url.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/powerjo/dev/juice/juice-forecast/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Apr 14 2020, 11:26:53)  [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

```py
from pydantic import parse_obj_as, AnyUrl

def test_update_url_path():
    url = 'https://localhost:5432/postgres'
    dsn = parse_obj_as(AnyUrl, url)
    dsn.path = "/new_path"
    assert dsn.path == "/new_path", dsn.path # ok
    assert "/new_path" in dsn, dsn # not ok

```

**Comment by xkortex** [comment]
The way the `AnyUrl` object API works, these fields aren't really settable. Basically `AnyUrl` is a `str` subclass, meaning it's usable by any function that accepts `url: str`. So the fields like scheme, port, path, etc, aren't so much settable properties, but ought to read-only attributes. 

IMHO this interface is a little crufty. You can mis-use it in ways such as the above. It's also difficult to assign things. One might reasonably expect `AnyUrl('http://example.com/')` to work, parsing the URL and giving the structured object `AnyUrl('http://example.com/', scheme='http', host='example.com', tld='com', host_type='domain', path='/')` Instead, you get `TypeError: __init__() needs keyword-only argument scheme` or `...argument host`. So you have to manually provide `scheme` and `host`. But the initializer does not actually vet this, and you can do improper things like: 

```
>>> AnyUrl('http://example.com/', scheme='file', host='foobar')
AnyUrl('http://example.com/', scheme='file', host='foobar', host_type='domain')
```

What you have to do instead is use `parse_obj_as(AnyUrl, 'http://example.com/')` which is not as intuitive and kinda cumbersome.

**Comment by Kludex** [comment]
This problem doesn't exist in V2, since the attribute `path` is not writable. For that reason, and our main focus being V2, I'll be closing this issue.
