### ISSUE TITLE
attrs equivalent to pydantic.dataclasses.dataclass

### ISSUE THREAD

**Issue by techdragon** [pydantic/pydantic#1962]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

I'd like to be able add pydantic to code already built using attrs more easily. The dataclasses support is very handy for new code but I have a lot of code built using attrs and it would be nice to have an equivalent "wrapper" that would help with the adopting pydantic in these cases. I imagine it looking somewhat like this.... of course it will also look quite a bit nicer once attrs ships their upcoming changes to stop needing `(auto_attribs=True)` all the time. 

```py
from pydantic import AnyUrl
from pydantic.attrs import attr


@attr.s(auto_attribs=True)
class NavbarButton:
    href: AnyUrl


@attr.s(auto_attribs=True)
class Navbar:
    button: NavbarButton


navbar = Navbar(button=('https://example.com',))
print(navbar)
#> Navbar(button=NavbarButton(href=AnyUrl('https://example.com', scheme='https',
#> host='example.com', tld='com', host_type='domain')))
...
```

**Comment by PuneetGrov3r** [comment]
@techdragon just for info, why are you moving from attrs to pydantic? What are your main reasons?
I am also deciding on choosing one of attrs or pydantic to use in my project, but most blogs and videos online shows attrs to be superior considering memory efficiency and speed. Although I like python type definitions being used in pydantic and I think pydantic.dataclasses.dataclass will be a good option too.

**Comment by samuelcolvin** [comment]
I think best to use pydantic or dataclasses, I doubt we'll support this.
