### ISSUE TITLE
support a field delete operator

### ISSUE THREAD

**Issue by sasano8** [pydantic/pydantic#1968]
Thank you for the great library.

I want you to be able to delete a attribute of the inherited class.
If this request is accepted, I will make a pull request.

[Similar issues #660](https://github.com/samuelcolvin/pydantic/issues/660)

The above behavior depends on the exclude option.
This is a strong exclusion that removes the definition itself.

```py
from pydantic import BaseModel, Delete

class Person(BaseModel):
  id: int
  name: str

class PersonCreate(Person):
  id: Delete

obj = PersonCreate(name='test')
print(hasattr(obj, 'id'))  # => False

```

**Comment by daviskirk** [comment]
I also kind of need the deletion of a field but I don't see that as working well with the inheritance model in python in general (and I'm pretty sure that mypy won't understand or like that in any case) so I'll start with the simple export exclusion.

I currently can inherit the model and then just delete the field from __fields__ which word functionally but is really hacky.
Perhaps a less invasive way would be to "hide" the field so it won't show up in the schema and will through a validation error if it is set?

Would a pull request for something like this be accepted?

**Comment by sasano8** [comment]
Sure, the field delete feature would confuse mypy.

But I don't think it's a problem. 
Because if you refer to it, you will get an "NoAttributeError".

Currently, I implemented the prefab function to express the difference.
Another way for difference expression.

This is useful in the following cases:
- Remove the primary key for create.
- All fields optionalize for patch. 

```
@router.patch("/{id}/patch")
async def patch(self, id: int, data: User.prefab(suffix="Patch", exclude=["id"], requires=[], optionalize=[...])):
  ...
```

**Comment by jeanmonet** [comment]
> I currently can inherit the model and then just delete the field from **fields** which word functionally but is really hacky. Perhaps a less invasive way would be to "hide" the field so it won't show up in the schema and will through a validation error if it is set?

What I'm about to go for:

```python
class ModelClass(pydantic.BaseModel):
    ...
    delete_this_field: str

ModelClass.__fields__.pop("delete_this_field")
```

This seems to produce the desired result, but haven't tested extensively. The field disappears from schema and no validation behavior seems to take place.

**Comment by freenetwork** [comment]
@jeanmonet thx
I need solve

**Comment by agronick** [comment]
If you can add arbitrary fields by setting
```py
class Config:
        extra = "allow"
```
you need a way to delete these fields. Currently there is none.

**Comment by adriangb** [comment]
Pydantic could implement this sort of thing at runtime but we won't be doing it until Python's typing ecosystem gets partial types, etc. That is bound to happen at some point and we don't want to have two different ways to do it when that happens. I'm closing this until that time comes.
