### ISSUE TITLE
__root__ field parsing doesn't depend on Union type order

### ISSUE THREAD

**Issue by perminovs** [pydantic/pydantic#1982]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug \_\_root\_\_ field parsing doesn't depend on Union type order

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: .venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Oct 28 2019, 16:14:01)  [GCC 8.3.0]
                     platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions', 'email-validator']

```

Parsed field value depends on Union type order, as it specified by [docs](https://pydantic-docs.helpmanual.io/usage/types/#literal-type):
> With proper ordering in an annotated Union, you can use this to parse types of decreasing specificity
```py
from typing import Union, Dict
from pydantic import BaseModel

T1 = Union[Dict[str, str], str]
T2 = Union[str, Dict[str, str]]

class A(BaseModel):
    a: T1

class B(BaseModel):
    a: T2

print(A.parse_obj({'a': ''}))  # a={}
print(B.parse_obj({'a': ''}))  # a=''
```
But:
```py
from typing import Union, Dict
from pydantic import BaseModel

T1 = Union[Dict[str, str], str]
T2 = Union[str, Dict[str, str]]

class A(BaseModel):
    __root__: T1

class B(BaseModel):
    __root__: T2

print(A.parse_obj({'a': ''}))  # __root__={'a': ''}
print(B.parse_obj({'a': ''}))  # __root__={'a': ''}
```
Both values are equal. Is that behavior expected for `__root__`?

**Comment by samuelcolvin** [comment]
Seems to be a particular problem with dictionaries:

```py
from typing import Union
from pydantic import BaseModel

T1 = Union[int, str]
T2 = Union[str, int]


class A(BaseModel):
    __root__: T1


class B(BaseModel):
    __root__: T2


print(A.parse_obj('123'))  # __root__=123
print(B.parse_obj('123'))  # __root__='123'
```

**Comment by perminovs** [comment]
Interesting. Speaking about dictionaries: is it normal that empty string is valid dict?
```py
print(A.parse_obj({'a': ''}))  # a={}
```

**Comment by samuelcolvin** [comment]
See #1268 and #558, it should change in v2.

**Comment by dmontagu** [comment]
This is fixed in v2
