### ISSUE TITLE
Use dict()-like signature on BaseModel (allow positional arg data)

### ISSUE THREAD

**Issue by Bobronium** [pydantic/pydantic#2043]
### Checks
* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

#### Pydantic version info
```py
             pydantic version: 1.7
            pydantic compiled: False
                 install path: /Users/arseny.boikov/dev/py/pydantic/pydantic
               python version: 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.15.5-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']
```

# Feature Request
Allow `BaseModel` calls with data in positional argument, like built-in `dict()` does
```py
from pydantic import BaseModel

class Model(BaseModel):
    foo: str = 'a'
    bar: str = 'b'

class OtherModel(BaseModel):
    bar: str
    baz: str = 'c'

data = {'foo': 'value', 'bar': 'value'}
Model(data)  # equivalent to Model(**data)
Model(data, bar='override_bar')  # equivalent to Model(**dict(data, bar='override_bar'))
OtherModel(Model(), baz='spam')  # equivalent to OtherModel(**dict(Model(), baz='spam'))
```
### Pros
- More flexible API
- Less boilerplate when instancing model from data with additional keys
- no need to have `BaseModel.parse_obj`
- consistency with `dict` and other mappings
...

### Cons
- User-defined models might not have support for data in positional arg, therefore bringing inconsistency across models
- Code that used to rely on `TypeError` raised when calling Model with positional arg will stop working (however I doubt that such code exists in production)
...

### Things to consider
- What signature of models should look like?
...

### Possible implementation
```py
    def __init__(*self_and_data: Any, **data: Any) -> None:
        self, *mapping = self_and_data
        if mapping and data:
            data = dict(*mapping, **data)
        elif mapping:
            data, *extra_args = mapping
            if extra_args:
                raise TypeError('BaseModel.__init__ takes at most 2 positional args, {2 + len(extra_args)} given')

        values, fields_set, validation_error = validate_model(self.__class__, data)
       ...  # rest of the code unchanged
```

**Comment by Kludex** [comment]
On V2, we have `model_validate`:

```python
from pydantic import BaseModel


class User(BaseModel):
    id: int
    name: str


user = User.model_validate({"id": 1, "name": "John"})
print(user)
```
