### ISSUE TITLE
Support fields using pathlib.PurePath

### ISSUE THREAD

**Issue by choogeboom** [pydantic/pydantic#2089]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: False
                 install path: /pyenv/versions/3.8.5/envs/mep-fulcrum/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Oct  6 2020, 09:38:38)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
                     platform: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```
Pydantic supports `pathlib.Path`, but that creates a _concrete path_. Sometimes we want to create a model that specifies a path that is independent of the file system on the currently running machine. For that, we need a _pure path_.

```py
import pathlib

import pydantic

class ExampleModel(pydantic.BaseModel):
    pure_path: pathlib.PurePath
```

**Comment by randallpittman** [comment]
Workaround I used for PurePosixPath (as an SSH destination file path). I copied the validator and errors for Path and used them for PurePosixPath:

```python
from pathlib import Path, PurePosixPath
from typing import Any, Optional

from pydantic import BaseModel, PydanticTypeError, validator

class PPPathError(PydanticTypeError):
    msg_template = 'value is not convertible to a PurePosixPath'

class RsyncParams(BaseModel):
    """Simple class to rsync local files over ssh to a some remote system"""

    dest_user: str
    dest_server: str
    dest_base_dir: PurePosixPath
    options: str = ""
    ssh_key: Optional[Path] = None
    ssh_options: str = ""

    class Config:
        arbitrary_types_allowed = True

    @validator("dest_base_dir", pre=True)
    def dest_base_dir_to_path(cls, v: Any) -> PurePosixPath:
        if isinstance(v, PurePosixPath):
            return v
        try:
            return PurePosixPath(v)
        except TypeError:
            raise PPPathError()

    ...  # etc
```

**Comment by randallpittman** [comment]
Can also "register" a validator for a type such as `PurePosixPath` as shown here:

```python

# ## Add PurePosixPath validation to pydantic
class PurePosixPathError(PydanticTypeError):
    msg_template = "value is not a valid pure POSIX path"


def validate_pure_posix_path(v: Any) -> PurePosixPath:
    """Attempt to convert a value to a PurePosixPath"""
    if isinstance(v, PurePosixPath):
        return v
    try:
        return PurePosixPath(v)
    except TypeError:
        raise PurePosixPathError()


_VALIDATORS.append((PurePosixPath, [validate_pure_posix_path]))
```

**Comment by m0rtalis** [comment]
I did as @randallpittman described but now I get:
```
[...]
  File "pydantic\schema.py", line 863, in pydantic.schema.field_singleton_schema
ValueError: Value not declarable with JSON Schema, field: name='path' type=PureWindowsPath required=True
```
When using it together with FastApi.

**Comment by randallpittman** [comment]
@m0rtalis - you need to add an encoder to `json_encoders`: https://pydantic-docs.helpmanual.io/usage/exporting_models/#json_encoders

**Comment by m0rtalis** [comment]
already tried it but does not work. I created a SO Question for it, which is probably the better forum for this https://stackoverflow.com/questions/68893175/error-value-not-declarable-with-json-schema-for-purepath-with-pydantic-and-fasta

**Comment by gunstonej** [comment]
I had the same issue and Config solution from @randallpittman above worked for me. If your also using `PureWindowsPath` i think that would also need adding, i.e.  
```python
class MyModel(BaseModel):
    class Config:
        json_encoders = {PurePosixPath:  str, PureWindowsPath: str}
```

**Comment by adriangb** [comment]
V2 uses PurePath: https://github.com/pydantic/pydantic/blob/a82045c97326b62599329f99496914b4bcd3da6a/pydantic/_internal/_std_types_schema.py#L192

PRs welcome for other types of paths.

**Comment by DSLituiev** [comment]
@randallpittman `from pydantic.validators import _VALIDATORS`
does not exist in v 2.5.0
