### ISSUE TITLE
Model with Enum of multiple submodels does not allow extra fields in submodels

### ISSUE THREAD

**Issue by dorinclisu** [pydantic/pydantic#2173]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.2
            pydantic compiled: True
                 install path: /usr/local/lib/python3.6/site-packages/pydantic
               python version: 3.6.12 (default, Oct 13 2020, 21:45:01)  [GCC 8.3.0]
                     platform: Linux-4.19.128-microsoft-standard-x86_64-with-debian-10.6
     optional deps. installed: ['typing-extensions']
```

How to replicate:
```py
from enum import Enum
from typing import List
from pydantic import BaseModel

class ChoiceOptionReference(BaseModel):
    id: int
    name: str

class FruitChoice(Enum):
    apple  = ChoiceOptionReference(id=0, name='Apple')
    orange = ChoiceOptionReference(id=1, name='Orange')
    banana = ChoiceOptionReference(id=2, name='Banana')

class Order(BaseModel):
    fruit_choices: List[FruitChoice]

raw_apple_choice = {
    'id': 0,
    'name': 'Apple'
}
raw_apple_choice_extra = {
    'id': 0,
    'name': 'Apple',
    'extra': 'whatever'
}
raw_order = {
    'fruit_choices': [
        raw_apple_choice
    ]
}
raw_order_extra = {
    'fruit_choices': [
        raw_apple_choice_extra
    ]
}

apple_choice = ChoiceOptionReference(**raw_apple_choice) # works fine
apple_choice = ChoiceOptionReference(**raw_apple_choice_extra) # works fine, extra field is ignored
order        = Order(**raw_order) # works fine
order        = Order(**raw_order_extra) # oh no
# pydantic.error_wrappers.ValidationError: 1 validation error for Order
# fruit_choices -> 0
#   value is not a valid enumeration member; permitted: ChoiceOptionReference(id=0, name='Apple'), ChoiceOptionReference(id=1, name='Orange'), ChoiceOptionReference(id=2, name='Banana') (type=type_error.enum; enum_values=[<FruitChoice.apple: ChoiceOptionReference(id=0, name='Apple')>, <FruitChoice.orange: ChoiceOptionReference(id=1, name='Orange')>, <FruitChoice.banana: ChoiceOptionReference(id=2, name='Banana')>])

```

This might be a feature but since it's not clearly documented, and the behavior is unexpected (it took me a while to find the cause, and the fact that pydantic doesn't show which is the invalid value also doesn't help), I definitely consider it a bug.

**Comment by PrettyWood** [comment]
Hi @dorinclisu 
When using strings, we usually do
```python
class FruitChoice(str, Enum):
    apple  = 'Apple'
    ...
```
so when `field.type_` [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/validators.py#L269) is resolved to `str` (and not default `enum`).
So here you would want to do something like 
```python
class FruitChoice(ChoiceOptionReference, Enum):
    apple  = ChoiceOptionReference(id=0, name='Apple')
    ...
```
But you'll need probably need to create a custom metaclass and resolve the conflict
```python
class ModelEnumMetaclass(ModelMetaclass, EnumMeta):
    ...

class FruitChoice(ChoiceOptionReference, Enum, metaclass=ModelEnumMetaclass):
    ...
```
This custom metaclass could probably be something done and exposed by _pydantic_.
Hope it helps

**Comment by dorinclisu** [comment]
Thanks for the pointer. Indeed using string enum is more common and simple to handle. However, in my application (talking to another API) I not only have to accept that input, but also pass it back with the right `id` and `name` pairing which is why I resorted to this kind of enum. I had also tried `class FruitChoice(ChoiceOptionReference, Enum):` and got metaclass conflict though I wasn't aware it can be solved with a custom metaclass.

**Comment by dmontagu** [comment]
For various reasons, I think it's preferable to not attempt to do rich parsing of enum values by introspecting the default value, and I think it's not worth attempting to support metaclass compatibility for as exotic a use case as this.

In v2, I would suggest either creating a custom `__pydantic_core_schema__` for such a type that causes it to validate the way you want (admittedly this will require some semi-advanced skills with `pydantic_core`), or to just refactor your code a bit to not make use of an enum.Enum in this way. For example, you could parse the value into a pydantic type with appropriate validation to ensure it is definitely convertible into one of the enum cases you care about, then add a method on the model to do the conversion.
