### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [pydantic/pydantic#2187]
**Summary**
Installing pydantic on aarch64 via pip using command "pip3 install pydantic" tries to build wheel from source code

**Problem description**
pydantic doesn't have wheel for aarch64 on PyPI repository. So, while installing pydantic via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pydantic. Making wheel available for aarch64 will benefit aarch64 users by minimizing pydantic installation time.

**Expected Output**
Pip should be able to download pydantic wheel from PyPI repository rather than building it from source code.

@pydantic-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pydantic wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by samuelcolvin** [comment]
https://cibuildwheel.readthedocs.io/en/stable/

Should be as simple as adding another build option to ci. Feel free to submit a pr. That stage normally only runs when the PR is married with master but it's pretty trivial to comment out the restriction for testing.

**Comment by odidev** [comment]
@samuelcolvin Thanks for your quick response, I will start working on it and will raise a PR.

**Comment by dmontagu** [comment]
I believe this is now resolved in v2, but please comment here and let us know if that is not the case. (You can try via `pip3 install --pre pydantic==2.0a3`).
