### ISSUE TITLE
BaseModel deserializes custom types inherited from `str` or any other built-in python types into base types instead of the intended inherited/custom types

### ISSUE THREAD

**Issue by Adnan1011** [pydantic/pydantic#2189]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
https://github.com/samuelcolvin/pydantic/issues/2041 seems related but not exactly the same issue
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/adnan/image-recognition/lib/python3.6/site-packages/pydantic
               python version: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29)  [GCC 7.3.0]
                     platform: Linux-5.4.0-56-generic-x86_64-with-debian-buster-sid
     optional deps. installed: ['typing-extensions']
```
It seems like pydantic deserializes any fields having types that inherit from python built-in types like `str`, `int` always into the base types like `str`, `int` rather than the intended custom/inherited types. Here's how to this issue can be reproduced:
```
from pydantic import BaseModel

    class CustomString(str):
        def print_self_yes(self):
            print(f'{self}_yes')

    class TestClass(BaseModel):
        field_1: int
        field_2: CustomString

    x = {"field_1": 12, "field_2": "name"}

    y = TestClass(**x)
    print(f'field_2 is of type: {type(y.field_2)}')
    y.field_2.print_self_yes()
```
Output of the above code snippet is:
```
field_2 is of type: <class 'str'>
AttributeError: 'str' object has no attribute 'print_self_yes'
```
Here, `field_2` should have been of type `CustomString`. However, pydantic is assigning it the base type i.e. `str` and hence we see the above error.

Defining `__get_validators__` on `CustomString` can make it work. But is it intentionally kept that way? Shouldn't we support any custom type regardless of whether or not it inherits from any built-in type or not?

**Comment by PrettyWood** [comment]
Hi @Adnan1011 
I just had a look and in fact it's expected as you set a `str` in the input, which won't be coerced in the end.
You can either
- set the right type in the input `x = {"field_1": 12, "field_2": CustomString("name")}` instead of plain `str`
- add a validator for one, some, all fields
```python
    @validator('*')
    def coerce_set_type(cls, v, field):
        try:
            return field.outer_type_(v)
        except:
            return v
```
or something like this.
I actually worked on a validator in https://github.com/PrettyWood/pydantic/commit/4cfed45fe47d4cd1a44f9bc4f016b0490a116aef that could be run in the `post_validators`. Still not sure if this would make sense. @samuelcolvin any thoughts ?

Cheers

**Comment by samuelcolvin** [comment]
Solution is to add validation to your own type, or if you don't own the type, add validation using an argument to `Annotated`

```py
from typing import Annotated

from pydantic_core import core_schema

from pydantic import BaseModel

class YourOwnType(str):
    def print_self_yes(self):
        print(f'{self}_yes')

    @classmethod
    def __get_pydantic_core_schema__(cls, _handler):
        return core_schema.no_info_after_validator_function(cls, core_schema.str_schema())


class ThirdPartyType(str):
    def print_self_yes(self):
        print(f'{self}_yes')



class ApplyValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, source, _handler):
        return core_schema.no_info_after_validator_function(source, core_schema.str_schema())


WrappedThirdPartyType = Annotated[ThirdPartyType, ApplyValidation]


class TestClass(BaseModel):
    field_1: int
    field_2: YourOwnType
    field_3: WrappedThirdPartyType

x = {"field_1": 12, "field_2": "name", "field_3": "name"}

y = TestClass(**x)
print(f'field_2 is of type: {type(y.field_2)}')
y.field_2.print_self_yes()
print(f'field_3 is of type: {type(y.field_3)}')
y.field_3.print_self_yes()
```

Since this is working on main, I'm closing this issue.
