### ISSUE TITLE
Deserialisation fails for dates before year 1000 when using orjson

### ISSUE THREAD

**Issue by Apo-** [pydantic/pydantic#2218]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.7.3
pydantic compiled: True
    install path: /iota/.venv/lib/python3.8/site-packages/pydantic
python version: 3.8.7 (default, Dec 22 2020, 18:57:26)  [GCC 8.3.0]
    platform: Linux-4.15.0-126-generic-x86_64-with-glibc2.2.5
optional deps. installed: ['typing-extensions']
```

```py
from datetime import datetime

import orjson
from pydantic import BaseModel


def orjson_dumps(v, *, default):
    return orjson.dumps(v, default=default).decode()

class DateContainer(BaseModel):
    d: datetime
    
    class Config:
        json_loads = orjson.loads
        json_dumps = orjson_dumps


DateContainer.parse_raw(DateContainer(d=datetime.utcnow()).json())                          # Works fine
DateContainer.parse_raw(DateContainer(d=datetime.utcnow().replace(year=1000)).json())       # Works fine
DateContainer.parse_raw(DateContainer(d=datetime.utcnow().replace(year=999)).json())        # Exception
DateContainer.parse_raw(DateContainer(d=datetime.min).json())                               # Exception
```

When using orjson for ser/de, deserialisation fails for datetimes with year before 1000. Not sure if that's an issue on darwin though, since this sounds a lot like https://bugs.python.org/issue13305, https://bugs.python.org/issue32195.

The problem seems to be that when using orjson we get the following:
```py
>>> DateContainer(d=datetime.min).json()
'{"d":"1-01-01T00:00:00"}'

>>> DateContainer.parse_raw('{"d":"1-01-01T00:00:00"}')
... Exception

# Manually pad the year with zeros
>>> DateContainer.parse_raw('{"d":"0001-01-01T00:00:00"}')
DateContainer(d=datetime.datetime(1, 1, 1, 0, 0))
```

Looks like when parsing datetime we are expecting 4 digits in the year here https://github.com/samuelcolvin/pydantic/blob/master/pydantic/datetime_parse.py#L23.
This is the same behaviour that `datetime.fromisoformat(...)` has, but could cause issues with a bunch of datetime serializers.

Of course there's a good argument to be made for pydantic not supporting datetimes with years that are not 4-digit long, in which case an addition in the docs could be useful in the orjson section to use `orjson.OPT_PASSTHROUGH_DATETIME` option along with `default` for datetime, time and date objects.

**Comment by adriangb** [comment]
We won't allow customizing the serializer in V2 and this is not a problem for the default serialization (which is in Rust and is almost as fast as orjson).
