### ISSUE TITLE
Bug: Field ordering is not correct when inheritance.

### ISSUE THREAD

**Issue by ghengao** [pydantic/pydantic#2234]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/ehengao/.local/lib/miniconda3/envs/vscode/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jul  2 2020, 16:21:59)  [GCC 7.3.0]
                     platform: Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-glibc2.10
     optional deps. installed: ['typing-extensions', 'email-validator']
```

Only related issue i have seen here i https://github.com/samuelcolvin/pydantic/issues/1754, but it is a different concern regardless of the ordering. 

The reason i need the ordering is for the purpose of validation the last field values against other fields with the capability of accessing the `ModelField` information. (Therefore, using `root_validator` does not seem to be convienient.)

```py
from pydantic import BaseModel
import typing as tp

class A(BaseModel):
    a: str = 1
    c: str = 1 
    b: tp.Optional[tp.List[int]]


class B(A):
    d: str = 3
    b: tp.Optional[tp.List[str]]

print(B.__fields__.keys())
# This outputs to dict_keys(['a', 'c', 'b', 'd'])
# It is expected to be dict_keys(['a', 'c', 'd', 'b'])
```

**Comment by ghengao** [comment]
Honestly, i like the idea of dataclassing these models using the `__post_init__` hooks, it would be nice for such hooks to be available within the pydantic model as well.

**Comment by PrettyWood** [comment]
Hello @ghengao! Happy new year and thanks for reporting!
IMO you're absolutely right. Fields that are overwritten in submodels should appear last. The workaround on #1754 was easy but it should have not been necessary. I opened #2236 to show a basic implementation + start discussion. Feedback welcome

**Comment by samuelcolvin** [comment]
I'm really not sure I agree that it's wrong currently. I think the current behaviour could be considered correct.

Either way we need:
* more people to agree that it's currently wrong before we change it
* to wait for v2 for a subtle change like this

**Comment by leosussan** [comment]
I agree that this is a bug, personally - primarily because of the importance of field order when constructing validators, the rule for which you've appropriately defined [here](https://pydantic-docs.helpmanual.io/usage/validators/):
![CleanShot 2021-09-21 at 16 36 17@2x](https://user-images.githubusercontent.com/7993496/134243982-b3e41b6d-fd72-4f04-9726-69d5588f82d0.png)

Given the above, consider the following example:

```python
import chevron
from pydantic import BaseModel, validator


class BaseResponseModel(BaseModel):
    status_code: int
    message: str

    @validator("message")
    def inflate_message(cls, v: str, values: dict) -> str:
        return chevron.render(template=v, data=values)


class PersonResponseOut(BaseResponseModel):
    person_id: str
    message: str = "Successfully returned person with id {{ person_id }}"
```

What I would expect, is that `person_id` would be used to inflate the `message` string with the value of variable `person_id`, as `values` would include the field. The string would translate to 'succesfully 

Instead, we get:

```python
>>> PersonResponseOut(person_id="abc123", status_code=200)
PersonResponseOut(message='Successfully returned person with id {{ person_id }}', status_code=200, person_id='abc123')
```

Contrast this with the following working example:

```python
>>> PersonResponseOut(person_id="abc123", status_code=200, message="Successfully returned a response with {{ status_code }}")
PersonResponseOut(status_code=200, message='Successfully returned a response with 200', person_id='abc123')
```
 
Chosen validator is only meant to give an easily visible representation for what variables are available when & where.

**Comment by leosussan** [comment]
For those of you that need a quick fix to this -- here is a *_very_* rough bit of code that isn't great, but worked for me.

Using the same example above, add two methods to the Base class:

```python
import copy

import chevron
from pydantic import BaseModel, validator
from pydantic.main import ModelField


class BaseResponseModel(BaseModel):
    status_code: int
    message: str

    @validator("message")
    def inflate_message(cls, v: str, values: dict) -> str:
        return chevron.render(template=v, data=values)

    @classmethod
    def __new_fields__(cls) -> dict:
        if not (getattr(cls, "_new_fields", None)):
            all_fields: dict = copy.copy(cls.__fields__)
            if all_fields != BaseResponseModel.__fields__:
                field: ModelField
                for key, field in cls.__fields__.items():
                    root_field: Optional[
                        ModelField
                    ] = BaseResponseModel.__fields__.get(key)
                    if (
                            root_field
                    ) and field.__str__() != root_field.__str__():
                        all_fields[key] = all_fields.pop(key)
            cls._new_fields = all_fields
        return cls._new_fields

    def __new__(cls, *args, **kwargs):
        cls.__fields__ = cls.__new_fields__()
        return super(BaseResponseModel, cls).__new__(cls)


class PersonResponseOut(BaseResponseModel):
    person_id: str
    message: str = "Successfully returned person with id {{ person_id }}"
    
    class Config:
        validate_all = True
```

Returning to our original example:

```python
>>> PersonResponseOut(person_id="abc123", status_code=200)
PersonResponseOut(status_code=200, person_id='abc123', message='Successfully returned person with id abc123')
```

**Comment by dmontagu** [comment]
The field order hasn't changed, but I think that now that we have deprecated `@validator` in v2 in favor of `@field_validator` and `@root_validator`, the issue is largely mitigated. If you disagree, please comment and we can reopen the issue.

**Comment by a3ng7n** [comment]
Is there any "correct" way to alter validator ordering in children classes? I've even tried re-declaring a parent's field in a subclass in the correct ordering, but it uses the parent ordering anyway. Not sure if my opinion counts for much, but this doesn't seem correct/expected.

Appreciate the response from @leosussan , but I've already been bit by munging pydantic features with construction modification, so I'm hoping to avoid that if at all possible.

And let me know if this is just a skill-issue and there's a method advertised elsewhere I missed.
