### ISSUE TITLE
Support implicit casting for enum members in Literal

### ISSUE THREAD

**Issue by tobinus** [pydantic/pydantic#2257]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues ~and couldn't find anything~
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [ ] (Sorry) After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /Users/n643674/git/digas-synkronisering-fra-prf/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.0 (default, Dec  9 2020, 14:28:15)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Enums are very convenient to use for tagged unions. However, they are not usable by Pydantic, which tries to compare the original input string to the enum member, without trying to convert the input to an enum member.

This is the second [Literal example](https://pydantic-docs.helpmanual.io/usage/types/#literal-type), adapted to using Enum members instead of string literals:
```py
import enum
from typing import ClassVar, List, Union, Literal

from pydantic import BaseModel


class DessertTypes(enum.Enum):
    CAKE = 'cake'
    ICE_CREAM = 'icecream'


class Cake(BaseModel):
    kind: Literal[DessertTypes.CAKE]
    required_utensils: ClassVar[List[str]] = ['fork', 'knife']


class IceCream(BaseModel):
    kind: Literal[DessertTypes.ICE_CREAM]
    required_utensils: ClassVar[List[str]] = ['spoon']


class Meal(BaseModel):
    dessert: Union[Cake, IceCream]


print(type(Meal(dessert={'kind': 'cake'}).dessert).__name__)
```

Expected output:
```
Cake
```

Actual output:
```
Traceback (most recent call last):
  File ".../cake_example.py", line 26, in <module>
    print(type(Meal(dessert={'kind': 'cake'}).dessert).__name__)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Meal
dessert -> kind
  unexpected value; permitted: <DessertTypes.CAKE: 'cake'> (type=value_error.const; given=cake; permitted=(<DessertTypes.CAKE: 'cake'>,))
dessert -> kind
  unexpected value; permitted: <DessertTypes.ICE_CREAM: 'icecream'> (type=value_error.const; given=cake; permitted=(<DessertTypes.ICE_CREAM: 'icecream'>,))
```

This was reported in late 2019 as well, in issue #1086. There, Samuel asked that a new issue be created if support for `Literal[DessertTypes.CAKE]` was desired in the future. Please consider this that issue 🙂 

In the original issue, it was assumed that MyPy didn't support Enum instances inside Literal. It turns out that this was a case of outdated documentation at Mypy, according to python/mypy#8152, and Mypy does indeed support enum members inside Literal 🎉

I was confused that Pydantic didn't support this and wondered if I had done something wrong since I was used to it working with Mypy, so if the conclusion is to not implement this (now), it might help some other people out if the documentation mentioned this limitation.

If I defined the enum as `class DessertTypes(str, enum.Enum)` it actually works as expected. Or, at least it will when the fix for #2166 makes it into a release (right now, you would end up with a `str` in the `Literal[DessertType.CAKE]` field). I'm not sure if that's a desired workaround or not.

**Comment by PrettyWood** [comment]
Hi @tobinus 
I don't understand. If you want raw enums, then you should use raw enum as value hence write
```python
print(type(Meal(dessert={'kind': DessertTypes.CAKE}).dessert).__name__)
# Cake
```
which works instead of 
```python
print(type(Meal(dessert={'kind': 'cake'}).dessert).__name__)
# ValidationError
```
which doesn't
Am I missing something?

**Comment by tobinus** [comment]
In the example, the dictionary is defined in Python, so there it would make sense to define it that way, yes. I don't have that luxury when reading in configuration files written in TOML or JSON or whatever.

**Comment by layday** [comment]
If that is a concession you're willing to make, you could have `DessertTypes` derive from `str`:

```py
class DessertTypes(str, enum.Enum):
    CAKE = 'cake'
    ICE_CREAM = 'icecream'
```

... and then Pydantic will correctly match `'cake'` to `DessertTypes.CAKE` following #2181.

**Comment by tobinus** [comment]
> If that is a concession you're willing to make, you could have `DessertTypes` derive from `str`:
> 
> ```python
> class DessertTypes(str, enum.Enum):
>     CAKE = 'cake'
>     ICE_CREAM = 'icecream'
> ```
> 
> ... and then Pydantic will correctly match `'cake'` to `DessertTypes.CAKE` following #2181.
> 
> Edit: Whoops, I missed your mentioning that at the bottom. I think it _is_ desirable, because the mix-in type is what allows comparing `Enum` members to strings.

I guess? But in that case, Pydantic is placing different requirements for how your enum should be defined in order for implicit casting to work, based on how you use it:

* Using an enum member in a `Literal`: Enum _must_ derive from the value type
* Using the enum itself as the type of a field: Enum _may_ derive from the value type, but it is not required

So:
```py
import enum
from typing import ClassVar, List, Literal

from pydantic import BaseModel


class DessertTypes(enum.Enum):
    CAKE = 'cake'
    ICE_CREAM = 'icecream'


class DessertContainers(enum.Enum):
    BOX = 'box'
    PLATE = 'plate'


class Cake(BaseModel):
    # This works:
    container: DessertContainers

    # This does not, DessertTypes must derive from str:
    kind: Literal[DessertTypes.CAKE]


print(Cake(kind='cake', container='plate'))
```

From the perspective of someone using the library (without knowing its internals), this distinction is a bit surprising.

**Comment by gbdlin** [comment]
Also, as mentioned in #1086, pydantic is now inconsistent between using enums outside of literals (where proper type casting happens) and inside of them.

**Comment by trbabb** [comment]
I found this bug after searching for it, since I just ran into the same issue myself. I can confirm that I had the same expectations as @tobinus; I was surprised that a bare value from JSON wasn't converted to its annotated Enum type. This is prompting me to write workarounds in my own codebase.

**Comment by adriangb** [comment]
This may seem inconsistent, but it really isn't: `DessertTypes('cake')` works (and that is what Pydantic does internally). 

There would have to be a very good reason for us to change this behavior, and I don't think the argument here is strong enough.

**Comment by tobinus** [comment]
> 



> This may seem inconsistent, but it really isn't: `DessertTypes('cake')` works (and that is what Pydantic does internally).
> 
> There would have to be a very good reason for us to change this behavior, and I don't think the argument here is strong enough.

Huh? What do you mean? What behaviour is it consistent with?

**Comment by adriangb** [comment]
Given:

```python
from enum import Enum

class StrEnum(str, Enum):
    foo = 'cake'

class NonStrEnum(Enum):
    foo = 'cake'

assert NonStrEnum('cake') is NonStrEnum.foo
assert StrEnum('cake') is StrEnum.foo
assert 'cake' not in {NonStrEnum.foo}
assert 'cake' in {StrEnum.foo}
```

As you can see `'cake' not in {NonStrEnum.foo}` but `NonStrEnum('cake') is NonStrEnum.foo`. I do think that's pretty inconsistent, but that's how Python itself works 🤷🏻 .

Honestly, in general, I recommend using `Literal` with bare primitive types instead of an Enum, when possible.

**Comment by tobinus** [comment]
I really have no idea what you're talking about. Are you mistaking this issue for a different one? I'm starting to see the problem, though.

For most cases, Pydantic automatically tries to convert the data you give it into the type you've specified. However, what I'm starting to realise is that this is not the case with `Literal`.

Let us remove `Enum` from the picture and instead focus on the automatic conversion between `str` and `int`. This example demonstrates how the automatic conversion is performed with non-literal int, but not for literal int:

```python
from typing import Literal

from pydantic import BaseModel


class WithLiteralInt(BaseModel):
    number: Literal[1]


class WithInt(BaseModel):
    number: int


print(WithInt(number=1))  # correct
print(WithInt(number='1'))  # is converted automatically

print(WithLiteralInt(number=1))  # correct
print(WithLiteralInt(number='1'))  # is NOT converted automatically -- fails
```

I'm willing to agree that this may make sense. This does, however, break the expectations that Pydantic sets up regarding automatic conversions. Should I make a PR adding a note about this to the documentation on Literals? This is absolutely not obvious, as demonstrated in this issue.

The fact that subclassing `str` works in the case of enums is not so relevant for this issue, though it is a neat hack.

**Comment by dmontagu** [comment]
@tobinus I think you make a fair point here; I think we'd definitely accept a PR adding a note about this in the docs.
