### ISSUE TITLE
Skip invalid items of collections instead of raising ValidationError

### ISSUE THREAD

**Issue by Bobronium** [pydantic/pydantic#2274]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request
When parsing data, you may encounter some invalid items in a list. In some cases, it's not worth to through away all of the data because of just one invalid item.

What I need is to skip invalid items if a list and leave only valid ones.

Sure, this can be done using `@validator(pre=True)`, but this needs to be default behaviour of my models and to accomplish this I will basically have to write custom validator for every single list by hand, which is not very handy.

### Related issues
#800

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```py
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /Users/rocky/.local/share/virtualenvs/.../lib/python3.6/site-packages/pydantic
               python version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
                     platform: Darwin-20.1.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

## Here's how I expect it to work:

```py
from pydantic import BaseModel
from pydantic.types import OptionalList

class Model(BaseModel):
    a: OptionalList[int]

m = Model(a=[1, '2', '?'])
assert m.a == [1, 2]
assert m.__skipped__ == [{'loc': ('a', 2), 'msg': 'value is not a valid integer', 'type': 'type_error.integer'}]
# skipped list should be returned by `validate_model()` just like errors
...
```

## Things to think of:
- Support of`conlist`, `conset` etc... and interaction with them
- Default values instead of invalid skipped ones

### Another possible syntax:
```py
a: List[int] = Field(skip_invalid=True)
```
```py
class Config:
    skip_invalid_collections_items = True

**Comment by DerRidda** [comment]
Hey fellow person who needs to only optionally validate some fields!

This has been a huge pain point for me in the past and I now have a working solution (for pydantic 1.4) that is extremely hacky and quite slow, as it delegates type creation to the runtime for optional types.

Some concerns about your proposal:
### Storing your validation notices on the model instance will break in cases where required fields are also invalid
Quite straight forward: if you have an invalid required field, it will still raise a validation error and you'll never get the model instance, thus `m.__skipped__` doesn't exist.

My solution here was to raise these optional fields as warnings. That works every time regardless of the total outcome of the validation.

Some downsides are...
- Warnings in Python are dumb and you need to once again create the warning types at runtime to give them a payload (The validation message).
- Collecting warnings in Python are not thread-safe but that#s more of an academic point in Python-land.

### `loc` is a lie, sort of
This one was driving me nuts for ages! The loc is only created when the total list of nested validation errors is flattened the final flat list. I had to reach deep into the guts of the BaseModel class to hack the propagation of the actual loc into it, because of how pydantic operates this also has some very real implications as it introduces essentially state on certain types, where there should rather be one, namely the ModelField classes. Those essentially now get polluted by the loc and you need to clean up after yourself and reset it. This also forbids recursive type uses in most cases, which doesn't affect my use case but isn't good enough for the general goals of this library.


IMHO, what needs to come first before this can be a reality is moving the loc generation into the whole validation flow for all validation first, only then can you really start extracting validation information anywhere in the validation flow, which is a necessary but insufficient prerequisite for this feature to work.

**Comment by MrMrRobat** [comment]
> Quite straight forward: if you have an invalid required field, it will still raise a validation error and you'll never get the model instance, thus `m.__skipped__` doesn't exist.

I mentioned that skipped values should be returned by `validate_model()`, just like errors. At this point, we can pass them into raised ValidationError and display as regular errors with some special flag, like so:
```py
[
    {'loc': ('a', 2), 'msg': 'value is not a valid integer', 'type': 'type_error.integer', 'skipped': True}, 
    {'loc': ('b',), 'msg': 'field required', 'type': 'value_error.missing'},
]
```

> My solution here was to raise these optional fields as warnings.

As for warnings, I think, they are too specific to fit in every workflow. And personally, I'd preferred some other way to gather skipped fields.

> IMHO, what needs to come first before this can be a reality is moving the loc generation into the whole validation flow for all validation first, only then can you really start extracting validation information anywhere in the validation flow, which is a necessary but insufficient prerequisite for this feature to work.

Agreed.

> EDIT: Oh yeah, what's extra interesting for you, to make lists work in a reasonable manner I had to iterate over them and validate every item one by one and only add the valid ones back to the resulting list.

That's exactly what I don't want to do every time and that's why I decided to open this issue in the first place :)

**Comment by MrMrRobat** [comment]
Here's my temporary implementation. It works as expected with `GenericModel` and generate schema identical to `typing.List`.

```py
from typing import TYPE_CHECKING, Any, List, Optional, TypeVar, cast

from pydantic import BaseModel
from pydantic.fields import ModelField, Undefined
from pydantic.validators import list_validator

if TYPE_CHECKING:
    from pydantic.typing import DictStrAny

ItemT = TypeVar('ItemT')


class LenientList(List[ItemT]):
    """
    LenientList[T] is same as List[T], but will skip invalid items instead of raising error

    At some point this behaviour might be implemented in pydantic:
    https://github.com/samuelcolvin/pydantic/issues/2274
    """

    _item_field: ModelField

    def __class_getitem__(cls, type_):
        """
        Returned type must be subclass of LenientList for validation to work,
        But it also needs to smell like typing.List[T] for pydantic magic to work properly
        """
        if isinstance(type_, tuple):
            (type_,) = type_
        elif hasattr(cls, '_item_field'):
            raise TypeError(f'{cls.__name__} is already concrete')

        if isinstance(type_, TypeVar):
            pydantic_type = type(f'LenientList[{type_}]', (cls,), {})
        else:
            item_field = ModelField.infer(
                name='item',
                value=Undefined,
                annotation=type_,
                class_validators=None,
                config=BaseModel.__config__,
            )
            t_name = getattr(type_, "__name__", None) or type_.__class__.__name__
            pydantic_type = type(f'LenientList[{t_name}]', (cls,), {'_item_field': item_field})

        generic_alias = super().__class_getitem__(type_)
        # this will enable support of GenericModel and json schema
        pydantic_type.__origin__ = generic_alias.__origin__
        pydantic_type.__parameters__ = generic_alias.__parameters__
        pydantic_type.__args__ = generic_alias.__args__
        return pydantic_type

    @classmethod
    def __get_validators__(cls):
        yield cls._list_validator

    @classmethod
    def _list_validator(cls, raw_value: Any, values: 'DictStrAny', field: ModelField) -> Optional[List[ItemT]]:
        if raw_value is None and not field.required:
            return None
        list_value: List[Any] = list_validator(raw_value)
        parsed: List[ItemT] = []
        for item in list_value:
            value, error = cls._item_field.validate(item, values, loc=())
            if error is None:
                parsed.append(cast(ItemT, value))
        return parsed


class Root(BaseModel):
    items: LenientList[int]


print(Root(items=[1, 'noo', 3]))  # items=[1, 3]
```

**Comment by EwertonBello** [comment]
> Here's my temporary implementation. It works as expected with `GenericModel` and generates schema identical to `typing.List`.
> 
> ```python
> from typing import TYPE_CHECKING, Any, List, Optional, TypeVar, cast
> 
> from pydantic import BaseModel
> from pydantic.fields import ModelField, Undefined
> from pydantic.validators import list_validator
> 
> if TYPE_CHECKING:
>     from pydantic.typing import DictStrAny
> 
> ItemT = TypeVar('ItemT')
> 
> 
> class LenientList(List[ItemT]):
>     """
>     LenientList[T] is same as List[T], but will skip invalid items instead of raising error
> 
>     At some point this behaviour might be implemented in pydantic:
>     https://github.com/samuelcolvin/pydantic/issues/2274
>     """
> 
>     _item_field: ModelField
> 
>     def __class_getitem__(cls, type_):
>         """
>         Returned type must be subclass of LenientList for validation to work,
>         But it also needs to smell like typing.List[T] for pydantic magic to work properly
>         """
>         if isinstance(type_, tuple):
>             (type_,) = type_
>         elif hasattr(cls, '_item_field'):
>             raise TypeError(f'{cls.__name__} is already concrete')
> 
>         if isinstance(type_, TypeVar):
>             pydantic_type = type(f'LenientList[{type_}]', (cls,), {})
>         else:
>             item_field = ModelField.infer(
>                 name='item',
>                 value=Undefined,
>                 annotation=type_,
>                 class_validators=None,
>                 config=BaseModel.__config__,
>             )
>             t_name = getattr(type_, "__name__", None) or type_.__class__.__name__
>             pydantic_type = type(f'LenientList[{t_name}]', (cls,), {'_item_field': item_field})
> 
>         generic_alias = super().__class_getitem__(type_)
>         # this will enable support of GenericModel and json schema
>         pydantic_type.__origin__ = generic_alias.__origin__
>         pydantic_type.__parameters__ = generic_alias.__parameters__
>         pydantic_type.__args__ = generic_alias.__args__
>         return pydantic_type
> 
>     @classmethod
>     def __get_validators__(cls):
>         yield cls._list_validator
> 
>     @classmethod
>     def _list_validator(cls, raw_value: Any, values: 'DictStrAny', field: ModelField) -> Optional[List[ItemT]]:
>         if raw_value is None and not field.required:
>             return None
>         list_value: List[Any] = list_validator(raw_value)
>         parsed: List[ItemT] = []
>         for item in list_value:
>             value, error = cls._item_field.validate(item, values, loc=())
>             if error is None:
>                 parsed.append(cast(ItemT, value))
>         return parsed
> 
> 
> class Root(BaseModel):
>     items: LenientList[int]
> 
> 
> print(Root(items=[1, 'noo', 3]))  # items=[1, 3]
> ```

How would it work for a single item? to implement a pagination

**Comment by vsheg** [comment]
A very useful suggestion. I'm working with an old and poorly documented API, and I can't predict in advance all possible responses and exception handling, ignoring and logging artifacts in this case is a great strategy. The code remains clean and understandable

**Comment by 1995chen** [comment]
> Here's my temporary implementation. It works as expected with `GenericModel` and generates schema identical to `typing.List`.
> 
> ```python
> from typing import TYPE_CHECKING, Any, List, Optional, TypeVar, cast
> 
> from pydantic import BaseModel
> from pydantic.fields import ModelField, Undefined
> from pydantic.validators import list_validator
> 
> if TYPE_CHECKING:
>     from pydantic.typing import DictStrAny
> 
> ItemT = TypeVar('ItemT')
> 
> 
> class LenientList(List[ItemT]):
>     """
>     LenientList[T] is same as List[T], but will skip invalid items instead of raising error
> 
>     At some point this behaviour might be implemented in pydantic:
>     https://github.com/samuelcolvin/pydantic/issues/2274
>     """
> 
>     _item_field: ModelField
> 
>     def __class_getitem__(cls, type_):
>         """
>         Returned type must be subclass of LenientList for validation to work,
>         But it also needs to smell like typing.List[T] for pydantic magic to work properly
>         """
>         if isinstance(type_, tuple):
>             (type_,) = type_
>         elif hasattr(cls, '_item_field'):
>             raise TypeError(f'{cls.__name__} is already concrete')
> 
>         if isinstance(type_, TypeVar):
>             pydantic_type = type(f'LenientList[{type_}]', (cls,), {})
>         else:
>             item_field = ModelField.infer(
>                 name='item',
>                 value=Undefined,
>                 annotation=type_,
>                 class_validators=None,
>                 config=BaseModel.__config__,
>             )
>             t_name = getattr(type_, "__name__", None) or type_.__class__.__name__
>             pydantic_type = type(f'LenientList[{t_name}]', (cls,), {'_item_field': item_field})
> 
>         generic_alias = super().__class_getitem__(type_)
>         # this will enable support of GenericModel and json schema
>         pydantic_type.__origin__ = generic_alias.__origin__
>         pydantic_type.__parameters__ = generic_alias.__parameters__
>         pydantic_type.__args__ = generic_alias.__args__
>         return pydantic_type
> 
>     @classmethod
>     def __get_validators__(cls):
>         yield cls._list_validator
> 
>     @classmethod
>     def _list_validator(cls, raw_value: Any, values: 'DictStrAny', field: ModelField) -> Optional[List[ItemT]]:
>         if raw_value is None and not field.required:
>             return None
>         list_value: List[Any] = list_validator(raw_value)
>         parsed: List[ItemT] = []
>         for item in list_value:
>             value, error = cls._item_field.validate(item, values, loc=())
>             if error is None:
>                 parsed.append(cast(ItemT, value))
>         return parsed
> 
> 
> class Root(BaseModel):
>     items: LenientList[int]
> 
> 
> print(Root(items=[1, 'noo', 3]))  # items=[1, 3]
> ```
work fine, thank you

**Comment by aliceh75** [comment]
In case anyone is waiting for feedback on this, `LenientList` as implemented here by Bobronium works for me in a complex schema, with pydantic 1.10.2. I don't know the internals of pydantic enough to give a proper code review though.

**Comment by radupotop** [comment]
A property to collect the errors on LenientList would be very handy, so they can be logged for later inspection.

**Comment by samuelcolvin** [comment]
> A property to collect the errors on LenientList would be very handy, so they can be logged for later inspection.

collecting errors should become possible in V2 with `context`, see [here](https://docs.pydantic.dev/blog/pydantic-v2/#validation-context).

---

This should be possible in V2 with [`on_error='omit'`](https://github.com/pydantic/pydantic-core/blob/7d7ca9f1d11b7145df72c70601271ac3c7113c6e/pydantic_core/core_schema.py#L1470) but we should make sure it's actually possible before release.

**Comment by samuelcolvin** [comment]
@Bobronium it should be possible now using [`__get_pydantic_validation_schema__`](https://github.com/pydantic/pydantic/blob/afff676c03838cfbc948ad8217f969f686d7796a/pydantic/_internal/_generate_schema.py#LL86C49-L86C49), any chance you could try it out? PR welcome to add this type for V2.

**Comment by Bobronium** [comment]
@samuelcolvin, thanks for a heads up! 

Yeah, I totally can try to implement it. 

Do you have any concrete time frame for this PR in mind?

**Comment by samuelcolvin** [comment]
No hurry, some time before the end of March would be great.

**Comment by mason3k** [comment]
Hi @Bobronium, is there any chance you've had an opportunity to work on this? Can I help in any way?

**Comment by Bobronium** [comment]
@Mason3k, I haven't even started yet, but planned later this month, as was discussed above. 

I would be glad to accept any help on this! And if you'd like to work on this yourself, I'd be glad to provide my help. We can code pair, for example and I could assist you if you'd have any difficulties.

**Comment by adriangb** [comment]
I have some good news, after thinking about this for a bit I think this not only works in V2 but is also super powerful and re-usable:

```python
from dataclasses import dataclass
from typing import Annotated, Any, Callable, List, TypeVar

from pydantic_core import ValidationError
from pydantic_core import core_schema as cs

_ERROR = object()

@dataclass
class ErorrItemsMarker:
    def __get_pydantic_core_schema__(
        self, source_type: Any, handler: Callable[[Any], cs.CoreSchema]
    ) -> cs.CoreSchema:
        schema = handler(source_type)
        def val(v: Any, handler: cs.ValidatorFunctionWrapHandler) -> Any:
            try:
                return handler(v)
            except ValidationError:
                return _ERROR

        return cs.no_info_wrap_validator_function(val, schema, serialization=schema.get('serialization'))


@dataclass
class ListErrorFilter:
    def __get_pydantic_core_schema__(
        self, source_type: Any, handler: Callable[[Any], cs.CoreSchema]
    ) -> cs.CoreSchema:
        schema = handler(source_type)

        def val(v: List[Any]) -> List[Any]:
            return [item for item in v if item is not _ERROR]

        return cs.no_info_after_validator_function(val, schema, serialization=schema.get('serialization'))


T = TypeVar('T')

LenientList = Annotated[List[Annotated[T, ErorrItemsMarker()]], ListErrorFilter()]


from pydantic import BaseModel


class Model(BaseModel):
    x: LenientList[int]
    y: LenientList[str]
    z: LenientList[List[int]]


print(Model(x=[1, '2', 'c'], y=['a', 'b', 3], z=[['a'], ['1']]))
#> x=[1, 2] y=['a', 'b'] z=[[1]]
```

Obviously you may want slightly different behavior, but I think this general template can be adapted.

**Comment by samuelcolvin** [comment]
It's also supported out of the box in pydantic-core, see a test example [here](https://github.com/pydantic/pydantic-core/blob/43aa422a47b945516784a907bdc9e64344934333/tests/validators/test_list.py#L173-L185) and the schema to configure it [here](https://github.com/pydantic/pydantic-core/blob/43aa422a47b945516784a907bdc9e64344934333/pydantic_core/core_schema.py#L2237).

I implemented this months ago thinking of this issue, but forgot to reference it and we haven't added support in python yet.

**Comment by dmontagu** [comment]
@samuelcolvin that doesn't expose a way to track the errors does it? I implemented a slight tweak to @adriangb's very good suggestion here: https://gist.github.com/dmontagu/7f0cef76e5e0e04198dd608ad7219573, this adds an attribute to `LenientList` called `errors` that lets you retrieve the validation errors, and has a method `with_errors()` that returns the items and errors in the order corresponding to validation.

The implementation has some warts, but perhaps someone will find it useful.

Either way, this is another good example of how to create a pydantic core schema for a custom generic type.

**Comment by mdagost** [comment]
Is there any example anywhere of using this `on_error='omit'` in v2?

**Comment by divadsn** [comment]
Bump

**Comment by Viicos** [comment]
[`OnErrorOmit`](https://docs.pydantic.dev/latest/api/types/#pydantic.types.OnErrorOmit) can be used to use `on_error='omit'`.

**Comment by leonardzou** [comment]
> Is there any example anywhere of using this `on_error='omit'` in v2?

There's an example here 🙂 https://github.com/pydantic/pydantic/blob/cd3b0ad3943829a00d22da9a9156256b97fad9ae/tests/test_types.py#L6656

or for a list `List[OnErrorOmit[<type>]]`

**Comment by pipinfitriadi** [comment]
> > Is there any example anywhere of using this `on_error='omit'` in v2?
> 
> There's an example here 🙂
> 
> https://github.com/pydantic/pydantic/blob/cd3b0ad3943829a00d22da9a9156256b97fad9ae/tests/test_types.py#L6656
> 
> or for a list `List[OnErrorOmit[<type>]]`

This is what I am looking for.. thanks @adriangb @leonardzou.. Anyway, how we can get list errors for further development? Lets say I want it to put on logging.error message
