### ISSUE TITLE
Allow specifying individual settings as files

### ISSUE THREAD

**Issue by notpushkin** [pydantic/pydantic#2284]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

In addition to `secrets_dir`, it would be nice to allow passing individual environment, like in [lego](https://go-acme.github.io/lego/dns/#environment-variables-file) / [Traefik](https://doc.traefik.io/traefik/https/acme/#providers). This would be more flexible as it doesn't make code author assume there's a single `_secrets_dir` at a specified location:

```py
class Settings(BaseSettings):
    ...
    database_password: str
```
```sh
printf "This is a secret" | docker secret create my_secret_data -
docker service create \
       --name pydantic-with-secrets \
       --secret my_secret_data \
       -e DATABASE_PASSWORD_FILE=/run/secret/my_secret_data
       pydantic-app:latest
```

Please let me know if you would be interested in a PR!

---

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/ale/dev/lunni/core/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-62-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

**Comment by picarro-mbuckner** [comment]
I would also add that in Kubernetes you can mount a configmap into a container with a very similar structure to a secrets directory. It would be handy to be able to specify a non secrets directory in the same way, as in that setup you can't mount both sources to the same directory.

The logic in this SecretSettingsSource class could be more generalized into a DirectorySettingsSource so one could have multiple directories specified: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/env_settings.py#L246 I'm also happy to submit a PR

**Comment by samuelcolvin** [comment]
this should be supported in pydantic-settings now since we allow customisation of sources.

**Comment by notpushkin** [comment]
@samuelcolvin I've looked into it and seems like it's be possible to just add a new `SettingsSource`. Should I move this ticket over to the pydantic-settings repo?

Congrats on the funding round BTW!

**Comment by hramezani** [comment]
@notpushkin I am not sure that we want to support this source in `pydantic-settings`. So, as @samuelcolvin mentioned you can have your own source class.

BTW, let's wait for @samuelcolvin to decide.
