### ISSUE TITLE
Allow parsing extra attributes into a separate dict

### ISSUE THREAD

**Issue by notpushkin** [pydantic/pydantic#2285]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this feature/change is needed
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Feature Request

---

Right now, model config's `extra` option can only cause validation to fail if extra attributes are included (`'forbid'`), silently ignore any extra attributes (`'ignore'`), or assign the attributes to the model (`'allow'`). I'm trying to implement a parser for a subset of the [Compose Spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md), which defines three ways of handling [extra attributes](https://github.com/compose-spec/compose-spec/blob/563f286ca089b3d27e66fffce262d213e7b55202/spec.md#requirements-and-optional-attributes):

- default: warn user about unsupported attributes, but ignore them
- strict: warn user about unsupported attributes and reject the compose file (`'forbid'` in Pydantic)
- loose: ignore unsupported attributes AND unknown attributes (`'ignore'` in Pydantic)

I want to implement the `default` mode, but for that I need to get the extra attributes without actually parsing them into the model. The most straightforward and, hopefully, useful for other use cases way is to parse them into some separate dict like `my_model.extra`:

```py
class ComposeProject(BaseModel):
    version: Optional[str]

    class Config:
        extra = "separate"

project = ComposeProject({
  "version": "3",
  "services": ...
})
project.version  # => '3'
project.extra  # => {'services': Ellipsis}
f"Ignored unsupported attributes: {', '.join(project.extra.keys())}"
```

---

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/ale/dev/lunni/core/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
                     platform: Linux-5.4.0-62-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

**Comment by PrettyWood** [comment]
Hi @notpushkin 
You can do it yourself quite easily
```py
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, root_validator


class ComposeProject(BaseModel):
    versio: Optional[str] = Field(alias='version')  # just to show that it supports alias too
    extra: Dict[str, Any]

    @root_validator(pre=True)
    def build_extra(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        all_required_field_names = {field.alias for field in cls.__fields__.values() if field.alias != 'extra'}  # to support alias

        extra: Dict[str, Any] = {}
        for field_name in list(values):
            if field_name not in all_required_field_names:
                extra[field_name] = values.pop(field_name)
        values['extra'] = extra
        return values


project = ComposeProject(**{
  "version": "3",
  "services": ...
})
print(project.versio)  # => '3'
print(project.extra)  # => {'services': Ellipsis}
```
Hope it helps!

**Comment by pawelzelus** [comment]
@PrettyWood Very thankful, thank you. I was wondering if this is even possible to do for children of the model? Current solution ignores it and I'm not sure how read children from `cls`.

**Comment by dmontagu** [comment]
In v2, you can get information about the fields through `cls.model_fields` (I believe `cls.__fields__` in v1). If you want to do this sort of thing in a recursive way, I think you'll need to implement some form of complex `root_validator`/`model_validator`, but this is a sufficiently exotic use case that I think we won't be able to offer direct support for other approaches here (with the _possible_ exception of a modified approach to `extra='allow'` where we store the values in an attribute outside `__dict__`) without stronger community consensus.
