### ISSUE TITLE
Add some documentation to warn about `BaseModel.validate()` method

### ISSUE THREAD

**Issue by nathanparekh** [pydantic/pydantic#2289]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
It seems like Literals are not properly evaluated when a root validator is added to a model. In the example below, a Literal would be expected to discriminate which submodel the data is matched to based on the operator value (if an arithmetic operator is provided, it should use the ArithmeticOperators model, if boolean BooleanOperators, etc.). However, the models are not properly determined if the root validator on the BooleanOperators model passes and returns a value. It would be expected that because of the Literal operator, the provided data should not match the BooleanOperators model and should instead match the ArithmeticOperators model first; instead, the model never reaches the ArithmeticOperators validation.

### Example

```py
from typing import Literal, List, Dict, Any, Union

import inflection
import pydantic
from pydantic import Field, root_validator, BaseModel


class Parent(pydantic.BaseModel):
    string_value: str = "string"

    class Config:
        extra = "forbid"

        @classmethod
        def alias_generator(cls, string: str) -> str:
            return inflection.camelize(string, False)


class BooleanOperators(Parent):
    operator: Literal["or", "and", "xor", "nor", "not"]
    args: List[str] = Field(min_items=1)

    @root_validator
    def validate(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        if values["operator"] == "not":
            if len(values["args"]) > 1:
                raise ValueError("'not' may not have more than 1 argument")
        else:
            if len(values["args"]) < 2:
                raise ValueError("other than 'not' require at least 2 arguments")
        return values


class ArithmeticOperators(Parent):
    operator: Literal["+", "-", "*", "/"]
    args: List[str] = Field(min_items=2)


class NonExistentOperators(Parent):
    operator: Literal["foo", "bar"]
    args: List[str] = Field(min_items=1)


class MainModel(BaseModel):
    submodel: Union[BooleanOperators, ArithmeticOperators, NonExistentOperators]

```

Expected:
```py
>>> MainModel(submodel={"operator":"+", "args":["helloWorld","testText"]})
MainModel(submodel=ArithmeticOperators(string_value='string', operator='+', args=['helloWorld', 'testText']))
```
Actual:
```py
>>> MainModel(submodel={"operator":"+", "args":["helloWorld","testText"]})
MainModel(submodel={'operator': '+', 'args': ['helloWorld', 'testText']})
```
### Current Workaround
Reversing the order of BooleanOperators and ArtithmeticOperators in the Union takes care of the issue based on prioritization on models. However, this is not documented to apply in the case of Literals, and it is confusing -- it would make sense that the first model would not match and it would progress to the second, so the order is assumed not to matter in this case.

---
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.7.3
            pydantic compiled: True
               python version: 3.8.6rc1 (tags/v3.8.6rc1:08bd63d, Sep  7 2020, 23:10:23) [MSC v.1927 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by PrettyWood** [comment]
Hi @nathanparekh 
The fix is very easy but not trivial to find: you need to change the name of your `root_validator` (`validate` is reserved and you overwrite it here)
Similar issue: https://github.com/samuelcolvin/pydantic/issues/1746, solution planned for v2: https://github.com/samuelcolvin/pydantic/issues/1001
Try with this for example

```python
class BooleanOperators(Parent):
    operator: Literal["or", "and", "xor", "nor", "not"]
    args: List[str] = Field(min_items=1)

    @root_validator
    def valid_op(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        with suppress(KeyError):
            if values["operator"] == "not":
                if len(values["args"]) > 1:
                    raise ValueError("'not' may not have more than 1 argument")
            else:
                if len(values["args"]) < 2:
                    raise ValueError("other than 'not' require at least 2 arguments")

        return values
```

Hope it helps! :)

**Comment by nathanparekh** [comment]
Hi @PrettyWood,
Thanks for the hint! That clears things up. I guess I totally misjudged what the problem was. 
Would it be helpful if I tried adding a warning or another bullet under "things to note" on the validators page of the docs?

**Comment by PrettyWood** [comment]
A warning for v1 can probably be added! Doc PRs are always welcome :)

**Comment by dmontagu** [comment]
This is now resolved in v2 — pydantic-specific methods are "namespaced" to always start with `model_`, so it should be easier to avoid surprises. (We have plans for a solution that ensures even those names are available, though it's not ready quite yet).

(Please comment if I've misunderstood and this issue should be re-opened.)
