### ISSUE TITLE
Aliases are not applied in validators or class methods of BaseModel causing error

### ISSUE THREAD

**Issue by lynochka** [pydantic/pydantic#2299]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
Aliases are not applied in validators or class methods of BaseModel causing error in a method calling it for validation.
Originally, I did not find any native method in BaseModel to verify the required properties of a Field, the schema was valid without passing them  (I need them in the schema rather than creating multiple validators or replicating code).

I tried different ways and saw that schema is not correct at the moment of validation (.

```py
people = [
                {
                    "Id": "123",
                    "DisplayName": "Bob",
                    "ScoredEmailAddresses": {
                        "scoredEmailAddresses": [
                            {
                                "Address": "Bob@yahoo.com",
                                "RelevanceScore": 306722690.0,
                                "SelectionLikelihood": "NotSpecified",
                            }
                        ]
                    }
                }
            ]

from typing import Dict, Any
from jsonschema import validate
from pydantic import BaseModel, Field

def to_camel(string: str) -> str:
    return ''.join(word.capitalize() for word in string.split('_'))

class People(BaseModel):
    id: str = Field(alias="Id")
    display_name: str = Field(alias="DisplayName")
    scored_email_addresses: Dict[str, Any] = Field(properties={"scoredEmailAddresses":{}}, required=["scoredEmailAddresses"])

    class Config:
        alias_generator = to_camel

    def validate(self):
        print(self.dict())
        validate(instance=self.dict(), schema=type(self).schema())
        return self


print(People.schema_json(indent=4)) 
people = People(**people[0])
print(people)
validate(instance=people[0], schema=People.schema())
print(people.validate())
"""output
ValidationError: 'Id' is a required property

Failed validating 'required' in schema:
    {'properties': {'DisplayName': {'title': 'Displayname',
                                    'type': 'string'},
                    'Id': {'title': 'Id', 'type': 'string'},
                    'ScoredEmailAddresses': {'properties': {'scoredEmailAddresses': {}},
                                             'required': ['scoredEmailAddresses'],
                                             'title': 'Scoredemailaddresses',
                                             'type': 'object'}},
     'required': ['Id', 'DisplayName', 'ScoredEmailAddresses'],
     'title': 'People',
     'type': 'object'}

On instance:
    {'display_name': 'Bob',
     'id': '123',
     'scored_email_addresses': {'scoredEmailAddresses': [{'Address': 'Bob@microsoft.com',
                                                          'RelevanceScore': 306722690.0,
                                                          'SelectionLikelihood': 'NotSpecified'}]}}
"""
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: C:\repos\peopleintelligence\CollaborationNetworks\.env\Lib\site-packages\pydantic
               python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']

jsonschema: 3.2.0
```

```py
import pydantic
import jsonschema 
...
```

**Comment by PrettyWood** [comment]
Hi @lynochka
Just add `by_alias=True` in `dict()` ;)
FYI it's better to avoid the method name `validate` as it overwrites _pydantic_ one (this will be changed in v2).
So putting things together
```py
class People(BaseModel):
    ...

    def validate_dict(self):
        validate(instance=self.dict(by_alias=True), schema=type(self).schema())
        return self
```
Hope it helps!

**Comment by lynochka** [comment]
Ah, great, thanks! Your documentation is mostly examples based. I should have dug more into the source :D 

Could you please confirm that there is no native method within _pydantic_ to do this validation (you saw that I had to combine it with _jsonschema_)

**Comment by PrettyWood** [comment]
If you want to validate against the schema you'll indeed need to use `jsonschema` yourself.
If you just want to validate your payload, that's the whole purpose of _pydantic_. Creating an instance of the object already does validation (not a strict one though)
By the way you may want to rewrite your model like this
```py
from typing import Any

from pydantic import BaseModel, Field

def to_camel(string: str) -> str:
    return ''.join(word.capitalize() for word in string.split('_'))


class ScoredEmailAddresses(BaseModel):
    scoredEmailAddresses: Any = ...


class People(BaseModel):
    id: str = Field(alias="Id")
    display_name: str = Field(alias="DisplayName")
    scored_email_addresses: ScoredEmailAddresses

    class Config:
        alias_generator = to_camel


People(**heron_people[0])
```

**Comment by lynochka** [comment]
I understand that you could take out ScoredEmailAddresses, but it was an example, i have a much deeper structure which might need usage of Field anyway

**Comment by lynochka** [comment]
And as a follow-up question, can any validator decorator  use 'self' instead of 'values' dictionary , otherwise, it is not as straightforward to change specific keys with aliases in order to validate as a part of the decorator.

**Comment by PrettyWood** [comment]
Nope only `values`, which are the values of the previous fields (order matters!)
You may want to have a look at `root_validator` if you want to really change different keys based on other values.

**Comment by lynochka** [comment]
`root_validator` is the one I am talking about, it does not include self. All in all I am asking how to write the same thing as what validate_dict would do in a (decorated) method that would verify my instance on creation. Thanks in advance!

**Comment by PrettyWood** [comment]
How about
```py
    @root_validator
    def validate_against_schema(cls, values):
        alias_values = {to_camel(k): v for k, v in values.items()}
        validate(instance=alias_values, schema=cls.schema())
        return values
```
?

**Comment by lynochka** [comment]
Ahah, pretty cool, but now all our aliases follow the standard camel case format

**Comment by PrettyWood** [comment]
```py
    @root_validator
    def validate_against_schema(cls, values):
        name_to_alias = {name: field.alias for name, field in cls.__fields__.items()}
        alias_values = {name_to_alias[k]: v for k, v in values.items()}
        validate(instance=alias_values, schema=cls.schema())
        return values
```
? 😆

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
