### ISSUE TITLE
OverflowError if np.inf for integer values

### ISSUE THREAD

**Issue by andreas-vester** [pydantic/pydantic#2345]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Pydantic Version: 1.7.3

The following code generates an ``OverflowError: cannot convert float infinity to integer``

```
import numpy as np
from pydantic import BaseModel


class Model(BaseModel):
    num: int


Model(num=np.inf)
```

On the other hand, using ``np.nan`` generates a ``type_error.integer``, which is more intuitive, in my view.

Shouldn't we get the same error for ``np.inf``, too?

**Comment by PrettyWood** [comment]
Hi @KraxelHuber 
We could maybe add `OverflowError` in the caught errors here
https://github.com/samuelcolvin/pydantic/blob/61b45340e78a66af132d975ba063fae691db25a0/pydantic/validators.py#L121-L124
The only problem is that depending on the used libraries it won't have the same meaning and I'm afraid we'll need to add more and more exceptions that are not directly related to python or pydantic
It may be better to add your own validator

**Comment by KraxelHuber** [comment]
I think ``np.inf`` should raise the same error as ``np.nan``. It simply is not a valid ``int``.

**Comment by Kludex** [comment]
On V2 we have the following validation error:

```python
num
  Input should be a finite number [type=finite_number, input_value=inf, input_type=float]
```
