### ISSUE TITLE
Attribute disappear from model instance after assignment validation

### ISSUE THREAD

**Issue by nobbynobbs** [pydantic/pydantic#2346]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:

```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /home/user/project/.venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.9 (default, Aug 18 2020, 02:07:21)  [GCC 9.3.0]
                     platform: Linux-5.5.15-050515-generic-x86_64-with-Ubuntu-20.04-focal
     optional deps. installed: ['typing-extensions']
```

<details>
<summary>description</summary>

I use pydantic as mapper for MongoDB documents. The data in db is dirty and sometimes contains `null` values in fields where it's not supposed to be. To prevent validation errors and use defaults for such values I've defined root_validator to get rid of `null`s and it've been working fine until update.
</details>

Here is minimal example illustrated the problem. Probably it's related to changes in #2116

```py
from typing import Optional

import pydantic
import pytest


class A(pydantic.BaseModel):
    a: Optional[dict] = None
    b: int = 1

    class Config:
        validate_assignment = True

    @pydantic.root_validator(pre=True)
    def omit_empty(cls, values):
        """remove None values from raw data before instance creation"""
        return {k: v for k, v in values.items() if v is not None}


def test_disappearing():
    a = A()
    assert a.a is None  # OK
    a.b = 2
    with pytest.raises(AttributeError) as e:
        # I would never expect for attribute just disappear but it does
        assert a.a is None
    assert "'A' object has no attribute 'a'" in str(e)
```

**Comment by PrettyWood** [comment]
Hi @nobbynobbs 
Well `root_validators` are just like other `validators` but with the whole context and are such considered like one also for assignment since https://github.com/samuelcolvin/pydantic/issues/1971.
But I agree it's not really clear the validators you want to run at `init` and the ones you want to run at `assignment`. Currently there is no distinction done :/

**Comment by nobbynobbs** [comment]
@PrettyWood hi! Could you suggest any workaround? Probably in my case I may just override `__init__`, filter `None` values there and remove `root_validator` at all. And If so, should I close the issue or not? Field vanishing looks like very unexpected behavior for me )

**Comment by PrettyWood** [comment]
How about
```py
class A(pydantic.BaseModel):
    a: Optional[dict] = None
    b: int = 1

    class Config:
        validate_assignment = True

    def __init__(self, **values):
        data = {k: v for k, v in values.items() if v is not None}
        super().__init__(**data)
```
?

**Comment by nobbynobbs** [comment]
@PrettyWood 
Yes, thanks you, I've made exactly like that )))
