### ISSUE TITLE
Remove support for python 3.6

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#2374]
Python 3.6 is 4 years old and reaches end of life at the end of this year.

It's served us well, but perhaps it's time to throw it in the rubbish bin (yes UK english 🖕) of history and move on.

Doing this would:
* make CI run faster
* use a little less energy to run CI, I know that sounds very woke but when you think about the amount of CPU time spend running tests and compilation it get's a bit scary, especially with #2358
* simplify some of the logic around typing a lot

Blockers?:
* according to https://pypistats.org/packages/pydantic python 3.6 has only just dropped to 3rd place behind 3.7 and 3.8 and still represents 18% of downloads
* are there any platforms that really want to use pydantic but only support 3.6? E.g. there are pydantic packages for fedora, ubuntu, suse, debian and other flavours of linux, do any of them require 3.6. Do we care?

**Comment by StephenBrown2** [comment]
> end of life at the end of this year.

I would say hang on until the end of the year, I know of several instances that are still running Ubuntu 18.04, which ships with 3.6, even though the latest LTS (20.04) comes with 3.8.

**Comment by PrettyWood** [comment]
I think it's too soon to drop python 3.6 support too **but** we could make v2 for python 3.7+ only.
For python 3.6 people would need to stick with v1.8/9/10 depending on how many versions are left before v2.
This way no need to run the CI on 3.6 for future dev

**Comment by daviskirk** [comment]
I would push v2 as far up the version chain as possible. Having spent some time looking at all of the changes to typing coming in to 3.7, 3.8, 3.9, 3.10 those parts are probably going to be really hard to support (nicely) all at once.

**Comment by samuelcolvin** [comment]
Done in V1.10.
