### ISSUE TITLE
Validators are called without fields being set if there are any `pre` validators

### ISSUE THREAD

**Issue by ofek** [pydantic/pydantic#2376]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: C:\Users\ofek\AppData\Local\Programs\Python\Python38\Lib\site-packages\pydantic
               python version: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions', 'email-validator']
```

```py
from typing import Optional

from pydantic import BaseModel, validator


class UserModel(BaseModel):
    name: str
    foo: Optional[str]

    @validator('foo', pre=True)
    def validate_if_set(cls, v, field):
        raise ValueError('should not occur')

    @validator('foo', pre=True, always=True)
    def set_default(cls, v, field):
        raise ValueError('to illustrate this has not even been called yet')


def main():
    user = UserModel(name='test')
    print(user)


if __name__ == '__main__':
    main()
```

**Comment by ofek** [comment]
Is there an attribute on `field` that indicates whether or not it was supplied by the user/class constructor?

**Comment by PrettyWood** [comment]
Thanks for reporting! I guess it has never been spotted in more than 3 years ^^
Here is [an idea of a fix](https://github.com/samuelcolvin/pydantic/compare/master...PrettyWood:fix/always?expand=1)
There is no way to know whether or not a value has been supplied at this stage.
You could probably use `root_validator`

**Comment by ofek** [comment]
Is there any way to pass arbitrary data from the constructor to the validators?

**Comment by ofek** [comment]
@samuelcolvin Do you know of a way (even hacky) to pass arbitrary data from the constructor to the validators? I can pass data only to `@root_validator(pre=True)`.

**Comment by dmontagu** [comment]
It appears to me the specific issue reported here has been resolved in v2.

@ofek if you are still interested, depending on what you want it may be possible to do it in v2 via `@model_validator(mode='wrap')`. If that doesn't work for you please provide more information.

**Comment by ofek** [comment]
Awesome, thanks!
