### ISSUE TITLE
Inheriting GenericModel does not make the subclass Generic

### ISSUE THREAD

**Issue by phdowling** [pydantic/pydantic#2380]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

To start: I hope I have not misunderstood how Generics are supposed to work in pydantic. If I have, feel free to disregard this issue. My problem boils down to something simple. Let's say we inherit from a generic class in "plain python". If we do this, then the child class is also a generic, we can index it with a type parameter:
```py
from typing import TypeVar, Generic
T = TypeVar("T")

class MyGeneric(Generic[T]):
    def __init__(self, field: T):
        self.field = field
    field: T

a = MyGeneric[str](field="abc")

class MyOtherGeneric(MyGeneric[T]):
    pass

b = MyOtherGeneric[int](field=1)
```

Trying almost the same thing in pydantic, we get an exception:
```py
from pydantic.generics import GenericModel
from typing import TypeVar, Generic
T = TypeVar("T")

class MyGenericModel(GenericModel, Generic[T]):
    field: T

c = MyGenericModel[str](field="abc")

class MyOtherGenericModel(MyGenericModel[T]):
    pass

d = MyOtherGenericModel[int](field=1)  # this part breaks
```
Here's the error:
```
Traceback (most recent call last):
  File "........./generic.py", line 28, in <module>
    c = MyOtherGenericModel[int](field=1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pydantic/generics.py", line 52, in __class_getitem__
    check_parameters_count(cls, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pydantic/generics.py", line 118, in check_parameters_count
    raise TypeError(f'Too {description} parameters for {cls.__name__}; actual {actual}, expected {expected}')
TypeError: Too many parameters for MyOtherGenericModel; actual 1, expected 0

```

The only workaround I've found is to use multiple inheritance and to keep adding Generic[T] as a second parent class on the child. In principle that works, but its easy to forget this (which would cause issues down the line that might not be caught right away).

Is this fundamentally supposed to work, and is there a way to make it work?

**Comment by tfwillems** [comment]
Hi @phdowling,

The [docs](https://pydantic-docs.helpmanual.io/usage/models/#generic-models) point out that "To inherit from a GenericModel without replacing the TypeVar instance, a class must also inherit from typing.Generic." So this would resolve your issue:

```py

from pydantic.generics import GenericModel
from typing import TypeVar, Generic
T = TypeVar("T")

class MyGenericModel(GenericModel, Generic[T]):
    field: T


class MyOtherGenericModel(MyGenericModel[T], Generic[T]):
    pass

d = MyOtherGenericModel[int](field=1)  # no longer breaks

```

**Comment by phdowling** [comment]
Hi @tfwillems - thanks for the quick reply. I did notice that adding `Generic` as a parent on each subclass fixes it, sorry of course for missing it in the docs. 

I guess that means it's intended behaviour, which makes this not so much a bug but rather a question: is there any chance this would ever be changed? Here's the issue I see: If I ship a library that uses pydantic types, with some of them being generic, users must always remember to subclass `Generic` even if their own code has no need for some given class to be generic (as long as the library needs the class to be generic somewhere down the line). It's easy for users to forget this, and potentially difficult for them to understand why it's be necessary.

I realize it might seem like a niche concern, but since it's somewhat unexpected behavior I'm wondering if this was a deliberate design decision or whether might be changed in the future (or, if say I manage to figure this out by myself, whether a PR that changes it would be welcome).

**Comment by daviskirk** [comment]
I don't know if it's possible to change this, or if there might be a really good reason why we would want to keep it the way it is (forcing us to reapply the "Generic" base class).  If not, I could at least try and look at what is possible.

If it doesn't work, perhaps we can add a nicer error message

**Comment by phdowling** [comment]
This looks relevant:
https://github.com/samuelcolvin/pydantic/blob/619ff261c9bdc2a612ef2fcfa17a005dfefbcf21/pydantic/generics.py#L39
I assume it refers to this line:
https://github.com/samuelcolvin/pydantic/blob/master/pydantic/generics.py#L84

I guess if `Generic[T]` (with the according type vars) were added as a base to the subsequent create_model call whenever there are such typevars still present in the `params` of the __class_getitem__, this should work. I think `create_model` does not accept tuples in its `__base__` parameter though, so that would seem to be the root cause (related old issue: https://github.com/samuelcolvin/pydantic/issues/2029).

So to me it looks like the solution is to either let create_model accept a tuple of BaseModel types, or to change that `create_model` call to somehow create the new type by just using a `type(...)` call (which seems tricky to get right).

**Comment by Kludex** [comment]
`GenericModel` is removed from Pydantic on V2.

**Comment by dmontagu** [comment]
In v2, even though we don't have `GenericModel` and you just use `BaseModel`, it's still the case that you need to add `Generic[<parameters>]` to any subclasses (as noted [here](https://github.com/pydantic/pydantic/issues/2380#issuecomment-782380405)). We are interested to remove the need for this, but when I last tried I couldn't get it to work after a moderate amount of effort.

I believe (not 100% sure though) there is already some issue already for tracking this, so I don't think you need to worry too much about this being forgotten; more likely, the fact that it can be worked around by just re-inheriting from Generic means that it won't be a high enough priority to get fixed given all the other priorities.

A PR fixing this in v2 would definitely be welcome, but I'll just give the warning that this code is pretty nasty and complex, so it may be hard to get it to work without breaking some of the more complex examples.

 inheriting from Generic with all parameters
