### ISSUE TITLE
schema_json does not include $schema version it is supposed to comply with

### ISSUE THREAD

**Issue by ssbarnea** [pydantic/pydantic#2396]
# Bug

The generated schemas do not include any default `$schema` field which is quite dangerous as it gives no indication who can use them.

Which ones are they supposed to respect?

* https://json-schema.org/draft/2020-12/schema
* https://json-schema.org/draft/2019-09/schema
* https://json-schema.org/draft/draft-07/schema

As someone that expect to produce schemas using pydantic, I do need to also indicate the consumers which version of the spec they should expect to use, especially as not all consumers can deal with all versions.

**Comment by tlambert03** [comment]
nearly a year old, would love to know this as well.  Does anyone know off the top of their head what draft is being targeted?

**Comment by tlambert03** [comment]
fwiw, the link in this sentence in the [docs](https://pydantic-docs.helpmanual.io/usage/schema/) currently points to `draft/2020-12`

> The generated schemas are compliant with the specifications: JSON Schema Core, JSON Schema Validation and OpenAPI.

**Comment by michellemay** [comment]
If I may jump in the conversation. We had an issue with schema version as well.  

The generated schema for data classes were used as sub schema inside a larger schema. Validation tools do not allow for mixed versions. Therefore, all schemas must respect one and only one version. 

Using pydantic to generate schema automatically should provide a mechanism to target specific version.

**Comment by dmontagu** [comment]
In V2, we are explicitly targeting `https://json-schema.org/draft/2020-12/schema`. I know that currently it generates something with openapi extensions when discriminators are involved, and we do plan to add support for modifying that behavior.

We designed the JSON schema generation approach to be much easier to modify thanks to the ability to override `GenerateJsonSchema`, so while we don't currently include the schema version by default when generating the schema, it should be straightforward to add it by overriding the `GenerateJsonSchema.generate` method (or similar) as you see fit.
