### ISSUE TITLE
Ability to exclude error type e.g. (type=type_error.integer) from ValidationError message

### ISSUE THREAD

**Issue by polamayster** [pydantic/pydantic#2499]
I think it is possible to extend `ValidationError` class and override `__str__` method, but there is or should be an easier way to customize responses containing ValidationErrors similar way as it is for `msg` with message template.

**Comment by dmontagu** [comment]
If you are still interested in this behavior, could you provide more detail about the current behavior you want to change, and what your desired behavior is?

**Comment by Kludex** [comment]
I'll be closing the issue since it's stale.

Once @polamayster replies, we can reopen it. 🙏
