### ISSUE TITLE
Broken rendering in Schema page

### ISSUE THREAD

**Issue by johnthagen** [pydantic/pydantic#2540]
https://pydantic-docs.helpmanual.io/usage/schema/#field-customisation

The `!!! note` admonition is not rendering properly.

<img width="800" alt="Screen Shot 2021-03-17 at 11 23 21 AM" src="https://user-images.githubusercontent.com/10340167/111493227-bf630c80-8713-11eb-92e3-effed1732986.png">

**Comment by PrettyWood** [comment]
Thanks @johnthagen for reporting! 👍
Quick fix done

**Comment by adriangb** [comment]
Fixed and docs will be rewritten for V2.
