### ISSUE TITLE
String validation error messages should account for instances of one

### ISSUE THREAD

**Issue by alecgerona** [pydantic/pydantic#2548]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.7.3
pydantic compiled: True
install path: /home/alec/Work/cor-xms-api/venv/lib/python3.9/site-packages/pydantic
python version: 3.9.2 (default, Feb 20 2021, 18:40:11)  [GCC 10.2.0]
platform: Linux-5.11.7-arch1-1-x86_64-with-glibc2.33
optional deps. installed: ['email-validator', 'devtools']
```

String error messages, specifically, `AnyStrMinLengthError` and `AnyStrMaxLengthError` has
> 'ensure this value has at most {limit_value} characters'
for their message.

I think it should be
> 'ensure this value has at most {limit_value} character/s'

**Comment by PrettyWood** [comment]
Yep a started was opened https://github.com/samuelcolvin/pydantic/pull/2115 but got closed by author.
PR welcome!

**Comment by alecgerona** [comment]
Great! I'll get right to it.

**Comment by dmontagu** [comment]
Looks like this has been addressed in v2
