### ISSUE TITLE
Type validation issue - Unions and Annotations

### ISSUE THREAD

**Issue by AA-Turner** [pydantic/pydantic#2551]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.1
pydantic compiled: False
install path: <path>\Lib\site-packages\pydantic
python version: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 04:59:43) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.18362-SP0
optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

Hi - thanks for developing pydantic, it is fantastically useful!

Came accross an interesting interaction between `Union` and `Annotated` types which I'm pretty sure isn't meant to happen. If you run the minimal reproducer below, it passes when it should error on the first type. 
```python
from typing import Annotated, Literal, Union

import pydantic


class Fruit(pydantic.BaseModel):
    x: Union[Literal["apples"], Annotated[str, pydantic.Field(regex=r"^oranges.*")]]
    z: Annotated[str, pydantic.Field(regex=r"^oranges.*")]


Fruit(x="blah", z="oranges are nice")
```

I got pretty stuck into the weeds looking for the root cause here, and I think it is the interaction of these two parts here:

`ModelMetaclass.__new__` calls `pydantic.fields.ModelField.infer` on model definition as a class. `ModelField.infer` has a call to `schema.get_annotation_from_field_info`, which turns a type like `Annotated[str, pydantic.Field(regex=r"^oranges.*")]` into `pydantic.types.ConstrainedStrValue`.
https://github.com/samuelcolvin/pydantic/blob/4ec6c5290528c32155d9aea0d996ddbf9e34d776/pydantic/fields.py#L409

However, when a sub-field is created (in `ModelField._type_analysis`), this call doesn't happen.
https://github.com/samuelcolvin/pydantic/blob/4ec6c5290528c32155d9aea0d996ddbf9e34d776/pydantic/fields.py#L547
https://github.com/samuelcolvin/pydantic/blob/4ec6c5290528c32155d9aea0d996ddbf9e34d776/pydantic/fields.py#L631-L653

I'd send a PR, but if I'm honest I'm not sure what *should* happen here - or indeed what the best way of rectifying it is. For now `pydantic.constr` suits me well, but I wanted to update to `Annotated` types for type purity!

Thanks,
Adam

**Comment by PrettyWood** [comment]
Hi @AA-Turner 
When you want to use constraints on fields, you should use `constr` (or other con types).
Adding `regex` in the `Field` part will only add the information in the schema!
Funny enough I just worked on https://github.com/samuelcolvin/pydantic/pull/2553, which may help writing your constraints.
Hope it helps!

**Comment by AA-Turner** [comment]
Thanks @PrettyWood :)

Can I ask, is the intended behaviour that `Field` currently not act as a restrictive type? My confusion came from the fact that in my reproducer above, the `Annotated-Field-regex` (key Z) did raise validation errors, and the same within a `Union` (key X) didn't. 

Are you able to shed any light at all on what the  'correct' behaviour here is please?

**Comment by AA-Turner** [comment]
(Obviosuly you'd have to pass rubbish data to see the error states, e.g. `Fruit(x="blah", z="blah")`)

**Comment by PrettyWood** [comment]
Oops it has been fixed sorry I said something wrong. So yes it's probably a bug I'll have a quick look

**Comment by AA-Turner** [comment]
No worries at all - thanks so much for confirming!

**Comment by PrettyWood** [comment]
I just checked this morning. It will need some refactoring. `Annotated` support has just been added but currently we only support one `Field` for the whole field
Both are equivalent
```py
    z1: Annotated[str, Field(regex=r"^oranges.*")]
    z2: str = Field(regex=r"^oranges.*")
```
But `Union` and other nested types are not.
In the meantime I would recommend to write it like this
```py
class Y(BaseModel):
    __root__: Annotated[str, Field(regex=r"^oranges.*")]

class Fruit(BaseModel):
    x: Union[Literal["apples"], Y]
```
The way you would have written without `Annotated` anyway.
I'll probably work on this if noone does it before!

**Comment by AA-Turner** [comment]
Brill, makes sense. Thanks for the suggestion!

**Comment by davidhewitt** [comment]
I noticed that as well as unions I'd also really love to be able to do this for other containers like list:

```python
Y = Annotated[str, Field(regex=r"^oranges.*")]

class Fruit(BaseModel):
    x: list[Y]
```

I could potentially contribute on this some time, with some pointers on what I might need to change.

**Comment by tkaraouzene** [comment]
Hi everyone, 

First of all thanks for this wondefull library.
I just post here because I have the same issue with ``@validate_arguments`` decorator.

Here an example:

```python
    from pydantic import validate_arguments, Field
    from pydantic.typing import Annotated

    @validate_arguments
    def foo(bar: Union[str, Annotated[int, Field(ge=0, multiple_of=1)]]):

        print("ok")

        return bar
```

**[In]:**
```
    foo(-5)
```
**[Out]**:
```
ok
Out[3]: '-5'
```

**[In]:**
```
    foo([])
```
**[Out]:**
```
pydantic.error_wrappers.ValidationError: 2 validation errors for Foo
bar
  str type expected (type=type_error.str)
bar
  value is not a valid integer (type=type_error.integer)
```

**Comment by Kludex** [comment]
The example in the issue description works as expected on V2.
