### ISSUE TITLE
Cannot construct parameterised type that includes validation

### ISSUE THREAD

**Issue by chilversc** [pydantic/pydantic#2581]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: False
                 install path: /home/chris/projects/external/pydantic/pydantic
               python version: 3.9.2 (default, Mar 24 2021, 22:11:22)  [GCC 9.3.0]
                     platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

# Test Case

```py
@skip_36
def test_construct_parameterized_type_with_validation():
    T = TypeVar('T')

    class Page(GenericModel, Generic[T]):
        page: int = Field(ge=1)
        items: Sequence[T]

    # Check we can perform this assignemnt, this is the actual test
    response_model = Page[str]
    assert response_model.__name__== 'Page[str]'

    # Sanity check the resulting type works as expected
    valid = response_model(page=1, items=[])
    assert valid.page == 1

    with pytest.raises(ValidationError) as exc_info:
        response_model(page=0, items=[])
    assert exc_info.value.errors() == [{'loc': ('__root__', 'page'), 'msg': 'sum too large', 'type': 'value_error'}]
```

# Output
```
E           ValueError: On field "page" the following field constraints are set but not enforced: ge. 
E           For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints

pydantic/schema.py:926: ValueError
```

# Description

I have a generic page type that I use for responses in FastAPI. To detect bugs the invariants of this response type are configured as standard validations such as `page: int = Field(ge=1)`.

The type can be used normally, and will have the correct paramerized type when instantiating it, such as `Page[str](page=1, ...)`.

However, when trying to assign the `Type[Page[str]]` to the `response_model` parameter in FastAPI pydantic throws a `ValueError` with the message "On field "page" the following field constraints are set but not enforced: ge."

```
@app.get("/", response_model=Page[str])
def index():
    return Page(page=1, items=["foo", "bar"])
```

Without the assignment to `response_model` this function will work as intended.

While debugging the pydantic code it seems during the evaluation of the assignment to `response_model`, the type being evaluated `annotation` at `pydantic/schema.py:926` is an instance of type `pydantic.fields.DeferredType`.

**Comment by Nohysiwe** [comment]
##### I have encountered the same bug . 
```python
# python version: python3.7.9
# pydantic version: 1.8.1
from typing import List, TypeVar, Generic
from pydantic import Field
from pydantic.generics import GenericModel

T = TypeVar('T')
class PageDTO(GenericModel, Generic[T]):
    """
        分页列表
    """
    recordList: List[T] = Field(
            [] ,
            title = "page_list"
        )
    count: int = Field(
            ... ,
            title = "总数",
            ge = 0,
        )
if __name__ == "__main__":
    page = PageDTO[str]     
    # Then it will throw an Error.
    # ValueError: On field "count" the following field constraints are set but not enforced: ge
    # Not only PageDTO[ str ] ,but also PageDTO[ <Any> ]
```
##### Yeah, it seems like the `ge = 0` cause this error. But I don't understand the meaning of 'constraints not enforced'.

**Comment by Tim-ONT** [comment]
Hi,

Firstly, thanks for working hard on this library, it works really well and is a huge time saver!! 😄 

I have come across this issue as well! Here is what I think is a minimal example:

```python
# simple_model.py

from typing import Generic, TypeVar
from pydantic import Field
from pydantic.generics import GenericModel

DataT = TypeVar("DataT")

class SimpleModel(GenericModel, Generic[DataT]):
    data: DataT
    # This works with Field(...) but as soon as any constraints are added
    # will fail when the generic is instantiated
    number: int = Field(..., ge=0)
```

then in the console:

```python
>>> from simple_model import SimpleModel
>>> SimpleModel.schema()
{'title': 'SimpleModel', 'type': 'object', 'properties': {'data': {'title': 'Data'}, 'number': {'title': 'Number', 'minimum': 0, 'type': 'integer'}}, 'required': ['number']}
>>> SimpleModel[int].schema()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tguite/dev/calibration/.venv/lib/python3.8/site-packages/pydantic/generics.py", line 85, in __class_getitem__
    create_model(
  File "pydantic/main.py", line 990, in pydantic.main.create_model
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 410, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 927, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "number" the following field constraints are set but not enforced: ge. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

I'm not sure where this bug is coming from but it reduces the utility of generic models.

Please let me know if there is anything else I can do to help with investigating this bug!

Cheers,

Tim

**Comment by MaratBR** [comment]
Ok, first of all: +1 This issue annoys me too.

I don't really know much about pydantic's internal workings so I am just guessing here based on what I found.
I did some debugging on the latest version (1.9.0a2 from the master). It seems like the problem comes from a combination of [`get_annotation_with_constraints`](/samuelcolvin/pydantic/blob/master/pydantic/schema.py#L1021) function and a generic model (or, to be more particular, `DeferredType`).

When this function is called with `DeferredType` as annotation it returns an empty set of used constraints. Later, in `get_annotation_from_field_info` ValueError is raised because none of the constraints were used (since it's `DeferredType`).

Not sure how to fix that though, tried just editing the code to bypass this exception, but it causes some assertions to fail in `validate` method of `BaseModel`.

**Comment by aguckenber-chwy** [comment]
+1

**Comment by parikls** [comment]
+1. Any updates here?

**Comment by nilueps** [comment]
+1 also facing this issue

**Comment by tstorek** [comment]
+1 also came across it now :/

**Comment by samuelcolvin** [comment]
Will probably have to wait for V2 for a fix.

**Comment by tstorek** [comment]
In the meanwhile I use this workaround for my problem. 
Hopefully, that fits the original issue. 
Ugly but it works.
I think it also for CustomTypes. 
It is now somehow I chained validation.

```python 

from pydantic import (
    BaseModel,
    Field,
    BaseConfig
)
from typing import Optional


class Throttle(BaseModel):
    throttling: Optional[int] = Field(
        default=None,
        ge=0,
        strict=True,
        description="Minimal period of time in seconds which "
                    "must elapse between two consecutive notifications. "
                    "It is optional."
    )

    class Config(BaseConfig):
        validate_assignment = True

if __name__ == '__main__':
    throttle = Throttle(throttling=1)
    throttle.throttling = 1
    Throttle(throttling=0.1) #raises
    Throttle(throttling=-1) #raises

```

**Comment by djmango** [comment]
+1

**Comment by KochankovID** [comment]
+1

**Comment by adriangb** [comment]
This is fixed in V2:

```python
from typing import Generic, Sequence, TypeVar

from pydantic import BaseModel, Field

T = TypeVar('T')

class Page(BaseModel, Generic[T]):
    page: int = Field(ge=1)
    items: Sequence[T]

# Check we can perform this assignment, this is the actual test
response_model = Page[str]
assert response_model.__name__== 'Page[str]'

# Sanity check the resulting type works as expected
valid = response_model(page=1, items=[])
assert valid.page == 1

response_model(page=0, items=[])
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Page[str]
page
  Input should be greater than or equal to 1 [type=greater_than_equal, input_value=0, input_type=int]
"""
```

With no warnings.

If there is something FastAPI need to do they'll do they upgrade to Pydantic V2.
