### ISSUE TITLE
Parameterised `typing.Pattern[str]` field annotation fails

### ISSUE THREAD

**Issue by smithfred** [pydantic/pydantic#2636]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c 'import pydantic.utils; print(pydantic.utils.version_info())'
             pydantic version: 1.7.3
            pydantic compiled: False
                 install path: /usr/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Feb 20 2021, 00:00:00)  [GCC 11.0.0 20210210 (Red Hat 11.0.0-0)]
                     platform: Linux-5.11.10-300.fc34.x86_64-x86_64-with-glibc2.33
     optional deps. installed: ['email-validator']

```

## Reproducer

```py
import pydantic, typing
class Foo(pydantic.BaseModel):
     foo: typing.Pattern[str]
```

## Result

``` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/pydantic/main.py", line 262, in __new__
    fields[ann_name] = inferred = ModelField.infer(
  File "/usr/lib/python3.9/site-packages/pydantic/fields.py", line 315, in infer
    return cls(
  File "/usr/lib/python3.9/site-packages/pydantic/fields.py", line 284, in __init__
    self.prepare()
  File "/usr/lib/python3.9/site-packages/pydantic/fields.py", line 356, in prepare
    self._type_analysis()
  File "/usr/lib/python3.9/site-packages/pydantic/fields.py", line 510, in _type_analysis
    raise TypeError(f'Fields of type "{origin}" are not supported.')
TypeError: Fields of type "<class 're.Pattern'>" are not supported.
```

## Additional info

* The reproducer works if instead the unparameterised `typing.Pattern` generic is substituted, however the modified version fails static type checking with e.g. Mypy, as expected:

```bash
error: Missing type parameters for generic type "Pattern"  [type-arg]
```

**Comment by kkirsche** [comment]
This also occurs with `re.Pattern` which seems to be replacing the typing version of these.

https://docs.python.org/3/library/typing.html#typing.Pattern

The aliases `re.Match` and `typing.Match` also fail.

**Comment by ciaranevans** [comment]
Having the same issue:

```python
import typing

pattern: typing.Pattern[str]
```

```
TypeError: Fields of type "<class 're.Pattern'>" are not supported.
```

If I don't use `Pattern[str]` and instead use `Pattern`, `mypy` will moan about:
```
error: Missing type parameters for generic type "Pattern"
```

**Comment by Cielquan** [comment]
This is still the case. Have the same issue on 1.9.

**Comment by vvadik** [comment]
Error still appears in python 3.10 and pydantic = "^1.10.2"

**Comment by samuelcolvin** [comment]
This is fixed on main and will be included in V2, you can try it now on the alpha release.
