### ISSUE TITLE
Cannot import pydantic when typing.TYPE_CHECKING is True

### ISSUE THREAD

**Issue by utf** [pydantic/pydantic#2645]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Importing pydantic fails when `typing.TYPE_CHECKING` is set to True. Tested in a clean conda env using Python 3.8.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /Users/alex/miniconda3/envs/pydantic/lib/python3.8/site-packages/pydantic
               python version: 3.8.8 (default, Feb 24 2021, 13:46:16)  [Clang 10.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
>>> import typing
>>> typing.TYPE_CHECKING = True
>>> import pydantic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 3, in init pydantic.dataclasses
    import copy
  File "pydantic/class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic/errors.py", line 5, in init pydantic.errors
  File "pydantic/typing.py", line 181, in init pydantic.typing
    tvars.append(t)
  File "pydantic/fields.py", line 27, in init pydantic.fields
ImportError: cannot import name errors
```

**Comment by jie8357IOII** [comment]
I guess you have the python package with `typing.py` locally, pydantic would try to load non-existing TYPE_CHECKING from your local first.

**Comment by adriangb** [comment]
What's the real use case here? As far as I know `typing.TYPE_CHECKING` is supposed always be False at runtime and you wouldn't expected code guarded by it to be actually runnable. For example you can have circular imports within `typing.TYPE_CHECKING` blocks (not saying it's a good thing, but it's allowed and common use of `typing.TYPE_CHECKING`) so if you tried to run that code it would fail.

Since this is not supposed to work in the first place I'm going to close the issue. If you can present a compelling real world use case we'll be happy to re-visit.

**Comment by dantownsend** [comment]
The use case is avoiding unnecessary imports if you just want something for type annotation purposes.

```python
from __future__ import annotations
import typing
if typing.TYPE_CHECKING:
    from pydantic import BaseModel

def my_func(model: BaseModel):
    ...
```

It's not the end of the world - can just import pydantic outside of the `if` block. It's just strange it doesn't work.

**Comment by dantownsend** [comment]
>  Right but your example runs fine if you put it in a main.py file and do python run main.py because the code inside of if typing.TYPE_CHECKING is not actually being executed.

I think I was running a linter or something - honestly can't remember as it was 1.5 years ago. Maybe the original poster can provide more context.
