### ISSUE TITLE
inconsistent values with default values and use_enum_values

### ISSUE THREAD

**Issue by tharwan** [pydantic/pydantic#2708]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

When creating a model that uses Enums and use_enum_values in the Config there are inconsistent values in the property if the default value is given as an Enum. In that case the property will return the Enum but not the value. However if the Enum is passed in during initialization the property will correctly(?) return the string value.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
                 install path: /home/fkuehnlenz/e2m.prometheus.tradingapp/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar  9 2021, 09:41:19)  [GCC 9.3.0]
                     platform: Linux-5.4.0-71-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

```

```py
from pydantic import BaseModel
from enum import Enum


class Resolution(Enum):
    qh = "15min"
    h = "1h"

class Config(BaseModel):
    resolution: Resolution = Resolution.qh
    other: str = "foo"
    class Config:
        use_enum_values = True

assert Config(resolution = "15min").resolution == "15min"
assert Config(resolution = Resolution.qh).resolution == "15min"

# this fails as expected
# assert Config(resolution = "15min").resolution == Resolution.qh

# this fails unexpected
assert Config().resolution == "15min"
```

**Comment by PrettyWood** [comment]
Hi @tharwan 
You can add `Config.validate_all = True` to trigger validation on default value and hence activate `use_enum_values` for it.
By default default values are just passed _as is_
