### ISSUE TITLE
`BaseModel` runtime-warns about private class vars from an arbitrary type annotation

### ISSUE THREAD

**Issue by goodboy** [pydantic/pydantic#2816]
I tried to find something similar to this in the issue set but figured it was worth a new one:

This code triggers an odd `RuntimeWarning` at import time:

```python
from dataclasses import dataclass

from pydantic import BaseModel


@dataclass
class C:
    _private: str = 'yo'


class D(BaseModel):
    c: C = None
    
    class Config:
        arbitrary_types_allowed = True
        validate_all = False
        keep_untouched = (C,)
        underscore_attrs_are_private = False

```
running this code gives:
```
[nav] In [9]: run snippets/pydantic_warning.py
/home/goodboy/repos/piker/snippets/pydantic_warning.py:11: RuntimeWarning: fields may not start with an underscore, ignoring "_private"
  class D(BaseModel):
```
It doesn't seem to matter what `Config` settings I use; the warning stays.

For me this was quite odd since in my real use case, my annotation type was from another lib using a plain stdlib `@dataclass` and `pydantic` was reporting it as though those attrs were local to the class `D` here; so I was pretty confused tracking down the source. If I convert `c` -> `_c` the warning doesn't show up.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
(3.9)  >>> python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/goodboy/repos/piker/3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, May 12 2021, 17:14:51)  [GCC 10.2.0]
                     platform: Linux-5.12.4-arch1-2-x86_64-with-glibc2.33
     optional deps. installed: ['typing-extensions']
```

Hopefully this isn't just noise 😂

**Comment by PrettyWood** [comment]
Hi @goodboy and thanks for reporting.
Yes it's actually "normal" because when you use a stdlib `dataclass` inside a `BaseModel`, _pydantic_ will convert you stdlib `dataclass` into a _pydantic_ `dataclass` to validate (and coerce if needed) input data.
Behind the scenes it creates a `BaseModel` based on your stdlib `dataclass` and will raise a `RunWarning` at this moment.

**Comment by goodboy** [comment]
@PrettyWood cool.

So the right way to mask this warning is to make the attr private then or does this mean you have to leak `pydantic` config stuff to stdlib dataclasses as a user?

**Comment by PrettyWood** [comment]
Honestly we should probably just remove this warning since creating a new class that inherits from `BaseModel` does not raise anything but using `create_model` does

**Comment by alex-klepa** [comment]
+1 to remove the warning

**Comment by rysuds** [comment]
Currently hitting this as well! Do ya'll know of a clean way to suppress this message in the short term?

**Comment by mnemio** [comment]
I am still getting this warning in dataclasses with the latest GA pydantic version,  1.10.7.  Is that last merge still pending a release?

**Comment by mnemio** [comment]
> Have you tried the alpha release of v2?

Ah, not yet. I ran into other issues trying that. I will see if I can resolve them in my dependent code.
