### ISSUE TITLE
Mypy: unexpected behavior with orm_mode and classmethods

### ISSUE THREAD

**Issue by tammoippen** [pydantic/pydantic#2819]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/tammo/unbind/monorepo/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Mar 15 2021, 12:27:27)  [GCC 9.3.0]
                     platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']

❯ mypy --version
mypy 0.812
```

```py
from typing import Optional

import pydantic as pyd


class DBModel:
    id: str
    name: Optional[str]


class Model(pyd.BaseModel):
    id: str
    name: Optional[str]
    something: Optional[str] = None

    class Config:
        orm_mode = True

    @classmethod
    def from_db(cls, model: DBModel) -> "Model":
        result = cls.from_orm(model)
        result.something = "assign something here"
        return result

```

When running mypy I get the following error:

```sh
❯ mypy issue.py
issue.py:21: error: The pydantic mypy plugin ran into unexpected behavior: ctx.type: Type[issue.Model] (of type TypeType)
Please consider reporting this bug at https://github.com/samuelcolvin/pydantic/issues/new/choose so we can try to fix it!
Found 1 error in 1 file (checked 1 source file)
```

Workarounds: 

- Removing the `orm_mode = True` and manually creating `result` fixes the mypy issue.
- using `result = Model.from_orm(model)` fixes the issue

**Comment by hramezani** [comment]
`orm_mode` is removed from V2

**Comment by dmontagu** [comment]
(For a bit of additional context — you'll now set `from_attributes = True` in the config, instead of `orm_mode = True`, and then you'll be able to just call `cls.model_validate(model)` and it will do the right thing. If you run into more mypy plugin issues after making this change, please let us know.)
