### ISSUE TITLE
Unexpected behavior when configuring settings with .env file and nested settings with settings class inheritance

### ISSUE THREAD

**Issue by jwhite3** [pydantic/pydantic#2836]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.1
            pydantic compiled: True
               python version: 3.8.8 (default, Mar 19 2021, 16:09:34)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

Hello! I'm really enjoying this package, but I've encountered some unexpected behavior that I haven't been able to find a solution for. 

Say I have a model structure like so:
```py
import pydantic

class OtherSettings(pydantic.BaseModel):
    apple: str = 'Fiji'
    banana: str = 'yum'


class Settings(pydantic.BaseSettings):
    env: str = pydantic.Field(..., env='my_env')
    other: OtherSettings = OtherSettings()


class SpecificEnvironmentSettings(Settings):
    other: OtherSettings = OtherSettings(apple='Gala')

    class Config:
        env_prefix = 'my_'
        env_file = '/path/to/.env'


def settings_factory():
    if Settings().ENVIRONMENT == 'specific':
        return SpecificEnvironmentSettings()


SETTINGS = settings_factory()
...
```
There are cases where I'd like to set a field in `OtherSettings` via the `.env` file. However, I've found that when I attempt to set a single field in the `.env`, I get the wrong default values of the other fields. In this example, if I have in my `.env`: 
```
my_other='{"banana":"gross"}'
```
And I trigger the use of the `SpecificEnvironmentSettings` class, instead of the expected `apple='Gala'`, I get the "original" default value of `apple='Fiji'`.

**Comment by jwhite3** [comment]
I should note that an obvious way around this would be to implement more "flattened" settings classes, but I'm hoping to avoid that if I can. We're fans of being able to implement modular settings "sections"

**Comment by jwhite3** [comment]
I've found that I can actually get this to work if I do the following: 

Instead of defining subclasses of the base `Settings` class:
```python
...  # Following the example above

def settings_factory():
    if Settings().ENVIRONMENT == 'specific':
        return SpecificEnvironmentSettings(other=dict(apple='Gala'))

...
```
Specifically, the merging is successful if I use init variables that are _specifically dictionaries_ rather than overriding the nested "sections". I would imagine that it should also work with an instance of `OtherSettings` too, but it doesn't.

**Comment by hramezani** [comment]
I think it's the expected behavior. because when you set the `my_other='{"banana":"gross"}'` environment variable, you are overriding the default value of the `other` field in the `SpecificEnvironmentSettings` model and set it to `OtherSettings(banana='gross')` and as you didn't provide the default value for `apple` it uses the `Fiji` which is the default value
