### ISSUE TITLE
Catch and raise on ignored pydantic data set in Annotated[]

### ISSUE THREAD

**Issue by tuukkamustonen** [pydantic/pydantic#2862]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

`Annotated` usage is described at https://pydantic-docs.helpmanual.io/usage/schema/#typingannotated-fields. The docs only mention `Annotated[str, Field()]` pattern as an example.

However, if user attempts to add the constrained types.

```py
from typing_extensions import Annotated
from pydantic import StrictStr, BaseModel, constr

class Model(BaseModel):
    field1: Annotated[str, constr(strict=True)]
    field2: Annotated[str, constr(min_length=1)]
    field3: Annotated[str, StrictStr]

m = Model(
    field1=111
    field2='',
    field3=333,
)
```

If you run this, it passes without errors.

I do understand this invalid use of `pydantic` as `constr()` and `StrictStr` are intended as types (with built-in validation) and not merely as validators. However, the problem is above passes silently.

While it's completely legal to attach whatever data via `Annotated`, could `pydantic` attempt to prevent above cases, ie. where user is attaching pydantic-specific information, clearly intended for validation, but it gets simply ignored here?

Alternative: Could above made work? So that validation+strictness would be taken from `constr()` and type as the first element of `Annotated[str, constr(strict=True, min_length=1)]`? (This would allow using `constr()` in a `mypy`-compatible way until v2 lands and perhaps moves validation out of the type classes.)

#  Env

```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/musttu/.pyenv/versions/3.7.10/envs/famp/lib/python3.7/site-packages/pydantic
               python version: 3.7.10 (default, Mar 19 2021, 13:17:32)  [GCC 9.3.0]
                     platform: Linux-5.8.0-53-generic-x86_64-with-debian-bullseye-sid
     optional deps. installed: ['typing-extensions']
```

**Comment by Jaakkonen** [comment]
It looks like the argument passed in the `Annotated[T, V]` is treated type `T` with value `V` if `V` is of type `FieldInfo`.
The `Annotated` goes to [fields.py:553](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/fields.py#L553) where the type is replaced by its first argument. The value for the `ModelField` is got from `_get_field_info` and the existing `Field` is used at [fields.py:406](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/fields.py#L406) if there's one.

The support for `constr` as Annotated argument could be hacked in by making `_get_field_info` return `Optional[Type]` (in addition to other returns) if there's a `ConstrainedStr`/etc argument and use it in the `ModelField.infer` classmethod. This way the recursive `_type_analysis` call in `origin is Annotated` branch would go to the branch `hasattr(origin, '__get_validators__')` [fields.py:647](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/fields.py#L647) and a validator would be added to the model.

I couldn't find a way to implement `StrictStr` behavior but for the min/max length you can do:
```py
from typing import Annotated
from pydantic import BaseModel, Field

class Model(BaseModel):
    field2: Annotated[str, Field(min_length=1,)]

m = Model(
    field2='',
)  # ValidationError
```

**Comment by dmontagu** [comment]
I think it would be difficult to implement something that warns if you use types as annotations in general, since anything could occur as an annotation for the sake of integration with another library.

If there is broad consensus, we could perhaps add checks for common mistakes when analyzing a type and iterating through the annotations, but for various reasons I think it's best if we don't attempt to introspect annotations too deeply if they aren't explicitly recognized as something we know how to handle.

As a result, I'm going to close this issue for now, but if you think it should be re-opened feel free to request that.
