### ISSUE TITLE
Flake8 raises "syntax error in forward annotation" on regex constraints

### ISSUE THREAD

**Issue by jceresini** [pydantic/pydantic#2872]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/jceresini/repos/boarding/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, May 21 2021, 16:03:03)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-11.2.3-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Simplified example

This is actually taken from docs here: https://pydantic-docs.helpmanual.io/usage/types/#constrained-types
I removed anything that wasn't necessary to demonstrate the issue

```py
from pydantic import BaseModel, constr


class Model(BaseModel):
    regex_str: constr(regex=r'^apple (pie|tart|sandwich)$')
```

### Package versions 
```
$ pip freeze
flake8==3.9.2
mccabe==0.6.1
pycodestyle==2.7.0
pydantic==1.8.2
pyflakes==2.3.1
typing-extensions==3.10.0.0
```

### The error I'm seeing when running flake8
```
$ python -m flake8 foo.py
foo.py:5:29: F722 syntax error in forward annotation '^apple (pie|tart|sandwich)$'
```

I saw this was reported on pyflakes, but they closed it, and honestly I don't understand enough to know which side it should be fixed on: https://github.com/PyCQA/pyflakes/issues/542

In case you're interested in the use case, we have pipelines that deploy our code that halt immediately on anything flake8 considers a `syntax error`.

**Comment by jceresini** [comment]
FWIW the actual flake8 invocation in our pipelines was stolen from here: https://docs.github.com/en/actions/guides/building-and-testing-python. It looks like this

```
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
```

**Comment by nlnjnj** [comment]
`    effective_duration: dict[
        constr(max_length=64, regex=r'task_[a-z_]{4,32}_[0-9]{1,2}'), conint(gt=0)
    ] = Field(`

`F722 syntax error in forward annotation 'task_[a-z_]{4,32}_[0-9]{1,2}'`

Got the same issue.
