### ISSUE TITLE
Cannot define numpy ndarray field with default value

### ISSUE THREAD

**Issue by alixdamman** [pydantic/pydantic#2923]
Hello,

I'm facing an error message thrown by the `smart_deepcopy` function (from `pydantic/utils.py`) when I try to create a model with a numpy ndarray field with a default value.

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.7.1
pydantic compiled: False
install path: C:\Users\(...)\Miniconda3\Lib\site-packages\pydantic
python version: 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19042-SP0
optional deps. installed: ['typing-extensions']
```

Code:
```py
import pydantic
import numpy as np

class Test(pydantic.BaseModel):
    class Config:
        arbitrary_types_allowed = True

    arr = np.full([2, 2], fill_value=5)
```

Output:
```
Traceback (most recent call last):
  File "C:\Users\(...)\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-3eada7552069>", line 1, in <module>
    class Test(pydantic.BaseModel):
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\main.py", line 285, in __new__
    inferred = ModelField.infer(
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\fields.py", line 315, in infer
    return cls(
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\fields.py", line 284, in __init__
    self.prepare()
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\fields.py", line 350, in prepare
    self._set_default_and_type()
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\fields.py", line 379, in _set_default_and_type
    default_value = self.get_default()
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\fields.py", line 287, in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
  File "C:\Users\(...)\Miniconda3\lib\site-packages\pydantic\utils.py", line 621, in smart_deepcopy
    elif not obj and obj_type in BUILTIN_COLLECTIONS:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Note: I also tried with a more recent version of pydantic: 1.8.3 but got the same problem.

The workaround I use for now is to simply return the version 1.5 of pydantic.

**Comment by aeisenbarth** [comment]
The branch which contains the `not obj` check is only executed for mutable types without default factory. You can work around it by providing a default factory that generates the default value. (Therefore a type annotation is needed.)

```
import pydantic
import numpy as np

class Test(pydantic.BaseModel):
    class Config:
        arbitrary_types_allowed = True

    arr: np.ndarray = pydantic.Field(default_factory=lambda: np.full([2, 2], fill_value=5))
```

**Comment by lex-quarkie** [comment]
Same situation for me.

values = np.arange(1, 5.5, 0.5) is throwing error:

pydantic/main.py:299: in pydantic.main.ModelMetaclass.__new__
    ???
pydantic/fields.py:411: in pydantic.fields.ModelField.infer
    ???
pydantic/fields.py:342: in pydantic.fields.ModelField.__init__
    ???
pydantic/fields.py:445: in pydantic.fields.ModelField.prepare
    ???
pydantic/fields.py:473: in pydantic.fields.ModelField._set_default_and_type
    ???
pydantic/fields.py:345: in pydantic.fields.ModelField.get_default
    ???
pydantic/utils.py:627: in pydantic.utils.smart_deepcopy
    ???
E   ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by Holt59** [comment]
> The branch which contains the `not obj` check is only executed for mutable types without default factory. You can work around it by providing a default factory that generates the default value. (Therefore a type annotation is needed.)
> 
> ```
> import pydantic
> import numpy as np
> 
> class Test(pydantic.BaseModel):
>     class Config:
>         arbitrary_types_allowed = True
> 
>     arr: np.ndarray = pydantic.Field(default_factory=lambda: np.full([2, 2], fill_value=5))
> ```

I have the same issues with frozen model and a default factory, so that might not be True anymore... It's actually pretty hard to know which field raise these errors (in my case these are warnings from `astropy`).

**Comment by dmontagu** [comment]
I think it would be nice to have better error-handling in this situation, but using `default_factory` is definitely the right way to handle the setting of a default value of anything mutable (such as a numpy array) on a pydantic model.

**Comment by dmontagu** [comment]
The issue creating the type seems to be resolved in v2, so I'm going to close this issue:

```python
import pydantic
import numpy as np


class Test(pydantic.BaseModel):
    class Config:
        arbitrary_types_allowed = True

    arr: np.ndarray = np.full([2, 2], fill_value=5)

print(Test())
"""
arr=array([[5, 5],
       [5, 5]])
"""
```

I will note that I think it may be a good idea for us to provide better integration with `numpy` by default (i.e., not requiring arbitrary_types_allowed; it may be possible to accomplish this in some convenient way with the `__array__` method or similar, depending on how "standardized" this behavior is), but I think a separate issue should be created for that.

(A third-party package for this, or `pydantic-extra-types`, may also be preferable instead.)

**Comment by Kludex** [comment]
- Follow https://github.com/pydantic/pydantic-extra-types/issues/31 for `numpy` support on `pydantic-extra-types`.
