### ISSUE TITLE
Data loss when parsing Union types

### ISSUE THREAD

**Issue by blazing-gig** [pydantic/pydantic#2941]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /Users/I0847/personal/pydantic/pydantic
               python version: 3.9.0 (default, Dec 31 2020, 18:45:56)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

## Case 1:

There seems to be a problem parsing `typing.Union` types for recursive models. Consider the following code:

```py
from pydantic import BaseModel

class A(BaseModel):
    a: Optional[str]

class B(BaseModel):
    b: Union[A, Dict[str, str]]

n = B(b={"sdf": "sss"})
print(n.dict())
```
The response is:
```
{'b': {'a': None}}
```

The expected response is:
```
{'b': {"sdf": "sss"}}
```

## Case 2:

However, I found that the above problem didn't occur if the `class B` mentioned above is changed to the following:

```py
...
class B(BaseModel):
    b: Union[A, str]
```

## Case 3:

When tinkering around with the `orm_mode` property, I stumbled upon the same issue. But this time, the error occurs for both the above mentioned cases:

```py
class PetCls:
    def __init__(self, name: str = None, species: str = None):
        self.name = name
        self.species = species

class PersonCls:
    def __init__(
            self, *, name: str, age: float = None,
            pets: Union[PetCls, str]
    ):
        self.name = name
        self.age = age
        self.pets = pets


class Pet(BaseModel):
    name: Optional[str]
    species: Optional[str]

    class Config:
        orm_mode = True

class Person(BaseModel):
    name: str
    age: float = None
    pets: Union[Pet, str]
    # pets: Union[Pet, Dict[str, str]] <---- This would fail as well

    class Config:
        orm_mode = True

anna = PersonCls(
    name='Anna', age=20, pets="hello",
)

anna_model = Person.from_orm(anna)
print(anna_model.dict())

```
Actual response:
```
{'age': 20.0,
 'lala': {'name': 'gili', 'species': 'puppy'},
 'name': 'Anna',
 'pets': {'name': None, 'species': None}}
```

Expected response:
```
{'age': 20.0,
 'lala': {'name': 'gili', 'species': 'puppy'},
 'name': 'Anna',
 'pets': 'hello'}
```
-------

After looking into the source code, I found that the issue seems to be with handling of `Union` types. Rearranging [these lines](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/main.py#L739-L753) could get rid of the `Case 2` for the `from_orm` method. But Case 1 still exists. 

Further tracing led me to the [_validate_singleton](https://github.com/samuelcolvin/pydantic/blob/a4cb4ee3bc57911a18b13643c44ab14e2ea28d33/pydantic/fields.py#L922) method which gets called while handling `Union` fields. Currently the method iterates over `sub_fields` and calls validate on them with the provided value. The problem is that even if there's a type mismatch between the value and the field, the parsing could succeed without any errors.

Would it be possible to first find out which field in the list of `sub_fields` should handle that particular value based on type comparison and then call that field's `validate` method ? This might be a bit costly but I think it has to be done. Also, I believe that the `Union` type could have a shape of its own and handled in a separate handler function as compared to doing it in the `_validate_singleton` method.

I'd like to know the community's thoughts behind this. If we could agree on a solution, I could submit a PR for the same. 

Also, if this is fixed, I could submit a PR for another [feature](https://github.com/samuelcolvin/pydantic/discussions/2846) that I've been working on.

**Comment by PrettyWood** [comment]
Hi @blazing-gig 
It's a very well known issue that is partially solved by https://github.com/samuelcolvin/pydantic/pull/2092
We'll go even further once dict validation will be stricter but this will have to wait for v2

**Comment by blazing-gig** [comment]
Hey @PrettyWood ,

Thanks for the update. The PR seems to do pretty much what I had in mind and seems convincing. Any idea why it's still not merged ? This seems to be a pretty important fix.

**Comment by hramezani** [comment]
The first example of the issue is working as expected in V2.
Also, `orm_mode` is removed in V2
