### ISSUE TITLE
Docstring of multiline Field description is not well formatted

### ISSUE THREAD

**Issue by tkaraouzene** [pydantic/pydantic#2947]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
python version: 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

# Bug
Hi every one and thanks for this library 👏 . 
Here an example of class ``Field`` with a multi line description:

```python
from pydantic import BaseModel

class Foo(BaseModel):

    bar: float = Field(description="Short explanation.\n\n"
    "* If > 0: bla bla\n"
    "* If < 0: bla bla\n"
    "* If == 0: bla bla\n")
```

The generated openAPI seems correct:
 
![image](https://user-images.githubusercontent.com/20064077/123788386-39db2500-d8dc-11eb-8ac1-39f0ddb745ba.png)

However the generated doctring (``Sphinx==3.5.4``) has format glitchs: 
![image](https://user-images.githubusercontent.com/20064077/123788600-7eff5700-d8dc-11eb-827a-5a5b8eac0cd0.png)

**Comment by Paul-AUB** [comment]
I'm also interrested in this bug fix !

**Comment by dcoulomb** [comment]
Following

**Comment by PrettyWood** [comment]
How is it related to pydantic and not sphinx?

**Comment by tkaraouzene** [comment]
Ok my bad, my explanation was very bad...

the way I use to write the documentation of a ``BaseModel`` ``Field`` was as following:

```python
class Foo(BaseModel):

    bar: float
    """Short explanation.
    
    * If > 0: bla bla
    * If < 0: bla bla
    * If == 0: bla bla
    """
```
This way is "pythonic" and is working well with ``sphinx``. 
However, this documentation is not caught within the json schema.

My need is: would it be possible for ``pydantic`` to automatically put this documentation within the ``Field`` description. 

(The thing I discussed above was a workaround, sorry if I was confusing)

Tell me if I'm not clear.

Thanks

**Comment by darasg** [comment]
Also interested !

**Comment by rattrayalex** [comment]
Just to be explicit, I would love to see this format work for `description`s in general, even separate from newlines:

```py
class Foo(BaseModel):

    bar: float
    """Short explanation."""

    # instead of:
    foo: float = Field(description="Short description.")
```

Is that possible? Should I open it as a separate issue?

**Comment by maxmorlocke** [comment]
I've found `</br>' to work effectively at the end of each line when using pydantic in combination with django ninja.

**Comment by samuelcolvin** [comment]
Replacing with #5656 since that seems like a clearer description of the feature request.
