### ISSUE TITLE
Creating by assignment model.Config.extra overwrites model.__config__.extra

### ISSUE THREAD

**Issue by MajorDallas** [pydantic/pydantic#2952]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

If the `Config` class doesn't initially define `extra` and it's assigned later, the model's `__config__.extra` attribute gets overridden. If `"ignore"` is assigned to `extra` in this way, the model will behave as if `extra` is set to `"forbid"`.

I'll state upfront that I doubt this would be an issue in production code (at least, I can't think of why you would need to do this). I discovered this in an ipython session while exploring the config options.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
#  python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /usr/local/lib/python3.8/site-packages/pydantic
               python version: 3.8.3 (default, Jun  9 2020, 17:39:39)  [GCC 8.3.0]
                     platform: Linux-4.19.121-linuxkit-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel

from typing import Optional

class A(BaseModel):
   foo: Optional[str]
    class Config:
        extra = "ignore"

A.__config__.extra
# Out[50]: <Extra.ignore: 'ignore'>

A.Config.extra
# Out[51]: 'ignore'

class F(BaseModel):
    foo: Optional[str]
    class Config:
        pass

F.__config__.extra
# Out[57]: <Extra.ignore: 'ignore'>

F.Config.extra
# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# <ipython-input-58-5a2b9a84b43d> in <module>
# ----> 1 F.Config.extra
# 
# AttributeError: type object 'Config' has no attribute 'extra'

F.Config.extra = "ignore"

F.Config.extra
# Out[60]: 'ignore'

F.__config__.extra
# Out[61]: 'ignore'     # !!!

A(**{"bar": 1})
# Out[64]: A(foo=None)

F(**{"bar": 1})
# ---------------------------------------------------------------------------
# ValidationError                           Traceback (most recent call last)
# <ipython-input-65-cb6a95a41f70> in <module>
# ----> 1 F(**{"bar": 1})
# 
# /usr/local/lib/python3.8/site-packages/pydantic/main.cpython-38-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()
#
# ValidationError: 1 validation error for F
# bar
#   extra fields not permitted (type=value_error.extra)
```

**Comment by lig** [comment]
@MajorDallas thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
