### ISSUE TITLE
Type validation is not performed when a @root_validator is used (in a 3 model hierarchy where the @root_validator is in the middle model)

### ISSUE THREAD

**Issue by gregsifr** [pydantic/pydantic#2967]
# Bug
Type validation is completely skipped when an empty `@root_validator(pre=True)` is used in the below example.
If the root validator decorator and function is removed, the validation is applied correctly. 

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /opt/conda/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32)  [GCC 9.3.0]
                     platform: Linux-5.11.0-22-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']

```

```py
from enum import Enum
from pydantic import BaseModel, root_validator

class Bucket(str, Enum):
    b1: str = "1"
    b2: str = "2"
    b3: str = "3"
    b4: str = "4"
    b5: str = "5"


class BucketRange(BaseModel):
    minimum: Bucket
    maximum: Bucket
        
    @root_validator(pre=True)
    def validate(cls, values):
        # want to use the root_validator to assert int(minimum) <= int(maximum)
        return values


class Results(BaseModel):
    values: BucketRange    


# The below does not raise any errors
Results(values=dict(minimum='1', maximum='I CAN TYPE WHATEVER I WANT IN HERE AND IT PASSES'))
...
```

**Comment by duf59** [comment]
I am hitting a similar issue, need to use a `root_validator` in a submodel.
The above script still does not raise an error with `pydantic==1.10.2`.
`pre` and `skip_on_failure` values do not change the behaviour.

@gregsifr did you find a workaround?

**Comment by samuelcolvin** [comment]
This is because you've called your root validator `validate` which is overwriting the `validate` method on the model.

In V2, methods like this will become private and thereby much harder to accidentally overwrite.

**Comment by duf59** [comment]
Wow, thanks a lot! I would never have figured this one out!
