### ISSUE TITLE
add built-in support for custom ORM/Pydantic mapping (including mapping Pydantic attributes to 'nested' attributes of underlying ORM object)

### ISSUE THREAD

**Issue by scd75** [pydantic/pydantic#3007]
### Discussed in https://github.com/samuelcolvin/pydantic/discussions/2680

<div type='discussions-op-text'>

<sup>Originally posted by **scd75** April 17, 2021</sup>
I started using Pydantic and find the library super rich and well-designed. So first, Thanks for that!

I use it in the context of FastAPI (@tiangolo) , and have a DB which I manage through SQLAlchemey ORM. I constructed separately my models on DB side (for handling DB I/O), and my models on Pydantic side (for serialization).
I understand there have been many discussions around bridging the gap between the 2 frameworks, but this is not my exact point here.
When I return a DB entry through a pydantic model (thanks to FastAPI's 'response_model', I would like some attributes from my DB object's related entries (eg relationships) to be directly mapped as attributes of my pydantic model.
Example:
```
# SQLAlchemy models:

class Parent(Base):
    __tablename__ = "parent"

    id = Column(Integer, primary_key=True)
    reference = Column(String(20), nullable=False, unique=True)
    name = Column(String)

    childs= relationship("Child", back_populates="childs")

class Child(Base):
    __tablename__ = "child"

    id = Column(Integer, primary_key=True)
    parent_id = Column(Integer, ForeignKey("parent.id"))
    reference = Column(String(20), nullable=False, unique=True)
    name = Column(String)

    parent = relationship("Parent", back_populates="parent")



# Pydantic models

class ChildPydantic(BaseModel):
    reference: str
    name: Optional[str] = None
    parent_reference: str

    class Config:
        orm_mode = True


class ParentPydantic(BaseModel):
    reference: str
    name: Optional[str] = None
    childs: Optional[List[ChildPydantic]] = []

    class Config:
        orm_mode = True

```
Say I get some instance 'my_child' of Child class (on ORM side then), I would like to map the attribute 'parent_reference' from ChildPydantic class to my_child.parent.reference attribute.
I do not want to return the whole structure "Parent" in my Pydantic-serialized response.

I played first with validators, then ended up implementing a custom GetterDict as follows:
```
def get_custom_mapper(mapping: dict):

    def rgetattr(obj, attr, *args):
        def _getattr(obj, attr):
            return getattr(obj, attr, *args)
        return functools.reduce(_getattr, [obj] + attr.split('.'))

    class CustomGetterDict(GetterDict):
    
        def __getitem__(self, key: str) -> Any:
            if key in mapping:
                try:
                    return rgetattr(self._obj, mapping[key])
                except AttributeError as e:
                    raise KeyError(key) from e
            try:
                return getattr(self._obj, key)
            except AttributeError as e:
                raise KeyError(key) from e

        def get(self, key: Any, default: Any = None) -> Any:
            if key in mapping:
                return rgetattr(self._obj, mapping[key], default)
            return getattr(self._obj, key, default)

    return CustomGetterDict
```

And use it like that:

```
class ChildPydantic(BaseModel):
    reference: str
    name: Optional[str] = None
    parent_reference: str

    class Config:
        orm_mode = True
        getter_dict = get_custom_mapper(mapping={
            'parent_reference': 'parent.reference',
        })

```
That works great, but maybe it would be a good idea to "robustify" the solution, and add it as a built-in feature.
Thanks!

</div>

**Comment by scd75** [comment]
Bringing up this topic again. The solution described above does not allow for type validation / parsing on nested attributes. Would be great to have a robust built-in method for this problem

Thanks!

**Comment by sydney-runkle** [comment]
It seems like [SQLModel](https://sqlmodel.tiangolo.com/) suit this use case quite well. I agree that this is important gap to bridge!
