### ISSUE TITLE
Json field with generics not parsed as expected

### ISSUE THREAD

**Issue by Ohad31415** [pydantic/pydantic#3034]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.1
pydantic compiled: True
install path: C:\Python\Python39\Lib\site-packages\pydantic
python version: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
platform: Windows-10-10.0.19041-SP0
optional deps. installed: ['dotenv', 'typing-extensions']
```

### Code Snippet: 
As I understand this code suppose to throw ValidationError on missing fields (name, age).
This works as expected if not using generics. 

```python
from typing import TypeVar, Generic

from pydantic import BaseModel, GenericModel, Json

MsgT = TypeVar('MsgT')

class MyModel(GenericModel, Generic[MsgT]):
    message: Json[MsgT]


class MessageModel(BaseModel):
    name: str
    age: int


obj = MyModel[MessageModel](message='{}')
assert obj.message == {}
```

#### Edition: 
If instead of having annotation as `Json[MsgT]` in `MyModel` I change it to `message: MsgT` and then construct it as `MyModel[Json[MessageModel]](message='{}')` it works great.

**Comment by Kludex** [comment]
Given it was already solved, I'll be closing the issue. 🙏
