### ISSUE TITLE
Custom types cause typing errors

### ISSUE THREAD

**Issue by Dreamsorcerer** [pydantic/pydantic#3042]
Trying out the example at https://pydantic-docs.helpmanual.io/usage/types/#classes-with-__get_validators__
If you enable all the extra options in the mypy plugin, you get this error:
`error: Argument "post_code" to "Model" has incompatible type "str"; expected "PostCode" [arg-type]`

Additionally, if you try to set a default like:
`    post_code: PostCode = "BN1 1AA"`
Then you get this error:
`error: Incompatible types in assignment (expression has type "str", variable has type "FormatStr") [assignment]`

These errors make sense, as we actually only want to validate a str, not change the type (there is a comment about that in the example, where it probably makes more sense to return a str)

Wouldn't this be better if validators can be included using `Annotated`? Which would accurately match the exact meaning that we are trying to give this custom type.

For example, my actual use case is just wanting to format a str with previously defined values, so the validator could be something along these lines:
```python
class _FormatStr:
    validate_always = True

    @classmethod
    def __get_validators__(cls):
        yield cls.validate
    
    @classmethod
    def validate(cls, v: str, values: Dict[str, str]) -> str:
        try:
            return v.format(**values)
        except KeyError as e:
            raise ValueError("Missing settings needed for '{}'.".format(v)) from e

FormatStr = Annotated[str, _FormatStr]

class WelcomeMessage(BaseModel):
    name: str
    message: FormatStr = "Hello, {name}"
```

The main differences from the docs example is not inheriting from `str`, not returning an instance of `cls`, and using `Annotated` to specify the validator (this could really just be a standalone function, rather than a class, as long as there's a way to specify the validate_always option).

This should type check cleanly if implemented. The plugin could also check that the type accepted by `_FormatStr.validate()` is compatible with the primary type specified in `Annotated` (so `Annotated[int, _FormatStr]` would cause a type error).

If we can allow multiple validators as well, then it would allow chaining validators together which would also be great. For example:
```python
# Formats the string, then passes it to another validator which checks the result is a valid format for a name.
name: Annotated[str, FormatStr, ValidFullName] = "{first_name} {last_name}"
# Could also be used to convert type of previous field or something
name_dict: Annotated[Dict[str, str], ConvertNameToDict]
```

**Comment by Dreamsorcerer** [comment]
Would also be nice to specify input/output types explicitly and still be strict typing capable. Something like:
```python
class ConvertToDict:
    ...
    def validate(self, v: str):
        return {...}

class Name(BaseModel):
    name: Annotated[Dict[str, str], ConvertToDict]

n = Name(name="Foo Bar")  # Type of name in __init__ is str, based on validate().
n.name["first"]  # Output type is Dict[str, str]
```

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
