### ISSUE TITLE
"none is not an allowed value" for Enum type

### ISSUE THREAD

**Issue by adam505hq** [pydantic/pydantic#3049]
### Checks

* [ x ] I added a descriptive title to this issue
* [ x ] I have searched (google, github) for similar issues and couldn't find anything
* [ x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/adam/***/***/***/env/lib/python3.6/site-packages/pydantic
               python version: 3.6.13 (default, Apr  6 2021, 08:23:28)  [GCC 10.2.0]
                     platform: Linux-5.10.33-1-lts-x86_64-with-arch
     optional deps. installed: ['typing-extensions']
```

Given below code:
```py
from enum import Enum

from pydantic import BaseModel

class Bar(Enum):
    choice1 = "1"
    choice2 = "2"
    null = None


class Foo(BaseModel):
    bar : Bar

```

Output is given as below:
```
In [3]: Foo(bar=None)
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-3-2625ff945968> in <module>
----> 1 Foo(bar=None)

~/Projects/***/***/env/lib/python3.6/site-packages/pydantic/main.cpython-36m-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Foo
bar
  none is not an allowed value (type=type_error.none.not_allowed)
```

It works for strings though:
```
In [4]: Foo(bar='1')
Out[4]: Foo(bar=<Bar.choice1: '1'>)
```

Current workaround I use is to add `bar : Optional[Bar]`:
```
In [2]: Foo(bar=None)
Out[2]: Foo(bar=None)
```

In my opinion, `Optional` should not be required and it should work out of box with the way Enum is constructed. Also - the plus side of including `null = None` in enum is that in json schema it's clear that this type can also be null. See https://github.com/json-schema-org/json-schema-spec/issues/258

**Comment by shashankrnr32** [comment]
My simple try to fix it in this [branch](https://github.com/samuelcolvin/pydantic/compare/master...shashankrnr32:fix_enum_none?expand=1). 

Uses the private attribute `_value2member_map_` from `EnumMeta` class to check if a particular value is part of the class. I am still a bit not comfortable with this check as this private variable can be removed/modified in the new versions of python (Highly improbably and although I have added a `hasattr` check just to be safe). I didn't want to iterate through the values as this will reduce performance!

I am happy to raise a PR if this solution is ok!

**Comment by adriangb** [comment]
This seems to work as you want in V2:

```python
from enum import Enum

from pydantic import BaseModel


class Bar(Enum):
    choice1 = "1"
    choice2 = "2"
    null = None


class Foo(BaseModel):
    bar : Bar


assert Foo(bar=None).bar is Bar.null
assert Foo.model_validate_json('{"bar": null}').bar is Bar.null
```

Please re-open the issue if that is not the case.
