### ISSUE TITLE
Document that recursive models will make a copy of instances passed into a constructor by default?

### ISSUE THREAD

**Issue by goodboy** [pydantic/pydantic#3100]
My apologies if this is documented somewhere or if there is already an open issue; I wasn't able to find anything on it.

This issue was a source of some considerable pain for me as the use case was updating an existing model instance which was expected to be the same instance passed by reference to both a closure and another composite model.

TDLR: it seems if you pass a model instance to a so called [recursive model](https://pydantic-docs.helpmanual.io/usage/models/#recursive-models) the parent makes a copy/new instance of the passed in child model instance?

Just punching this out in `ipython`:

```python
[ins] In [4]: from pydantic import BaseModel
[nav] In [10]: class C:
          ...:     ...
          ...:

[nav] In [11]: class ArbitraryComposite(BaseModel):
          ...:     c: C
          ...:     class Config:
          ...:         arbitrary_types_allowed = True

[nav] In [12]: c = C(); id(c) == id(ArbitraryComposite(c=c).c)
Out[12]: True

[nav] In [13]: class C_from_base(BaseModel):
          ...:     ...
          ...:

[nav] In [14]: class Composite(BaseModel):
          ...:     c: C_from_base
          
[nav] In [16]: c = C_from_base(); id(c) == id(Composite(c=c).c)
Out[16]: False  
```

I finally figured out that `copy_on_model_validation = False` set on the `C_from_base.Config` fixes this but, wow, what a headache and hard to figure out issue.

So in the 2nd case if I wanted the instance `c` to be *the same instance* referenced in the local scope I have to configure the child model as mentioned, but it was not at all clear that models instances were copied by default especially when in the arbitrary case, *they're not*. I'd almost go so far to say this is fairly un-intuitive implicit behavior.

My suggestion would be to at least document the `copy_on_model_validation = False` bit in the [recursive models section](https://pydantic-docs.helpmanual.io/usage/models/#recursive-models) with maybe an example of incrementally passing in instance references?

Sorry if this came off as rubber ducking.

**Comment by PrettyWood** [comment]
@goodboy PR welcome to add a "info" or "warning" section

**Comment by goodboy** [comment]
Sweet will do!

**Comment by goodboy** [comment]
Or I'll slack 😂

Sorry ended up going with a diff lib for what i needed.
Hopefully this issue still serves as a "doc".

**Comment by dmontagu** [comment]
For what it's worth, this seems to be resolved in v2:
```python
from pydantic import BaseModel
class C:
    ...

class ArbitraryComposite(BaseModel):
    c: C
    class Config:
        arbitrary_types_allowed = True

c = C()
print(id(c) == id(ArbitraryComposite(c=c).c))
#> True

class C_from_base(BaseModel):
    ...

class Composite(BaseModel):
    c: C_from_base

c = C_from_base()
print(id(c) == id(Composite(c=c).c))
#> True
```
If something is still misbehaving please let us know and we can reopen the issue.
