### ISSUE TITLE
Custom json encoder for bytes yields infinite loop

### ISSUE THREAD

**Issue by MarcMueltin** [pydantic/pydantic#3104]
Hi, 

I'm trying to use Base64 encoding for the custom json encoding of bytes, but that results in an infinite loop eating up all my RAM. Am I overlooking something? What's the solution?

Here's a post that illustrates the exact same problem I have: https://www.gitmemory.com/issue/samuelcolvin/pydantic/863/538754238

**Comment by shashankrnr32** [comment]
I am not aware of your usecase here, I use bytes in a similar way (Base64 encoding while converting to JSON). You can convert the bytes object into an array of bytes or a string which are both JSON compatible

To convert into an array of bytes. I personally use this.
```python
json_encoders = {
    bytes: lambda v: list(base64.b64encode(v))
}
```

To convert into a UTF-8 string.
```python
json_encoders = {
    bytes: lambda v: base64.b64encode(v).decode()
}
```

Note that with this, you will have to write a custom validator to deserialize the converted JSON to the Model.

Please feel free to correct me if I wrong in understanding your problem.

**Comment by MarcMueltin** [comment]
Thanks @shashankrnr32, I just now had time to check out your solution approach for encoding bytes and it works. Thanks for that! How would you go about writing such a custom validator to deserialize the converted JSON to the Model?

I'm trying to think of a way with a root validator that applies to all models (on the BaseModel level) and checks whether or not a field is of type List[bytes] and go from there, but that already doesn't seem to work. Any hint would be greatly appreciated.

Also: is there a plan to fix that issue with the infinite loop?

My use case is that I am implementing a communication protocol with lots of different messages that adhere to a certain XSD schema. Some of those message fields are of type bytes.

**Comment by Kludex** [comment]
Since we now have the `Base64Str` and `Base64Bytes`, I'll close this.

See [Base64 encoding support](https://docs.pydantic.dev/latest/usage/types/encoded/#base64-encoding-support) for more details.
