### ISSUE TITLE
Add a config to make all fields Optional

### ISSUE THREAD

**Issue by christophelec** [pydantic/pydantic#3120]
### Discussed in https://github.com/samuelcolvin/pydantic/discussions/3089

<div type='discussions-op-text'>

<sup>Originally posted by **christophelec** August 11, 2021</sup>
# Proposal : adding a Config key to set all fields of a model as Optional

## Context :

In FastAPI, the OpenAPI spec is defined via Pydantic models.
 
To create a partial update endpoint in FastAPI, I'd like to be able to create a Model derived from another, but with all fields Optional, without having to manually duplicate all fields.

For example, let's say I have an API dealing with user, and creating a user takes as input : 

```python
class User(BaseModel):
  first_name: str
  last_name: str
  age: int
  address: str
```

If I want to have an endpoint to be able to partially update the user (e.g. change only the first_name), I'd like an endpoint where I can send :
```json
{"first_name": "NEW"}
```

To have this behavior, currently I have to either : 
* Create a specific model for patching, with all fields set as Optional : 
```python
class PatchedUser(BaseModel):
  first_name: Optional[str]
  last_name: Optional[str]
  age: Optional[int]
  address: Optional[str]
```
* Set all fields as Optional in the first model, and then add back manual validation down the road in the context of a user creation (where the fields are mandatory) (https://fastapi.tiangolo.com/tutorial/body-updates/#partial-updates-with-patch)

The first solution results in a lot of duplication, and therefore a lot of potential bugs.
The second one makes the schema less clear, and validation less easy.

## Proposed solution

I would like to be able to derive a model from this base model, but switching all the fields to Optional. A possible usage could be : 

```python
class PartialUser(User):
  class Config:
    all_optional = True
```

This way, the PartialUser would keep all the fields from User, but setting them as Optional.

The result in FastAPI would look like this : 

```python
@router.post("/users/")
async def create_user(
    user: User,
):
    # All fields are mandatory
    return create_user(user)

@router.patch("/users/{user_id}/")
async def update_user(
    user_id: int,
    user: PartialUser,
):
  # Only fields to modify will be kept
  return update_user(user.dict(exclude_unset=True))
```

I'm willing to open a PR if you think this is a good idea.</div>

**Comment by PrettyWood** [comment]
Hello @christophelec 
In the meantime you can see https://github.com/samuelcolvin/pydantic/issues/2272#issuecomment-771205557.
For feature requests, better use the discussions section btw

**Comment by christophelec** [comment]
Hello @PrettyWood, I opened the discussion last week but it did not trigger much discussion except a :+1:, so I went ahead and opened the issue, as well as started a PR as it would be really useful on my side.

The PR is here : https://github.com/samuelcolvin/pydantic/pull/3121, and I just saw your comment about class kwargs, which indeed would be nice : I'll update accordingly.

I'm ok to close the issue

**Comment by mrlubos** [comment]
Per discussion in #3179, the current advice is to wait for v2

**Comment by adriangb** [comment]
I don't think we'll have a special solution for this in v2. This is just not possible to express to Python's type system. The best I could come up with is the following, but I think it would work in v1 as well so it's nothing new:

```python
from copy import deepcopy
from typing import Any, Optional, Tuple, Type, TypeVar

from pydantic import BaseModel, create_model
from pydantic.fields import FieldInfo


class User(BaseModel):
  first_name: str
  last_name: str


def make_field_optional(field: FieldInfo, default: Any = None) -> Tuple[Any, FieldInfo]:
  new = deepcopy(field)
  new.default = default
  new.annotation = Optional[field.annotation]  # type: ignore
  return (new.annotation, new)


BaseModelT = TypeVar('BaseModelT', bound=BaseModel)

def make_partial_model(model: Type[BaseModelT]) -> Type[BaseModelT]:
  return create_model(  # type: ignore
    f'Partial{model.__name__}',
    __base__=User,
    __module__=User.__module__,
    **{
        field_name: make_field_optional(field_info)
        for field_name, field_info in User.model_fields.items()
    }
    )


PartialUser = make_partial_model(User)


print(PartialUser(first_name='Adrian'))
#> first_name='Adrian' last_name=None
```

**Comment by jd-solanki** [comment]
Can we reopen this for v2? In typescript, it's just `Partial<User>` 🤷🏻‍♂️

**Comment by samuelcolvin** [comment]
We'll support it as soon as python has a type that allows us to express this in a way that type checkers can understand.

If you really want this, I could post on discuss.python.org advocating for this feature in the language, post the link here and I'll reply and support it.

You're best option might be to use a typeddict where you can set `total=False`, though I still don't think there's a way to "partialise" an existing model.

**Comment by jd-solanki** [comment]
Thanks @samuelcolvin for responding.

> If you really want this

Yes, I honor the work you are doing (as I'm also the OSS dev) and if you can raise the query upstream (python) it will be a great addition to pydantic because people (mostly FastAPI devs) always wanted this. I'll do my best to support this query.

I tried typedDict with my knowledge but I failed because I wanted to "partialise" the class inherited from `BaseModel` just like you mentioned.

Best Regards,
JD

**Comment by sree1026** [comment]
> I don't think we'll have a special solution for this in v2. This is just not possible to express to Python's type system. The best I could come up with is the following, but I think it would work in v1 as well so it's nothing new:
> 
> ```python
> from copy import deepcopy
> from typing import Any, Optional, Tuple, Type, TypeVar
> 
> from pydantic import BaseModel, create_model
> from pydantic.fields import FieldInfo
> 
> 
> class User(BaseModel):
>   first_name: str
>   last_name: str
> 
> 
> def make_field_optional(field: FieldInfo, default: Any = None) -> Tuple[Any, FieldInfo]:
>   new = deepcopy(field)
>   new.default = default
>   new.annotation = Optional[field.annotation]  # type: ignore
>   return (new.annotation, new)
> 
> 
> BaseModelT = TypeVar('BaseModelT', bound=BaseModel)
> 
> def make_partial_model(model: Type[BaseModelT]) -> Type[BaseModelT]:
>   return create_model(  # type: ignore
>     f'Partial{model.__name__}',
>     __base__=User,
>     __module__=User.__module__,
>     **{
>         field_name: make_field_optional(field_info)
>         for field_name, field_info in User.model_fields.items()
>     }
>     )
> 
> 
> PartialUser = make_partial_model(User)
> 
> 
> print(PartialUser(first_name='Adrian'))
> #> first_name='Adrian' last_name=None
> ```
> 
> Since we can't really do much better than that without the Python ecosystem reaching a consensus and adding typing support for a partial operator, I'm closing this as a wontfix.

@adriangb Thank you so much for the solution. Seems like Pydantic v1.10 throws `TypeError: Object of type 'ModelField' is not JSON serializable` when I try to call`schema_json()` on the PartialUser object. 

However, when testing with Pydantic v2.0.3, the error is no longer thrown. I'm not sure why the older version of Pydantic was throwing the error. In any case, I plan to update to the latest version, so it's not a major concern for me. I just wanted to post the issue here so that anyone else facing the same error with older Pydantic versions will know that updating might resolve it.

**Comment by tobiasfeil** [comment]
Has anyone actually tried the code? I had to replace 
```python
    __base__=User,
    __module__=User.__module__,
```
with
```python
    __base__=model,
    __module__=model.__module__,
```

**Comment by ptrba** [comment]
This works just fine. One potential improvement: The @adriangb solution will override all default values of the original model and set them to `None`. If you want to preserve defaults you need to modify accordingly:

```
import pydantic_core

...

def make_field_optional(field: FieldInfo, default: Any = None) -> Tuple[Any, FieldInfo]:
  new = deepcopy(field)
    if not isinstance(field.default, pydantic_core.PydanticUndefinedType):
        new.default = field.default
    else:
        new.default = default
  new.annotation = Optional[field.annotation]  # type: ignore
  return (new.annotation, new)
```

**Comment by alemar99** [comment]
If someone is looking for a solution that is not dynamic and will preserve type hints as well, I've made a script to automatically generate models with all fields optional. You can see it here: https://github.com/alemar99/pydantic-optional-models

**Comment by timonrieger** [comment]
> I don't think we'll have a special solution for this in v2. This is just not possible to express to Python's type system. The best I could come up with is the following, but I think it would work in v1 as well so it's nothing new:

[@adriangb 's solution](#issuecomment-1528030416) is not working anymore in the [v2.12.0a1](https://github.com/pydantic/pydantic/releases/tag/v2.12.0a1) release. it works in v2.11.x.
can't tell if it's pydantic-core ([diff](https://github.com/pydantic/pydantic-core/compare/v2.34.1...v2.35.1.diff)) or pydantic ([diff](https://github.com/pydantic/pydantic/compare/v2.11.7...v2.12.0a1.diff)). The issue is that fields are not marked as optional anymore, but kept as required. Quickfix is pinning the pydantic version to <2.12.0.

for reference that's the code I have been using for months, before it broke in the prerelease
```python

def partial_model(model: Type[BaseModel]) -> Type[BaseModel]:
    """Marks all fields of a model as optional. Useful for updating models.
    >>> @partial_model
    >>> class Model(BaseModel):
    >>>     i: int
    >>>     f: float
    >>>     s: str
    """

    def make_field_optional(
        field: FieldInfo, default: Any = None
    ) -> Tuple[Any, FieldInfo]:
        new = deepcopy(field)
        new.default = default
        new.annotation = Optional[field.annotation]  # type: ignore
        return new.annotation, new

    return create_model(
        model.__name__,
        __base__=model,
        __module__=model.__module__,
        __doc__=model.__doc__,
        **{
            field_name: make_field_optional(field_info)
            for field_name, field_info in model.model_fields.items()
        },
    )

```

**Comment by iangoldby** [comment]
Would it help to use the[ Partial class from this response](https://github.com/pydantic/pydantic/issues/9573#issuecomment-2282680469) to another issue instead of create_model()? For me that seems still to be a viable approach in 2.12.0.

**Comment by Viicos** [comment]
@iangoldby see my solution at the end of this comment: https://github.com/pydantic/pydantic/issues/12329#issuecomment-3382159312.
