### ISSUE TITLE
The hypothesis plugin always generates None for Optional fields when building pydantic models

### ISSUE THREAD

**Issue by gautehalvorsen** [pydantic/pydantic#3126]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
Python 3.8.5
pydantic==1.8.2
hypothesis==6.14.1

When a field in the pydantic model is marked as Optional, the hypothesis plugin always seems to generate None for this field when building the model.

Expected behavior: I would expect it to be None about 50% of the time, but set with the proper field value otherwise
Actual behavior: Always seems to be None

Here's a minimal example that I think illustrated the problem. This test will always fail, because I've never seen the field be anything but None
```py
import typing
from hypothesis import assume, given, strategies as st
from pydantic import BaseModel,  PaymentCardNumber, PositiveFloat
class Model(BaseModel):
    card: typing.Optional[PaymentCardNumber]
    price: PositiveFloat


@given(st.builds(Model))
def test_card_property(instance):
    assume(instance.card is not None)

...
```

**Comment by daviskirk** [comment]
You can "from_type" instead.  In fact, it produces a `builds` strategy internally but adds all the correct strategies for the fields:

```python
>>> st.builds(Model)
builds(Model)
>>> st.from_type(Model)
builds(Model, card=one_of(none(), one_of(none(), from_regex('4[0-9]{14}|5[12345][0-9]{13}|3[47][0-9]{12}|[0-26-9][0-9]{10,17}', fullmatch=True).map(add_luhn_digit))))
>>> st.from_type(Model).example()
Model(card='5216708354704600', price=1.7976931348623157e+308)
```

**Comment by gautehalvorsen** [comment]
Nice! Thank you! It would be nice if this worked for builds to, or was better documented in the documentation

**Comment by DaanRademaker** [comment]
Did you ever figure out a way to solve this? I am having exactly the same issues.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
