### ISSUE TITLE
json_loads/dumps not used on nested types

### ISSUE THREAD

**Issue by mfulgo** [pydantic/pydantic#3153]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
When specifying `json_loads` or `json_dumps` for a class, the custom method is not used if the class is (de)serialized by an object containing it. This may be the intended behavior, but I didn't find it documented.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /Users/matt/work/external/pydantic/pydantic
               python version: 3.8.11 (default, Jun 29 2021, 03:17:05)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.6-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```
Example failing test (added to `tests/test_json`):
```py
def test_custom_nested_decode_encode():
    load_calls, dump_calls = 0, 0

    def custom_loads(s):
        nonlocal load_calls
        load_calls += 1
        return json.loads(s.strip('$'))

    def custom_dumps(s, default=None, **kwargs):
        nonlocal dump_calls
        dump_calls += 1
        return json.dumps(s, default=default, indent=2)

    class Model(BaseModel):
        a: int
        b: str

        class Config:
            json_loads = custom_loads
            json_dumps = custom_dumps

    class Wrapper(BaseModel):
        m: Model

    w = Wrapper.parse_raw('{"m":{"a$": 1, "b": "foo"}}')
    assert w.dict() == {'m': {'a': 1, 'b': 'foo'}}
    assert w.json() == '{"m": {\n  "a": 1,\n  "b": "foo"\n}}'
    # FIXME: These assertions are missing in the previous test.
    assert load_calls == 1
    assert dump_calls == 1
```
Fails with:
```
E           pydantic.error_wrappers.ValidationError: 1 validation error for Wrapper
E           m -> a
E             field required (type=value_error.missing)
```

I expected `Model`'s load/dumps methods to be used, but again, maybe that's not the intended behavior.

Ultimately, I'd like to specify both a custom encoder and decoder for a class so it can be serialized to/from a specifically-formatted string. This approach doesn't feel like the right way to do that, but I came across the issue while trying to figure that out.

**Comment by deanq** [comment]
I have encountered this bug as well. This is essential for when writing legacy-compatible API. Sometimes you just have to serialize a field as a different name, but only at the json() level. In my case, putting an alias doesn't work since it should never be saved into the database with the alias name. Having a custom json_dumps function was a good temporary work-around (at least until the consuming legacy app removes that requirement).

To be specific, Django uses `User.pk` when serializing `User.id`. My API needs to suppor that json transformation only at the response level.

**Comment by Kludex** [comment]
Yes, it's the intended behavior. The `Wrapper` class should have its own `json_loads` and `json_dumps`.
