### ISSUE TITLE
`NameEmail` should support quoted names

### ISSUE THREAD

**Issue by nzig** [pydantic/pydantic#3173]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/.../.virtualenvs/.../lib/python3.8/site-packages/pydantic
               python version: 3.8.11 (default, Jul 10 2021, 20:47:03)  [GCC 10.3.0]
                     platform: Linux-5.11.0-31-generic-x86_64-with-glibc2.33
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

RFC 5322 allows for addresses of the form `"Quoted Name" <me@example.com>`. In my experience with email this form is pretty common. I would like for pydantic's `NameEmail` to recognize this format as well, and to preserve it if it is parsed (so that `str(NameEmail.validate('"Quoted Name" <me@example.com>')) == '"Quoted Name" <me@example.com>'`).

I know that email parsing is not well-defined, and pydantic does not aim to support every email edge case, so I would like to see if there's an appetite for supporting this in pydantic. I can submit a PR if so.

**Comment by Kludex** [comment]
PR welcome to implement on V2. 🙏

**Comment by sydney-runkle** [comment]
Closing for now - validation is supported for this case:

```py
from pydantic import BaseModel, NameEmail


class MyModel(BaseModel):
    x: NameEmail

m = MyModel(x='"Quoted Name" <me@example.com>')
print(m.model_dump_json())
#> {"x":"Quoted Name <me@example.com>"}
```
