### ISSUE TITLE
Pydantic fails when converting recursive stdlib dataclasses to Pydantic models

### ISSUE THREAD

**Issue by adibbaziz** [pydantic/pydantic#3251]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/adib/ponicode/refactojr/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
                     platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

## Description
Hello, I am trying to add data validation to an existing codebase. Type hints are enforced using stdlib dataclasses.

Some of the dataclasses are recursive. You can find a simple example to reproduce the bug below.
It happen in two cases:
- Creating a Pydantic model with a field that is a recursive dataclass
- Trying to transform a recursive dataclass to a Pydantic model

## Example
```py
from __future__ import annotations
from dataclasses import dataclass
import pydantic
from typing import Optional


@dataclass
class Node:
    left: Optional[Node] = None
    right: Optional[Node] = None


class Tree(pydantic.BaseModel): # This raises: Exception has occurred: RecursionError
    root_node: Node


PydanticNode = pydantic.dataclasses.dataclass(Node) # This raises: Exception has occurred: RecursionError

```

**Comment by dmontagu** [comment]
Strangely the code above still errors for me in v2, but if I change `Optional[Node]` to `Node | None` or remove the `from __future__ import annotations` and change `Node` to `'Node'` in annotations, this error goes away.

I think the solution to this will be to allow dataclasses to have invalid forward refs that get populated through something equivalent to model_rebuild (where you can specify a namespace), and/or to better-infer the proper namespace.

**Comment by dmontagu** [comment]
This seems to be fixed now in v2:
```python
from __future__ import annotations
from dataclasses import dataclass
import pydantic
from typing import Optional


@dataclass
class Node:
    left: Optional[Node] = None
    right: Optional[Node] = None


class Tree(pydantic.BaseModel): # This raises: Exception has occurred: RecursionError
    root_node: Node


PydanticNode = pydantic.dataclasses.dataclass(Node) # This raises: Exception has occurred: RecursionError

print(PydanticNode(left=PydanticNode(), right=PydanticNode()))
#> Node(left=Node(left=None, right=None), right=Node(left=None, right=None))
```
I'm going to close this as fixed-in-v2/won't-fix-in-v1.
