### ISSUE TITLE
Using a type with `__root__` set to `Any` as a property, an error occurs when passing `None`

### ISSUE THREAD

**Issue by yacchi** [pydantic/pydantic#3258]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /usr/local/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep  3 2021, 12:37:55)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-11.5.2-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

# Description
If you use a type with `__root__` set to `Any` as a property, it will error as `none is not an allowed value` when you pass `None`, which should be available.

When a type other than `None` (e.g. str, int, dict, etc.) is passed, it can be used without any problem.

# Example

```py
from typing import Any
from pydantic import BaseModel


def test_any_none_nested():
    class Inner(BaseModel):
        __root__: Any

    class Outer(BaseModel):
        foo: Inner

    m = Outer(foo=None)
    assert m.dict() == {"foo": None}


test_any_none_nested()
```

If you run this code, you will get an error that `None` is not allowed, even though you have set a value for `Any`.

```
Traceback (most recent call last):
  File "/private/tmp/test_any_none_nested.py", line 16, in <module>
    test_any_none_nested()
  File "/private/tmp/test_any_none_nested.py", line 12, in test_any_none_nested
    m = Outer(foo=None)
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Outer
foo
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by lig** [comment]
thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by lig** [comment]
@yacchi thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
