### ISSUE TITLE
Custom containers in pydantic

### ISSUE THREAD

**Issue by vincent-lg** [pydantic/pydantic#3265]
```
pydantic version: 1.8.2
pydantic compiled: False
install path: C:\...\pyenv\Lib\site-packages\pydantic
python version: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:05:41) [MSC v.1929 32 bit (Intel)]
platform: Windows-10-10.0.19042-SP0
optional deps. installed: ['email-validator', 'typing-extensions']
```

I'm playing with collections in Pydantic.  That is to say, if a field is a collection type (say, `typing.List`), I'd like to monitor what changes in it.  In theory, it's rather simple to do:  I created a small class (inhering from `collections.abc.MutableSequence`) that looks like a list and implements some checks when modified.  So far so good.

```py
from typing import List

import pydantic

class Account(pydantic.BaseModel):
    users: List["User"]


class User(pydantic.BaseModel):

    #...
```

Of course, doing that would raise an error:

```
>>> Account(MyExtendedCollection())
pydantic.error_wrappers.ValidationError: 1 validation error for Account
users
  value is not a valid list (type=type_error.list)
```

That's kind of normal, since `issubclass(MyExtendedCollection, list)` will return `False`.  I had hoped Pydantic would link these (it's not encouraged to inherit from `list` in Python, I think, using `collections.abc` seems to be encouraged over subclassing them).

Well, the problem might be in the type annotation: `users` ha type `list` after all.  Well... it has type `typing.List["User"]` which is not exactly the same thing.  I can't do that for instance:

```
class Accoun(pydantic.BaseModel):

    users: MyExtendedCollection["User"] # Breaks
```

So I'm not sure how to handle this situation.  It seems `pydantic` is able to handle additional types that can be defined by the user.  Can users explain to pydatic that `MyExtendedCollection` is, indeed, a list?  Is there another approach?

P.S. : it sounds like this bug would be a question which already has an answer.  If so, I apologize for posting.  But it might very well be a feature in waiting.  I'll let you decide which.

Thank you for this library!

**Comment by HashimHL** [comment]
The way I'm going for is to just to make the sequence class as a pydantic class, another option is to use [custom root types](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) to wrap your class inside it if you don't want to make your class pydanticy. Just note that this will not work correctly with `MutuableMapping` or anything that wants to use `__iter__` aka any subclass of [collections.abc.Iterator](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterator) because pydantic base models already have an `__iter__` function

here is a working example for your case that works in python3.9+.
```python
from collections.abc import MutableSequence, Sequence
from pydantic import BaseModel
from pydantic.generics import GenericModel
from typing import TypeVar, Generic, Optional

data_type = TypeVar("data_type")
class SequenceTracker(GenericModel, MutableSequence[data_type], Generic[data_type]):
    data: list[data_type] = []
    _get: int = 0
    _set: int = 0
    _del: int = 0
    _len: int = 0
    _insert: int = 0
    def __getitem__(self, index: int) -> data_type:
        self._get+=1
        return self.data[index]
    def __setitem__(self, index: int, value: data_type) -> None:
        self._set+=1
        self.data[index] = value
    def __delitem__(self, index: int) -> None:
        self._del+=1
        del self.data[index]
    def __len__(self) -> int:
        self._len+=1
        return len(self.data)
    def insert(self, index: int, value: data_type) -> None:
        self._insert+=1
        self.data.insert(index, value)
    def stats(self) -> dict[str, int]:
        return dict(get=self._get, set=self._set, delete=self._del, len=self._len, insert=self._insert)
    class Config:
        underscore_attrs_are_private = True


class User(BaseModel):
    id: int
    name: str


class Account(BaseModel):
    users: SequenceTracker[User]


st = SequenceTracker[User]()
st.append(User(id=5, name="cat"))
st.append(User(id=6, name="dog"))
assert st.stats() == {'get': 0, 'set': 0, 'delete': 0, 'len': 2, 'insert': 2}

a = Account(users=st)
a_dict = a.dict()
assert a_dict=={'users': {'data': [{'id': 5, 'name': 'cat'}, {'id': 6, 'name': 'dog'}]}}

parsed_a = Account.parse_obj(a_dict)
assert parsed_a == a

parsed_a.users.append(User(id=1, name="banana"))
assert parsed_a != a
```

**Comment by dmontagu** [comment]
While going through other issues I ultimately ended up implementing a custom generic container in [this gist](https://gist.github.com/dmontagu/7f0cef76e5e0e04198dd608ad7219573), linked from this comment: https://github.com/pydantic/pydantic/issues/2274#issuecomment-1528082601, it may be useful for reference.
