### ISSUE TITLE
Empty objects should be validated as None for optional fields

### ISSUE THREAD

**Issue by a5r0n** [pydantic/pydantic#3295]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/aaron/Dev/Python/twistbot/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.0 (default, Aug  2 2021, 23:21:12)  [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
                     platform: Linux-5.14.9-200.fc34.x86_64-x86_64-with-glibc2.33
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

(i'm not sure if is actually bug, maybe is a Feature Request )

when we pass an empty dict (and list too?) for an `Optional` field,  it's should be handle as `None` if not all of this field fields are optional.

lets say, 
if some field raises `ValidationError`, we should try handle it as None, at last when is an empty object (list or dict)

```py
from typing import Optional, Dict
from pydantic import BaseModel

class Data(BaseModel):
    some: Dict

class EmptyDictTest(BaseModel):
    data: Optional[Data] = None


EmptyDictTest.parse_obj({"data": {}})

pydantic.error_wrappers.ValidationError: 1 validation error for EmptyDictTest
data -> some
  field required (type=value_error.missing)

```

**Comment by oligond** [comment]
I'm not really sure that I got your idea right because I can't make entirely sense of that phrase (especially the last part _if not all of this field's fields are optional_ - what outcome should we expect if all the fields in the field's model are indeed optional?):

> when we pass an empty dict (and list too?) for an Optional field, it's should be handle as None if not all of this field fields are optional.

Let me translate your model declarations for `Data` and `EmptyDictTest` into human language:
_`EmptyDictTest` might contain a `data` field (or not, it's optional), and whenever there's a `data` field present, it should be a dict that must contain a `some` field/key._

That said, it looks like a misunderstanding on your part what exactly is _optional_ here.

The `Optional` on the annotation of `EmptyDictTest.data` allows to pass in an empty dict (strictly spoken a dict without a `data` field, but as that's the only field in your model, this amounts to an empty one).

`EmptyDictTest.parse_obj({})` will thus work.

To fix your code example in order to behave according to your expectation (make `some` optional), update the annotation for `Data.some` to `Optional[Dict]`. Your test statement should work after that.

As I see it, it's within the responsibility of your code to remove the `data` field from the dict you're parsing in case it's empty (if that's what you want: _Treat empty dict just like an unset value_).

Pydantic already provides you with means to achieve this easily. You could use a `root_validator` for that purpose that removes the field if it's an empty dict:

```python
from typing import Optional, Dict
from pydantic import BaseModel, root_validator

class Data(BaseModel):
    some: Dict

class EmptyDictTest(BaseModel):
    data: Optional[Data] = None

    @root_validator(pre=True)
    def remove_empty(cls, values):
        if values.get("data") == {}:
            values.pop("data")
        return values


EmptyDictTest.parse_obj({"data": {}})
```
Hope I didn't miss your point completely 😉

**Comment by a5r0n** [comment]
first, thanks for your time.

> and whenever there's a `data` field present, it should be a dict that must contain a `some` field/key.

if `data` field is `None` is fine too.
so an "falsey" object should be equal to None?


some weird APIs in the world (whatsapp) sends an empty dict when `data` field object is empty, instead of just not include it.


the `@root_validator` works well, and that's what i'm using right now.
but in my opinion, pydantic should do that instead of defined root_validator in each model of the api.

(BTW, root validator can be reused?)

**Comment by oligond** [comment]
> but in my opinion, pydantic should do that instead of defined root_validator in each model of the api.

I'm not so sure this would be a sensible default apart from your specific use case.

If you need to apply that same logic all over the place, you could

1. generalize my sample `root_validator` from the comment above to be applied to ALL list/dict fields

2. subclass pydantic.BaseModel and use your subclass to declare your models to have it everywhere

```python
from typing import Optional, Dict, List
from pydantic import BaseModel, root_validator

class EliminateEmptyListAndDictModel(BaseModel):

    @root_validator(pre=True)
    def remove_empty(cls, values):
        fields = list(values.keys())
        for field in fields:
            value = values[field]
            if isinstance(value, dict) or isinstance(value, list):
                if not values[field]:
                    values.pop(field)
        return values


class Data(BaseModel):
    some: Dict


class EmptyDictTest(EliminateEmptyListAndDictModel):
    data_dict: Optional[Data] = None
    data_list: Optional[List] = None
    # we add data_scalar to test that falsy scalar values (0 in the case of int) are not replaced
    data_scalar: int = None


test = EmptyDictTest.parse_obj({"data_dict": {}, "data_list": [], "data_scalar": 0})
print(test)
# data_dict=None data_list=None data_scalar=0
```
Like this, there also wouldn't be any need to reuse the root validator.

**Comment by adriangb** [comment]
This can't become the default. The workaround is easy in V1 and easier in V2:

```python
from typing import Annotated, Any, Dict, Optional, TypeVar

from pydantic import BaseModel
from pydantic.annotated_arguments import BeforeValidator


class Data(BaseModel):
    some: Dict[Any, Any]

T = TypeVar('T')

def falsy_to_none(x: Any) -> Any:
    return x or None

LeniantOptional = Annotated[Optional[T], BeforeValidator(falsy_to_none)]

class EmptyDictTest(BaseModel):
    data: LeniantOptional[Data] = None

assert EmptyDictTest.parse_obj({'data': {}}).data is None
```

**Comment by Sunchock** [comment]
Using `pydantic 2.7.1`, I wasn't able to find pydantic.annotated_arguments import

So here is another solution using [field_validator](https://docs.pydantic.dev/latest/concepts/validators/#field-validators)
```python
#!/usr/bin/env python3
# Python imports
from typing import Optional
# Packages imports
from pydantic import BaseModel, field_validator

class B(BaseModel):
    var3: str
    var4: str

class A(BaseModel):
    var1: int
    var2: Optional[B] = None

    @field_validator('var2', mode='before')
    def check_empty(cls, value):
        return value or None

if __name__ == "__main__":
    data = {
        "var1": 1,
        "var2": {}
    }
    result = A.model_validate(data)
    print(result)
```

**Comment by adriangb** [comment]
Just import it straight from `pydantic`:

```python
from typing import Annotated, Any, Dict, Optional, TypeVar

from pydantic import BaseModel
from pydantic import BeforeValidator


class Data(BaseModel):
    some: Dict[Any, Any]

T = TypeVar('T')

def falsy_to_none(x: Any) -> Any:
    return x or None

LeniantOptional = Annotated[Optional[T], BeforeValidator(falsy_to_none)]

class EmptyDictTest(BaseModel):
    data: LeniantOptional[Data] = None

assert EmptyDictTest.parse_obj({'data': {}}).data is None
```
