### ISSUE TITLE
Sequences fail the `sequence_like()` check

### ISSUE THREAD

**Issue by luke321321** [pydantic/pydantic#3298]
# Bug

Custom classes that are subclasses of `collections.abc.Sequence` don't return true from `sequence_like` https://github.com/samuelcolvin/pydantic/blob/c256dccbb383a7fd462f62fcb5d55558eb3cb108/pydantic/utils.py#L135-L136 and so raise an error when validating
https://github.com/samuelcolvin/pydantic/blob/c256dccbb383a7fd462f62fcb5d55558eb3cb108/pydantic/fields.py#L786
 for not being a valid sequence.

What would happen if we modified this check to include instance of `Sequence`?  There might be other implications of this for `dict`s or `str` being validated into a list of keys.  However, I think that the current situation seems like it could be somewhat improved to support custom class that implement the `Sequence` interface.

I came across this in the wild when attempting to validate a `fastcore.foundation.L` object which can behave like a list+ but is not an explicit subclass of `list` and so unexpectedly throw validation errors.

Minimal example:
```py
from collections.abc import Sequence as _Sequence
from typing import Sequence

import pydantic


class BasicSequence(_Sequence):
    def __init__(self, items: list):
        self._items = list(items)

    def __getitem__(self, i: int):
        return self._items[i]

    def __len__(self) -> int:
        return len(self._items)


class Model(pydantic.BaseModel):
    sequence: Sequence


seq = BasicSequence([1, 2, 3])
Model(sequence=seq)
```
Gives the following output
```
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Model
sequence
  value is not a valid sequence (type=type_error.sequence)
```

## System information:
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/{USER}/.pyenv/versions/3.9.4/envs/{REPO}/lib/python3.9/site-packages/pydantic
               python version: 3.9.4 (default, May 24 2021, 12:01:43)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-11.6-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

**Comment by thejaminator** [comment]
Seconded, facing the same issue when adding pydantic support to a custom sequence type

**Comment by chbndrhnns** [comment]
I am seeing a similar behaviour for a custom type that implements `collections.abc.MutableSet`.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
