### ISSUE TITLE
None is not allowed value for Required Optional objects

### ISSUE THREAD

**Issue by xsway** [pydantic/pydantic#3308]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

I checked quite a bit discussions, documentation etc but couldn't find the answer to my question. Thanks for taking time in checking this.

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/elsa/miniforge3/envs/...
               python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:27:18)  [Clang 11.1.0 ]
                     platform: macOS-11.2.3-arm64-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']

```

I wanted to use `Field(...)` as described in the docs (https://pydantic-docs.helpmanual.io/usage/models/#required-optional-fields) to get a required field that can take None value. This works with simple types like int, str etc as described in the docs. However, when used with custom objects like `Data` below, it gives `none is not an allowed value (type=type_error.none.not_allowed)`.

```py
import pydantic

class Data(BaseModel):
    x: int = 3
    
class Model(BaseModel):
    data: Data = Field(...)

Model(data=None)    # should be ok, but is not
```

**Comment by PrettyWood** [comment]
@xsway You need to use `...` **and** `Optional` 
```py
class Model(BaseModel):
    data: Optional[Data] = ...
```

**Comment by xsway** [comment]
Thanks a lot! It seems I forgot `Optional[]` and got confused because it works without Optional with e.g. `data: int = ...`.

**Comment by argv1** [comment]
I got 
`"itemNumber": null, `
in my JSON file, used 
`itemNumber: Optional[str] = ...`
in the basemodel and still receive
`none is not an allowed value (type=type_error.none.not_allowed)`
