### ISSUE TITLE
Mypy screams about not passing a value for validator-default attribute

### ISSUE THREAD

**Issue by mdczaplicki** [pydantic/pydantic#3314]
### Discussed in https://github.com/samuelcolvin/pydantic/discussions/3280

<div type='discussions-op-text'>

<sup>Originally posted by **mdczaplicki** October  1, 2021</sup>
I have this schema:

```
class X(BaseModel):
  x: int
  y: int

  @root_validator(pre=True)
  def _set_y(cls, values):
    values["y"] = values["x"] + 2
    return values

x = X(x=2)  # mypy complains here about not passing y
```

Is there anything I can do for mypy not to complain about it? For now I've added `# type: ignore` to initialization of `X`, but maybe there's a way to mark `y` as not mandatory to pass.</div>

**Comment by pszpetkowski** [comment]
The value in the object might indeed be always present, but it is not required in the input schema. In the above example you are trying to violate your own contract.

**Comment by adriangb** [comment]
You could do something like:

```python
UNSET: Any = object()

class X(BaseModel):
  x: int = UNSET
```

That's typically what's done for situations like this not just in Pydantic but Python in general.

Unfortunately getting this to "work" with MyPy would be difficult if not impossible even using a plugin. Even if we could get it to work, I'm not sure it's a good idea, it's really fighting the type system. And it would never work for other type checkers.

**Comment by dmontagu** [comment]
One thing I'll note that I believe can be done now in v2 is to override the `__init__` and remove the `y` from the signature. This may require a bit of work on the mypy plugin before it behaves perfectly, but my intent is to use the explicitly specified `__init__` signature when present.

I think @adriangb's suggestion is probably the best choice in general though (combined with a validator that replaces the `UNSET`.
