### ISSUE TITLE
Field that is a subclass of list gets converted into list instead of specific subclass

### ISSUE THREAD

**Issue by thejaminator** [pydantic/pydantic#3318]
### Checks

* [ x] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/my_user/ml/surf/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import pydantic
from typing import *

A = TypeVar("A")


class Slist(list, Generic[A]):
    @property
    def length(self) -> int:
        return len(self)

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not isinstance(v, list):
            raise TypeError(f'list required, got {v}')
        else:
            return Slist(v)


class MyModel(pydantic.BaseModel):
    children: Slist[str]


def test_parsing():
    type(MyModel.parse_obj({"children": ["sds"]}).children) # type is list instead of Slist
    print(isinstance(MyModel.parse_obj({"children": ["sds"]}).children, Slist)) # False
test_parsing()
...
```

I have implemented a subclass of list, `Slist` that has more methods .  I am trying to read fields into Slist. However, pydantic converts them into the parent class list instead of `Slist`.

I have followed https://pydantic-docs.helpmanual.io/usage/types/#classes-with-__get_validators__ to implenented a custom __get_validators__, but pydantic seems to turn it back into a list anyhow. Any tips?

Possible workarounds:
Don't inherit from list? https://github.com/samuelcolvin/pydantic/issues/3265

**Comment by dmontagu** [comment]
It seems this is resolved in v2, or at least the example you shared now prints `True`.

If you try out v2 and run into related issues, we will be happy to reopen this issue and continue to investigate/attempt to resolve the issues.
