### ISSUE TITLE
"[...] see `arbitrary_types_allowed` in Config" error message when using `dataclass`

### ISSUE THREAD

**Issue by maltekliemann** [pydantic/pydantic#3320]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/malte/.pyenv/versions/3.8.0/Python.framework/Versions/3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.0 (default, Sep  8 2020, 20:38:09)  [Clang 11.0.3 (clang-1103.0.32.62)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

When using arbitrary types with a `dataclass`, as follows, a confusing error is raised:

```py
import pydantic


class MyClass:
    pass


@pydantic.dataclasses.dataclass
class Dataclass:
    value: MyClass
```

The error message is: ``RuntimeError: no validator found for <class '__main__.MyClass'>, see `arbitrary_types_allowed` in Config``. This would be fine, except that adding `class Config: arbitrary_types_allowed = True` to `Dataclass` doesn't change anything (is there even a `Config` for `dataclasses`?). So the fix proposed by the error doesn't work, and my contention is that the error message is incorrect.

The docs discuss arbitrary types and `dataclass`, but only in the context where a `BaseModel` validates an stdlib `dataclass`. I did not find any mention that using arbitrary types as members of a dataclass is illegal.

**Comment by aycaecemgul** [comment]
Solution above did not work for me but the [example](https://pydantic-docs.helpmanual.io/usage/model_config/#change-behaviour-globally) in the docs did:

```
from pydantic import BaseModel as PydanticBaseModel

class BaseModel(PydanticBaseModel):
    class Config:
        arbitrary_types_allowed = True

class Model(BaseModel):
    x: MyClass
```

**Comment by MaheshGowda30** [comment]
(myvenv) PS C:\Users\aethe\Desktop\work\Machine Learning Project\customer_satisfaction> python run_pipeline.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\aethe\Desktop\work\Machine Learning Project\customer_satisfaction\run_pipeline.py:8 in  │
│ <module>                                                                                         │
│                                                                                                  │
│    5 │   """                                                                                     │
│    6 │   run pipline                                                                             │
│    7 │   """                                                                                     │
│ ❱  8 │   train_pipeline(data_path=r"C:\Users\aethe\Desktop\work\Machine Learning Project\cust    │
│    9                                                                                             │
│   10                                                                                             │
│   11                                                                                             │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\new\pipelines\pipeline.py:1222 in   │
│ __call__                                                                                         │
│                                                                                                  │
│   1219 │   │   │   # pipeline. Is this what we want?                                             │
│   1220 │   │   │   return self.entrypoint(*args, **kwargs)                                       │
│   1221 │   │                                                                                     │
│ ❱ 1222 │   │   self.prepare(*args, **kwargs)                                                     │
│   1223 │   │   return self._run(**self._run_args)                                                │
│   1224 │                                                                                         │
│   1225 │   def _call_entrypoint(self, *args: Any, **kwargs: Any) -> None:                        │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\new\pipelines\pipeline.py:385 in    │
│ prepare                                                                                          │
│                                                                                                  │
│    382 │   │   │   # Enter the context manager, so we become the active pipeline. This           │
│    383 │   │   │   # means that all steps that get called while the entrypoint function          │
│    384 │   │   │   # is executed will be added as invocation to this pipeline instance.          │
│ ❱  385 │   │   │   self._call_entrypoint(*args, **kwargs)                                        │
│    386 │                                                                                         │
│    387 │   def register(self) -> "PipelineResponseModel":                                        │
│    388 │   │   """Register the pipeline in the server.                                           │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\new\pipelines\pipeline.py:1250 in   │
│ _call_entrypoint                                                                                 │
│                                                                                                  │
│   1247 │   │   │   ) from e                                                                      │
│   1248 │   │                                                                                     │
│   1249 │   │   self._parameters = validated_args                                                 │
│ ❱ 1250 │   │   self.entrypoint(**validated_args)                                                 │
│   1251 │                                                                                         │
│   1252 │   def _prepare_if_possible(self) -> None:                                               │
│   1253 │   │   """Prepares the pipeline if possible.                                             │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\pipelines\training_pipelines.py:9 in train_pipeline                │
│                                                                                                  │
│    6 from steps.evaluation import evaluate_model                                                 │
│    7 @pipeline                                                                                   │
│    8 def train_pipeline(data_path:str):                                                          │
│ ❱  9 │   df = ingest_df(data_path)                                                               │
│   10 │   clean_df(df)                                                                            │
│   11 │   train_model(df)                                                                         │
│   12 │   evaluate_model(df)                                                                      │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\steps\base_step.py:533 in __call__  │
│                                                                                                  │
│    530 │   │   │   input_artifacts,                                                              │
│    531 │   │   │   external_artifacts,                                                           │
│    532 │   │   │   parameters,                                                                   │
│ ❱  533 │   │   ) = self._parse_call_args(*args, **kwargs)                                        │
│    534 │   │                                                                                     │
│    535 │   │   upstream_steps = {                                                                │
│    536 │   │   │   artifact.invocation_id for artifact in input_artifacts.values()               │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\steps\base_step.py:457 in           │
│ _parse_call_args                                                                                 │
│                                                                                                  │
│    454 │   │   parameters = {}                                                                   │
│    455 │   │                                                                                     │
│    456 │   │   for key, value in bound_args.arguments.items():                                   │
│ ❱  457 │   │   │   self.entrypoint_definition.validate_input(key=key, value=value)               │
│    458 │   │   │                                                                                 │
│    459 │   │   │   if isinstance(value, StepArtifact):                                           │
│    460 │   │   │   │   artifacts[key] = value                                                    │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\steps\entrypoint_function_utils.py: │
│ 188 in validate_input                                                                            │
│                                                                                                  │
│   185 │   │   │   )                                                                              │
│   186 │   │                                                                                      │
│   187 │   │   try:                                                                               │
│ ❱ 188 │   │   │   self._validate_input_value(parameter=parameter, value=value)                   │
│   189 │   │   except ValidationError as e:                                                       │
│   190 │   │   │   raise RuntimeError(                                                            │
│   191 │   │   │   │   f"Input validation failed for input '{parameter.name}': "                  │
│                                                                                                  │
│ C:\Users\aethe\Desktop\work\Machine Learning                                                     │
│ Project\customer_satisfaction\myvenv\Lib\site-packages\zenml\steps\entrypoint_function_utils.py: │
│ 212 in _validate_input_value                                                                     │
│                                                                                                  │
│   209 │   │   # Create a pydantic model with just a single required field with the               │
│   210 │   │   # type annotation of the parameter to verify the input type including              │
│   211 │   │   # pydantics type coercion                                                          │
│ ❱ 212 │   │   validation_model_class = create_model(                                             │
│   213 │   │   │   "input_validation_model",                                                      │
│   214 │   │   │   __config__=ModelConfig,                                                        │
│   215 │   │   │   value=(parameter.annotation, ...),                                             │
│                                                                                                  │
│ in pydantic.main.create_model:1026                                                               │
│                                                                                                  │
│ in pydantic.main.ModelMetaclass.__new__:197                                                      │
│                                                                                                  │
│ in pydantic.fields.ModelField.infer:506                                                          │
│                                                                                                  │
│ in pydantic.fields.ModelField.__init__:436                                                       │
│                                                                                                  │
│ in pydantic.fields.ModelField.prepare:557                                                        │
│                                                                                                  │
│ in pydantic.fields.ModelField.populate_validators:831                                            │
│                                                                                                  │
│ in find_validators:765                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: no validator found for <class 'pandas.core.frame.DataFrame'>, see `arbitrary_types_allowed` in Config

**Comment by neilyoung** [comment]
> class BaseModel(PydanticBaseModel):
>     class Config:
>         arbitrary_types_allowed = True

That's the answer

**Comment by lukekhaurecon** [comment]
P.S. The accepted answer here will now give a deprecation warning

See: https://docs.pydantic.dev/2.10/migration/

**Comment by stefanodesaraca** [comment]
> Solution above did not work for me but the [example](https://pydantic-docs.helpmanual.io/usage/model_config/#change-behaviour-globally) in the docs did:
> 
> ```
> from pydantic import BaseModel as PydanticBaseModel
> 
> class BaseModel(PydanticBaseModel):
>     class Config:
>         arbitrary_types_allowed = True
> 
> class Model(BaseModel):
>     x: MyClass
> ```

This worked for me as well.
