### ISSUE TITLE
compound type (Union) gets preferentially parsed as string

### ISSUE THREAD

**Issue by amenck** [pydantic/pydantic#3321]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: /usr/local/lib/python3.7/site-packages/pydantic
               python version: 3.7.11 (default, Jul  6 2021, 12:42:50)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator']
```

```py
from pydantic.dataclasses import dataclass
from typing import Dict, Union

@dataclass
class MyDataclass:
	c: Dict[str, Union[str, bool, int]]

print(MyDataclass(c={"a": 1, "b": True, "c": "d"}))
```
output: `MyDataclass(c={'a': '1', 'b': 'True', 'c': 'd'})`
expected output: `MyDataclass(c={'a': 1, 'b': True, 'c': 'd'})`

As you can see from the repro above, it seems that the `str` component of the `Union`. If I change the order to `[bool, int, str]`, the output becomes: `MyDataclass(c={'a': True, 'b': True, 'c': 'd'})`. I'm not familiar at all with how the underlying code works, but my guess is that this is giving preference to types given their order in the `Union`. I find this behavior quite odd, especially considering that the objects in the input already conform to the types specified in the dataclass. Is this intended behavior?

**Comment by mwgamble** [comment]
> I believe this is intended. From the [Unions section of the docs](https://pydantic-docs.helpmanual.io/usage/types/#unions), emphasis mine:

The ordering of unions is supposed to be ignored:

https://github.com/python/cpython/blob/main/Lib/typing.py#L564

**Comment by tuchandra** [comment]
> > I believe this is intended. From the [Unions section of the docs](https://pydantic-docs.helpmanual.io/usage/types/#unions), emphasis mine:
> 
> The ordering of unions is supposed to be ignored:
> 
> https://github.com/python/cpython/blob/main/Lib/typing.py#L564

The ordering is ignored when a type checker is reading an annotation to determine what type a variable is. If we have `x: str | int`, then yeah, that's equivalent to `x: int | str`.

But that's not what pydantic is doing. Pydantic is a parsing library, so when it sees that a value is supposed to be parsed into a Union, it has to decide which member to use. It can't parse something into a str and int simultaneously. It uses the order to make that decision in a predictable way.

**Comment by tuchandra** [comment]
Regardless, though, looks like #2902 has landed!

**Comment by mwgamble** [comment]
> But that's not what pydantic is doing.

Yes, I eventually worked that out after hours of pulling my hair out. Unfortunately for someone who's very familiar with how mathematical unions are supposed to work, this behaviour was [extremely surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).
