### ISSUE TITLE
How to parse raw data to multiple Models based on Model definition

### ISSUE THREAD

**Issue by prutheus** [pydantic/pydantic#3350]
Hello!
I want to achieve something similar to Jackson Parsing in Java.

I have some raw data strings:

```
'{"heartbeat": 8000}'
'{"login": true, "key": "asdf"}'
...
```

Each line is one data object.
Now, I have defined two Models:

```
class Heartbeat(BaseModel):
    heartbeat: int = Field(...)
```

```
class Login(BaseModel):
    login: bool = Field(...)
    key: str = Field(...)
```

I want to iterate over my lines from the raw data. Each line should get parsed as model.
I know there is `Heartbeat.parse_raw(...)` ... but if we are on line 2, this fails.
I want a way to parse each line with the right matching model, if a line does not fit to a model, it should raise an exception.

How would this be possible?

THANKS!

**Comment by BCarley** [comment]
I don't think this is a particularly good fit for a `github` issue but I would use [`parse_obj_as`](https://pydantic-docs.helpmanual.io/usage/models/#parsing-data-into-a-specified-type)

```python
import json
import typing

import pydantic


class Heartbeat(pydantic.BaseModel):
    heartbeat: int = pydantic.Field(...)


class Login(pydantic.BaseModel):
    login: bool = pydantic.Field(...)
    key: str = pydantic.Field(...)


class Root(pydantic.BaseModel):
    __root__: typing.Union[Heartbeat, Login]


TEXT = """{"heartbeat": 8000}
{"login": true, "key": "asdf"}"""


def main():
    for idx, line in enumerate(TEXT.split("\n")):
        data = Root.parse_raw(line).__root__

        print(f"Using `__root__` method: \n {data}\n")
        if idx == 0:
            assert isinstance(data, Heartbeat)
        elif idx == 1:
            assert isinstance(data, Login)
        data = pydantic.parse_obj_as(
            typing.Union[Heartbeat, Login], json.loads(line)  # type: ignore
        )

        print(f"Using `parse_obj_as` method: \n {data}\n")
        if idx == 0:
            assert isinstance(data, Heartbeat)
        elif idx == 1:
            assert isinstance(data, Login)


if __name__ == "__main__":
    main()
```

**Comment by Kludex** [comment]
Given @BCarley reply, and the time this issue has been opened without the author's confirmation, I'll be closing the issue.
