### ISSUE TITLE
Methods decorated with `lru_cache` or `cache` don't get `self` passed as default argument on call

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#3376]
# Bug

### Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/can/.cache/pypoetry/virtualenvs/bikipy-Cb5pIUSo-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Oct 21 2021, 08:33:25)  [GCC 11.1.0]
                     platform: Linux-5.14.14-zen1-1-zen-x86_64-with-glibc2.33
     optional deps. installed: ['typing-extensions']
```

## Explanation
Whenever I use caching in a `BaseModel` derived class, the respective method doesn't get `self` passed to itself when called.

### Remarks
Notice that I was required to set `arbitrary_types_allowed` to `True` in the config, needed to use caching with decoration, otherwise an error would be thrown.

```py
from functools import lru_cache

from pydantic import BaseModel


class CacheTester(BaseModel):
    a: int = 43
    b: str = "boring"

    class Config:
        arbitrary_types_allowed = True

    @lru_cache
    def will_crash(self, var):
        return self.a, self.b, var


ct = CacheTester()
ct.will_crash(var=5)
```
Output:
```shell
Traceback (most recent call last):
  File "/home/can/Software_Projects/BiKiPy/examples/nort_belhaj_analysis/test.py", line 19, in <module>
    ct.will_crash(var=5)
TypeError: will_crash() missing 1 required positional argument: 'self'
```

### Bandage till bug fix
(I know that it looks terrible (it is), but this is production)
```py
class CacheTester(BaseModel):
    a: int = 43
    b: str = "boring"

    class Config:
        arbitrary_types_allowed = True
        frozen = True

    @lru_cache
    def will_crash(self, var):
        return self.a, self.b, var


ct = CacheTester()
ct.will_crash(self=ct, var=5)
```
Notice `self=ct`, and `frozen = True`.

### Solution
1. Make `BaseModel` require `frozen` as `True` when utilizing caching on methods.
2. Patch the caching issue, `self` **not** being the default 1st argument when respective method is called.

**Comment by caniko** [comment]
Duplicate of #2313

**Comment by ughstudios** [comment]
Was this ever addressed?

**Comment by caniko** [comment]
@ughstudios, partially #2625 as sometimes the method has no arguments other than `self` hence it being a `property`.

But no, this has issue has still not been addressed. Maybe @samuelcolvin has some ideas?

**Comment by Expan75** [comment]
A little annoying but can be easily circumvented by delegating validation logic to a method/function outside of the declared pydantic class. 

```python
import time
from pydantic import validator
from pydantic.dataclasses import dataclass
from functools import lru_cache

@lru_cache
def heavy_processing(search_term: str) -> str:
       time.sleep(10)
       return search_term

@dataclass
class User:
       name: str

       @validator("name")
       def should_exist(cls, value):
              result = heavy_processing(value)
              if result is None:
                 raise ValueError
              return result

user1 = User("Erik") # takes 10s
user2 = User("Erik") # takes 0s
```

**Comment by caniko** [comment]
@Expan75 you can also do:
```python
class MyModel(BaseModel):
    power_level: int

    def experience(self) -> float:
        @lru_cache
        def compute_experience(power_level: int) -> float:
            return power_level * 3.14
        return compute_experience(self.power_level)
```
This is still very dissatisfying! I should be able to get class attributes inside a cached method!

**Comment by hgalytoby** [comment]
> @Expan75, I don't think your example is relevant to the current issue. You are running a cached function inside a validator. Cached validator is a very interesting idea, nonetheless!
> 
> You can also do:
> 
> ```python
> class MyModel(BaseModel):
>     power_level: int
> 
>     def experience(self) -> float:
>         @lru_cache
>         def compute_experience(power_level: int) -> float:
>             return power_level * 3.14
>         return compute_experience(self.power_level)
> 
>     def alt_experience(self) -> float:
>         @lru_cache
>         def compute_experience() -> float:
>             return self.power_level * 3.14
>         return compute_experience()
> ```
> 
> This is still very dissatisfying! I should be able to get class attributes inside a cached method without the need for a wrapper, code aesthetics!

I just tested your code, I found that there is no caching effect, I wonder if I did something wrong?


try:
```python

class MyModel1(BaseModel):
    power_level: int

    def experience(self) -> float:
        @lru_cache
        def compute_experience_fail(power_level: int) -> float:
            print('compute_experience_fail')
            return power_level * 3.14

        return compute_experience_fail(self.power_level)


@lru_cache
def compute_experience_ok(power_level: int) -> float:
    print('compute_experience_ok')
    return power_level * 3.14


class MyModel2(BaseModel):
    power_level: int

    def experience(self) -> float:
        return compute_experience_ok(self.power_level)


m1 = MyModel1(power_level=123)
m1.experience()  # compute_experience_fail
m1.experience()  # compute_experience_fail
m1.experience()  # compute_experience_fail

m2 = MyModel2(power_level=123)
m2.experience()  # compute_experience_ok
m2.experience()
m2.experience()
```

**Comment by eKluev** [comment]
C'mon guys where is the solve? 3 month passed away. I have to use cached methods in Pydantic classes.

**Comment by caniko** [comment]
@Expan75:
> I just tested your code, I found that there is no caching effect, I wonder if I did something wrong?

Yes, it needs to be outside, fixing.


> C'mon guys where is the solve? 3 month passed away. I have to use cached methods in Pydantic classes.

The devs are focused on V2 I am afraid. Use my workaround for now.

**Comment by adriangb** [comment]
First off, what you are doing is dangerous: https://rednafi.github.io/python/lru_cache_on_methods/

Here's a safe version that works with Pydantic:

```python
from functools import lru_cache

from pydantic import BaseModel


@lru_cache
def func(a, b, var):
    return a * b * var


class CacheTester(BaseModel):
    a: int
    b: int

    def model_func(self, var):
        return func(self.a, self.b, var)


ct = CacheTester(a=2, b=3)
assert ct.model_func(var=5) == 2 * 3 * 5
```

**Comment by adriangb** [comment]
But also your initial example, with `frozen=True` so that `self` serves as a cache key (which is probably not what you want) works on V2:

```python
from functools import lru_cache

from pydantic import BaseModel


class CacheTester(BaseModel):
    a: int = 43
    b: str = "boring"

    class Config:
        arbitrary_types_allowed = True

    @lru_cache
    def will_crash(self, var):
        return self.a, self.b, var


ct = CacheTester()
ct.will_crash(var=5)
```

I think what you actually want is to _cache per instance_ which is going to be much more performant and simpler if you just implement `__hash__`:

```python
from functools import lru_cache

from pydantic import BaseModel


class CacheTester(BaseModel):
    a: int = 43
    b: str = "boring"

    class Config:
        arbitrary_types_allowed = True

    @lru_cache
    def will_crash(self, var):
        return self.a, self.b, var
    
    def __hash__(self):
        return id(self)


ct = CacheTester()
ct.will_crash(var=5)
```

Unfortunately we do not have the bandwidth to backport this to v1.

**Comment by caniko** [comment]
Shouldn't this be defined by default @adriangb? I don't see why not.
```python
def __hash__(self):
        return id(self)
```

**Comment by adriangb** [comment]
And override it for frozen models? That does seem reasonable. Want to make a PR and see if anything breaks?

**Comment by adriangb** [comment]
@caniko Thank you for making the PR. Unfortunately, I spoke too soon, after discussing with the team it's clear that adding a default hash is not sound. Here are a couple of reasons:
1. We already define a custom `__eq__` and indeed the behavior in Python is that if you define an `__eq__` that doesn't do identity comparison then `__hash__` shouldn't either.
2. Dataclasses are unhashable by default. I'm not sure why this choice was made but I get the feeling that there are good reasons.
3. It's easy to work around by using a custom subclass of `BaseModel` that implements `__hash__` which is already a common pattern for any large codebase to share a config, etc.
4. Your original use case is not sound and quite dangerous actually: using `@lru_cache` on instance methods leads to memory leaks because it doesn't use a weak key dict internally resulting in references to the model / `self` that prevent it from being garbage collected. So even if we could implement this change you should probably change your overall approach anyway!

**Comment by caniko** [comment]
Yes, I understand it makes sense I thought you actually thought about all of these things when you concurred. Should've been more critical :sweat_smile: 

Yes these concerns are valid! the objects that have the self LRU cache always have a persistent reference so they never get garbage collected; moreover, they will be garbage collected at the end of the runtime when the LRU is flushed; so it is not a memory leak. We don't want this to persist beyond the use of the object anyway, it is a problem nonetheless.

No matter what, I learned a lot about the inner workings of `pydantic` in the process! Thanks!
