### ISSUE TITLE
Raising ValidationError from arbitrary generic class as shown in docs does not pass mypy

### ISSUE THREAD

**Issue by LHCGreg** [pydantic/pydantic#3382]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: C:\Users\GNAJDA\AppData\Local\pypoetry\Cache\virtualenvs\pydantic-validation-error-repro-yBziGAlX-py3.7\Lib\site-packages\pydantic
               python version: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```
Here is the sample code from https://pydantic-docs.helpmanual.io/usage/types/#generic-classes-as-types, slightly modified to add some missing type annotations to satisfy mypy:

```
from pydantic import BaseModel, ValidationError
from pydantic.fields import ModelField
from typing import Callable, Iterable, TypeVar, Generic

AgedType = TypeVar("AgedType")
QualityType = TypeVar("QualityType")


# This is not a pydantic model, it's an arbitrary generic class
class TastingModel(Generic[AgedType, QualityType]):
    def __init__(self, name: str, aged: AgedType, quality: QualityType):
        self.name = name
        self.aged = aged
        self.quality = quality

    @classmethod
    def __get_validators__(cls) -> Iterable[Callable[[object, ModelField], "TastingModel"]]:
        yield cls.validate

    @classmethod
    # You don't need to add the "ModelField", but it will help your
    # editor give you completion and catch errors
    def validate(cls, v: object, field: ModelField) -> "TastingModel":
        if not isinstance(v, cls):
            # The value is not even a TastingModel
            raise TypeError("Invalid value")
        if not field.sub_fields:
            # Generic parameters were not provided so we don't try to validate
            # them and just return the value as is
            return v
        aged_f = field.sub_fields[0]
        quality_f = field.sub_fields[1]
        errors = []
        # Here we don't need the validated value, but we want the errors
        valid_value, error = aged_f.validate(v.aged, {}, loc="aged")
        if error:
            errors.append(error)
        # Here we don't need the validated value, but we want the errors
        valid_value, error = quality_f.validate(v.quality, {}, loc="quality")
        if error:
            errors.append(error)
        if errors:
            raise ValidationError(errors, cls)
        # Validation passed without errors, return the same instance received
        return v


class Model(BaseModel):
    # for wine, "aged" is an int with years, "quality" is a float
    wine: TastingModel[int, float]
    # for cheese, "aged" is a bool, "quality" is a str
    cheese: TastingModel[bool, str]
    # for thing, "aged" is a Any, "quality" is Any
    thing: TastingModel


model = Model(
    # This wine was aged for 20 years and has a quality of 85.6
    wine=TastingModel(name="Cabernet Sauvignon", aged=20, quality=85.6),
    # This cheese is aged (is mature) and has "Good" quality
    cheese=TastingModel(name="Gouda", aged=True, quality="Good"),
    # This Python thing has aged "Not much" and has a quality "Awesome"
    thing=TastingModel(name="Python", aged="Not much", quality="Awesome"),
)
print(model)
```

When running mypy on this code, I get the error

```
pydantic_validation_error_repro\repro.py:43: error: Argument 2 to "ValidationError" has incompatible type "Type[TastingModel[AgedType, QualityType]]"; expected "Union[Type[BaseModel], Type[Dataclass]]"
Found 1 error in 1 file (checked 2 source files)
```

Since this code sample is from the docs, I assume it is intentional that you can use classes do not inherit from BaseModel and are not dataclasses in this way. Should ValidationError's constructor's model parameter annotation be loosened to just `object`?

I can work around this by casting `cls` to `Type[BaseModel]` when constructing a `ValidationError` but I'd prefer to not have to lie to mypy.

**Comment by hramezani** [comment]
@LHCGreg sorry for the late response. we were (and still are) working on `Pydantic V2`.
As you may know, `Pydantic V2` is in alpha state and you can install the latest alpha (`v2.0a3`) by `pip install pydantic --pre`
Could you please try to rewrite this example with `Pydantic V2` and test it? I think it got fixed in `V2`.
BTW, if you see any problem with `V2`. Feel free to open a new issue.

**Comment by LHCGreg** [comment]
@hramezani The reproduction code does not work as is in pydantic 2.0a3. The following mypy errors are reported:

```
pydantic_validation_error_repro\repro.py:2: error: Module "pydantic.fields" has no attribute "ModelField"  [attr-defined]
pydantic_validation_error_repro\repro.py:43: error: Argument 1 to "ValidationError" has incompatible type "List[Any]"; expected "str"  [arg-type]
pydantic_validation_error_repro\repro.py:43: error: Argument 2 to "ValidationError" has incompatible type "Type[TastingModel[AgedType, QualityType]]"; expected "List[InitErrorDetails]"  [arg-type]
```

I could not find any documentation for V2 other than the brief migration notes at https://docs.pydantic.dev/latest/blog/pydantic-v2-alpha/ so I'm not sure what the correct V2 equivalent of this code is.

However, it looks like the signature of `ValidationError`'s constructor is now `def __init__(self, title: str, errors: list[InitErrorDetails], error_mode: Literal['python', 'json'] = 'python') -> None` so it does not take a Type anymore, which is where the problem was before, so I guess it's fixed now. It is also "fixed" in the sense that part of the problem was an example in the docs having a type checker error, and now there are no docs (yet).

**Comment by hramezani** [comment]
@LHCGreg Thanks for checking.
Yeah, the documentation is not good yet but we are working on it and it will improve
