### ISSUE TITLE
Type resolution of the pydantic Json type returns Any

### ISSUE THREAD

**Issue by Goldziher** [pydantic/pydantic#3415]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

I am building a library on top of pydantic, and I am using the typing resolution of pydantic. It all works as intended except the Json type, which is resolved as any. [](url)

In my test I have the following class

```
from pydantic import BaseModel

class MyModel(BaseModel):
        # ....
        Json_pydantic_type: Json
        
```

If I now inspect `MyModel.__fields__` and look at how `Json_pydantic_type`, i will see that it is defined as a type `Any`.

Please see the following video:

https://user-images.githubusercontent.com/30733348/141681541-b9e20132-d8ec-4a4b-8de6-a379dffe7616.mov

**Comment by Kludex** [comment]
The behavior changed on V2.

With the following snippet:
```python
from pydantic import BaseModel, Json

class MyModel(BaseModel):
        # ....
        Json_pydantic_type: Json

print(MyModel.model_fields)  # instead of `__fields__` use `model_fields`
```

You'll have this output:
```py
{'Json_pydantic_type': FieldInfo(annotation=Json, required=True)}
```

Given that we have this sorted out on V2, I'll be closing this issue. If my understanding is wrong, please let me know, and I'll reopen it.
