### ISSUE TITLE
Hypothesis plugin raises ZeroDivisionError for no apparent reason

### ISSUE THREAD

**Issue by Goldziher** [pydantic/pydantic#3418]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
...
```

I'm developing a library using pydantic. While testing some code with hypothesis, i encountered an error stemming from the pydantic plugin - which i do not actually use. It seems though that its enough I am using hypothesis + pydantic builtin functions to fire it. 

if in the below test, multiple_of is 0 an error will occur

```python
@given(
    floats(allow_nan=False, allow_infinity=False, min_value=-1000000000, max_value=1000000000),
    floats(allow_nan=False, allow_infinity=False, min_value=-1000000000, max_value=1000000000),
)
def test_handle_constrained_float_handles_multiple_of_with_lt(val1, val2):
    multiple_of, max_value = sorted([val1, val2])
    if multiple_of < max_value:
        result = handle_constrained_float(confloat(multiple_of=multiple_of, lt=max_value), faker)
        assert result % multiple_of == 0 if multiple_of != 0 else True
    else:
        with pytest.raises(AssertionError):
            handle_constrained_float(confloat(multiple_of=multiple_of, lt=max_value), faker)
```

The stack trace I am getting is:

```
pydantic/types.py:291: in pydantic.types.confloat
    ???
pydantic/types.py:148: in pydantic.types.ConstrainedNumberMeta.__new__
    ???
pydantic/_hypothesis_plugin.py:196: in pydantic._hypothesis_plugin._registered
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   ZeroDivisionError: float division by zero

pydantic/_hypothesis_plugin.py:298: ZeroDivisionError
```

Note, my own code handles zeros without raising an error at all - and the following test works without issue:

```python
def test_handle_constrained_float_handles_multiple_of_zero_value():
    assert handle_constrained_float(confloat(multiple_of=0), faker) == 0
```

**Comment by danelkay93** [comment]
I second this. This occurs without even using the floats strategy, or builds on a Pydantic Model with float fields. Just importing hypothesis.given with the Pydantic plugin active causes it.

**Comment by samuelcolvin** [comment]
Cc @Zac-HD

**Comment by danelkay93** [comment]
Python 3.10.4 with hypothesis 6.45.0 and pydantic 1.9.0:

```
from hypothesis import given
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
/usr/local/lib/python3.10/site-packages/hypothesis/__init__.py:56: in <module>
    run()
/usr/local/lib/python3.10/site-packages/hypothesis/entry_points.py:63: in run
    hook = entry.load()
/usr/local/lib/python3.10/importlib/metadata/__init__.py:171: in load
    module = import_module(match.group('module'))
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pydantic/_hypothesis_plugin.py:362: in init pydantic._hypothesis_plugin
    ???
pydantic/_hypothesis_plugin.py:196: in pydantic._hypothesis_plugin._registered
    ???
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/core.py:1809: in register_type_strategy
    elif isinstance(strategy, SearchStrategy) and strategy.is_empty:
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py:134: in accept
    recur(self)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py:130: in recur
    mapping[strat] = getattr(strat, calculation)(recur)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:88: in calc_is_empty
    return recur(self.wrapped_strategy)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py:130: in recur
    mapping[strat] = getattr(strat, calculation)(recur)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py:607: in calc_is_empty
    return all(recur(e) for e in self.original_strategies)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py:607: in <genexpr>
    return all(recur(e) for e in self.original_strategies)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/strategies.py:130: in recur
    mapping[strat] = getattr(strat, calculation)(recur)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:88: in calc_is_empty
    return recur(self.wrapped_strategy)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/lazy.py:108: in wrapped_strategy
    base = self.function(*self.__args, **self.__kwargs)
/usr/local/lib/python3.10/site-packages/hypothesis/strategies/_internal/numbers.py:359: in floats
    raise FloatingPointError(
E   FloatingPointError: Got allow_subnormal=True, but we can't represent subnormal floats right now, in violation of the IEEE-754 floating-point specification.  This is usually because something was compiled with -ffast-math or a similar option, which sets global processor state.  See https://simonbyrne.github.io/notes/fastmath/ for a more detailed writeup - and good luck!
```

The bandaid fix that I'm using for now is using [daz](https://github.com/chainer/daz):
```
import daz
daz.unset_ftz()
daz.unset_daz()
```

**Comment by Zac-HD** [comment]
Oh boy, this is going to be a fun one.

- denormals-are-zero violates IEEE-754 semantics, and there's no solution short of tracking down the evil compiler option and turning it back off - as https://simonbyrne.github.io/notes/fastmath/ notes, simply loading a shared library can change the results in completely unrelated code!

- `multiple_of=0` is inherently invalid, because [the jsonschema standard *defines `multipleOf` in terms of division*](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.2.1).  Since we're now in the position of dealing with absurdity, the best option for Pydantic is probably to either:
  - raise an error on `multiple_of=0` which explains this issue, or
  - silently convert it to a constrained number which must be equal to zero based on min and max values

For @Goldziher's test, I would just add `from hypothesis import assume` and `assume(multiple_of != 0)` to reject invalid examples.  

(after which you'll discover that the modulo approach to multiple_of gives different results, but that's a whole separate semantic issue for whoever has to write that test.  `hypothesis-jsonschema` was *not an easy project* 😬)

**Comment by danelkay93** [comment]
@Zac-HD If a stack is based on widely-used Docker images, and the PyPi version of both pydantic and Hypothesis, how would you suggest avoiding the error, at least only on import (avoiding usage of floats)?

**Comment by Zac-HD** [comment]
If "the error" is multiple-of-zero, you could write a PR for Pydantic as I suggest above.  If "the error" is denormals-are-zero, I'd suggest using images that don't compile with unsafe math flags.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
