### ISSUE TITLE
`BaseModel.schema()` raises exception when it contains a frozen dataclass

### ISSUE THREAD

**Issue by rsayn** [pydantic/pydantic#3469]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/{username}/Library/Caches/pypoetry/virtualenvs/{virtualenv_name}-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.12 (default, Nov  4 2021, 13:59:45)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-11.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
import pydantic
import dataclasses

@dataclasses.dataclass(frozen=True)
class ParentClass:
    child: ChildClass

@dataclasses.dataclass(frozen=True)
class ChildClass:
    name: str

class WrapperModel(pydantic.BaseModel):
    parent: ParentClass

# Test 1: create schema from the wrapper class
print(WrapperModel.schema()) # raises "TypeError: cannot inherit non-frozen dataclass from a frozen one"

# Test 2: convert child class to Pydantic and create schema
PydanticChild = pydantic.dataclasses.dataclass(ChildClass) # raises "TypeError: cannot inherit non-frozen dataclass from a frozen one"

# Test 3: add "frozen" when converting
PydanticChild = pydantic.dataclasses.dataclass(ChildClass, frozen=True) # works okay
print(PydanticChild.__pydantic_model__.schema()) # works okay

# Test 4: add "frozen" on parent conversion
PydanticParent = pydantic.dataclasses.dataclass(ParentClass, frozen=True) # works okay
print(PydanticParent.__pydantic_model__.schema()) # raises "TypeError: cannot inherit non-frozen dataclass from a frozen one"

# Test 5: simply use the WrapperModel class
model = WrapperModel(parent=ParentClass(child=ChildClass(name='hello'))) # works okay

```

The error message is quite confusing here, since no inheritance is explicitly performed by the user.
I think this issue is due to some instruction inside `BaseModel.schema()` trying to convert the native dataclass into a Pydantic dataclass without taking into account the `frozen` argument.

**Comment by Kludex** [comment]
This is interesting. 🤔 I'm testing this on V2, and...  

The following code raises `TypeError`:

```python
import pydantic
import dataclasses


@dataclasses.dataclass(frozen=True)
class ChildClass:
    name: str


# my_dataclass = dataclasses.dataclass(ChildClass)
another_dataclass = pydantic.dataclasses.dataclass(ChildClass)
```

If I uncomment the commented line, then it works. 🤔

Do you have any idea what could be happening @dmontagu ?

**Comment by dmontagu** [comment]
@Kludex the following works as the last line in your snippet:
```python
another_dataclass = pydantic.dataclasses.dataclass(frozen=True)(ChildClass)
```

Maybe we need to be better about inferring the dataclass kwargs better when wrapping with pydantic dataclass? Not sure

**Comment by Kludex** [comment]
> Maybe we need to be better about inferring the dataclass kwargs better when wrapping with pydantic dataclass? Not sure

It does look like. I mean, I was a bit surprised with the behavior from my snippet.

I've added the label "Feedback wanted" to see what others have to say... 🙏

**Comment by dmontagu** [comment]
For what it's worth, I think a PR addressing this would be welcome. I'm not sure if/where `@dataclasses.dataclass` stores its configuration on the class but if you can find it I think we could attempt to use the values.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
