### ISSUE TITLE
Mypy plugin does not understand ternary operators: 'Invalid value for "Config.extra"  [pydantic-config]'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pydantic/pydantic#3481]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Code
```python
from .my_local_file import SOME_CONDITION

from pydantic import BaseModel, Extra


class Foo(BaseModel):
    # model attributes does not matter
    bar: str

    class Config:
        extra = Extra.forbid if SOME_CONDITION else Extra.allow
```

# Error
```python
error: Invalid value for "Config.extra"  [pydantic-config]
```

# Steps to reproduce

Run Mypy check, e.g. `pre-commit run mypy --all-files`.

# Versions
pydantic 1.8.2
Python 3.8

# Temporary workarounds
Either use `# type: ignore[pydantic-config]` comment to suppress the warning, or refactor ternary operator into IF / ELSE statements.

**Comment by adriangb** [comment]
This runs with `mypy --strict` on Pydantic V2 with no errors. Since we will be directing most energy towards V2 going forward I'm going to close this issue. Please upgrade to Pydantic V2 and try again.
