### ISSUE TITLE
Validators not recognized as class methods by mypy

### ISSUE THREAD

**Issue by jwodder** [pydantic/pydantic#3489]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/jwodder/.local/virtualenvwrapper/venvs/tmp-6f28d3440ecc68d/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 21 2021, 03:23:42)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-11.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Consider the following code:

```py
from pydantic import BaseModel, validator

class Foo(BaseModel):
    bar: str

    @validator("bar")
    def _validate(cls, v: str) -> str:
        if v == cls.__name__:
            raise ValueError("Pick something else")
        return v

print(Foo(bar="bar"))
print(Foo(bar="Foo"))
```

This works, but when mypy 0.910 is run on the code with the following config file:

```ini
[mypy]
plugins = pydantic.mypy
```

the code fails to type-check with the error "`"Foo" has no attribute "__name__"`".  Apparently, mypy fails to detect that `_validate` is a classmethod, i.e., that `cls` is `Foo` rather than an instance of `Foo`.

While this can be solved by inserting `@classmethod` after (but not before!) the `@validator` decorator, it's unclear whether such use is supported by pydantic, and either way, I don't think it's intended to be necessary.

**Comment by lig** [comment]
@jwodder thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by jmuddle-via** [comment]
@lig I can confirm that I have seen this issue with Pydantic V2.

To resolve it, I added the classmethod decorator.
```python
    @validator("class_name", pre=True, always=True)
    @classmethod
    def set_class_name(cls, v: str) -> str:
```
