### ISSUE TITLE
PR checking action

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#3500]
We need an action to check the the following are correct on PRs:
* The change description exists and is correctly named and formatted (we can't be too exact on formatting correctness)
* The issue used in the change description is referenced in the body of the PR (if applicable) and visa versa
* If an issue is referenced in the change description, it's prefixed by "fix" etc. in the PR body
* all the tick boxes are ticked.
* issue IDs are not used in the PR title - this is a person annoyance of mine.

This will need to be a new custom action, would be great if someone else could work on it? :crossed_fingers:

**Comment by amirkdv** [comment]
@samuelcolvin I took a stab at this! Let me know what you think of the general approach below and some workflow details bookmarked in the PR.

------

**Overview**

* New workflow with one action that runs a bunch of PR checks and posts a comment if either fail.
* Achieving the goals you listed needs a markdown parser. I used [readthedocs/commonmark.py] to go from markdown to html and [beautifulsoup] for navigating the html DOM.
* Lastly, there's the algo for extracting semantic "sections" from a flat DOM tree. Roughly, everything between two consecutive headings becomes a section.

[readthedocs/commonmark.py]: https://github.com/readthedocs/commonmark.py
[beautifulsoup]: https://pypi.org/project/beautifulsoup4/

**Standalone Use**

To test the Python script independently without having to trigger actions:
```sh
(venv) $ pip install -r .github/workflows/requirements.txt
(venv) $ GITHUB_TOKEN=... .github/workflows/pr-check samuelcolvin/pydantic 3222
# Thank you for opening a Pull Request!
# 
# Before assigning it for review, please fix the following issue(s):
# 
# - PR titles shouldn't contain issue IDs, found: '#1497'.
# - Issue refs should use valid linking verbs like 'fixes #N'.
```

**In Action**

To see the action doing its job see this [dummy PR](https://github.com/amirkdv/pydantic/pull/1).

**Spec Question**

> The change description exists and is correctly named and formatted (we can't be too exact on formatting correctness)
> The issue used in the change description is referenced in the body of the PR (if applicable) and visa versa

Are these about the `changes/*.md`? I haven't touched these yet.

**External action repo?**

What if we carve out all the markdown parsing and DOM munging into a standalone docker action repo (a la [label-and-assign]) that makes no assumptions about pydantic and its current PR template? It could produce a JSON like this:
```json
{
  "Change summary": "<p> Lorem ipsum ... </p>",
  "Checklist": "<ul> <li> [ ] to do </li> </ul>",
  "..."
}
```

where the keys are headings and values are HTML markup for a section (we'd still need to parse the html here). That way I can also use pydantic in the new code without it getting weird!

[label-and-assign]: https://github.com/samuelcolvin/label-and-assign/

**Comment by samuelcolvin** [comment]
Your work on the PR looks awesome, thank you.

I'll reply in detail on the PR.

**Comment by samuelcolvin** [comment]
Done, see https://github.com/pydantic/hooky
