### ISSUE TITLE
Extra.forbid hides existing additionalProperties on models with __root__: Dict

### ISSUE THREAD

**Issue by tsnowlan** [pydantic/pydantic#3505]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /dist/app/lib/python3.7/site-packages/pydantic
               python version: 3.7.5 (default, Feb 23 2021, 13:22:40)  [GCC 8.4.0]
                     platform: Linux-5.11.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions']

             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /home/user/miniconda3/envs/foo/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 | packaged by conda-forge | (default, Oct 12 2021, 21:24:28) [GCC 9.4.0]
                     platform: Linux-5.11.0-40-generic-x86_64-with-glibc2.31
     optional deps. installed: ['email-validator', 'typing-extensions']
```

## Description

We use a custom BaseModel that, among other things, has `Config.extra = Extra.forbid` by default. I noticed however that key schema details were being omitted from subclasses that use a custom `__root__: Dict[Foo, Bar]`. I eventually discovered that the extended schema data (`additionalProperties`) was hidden only when `Extra.forbid` was set. `Extra.ignore` and `Extra.ok` had no effect.

### Sample code

```py

import json
from typing import Dict, List
from pydantic import BaseModel, Extra


def print_schema(model):
    print(f"Model: {model.__name__}")
    print(f"Annotations: {model.__annotations__['__root__']}")
    print(f"Schema:\n{json.dumps(model.schema(), indent=2)}\n")


class DictModel(BaseModel):
    __root__: Dict[str, List[int]]


class ForbiddenDict(DictModel):
    class Config:
        extra = Extra.forbid


print_schema(DictModel)
print_schema(ForbiddenDict)
```

### Sample output

```
Model: DictModel
Annotations: typing.Dict[str, typing.List[int]]
Schema:
{
  "title": "DictModel",
  "type": "object",
  "additionalProperties": {
    "type": "array",
    "items": {
      "type": "integer"
    }
  }
}

Model: ForbiddenDict
Annotations: typing.Dict[str, typing.List[int]]
Schema:
{
  "title": "ForbiddenDict",
  "type": "object",
  "additionalProperties": false
}
```

I understand the general logic of disabling `additionalProperties` when [extra is forbidden](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/schema.py#L640), but I think this should either not override any settings that already exist. Or, alternatively, if there is an existing value and a custom root is being used.

As a workaround, I've individually set `Config.extra = Extra.ignore` on each of these models, but this is not an ideal solution.

**Comment by Kludex** [comment]
Given the comment on https://github.com/pydantic/pydantic/pull/3506#issuecomment-1206501602, I'll be closing this.

Please try V2, and if the behavior doesn't satisfy you, please create a new issue. 🙏
