### ISSUE TITLE
pydantic.error_wrappers.ValidationError: cannot parse boolean value in WSL

### ISSUE THREAD

**Issue by msi1427** [pydantic/pydantic#3521]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
Loading .env environment variables…
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /mnt/i/Leadbook/scoring_model/env/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 16 2021, 03:05:18)  [GCC 7.5.0]
                     platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.27
     optional deps. installed: ['dotenv', 'typing-extensions']
```

We are deploying a uvicorn app from WSL. But when we do that, we get `pydantic.error_wrappers.ValidationError` which further says `value could not be parsed to a boolean (type=type_error.bool)`. However, this problem does not occur in Linux or macOS.
```py
from pydantic import BaseSettings
class Settings(BaseSettings):
    debug: bool = False
...
```

**Comment by kenzo47** [comment]
I encountered this bug as well. I deleted my project, cloned it again from github, made a new virtual environment and installed the requirements.txt and this fixed my issue.

**Comment by dmontagu** [comment]
Based on @kenzo47's comment I'm going to assume this was an issue with the environment and close this issue.

If you (or others) are still having this problem, I think we would need a more detailed description of how to reproduce the issue in order to attempt to resolve it.

**Comment by tanjucat** [comment]
I see the validation error consistently (even in fresh env creation etc.) where pydantic is installed via langroid on macOS. 
ref: https://github.com/langroid/langroid/issues/594
