### ISSUE TITLE
Field with `__root__: List` serialzed to empty dict if exclude_defaults=True

### ISSUE THREAD

**Issue by mike0sv** [pydantic/pydantic#3524]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
If you have a list-like model with `__root__: List` annotation with default value and this model is used as a nested field in another model, on `.dict(exclude_defaults=True)` call on parent model the value of this field is serialized to `{}`, not `[]` (see example below).

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /Users/mike0sv/miniconda3/envs/mlem/lib/python3.7/site-packages/pydantic
               python version: 3.7.11 (default, Jul 27 2021, 07:03:16)  [Clang 10.0.0 ]
                     platform: Darwin-21.1.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']

```

```py
from typing import List

from pydantic import BaseModel, parse_obj_as


class ListLike(BaseModel):
    __root__: List[str] = []


class Model(BaseModel):
    field: ListLike


if __name__ == '__main__':
    obj = Model(field=ListLike())
    payload = obj.dict(exclude_defaults=True)
    # payload = {'field': {}}
    parse_obj_as(Model, payload)
    # pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[Model]
    # __root__ -> field -> __root__
    #   value is not a valid list (type=type_error.list)
```

I investigated a bit, and it seems this happens in `BaseModel._get_value`
https://github.com/samuelcolvin/pydantic/blob/d36bb74e83f5c8f1fd073d39d935f34876af6da4/pydantic/main.py#L705
If `exclude_defaults=False`, `v_dict` has value `{"__root__": []}` and everything is ok. And if `exclude_defaults=True`, `__root__` field is excluded, `v_dict` has value of `{}`, check for `ROOT_KEY` is skipped and empty `v_dict` itself is returned.

**Comment by hramezani** [comment]
We are going to implement a `RootModel` instead of recommending `__root__` on V2.

I'll let this issue open until we implement the RootModel.

**Comment by Kludex** [comment]
Since we now have the [`RootModel`][rootmodel] on V2, I'll close this issue.

[rootmodel]: https://docs.pydantic.dev/latest/usage/models/#rootmodel-and-custom-root-types
