### ISSUE TITLE
Annotations of the base class lost in the "create_model" function.

### ISSUE THREAD

**Issue by ilyaTT** [pydantic/pydantic#3557]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /opt/miniconda3/envs/fastapi_test/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0]
                     platform: Linux-4.19.0-16-amd64-x86_64-with-glibc2.28
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```py
from pydantic import BaseModel, create_model

class A(BaseModel):
    i1: int
    s1: str

assert A.__annotations__ == {'i1': int, 's1': str}


class B(A): ...

assert B.__annotations__ == {'i1': int, 's1': str}


C = create_model('C', __base__=A)
try:
    assert C.__annotations__ == {'i1': int, 's1': str}
except AssertionError:
    print(C.__annotations__)

```

**Comment by dmsfabiano** [comment]
Was there an update on this? still happens today

**Comment by dmontagu** [comment]
For what it's worth, I looked into the behavior in v2 and v1.10.7:

```python
from pydantic import BaseModel, create_model

class A(BaseModel):
    i1: int
    s1: str
assert A.__annotations__ == {'i1': int, 's1': str}

class B(A): ...
assert B.__annotations__ == {}

C = create_model('C', __base__=A)
assert C.__annotations__ == {}
```

This is how it works for "standard" types:

```python
class A:
    i1: int
    s1: str
assert A.__annotations__ == {'i1': int, 's1': str}


class B(A): ...
assert B.__annotations__ == {}
```

So I would consider this issue resolved, in the sense that pydantic models now behaves the same as any other class. (As far as I can tell?)

If you need the annotations for all fields, you may be able to do something with (in v1) `{k: v.type_ for k, v in MyModel.__fields__.items()}`. (And I think the analogous thing in v2 would be `{k: v.annotation for k, v in MyModel.model_fields.items()}`)
