### ISSUE TITLE
Alias ignored on custom root type

### ISSUE THREAD

**Issue by Okonos** [pydantic/pydantic#3560]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /home/user/.local/share/virtualenvs/pydanticvenv/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, Nov 18 2021, 16:00:48)  [GCC 10.3.0]
                     platform: Linux-5.11.0-41-generic-x86_64-with-glibc2.33
     optional deps. installed: ['typing-extensions']
```

The provided snippet works fine on `1.7.4`, but does not on `1.8.x`.
`git bisect` points to #2238 as first bad commit. The culprit seems to be the `validate` method, where value is wrapped with the dict under `ROOT_KEY`, leading to validation error.

```py
from pydantic import BaseModel, Field


class NestedModel(BaseModel):
    __root__: int = Field(..., alias='x')


class MyModel(BaseModel):
    v: NestedModel


MyModel(**{'v': {'x': 2}})
# pydantic.error_wrappers.ValidationError: 1 validation error for MyModel
# v -> x
#   field required (type=value_error.missing)
```

**Comment by Kludex** [comment]
Since this is stale, I'll be closing it. Sorry for the long delay.

I don't think the behavior you describe was ever supposed to be supported, since you can achieve it with the following:

```py
from pydantic import BaseModel
from typing_extensions import TypedDict


class NestedModel(TypedDict):
    x: int


class MyModel(BaseModel):
    v: NestedModel


MyModel(**{"v": {"x": 1}})
```

Hope this is enough. If not, please open a new issue. 🙏
