### ISSUE TITLE
Pydantic converts 'list' and 'set' to 'list_iterator' and 'set_iterator' objects. 'collections.abc.Iterable' as type hint must be either explicitly forbidden or supported by Pydantic

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pydantic/pydantic#3581]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0a2
            pydantic compiled: False
                 install path: /projects/project/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.1 (main, Dec 21 2021, 17:46:38) [GCC 9.3.0]
                     platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```
# Problem

I use `Iterable` as a type hint and I pass `list` or `set` as arguments, but I get back `list_iterator` or `tuple_iterator`. 

This Pydantic behavior makes it easy to introduce bugs in a code.

# Reproducible code sample

```py
from collections.abc import Iterable

from pydantic import BaseModel


class Foo(BaseModel):
    bars: Iterable[str]


foo = Foo(bars=["spam", "eggs"])
print(foo.dict())

foo_2 = Foo(bars=("spam", "eggs"))
print(foo_2.dict())
```

Run output:
```
{'bars': <list_iterator object at 0x7f2e3662ab90>}
{'bars': <tuple_iterator object at 0x7f2e361af190>}
```

# Expected behavior

### Another option:

  Output must be:
```python
{'bars': ["spam", "eggs"]}
```

(not `{'bars': <list_iterator object at 0x7f2e3662ab90>}` as I get now).

**Comment by MentalBlood** [comment]
I have found that typing field as `typing.Sequence[str] | typing.Iterable[str]` kinda solves the problem. It's interesting that order matters, so using `typing.Iterable[str] | typing.Sequence[str]` will still convert sequence to iterable using `__iter__`

**Comment by dmontagu** [comment]
This behavior remains in v2 — the way it has been implemented, we convert items passed to fields of type `Iterable` into a generator, and validate as items are iterated over. This is useful for handling objects that you can't iterate over eagerly (such as infinite generators).

 If this behavior is a problem for you, please open a feature request requesting a change in this behavior; you'll need to suggest an alternative approach that also handles generators nicely (I can imagine some, such as calling `__iter__` and then deciding what to ultimately return based on whether the resulting value is an instance of `Sequence` or not).

I think @MentalBlood's suggestion of using `typing.Sequence[str] | typing.Iterable[str]` as the annotation may be a good workaround if you want to preserve the sequence-ness of the attributes used to instantiate your model.
