### ISSUE TITLE
Cannot set default in subclass with subscripted generic hint (eg: Union)

### ISSUE THREAD

**Issue by JacobHayes** [pydantic/pydantic#3620]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: <some venv>
               python version: 3.9.7 (default, Nov 15 2021, 13:16:09)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-12.0.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

When checking the default field value on a subclass, we call `lenient_issubclass` (and thus `issubclass`) with the original type hint - which errors if that is a subscripted generic such as `Union[int, str]`:

```py
from typing import Union

from pydantic import BaseModel

class A(BaseModel):
    x: Union[int, str]

class B(A):
    x = "hi"  # 1.9.0 - TypeError: Subscripted generics cannot be used with class and instance checks
```

This wasn't supported before https://github.com/samuelcolvin/pydantic/pull/3018 / 1.9.0 anyway (one would have had to explicitly set the type hint in the subclass - which still works, so no regression), but I missed that `lenient_issubclass` doesn't handle `Union`/generics. Apologies for not getting around to testing this out before 1.9.0. :/

--

I'm happy to take a crack at fixing, but what is the best approach? At the simplest, should `lenient_issubclass` be made smarter to (at least) support `Union`s?

cc @PrettyWood as reviewer on https://github.com/samuelcolvin/pydantic/pull/3018

**Comment by adriangb** [comment]
Your example works on V1.10.X, so it seems like it got fixed at some point.

For Pydantic V2 though we require explicit type hints on all fields, including overrrides, so you'll have to do:

```python
from typing import Union

from pydantic import BaseModel


class A(BaseModel):
    x: Union[int, str]

class B(A):
    x: Union[int, str] = "hi"
```

**Comment by JacobHayes** [comment]
> For Pydantic V2 though we require explicit type hints on all fields

Is there a way I can request (or help implement) this not be required on subclasses for fields already defined (or maybe an explanation of the motivation I missed)? 😅 I'm working on a library that expects users to subclass some base classes defined in the library and requiring it would add a lot of stutter to the end users' code.

**Comment by adriangb** [comment]
@samuelcolvin do you remember why we went back to the old behavior?
