### ISSUE TITLE
Pydantic config management access variable in same class with environment variable

### ISSUE THREAD

**Issue by anandtripathi5** [pydantic/pydantic#3632]
I have config like below

```
class NewConfig(BaseSettings):
    test_config: str = ''
    another_config = test_config+'asd'


```
I'm exporting test_config as` export test_config=hello`
and doing
```
config = NewConfig()
print(config.another_config) # This should print 'helloasd' But it is printing 'asd'
```

**Comment by Plozano94** [comment]
I'm not an expert on pydantic, but I don't think you can put a default value based in other one that way. The behavior you saw is caused because bringing the value from the environment variable is done when the __init__ of the superclass is reached, and your expression of "another_config" is evaluated before. This example could achive what you are trying:

 ```

from pydantic import BaseSettings

class NewConfig(BaseSettings):
    test_config: str = ''
    another_config: str = ''

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.another_config = self.test_config + 'asd'

config = NewConfig()
print(config.another_config) 
```

I hope it helps.

**Comment by hramezani** [comment]
It's possible to do this in `Pydantic V2` and `pydantic-settings`.

As you may know, `pydantic-settings` is now a separate package and is in alpha state now. you can install it by `pip install pydantic-settings --pre`.

Here is your provided example in `pydantic-settings`:
```py
from pydantic.decorators import model_validator
from pydantic_settings import BaseSettings


class NewConfig(BaseSettings):
    test_config: str = ''
    another_config: str = ''

    @model_validator(mode='before')
    @classmethod
    def val_model(cls, values, info):
        values['another_config'] = values.get('another_config', '') + 'asd'
        return values
```
