### ISSUE TITLE
pydantic is beyond fantastic

### ISSUE THREAD

**Issue by jessekrubin** [pydantic/pydantic#3633]
I have no bug to report. 

I am just here to say that pydantic is THE BEST PYTHON LIBRARY I have ever used.

If I had to pick just one python library to take with me to a desert island, it would be pydantic. I use pydantic for everything and it has changed the way I write python; it kicks an unbelievable amount of ass.

@samuelcolvin, et al, great work! keep it up!

**Comment by frediy** [comment]
I'm having the same problem. It's just too good. Some times I can't even sleep at night, because all I can think of is how awesome pydantic is.

**Comment by marianhlavac** [comment]
![](https://media.giphy.com/media/cYRQWBrPipB7aWa4dD/giphy.gif)

**Comment by Kludex** [comment]
Yey! 😁🎉

On behalf of the team, thank you for the kind words! 🙏

**Comment by samuelcolvin** [comment]
Thanks so much, and so sorry I never replied to this one.
