### ISSUE TITLE
List/Dict object passed to model is copied instead of kept as reference

### ISSUE THREAD

**Issue by lindycoder** [pydantic/pydantic#3664]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /***/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 26 2021, 20:52:48)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-12.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

HI!

This _may_ be a documentation issue, I'm trying to pass a **reference** to a `list` in a `BaseModel` constructor and it seems the list is copied.  (See code below)

This might be related to #3565 and a side-effect of the validation.

Is it the expected behaviour?
If not, what would be the good approach to make a list field accept a reference (with or without validation)?

I can understand the intent that the list is "not managed by pydantic"-ish ensuring values are still legit, but tampering with the copied list afterward does not trigger validation anyway.

```py
from typing import List
from pydantic import BaseModel

class Model(BaseModel, copy_on_model_validation=False):
    some_list: List[str]

a_list = [1, 2, 3]
model = Model(some_list=a_list)

a_list.append(4)
print(model.some_list)
>>> ['1', '2', '3']
```
expected:
```
>>> ['1', '2', '3', '4']
```

**Comment by lindycoder** [comment]
The same "idea" with a model does not copy the object and does pass the reference it would seem.
```
from pydantic import BaseModel

class RefModel(BaseModel):
    name: str

class Model(BaseModel):
    ref: RefModel

ref = RefModel(name='Foo')
model = Model(ref=ref)

ref.name = 'Bar'

print(model.ref)
>>> name='Bar'
```
So this is good.

**Comment by hramezani** [comment]
I think the behavior in your first example is expected because `a_list` and `model.some_list` are not the same
