### ISSUE TITLE
`dataclass`es with a base in a different file evaluate the `ForwardRef`s of the base type in the namespace of the sub type, not the base type

### ISSUE THREAD

**Issue by DetachHead** [pydantic/pydantic#3666]
Reraising #1668.
this issue was closed a year ago but the error still occurs in the latest version (1.9.0) 

It looks like when the subtype is in the same file, `ForwardRef`s are automatically resolved, but when they are in a different file you are presented with `field "x" not yet prepared so type is still a ForwardRef, you might need to call X.update_forward_refs().`.

But when you call `X.__pydantic_model__.update_forward_refs()` you can get `NameError: name 'Y' is not defined`. I believe this is due to Pydantic using the wrong namespace to evaluate the forward refs of the base types.

Thanks @KotlinIsland for minifying this.

**Comment by KotlinIsland** [comment]
a.py:
```py
from __future__ import annotations

from typing import Literal
from pydantic.dataclasses import dataclass


@dataclass
class Foo:
    a: Literal["hi"]
```

b.py:
```py
from pydantic.dataclasses import dataclass
from a import Foo



@dataclass
class Bar(Foo):
    pass


Bar.__pydantic_model__.update_forward_refs()  # NameError: name 'Literal' is not defined
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, PR welcome to fix this. (No idea how hard/easy a fix would be).

**Comment by treykeown** [comment]
Bumped #6387, also bumping this now that pep695 has landed in 3.12

**Comment by DetachHead** [comment]
@treykeown that PEP695 is for the new type parameter syntax. did you mean a different PEP?

**Comment by treykeown** [comment]
Quoting @samuelcolvin from the other issue:
> I don't see an easy way to solve this until we get pep695
> 
> It's a long standing and fundamental limitation of pep563 that annotations not defined in the module namespace are not available. We work around that somewhat by looking in the local namespace when building a model, but looking elsewhere will quickly become impractical.
> 
> Maybe we could look in the module namespace of the parent, not sure what errors that could introduce.
I haven't yet fully read pep695, but it seems that there's a new scope added in addition to the syntactic change - I'm assuming it's the `def695` scope referenced in there.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.

**Comment by DetachHead** [comment]
@sydney-runkle this is still an issue in pydantic v2

**Comment by DetachHead** [comment]
this seems to be fixed now
