### ISSUE TITLE
Custom JSON encoder of a nested model is not being used by the outer model

### ISSUE THREAD

**Issue by kevin-finvault** [pydantic/pydantic#3693]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/kevinobrien/.virtualenvs/finvault-backend/lib/python3.10/site-packages/pydantic
               python version: 3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-12.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

I am trying to create a custom JSON encoding for a nested Pydantic model. 

I have followed the [docs exactly as shown here](https://pydantic-docs.helpmanual.io/usage/exporting_models/#json_encoders). The only difference being that one of my model's attributes is an instance of another model. I have also asked the question on Stackoverflow and the Discussions page here, both with no reponses. 

I have simplified the problem to the following example:

```py
from pydantic import BaseModel


class SubModel(BaseModel):
    name: str
    short_name: str


class TestModel(BaseModel):
    sub_model: SubModel

    class Config:
        json_encoders = {SubModel: lambda s: s.short_name}


model = TestModel(sub_model=SubModel(name="Sub Model", short_name="SM"))

print(model)
print(model.json())
```

I am expecting the final line to output:

`{"sub_model": "SM"}`

But instead I am getting the output as if I never even defined my own `json_encoders`:

`{"sub_model": {"name": "Sub Model", "short_name": "SM"}}`

How can I correctly define a JSON encoder for a nested Pydantic model? I believe I am doing this as intended and my assumed output is reasonable?

**Comment by lucastosetto** [comment]
@kevin-finvault You should use the following flag to get the wanted output: `model.json(models_as_dict=False)`.

**Comment by kevin-finvault** [comment]
Thanks. Is there any way to achieve the same with `.dict()`?

**Comment by kevin-finvault** [comment]
@lucastosetto This does not work for models nested deeper than a depth of 1:

```
from pydantic import BaseModel


class SubModel1(BaseModel):
    name: str
    short_name: str


class SubModel2(BaseModel):
    name: str
    sub_sub_model: SubModel1


class Model(BaseModel):
    sub_model_1: SubModel1
    sub_model_2: SubModel2

    class Config:
        json_encoders = {SubModel1: lambda s: s.short_name}


model = Model(
    sub_model_1=SubModel1(name="Sub Model 1", short_name="SM1"),
    sub_model_2=SubModel2(name="Sub Model 2", sub_sub_model=SubModel1(name="Sub Sub Model", short_name="SSM")),
)

print(model)
print(model.json(models_as_dict=False))
```

This outputs:

```
{"sub_model_1": "SM1", "sub_model_2": {"name": "Sub Model 2", "sub_sub_model": {"name": "Sub Sub Model", "short_name": "SSM"}}}
```

Whereas I would like:

```
{"sub_model_1": "SM1", "sub_model_2": {"name": "Sub Model 2", "sub_sub_model": "SSM"}}
```

**Comment by kevin-finvault** [comment]
Hi @lucastosetto Thanks! This works for my original example, however it is not working for models nested at a depth greater than 1:

```
from pydantic import BaseModel


class SubModel1(BaseModel):
    name_1: str
    short_name: str


class SubModel2(BaseModel):
    name_2: str
    sub_sub_model: SubModel1


class TestModel(BaseModel):
    sub_model_1: SubModel1
    sub_model_2: SubModel2

    class Config:
        json_encoders = {SubModel1: lambda s: s.short_name}


model = TestModel(
    sub_model_1=SubModel1(name_1="Sub Model", short_name="SM"),
    sub_model_2=SubModel2(name_2="Sub Model 2", sub_sub_model=SubModel1(name_1="Sub Sub Model", short_name="SSM")),
)

print(model.json(models_as_dict=False))
```

This outputs:

```
{"sub_model_1": "SM", "sub_model_2": {"name_2": "Sub Model 2", "sub_sub_model": {"name_1": "Sub Sub Model", "short_name": "SSM"}}}
```

Whereas I expected:

```
{"sub_model_1": "SM", "sub_model_2": {"name_2": "Sub Model 2", "sub_sub_model": "SSM"}}
```

I would have thought that the `json_encoders` are applied recursively to all nested models?

**Comment by cwerner** [comment]
I think I also have this problem. In my case the custom json encoder is located at lvl2 (merging fields of lvl1 into a string as in the docs). If lvl2 is itself contained in another model the conversion is not happening. Is this expected?

lvl2 -> lvl1
lvl2.json(models_as_dict=True) ok

lvl3 -> lvl2 -> lvl1 
lvl3.json(models_as_dict=True) not ok/ no conversion

**Comment by samuelcolvin** [comment]
@PrettyWood, any idea on how to fix this in deeper sub-models.

My instinct is that the solution is to wait for v2 and a comprehensive rewrite which (among many other things) uses `model.json()` recursively.

**Comment by roussel-ryan** [comment]
I'm also having the same problem, is there any fix for this yet?

**Comment by samuelcolvin** [comment]
Not yet, this will be fixed in v2, see #4456.

**Comment by rishacha** [comment]
@samuelcolvin  - Any idea when one can expect v2? Is there some beta which can be used where this bug is fixed?

**Comment by gsakkis** [comment]
Not sure if it's the same issue but the nested model Config is ignored by the outer model:
```py
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Child(BaseModel):
    id: UUID = Field(default_factory=uuid4)

    class Config:
        json_encoders = {UUID: lambda v: "XXX"}


class Parent(BaseModel):
    child: Child


c = Child()
p = Parent(child=c)
print(c.json())
print(p.json())
```

Output:
```
{"id": "XXX"}
{"child": {"id": "8749772a-9398-475e-9865-42b30389073d"}}
```

Passing `models_as_dict=False` has no effect in this case.

**Comment by samuelcolvin** [comment]
> @samuelcolvin - Any idea when one can expect v2? Is there some beta which can be used where this bug is fixed?

#4887.

> Not sure if it's the same issue but the nested model Config is ignored by the outer model:

Sale I think, either way, should be fixed in V2.

**Comment by michael-person** [comment]
so this is a horrible workaround but if you don't want to update to v2 then you can manually call the custom json serializer like so:

'
import json
from uuid import UUID, uuid4
from pydantic import BaseModel, Field


class Child(BaseModel):
    id: UUID = Field(default_factory=uuid4)

    class Config:
        json_encoders = {UUID: lambda v: "XXX"}


class Parent(BaseModel):
    child: Child

    class Config:
        json_encoders = {
            Child: lambda child: json.loads(child.json(models_as_dict=False))
        }


c = Child()
p = Parent(child=c)
print(c.json())
print(p.json())
'

**Comment by Kludex** [comment]
This is solved on V2. The way you'd do it on V2 would be:

```python
from pydantic import BaseModel
from typing import Annotated
from pydantic.annotated_arguments import PlainSerializer


def user_serializer(v: "User", _info):
    if v.friends is None:
        return f"User({v.name})"
    return v


SerializedUser = Annotated["User", PlainSerializer(user_serializer)]

class User(BaseModel):
    name: str
    friends: list[SerializedUser] | None = None


m = User(name="anne", friends=[User(name="ben"), User(name="charlie")])
assert m.model_dump_json() == '{"name":"anne","friends":["User(ben)","User(charlie)"]}'
```

**Comment by haf** [comment]
@Kludex Do you know the solution to this?

```
Because fastapi (0.95.1) depends on pydantic (>=1.6.2,<1.7 || >1.7,<1.7.1 || >1.7.1,<1.7.2 || >1.7.2,<1.7.3 || >1.7.3,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0)
 and no versions of fastapi match >0.95.1,<0.96.0,
```

Then how would one use it with latest FastAPI?

**Comment by samuelcolvin** [comment]
You can't until FastAPI adopts Pydantic V2.
