### ISSUE TITLE
Regression 1.9.0: Field(discriminator=...) fails to resolve List[Union[...]], but does resolve Union[...]

### ISSUE THREAD

**Issue by TueVJ** [pydantic/pydantic#3694]
### Checks

* [ x ] I added a descriptive title to this issue
* [ x ] I have searched (google, github) for similar issues and couldn't find anything
* [ x ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Creating a List of a Union of BaseModel-derived types stopped working with Pydantic 1.9.0.

Though the docs note that Smart Union does not work with collections (Which would presumably give this error), I can't see anywhere that this should be the default behavior in 1.9.0.  The bug still occurs if Config is used to force smart_union=False.

This bug occurs for pydantic 1.9.0 for both Python 3.9 and 3.10. Pydantic 1.8.2 runs the example below without issues in both python 3.9 and 3.10.

Error message is:
Traceback (most recent call last):
  File "/[snip]/pydantic_test.py", line 16, in <module>
    class LetterCollection(BaseModel):
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 603, in pydantic.fields.ModelField._type_analysis
TypeError: `discriminator` can only be used with `Union` type

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
             pydantic version: 1.9.0
            pydantic compiled: True
            install path: /home/USER/.cache/pypoetry/virtualenvs/test-5aHI9hxT-py3.10/lib/python3.10/site-packages/pydantic
            python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
            platform: Linux-5.15.12-1-MANJARO-x86_64-with-glibc2.33
            optional deps. installed: ['typing-extensions']"

Minimal working example:
```py
from typing import List, Union, Literal
from pydantic import BaseModel, Field


class A(BaseModel):
    a: int = 0
    letter_type: Literal["A"] = "A"


class B(BaseModel):
    b: int = 1
    letter_type: Literal["B"] = "B"


Letters = Union[A, B]


class LetterWrapper(BaseModel):
    letters: Letters = Field(default=A(), discriminator="letter_type")  # Works


class LetterCollection(BaseModel):
    letters: List[Letters] = Field(default_factory=list, discriminator="letter_type")  # Fails


letters = [A(), B()]
letterc = LetterCollection(letters=letters)

print(letters)  # [A(a=0, letter_type='A'), B(b=1, letter_type='B')]
print(letterc)  # letters=[A(a=0, letter_type='A'), B(b=1, letter_type='B')]

```

**Comment by hacker-DOM** [comment]
Any updates on this? 🙏

**Comment by samuelcolvin** [comment]
@PrettyWood any idea?

Otherwise I'll try to look at it soon.

**Comment by samuelcolvin** [comment]
Discriminated unions weren't added until 1.9, so it doesn't make sense for this to be a regression.

Hopefully we can make discriminated unions more powerful in v2, but I don't think this is a regression.

**Comment by TueVJ** [comment]
I marked this as a regression since the example given above works as expected in 1.8.2, properly resolving both letters and letterc.
I.e. it is not a regression of the discriminated union feature, but of the module as a whole.

It's possible that the regression is related to the introduction of discriminated unions, but that isn't obvious from the output messages.

**Comment by samuelcolvin** [comment]
I understand, but this is just a limitation of discriminated unions for now.

I was discussing this with @PrettyWood yesterday - the internal of pydantic v1 are seriously in need of a re-think, hence why I'm working on pydantic-core and an entire rewrite. I want to get the essential fixes out in v1.9.1, then get the already merged and ready PRs out in v1.10 to avoid pissing people off a lot, then move on to v2.

Hence I'm trying to minimise the complex and potentially disruptive changes in v1.X - like fixing this.

**Comment by TueVJ** [comment]
I see - the decision makes sense to me now. Thank you for the clarification.

**Comment by Kludex** [comment]
On V2, the following snippet works as expected:

```python
from typing import List, Union, Literal, Annotated
from pydantic import BaseModel, Field


class A(BaseModel):
    a: int = 0
    letter_type: Literal["A"] = "A"


class B(BaseModel):
    b: int = 1
    letter_type: Literal["B"] = "B"


Letters = Annotated[Union[A, B], Field(discriminator="letter_type")]


class LetterCollection(BaseModel):
    letters: List[Letters] = Field(default_factory=list)


letterc = LetterCollection.parse_obj(
    {"letters": [{"letter_type": "B", "b": 1}, {"letter_type": "A", "a": 2}]}
)
print(letterc)
```

We set the `discriminator` for the `Union[A, B]`, and then we create a list of that union.
