### ISSUE TITLE
Linting error when using nested models with optional arguments

### ISSUE THREAD

**Issue by andrewmsaid** [pydantic/pydantic#3710]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
pydantic compiled: True
    install path: /usr/local/lib/python3.9/site-packages/pydantic
python version: 3.9.9 (main, Nov 17 2021, 16:20:40)  [GCC 10.2.1 20210110]
    platform: Linux-5.10.76-linuxkit-x86_64-with-glibc2.31
optional deps. installed: ['email-validator', 'typing-extensions']
```

When setting one of a model's arguments as another model and the nested model only has optional arguments, linter throws an error saying "Arguments missing for parameters". Because the default is an empty object and the NestedModel has all objects, this would run fine, but still shows linting errors.

```py
import pydantic
from typing import Optional


class NestedModel(pydantic.BaseModel):
    attribute_a: Optional[int]
    attribute_b: Optional[int]
    attribute_c: Optional[str]


class MainModel(pydantic.BaseModel):
    nested: NestedModel = pydantic.Field(default=NestedModel())
```

![image](https://user-images.githubusercontent.com/98128064/150431021-0678ef4b-c51b-443f-a22d-9bc374a56b17.png)

**Comment by blueridger** [comment]
The workaround I use is setting an explicit None default.
```
    attribute_a: Optional[int] = None
```

**Comment by samuelcolvin** [comment]
That's correct and will be necessary at runtime in V2.
