### ISSUE TITLE
BaseModel.copy() ignores the `Extra.ignore` configuration

### ISSUE THREAD

**Issue by samuelduchesne** [pydantic/pydantic#3732]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: C:\Users\samuel.letellier-duc\Miniconda3\envs\surrogate-api\Lib\site-packages\pydantic
               python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['email-validator', 'typing-extensions']
```

When copying a model and specifying `update`, even if the Model has Extra set at `ignore`, additional attributes are added to the model. Here is a simple reproducible example.

```py
>>> class Model(BaseModel):
>>>     attribute_1: int
>>>     attribute_2: int
>>> 
>>>     class Config:
>>>         extra = Extra.ignore
>>>
>>> model = Model(attribute_1=1, attribute_2=2, attribute_3=3)
>>> model
Model(attribute_1=1, attribute_2=2)
# attribute_3 is ignored
```

```py
>>> model_copy = model.copy(update={"attribute_3":3})
>>> model_copy
Model(attribute_1=1, attribute_2=2, attribute_3=3)
# attribute_3 is not ignored
```

**Comment by basnijholt** [comment]
Same for:
```python
from pydantic import BaseModel, Extra

class A(BaseModel):
    x: int = 1
    class Config:
        extra = Extra.forbid
        
# A(y=1) # raises 'extra fields not permitted'
# but
a = A()
a.copy(update={'y': 1})
# returns: A(x=1, y=1)
```

**Comment by jskrzypek** [comment]
@samuelcolvin We could get behavior similar to what would have been introduced in #3766 by simply adding an optional `extra` kwarg to `BaseModel.copy()` and respecting that rather than the `extra` attribute of the class' Config. IIUC havinf this default to `Extra.allow` ought to enable the intended functionality while avoiding breaking changes...

**Comment by samuelcolvin** [comment]
Too late to change this in V1.10 and the plan is to remove `copy()` in V2 and instead implement `__copy__` to hook into standard lib tooling.
