### ISSUE TITLE
Unenforced field constraints error with `update_forward_refs`

### ISSUE THREAD

**Issue by adri1wald** [pydantic/pydantic#3745]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.9.0
       pydantic compiled: True
            install path: [HIDDEN]/.venv/lib/python3.8/site-packages/pydantic
          python version: 3.8.11 (default, Aug 22 2021, 20:13:49)  [Clang 11.0.3 (clang-1103.0.32.62)]
                platform: macOS-10.16-x86_64-i386-64bit
optional deps. installed: ['email-validator', 'typing-extensions']
```

**Trying to create a recursive model with pydantic I stumbled on an unenforced field constraints error.**

I created a minimal reproduction that illustrates the bug. Running the code below:
```py
from __future__ import annotations
from typing import List, Optional
from pydantic import BaseModel, Field

class Data(BaseModel):
    field: Optional[List[Data]] = Field(
        None,
        min_items=1,
    )

Data.update_forward_refs()

model = Data(field=[Data()])
print(model)
```

outputs:
```
  File "test.py", line 5, in <module>
    class Data(BaseModel):
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 486, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 1012, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "field" the following field constraints are set but not enforced: min_items. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

Removing the min_items constraints:
```py
from __future__ import annotations
from typing import List, Optional
from pydantic import BaseModel, Field

class Data(BaseModel):
    field: Optional[List[Data]] = Field(
        None,
        # min_items=1, <-----
    )

Data.update_forward_refs()

model = Data(field=[Data()])
print(model)
```

works as expected:
```
field=[Data(field=None)]
```

**Am I right in thinking this is a bug or am I misunderstanding unenforced field constraints?**

**Comment by mgberg** [comment]
I'm running into the same issue running pydantic 1.9.0 in python 3.9.7 on linux.

**Comment by yanyongyu** [comment]
Seems using `from __future__ import annotations` causes field annotation becomes `ForwardRef["some type"]`, pydantic will not resolve constraints for `ForwardRef`.

**Comment by Kludex** [comment]
Given the error message, it looks like this is expected. 🤔 

This actually made me find a bug on V2. I've documented it on https://github.com/pydantic/pydantic/issues/5645.
