### ISSUE TITLE
Json strategy doesn't work as expected (?)

### ISSUE THREAD

**Issue by asmodehn** [pydantic/pydantic#3757]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: C:\Users\avincent2\PycharmProjects\wdms-pydantic-bug\.venv\Lib\site-packages\pydantic
               python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

In this sample test, commenting the json_field makes the test pass.
```py
import pytest
from pydantic import BaseModel,  Json
from hypothesis import settings, given,  Verbosity, strategies as st


class MyObject(BaseModel):
    json_field: Json
    int_field: int


@given(my_object=st.from_type(MyObject))
@settings(verbosity=Verbosity.verbose)
def test_json_init_dict(my_object):
    assert MyObject(**my_object.dict())


if __name__ == "__main__":
    pytest.main(["-sv", __file__])
```

However with the json_field the test fails as:
```
E   pydantic.error_wrappers.ValidationError: 1 validation error for MyObject
E   json_field
E     JSON object must be str, bytes or bytearray (type=type_error.json)
```

I m wondering if the strategy is doing what it is supposed to ?
I understand there might be some semantic differences between the "json string/bytes" and the "json-expressible datastructure" like shown in https://hypothesis.readthedocs.io/en/latest/data.html#recursive-data ?

**Comment by lig** [comment]
@asmodehn thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
