### ISSUE TITLE
Constrained collection type coercions occur before contained constrained types'

### ISSUE THREAD

**Issue by timbedard** [pydantic/pydantic#3763]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.9.0
       pydantic compiled: True
            install path: .../.venv/lib/python3.9/site-packages/pydantic
          python version: 3.9.10 (main, Jan 15 2022, 11:48:04)  [Clang 13.0.0 (clang-1300.0.29.3)]
                platform: macOS-12.1-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

When a field is a constrained collection type (like `conlist`) that contains another constrained type (like `constr`), the container constraints are applied before the contained type constraints are. For `unique_items` this could prevent work when there are duplicate items, BUT if the contained type has a coercive constraint like `to_lower` this prevents duplicates from being caught.

### Example
```py
from pydantic import BaseModel, conlist, constr

class ExampleModel(BaseModel):
    groceries: conlist(constr(to_lower=True), unique_items=True)

assert ExampleModel(groceries=["SPAM", "eggs", "spam"]).groceries == ["spam", "eggs"]
```
The above example instead yields `[["spam", "eggs", "spam"]`.

**Comment by Kludex** [comment]
We don't have the above issue on V2 anymore. `unique_items` was removed, you can achieve the wanted behavior with the following snippet:

```python
from pydantic import BaseModel, constr
from typing import Set


class ExampleModel(BaseModel):
    groceries: Set[constr(to_lower=True)]


model = ExampleModel(groceries={"SPAM", "eggs", "spam"})

assert model.groceries == {"spam", "eggs"}, model
```
