### ISSUE TITLE
wrong type signature of `custom_pydantic_encoder` (with solution)

### ISSUE THREAD

**Issue by fwojciec** [pydantic/pydantic#3768]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: False
                 install path: /Users/filip/code/temp/pydantic/pydantic
               python version: 3.10.1 (main, Jan 13 2022, 15:16:24) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-12.1-arm64-arm-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

Pyright typecheck fails for the following implementation of `custom_pydantic_encoder`:

```py
from datetime import datetime
from functools import partial

from pydantic.json import custom_pydantic_encoder


def iso_format(date: datetime) -> str:
    "Convert date to AWS ApiGateway RFC3339 format."
    return date.isoformat(timespec="milliseconds")


custom_json_encoder = partial(custom_pydantic_encoder, {datetime: iso_format})
```

While `mypy` doesn't see any issues with this code, I believe that `pyright` is actually correct in raising the following error:

<img width="678" alt="Screen Shot 2022-02-02 at 9 47 24 AM" src="https://user-images.githubusercontent.com/1042048/152209018-7d139606-83c6-4667-b97f-f0b37cd97210.png">

The issue can be resolved my making the following change:

```diff
index b732cc0..8983eb4 100644
--- a/pydantic/json.py
+++ b/pydantic/json.py
@@ -90,7 +90,7 @@ def pydantic_encoder(obj: Any) -> Any:
         raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")


-def custom_pydantic_encoder(type_encoders: Dict[Any, Callable[[Type[Any]], Any]], obj: Any) -> Any:
+def custom_pydantic_encoder(type_encoders: Dict[Type[Any], Callable[[Any], Any]], obj: Any) -> Any:
     # Check the class type and its superclasses for a matching encoder
     for base in obj.__class__.__mro__[:-1]:
         try:
```

Incidentally, following the change, the type signature of `type_encoders` is the same as the type signature of `ENCODERS_BY_TYPE` [here](https://github.com/samuelcolvin/pydantic/blob/9d631a3429a66f30742c1a52c94ac18ec6ba848d/pydantic/json.py#L44) - so I believe this is what was intended all along.

I'd be happy to make the PR if the change is acceptable.

**Comment by EliavLunar** [comment]
Any news about this one...?
