### ISSUE TITLE
BaseSettings - can't use `user` as attribute name, value is always `root`

### ISSUE THREAD

**Issue by tonofll** [pydantic/pydantic#3775]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /databricks/python3/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
                     platform: Linux-5.4.0-1063-azure-x86_64-with-glibc2.29
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```py
from pydantic import BaseSettings
from os import environ


class MyConfig(BaseSettings):
    host: str = "my_host"
    database: str = "my_database"
    user: str = "my_user"
    another_user: str = "my_another_user"
    password: str = "my_password"

my_config = MyConfig()
print({
        "host": my_config.host,
        "database": my_config.database,
        "user": my_config.user,
        "another_user": my_config.another_user,
        "password": my_config.password,
    })
```
**Output**
```
{'host': 'my_host', 'database': 'my_database', 'user': 'root', 'another_user': 'my_another_user', 'password': 'my_password'}
```
As you can notice, `user` attribute seems to be hardcoded to `root` value always, regardless of its value. However the rest of the attributes seems to work fine. If `user` attribute name is protected, it should raise at least an Exception.

**Comment by trankov** [comment]
Got the same issue using **_secrets_dir** approach. File 'user' contains actual database user name, but returns 'admin'. The problem didn't appeared at local dev environment under Mac OS, but raises at stage server under Ubuntu 20. Seems like a bug.

**Comment by samuelcolvin** [comment]
Please confirm if the same behavior is seen with v1.8.2.

**Comment by hramezani** [comment]
It's because you have a `user` or `USER` environment variable. it may be set by the OS.

**Comment by trankov** [comment]
> It's because you have a `user` or `USER` environment variable. it may be set by the OS.

Yes, sure, thank you. I wrote this note a year ago, but for a now I got the reason. I'm using a solution [as described in Documentation](https://pydantic-docs.helpmanual.io/usage/settings/#removing-sources), just customizing sources order. Unfortunately I forgot to mention it there, sorry.
