### ISSUE TITLE
Calling `json()` no longer calls `dict()`

### ISSUE THREAD

**Issue by andreyfedoseev** [pydantic/pydantic#3780]
According to the [documentation](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeljson):

> Typically, .json() in turn calls .dict() and serialises its result.

This behavior [has been changed in 1.9.0](https://github.com/samuelcolvin/pydantic/commit/458f257dcbe4d307ad71c28a9947e30eab742131#diff-8708af8d26c26644976866f974e0b810b0940ede43ff487e457057d5a1f07999L472),  and calling `.json()` doesn't call `.dict()` anymore.

I consider this a breaking change because it breaks a documented feature. Also, the documentation hasn't been updated to reflect this change.

### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
1.9.0
```

```py
import pydantic

class MyModel(pydantic.BaseModel):
    
    spam: int

    def dict(self, **kwargs):
        d = super().dict(**kwargs)
        d["ham"] = 2
        return d

MyModel(spam=1).json()

# expect to get: {"spam": 1, "ham": 2}
# actually get: {"spam": 1}
```

**Comment by hramezani** [comment]
Unfortunately, this was a breaking change. I've created a PR to update the documentation
