### ISSUE TITLE
Pure-python implementation of `dataclasses` module has differences regarding slots

### ISSUE THREAD

**Issue by spookylukey** [pydantic/pydantic#3791]
When using pydantic.dataclasses.dataclass, `typing.get_type_hints()` output on a Pydantic model includes `__slots__` for the pure-Python version, but not for the Cython version.

Test case:

```python
# test.py
import typing
from pydantic.dataclasses import dataclass

@dataclass
class Foo:
    pass

print(typing.get_type_hints(Foo.__pydantic_model__))
```

```bash
$ pip install pydantic
$ python test.py
{}
$ pip uninstall pydantic
$ SKIP_CYTHON=1 pip install --no-binary pydantic pydantic
$ python test.py
{'__slots__': typing.Tuple[str, ...]}
```

Found this with 1.8.2 , but the issue is still there with latest version - 1.9.0.

I don't know if this is deliberate, or unavoidable, but it tripped me up, so I thought it was worth reporting.

## Impact

I discovered this because we were experimenting with [AWS Graviton](https://aws.amazon.com/ec2/graviton/) instances, which are 64-bit ARM CPUs, where, for whatever reason, we are falling back to the pure-Python version.

## Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

**Comment by Goldziher** [comment]
Yup this is clearly a bug. Pydntic will fail validation for dataclasses that use `slots=True`. See this for reference:

```python
import pytest
from dataclasses import dataclass
from unittest import skipIf

from pydantic import BaseModel


@skipIf(sys.version_info < (3, 10), "python version incompatible with 'slots' arg")
def test_pydantic_handling_stdlib_dataclass_slots() -> None:
    """
    Test showing failure when using the slots kwarg available the stdlib dataclass decorator in python 3.10+
    """
    @dataclass(slots=True)
    class UserWithSlots:
        username: str
        group: str

    @dataclass(slots=False)
    class UserWithoutSlots:
        username: str
        group: str

    class ModelThatRaises(BaseModel):
        user: UserWithSlots

    class ModelThatDoesntRaise(BaseModel):
        user: UserWithoutSlots

    with pytest.raises(ValidationError):
        ModelThatRaises(user={"username": "MoisheZuchmir", "group": "admins"})

    ModelThatDoesntRaise(user={"username": "MoisheZuchmir", "group": "admins"})
```

Reported in Starlite here: https://github.com/starlite-api/starlite/issues/359

**Comment by samuelcolvin** [comment]
Have you tried on master? Might be fixed by #2557

**Comment by Goldziher** [comment]
@infohash can you try master?

**Comment by PrettyWood** [comment]
The code of @spookylukey works on `master` since the refacto. But your code @Goldziher doesn't. We still don't support dataclasses with `slots`, which was added in 3.10. Is it something that you need in starlite?

**Comment by PrettyWood** [comment]
Doesn't feel like it's going to be easy to add since we keep a kind of state when wrapping up the dataclass and a slotted dataclass doesn't allow mutations on those fields. We would need to mess up even more with init, which is something I really don't want to do.
In v2, it should be easier to use pydantic directly with stdlib dataclasses, without the custom pydantic one 🙏

**Comment by samuelcolvin** [comment]
Agreed, I think we can live without slots for v1.10.
