### ISSUE TITLE
Optional nested custom root type not parsed properly when None

### ISSUE THREAD

**Issue by DeviousStoat** [pydantic/pydantic#3836]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.0
            pydantic compiled: False
                 install path: /tmp/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
                     platform: Linux-5.16.9-200.fc35.x86_64-x86_64-with-glibc2.34
     optional deps. installed: ['typing-extensions']
```

The issue is that a custom root type model is converted to its `__root__` value but the `None` validation occurs on the parent field if it is used as a sub field.

```py
from pydantic import BaseModel

class MyRootModel(BaseModel):
    __root__: str | None
    
class MyModel(BaseModel):
    v: MyRootModel
    
my_root = MyRootModel.parse_obj(None)
my_model = MyModel(v=my_root)
assert my_model.dict() == {"v": None}

MyModel.parse_obj(my_model.dict())  # ValidationError here
```
Here we get a validation error on the last line:
```py
v
  none is not an allowed value (type=type_error.none.not_allowed)
```

This example is really simple so it might seem a bit weird but this setup might be useful if we add some specific handling of the `None` value in `MyRootModel`

I looked around a bit and can propose two very simple solutions to this issue:
* In the validation of `ModelField` [here](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/fields.py#L842) add a check for custom root type something like `or (issubclass(self.type_, BaseModel) and self.type_.__custom_root_type__)` so that the validation is deferred to the specific validation functions and `None` is accurately validated by the root model.
* Or in the `validate_model` function there could be a call to `_enforce_dict_if_root` in the iteration of fields if the field is subclass of `BaseModel`.

Let me know if you think this is an issue and if any of the solutions seem appropriate and I can open a PR.

**Comment by igorbga** [comment]
I can confirm that bug, in fact I was preparing some code to illustrate it so here it goes:

```python
from typing import Optional

from pydantic import BaseModel, root_validator


class ConsumedRegularModel(BaseModel):
    value: Optional[int]


class ConsumingRegularModel(BaseModel):
    consumed: ConsumedRegularModel

    @root_validator
    def consuming_validator(cls, values):
        print(values)
        return values


class ConsumedRootModel(BaseModel):
    __root__: Optional[int]


class ConsumingRootModel(BaseModel):
    consumed: ConsumedRootModel

    @root_validator
    def consuming_validator(cls, values):
        print(values)
        return values


ConsumingRegularModel(consumed=ConsumedRegularModel(value=5))
ConsumingRegularModel(consumed={"value": 5})
ConsumingRegularModel(consumed=ConsumedRegularModel(value=None))
ConsumingRegularModel(consumed={"value": None})

with_value = ConsumedRootModel.parse_obj(5)
print(with_value)
without_value = ConsumedRootModel.parse_obj(None)
print(without_value)

ConsumingRootModel(consumed=ConsumedRootModel(__root__=5))
ConsumingRootModel(consumed=5)
ConsumingRootModel(consumed=ConsumedRootModel(__root__=None))

ConsumingRootModel(consumed=None) # An unexpected ValidationError happens


```

**Comment by igorbga** [comment]
For my example a simple workaroung is adding this to ConsumingRootModel class:

```python

    @root_validator(pre=True)
    def solve_issue_3836(cls, values):
        value = values.get('consumed', ...)
        if value is None:
            values["consumed"] = ConsumedRootModel.parse_obj(None)
        return values
```

**Comment by hramezani** [comment]
We are going to implement a `RootModel` instead of recommending `__root__` on V2.

I'll let this issue open until we implement the RootModel.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
