### ISSUE TITLE
hashable isnt valid

### ISSUE THREAD

**Issue by zrothberg** [pydantic/pydantic#3837]
The way it frozen=true currently works does not yield a valid object. 

Per the standard docs 

"An object is hashable if it has a hash value which never changes during its lifetime (it needs a __hash__() method), and can be compared to other objects (it needs an __eq__() method). **Hashable objects which compare equal must have the same hash value.**"

This is actually required for the in keyword. So currently pydantics ones appear to be broken. Frankly I don't see a way around this without ruining eq. Hashability should most likely just be deprecated and removed.

**Comment by lig** [comment]
@zrothberg thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
