### ISSUE TITLE
Field ordering, when used with model inheritance

### ISSUE THREAD

**Issue by zry9056** [pydantic/pydantic#3838]
I would like to construct several models that share some common fields and functionalities. My code looks like the following, where I inherit Config_A and Config_B from Config. In Config_A, I omitted those fields defined in its parent class and kept all in Config_B. I want to preserve the order of fields as defined in Config_B, since I would like to use the **values** property in both child models, and the order matters (imagine I'm inserting these fields into a database table). As I tested out, both Config_A and Config_B have their fields declared in Config come first, which is not what I want. I wonder if there is any way to custom field ordering in this situation? Any solutions without inheritance are also welcomed as long as it does not require me to duplicate common methods under the two models.

```
from typing import Optional, Any
from pydantic import BaseModel

class Config(BaseModel):
    create_time: Optional[str]
    update_person: Optional[str]
    update_time: Optional[str]

    @property
    def values(self):
        return list(self.dict().values())

    def fill_in_time(self, time, flag):
        if flag == 'create' and not self.create_time:
            self.create_time = time


class Config_A(Config):
    name: str
    status: int
    config: Any


class Config_B(Config):
    name: str
    create_time: Optional[str]
    update_person: Optional[str]
    update_time: Optional[int]
    config: List[dict]
```

**Comment by ijc-90** [comment]
I need the same thing, a way to declare the order of fields, or at least a config to be able to put the inherited fields first. In this example I need Config_A order to be:
```
    name: str
    status: int
    config: Any
    create_time: Optional[str]
    update_person: Optional[str]
    update_time: Optional[str]
    ```

**Comment by samuelcolvin** [comment]
This isn't possible, you can either definite the class again with all methods, or implement your own logic reorder as required.

**Comment by guvkay20** [comment]
Not helpful Mr. Colvin; there are genuine LLM prompting benefits to such reorderings.

**Comment by PSU3D0** [comment]
Any changes here?
