### ISSUE TITLE
Allow literal enum value discriminator to be initialized by string

### ISSUE THREAD

**Issue by ljnsn** [pydantic/pydantic#3850]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: False
                 install path: /home/ljnsn/.virtualenvs/pydantictest/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 10 2021, 14:59:43)  [GCC 11.2.0]
                     platform: Linux-5.15.23-76051523-generic-x86_64-with-glibc2.34
     optional deps. installed: ['typing-extensions']
```

I'm not sure if this is `Literal` limitation or related to pydantic, but it would be nice if we could initialize models with a literal `Enum.value` field by string. Similar to how a string is cast to the correct enum value, if the field type is an `Enum` and the incoming value is a string.

I'm initializing models from json data received via API, so the incoming values will be strings. I can get around this by using `Literal[Enum.value.value]` as discriminator field, but it's ugly and pyright complains that this is an invalid argument to `Literal`.
 
```py
from enum import Enum
from typing import Literal, Union

from pydantic import BaseModel, Field


class Pet(Enum):
    CAT = "cat"
    DOG = "dog"
    LIZARD = "lizard"
    REPTILE = "reptile"


class Base(BaseModel):
    friend: Pet


class Cat(Base):
    pet_type: Literal[Pet.CAT]
    meows: int


class Dog(Base):
    pet_type: Literal[Pet.DOG]
    barks: float


class Lizard(Base):
    pet_type: Literal[Pet.LIZARD, Pet.REPTILE]
    scales: bool


class Model(BaseModel):
    pet: Union[Cat, Dog, Lizard] = Field(..., discriminator="pet_type")
    n: int


print(Cat(**{"friend": "dog", "pet_type": Pet.CAT, "meows": 3}))
# > friend=<Pet.DOG: 'dog'> pet_type=<Pet.CAT: 'cat'> meows=3

print(Dog(**{"friend": "cat", "pet_type": "dog", "barks": 3.14}))
ValidationError: 1 validation error for Dog
# > pet_type
#     unexpected value; permitted: <Pet.DOG: 'dog'> (type=value_error.const; given=dog; permitted=(<Pet.DOG: '
#   dog'>,))


print(Model(pet={"friend": "cat", "pet_type": Pet.DOG, "barks": 3.14}, n=1))
# > pet=Dog(friend=<Pet.CAT: 'cat'>, pet_type=<Pet.DOG: 'dog'>, barks=3.14) n=1

print(Model(pet={"friend": "cat", "pet_type": "dog", "barks": 3.14}, n=1))
# > ValidationError: 1 validation error for Model
#   pet
#     No match for discriminator 'pet_type' and value 'dog' (allowed values: <Pet.CAT: 'cat'>, <Pet.DOG: 'dog'
#   >, <Pet.LIZARD: 'lizard'>, <Pet.REPTILE: 'reptile'>) (type=value_error.discriminated_union.invalid_discrim
#   inator; discriminator_key=pet_type; discriminator_value=dog; allowed_values=<Pet.CAT: 'cat'>, <Pet.DOG: 'd
#   og'>, <Pet.LIZARD: 'lizard'>, <Pet.REPTILE: 'reptile'>)
```

**Comment by ayyess** [comment]
A [str Enum](https://docs.python.org/3/library/enum.html#restricted-enum-subclassing) looks to be a workaround to this.

```
class Pet(str, Enum):
    CAT = "cat"
    DOG = "dog"
    LIZARD = "lizard"
    REPTILE = "reptile"

# friend=<Pet.DOG: 'dog'> pet_type=<Pet.CAT: 'cat'> meows=3
# friend=<Pet.CAT: 'cat'> pet_type=<Pet.DOG: 'dog'> barks=3.14
# pet=Dog(friend=<Pet.CAT: 'cat'>, pet_type=<Pet.DOG: 'dog'>, barks=3.14) n=1
# pet=Dog(friend=<Pet.CAT: 'cat'>, pet_type=<Pet.DOG: 'dog'>, barks=3.14) n=1
```

**Comment by njanke96** [comment]
I still think this could be a feature, perhaps a Model config option. In my case I am using IntEnum, serializing to a postgres database. The enum types are also defined in the database, but the database row values for these columns are returned as strings rather than integers, forcing me to define validators for these types so I can use `from_orm()`:

```python
@validator("connect_type", pre=True)
    def validate_connect_type(cls, value):
        if isinstance(value, str):
            # ConnectType is an IntEnum
            return ConnectType[value]
        else:
            return value
```

It's a bit impractical defining these for each IntEnum field. It would be convenient if we could define a model config option such as  `allow_enum_strings` or similar.

**Comment by samuelcolvin** [comment]
For anyone watching this, it's worth looking at tagged unions in V2, they're way more powerful.

Th discriminator can be:
* a key to any item of the input, regardless of whether it's in the models
* a path deep within a the input object
* more than one key/path to try
* a function to select which choice to to validate with

I'm sure yet what the interface will be in python, but you can see examples of the runtime behaviours in [`pydantic-core/tests/validators/test_tagged_union.py`](https://github.com/pydantic/pydantic-core/blob/main/tests/validators/test_tagged_union.py).

**Comment by richardxia** [comment]
I'm still hitting the reported issue in Pydantic V2, though the [workaround](https://github.com/pydantic/pydantic/issues/3850#issuecomment-1069353196) to explicitly subclass from `str` works fine for me.

I'm wondering if the Pydantic maintainers consider this to actually be a bug, or if it's "working as intended". The latter is fine for my use case, but I think it could use some documentation, it didn't appear to be documented at all in either the [Discriminated Unions](https://docs.pydantic.dev/2.0/usage/types/unions/#discriminated-unions-aka-tagged-unions) section or the [Enums](https://docs.pydantic.dev/2.0/usage/types/enums/) page of the docs.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
