### ISSUE TITLE
Restore `.dict()` parity with `.json()`

### ISSUE THREAD

**Issue by vberlier** [pydantic/pydantic#3852]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/vberlier/projects/beet/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
                     platform: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

Right now there's no way to get the exact value serialized by the `.json()` method as a `dict` when using custom root types. The `.json()` method has an [extra check](https://github.com/samuelcolvin/pydantic/blob/9d631a3429a66f30742c1a52c94ac18ec6ba848d/pydantic/main.py#L488) that would be useful to enable as well for `.dict()`, maybe using an explicit keyword-only argument.

```py
mymodel.dict()  # {'__root__': {'foo': 'bar'}}
mymodel.dict(exclude_root=True)  # {'foo': 'bar'}
mymodel.json()  # '{"foo": "bar"}'
```

The `exclude_root` keyword argument would exclude the custom root like in `.json()`. If that sounds reasonable I'd be happy to help with a PR.

**Comment by Kludex** [comment]
We are going to implement a `RootModel` instead of recommending `__root__` on V2.

I'll let this issue open until we implement the `RootModel`.

**Comment by Kludex** [comment]
`RootModel` is now implemented on V2. 🙏
