### ISSUE TITLE
Adding BGR convenience methods/functions to pydantic.color

### ISSUE THREAD

**Issue by MichaelCG8** [pydantic/pydantic#3856]
I propose adding BGR equivalents of existing RGB methods on the Color class, and RGB functions in color.py. I'm happy to do this work and submit a PR.

An example use case is any project involving OpenCV, which is heavily used in image processing and by default uses BGR ordering.

| Existing Method          | To Add                          |
|-------------------------------| ------------------------------|
| `Color.as_hex()`          | `Color.as_bgr_hex()`    |
| `Color.as_rgb()`           | `Color.as_bgr()`            |
| `Color.as_rgb_tuple()` | `Color .as_bgr_tuple()` |

| Existing Function | To Add                   |
|------------------------|---------------------------|
| `parse_tuple()`    | `parse_bgr_tuple()` |
| `parse_str()`        | `parse_bgr_str()  `   |
| `ints_to_rgba()`   | `ints_to_bgra()`        |

Rather than complicating the `Color` class by internally keeping whether it is in RGB or BGR format, I think it would be best to always be in RGB internally, and that is how it would print by default.  This would be documented, and it would be explained that any BGR access needs to be done explicitly via one of the new methods.

An alternative to new methods/functions is to add a keyword argument, for example `parse_str(value: str) -> RGBA:` becomes `parse_str(value: str, bgr=False) -> RGBA:`. I don't have strong feelings about which is preferable, although I think the latter approach applies better to  `parse_str()` than it does to functions/methods that have "rgb" in their name, such as `Color.as_rgb(self) -> str:`.becoming `as_rgb(self, bgr=False) -> str:`

**Comment by dmontagu** [comment]
I think we would be open to a PR adding these methods if still desired, but seeing as this issue is stale I'm going to close it for now. If you want to work on this please comment and I can re-open the issue and confirm with the other maintainers that they are comfortable adding this functionality.
