### ISSUE TITLE
`create_model_from_typeddict` doesn't play nice with `NotRequired`

### ISSUE THREAD

**Issue by eastside** [pydantic/pydantic#3859]
### Checks

* [ x] I added a descriptive title to this issue
* [ x] I have searched (google, github) for similar issues and couldn't find anything
* [ x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
root@9e1532e73d46:/code# python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /usr/local/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 (main, Feb  8 2022, 05:06:38)  [GCC 10.2.1 20210110]
                     platform: Linux-5.10.47-linuxkit-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Hey there!

`NotRequired` is a relatively new feature for TypedDict, available in typing_extensions. (Check out [PEP 0655](https://www.python.org/dev/peps/pep-0655/).) You basically just wrap a type with NotRequired and it means "this property could either be _this type_, or it could not be present on the dictionary." This is a distinction from Optional, which is just a union of Null and that type.

So like, for example, let's throw the following in `test.py` and validate it with mypy:

```py
from typing_extensions import TypedDict, NotRequired

class Movie(TypedDict):
    title: str
    year: NotRequired[int]

Movie(title='The Matrix', year=1999)    # Validation pass
Movie(title='The Matrix')               # Validation pass
Movie(title='The Matrix', year='asdf')  # Validation failure: year should be int
Movie(title='The Matrix', year=None)    # Validation failure: year should not be None

if __name__ == '__main__':
    from pydantic import ValidationError, create_model_from_typeddict
    movie_model = create_model_from_typeddict(Movie)
```

Let's see if mypy recognizes these validation errors...
```
root@9e1532e73d46:/code# mypy test.py
test.py:9: error: Incompatible types (expression has type "str", TypedDict item "year" has type "int")
test.py:10: error: Incompatible types (expression has type "None", TypedDict item "year" has type "int")
Found 2 errors in 1 file (checked 1 source file)
```
Good job mypy! The validation failures are exactly what we expect.

Sadly however, **pydantic doesn't like NotRequired.** We get an error when we use create_model_from_typedict. 😞 

We'll run the Python script (triggering the `if __name__ == '__main__'` bit), and see the exception:
```
root@9e1532e73d46:/code# python3 test.py
Traceback (most recent call last):
  File "/code/test.py", line 14, in <module>
    movie_model = create_model_from_typeddict(Movie)
  File "pydantic/annotated_types.py", line 35, in pydantic.annotated_types.create_model_from_typeddict
  File "pydantic/main.py", line 972, in pydantic.main.create_model
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 638, in pydantic.fields.ModelField._type_analysis
  File "/usr/local/lib/python3.9/typing.py", line 851, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

I'm super new to Pydantic so please let me know if I'm missing something. 👍

**Comment by michaeloliverx** [comment]
I have hit this issue too, are there plans to support this ?

**Comment by BrutalSimplicity** [comment]
Same

**Comment by AGiantSquid** [comment]
I have this issue as well.

**Comment by samuelcolvin** [comment]
Ye, pydantic (so far) doesn't really have the idea of an omitted field, just a field with a default.

This will be fixed in V2 which will have first class TypedDict support.

**Comment by hramezani** [comment]
`create_model_from_typeddict` is removed in `V2`
