### ISSUE TITLE
Root-validator reuse fails w/ dynamic functions

### ISSUE THREAD

**Issue by twcurrie** [pydantic/pydantic#3878]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
In the following code snippet, a configuration value is either set or derived from another configuration value through a dynamically defined root-validator function.  When multiple of these functions are used, even with the `reuse` flag being set to `True`, this fails to construct the value with version `1.9.0`.  At version `1.8.2`, this had no issue.   A single use of the function does not trigger failure; this can be demonstrated by deleted `BUILT` and the following `_built = ...` line in the code snippet below.

```py
from pydantic import (
    BaseSettings,
    root_validator,
)
from typing import Any, Dict


def get_or_build(base: str, field: str, suffix: str):
    def _get_or_build(cls, values: Dict[str, Any]) -> Any:
        if field in values:
            return values
        if base in values:
            values[field] = f"{values[base]}-{suffix}"
            return values
        raise ValueError(f"Must include BASE or {field}")

    return _get_or_build


class Settings(BaseSettings):
    BASE: str
    CONSTRUCTED: str
    _constructed = root_validator(allow_reuse=True, pre=True)(
        get_or_build(base="BASE", field="CONSTRUCTED", suffix="appended")
    )
    BUILT: str
    _built = root_validator(allow_reuse=True, pre=True)(
        get_or_build(base="BASE", field="BUILT", suffix="appended")
    )

settings = Settings()

```
### 1.8.2
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: True
                 install path: /Users/trevor.currie/.pyenv/versions/3.9.6/envs/pydantic-1.8.2/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Oct 18 2021, 10:31:44)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Result of execution of `BASE=a-string python -c "from pydantic_bug import settings; print(settings.BASE); print(settings.CONSTRUCTED); print(settings.BUILT)"`: 

```
a-string
a-string-appended
a-string-appended
```

### 1.9.0
Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/trevor.currie/.pyenv/versions/3.9.6/envs/pydantic-1.9.0/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Oct 18 2021, 10:31:44)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
Result of execution of `BASE=a-string python -c "from pydantic_bug import settings; print(settings.BASE); print(settings.CONSTRUCTED); print(settings.BUILT)"`: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/trevor.currie/Code/pydantic_bug/pydantic_bug.py", line 32, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
CONSTRUCTED
  field required (type=value_error.missing)
```

I believe this to be related to the changes implemented in PR #2670, but that's currently only a speculation based on the contents of the release [changes](https://github.com/samuelcolvin/pydantic/releases/tag/v1.9.0).

**Comment by pstjohn** [comment]
Is there a workaround for this in the meantime? Just looking for a way to have a parameterized root_validator shared between a couple different BaseModels

**Comment by lig** [comment]
@pstjohn Thank you for the feedback!

Could you please test this with Pydantic 1.10.9?

It would be great if you will be able to test this with Pydantic 2.0b2 and pydantic-settings 2.0b1 as well.

Also, a minimal reproducible example would help understanding the issue better.

**Comment by pstjohn** [comment]
Sure! Apologies, I was assuming I was running into the same problem as the first issue.
My issue is specifically the re-use of multiple root validators in the same BaseModel, where only the _last_ root validator is applied.

Here's a repro:

```python
import pydantic
import pytest


def check_present_in_values(item: str):

    @pydantic.root_validator(allow_reuse=True)
    def _wrapped(cls, values):
        if item not in values.values():
            raise ValueError
        else:
            return values
            
    return _wrapped


class MyClass(pydantic.BaseModel):
    field1: str
    field2: str

    _cat_validator = check_present_in_values('cat')
    _dog_validator = check_present_in_values('dog')


def test_myclass_valid_class_passes():
    MyClass(field1='cat', field2='dog')
    
    
def test_myclass_invalid_class_last_validator_raises():
    with pytest.raises(ValueError):
        MyClass(field1='cat', field2='parrot')
        
    
def test_myclass_invalid_class_first_validator_raises():
    with pytest.raises(ValueError):
        MyClass(field1='snake', field2='dog')        
```


With pydantic==1.8.2, `pytest test_3878.py` works here; but with pydantic >= 1.9.0, the last test will fail: 
```
FAILED test_3878.py::test_myclass_invalid_class_first_validator_raises - Failed: DID NOT RAISE <class 'ValueError'>
```

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.

**Comment by michaelgmiller1** [comment]
@sydney-runkle we are seeing this in our production code and it is a scary bug. We are skipping validations unbeknownst to us. We cannot upgrade to v2 due to the longstanding performance issues: https://github.com/pydantic/pydantic/discussions/6748

This is a minimum reproducible example. If you run it, everything validates (which it should NOT). If you switch the order of `_val1` and `_val2` then the validation fails (which it should). Even if it cannot be fixed, can you please offer a workaround for users limited to v1?

```python
from typing import List, Callable
from pydantic import root_validator, BaseModel


def exactly_one_of(keys: List[str]) -> Callable:
    def _validator(cls, v):
        vv = [1 if v.get(k) else 0 for k in keys]
        if sum(vv) != 1:
            raise Exception(f"Exactly one of {', '.join(keys)} is required for {cls}")
        return v

    return root_validator(_validator, allow_reuse=True)


def exactly_zero_or_one_of(keys: List[str]) -> Callable:
    def _validator(cls, v):
        vv = [1 if v.get(k) else 0 for k in keys]
        if sum(vv) > 1:
            raise Exception(f"exactly zero or one of: {keys} is required")
        return v

    return root_validator(_validator, allow_reuse=True)


class ExampleModel(BaseModel):
    field1: str
    field2: str
    _val1 = exactly_one_of(["field1", "field2"])
    _val2 = exactly_zero_or_one_of(["field1"])


ExampleModel(
    field1="hi",
    field2="there",
)
```

**Comment by sydney-runkle** [comment]
@michaelgmiller1,

Sorry to hear that. Understood - we'll be working on import time improvements + schema build improvements as to reduce the performance problems in V2.

At the moment, I'd say the best workaround would be to avoid using the dynamic functions. I know this isn't the best solution, but given that we're no longer actively working on V1, this is probably the best approach. You could also combine the logic of your dynamic functions into one, then only use one root validator, which should also work.
