### ISSUE TITLE
specifying default value in Field causes Pylance to expect an argument when calling the model constructor

### ISSUE THREAD

**Issue by EyalPerry** [pydantic/pydantic#3905]
# Bug

If you put the following snippet in VSCode and use Pylance (a common setup I assume), the below snippet will cause Pylance to complain `Argument missing for parameter value`.

Maybe it's a Pylance issue, maybe not.. I don't know enough, but it would be super awesome if there's some switch you can flip to support this :)

```python
from pydantic import BaseModel, Field, constr

class MyModel(BaseModel):
    value: str = Field('default_value', type=constr, min_length=1, max_length=200)

if __name__ == "__main__":
    a = MyModel()
    print(a)

```

**Comment by adriangb** [comment]
I recommend you use PEP593 `Annotated`:

```python
from typing import Annotated  # or typing_extensions
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    value: Annotated[str, Field(min_length=1, max_length=200)] = 'default_value'

if __name__ == "__main__":
    a = MyModel()
    print(a)

```

**Comment by Gamrix** [comment]
Also, for people who get here, you can also fix this by making `default` a keyword argument.

**Comment by adriangb** [comment]
Thanks @Gamrix! It probably has to do with dataclass transform then. I wonder if that’s some thing we can fix
