### ISSUE TITLE
Exception handling during validation

### ISSUE THREAD

**Issue by TaZi-loh** [pydantic/pydantic#3915]
hi,
in our project, we often struggle with validation problems like the following
```
from pydantic import BaseSettings, validator


class OtherCfg(BaseSettings):
    c: int = 5

    @validator("c")
    def vali(cls, v):
        raise ValueError("something went wrong during validation")


class Cfg(BaseSettings):
    a: OtherCfg = None
    b: OtherCfg = None

    @validator("a", pre=True, always=True)
    def val(cls, v):
        if v is None:
            v = OtherCfg()
        return v

    @validator("b")
    def val2(cls, v, *, values):
        return values["a"]


print(Cfg())
```
The class `Cfg` has a member `a` that will receive a default value from its validator. The member `b` is now something that needs some information from `a`. Sometimes the validation of `a` does not succeed (like in the example above). 

The problem here is, that the error is only reported to the user during the validation of `b`, where even a `KeyError` is thrown and the program crashes with 
```
  File "/home/user/Coding/anything_goes.py", line 34, in <module>
    tmp = Cfg()
  File "pydantic/env_settings.py", line 36, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 404, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1040, in pydantic.main.validate_model
  File "pydantic/fields.py", line 716, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 913, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 279, in pydantic.class_validators._generic_validator_cls.lambda4
  File "/home/user/Coding/anything_goes.py", line 28, in val2
    return values["a"]
KeyError: 'a'
python-BaseException
```

My questions are:
- is this behavior intended?
- if so, how could I avoid it? Meaning how can I already stop the validation, after it failed for `a` and get a message, that there was a problem with `a`? (our configs are pretty involved and it sometimes takes quite some time to find the real culprit)

**Comment by 07pepa** [comment]
yes it is intended!
You need to use root_validator for complex relation of object
https://pydantic-docs.helpmanual.io/usage/validators/#root-validators

please read documentation before raising any issue and use debuger in your IDE to try to resolve it by yourself

and idealy please contribute to this project thanks

**Comment by TaZi-loh** [comment]
hi pepa, thank you for your reply. I know root-validators and use them regularly, but I don't see how they would help with this problem. Could you elaborate a bit more on this?

**Comment by TaZi-loh** [comment]
sry, I fear I did not explain my problem well enough. I will try to do better now =)

Image `Cfg` being a very large config (of some machine learning model but that doesn't matter too much). People write .json files to configure this by hand and they tend to make errors during the process. Now during the creation of `a` some mistake was recognized by the validator and accordingly a `ValueError` was risen. However the user doesn't get to know this. He doesn't see the `ValueError` but instead, he only realizes that something is wrong, when the `KeyError` in the validation of `b` is raised. But even then, he has no real clue, what went wrong. Moreover, from his perspective, the creation of `Cfg` could already stop at the point where the validators of `a` finished because the it will never finish successfully anyways.
That said, the above example looks simple, but when you operate with lots of `Union`s as types in your config, things spiral out of control quickly.

One solution I could think of would be an option in the `class Config` that would stop if an exception is raised. What do you think of that?

**Comment by 07pepa** [comment]
i get you now. BTW  i use pydantic to validate json/yaml configs as well and it is awsome.

if you read [this](https://pydantic-docs.helpmanual.io/usage/validators/) you will see this qote:
`"validators should either return the parsed value or raise a ValueError, TypeError, or AssertionError (assert statements may be used)."` This means that your (bug) that throws KeyError overules any validation and 

Since you are accesing something that does not exist you get key error
that is caused likely by someting like pre=True and always in 
`@validator("a", pre=True, always=True)`  (pre means before validation (may not be filled yet)  and always mean even if empty so value you get may be `None`)


 ### What to do now
* you should investigate why are you getting key error 
* i sugest you no not use validators if you can ( search if you can use [constrained type](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types) or [anotated field](https://pydantic-docs.helpmanual.io/usage/schema/#typingannotated-fields)  )  a lot can be done without validator
you are also using **BaseSettings** instead of **BaseModel** (use base model in your classes)
* posibly even change how json look i would do a AI seting something like this
```python
from pydantic import BaseModel, validator, conlist, PositiveInt


class Layer(BaseModel):
    some_value: int
    magic_value: PositiveInt


class AISettings(BaseModel):
    layers: conlist(Layer, max_items=6)
```
that would result in json like this
```json
{
   "layers":[{"some_value":5,"magic_value":6},{"some_value":7,"magic_value":8}]
}
```
* if you need mandatory value just make it part of model. If it is optional make it optional  and only then if it is sometimes optional add validator that will verify if it is missing or not

**Comment by TaZi-loh** [comment]
you are much closer now, but not yet 100% there.

You have to imagine, that the validator for `b` is in reality much more complicated and uses the value of `a` to derive a dynamic default value for himself. It is also known, that the `KeyError` causes a crash. 

But image how this feels for the user. He receives the `KeyError` but the actual mistake he made was somewhere else. And this is even an almost user friendly case, because the user can "guess" that he made a mistake in the config for `a`. 

Now consider the following (btw. everything I give as examples here has happened on multiple occasions in our project):
A member of type `Union[Cfg, <some_type>]` is part of another config. For the `Union` to be handled correctly, I can not afford to have this `KeyError` raised, when this member should be configured with <some_type> while pydantic tries to create `Cfg` first while stepping through the `Union`. So I have to modify the validator of `b` to something like:
```
if "a" not in values:
    raise ValueError("This should only fail during the creation of a Union. Otherwise you made a mistake in the configuration")
return values["a"]
```
Now the config creation won't crash anymore even if the user did something wrong, but the validation messages he gets become more and more opaque and you really have to be a pydantic specialist to find out, what the user did wrong (I spent days already debugging such things). 

Now the whole issue would be solved, if I could make pydantic stop in the creation of `Cfg` right at the first `ValueError`.

**Comment by 07pepa** [comment]
then i thin you need  raise Feature request to add skip_on_failure=True to validator like root validator does https://pydantic-docs.helpmanual.io/usage/validators/

**Comment by AdrianSosic** [comment]
Have the same issue and would definitely welcome a built-in solution. My current workaround is to raise a different exception type (one that is not caught by pydantic).

**Comment by samuelcolvin** [comment]
We have the new system of validators, including wrap validators in V2.

https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#validator-function-improvements
