### ISSUE TITLE
keep_untouched does not work with type-annotated descriptors

### ISSUE THREAD

**Issue by PhilReinhold** [pydantic/pydantic#3928]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
pydantic compiled: False
install path: /Users/pcrein/qdash/.venv/lib/python3.9/site-packages/pydantic
python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:28:27)  [Clang 11.1.0 ]
platform: macOS-11.6.5-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel

class Greeting:
    def __set_name__(self, owner, name):
        self.name = name

    def __get__(self):
        return f"hello, {self.name}"


class MyModel(BaseModel):
    x: str = Greeting()

    class Config:
        keep_untouched = (Greeting,)



m = MyModel()
print(m.dict())
# {'x': <__main__.Greeting object at 0x112befdc0>}
# Just {} if `str` annotation on x is omitted
```

I would expect `x` to be omitted from the model fields, regardless of whether it is given a type annotation. Maybe this was a deliberate choice, but I'm not sure why. I can get the behavior I expect by making `Greeting` inherit from `property`, but this is pretty ugly. I guess I would suggest that perhaps the `untouched_types` variable in `ModelMetaclass.__new__` have the `keep_untouched` section added for both annotated and un-annotated sections of the fields initialization, but maybe it's more complicated than that.

**Comment by Kludex** [comment]
This is working on V2.

See the adaptation for V2:

```python
from pydantic import BaseModel


class Greeting:
    def __set_name__(self, owner, name):
        self.name = name

    def __get__(self, instance, owner):  # There were 2 parameters missing!
        return f"hello, {self.name}"


class MyModel(BaseModel):
    x: str = Greeting()

    class Config:
        keep_untouched = (Greeting,)  # On v2 you should use `ignored_types` instead of `keep_untouched`.


m = MyModel()
print(m.dict())  # On v2 you should use `model_dump()` instead of `dict()`.
```

Since we are focusing on v2, and it's already solved there, I'll close this issue. 🙏
