### ISSUE TITLE
Assigning empty sequence to field resets the field to its default value

### ISSUE THREAD

**Issue by JoshPaterson** [pydantic/pydantic#3939]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/josh/.pyenv/versions/3.10.2/envs/lsmc/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Mar  1 2022, 19:37:34) [GCC 9.3.0]
                     platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel

class Unchecked(BaseModel):
    def __repr__(self):
        return '<unchecked>'

    def __str__(self):
        return repr(self)

UNCHECKED = Unchecked()


class Book(BaseModel):
    title: str | None | Unchecked = UNCHECKED

    class Config:
        validate_assignment = True


book = Book(**{})
print('Default value:', book.title)
book.title = 'testing1'
print(book.title)
book.title = []
print(book.title)

book.title = 'testing2'
print(book.title)
book.title = ()
print(book.title)

book.title = 'testing3'
print(book.title)
book.title = {}
print(book.title)
```
`UNCHECKED` is a custom sentinel value that I use similarly to `None`. When I try to set `book.title` to an empty sequence I expect a `ValidationError`, but instead the value is reset to the field's default value. If I remove `Unchecked` from the type hint for `Book.title` the `ValidationError is raised as expected, so the problem is related to that class.

**Comment by JoshPaterson** [comment]
If anyone else encounters this or if this turns out to be expected behavior I am currently getting around this by adding this validator:
```py
    @validator('title', pre=True)
    def not_empty_sequence(cls, v):
        if isinstance(v, list | tuple | set):
            raise ValidationError('Cannot be an empty sequence')
        return v
```

**Comment by Kludex** [comment]
This is working on V2, so I'll be closing this issue. 🙏
