### ISSUE TITLE
Hard-coded -O3 CFLAGS

### ISSUE THREAD

**Issue by TheChymera** [pydantic/pydantic#3942]
Is there a particular reason to hard-code `-O3` in setup.py?
https://github.com/samuelcolvin/pydantic/blob/d7a8272d7e0c151b0bd43df596be02e0d436ebdf/setup.py#L87

I use `-O3` globally and am very happy with it, but a lot of people seem to mistrust it, isn't it better to leave it to the system compilation settings to decide?

**Comment by samuelcolvin** [comment]
Well we want to use it in build in ci. Happy to switch to configure it via an environment variable.

**Comment by samuelcolvin** [comment]
I believe this is fixed on v1.X releases, and it definitely no longer applies on V2.
