### ISSUE TITLE
Json Type incompatible with Constrained Types `conlist`, `conset`

### ISSUE THREAD

**Issue by Toreno96** [pydantic/pydantic#3948]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/dstasczak/tmp/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Oct 13 2021, 06:43:20) [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel, Json, conlist

class Foo(BaseModel):
    foo: Json[conlist(int)]

foo = Foo(foo="[1, 2, 3]")
assert foo.foo == [1, 2, 3]
```

Output:
```py
$ python json_conlist.py
Traceback (most recent call last):
  File "/Users/dstasczak/tmp/json_conlist.py", line 6, in <module>
    foo = Foo(foo="[1, 2, 3]")
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Foo
foo
  value is not a valid list (type=type_error.list)
```

Expected would be no output actually, including passed assertion.

The same happens if I use `conset` instead of `conlist`. I didn't check the other iterable contained types. I checked `conint` and it works.

To compare, when using `list[int]` instead of `conlist[int]`:

```py
from pydantic import BaseModel, Json

class Foo(BaseModel):
    foo: Json[list[int]]

foo = Foo(foo="[1, 2, 3]")
assert foo.foo == [1, 2, 3]
```

```py
$ python json_list.py
$
```

Ofc `list[int]` is limiting, because in the final solution I want to use `min_items` kwarg of `conlist`.

**Comment by hramezani** [comment]
It's working as expexted in `Pydantic V2`

**Comment by selenecodes** [comment]
Isn't Pydantic V2 still in pre-release? Since it's not working in 1.10.7

**Comment by hramezani** [comment]
Yes it is on alpha state but we only provide patch and security patch for v1. So, we are not going to fix it on v1.
