### ISSUE TITLE
validator with pre and always set to True not called when no value and no default are provided

### ISSUE THREAD

**Issue by VianneyMI** [pydantic/pydantic#3955]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version : 1.8.2
pydantic compiled: True
python version: 3.8.6
platform: Windows 10
```

Sample code:

```py
from  pydantic import BaseModel, validator

class Test(BaseModel):
     x : int
 
     @validator("x", pre=True, always=True)
     def validate_x(cls, value):
         if not value:
             return 0
Test()
```

Expected output :

Test(x=0)

Result : 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Test
x
  field required (type=value_error.missing)

The validator is not called when x is not passed to the constructor while it should be according to the docs:

# Altervnatives

`Test(x=None)`

gives the expected output.
Similarly, setting a default in the schema works.

# Disclaimer

This is not a real use case but I did encounter this problem in a real and interesting case where I am trying to copy a value of a previously validated field in x

**Comment by accelleon** [comment]
A validator marked with `pre=True` doesn't create a default for a field that is unassigned. The validator gets called after field assignment but before type validation. All fields must be populated before any validators will be called.

Honestly a perfectly valid option to the above issue is:
```python
from  pydantic import BaseModel, validator

class Test(BaseModel):
     x : int = None
 
     @validator("x", pre=True, always=True)
     def validate_x(cls, value):
         if not value:
             return 0
Test()
```

**Comment by VianneyMI** [comment]
You're right on that point the example in the docs does set a default to `None` before modifying it dynamically.
However, I maintain that the name and even the wording in the docs suggest that the decorator will always be called and this is not the case.
Second it is misleading to set the "static" default to `None` here given that the field is not typed as Optional and is essentially required. Type checkers such as mypy will complain about it as shown below.
![image](https://user-images.githubusercontent.com/59029806/164187656-19e81b4d-6e50-4532-ba90-21d14066a4dc.png)

What I could do is to set a default with a compatible type (e.g. 0.0 in the example above) but again this is not optimal
Thanks for your help anyway @accelleon, but I'll leave this open for now.

**Comment by berzi** [comment]
I agree with VianneyMI and am having the same issue. Since I'm also using mypy, lying about the type by giving it a default of None and not annotating them as Optional is not a valid workaround.

`pre=True, always=True` validators should create fields that are not present at instantiation, I believe this would be the expected behaviour by most of those who read the docs on these parameters. And not giving any option to the programmer to set defaults short of willfully annotating a type incorrectly should not be the norm.

Say I have a BaseSettings subclass which requires some attribute `x`, but this attribute has to be populated at instantiation time. If I can do this through a validator I can use Pydantic's infrastructure to very elegantly populate the attribute with a default without disregarding any override the user might have provided with an environment variable. If this is not possible, then all of this has to happen outside the settings class.

**Comment by samuelcolvin** [comment]
I agree it doesn't make much sense. This will be fixed in v2.

**Comment by mojimi** [comment]
Is there another way of solving this using another approach other than validator? Changing __init__ maybe? Would love to get an example

**Comment by berzi** [comment]
@mojimi Overriding init is discouraged with Pydantic. You can use a root_validator.

**Comment by ieaves** [comment]
This isn't particularly elegant but for people using mypy who don't want to use a `root_validator` or fake an `Optional` annotation you can subclass your response type to create a valid defaul value which both satisfies mypy and triggers the pydantic validator. i.e.

```
class _DEFAULT_INT(int):
    pass

class TEST(BaseModel):
    id_field: int = _DEFAULT_INT(0)

    @validator("id_field", always=True, pre=True)
    def validate_id_field(cls, v):
        if isinstance(v, _DEFAULT_INT):
            # compute and return a default value
        else:
            return v
```

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.

**Comment by Vigilans** [comment]
I am using a wrap validator to manage a set of settings enabled by a single switch:
```python
@lru_cache
def enable_if(key: str) -> WithInfoWrapValidatorFunction:
    return lambda value, handler, info: handler(value) if info.data[key] else value

class Settings(BaseSettings):
    ldap_enabled: bool = Field(default=False)
    ldap_host: Annotated[str, WrapValidator(enable_if("ldap_enabled"))]
    ldap_port: Annotated[int, WrapValidator(enable_if("ldap_enabled"))]
    ldap_bind_dn: ...
```

However, `Field required` error making the `enabled_if` validator not called at all.
