### ISSUE TITLE
copy with include/exclude does not create properties for missing items

### ISSUE THREAD

**Issue by tl24** [pydantic/pydantic#3987]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/user/venvs/project/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 15 2021, 18:05:17)  [GCC 5.4.0 20160609]
                     platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
...
```

When you copy a model with include/exclude, the properties that aren't copied don't show up in the model at all.  Trying to reference any properties that weren't copied raises an AttributeError rather than just giving you back the default.
```py
from pydantic import BaseModel
class User(BaseModel):
     id: int
     name: str = None

user = User(id=3)
copied = user.copy(include={"id"})

# raises attribute error, instead of returning None
print(copied.name)

# prints None successfully
print(user.name)

```

**Comment by accelleon** [comment]
I suspect this is likely intended this way. The `copy()` method bypasses the validation. The default fields are actually populated by `validate_model()`. `validate_model()` is called in `__init__()` but we explicitly call `__new__()` to create the new object and avoid validation.

Judging by the docs example as well it seems intended.

**Comment by mrlonis** [comment]
Interesting.

Admittedly I haven't looked at the docs for the `copy()` method itself, as the name of the function "copy" just kind of implies that you get a copy of the object. Furthermore, when NO fields are excluded, it seems logical to assume that all other fields would just be included, albeit not initialized. Instead, the object results in key attributes missing, so you aren't getting a "copy" you're getting an entirely new arbitrary object. Which sure, I can workaround, but seems to defy all logic without having looked at the docs. I can see [here](https://pydantic-docs.helpmanual.io/usage/exporting_models/) though that the docs do kind of make this known.

I feel like if fields were marked as excluded, then okay sure those attributes can be dropped and result in an AttributeError, but when nothing is excluded, only included is provided, it doesn't make sense at first glance.

Thanks for explaining this in great detail @accelleon ! This makes a lot more sense now why Pydantic was behaving this way.

**Comment by accelleon** [comment]
@mrlonis 
The way I think about it is you're not actually copying the model but copying the things inside of it into something that resembles the original model. And even then its has more things that'll trip you up if you weren't aware of it.

Without `deep=True` the references inside of the 2 copied models *are the same*.
```python
from typing import List
from pydantic import BaseModel

class Foo(BaseModel):
    bar: List[str]

foo = Foo(bar=['a', 'b'])
foo2 = foo.copy()
foo3 = foo.copy(deep=True)

print(foo.bar)
#> ['a', 'b']
foo2.bar.append('c')
print(foo.bar)
#> ['a', 'b', 'c']
print(foo3.bar)
#> ['a', 'b']
```
This is also true for all of pydantic `exclude` and `include` imply the opposite attribute. If you've got a model with `a,b,c` and specify `include={'a'}`, `exclude={'b','c'}` is implicit.

**Comment by mrlonis** [comment]
@accelleon  Makes sense to me now! Again, I really appreciate your detailed responses to this, it has been really enlightening!

**Comment by Kludex** [comment]
On V2, this works as expected.

The `copy` method is deprecated, and the way you'd use the `include` parameter would be:

```py
from pydantic import BaseModel


class User(BaseModel):
    id: int
    name: str | None = None


user = User(id=3)
data = user.model_dump(include={"id"})
copied = user.model_validate(data)

print(copied.name)
print(user.name)
```

Since we are focusing on V2, I'll be closing this issue. 🙏
