### ISSUE TITLE
validator result depends on order of fields

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#3990]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Switching around the order of fields makes the test pass (as I would expect it for both cases).

I expect all values to be available. Am I missing something?
I know I can use a `root_validator` to circumvent that behaviour.
However, I have not found another report about that and decided to report it.

It occurs also with pydantic 1.8.2

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
pydantic compiled: True
path: /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/juice-auth-v2-3il_93qV-py3.9/lib/python3.9/site-packages/pydantic
version: 3.9.9 (main, Nov 30 2021, 17:19:58)  [Clang 13.0.0 (clang-1300.0.29.3)]
platform: macOS-12.2.1-arm64-arm-64bit
optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
import typing

import pydantic as pydantic
import pytest


class MyModel(pydantic.BaseModel):
    third: typing.Optional[str]
    second: typing.Optional[str]

    @pydantic.validator("third", always=True)
    def _ensure_third(cls, val, values):
        if not val and values.get("second"):
            raise ValueError("missing third")
        return val


def test_should_pass():
    with pytest.raises(ValueError, match="third"):
        MyModel(second="present", third=None)
```

**Comment by accelleon** [comment]
Functioning as intended per docs: https://pydantic-docs.helpmanual.io/usage/validators/

where validators rely on other values, you should be aware that:
* **Validation is done in the order fields are defined**. E.g. in the example above, `password2` has access to `password1` (and name), but `password1` does not have access to `password2`. See [Field Ordering](https://pydantic-docs.helpmanual.io/usage/models/#field-ordering) for more information on how fields are ordered
* If validation fails on another field (or that field is missing) it will not be included in `values`, hence `if 'password1' in values and ...` in this example.

`pre=True` root validators are the only validators guaranteed to have access to *all* values regardless of whether they validator or not.
non-root validators will only have access to values that both a) come before that field and b) passed their individual validation.
`pre=False` root validators where `skip_on_failure==False` will only have access to values that passed their individual validation.

**Comment by adamsuskin** [comment]
While this is documented and appears to be intentional, I'll chime in that this is a total gotcha. Coming from other languages, this is certainly not what I would expect for default validator behavior.

Perhaps there is a way to call it out a little louder in the docs and decorator docstring?

**Comment by dmontagu** [comment]
The `@validator` decorator has been deprecated in v2, and we recommend using `@model_validator` now if you need to do validation making use of multiple fields values together. That should eliminate any potential for confusion related to validator execution order.

**Comment by tstorek** [comment]
@dmontagu Is the `model_validator` command also available for v1? I have a project that uses the SettingsModel. Hence, I am still on v1

**Comment by acederberg** [comment]
Hi @tstorek,

I imagine that you have already found an answer elsewhere, but I thought it might be helpful to leave this comment for whoever needs it. 

> Is the model_validator command also available for v1? 

No, but you can use `root_validator` in v1 to approximate the functionality of `model_validator` in v2. 

> I have a project that uses the SettingsModel. Hence, I am still on v1

The functionality of `SettingsModel` can be replaced with `BaseSettings` from `pydantic_settings>=2.0.0`.
