### ISSUE TITLE
Validation fails to forbid extra fields for child objects passed in constructor

### ISSUE THREAD

**Issue by tjb9dc** [pydantic/pydantic#4015]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Validation fails to catch extra fields when a child object is passed into a model constructor in place of a field expecting something it inherits from. I.e., the model contains a field of some parent class type, but some child type is used instead which has extra fields compared to the parent. However, validation does catch the extra fields when building a model object via parse_obj.

The issue is [here](https://github.com/samuelcolvin/pydantic/blob/8997cc5961139dd2695761a33c06a66adbf1430a/pydantic/main.py#L667-L669), where a child object passes through without further inspection since child objects are instances of their parents. My guess is we want something like [this](https://github.com/samuelcolvin/pydantic/blob/8997cc5961139dd2695761a33c06a66adbf1430a/pydantic/main.py#L1030-L1042) to further inspect the fields of the child. We probably want this to work recursively, and might not want to just go back and forth between dictionary representations of objects, so I'm not sure what the best route is.

I've written tests that show the behavior in my fork of pydantic: https://github.com/tjb9dc/pydantic/commit/79187fc41652381d298572de9ac48e3d4a4fc05a

```

**Comment by tjb9dc** [comment]
There's also the added fun that if we fix this, we would be adding new validation which could fail at runtime for existing cases that pass :(

**Comment by hramezani** [comment]
In `V2` we decided to allow sub class objects.
If you dump the model by `model_dump` the extra field shouldn't be there.

you can change the behaviour by `revalidate_instances='always'`

Here is your example in `v2`:
```py
import pytest

from pydantic import BaseModel, ConfigDict


class ForbidExtraModel(BaseModel):

    model_config = ConfigDict(extra='forbid')


class Inner(ForbidExtraModel):
    core_field: str
    model_config = ConfigDict(extra='forbid', revalidate_instances='always')


class InnerChild(Inner):
    extra_field: str


class Outer(ForbidExtraModel):
    inner: Inner


def test_validation_from_constructor() -> None:
    # This test FAILS since the constructor does not validate
    with pytest.raises(Exception):
        Outer(inner=InnerChild(core_field='core_field', extra_field='extra_field'))


def test_validation_from_parse_obj() -> None:
    # This test SUCCEEDS since parse_obj recursively validates objects correctly
    outer_dict = {'inner': {'core_field': 'core_field', 'extra_field': 'extra_field'}}
    with pytest.raises(Exception)as e:
        Outer.model_validate(outer_dict)


def test_round_trip() -> None:
    # This test FAILS, but would change once test_validation_from_constructor() is fixed since it shouldn't be
    # possible to construct Outer this way. But it does fail currently and shows the inconsistency in validation
    outer_dict = Outer(inner=InnerChild(core_field='core_field', extra_field='extra_field')).model_dump()
    Outer.model_validate(outer_dict)
```
