### ISSUE TITLE
Runtime error for class types only defined in stub file

### ISSUE THREAD

**Issue by Delgan** [pydantic/pydantic#4021]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/delgan/Programmation/loguru/env/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
                     platform: Linux-5.16.16-arch1-1-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

```py
import logging.config
import pydantic
import dataclasses


@pydantic.dataclasses.dataclass
class Foo:
    conf: 'logging.config._RootLoggerConfiguration'
```

Hi.

Replacing `@pydantic.dataclasses.dataclass` with `@dataclasses.dataclass` works fine. In such case, `mypy` also reports no error and is able to correctly parse the `Foo.conf` type. However, the Pydantic decorator causes an exception while the file is executed:

```
Traceback (most recent call last):
  File "/home/delgan/Programmation/loguru/test.py", line 7, in <module>
    class Foo:
  File "pydantic/dataclasses.py", line 255, in pydantic.dataclasses.dataclass
    'default',
  File "pydantic/dataclasses.py", line 250, in pydantic.dataclasses.dataclass.wrap
    # When cls._FIELDS is filled in with a list of Field objects, the name
  File "pydantic/dataclasses.py", line 186, in pydantic.dataclasses._process_class
    MISSING = _MISSING_TYPE()
  File "pydantic/main.py", line 972, in pydantic.main.create_model
  File "pydantic/main.py", line 187, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 356, in pydantic.typing.resolve_annotations
    
  File "/usr/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'logging.config' has no attribute '_RootLoggerConfiguration'
```

The problem seems to come from Pydantic trying to access a class which only exists in the `.pyi` [stub file](https://mypy.readthedocs.io/en/stable/stubs.html) and is not available at runtime: https://github.com/python/typeshed/blob/a8504f269eaf975e709115388b5dae339270e880/stdlib/logging/config.pyi#L25

Do you think a workaround is possible? Maybe gracefully handling this kind of exception?

Note that in this case, the `_RootLoggerConfiguration` is not meant to be public but there exists libraries with public "stub only classes" (I used `logging.config` as an example for simplification reasons).

**Comment by samuelcolvin** [comment]
We could probably provide a more helpful exception and raise an `ImportError`, but I don't think it's really possible to imagine dealing with this any other way.

**Comment by Delgan** [comment]
I was thinking that maybe `pydantic` could try loading the stub file (which usually is valid Python as far as I know). 

```python
import types
import sys
import somelib

def load_stub_file(lib):
    name = lib.__name__ + "_types"
    path = lib.__file__ + "i"

    with open(path) as file:
        stub = file.read()

    module = types.ModuleType(name)
    exec(stub, module.__dict__)
    sys.modules[name] = module

load_stub_file(somelib)
import somelib_types
```

In case of initial `AttributeError`, give another try using the "stub lib" (if available), finally give up.

**Comment by adriangb** [comment]
We won't be able to load stub files like this, that would be a pretty major feature request that I imagine has a lot of gotchas (what if you define a model with a validator in the stub file? do we run it?). There also doesn't seem to be a huge push from the community for this feature (0 thumbs up on this issue) so I'm going to close this as a wontfix, at least for now.
