### ISSUE TITLE
Forward reference on model's attribute is inconsistent

### ISSUE THREAD

**Issue by Drachenfels** [pydantic/pydantic#4090]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: $HOME/experiments-pydantic-forward-ref/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0]
                     platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

# Bug

## Description

When using forward references on pydantic's models attributes, they are resolved as soon as they are declared (and present in module's global scope I observed). It's good enough if it's a different model elsewhere but problematic if what we use is a lazy-loading wrapper class, defeating the purpose of lazy-loading. 

## Self-contained code

Works as-is, only pydantic is needed.

```py
from __future__ import annotations

import enum

from pydantic import BaseModel

mode = 'no-pydantic'


if mode == 'no-pydantic':
    class MyBaseModel:
        def __init__(self, a, b: settings.LazyFruits = None):
            self.a = a
            self.b = b

        def dict(self):
            return {
                'a': self.a,
                'b': self.b,
            }

elif mode == 'with-pydantic':
    MyBaseModel = BaseModel

else:
    raise RuntimeError("Set mode to either: with-pydantic or no-pydantic")


class Fruits(str, enum.Enum):
    banana = "BANANA"
    orange = "ORANGE"
    apple = "APPLE"


class LazyFruits:
    def __init__(self):
        self._initialized = False
        self._dict = {}

    def setup(self):
        if self._initialized:
            return

        print("CALLED SETUP!")

        self._dict["FRUITS"] = Fruits

        self._initialized = True

    def __getattr__(self, attr):
        self.setup()

        return self._dict[attr]


print("A" * 40)


class Model1(MyBaseModel):
    a: int
    b: settings.FRUITS = None


print("B" * 40)

settings = LazyFruits()

print("C" * 40)


class Model2(MyBaseModel):
    a: int
    b: settings.FRUITS = None


print("D" * 40)

print("We expect setup now, not before")

print(settings.FRUITS)

ff = Model2(a=1, b="BANANA")
print(ff.dict())

ff = Model1(a=1, b="BANANA")
print(ff.dict())
```

The expected outcome: (pick: mode == 'no-pydantic'):
```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
We expect setup now, not before
CALLED SETUP!
<enum 'Fruits'>
{'a': 1, 'b': 'BANANA'}
{'a': 1, 'b': 'BANANA'}
```

We get: (pick: mode == 'with-pydantic')
```
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CALLED SETUP!
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
We expect setup now, not before
<enum 'Fruits'>
{'a': 1, 'b': <Fruits.banana: 'BANANA'>}
Traceback (most recent call last):
  File "cc.py", line 85, in <module>
    ff = Model1(a=1, b="BANANA")
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1038, in pydantic.main.validate_model
  File "pydantic/fields.py", line 833, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "b" not yet prepared so type is still a ForwardRef, you might need to call Model1.update_forward_refs()
```

There will be as well config error that Model1 is still ForwardRef.

Caveat: Perhaps I am missing some information about pydantic on how it should behave, however documentation does not cover anything similar to my use-case (https://pydantic-docs.helpmanual.io/usage/postponed_annotations/#self-referencing-models).

What I know for certain is that if we stop superclassing Model with BaseModel of pydantic, this evaluation disappears but if we remove import future, it will be back again - as expected.

**Comment by samuelcolvin** [comment]
I don't really understand what you're suggestion the bug is.

Is this new in version v1.9.1, could it be related to #3713?

**Comment by Liron-Berger** [comment]
`__getattr__` here is called during the instansiation of the class `LazyFruits`.

Consider the following example:
```python
from pydantic import BaseModel

class LazyFruits:
    def __getattr__(self, attr):
        raise NotImplementedError()

settings = LazyFruits()

class Model1(BaseModel):
    b: "settings.FRUITS" = None
```
The creation of `Model1` will fail in the `__new__` method of `ModelMetaclass`.
(`resolve_annotations` analyzes the annotations of the class, which in turn trigger the `__getattr__` method of `LazyFruits`.)

Not sure if this is a bug though as you are trying to call some logic during the annotation of an attribute.

**Comment by Drachenfels** [comment]
Hi guys,

To clarify a bit more.

If we remove pydantic from the code above, despite having settings.FRUIT as annotation, setup() and __getattr__ will never trigger unless we access settings.FRUIT (as expected).

But use BaseModel of Pydantic as supercalss of Model1 or Model2 and forward reference stops working, setup() and by extension __getattr__ will be called. Triggering cascade of function calls that prematurely will materialize settings.

I have modified the code so that you guys can run it with or without pydantic.

**Comment by Drachenfels** [comment]
> Not sure if this is a bug though as you are trying to call some logic during the annotation of an attribute.

Exactly my point, I do not want to call any logic and pure Python is not going to but Pydantic does.

**Comment by Kludex** [comment]
Given that the code in the OP gives the proposed output on V2, I'll be closing this issue.
