### ISSUE TITLE
Incorrect schema generation, conflict with python-jsonschema

### ISSUE THREAD

**Issue by thevoiddancer** [pydantic/pydantic#4111]
I'm sorry in advance if this is already covered somewhere.

### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/thevoiddancer/miniconda3/envs/sbox/lib/python3.8/site-packages/pydantic
               python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0]
                     platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.17
     optional deps. installed: ['email-validator', 'typing-extensions']
```

So In the last week I've run across multiple cases where pydantic generates a schema that crashes with json schema validator using jsonschema.validate. Following examples should demonstrate two of those situations. They are runnable as is.

### Example 1: Optional
Code below should pass on all three variations of parameters, both for pydantic and jsonschema validation. However, it fails on second one, when specifying None as value, but fails only on jsonschema - it passes on pydantic validation, as it should. Same thing happens if pet_type has a default value.
#### Code
```py
from pydantic import BaseModel
from typing import Optional
from jsonschema import validate

class Pet(BaseModel):
    pet_type: Optional[str]

print("Should pass both:")
params = {'pet_type': 'cat'}
try:
    Pet(**params)
    print("pass pydantic validation")
except:
    print("fails pydantic validation")
try:
    validate(instance=params, schema=Pet.schema())
    print("pass jsonschema validation")
except:
    print("fails jsonschema validation")

print("Should pass both:")
params = {'pet_type': None}
try:
    Pet(**params)
    print("pass pydantic validation")
except:
    print("fails pydantic validation")
try:
    validate(instance=params, schema=Pet.schema())
    print("pass jsonschema validation")
except:
    print("fails jsonschema validation")

print("Should pass both:")
params = {}
try:
    Pet(**params)
    print("pass pydantic validation")
except:
    print("fails pydantic validation")
try:
    validate(instance=params, schema=Pet.schema())
    print("pass jsonschema validation")
except:
    print("fails jsonschema validation")
```

#### Output
```
Should pass both:
pass pydantic validation
pass jsonschema validation
Should pass both:
pass pydantic validation
fails jsonschema validation
Should pass both:
pass pydantic validation
pass jsonschema validation
```

Schema it generates looks like
```
{
  'title': 'Pet',
  'type': 'object',
  'properties': {
    'pet_type': {
      'title': 'Pet Type', 
      'type': 'string'
    }
  }
}
```
whereas the correct schema for optional should be
```
{
  'title': 'Pet',
  'type': 'object',
  'properties': {
    'pet_type': {
      'title': 'Pet Type',
      'oneOf': [
        {'type': 'string'}, 
        {'type': 'null'}
      ]
    }
  }
}
```

The second schema passes on jsonschema.validate, but the first one doesn't.

### Example 2: Optional
Code below should fail, and it does. But it is expected that the failure be in an informative way. For pydantic validation that is correct, but that fails again on jsonschema validation. This is not such a huge bug (still fails when it should fail), but usage of discriminator should focus the validation not to go through every possible version, but to just check one, the one with the correct discriminator. The error output directs the user to something completely different, defeating the purpose of using validation and discriminator.

#### Code
```py
from pydantic import BaseModel, Field
from typing import List, Union, Literal
from typing_extensions import Annotated
from jsonschema import validate

class Cat(BaseModel):
    pet_type: Literal['cat']
    meows: bool

class Dog(BaseModel):
    pet_type: Literal['dog']
    barks: bool

Pets = Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]

class Pets(BaseModel):
    my_pets: List[Pets]

params = {'my_pets': [
    {'pet_type': 'cat'},
]}
try:
    Pets(**params)
    print("pass pydantic validation")
except Exception as e:
    print("fails pydantic validation")
    print(e)
try:
    validate(instance=params, schema=Pets.schema())
    print("pass jsonschema validation")
except Exception as e:
    print("fails jsonschema validation")
    print(e)
```

#### Output
```
fails pydantic validation
1 validation error for Pets
my_pets -> 0 -> Cat -> meows
  field required (type=value_error.missing)
fails jsonschema validation
'cat' is not one of ['dog']

Failed validating 'enum' in schema[1]['properties']['pet_type']:
    {'enum': ['dog'], 'title': 'Pet Type', 'type': 'string'}

On instance['pet_type']:
    'cat'
```

The problem is that the error message - `'cat' is not one of ['dog']` - not only points to a class that was not used, it doesn't correctly identify what was the problem (lack of 'meows' parameter). 

Is such behavior expected, or is it a bug? And is there a way to force correct schema generation without manually correcting every class by using `schema_extra`?

**Comment by incorvia** [comment]
I've also run into this bug. I was surprised considering I thought this use of optional failing under a None condition to be such a common use case that it would have been handled or discussed more thoroughly. I was starting to think maybe my assumption of what Optional should do was wrong, that perhaps the intention was that it should allow no key, but fail on existence of none but it's nice to see these tests above to showcase the issue.

**Comment by adrien-turiot-maxa** [comment]
We also face this issue, here is a minimal example having the issue:

```py
from pydantic import BaseModel
from typing import Optional
import jsonschema

class MyModel(BaseModel):
    value: Optional[int]

jsonschema.validate({"value": None}, MyModel.schema())  # ValidationError: None is not of type 'integer'
```

**Comment by PrettyWood** [comment]
Yep nullable in generated json schema is not properly handled. It'll be there in v1.10 or v2

**Comment by samuelcolvin** [comment]
If it fixed in master of is there a PR?

**Comment by PrettyWood** [comment]
https://github.com/samuelcolvin/pydantic/pull/1611

**Comment by dmontagu** [comment]
This seems to be fully resolved in v2, with the only caveat being that you need to set a default value of `None` for your first example to work:
```python
class Pet(BaseModel):
    pet_type: Optional[str] = None
```
In the second, you now get:
```python
1 validation error for Pets
my_pets.0.cat.meows
  Field required [type=missing, input_value={'pet_type': 'cat'}, input_type=dict]
```
Which seems correct. In general I think we've made some major improvements to the way JSON schema is generated, so hopefully we have fewer of these bizarre inconsistencies/inaccuracies going forward. (Please continue to report things if you run into problems.)
