### ISSUE TITLE
Custom Data Type validators are not called when using square bracket type hints

### ISSUE THREAD

**Issue by lukitox** [pydantic/pydantic#4122]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.1
pydantic compiled: True
install path: /home/lhilbers/.conda/envs/***/lib/python3.9/site-packages/pydantic
python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)  [GCC 9.4.0]
platform: Linux-5.13.0-44-generic-x86_64-with-glibc2.31
optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```
Hello everybody,

i wanted to add a method to a list attribute of a model. So i read the [Custom Data Types](https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types) example in the documentation and implemented my own custom list type inheriting from [`collections.UserList`](https://docs.python.org/3/library/collections.html#collections.UserList).
When not using the square bracket type hints for the UserList's items, it works like expected. The given normal list is converted to the custom list at instantiation.

When adding type hints, the validation of the lists items according to the hints works fine, but the type conversion into `UserList` is gone, because somehow the validator is not called any more.

## Minimal working example

```py
from pydantic import BaseModel
from collections import UserList


class CustomList(UserList):

    @classmethod
    def __get_validators__(cls):
        yield cls.validate
        
    @classmethod
    def validate(cls, v):
        print("I'm called")
        return cls(v)

    def some_custom_method(self):
        pass
    
class ItemType(BaseModel):
    a: str
    b: int  
    
class SomeModel(BaseModel):
    some_list: CustomList[ItemType]  #  If the Type hint is removed, the validator is called
    
foo = SomeModel(
    some_list=[ItemType(a='foo', b=23), ItemType(a='baz', b=42)]
)
assert isinstance(foo.some_list, CustomList), f"{type(foo.some_list)=} is normal list. Notice that the validator has not been called"
```
Results in:
```py
AssertionError: type(foo.some_list)=<class 'list'> is normal list. Notice that the validator has not been called
```

If i remove the type hint in the model definition, `some_list` is of type `CustomList`, like expected. But the type validation  of the items is gone:
```py
class SomeModel(BaseModel):
    some_list: CustomList  #  no [ItemType]
    
foo = SomeModel(
    some_list=[ItemType(a='foo', b=23), ItemType(a='baz', b=42)]
)

print(type(foo.some_list))
```
Prints
```py
I'm called
<class '__main__.CustomList'>
```

## Additional notes:
- Inheriting from `list` instead of `UserList` leads to identical behaviour.

Thank you for your great work on pydantic :grinning:. I hope that i did not miss something and waste your time because of that :innocent:.

**Comment by dmontagu** [comment]
There are various challenges here that would be required to get this working in v1:
* You need to create a custom subclass of `types.GenericAlias` that proxies the `__get_validators__` to the origin
* Because `UserList` isn't a subclass of `typing.List`, the current v1 logic goes down the sequence path, and ends up not grabbing validators off the type (I'm not sure why this isn't done)
* The current approach to validating sequences applies the type-provided validators before doing others (was able to get this to happen by inheriting from both `UserList` and `List`), so it ends up getting converted back to a list anyway; this would need to be changed.

Ultimately this would require significant enough changes that it won't be done for v1.

-----

However, this should be fairly straightforward to handle properly in v2:

```python
from collections import UserList
from typing import Any, get_args, List, Callable

from pydantic_core import core_schema

from pydantic import BaseModel


class CustomList(UserList):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: Callable[[Any], core_schema.CoreSchema]
    ) -> core_schema.CoreSchema:
        args = get_args(source_type)
        if args:
            schema = handler(List[args])
        else:
            schema = handler(List)
        return core_schema.no_info_after_validator_function(cls.validate, schema)

    @classmethod
    def validate(cls, v):
        print("I'm called")
        return cls(v)

    def some_custom_method(self):
        pass


class ItemType(BaseModel):
    a: str
    b: int


class SomeModel(BaseModel):
    some_list: CustomList[ItemType]  # If the Type hint is removed, the validator is called


foo = SomeModel(
    some_list=[ItemType(a='foo', b=23), ItemType(a='baz', b=42)]
)
assert isinstance(foo.some_list,
                  CustomList), f"{type(foo.some_list)=} is normal list. Notice that the validator has not been called"
```
This prints "I'm called" and does not raise the AssertionError
