### ISSUE TITLE
Union produces anyOf instead of oneOf for OpenAPI generation

### ISSUE THREAD

**Issue by stdkoehler** [pydantic/pydantic#4125]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: C:\Users\DEKOEHLS\Programme\Anaconda3\Lib\site-packages\pydantic
               python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19042-SP0
     optional deps. installed: ['dotenv', 'typing-extensions']
```

```py
from typing import Literal, Union
from pydantic import BaseModel, Field


class Cat(BaseModel):
    pet_type: Literal['cat']
    meows: int


class Dog(BaseModel):
    pet_type: Literal['dog']
    barks: float


class Pet(BaseModel):
    __root__: Union[Cat, Dog] = Field(..., discriminator='pet_type')

Pet.schema_json()
```

Hi all,

Example from https://pydantic-docs.helpmanual.io/usage/types/#discriminated-unions-aka-tagged-unions:

Using the class Pet above in FastAPI to allow either Cat or Dog as an input leads to an OpenAPI.json which makes Pet like (printed as yaml)

````yaml
Pet:
  anyOf:
  - $ref: '#/components/schemas/Cat'
  - $ref: '#/components/schemas/Dog'
  
  discriminator:
    propertyName: pet_type
````

both OpenApi (https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) and the specification https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#discriminatorObject linked by the pydantic docs (link on top) state that it should be oneOf.
This also corresponds to the "typing" interpretation of *Union* which is, besides the naming, not a union of the arguments but a "one of those elements"

I already found a issue here which has been closed:
https://github.com/samuelcolvin/pydantic/issues/656
I didn't understand the arguments to be honest, However, I think it's just wrong to make it an anyOf.

I tried to post it on FastAPI since it leads to an incorrect openapi.json so I thought maybe a workaround on FastAPI side was meaningful. They forwarded me back here though.
https://github.com/tiangolo/fastapi/issues/4959

Best
Stefan

**Comment by MaxwellPayne** [comment]
I agree that this is a bug. I ran into an issue when using [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate a TypeScript SDK from an `anyOf` discriminated union that was generated by Pydantic. The generated TypeScript code looked incorrect when my models used `anyOf`, but worked just fine once I switched to `oneOf`.

I opened #4335 to propose a fix.
