### ISSUE TITLE
printing instance of model derived from BaseModel does not call __repr__

### ISSUE THREAD

**Issue by lwanger** [pydantic/pydantic#4133]
### Checks

* [X ] I added a descriptive title to this issue
* [ X] I have searched (google, github) for similar issues and couldn't find anything
* [ X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I have defined a simple Pydantic model that is derived from BaseModel. The model has a __repr__ method defined on it. calling print on the model (i.e. print(model) ) does not call the __repr__ method. The documentation for print says it will first look for a __str__ method and if not found use the __repr__ method, so the provided __repr__ should be called.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: D:\onedrive_ves\OneDrive - Velocity E Sports\code\tms\venv\pytms\Lib\site-packages\pydantic
               python version: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['dotenv', 'typing-extensions']
...
```py
from pydantic import BaseModel

class Status(BaseModel):
    name: str

    def __repr__(self):
        return f"Status __repr__ called"

if __name__ == '__main__':
    status = Status(name="Cancelled")
    print(status)  # should call __repr__ but doesn't
...

output:
```
name='Cancelled'
```

should be:
```
Status __repr__ called
```

**Comment by hramezani** [comment]
You can change it by override `__str__` in V2
