### ISSUE TITLE
Optional field not working in dataclass inheritance

### ISSUE THREAD

**Issue by SHxKM** [pydantic/pydantic#4134]
### Checks

* [ X ] I added a descriptive title to this issue
* [ X ] I have searched (google, github) for similar issues and couldn't find anything
* [ X ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
          pydantic version: 1.9.0
          pydantic compiled: True
          install path: /Users/me/.virtualenvs/me/lib/python3.6/site-packages/pydantic
          python version: 3.6.8 (default, Aug 30 2021, 20:27:20)  [GCC Apple LLVM 12.0.5 (clang-1205.0.22.11)]
          platform: Darwin-20.6.0-x86_64-i386-64bit
          optional deps. installed: ['dotenv', 'typing-extensions']
```

While debugging a separate issue, I came across a case where declaring a field as `Optional` does not work in the following scenario:

```py
from pydantic.dataclasses import dataclass

class ApiBaseModelConfig:
    alias_generator = to_camel


@dataclass(config=ApiBaseModelConfig)
class ApiBaseModel:
    foo: Optional[AnyStr]


@dataclass
class ApiIdentifiable(ApiBaseModel):
    id: str
    type: str
    href: str


@dataclass
class ApiSomeObject(ApiIdentifiable):
    attributes: ApiSomeObjectAttributes
    relationships: ApiSomeObjectRelationships


some_api_object = {...}
ApiSomeObject(**some_api_object)
```

And the error output:

```
    ApiSomeObject(**item)
TypeError: __init__() missing 1 required positional argument: 'foo'
```

**Comment by PrettyWood** [comment]
Please share a proper [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example). I can't reproduce your bug
