### ISSUE TITLE
Memory usage increases significantly going from pydantic 1.9.0 to 1.9.1

### ISSUE THREAD

**Issue by mansoor2016** [pydantic/pydantic#4160]
### Checks

* [X ] I added a descriptive title to this issue
* [X ] I have searched (google, github) for similar issues and couldn't find anything
* [X ] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/mansoor/source/test-oracle/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, May 23 2022, 22:01:06)  [GCC 9.4.0]
                     platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']

```
Updating between pydantic 1.9.0 and 1.9.1 results in a dramatic spike in memory usage for our production application. This is most prominent where we have deep nested BaseModel classes serialising large amounts of data to json.

![Peak memory usage](https://user-images.githubusercontent.com/20601657/173560182-c5a20026-4ec0-4b39-aaa8-014ae639a898.png)

The memory profiler indicates that Pydantic 1.9.1 is deep copying dictionary data, which it was not doing before

![Pydantic memory usage spike (censored)](https://user-images.githubusercontent.com/20601657/173570017-48ad916e-842b-43eb-8d8c-c109c2b01842.png)

Attempted MRE:
There is a ~40% increase in mem usage for this example

```
from typing import Generic, TypeVar, List

import orjson
import tempfile
from pydantic import BaseModel, Field
from pydantic.generics import GenericModel

_T = TypeVar('_T')


class MyGenericValue(GenericModel, Generic[_T]):
    value: _T


class GenericValueList(GenericModel, Generic[_T]):
    __root__: List[MyGenericValue[_T]]


class MyClass(BaseModel):
    n = 10000
    my_list: GenericValueList[float] = \
        Field(GenericValueList(__root__=[MyGenericValue(value=42.0)] * n))


if __name__ == '__main__':
    nested_base_model = MyClass()
    tdm_json = orjson.dumps(nested_base_model.dict())
    output_file = tempfile.NamedTemporaryFile()
    with open(output_file.name, "wb") as fh:
        fh.write(tdm_json)
```

**Comment by samuelcolvin** [comment]
Is this related to #3641?

How does the memory profile compare with v1.8.2?

Can you provide a self contained, minimal example?

**Comment by samuelcolvin** [comment]
opposite problem, but might be worth looking at #3829 too.

**Comment by mansoor2016** [comment]
I've have produced a minimal reproducible example,

**Comment by kveretennicov** [comment]
@samuelcolvin, is this issue on some kind of roadmap? Cheers
