### ISSUE TITLE
Support TypeVar/Generic in BaseModels

### ISSUE THREAD

**Issue by PythonCoderAS** [pydantic/pydantic#4171]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I would like to be able to use TypeVars/Generics when defining model types.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/User/.local/share/virtualenvs/Wayback-Archiver-Server-1UzVHoC9/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, May 24 2022, 21:28:44)  [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-11.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel
from typing import Generic, TypeVar

T = TypeVar("T", bound=BaseModel)

class SomeClass(BaseModel, Generic[T]):
    data: list[T]
    attr: str

class AnotherClass(BaseModel):
    attr2: int

x = SomeClass[AnotherClass]
```

A current workaround is to subclass and redefine, such as:

```py
class AnotherClassInSomeClass(SomeClass[AnotherClass]):
    data: list[AnotherClass]
```

**Comment by JP-Dhabolt** [comment]
@PythonCoderAS You can do what you are looking for using `from pydantic.generics import GenericModel` instead of using the `BaseModel`.  I use this extensively.

**Comment by PythonCoderAS** [comment]
What is the difference between BaseModel and GenericModel? I pass these models to FastAPI so I'm not sure if GenericModel will work.

**Comment by JP-Dhabolt** [comment]
I will defer to the documentation on the exact differences, but it is in place as the supported way to work with generics: https://pydantic-docs.helpmanual.io/usage/models/#generic-models

I use these extensively for FastAPI models, and they work without a hitch.  The OpenAPI spec will show `SomeClass[AnotherClass]` (in your use case) as the name of the model. They also work deeply nested.

**Comment by dmontagu** [comment]
This is fixed in v2 — we re-implemented generics in v2 in such a way that you can do precisely what is shown in the main body of this issue, no more `GenericModel`.

**Comment by salman14890** [comment]
I received user warning UserWarning: `pydantic.generics:GenericModel` has been moved to `pydantic.BaseModel`.

In my schemas.py I use from pydantic import BaseModel

I am not getting what's the change I need to add. Can anyone help me.

**Comment by Kludex** [comment]
> I received user warning UserWarning: `pydantic.generics:GenericModel` has been moved to `pydantic.BaseModel`.
> 
> In my schemas.py I use from pydantic import BaseModel
> 
> I am not getting what's the change I need to add. Can anyone help me.

https://docs.pydantic.dev/latest/migration/#changes-to-pydanticgenericsgenericmodel
