### ISSUE TITLE
Use construct to generate model can not set alias to False when export dict

### ISSUE THREAD

**Issue by GGGoingdown** [pydantic/pydantic#4174]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.9.0
pydantic compiled: True
python version: 3.9.7 (default, Jan 26 2022, 09:05:50)  [GCC 7.5.0]
```

```py
import pydantic

class User(BaseModel):
    user_name: str = Field(alias="name")
    age: int

fake_user = {"name": "gggoingdown", "age": 28}
user = User.construct(**fake_user)
print(user.dict(by_alias=False))
# Expect output : 
{"user_name": "gggoingdown", "age": 28}
# Get : 
{'name': 'gggoingdown', "age": 28}
...
```

**Comment by hramezani** [comment]
It's working as expected in V2
