### ISSUE TITLE
Result of default_factory is not type-checked against annotation

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#4175]
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

I expect that the instance that the default_factory produces is type-checked against the annotated type. Instanciating the model without providing a value for `field` creates an invalid model here.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/juice-report-m7V9HNF8-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Nov 30 2021, 17:19:58)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-12.4-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
import pydantic


class One:
    ...


class Other:
    ...


class C(pydantic.BaseModel):
    field: One = pydantic.Field(default_factory=Other)

    class Config:
        arbitrary_types_allowed = True


def test_default():
    with pytest.raises(ValueError):
        assert C()

```

**Comment by dolfinus** [comment]
It's even worse:
```python
>>> class A(BaseModel):
...   abc: int = '123'
... 
>>> A()
A(abc='123')
>>> A().abc
'123'
```

**Comment by PrettyWood** [comment]
You need to set `Config.validate_all` to `True` to validate default values. See [the doc](https://pydantic-docs.helpmanual.io/usage/model_config/)

**Comment by dolfinus** [comment]
Thank you, I've missed this option
