### ISSUE TITLE
Pickling error with `create_model`

### ISSUE THREAD

**Issue by sunnyosun** [pydantic/pydantic#4178]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /opt/miniconda3/envs/py39/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52)  [Clang 13.0.1 ]
                     platform: macOS-12.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Minimum Reproducible Example

```py
from pydantic import create_model, BaseModel
import pickle

class Model1(BaseModel):
    x: str = 'a'
    y: str = 'b'

Model2 = create_model('Model1', **{'x': 'a', 'y': 'b'})

print(pickle.dumps(Model1))
print(pickle.dumps(Model2))

```

Pickling error with Model2 but not Model1
<img width="648" alt="Screen Shot 2022-06-22 at 01 44 50" src="https://user-images.githubusercontent.com/38218185/174864913-fa447da7-ce40-4b03-8d73-3ca0ad3ee010.png">

**Comment by raceychan** [comment]
I know this is irrelevant, but may I ask what IDE do you use for jupyter? that tracebook looks great.

**Comment by sunnyosun** [comment]
I use the integrated Jupiter notebook in vs-code! :)

~Sunny
