### ISSUE TITLE
Cannot serialize Model to dict/json when it includes field of type Set[SomeHashableModel]

### ISSUE THREAD

**Issue by phdowling** [pydantic/pydantic#4186]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']

```
Runnable example:

```py
from typing import Set
from pydantic.main import BaseModel

class MyObject(BaseModel):
    a: str

    def __hash__(self):
        return hash(self.a)

    def __eq__(self, other):
        return self.__class__ == other.__class__ and self.a == other.a

class MyNestedObject(BaseModel):
    objs: Set[MyObject]

a = MyNestedObject(objs={MyObject(a="hello world")})  # works fine (but only when we add __hash__ above)
a.dict()  # fails: unhashable type 'dict'
a.json()  # fails: unhashable type 'dict'
```
What's the correct way (if any) to serialize such a model to JSON, or turn it into a dict? I can think of some workarounds around registering custom validators or overriding .dict() and .json() to convert to a list under the hood, but that seems quite hacky. Based on searching around the docs and other issues, I get the sense that this is meant to work out of the box (and possibly even worked at some point?). The issue came up in 1.8.2 as well for me, I did not try to reproduce it in older versions. Any help is greatly appreciated!

**Comment by phdowling** [comment]
This is something of a workaround I was able to come up with to fix `.dict()`, but it seems inefficient and prone to errors or unintended effects:
```python
class MyNestedObject(BaseModel):
    objs: Set[MyObject]

    def dict(
        self, *args, **kwargs
    ):
        changed = set()
        for k, v in self:
            if isinstance(v, set):
                setattr(self, k, list(v))
        res = super(MyNestedObject, self).dict(*args, **kwargs)
        for k in changed:
            setattr(self, k, set(getattr(self, k)))
        return res
```
In fact, it definitely has one side-effect: it fixes `.json()` as well, but only if you run `.dict()` first.

**Comment by raceychan** [comment]
```python
from typing import Set
from pydantic.main import BaseModel

class MyObject(BaseModel):
    a: str

    class Config:
        frozen=True

class MyNestedObject(BaseModel):
    objs: Set[MyObject]

a = MyNestedObject(objs={MyObject(a="hello world")})  # works fine (but only when we add __hash__ above)
a
```

**Comment by phdowling** [comment]
`dict(a)` only turns the outer object into a dict. I assume the problem is that `a.dict()` turns the inner objects into dicts first and then tries to add them to a `set` (rather than straight into the final `list` container they would eventually end up in)

**Comment by MauriceBenink** [comment]
The main issue is that you cannot hash a `dict` or `list`. And you want to store your values in a `set`. Which requires hashable values .

my suggestion would be 
     Either overwriting the dict() method to return a `tuple` of `key`, `value` tuples
     Changing the type of `MyObject` to a `NamedTuple`, # Named tuple does lose the key value when converting to json

```python
from typing import Set
from pydantic.main import BaseModel



class TupleDict(dict):
    """
    This class wont be used directly. This is simply used to separate the hashing / compare logic
    """
    def dict(self):
        return tuple(self.items())
    
    def __hash__(self):
        return hash(e for e in self.dict())
    
    def __eq__(self, other):
        if not self.__class__ == other.__class__:
            if isinstance(other, tuple):    # Allows for direct comparison against tuples
                return hash(self) == hash(e for e in other)
        return hash(self) == hash(other)


class TupleModel(BaseModel):
    """
    Class for merging initial 2 classes, This is mainly for ensuring the __eq__ works as expected
    TupleDict not directly inherited to prevent it easily being changed
    Hash has to be redefined becuase the __eq__ also changed
    __eq_model__ + __eq_hash__ is to store the compare of the parents somewhere other then __eq__
    """
    __hash__ = TupleDict.__hash__
    __eq_model__ = BaseModel.__eq__
    __eq_hash__ = TupleDict.__eq__
    
    def __eq__(self, other):
        if isinstance(other, BaseModel):
            return self.__eq_model__(other)
        return self.__eq_hash__(other)
    
    def dict(self, *args, **kwargs):
        return tuple(super().dict(*args, **kwargs).items())


class MyObject(TupleModel):
    a: str
    b: str


class MyNestedObject(BaseModel):
    objs: Set[MyObject]


a = MyNestedObject(objs={MyObject(a="hello world", b="hi")})  # works fine (but only when we add __hash__ above)

assert a.dict() == {'objs': {(('a', 'hello world'), ('b', 'hi'))}}
assert a.json() == '{"objs": [[["a", "hello world"], ["b", "hi"]]]}'


```

**Comment by apirogov** [comment]
I've run into the same issue, but I would like to have `__eq__` and `__hash__` work + support sets of models (like here), but still keep `dict()` and `json()` behave normally. Is there a "clean" way to do that without hacking `_get_value`?

**Comment by mwgamble** [comment]
This issue also affects comparisons. I have tests that are trying to run this code:

```
assert actual == expected
```

Where `actual` and `expected` are Pydantic models that contain sets of nested models. This doesn't work, because the comparison logic works by converting both models to dictionaries, which runs into the issue in this thread.

Fixing this requires manually overriding the `__eq__` method for all affected classes, which quickly gets unwieldy.

**Comment by jamesbraza** [comment]
> ```python
>     def dict(
>         self, *args, **kwargs
>     ):
>         changed = set()
>         ...
>         return res
> ```

Note this is only for pydantic v1, this doesn't work for v2 with `model_dump`

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.

**Comment by ubipo** [comment]
This is also an issue in v2 (tested on v2.5.2):

``` python
from pydantic import BaseModel, __version__


class FrozenModel(BaseModel):
    class Config:
        frozen = True


class Child(FrozenModel):
    some_field: str


class Parent(FrozenModel):
    test: frozenset[Child]


child = Child(some_field="value")
parent = Parent(test=frozenset([child]))
print(__version__)
print(parent.model_dump())
```

```
2.5.2
Traceback (most recent call last):
  File "/Users/pieter/Documents/projects/VRT/datalake/import/windows-exporter/test.py", line 22, in <module>
    print(parent.model_dump())
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/pieter/Documents/projects/VRT/datalake/import/windows-exporter/.venv/lib/python3.12/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by mac01021** [comment]
Do core devs have a preferred strategy for closing this issue?  I need this capability for a project at work so I'm thinking about taking a stab at a PR.

**Comment by mac01021** [comment]
Actually it seems like this might be just about as solved as it is ever going to be in Pydantic v2.

@ubipo 's code above does indeed raise an exception.   But if you `parent.model_dump(mode="json")` then it correctly returns a list with a dict inside.  Likewise, `model_dump_json` works as expected.


For the default `mode="python"` case, the unit tests in `pydantic-core` assert specifically that a set must be dumped to a set.  As long as the specification for a python-mode dump of a set of basemodels is for it to return a set of dicts, the desired output value can never exist.

**Comment by sydney-runkle** [comment]
I agree with @mac01021's analysis above - going to close as not planned.

**Comment by sydney-runkle** [comment]
See https://github.com/pydantic/pydantic/pull/10324 for some recent work on this front.
