### ISSUE TITLE
Discriminated Union gives wrong type when all subclasses have defaults

### ISSUE THREAD

**Issue by lukehsiao** [pydantic/pydantic#4193]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /home/redacted/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jun  9 2022, 20:09:08) [GCC 10.3.0]
                     platform: Linux-5.13.0-44-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']

```

```py
from typing import Literal, Union

from pydantic import BaseModel, Field


class Cat(BaseModel):
    _name: Literal["cat"] = "cat"
    meows: int = 1


class Dog(BaseModel):
    _name: Literal["dog"] = "dog"
    barks: float = 0.1


class Lizard(BaseModel):
    _name: Literal["reptile", "lizard"]
    scales: bool = True


class Model(BaseModel):
    pet: Union[Cat, Dog, Lizard] = Field(..., discriminator="_name")
    n: int = 3

t = Model(pet=Dog(barks=3.14))

# This is a Cat instead
try:
    assert isinstance(t.pet, Dog)
except AssertionError:
    print(t.pet)
```

I would expect that this is correctly interpreted as a `Dog`. It seems that Pydantic is perhaps attempting to coerce the values, and since `Cat` is listed first in the `pet` Union, and has default values for all fields, it just becomes a `Cat` and the provided `Dog` is ignored.

Adding `smart_union=True` to the `Model` class also does not resolve the issue.

**Comment by syonekura** [comment]
Hi @lukehsiao , I'm having the same issue on pydantic `1.10.2`, wondering if you came across a workaround for this

**Comment by lukehsiao** [comment]
> I'm having the same issue on pydantic 1.10.2, wondering if you came across a workaround for this

I'm afraid not :(.

**Comment by syonekura** [comment]
nvm my previous comment. I didn't realize earlier my environment was calling an earlier (cached) pydantic version, sorry for the confusion. 

This works on `1.10.2`

```
from typing import Literal, Union

from pydantic import BaseModel, Field


class Cat(BaseModel):
    name: Literal["cat"] = "cat"
    meows: int = 1


class Dog(BaseModel):
    name: Literal["dog"] = "dog"
    barks: float = 0.1


class Lizard(BaseModel):
    name: Literal["reptile", "lizard"]
    scales: bool = True


class Model(BaseModel):
    pet: Union[Cat, Dog, Lizard] = Field(discriminator="name")
    n: int = 3


def test():
    t = Model(pet=Dog(barks=3.14))
    # This is a Cat instead
    assert isinstance(t.pet, Dog)

```

However this fails under a different error for `1.10.2` (note the discriminator is now `_name`)

```
from typing import Literal, Union

from pydantic import BaseModel, Field


class Cat(BaseModel):
    _name: Literal["cat"] = "cat"
    meows: int = 1


class Dog(BaseModel):
    _name: Literal["dog"] = "dog"
    barks: float = 0.1


class Lizard(BaseModel):
    _name: Literal["reptile", "lizard"]
    scales: bool = True


class Model(BaseModel):
    pet: Union[Cat, Dog, Lizard] = Field(discriminator="_name")
    n: int = 3


def test():
    t = Model(pet=Dog(barks=3.14))
    # This is a Cat instead
    assert isinstance(t.pet, Dog)

```

Error thrown is:

```
pydantic.errors.ConfigError: Model 'Cat' needs a discriminator field for key '_name'
```

Seems to be a different issue

**Comment by lukehsiao** [comment]
Ah, actually seems they more-or-less fixed this then! Good to know!
