### ISSUE TITLE
instance created with copy.copy alows changing the target of a reference in the original

### ISSUE THREAD

**Issue by tarbaig** [pydantic/pydantic#4206]
# Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Version
pydantic version: 1.9.1
pydantic compiled: True
 python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
 platform: Linux-5.11.0-49-generic-x86_64-with-glibc2.33
optional deps. installed: ['typing-extensions']
# Bug
Pythons behavior for shallow copies normaly is like this:
Shallow copied lists are the same reference, but setting a new reference on the copy does not modify the original.

```python
from dataclasses import dataclass
import copy 

@dataclass
class X:
    val : List[int]

x = X(val=[1])
y = copy.copy(x)

assert x.val == y.val

y.val = []

assert y.val != x.val
```

This is not true for pydantic

```python
class X(BaseModel):
     val: List[int]

x = X(val=[1])
y = copy.copy(x)

assert x.val == y.val # holds

y.val = []

assert y.val != x.val #error
```

This is unexpected and forces otherwise agnostic code to check if a passed object is a pydantic object. 

Also based on #1383 is would assume this is not desired.

**Comment by hang-onlyalt** [comment]
also copy.deepcopy seems having the same problem

**Comment by treharne** [comment]
I confirm that this bug exists in 1.10.2, and I also understood from #1383 that is is not desired.

```python
>>> import copy
>>> from pydantic import BaseModel, __version__
>>> __version__
'1.10.2'
>>> 
>>> class T(BaseModel):
...     name: str
... 
>>> t1 = T(name='jesse')
>>> t2 = copy.copy(t1)
>>> t2.name = 'james'
>>> t1.name
'james'
```

I'm moving some of our code from python classes to Pydantic classes. Unit tests which use copy all broke.

Workaround -> Use deepcopy for now
```python
>>> t3 = copy.deepcopy(t1)
>>> t3.name = 'jennifer'
>>> t1.nama
```

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.

**Comment by maartenbreddels** [comment]
Not elegant, but this works 'better' for v1 (without an expensive deepcopy):
```
type(model)(**{**model.dict(), **kwargs})
```

cc @mariobuikhuizen
