### ISSUE TITLE
Failure to produce JSON Schema for custom data type of NamedTuple with validator 

### ISSUE THREAD

**Issue by ssmssam** [pydantic/pydantic#4212]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
In the example shown in this [Link](https://pydantic-docs.helpmanual.io/usage/schema/#modifying-schema-in-custom-fields),  if _RestrictedAlphabetStr_ is changed to a NamedTuple the code will error with the following 
 AttributeError: type object 'RestrictedAlphabetStr' has no attribute '__pydantic_model__'

` class RestrictedAlphabetStr(NamedTuple):`

Should this be the case? This only happens when the custom data type has a __get_validators__ method 

Could it be here where namedTuples do not get the __pydantic_model__ attribute added to them  https://github.com/samuelcolvin/pydantic/blob/bf4b63e6c342c965a9aa0b914d19f196b0c1f5d6/pydantic/schema.py#L899  

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
  pydantic version: 1.9.1
            pydantic compiled: True


```

```py
 from typing import Optional

    from pydantic import BaseModel, Field
    from pydantic.fields import ModelField

    class RestrictedAlphabetStr(NamedTuple):
        @classmethod
        def __get_validators__(cls):
            yield cls.validate

        @classmethod
        def validate(cls, value, field: ModelField):
            alphabet = field.field_info.extra['alphabet']
            if any(c not in alphabet for c in value):
                raise ValueError(f'{value!r} is not restricted to {alphabet!r}')
            return cls(value)

        @classmethod
        def __modify_schema__(cls, field_schema, field: Optional[ModelField]):
            if field:
                alphabet = field.field_info.extra['alphabet']
                field_schema['examples'] = [c * 3 for c in alphabet]

    class MyModel(BaseModel):
        value: RestrictedAlphabetStr = Field(alphabet='ABC')

    print(MyModel.schema_json(indent=2))

...
```

**Comment by samuelcolvin** [comment]
This should be fixed in V2.

Sorry for the slow reply.

**Comment by hramezani** [comment]
@ssmssam Please test your example with `Pydantic V2` which is in alpha state and open a new issue if the problem still exists.
