### ISSUE TITLE
Custom validator does not include Enum fields in 'values' argument

### ISSUE THREAD

**Issue by radiophysicist** [pydantic/pydantic#4222]
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/shade/.virtualenvs/kafka_sap_pi_adapter/lib/python3.8/site-packages/pydantic
               python version: 3.8.13 (default, Mar 19 2022, 05:55:35)  [GCC 11.2.0]
                     platform: Linux-5.10.126-1-MANJARO-x86_64-with-glibc2.34
     optional deps. installed: ['dotenv', 'typing-extensions']
```
Hello!

I have a problem with custom validator and a model including Enum fields.
Given the following model which works like expected:
```
from pydantic import Field, validator
from pydantic.main import BaseModel


class E1ADHDR(BaseModel):
    message_type: str = Field(alias="MESTYP")
    message_type_lng: str = Field(alias="MESTYP_LNG")
    e1state: List[E1STATE] = Field(alias="E1STATE")

    @validator("e1state", each_item=True)
    def check_names_not_empty(cls, val, values, **kwargs):
        if values["message_type"] == "RELEVANT_OOS_DETECTED" and val.stapa4_lng is None:
            raise ValueError("stapa4_lng is required")
        return val
```
If I change the type of `message_type ` field from `str` to `Enum` like this:
```
class E1AdhrMessageType(Enum):
    """Possible values of E1STATE's status field."""

    trigger = "OOS_RELEVANT_DETECTED"
    invent = "WVINVE_UTP"
    writeoff = "WRITEOFF_UTP"
```
the `message_type` field disappears from `values` in validator resulting in KeyError exception

**Comment by PrettyWood** [comment]
You mean change from `str` to `E1AdhrMessageType`?

**Comment by radiophysicist** [comment]
Yes

**Comment by danielkatzan** [comment]
Is that the only change u did?
is it possible u also changed the fields order?

from the docs: [https://pydantic-docs.helpmanual.io/usage/validators/](https://pydantic-docs.helpmanual.io/usage/validators/)

> Validation is done in the order fields are defined. E.g. in the example above, password2 has access to password1 (and name), but password1 does not have access to password2. See [Field Ordering](https://pydantic-docs.helpmanual.io/usage/models/#field-ordering) for more information on how fields are ordered

**Comment by radiophysicist** [comment]
Sorry for late answer. 
This seems to be the only change I did. 
I've re-checked again and noticed that version with enum:
```
from enum import Enum
from typing import List, Optional

from pydantic import Field, validator
from pydantic.main import BaseModel

class E1AdhrMessageType(Enum):
    """Possible values of E1STATE's status field."""

    trigger = "OOS_RELEVANT_DETECTED"
    invent = "WVINVE_UTP"
    writeoff = "WRITEOFF_UTP"


class E1ADHDREnum(BaseModel):
    message_type: E1AdhrMessageType = Field(alias="MESTYP")
    e1state: List[int] = Field(alias="E1STATE")
    stapa4_lng: Optional[str]

    @validator("e1state", each_item=True)
    def check_names_not_empty(cls, val, values, **kwargs):
        print("validator_enum", val, values)
        if values["message_type"] == "RELEVANT_OOS_DETECTED" and val.stapa4_lng is None:
            raise ValueError("stapa4_lng is required")
        return val


m_enum = E1ADHDREnum.parse_obj({
    "MESTYP": "xxx",
    "E1STATE": [1, 2, 3],
})
```
crashes with the KeyError
```
validator_enum 1 {}
Traceback (most recent call last):
  File "./model_test.py", line 31, in <module>
    m_enum = E1ADHDREnum.parse_obj({
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 404, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1040, in pydantic.main.validate_model
  File "pydantic/fields.py", line 734, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 767, in pydantic.fields.ModelField._validate_sequence_like
  File "pydantic/fields.py", line 899, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 737, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 913, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 275, in pydantic.class_validators._generic_validator_cls.lambda2
  File "./model_test.py", line 26, in check_names_not_empty
    if values["message_type"] == "RELEVANT_OOS_DETECTED" and val.stapa4_lng is None:
KeyError: 'message_type'
```
only in case if invalid value for `message_type` is given.
If the field value matches the E1ADHDREnum values validation works as expected.
Is it accepted behavior not to check enum values first in this case?

**Comment by danielkatzan** [comment]
Yep, this is the expected behavior, and it is also documented [here](https://pydantic-docs.helpmanual.io/usage/validators/)

see the second bullet:

> where validators rely on other values, you should be aware that:
> 
> Validation is done in the order fields are defined. E.g. in the example above, password2 has access to password1 (and name), but password1 does not have access to password2. See [Field Ordering](https://pydantic-docs.helpmanual.io/usage/models/#field-ordering) for more information on how fields are ordered
> If validation fails on another field (or that field is missing) it will not be included in values, hence if 'password1' in values and ... in this example.
