### ISSUE TITLE
Alias generator with Pydantic dataclass not behaving as expected

### ISSUE THREAD

**Issue by CuriousHexagon** [pydantic/pydantic#4286]
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
Using Pydantic 1.9.0 and python 3.9.10

Using `alias_generator` in the `Config` for a `pydantic.dataclasses.dataclass`  throws `unexpected keyword` when using the alias, but also Pydantic is aware of the alias since `field required (type=value_error.missing)` is also thrown when the alias name is not used.

The same example works without issue with a `BaseModel` class. The documentation provides an example of using `Config` with a `pydantic.dataclasses.dataclass` but does not mention of any `Config` limitations when using such a dataclass.

```py

from pydantic.dataclasses import dataclass


def to_lower_camel(name: str) -> str:
    """
    Converts a snake_case string to lowerCamelCase
    """
    upper = "".join(word.capitalize() for word in name.split("_"))
    return upper[:1].lower() + upper[1:]


class MyConfig:
    alias_generator = to_lower_camel


@dataclass(config=MyConfig)
class User:
    name: str
    highest_score: int

    class Config:
        alias_generator = to_lower_camel
```
Exception thrown when trying to use the alias:
```py
user_a = User(name='abc', highestScore=100)

# OUTPUT 
# Traceback (most recent call last):
#     user = User(name='abc', highestScore=100)
# TypeError: __init__() got an unexpected keyword argument 'highestScore'
```
Exception thrown when not using the alias (expected - but demonstrates that neither naming convention now works):
```py
user_b = User(name='abc', highest_score=100)

# OUTPUT
# pydantic.error_wrappers.ValidationError: 1 validation error for User
# highestScore
#   field required (type=value_error.missing)
```

**Comment by samuelcolvin** [comment]
Yes, we use the standard dataclass initialisation to resolve args and kwargs, then do validation, thus aliases can't be used because dataclasses don't know how to handle them.

This is will be fixed in pydantic V2, in fact I'm working on the functionality right now https://github.com/samuelcolvin/pydantic-core/pull/190.

We could definitely update the docs to mention which bits of config work, and which don't. Similar things have been reported before e.g. #986.

**Comment by devraj** [comment]
Hey all,

I am seeing this to be the case in pydantic `2.1.1` installed with `fastapi` version `0.101.0`, wondering if this was resolved when using pydantic with fastapi.

Thank you.

**Comment by hramezani** [comment]
@devraj it is working as expected. here is the above example in V2:

```py
from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


def to_lower_camel(name: str) -> str:
    """
    Converts a snake_case string to lowerCamelCase
    """
    upper = "".join(word.capitalize() for word in name.split("_"))
    return upper[:1].lower() + upper[1:]


@dataclass(config=ConfigDict(alias_generator=to_lower_camel))
class User:
    name: str
    highest_score: int

print(User(name='abc', highestScore=100))  # User(name='abc', highest_score=100)
```

**Comment by devraj** [comment]
@hramezani thank you for responding to me, I think I found where I am coming unstuck. I am using `pydantic` to serialise SQLALchemy models. My `model_config` looks like so:

```
    model_config = ConfigDict(
        from_attributes=True,
        alias_generator=to_lower_camel,
    )
```

if the `alias_generator` is set (I am using the same function as you posted in your response) then seems to query the SQLAlchemy object for the camelized key and throws this error:

```
harvest-api            |   {'type': 'missing', 'loc': ('response', 3, 'lastName'), 'msg': 'Field required', 'input': <harvest.models.user.User object at 0xffff9b81dc10>, 'url': 'https://errors.pydantic.dev/2.0.3/v/missing'}
```

Clearly I am missing something about using `alias_generator` and `from_attributes`. I'll go ready the docs further, but if you do have any insights please do share 🙏

**Comment by devraj** [comment]
To answer my own question setting `populate_by_name` in the configuration to `true` and not setting `from_attributes` makes it all work as expect:

```
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=to_lower_camel,
    )
```
