### ISSUE TITLE
Mypy 0.950+ breaks valid usage of Pydantic generic models

### ISSUE THREAD

**Issue by EldarSehayekZenity** [pydantic/pydantic#4327]
# Bug

I use Pydantic latest version 1.9.1 and Mypy 0.940. I tried to upgrade to Mypy 0.950 and received new type compatibility issues because the type arguments for Pydantic generic models wasn't resolved properly when inheritance was involved, the code sample below will show mypy error: Argument "data" to "GenericDerivedClass" has incompatible type "List[str]"; expected "List[_TResult]"
I'll mention that I work with VSCode, and Pylance doesn't have the same issue, it recognizes the generics usage as valid.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`: 
```
pydantic version: 1.9.1
pydantic compiled: True
install path: <my project's virtual env pydantic lib path, omitted for privacy reasons>
python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.22000-SP0
optional deps. installed: ['typing-extensions']
```

```py
from typing import Generic, TypeVar
from pydantic.generics import GenericModel

_TResult = TypeVar("_TResult")

class GenericSuperClass(GenericModel, Generic[_TResult]):
    data: list[_TResult]
    total: int

class GenericDerivedClass(GenericSuperClass[_TResult], GenericModel, Generic[_TResult]):
    extra: int

def use_generic_super_class() -> None:
    strings: list[str] = ["foo", "bar"]

    derived_class: GenericDerivedClass[str] = GenericDerivedClass(data=strings, total=2, extra=5)
    print(derived_class)
```

# Troubleshooting

Didn't solve: I tried making `GenericDerivedClass` not inherit from `GenericModel`
Did solve: I tried making `GenericDerivedClass` have a field of type `GenericSuperClass[_TResult]` instead of inherit from it,
So I can say this is an inheritence issue with generic models.

**Comment by samuelcolvin** [comment]
If it started breaking between mypy versions, I would suggest reporting it to mypy and see what they say.

It seems more likely to be a bug with mypy.

On the pydantic side, we're going to change how Generics work in V2 but I doubt we can make any changes to generics before v1.10.

**Comment by Kludex** [comment]
As per the mypy issue, this was solved at some point: https://github.com/python/mypy/issues/13421#issuecomment-1676426794.
