### ISSUE TITLE
Constrained date types

### ISSUE THREAD

**Issue by the-matt-morris** [pydantic/pydantic#4330]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

This library is amazing, I use it all the time.  Thanks for all the great work!

I'm guessing there may be reasoning behind why it exists as it does today, but I wanted to create a proposal for constrained dates.  Currently, `PastDate` and `FutureDate` subclass `datetime.date` and are super useful.  However, there are some cases where you want to specify specific bounds on the date and it would be useful to use that with constraints rather than having to create a custom type that performs the validation in `__get_validators__`.

## Currently

```python
from typing import TYPE_CHECKING
from datetime import date

from pydantic.datetime_parse import parse_date


if TYPE_CHECKING:
    NinetiesDate = date
else:

    class NinetiesDate(date):
        @classmethod
        def __get_validators__(cls) -> 'CallableGenerator':
            yield parse_date
            yield cls.validate

        @classmethod
        def validate(cls, value: date) -> date:
            if not (1990 <= value.year <= 1999):
                raise ValueError("Date not in the 1990s!")

            return value
```

## Proposal

`pydantic.errors`

```python
from pydantic import errors

class _DateBoundError(errors.PydanticValueError):
    def __init__(self, *, limit_value: date) -> None:
        super().__init__(limit_value=limit_value)


class DateNotGtError(_DateBoundError):
    code = 'date.not_gt'
    msg_template = 'ensure this value is greater than {limit_value}'


class DateNotGeError(_DateBoundError):
    code = 'date.not_ge'
    msg_template = 'ensure this value is greater than or equal to {limit_value}'


class DateNotLtError(_DateBoundError):
    code = 'date.not_lt'
    msg_template = 'ensure this value is less than {limit_value}'


class DateNotLeError(_DateBoundError):
    code = 'date.not_le'
    msg_template = 'ensure this value is less than or equal to {limit_value}'
```

`pydantic.validators`

```python
from datetime import date

def date_range_validator(v: date, field: 'ModelField') -> date:
    field_type: ConstrainedDate = field.type_
    if field_type.gt is not None and not v > field_type.gt:
        raise errors.DateNotGtError(limit_value=field_type.gt)
    elif field_type.ge is not None and not v >= field_type.ge:
        raise errors.DateNotGtError(limit_value=field_type.ge)

    if field_type.lt is not None and not v < field_type.lt:
        raise errors.DateNotGtError(limit_value=field_type.lt)
    if field_type.le is not None and not v <= field_type.le:
        raise errors.DateNotGtError(limit_value=field_type.le)

    return v
```

`pydantic.types`

```python
from datetime import date
from typing import Any, Dict, Optional, cast

from pydantic.datetime_parse import parse_date
from pydantic.types import  _registered
from pydantic.utils import update_not_none


class ConstrainedDateMeta(type):
    def __new__(cls, name: str, bases: Any, dct: Dict[str, Any]) -> 'ConstrainedDate':  # type: ignore
        new_cls = cast('ConstrainedDate', type.__new__(cls, name, bases, dct))

        if new_cls.gt is not None and new_cls.ge is not None:
            raise errors.ConfigError('bounds gt and ge cannot be specified at the same time')
        if new_cls.lt is not None and new_cls.le is not None:
            raise errors.ConfigError('bounds lt and le cannot be specified at the same time')

        return _registered(new_cls)  # type: ignore


OptionalDate = Optional[date]


class ConstrainedDate(date, metaclass=ConstrainedDateMeta):
    strict: bool = False
    gt: OptionalDate = None
    ge: OptionalDate = None
    lt: OptionalDate = None
    le: OptionalDate = None

    @classmethod
    def __modify_schema__(cls, field_schema: Dict[str, Any]) -> None:
        update_not_none(
            field_schema,
            exclusiveMinimum=cls.gt,
            exclusiveMaximum=cls.lt,
            minimum=cls.ge,
            maximum=cls.le,
        )

    @classmethod
    def __get_validators__(cls) -> 'CallableGenerator':
        yield parse_date


if TYPE_CHECKING:
    PastDate = date
    FutureDate = date
    NonPastDate = date
    NonFutureDate = date
else:
    class PastDate(ConstrainedDate):
        lt = date.today()

    class FutureDate(ConstrainedDate):
        gt = date.today()

    class NonPastDate(ConstrainedDate):
        le = date.today()

    class NonFutureDate(ConstrainedDate):
        ge = date.today()
```

In use:

```python
from datetime import date

from pydantic import ConstrainedDate, validate_arguments


class NinetiesDate(ConstrainedDate):
    ge = date(1990, 1, 1)
    lt = date(2000, 1, 1)


@validate_arguments
def my_func(foo: NinetiesDate):
    return foo


my_func(date(1995, 1, 1))
my_func(date(2000, 1, 1))
```

Output:

```
datetime.date(1995, 1, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic/decorator.py", line 133, in pydantic.decorator.ValidatedFunction.call
    func.__dict__.update(kw)
  File "pydantic/decorator.py", line 130, in pydantic.decorator.ValidatedFunction.init_model_instance
    else:
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MyFunc
foo
  ensure this value is greater than 2000-01-01 (type=value_error.date.not_gt; limit_value=2000-01-01)
```

There would have to be additional work to make this work with `Field`, but that could be done if this proposal, or something along these lines, were accepted.  Thanks.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for the detailed request.

Much of this is implemented in #3739.

Also, the constraints are already implemented in pydantic-core, ready for V2, eg. see [here](https://github.com/pydantic/pydantic-core/blob/0e2446d70ff68bf05c809b209bee923d6795012d/tests/validators/test_date.py#L148-L177).

The only open question is how we support `today()` (and now for `FutureDatetime`) - you see the constraint validation in V2 is don't purely in rust using [speedate](https://github.com/pydantic/speedate), so we either to allow speedate to access know about `now` and `today`, which shouldn't be too hard.

**Comment by the-matt-morris** [comment]
Thanks for the response.  My bad for not finding PR #3740 , which as you said, did implement the majority of this (the constraints at least).

**Comment by rt87** [comment]
Nice, I will check it out once released!

Unless I missed it, this is only for dates, not datetimes, correct?

I would love to see this being extended to datetimes, including:

- constraining timezones
- coercion to a specific zone , i.e. "astimezone(...)" (before/after any gt/lt checks)
- adding timedeltas and/or setting concrete values for specific attributes, i.e. "replace(minute=0, ...)". rounding might be nice, too, but might also be a bit much

If this is still missing and if I'm not the only one interested in this feature, I would be happy to put this in a FR of its own and maybe even prodive some sort of rudimentary implementation.

**Comment by samuelcolvin** [comment]
Should work for dates, times, datetimes and durations.

Can't do timezone constraints yet, probably best to manage this in python.

**Comment by samuelcolvin** [comment]
Formats or constraining particular components can be don't in python via validators.

**Comment by rt87** [comment]
ok, thx.

is it planned to add constrained zones and formats in the near future?

**Comment by samuelcolvin** [comment]
No, because:
1. You can do both with validators easily
2. I don't see any point in constraining formats - the formats speedate allows are already unambiguous, why make submitting data harder
3. Constraining timezone has different options - mainly, whether to constrain based on timezone or timezone offset

**Comment by rt87** [comment]
True, but using a lot of validators, even simple ones, May bloat your model quite a bit.

I was thinking actual zones, i.e. names, but Sure, offsets might be good, too.

**Comment by samuelcolvin** [comment]
And adding endless options will bloat pydantic and make it harder to maintain, so we can't add everything to pydantic.

V2 will allow custom types to be much simpler. With that, you'd only need to define your logic once.

**Comment by rt87** [comment]
yes, but not MY code.... ;)

that sounds very nice!

**Comment by samuelcolvin** [comment]
😂

This is not a democracy.

**Comment by v3ss0n** [comment]
> And adding endless options will bloat pydantic and make it harder to maintain, so we can't add everything to pydantic.

i agree , i think validtors outside of core should be in its own package with with seperate repo which is easy for user to add more validators , without bloating the core.

**Comment by adriangb** [comment]
This is much better supported in v2. You can now do something like:


```python
from dataclasses import dataclass
from datetime import date
from typing import Annotated, Any

from pydantic_core import core_schema as cs

from pydantic import BaseModel
from pydantic.annotated import GetCoreSchemaHandler


@dataclass
class DateGt:
    date: date

    def __get_pydantic_core_schema__(
        self, source_type: Any, handler: GetCoreSchemaHandler
    )  -> cs.CoreSchema:
        schema = handler(source_type)
        def val(v: date) -> date:
            if not v > self.date:
                raise ValueError(f'Date should be greater than {self.date}')
            return v

        return cs.no_info_after_validator_function(
            val, schema, serialization=schema.get('serialization')
        )


class Model(BaseModel):
    dob: Annotated[date, DateGt(date(year=1900, month=1, day=1))]


Model(dob=date(year=1942, month=4, day=20))
Model(dob=date(year=1842, month=4, day=20))
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
dob
  Value error, Date should be greater than 1900-01-01 [type=value_error, input_value=datetime.date(1842, 4, 20), input_type=date]
"""
```

In the future we may even be able to support `dob: Annotated[date, Field(gt=date(year=1900, month=1, day=1))]`
