### ISSUE TITLE
Nested Annotated List don't enforce requirements correctly.

### ISSUE THREAD

**Issue by eseglem** [pydantic/pydantic#4333]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using an `Annotated[List[...], Field(...)]` inside another one, only the outermost `Field` restrictions apply. 

### Example Code

```Python
from typing import List
from typing_extensions import Annotated
from pydantic import BaseModel, Field

B = Annotated[List[int], Field(min_items=2, max_items=2)]
C = Annotated[List[B], Field(min_items=1)]
D = Annotated[List[B], Field(max_items=3)]
E = Annotated[List[B], Field(min_items=3)]

class BB(BaseModel):
    b: B

class CC(BaseModel):
    c: C

class DD(BaseModel):
    d: D

class EE(BaseModel):
    e: E

BB(b=[0])  # Correctly fails, not enough items
BB(b=[0,1])  # No validation error, as expected
BB(b=[0,1,2]) # Correctly fails, too many items

CC(c=[[0]])  # Does not fail, but inner is too short
CC(c=[[0,1,2]])  # Does not fail, but inner is too long
CC(c=[[0,1],[0,1],[0,1]])  # No validation error, as expected

DD(d=[[0,1,2]])  # Does not fail, but inner is too long
DD(d=[[0,1,2,4]])  # Fails but for wrong reason, does not like that inner has more than 3

EE(e=[[0,1],[0,1],[0,1]])  # Fails but shouldn't, thinks inner are too short
EE(e=[[0,1,2],[0,1,2],[0,1,2]])  # Does not fail, but inner are too long
```

For `CC.__annotations__` it correctly sees both there still: 
```
typing_extensions.Annotated[
    typing.List[
        typing_extensions.Annotated[
            typing.List[int], 
            FieldInfo(default=PydanticUndefined, min_items=2, max_items=2, extra={})
        ]
    ], 
    FieldInfo(default=PydanticUndefined, min_items=1, extra={})
]
```
But the outer `FieldInfo` is applied to both lists.

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/erik/geojson-pydantic/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
                     platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by danielkatzan** [comment]
Taking a look at the issue, it looks like it's the result of trying to annotate the constraints `here`
a `conlist` is created for both the inner and outer `Annotated`, both with the constraints of the outer `field_info`

**Comment by eseglem** [comment]
@danielkatzan your `here` is code but I think you meant it to be a link. I can try my hand at a PR if you point me in the right direction.

**Comment by danielkatzan** [comment]
@eseglem updated my comment with the link, not exactly sure how this should be treated
constrains seems to be computed recursively, for each sub types, but the constraints used are from the top level annotation

**Comment by samuelcolvin** [comment]
Confirmed, here's the simplest demo of the bug:

```py
from typing import List
from typing_extensions import Annotated
from pydantic import BaseModel, Field

B = Annotated[List[int], Field(max_items=2)]


class CC(BaseModel):
    c: List[B]


CC(c=[[0, 1, 3]])
```

My instinct at this point (a few days from releasing the pre-release of v1.10) is that this will have to wait for V2.

But if someone can find a fix which doesn't break other things, is easy to reason about and has a small footprint; I'd be happy to review.

**Comment by danielkatzan** [comment]
Hi @samuelcolvin 
being trying to work on a solution, my idea is to modify the recursive [go](https://github.com/pydantic/pydantic/blob/master/pydantic/schema.py#L1029) function, to accept a second `field_info_` param, which will be passed around as is in all the recursive calls

except for the case where `origin is Annotated` [here](https://github.com/pydantic/pydantic/blob/master/pydantic/schema.py#L1044)
In that case we need to calculate the origin FieldValue similarly to how it's done [here](https://github.com/pydantic/pydantic/blob/master/pydantic/fields.py#L453), and pass that to the `go` call

This approach seems to fix the issue, but only works in case top level field as at least on constraint on it due to this [`if`](https://github.com/pydantic/pydantic/blob/master/pydantic/schema.py#L1003)

trying to look for a workaround for that, if u have any ideas \ comments on my approach?

further more, while working on it, I tried to remove that `if`, and of course encountered some failing tests, which led me to potentially other issues

e.g. 
the following fails
```
    class Model(BaseModel):
        tuple: Tuple[int] = Field(max_items=2)
       
   class Model(BaseModel):
        tuple: Tuple[int, ...] = Field(max_items=2)
```
seems to be because there is no field constraints for tuples, is there a specific reason for that? or was it simply not implemented yet?
this also fails
```
    class Model(BaseModel):
        tuple: Tuple[] = Field(max_items=1)
```
since trying to this [line](https://github.com/pydantic/pydantic/blob/master/pydantic/schema.py#L1071) which evaluates to `typing.Tuple[((),)] `

**Comment by danielkatzan** [comment]
I think something in the sense of this will work

```
    constraints = field_info.get_constraints()
    used_constraints: Set[str] = set()
    if constraints or _has_nested_constraints(annotation):
        annotation, used_constraints = get_annotation_with_constraints(annotation, field_info)
        
    ...
    
def _has_nested_constraints(annotation: Any) -> bool:
    if (
        is_literal_type(annotation)
        or isinstance(annotation, ForwardRef)
        or lenient_issubclass(annotation, (ConstrainedList, ConstrainedSet, ConstrainedFrozenSet))
    ):
        return False
    origin = get_origin(annotation)
    if origin is Annotated:
        field_infos = [arg for arg in get_args(annotation)[1:] if isinstance(arg, FieldInfo)]
        field_info = next(iter(field_infos), None)
        if field_info is None:
            return False
        return bool(field_info.get_constraints())
    args = get_args(annotation)
    return any(_has_nested_constraints(_annotation) for _annotation in args)
```

**Comment by Kludex** [comment]
This is already solved on V2.

For v1, same message as stated previously applies:
> ... if someone can find a fix which doesn't break other things, is easy to reason about and has a small footprint; I'd be happy to review.
