### ISSUE TITLE
Schema generation for discriminated unions using literal Enum values is incompatible with OpenAPI

### ISSUE THREAD

**Issue by princematheww** [pydantic/pydantic#4337]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I noticed that using `BaseModel.schema()` for schema generation doesn't generate the right schema for discriminated unions using Enums(and possibly other non-string types). In fields used as discriminators, which are of type `Literal[term]`, `term` can be of any primitive type, or an Enum. According to the [OpenAPI spec for discriminators](https://swagger.io/specification/#discriminator-object), the field 'discriminator.mapping' needs to be of type `Map[string, string]`. Although, when Pydantic generates the value for 'mapping', it uses the actual value of the discriminator(in my case it was an Enum). In all cases, Pydantic should resolve the discriminator value to a string.

I noticed this issue while using FastAPI with a `return_model` that contained a nested discriminated union that has a field of type `Literal[PetType.CAT]` where `PetType` is an Enum. I saw the following error originating from [`fastapi.openapi.models.OpenAPI`](https://github.com/tiangolo/fastapi/blob/master/fastapi/openapi/models.py#L389):

```
[20220804 00:46:29:093 httptools_impl.py:404 ERROR] pydantic.error_wrappers.ValidationError: 1 validation error for OpenAPI
[20220804 00:46:29:093 httptools_impl.py:404 ERROR] components -> schemas -> Model -> properties -> pet_type -> discriminator -> mapping -> __key__
[20220804 00:46:29:093 httptools_impl.py:404 ERROR]   str type expected (type=type_error.str)
```

Looking in the Pydantic code, I think the bug is in this part:
https://github.com/samuelcolvin/pydantic/blob/576e4a3a8d9c98cbf5a1fe5149450febef887cc9/pydantic/schema.py#L718-L735

Here, the `discriminator_value` should probably be checked for an Enum, and it's `.value` be retrieved and used. There might be similar resolution logic required for primitives other than `str`.

### Example Code

```Python
from enum import Enum
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field

class PetType(Enum):
    CAT = "cat"
    DOG = "dog"
    REPTILE = "reptile"
    LIZARD = "lizard"

class Cat(BaseModel):
    pet_type: Literal[PetType.CAT]
    meows: int

class Dog(BaseModel):
    pet_type: Literal[PetType.DOG]
    barks: float

Pet = Annotated[Union[Cat, Dog], Field(discriminator="pet_type")]

class Model(BaseModel):
    pet: Pet
    n: int

print(Model.schema()['properties']['pet']['discriminator'])
"""
The output for the above will be:
>>> {'propertyName': 'pet_type', 'mapping': {<PetType.CAT: 'cat'>: '#/definitions/Cat', <PetType.DOG: 'dog'>: '#/definitions/Dog'}}

When it really should be:
>>> {'propertyName': 'pet_type', 'mapping': {'cat': '#/definitions/Cat', 'dog': '#/definitions/Dog'}}
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /usr/local/python/python-3.9/std/lib/python3.9/site-packages/pydantic
               python version: 3.9.7
                     platform: Linux
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @princematheww for reporting the issue.

I can confirm that it happens on the master.

It can be fixed by using the enum value in like `pet_type: Literal[PetType.CAT.value]` but mypy complain about it.

we can fix the problem in Pydantic schema as @princematheww mentioned.

Let's wait for @samuelcolvin to confirm the fix.

**Comment by samuelcolvin** [comment]
Yes sounds like we should fix it.

**Comment by samuelcolvin** [comment]
(@hramezani ideally we should remove the 'unconfirmed' label when we l we're reproduced the bug, should make it easier to filter issues that need triage.

**Comment by abrahamko** [comment]
I'm facing the exact same error.
There's no update on this issue for the last 5 months.
Is there any progress here?

**Comment by samuelcolvin** [comment]
Will be fixed in V2, ref #4666.

Pr welcome to fix in v1.10.

**Comment by dmontagu** [comment]
For what it's worth, before 3.11, I think it should work almost equivalently to what `StrEnum` does in 3.11 if you just inherit from `str` before `Enum`:

```
class PetType(str, Enum):
    ...
```

**Comment by dmontagu** [comment]
@michaeligreenberg this does look like a bug to me, but is not related to this issue (which was specific to problems caused by using literal enums; changing all the `Literal[Color.White]` etc. to strings results in the same schema in v1 as far as I can tell).

Feel free to create a new issue for this, but I will note that this has already been fixed in v2. I would be happy to review a PR fixing this in v1 but may not have the time to dedicate to fixing it in v1 myself.

**Comment by michaeligreenberg** [comment]
@dmontagu Thanks for your fast response! I confirmed that this is unrelated to literal enums and the issue exists for discriminated unions on string properties.

**Comment by dmontagu** [comment]
The original reported issue is fixed in 1.10.7 and v2, so I will close this; please create a new issue for any other bugs discussed in this thread if they are still causing problems.

**Comment by yarinsa** [comment]
Can anyone here confirm that v2 solved the issue for that exact case?

**Comment by javibookline** [comment]
> Can anyone here confirm that v2 solved the issue for that exact case?

@yarinsa a test was added to cover this case in v2 [#https://github.com/pydantic/pydantic/commit/14e9b2f6a3694aa62584e94f2a42d01c6c653157](https://github.com/pydantic/pydantic/blob/2155e4d8759e80d8a21339e61c9939c6b042c11b/tests/test_json_schema.py#L3915)

So if all tests are passing then yes, this exact case is covered in v2.

**Comment by mvanderlee** [comment]
In case others land here: This bug and test is for the schema generation only! Not the actual model validation which doesn't work. (2.12.5)

_Edit: It works fine if you use (str, Enum) or StrEnum_
