### ISSUE TITLE
Support `re.Pattern` and  bare `type` as types 

### ISSUE THREAD

**Issue by Bobronium** [pydantic/pydantic#4360]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Ref: https://github.com/pydantic/pydantic/issues/4334#issuecomment-1207212891

```py
import re
import typing
from pydantic import BaseModel

class Model(BaseModel):
    typing_pattern: typing.Pattern  # this is supported
    re_pattern: re.Pattern  # RuntimeError: no validator found for <class 're.Pattern'>, see `arbitrary_types_allowed` in Config
```

```py
from typing import Type
from pydantic import BaseModel

class Model(BaseModel):
    cls: Type  # treated as Type[Any]
    cls: type  # RuntimeError: no validator found for <class 'type'>, see `arbitrary_types_allowed` in Config
```

It's pretty easy to fix, but my hands are full now. Would appreciate somebody picking this up.

##### Would require adding `or self.type_ is re.Pattern` here:
https://github.com/pydantic/pydantic/blob/11d8589423ac82f64eb4007bdad824f4a6217434/pydantic/fields.py#L599
##### adding `or type_ is re.Pattern` here:
https://github.com/pydantic/pydantic/blob/11d8589423ac82f64eb4007bdad824f4a6217434/pydantic/validators.py#L687
##### and replacing part after `or` with `field_type is type_ and (type_ is Pattern or type_ is re.Pattern)`
https://github.com/pydantic/pydantic/blob/11d8589423ac82f64eb4007bdad824f4a6217434/pydantic/schema.py#L805

##### As for bare `type`, you'd need to add `if type_ is type: return True` before this line:
https://github.com/pydantic/pydantic/blob/11d8589423ac82f64eb4007bdad824f4a6217434/pydantic/typing.py#L572

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I've created a PR to add `re.Pattern` https://github.com/pydantic/pydantic/pull/4366
I will create another one for `type` soon
