### ISSUE TITLE
Empty Env var breaks parse HttpUrl optional fields

### ISSUE THREAD

**Issue by tonal** [pydantic/pydantic#4368]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

```
$ DSN= python env_t.py
Traceback (most recent call last):
  File "/home/user/projects/basket_rules/basket_server/env_t.py", line 10, in <module>
    t = Test()
  File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Test
dsn
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)
```

### Example Code

```Python
from pydantic import BaseSettings, HttpUrl


class Test(BaseSettings):
  dsn:HttpUrl|None


t = Test()
print(t)
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /home/user/.pyenv/versions/3.10.6/envs/basket_server/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug  3 2022, 10:03:21) [GCC 9.4.0]
                     platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I'm not sure I agree that this is a bug, you've provided `''` as the input to a URL fields, `''` is not a valid URL.

**Comment by samuelcolvin** [comment]
Let me know if I'm missing something or there's another way view this? Otherwise you can probably fix it with a validator.

**Comment by tonal** [comment]
@samuelcolvin Common way to drop environment value - set empty before call.
For example start tests:
```bash
MYSQL_PASWD= python -m pytest
```

**Comment by samuelcolvin** [comment]
The canonical way to drop env variables is with `unset`.

But if you want the behaviour of ignoring empty en vars, you can implement it via a validator.
