### ISSUE TITLE
[Docs] Reflect the latest changes regarding `copy_on_model_validation`

### ISSUE THREAD

**Issue by gdalmau** [pydantic/pydantic#4369]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

The latest release [v1.9.2](https://github.com/pydantic/pydantic/releases/tag/v1.9.2) introduced changes in the configuration option `copy_on_model_validation` which are not reflected in the documentation.

Currently the documentation in https://pydantic-docs.helpmanual.io/usage/model_config/ shows:

> `copy_on_model_validation`: whether inherited models used as fields should be reconstructed (copied) on validation instead of being kept untouched (default: True)

### Affected Components

- [x] [Documentation](https://pydantic-docs.helpmanual.io/)
- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Very good point, thank you for reporting.

Would you be willing to create a PR for this? If so you'll need to set the base to `1.9.X-fixes`
