### ISSUE TITLE
Error with `BaseSettings` from a `.env` when trying to load a dictionary in a nested sub-model.

### ISSUE THREAD

**Issue by lopezco** [pydantic/pydantic#4389]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I tried to load a dictionary from a `.env` in a nested sub-model.

Here is my `.env` file:

```
# tests/config/my.env
direct_dict={"v1": "V1", "v2": "V2"}
from_base_model__v1=V1
from_base_model__v2=V2

submodel__direct_dict={"v1": "V1", "v2": "V2"}
submodel__from_base_model__v1=V1
submodel__from_base_model__v2=V2
```

I wrote the code to test reading the dict as a part of the base settings and as a part of the sub-model.
I get the following error:

```
ValidationError: 1 validation error for Settings
submodel -> direct_dict
  value is not a valid dict (type=type_error.dict)
```

If I remove `direct_dict` from the `SubModel` class it works

### Example Code

```Python
import pydantic
from typing import Optional, Dict, Any

class Data(pydantic.BaseModel):
    v1: str
    v2: str

class Submodel(pydantic.BaseModel):
    direct_dict: Dict[str, Any]
    from_base_model: Data

class Settings(pydantic.BaseSettings):
    direct_dict: Dict[str, Any]
    from_base_model: Data
    submodel: Submodel

    class Config:
        case_sensitive = True
        env_file='./tests/config/my.env'
        env_nested_delimiter='__'

s = Settings()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: C:\Users\jlopezcolina\Envs\applications_utils\Lib\site-packages\pydantic
               python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)]  
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lopezco** [comment]
Thanks @hramezani 
Do you have an estimated release date for V2?

**Comment by hramezani** [comment]
Not sure. We are preparing V1.10 which is the latest one on V1.x. but the fix for this issue won't be included

**Comment by samuelcolvin** [comment]
> Thanks @hramezani Do you have an estimated release date for V2?

https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#plan-timeframe

**Comment by grudelsud** [comment]
hi folks,

just wanted to add to this bug that I am running into the same problem when using sets in nested models

here's an example:

```python
from typing import Set
from pydantic import BaseSettings, BaseModel


class TestModel(BaseModel):
    GIT_URL: str
    ENVIRONMENT_GIT_BRANCHES: Set[str]


class TestSettings(BaseSettings):
    NON_NESTED_TEST: Set[str]
    APP_BANKING: TestModel = {}
```

with my .env file set as

```
export NON_NESTED_TEST='["develop", "staging", "production"]'

export APP_BANKING__GIT_URL=""
export APP_BANKING__ENVIRONMENT_GIT_BRANCHES='["develop", "staging", "production"]'
```

the `NON_NESTED_TEST` variable works fine, while the nested variable raises:

```
pydantic.error_wrappers.ValidationError: 1 validation error for TestSettings
APP_BANKING -> ENVIRONMENT_GIT_BRANCHES
  value is not a valid set (type=type_error.set)
```

and below here my environment:

```
pydantic VERSION = '1.10.2'
Python 3.8.13
platform macOS-12.5.1-x86_64-i386-64bit
```

if someone can suggest a temporary workaround until version 2 is released, I'd be grateful 😄 

thanks, and merry Christmas! 🎄

**Comment by Pacheco95** [comment]
@grudelsud I'm facing the same problem! When the `set` attribute comes from a root class, it works. When it comes from a submodel it fails. There is a workaround using pre validators:

> Tested with v1.10.2 and 1.10.3

```py
import os

from pydantic import BaseModel, Field, BaseSettings, validator


class DedicatedQueue(BaseModel):
    name: str
    enabled: bool

    class Config:
        frozen = True


INSTANTIATE_ROOT_CLASS = False

FORCE_CUSTOM_PARSING = False

"""
If `INSTANTIATE_ROOT_CLASS == True` and `FORCE_CUSTOM_PARSING == False` it fails
If `INSTANTIATE_ROOT_CLASS == False` it works
If `FORCE_CUSTOM_PARSING == True` everything works regardless of `INSTANTIATE_ROOT_CLASS`
"""


class CelerySettings(BaseSettings):
    dedicated_queues: set[DedicatedQueue] = Field(default_factory=set)

    if FORCE_CUSTOM_PARSING:

        @validator("dedicated_queues", pre=True)
        def _validate_dedicated_queues(cls, values):
            if not isinstance(values, str):
                return values

            try:
                import json
                return json.loads(values)
            except Exception:
                raise


class ApplicationSettings(BaseSettings):
    celery: CelerySettings

    class Config:
        env_nested_delimiter = "__"


if INSTANTIATE_ROOT_CLASS:
    os.environ["CELERY__DEDICATED_QUEUES"] = '[{"name": "integrator:ev:ITEM", "enabled": true}]'
    settings = ApplicationSettings()
else:
    os.environ["DEDICATED_QUEUES"] = '[{"name": "integrator:ev:ITEM", "enabled": true}]'
    settings = CelerySettings()

print(settings)

```

**Comment by hramezani** [comment]
it got fixed in the new `pydantic-settings`.
As you may know, `pydantic-settings` is a new package and is in the alpha state. You can install it by `pip install pydantic-settings --pre` and test it.
