### ISSUE TITLE
Schema ignores enumerator on dictionary keys

### ISSUE THREAD

**Issue by lachlancoding** [pydantic/pydantic#4393]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When a model has a dictionary field whose keys are of an Enumerated type, pydantic enforces validation of the dictionary keys at construction time, but the schema generated makes no mention of the key requirements. 

A dictionary using a constr with a regex pattern for its keys will include its pattern in the 'patternProperties', but an enumerated type will just include the value type in the additionalProperties. Also, if the field is just a regular Enum, the valid values are included in the 'anyOf' field. 

However in this specfic situation of an enum keyed dict, nothing is included in the schema, so someone trying to generate a valid example of the model would have no indication that there is even a requirement until it fails at construction time validation.

### Example Code

```Python
from pydantic import BaseModel

class AnEnumerator(str, enum.Enum):
    a_value = "a"
    b_value = "other"

class BadType(BaseModel):
    an_enum_keyed_dict: Dict[AnEnumerator, int]

schema = BadType.schema()
print(schema)

{
  'title': 'BadType', 
  'type': 'object', 
  'properties': {
    'an_enum_keyed_dict': {
      'title': 'An Enum Keyed Dict', 
      'type': 'object', 
      'additionalProperties': {'type': 'integer'}
    }
  }, 
  'required': ['an_enum_keyed_dict']
}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
pydantic compiled: True
install path: /usr/local/lib/python3.8/dist-packages/pydantic
python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Before going any further, would this be valid in JSON Schema?

**Comment by lachlancoding** [comment]
I'm not well versed on json schema, I just feel like something in the schema should let you know that Pydantic's gonna flip out if the keys aren't a specific value. 

I guess I would expect the above example to produce something like this?
```
{
  'title': 'BadType',
  'type': 'object',
  'properties': {
    'an_enum_keyed_dict': {
      'title': 'An Enum Keyed Dict',
      'type': 'object',
      "propertyNames": {
        "enum": [
          "a",
          "other"
        ],
        "type": "string"
      },
      "additionalProperties": {
        "type": "integer"
      }
    }
  },
  'required': ['an_enum_keyed_dict']
}
```

**Comment by samuelcolvin** [comment]
https://twitter.com/samuel_colvin/status/1560494510605574145?t=FVx_schJ1cKG7rapfCIAAA&s=19

**Comment by anhpham1509** [comment]
@samuelcolvin Is that possible to populate enum values as keys during schema generation?

**Comment by dmontagu** [comment]
If you can propose a JSON schema for this scenario that you want that is also valid according to JSON schema draft 2020-12, I'm sure `GenerateJsonSchema` could be modified to make it work.

You may even be able to override `GenerateJsonSchema` yourself to achieve the change you want, even if it is not valid JSON schema according to draft 2020-12, but if it isn't, it probably won't be accepted into the official implementation in `pydantic.json_schema.GenerateJsonSchema`.

**Comment by st3w4r** [comment]
I'm looking for this ability as well.

Based on the [JSON schema draft 2020-12](https://json-schema.org/draft/2020-12/json-schema-core#name-propertynames):

> The value of "propertyNames" MUST be a valid JSON Schema.

This should be valid:
```json
"propertyNames": {
  "enum": [
    "keyA",
    "keyB"
  ]
}
```
More details here: https://stackoverflow.com/a/52911689/3877390

I give a try with the python [jsonschema](https://github.com/python-jsonschema/jsonschema) implementation.

```python
import jsonschema

jsonschema.validate(
    instance={
        "mapping":{
            "keyA": "value1",
            "not_a_valid_key": "value2",
        }
    }, schema={
        "properties": {
            "mapping": {
                "propertyNames": {
                    "enum": [
                        "keyA",
                        "keyB"
                    ]
                },
                "additionalProperties": {
                    "type": "string"
                },
                "title": "Mapping",
                "type": "object"
            }
        },
        "required": [
            "mapping"
        ],
        "title": "SimpleModel",
        "type": "object"
    }
)
```
This is working as expected, returning an error when the key is not part of the enum.
```bash
$ jsonschema.exceptions.ValidationError: 'not_a_valid_key' is not one of ['keyA', 'keyB']

Failed validating 'enum' in schema['properties']['mapping']['propertyNames']:
    {'enum': ['keyA', 'keyB']}

On instance['mapping']:
    'not_a_valid_key'
```

I'm keen to contribute in supporting this feature.
