### ISSUE TITLE
Reformatting url validation

### ISSUE THREAD

**Issue by david-shiko** [pydantic/pydantic#4414]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Currently Pydantic has many different field types for url validation.
For example `AnyHttpUrl`, `AnyUrl`, `FileUrl`, etc.
The difference them without reading additional docs is pretty obscured.

May be it's better to reformat validation in the next style:

1. Single filed for all urls (just `url` field for example)
2. Special editable types for schemes, ip, path, TLD, etc. Ut may be just a list of available schemes, paths, etc.
3. Make explicit arguments of current existing urls schemes. 
    Current urls types has implicit `max_length` limit (64 symbols), but the `max_length` parameter itself not exists.
    
Finally this will looks like:
```
class Bar(pydantic.BaseModel):
    url_1: pydantic.url(allowed_schemes={'http', 'https', 'ftp'}, allowed_tld={'com', 'org'}, max_length=128)
    # pydantic.types.net.scheme.all_http = {'http', 'https'}; "any_htpp" will be a bit obscure
    url_2: pydantic.url(allowed_schemes=pydantic.types.net.scheme.all_http, 
                                  allowed_TLD=pydantic.types.net.tld.proprietary)
    url_3: pydantic.url(allowed_schemes="*",  # Any string at all (not only valid one because all valid - is a default)
                                  allowed_TLD=[pydantic.types.net.tld.proprietary, pydantic.types.net.tld.org])
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
That's exactly what `stricturl` does. We could perhaps rename it, but I don't want to change functionality, many people find the specific types useful.

**Comment by david-shiko** [comment]
Thanks, missed paragraph about `stricturl` because it was in the bottom of urls section :)

**Comment by samuelcolvin** [comment]
I agree with your point, in the docs we should:
* put this method first and basically say, "here are a bunch of reconfigured ways to use it"
* we should rename it to something more generic, I would be a bit worried that `url` might conflict with other things, but maybe it's fine
