### ISSUE TITLE
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (1.10.0a1)

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#4423]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

the setup.py as to be adjusted (requirements.txt is)
https://github.com/pydantic/pydantic/blob/9d2e1c40cb0c839771afaf503cbf6590aa335f57/setup.py#L132-L134

### Example Code

```Python
pip install --upgrade typing_extensions=4.0.1
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
```

### Python, Pydantic & OS Version

```Text
I use 1.10.0a1.

~/venv/openapi3/bin/python -c "import pydantic.utils; print(pydantic.utils.version_info())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File …/lib/python3.9/site-packages/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "…/lib/python3.9/site-packages/pydantic/dataclasses.py", line 39, in <module>
    from typing_extensions import dataclass_transform
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (…/lib/python3.9/site-packages/typing_extensions.py)
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @commonism for testing and reporting. I can confirm the bug.

I think we need to change it  `typing_extensions>=4.1.0`. Would you like to prepare a patch?

**Comment by matteoaurelio** [comment]
Hi, I still have this error as well. I did all the steps mentioned here but this error keeps coming. I have Python 3.8 and 3.9.

``
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
    #   |
ImportError: cannot import name dataclass_transform
``

**Comment by samuelcolvin** [comment]
I've formatted your code to be readable, are you sure you're using `require typing_extensions>=4.1.0`?

**Comment by matteoaurelio** [comment]
Hi @samuelcolvin , thank you for your answer. Yes, I am using that version of typing_extensions

**Comment by commonism** [comment]
Let's see and locate yours:

~/venv/python3

```
import typing_extensions
import sys
sys.modules["typing_extensions"]
<module 'typing_extensions' from '…/venv/lib/python3.10/site-packages/typing_extensions.py'>
```

the files does not export __VERSION__ or something … so …

```
grep dataclass_transform …/venv/aiopenapi3/lib/python3.10/site-packages/typing_extensions.py
    'dataclass_transform',
if hasattr(typing, 'dataclass_transform'):
    dataclass_transform = typing.dataclass_transform
    def dataclass_transform(
            from typing_extensions import dataclass_transform
            @dataclass_transform()
            @dataclass_transform()
            @dataclass_transform()
        ``__dataclass_transform__`` attribute on the decorated object.
            cls_or_fn.__dataclass_transform__ = {
```
