### ISSUE TITLE
min_anystr_length config is not displayed in schema

### ISSUE THREAD

**Issue by Colin-b** [pydantic/pydantic#4427]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When setting up [min_anystr_length](https://pydantic-docs.helpmanual.io/usage/model_config/#options) on a pydantic model, the restriction on string length is not replicated in the generated schema.

### Example Code

```Python
import pydantic
import pytest


def test_pydantic_min_anystr_length_config_not_replicated_in_schema():
    class Demo(pydantic.BaseModel):
        class Config:
            min_anystr_length = 1

        misleading: str
        correct: str = pydantic.Field(min_length=1)

    # Demo that schema is not considering any length validation on misleading
    assert Demo.schema() == {
        'properties': {
            'misleading': {'title': 'Misleading', 'type': 'string'},
            'correct': {'title': 'Correct', 'type': 'string', 'minLength': 1},
        },
        'required': ['misleading', 'correct'],
        'title': 'Demo',
        'type': 'object'
    }

    # Demo that code is doing length validation on misleading
    with pytest.raises(pydantic.ValidationError) as expected_error:
        Demo(misleading="", correct="")
    assert expected_error.value.errors() == [
        {
            'ctx': {'limit_value': 1},
            'loc': ('misleading',),
            'msg': 'ensure this value has at least 1 characters',
            'type': 'value_error.any_str.min_length'
        },
        {
            'ctx': {'limit_value': 1},
            'loc': ('correct',),
            'msg': 'ensure this value has at least 1 characters',
            'type': 'value_error.any_str.min_length'
        }
    ]
```

### Python, Pydantic & OS Version

```Text
Python 3.9.1
Pydantic 1.9.1
Windows 10
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Confirmed, we've never replicated `min_anystr_length` and `max_anystr_length` to JSON Schema.

I think with the alpha of v1.10 released and V2 dropping `min_anystr_length` and `max_anystr_length`, we probably won't fix this as much as remove the issue in V2.

**Comment by dmontagu** [comment]
As these config settings are removed in v2, I'm going to close this issue.
