### ISSUE TITLE
inherit from a normal python class 

### ISSUE THREAD

**Issue by tweigel-dev** [pydantic/pydantic#4435]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Hay, 
thanks for maintaining such a great lib.
I noticed that the functionality of the BaseModel is a bit limited. 
Thus I would like to have the support the enhance a normal class from python with the functionality of a BaseModel.
So the user does not have to know from minute 0 that he will use BaseModel.
## what is possible now
~~~ python
class Base(BaseModel):
    foo:str
    bar:str

class A(Base):
    bas: str

A.__fields__, A(foo="abc",bar="xyz",bas=123)
~~~
outputs:
~~~
({'foo': ModelField(name='foo', type=str, required=True),
  'bar': ModelField(name='bar', type=str, required=True),
  'bas': ModelField(name='bas', type=str, required=True)},
 A(foo='abc', bar='xyz', bas='123'))
~~~
# what I would like to have 
~~~ python
class Base:
    foo:str
    bar:str

class A(BaseModel,Base):
    bas: str

A.__fields__, A(foo="abc",bar="xyz",bas=123)
~~~
current output:
~~~
({'bas': ModelField(name='bas', type=str, required=True)}, A(bas='123'))
~~~
Implementing this would hold the DRY principle and could simplify  the ORM methology https://pydantic-docs.helpmanual.io/usage/models/#orm-mode-aka-arbitrary-class-instances

Thanks in advance and looging forward to the discussion!

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I don't agree about this. V2 will support lots of forms of validation, but this seems outside the bounds of what we want to support.
