### ISSUE TITLE
An iterable is not a valid type for sequence

### ISSUE THREAD

**Issue by Dreamsorcerer** [pydantic/pydantic#4438]
### Description

From the docs:
> If you have a generator you can use Sequence as described above. In that case, the generator will be consumed and stored on the model as a list and its values will be validated with the sub-type of Sequence (e.g. int in Sequence[int]).

Code below produces:
```
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[Schema]
__root__ -> resources
  value is not a valid list (type=type_error.list)
```

### Example Code

```Python
from typing import TypedDict, Any
from pydantic import parse_obj_as

class Schema(TypedDict):
    resources: list[Any]

class Something:
    def __init__(self, foo):
        ...

schema = {"resources": map(Something, ("foo", "bar"))}
parse_obj_as(Schema, schema)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /home/ubuntu/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
                     platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Weird, map must produce some weird generator that isn't recognised. What happens on pydantic-core?

**Comment by vetedde** [comment]
Replace `resources: list[Any]` to `resources: Iterable[Any]`
https://pydantic-docs.helpmanual.io/usage/types/
