### ISSUE TITLE
Tuple is transformed into "items" and not "prefixItems"

### ISSUE THREAD

**Issue by anneum** [pydantic/pydantic#4441]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When I create a json schema from a pydantic class, the following schema results. The validation (e.g. https://json-schema.hyperjump.io/) of the schema fails because of the `"items"` values.  
```
{
  "title": "Coordinate",
  "type": "object",
  "properties": {
    "coordinates": {
      "title": "Coordinates",
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": [
        {
          "type": "number"
        },
        {
          "type": "number"
        }
      ]
    }
  },
  "required": [
    "coordinates"
  ]
}
```
From my point of view the better way to create a schema for a tuple is `"prefixItems"` and `"items": false` instead of `"items"` as you can see in the following schema:
```
{
  "title": "Coordinate",
  "type": "object",
  "properties": {
    "coordinates": {
      "title": "Coordinates",
      "type": "array",
      "prefixItems": [
        {
          "type": "number"
        },
        {
          "type": "number"
        }
      ],
      "items": false
    }
  },
  "required": [
    "coordinates"
  ]
}
```

Additionally, for schemas with references `$refs`, the definitions should be under the keyword `$defs` instead of `definitions` according to https://json-schema.org/draft/2020-12/json-schema-core.html#name-schema-re-use-with-defs. 

### Example Code

```Python
from typing import Tuple
from pydantic import BaseModel

class Coordinate(BaseModel):
    coordinates: Tuple[float, float]

print(Coordinate.schema_json(indent=2))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /home/user/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0]
                     platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.29
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
> From my point of view the better way to create a schema for a tuple is "prefixItems" and "items": false instead of "items"

Why? What we have is more concise and equally correct AFAIK.

If you want this changing in V2, you'd need to give a strong argument for it.

**Comment by anneum** [comment]
@samuelcolvin Thank you for your quick reply and sorry, I should have been more precise. 

Tuple items are ordered and for this it is important that the schema also provides a way to order the items.
Because of the json-schema specification I think it is the right implementation for a tuple:
> Tuple validation is useful when the array is a collection of items where each has a different schema and the ordinal index of each item is meaningful.

Soruce: https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation


> Validation succeeds if each element of the instance validates against the schema at the same position, if any.

Soruce: https://json-schema.org/draft/2020-12/json-schema-core.html#name-prefixitems

**Comment by samuelcolvin** [comment]
I think this is related to a change in JSON Schema

From https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

> In Draft 4 - 2019-09, tuple validation was handled by an alternate form of the `items` keyword. When `items` was an array of schemas instead of a single schema, it behaved the way `prefixItems` behaves.

This won't change in V1.10, but in V2 I hope to formally test against a specific version of JSON Schema #4404 and be explicit about exactly what version(s) we support and don't support.

**Comment by Trolldemorted** [comment]
Can you estimate when you'll ship a release with support for this?

**Comment by samuelcolvin** [comment]
See https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#plan-timeframe

V1.10 is released so I'm working on V2 now.
