### ISSUE TITLE
Config `arbitrary_types_allowed=True` not respected for `numpy.ndarray` in Pydantic dataclasses

### ISSUE THREAD

**Issue by vibhas-singh** [pydantic/pydantic#4443]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am trying to use Pydantic's dataclass in my codebase.
I have one dataclass in which the datatype of one of the attributes is `np.ndarray`.

I am using `arbitrary_types_allowed` as `True` but still it is throwing error as
```python
RuntimeError: no validator found for <class 'numpy.ndarray'>, see `arbitrary_types_allowed` in Config
```

The scope of my use case is limited to just validating that the type of this particular attribute is always `np.ndarray` only and not anything else.

### Example Code

```Python
from pydantic.dataclasses import dataclass
from pydantic import Field
import numpy as np

@dataclass
class MyDataclass:
    my_array: np.ndarray = Field(default_factory=lambda: np.zeros([10, 10]))

    class Config:
        arbitrary_types_allowed = True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
pydantic compiled: True
install path: /opt/anaconda3/envs/llm-env/lib/python3.8/site-packages/pydantic
python version: 3.8.12 (default, Oct 12 2021, 06:23:56)  [Clang 10.0.0 ]
platform: macOS-10.16-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [x] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by PrettyWood** [comment]
Config is passed as kwarg for dataclasses

**Comment by vibhas-singh** [comment]
Thanks!
Apologies for missing this important detail.

Linking the reference for the same here: https://pydantic-docs.helpmanual.io/usage/model_config/
