### ISSUE TITLE
Minor typo in comment

### ISSUE THREAD

**Issue by skewty** [pydantic/pydantic#4444]
https://github.com/pydantic/pydantic/blob/f8575aa3793c565cf006979c60ad62312406d5b5/pydantic/typing.py#L341

`"check sare very flakey"` -> `"checks are very flakey"`

**Comment by samuelcolvin** [comment]
Pr welcome, but I think we can live with this.

**Comment by skewty** [comment]
I'd rather not show up as a contributor for something so small.
Thanks for the great product..  Use it with almost every project I write.

**Comment by samuelcolvin** [comment]
No problem, Thank you so much.
