### ISSUE TITLE
Unexpected validation error for Json List[int] fields

### ISSUE THREAD

**Issue by srsridharan** [pydantic/pydantic#4445]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Validating a model with a simple signature
```
class MyJsonModel(BaseModel):
    json_obj: Json[List[int]]
```
fails with a simple example of the form  ` MyJsonModel(json_obj='[00, 2, 3]'))`

I am unsure about if I am missing something obvious. Even changing the field to Json[List[str]]  does not resolve the issue even though 00 is a valid string! Any suggestions are welcome

### Example Code

```Python
from typing import List
from pydantic import BaseModel, Json, ValidationError

class MyJsonModel(BaseModel):
    json_obj: Json[List[int]]
        
class MyJsonModelNew(BaseModel):
    intvar: int

#works fine
print(MyJsonModel(json_obj='[0, 2, 3]'))
#> [0, 2, 3]
#works fine
print(MyJsonModelNew(intvar='00'))
#> 0 

# Validation error
print(MyJsonModel(json_obj='[00, 2, 3]'))
  # > Validation error json_obj
  #>  Invalid JSON (type=value_error.json)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: ~/.cache/pypoetry/virtualenvs/engine-YmclqiR--py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, May 17 2022, 14:19:07)  [GCC 5.4.0 20160609]
                     platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
The input is invalid json.

```py
import json
json.loads('[00, 2, 3]')
#> JSONDecodeError: Expecting ',' delimiter: line 1 column 3 (char 2)
```

Also in js:
```js
JSON.parse('[00, 2, 3]')
//> SyntaxError: Unexpected number in JSON at position 2
```

---

Please don't waste maintainers time with issues like this.
