### ISSUE TITLE
🐛 `extra="allow"/"ignore"` doesn't seem to be working with dataclasses

### ISSUE THREAD

**Issue by vibhas-singh** [pydantic/pydantic#4447]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am trying to ignore/silently pass the extra argument I receive while constructing a dataclass.
I am trying to use `extra="ignore"` and `extra="allow"` in my dataclass config - but it doesn't seem to work as expected.

### Example Code

```Python
from pydantic.dataclasses import dataclass

class DataclassConfig:
    arbitrary_types_allowed = True
    extra = "allow"

@dataclass(config=DataclassConfig)
class MyDataclass:
    name : str
    age: int
    
my_obj = MyDataclass(**{"name": "John WIck", "age": 12})
print(my_obj)
>>> MyDataclass(name='John WIck', age=12)

my_obj = MyDataclass(**{"name": "John WIck", "age": 12, "gender": "M"})
print(my_obj)
>>> TypeError: __init__() got an unexpected keyword argument 'gender'


class DataclassConfig:
    arbitrary_types_allowed = True
    extra = "ignore"

@dataclass(config=DataclassConfig)
class MyDataclass:
    name : str
    age: int
    
my_obj = MyDataclass(**{"name": "John WIck", "age": 12})
print(my_obj)
>>> MyDataclass(name='John WIck', age=12)


my_obj = MyDataclass(**{"name": "John WIck", "age": 12, "gender": "M"})
print(my_obj)
>>> TypeError: __init__() got an unexpected keyword argument 'gender'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
pydantic compiled: True
install path: /opt/anaconda3/envs/llm-env/lib/python3.8/site-packages/pydantic
python version: 3.8.12 (default, Oct 12 2021, 06:23:56)  [Clang 10.0.0 ]
platform: macOS-10.16-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by PrettyWood** [comment]
It has been added in v1.10 (see https://github.com/pydantic/pydantic/blob/main/HISTORY.md#v1100a1-2022-08-22). It's still in beta but should be released soon
