### ISSUE TITLE
`ClassVar` set to ellipsis should be required by daughter classes

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#4448]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

#### Currently
Running this raises no errors:
```python
import abc

from pydantic import BaseModel
from typing import ClassVar


class AbstractModel(BaseModel, abc.ABC):
    required_class_var: ClassVar[str] = ...


class MyModel(AbstractModel):
    against_the_world: str = "forgot_to_define_required_class_var"
```

#### Proposal

This should raise an error:
```python
class MyModel(AbstractModel):
    against_the_world: str = "forgot_to_define_required_class_var"
```
This is should be OK:
```python
class MyModel(AbstractModel):
    required_class_var: str = "defined!"
```
This is also should be OK:
```python
class MyModel(AbstractModel, abc.ABC)):
    this_var: str = "procastrinates"
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Please can you update your issue to be clearer about what the current behaviour is and what you're proposing.

Also, is there any recommendation on this from the standard lib or a PEP?

**Comment by caniko** [comment]
> Please can you update your issue to be clearer about what the current behaviour is and what you're proposing.

Done.

> Also, is there any recommendation on this from the standard lib or a PEP?

No, do you think it should? To me, it makes sense considering `pydantic.Fields` act this way with elipsis.

**Comment by samuelcolvin** [comment]
Makes sense to me, only problem is we might remove use of `abc` in V2 due to https://github.com/python/cpython/issues/92810

**Comment by caniko** [comment]
> Makes sense to me, only problem is we might remove use of `abc` in V2 due to [python/cpython#92810](https://github.com/python/cpython/issues/92810)

So no more abstract classes in `pydantic`? What? :cry:

**Comment by samuelcolvin** [comment]
we'll definitely support abstract classes, we just might not use the `abc` module.

But if there's a good reason to stick with `abc`, we can just override `__isinstance__`.

**Comment by caniko** [comment]
Great! I have no particular attachment to `abc`, just translate the behaviour above to the _new_ way in v2.

**Comment by dlqqq** [comment]
@samuelcolvin Is there any other way in pydantic currently that allows base classes to require a subclass to implement a class attribute? If not, I'm open to owning the PR that would resolve this issue.

**Comment by dlqqq** [comment]
@samuelcolvin ^?

**Comment by dmontagu** [comment]
@dlqqq this is a way you can make base classes require subclasses implement a class attribute:
```python
import abc

from pydantic import BaseModel
from typing import ClassVar


class AbstractModel(BaseModel, abc.ABC):
    required_class_var: ClassVar[str] = ...

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        if cls.required_class_var is ...:
            raise TypeError(f"{cls.__name__} must define required_class_var")


class MyGoodModel(AbstractModel):
    required_class_var: ClassVar[str] = "okay"

    not_required_class_var: str = "not okay"


class MyBadModel(AbstractModel):
    not_required_class_var: str = "not okay"

#> TypeError: MyBadModel must define required_class_var
```
If you want this done more automatically by pydantic, that would require a pull request.

**Comment by Viicos** [comment]
From a type checking perspective, the ellipsis has no meaning, so a simple annotation without any assignments can be used.

One question related to this: what if a subclass of `MyModel` sets the class variable? pyright does not complain about the provided code snippet unless `@final` is used on `MyModel` ([playground](https://pyright-play.net/?pythonVersion=3.12&strict=true&locale=en-us&reportUninitializedInstanceVariable=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMrCoCGANgLABQlWOeURARgMaWWiSyKoY274DCJIgGdhANSIhWVCkyGioAQQbCYIIkxgBZMABMApiQAUjJgDpFAIX4BKAFyUoTqCH0BHAK5JXugPpyRYV8AN0k7KEFAiRAAbVUQAF1pSgABQhRSSgCFLTgdA2NleI1tPUN7R2ciNCJUVV8YAAt9XwB3XBJdcPioAF4oACJgXDQwGAawXwN0ltdPb30-bKDQkAHKIA)).

**Comment by Viicos** [comment]
Considering:

> One question related to this: what if a subclass of `MyModel` sets the class variable? pyright does not complain about the provided code snippet unless `@final` is used on `MyModel` ([playground](https://pyright-play.net/?pythonVersion=3.12&strict=true&locale=en-us&reportUninitializedInstanceVariable=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMrCoCGANgLABQlWOeURARgMaWWiSyKoY274DCJIgGdhANSIhWVCkyGioAQQbCYIIkxgBZMABMApiQAUjJgDpFAIX4BKAFyUoTqCH0BHAK5JXugPpyRYV8AN0k7KEFAiRAAbVUQAF1pSgABQhRSSgCFLTgdA2NleI1tPUN7R2ciNCJUVV8YAAt9XwB3XBJdcPioAF4oACJgXDQwGAawXwN0ltdPb30-bKDQkAHKIA)).

I think this would be only viable to be enforced if the class is marked as `@final`, otherwise this would be too opinionated. However, final classes are only [introspectable in 3.11](https://github.com/python/cpython/issues/90500) unless `typing_extensions.final` is used.

For this reason, and the fact that as David mentioned this can be implemented pretty easily in user code to better fit specific needs (whether the ellipsis should be used/the class should be marked as final), I'll close as not planned.
