### ISSUE TITLE
`pydantic.color.Color` is not hashable in 1.10.0 release

### ISSUE THREAD

**Issue by Czaki** [pydantic/pydantic#4454]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

In pydantic `1.9.2` (and earlier), the Color class was Hashable. in release 1.10.0 it is not hashable that broke usage color as an argument to function decorated with `@lru_cache` from std lib. (https://github.com/napari/napari/issues/4995) 

A I do not see public method for mutate such object IO thin that it is deprecation. 

### Example Code

pydantic 1.9.2
```Python

In [1]: from pydantic.color import Color                                                     

In [2]: a = Color((0,0,0))                                                                   

In [3]: hash(a)                                                                              
Out[3]: 8771047785283
```

pydantic 1.10.0
```python
In [1]: from pydantic.color import Color                                                     

In [2]: a = Color((0,0,0))                                                                   

In [3]: hash(a)                                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-57b555d30865> in <module>
----> 1 hash(a)

TypeError: unhashable type: 'Color'
```
```


### Python, Pydantic & OS Version

```Text
pydantic 1.9.2 vs pydantic 1.10.0 tested on ubuntu and macos m1.
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [x] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks so much for reporting, I've added `napari` to #4359.

Confirmed. Seems this was an unexpected side effect of #3646 I didn't know that adding `__eq__` brakes hashing.

PR welcome to fix this, otherwise I'll do it soon.

**Comment by Czaki** [comment]
I just found it here (second paragraph): https://docs.python.org/3/reference/datamodel.html#object.__hash__, but also do not know earlier.
