### ISSUE TITLE
Regression: Cannot create abstract subclass of SecretStr when abc.ABC goes first

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#4459]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Running the example gives me this error:

```
tests/test_order.py:None (tests/test_order.py)
test_order.py:6: in <module>
    class MySecret(abc.ABC, pydantic.SecretStr):
../../../../../.pyenv/versions/3.9.12/lib/python3.9/abc.py:106: in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
E   TypeError: Cannot create a consistent method resolution
E   order (MRO) for bases ABC, SecretStr
```

With 1.10, `SecretStr` inherits from `SecretField` which is the cause of the problem that does not occur in older versions.

Moving the `abc.ABC` parent class to the end fixes the problem.

This is a strange behaviour as `abc.ABC` is meant as a drop-in replacement for `metaclass=ABCMeta` and I do not expect that kind of side effect.

### Example Code

```Python
import abc

import pydantic


class MySecret(abc.ABC, pydantic.SecretStr):
    ...


def test_():
    assert MySecret("abc")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.1
            pydantic compiled: True
                 install path: /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/juiceutils-fastapi-eDHiZ_Ay-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, May 25 2022, 10:42:02)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by chbndrhnns** [comment]
Upon further [reading](https://stackoverflow.com/a/65548520/6112272), the MRO error is expected if two classes in the class hierarchy implement `abc.ABC`.

Using `metaclass=abc.ABCMeta` solves the issue and also (as I wrote above) moving `abc.ABC` to the end.

**Comment by samuelcolvin** [comment]
Thanks for reporting.

Seems pretty niche, do you think we need to make any changes in pydantic it just update the docs?

**Comment by chbndrhnns** [comment]
It's an interesting (but niche) side effect. If this behaviour applies to more pydantic data types, I would suggest a general note: "If you make a subclass of a pydantic type abstract, either use `metaclass=ABCMeta` or move `abc.ABC` to the end of the subclasses"

But I also understand nothing changes.
The issue here will stay for further reference.

**Comment by samuelcolvin** [comment]
Totally agree.

We should review prior to V2 and make sure all pydantic types exhibit the same behaviour.

**Comment by dmontagu** [comment]
This is resolved in v2.
