### ISSUE TITLE
v1.10.2

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4472]
* [x] #4470
* [x] #4471
* [x] #4476 - may as well before it causes problems.
* [x] #4480
* [x] #4482
* [x] #4484

Anything more?

**Comment by samuelcolvin** [comment]
https://github.com/pydantic/pydantic/issues/1477

**Comment by Bobronium** [comment]
Could you please take a look at https://github.com/pydantic/pydantic/issues/3300#issuecomment-1236129855?

**Comment by samuelcolvin** [comment]
done.
