### ISSUE TITLE
Generic model parameterization raise `KeyError` after multiple calls 

### ISSUE THREAD

**Issue by uriyyo** [pydantic/pydantic#4483]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

After 200+ same generic model parameterization pydantic throws `KeyError`.
This issue is only reproducible when one generic model is inherited from another generic model and they use different instances of `TypeVar`.

The issue isn't reproducible in version `1.9.0`.

UPDATE: After investigation, I have found that [#4083](https://github.com/pydantic/pydantic/pull/4083) is the root cause of this issue.

### Example Code

```Python
from itertools import count
from typing import Generic, TypeVar

from pydantic import BaseModel
from pydantic.generics import GenericModel

T = TypeVar("T")


class Base(GenericModel, Generic[T]):
    a: T


R = TypeVar("R")


class Delivered(Base[R], Generic[R]):
    b: R


for i in count():
    class B(BaseModel):
        a: int


    m = Delivered[B]
```
```py
Traceback (most recent call last):
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/temp.py", line 26, in <module>
    m = Delivered[B]
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 98, in __class_getitem__
    __base__=(cls,) + tuple(cls.__parameterized_bases__(typevars_map)),
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 219, in __parameterized_bases__
    yield from build_base_model(base_model, typevars_map)
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 185, in build_base_model
    parameterized_base = base_model.__class_getitem__(base_parameters)
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 98, in __class_getitem__
    __base__=(cls,) + tuple(cls.__parameterized_bases__(typevars_map)),
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 219, in __parameterized_bases__
    yield from build_base_model(base_model, typevars_map)
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 184, in build_base_model
    base_parameters = tuple([mapped_types[param] for param in base_model.__parameters__])
  File "/Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic/generics.py", line 184, in <listcomp>
    base_parameters = tuple([mapped_types[param] for param in base_model.__parameters__])
KeyError: ~T
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /Users/yuriikarabas/my-projects/fastapi-pagination/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for reporting, @PrettyWood has plans to improve generics in V2.

Until then this is just a limitation of pydantic, better this than the silent memory leak.

**Comment by dmontagu** [comment]
This appears to be fixed now in v2, at least I don't get the error running the above for a long time.
