### ISSUE TITLE
Model instance reference equality check fails when used as a field of another model.

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#4485]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic  (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Model instances do not have the same `id(obj)` output when used as a field of another model instance.
Both references are confirmed to be using the same underlying model instance as expected because updating an attribute on one updates it on the other. 
However, `model is wrapped_model.model` outputs to `False` when it should be `True`.

Hit this strange behaviour when validating my system hasn't accidentally duplicated model instances which should be used globally.

### Example Code

```Python
from pydantic import BaseModel

class Model(BaseModel):
    field = "foo"

class ModelWrapper(BaseModel):
    model: Model

model = Model()
wrapper = ModelWrapper(model=model)
model.field = "bar"

print(f"Model id: '{id(model)}', field: '{model.field}'")
print(f"Wrapped Model id: '{id(wrapper.model)}', field: '{wrapper.model.field}'")
print(f"Are same object: {model is wrapper.model}")

'''
  CONSOLE OUT:
  Model id: '140480413832272', field: 'bar'
  Wrapped Model id: '140479906941136', field: 'bar'
  Are same object: False
'''
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.1
            pydantic compiled: True
                 install path: .../lib/python3.11/site-packages/pydantic
               python version: 3.11.0rc1 (main, Aug  8 2022, 18:31:54) [GCC 9.4.0]
                     platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Settings Management](https://pydantic-docs.helpmanual.io/usage/settings/)
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I can confirm it. this is the same in `v1.9.2` and `v1.8.2`. 
Not sure how we should address it and as it's not a change in behavior, we may address it in `v2`.

@samuelcolvin what do you think?

**Comment by PrettyWood** [comment]
By default fields are deepcopied but it can be changed through the config. It could be changed in v2 to keep references by default. Personally I would like that. But not sure if that's what @samuelcolvin wants.

**Comment by zakstucke** [comment]
@PrettyWood I don't think it is being deep copied correctly if that's meant to be the default behaviour. 
See the example, I update the model instance "field" attribute from "foo" to "bar", it is changed in both locations. 

Given they seem to be the same object (which was the default behaviour I was expecting), then the `is` check not outputting `True` between the two objects does seem to be a bug.

**Comment by PrettyWood** [comment]
By default we shallow copy sorry. You can change the behaviour with `Config.copy_on_model_validation` set to `'none'`, `'shallow'` (default) or `'deep'`
