### ISSUE TITLE
string values of `given` in `value_error.const` error messages are reported without enclosing quotes

### ISSUE THREAD

**Issue by DMRobertson** [pydantic/pydantic#4505]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I noticed that strings are reported without enclosing quotes. This isn't a huge problem but it could cause confusion if `given` is a string which looks like `str(x)` for some non-string `x`. E.g. in the example below I get the same error message when `given` is the integer `123` and the string `'123'`.

I haven't looked at the source code, but I would guess there is a format string which ends up calling `str(given)` instead `repr(given)`. I think I'd prefer the latter, though if `given` were a complicated object like a a long list or a heavily nested dictionary its `repr(...)` could be unwieldy.

### Example Code

```Python
from pydantic import BaseModel, ValidationError
from typing import Literal

class Model(BaseModel):
    field: Literal["hello", "world"]

try:
    Model.parse_obj({"field": 123})
except ValidationError as e:
    print(e)
    # 1 validation error for Model
    # field
    #   unexpected value; permitted: 'hello', 'world' (type=value_error.const; given=123; permitted=('hello', 'world'))


try:
    Model.parse_obj({"field": "123"})
except ValidationError as e:
    print(e)
    # 1 validation error for Model
    # field
    #   unexpected value; permitted: 'hello', 'world' (type=value_error.const; given=123; permitted=('hello', 'world'))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/dmr/.cache/pypoetry/virtualenvs/matrix-synapse-RhMlrixz-py3.10/lib64/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
                     platform: Linux-5.18.18-200.fc36.x86_64-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions'
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by DMRobertson** [comment]
I think `given` is part of the `ctx` which gets formatted here:

https://github.com/pydantic/pydantic/blob/ee52496101f7d2b69ccfad61b89f985af52ad0e6/pydantic/error_wrappers.py#L82-L96

**Comment by hramezani** [comment]
@DMRobertson This got fixed in `Pydantic V2`.
Pydantic V2 alpha is out and you can install it by `pip install pydantic --pre`.

Here is the output of your example code in Pydantic V2:
```bash
1 validation error for Model
field
  Input should be 'hello' or 'world' [type=literal_error, input_value=123, input_type=int]
1 validation error for Model
field
  Input should be 'hello' or 'world' [type=literal_error, input_value='123', input_type=str]
```

The `input_value` is `123` for number input and `'123'` for string input
