### ISSUE TITLE
Maximum recursion depth exceeded. Two python dataclasses references each other + one pydantic inheritor.

### ISSUE THREAD

**Issue by david-shiko** [pydantic/pydantic#4509]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have created basic python schemas via python data classes. 
It's mostly for logical description, I'm not using these schemas directly in the code.

Then I'm inheriting these schemas to make validation with Pydantic and make my life easiest :)
In fact, I'm overriding every field after inheritance. Inheritance here mostly marks a logical structure.

And boom, getting maximum recursion depth. 
The key moment: 
Two python data classes use type annotation of each other and then empty Pydantic data just inherit one of the models. That is.

P.S.  I looked at a few similar questions (https://github.com/pydantic/pydantic/issues/2279#issue-791121103) but I'm not using `update_forward_refs` as it was in both questions.

### Example Code

```Python
from __future__ import annotations
import pydantic
import dataclasses


@dataclasses.dataclass
class Recipe:
    author: Cook

The error:
...
RecursionError: maximum recursion depth exceeded while calling a Python object


@dataclasses.dataclass
class Cook:
    recipes: list[Recipe]


@pydantic.dataclasses.dataclass
class Foo(Cook):
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: /home/david/PycharmProjects/tasti/venv/lib/python3.10/site-packages/pydantic
python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.35
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Confirmed, this is new in v1.10.

Any idea what this might be @PrettyWood? Seems to be related to the the dataclass changes 😞.

**Comment by mfulgo** [comment]
I'm able to reproduce the issue in `v1.10.2`, `v1.10.1`, `v1.10.0`, `v1.9.2`, `v1.9.1`, `v1.9.0`, `v1.8.2`, `v1.8.1`, `v1.8`, but not `v1.7.4`.

@samuelcolvin - Given that this has been an issue since 2021-02-26, is it something that needs to go into 1.10.3 before it's released? I'm a little afraid cycle detection for this could end up being a sizable effort, but others can probably judge that better than I.


-----------
(Note: I needed to use `List[Recipe]` instead of `list[Recipe]` to trigger the issue.)
Including the relevant parts of the stack trace here:
```
tests/test_dataclasses_cycle.py:None (tests/test_dataclasses_cycle.py)
test_dataclasses_cycle.py:20: in <module>
    class Foo(Cook):
../pydantic/dataclasses.py:255: in dataclass
    return wrap(_cls)
../pydantic/dataclasses.py:250: in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen, config)
../pydantic/dataclasses.py:186: in _process_class
    cls.__pydantic_model__ = create_model(
../pydantic/main.py:974: in create_model
    return type(__model_name, (__base__,), namespace)
../pydantic/main.py:287: in __new__
    fields[ann_name] = ModelField.infer(
../pydantic/fields.py:392: in infer
    return cls(
../pydantic/fields.py:327: in __init__
    self.prepare()
../pydantic/fields.py:432: in prepare
    self._type_analysis()
../pydantic/fields.py:610: in _type_analysis
    self.sub_fields = [self._create_sub_type(self.type_, '_' + self.name)]
../pydantic/fields.py:629: in _create_sub_type
    return self.__class__(
../pydantic/fields.py:327: in __init__
    self.prepare()
../pydantic/fields.py:438: in prepare
    self.populate_validators()
../pydantic/fields.py:651: in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
../pydantic/validators.py:675: in find_validators
    yield from make_dataclass_validator(type_, config)
../pydantic/dataclasses.py:266: in make_dataclass_validator
    cls = dataclass(_cls, config=config, **stdlib_dataclass_parameters)
(repeats from ../pydantic/dataclasses.py:255: in dataclass)
```

**Comment by samuelcolvin** [comment]
This won't be added in a patch release, it's a difficult and complex matter that wouldn't be suitable for pydantic v1 rich is effectively in maintenance mode now.

However it's already implemented in pydantic-core and will be there in V2.

**Comment by samuelcolvin** [comment]
Sorry ignore that, I thought it was referring to general recursion detection.

If this is new in v1.10, it should be possible to fix it in v1.10.3.

**Comment by mfulgo** [comment]
I'm just saying it's new as of v1.8, so it's been a bug for a while. I'm sure it's fixable in v1, just a question of effort and whether you want it for 1.10.3 or if it can wait for 1.10.4.

**Comment by adriangb** [comment]
It seems this is still an issue in v1.10.X _and_ v2. I made #5624 for v2, but the v1 fix/issue is unrelated so I don't think we'll be able to get around to that. I'd recommend upgrading to v2 once it's released (and please try it before then!).
