### ISSUE TITLE
Settings: Environment variables are not read if explicitly specified for nested fields

### ISSUE THREAD

**Issue by m2m1** [pydantic/pydantic#4515]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I use pydantic settings to read environment variables. I want to explicitly specify the name of an environment variable for fields using `var: int = Field(..., env='desired_name')`. This raises an error for me if the field is placed inside of a submodel. I expected that the environment variable is read and stored correctly.

The environment variable is read correctly if:
- the name of the environment variable matches the env_nested_delimiter convention if it is set up
- the environment variable matches the nested model structure with dicts
- the field is a top level field

### Example Code

```Python
from pydantic import BaseSettings, Field, BaseModel
import os


class SubModel(BaseModel):
    sub_var: int = Field(..., env='desired_name')


class Config(BaseSettings):
    sub: SubModel
    top_var: int = Field(..., env="t_var")


os.environ["t_var"] = "21"
os.environ["desired_name"] = "42"

c = Config()
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 1.10.1
            pydantic compiled: True
                 install path: /home/xxxx/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
                     platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I think the current behavior is right. You are initializing `Config` model and Pydantic is looking for its fields `sub` and `top_var`.

**Comment by samuelcolvin** [comment]
Please use discussions for questions. This is not a bug.
