### ISSUE TITLE
BaseModel does not validate field when updating it

### ISSUE THREAD

**Issue by will-afs** [pydantic/pydantic#4522]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

BaseModel should validate fields at instanciation and when setting a new value for a field.
It appears it only validates fields at instanciation. Not when setting a new value for a field.

### Example Code

```Python
>>> from pydantic import BaseModel, Field, NonNegativeFloat
>>> class Account(BaseModel):
...     rate_of_interest: NonNegativeFloat
... 
>>> a = Account(rate_of_interest = -0.0002199999999999850)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Account
rate_of_interest
  ensure this value is greater than or equal to 0 (type=value_error.number.not_ge; limit_value=0)
```

OK

```Python
>>> a = Account(rate_of_interest = -0)
>>> a
Account(rate_of_interest=0.0)
```

OK

```Python
>>> a.rate_of_interest = -0.0002199999999999850
>>> a
Account(rate_of_interest=-0.000219999999999985)
```

/!\ NOK /!\ 

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /home/william/Programming/sara/sara_api/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug  2 2022, 15:11:28) [GCC 9.4.0]
                     platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
You can use [validate_assignment](https://pydantic-docs.helpmanual.io/usage/model_config/#options) option to perform validation on assignment.

```python
from pydantic import BaseModel, Field, NonNegativeFloat
class Account(BaseModel):
    rate_of_interest: NonNegativeFloat

    class Config:
        validate_assignment = True
```
