### ISSUE TITLE
The combination of a constrained type and a Generic Model raise keyerror

### ISSUE THREAD

**Issue by fr-ser** [pydantic/pydantic#4528]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

As shown in the example below Pydantic raises a Keyerror, when I try to retrieve the schema for this code (combination of constr and GenericModel)

```txt
Traceback (most recent call last):
  File "repro.py", line 22, in <module>
    TheModel.schema()
  File "pydantic/main.py", line 664, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 186, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 922, in pydantic.schema.field_singleton_schema
KeyError: <class '__main__.Wrapper[ConstrainedStrValue]'>
```

### Example Code

```Python
from typing import Generic, TypeVar

from pydantic import BaseModel, constr
from pydantic.generics import GenericModel

GenericValue = TypeVar("GenericValue")


_PhoneString = constr(min_length=1)
_BicString = constr(min_length=2)


class Wrapper(GenericModel, Generic[GenericValue]):
    value: GenericValue


class TheModel(BaseModel):
    bic_swift2: Wrapper[_PhoneString]  # type: ignore
    bic_swift: Wrapper[_BicString]  # type: ignore


TheModel.schema()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/name/Desktop/repro/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.13 (default, Aug  3 2022, 12:05:10)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.6-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
We'll see if we can support this in V2, no guarantees though.

**Comment by sydney-runkle** [comment]
Marking as resolved, looks like this is supported in v2!
