### ISSUE TITLE
Confusing docs about models

### ISSUE THREAD

**Issue by Chichilele** [pydantic/pydantic#4530]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

[prase_obj doc](https://github.com/pydantic/pydantic/blob/abd687700afe28745a3af5bca6f0f0ba48c86d1e/docs/usage/models.md?plain=1#L82) and [helper docs](https://github.com/pydantic/pydantic/blob/abd687700afe28745a3af5bca6f0f0ba48c86d1e/docs/usage/models.md?plain=1#L231) say conflicting things

`parse_obj` docs says if object it NOT a dictionary:
> `parse_obj()`
: a utility for loading any object into a model with error handling if the object is not a dictionary;
  cf. [helper functions](#helper-functions)

and helper docs says it takes a dict argument.
> * **`parse_obj`**: this is very similar to the `__init__` method of the model, except it takes a dict
  rather than keyword arguments. If the object passed is not a dict a `ValidationError` will be raised.

### Python, Pydantic & OS Version

```Text
v 1.10.2
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @Chichilele for reporting.

> parse_obj docs says if object it NOT a dictionary:
parse_obj()
: a utility for loading any object into a model with error handling if the object is not a dictionary;
cf. [helper functions](https://github.com/pydantic/pydantic/issues/4530#helper-functions)

I think it means it will raise an error in the object is not a dict. But agree with you that it is not clear.

We are working on `V2` and the [parse_obj probably will be changed to model_validate](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#model-namespace-cleanup). We have to address this in `V2`

**Comment by Chichilele** [comment]
Sounds like an amazing plan. Keep up with the good work!
