### ISSUE TITLE
Unexpected behavior when creating a dataclass with `confloat` and validator method.

### ISSUE THREAD

**Issue by EricKeenan** [pydantic/pydantic#4531]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I'm trying to restrict parameter values and enforce relative comparisons using a `confloat` and validator method, respectively. Specifically, I want:
1. 0 < `a` < 100
2. `a` < `b`

My implementation attempt looks like this:
```python
from pydantic import validator, confloat
from pydantic.dataclasses import dataclass

@dataclass
class testClass:
    a: confloat(gt=0, lt=100)
    b: float

    @validator('b')
    def compare_magnitudes(cls, v, values):
        if  v <= values['a']:
            raise ValueError("b <= a")
        else:
            return v

x = testClass(a=-10, b=90)
```

I expect this to fail because `a` < 0. However, the error (in my opinion) is not useful. Instead of telling the user that the `confloat` restriction is violated, it simply declares that `a` is not defined.
```console
(osn-attune) WMRUSR21LTM0020:stradivarius erickeenan$ python3 test.py
Traceback (most recent call last):
  File "/Users/erickeenan/repos/stradivarius/stradivarius/test.py", line 18, in <module>
    x = testClass(a=-10, b=90)
  File "pydantic/dataclasses.py", line 313, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    f'order={self.order!r},'
  File "pydantic/dataclasses.py", line 414, in pydantic.dataclasses._dataclass_validate_values

  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 898, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 287, in pydantic.class_validators._generic_validator_cls.lambda5
  File "/Users/erickeenan/repos/stradivarius/stradivarius/test.py", line 13, in compare_magnitudes
    if  v <= values['a']:
KeyError: 'a'
```

Instead I was expecting the error to look like what comes from the same code but without the `validator` method:
```python
from pydantic import validator, confloat
from pydantic.dataclasses import dataclass

@dataclass
class testClass:
    a: confloat(gt=0, lt=100)
    b: float

    # @validator('b')
    # def compare_magnitudes(cls, v, values):
    #     if  v <= values['a']:
    #         raise ValueError("b <= a")
    #     else:
    #         return v

x = testClass(a=-10, b=90)
```
```console
(osn-attune) WMRUSR21LTM0020:stradivarius erickeenan$ python3 test.py
Traceback (most recent call last):
  File "/Users/erickeenan/repos/stradivarius/stradivarius/test.py", line 18, in <module>
    x = testClass(a=-10, b=90)
  File "pydantic/dataclasses.py", line 313, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    f'order={self.order!r},'
  File "pydantic/dataclasses.py", line 416, in pydantic.dataclasses._dataclass_validate_values
    def _field_init(f, frozen, globals, self_name):
pydantic.error_wrappers.ValidationError: 1 validation error for testClass
a
  ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)
```

Is there a way to preserve the `confloat` message while keeping the validator method? Is this a bug? Or do I have something wrong with my implementation? 

### Python, Pydantic & OS Version

```Text
(osn-attune) WMRUSR21LTM0020:stradivarius erickeenan$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/erickeenan/anaconda3/envs/osn-attune/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ]
                     platform: macOS-12.6-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by EricKeenan** [comment]
@hramezani Thanks for your reply.

So the correct interpretation would be that since `a` fails it's validation (-10 < 0), `compare_magnitudes` cannot find `a`, hence the `KeyError`? 

Is there a straightforward approach in `pydantic` to produce a more informative error. E.g. something like `ensure this value is greater than 0 (type=value_error.number.not_gt; limit_value=0)`

```python
from pydantic import validator, confloat
from pydantic.dataclasses import dataclass

@dataclass
class testClass:
    a: confloat(gt=0, lt=100)
    b: float

    @validator('b')
    def compare_magnitudes(cls, v, values):
        if  v <= values['a']:
            raise ValueError("b <= a")
        else:
            return v

x = testClass(a=-10, b=90)
```

**Comment by samuelcolvin** [comment]
No, because it would involve using a different object that would be slower to access.

Something might be possibly in v2 though.
