### ISSUE TITLE
Encode dataclass custom root json is different from `BaseModel` custom root json

### ISSUE THREAD

**Issue by zen-xu** [pydantic/pydantic#4539]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Encode dataclass custom root json is different from `BaseModel` custom root json

### Example Code

```Python
import json

from pydantic import BaseModel
from pydantic.dataclasses import dataclass
from pydantic.json import pydantic_encoder
from typing import List

class Model1(BaseModel):
    __root__: List[int]

obj1 = Model1(__root__=[1, 2, 3])
print(obj1.json())
"""
[1, 2, 3]
"""

@dataclass
class Model2:
    __root__: List[int]

obj2 = Model2(__root__=[1, 2, 3])
print(json.dumps(obj2, default=pydantic_encoder))
"""
{"__root__": [1, 2, 3]}
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/near/.pyenv/versions/miniconda3-latest/envs/test2/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-21.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
ye, we have [Custom Root Types](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) on models, but not dataclasses.

**Comment by zen-xu** [comment]
I fix it in #4540 
@samuelcolvin

**Comment by samuelcolvin** [comment]
It's not a bug, it's the correct behaviour.

**Comment by zen-xu** [comment]
The reason is?

**Comment by samuelcolvin** [comment]
1. Custom root types wouldn't make sense on dataclasses
2. Please ready [pull request template](https://github.com/pydantic/pydantic/blob/main/.github/PULL_REQUEST_TEMPLATE.md) which you must have seen and deleted - we're working on V2 where custom root types will be removed completely, and this isn't suitable for a patch release on V1.X, you might also want to read https://pydantic-docs.helpmanual.io/blog/pydantic-v2/
3. Your PR contained no explanation.

**Comment by zen-xu** [comment]
Since the `pydantic_dataclass` custom root cannot be mixed with other fields, I think to encode it should be the same behavior as `BaseModel`.

And not everyone is ready to move `pydantic` from V1 to V2, that needs time

**Comment by samuelcolvin** [comment]
> And not everyone is ready to move pydantic from V1 to V2, that needs time

Agreed, but active development of V1 has stopped we're just releasing some minimal bug fixes, there will be no V1.11 and this change would not be suitable for a patch release.

**Comment by zen-xu** [comment]
So inconsistent behavior of encoding custom root between `pydantic_dataclass` and `BaseModel` is not a Bug?

**Comment by samuelcolvin** [comment]
No it's not - `__root__` doesn't mean anything special in dataclasses.

But more generally, there are real and problematic bugs in pydantic v1 - like in any codebase of this size and complexity. But if we tried to fix them all, we'd 1) fail, 2) never get to V2 such should be significantly easier to maintain, and long term have far fewer bugs.
