### ISSUE TITLE
PostgresDsn multiple hosts without TLD

### ISSUE THREAD

**Issue by levsh** [pydantic/pydantic#4541]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hi!
I have two questions:
1. From [docs](https://pydantic-docs.helpmanual.io/usage/types/#urls) "PostgresDsn: user info required, TLD not required, host required, as of V.10 PostgresDsn supports multiple hosts". User info required but postgresql [docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) has example "postgresql://host1:123,host2:456/somedb?target_session_attrs=any&application_name=myapp"
2. It seems PostgresDsn doesn't work properly with multiple hosts without TLD

Thank you

### Example Code

```Python
In [1]: import pydantic
   ...: from pydantic import BaseModel, PostgresDsn
   ...: 
   ...: class M(BaseModel):
   ...:     url: PostgresDsn
   ...: 

# Not ok
In [2]: M(url="postgresql://host1:123,host2:456/somedb?target_session_attrs=any&application_name=myapp")
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In [2], line 1
----> 1 M(url="postgresql://host1:123,host2:456/somedb?target_session_attrs=any&application_name=myapp")

File ~/.local/share/virtualenvs/.../lib/python3.8/site-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for M
url
  userinfo required in URL but missing (type=value_error.url.userinfo)

# Not ok
In [3]: M(url="postgresql://u:p@host1:123,host2:456/somedb?target_session_attrs=any&application_name=myapp")
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In [3], line 1
----> 1 M(url="postgresql://u:p@host1:123,host2:456/somedb?target_session_attrs=any&application_name=myapp")

File ~/.local/share/virtualenvs/.../lib/python3.8/site-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for M
url
  build() needs keyword-only argument host (type=type_error)

# Add .com
# Ok
In [4]: M(url="postgresql://u:p@host1.com:123,host2.com:456/somedb?target_session_attrs=any&application_name=myapp")
Out[4]: M(url=PostgresDsn('postgresql://u:p@host1.com:123,host2.com:456/somedb?target_session_attrs=any&application_name=myapp', ))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/vagrant/.local/share/virtualenvs/.../lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Dec 22 2020, 17:04:29)  [GCC 7.5.0]
                     platform: Linux-4.15.0-192-generic-x86_64-with-glibc2.27
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
There are a couple of problems here.
1. `PostgresDsn(...)` has some slightly weird behaviour and isn't expected to work like this. I agree that this is very confusing, it should either work properly, or fail completely.
2. There are a whole host of problems with `URL` types see #4470 for some explanation, basically we run some different logic only if there's a TLD, the problem as per #4470 is that if we run that logic on all URLs, a whole bunch of tests fail.

The medium term solutions is to move to a dedicated URL validation library in V2, there is'nt really a good short term solution I'm afraid, you might be best to implement your own validation.

**Comment by Kludex** [comment]
This is already working on V2. 🙏
