### ISSUE TITLE
Field validators doesn't work properly with forward refs

### ISSUE THREAD

**Issue by suharnikov** [pydantic/pydantic#4547]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When I add `max_item` validator to forward ref list field I get the next error:
```py
File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 1011, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "nested_list" the following field constraints are set but not enforced: max_items. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```
But when I use direct order without `annotations` it works properly

### Example Code

```Python
from __future__ import annotations

from pydantic import Field, BaseModel


class TestModel(BaseModel):
    nested_list: list[Nested] = Field(max_items=5)


class Nested(BaseModel):
    pass

# File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
#   File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
#   File "pydantic/schema.py", line 1011, in pydantic.schema.get_annotation_from_field_info
# ValueError: On field "nested_list" the following field constraints are set but not enforced: max_items. 
# For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: /usr/lib/python3.10/site-packages/pydantic
python version: 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
platform: Linux-5.19.9-zen1-1-zen-x86_64-with-glibc2.36
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Confirmed, thanks for reporting. Realistically, I doubt this will be closed until V2, but good to have it reported so we make sure it does get fixed in V2.

**Comment by hramezani** [comment]
@suharnikov it got fixed in `V2`.
As you may know, `Pydantic V2` is now in an alpha state. you can install it by `pip install pydantic --pre`.

Here is a working example inspired by your initial example:
```py
from __future__ import annotations

from pydantic import Field, BaseModel


class TestModel(BaseModel, undefined_types_warning=False):
    nested_list: list[Nested] = Field(max_items=2)


class Nested(BaseModel):
    a: str

TestModel.model_rebuild()
print(TestModel(nested_list=[Nested(a='a'), Nested(a='a')]))
```
