### ISSUE TITLE
v1.10.3

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4552]
We need a new release which should fix (beyond what's already merged) the following:
* [x] #4493 (fixes #4487)
* ~[ ] #4509 - if possible, but it's not new in v1.10~
* [x] #4551
* [x] #4695
* [x] #4568
* [x] #4781
* [x] #2276
* [x] #4878
* [x] #4884

Anything else?

**Comment by samuelcolvin** [comment]
@PrettyWood @hramezani I think we're ready to go :rocket:.

Let me know here if you think there's anything that needs doing before we release v1.10.3?

**Comment by hramezani** [comment]
Nothing from my side.  Let's go 🚀

**Comment by PrettyWood** [comment]
Same

**Comment by samuelcolvin** [comment]
Done, building now.
