### ISSUE TITLE
"Too few public methods" false positives in PyLint when inheriting from GenericModel

### ISSUE THREAD

**Issue by rkr87** [pydantic/pydantic#4553]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have a class that inherits from GenericModel and adds _x_ public methods to the resulting model. If I then inherit from my created class but don't specify any additional public methods, I receive a "Too few public methods" warning from PyLint (despite the resulting class having the public methods inherited from the base class).

Example below;
RootDictModel inherits from GenericModel and adds 3 public methods.
Tags inherits from RootDictModel (specifying Types)
Shortcuts inherits from RootDictModel (specifying Types)

Both Tags and Shortcuts give a "Too few public methods" warning in Pylint. However, if I switch RootDictModel to inherit from BaseModel instead of GenericModel - the Pylint errors go away.

### Example Code

```Python
from typing import Generic, Iterator, Tuple, TypeVar
from pydantic import BaseModel, ConstrainedStr, Field
from pydantic.generics import GenericModel

_KT = TypeVar('_KT', str, ConstrainedStr)
_VT = TypeVar('_VT')

class RootDictModel(GenericModel, Generic[_KT, _VT]):
    __root__: dict[_KT, _VT] = {}
    def __getitem__(self, key: _KT) -> _VT:
        return self.__root__[key]
    def __iter__(self) -> Iterator[_KT]:  # type: ignore
        return iter(self.__root__)
    def keys(self) -> list[_KT]:
        return list(self.__root__.keys())
    def values(self) -> list[_VT]:
        return list(self.__root__.values())
    def items(self) -> list[Tuple[_KT, _VT]]:
        return list(self.__root__.items())

class TagKey(ConstrainedStr):
    regex: re.Pattern[str] = re.compile(r'^\d*$')

class Tags(RootDictModel[TagKey, str]):
    ...

class Shortcut(BaseModel, extra='allow'):
    id: int = Field(alias="appid")
    name: str = Field(alias="appname")
    tags: Tags = Tags()

class Shortcuts(RootDictModel[str, Shortcut]):
    ...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: False
install path: /home/deck/Desktop/PythonProjects/projects/distiller/.venv/lib/python3.10/site-packages/pydantic
python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
platform: Linux-5.18.1-arch1_testHoloISO_20220606.1811-x86_64-with-glibc2.33
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
PyLint doesn't play well with pydantic, see #568 and a few other issues.

Generics will change somewhat in pydantic V2, but I can't guarantee it'll play nicely with pylint.
