### ISSUE TITLE
Pydantic type hints for parse_obj_as don't pass mypy strict validation

### ISSUE THREAD

**Issue by EldarSehayekZenity** [pydantic/pydantic#4556]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Our team is using pydantic extensively and I'm working on enabling mypy strict validations.
We have code that calls the `parse_obj_as` generic function, however due to how its type hinted mypy infers it returns `Any` instead of the type `T` it is given. If I make mypy "skip" pydantic then it treats the return type as `Any` and not `T` as desired.
For your information, I've opened this originally as [issue on the mypy team](https://github.com/python/mypy/issues/13712), they insist it should be solved on pydantic's end and they reject the idea of implementing a feature that allows mypy to trust an imported package's type hints as is.

To re-produce the issue, run mypy on below code with the following settings:

- Mypy version used: 0.971
- Mypy command-line flags: N/A
- Mypy configuration options from `pyproject.toml`:

[tool.mypy]
follow_imports = "normal"
ignore_errors = false
implicit_reexport = false
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
disallow_untyped_defs = true
check_untyped_defs = true
allow_redefinition = false
local_partial_types = true
strict_optional = true
strict_equality = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
no_implicit_optional = true
strict = true

- Python version used: 3.10.4
- Operating system and version: Windows 11

### Example Code

```Python
from pydantic import AnyHttpUrl, parse_obj_as

def get_url() -> AnyHttpUrl:
    return parse_obj_as(AnyHttpUrl, "https://contoso.com")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: <installed in my project's venv, path omitted for privacy>
python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.22000-SP0
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Ye, in v2 we could probably return `T`.

**Comment by dmontagu** [comment]
This should be fixed in v2 since we no longer have a `@no_type_check` on anything in v2 that is related to types (and `AnyUrl` has changed a bit more significantly, so shouldn't have this issue).
