### ISSUE TITLE
create_model_from_namedtuple error due to typing.NamedTuple implementation.

### ISSUE THREAD

**Issue by viniciusao** [pydantic/pydantic#4559]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I was following pydantic's tutorial about models creation and I tried _create_model_from_namedtuple_, but I received the following error:

![image](https://user-images.githubusercontent.com/71805493/191988304-f43993af-7844-4643-85e3-b8ec5b143f8d.png)

I expected to convert smoothly as with TypedDict.

### Example Code

```Python
class Shape(NamedTuple):
    width: float
    height: float

create_model_from_namedtuple(Shape(1, 1))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: /home/vinicius/PycharmProjects/pydantic_fix/venv/lib/python3.10/site-packages/pydantic
python version: 3.10.5 (main, Jun 11 2022, 16:53:24) [GCC 9.4.0]
platform: Linux-5.4.0-121-generic-x86_64-with-glibc2.31
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by florianfischer91** [comment]
I think you have to pass in a type (class) instead of an instance?

**Comment by viniciusao** [comment]
> I think you have to pass in a type (class) instead of an instance?

You are right, thanks!
