### ISSUE TITLE
Encoder class kwarg is ignored on json serialization

### ISSUE THREAD

**Issue by gustavopcassol** [pydantic/pydantic#4560]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The encoder class is ignored when passed through the `cls` kwarg of the `json` method of `BaseModel`. It is a valid `json.dumps` kwarg that expects an encoder class ([example](https://docs.python.org/3/library/json.html#:~:text=Extending%20JSONEncoder%3A)), but since a default encoder is used when `json`'s `encoder` kwarg is `None`, the encoder class' `default` method is "overwritten" by it.

### Example Code

```Python
from pydantic import BaseModel
from json import JSONEncoder

class MyExoticType:
    pass

class Model(BaseModel):
    x: MyExoticType

    class Config:
        arbitrary_types_allowed = True

class CustomEncoder(JSONEncoder):
    def default(self, o):
        if isinstance(o, MyExoticType):
            return 'exo'
        raise TypeError('not serialisable')

# Raises 'TypeError' instead of properly encoding.
Model(x=MyExoticType()).json(cls=CustomEncoder)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.0.dev0
                 install path: /Users/gustavokrieger/PycharmProjects/pydantic/pydantic
               python version: 3.10.4 (main, Jun 28 2022, 21:27:37) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by gustavopcassol** [comment]
I have an idea of a solution. If you guys agree this is an actual issue, please let me know what I need to do before opening a PR.

**Comment by hramezani** [comment]
Thanks @gustavopcassol for the issue.

We are working on `V2` and probably `json()` will be replaced by [model_dump_json()](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#model-namespace-cleanup).

So, I would suggest waiting for `V2`

**Comment by gustavopcassol** [comment]
Oh, ok. Anyway, if you guys ever look back at this, what I had in mind for a solution was this code:

```python
if encoder or 'cls' not in dumps_kwargs:
    encoder = cast(Callable[[Any], Any], encoder or self.__json_encoder__)
```

Replacing this line:

https://github.com/pydantic/pydantic/blob/60cad30b2cd1dc3aa1858ddf907666e6f3429182/pydantic/main.py#L487

**Comment by dmontagu** [comment]
In v2, we've removed the ability to pass json dumps kwargs directly into `model_json_dumps`, so I think this is no longer relevant.

But I'll note that you should be able to achieve everything that could be achieved with JSON encoders through the new `@field_serializer` or `@model_serializer` decorator. I'm not sure whether we have much documentation for these yet, but either way, there are many tests you can look at using these decorators on the `main` branch.

If there is functionality that you need but can't replicate, please let us know; I think anything that is still not possible should be doable by adding context to serialization (if we haven't already? I'm sure we'll need to eventually..)

Because of the above, I'm going to close this issue now, but feel free to create a new issue if the new approach in v2 doesn't work for you.
