### ISSUE TITLE
AnyUrl field with a default value ends up as str

### ISSUE THREAD

**Issue by thosil** [pydantic/pydantic#4567]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I'm using an AnyUrl field in a class with a default value, but the result is a string instead of an AnyUrl.

### Example Code

```Python
from pydantic import BaseModel, AnyUrl
class C(BaseModel):
    url_a: AnyUrl = "http://localhost"
    url_b: AnyUrl

c = C(url_b="http://localhost")
isinstance(c.url_a, AnyUrl) # False
isinstance(c.url_a, str) # True
isinstance(c.url_b, AnyUrl) # True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /EDITED/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
                     platform: Linux-5.15.0-10047-tuxedo-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @thosil for reporting :+1: 

We are working on V2 let's wait for it and revisit this topic again.

**Comment by thosil** [comment]
Thank you for the quick answer and the awesome job you're doing with this lib.

> This just because default values are not run though validation.
> 
omg, I didn't realize that! This is... confusing. Is it wrote somewhere in the doc? I saw this but it doesn't clearly say that there's no validation on default values:

> pydantic is primarily a parsing library, not a validation library.

but at the beginning of the README.md:

> Data validation using Python type hints.

:thinking: 

On the other hand, what's the proper way to create a default valid value for an AnyUrl field?

**Comment by samuelcolvin** [comment]
There's a `validate_always` config argument, that I think might should trigger validation on the default value.

`AnyUrl` is a bit of a mess, it's going to be rewritten significantly in v2, I think you might be able to use `AnyUrl.build()`, but you'll have to check the code and do some trial and error.

Regarding the word "validate", see https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#im-dropping-the-word-parse-and-just-using-validate

**Comment by thosil** [comment]
You're right, I missed it [in the doc](https://pydantic-docs.helpmanual.io/usage/model_config/#options)

> validate_all
>    whether to validate field defaults (default: False)

(activated by default in BaseSettings btw)

When set to True, a default string value is properly converted as Any(*)Url, exactly what I was looking for.

Many thanks!
