### ISSUE TITLE
Hypothesis Plugin docs aren't clear w.r.t. aliases

### ISSUE THREAD

**Issue by badge** [pydantic/pydantic#4570]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

This is not a bug with Pydantic itself, but the docs on how to use the Hypothesis plugin aren't clear that if a field has an alias, this should be passed as the keyword to `st.builds`, rather than the field name itself.

[I have commited a fix on my fork of Pydantic here](https://github.com/badge/pydantic/commit/cc8f833d81f2678ad7dc85997bcc19bb760d1ec4), but saw the note about PRs when I went to open one.

Note that this example code below isn't guaranteed to print `AssertionError raised` when `test_with_discount_field_name` is called, as Hypothesis may (though unlikely) generate a value for `price` which is valid.

### Example Code

```Python
import typing
from hypothesis import given, strategies as st
from pydantic import BaseModel, Field, PositiveFloat

class Model(BaseModel):
    price: PositiveFloat = Field(alias='Price')


@given(st.builds(Model, Price=st.floats(100, 200)))
def test_with_discount(instance):
    # This test shows how you can override specific fields,
    # and let Hypothesis fill in any you don't care about.
    assert 100 <= instance.price <= 200


@given(st.builds(Model, price=st.floats(100, 200)))
def test_with_discount_field_name(instance):
    # This test shows how you can override specific fields,
    # and let Hypothesis fill in any you don't care about.
    assert 100 <= instance.price <= 200


test_with_discount()


try:
    test_with_discount_field_name()
except AssertionError:
    print('AssertionError raised')
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 2.0.0.dev0
                 install path: /Users/matthew/projects/pydantic/pydantic
               python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:14)  [Clang 12.0.1 ]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for reporting, PR against `main` welcome to update the documentation, we can then backport it to the v1.10 branch.

That way even if that section of docs is re-written we should remember to get it right.

**Comment by sydney-runkle** [comment]
See https://github.com/pydantic/pydantic/pull/8373#issuecomment-1857831617
