### ISSUE TITLE
Typing Union working incorrectly

### ISSUE THREAD

**Issue by sipan17** [pydantic/pydantic#4571]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

We use Pydantic for request validation and we encountered an issue with its logic. For the "Union" type we expect it to parse the values as they are if the type of the value is in the union. In the example below we define a simple union of string and float types. We expect the value 5 to be parsed as float, and the value "5" to be parsed as string. However, in the first case both are parsed as floats, and in the second case, both are parsed as strings. Except for the wrong parsing, the "Union" type is said to ignore the order of the types (https://pydantic-docs.helpmanual.io/usage/types/#unions), but as it is evident in our example, the order changes the operation logic. 
```python
from typing import Union

from pydantic import BaseModel

value_type1 = Union[float, str]

int_value = {'value': 5}
string_value = {'value': "5"}


class Payload1(BaseModel):
    value: value_type1


payload1_int = Payload1(**int_value)
payload1_string = Payload1(**string_value)

print("type = Union[float, str]")
print(type(payload1_int.value))
print(type(payload1_string.value))

value_type2 = Union[str, float]


class Payload2(BaseModel):
    value: value_type2


payload2_int = Payload2(**int_value)
payload2_string = Payload2(**string_value)

print("\ntype = Union[str, float]")
print(type(payload2_int.value))
print(type(payload2_string.value))
```
The output of the script is the following
```python
type = Union[float, str]
<class 'float'>
<class 'float'>

type = Union[str, float]
<class 'str'>
<class 'str'>
```

### Example Code

```Python
from typing import Union

from pydantic import BaseModel

value_type1 = Union[float, str]

int_value = {'value': 5}
string_value = {'value': "5"}


class Payload1(BaseModel):
    value: value_type1


payload1_int = Payload1(**int_value)
payload1_string = Payload1(**string_value)

print("type = Union[float, str]")
print(type(payload1_int.value))
print(type(payload1_string.value))

value_type2 = Union[str, float]


class Payload2(BaseModel):
    value: value_type2


payload2_int = Payload2(**int_value)
payload2_string = Payload2(**string_value)

print("\ntype = Union[str, float]")
print(type(payload2_int.value))
print(type(payload2_string.value))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/sipan/anaconda3/envs/rp/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0]
                     platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Have you tried `smart_union`, it's in the docs.

This behavior (roughly) will become the default in v2.

**Comment by Dumaiu** [comment]
Relevant docs are [here](https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union).  A modified version of your example, @sipan17:

```python
from typing import Union

from pydantic import BaseModel

value_type1 = Union[float, str]

int_value = {'value': 5}
string_value = {'value': "5"}


class Payload1(BaseModel):
    value: value_type1

    class Config: #               👈
        smart_union = True 


payload1_int = Payload1(**int_value)
payload1_string = Payload1(**string_value)

print("type = Union[float, str]")
print(type(payload1_int.value))
print(type(payload1_string.value))

value_type2 = Union[str, float]


class Payload2(BaseModel):
    value: value_type2

    class Config: #               👈
        smart_union = True 
        

payload2_int = Payload2(**int_value)
payload2_string = Payload2(**string_value)

print("\ntype = Union[str, float]")
print(type(payload2_int.value))
print(type(payload2_string.value))
```

Output:
```python
type = Union[float, str]
<class 'float'> #               👈
<class 'str'>

type = Union[str, float]
<class 'str'>
<class 'str'>
```
-----------------------------------
I guess that `float` and `str` have the same coercive priority when it comes to integers, so order matters.  But, by contrast, this works:
```python
from typing import Union
from pydantic import BaseModel

class Payload3(BaseModel):
    value: Union[str, int]

    class Config:
        smart_union = True

payload3_int = Payload3(value=5)
payload3_string = Payload3(value='5')

print("\ntype = Union[str, int]")
print(type(payload3_int.value))
print(type(payload3_string.value))
```
Output:
```python
type = Union[str, int]
<class 'int'> #               👈
<class 'str'>
```

**Comment by dolfinus** [comment]
So you've passing integer to a field which can only be float or str, and pydantic converts it to an expected type (they are not strict). How it is suppose to understand that float is a preferred value type in this case?

**Comment by sipan17** [comment]
Thanks a lot, @samuelcolvin @Dumaiu. Your suggestions actually solve the issue. 

I think there is still an issue with Union type. In the documentation, it is specified that "typing.Union also ignores order when [defined](https://docs.python.org/3/library/typing.html#typing.Union)". However, the order does matter and changes the logic.

**Comment by sipan17** [comment]
@dolfinus changing the float to int does not solve the issue. 5 is still parsed as a string in the first case.
