### ISSUE TITLE
Root validator comes in before required field check

### ISSUE THREAD

**Issue by afallou** [pydantic/pydantic#4572]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using a `@root_validator` along with required fields, the validation of required fields only happens after the root validator.
I'm filing this as a bug, since the [docs](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) state that `pre=False` is the default, in which case the root validator should come in after field-level validation. From my perspective, that should include erroring on missing fields.

### Example Code

```Python
from pydantic import BaseModel, ValidationError, root_validator


class Lizard(BaseModel):
    lizard_type: str
    color: str | None

    @root_validator
    def validate_color(cls, values):
        if values["lizard_type"] == "chamaleon" and values.get("color") is None:
            raise ValidationError("The chamaleon's current color must be specified")

        return values


try:
    Lizard(color="blue")
except ValidationError as e:
    # Here I expect to get:
    #    pet -> Lizard -> lizard_type
    #       field required (type=value_error.missing)
    # instead I get:
    #     KeyError: 'lizard_type'
    # unless the root validator doesn't error
    print(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/adrienfallou/.virtualenvs/provider-engagement-service/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jul 12 2022, 12:45:54) [Clang 13.0.0 (clang-1300.0.27.3)]
                     platform: macOS-12.4-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by afallou** [comment]
On closer inspection, it seems that this happens even without discriminated unions:
```
from pydantic import BaseModel, ValidationError, root_validator


class Lizard(BaseModel):
    # pet_type: Literal['lizard']
    lizard_type: str
    color: str | None

    @root_validator
    def validate_color(cls, values):
        if values["lizard_type"] == "chamaleon" and values.get("color") is None:
            raise ValidationError("The chamaleon's current color must be specified")

        return values


try:
    Lizard(color="blue")
except ValidationError as e:
    # Here I expect to get:
    #    pet -> Lizard -> lizard_type
    #       field required (type=value_error.missing)
    # instead I get:
    #     KeyError: 'lizard_type'
    print(e)

```
which makes me wonder if it's not intended behavior 🤔

**Comment by hramezani** [comment]
Thanks, @afallou for reporting.

`lizard_type` is a required field and you didn't provide any value for that in `Lizard(color="blue")`.
As stated in [root_validator doc](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators), You can change the behavior(to get the required field validation) by using `skip_on_failure=True`. `@root_validator(skip_on_failure=True)`


>As with field validators, "post" (i.e. pre=False) root validators by default will be called even if prior validators fail; this behaviour can be changed by setting the skip_on_failure=True keyword argument to the validator.

**Comment by afallou** [comment]
Thank you @hramezani – I think I had read that part of the doc wrong.
