### ISSUE TITLE
"Unexpected keyword argument" error in system dataclasses with __init__ defined

### ISSUE THREAD

**Issue by davidhao3300** [pydantic/pydantic#4584]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

See example code. In 1.9.0, the code succeeds, while in 1.10.0+, the following error occurs:
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    print(SomeModel(**{"data": {"arg1": 1}}))
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for SomeModel
```

### Example Code

```Python
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class DataClass:
    arg1: int

    def __init__(self, aliased: int):
        self.arg1 = aliased

class SomeModel(BaseModel):
    data: DataClass

print(SomeModel(**{"data": {"arg1": 1}}))
```

Succeeds in 1.9.0, but fails in 1.10.0+

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/ubuntu/strap/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.8 (default, Feb 20 2021, 21:09:14)  [GCC 7.5.0]
                     platform: Linux-5.4.0-1083-aws-x86_64-with-glibc2.27
     optional deps. installed: ['devtools', 'dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I think that's just a limitation of out dataclass implementation, will probably raise an error in v2 too.

**Comment by davidhao3300** [comment]
Was just reviewing old issues I filed - what's the suggestion here? To stop mixing pydantic with dataclasses?

**Comment by samuelcolvin** [comment]
No, to not define a custom init function.

**Comment by PrettyWood** [comment]
Pydantic dataclasses are now much closer to standard ones since it tries to keep the stdlib dataclass untouched and just add validation.
In your example it just doesn't work with stdlib dataclasses

```py
from dataclasses import dataclass

@dataclass
class DataClass:
    arg1: int

    def __init__(self, aliased: int):
        self.arg1 = aliased

DataClass(arg1=1)  # breaks since it needs 'aliased' as kwarg
```

**Comment by davidhao3300** [comment]
Got it, thanks
