### ISSUE TITLE
`mypy` doesn't distinguish between pydantic model instance and the `dict()` output of it.

### ISSUE THREAD

**Issue by maratumba** [pydantic/pydantic#4586]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

`mypy` allows both model instance and its `.dict()` value for instantiation for another model with the field type as the first model.

### Example Code

```Python
from pydantic import BaseModel

class SomeModel(BaseModel):
    some_field: str

class SomeOtherModel(BaseModel):
    some_model: SomeModel

some_model_instance = SomeModel(some_field="foo")
some_other_model_instance = SomeOtherModel(some_model=some_model_instance.dict())
# mypy doesn't complain about this, even with `--strict`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/user/some-project/.direnv/python-3.10.4/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Sep  5 2022, 15:56:37) [Clang 13.1.6 (clang-1316.0.21.2)]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I think that's correct since `SomeOtherModel(some_model=my_dict)` might well be valid.
