### ISSUE TITLE
Incorrect coercion of dict items with `Mapping` type

### ISSUE THREAD

**Issue by sisp** [pydantic/pydantic#4588]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When a model attribute is declared using the `Mapping` type and a list of tuples (i.e. `dict` items) is passed, the data is not coerced to a builtin `dict` but incorrectly to a list of the keys. When using a `Dict` type instead, it works as expected.

The example code below results in the following error:

```
>       assert repr(m) == "Model(x={'one': 1, 'two': 2}, y={'one': 1, 'two': 2})"
E       assert "Model(x={'on...one', 'two'])" == "Model(x={'on...1, 'two': 2})"
E         - Model(x={'one': 1, 'two': 2}, y={'one': 1, 'two': 2})
E         ?                                 ^     ---       ^^^^
E         + Model(x={'one': 1, 'two': 2}, y=['one', 'two'])
E         ?
```

### Example Code

```Python
from typing import Any, Dict, Mapping

from pydantic import BaseModel


def test_typing_coercion_dict_mapping_items():
    class Model(BaseModel):
        x: Dict[Any, Any]
        y: Mapping[Any, Any]

    v = [['one', 1], ['two', 2]]
    m = Model(x=v, y=v)
    assert repr(m) == "Model(x={'one': 1, 'two': 2}, y={'one': 1, 'two': 2})"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
       pydantic compiled: False
            install path: $HOME/dev/pydantic/pydantic
          python version: 3.9.13 (main, Sep  2 2022, 22:36:50)  [GCC 9.4.0]
                platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.31
optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
As discussed on #4589, changing this would be too potentially disruptive to fix in a patch release of V1.10.

Currently lists are not allowed as inputs to `Dict` or (as yet unimplemented) `Mapping` in v2, rendering this issue somewhat moot.

The real question is whether we should provide a flag to allow lists (and list-like types) as input to a dict/mapping? @sisp if you require that, best to create a new "feature request" issue requesting it.
