### ISSUE TITLE
Types ConstrainedList or classes with __origin__ fail with IndexError: tuple out of range

### ISSUE THREAD

**Issue by RafeSacks** [pydantic/pydantic#4591]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hi,

The following fails for me in Python 3.9 and I'm not sure what I can try next. 

```python
>>> from pydantic import ConstrainedList, BaseModel
>>> class ConstrainedListDebug(BaseModel):
...     items: ConstrainedList = None

Traceback (most recent call last):
  [...SNIP...]
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 694, in pydantic.fields.ModelField._type_analysis
IndexError: tuple index out of range
```
This is fine

```python
class ListDebug(list):
    pass

class ConstrainedListDebug(BaseModel):
    items: ListDebug = None
```

This went a bit too deep in to the code base but some process-of-elimination testing narrowed it down to the use of `__origin__`. Adding it in causes the same error as shown above (even if set to `None`).

```python
class ListDebug(list):
    __origin__ = list

class ConstrainedListDebug(BaseModel):
    items: ListDebug = None
```

### Example Code

```Python
from pydantic import ConstrainedList, BaseModel
class ConstrainedListDebug(BaseModel):
     items: ConstrainedList = None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: [REDACTED]\venv\Lib\site-packages\pydantic
               python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.18363-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
This is not documented and not expected to work.

Use`conlist` as documented.

Please use discussions for questions.

**Comment by RafeSacks** [comment]
Using the factory seems to work. Is this all by design?:
```
    from pydantic import conlist, BaseModel

    class ConstrainedListDebug(BaseModel):
        items: conlist(str) = None
```

**Comment by RafeSacks** [comment]
Just to add some context: I was just trying to subclass the `ConstrainedList`. I have the need to create a similar API of datatypes and I've gotten quite far with the pattern where most classes can be used as types directly or "constrained" with args. I was making a specialized (pre-constrained?) array type (e.g. "Int2"). Mine works via the factory as well so I think I can live with it. I'm just explaining how I got there. The simple types work without the factory since the class attributes are supported in the validators and such.
