### ISSUE TITLE
`typing.Union` is not handled properly when the `union types` have the same attributes leading to bad references.

### ISSUE THREAD

**Issue by marcosschroh** [pydantic/pydantic#4595]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using `typing.Union` and the `types` of the Union have the same `attributes`, the class instantiation does not work properly leading to bad references and changing the attributes data types. Using the same code described in the section `Example Code` but with `dataclasses` (replacing `pydantic` with `dataclasses`) it works perfectly fine. 

### Example Code

```Python
import typing
from pydantic import BaseModel


class A1(BaseModel):
    some_attribute: str


class A2(BaseModel):
    some_attribute: int


class B(BaseModel):
    a: typing.Union[A1, A2]


if __name__ == "__main__":
    a1 = A1(some_attribute="name")
    a2 = A2(some_attribute=100)

    b1 = B(a=a1)
    b2 = B(a=a2)

    assert isinstance(b1.a, A1), f"{type(b1.a)} != {A1}"
    print(b2.a)  # This is orint some_attribute='100' CHANGING the TYPE!!!
    assert isinstance(b2.a, A2), f"{type(b2.a)} != {A2}"
    # AssertionError: <class '__main__.A1'> != <class '__main__.A2'>
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/marcosschroh/Projects/dataclasses-avroschema/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 17:02:14)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
This is a known problem, there are lots of other issues about unions coercing the first possible type.

Have you tried `SmartUnion`?

Also, unions will get smarter in v2.
