### ISSUE TITLE
Field add not_allow_empty option

### ISSUE THREAD

**Issue by fatelei** [pydantic/pydantic#4598]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Sometimes, empty string is not expect. `Field` can add an argument `blank=True/False` like `django CharField`, when blank is False, empty string is not allowed, otherwise it is allowed.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by fatelei** [comment]
currently, i use `min_length=1` to implement it

**Comment by samuelcolvin** [comment]
If we added this, it just be an alias of `min_length=1`, perhaps with `strip_whitespace=True` to avoid spaces only.

**Comment by fatelei** [comment]
> strip_whitespace

yes, syntax sugar

**Comment by adriangb** [comment]
This is very easy to add yourself, and will be even easier in V2:

```python
from typing import Annotated

from annotated_types import MinLen

from pydantic import BaseModel

NonEmptyStr = Annotated[str, MinLen(1)]

class Model(BaseModel):
    x: NonEmptyStr

Model(x='a')  # ok
Model(x='')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x
  String should have at least 1 characters [type=string_too_short, input_value='', input_type=str]
"""
```
