### ISSUE TITLE
`decorator.ValidatedFunction`: Allow users to know which `ModelField` an argument relates to

### ISSUE THREAD

**Issue by tombulled** [pydantic/pydantic#4600]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

I'm currently working on a HTTP client library which uses `pydantic` under the hood.
The main concept of the library is to create parameter classes which extend `FieldInfo`, for example:
```python
from typing import Any
from pydantic.fields import FieldInfo
from pydantic.typing import Annotated


class QueryField(FieldInfo):
    pass


class PathField(FieldInfo):
    pass


def Query(*args, **kwargs) -> Any:
    return QueryField(*args, **kwargs)


def Path(*args, **kwargs) -> Any:
    return PathField(*args, **kwargs)


def get_user(
    user_id: Annotated[int, Path()], details: Annotated[str, Query()] = "full"
) -> list:
    ...
```
In the above example, `Query` represents a query parameter and `Path` represents a path parameter (similar to how `fastapi` works).

I need to be able to populate a "request" with the specified values. The `ValidatedFunction` class pydantic uses would be the perfect candidate for supporting this functionality, however there is currently no easy way to match an argument to the `ModelField` it relates to.

Pydantic's `ValidatedFunction` exposes a `build_values` method which allows the user to specify `args` and `kwargs`, and for these to be converted into arguments that can be passed to the constructed model's constructor.

```python
from typing import Any, Dict
from pydantic.decorator import ValidatedFunction

validated_function: ValidatedFunction = ValidatedFunction(get_user, None)

values: Dict[str, Any] = validated_function.build_values((123,), {})
```
```python
>>> values
{'user_id': 123}
```

The model can be instantiated easily using the `init_model_instance` method, as is used by the `call` method:

```python
from pydantic import BaseModel

model: BaseModel = validated_function.init_model_instance(123)
```
```python
>>> model
GetUser(user_id=123, v__duplicate_kwargs=None, details='full', args=None, kwargs=None)
```

At this point I'd love to be able to get the arguments as a `Dict[str, Any]` so that I can cross-reference the argument with the `ModelField` it relates to. Importantly, it'd be nice to be aware of default values as well.

Unfortunately, Pydantic currently keeps all of the logic that determines the `args` and `kwargs` to pass to the function in the `execute` method. However, this raises the question, what if the user (such as myself) never wants to execute the function? One approach a user might take to achieving this would be to create a wrapper that intercepts the generated arguments, for example:
```python
from functools import wraps

@wraps(get_user)
def wrapper(*args, **kwargs):
    print("Intercepted arguments:", args, kwargs)

    return get_user(*args, **kwargs)

validated_function_for_wrapper: ValidatedFunction = ValidatedFunction(wrapper, None)

_ = validated_function_for_wrapper.call(123)
```
```python
>>> _ = validated_function_for_wrapper.call(123)
Intercepted arguments: () {'user_id': 123}
```

However, the above example shows that Pydantic doesn't pass the default values to the function. Instead, it relies on the function knowing what its defaults are.

Ultimately, what'd be really awesome would be if `ValidatedFunction` had a `prepare_arguments` (or otherwise named) method. This method would ideally work in the following way:
```python
>>> validated_function_for_wrapper.prepare_arguments(123)
{"user_id": 123, "details": "full"}
```

The user could interrogate the model, however it is currently polluted with `args`, `kwargs` and `v__xxx` fields. I've noticed that this is listed as a temporary solution in need of improving (ref: #1205). A hacky solution would be:
```python
arguments: Dict[str, Any] = {
    key: value
    for key, value in model.dict().items()
    if not key.startswith("v__") and key not in ("args", "kwargs")
}
```
```python 
>>> arguments
{'user_id': 123, 'details': 'full'}
```
However, the above solution is not ideal.

#### Conclusion
As the `ValidatedFunction` class is shaping up to be an integral part of my library, I am more than happy to do the leg work for this :slightly_smiling_face: 

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for the question.

Add you may know, we're in the process of completely rewriting pydantic for V2, see https://pydantic-docs.helpmanual.io/blog/pydantic-v2/.

As a result of the rewrite I think `ValidatedFunction` will be replaced by a generic `validate` decorator which can be use to add validation to:
* Functions
* Dataclasses
* TypedDicts
* Named tuples
* Tuples

I've already built a validator in pydantic-core specifically to process arguments, see [here](https://github.com/pydantic/pydantic-core/blob/04775e35d7ec65d2694fd08125af7ec7f9330726/tests/validators/test_arguments.py#L761) for a rough implementation of `validate` using it.

I'm not sure at this point what the best approach would be to help you, maybe you could check out the above links and let me know what you think?

**Comment by samuelcolvin** [comment]
Pydantic v1.10 is receiving bug fixes only at this point so won't be changed.

**Comment by tombulled** [comment]
Thanks for your reply, and all of your hard work - Pydantic is awesome and I cannot rave about it enough!

As Pydantic v1.10 is only receiving bug fixes at the moment, I completely understand there's no point making any changes on this front, only for them to be superseded by a v2 release.

For the time being, I'll rock a modified `ValidatedFunction` in my code base, then will look to migrate to Pydantic v2 once it's officially released :slightly_smiling_face:

**Comment by tombulled** [comment]
Closing the issue as not planned

**Comment by tombulled** [comment]
Closing the issue as not planned

**Comment by tombulled** [comment]
Closing the issue as not planned

**Comment by samuelcolvin** [comment]
Best thing would be to look at v2 at the first alpha and confirm it can do what you want.
