### ISSUE TITLE
validate_arguments unexpected behavior

### ISSUE THREAD

**Issue by yusufsali61** [pydantic/pydantic#4601]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Below code gives the error:

```
Traceback (most recent call last):
  File "C:\Users\yusuf.sali\Desktop\Yusuf_Sali_Personal\Learning\fastapi\deneme.py", line 13, in <module>
    print(adder("yusuf", "10"))
  File "pydantic\decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic\decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
    
  File "pydantic\decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
    
  File "C:\Users\yusuf.sali\Desktop\Yusuf_Sali_Personal\Learning\fastapi\deneme.py", line 9, in adder
    return a + " " + b if T == str else a + b
TypeError: can only concatenate str (not "int") to str
```

Shouldn't it just print yusuf10 to console?  

### Example Code

```Python
from typing import TypeVar

from pydantic import validate_arguments

T = TypeVar("T", int, str)


@validate_arguments
def adder(a: T, b: T) -> T:
    return a + b


print(adder("yusuf", "10"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: C:\Users\yusuf.sali\Miniconda3\envs\fastapi_learning\Lib\site-packages\pydantic
               python version: 3.10.6 | packaged by conda-forge | (main, Oct  7 2022, 20:14:50) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
[Pydantic may cast input data](https://pydantic-docs.helpmanual.io/usage/models/#data-conversion) and it casts the second arg `"10"` to `int` when initializing the model. That's why you will get this error.
If you call your function by a string like `"test"` it will be fine.

I am not sure the casting behavior is right. @samuelcolvin may have more clear answer here.

BTW, the if condition in your function(`if T == str`) is always `False`. you can replace it with `if isinstance(a, str)`

**Comment by yusufsali61** [comment]
> [Pydantic may cast input data](https://pydantic-docs.helpmanual.io/usage/models/#data-conversion) and it casts the second arg `"10"` to `int` when initializing the model. That's why you will get this error. If you call your function by a string like `"test"` it will be fine.
> 
> I am not sure the casting behavior is right. @samuelcolvin may have more clear answer here.
> 
> BTW, the if condition in your function(`if T == str`) is always `False`. you can replace it with `if isinstance(a, str)`

Thanks for your reply ramezani. (`if T == str`) was just for seeing the result, I forgot to delete it. And I also guessed the casting behavior but the reason I post this issue is that why doesn't it simply let the function to execute when there is actually no problem? I think it should be fixed. Before casting, maybe there should be a type checking to decide which type to give priority over others. Or a more robust mechanism maybe. At the end, isn't this error a problem with pydantic that needs to be fixed?

**Comment by samuelcolvin** [comment]
We don't claim to support typevar like this, it would require a significant change since the way `b` is validated works be effected by the value of `a`.

You could achieve something like this with a validator function, but I don't think it's something we intend to support in future.

I guess the reason for it is that T is being interpretted as `Union[int, str]` which will cast to an int of possible. You might have luck with `smart_union` behavior.
