### ISSUE TITLE
[Feature Request] Structural Discriminated Unions

### ISSUE THREAD

**Issue by enezhadian** [pydantic/pydantic#4604]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Pydantic currently has support for Discriminated Unions (a.k.a. Tagged Unions), which allows validating a field against one of the submodels specified in the union based on a "discriminator" field. Here is how this feature currently works:
```python
from typing import Literal, Union
from pydantic import BaseModel, Field

class Square(BaseModel):
    name: Literal["square"]
    side: float

class Circle(BaseModel):
    name: Literal["circle"]
    radius: float

class Frame(BaseModel):
    shape: Union[Square, Circle] = Field(..., discriminator="name")

Frame.validate({"shape": {"name": "square", "side": 1}}) # Returns Frame(shape=Square(name='square', side=1.0))
Frame.validate({"shape": {"name": "circle", "radius": 1}}) # Returns Frame(shape=Circle(name='circle', radius=1.0))
```

I would like to propose to extend this functionality to support 'structural' discrimination, i.e. automatically detect the submodel to use for validation based on the definitons of submodels without requiring a discriminator field. Something like this:
```python
class Square(BaseModel):
    side: float

class Circle(BaseModel):
    radius: float

class Frame(BaseModel):
    shape: Union[Square, Circle] = Field(..., discriminated=True) # Somehow specify one of the submodels needs to be used

Frame.validate({"shape": {"side": 1}}) # Should return Frame(shape=Square(side=1.0))
Frame.validate({"shape": {"radius": 1}}) # Should return Frame(shape=Circle(radius=1.0))
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by PrettyWood** [comment]
You can with `smart_union` even though it doesn't "detect" per se beforehand

**Comment by samuelcolvin** [comment]
Also tagged unions are much more powerful in v2, you can use any key or path or a function as the descriminator.
