### ISSUE TITLE
Generic argument cannot be used a discriminator

### ISSUE THREAD

**Issue by tibbe** [pydantic/pydantic#4606]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Using a `TypeVar`, instantiated to a `Literal` doesn't work if the `TypeVar` is used as the type of a discriminator field (see code below). Error:

```
$ python3
Python 3.9.13 (main, Sep 12 2022, 14:27:42) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import repro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tibbe/work/benetics/backend/repro.py", line 24, in <module>
    class Container(BaseModel):
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 639, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 753, in pydantic.fields.ModelField.prepare_discriminated_union_sub_fields
  File "pydantic/utils.py", line 742, in pydantic.utils.get_discriminator_alias_and_values
pydantic.errors.ConfigError: Field 'type_' of model 'A' needs to be a `Literal`
```

### Example Code

```Python
repro.py:

from typing import Generic, Literal, TypeVar, Union

from pydantic import BaseModel, Field


T = TypeVar('T')


class Base(Generic[T], BaseModel):
    type_: T


class A(Base[Literal["A"]]):
    pass


class B(Base[Literal["B"]]):
    pass


MyUnion = Union[A, B]


class Container(BaseModel):
    contained: MyUnion = Field(discriminator='type_')
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.9.2
            pydantic compiled: True
                 install path: /Users/tibbe/work/benetics/backend/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Sep 12 2022, 14:27:42)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.6-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by tibbe** [comment]
As a workaround you can give the `TypeVar` a bound of all possible literal values but this breaks abstraction/encapsulation as the base class needs to know of all subclasses:

```py
T = TypeVar('T', bound=Literal['A', 'B'])
```

**Comment by samuelcolvin** [comment]
We don't claim to support discriminated unions with generics, I believe there are other issues which cover this.

Will try to support them in v2, but no guarantee.

Please let me know if there's really no existing issue which describes this and we can reopen this.
