### ISSUE TITLE
Model initialization goes wrong when a field's type is a Union

### ISSUE THREAD

**Issue by codenforcement** [pydantic/pydantic#4607]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I'm developing a project that involves Abstract Syntax Trees, and I use pydantic models to represent ASTs (that's maybe not the best idea, but that's pretty irrelevant to the bug). Recently, I started using `Union`s to split ASTs into categories — such as the category of expressions, statements, etc. — but when I started to use these `Union`s in pydantic models, I noticed an absolutely unpredictable behavior. I tried to reproduce it with an extremely small example:

```python
from __future__ import annotations
from typing import Union
from pydantic import BaseModel

Value = Union[int, str, None]

class AST:
    def compute(self) -> Value:
        raise NotImplementedError()

class ValueAST(AST, BaseModel):
    value: Value

    def compute(self) -> Value:
        return self.value

class PlusAST(AST, BaseModel):
    left: Expr
    right: Expr

    def compute(self) -> Value:
        return self.left.compute() + self.right.compute()

class MinusAST(AST, BaseModel):
    left: Expr
    right: Expr

    def compute(self) -> Value:
        return self.left.compute() - self.right.compute()

class PrintAST(AST, BaseModel):
    value: Expr

    def compute(self) -> Value:
        print(f"Printing the value: {self.value.compute()}")
        return None

Expr = Union[ValueAST, PlusAST, MinusAST]

if __name__ == "__main__":
    PlusAST.update_forward_refs(Expr=Expr)
    MinusAST.update_forward_refs(Expr=Expr)
    PrintAST.update_forward_refs(Expr=Expr)

    program = PrintAST(value=PlusAST(left=ValueAST(value=1), right=ValueAST(value=2)))

    print(program)

    program.compute()
```

The expected output is this:

```
value=PlusAST(left=ValueAST(value=1), right=ValueAST(value=2))
Printing the value: 3
```

However, we are getting this:

```
value=ValueAST(value=None)
Printing the value: None
```

Surprisingly, the `PrintAST` was initialized with a wrong value, i.e., with an instance of `ValueAST` instead of `PlusAST`. I tried to examine the behavior to understand what exactly goes wrong, and it seems that during initialization, assigned attributes are different from passed ones:

```python
...

class PrintAST(AST, BaseModel):
    value: Expr

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        print(f"Kwargs: {kwargs}")
        print(f"Self: {self.__dict__}")

...
```

The output is:

```
Kwargs: {'value': PlusAST(left=ValueAST(value=1), right=ValueAST(value=2))}
Self: {'value': ValueAST(value=None)}
...
```

(I purposefully used `__dict__` instead of `.dict()` to display class names.)

This happens only when a field's type is a union, such as `Expr`. If we change every occurrence of `Expr` with just `AST`, everything works as expected:

```python
from __future__ import annotations
from typing import Union
from pydantic import BaseModel as PydanticBaseModel

Value = Union[int, str, None]

class BaseModel(PydanticBaseModel):
    class Config:
        arbitrary_types_allowed = True

class AST:
    def compute(self) -> Value:
        raise NotImplementedError()

class ValueAST(AST, BaseModel):
    value: Value

    def compute(self) -> Value:
        return self.value

class PlusAST(AST, BaseModel):
    left: AST
    right: AST

    def compute(self) -> Value:
        return self.left.compute() + self.right.compute()

class MinusAST(AST, BaseModel):
    left: AST
    right: AST

    def compute(self) -> Value:
        return self.left.compute() - self.right.compute()

class PrintAST(AST, BaseModel):
    value: AST

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        print(f"Kwargs: {kwargs}")
        print(f"Self: {self.__dict__}")

    def compute(self) -> Value:
        print(f"Printing the value: {self.value.compute()}")
        return None

if __name__ == "__main__":
    program = PrintAST(value=PlusAST(left=ValueAST(value=1), right=ValueAST(value=2)))

    print(program)

    program.compute()
```

The output is:

```
Kwargs: {'value': PlusAST(left=ValueAST(value=1), right=ValueAST(value=2))}
Self: {'value': PlusAST(left=ValueAST(value=1), right=ValueAST(value=2))}
value=PlusAST(left=ValueAST(value=1), right=ValueAST(value=2))
Printing the value: 3
```

It appears that it's only the issue of models, as rewriting the code to use dataclasses instead works as expected:

```python
from __future__ import annotations
from typing import Union
from pydantic.dataclasses import dataclass

Value = Union[int, str, None]

class AST:
    def compute(self) -> Value:
        raise NotImplementedError()

@dataclass
class ValueAST(AST):
    value: Value

    def compute(self) -> Value:
        return self.value

@dataclass
class PlusAST(AST):
    left: Expr
    right: Expr

    def compute(self) -> Value:
        return self.left.compute() + self.right.compute()

@dataclass
class MinusAST(AST):
    left: Expr
    right: Expr

    def compute(self) -> Value:
        return self.left.compute() - self.right.compute()

@dataclass
class PrintAST(AST):
    value: Expr

    def compute(self) -> Value:
        print(f"Printing the value: {self.value.compute()}")
        return None

Expr = Union[ValueAST, PlusAST, MinusAST]

if __name__ == "__main__":
    PlusAST.__pydantic_model__.update_forward_refs(Expr=Expr)
    MinusAST.__pydantic_model__.update_forward_refs(Expr=Expr)
    PrintAST.__pydantic_model__.update_forward_refs(Expr=Expr)

    program = PrintAST(value=PlusAST(left=ValueAST(value=1), right=ValueAST(value=2)))

    print(program)

    program.compute()
```

with the output:

```
PrintAST(value=PlusAST(left=ValueAST(value=1), right=ValueAST(value=2)))
Printing the value: 3
```

As reported, I use Python 3.10, but I used the old union notation and other stuff to make the bug reproducible on older versions.

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
               python version: 3.10.7 (main, Oct  1 2022, 18:06:05) [GCC 7.5.0]
                     platform: Linux-4.15.0-193-generic-x86_64-with-glibc2.27
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Your example is too complex for me to dig into, but the problems with union behaviour is well know and documented both in the docs and many existing issues.

Did you try [Smart Unions](https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union)?
