### ISSUE TITLE
Mutable initialization of underscored private attributes does not properly copy

### ISSUE THREAD

**Issue by erichaydel** [pydantic/pydantic#4608]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When creating a pydantic class with a sunder attribute, the `smart_deepcopy` function is not called. Therefore, the mutable object (such as a list) is shared among members of the class. 
This is confusing behavior since it differs from regular attributes on a model. These fields behave more like legitimate class variables, which isn't well-documented.

### Example Code

```Python
from typing import List
from pydantic import BaseModel


class Model(BaseModel):
    public_list: List[str] = []
    _private_list: List[str] = []


model1 = Model()
model2 = Model()

assert id(model1.public_list) != id(model2.public_list)  # Passes
assert id(model1._private_list) != id(model2._private_list)  # Fails

> Traceback (most recent call last):
>  File "example.py", line 14, in <module>
>    assert id(model1._private_list) != id(model2._private_list)
> AssertionError
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: False
     install path: /usr/local/lib/python3.8/site-packages/pydantic
python version: 3.8.14 (default, Sep 13 2022, 15:03:48)  [GCC 10.2.1 20210110]
platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dsal3389** [comment]
Try to use the `PrivateAttr` object in your model to declare private attributes,
more about it here https://pydantic-docs.helpmanual.io/usage/models/#private-model-attributes


```py
from pydantic import BaseMode, PrivateAttr

class Model(BaseModel):
    public_list: List[str] = []
    _private_list = PrivateAttr(default_factory=list)

# ...code

assert id(model1._private_list) != id(model2._private_list)  # pass
```

**Comment by Kludex** [comment]
None of them are passing on V2, and this is expected.

Pydantic copies the attributes in order to efficiently iterate over its elements for validation.
