### ISSUE TITLE
Storing arbitrary extra data on a model with `Extra.allow`

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#4617]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Currently model values are store in `__dict__`.
Using Extra.allow, this can break the object by overwriting methods/properties such as .dict().

```python
import pydantic

class AccountTaskExpiryDurationFromCompleteAfter(pydantic.BaseModel):
    class Config(pydantic.BaseConfig):
        extra = pydantic.Extra.allow

b = AccountTaskExpiryDurationFromCompleteAfter(dict='yes')
b.dict()
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#TypeError: 'str' object is not callable
```

I propose to change this behaviour - not using `__dict__` but e.g. `__values__`.
To resolve, I propose something along
```python
  def __getattr__(self, name):
    return collections.ChainMap(self.__dict__, self.__values__)[name]
```

Additionally it should be possible to filter the access via getattr to only allow "known" attribute access, limiting the access to additional values gathered by Extra.allow to via `__values__[key]`.

This would improve using pydantic for the (default) additionalProperties:True in json schema models, as it would allow accepting unknown properties without the danger of corrupting the model by overwriting model defined properties.

related: https://github.com/python-lapidary/lapidary/discussions/22

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
nice little headache this, thanks :smile:.

I'll think about it.

**Comment by samuelcolvin** [comment]
See #4850 which is somewhat related.

I don't think we want to stop using `__dict__`, because:
1. We moved to using `__dict__` from `__values__` in the past because of the significant performance improvement, see #712
2. We use `__dict__` in pydantic-core since it works both for pydantic models, and dataclasses
3. It's likely other tools (both knowing about pydantic and not knowing about pydantic) expect `__dict__`

However I completely agree with the principle the your request is based on.

As per the blog post on V2, we do want to enforce namespaces in pydantic models which cannot be messed with, most obviously that's `model_*`, but I want to allow libraries to fine others.

There's also the issue of extra attributes which aren't valid python identifiers, or aren't even strings.

So the question is, how do we allow arbitrary data to be stored on on a model without messing with namespaces?

The only option I can think of right now, is something like #4850 but behind a config flag, but I'm open to other ideas.

(I'll delete your comment from #4887 as it's not relevant there, we can discuss this more here, I've also added this to the V2 milestone and project)

**Comment by commonism** [comment]
I think having the accepted property names in model_extra: Union[set[str],dict[str,str]] might be convenient.

Ideas:

`Config.extra = pydantic.Extra.accept` - do not expose unknown properties via `__getattr__`, just `__getitem__`

`Config.extra: Callable[[str, Any], Tuple[str, Any] ]` - allow a function to validate the key & mangle the value (e.g. patternProperties), `__getattr__` & `__getitem__` as above

`Config.extra: Callable[[str, Any], Tuple[str, str, Any]]` - same, but using the additional return value to cluster the property names - e.g. `model_extra['patternProperties.name'][str]`

**Comment by dmontagu** [comment]
I think it could make sense to do something akin to JSONschema's [patternProperties](https://json-schema.org/understanding-json-schema/reference/object.html#pattern-properties)/[additionalProperties](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties) here. 

In particular, I'm imagining that there could be an `extra_pattern_properties` config field of type `dict[Pattern, type[Any]]`, and an `extra_additional_properties` config field of type `type[Any]` against which extra data gets validated. Maybe this is overkill, but it would at least play nice with JSON schema, and would allow users to prevent their models from getting broken while still being able to receive "extra" data in API requests. (We could do `extra_pattern_properties` only if preferred, and just map the regex `'.*'` to `additionalProperties` in the JSON schema.)

**Comment by commonism** [comment]
That's even more than I asked for and exactly what OpenAPI needs.

I'd go with it.

**Comment by dmontagu** [comment]
Samuel will add a PR to pydantic core that makes it so extra attributes are stored elsewhere

**Comment by dmontagu** [comment]
@commonism I believe we now store extra in `__pydantic_extra__` — what do you think of this?

**Comment by commonism** [comment]
I had a look on commit https://github.com/pydantic/pydantic/commit/517161d61284df9089ddea738df7f9aa236da03e
It's accompanied by model_extra - it's an improvement for sure and will lift some limitations (e.g. `schema: {}`)
As I'm within the requirements of JSON Schema, do you intent to extend this towards patternProperties/additionalProperties within pydantic or shall I go with __pydantic_extra__ and root validators to mangle the properties?

**Comment by samuelcolvin** [comment]
Pydantic-core allows a specific validator for extra data, we currently don't provide a way to set that in pydantic, but pr welcome either now or after V2 release - since it's a new feature and should be completely backwards compatible.

For patterns - use a `model_validator`.

**Comment by dmontagu** [comment]
I'm going to close this now, but @commonism if there's a feature you'd like implemented beyond the new `__pydantic_extra__` stuff (related to `patternProperties` or whatever), feel free to create a new issue for that.
