### ISSUE TITLE
Model schemas for lists of optional values drops optionality

### ISSUE THREAD

**Issue by TNonet** [pydantic/pydantic#4619]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When generating a schema for a model that has a list of optional values (i.e. a list that can contain values or None), the optionality value is not included in the JSON Schema

### Example Code

```Python
from pydantic import BaseModel
from typing import List, Optional, Union

class ListOfOptionalItems(BaseModel):
    a: List[int]
    b: List[Optional[int]]
    c: List[Union[int, None]]
    d: List[Union[int, float]]

ListOfOptionalItems.schema()
{'title': 'ListOfOptionalItems',
 'type': 'object',
 'properties': {'a': {'title': 'A',
   'type': 'array',
   'items': {'type': 'integer'}},
  'b': {'title': 'B', 'type': 'array', 'items': {'type': 'integer'}},
  'c': {'title': 'C', 'type': 'array', 'items': {'type': 'integer'}},
  'd': {'title': 'D',
   'type': 'array',
   'items': {'anyOf': [{'type': 'integer'}, {'type': 'number'}]}}},
 'required': ['a', 'b', 'c', 'd']}

# Which should look like
{'title': 'ListOfOptionalItems',
 'type': 'object',
 'properties': {'a': {'title': 'A',
   'type': 'array',
   'items': {'type': 'integer'}},
  'b': {'title': 'B', 'type': 'array', 'items': {'anyOf': [{'type': 'integer'}, {'type': 'null'}]}},
  'c': {'title': 'C', 'type': 'array', 'items': {'anyOf': [{'type': 'integer'}, {'type': 'null'}]}},
  'd': {'title': 'D',
   'type': 'array',
   'items': {'anyOf': [{'type': 'integer'}, {'type': 'number'}]}}},
 'required': ['a', 'b', 'c', 'd']}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: /.../pypoetry/virtualenvs/.../lib/python3.9/site-packages/pydantic
python version: 3.9.12 (main, May 11 2022, 08:10:09)  [GCC 8.3.0]
platform: Linux-5.4.196-108.356.amzn2.x86_64-x86_64-with-glibc2.28
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I'm not that surprised, optional has had weird meanings in pydantic in the past as it originally meant "optional", not nullable.

Will be fixed in v2, I doubt we'll fix it in v1.10 at this stage.

**Comment by samuelcolvin** [comment]
Realistically, the simplest solution will be to manually edit the schema after generation.

**Comment by TNonet** [comment]
I have been doing that, but I would like to automate it somewhat.

My current planned workaround is to recursively replace the type annotations of  `Optional[X]` with `Union[X, NonePlaceHolder]` before generating the schema, and then post-processing the schema... However, that is quite hacky!

Could a custom JSON Encoder work here?

**Comment by commonism** [comment]
> OpenAPI 3.0 does not have an explicit null type as in JSON Schema,
https://swagger.io/docs/specification/data-models/data-types/

OpenAPI 3.1 has
https://github.com/OAI/OpenAPI-Specification/issues/2244

**Comment by 243f6a8885a308d313198a2e037** [comment]
I ran into the same problem and may found a workaround for this:

* Plan A (incomplete): `pydantic.Field` has `extra` var-keyword argument.
  * Problem: this only works with simple `Optional[T]`, *not with `List[Optional[T]]`* ...
* Plan B (incomplete): Create a custom field type with `__modify_schema__` classmethod, adding `"nullable": true` to schema.
  * Problem: this can generate expected schema, but *invalidates nulls on validation* since it is subclass of `int`, not `Optional[int]` ...
* Plan C: explicitly annotate like `Optional[NullableInt]` to make null values valid.

I think Plan C will be the solution.

Maybe it is better (if possible) to keep using `Optional[T]` as annotation and replace the type information stored in `FieldInfo` once, just before schema generation, to keep mypy silent for existing code.

e.g.

```python
import json
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field
from typing_extensions import Annotated


class NullableInt(int):
    @classmethod
    def __modify_schema__(cls, field_schema: Dict[str, Any]) -> None:
        field_schema["nullable"] = True


class _SampleModel(BaseModel):
    f_int: int

    f_optional_int: Optional[int]  # unexpected result
    f_union_none_int: Union[int, None]  # unexpected result

    # WORKAROUND
    f_optional_int_nullable_A: Optional[int] = Field(..., nullable=True)
    f_optional_int_nullable_B: NullableInt
    f_optional_int_nullable_C: Optional[NullableInt] = Field(...)

    f_list_int: List[int]

    f_list_optional_int: List[
        Annotated[Optional[int], Field(nullable=True)]
    ]  # unexpected result

    f_list_optional_int_nullable: List[Optional[int]]

    # NOTE this is incorrect: list is not nullable
    # f_list_optional_int_nullable_A: List[Optional[int]] = Field(nullable=True)

    # WORKAROUND
    f_list_optional_int_nullable_B: List[NullableInt]  # correct schema, cannot validate
    f_list_optional_int_nullable_C: List[Optional[NullableInt]]


def test_json_schema() -> None:
    json_schema = json.loads(_SampleModel.schema_json())
    print(json_schema)
    assert json_schema == {
        "title": "_SampleModel",
        "type": "object",
        "properties": {
            "f_int": {"title": "F Int", "type": "integer"},
            "f_optional_int": {"title": "F Optional Int", "type": "integer"},
            "f_union_none_int": {"title": "F Union None Int", "type": "integer"},
            "f_optional_int_nullable_A": {
                "title": "F Optional Int Nullable A",
                "nullable": True,
                "type": "integer",
            },
            "f_optional_int_nullable_B": {
                "title": "F Optional Int Nullable B",
                "nullable": True,
                "type": "integer",
            },
            "f_optional_int_nullable_C": {
                "title": "F Optional Int Nullable C",
                "nullable": True,
                "type": "integer",
            },
            "f_list_int": {
                "title": "F List Int",
                "type": "array",
                "items": {"type": "integer"},
            },
            "f_list_optional_int": {
                "title": "F List Optional Int",
                "type": "array",
                "items": {"type": "integer"},
            },
            "f_list_optional_int_nullable": {
                "title": "F List Optional Int Nullable",
                "type": "array",
                "items": {"type": "integer"},
            },
            "f_list_optional_int_nullable_B": {
                "title": "F List Optional Int Nullable B",
                "type": "array",
                "items": {"type": "integer", "nullable": True},
            },
            "f_list_optional_int_nullable_C": {
                "title": "F List Optional Int Nullable C",
                "type": "array",
                "items": {"type": "integer", "nullable": True},
            },
        },
        "required": [
            "f_int",
            "f_optional_int_nullable_A",
            "f_optional_int_nullable_B",
            "f_optional_int_nullable_C",
            "f_list_int",
            "f_list_optional_int",
            "f_list_optional_int_nullable",
            "f_list_optional_int_nullable_B",
            "f_list_optional_int_nullable_C",
        ],
    }

    # (Failure B)
    # > E   pydantic.error_wrappers.ValidationError: 2 validation errors for _SampleModel
    # > E   f_optional_int_nullable_B
    # > E     none is not an allowed value (type=type_error.none.not_allowed)
    # > E   f_list_optional_int_nullable_B -> 1
    # > E     none is not an allowed value (type=type_error.none.not_allowed)

    _SampleModel(
        f_int=12,
        f_optional_int_nullable_A=None,
        # f_optional_int_nullable_B=None,  # fails! (Failure B)
        f_optional_int_nullable_B=12,
        f_optional_int_nullable_C=None,
        f_list_int=[12],
        f_list_optional_int=[12, None],
        f_list_optional_int_nullable=[12, None],
        # f_list_optional_int_nullable_B=[12, None],  # fails! (Failure B)
        f_list_optional_int_nullable_B=[12],
        # f_list_optional_int_nullable_C=[12, None],  # mypy warns but works
        # > List item 0 has incompatible type "int"; expected "Optional[NullableInt]"  [list-item]mypy(error)
        f_list_optional_int_nullable_C=[NullableInt(12), None],  # no error!
    )
```

**Comment by TNonet** [comment]
Thank you @243f6a8885a308d313198a2e037!

I will look into that!

**Comment by dmontagu** [comment]
I'm going to close this now as this is fixed in v2 and as Samuel mentioned, we are trying to avoid splitting our attention between v2 and bugfixes for v1 that have already been eliminated in v2.
