### ISSUE TITLE
Positional-only parameters are only supported in Python 3.8 and greater

### ISSUE THREAD

**Issue by Sanix-Darker** [pydantic/pydantic#4623]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Am using the last release of pydantic in a codebase but, after a bump from python3.10.6 to python3.10.7, am getting this error :
 
![Screenshot from 2022-10-14 12-04-35](https://user-images.githubusercontent.com/22576758/195820928-8cc63873-fde8-4dff-b4d8-83290c544769.png)

From the [pep-0570](https://peps.python.org/pep-0570/).

So this is a [known issue](https://github.com/python/mypy/issues/13627) and has been fixed on the last release of mypy 0.981 from https://github.com/python/mypy/pull/13500 !

So i was wondering if it's possible to open a PR and bump mypy version for pydantic just to fix that issue ? 🙏🏽 

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/dk/ACTUALC/toucantoco/laputa/env/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0]
                     platform: Linux-5.14.0-1051-oem-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
pydantic doesn't have mypy as a dependency, you can install whichever version you like.

We do test against some specific versions, but shouldn't affect which versions you can install.

**Comment by Sanix-Darker** [comment]
> pydantic doesn't have mypy as a dependency

@samuelcolvin i may be wrong but it looks like it's on requirements... and it's pinned here https://github.com/pydantic/pydantic/blob/main/requirements/linting.txt#L38 🤔 ?
