### ISSUE TITLE
Coercion to Custom Wrapper Type

### ISSUE THREAD

**Issue by dan-fritchman** [pydantic/pydantic#4625]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Love the library, thanks for all of your work on it.  
This is more of a "is this a feature question" than a "feature request".  

Pydantic has many great conversions and coercions among standard library types.  
If possible I would like to make use of them in a *wrapper type*, or at least its constructor.  

This should convey the gist: 

```python
from enum import Enum
from decimal import Decimal
from pydantic.dataclasses import dataclass

class Prefix(Enum):
    # Metric / SI Prefixes
    NANO = -9
    MICRO = -6
    MILLI = -3
    UNIT = 0  # No prefix
    # ... lots of other SI prefixes ...

@dataclass
class Prefixed:
    # SI-Prefixed Number
    number: Decimal  # Numeric Portion
    prefix: Prefix = Prefix.UNIT  # Enumerated SI Prefix. Defaults to unity.

@dataclass
class HasPrefixed:
    # A dataclass with a Prefixed attribute
    p: Prefixed

# So this works:
HasPrefixed(Prefixed(11))

@dataclass
class HasDecimal:
    # A dataclass with a Decimal attribute
    d: Decimal

# And this works too:
HasDecimal(11)

# Now the question:
# Can we route this `int` through *both* the `Prefixed` and `Decimal` constructors somehow?
HasPrefixed(11)  # Fails
```

This fails with: 

```
  instance of Prefixed, tuple or dict expected (type=type_error.dataclass; class_name=Prefixed)
```

Alternately stated, I'd like to get that literal `11` piped through both the `Decimal` and `Prefixed` constructors. 

Part of the idea is that there will be *many* different classes like `HasPrefixed`, and I'd like to embed the conversion in the `Prefixed` class so that they each don't need to. I've tried a `BaseModel` and custom `validator`s version as well, to no better success, and think the `dataclass` version shows it more clearly. 

Is something like this possible? 

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
You want custom data types: https://pydantic-docs.helpmanual.io/usage/types/#custom-data-types.

Please use discussions for questions in future.
