### ISSUE TITLE
Nested class with a non-unique name results in a KeyError

### ISSUE THREAD

**Issue by straygar** [pydantic/pydantic#4628]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have seen a related issue (https://github.com/pydantic/pydantic/issues/1912) where a fix seems to have been merged 2 years ago, but this issue still occurs to me on the newest Pydantic version.

After running the reproducible example (see below), I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 675, in pydantic.main.BaseModel.schema_json
  File "pydantic/main.py", line 664, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 186, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 924, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 922, in pydantic.schema.field_singleton_schema
KeyError: <class '__main__.Params'>
```

### Example Code

```Python
from pydantic import BaseModel
from pydantic.dataclasses import dataclass

@dataclass  # verified that it makes no difference whether this is a dataclass or BaseModel
class Foo:
  @dataclass
  class Params:
      foo: str = 'default'
  params: Params = Params()

@dataclass
class Barr:
  @dataclass
  class Params:
      barr: str = 'default'
  params: Params = Params()

class Bazz(BaseModel):
  foo: Foo
  barr: Barr

Bazz.schema_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
python version: 3.8.2 (default, Jun  8 2021, 11:59:35)  [Clang 12.0.5 (clang-1205.0.22.11)]
platform: macOS-11.6.1-arm64-arm-64bit
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for reporting, you can work around this by making `Foo`, `Foo.Param`, `Barr`, `Barr.Params` into models rather than dataclasses.

Realistically, this won't be changed or fixed until pydantic V2.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
