### ISSUE TITLE
mypy plugin allow omitting nullable fields when instantiating with init_typed=True

### ISSUE THREAD

**Issue by anentropic** [pydantic/pydantic#4634]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

In this case:

```python
class MyModel(BaseModel):
   required_field: int
   optional_field: Optional[str]

instance = MyModel(required_field=123)
```

With mypy plugin configured:
```toml
[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
```

I get mypy error:
```
error: Missing named argument "optional_field" for "MyModel"
```

I find the `init_typed=True` config useful to catch instantiations with invalid args (e.g. a common mistake it found in my current codebase it passing an `Optional[something]` into a `something` field)

But it's also a bit too strict, e.g. the case above should be fine, I'd like to not have to pass explicit `None` for all the optional fields when instantiating.

Related, but it'd also be nice to have a separate alternative config setting something like `init_coercibly_typed` where the annotated init arg type for say `time` field is `time | str` like the [model accepts](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) (instead of just `time`)... so I can get the benefit of `init_typed` arg checking but without having to do all the type coercions in my code that Pydantic already knows how to do.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Yup, not surprised. Best solution is to use `optional_field: Optional[str] = None`.

Behaviour in V2 will match what mypy is saying and how dataclasses work anyway.

Since v1.10 is only receiving bug fixes, I don't think we change this now.

**Comment by anentropic** [comment]
Thanks

Any thoughts about this part:
> Related, but it'd also be nice to have a separate alternative config setting something like init_coercibly_typed where the annotated init arg type for say time field is time | str like the [model accepts](https://pydantic-docs.helpmanual.io/usage/types/#datetime-types) (instead of just time)... so I can get the benefit of init_typed arg checking but without having to do all the type coercions in my code that Pydantic already knows how to do.

is it worth my opening a separate issue for that to track as a feature request for v2?

**Comment by samuelcolvin** [comment]
One of the things already planned for V2 is a complete list of what types are allowed to what types are allowed to each field type, we should be able to just that information in:
* Mypy
* Signature generation
* Hypothesis
* Pycharm plugin
* Docs

I'll by creating an issue to discuss this tomorrow (meant to do it today but didn't manage), so probably no point in creating another issue.

**Comment by anentropic** [comment]
sounds great!

**Comment by samuelcolvin** [comment]
See #4680
