### ISSUE TITLE
Class validator in Union type field is not invoked when None value is passed

### ISSUE THREAD

**Issue by AntonOvsyannikov** [pydantic/pydantic#4636]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am trying to parse not well known data structure with pydantic, so some models can be bad and will not correspond input data. To solve the idea is to declare fallback class Unknown, and use it in Union type for field, which can be parsed incorrectly.
```
class Model(BaseModel):
  foo: int | Unknown 
```
This means I expect int, but if no - fall back to Unknown should occur.

The problem is that it works well, except None values, i.e. if I not expect None, I'd like to fall back to Unknown, but this not happens, pydantic reports validation error.

### Example Code

```Python
from pydantic import BaseModel


class Unknown:
    def __init__(self, v):
        self.v = v

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        return cls(v)


class Model(BaseModel):
    foo: int | Unknown


print(Model.parse_obj({'foo': 1}))  # foo=1

print(Model.parse_obj({'foo': 'bar'}))  # foo=<__main__.Unknown object>

print(Model.parse_obj({'foo': None}))  # ValidationError: foo: none is not an allowed value
# ISSUE ! Expected foo=<__main__.Unknown object>
```

### Python, Pydantic & OS Version

```Text
> python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.2
            pydantic compiled: True
                 install path:... 
               python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]       
                     platform: Windows-10-10.0.22000-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Yup, this is know behavior, try using `validate_always`, that definitely used to solve this problem.

This is pretty baked into pydantic v1 do don't be changed before v2, it's fixed in v2.
