### ISSUE TITLE
Two instances of two SecretStr subclasses are not the same 

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#4651]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

That's a regression from 1.9 where the code snippet works fine.

The reason is this change in `SecretField`:

```py
# v1.10
class SecretField(abc.ABC):
    ...

    def __eq__(self, other: Any) -> bool:
        return isinstance(other, self.__class__) and self.get_secret_value() == other.get_secret_value()
```

```py
# v1.9
class SecretStr:
    ...
   def __eq__(self, other: Any) -> bool:
        return isinstance(other, SecretStr) and self.get_secret_value() == other.get_secret_value()
```

### Example Code

```Python
import pydantic


class SecretOne(pydantic.SecretStr):
    ...


class SecretTwo(pydantic.SecretStr):
    ...


def test_eq():
    assert SecretOne("secret") == SecretTwo("secret")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/xxx/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, May 25 2022, 10:42:02)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.6-arm64-arm-64bit
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I would argue it could be seen as a correction, not a regression.

There's nothing that says instances of two different classes should ever be equal.

But I agree it's unfortunate that it changed in a minor release, sorry.

I don't intend to change this behaviour. You can always implement your own custom `__eq__` method if you like.

**Comment by chbndrhnns** [comment]
I would argue from the observable behaviour point of view.

`SecretStr` used to be a string type. For a string, it does not matter how often you subclass it, the value is what matters for equality. Changing this observable behaviour is indeed unfortunate.

Now, `SecretStr` implements `SecretField` and no longer `str`. I do understand that in this case,  you do not want to keep the str semantics in this case, either.
