### ISSUE TITLE
'issubclass() arg 1 must be a class' with generic list 

### ISSUE THREAD

**Issue by rafalkrupinski** [pydantic/pydantic#4652]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

issubclass fails on when the type checked is a generic container

### Example Code

```Python
import pydantic

class MyModel(pydantic.BaseModel):
    pass

issubclass(list, pydantic.BaseModel)
# False
issubclass(list[MyModel], pydantic.BaseModel)
# TypeError: issubclass() arg 1 must be a class
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: False
                 install path: /home/matte/.cache/pypoetry/virtualenvs/gsmtasks-client-enuYBuiM-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
                     platform: Linux-5.10.0-19-amd64-x86_64-with-glibc2.31
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
this is just python, it's not specific to pydantic.

**Comment by rafalkrupinski** [comment]
Is it a good work-around? (works for me so far - with the generic list)
```python
pydantic.BaseModel in inspect.getmro(typ)
```

**Comment by samuelcolvin** [comment]
no, you're better to use `typing_extensions.get_origin`.

**Comment by rafalkrupinski** [comment]
But I don't know if it's a generic class there. Could be str

**Comment by samuelcolvin** [comment]
Then you'll need to write some more complex logic 😀.
