### ISSUE TITLE
Add approximate equality

### ISSUE THREAD

**Issue by Besler** [pydantic/pydantic#4657]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Loving pydantic, I wanted to _float_ the idea of an approximate equal operator in `BaseModel`, inspired by Rust's [approx](https://docs.rs/approx/latest/approx/) crate.

# Example
```python
from pydantic import BaseModel

class Foo(BaseModel):
    id: int
    number: float

a = Foo(id=1, number=0.3)
b = Foo(id=2, number=0.1 + 0.2)
assert (0.1 + 0.3 == 0.3) == False
assert (a == b) == False
assert a.isclose(b) # proposed interface
```

This then extends to nested models and the like.

# Why
A standard use case is to have a bunch of `BaseModel`s that relate somehow. Just for unit testing, I have to add custom `isclose` methods for each class if they have float members. This becomes burdensome and error prone. Abstracting it would be very helpful.

# Possible Solutions
## [PEP 485](https://peps.python.org/pep-0485/) Style
This defines an `isclose` method for the `math` package and adds a requirement for how to do relative precision arithmetic. An `isclose` class method could be added to `BaseModel` allowing floating point comparison.

```python
import math

class BaseModel:

    ....

  def isclose(
    self,
    other: Self,
    rel_tol: double = 1e-09,
    abs_tol: double = 0.0,
  ) -> bool:
    is_model_close = True
      
    for member in self:  # pseudo code
      self_member = getattr(self, member)
      other_member = getattr(other, member)
    
      # Order of operations:
      #    1) member.isclose (BaseModel, numpy)
      #    2) type check w/ math library (standard types supported by math)
      #    3) __eq__ operator (default)
      this_member_is_close = True
      if hasattr(member, 'isclose`) and callable(getattr(member, 'isclose')):
        this_member_is_close = self_member.isclose(
          other_member,
          rel_tol=rel_tol,
          abs_tol=abs_tol,
        )
      elif isinstance(member, (float,)):
        this_member_is_close = math.isclose(
          self_member,
          other_member,
          rel_tol=rel_tol,
          abs_tol=abs_tol,
         )
      else:
        this_member_is_close = self_member == other_member
            
      is_model_close &= this_member_is_close
  
    return is_model_close
```

**Advantages**
- Pythonic
- Arithmetic already handled by existing `isclose` method

**Disadvantages**
- Maybe slow because of branching (and speed of `isinstance`, `callable`, `hasattr`?)
- `numpy` uses `rtol`, `atol` while `math` uses `rel_tol`, `abs_tol`, requiring additional logic for `numpy`
- Allows members to have their own definition of `isclose`, which may not be consistent.
- Handling of `inf`, `-inf`, and `NaN` is different betwen `math` and `numpy`

One would probably have to decide what is to be supported out of the box (e.g. `numpy`, `math::float`) and make everyone else implement `isclose` on their most abstract model.

Ideally Python itself would have a `isclose` method across `PyObject`, but that's an insane PEP to propose.

## Rust [approx](style)
Rust macros are used to define some meta programming using a `#derive` method such that if the members have a `PartialEq` method, then they can be compared using relative precision. The equivalent in Python would be probably be python decorators, but that gets messy.

# Proposal
Does the `isclose` solution seem possible and scalable?

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Much enjoying the "float" pun, but my instinct is that this doesn't belong inside pydantic. You could implement it as either a function or base class.

If you create a package, happy to link to it from the docs.
