### ISSUE TITLE
Multiplying timedelta by sign causes issues due to precision

### ISSUE THREAD

**Issue by RafeSacks** [pydantic/pydantic#4659]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I noticed the parse_duration function was not round-tripping a value in a test and narrowed it down to the sign multiplication on line 246 in datetime_parse.py:
```python
    kw_ = {k: float(v) for k, v in kw.items() if v is not None}

    return sign * timedelta(**kw_)
```

Multiplying only the day fixed the issue, but in further testing I noticed the day isn't always there. The following passes my tests. If there is a more elegant way, please let me know.
```python
    kw_ = {k: float(v) for k, v in kw.items() if v is not None}
    if "days" in kw_:
        kw["days"] *= sign
    else:
        kw["seconds"] *= sign
    return timedelta(**kw_)
```

Demonstration:
Reproduction value: `'-P1DT0H0M0.000001S'` 
Using a break point and interactive shell at the line. Note it wraps to the second day and is not equal if serialized again.
```python
>>> kw
{'days': '1', 'hours': '0', 'minutes': '0', 'seconds': '0.000001'}
>>> kw_
{'days': 1.0, 'hours': 0.0, 'minutes': 0.0, 'seconds': 1e-06}
>>> datetime.timedelta(**kw_)
datetime.timedelta(days=1, microseconds=1)
>>> result = sign * datetime.timedelta(**kw_)
>>> result
datetime.timedelta(days=-2, seconds=86399, microseconds=999999)
>>> import pydantic.json
>>> pydantic.json.timedelta_isoformat(result)
'-P2DT23H59M59.999999S'
```
With the fix, the expected day is preserved and serialization works round-trip
```python
>>> kw_["days"] *= sign
>>> kw_
{'days': -1.0, 'hours': 0.0, 'minutes': 0.0, 'seconds': 1e-06}
>>> result = datetime.timedelta(**kw_)
>>> result
datetime.timedelta(days=-1, microseconds=1)
>>> import pydantic.json
>>> pydantic.json.timedelta_isoformat(result)
'-P1DT0H0M0.000001S'
```

If I can slide a potential improvement in here...? While running hypothesis testing I found a large value results in an `OverflowError` rather than a `ValueError` which would cause it to be caught as a validation issue. I'm not sure how you feel about this, but here is a snippit if interested:
Using `'86400000000000.000000'`
```python
    try:
        return timedelta(**kw_)
    except OverflowError as err:
        raise ValueError(f"Failed to parse duration due to OverflowError: {err}")
```
results in:
```python
ValueError: Failed to parse duration due to OverflowError: days=1000000000; must have magnitude <= 999999999
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: S:\dev\git\python-universal-properties\venv\Lib\site-packages\pydantic
               python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.18363-SP0
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for the contribution.

We won't be changing this in v1 as it's in maintenance only state now.

Best to check if the functionality is correct on v2. If you find a problem feel free to create a new issue.

**Comment by RafeSacks** [comment]
Hi, how do I find v2? I don't see a branch and `1.10.2` is the highest I've found.

**Comment by samuelcolvin** [comment]
Main will be v2, but most of the work so far is in #4516 which I intend to merge this week.

**Comment by samuelcolvin** [comment]
#4516 is merged into `main`, so you can just look there or in pydantic-core @RafeSacks.
