### ISSUE TITLE
V2: Strict mode for types defined in python

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4664]
See [the "strict mode" section of the blog post](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#strict-mode).

#4516 implements types for all/most of the types supported in V1.

But it doesn't touch the issue of "strict mode" at all. We need to:
* modify all types defined in pydantic to make them work correctly in strict mode
* add thorough tests for these

pydantic-core can switch from strict to lax mode at validation time, it doesn't require separate validators, however unfortunately I very much doubt that will be possible in pydantic - many of the schemas will need to be different for strict and lax mode.

I guess we define models as strict or lax, then add class methods:
* `model_lax()` which creates a lax version of the model
* `model_strict()` which creates a strict version of the model

The other option is to build (or optionally) build (perhaps lazily) two validators for a model.

**Comment by adriangb** [comment]
>  pydantic V2 will offer a strict switch which can be set on either a model or a field

A couple things that spring to mind:

1. The API for configuring this on a field vs. a model. The logical places to put this seem to be `Annotated[..., Field(strict=True)]` and `BaseModel.Config.strict` respectively. I could also see `Annotated[MyModel, Field(strict=True)]` since `pydantic-core` no longer has special treatment of Models vs. Fields.
2. If the configuration is set on a field, does it propagate recursively to nested fields/models? It seems like if it's set on `BaseModel.Config.strict` the users intention would usually be to propagate it to all of this models fields and their fields, recursively. I'm less sure if that would always be the intention when set for an individual field.

Thinking of the first point: do we have a story for merging multiple `Field()` metadata? I think that since `Field()` is a `GroupedMetadata` which unpacks into an iterator we could have something like this for fields:

```from pydantic import BaseModel, Strict

class ModelWithStrictField(BaseModel):
    # unpacks to Annotated[int, Field(strict=True)] 
    # and can be nested like Strict[PositiveInt[int]] or `PostitiveInt[Strict[int]]
    foo: Strict[int] 
```

This could theoretically also work for models themselves but it's a bit tricky because of how models are used as validators. That is, if we had something like:

```python
class Model(BaseModel):
    pass

validator = Validator(Strict[Model])
```

This would be compelling. But we don't have a `Validator` concept in Pydantic, so I think for models we'll have to offer a knob in `BaseModel.Config`.

**Comment by adriangb** [comment]
After exploring how things currently work in pydantic-core I've learned that passing `strict=True` or `strict=False` to a validator overrides whatever is set on the field. Given this, I propose the following:

- Setting `strict` on a field only sets it for that field (not recursive) and configures the schema but not the validator. The default validator will use `strict=None` so fields with `strict=True` will have strict mode enforced by default.
- Setting `strict` on a `BaseModel.Config` makes the default validator use `strict=True`.

I'm going to punt on the whole two validators thing and classmethods for now. I'd like to explore an API for getting a `pydantic-core` validator for a given `BaseModel` (so you as a user could say `strict_validator = create_validator(MyModel, strict=True)` or something, as well as some other alternatives. In the meantime I plan to move forward with implementing things using the "default" validator.

A couple points where I need some clarification @samuelcolvin:

> pydantic-core can switch from strict to lax mode at validation time, it doesn't require separate validators, however unfortunately I very much doubt that will be possible in pydantic - many of the schemas will need to be different for strict and lax mode

I must be missing something here: why do schemas need to change in strict vs. lax mode? Isn't the whole point of having `strict: bool | None = None` in pydantic-core's validator that we can change this configuration without changing the schema?

> modify all types defined in pydantic make them work correctly in strict mode and add thorough tests for these

Aside from adding a `strict: bool = False` parameter to `Field`, what modifications are needed for other types? I must be missing something.

**Comment by adriangb** [comment]
What do we have left to do here?

> modify all types defined in pydantic make them work correctly in strict mode
> add thorough tests for these

I'm still not sure I understood what is meant here

> I guess we define models as strict as lax, then add class methods:

Maybe we can table this since for now it is possible to do:

```python
class StrictModel(LaxModel):
    class Config:
       strict = True
```

Which should work well with https://github.com/pydantic/pydantic/issues/4673#issuecomment-1304311911

And the other way around. Which is a couple more lines of code but avoids introducing a new API. Then once we see how people use this we can think about adding a new API.

**Comment by samuelcolvin** [comment]
Sorry, not to have replied earlier, I did the classic "reads comment on phone in evening, thinks "this is too complex/interesting to reply to now, I'll reply in the morning" then forgets".

In roughly order of your questions:

> `Annotated[MyModel, Field(strict=True)]`

I think this, or it's equivalent `Annotated[MyModel, Strict()]` should work fine, if not, it shouldn't be too hard to make it work.

> If the configuration is set on a field, does it propagate recursively to nested fields/models?

I think it should, e.g. if you had

```py
# implicitly not strict
class SubModel(BaseModel):
    x: int
    y: str

class MainModel(BaseModel):
    sub_model: SubModel = Field(strict=True)
```

I think you'd expect `sub_model.x` to be strict.

The more complex question is what should happen in the following scenario

```py
# implicitly not strict
class SubModel(BaseModel):
    x: int
    y: str

class MainModel(BaseModel, strict=True):
    sub_model: SubModel
```

In this scenario, should `sub_model.x` be strict? I think by default, it should.

In pydantic-core we have a very powerful (read, probably over-complicated) system of logic for merging parent config and child config, see [here](https://github.com/pydantic/pydantic-core/blob/463ed7aa83b08c43bc699e7e5380026551e38876/pydantic_core/core_schema.py#L25-L28) and [here](https://github.com/pydantic/pydantic-core/blob/463ed7aa83b08c43bc699e7e5380026551e38876/src/validators/new_class.rs#L168-L205). Whether we expose and document all that, or just choose a sensible default for V2 is up for debate.

> But we don't have a Validator concept in Pydantic, so I think for models we'll have to offer a knob in BaseModel.Config.

We will, see #4669.

> I must be missing something here: why do schemas need to change in strict vs. lax mode?

The pydantic-core validators do not, they're all already set up to work with a runtime choice of strict or lax. The problem is with all the validators implemented in python. Some might be fine, but many will not.

One example is the `UUID` validator, which is currently defined as 

https://github.com/pydantic/pydantic/blob/13ad034e4400baf5a875767e363aba879501065f/pydantic/_internal/_std_types_schema.py#L91-L105

(`strict=True` here just means we only make one pass over the union options in "strict mode", but that means we accept a UUID, OR string or bytes which passes [`UUID(__input_value)`](https://github.com/pydantic/pydantic/blob/13ad034e4400baf5a875767e363aba879501065f/pydantic/_internal/_validators.py#L230))

The validator is inherently lax. There are quite a few other validators in that file that follow similar principles.

Obviously in the case of `uuid_schema` we need a new `strict_uuid_schema` function which is basically just

```py
def strict_uuid_schema(_schema_generator: GenerateSchema, uuid_type: type[UUID]):
    return core_schema.is_instance_schema(uuid_type)
```

There's then a choice of two ways (that I can think of) to use the schema generated by `strict_uuid_schema`:

We have a strict `True/False` parameter on `GenerateSchema` and choose which function to use to generate the schema then. After that a validator is inherently either strict or lax. We could perhaps have some complicated way to know if a schema is suitable to be used in both strict and lax validation or not, but that sounds horrible.

OR

(new idea I've just had) We introduce a new validator type in pydantic-core `StrictOrLaxValidator` which takes two schemas, and chooses which one to use at validation time based on the strict argument. I think this is a much better idea, I'll create an issue now on pydantic-core.

With both routes, we need functions to generate both strict and lax schemas for python types where applicable.

I guess we should also rename the `uuid_schema` function to `lax_uuid_schema` for clarity while adding `strict_uuid_schema`.

---

I think that covers the main things, does that make sense?
