### ISSUE TITLE
V2: Fixes for private attrs, class vars, final

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4667]
Some of this is done in #4516, but more cleanup is necessary.

In particular I think private attributes are mostly complete, but classvars are not implemented properly unlike in V1.

To Fully support `Final` (aka frozen) fields, we need to complete and release https://github.com/pydantic/pydantic-core/pull/237.

@Bobronium did most of the original work on private attributes, maybe he would be willing to look at this?

**Comment by Bobronium** [comment]
> @Bobronium did most of the original work on private attributes, maybe he would be willing to look at this?

Hello! Thanks for mentioning me :)

It's a bit unclear what is there to work at and where.

Questions I have:
- what's current state (and where it's present)?
- what's DoD (I assume making it work just as it worked in V1)?
- is there a TL;DR I can read to start contributing on V2 or this issue in particular?

**Comment by samuelcolvin** [comment]
no problem

> * what's current state (and where it's present)?

#4516 is merged, which adopts pydantic-core for validation, I think private attributes are working well but class vars are broken and need to be fixed again

> * what's DoD (I assume making it work just as it worked in V1)?

Yes, basically I think we want this to work pretty unchanged from V1. Unless you have any idea of improvements?

> * is there a TL;DR I can read to start contributing on V2 or this issue in particular?

I replied to your email, basically the blog and #4516.

**Comment by misuzu** [comment]
Is there any hope for https://github.com/pydantic/pydantic/issues/2105 in V2?

**Comment by samuelcolvin** [comment]
as per my comment on #2105, I'll accept fields with a single leading underscore though I don't really like it.

Not sure how it would affect this though.
