### ISSUE TITLE
V2: rename model methods

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4672]
See https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#model-namespace-cleanup

This is mostly mechanical and fixing lots of tests, should definitely wait for #4516, but even after that, the biggest problem might be conflicts with other open PRs.

**Comment by nefas777** [comment]
Hi, I would like to help the project and this issue looks like good to start with. Can I take it? Do I need to change any docs (blog, ...)? Are there any other blockers except https://github.com/pydantic/pydantic/pull/4516?

**Comment by samuelcolvin** [comment]
Hi @nefas777, I'd love you to take this on. Thanks so much.

The docs should be updated, but don't worry too much since most of the docs will be rewritten, blog doesn't need to be updated.

I don't think there are any blockers on this, the only thing to clarify is names if there are any method names you're not sure about - probably best to start, create a draft PR and comment there if you aren't clear or have any questions.

Thanks so much for the offer. :raised_hands:
