### ISSUE TITLE
V2: Make `Config` a dict not a class

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4673]
I would like to suggestion (strongly, but I will take feedback) that we change config from a nested class on a model, to a dict.

Rationale for this:
* config is already a dict if you set it via kwargs to a class on definition
* Config inheritance is currently magic, complicated and error prone
* when methods are defined on the config class, what do `self` or `cls` "mean", it's not clear to me, or to others
* we already have the weird distinction between `Model.__config__` and `Model.Config`, would be good to remove this
* Most of all, as more and more validation goes on without a model, it's not clear how config should be defined if it's a class

With that, I would suggest the default way of defining config on a model, is via kwargs, e.g:

```py
from pydantic import BaseModel

def my_alias_generate(..) ...:

class MyModel(BaseModel, strict=True, alias_generator=my_alias_generate, ...):
    ...
```

But, to support bigger configs, we could also support

```py
from pydantic import BaseModel, ConfigTypeDict

def my_alias_generate(..) ...:

class MyModel(BaseModel):
    model_config = ConfigTypeDict(strict=True, alias_generator=my_alias_generate, ...)
    ...
```

Then with the `validate` function #4669, config becomes

```py
from pydantic import validate

@validate(strict=True, alias_generator=...)
def my_method(...):
   ...
```

questions?

**Comment by PrettyWood** [comment]
I'm completely in favour of this! In fact I already added config as a dict in https://github.com/pydantic/pydantic/pull/2557/commits/04f7ea0e2a21a8db36a39e277e1fb21f5bdf59f6 as for dataclasses, it's even worse to create a class on a side to add it in the decorator.
A (typed)dict does clearly the trick !

**Comment by 0xMochan** [comment]
How would config inheritance work with this system?
I understand the original system is "magic", but would it still function in a similar manner with this.
I'm all for simpler code so I can cope if we lose out on config inheritance.

**Comment by samuelcolvin** [comment]
Yes, config on a child class would be merged with parent classes with child classes taking priority.
