### ISSUE TITLE
When "orm_mode" is True, we are seeing inconsistent behaviours when a field annotated with another BaseModel is instantiated using a dictionary of attributes.

### ISSUE THREAD

**Issue by benwah** [pydantic/pydantic#4678]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Let's say I have a model such as

```python
class OrmFoo(BaseModel):
    name: str | None
```

.. and I instantiate the model using:

```python
OrmFoo(foo={"name": SOMETHING})
```

Then the validation behaviour is quite strange and inconsistent depending on the make-up of various fields on the "sub model", and depending on whether we are using "orm mode" or not.

### Example Code

```Python
from typing import List

import pytest
from pydantic import BaseModel, ValidationError


class OrmFoo(BaseModel):
    name: str | None

    class Config:
        orm_mode = True


class OrmBasket(BaseModel):
    foo: OrmFoo

    class Config:
        orm_mode = True


class OrmFoo2(BaseModel):
    name: str | None
    age: int

    class Config:
        orm_mode = True


class OrmBasket2(BaseModel):
    foo: OrmFoo2

    class Config:
        orm_mode = True


class Foo(BaseModel):
    name: str | None


class Basket(BaseModel):
    foo: Foo


class MyType:
    ...


class TestOrmMode:
    def test_foo_is_string(self):
        """I would expect this test to fail since foo is str rather than OrmFoo"""
        with pytest.raises(ValidationError):
            print(OrmBasket(foo="").dict())

    def test_foo_is_int(self):
        """I would expect this test to fail since foo is int rather than OrmFoo"""
        with pytest.raises(ValidationError):
            print(OrmBasket(foo=1).dict())

    def test_foo_is_anything(self):
        """I would expect this test to fail since foo a custom type."""
        with pytest.raises(ValidationError):
            print(OrmBasket(foo=MyType()).dict())

    def test_foo_is_dict(self):
        assert OrmBasket(foo={"name": "James"}).foo.name == "James"

    def test_foo_is_empty_dict(self):
        assert OrmBasket(foo={}).foo.name is None


class TestOrmModeBasket2:
    def test_foo_is_string(self):
        with pytest.raises(ValidationError):
            print(OrmBasket2(foo="").dict())

    def test_foo_is_int(self):
        with pytest.raises(ValidationError):
            print(OrmBasket2(foo=1).dict())

    def test_foo_is_anything(self):
        with pytest.raises(ValidationError):
            print(OrmBasket2(foo=MyType()).dict())

    def test_foo_is_dict(self):
        assert OrmBasket2(foo={"name": "James", "age": 1}).foo.name == "James"

    def test_foo_is_empty_dict(self):
        with pytest.raises(ValidationError):
            print(OrmBasket2(foo={}))


class TestBasket:
    """
    Why is the behaviour on construction different when `orm_mode` is False and when
    it's True? I thought that `orm_mode` only allowed us to use `from_orm`.
    """

    def test_foo_is_string(self):
        """I would expect this test to fail since foo is str rather than OrmFoo"""
        with pytest.raises(ValidationError):
            print(Basket(foo="").dict())

    def test_foo_is_int(self):
        """This now passes, good."""
        with pytest.raises(ValidationError):
            print(Basket(foo=1).dict())

    def test_foo_is_anything(self):
        """This now passes, good."""
        with pytest.raises(ValidationError):
            print(Basket(foo=MyType()).dict())

    def test_foo_is_dict(self):
        assert Basket(foo={"name": "James"}).foo.name == "James"

    def test_foo_is_empty_dict(self):
        assert Basket(foo={}).foo.name is None

```

### Python, Pydantic & OS Version

```Text
Python: 3.10.6
Pydantic: 1.10.2
OS: Debian Unstable, Kernel 6.0.2-1
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Honestly I'm pretty confused by your example, it doesn't help that I'm a bit unclear on when "fail" refers to validation raising and error and the test failing.

But more generally, `from_orm` means validation of sub models will try taking attributes form objects as well as items from dicts, whether or not you use `from_orm`, see 

https://github.com/pydantic/pydantic/blob/36be4c9f4e708a15472d55a09f15481943e86ee6/pydantic/main.py#L712-L713

I think that's your question?

The good news is that this will change in V2:
* "from ORM" is being replaced with the much better "from attribures" name
* the `from_orm` method will be removed and instead you'll always use the normally ways to create a model: `__init__` and `model_validate` (née `parse_obj`)

Hope that helps, feel free to create a discussion if you have any more questions.
