### ISSUE TITLE
V2 docs: Conversion table

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4680]
In V2 I intend to provide a complete list of valid fields types, and what types can be provided to each of those types in strict and lax mode.

See [this section of the blog](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#formalised-conversion-table) for more details.

For example, if the field type is `int`, valid inputs are:
* in strict mode:
  * `int` - all, but note `bool`s which are subclasses of `int` are forbidden
* in lax mode:
  * `int` - all
  * `float` - if `f % 1 == 0` - e.g. `2.0` can be coerced to an int, but not `2.1` (I think we have some minimal allowed difference to account for floats being fuzzy)
  * `bool` - all - the value is coerced to an actual int
  * `string` provided either `str.parse::<i64>` or `str.parse::<f64>() -> float_as_int` pass, we need to define exactly what this means
  * `bytes` provided they decode to a string which passes the above

There's also the issue of which JSON types are allowed to each type, that's kind of obvious in the case of `int`, but much less clear for other types.

The plan is to use this table/matrix in a number of places:
* Mypy plugin
* Signature generation
* Hypothesis plugin
* Pycharm plugin maybe, if @koxudaxi is willing?
* Docs - as a big table or maybe as multiple sections

For this reason the data needs to be easily parsed - e.g. it can't just be one big markdown document

My suggestion would be that this should be structured as one markdown file per type, each markdown file should start with a code block of toml with the structured data set out below, followed by a markdown body containing the long description. We can then write some code which reads these files, parses them, validates the output against a pydantic model, and makes the result available for the above uses. We might need to generate a JSON or python file with this data to include in the package. I'm flexible on how we do all this if you have a better idea (but my idea sounds pretty good :-))?

Either away, the output should be a dict as follows:
* key: the code name of the type, e.g. `int`, `float`, `Counter` etc:
* value, dict with:
  * short description: one line string
  * long description (probably form markdown body): string with example of usage, some will be longer than others
  * any customisation allowed on the type, e.g. `from_attributes` on a TypedDict, dict with:
    * key: parameter name, e.g. `from_attributes`
    * value, dict with:
      * `type` - python type hint for this parameter
      * `description` - string description of the meaning/use of this parameter
  * input types, dict:
    * key: input type
    * value, dict with:
      * mode: strict/lax
      * conditions - string explaining when it would be allowed
      * input formats: python and/or json
  * JSON schema representation: ... what do we need here?

**Comment by corleyma** [comment]
Naive question: how will this work with custom types?  It's pretty common in pydantic v1 to define "parsing" validators that go from primitive types to custom types.  What will that look like in v2, given the intent to exhaustively specify acceptable conversions?  It would definitely be nice if it were possible for users to make mypy understand that e.g. ints and bools can be parsed to MyCustomType, but strings cannot.

**Comment by koxudaxi** [comment]
@samuelcolvin 
Thank you for mentioning me.

I agree with you.
I will implement this feature in the PyCharm plugin.
From the PyCharm side, all file format is OK as the conversion table.
The plugin can load data from `toml`, `json`, and python files.
In any case, the plugin will be able to cache the table when detecting the pydantic library. it means don't affect the performance of PyCharm.

**Comment by steve-mavens** [comment]
@corleyma maybe if the validator specifies the field it applies to with a string literal (which is the common case) then that's enough information to allow the plugin to take the types from the validator signature and add them to the acceptable types for the field?

**Comment by samuelcolvin** [comment]
@corleyma good question.

@corleyma that's partially right, particularly if I substitute "type" for "field" in the first sentence.

More generally there are really two types of custom validator in V2, I'll demonstrate both here:

```py
import re
from typing import Annotated

from pydantic import BaseModel


class Box:
    """
    This is a concrete type.
    """
    width: int
    height: int

    def __init__(self, width: int, height: int):
        self.width = width
        self.height = height

    @property
    def area(self):
        return self.width * self.height

    @classmethod
    def validate_box(cls, input, **kwargs) -> 'Box':
        if m := re.fullmatch(r'box\((\d+), (\d+)\)', input, flags=re.I):
            return cls(int(m.group(1)), int(m.group(2)))
        else:
            raise ValueError('Invalid box format')

    def __repr__(self):
        return f'Box({self.width}, {self.height})'

    @classmethod
    def __get_pydantic_validation_schema__(cls, *, types_namespace):
        return {
            'type': 'function',
            'mode': 'plain',
            'function': cls.validate_box,
        }


class BoxTupleValidator:
    """
    This is a validator, but it's never initialized.
    """

    @classmethod
    def validate_box_tuple(cls, input, **kwargs) -> tuple[int, int]:
        if m := re.fullmatch(r'box\((\d+), (\d+)\)', input, flags=re.I):
            # no conversion to int here, instead we pass this tuple of strings to the innner validator
            return m.group(1), m.group(2)
        else:
            raise ValueError('Invalid box format')

    @classmethod
    def __get_pydantic_validation_schema__(cls, inner_schema, /):
        """
        Note: here we use a "before" function validator, so the output of `validate_box_tuple`
        is passed to the validator built from the `inner_schema`.
        """
        assert inner_schema == {
            'type': 'tuple',
            'mode': 'positional',
            'items_schema': (
                {'type': 'int'},
                {'type': 'int'},
            ),
        }
        return {
            'type': 'function',
            'mode': 'before',
            'function': cls.validate_box_tuple,
            'schema': inner_schema,
        }


class BoxModel(BaseModel):
    box: Box
    box_tuple: Annotated[tuple[int, int], BoxTupleValidator]


m = BoxModel(box='box(1, 2)', box_tuple='box(1, 2)')
print(m)
```

We could add another magic attribute to either `ConcreteBox` or `BoxTupleValidator` or both like `__pydantic_allowed_types__` to allow tools like the pycharm plugin to show correct warnings.

We could also use this attribute on types included in pydantic to generate the main table.

**Comment by corleyma** [comment]
Thanks for clarifying @samuelcolvin; overall, I really like the general approach of being totally explicit whilst supporting the ability for custom types to also use this machinery.

**Comment by samuelcolvin** [comment]
Idea is to write it as a python file, with an abc, then implementations of the abc for every type we want to document.

That way we can put tests next to the documentation.

For example for `int` (as described above), we might have:

```py
class Int(DocumentType):
    """
    Docstring can become the intro.
    """
    documented_type = int
    strict_mode = [
        AllowedType(int, note='`bool`s (which are technically a subclass) of `int` are forbidden'),
    ]
    lax_mode = [
        AllowedType(int),
        AllowedType(float, note='if `f % 1 == 0` - e.g. `2.0` can be coerced to an int, but not `2.1`'),
        AllowedType(bool),
        AllowedType(str, note='provided either `str.parse::<i64>` or `str.parse::<f64>() -> float_as_int` pass, we need to define exactly what this means'),
    ]
    core_schema = core_schema.IntSchema

    def test_strict(self):
        ...

    def test_lax(self):
        ...
```

We can then process that file to turn the data into json, yaml, markdown etc.

**Comment by samuelcolvin** [comment]
Better idea:

```py
from dataclasses import dataclass
from typing import Any


@dataclass
class Row:
    field_type: type[Any]
    input_type: type[Any]
    mode: Literal['lax', 'both']
    input_format: str | None = None
    condition: str | None = None


table_info: list[Row] = [
    Row(
        int,
        int,
        'both',
    ),
    Row(
        int,
        float,
        'both',
        condition='value % 1 == 0',
    ),
 ]
```
