### ISSUE TITLE
V2 docs: error codes and details

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4681]
As described [here](https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#error-descriptions) I want to provide documentation for every validation error, a link to each error will be included in `validation_error.errors()`.

Each error already has a unique `type` (if the same `type` is used in two different places, it's assume it's the same error and should have the same message).

However I want to go one step further and also add a unique code to each [`PydanticUserError`](https://github.com/pydantic/pydantic/blob/eaa2ad14c71138600de301d5f0ebf8fda6775788/pydantic/errors.py#L6), `PydanticUndefinedAnnotation` etc. and print a link to the docs for that error in the `__str__` method for the error.

A bit like the conversion table #4680, I think we should have one markdown file for each validation error with a code block of toml containing structured data and the rest of the markdown file with details about the error.

Obviously building comprehensive docs for every error, both validation errors and error raised to pydantic developers is a massive piece of work, at this stage I just want to get all the markdown files in place with a one line explanation, then others can contribute by adding more details. Ultimately, once we've released pydantic V2 users who are not satisfied by the details given on an error will be encouraged to contribute by submitting a PR to add more details.

---

### What's required here

At this stage we need (once #4516 is merged):
* to modify [`pydantic/errors.py`](https://github.com/pydantic/pydantic/blob/eaa2ad14c71138600de301d5f0ebf8fda6775788/pydantic/errors.py) to use a mixin for each of those classes which:
  * adds `__init__(self, type: str, message: str)`
  * adds `__str__` with the type and a placeholder for the help URL
  * adds a no-op `_check()` method (see below), and calls it on `__init__` (or maybe we could get away with just spying on `__init__`?)
* an `autouse` pytest fixture which mocks `PydanticErrorMixin._check`  and checks all errors have a matching description file - this forces future contributors to add details some docs on any new error they add (e.g. if it's just "you broke foobar, users should never see this, please create an issue if you're getting this error")
* we also need an `autouse` fixture which checks we've got docs in the pydantic repr for every use of `PydanticCustomError`
* a directory in `docs` which contains markdown files with error details

We need to differentiate between developer errors and validation errors, but I guess that can just be a value in the structured data.

To make it as painless as possible to contribute to both pydantic and pydantic-core, the error information for each exception should be in the same repo as the code, therefore we'll need to add a similar directory of errors information to pydantic-core.

I would love someone to take this on once #4516 is merged, any volunteers?

**Comment by samuelcolvin** [comment]
See https://github.com/pydantic/pydantic-core/issues/312 for similar in pydantic-core

**Comment by bgoldstone** [comment]
I am interested in working on this codebase, but I am confused as most of the calls to PydanicUserError are with one string parameter and two. Can you please clarify?

**Comment by bgoldstone** [comment]
I am interested in working on this codebase, but I am confused as most of the calls to PydanicUserError are with one string parameter and two. Can you please clarify @samuelcolvin?

**Comment by bgoldstone** [comment]
#4870

**Comment by ybressler** [comment]
Does this issue have an assignee? (Is it @bgoldstone ?) Else, I can take this one.

**Comment by ybressler** [comment]
Keep going with it then @bgoldstone

**Comment by tpdorsey** [comment]
@samuelcolvin I think we can close this now, can you confirm?
