### ISSUE TITLE
V2: config parameter to warning about missing annotations

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4683]
We have [logic](https://github.com/pydantic/pydantic/blob/eaa2ad14c71138600de301d5f0ebf8fda6775788/pydantic/_internal/_model_construction.py#L203) to deal with the case where an annotation is not defined when a model is constructed, at the moment this silently stops the schema/validator build and `__pydantic_model_complete__` is left `False` in the hope that the missing annotation(s) can be defined and the model completed via `model_rebuild`.

I think we should have a config flag, default True which raising a warning when this happens - it should be a `UserWarning` so it gets printed by default.

Needs #4516 to be merged before this can be worked on, but would be amazing if someone could take this on.

**Comment by ybressler** [comment]
I'd be happy to contribute to this. Would be my first contribution to pydantic – do you think it's suitable?

**Comment by samuelcolvin** [comment]
Yes absolutely, please submit a PR.

**Comment by ybressler** [comment]
Sweet! I'll get to working on this over the weekend / next week. (Meanwhile, is it possible for you to `assign` to me? Easier for me to be organized. If this is against your management preference, that's ok too.

**Comment by jimkring** [comment]
@samuelcolvin I was looking at #4683 and I could not create a unit test that demonstrates the problem you're describing.

What do you mean exactly by "the case where an annotation is not defined when a model is constructed"?

I tried a variety of different things and I could not make a test where `assert f.__pydantic_model_complete__` would fail.

for example:

```python
def test_warn_on_model_missing_annotation():
    
    Foo = ForwardRef('Foo')

    class Foo(BaseModel):
        a: int = 123
        b: Foo = None
    
    f = Foo().construct()
    
    assert f.__pydantic_model_complete__, 'Model should be complete'
```

Would you be willing to share a simple (xfail) test that demonstrates the desired pass conditions?

Thanks.

**Comment by samuelcolvin** [comment]
I I think of you define `Foo` after `Bar` you should get the error.

Or definitely if `Foo` is another pydantic model with references `Bar`.

**Comment by jimkring** [comment]
@samuelcolvin Thanks for that info. I spent a while looking through the code.  I just created a PR with an attempt to implement this feature.  I have some questions that I'll ask in the PR.
