### ISSUE TITLE
V2: `SecretBytes()` encoding prints a bytes repr, not a string of asterisks. (pydantic-core branch)

### ISSUE THREAD

**Issue by dwreeves** [pydantic/pydantic#4688]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The following two test cases for `tests/test_json.py::test_encoding` are failing in the `babelfish` branch:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/31971762/198853890-f2ea7b07-96d6-4340-bb77-de0e6fae69c0.png">

It looks like the problem is that the `__str__` method for `SecretBytes` is returning a `bytes` and not `str`.

I have a fix here that can be merged into the `babelfish` branch that gets these 2 test cases to pass: https://github.com/pydantic/pydantic/commit/e402b6ffe96946fd684ef4832334473adaef325a but I do not have permission to open a pull request as per the PR template, so I'm opening an issue here.

Note we need to revert a test in `test_types.py` as well, but 1/2 of what we revert back was the original behavior and it looks like that test was modified to make it pass. See pre-babelfish tests here: https://github.com/pydantic/pydantic/blob/f7ff485fd705eaffb261fa2adb5b68d7f3d9758c/tests/test_types.py#L2699

I also believe that the behavior in my commit https://github.com/pydantic/pydantic/commit/e402b6ffe96946fd684ef4832334473adaef325a is the most sensible behavior:

- The internal type is a bytes, so `SecretBytes(b'**********')` is a sensible repr.
- However, `str()` should always return a `str` type, not `bytes`.

### Python, Pydantic & OS Version

```Text
Strictly speaking:


Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pydantic.utils'
```

But if I run `python -c "import pydantic.version; print(pydantic.version.version_info())"`:

```
             pydantic version: 2.0.0.dev0
                 install path: /Users/wd/projects/pydantic/pydantic
               python version: 3.7.13 (default, Jul  9 2022, 14:43:13)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: Darwin-19.6.0-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```
```


### Affected Components

- [x] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [x] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
As per #4456 all this logic needs to be written, I haven't addressed it at all in that branch.
