### ISSUE TITLE
V2: replace URL types with a 3rd party library

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4694]
As per #4470, the `URL` types - everything inheriting from `AnyUrl` are messed up, it may just be weird edge cases that don't work, but getting URLs to be validated correct is a really hard task and shouldn't be included in pydantic.

In V2, we should use a 3rd party library for URL parsing and validation, ideally in rust as part of pydantic-core.

**Comment by samuelcolvin** [comment]
Also #1665 - remove `user_required`.

**Comment by commonism** [comment]
I can recommend [yarl.URL](https://github.com/aio-libs/yarl)

**Comment by samuelcolvin** [comment]
This is done, we're using the URL crate from rust.
