### ISSUE TITLE
Date field doesn't support all datetime format when it should

### ISSUE THREAD

**Issue by cscetbon** [pydantic/pydantic#4702]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

At https://pydantic-docs.helpmanual.io/usage/types/#datetime-types it says  
```
date fields can be:
str, following formats work:

...see datetime
```

However date field doesn't support strings that have time in it when it should.

### Example Code

```Python
from datetime import datetime, date
from pydantic.dataclasses import dataclass

@dataclass
class Bug:
    dateField: date = None
    datetimeField: datetime = None

In [2]: Bug(dateField="2022-01-01")
Out[2]: Bug(dateField=datetime.date(2022, 1, 1), datetimeField=None)

In [3]: Bug(datetimeField="2022-01-01T12:00:00")
Out[3]: Bug(dateField=None, datetimeField=datetime.datetime(2022, 1, 1, 12, 0))

In [4]: Bug(dateField="2022-01-01T12:00:00")
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In [4], line 1
----> 1 Bug(dateField="2022-01-01T12:00:00")

File /usr/local/lib/python3.10/site-packages/pydantic/dataclasses.py:313, in _add_pydantic_validation_attributes.<locals>.new_init(self, *args, **kwargs)
    310 handle_extra_init(self, *args, **kwargs)
    312 if self.__class__.__pydantic_run_validation__:
--> 313     self.__pydantic_validate_values__()
    315 if hasattr(self, '__post_init_post_parse__'):
    316     # We need to find again the initvars. To do that we use `__dataclass_fields__` instead of
    317     # public method `dataclasses.fields`
    318     import dataclasses

File /usr/local/lib/python3.10/site-packages/pydantic/dataclasses.py:416, in _dataclass_validate_values(self)
    414 d, _, validation_error = validate_model(self.__pydantic_model__, input_data, cls=self.__class__)
    415 if validation_error:
--> 416     raise validation_error
    417 self.__dict__.update(d)
    418 object.__setattr__(self, '__pydantic_initialised__', True)

ValidationError: 1 validation error for Bug
dateField
  invalid date format (type=value_error.date)
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: False
                 install path: /usr/local/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Oct 25 2022, 03:04:20) [GCC 11.2.1 20220219]
                     platform: Linux-5.15.49-linuxkit-aarch64-with
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
It's mentioned on doc that `date` supports string with `YYYY-MM-DD` format.
