### ISSUE TITLE
Applying validators to child items of lists

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#4707]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Followup to https://github.com/pydantic/pydantic/pull/4516#discussion_r1012045834

We are currently on the path to allow the following in v2:

```python
data: Annotated[list[int], Field(min_items=3, gt=0)]
# or
data: list[int] = Field(min_items=3, gt=0)
```

Since `gt=0` doesn't apply to `list` we'd automatically apply it the items (`int`).

I think this behavior might be confusing and lead to issues down the road so I would like to propose we remove it for now and add it later once v2 is more stable and if users request it. The alternative, which is just a bit more boilerplate, is:

```python
data: Annotated[list[Annotated[int, Field(gt=0)], Field(min_items=3)]
# or the more legible option imo
PositiveInt = Annotated[int, Field(gt=0)]
data: Annotated[list[PositiveInt], Field(min_items=3)]
# but also possibly
PositiveInt = Annotated[int, Field(gt=0)]
T = TypeVar("T")
ListWithAtLeast3Items = Annotated[list[T], Field(min_items=3)]
data: ListWithAtLeast3Items[PositiveInt]
# which allows m x n composability
PhoneNumber = Annotated[str, Field(regex=r"\d{9})]
data2: ListWithAtLeast3Items[PhoneNumber]
```

I think the advantages of this style are:
1. Straightforward interpretation. There is no confusion as to what things constraints apply to, how constraints interact with generics, etc.
2. Easier to implement (I think). We don't need any special casing, we always apply constraints to the type at the level the annotations is at.
3. More re-usable code. When using type aliases, this style naturally leads to re-usable code.
4. More legible code. Using type aliases with meaningful names helps understand the code. If you read `ListWithAtLeast3Items[PhoneNumber]` you probably don't even have to go look at the constraints to understand what is valid and what is not.

The disadvantages are:
1. More code and if using type aliases more _lines_ of code. I think this is mitigated by the fact that the magic pushdown approach doesn't scale beyond a single level of nesting. If you want to do `list[list[int]]` you still have to use the nested annotated approach.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks, I'm on the fence on this.

What do others think?

What about:

```py
data: int | None = Field(gt=0)
```

Do you we should allow some cases like this, or have a hard rule against magically pushing constraints down?

**Comment by adriangb** [comment]
I thought this wasn't implemented in V1 but it looks like it is:

```python
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    foo: list[int] = Field(gt=0)

MyModel(foo=[1])  # ok
MyModel(foo=[-1])  # fails
```

So I guess if we released V2 without it we'd be making a breaking change. On the other hand maybe this is somewhere we _should_ make this change if we have a better way to do this in V2.

**Comment by samuelcolvin** [comment]
Ye, that's why I think I started thinking about it.

No question, we should prioritise "make it right" over "make it compatible", so the argument that it worked in V1 is only a lite argument in favour.

Still, on balance I think I'm in favour of the magic.

Remember the situation is much better than in V1, if you add constraints that aren't used in V2/core an error will be raised, so we shouldn't have any silent failures.

**Comment by adriangb** [comment]
What's the expected behavior for `data: dict[str, str] = Field(regex=r"...")`? Does the regex apply to the keys, the values or both?

**Comment by samuelcolvin** [comment]
I would argue that constraints should only "cascade" (is that a good term?) to dict values. If they're not valid, that would be an error.

I think that's what people would mostly want, but as long as we were explicit that would be ok.

**Comment by adriangb** [comment]
Indeed that is the behavior for V1 (sans the raising an error for invalid constraints part).

I'll also note that V1 applies constraints to nested items, which seems even more problematic:

```python
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    foo: dict[int, list[int]] = Field(gt=0)

MyModel(foo={1: [1]})  # ok
MyModel(foo={1: [-1]})  # fails
```

**Comment by samuelcolvin** [comment]
well, if constraints could should cascade, they should cascade recursively/indefinitely (that would also be much easier in code).

But maybe that's an argument against doing this.

**Comment by dmontagu** [comment]
Just getting up to speed on these things; for what it's worth, I would expect that the mixing of "levels" in the annotation `data: list[int] = Field(min_items=3, gt=0)` might cause some confusion and feel a bit more magical than preferable for newcomers.

Also, in case we did some form of cascading, would the following make sense?
```
MyList = Annotated[list[int], Field(min_items=3, gt=0)]
MyNestedList = Annotated[MyList, Field(gt=1)]
```

While a bit of thinking might make it obvious what the constraint-cascading logic should be, overall it seems to me cascading might ultimately end up being a recurring source of bugs and/or light confusion.

-----

On the other hand, I think this approach from @adriangb is very clear and looks great, and I think users would quickly pick it up from examples:
```
PositiveInt = Annotated[int, Field(gt=0)]
T = TypeVar("T")
ListWithAtLeast3Items = Annotated[list[T], Field(min_items=3)]
data: ListWithAtLeast3Items[PositiveInt]
```

This also strikes me as the sort of thing where a docs page with a laundry list of examples would go a long way.

So, my vote would be to not do _any_ constraint cascading, and just encourage people to (re)use more type aliases for clarity.

**Comment by adriangb** [comment]
Mostly agreed David, I just want to make one small clarification:

> in case we did some form of cascading, would the following make sense?
>```python
> MyList = Annotated[list[int], Field(min_items=3, gt=0)]
> MyNestedList = Annotated[MyList, Field(gt=1)]
> ```

[PEP 593](https://peps.python.org/pep-0593/#syntax) says "Nested Annotated types are flattened, with metadata ordered starting with the innermost annotation". So, in this example by definition (and implementation in `Annotated` itself and thus `get_type_hints`) `MyNestedList = Annotated[list[int], Field(min_items=3, gt=0), Field(gt=1)]`. I think we'll have to allow multiple `Field`s at a single level so that users can add more constraints/metadata to an already annotated type. We'll need to come up with a clear approach to resolving conflicts or erroring (I'd suggest it act like dict unpacking) but that's getting off the topic of this issue.

**Comment by adriangb** [comment]
@samuelcolvin did we come to a consensus here? Are we going with the magical pushdown approach or the no magic approach?

**Comment by samuelcolvin** [comment]
I think best we just have a way to apply validators via `Annotated[Xyz, FunctionValidator(my_function)]` WDYT?

**Comment by adriangb** [comment]
Yes, we should have that. I take it by that you mean that we won't have any sort of magical pushdown?

**Comment by adriangb** [comment]
Completed in https://github.com/pydantic/pydantic/pull/5364
