### ISSUE TITLE
Add timezone to tzinfo parsing to pydantic 2.0

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4710]
### Discussed in https://github.com/pydantic/pydantic/discussions/4708

<div type='discussions-op-text'>

<sup>Originally posted by **07pepa** November  2, 2022</sup>
Pydantic 1.x is missing native suport for timezone parsing  (and since this will probably will not be added natively). I am asking to add it to pydantic 2.x (does not have to be in rust) 

hopefully there is something like pytz (but there is issue how to keep database of all timezone up to date without need to recompile/ update rust part) 

</div>

**Comment by 07pepa** [comment]
curently i have this usecase in dict (yaml  :D )  there is string that is validated and converted with pydantic and help of pytz to datetime.tzinfo

(probably there are more usecases)

i can provide code

**Comment by samuelcolvin** [comment]
So you just want to check a string represents a valid timezone?

That seem pretty easy, but also pretty easy to implement as a custom type/validator.

The more complex case would be validating and using a timezone string as part of a datetime object. Part from anything else, that's not covered by ISO8601 or RFC3338 AFAIK.

**Comment by 07pepa** [comment]
yep and converting it to tzinfo object

and yes i know exacly what the problem woth RFC and iso but
google solves it like this

```json
{"dateTime": "2022-11-02T16:00:00+01:00", "timeZone": "Europe/Prague"}
```


Even there is fairly nice solution i still recomend to stay mile away from dealing with timezones
since it is [nightmare](https://www.youtube.com/watch?v=-5wpm-gesOY).

**Comment by dmontagu** [comment]
@samuelcolvin Possibly related? https://github.com/pydantic/pydantic-core/issues/589

**Comment by slingshotvfx** [comment]
> So you just want to check a string represents a valid timezone?

+1 for this feature. I'd like to be able to use `zoneinfo.ZoneInfo` as a type in a pydantic model and have it validate to a ZoneInfo object and serialize to a string.

In my case, I store user's timezone preference as a setting in a database using Pydantic/Beanie.

I copied this [docs example](https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types) and came up with this:

```python
class _ZoneInfoPydanticAnnotation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type: Any, _handler: GetCoreSchemaHandler) -> core_schema.CoreSchema:
        def validate_from_str(value: str) -> ZoneInfo:
            try:
                return ZoneInfo(value)
            except ZoneInfoNotFoundError:
                raise ValueError("Invalid timezone")

        from_str_schema = core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(validate_from_str),
            ]
        )
        return core_schema.json_or_python_schema(
            json_schema=from_str_schema,
            python_schema=core_schema.union_schema(
                [
                    # check if it's an instance first before doing any further work
                    core_schema.is_instance_schema(ZoneInfo),
                    from_str_schema,
                ]
            ),
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda instance: str(instance), when_used="json"
            ),
        )

TimezoneInfo = Annotated[ZoneInfo, _ZoneInfoPydanticAnnotation]
```

It seems to work, but still could be nice to have a native pydantic type.


p.s. unrelated to pydantic but for anyone who might stumble across this, I also had to add a custom encoder to Beanie:

```python
class Settings:
    bson_encoders = {ZoneInfo: str}
```

**Comment by 07pepa** [comment]
i am providing also my impleementation that i made last year it is  pure python   (pytz) implementation for reference... feel free to use it in non profit code...or in pydantic ( i do not have time to do it in rust or write tests)
its basicly same as zone info one.
```python
from collections.abc import Callable
from datetime import tzinfo
from typing import (
    Any, Annotated
)

from pydantic import GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema
from pytz import timezone, UnknownTimeZoneError, InvalidTimeError


class _PydanticTzInfoAnnotation:
    def __init__(self, *args, **kwargs):
        super.__init__(*args, **kwargs)

    @classmethod
    def __get_pydantic_core_schema__(
            cls,
            _source_type: Any,
            _handler: Callable[[Any], core_schema.CoreSchema],
    ) -> core_schema.CoreSchema:

        def check_timezone(tz: str | tzinfo) -> tzinfo:
            if not isinstance(tz, str):
                raise TypeError('timezone must be string')
            try:
                return timezone(tz)
            except UnknownTimeZoneError | InvalidTimeError as tz_info_err:
                raise ValueError from tz_info_err

        tz_schema = core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(check_timezone),
            ]
        )

        return core_schema.json_or_python_schema(
            json_schema=tz_schema,
            python_schema=core_schema.union_schema(
                [
                    # check if it's an instance first before doing any further work
                    core_schema.is_instance_schema(tzinfo),
                    tz_schema,
                ]
            ),
            serialization=core_schema.plain_serializer_function_ser_schema(
                lambda instance: str(instance)
            ),
        )

    @classmethod
    def __get_pydantic_json_schema__(
            cls, _core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        return handler(core_schema.int_schema())


PydanticTzInfo = Annotated[
    tzinfo, _PydanticTzInfoAnnotation
]
```

**Comment by mikenerone** [comment]
I'd like to see better zoneinfo/tzinfo support added to `pydantic-extra-types`.
