### ISSUE TITLE
Add documentation on ClassVar support 

### ISSUE THREAD

**Issue by heavelock** [pydantic/pydantic#4717]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hey! 

I was looking on how to properly add Class Variable to a pydantic model and it took me some effort to find a solution for that. It turned out that Pydantic supports `ClassVar[T]` notation for class variables but it is not described anywhere apart of the issues.

That support was added here in that PR:
https://github.com/pydantic/pydantic/pull/339
and the reason for not adding that to documentation is:
`I guess if we were perfect we'd add a section to documentation on this, but for now I can't be bothered.` 
https://github.com/pydantic/pydantic/pull/339#issuecomment-450227723

I would like to add that to the documentation but since big changes to pydantic are on the way I prefer to ask first for a green light before putting any effort for that. 

So, should I add it to the documentation?

### Python, Pydantic & OS Version

```Text
Macos, py3.9, pydantic 1.10.2
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
https://docs.pydantic.dev/latest/concepts/models/#class-vars, marking as done :)
