### ISSUE TITLE
Different serialization behavior when using frozen models vs frozen dataclasses

### ISSUE THREAD

**Issue by ldaniluk** [pydantic/pydantic#4719]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

It is impossible to serialize a pydantic model containing a set of frozen BaseModels but it is possible to serialize a pydantic model containing a set of frozen pydantic dataclasses.

### Example Code

```Python
from pydantic import BaseModel
from pydantic.dataclasses import dataclass


class FrozenModel(BaseModel):
    field: str
    
    class Config:
        frozen = True

        
@dataclass(frozen=True)
class FrozenDataclass:
    field: str
    
    
class ModelWithSetOfModels(BaseModel):
    field: set[FrozenModel]
    
    
class ModelWithSetOfDataclasses(BaseModel):
    field: set[FrozenDataclass]




sample_frozen_model = FrozenModel(field="sample")
sample_frozen_model_set = ModelWithSetOfModels(field={sample_frozen_model})
sample_frozen_model_set.json()

"""
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [7], line 3
      1 sample_frozen_model = FrozenModel(field="sample")
      2 sample_frozen_model_set = ModelWithSetOfModels(field={sample_frozen_model})
----> 3 sample_frozen_model_set.json()

File /usr/local/lib/python3.10/site-packages/pydantic/main.py:492, in pydantic.main.BaseModel.json()

File /usr/local/lib/python3.10/site-packages/pydantic/main.py:868, in _iter()

File /usr/local/lib/python3.10/site-packages/pydantic/main.py:794, in pydantic.main.BaseModel._get_value()

TypeError: unhashable type: 'dict'
"""


sample_frozen_dataclass = FrozenDataclass(field="sample")
sample_frozen_dataclass_set = ModelWithSetOfDataclasses(field={sample_frozen_dataclass})
sample_frozen_dataclass_set.json()

# '{"field": [{"field": "sample"}]}'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /usr/local/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug 23 2022, 08:36:38) [GCC 10.2.1 20210110]
                     platform: Linux-5.10.104-linuxkit-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
@ldaniluk thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by lig** [comment]
The example works in Pydantic v2
