### ISSUE TITLE
TypeVars not *really* supported? Mypy error even with plugin

### ISSUE THREAD

**Issue by berzi** [pydantic/pydantic#4720]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The code below uses a bounded TypeVar as the type for the field `some_thing`. Despite having the [plugin enabled](https://pydantic-docs.helpmanual.io/mypy_plugin/#enabling-the-plugin), Mypy reports an error like:

```
error: Type variable "my.app.models.T_SomeOtherModelSubclass" is unbound  [valid-type]
        some_thing: T_SomeOtherModelSubclass
```

This seems like something Pydantic's Mypy plugin should handle.

If this is actually a Mypy issue, please guide me to describe it to them, because otherwise they might just say it's Pydantic's fault and the issue will never be resolved.

At the moment I am forced to use a type of `Any` and an ad-hoc validator to support any subclass of a specific model in a pydantic field, which is really not ideal.

### Example Code

```Python
from typing import TypeVar

from pydantic import BaseModel


class SomeOtherModel(BaseModel):
    pass


T_SomeOtherModelSubclass = TypeVar("T_SomeOtherModelSubclass", bound=SomeOtherModel)


class MyModel(BaseModel):
    some_thing: T_SomeOtherModelSubclass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
            pydantic compiled: False
                 install path: [REDACTED]\venv\Lib\site-packages\pydantic
               python version: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.22000-SP0
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Afaik, this isn't a valid use of typevar since the class where it's used isn't generic.

Here you can just use `SomeOtherModel`.

**Comment by berzi** [comment]
> Afaik, this isn't a valid use of typevar since the class where it's used isn't generic.
> 
> Here you can just use `SomeOtherModel`.

@samuelcolvin [The documentation](https://pydantic-docs.helpmanual.io/usage/types/#typevar) clearly shows this should be possible. Furthermore, using `SomeOtherModel` has a different effect that in my use-case defeats the purpose entirely: any subclass of `SomeOtherModel` I give into the field would turn into a `SomeOtherModel` object, instead of retaining its original type.

**Comment by samuelcolvin** [comment]
Yes, but it's still not a valid use case from the perspective of mypy, or indeed python typing. Hence you can't expect mypy to like it.

Nothing the plugin can do about that.

Of course, if you think I'm incorrect, you're free to create a PR and prove me wrong. I'll happily accept the PR if it works.

**Comment by berzi** [comment]
I'd expect anything that is explicitly supported by Pydantic to be at the very least not considered an error, even if it won't have the effect I hope for.

**Comment by samuelcolvin** [comment]
I agree it's not ideal.

I think in v2 we should provide a way to differentiate between requiring an exact model and allowing subclasses of a model. That would remove the need for `TypeVar` outside generics and indirectly solve your problem.

**Comment by berzi** [comment]
That would be great. Perhaps it could be done through a field annotation? Or maybe it makes more sense to have a separate generic type like `Subclass[T]`.

Should I open a separate issue for discussion on this?

**Comment by samuelcolvin** [comment]
Yes, separate issue please. It should be done via an annotation, also probably a config parameter.
