### ISSUE TITLE
`dataclasses.replace` alternative for Pydantic

### ISSUE THREAD

**Issue by 0xMochan** [pydantic/pydantic#4723]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

`dataclasses.replace` is a very convenient method that helps you reconstruct a `dataclass` by replacing one field with another (or field**s**).

[Documentation](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace)

This method is really nice for frozen dataclasses since it's easy to reconstruct a frozen object with a slight change.
In Pydantic, it would be nice to use this method with frozen models as a similar feature. 

```py
from pydantic import BaseModel, replace

class MyModel(BaseModel, frozen=True):
  a: int
  b: str

model_a = MyModel(a=10, b="taco")
model_b = replace(model_a, b="cat")

model_b
# MyModel(a=10, b="cat")
```

I think this feature would fit within Pydantic's feature set, especially since frozen models are getting improved in the rewrite. It would provide a mechanism that makes working with frozen models much easier, akin to how the standard lib dataclasses work.

> Also, while using both `@dataclass` and `BaseModel` would provide me this behavior, I find it quite odd to use both just for this feature since it be extra bloat. `replace` itself is a concept that relates to frozen data objects and `dataclasses` (and `pydantic`) just fits that criteria.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
I think you can achieve this through the `update` argument to the `model_copy` method. Does that work for you?

(Eventually, I think we will add something similar into a `methods` module and/or onto `TypeAdapter`.)
