### ISSUE TITLE
Support field type for subclass of type without flattening

### ISSUE THREAD

**Issue by berzi** [pydantic/pydantic#4728]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Feel free to suggest a title change, I described it as clearly as I could.

## Problem and proposed solution
Originally discussed in #4720 .

When defining a Pydantic model field as `SomeType`, any subclass of `SomeType` is accepted, but whatever the input, the model will then hold just an instance of `SomeType` itself, losing any additional information the subclass might have had.

I propose support for a field type which would retain the type of the object that is passed in. If this were a generic annotation type called `Subclass`, then a field of type `Subclass[SomeType]` would evaluate to a type of `Union[SomeType, ASubclassOfSomeType, AnotherSubclassOfSomeType]` etc.

From the above definition alone it's quite apparent how it is impossible, without this feature, to properly type a field for all subclasses of a certain type when the subclasses are generated dynamically, or in libraries if the subclasses are defined by consumers of the library who cannot, of course, be expected to modify the library's code to fit their use-case.  
Even where the subclasses should be known at programming time, it would still be an uncomfortable burden to keep the `Union` type updated whenever a subclass must be added or removed.

The only alternative currently supported is an `Any` typing with an accompanying validator, which would work at runtime but does not give any assurance upon linting and type-checking, and also doesn't let IDEs autocomplete properly.

### The problem in code
```py
# For the sake of example, assume a BaseModel with Config.validate_assignment == True

# Doesn't _need_ to be a Pydantic model.
class SomeType(BaseModel):
    some_field_a: str
    some_field_b: str


class ASubclassOfSomeType(SomeType):
    some_field_c: str


class AnotherSubclassOfSomeType(SomeType:
    @validator("some_field_a")
    def validator(cls, v):
        if v == "a":
            raise ValueError("Value must be something other than 'a'!")
        return v


class ModelWithSimpleTypeAnnotation(BaseModel):
    my_type_instance: SomeType


instance_of_some_type = SomeType(some_field_a="a", some_field_b="b")
instance_of_subclass = ASubclassOfSomeType(some_field_a="a", some_field_b="b", some_field_c="c")
instance_of_other_subclass = AnotherSubclassOfSomeType(some_field_a="not a", some_field_b="b")

a = ModelWithSimpleTypeAnnotation(my_type_instance=instance_of_some_type)
b = ModelWithSimpleTypeAnnotation(my_type_instance=instance_of_subclass)
c = ModelWithSimpleTypeAnnotation(my_type_instance=instance_of_other_subclass)

type(a.my_type_instance) == "SomeType"
type(b.my_type_instance) == "SomeType"
type(c.my_type_instance) == "SomeType"

b.some_field_c  # AttributeError
c.my_type_instance.some_field_a = "a"  # Validator does not fire
```

## Proposed interface
I see two possible alternatives.

- A generic type like:
```py
class MyModel(BaseModel):
    my_type_instance: AnySubclassOf[SomeType]
```
- A field annotation like:
```py
class MyModel(BaseModel):
    my_type_instance: Annotated[SomeType, Field(retain_subclass=True)]
```

Personally, I have no strong preference between the two, but I find the first option more elegant and clean to read.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment]
On V2, we have the [`InstanceOf`](https://docs.pydantic.dev/latest/usage/validators/#special-types).

I believe the above should be enough. If that's not the case, please open a new issue. 🙏
