### ISSUE TITLE
Equality checks should use overloaded __eq__ methods of nested classes

### ISSUE THREAD

**Issue by jn-chrn** [pydantic/pydantic#4783]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

## Simple description:
Pydantic does not use overloaded `__eq__` methods of nested class,es and thus, some equality checks have the unexpected behavior of failing, even though they should succeed thanks to custom equality checks. The custom checks are never even called.

## Use case:
We have a case where a class inheriting from `BaseModel` (let's call it `A`) has an overloaded `__eq__` method. This is necessary for our use case. A second class (let's call it `B`) has an attribute of class `A`. If we then perform an equality check of two instances of `B` which are equal according to our specifications, but not strictly equal, the equality checks returns `False`.

## Expected behavior:
When doing an equality check, pydantic should reuse the `__eq__` methods of the nested classes, and not ignore it entirely. 

This is for the moment a wanted behavior in pydantic, but not very explicit from an external point of view. We spent some time debugging our comparison code, before we realised that pydantic just ignores our checks. Are there any plan to change this behavior?

## Our workaround
So far we simply stopped using overloading of the `__eq__` method and instead use our own custom check method. 

### Example Code

```Python
from pydantic import BaseModel


class InnerClass(BaseModel):
    value: float

    def __eq__(self, other):
        """Custom equality check."""
        return abs(self.value - other.value) < 0.01


class OuterClass(BaseModel):
    attribute: InnerClass

    # Uncommenting this method is a workaround to solve the issue
    # def __eq__(self, other):
    #     return self.attribute == other.attribute


base = OuterClass(attribute=InnerClass(value=1))
same_as_base = OuterClass(attribute=InnerClass(value=1))
almost_same_as_base = OuterClass(attribute=InnerClass(value=1.00001))
different_from_base = OuterClass(attribute=InnerClass(value=1234))

assert base == same_as_base
assert base != different_from_base
assert base == almost_same_as_base  # Fail but should not, as the difference is lower than the tolerance
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/jc/miniconda3/envs/aiplan/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0]
                     platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Yes, see #3066, #4780, #4186 and other functions including "`__eq__`", we need to make significant changes to `__eq__` in v2.

**Comment by hramezani** [comment]
It's working as expected in `V2` and doesn't fail
