### ISSUE TITLE
Caching of models for dataclass sub types apparently ignores Config.alias_generator

### ISSUE THREAD

**Issue by 0rd0g** [pydantic/pydantic#4793]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

With classes derived from `BaseModel` which contain `dataclass` types as members, the schemas for those dataclasses depend on the order in which the `BaseModel` classes are declared. Normally this is not an issue, but if you have a `BaseModel` class whose `Config` uses a custom `alias_generator`, this becomes an issue. 
<br/>
The first-declared `BaseModel` class will dictate the cached schema of the contained `dataclass` types. 

### Example Code

```Python
from dataclasses import dataclass
from inflection import camelize
from pydantic import BaseModel, Extra


@dataclass
class Foo:
    first_foo: str
    second_foo: int


class CamelBaseModel(BaseModel):
    class Config:
        alias_generator = camelize
        allow_population_by_field_name = True
        extra = Extra.allow


bar_first = False

if bar_first:
    class Bar(BaseModel):
        first_bar: Foo


    class Baz(CamelBaseModel):
        first_baz: Foo


    BarSchema = Bar.schema()  # OK
    BazSchema = Baz.schema()  # WRONG - Fields of Foo not camel-cased
else:
    class Baz(CamelBaseModel):
        first_baz: Foo


    class Bar(BaseModel):
        first_bar: Foo

    BarSchema = Bar.schema()  # WRONG - Fields of Foo now camel-cased
    BazSchema = Baz.schema()  # OK
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/Nick/miniforge3/lib/python3.9/site-packages/pydantic
               python version: 3.9.1 | packaged by conda-forge | (default, Dec  9 2020, 01:07:47)  [Clang 11.0.0 ]
                     platform: macOS-12.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
ye, the current dataclass implementation has a few problems, see changes in v1.10.2 and #4552.

I'm hoping we can strip away a lot of the logic in V2, see #4670.

But I'm not keen to carry on patching V1 dataclasses unless absolutely necessary. @PrettyWood has done an amazing job as far as possible, but the underlying approach has too many edge cases.

The real solution is to do it right in V2 as per #4670 I'd prefer to remove some features/functionality and have a simpler, more easily maintained implementation.

**Comment by dmontagu** [comment]
As far as I can tell from running the code snippet in the issue body, it seems it behaves correctly in v2 and is now fixed. If you notice any misbehavior in v2 feel free to open a new issue or request that we reopen this one.
