### ISSUE TITLE
Type hints on a Field cause generator to be iterated

### ISSUE THREAD

**Issue by bunchesofdonald** [pydantic/pydantic#4807]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

If you have a model with a field defined with type hints and assign a generator to that field, the generator is called once for each type hint. When inspecting the field after initialization any values that were yielded are missing from the field's data.

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Any, Union, Sequence


def my_range(i: int):
    for i in range(i):
        print(f"yielding {i}")
        yield i


class Other(BaseModel):
    pass


class MyModel(BaseModel):
    data: Union[Other, dict, Any] = Field(default=None)


print("Initializing `MyModel`...")
instance = MyModel(data=my_range(5))
print(f"Printing instance data...")
print([n for n in instance.data])
```

This will print: 

```
Initializing `MyModel`...
yielding 0
yielding 1
Printing instance data...
yielding 2
yielding 3
yielding 4
[2, 3, 4]
```

The only workaround I've found is to add the `Sequence` type as the first item in the type hints:

```python
class MyModel(BaseModel):
    data: Union[Sequence, Other, dict, Any] = Field(default=None)
```

```
Initializing `MyModel`...
yielding 0
yielding 1
yielding 2
yielding 3
yielding 4
Printing instance data...
[0, 1, 2, 3, 4]
```

But if it's after any of the other type hints data is lost:

```python
class MyModel(BaseModel):
    data: Union[Other, dict, Sequence, Any] = Field(default=None)
```

```
Initializing `MyModel`...
yielding 0
yielding 1
yielding 2
yielding 3
yielding 4
Printing instance data...
[2, 3, 4]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /opt/anaconda3/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
It's working as expected in `Pydantic V2`
