### ISSUE TITLE
Dynamic registration for json_encoders

### ISSUE THREAD

**Issue by axonxorz** [pydantic/pydantic#4808]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

I have an application that defines a common `BaseModel` that is used everywhere else in the application, instead of `pydantic.BaseModel`

Part of this `BaseModel` implementation is a configured value for `BaseModel.Config.json_encoders`. Due to application structure, import order and circular imports, not all desired encoders are available at the moment our `BaseModel` is defined, but are added to the dictionary later with a call:

```python
def add_serializer(obj_type: T, serializer: Callable[[T], Any]):
    """Add a serializer function to the registry"""
    json_serializers[obj_type] = serializer
```

Any encoders added this way will _not_ be utilized by Pydantic. [Exploration of the source](https://github.com/pydantic/pydantic/blob/main/pydantic/main.py#L82) shows why this is the case, the encoder is "baked" into the new BaseModel class, with no way to update it.

I have found a workaround: Instead of using `BaseModel.Config.json_encoders`, I override `BaseModel.Config.json_dumps`. The only issue is that Pydantic is passing it's own internal encoder as the `default` argument to it's `json_dumps`. As such, my custom encoder must defer to Pydantic's, otherwise you lose all Pydantic-provided type encoding. My `json_dumps` implementation is:

```python
def json_dumps(obj: Any, **kwargs) -> Optional[str]:
    """Convenience method to encode as JSON string using our encoders configuration, but still allowing a
    caller-specified type encoder."""
    encoder_chain: List[Callable[[Any], Any]] = [json_encoder]
    default = kwargs.pop('default', None)
    if default:
        encoder_chain.append(default)
    def _default(value: Any) -> Optional[Any]:
        for e in encoder_chain:
            try:
                return e(value)
            except TypeError:
                continue
        raise TypeError(f'Don\'t know how to JSON serialize type {value.__class__}')
    return json.dumps(obj, default=_default, **kwargs)
```

This works, but feels janky (maybe just me?), is there a better way to change the encoding configuration after my `BaseModel` class is defined?

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
@axonxorz thank you for the feature request. Let me quote [Pydantic Migration Guide](https://docs.pydantic.dev/2.0/migration/):

> Due to performance overhead and implementation complexity, we have now removed support for specifying `json_encoders` in the model config. This functionality was originally added for the purpose of achieving custom serialization logic, and we think the new serialization decorators are a better choice in most common scenarios. However, if your usage of `json_encoders` is not compatible with the new serialization decorators, please create a GitHub issue letting us know. See [Custom data types](https://docs.pydantic.dev/2.0/usage/types/custom/) for further details.

As `json_encoders` config option isn't supported any more I'm closing this issue. Please, open a new one as the migration guide suggests in case this doesn't work for you.
