### ISSUE TITLE
Optional nested pydantic Model with Union

### ISSUE THREAD

**Issue by mihail-shusharin** [pydantic/pydantic#4810]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

While creating a pydantic class with Optional[Union[...]] field there is an unexpected behavior concluding in ignoring order of classes specified in Union, but only if pydantic with same classes in Union were defined (like using first defined order).

### Example Code

```Python
from pydantic import BaseModel
from pydantic.generics import GenericModel
from typing import Generic, List, Optional, Union, TypeVar
    
_DataT = TypeVar('_DataT')

class SubPydanticClass(GenericModel, Generic[_DataT]):
    val: Optional[_DataT]    
        
class BeforePydanticClass(BaseModel):
    list_field: Optional[Union[SubPydanticClass[List[str]], List[str]]]
        
        
class FirstPydanticClass(BaseModel):
    list_field: Optional[Union[List[str], SubPydanticClass[List[str]]]]
               
first_class_object = FirstPydanticClass(**{'list_field': []})
second_class_object = FirstPydanticClass(**{'list_field': ['val1', 'val2']})
print(first_class_object)
print(second_class_object)

#  list_field=SubPydanticClass[List[str]](val=None)
#  list_field=['val1', 'val2']

---------------- and with commented sub class this behavior expected ------------

from pydantic import BaseModel
from pydantic.generics import GenericModel
from typing import Generic, List, Optional, Union, TypeVar  
    
_DataT = TypeVar('_DataT')

class SubPydanticClass(GenericModel, Generic[_DataT]):
    val: Optional[_DataT]        
        
# class BeforePydanticClass(BaseModel):
#     list_field: Optional[Union[SubPydanticClass[List[str]], List[str]]]       
        
class FirstPydanticClass(BaseModel):
    list_field: Optional[Union[List[str], SubPydanticClass[List[str]]]]      
        
first_class_object = FirstPydanticClass(**{'list_field': []})
second_class_object = FirstPydanticClass(**{'list_field': ['val1', 'val2']})
print(first_class_object)
print(second_class_object)

#  list_field=[]
#  list_field=['val1', 'val2']
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: ""
               python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']

P.S. also happens on macOS and linux
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment]
@mihail-shusharin Can you provide a shorter example? Also, this may be already solved in Pydantic V2. Can you try it out? 🙏

**Comment by lig** [comment]
There is no order difference in the provided example using Pydantic v2.
