### ISSUE TITLE
Cannot View Documentation at docs.pydantic.dev

### ISSUE THREAD

**Issue by kennytrytek-wf** [pydantic/pydantic#4820]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Attempting to navigate to https://docs.pydantic.dev shows an error related to the certificate.

![Screen Shot 2022-12-06 at 11 39 15 AM](https://user-images.githubusercontent.com/1466480/205983347-1568d3ac-c0a1-424a-99ec-d0bfc925accc.png)

### Python, Pydantic & OS Version

```Text
macOS Monterey 12.6
Firefox 107.0.1
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by ziw-liu** [comment]
Can reproduce with MacOS 12.6 and Chrome 107.0.5304.121

**Comment by samuelcolvin** [comment]
Humm, I can't reproduce and I can see lots of traffic to the site since I switched the domain earlier today.

I would expect the problem to resolve itself, if it's not fixed tomorrow please comment again here and include the output of `https://docs.pydantic.dev/cdn-cgi/trace`

**Comment by samuelcolvin** [comment]
well, the site is deployed by CloudFlare, so it's me "rolling my own".

Again, what's the output of `https://www.cloudflare.com/cdn-cgi/trace`?

**Comment by samuelcolvin** [comment]
Also, if it's an issue with the certificate, please can you give some details on the certificate that you're getting.

**Comment by kennytrytek-wf** [comment]
https://www.cloudflare.com/cdn-cgi/trace
```
fl=94f24
h=www.cloudflare.com
ip=205.237.120.225
ts=1670425251.579
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0
colo=STL
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
kex=X25519

```

**Comment by kennytrytek-wf** [comment]
The issue appears to have just been resolved. I can access the site now.

**Comment by sebasibarguen** [comment]
Hi, I know this is an old issue, but I'm also having issues viewing pydantic docs (as well as accessing logfire dashboard). I believe it's cloudflare, but can't be sure.

Both sites simply do not load.

This is the output of my trace:

```
fl=363f207
h=www.cloudflare.com
ip=186.151.92.12
ts=1733269193.734
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
colo=MIA
sliver=none
http=http/3
loc=GT
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
rbi=off
kex=X25519MLKEM768
```
