### ISSUE TITLE
dataclasses with exclude=True in Field end up with those fields in their json

### ISSUE THREAD

**Issue by jacleggmsr** [pydantic/pydantic#4824]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

If I set Field(exclude=True) in a pydantic dataclass then it still gets dumped out to json.

### Example Code

```Python
import json
from pydantic.dataclasses import Field, dataclass
from pydantic.json import pydantic_encoder


@dataclass
class Top:
    x: str
    y: bool = Field(exclude=True)


def main():
    t = Top(x="Hello", y=True)
    as_json_str = json.dumps(t, default=pydantic_encoder)
    as_dict = json.loads(as_json_str)
    
    # This fails, but it shouldn't.
    assert "y" not in as_dict


if __name__ == "__main__":
    main()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: C:\Users\jaclegg\src\AIM-Lab\venv\Lib\site-packages\pydantic
               python version: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.22623-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by soamicharan** [comment]
@jacleggmsr As per code, above `exclude=True` will work for pydantic `BaseModel`, it will not work for `dataclass`

**Comment by lig** [comment]
Fixed in Pydantic v2. Please, use `TypeAdapter`.

```py
from pydantic import TypeAdapter
from pydantic.dataclasses import Field, dataclass


@dataclass
class Top:
    x: str
    y: bool = Field(exclude=True)


assert TypeAdapter(Top).dump_python(Top(x="Hello", y=True)) == {'x': 'Hello'}
assert TypeAdapter(Top).dump_json(Top(x="Hello", y=True)) == b'{"x":"Hello"}'
```
