### ISSUE TITLE
docs: pressing edit button points to 404

### ISSUE THREAD

**Issue by MartinBernstorff** [pydantic/pydantic#4831]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pressing the edit button in the top right points to a blank page.

https://docs.pydantic.dev/usage/validation_decorator/

![image](https://user-images.githubusercontent.com/8526086/206708002-a4db9bd0-286c-4427-b422-ced9e67ebeb1.png)

https://github.com/pydantic/pydantic/edit/master/docs/usage/validation_decorator.md

Seems it points to master instead of main.

### Python, Pydantic & OS Version

```Text
N/A
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
The edit button points to the `master` branch which is not valid and has to be replaced with `main`.
The `mkdocs.edit_uri` config is pointing to `main` in `main` and `1.10.X-fixes`.

main:
https://github.com/pydantic/pydantic/blob/f9853355275f91e80cd3a796559276a472d67e59/mkdocs.yml#L31

1.10.X-fixes:
https://github.com/pydantic/pydantic/blob/a801b0da56519a50084755a9580b6507f981ec76/mkdocs.yml#L31

**Comment by samuelcolvin** [comment]
let's just use `main`, that's a good start.

PR welcome to `main` for this, we can then cherry-pick it onto `1.10.X-fixes`

**Comment by hramezani** [comment]
It is working now!
