### ISSUE TITLE
Unable to reproduce the example from "Usage with mypy"

### ISSUE THREAD

**Issue by doktoren** [pydantic/pydantic#4837]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I cannot get mypy to report the error

```
13: error: "Model" has no attribute "middle_name"
```

from the example in https://docs.pydantic.dev/usage/mypy/ (I copied it into Example Code)

I tested by building the Dockerfile below using `DOCKER_BUILDKIT=1 docker build -t test .`

```
FROM python:3.10.9-buster

RUN pip install mypy==0.991 pydantic==1.10.2

COPY pydantic_mypy_test.py /pydantic_mypy_test.py

RUN mypy \
    --ignore-missing-imports \
    --follow-imports=skip \
    --strict-optional \
    pydantic_mypy_test.py
```

I've also tried other combinations of the versions of python, mypy and pydantic but I haven't found one that worked.

### Example Code

```Python
from datetime import datetime
from pydantic import BaseModel, NoneStr


class Model(BaseModel):
    age: int
    first_name = 'John'
    last_name: NoneStr = None
    signup_ts: datetime | None = None
    list_of_ints: list[int]


m = Model(age=42, list_of_ints=[1, '2', b'3'])
print(m.middle_name)  # not a model field!
Model()  # will raise a validation error for age and list_of_ints
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
             pydantic compiled: True
                  install path: /usr/local/lib/python3.10/site-packages/pydantic
                python version: 3.10.9 (main, Dec  8 2022, 01:57:21) [GCC 8.3.0]
                      platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.28
      optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment]
We should fix that documentation page for V1 and for V2.

PR is welcome. 🙏

**Comment by sydney-runkle** [comment]
@parhamfh,

Any interest in picking this issue up?

**Comment by parhamfh** [comment]
I had a look at this and the given Dockerfile gives this warning rather than the one in the docs:
```shell
pydantic_mypy_test.py:7: error: Class cannot subclass "BaseModel" (has type "Any")  [misc]
 ```

However, the docs do state:
> _Without any special configuration_, mypy catches one of the errors

So if the final `RUN` command in Dockerfile is changed to `RUN mypy pydantic_mypy_test.py` instead it results in:
`pydantic_mypy_test.py:16: error: "Model" has no attribute "middle_name"  [attr-defined]`

So the docs look alright to me, @sydney-runkle and @doktoren!

**Comment by doktoren** [comment]
Thank you for taking a look @parhamfh 
I just tested again. The lack of warning is indeed caused by `--follow-imports=skip` so do I agree that the docs are fine.

When presented with this smoking gun it seems kind of obvious that `--follow-imports=skip` could have the effect of disabling the check :disappointed:  Luckily I've since got rid of `--follow-imports=skip` in the project I'm working on so it nice to know that I now have the support of mypy when working with pydantic :+1:
