### ISSUE TITLE
GoogleStorageDsn

### ISSUE THREAD

**Issue by michealroberts** [pydantic/pydantic#4839]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

I'd like to add a Pydantic network validator that adheres to this general test suite:

```
def test_googlecloudstorage_dsns():
    class Model(BaseModel):
        a: GoogleCloudStorageDsn

    m = Model(a='gs://')
    assert m.a.scheme == 'gs'
    assert m.a.host == 'my-bucket'
    assert m.a.port == None
    assert str(m.a) == 'gs://my-bucket'

    m = Model(a='gs://my-bucket')
    assert str(m.a) == 'gs://my-bucket'

    with pytest.raises(ValidationError) as exc_info:
        Model(a='http://example.org')
    assert exc_info.value.errors()[0]['type'] == 'url_scheme'

    m = Model(a='gs://my-bucket')
    assert m.a.username is None
    assert m.a.password is None
```

I have the code ready to PR, so if the core team is happy I will be glad to make the MR?

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by uriyyo** [comment]
Hi @michealroberts,

You can define your own `pydantic` type:
```py
import pytest
from pydantic import AnyUrl, BaseModel, ValidationError


class GoogleCloudStorageDsn(AnyUrl):
    allowed_schemes = {'gs'}
    user_required = False
    host_required = False


def test_googlecloudstorage_dsns():
    class Model(BaseModel):
        a: GoogleCloudStorageDsn

    m = Model(a='gs://')
    assert m.a.scheme == 'gs'
    assert m.a.host is None
    assert m.a.port is None
    assert str(m.a) == 'gs://'

    m = Model(a='gs://my-bucket')
    assert str(m.a) == 'gs://my-bucket'

    with pytest.raises(ValidationError) as exc_info:
        Model(a='http://example.org')

    assert exc_info.value.errors() == [
        {'ctx': {'allowed_schemes': {'gs'}},
         'loc': ('a',),
         'msg': 'URL scheme not permitted',
         'type': 'value_error.url.scheme'}
    ]

    m = Model(a='gs://my-bucket')
    assert m.a.user is None
    assert m.a.password is None
```
