### ISSUE TITLE
Better jsonschema output compatibility

### ISSUE THREAD

**Issue by cmcconomyfwig** [pydantic/pydantic#4845]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

I would like to submit a PR to enhance the abilities for jsonschema generation; when generating a json, the following fields are currently missing:
* `$id` - typically a URL pointing to a particular repository where one may find this jsonschema instance hosted
* `$schema` - indicates the compatibility level used for jsonschema generation
* `description` - objects may contain a description field, which currently can only be provided by the docstring. If the docstring is to be used for other purposes, then you end up stuck

The Description approach contrasts to the Title field, which defaults to the classname but can be overridden using `Config.title`

To achieve the above features, I propose the following changes:
1. Calling `.schema_json()` now offers an optional kwarg, "flavor"; I only intend to support "flavor='jsonschema'". The default is `None` and doesn't prepend the optional `$` fields.
2. two new fields are added to Config: `uri`, an Optional[str] field which represents the URI to point to with `$schema`; and `description`, which is an Optional[str] which may be used to override the docstring for description.

PR to follow, suggestions welcome.

(PS. I tried to compile this with python 3.8, and `make docs` failed because of a structural matching example - I updated to 3.10 and of course it worked fine.)

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by cmcconomyfwig** [comment]
Please see PR:
https://github.com/pydantic/pydantic/pull/4846

Thank you.

**Comment by ybressler** [comment]
Can we link this issue to #4666  (Or mark as duplicated?)

**Comment by hramezani** [comment]
@cmcconomyfwig `Pydantic V2` alpha version is out. you can test it and if it's not satisfied your requirement please file another issue based on `Pydantic V2`
