### ISSUE TITLE
Should we move all extra items into an `.model_extra` dict model attribute?

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4850]
While working on https://github.com/pydantic/pydantic-core/pull/327 I started wondering whether it would be better to collect all "extra" items in a dict on a special attribute like `.model_extra`.

Concrete example:

```py
from pydantic import BaseModel

class Foobar(BaseModel, extra='allow'):
    x: int

foobar = Foobar(x=1, y='hello, this is an extra argument')

# before
assert foobar.y == 'hello, this is an extra argument'
# with this change, behaviour would become
assert foobar.model_extra['y'] == 'hello, this is an extra argument'
```

This would have a number of advantages:
* we could cope with non-string keys, and string keys which are not valid identifier names
* there's no risk of polluting the namespace or not being able to access items because they shadow method names
* it should be more "typing safe"

There are also some disadvantages:
* it's uglier to do `my_model.model_extra['thing']` than `my_model.thing`
* it's yet another breaking change from v1
* round-trip serialization get's more complicated, https://github.com/pydantic/pydantic-core/pull/327 already has (or will have) a `round_trip` argument to create dicts/json which are valid as input to the model, we would need to switch behaviour in `round_trip=True` mode to explode `model_extra` into the main model dict to match the input format

@tiangolo @hramezani @PrettyWood @adriangb and anyone else interested, let me know what you think.

Overall, I think I'm 👍 on this change, but happy to review feedback.

**Comment by samuelcolvin** [comment]
Twitter poll on whether this is a good idea, [here](https://twitter.com/samuel_colvin/status/1603365558145122305).

One more note: I guess the attribute `.model_extra` will only be a dict if we have `extra='allow'`, empty if there's no extra attributes. Otherwise i guess it should be `None`.

**Comment by adriangb** [comment]
I don't really like that being the only way. I do think it makes sense to keep track of what fields were "extras" for the purposes of exporting/serializing without them, maybe even lazily build a `.model_extra` dict so that users can easily access the extra attributes without having to do some sort of filtering of `__dict__` based on `__fields__`. But I would prefer to preserve the current behavior of unpacking them into the model's namespace, at least by default.

**Comment by hramezani** [comment]
Agree with @adriangb. Having this as an extra attribute would be great but I would prefer to keep the old behavior

**Comment by PrettyWood** [comment]
Agree with @adriangb as well. I understand the pros but it really feels counter-intuitive.

**Comment by samuelcolvin** [comment]
Twitter poll and comments weren't overwhelmingly pro either.

Decision made, we're not doing this.

If people really want this, they can probably add it via a root validator, albeit with a slight performance impact.

**Comment by samuelcolvin** [comment]
Happy to accept a PR to add lazy `.model_extra` if someone wants it.

**Comment by samuelcolvin** [comment]
We might have to do implement some variation on this idea behind a config flag to support the case described in #4617.
