### ISSUE TITLE
BaseModel.json() does not honor pydantic Config for property types

### ISSUE THREAD

**Issue by kfreezen** [pydantic/pydantic#4852]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I expect class A to be serialized the same way by `BaseModel.json()` regardless of whether it is a nested property of a jsonified class or not.

Related issue, submitted to fastapi: tiangolo/fastapi#5689

I'm mostly curious whether you would consider this expected behavior, or a bug. I would have expected it to honor the Config on class A regardless of class B's config.

### Example Code

```Python
from datetime import datetime

from pydantic import BaseModel, Field
from fastapi.encoders import jsonable_encoder


class A(BaseModel):
    class Config:
        json_encoders = {datetime: lambda t: round(t.timestamp())}

    date: datetime = Field(default_factory=datetime.now)


class B(BaseModel):
    a: A = Field(default_factory=A)


a = A()
b = B()

# a.dict() and b.dict() both serialize A the same way
print(a.dict())
print(b.dict())

# jsonable_encoder does not serialize A the same way.
print(a.json())
print(b.json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/kent/Library/Caches/pypoetry/virtualenvs/api-v1-eSVyJk8S-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug 27 2022, 15:26:33) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by tacozMacleo** [comment]
I can confirm this behavior.
I have been hunting the reason for why  `json_encoders` had not been used for a while now.
I do not have the option to set the  `json_encoders` for the Root `BaseModel`, and if this cannot be forced, I would be forced to handle the conversion outside the pydantic, which will defeat the purpose.
