### ISSUE TITLE
Union does not work at the top level

### ISSUE THREAD

**Issue by anneum** [pydantic/pydantic#4856]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

We have a class that contains a union on the top level and the validation fails. As soon as we add a level above (in the example the class ``Foo``) the union works. I expect and hope that the union should also work at the top level.

### Example Code

```Python
import json
from typing import Any, Union
from pydantic import BaseModel

class Data(BaseModel):
    data: Any

class Errors(BaseModel):
    errors: Any

class StreamResponse(BaseModel):
    __root__: Union[Data, Errors]

class Foo(BaseModel):
    bar: StreamResponse

jsonline = json.loads('{"data": "test"}')
# Works
Data(**jsonline)

# Does not work
StreamResponse(**jsonline)

# Also works
jsonline = json.loads('{"bar": {"data": "test"}}')
Foo(**jsonline)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/username/.venv.core/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
                     platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.29
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by uriyyo** [comment]
Hi @anneum,

You should change the way how you call `StreamResponse`. The correct options will be:
```py
StreamResponse(__root__=jsonline)
StreamResponse.parse_obj(jsonline)
```

**Comment by anneum** [comment]
@uriyyo Thanks for your answer. I will use the ``.parse_obj()``.
