### ISSUE TITLE
SecretStr regex constraints

### ISSUE THREAD

**Issue by gui-don** [pydantic/pydantic#4861]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Hello,

I would like to do something like this:
```
private_key: Annotated[SecretStr, Field(regex=_REGEX_KEY)] = None
```
For now, it is ignored: `ValueError: On field "private_key" the following field constraints are set but not enforced: regex.`.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
@gui-don thanks for the feature request. Could you please check that your request is still relevant for Pydantic v2?

**Comment by gui-don** [comment]
Sure, I'm not work currently on the project needing it, but I'll update when I do.

**Comment by Kludex** [comment]
@gui-don I'll be closing this PR for the time being.

If someone else has a real use-case for it, please share it. We'll be happy to reopen it.

**Comment by Callum027** [comment]
My project uses `SecretStr` and regular expressions to define a `StripeApiKey` type.

On Pydantic V1 this worked:

```python
from pydantic import SecretStr

class StripeAPIKey(SecretStr):
    """Secret string type for Stripe API keys.

    Conceals the API key when printed.
    To get the raw value, use the `get_secret_value()` method.
    """

    regex = re.compile("sk_(?:live|test)_[A-Za-z0-9]+")
```

But the constraint is no longer enforced on Pydantic V2 (even with using the `pattern` attribute instead).

I tried defining it like this in Pydantic V2:

```python
from typing import Annotated

from pydantic import Field, SecretStr

StripeAPIKey = Annotated[SecretStr, Field(pattern="sk_(?:live|test)_[A-Za-z0-9]+")]
"""Secret string type for Stripe API keys.

Conceals the API key when printed.
To get the raw value, use the `get_secret_value()` method.
"""
```

But I get the following error:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
stripe.api_key
  Input should be a valid string [type=string_type, input_value=SecretStr('**********'), input_type=SecretStr]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
```

I have other projects still on Pydantic V1 with similar constrained `SecretStr` types. I would really appreciate it if this could be implemented.

**Comment by Callum027** [comment]
I can implement a working constrained type using the following code:

```python
from typing import Annotated

from pydantic import AfterValidator, TypeAdapter, SecretStr

StripeAPIKey = Annotated[
    SecretStr,
    AfterValidator(
        lambda x: (
            TypeAdapter(
                Annotated[str, StringConstraints(pattern="sk_(?:live|test)_[A-Za-z0-9]+")],
            ).validate_python(x.get_secret_value())
        ),
    ),
]
"""Secret string type for Stripe API keys.

Conceals the API key when printed.
To get the raw value, use the `get_secret_value()` method.
"""
```

However, using this method, the input value is exposed when validation fails:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
stripe.api_key
  String should match pattern 'sk_(?:live|test)_[A-Za-z0-9]+' [type=string_pattern_mismatch, input_value='INVALID-API-KEY', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/string_pattern_mismatch
```

To implement it securely, then I'd either need to catch the error and obfuscate the value, or implement a completely custom validator that does not expose the value in the error message.

**Comment by Callum027** [comment]
Hi there, I appreciate the developers are busy but it's been a couple of weeks, just bumping for some visibility. Any chance this could happen?
