### ISSUE TITLE
mypy plugin fails to accept dataclasses as set_validation argument

### ISSUE THREAD

**Issue by carles-protopixel** [pydantic/pydantic#4864]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am using [the strategy described in the docs](https://docs.pydantic.dev/usage/dataclasses/#choose-when-to-trigger-validation) of using `set_validation` to trigger validation of an enhanced dataclass.

The mypy plugin fails to recognize the dataclass as a valid input for `set_validation`. When using mypy (+ pydantic plugin) on the sample file (based on the example in the documentation) I get the following error:

```
mypy test_dataclasses.py
import dataclasses.py:17: error: Value of type variable "DataclassT" of "set_validation" cannot be "User"  [type-var]
Found 1 error in 1 file (checked 1 source file)
```

### Example Code

```Python
import dataclasses
from pydantic.dataclasses import dataclass as pydantic_dataclass, set_validation


@dataclasses.dataclass
class User:
    id: int
    name: str


# Enhance stdlib dataclass
pydantic_dataclass(User)

with set_validation(User, True):
    User(id=1, name='Foo')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/protopixel/Documents/scratch/mypy_pydantic/env/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Oct 25 2022, 13:00:43)  [Clang 12.0.0 (clang-1200.0.32.29)]
                     platform: macOS-11.4-arm64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
