### ISSUE TITLE
Support custom keys for dictionaries

### ISSUE THREAD

**Issue by kdowney-cloudwallcapital** [pydantic/pydantic#4873]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

I would like to have UUID-keyed dictionaries rather than strings, and have not found a way to do this. I'd be happy to put in custom encoders, validators, etc., but it keeps failing with "TypeError: keys must be str, int, float, bool or None, not UUID." There seems to be a low-level check for key types that I haven't been able to bypass.

I am using pydantic 1.10.2.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Do you want to have something like this?

```py
import uuid

from typing import Dict
from uuid import UUID

from pydantic import BaseModel

class Model(BaseModel):
    x: Dict[UUID, str]


m = Model(x={uuid.uuid4(): 'test'})
```

**Comment by dmontagu** [comment]
@hramezani's example seems to work in v1; @kdowney-cloudwallcapital if you can share a code sample that doesn't work for you, that will help us either address the issue or point you in the right direction.

**Comment by sydney-runkle** [comment]
Closing as stale ^^
