### ISSUE TITLE
Cannot roundtrip "Json" type fields

### ISSUE THREAD

**Issue by kdowney-cloudwallcapital** [pydantic/pydantic#4874]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am round-tripping a Pydantic object with a field of type Dict[str, Json] like this:

```
def roundtrip(clazz: Type):
    obj = faker.create_fake_model(clazz)
    raw_json = obj.json()
    obj_out = clazz.parse_raw(raw_json)
    assert obj == obj_out
```

The fake data for the Json dictionary values are generated with Faker:

```
    def json_data_faker(self):
        num_elems = self.faker.pyint(min_value=1, max_value=5)
        keys = [self.faker.pystr() for _ in range(num_elems)]
        values = [self.faker.name() for _ in range(num_elems)]
        fake_dict = dict(zip(keys, values))
        return dumps(fake_dict)
```

I can confirm that at time of output, the field is str -> str, i.e. there is a quoted string containing the generated JSON. But when I inspect raw_json, it's been unpacked into a dictionary already, and so when I call parse_raw() I get errors like:

```
E   modelParameters -> HVGAtZgLTYZVzBlfmqPf
E     JSON object must be str, bytes or bytearray (type=type_error.json)
```

So it seems like the handling is not symmetrical: it encodes as JSON objects, but expects to parse a string.

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: XXX/.venv/lib/python3.10/site-packages/pydantic
python version: 3.10.6 (main, Sep 24 2022, 10:13:12) [Clang 14.0.0 (clang-1400.0.29.102)]
platform: macOS-13.0.1-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by ybressler** [comment]
Can you share the definition of your class `clazz`? Include the `Config` param, if one is defined.

**Comment by kdowney-cloudwallcapital** [comment]
- test helper: https://github.com/cloudwall/serenity.types.python/blob/557c61e6f1437c7fb1bddb01ce53aa876512c66d/tests/serenity_types_tests/testutils/serialization.py
- base class: https://github.com/cloudwall/serenity.types.python/blob/07a3550670e8b3857937fc4deb2c6e1f2b65d1c0/src/python/serenity_types/utils/serialization.py
- class with the issue: https://github.com/cloudwall/serenity.types.python/blob/abf9ef7b9f8ca5ba5bc72e3c915b51554cef2d53/src/python/serenity_types/catalog/model.py

I hope that helps!

**Comment by samuelcolvin** [comment]
This is a known issue, I can't find the issue right now, but it'll be fixed in V2. It's already implemented in https://github.com/pydantic/pydantic-core/pull/327.

**Comment by dmontagu** [comment]
This should be fixed now in v2, please comment here if it is not.
