### ISSUE TITLE
Timeline for Pydantic V2

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4887]
_(This issue exists to track progress towards Pydantic V2)_

See, [this blog post](https://docs.pydantic.dev/blog/pydantic-v2/) for details on the plan for V2.

See, [this project](https://github.com/orgs/pydantic/projects/1) for details on outstanding tasks.

I had originally said I would have pydantic V2 completed by the end of this year (2022), sadly that hasn't happened. I'm sorry about any inconvenience this has caused, I've tried very hard to get the release ready but a number of factors outside the project plan have delayed things 🙏 .

**My aim now is to have V2 released in Q1 2023.**

Thank you for your patience.

**Comment by commonism** [comment]
Hi,

I'd like to add https://github.com/pydantic/pydantic/issues/4617 to the TODO.
Having a powerful Config.extra would allow dealing with objects with additionalProperties|patternProperties mixed with properties, currently this is `__root__ cannot be mixed with other fields`, a real improvement.

**Comment by samuelcolvin** [comment]
Just an update that we're aiming for an alpha release of Pydantic V2 by the end of March.

We're deferring the following until after the alpha release:
* documentation of V2 (I have some exciting news on documentation coming soon)
* the hypothesis plugin
* any compatibility shims for V1
* V2 auto-migration tool, see #5013

**Comment by samuelcolvin** [comment]
First alpha is out 🚀

See [this blog post](https://docs.pydantic.dev/blog/pydantic-v2-alpha/) for more information.

**Comment by samuelcolvin** [comment]
Second alpha came out last week (sorry I didn't comment here).

Plan is to get to a feature freeze on the next couple of weeks, then we'll release one or more betas and solicit testing, but the API shouldn't change.

**Comment by samuelcolvin** [comment]
V2 beta and feature freeze is very close, see #5919.
