### ISSUE TITLE
can't get previous value of the field inside validator

### ISSUE THREAD

**Issue by vanyakosmos** [pydantic/pydantic#4888]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Can't get previous value of the field inside validator ¯\\\_(ツ)_/¯ 

### Example Code

```Python
class Foo(BaseModel):
  a: int
  b: int
  c: int
  
  class Config:
    validate_assignment = True

  @validator("b", always=True)
  def validate_b(cls, v, values, field):
    # field - doesn't have current value
    # values - has values of other fields, but not for 'b'
    if values.get("b") == 0:  # imaginary logic with prev value
      return values.get("b") - 1
    return v


f = Foo(a=1, b=0, c=2)
f.b = 3
assert f.b == -1  # fails
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /usr/local/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Aug 17 2021, 02:38:04)  [GCC 8.3.0]
                     platform: Linux-5.15.49-linuxkit-x86_64-with-glibc2.28
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
This is not a bug, it's the standard behaviour of pydantic.

if you want to get the value before validation, use `pre=True`. In V2 you'll be able to use a wrap validator to access the value before or after validation.

Please don't use "bug" issues to request features or ask questions.

**Comment by gsakkis** [comment]
> if you want to get the value before validation, use pre=True

This doesn't work for me even after changing the decorator to `@validator("b", pre=True)`. Adding a `print(v, values)` statement prints:
```
0 {'a': 1}
3 {'a': 1, 'c': 2}
```
That's the same output as with `pre=False`, it doesn't seem to affect anything here.

**Comment by hramezani** [comment]
What do you want to do exactly @gsakkis ?

**Comment by gsakkis** [comment]
Ensure that the new value of a field is valid based on its current value. Example is a state machine where only a subset of all possible `A -> B` state transitions are allowed. As things stand, I can only do this by overriding `__setattr__`:

```py
def __setattr__(self, key, value):
    if key == "state":
        old_value = self.state
        # check if old_value -> value is valid
    ....
```

**Comment by hramezani** [comment]
Currently, it's not possible to have the current value in the validator and I think this is the intended behavior.

@samuelcolvin I am right here? do we want to change the behavior?

Also, [This stackoverflow answer might be helpful](https://stackoverflow.com/a/74983091/3465428).

**Comment by gsakkis** [comment]
So I chased this down and it goes back to where `validate_assignment` was [initially introduced](https://github.com/pydantic/pydantic/pull/94). There is [this comment](https://github.com/pydantic/pydantic/pull/94#discussion_r146818108) but no justficication of why `exclude={name}` was/is needed or desired.
