### ISSUE TITLE
Field() overrides my __modify_schema__ settings

### ISSUE THREAD

**Issue by alispa** [pydantic/pydantic#4894]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I define a new type, called `Text`, and I need `type=text` in schema to distinguish big text fields from `type=string` fields.
I use` __modify_schema__` and it works well, but if I use `Field(min_lenght=)` it overrides my `__modify_schema__` `type='text'`, and converts it to `'type=string'`.

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Optional

class Text(str):
    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(type="text")  ## <-- (1) I set a new type called 'text'


class Example(BaseModel):
    works: Optional[Text] = Field(title="notes") ## <-- (2) this works nice, returns 'type=text'
    works_not: Optional[Text] = Field(title="notes", min_length=1) ## <-- (3) here, min_length causes the type to be 'type=string' instead of 'type=text'
    class Config:
        orm_mode = True
        anystr_strip_whitespace = True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /ADEV/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
                     platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']

Python 3.11.0rc1
Ubuntu 22.04.1 LTS
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks for reporting.

I don't think we can realistically change this in v1, bit let's make sure it's correct in V2.

**Comment by mryoho** [comment]
@samuelcolvin I also just ran into this. 

In my case, I'm trying to add some examples as shown in the [Custom Data Types example](https://docs.pydantic.dev/usage/types/#custom-data-types), but if that type is then used in a model where a `Field()` is used then the example key/value pair is removed from the `.schema()` from the instantiated model.

Is there any work around right now for this? Like doing additional work in the `__modify_schema__` class method, or does the order of operations just mean that the supplied `Field()` is always going to supplant the work done in `__modify_schema__`?

**Comment by mryoho** [comment]
@samuelcolvin Actually, after playing around a little bit more, I think I'm seeing something a little different here.

I'm working with 1.10.2.

Here's a toy example:
```python
class TelephoneUri(str):
    @classmethod
    def __modify_schema__(cls, field_schema: Dict[str, Any], field: Optional[ModelField]):
        
        field_schema.update(
            max_length=50,
            description='A telephone number in RFC 3966 format.',
            examples=['tel:+1-890-575-8666']
        )
        
# sets schema values by __modify_schema__
class User(BaseModel):
    name: str = Field(..., min_length=1)
    mobile: TelephoneUri

# description from __modify_schema__ is used, rather than that supplied by Field()
class User2(BaseModel):
    name: str = Field(..., min_length=1)
    mobile: TelephoneUri = Field(..., description="hello")

# including min_length or max_length deletes keys not included in Field()
class User3(BaseModel):
    name: str = Field(..., min_length=1)
    mobile: TelephoneUri = Field(..., description="hello", max_length=100)
```

And here's some various instantiated objects:
### User
```python
User(name='Patrick', mobile='tel:+1-800-800-8000').schema()
```
Output:
```
{'title': 'User',
 'type': 'object',
 'properties': {'name': {'title': 'Name', 'minLength': 1, 'type': 'string'},
  'mobile': {'title': 'Mobile',
   'max_length': 50,
   'description': 'A telephone number in RFC 3966 format.',
   'examples': ['tel:+1-890-575-8666'],
   'type': 'string'}},
 'required': ['name', 'mobile']}
```
### User2
```python
User2(name='Patrick', mobile='tel:+1-800-800-8000').schema()
```
Output:
```
{'title': 'User2',
 'type': 'object',
 'properties': {'name': {'title': 'Name', 'minLength': 1, 'type': 'string'},
  'mobile': {'title': 'Mobile',
   'description': 'A telephone number in RFC 3966 format.',
   'max_length': 50,
   'examples': ['tel:+1-890-575-8666'],
   'type': 'string'}},
 'required': ['name', 'mobile']}
```

### User3
```python
User3(name='Patrick', mobile='tel:+1-800-800-8000').schema()
```
Output:
```
{'title': 'User3',
 'type': 'object',
 'properties': {'name': {'title': 'Name', 'minLength': 1, 'type': 'string'},
  'mobile': {'title': 'Mobile',
   'description': 'hello',
   'maxLength': 100,
   'type': 'string'}},
 'required': ['name', 'mobile']}
```

I think that this demonstrates the potential bug with `min_length` or `max_length`.

I'm also curious if the behavior for the `User2` example (that the description does not override) is the intended functionality or not.

**Comment by pyoho-agn** [comment]
@lig Any update on when this might be implemented? Is this going to be a V2 thing?

**Comment by adriangb** [comment]
This seems to have been fixed in V2:

```python
from pprint import pprint
from typing import Any, Optional

from pydantic_core import CoreSchema

from pydantic import BaseModel, Field
from pydantic.annotated import GetCoreSchemaHandler
from pydantic.config import ConfigDict
from pydantic.json_schema import GetJsonSchemaHandler, JsonSchemaValue


class Text(str):
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type: Any, handler: GetCoreSchemaHandler) -> CoreSchema:
        return handler(str)

    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: CoreSchema, handler: GetJsonSchemaHandler) -> JsonSchemaValue:
        field_schema = handler(core_schema)
        field_schema.update(type='text')  ## <-- (1) I set a new type called 'text'
        return field_schema


class Example(BaseModel):
    works: Optional[Text] = Field(title='notes')
    works_not: Optional[Text] = Field(title='notes', min_length=1)

    model_config = ConfigDict(from_attributes=True, str_strip_whitespace=True)


pprint(Example.model_json_schema())
"""
{'properties': {'works': {'anyOf': [{'type': 'text'}, {'type': 'null'}],
                          'title': 'notes'},
                'works_not': {'anyOf': [{'minLength': 1, 'type': 'text'},
                                        {'type': 'null'}],
                              'title': 'notes'}},
 'required': ['works', 'works_not'],
 'title': 'Example',
 'type': 'object'}
 """
```

I'll note that you don't actually need to make `Text` a `str` subclass, I assume you'd want it to act like a string as far as Python is concerned so I would do something like:

```python
from typing import Annotated, Any, Optional

from pydantic_core import CoreSchema

from pydantic import BaseModel, Field
from pydantic.annotated import GetCoreSchemaHandler
from pydantic.config import ConfigDict
from pydantic.json_schema import GetJsonSchemaHandler, JsonSchemaValue


class AsText:
    def __get_pydantic_core_schema__(self, source_type: Any, handler: GetCoreSchemaHandler) -> CoreSchema:
        return handler(source_type)

    def __get_pydantic_json_schema__(self, core_schema: CoreSchema, handler: GetJsonSchemaHandler) -> JsonSchemaValue:
        field_schema = handler(core_schema)
        field_schema.update(type='text')  ## <-- (1) I set a new type called 'text'
        return field_schema


Text = Annotated[str, AsText()]


class Example(BaseModel):
    works: Optional[Text] = Field(title='notes')
    works_not: Optional[Text] = Field(title='notes', min_length=1)
```
