### ISSUE TITLE
Optional fields always generated as None when used with hypothesis

### ISSUE THREAD

**Issue by apirogov** [pydantic/pydantic#4898]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

All optional fields are set to `None` when generating instances with hypothesis.

The strategy for optional fields should be the same as for mandatory, in addition with adding (prepending?) `None` as a possible value to the stream.

### Example Code

```Python
from typing import Optional, Union, Literal

from hypothesis import given, strategies as st

from pydantic import BaseModel
from pydantic import PositiveInt

class MySchema(BaseModel):
    val: PositiveInt
    val2: Literal[1, 2]
    val3: Union[Literal["a"], Literal["b"]]
    val4: Union[None, Literal["value"]]
    val5: Optional[PositiveInt]


@given(st.builds(MySchema))
def test_schema(instance):
    print(instance.json(indent=2))

test_schema()  # notice that val4/val5 (both semantically "optional") are always None/null
```

### Python, Pydantic & OS Version

```Text
            pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /local/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.15 (default, Dec  7 2022, 10:08:58)  [GCC 9.4.0]
                     platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by badge** [comment]
I accidentally created a dupe of this in https://github.com/pydantic/pydantic/issues/4946 but that issue (now closed) does have a nice minimally failing example.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
