### ISSUE TITLE
Mypy strict flag

### ISSUE THREAD

**Issue by mwgamble** [pydantic/pydantic#4900]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Mypy has a `strict` flag, which automatically enables a whole bunch of other flags related to strictness. This is great because it helps to keep my configuration simple, and avoids me needing to be aware of new strictness flags as they are added (or removed) over time. At the time of writing, this flag in mypy enables around a dozen other flags.

The Pydantic mypy plugin has four flags of its own that relate to strictness. I'd like a way to automatically enable all of them with a single `strict` flag, for similar reasons to mypy itself. I don't want to have to worry about maintaining the list over time.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Surely we should just enable all the strict flags if:
1. They're not set to false explicitly
2. Mypy's strict flag is set to true

?

**Comment by mwgamble** [comment]
That sounds like a great solution :heart:

**Comment by samuelcolvin** [comment]
Pr welcome to add this.

**Comment by sydney-runkle** [comment]
I think this was addressed in https://github.com/pydantic/pydantic/pull/9998, closing.
