### ISSUE TITLE
False positive in EmailStr validation report

### ISSUE THREAD

**Issue by jenstroeger** [pydantic/pydantic#4910]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

An email produced by [Hypothesis’ `emails()` strategy](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.emails) fails to validate: `0@a0--0.ac`

### Example Code

```Python
>>> import pydantic
>>> pydantic.__version__
'1.10.4'
>>>
>>> from pydantic import BaseModel, EmailStr
>>> class EmailTest(BaseModel):
...     email: EmailStr
... 
>>> 
>>> EmailTest(email='foo@bar.com')
EmailTest(email='foo@bar.com')
>>> EmailTest(email='0@a0--0.ac')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for EmailTest
email
  value is not a valid email address (type=value_error.email)
>>>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /.../bla/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Dec  7 2022, 02:06:20) [Clang 10.0.1 (clang-1001.0.46.4)]
                     platform: macOS-10.14.6-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Please report to the upstream library.

**Comment by jenstroeger** [comment]
@samuelcolvin would that be the [email-validator](https://github.com/JoshData/python-email-validator) package as per optional dependency?

https://github.com/pydantic/pydantic/blob/08f7cf63c93836ae78514a0a200a6833cbac4b6a/pyproject.toml#L57
