### ISSUE TITLE
At instantiation some field types are changed

### ISSUE THREAD

**Issue by dk766** [pydantic/pydantic#4913]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have a class that extends Base Model and that contains a dict that has a Union of objects:
```
class Forest(BaseModel):

    animals: Dict[str, Union[Horse, Dog]]
```
One important note the Horse and Dog classes are identical with the only difference being the class name:

```
class Mammal(BaseModel):
    id: str
    no_legs: int
```
being the parent class with the child classes:
```
class Horse(Mammal):
    tail_length: float

class Dog(Mammal):
    tail_length: float
```
At instantiation of the Forest class I provide the dict that contains various instance of Horse and Doc instances:
```
a_horse = Horse(id="h_1", no_legs=4, tail_length=1000)
a_dog = Dog(id="d_01", no_legs=4, tail_length=400)
some_animals = {a_horse.id: a_horse, a_dog.id: a_dog}

a_forest = Forest(animals=some_animals)
```
 what I would expect after the instantiation when looking into the `a_forest.animals.values()` to find the instances that I provided
 What I find though is that all the instances are of type Horse:
```        
print(type(a_forest.animals[a_horse.id]))
print(type(a_forest.animals[a_dog.id]))
```
 will display:
```
<class 'test_bug.Horse'>
<class 'test_bug.Horse'>
```
instead of the expected:
```
<class 'test_bug.Horse'>
<class 'test_bug.Dog'>
```

If however I set the dict after the Forest class was already instantiated:
```
        a_forest = Forest(animals={})
        a_forest.animals = some_animals
```
The result is the one expected:
```
<class 'test_bug.Horse'>
<class 'test_bug.Dog'>
```

I created a simple unit test (that I pasted below) with the 2 cases that I described. Both test should pass but currently only one does.

### Example Code

```Python
from typing import Dict, Union
from unittest import TestCase

from pydantic import BaseModel


class Mammal(BaseModel):
    id: str
    no_legs: int


class Horse(Mammal):
    tail_length: float


class Dog(Mammal):
    tail_length: float


class Forest(BaseModel):
    animals: Dict[str, Union[Horse, Dog]]


class TestPydenticInstantiation(TestCase):
    def test_instantiation_1(self):
        a_horse = Horse(id="h_1", no_legs=4, tail_length=1000)
        a_dog = Dog(id="d_01", no_legs=4, tail_length=400)
        some_animals = {a_horse.id: a_horse, a_dog.id: a_dog}
        a_forest = Forest(animals=some_animals)
        print(type(a_forest.animals[a_horse.id]))
        print(type(a_forest.animals[a_dog.id]))

        self.assertIsInstance(a_forest.animals[a_horse.id], Horse)
        self.assertIsInstance(a_forest.animals[a_dog.id], Dog)

    def test_instantiation_2(self):
        a_horse = Horse(id="h_1", no_legs=4, tail_length=1000)
        a_dog = Dog(id="d_01", no_legs=4, tail_length=400)
        some_animals = {a_horse.id: a_horse, a_dog.id: a_dog}
        a_forest = Forest(animals={})
        a_forest.animals = some_animals
        print(type(a_forest.animals[a_horse.id]))
        print(type(a_forest.animals[a_dog.id]))

        self.assertIsInstance(a_forest.animals[a_horse.id], Horse)
        self.assertIsInstance(a_forest.animals[a_dog.id], Dog)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/chifu/.pyenv/versions/3.10.8/envs/prostgres_test/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Nov 30 2022, 12:57:21) [GCC 11.3.0]
                     platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dk766** [comment]
A small comment: I said the in expectations section of the original bug report that I would expect "to find the instances that I provided". This is not entirely true. It is ok If I have there deep copies of the objects that I provided in the constructor BUT it is essential that these new instances contain:
1. the same values (this is true now) 
2. they are also of the same types (this is the one that is NOT fulfilled)

**Comment by samuelcolvin** [comment]
Hi, thanks for reporting, this is a known issue and has been reported many times before, e.g. see #1423. We also talk about this at some length in the docs, see [here](https://docs.pydantic.dev/usage/types/#unions).

In V1.X you can use [`smart_union=True`](https://docs.pydantic.dev/usage/model_config/#smart-union) to resolve the problem.

This is fixed properly in V2.
