### ISSUE TITLE
`__fields_set__` includes excluded extras on copy

### ISSUE THREAD

**Issue by madkinsz** [pydantic/pydantic#4916]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When a model that allows extra fields is copied, excluding an extra field, that field is incorrect included in the new object's `__fields_set__` dictionary which causes problems when attributes are being dynamically retrieved (e.g. https://github.com/PrefectHQ/prefect/issues/8082)

### Example Code

```Python
from pydantic import BaseModel, Extra


class Something(BaseModel, extra=Extra.allow):
    a: int


o1 = Something(a=1, b=2)
assert "b" in o1.__fields_set__, f"'b' should be included in {o1.__fields_set__}"
o2 = o1.copy(exclude={"b"})
assert "b" not in o2.__fields_set__, f"'b' should be excluded from {o2.__fields_set__}"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Jun  1 2022, 06:36:29)  [Clang 12.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I can confirm the bug on `1.10.x`.
On `main`, after we comment [merging exclude](https://github.com/pydantic/pydantic/blob/main/pydantic/main.py#L503-L504) in [Switching to pydantic-core](https://github.com/pydantic/pydantic/commit/594effa279668bd955e98f1cd5c036b37d3bbd40), the `exclude` can't be a `set`(which is a separate problem IMO).
