### ISSUE TITLE
Initiate inherited fields with the base class env_prefix

### ISSUE THREAD

**Issue by devamin** [pydantic/pydantic#4918]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

It would be good if possible to initiate the inherited fields from env variable using the base class env_prefix if the subclass used env_prefix not found example below : 

```python
from pydantic import BaseSettings
import os

class App(BaseSettings):
    class Config:
        env_prefix="APP_"
    log_level:str = "INFO"

class WebApp(App):
    class Config:
        env_prefix="WEB_"
    host:str
    port:int
    
os.environ["APP_LOG_LEVEL"] = "WARN"
os.environ["WEB_HOST"] = "localhost"
os.environ["WEB_PORT"] = "8989"
print(WebApp()) # w.log_level = "INFO" -> w.log_level  = "WARN"
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I think it can make confusion because you defined the `env_prefix` in subclass
