### ISSUE TITLE
Would it be possible to add the fully-qualified path to the `.loc` tuple in `ValidationError`?

### ISSUE THREAD

**Issue by ConnorSMaynes** [pydantic/pydantic#4922]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

When using `pydantic` with `fastapi`, it is sometimes useful to know the exact location of a field which failed validation in a nested model. 

For example, we might have a form client-side which contains a table of objects for the user to add to. Once the user adds a few, they submit the form and the server kicks back an error saying one of the objects in the list in the model had a bad field value. At present, `pydantic` would just say field `x` was the problem and the user would have no idea which row in the table / model in the list contained the field with the issue. They might be able to track it down if the server also returns the field value, but then the size of the field value could become a problem in some cases.

Currently, this is not possible because `pydantic` only seems to return the field name for the field which failed validation instead of the full path to the field. Because the `.loc` property of `ValidationError` is a tuple, it should be possible to make this update without breaking too many people.

Sample Code:
```python
from pydantic import BaseModel, ValidationError


class InnerModel(BaseModel):
    inner: int


class OuterModel(BaseModel):
    outer: InnerModel


try:
    OuterModel(outer=InnerModel(inner="nuts"))
except ValidationError as ve:
    print(repr(ve.raw_errors[0]))
```

Current output:
```text
ErrorWrapper(exc=IntegerError(), loc=('inner',))
```

Desired output:
Note that the location fields are in reverse order `('inner', 'outer')`. I am guessing doing this instead of this, `('outer', 'inner')`, will reduce the chance of breaking others.
```text
ErrorWrapper(exc=IntegerError(), loc=('inner', 'outer'))
```

For arrays/lists, the field name followed by the 0-based index could be used.

This seems like an obvious thing, so apologies if I just have not found an existing request for the same feature.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
This is exactly what we have now, the only reason you're seeing "inner" is because `InnerModel(inner="nuts")` is failing and raising the exception, `OuterModel` is never called.

Try `OuterModel(outer=dict(inner="nuts"))`.

**Comment by T3sT3ro** [comment]
@samuelcolvin I think the demo is misleading. I have the FastAPI app with endpoint such as 

```py
class Settings(BaseModel):
    nfs: NfsSettings = Field(default_factory=NfsSettings)

class NfsSettings(BaseModel):
    enabled: bool = False
    mount_point: str = ""

    @field_validator("mount_point")
    def validate_mount_point(cls, v, info):
        if info.data.get("enabled", False) and not v:
            msg = "Mount point must be specified when NFS is enabled"
            raise ValueError(msg)
        return v
   
    ...

@router.put("/settings")
def update_settings(settingsDto: SettingsDto):
    try:
        settingsDto.to_domain() # converts SettingsDto to Settings
    except ValidationError as e:
        error_details = [{"loc": err["loc"], "msg": err["msg"], "type": err["type"]} for err in e.errors()]
        raise HTTPException(status_code=422, detail=error_details) from None

```

And unfortunately the returned error is looking like:

```json
{
  "detail": [
    {
      "loc": [
        "mount_point"
      ],
      "msg": "Value error, Mount point must be specified when NFS is enabled",
      "type": "value_error"
    },
    ...
  ]
}
```

So I'm missing the "nfs" key in the "loc" array which is a huge pain when I have nested models I parse from JSON in request, because I found no help in how to validate that properly, and I need to handle those errors on the frontend.

How can I solve that?
