### ISSUE TITLE
[1.10.x] Subclassing with Any  

### ISSUE THREAD

**Issue by efisoft-elt** [pydantic/pydantic#4924]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Seems that there is a  `issubclass( Any,  Something)` somewhere when subclassing a Model without redefining the field type.  

Of course the bug is easily fixed if the type is re-defined in subclass (B in the exemple below).  But can be time consuming to find. 

### Example Code

```Python
from pydantic import BaseModel
from typing import Any

class A(BaseModel):
    x: Any = None
class B(A):
    x = 0.0

```
raise: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-17-162f96959d5a> in <module>
----> 1 class B(A):
      2     x = 0
      3

~/anaconda3/lib/python3.7/site-packages/pydantic/main.cpython-37m-darwin.so in pydantic.main.ModelMetaclass.__new__()

~/anaconda3/lib/python3.7/site-packages/pydantic/utils.cpython-37m-darwin.so in pydantic.utils.lenient_issubclass()

~/anaconda3/lib/python3.7/site-packages/pydantic/utils.cpython-37m-darwin.so in pydantic.utils.lenient_issubclass()

~/anaconda3/lib/python3.7/typing.py in __subclasscheck__(self, cls)
    333
    334     def __subclasscheck__(self, cls):
--> 335         raise TypeError(f"{self} cannot be used with issubclass()")
    336
    337     @_tp_cache

TypeError: typing.Any cannot be used with issubclass()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/guieus/anaconda3/lib/python3.7/site-packages/pydantic
               python version: 3.7.1 (default, Dec 14 2018, 13:28:58)  [Clang 4.0.1 (tags/RELEASE_401/final)]
                     platform: Darwin-21.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Please try a newer release.

**Comment by efisoft-elt** [comment]
Just tried.  Some  bug  with 1.10.4

**Comment by hramezani** [comment]
Thanks @efisoft-elt  for reporting!

I can confirm the problem is reproducible on `1.10.x` but I couldn't reproduce it on `main`.

As we are working on `V2` and the plan is to just provide bug fix patches for `1.10.x`, I think we can accept a fix on `1.10.x` if it is an easy one.

**Comment by hramezani** [comment]
@samuelcolvin I think that would be great to have a `1.10.x bug` label. then we can add the label to the bugs that are only reproducible on `1.10.x`

**Comment by samuelcolvin** [comment]
Agreed, feel free to create. Once V2 is released we can have separate templates/forms for different versions.
