### ISSUE TITLE
Add Pydantic to PyPI classifers

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4935]
I think it would be good to add `Framework :: Pydantic` to PyPI's [list of classifers](https://pypi.org/classifiers/), there are lots of other frameworks listed there with much less use (both by dependants count and download count) than Pydantic.

Anyone know what the process is for this?

Should we just add one classifier, or multiple? I guess just one is fine.

**Comment by hramezani** [comment]
Seems we have to add it to https://github.com/pypa/trove-classifiers/

we can have one classifier per version like `Django`. for example:

- `Framework :: Pydantic :: 1.10`
- `Framework :: Pydantic :: 2`
- `Framework :: Pydantic :: 2.0`

**Comment by samuelcolvin** [comment]
Great, I think just major versions.

**Comment by hramezani** [comment]
Sure. I will take care of this

**Comment by samuelcolvin** [comment]
Amazing, please at me in an issue or pr.

**Comment by hramezani** [comment]
Here is the PR https://github.com/pypa/trove-classifiers/pull/127

**Comment by hramezani** [comment]
Closing this as the PR got merged!
