### ISSUE TITLE
Field alias produces warning in VSCode (pyright/pylance)

### ISSUE THREAD

**Issue by AlexanderPodorov** [pydantic/pydantic#4936]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

See example code.

### Example Code

```Python
from pydantic import BaseModel, Field

class Test(BaseModel):
    sender: str = Field(..., alias='from')

    class Config:
        allow_population_by_field_name = True

# Below code produces warning by pylance:
# Argument missing for parameter "from"
t = Test(sender='sender')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
               python version: 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.0.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by AlexanderPodorov** [comment]
Thank you @samuelcolvin !
As far as I understand this is affected by PEP681's `alias`. Generated `__init__` uses aliases, not field names.
There is the workaround using `alias_generator`.

**Comment by samuelcolvin** [comment]
I guess we could add a switch for V2 to generate the signature without aliases, would that help?

**Comment by AlexanderPodorov** [comment]
Yes, can't say exactly, but it should help. I think when we want to create a model using constructor (like in my example), we should always use field names. If we parse a dict or json, we could take `allow_population_by_field_name` into account.

**Comment by AlexanderPodorov** [comment]
I'm not an expert in PEP681, but as far as I understand if we have `Field(..., alias='something')`, static type checker will always take `alias` into account, according to PEP681 spec, right? I'm not sure, but we could also use another name instead of `alias`, so `dataclass_transform` won't take it into account.

**Comment by samuelcolvin** [comment]
There's two things here:
* PEP681 - dataclass transforms, where I think changing behaviour based on a config flag is hard or impossible
* Signature generation, which only works at execution time, this we could change

**Comment by AlexanderPodorov** [comment]
* PEP681: Yes, I agree
* Signature generation: I suspect it works already, that's why I suggested to change `alias` parameter name to something else, so it won't interfere with PEP681, providing editor support with no warnings.
I guess we have to collect people's feedbacks here as well.

**Comment by samuelcolvin** [comment]
I don't want to change the name of the `alias` kwarg just to dupe dataclass transforms.

**Comment by AlexanderPodorov** [comment]
Yes, I understand :) But, in this case, I'm afraid we won't be able to workaround this warning. So `alias_generator` have to be used instead to avoid the warning.
I have faced the situation where `alias` usage is unavoidable. JSON have to contain `from` field, which is also python keyword. According to PEP681's description, `from` will be present in generated `__init__` and this will be wrong too.

**Comment by AlexanderPodorov** [comment]
@samuelcolvin , it looks like new `aliases` attribute from V2 would help, isn’t it? It won’t interfere with `alias` defined in PEP 681.

**Comment by Jarmos-san** [comment]
As of Pydantic v2.10, the issue seems to be fixed! Passing `populate_by_name=True` to `ConfigDict()` seems to satisfy Pyright/Pylance (and mypy too).

Here is a working solution ([half of which was picked from the docs and modified](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.alias_generator)):

```python
from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

class Voice(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    name: str
    language_code: str

voice = Voice(name='Filiz', language_code='tr-TR')
print(voice.language_code)
#> tr-TR
print(voice.model_dump(by_alias=True))
#> {'name': 'Filiz', 'languageCode': 'tr-TR'}
```

**Comment by gaborbernat** [comment]
```python
from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel


class Base(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    foo: str
    bar_of: str


Base(foo="N", barOf="C")
```

This still fails with:

```
❯ pyright magic.py
magic.py:14:1 - error: Argument missing for parameter "bar_of" (reportCallIssue)
magic.py:14:15 - error: No parameter named "barOf" (reportCallIssue)
2 errors, 0 warnings, 0 informations 
```

**Comment by ziyuang** [comment]
It still cannot recognize the field name if there is an alias. What is the current situation?

**Comment by Viicos** [comment]
> What is the current situation?

Same as https://github.com/pydantic/pydantic/issues/4936#issuecomment-1379257253.

See https://github.com/pydantic/pydantic/issues/5893#issuecomment-2512807073 for a workaround.
