### ISSUE TITLE
Raise `AttributeError` while mock.patch method

### ISSUE THREAD

**Issue by lucemia** [pydantic/pydantic#4944]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Cannot mock BaseModel's method for testing

### Example Code

```Python
import pydantic
import mock


class Model:
    def foo(self):
        return "foo"


class PyDanticModel(pydantic.BaseModel):
    def foo(self):
        return "foo"


model = Model()
pydantic_model = PyDanticModel()


with mock.patch(
    "__main__.model.foo",
    autospec=True,
    return_value="bar",
):
    print(model.foo())

with mock.patch(
    "__main__.pydantic_model.foo",
    autospec=True,
    return_value="bar",
):
    print(pydantic_model.foo())

# will raise AttributeError: foo
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/chienhsundavidchen/repo/gstudio/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Nov 15 2022, 05:25:54) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.1-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @lucemia for reporting.

There is a logic to [prevent setting a value for a field that is not in model fields](https://github.com/pydantic/pydantic/blob/main/pydantic/main.py#L174-L176).

We may need to change it here but I am not sure.
Let's see what @samuelcolvin thinks.

You can fix the error by defining your model like:
```
class PyDanticModel(pydantic.BaseModel):
    def foo(self):
        return "foo"

    class Config:
        extra = pydantic.Extra.allow
```

**Comment by samuelcolvin** [comment]
humm, not sure how we would change this? `__setattr__` on a field that doesn't exist, **should** fail.

The other work around is to (temporarily) set `config.validate_assignment = False`, but the real solution is to avoid the need to mock a model.

Closing this for sake of tidiness, but happy to reconsider if someone can think of a logical work around.

Also worth noting that this logic will change a lot in V2 and fixing this might be easier or harder.

**Comment by Korben11** [comment]
`__setattr__` doesn't take into consideration methods.  I think it should account for `callables`.
https://docs.python.org/3/library/unittest.mock.html#patch-object
