### ISSUE TITLE
TypeHint Union[None, <anything>] is not converted correctly

### ISSUE THREAD

**Issue by janluak** [pydantic/pydantic#4952]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hey guys,

thanks for the nice tool!

I figured the type hint of `Union[None, <anything>]` is converted wrongly in a pydantic dataclass:
If you check the example, inspect.signature if collecting both items of `Union` while the created schema of `pydantic` (which I used again in a latter stage via `openapi_schema_pydantic` for api creation and stumbled upon it) is missing the `type: null`.

I hope this is an easy fix?
Thanks a lot!
janluak

### Example Code

```Python
from typing import Union, Literal, Iterable
import inspect

from pydantic import StrictStr
from pydantic.dataclasses import dataclass


@dataclass
class Data:
    a: str
    b: Union[None, str] = None
    c: Union[Literal[None], StrictStr] = None


Data(a="a", b=None, c=None)
Data(a="a", b="b", c="c")

signature = inspect.signature(Data)

original_b_signature = signature.parameters["b"].annotation.__dict__["__args__"]
# (<class 'NoneType'>, <class 'str'>)

pydantic_b_signature = Data.__pydantic_model__.schema()["properties"]["b"]
# {'title': 'B', 'type': 'string'}

assert isinstance(pydantic_b_signature["type"], Iterable) and not isinstance(pydantic_b_signature["type"], str)
assert len(original_b_signature) == len(pydantic_b_signature["type"])
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: .../python3.8/site-packages/pydantic
               python version: 3.8.9 (default, Mar 30 2022, 13:51:16)  [Clang 13.1.6 (clang-1316.0.21.2.3)]
                     platform: macOS-13.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Is it just the signature you're saying is wrong?

**Comment by janluak** [comment]
The signature from inspect is correct but the schema generated from pydantic is wrong.

The expected schema should contain `{"type": [null, "string"]}` but is missing the null.

**Comment by samuelcolvin** [comment]
This should be fixed in v2, I think it's too late to change this in v1.x.

**Comment by janluak** [comment]
uh, that's quite a bummer but understandable...

With the hint of v2 I just found this section: https://docs.pydantic.dev/blog/pydantic-v2/#required-vs-nullable-cleanup
I guess this will solve the issue. @samuelcolvin can you flag this issue to be reevaluated once v2 is out?

**Comment by janluak** [comment]
just scanned a bit through your article - thanks man!
for all your work and also the quick replies 👍

**Comment by samuelcolvin** [comment]
Checkout #4947, I haven't reviewed it fully, but might already solve this for V2.

**Comment by janluak** [comment]
I just checked it out and ran the code provided above again the mr from #4947, doesn't look on first glance:
```
Traceback (most recent call last):
  File ".../pydantic/check.py", line 8, in <module>
    class Data:
  File ".../pydantic/pydantic/dataclasses.py", line 230, in dataclass
    return wrap(_cls)
  File ".../pydantic/pydantic/dataclasses.py", line 224, in wrap
    _add_pydantic_validation_attributes(cls, the_config, should_validate_on_init, dc_cls_doc)
  File ".../pydantic/pydantic/dataclasses.py", line 335, in _add_pydantic_validation_attributes
    setattr(dc_cls, '__pydantic_model__', create_pydantic_model_from_dataclass(dc_cls, config, dc_cls_doc))
  File ".../pydantic/pydantic/dataclasses.py", line 393, in create_pydantic_model_from_dataclass
    model: Type['BaseModel'] = create_model(
  File ".../pydantic/pydantic/main.py", line 697, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
  File ".../pydantic/pydantic/main.py", line 94, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: __init_subclass__() takes no keyword arguments
```

**Comment by janluak** [comment]
btw, also for my own understanding:

checking out again https://docs.pydantic.dev/blog/pydantic-v2/#required-vs-nullable-cleanup:
`f2: str | None  # required, can be None - same as Optional[str] / Union[str, None]`

From a python side I completely go along with the equivalence of `Optional[str]` and `Union[str, None]`. Yet, from a json schema side I would rather think of the following:
```
Optional[str]
{
    "properties": {
        "f2": {
            "type": [
                "null",
                "string"
            ]
        }
    },
    "required": []
}

Union[str, None]
{
    "properties": {
        "f2": {
            "type": [
                "null",
                "string"
            ]
        }
    },
    "required": [
         "f2"
    ]
}
```

Especially for input validation I think it makes quite a difference if a key must be present (but may be null) or if it doesn't has to be there at all (which would require within python to then set a default, probably `None`, but best specified).
Theoretically, this would not allow the version `f2: Optional[str]` but only `f3: Optional[str] = None`...
I don't know what the python's specs say what `f2: str | None` is equivalent to `Optional[str]` or `Union[str, None]` but this seems to bit quite tricky as well...

**Comment by samuelcolvin** [comment]
This has been a discussion for years on Pydantic, e.g. see #1223. While I'm happy to repeat what we've decided, I'm not really interested in re-opening the discussion.

We're copying what dataclasses do for 2 reasons:
1. Because it makes the most sense
2. Because it's what dataclasses do

The biggest problem with this whole discussion is the `Optional` type, which does not necessarily mean a field is "optional", but that's solve by preferring `X | None` or `Union[X, None]`.

Therefore:
* **For an argument/field to be not required, it must have a default.**
* **`Union[X, None]`, `X | None` and `Optional[None]` are identical**

**Comment by janluak** [comment]
Thanks, makes sense. Not using optional myself anyways, just stumbled upon this now.

I'll wait for v2 for be released, thanks for all your effort 🙏
