### ISSUE TITLE
Assigning a default string value to type "import_string" doesn't result in evaluation

### ISSUE THREAD

**Issue by ybressler** [pydantic/pydantic#4957]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Born from this PR: https://github.com/pydantic/pydantic/pull/4901

**Assigning a default string value doesn't result in evaluation:**
```python3
from pydantic import BaseModel, ImportString


class ImportThingsWithDefault(BaseModel):
    obj: ImportString = 'math.cos'


# Using A default value doesn't cause automatic an import
my_cos = ImportThingsWithDefault()
print(my_cos.obj, type(my_cos.obj))

try:
    cos_of_0 = my_cos.obj(0)
except (NameError, TypeError) as e:
    print(e)


# Typically, you can overcome this with config settings
# Unfortunately this does not work here.
class ImportThingsWithDefaultValidated(BaseModel):
    obj: ImportString = 'math.cos'

    class Config:
        validate_all = True


my_cos_v = ImportThingsWithDefaultValidated()
print(my_cos_v.obj, type(my_cos_v.obj))

try:
    cos_of_0 = my_cos_v.obj(0)
except (NameError, TypeError) as e:
    print(e)
```

Related to https://github.com/pydantic/pydantic/issues/537

> Currently there's no way to run validation on defaults in V2, maybe we should add it?

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Currently we don't have validation of defaults at all in pydantic-core, probably best if you create an issue over the.

**Comment by samuelcolvin** [comment]
See https://github.com/pydantic/pydantic-core/issues/358
