### ISSUE TITLE
Serialization of ImportString does not have default behavior

### ISSUE THREAD

**Issue by ybressler** [pydantic/pydantic#4958]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Currently, if your model has a field whose type is `ImportString`, you will not be able to encode to a Json unless you employ a clever workaround:
```
from pydantic import BaseModel, ImportString
from types import BuiltinFunctionType


# The following class will not successfully serialize to JSON
# Since "obj" is evaluated to an object, not a pydantic `ImportString`
class WithCustomEncodersBad(BaseModel):
    obj: ImportString

    class Config:
        json_encoders = {
            ImportString: lambda x: str(x)
        }


# Create an instance
m = WithCustomEncodersBad(obj='math.cos')

try:
    m.json()
except TypeError as e:
    print(e)

# Let's do some sanity checks to verify that m.obj is not an "ImportString"
print(isinstance(m.obj, ImportString))
print(isinstance(m.obj, BuiltinFunctionType))


# So now that we know that after an ImportString is evaluated by Pydantic
# it results in its underlying object, we can configure our json encoder
# to account for those specific types
class WithCustomEncodersGood(BaseModel):
    obj: ImportString

    class Config:
        json_encoders = {
            BuiltinFunctionType: lambda x: str(x)
        }


m = WithCustomEncodersGood(obj='math.cos')
print(m.json())
```
**_We should instead implement a custom serializer to properly serialize an `ImportString`._**

> `json_encoders` like this is going in V2, see https://github.com/pydantic/pydantic-core/pull/327.
>
> Also we should probably add a custom serializer to ImportString to do this automatically.
> Depends on: https://github.com/pydantic/pydantic-core/pull/327

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
We're still working on serialization in V2, should be fixed soon.

**Comment by dmontagu** [comment]
@ybressler for what it's worth, here's a stab at handling this:
```diff
diff --git a/pydantic/types.py b/pydantic/types.py
index e9ac798b..e4875a12 100644
--- a/pydantic/types.py
+++ b/pydantic/types.py
@@ -7,6 +7,7 @@ from datetime import date, datetime
 from decimal import Decimal
 from enum import Enum
 from pathlib import Path
+from types import ModuleType
 from typing import (
     TYPE_CHECKING,
     Any,
@@ -288,12 +289,21 @@ else:
         def __get_pydantic_core_schema__(
             cls, source: type[Any], handler: GetCoreSchemaHandler
         ) -> core_schema.CoreSchema:
+            def serialize_import_string(v: Any) -> str:
+                if isinstance(v, ModuleType):
+                    return v.__name__
+                elif hasattr(v, '__module__') and hasattr(v, '__name__'):
+                    return f'{v.__module__}.{v.__name__}'
+                else:
+                    return str(v)
+
+            serialization = core_schema.plain_serializer_function_ser_schema(serialize_import_string)
             if cls is source:
                 # Treat bare usage of ImportString (`schema is None`) as the same as ImportString[Any]
-                return core_schema.general_plain_validator_function(lambda v, _: _validators.import_string(v))
+                return core_schema.general_plain_validator_function(lambda v, _: _validators.import_string(v), serialization=serialization)
             else:
                 return core_schema.general_before_validator_function(
-                    lambda v, _: _validators.import_string(v), handler(source)
+                    lambda v, _: _validators.import_string(v), handler(source), serialization=serialization
                 )
 
         def __repr__(self) -> str:
```

This results in `{"obj":"math.cos"}` at the end of your script above.

I am spread a bit thin right now to get this over the line but if you want to open a PR and add some tests we could probably get something like this merged.

**Comment by dmontagu** [comment]
I'm marking this as a "non-breaking-change", indicating it can be addressed after the v2 release, because right now serialization will just fail and I consider it a non-breaking change to make serialization go from failing to working by default. Also serializing an ImportString is already a very niche issue so I'm not concerned that changing the default behavior will cause widespread problems.
