### ISSUE TITLE
Add a host/domain name type

### ISSUE THREAD

**Issue by gui-don** [pydantic/pydantic#4966]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Hello 👋 

I would like to validate only the host support of a URL (domain name). For now, it seems I'm forced to do something like:

`endpoint_host: constr(regex=_host_regex))`

Not the intended usage…

I would like to use a type to validate a host only, something like:

`endpoint_host: Union[IPvAnyAddress, DomainName]`

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I'm afraid you'll need your own logic for this.

URL validation is moving into pydantic-core implemented in rust for V2.

Remember the definition of what's allowed in a domain and how it's encoded depends on the scheme.

You might look at urllib3 or similar to see if there's a way to validate domains you can reuse in a functional validator.
