### ISSUE TITLE
Getting dataclass_transform() got an unexpected keyword argument 'field_specifiers' when using v1.1.04

### ISSUE THREAD

**Issue by iudeen** [pydantic/pydantic#4968]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Getting 
```
dataclass_transform() got an unexpected keyword argument 'field_specifiers'
```
When starting a FastAPI app (v0.89.1).

### Example Code

```Python
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware


app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=Service.CORS_METHODS,
    allow_headers=["*"],
)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4                                                               
 pydantic compiled: True                                                                 
 install path: D:\ProgramData\Anaconda3\envs\event-engine\Lib\site-packages\pydantic
 python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]     
 platform: Windows-10-10.0.19045-SP0                                            
 optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by PrettyWood** [comment]
You are using pydantic 1.10.1

**Comment by iudeen** [comment]
No I actually got this error in 1.10.4

**Comment by samuelcolvin** [comment]
Then you have an outdated version of typing-extensions.
