### ISSUE TITLE
Excluded fields appear while using the copy function

### ISSUE THREAD

**Issue by joel314** [pydantic/pydantic#4969]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

In the code snippet below, the attribute `w` of the Pydantic class `A` is copied, even though it is marked as excluded. The output of the script gives: `y=1 z=A(w=2)`. 

When `y: int` is replaced by `y: int = Field(..., exclude=False)`, the program takes into account the exclusion of `w` and returns the expected result: `y=1 z=A()`.

I would have expected that `w` is never copied, regardless of the way the attribute `y` is declared. 

### Example Code

```Python
from pydantic import BaseModel, Field


class A(BaseModel):
    w: int = Field(..., exclude=True)


class B(BaseModel):
    y: int
    z: A


b1 = B(y=1, z=A(w=2))
b2 = b1.copy()
print(b2)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 1.10.4
            pydantic compiled: True
                 install path: C:\Users\...\venv\Lib\site-packages\pydantic
               python version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [x] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @joel314 for reporting this issue!

I can confirm the but on `1.10.x` and I think it was introduced in https://github.com/pydantic/pydantic/commit/7d9614e3f8811c624cdce11867bb8bd607fef5b8

[We are going to remove or change .copy in V2](https://docs.pydantic.dev/blog/pydantic-v2/#model-namespace-cleanup). So maybe we can accept a fix just for `1.10.x` if it is an easy one

**Comment by joel314** [comment]
Thanks a lot @hramezani , that sounds good.

**Comment by gsakkis** [comment]
Not sure if it's the same issue or I should open a new one but I actually expect the opposite: copy should copy all fields. `exclude` is a property of serialization, not of model instance state. Pydantic v2 does the right (IMO) thing by ignoring `exclude`, v1 doesn't:

```py
from pydantic import BaseModel, Field


class MyModel(BaseModel):
    included: int
    excluded: int = Field(exclude=True)


model = MyModel(included=1, excluded=2)
model2 = model.copy()
assert str(model) == str(model2), (str(model), str(model2))
```

Output:
- v1: `AssertionError: ('included=1 excluded=2', 'included=1')`
- v2: Passes (with a deprecation warning about using `model_copy` in place of `copy`).

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
