### ISSUE TITLE
[typing] Extra.allow does not changed hinted signature to include **kwargs

### ISSUE THREAD

**Issue by ringohoffman** [pydantic/pydantic#4971]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Models defined with `extra=pydantic.Extra.allow` do not modify the `__init__` signature to indicate that arbitrary kwargs are supported, which leads to static typing errors when using arbitrary kwargs.

I have a feeling this could be fixed by way of `ParamSpec`.

### Example Code

```Python
import pydantic


class MyMyodel(pydantic.BaseModel, extra=pydantic.Extra.allow):
    an_arg: int


model1 = MyMyodel(an_arg=1)
model2 = MyMyodel(an_arg=1, another_arg=1)  # Pylance: No parameter named "another_arg"
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /Users/ringo/opt/anaconda3/envs/glass310/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Oct 24 2022, 11:04:34) [Clang 12.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I think this is just a limitation of dataclass_transforms PEP 681, nothing pydantic can do about it.
