### ISSUE TITLE
BaseSettings with dict data type skipping the validator with pre enabled

### ISSUE THREAD

**Issue by alexanderluiscampino** [pydantic/pydantic#4974]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am trying to set up a `BaseSettings` model which retrieves the values from env. Also, I am adding a validator to certain fields, with pre=true, that basically fetches more information for that one field. 

If I set my field to `Dict[str, Any]` the model errors immediately, because the value of the env variable is indeed a string. But I'd expect it to go through the validator 1st, before attempting to parse it. This is the error I am getting: 

```
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 197, in pydantic.env_settings.EnvSettingsSource.__call__
  File "pydantic/env_settings.py", line 131, in pydantic.env_settings.Config.parse_env_var
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/allegro-source-classifier.build/test_.py", line 26, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 75, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 200, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing env var "credentials_secret_name"
```

Funny enough, if I set my field to be `CREDENTIALS: Union[Dict[str, Any] | str]` this will work.  The problem here is that I then have the wrong data type for that field, which creates some hinting issues in other places. 

### Example Code

```Python
import os
from typing import Any, Dict

import pydantic

os.environ['CREDENTIALS_SECRET_NAME'] = 'secret_name'

class Settings(pydantic.BaseSettings):
    CREDENTIALS: Dict[str, Any]= pydantic.Field(
        default=..., env="CREDENTIALS_SECRET_NAME"
    )


    @pydantic.validator('CREDENTIALS', pre=True)
    def fetch_secret(cls, value: str) -> Dict[str, Any]:
        """
        Loads the secret from secrets manager post validation of the env variable
        """
        print(f"Fetching credentials for the secret: {value}")
        return {
            "username": "John",
            "password": "MyPassword!"
        }


settings = Settings()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
pydantic compiled: True
install path: /usr/local/lib/python3.10/site-packages/pydantic
python version: 3.10.9 (main, Jan 11 2023, 15:12:53) [GCC 10.2.1 20210110]
platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
This is because for "complex" fields we try to parse them as JSON within settings, before beginning the validation logic.

There's no easy way around this for V1, should be solved in V2.
