### ISSUE TITLE
difference between how float('infinity') and np.inf are treated when it comes to equality comparison

### ISSUE THREAD

**Issue by Joshuaalbert** [pydantic/pydantic#4979]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When exploring how pydantic might be sucseptible to the whims of the serialiser used I came accross these interesting unexpected behaviours:
1. There is no equality between base models including `float('infinity')` and `float('nan')`, while there IS for those containing `np.inf` and `np.nan`.

### Example Code

```Python
from pydantic import BaseModel
import numpy as np

class A(BaseModel):
    a: float
    b: float
    c: float

# success!
s = A(a=np.nan, b=np.inf, c=-np.inf)
t = A(a=np.nan, b=np.inf, c=-np.inf)
assert s == t

# fail! Expected comparison to work
s = A(a=float('nan'), b=float('inf'), c=-float('inf'))
t = A(a=float('nan'), b=float('inf'), c=-float('inf'))
assert s == t
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /home/albert/miniconda3/envs/tha_py/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
                     platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [X] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Well, arguably this is to be expected since `float('nan') == float('nan')` is false, then again `numpy.nan == numpy.nan` is also false.

**Comment by Joshuaalbert** [comment]
Is there an explanation for why the comparison is passing for numpy nan and not for python nan, while they follow the same convention of comparison on bare objects?

**Comment by ybressler** [comment]
This is a well known python behavior:
```
>> float('inf') == float('inf')
False
```

**Comment by ybressler** [comment]
Suggesting we close this issue @samuelcolvin 

Send me a message on twitter @Joshuaalbert if you want to discuss further + build a workaround.

**Comment by samuelcolvin** [comment]
Just need to check why it's behaving differently for `np.nan`, then we can close.

**Comment by Kludex** [comment]
On V2 they have the same behavior. Shall we close this @samuelcolvin ?

**Comment by Kludex** [comment]
Since everything was answered here (I think), I'll be closing this issue.

Please let me know if we should reopen it.
