### ISSUE TITLE
Empty string `""` coerced to `{}` when field type is `dict[str, Any]`

### ISSUE THREAD

**Issue by SRv6d** [pydantic/pydantic#4993]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Empty string values for fields typed as any type of `dict` are converted to empty dicts `{}`.
I'm aware that pydantic coerces types when it can and both values are still _falsy_, but converting an empty sting to and empty dict seems a bit far fetched to me. Is this intended behaviour ? 

### Example Code

```Python
Python 3.11.0 (main, Nov 22 2022, 14:51:37) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydantic
>>> from typing import Any
>>> 
>>> class ExampleModel(pydantic.BaseModel):
...     dict_w_str_any: dict[str, Any]
... 
>>> example = ExampleModel(dict_w_str_any="")
>>> print(example)
dict_w_str_any={}
>>> 
>>> ExampleModel(dict_w_str_any="NonEmpty")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ExampleModel
dict_w_str_any
  value is not a valid dict (type=type_error.dict)
>>>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
pydantic compiled: True
install path: <project>/.venv/lib/python3.11/site-packages/pydantic
python version: 3.11.0 (main, Nov 22 2022, 14:51:37) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by SRv6d** [comment]
Alright, I figured this might be fixed with V2, thank you for confirming.
I also just realized that it is standard python behavior to create an empty dict if you pass an empty string to the `dict()` constructor: `dict("") == {}` is `True`. I'm sure there is some rationale behind it, but it seems somewhat unintuitive since you otherwise cannot create a dict from just a string.

**Comment by samuelcolvin** [comment]
> but it seems somewhat unintuitive since you otherwise cannot create a dict from just a string

Totally agree, but this will be why Pydantic has this behaviour.

---

The reason is that `dict` takes any iterable and tries to extract key/value pairs from each element, failing if any element is not a valid key/value pair.

Empty iterables like like `[]`, `()` and `''` don't have an invalid elements, thus an empty dict is successfully created.

Effectively, `dict` does

```py
def dict(thing):
    new_dict = {}
    for k, v in thing:
        new_dict[k] = v
    return new_dict
```

**Comment by SRv6d** [comment]
While I know that python essentially treats strings an iterable containing characters, I tend to forget about it in practice. If you have that in mind, `dict` behavior makes sense, although just raising a `TypeError` here would seem more intuitive to me. Thank you for the refresher, looking forward to pydantic v2.
