### ISSUE TITLE
Model from BaseSettings ignores env_prefix and Fields env key when initializing from Dict

### ISSUE THREAD

**Issue by hannes-tw** [pydantic/pydantic#4996]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I try to handle configs with the `BaseSettings` class and there seems to be an issue with the enforcement of the environment `env_prefix` when initializing a model instance from an unpacked dictionary. The same is true if I try to specify things manually under `class Config: fields=` in line with the documentation.  In both cases, the modified configuration setting seems to be ignored and I get `ValidationError`s for the respective fields. 

Everything works fine if the relevant variables are only present as environment variables in my terminal session. I can also work around this issue by explicitly declaring aliases either under `class Config: fields` or when defining the attributes themselves. However, if I understand correctly this not the preferred way to do things...

 

### Example Code

```Python
from pydantic import BaseSettings


class DevConfig(BaseSettings):
    env_state: str
    debug: bool
    class Config:
        env_prefix = "dev_"
        # same issue when using fields instead
        # fields = {"env_state": {"env": "dev_env_state"}, "debug": {"env": "dev_debug"}}


cfg_raw = {"dev_env_state": "dev", "dev_debug": True}
DevConfig(**cfg_raw)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
pydantic compiled: True
install path: .../miniconda3/envs/.../lib/python3.10/site-packages/pydantic
python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]
platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
`env_prefix` is just for environment variables, as the name and the documentation suggestions.

**Comment by hannes-tw** [comment]
> `env_prefix` is just for environment variables, as the name and the documentation suggestions.

Thanks a lot for the quick response and the clarification - and in this case sorry to bother, this was not on my conceptual map at all.

**Comment by samuelcolvin** [comment]
No problem, use `alias` if you want to use other names for arguments.
