### ISSUE TITLE
Validation error when union contains stdlib dataclass and it's subclass

### ISSUE THREAD

**Issue by matsjoyce-refeyn** [pydantic/pydantic#4997]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When a union is used which contains a stdlib dataclass (`DC`) and a subclass of that dataclass (`S`) in that order, the validators for `DC` are used when validating `S`. This is because `DC`s `__get_validators__` is accessible on `S`, and so `S` is never processed by the dataclass machinery (`find_validators` is not called on `S`).

### Example Code

```Python
import dataclasses
from typing import Union


@dataclasses.dataclass
class DC:
    a: int


@dataclasses.dataclass
class S(DC):
    b: int


import pydantic
import pydantic.dataclasses


class ForbidExtraKeywordDataclassConfig:
    extra = pydantic.config.Extra.forbid


@pydantic.dataclasses.dataclass(config=ForbidExtraKeywordDataclassConfig)
class Base:
    x: Union[DC, S]


# And trigger the bug
Base(x=S(a=1, b=2))

# Output is:
# Traceback (most recent call last):
#   File "c:/Users/matthew.joyce/Repos/manufacture_tools/pydantic_test.py", line 29, in <module>
#     Base(x=S(a=1, b=2))
#   File "pydantic\dataclasses.py", line 319, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
#     # function whose type depends on its parameters.
#   File "pydantic\dataclasses.py", line 422, in pydantic.dataclasses._dataclass_validate_values
#     # given, use it.  If not, call the factory.
# pydantic.error_wrappers.ValidationError: 2 validation errors for Base
# x -> b
#   extra fields not permitted (type=value_error.extra)
# x -> b
#   extra fields not permitted (type=value_error.extra)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: C:\Users\matthew.joyce\Repos\manufacture_tools\venv\env_venv\Lib\site-packages\pydantic
               python version: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Humm, weird.

Does it happen if `Base` is a model? Does the order of args to the union affect the result?

**Comment by matsjoyce-refeyn** [comment]
Using a model instead (rest of the code is the same):

```python
class Base(pydantic.BaseModel):
    class Config:
        extra = pydantic.config.Extra.forbid

    x: Union[DC, S]
```
results in
```
Traceback (most recent call last):
  File "c:/Users/matthew.joyce/Repos/manufacture_tools/pydantic_test.py", line 27, in <module>
    Base(x=S(a=1, b=2))
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Base
x -> b
  extra fields not permitted (type=value_error.extra)
x -> b
  extra fields not permitted (type=value_error.extra)
```

If the order of the union args is flipped, then the problem does not occur, because pydantic sees the subclass first.

**Comment by dmontagu** [comment]
For what it's worth, this seems fixed in v2

```python
import dataclasses
from typing import Union


@dataclasses.dataclass
class DC:
    a: int


@dataclasses.dataclass
class S(DC):
    b: int


import pydantic
import pydantic.dataclasses



@pydantic.dataclasses.dataclass(config=dict(extra='forbid'))
class Base:
    x: Union[DC, S]


# No longer triggers the bug
Base(x=S(a=1, b=2))
```

I will close the issue as we probably won't be making any more changes to v1 dataclasses (due to the potential for unexpected _new_ problems, since our efforts are focused on v2 now).
