### ISSUE TITLE
[PYD-140] use_enum_values config does not work for collections of enums in subclasses

### ISSUE THREAD

**Issue by jsamoocha** [pydantic/pydantic#5005]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When a subclass of a model accesses a superclass's collection of enums, the enums are returned instead of their values.

### Example Code

```Python
from pydantic import BaseModel
from typing import List
from enum import Enum

class Foo(Enum):
    FOO = 'foo'
    BAR = 'bar'

class FooModel(BaseModel):
    foo: Foo
    foo_list: List[Foo]

class FooExt(FooModel):
    class Config:
        use_enum_values = True

f = FooExt(foo='foo', foo_list=['foo', 'bar'])
{'foo': f.foo, 'foo_list': f.foo_list, 'f_dict': f.dict()}
```

In the code example above, I'd expect the output to be
```
{'foo': 'foo',
 'foo_list': ['foo', 'bar'],  # <--
 'f_dict': {'foo': 'foo', 'foo_list': ['foo', 'bar']}}
```
instead of
```
{'foo': 'foo',
 'foo_list': [<Foo.FOO: 'foo'>, <Foo.BAR: 'bar'>],  # <--
 'f_dict': {'foo': 'foo', 'foo_list': ['foo', 'bar']}}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /Users/jsamoocha/.local/share/virtualenvs/stravalib_fork-PV0q2u3e/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Dec  4 2022, 13:57:44) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.1-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)

<sub>[PYD-140](https://linear.app/pydantic/issue/PYD-140/use-enum-values-config-does-not-work-for-collections-of-enums-in)</sub>

**Comment by dmontagu** [comment]
As of v2.0b3, this config setting doesn't seem to do anything during serialization. In particular, the snippet above now behaves even worse.

**Comment by adriangb** [comment]
The only place this is tested is here: https://github.com/pydantic/pydantic/blob/78f0ce65295bba764784da15eca83173f9ccf9b6/tests/test_main.py#L601-L611

And this test seems completely wrong to me! it should be:

```python
def test_enum_values():
    FooEnum = Enum('FooEnum', {'foo': 'foo', 'bar': 'bar'})

    class Model(BaseModel):
        model_config = ConfigDict(use_enum_values=True)
        foo: FooEnum

    m = Model(foo='foo')
    # this is the actual value, so has not "values" field
    assert type(m.foo) is str, type(m.foo)
    assert m.foo == 'foo'
```
