### ISSUE TITLE
Enable idiomatic use of constrained types without triggering linting errors

### ISSUE THREAD

**Issue by vineetrajasekhar** [pydantic/pydantic#5006]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Current Behaviour ###
Thank you for this incredible tool. I love how tersely I'm able to define how I want my data to be shaped - and the use of constrained types plays a major role in this. Unfortunately, the most idiomatic way to use constrained types runs afoul of linters - Pylance in my case. 

Doing this:

```python
import pydantic

class MyClass(pydantic.BaseModel):
    my_constrained_float: pydantic.confloat(gt = 0, lt = 1)
```

... triggers "`Illegal type annotation: call expression not allowed`" under the `pydantic.confloat(...)` portion. 

The same applies to other constrained types like `constr`, `conint`, etc.

### What I've found/tried ###

[This is not a bug](https://github.com/microsoft/pylance-release/issues/3912#issuecomment-1416690551), nor is it a new issue([this](https://github.com/microsoft/pylance-release/issues/1181)). 

There is a [workaround](https://stackoverflow.com/questions/67009123/how-can-mypy-accept-pydantics-constr-types). Applied to the above example:

```python
import pydantic

class Myconfloat(pydantic.ConstrainedFloat):
    gt = 0
    lt = 1

class MyClass(pydantic.BaseModel):
    my_constrained_float: Myconfloat
```

The above addresses the issue of the aforementioned linter error, but this is clumsy, and operates [inconsistently between pylance and mypy](https://github.com/pydantic/pydantic/issues/156). This approach also forces the user to define a new class for every type of constraint they may want to apply, like below. 

```python
import pydantic

class Myconfloat_0_to_1(pydantic.ConstrainedFloat):
    gt = 0
    lt = 1
    
class Myconfloat_10_to_12(pydantic.ConstrainedFloat):
    gt = 10
    lt = 12

class MyClass(pydantic.BaseModel):
    my_constrained_float: Myconfloat_0_to_1
    my_other_constrained_float: Myconfloat_10_to_12
```
### Why do more ###

While the above workaround allows the subclass of BaseModel to be defined without linter errors, it simply pushes the error downstream - to when I instantiate my new class:

```python
import pydantic


class Myconfloat_0_to_1(pydantic.ConstrainedFloat):
    gt = 0
    lt = 1


class Myconfloat_10_to_12(pydantic.ConstrainedFloat):
    gt = 10
    lt = 12


class MyClass(pydantic.BaseModel):
    my_constrained_float: Myconfloat_0_to_1
    my_other_constrained_float: Myconfloat_10_to_12


first_float = 0.5
second_float = 11

my_instance = MyClass(
    my_constrained_float=first_float, my_other_constrained_float=second_float 
)

third_float = 1.1
fourth_float = 12

my_bad_instance = MyClass(
    my_constrained_float=third_float, my_other_constrained_float=fourth_float
)
```
At runtime, Pydantic correctly accepts `my_instance`, but (also correctly) raises `ValidationError`s on `my_bad_instance` citing the out-of-range values for `third_float` and `fourth_float`. But Pylance underlines `first_float `and `second_float ` in my definition of `my_instance`, as well as `third_float` and  `fourth_float`, citing the following error for all four: `Argument of type "float" cannot be assigned to parameter "my_constrained_float" of type "Myconfloat_0_to_1" in function "__init__"
  "float" is incompatible with "Myconfloat_0_to_1"`

This clearly isn't a bug, as Pydantic is behaving exactly as advertised - and it's not really a bug with Pylance either, as `float` is not implicitly compatible with a subclass of `pydantic.ConstrainedFloat`. 

### Ideally... ###

In a perfect world, Pylance would accept the use of confloat, constr, conint etc. in the idiomatic fashion native to Pydantic, i.e. the following, with no linting errors:

```python
class MyClass(pydantic.BaseModel):
    my_var: pydantic.confloat(gt=0, lt=1)
```

Less ideal, but acceptable, would be if passing obviously compatible values to con* types does not trigger the linter. 

### Why not fix with my own code ###

As this is a conflict between the (internally consistent) behaviours of Pylance and Pydantic, (unless I'm missing something) there is no fix I can implement short of omitting linting. Doing this globally would be unwise for obvious reasons. Doing it locally (`# type: ignore`) is a possibility, but it risks masking other misbehaviour that I'd like to avoid. 

(That said, if there's an obvious fix that I'm just too ignorant to have come up with myself, I apologise in advance...)

### Why add this feature to Pydantic (i.e. and not Pylance/MyPy) ###

Pylance's revulsion at trying to pass a call signature off as a type annotation seems reasonable, and would be desirable in most cases. It's Pydantic's particular (and particularly desirable) ability to turn otherwise thin, flavourless type annotations into a rich broth of functionality that makes this a conflict worth resolving, rather than simply avoiding... 

Thank you in advance for anything you can do regarding this - and regardless, thank you for your amazing ongoing work. All the best.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by vineetrajasekhar** [comment]
I can of course avoid this whole issue by using a validator to enforce my criteria - but that renders Pydantic's `con*` types somewhat redundant, and leaves a massive productivity enhancement on the table simply as a way to avoid enraging the linter... That'd be a case of the flea wagging the dog...

**Comment by samuelcolvin** [comment]
See annotated-types, we're using that methodology (and that library) in V2.

I think it should provide what you need.

**Comment by vineetrajasekhar** [comment]
Do you mean using typing.Annotated like this?
```python
from typing import Annotated

import pydantic


class MyClass(pydantic.BaseModel):
    myvar: Annotated[float, pydantic.confloat(gt=0, lt=1)]


x = MyClass(myvar=0.1)
```

This works! It adds very little "heft" to the natural way to use `confloat()`, and avoids any linting errors... 

This is a pretty neat workaround - unless you meant something different (better)? 

Thank you!

**Comment by vineetrajasekhar** [comment]
This is perfect - it allows typing.Annotated to act as a bridge between Pydantic's internally consistent behaviour and Pylance's internally consistent behaviour without compromising on either's effectiveness, and incurring a negligible additional cost... And if V2 is going to bring some of this "bridging" to the table out-of-the-box, so much the better! 

Thanks very much for the prompt response, closing this off now.

**Comment by samuelcolvin** [comment]
I meant https://github.com/annotated-types/annotated-types, but basically yes.

**Comment by Lawouach** [comment]
Hi there,

@vineetrajasekhar I was quite excited byt this approach but, as far I can see, this doesn't work on Python 3.10.6/Pydantic 1.10.5. Was this meant to be for Pytdantic v2 only? Or Python 3.11?

Thanks,

**Comment by poopledc** [comment]
> Hi there,
> 
> @vineetrajasekhar I was quite excited byt this approach but, as far I can see, this doesn't work on Python 3.10.6/Pydantic 1.10.5. Was this meant to be for Pytdantic v2 only? Or Python 3.11?
> 
> Thanks,

@samuelcolvin @vineetrajasekhar This doesn't work for python 3.9.15 and pydantic versions 1.9.0, 1.10.2, and 1.10.6

**Comment by poopledc** [comment]
The following code will show when Test is constructed with a string or int it will pass validation, when it really should error. Once the Annotated[str, string_type] is converted to a string_type the validation error occurs. However, then the Illegal Type Annotation error from Pylance exists

`from __future__ import annotations
from typing import Annotated

from pydantic import BaseModel
from pydantic import constr


string_type = constr(min_length=3)

class Test(BaseModel):
    string: Annotated[str, string_type]

class Test2(BaseModel):
    string: string_type

if __name__ == "__main__":
    _ = Test(string="1")
    _ = Test(string=1)
    _ = Test2(string=1)`

**Comment by sshishov** [comment]
I can confirm the same. If we are using `typing.Annotated` then the validation/modification which should be brought by `con*` types is not happening. Meaning this workaround is useless
