### ISSUE TITLE
[v2.dev]  Pydantic does not support custom annotation types

### ISSUE THREAD

**Issue by ddneilson** [pydantic/pydantic#5008]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

[PEP 593](https://peps.python.org/pep-0593/) says "If a library (or tool) encounters a typehint Annotated[T, x] and has no special logic for metadata x, it should ignore it and simply treat the type as T."

The current in-development branch of Pydantic v2 throws an error if it encounters Annotated metadata that are not "instances of annotated_types.BaseMetadata or PydanticMetadata or a subclass of PydanticMetadata".

I believe this to be a bug. Expected behavior is that Pydantic preserves the added metadata, but ignores it for its own processing.

As a motivating use-case, consider an application that uses Pydantic v2 for parsing & validating a data model, but then wants to do some post-processing/understanding of the data provided. Such an application (like my own) may find that the ideal mechanism for that post-processing is a recursive traversal through the model with functionality during the traversal dictated by annotations on the fields of the model. These annotations are not for parsing & validation, and should be ignored by Pydantic.

### Example Code

```Python
import sys
from pydantic import BaseModel

if sys.version_info < (3,9):
    from typing_extensions import Annotated
else:
    from typing import Annotated

class MyAnnotation:
    pass

class TestModel(BaseModel):
    attr: Annotated[str, MyAnnotation]

# Traceback (most recent call last):
#   File "testannotation3.py", line 12, in <module>
#     class TestModel(BaseModel):
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/main.py", line 103, in __new__
#     _model_construction.complete_model_class(
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 141, in complete_model_class
#     inner_schema, fields = build_inner_schema(
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 251, in build_inner_schema
#     schema = model_fields_schema(
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 41, in model_fields_schema
#     {
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 42, in <dictcomp>
#     k: schema_generator.generate_field_schema(k, v, validator_functions, serialization_functions)
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 192, in generate_field_schema
#     schema = apply_metadata(schema, field.metadata)
#   File "/home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 592, in apply_metadata
#     raise PydanticSchemaGenerationError(
# pydantic.errors.PydanticSchemaGenerationError: Metadata must be instances of annotated_types.BaseMetadata or PydanticMetadata or a subclass of PydanticMetadata
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.0.dev0
                 install path: /home/dneilson/python/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
                     platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']

Pydantic commit hash: ef3cc495a9c86553b62a95a6052fd9b6ebc045e9
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Fair, very happy to ignore the type.

Pr welcome.
