### ISSUE TITLE
`pydantic-extra` package?

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5012]
For types which shouldn't be included with pydantic but which people understandably want to reuse.

See #5011 - I don't think we should not add a one time password type to pydantic. The surface -area/problem-space of pydantic is already too large. I also strongly want to avoid more dependencies, even if they're optional.

However I would advocate for creating a package, perhaps `pydantic-extra` which includes:
* #5011 - OTP type
* #1551 - phone number type, which quite a lot of attention
* [`PaymentCardNumber`](https://docs.pydantic.dev/usage/types/#payment-card-numbers) - currently in pydantic
* [`Color`](https://docs.pydantic.dev/usage/types/#color-type) - currently in pydantic
* perhaps some kind of money type
* perhaps some types related to webauthn (although the `webauthn` package already uses pydantic, so maybe that's not necessary/a good idea
* password type, can mostly used `strip_whitespace` and `min_length`, but also integrate with https://github.com/dwolfhub/zxcvbn-python ???
* potentially more types, the threshold required to add a type to `pydantic-extra` can be significantly lower than for `pydantic`

`PaymentCardNumber` and `Color` will need to remain in pydantic (potentially with a dep warning) for now.

Before anyone asks, no, I do not want to move email types to `pydantic-extra` - they're used too much, also I want to move the implementation into rust https://github.com/pydantic/pydantic-core/issues/385.

I'd be happy to:
* host this in the pydantic GitHub org
* include the docs in `docs.pydantic.dev` (this is the plan for `pydantic-core` and `pydantic-settings` already)
* release it using my pypi account
* add more maintainers than pydantic has
* be more liberal about dependencies

The other advantage would be that we could make new releases of `pydantic-extra` more easily as they couldn't break any other bits of pydantic.

@pydantic/pydantic-maintainers WDYT?

If we decide to go ahead with this, @yezz123 would you be willing to be a maintainer of this???

**Comment by yezz123** [comment]
This looks impressive, as I worked before on several types regarding Pydantic in my work, I would be happy to elaborate on this and maintain Pydantic extra, it's going to be more helpful and contain several utilities that may open-source developers propose in discussions or issues.

- Same as the OTP Idea, you propose phone numbers, payment cards(already), integration such as colors, and money types or in general default currencies.
- My sense, here is we can create this as an integration that will be helpful in the future.

I would be happy if I maintain this! we can do it in Pydantic org while it will be an extra addon on the top of the package itself.

**Comment by samuelcolvin** [comment]
* repo created https://github.com/pydantic/pydantic-extra
* pypi project stub created to save the name
* @yezz123 invited to the pydantic or and to have write access on pydantic-extra

This seems to have started without waiting for more feedback, sorry, but still very open to any feedback.

In terms of timeline, I guess if we can get this ready to be released with V2, we can mark `Color` and `PaymentCardNumber` deprecated in V2.

**Comment by yezz123** [comment]
> * repo created https://github.com/pydantic/pydantic-extra
> * pypi project stub created to save the name
> * @yezz123 invited to the pydantic or and to have write access on pydantic-extra
> 
> This seems to have started without waiting for more feedback, sorry, but still very open to any feedback.
> 
> In terms of timeline, I guess if we can get this ready to be released with V2, we can mark `Color` and `PaymentCardNumber` deprecated in V2.

Amazing 🚀

**Comment by lewoudar** [comment]
Hi everyone, I also think it is a good idea and I agreed with @hramezani for the naming, something like `pydantic-types` or `pydantic-extra-types` seems more correct in my humble opinion.

**Comment by samuelcolvin** [comment]
I agree with @hramezani, I'll rename the repo, upload a new stub package and delete the old one.

Bring on namespaces in pypi and all this holding names would die away!

**Comment by tomy0000000** [comment]
Sound like a great idea. My project could make use of these handful types heavily.
I saw @samuelcolvin left a `helps-wanted` tag. Please write down which part needs help so that I might contribute to the projects.

**Comment by samuelcolvin** [comment]
Thanks @tomy0000000, hopefully @yezz123 can do some of the initial work setting up the repo - copying `Color` and `PaymentCardNumber` and their tests, setting up CI etc.

Once that's done, we can migrate the above bullet point to issues on the repo and start creating PRs.

`pydantic-extra-types` will never be released for V1, only with compatibility for V2, so types need to use the new protocol for custom types, which is mostly formalised but needs to be documented.

**Comment by tomy0000000** [comment]
> Once that's done, we can migrate the above bullet point to issues on the repo and start creating PRs.

Great, I'll stayed tuned

**Comment by ghandic** [comment]
Is there a possibility of this hooking into rust too? Or would it need to be compiled together with pydantic then?

**Comment by samuelcolvin** [comment]
This (or any code) can use the rust core-schema types, as is already done [here](https://github.com/pydantic/pydantic-extra-types/blob/af42ffe3c2206c721da90b98009d9ff29401d993/pydantic_extra_types/types/payment.py#L41-L49). 

That's the same thing pydantic itself does.

**Comment by ghandic** [comment]
So it be possible to write the color validation/parsing in rust within pydantic-extra? Perhaps something we could showcase for others trying to expand on the plugins

**Comment by samuelcolvin** [comment]
No, not writing rust, that would require the entire build process we have for pydantic-core, I mean we can use validators written in rust.

I very much doubt there's going to be the need to write validators in rust here or anywhere else.

**Comment by Kludex** [comment]
Since we've created https://github.com/pydantic/pydantic-extra-types, I'll be closing this issue. FYI @samuelcolvin
