### ISSUE TITLE
auto-migration tool for Pydantic V2

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5013]
@dmontagu and I were just talking about making migration to V2 as easy as possible.

Some things will be complicated, but others should be mechanical, e.g. renaming methods `dict()` to `model_dict()` etc.

When I spoke to the team from sourcegraph last week, @jdorfman mentioned that they had a tool for fixing entire codebases. Would it be possible to collaborate with sourcegraph to make this available for anyone upgrading pydantic?

Alternatively, I think someone was talking on twitter about a tool to apply transforms to code, @adriangb do you remember who it was? Could it have been @Kludex?

**Comment by jdorfman** [comment]
@samuelcolvin we (@beyang and I) will work on getting you a cloud account. That way you can run batch changes and save time.

**Comment by Kludex** [comment]
Maybe because of https://github.com/Kludex/bump-testclient.

I'm always looking for excuses to build codemods. :sweat_smile:

Do you have the transformations that need to happen already? I can create a repo, you create an issue with the cases needed, and I can build it.

**Comment by samuelcolvin** [comment]
Yes, that was it!

Let us do some digging and come up with a list of transforms. I'll reply here when things have settled a little and we have a list.

**Comment by samuelcolvin** [comment]
Absolutely, we'll definitely have a thorough migration guide.

**Comment by ghandic** [comment]
Perhaps the work going on in #5016 could inform this. There are a lot of scenarios we need to pick out with someone with the SME knowledge of where these objects will now reside or what the alternative is

**Comment by jdorfman** [comment]
> Is there any way others could upgrade their code using your tool, or does that require a sourcegraph cloud account?

Yes, I can invite anyone you need to your org. Hopefully it isn't too late.

**Comment by ghandic** [comment]
Will it be publicly available for any pydantic user to leverage?

**Comment by jdorfman** [comment]
@ghandic [Batch Changes](https://docs.sourcegraph.com/batch_changes) will be only available for project maintainers i.e. anyone who has write access to the repo.

**Comment by ghandic** [comment]
I think the requirement for this is for users in general, similar to the work @Kludex did for starlette to allow users to migrate with a simple command.

Give the widespread usage of pydantic there will be many users who could take advantage of the auto migration

**Comment by jdorfman** [comment]
@ghandic oh, I see.

> similar to the work @Kludex did for starlette to allow users to migrate with a simple command.

Can you please give me some more context?

**Comment by ghandic** [comment]
The migration from v1 to v2 has many breaking changes

Some of which can be handled automatically, such as moving files/function names. 

@Kludex shared the link above https://github.com/Kludex/bump-testclient for how he made an automigration tool for Starlette 

I'd imagine it could get to quite a sizable migration tool for this v1->v2 change so if source graph had some open tooling or free tiers that could achieve this then it could benefit a large community of Python developers

**Comment by jdorfman** [comment]
Got it thanks for explaining @ghandic 

All I have to offer at this time is the cloud server which might not be the way to benefit the vast community. =/

**Comment by beyang** [comment]
@jdorfman maybe we can offer a sign-up mechanism that makes this easy for users to run this across open source?

**Comment by angrycaptain19** [comment]
@brendanator and I were chatting a bit about this during PyCon and I think we (@sourcery-ai) should be able to help provide automated fixes for most of these breaking changes in V1 -> V2.

We can make a series of rules/automated transformations for each of these breaking changes and make them available to anyone through our CLI and set it up so you don't need an account/login to apply these changes.

But, also don't want to step on any toes if @Kludex already has this covered! Let me know if this would be helpful

**Comment by Kludex** [comment]
https://github.com/pydantic/bump-pydantic is available to help on the migration process. :)
