### ISSUE TITLE
Non-annotated fields not raising a warning (v2)

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5014]
It seems to me the following code:
```python
from pydantic import BaseModel

class A(BaseModel):
    x = True
```
should be raising this warning:
https://github.com/pydantic/pydantic/blob/ef3cc495a9c86553b62a95a6052fd9b6ebc045e9/pydantic/_internal/_model_construction.py#L76-L80

However, currently it hits this branch: https://github.com/pydantic/pydantic/blob/ef3cc495a9c86553b62a95a6052fd9b6ebc045e9/pydantic/_internal/_model_construction.py#L71

I suspect this is not the intended behavior.

**Comment by Kludex** [comment]
This is solved on v2 already. 🙏
