### ISSUE TITLE
Add nice error message when attempting to import removed modules/functions in v2

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5016]
If a user attempts to import removed functions, from removed modules, or both, we should give a better error message than a plain ImportError. Ideally the error message will include some information about the migration path, or possibly a request to create an issue if the changes break something in their codebase in a way that is difficult for them to resolve.

As an example, it would be preferable to get such an error message when attempting to run `from pydantic.generics import replace_types`.

Probably anything that could be construed as part of the "public" api of v1.X (i.e., doesn't use leading underscores in the name or import path) should be handled neatly.

**Comment by ghandic** [comment]
Keen to work on this! Will require a fair but of discussion on how we wish to inform the user, how long this will be persisted for etc.

I have an initial idea (see PR https://github.com/pydantic/pydantic/pull/5113) 


Using this PEP-562 standard, we could add a `__getattr__` method to all files (and the old file names - noting this will be all that is in them) 

Let me know your thoughts :)

**Comment by ghandic** [comment]
We could also monkeypatch internals, this seems like a nice way to do it, but potentially risky... 

```shell
Traceback (most recent call last):
  File "/projects/pydantic/caller.py", line 1, in <module>
    from pydantic import Required
  File "/projects/pydantic/import_helper.py", line 30, in _handle_fromlist_override
    raise exception
pydantic.import_helper.V2MigrationRemoved: pydantic.Required has been removed in favour of ...
```

**Comment by ghandic** [comment]
@samuelcolvin @dmontagu thoughts?
