### ISSUE TITLE
Default fallback type for GenericModel

### ISSUE THREAD

**Issue by samsja** [pydantic/pydantic#5025]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

# Context

GenericModel are fantastic. Nevertheless, it would be super nice if we could have a default fallback when the generic type is not precise.

```python
from typing import Generic, TypeVar, Optional

from pydantic.generics import GenericModel

DataT = TypeVar('DataT')

class MyDoc(GenericModel, Generic[DataT]): # here I want int to be the default fallback
    data: Optional[DataT]


doc = MyDoc[int](data = 1)
assert type(doc.data) == int

doc_2 = MyDoc[float](data = 1)
assert type(doc_2.data) == float

doc_3 = MyDoc(data = 1)
assert type(doc_2.data) == int # this will fail atm because I did not precise the default type should be int
```

There might be already a way to do it ?

If not I can see something like this 

```python
from pydantic.typing import TypeVar
DataT = TypeVar('DataT, default=int)

class MyDoc(GenericModel, Generic[DataT]): 
    data: Optional[DataT]
 ```

or 

```python
from typing import TypeVar
DataT = TypeVar('DataT)

class MyDoc(GenericModel, Generic[DataT], default=int):
    data: Optional[DataT]
```

though for the second one not sure how it would play with a generic with multiple entry.

Is this conceivable? 

Thanks in advance

FYI: we are looking to use such a feature in DocArray : https://github.com/docarray/docarray/issues/1105

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
I think this should be possible when using `typing_extensions.TypeVar`. PR welcome, but either way we will get to it eventually.

**Comment by samsja** [comment]
Oh I was not aware that TypeVar from typing_extension had a default fallback. Looks like this has been introduced in this PEP https://peps.python.org/pep-0696/. I will try to see if this is working

**Comment by samsja** [comment]
Working like a charm with TypeVar default. Thanks you for the hint.

```python
from typing_extensions import TypeVar
from typing import Generic, Optional

from pydantic.generics import GenericModel

DataT = TypeVar('DataT', default = int)

class MyDoc(GenericModel, Generic[DataT]): # here I want int to be the default fallback
    data: Optional[DataT]


doc = MyDoc[int](data = 1)
print(type(doc.data))
assert type(doc.data) == int

doc_2 = MyDoc[float](data = 1)
assert type(doc_2.data) == float

doc_3 = MyDoc(data = 1)
assert type(doc_3.data) == int # default fallback to int
```

**Comment by dmontagu** [comment]
I am surprised/don't trust that this is working properly — in your code snippet above, it looks to me like this is more a coincidence of the fact that you happened to pass it an int.

I'm going to re-open this issue for tracking purposes, I expect there is implementation work to be done, but I don't think it will be too hard to achieve.

**Comment by samsja** [comment]
oh yes you are right

**Comment by dmontagu** [comment]
For what it's worth, If anyone wants to take a stab at implementing this, the relevant bit of code is here: https://github.com/pydantic/pydantic/blob/7fd643ef4d6edc14065619342e1c6db07cbf1c05/pydantic/_internal/_generate_schema.py#L1130-L1138

You'll just need to figure out how to extra the default value from a `typing_extensions.TypeVar` and use that as a new conditional branch.

**Comment by samsja** [comment]
I can take a look and maybe draft a PR

**Comment by Kaushal-Dhungel** [comment]
Hi, I am new here. Can I get started with this one?

**Comment by lig** [comment]
@Kaushal-Dhungel 👍🏻 Sure. Go ahead. Please, don't hesitate opening a PR and ask for help if you'll need some.

**Comment by Kaushal-Dhungel** [comment]
> ```python
> doc_3 = MyDoc(data = 1)
> assert type(doc_2.data) == int # this will fail atm because I did not precise the default type should be int
> ```
Was this failing because you tried asserting `doc_2.data` instead of `doc_3.data` ??


Coming to the issue, in `typing_extensions.TypeVar` there is an argument named `default` passed in its `__new__` method. [https://github.com/python/typing_extensions/blob/cfd49f81b6adf2246b8b3e3f4d3933d19f8e3546/src/typing_extensions.py#L1510](See here). 
Since the `default` option is provided only for the `typing_extensions.TypeVar`, this is what I tried:- 

 ```python
        if hasattr(typevar,'__default__'):
            # ------ do something -----------
```

However, unlike `bound` and `constraints` ( which can not coexist ), the `default` can coexist with one of them. For example:-
`DataT = TypeVar('DataT', default=int, bound=BaseModel) `

So, I am stuck here. How should the schema be generated if both `default` and `bound` values are provided? I hope this is not a silly question to ask lol.

**Comment by alexmojaki** [comment]
> Here's my MRE feature request:

It looks like this is working now, maybe this was implemented recently?

**Comment by adriangb** [comment]
Yup we support `default` on TypeVar now!
