### ISSUE TITLE
Serialization/Deserialization not working correctly with TypeVar

### ISSUE THREAD

**Issue by domef** [pydantic/pydantic#5036]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The serialization/deserialization is not working correctly when using `TypeVar` types.
The output of the following code is:
```
a=MyModelType(b='c', c='d')
a=BaseModel()
```
However, I think that the output should be:
```
a=MyModelType(b='c', c='d')
a=MyModelType(b='c', c='d')
```

### Example Code

```Python
import pydantic as pyd
import typing as t


T1 = t.TypeVar("T1", bound=pyd.BaseModel)


class MyModelType(pyd.BaseModel):
    b: str = pyd.Field(..., description="C")
    c: str = pyd.Field(..., description="D")


class MyModelA(pyd.BaseModel, t.Generic[T1]):
    a: T1 = pyd.Field(..., description="A")


class MyModelB(MyModelA[MyModelType]):
    pass


model = MyModelB(a=MyModelType(b="c", c="d"))
print(model)
model_ = MyModelB.parse_obj(model.dict())
print(model_)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /home/federico/venvs/genesys/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
                     platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
When attempting to use generic models, you should be inheriting from `pydantic.generics.GenericModel`.

The following code produces the output you want:
```python
import pydantic as pyd
from pydantic.generics import GenericModel
import typing as t


T1 = t.TypeVar("T1", bound=pyd.BaseModel)


class MyModelType(pyd.BaseModel):
    b: str = pyd.Field(..., description="C")
    c: str = pyd.Field(..., description="D")


class MyModelA(GenericModel, t.Generic[T1]):
    a: T1 = pyd.Field(..., description="A")


class MyModelB(MyModelA[MyModelType]):
    pass


model = MyModelB(a=MyModelType(b="c", c="d"))
print(model)
model_ = MyModelB.parse_obj(model.dict())
print(model_)
```

```
a=MyModelType(b='c', c='d')
a=MyModelType(b='c', c='d')
```

I can't remember if there was a reason we couldn't raise an error if you inherit directly from `BaseModel` and `typing.Generic` in v1.X, but for what it's worth, we are planning to get rid of `GenericModel` in v2 (and the code you shared initially will be the right approach). But still working out some of the kinks there!

**Comment by samuelcolvin** [comment]
Great, explanation.

**Comment by domef** [comment]
Thank you!
