### ISSUE TITLE
Move ref from TypedDictSchema to ModelSchema (v2)

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5038]
One of the challenges I've been running into while working through JSON schema generation (#5029) has been the fact that in the `CoreSchema` created for BaseModels, a "ref" is not set for the `ModelSchema`, which has all the information about the class/class config, but _is set_ for the TypedDictSchema, which is missing much of this information.

My current approach is to store things in (what will eventually become) the `"definitions"` field of the JSON Schema if and only if the corresponding CoreSchema has set a `'ref'`. While we could change this, I think this is a reasonable thing to do that makes it a bit easier to reason about how CoreSchema gets translated to JSON schema (and I would like to do something similar for Enums, since I think we want to put their definitions in the `"definitions"` field as well).

The fact that `TypedDictSchema` gets the ref, but `ModelSchema`, of which the `TypedDictSchema` is the _inner_ schema, gets much of the data necessary for determining the JSON schema makes things a bit challenging (this would also be simpler if the ref were on the "outside" and the model definition / config were on the "inside", though that's not a change I am suggesting we make).

You can see this in the following code snippets:

Here is where the `TypedDictSchema` is created (with a ref):
https://github.com/pydantic/pydantic/blob/41ac98aee41aeb6e6592091055a61406036425d7/pydantic/_internal/_generate_schema.py#L40-L47

And here is where the `ModelSchema` is created (without a ref):
https://github.com/pydantic/pydantic/blob/41ac98aee41aeb6e6592091055a61406036425d7/pydantic/_internal/_model_construction.py#L172-L174

Is there any reason we can't move the ref from the `TypedDictSchema` to the `ModelSchema`? If nothing else it seems to me we could do that in the second snippet above via something like:
```python
    cls.__pydantic_core_schema__ = outer_schema = core_schema.model_schema(
        cls, inner_schema, config=core_config, call_after_init=model_post_init
    )
    outer_schema['ref'] = inner_schema['ref']
    del inner_schema['ref']
```
(though I think the above code is probably not the "right" approach).

If the `'ref'` is useful (or currently used :) for something besides the JSON schema generation, then it may be more of a headache, but I at least wanted to create an issue to hash this out a bit.

(@samuelcolvin)

**Comment by dmontagu** [comment]
Also, to be clear, we could have a ref present on both the ModelSchema _and_ the TypedDictSchema, but I think there is a benefit of keeping the CoreSchema refs we generated globally unique; in particular not having multiple schemas (even if immediately nested) sharing the same ref. I don't think it's a requirement, but I think it may make some of the code used to manipulate this stuff cleaner.

Also, it seems to me that since the ref being set on the TypedDict today really is coming from the import path of the Model class, it seems more natural that it would live on the `ModelSchema` anyway. But I could definitely be overlooking something.

**Comment by adriangb** [comment]
I think this is resolved now that we have totally distinct schemas.
