### ISSUE TITLE
mypy reports an error when referring to the `__pydantic_model__` attribute of a dataclass

### ISSUE THREAD

**Issue by slott56** [pydantic/pydantic#5040]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

MyPy (0.991) with the Pydantic plug-in, reports an error when referring to the `__pydantic_model__` attribute of a dataclass.

The example below provides the following report from mypy:

```
bug_report.py:8: error: "Type[SeriesSample]" has no attribute "__pydantic_model__"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

(Of course, the example works beautifully. Can't say enough good things about Pydantic.)

### Example Code

```Python
from pydantic.dataclasses import dataclass

@dataclass
class SeriesSample:
    x: float
    y: float

print(SeriesSample.__pydantic_model__.schema())
```

### Python, Pydantic & OS Version

```Text
(base) slott@MacBookPro-SLott project_2_5 % python -c "import pydantic.utils; print(pydantic.utils.version_info())"

             pydantic version: 1.10.2
            pydantic compiled: True
                 install path: /Users/slott/miniconda3/envs/projectbook/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Nov 24 2022, 08:09:04) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Not surprising since it's a magic dunder attribute, and typing doesn't even have a clear "dataclass" type.

Probably best to add a utility class like:

```py
get model(dc: type[MyDataclass]) -> type[BaseModel]:
    return m.__pydantic_model__  # type: ignore
```

**Comment by samuelcolvin** [comment]
hopefully we can add methods like this in V2, although specifically `__pydantic_model__` is being removed.
