### ISSUE TITLE
[1.10.X] mypy: BaseConfig.fields has incorrect type?

### ISSUE THREAD

**Issue by hoodmane** [pydantic/pydantic#5043]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

[The docs](https://docs.pydantic.dev/usage/exporting_models/#model-and-field-level-include-and-exclude) have roughly the following example:
```py
from pydantic import BaseModel, BaseConfig

class Transaction(BaseModel):
    id: str
    value: int

    class Config(BaseConfig):
        fields = {'value': {'exclude': True}}
```
Running mypy on this (default settings) fails with:
```
tmp.py:8: error: Dict entry 0 has incompatible type "str": "bool"; expected "str": "str"  [dict-item]
```
The problem is:
https://github.com/pydantic/pydantic/blob/1.10.X-fixes/pydantic/config.py#L92
`fields` should probably have type:
```py
Dict[str, Union[str, Dict[str, str | bool]]]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /home/hood/Documents/programming/sphinx-js/.tox/py310/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 (main, Feb  8 2023, 14:50:01) [GCC 9.4.0]
                     platform: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Thanks @hoodmane. Yes we can fix the annotation easily.

We're dropping `Config.fields` in v2.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
