### ISSUE TITLE
Exponential blowup in errors with recursive discriminated uinion

### ISSUE THREAD

**Issue by hoodmane** [pydantic/pydantic#5044]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Suppose we have a mutually recursive discriminated union with two options `A` and `B`. They are discriminated by the field `type` which is `"A"` on `A` and `"B"` on `B`. Both `A` and `B` have an optional child which is a discriminated union of A and B. If there is a validation error (say a missing field) nested n layers deep and n > 2, then pydantic generates 2^{n-1} - 2 errors. It also takes exponentially long to fail.

The problem is that it considers the discriminator to be refutable and so it backtracks exponentially much and complains that the `type` field is wrong tons of times. I would want some way to indicate that the `type` field is irrefutable, so if there is a problem don't try to match it against a different case in the `Union`, just fail.

### Example Code

The following code prints:

```
[1, 2, 6, 14, 30, 62, 126, 254, 510, 1022, 2046, 4094, 8190, 16382, 32766]
```

```Python
from pydantic import BaseModel, Field, ValidationError
from typing import Literal, Annotated, Union

Child = Annotated[Union["A", "B"], Field(discriminator="type")]


class B(BaseModel):
    type: Literal["B"]
    missing_field: str
    child: Child | None


class A(BaseModel):
    type: Literal["A"]
    child: Child | None


for X in [A, B]:
    X.update_forward_refs()


def parse_depth(depth):
    # missing missing_field ==> parse failure
    root = {"type": "B"}
    for _ in range(depth):
        root = {"type": "A", "child": root}

    A.parse_obj(root)

def count_errors(depth):
    try:
        parse_depth(depth)
    except ValidationError as e:
        return len(e.errors())
    else:
        assert False


if __name__ == "__main__":
    print([count_errors(n) for n in range(15)])
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /home/hood/Documents/programming/sphinx-js/.tox/py310/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 (main, Feb  8 2023, 14:50:01) [GCC 9.4.0]
                     platform: Linux-5.17.5-76051705-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)

**Comment by hoodmane** [comment]
I guess as a workaround, I can catch the error and filter out all errors that mention the discriminated field.

**Comment by dmontagu** [comment]
@hoodmane I can replicate the issue and understand where it is coming from. I imagine you would still have the performance overhead associated with generating all the errors even if you filter out the errors.

For what it's worth, I think we should do exactly what you have suggested (i.e., consider discriminators "infallible") in v2, and plan to implement things that way. (Assuming no objections from @samuelcolvin.)

**Comment by dmontagu** [comment]
I think if we "consider discriminators infallible", it will massively help with the confusing error messages that come from types with lots of union cases, even when they aren't recursive 😅 .

**Comment by hoodmane** [comment]
Currently I'm actually more concerned about being able to figure out what is wrong with my model: this is my key goal in using Pydantic is that it can tell me when my model is incorrect and how to fix it. Luckily in my use case the depth is only ~8 which doesn't cause too bad of a crash. From tests if depth is ~20 then it crashes the terminal window it is invoked from even if I press Ctrl+C right after starting.

**Comment by hoodmane** [comment]
Seems like to filter the errors I have to do:
```py
v = ValidationError(None, exc.model)
v._error_cache = [e for e in exc.errors() if e["loc"][-1] != "type"]
raise v from None
```

**Comment by hoodmane** [comment]
Though if I do:
```py
def fixed_errors(depth):
    try:
        parse_depth(depth)
    except ValidationError as exc:
        exc._error_cache = [e for e in exc.errors() if e["loc"][-1] != "type"]
        raise
    else:
        assert False
```
then this `fixed_errors` still displays exponentially many errors...

**Comment by dmontagu** [comment]
@hoodmane I think I figured it out for you:
```python
class B(BaseModel):
    type: Literal["B"]
    missing_field: str
    child: Child | None = Field(discriminator="type")


class A(BaseModel):
    type: Literal["A"]
    child: Child | None = Field(discriminator="type")
```
give this a shot 💪

**Comment by hoodmane** [comment]
Aha that is why getting rid of `| None` made such a dramatic difference. I was worried it would be mad that `None` has no field `type` if we do it this way.

Thanks so much @dmontagu!

**Comment by dmontagu** [comment]
I was also worried about it but I tried it anyway. Turns out whoever implemented it did a good job :)

**Comment by hoodmane** [comment]
Actually I am having trouble getting this to work in my real use case. I may have to search for a new minimal reproduction. But this makes me think there's a good chance some minor change will fix it...

**Comment by dmontagu** [comment]
Feel free to share once you have an example small enough you are comfortable sharing (doesn't have to be perfectly minimal) that reproduces the issue. Happy to help

**Comment by hoodmane** [comment]
Well the following long-winded workaround makes the error messages better for me:
```py
classesByDiscriminator = {disc: {} for disc in discriminators}

for cls in list(globals().values()):
    if not isclass(cls) or not issubclass(cls, BaseModel):
        continue
    for n in discriminators:
        if not n in cls.__annotations__:
            continue
        ann = cls.__annotations__[n]
        if getattr(ann, "__name__", None) != "Literal":
            continue
        for arg in ann.__args__:
            classesByDiscriminator[n][arg] = cls


def parse(json: dict[str, Any]) -> Root:
    try:
        return Root.parse_obj(json)
    except ValidationError as exc:

        s = sorted(set(e["loc"][:-1] for e in exc.errors()), key=lambda loc: (-len(loc),loc))
        handled = set()
        errors = []
        for loc in s:
            if loc in handled:
                continue
            # Add all prefixes of the current loc to handled
            for i in range(len(s)):
                handled.add(loc[:i])
            
            # follow path to get problematic subobject
            o = json
            for a in loc:
                o = o[a]

            # Work out the discriminator and use it to look up the appropriate class
            for n in discriminators:
                if n not in o:
                    continue
                if o[n] not in classesByDiscriminator[n]:
                    continue
                c = classesByDiscriminator[n][o[n]]
                try:
                    c.parse_obj(o)
                except ValidationError as e:
                    errs = e.errors()
                    for err in errs:
                        # Extend the loc so that it is relative to the top level object
                        err["loc"] = loc + err["loc"]
                    errors.extend(errs)

        exc._error_cache = errors
        raise
```

**Comment by dmontagu** [comment]
Is the issue that you had multiple models in a single union with different discriminator fields? Hard for me to tell from your code snippet, but it would make sense to me that that doesn't get handled well, though I'm not sure I have a good proposal for an improvement.

**Comment by hoodmane** [comment]
I have two different unions with two different discriminators but all models in each union share one discriminator. I'm pretty confused about what the problem is since in smaller examples it seems to work as expected...

**Comment by dmontagu** [comment]
Trying to read a bit into what you are talking about, it sounds like — maybe? — you've got something like:
```python
ModelsWithTypeDiscriminator = Annotated[Union["A", "B"], Field(discriminator="type")]
ModelsWithKindDiscriminator = Annotated[Union["C", "D"], Field(discriminator="kind")]

Child = Union[ModelsWithTypeDiscriminator, ModelsWithKindDiscriminator] # <-- the "problem" union; no common discriminator 
```
If this is right, I think it might be tough to resolve. I'm not sure, I'd guess that pydantic v1 just isn't capable of handling this neatly. (I'll just note, I am fairly confident that the more powerful TaggedUnion logic in pydantic_core will allow us to handle this fully and cleanly in v2. I understand that doesn't solve your problem today though.)

If I have understood correctly — and I realize I've made a bunch of assumptions here — I think you _might_ be able to work a fix into place relying on something like `@root_validator(pre=True)` to do a more detailed check prior to passing things into the "normal" validators (basically checking the discriminator values for multiple fields).

**Comment by hoodmane** [comment]
I don't think this is actually my problem: I have `ModelsWithType` and `ModelsWithKind` but I don't take their union. I am not sure yet whether it is important that I have two different discriminators or not.

**Comment by hoodmane** [comment]
Thanks @dmontagu!
