### ISSUE TITLE
Modelattribute with default value and validator will not be created (v2)

### ISSUE THREAD

**Issue by florianfischer91** [pydantic/pydantic#5045]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

This is related to pydantic v2.

Having a BaseModel with an attribute with a default value and a validator method does not create the attribute when the model gets instantiated. Output of the example below:

```bash
Traceback (most recent call last):
  File "...", line 10, in <module>
    assert FooModel().foo == 42
AttributeError: 'FooModel' object has no attribute 'foo'
```

If you remove the validator or pass a value for `foo` to `__init__` then everything works as expected.
Is this a known issue with needs to be fixed or should it actually already work?
I also tried to directly create the schemaValidator which does return an empty dictionary, so perhaps it is more related to pydantic-core than pydantic.

### Example Code

```Python
from pydantic import BaseModel, validator

class FooModel(BaseModel):
    foo: int = 42
    
    @validator("foo")
    def check_foo(cls, v, **kwargs):
        return v

assert FooModel().foo == 42
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.0.dev0
install path: ...
python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.19044-SP0
optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Good catch, this is a bug in pydantic-core.

Because the immediate field validator is not a `DefaultValidator`.

**Comment by florianfischer91** [comment]
Do you want to solve it by yourself? Otherwise i can also try and fix it if you can give me a hint how/where to start. I looked into the rust code and understand on a high level how the validators are created but don't know if it is just a small change or if i have to change f.i. the order of FunctionValidator -> DefaultValiidator
