### ISSUE TITLE
Type pd.Timestamp not enforced

### ISSUE THREAD

**Issue by nv-pipo** [pydantic/pydantic#5053]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using the BaseModel, pydantic ignores the specified type pd.Timestamp and converts to python's native datetime.

Uncommenting the custom __init__ makes the code print "Success!", but then what's the point, right?

### Example Code

```Python
import pandas as pd
from pydantic import BaseModel

object_sample = {
  "created_at": "2023-02-13T20:14:00.936721506Z"
}

class SamplePandasTimestamp(BaseModel):
    created_at: pd.Timestamp

    # def __init__(self, **data):
    #     data["created_at"] = pd.Timestamp(data["created_at"])
    #     super().__init__(**data)


instance_object = SamplePandasTimestamp(**object_sample)
if isinstance(instance_object.created_at, pd.Timestamp):
    print("Success!")
else:
    print("Failure")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /Users/pichurri/miniforge3/envs/py3_10-pydantic/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ]
                     platform: macOS-13.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
The problem comes from the fact that `pd.Timestamp` is a subclass of `datetime.datetime`. The validator that is parsing as a `datetime.datetime` is looked up by subclass relationship; @samuelcolvin I wonder if, in the case where a validator is retrieved by a subclass lookup, if the type is a strict subclass, we could (perhaps optionally?) add a validator that applies the class to the returned value. To prevent issues like this where the value is parsed with an incorrect type.

I'm not sure if this has been resolved in v2 or not.

For what it's worth, you may be able to work around this with:
```python

class PandasTimestamp(pd.Timestamp):
    @classmethod
    def convert_from_datetime(cls, v: Any) -> pd.Timestamp:
        return PandasTimestamp(v)  # could also return pd.Timestamp(v)

    @classmethod
    def __get_validators__(cls):
        # one or more validators may be yielded which will be called in the
        # order to validate the input, each validator will receive as an input
        # the value returned from the previous validator
        yield cls.convert_from_datetime


class SamplePandasTimestamp(BaseModel):
    created_at: PandasTimestamp
```

**Comment by samuelcolvin** [comment]
I don't think we can do anything for this in v1.

In v2, I think we should add documentation on how to work around this. We could even raise an error for subtypes to force the user to decide what to do manually.

**Comment by nv-pipo** [comment]
Thank you for the update and for the workaround 👍

**Comment by kamichal** [comment]
> I don't think we can do anything for this in v1.

Oh yes, you neglect 500 open issues because of v2.

# pydantic gets rusty

Regardless of how super-duper the V2 is going to be, the V1 is going to be keep in use for years by thousands of developers. You cannot stop maintaining v1.

**Comment by samuelcolvin** [comment]
V2 existed precisely because many of the open issues can't be solved in v1.

We're not ignoring open issues, we're working flat out to build a new version of pydantic that addresses them.

We are continuing to maintain v1, example - the patch release last week.

What we're not doing is implementing changes of behaviour in v1 which might break existing code, however loudly some people might demand those changes.

**Comment by dmontagu** [comment]
@adriangb I think this should be possible now in v2 with a custom annotation, but I'm not sure if there's currently a clean way to do it that works nicely with annotations/etc. Not sure if you have any good ideas. (Obviously if we ignore annotations, we can just produce a core schema that does a after function validator to convert to pd.Timestamp)

**Comment by dmontagu** [comment]
Need to add docs for handling custom types like this in v2 following `tests.test_types.test_third_party_type_integration` or similar.

**Comment by PierreSnell** [comment]
Hello, sorry to bump here, I haven't found a better place to ask. 

I got a similar problem with : 

```python
class MyModel(BaseModel):
    ...
    reception_date: datetime | None = Field(...,  gt=DEFAULT_MIN_DATETIME,  lt=DEFAULT_MAX_DATETIME)
```

Omitting the `Field` and everything is fine (I got a custom decorated validator to replace the validation) however, I don't have the `gt` and `lt` in the schema... 

Doing as above I ran into a 
```
ValueError: On field "reception_date" the following field constraints are set but not enforced: lt, gt. 
For more details see https://docs.pydantic.dev/usage/schema/#unenforced-field-constraints
```

I could use `exclusiveMaximum` to enforce my schema and keep the decorated validation function but I was wondering if what I was trying to do is possible. 

Thanks in advance, 
Have a great day.

**Comment by adriangb** [comment]
@PierreSnell I don't think this issue is the right place.

That said, on `main` at least I can't reproduce:

```python
from datetime import datetime

from pydantic import BaseModel, Field


class MyModel(BaseModel):
    reception_date: datetime | None = Field(..., gt=datetime(year=1999, month=1, day=1))


MyModel(reception_date=datetime(year=2000, month=1, day=1))  # no error
MyModel(reception_date=datetime(year=1990, month=1, day=1))  # error
```

**Comment by nv-pipo** [comment]
- [Tests with V2](#tests-with-v2)
  - [Same code as initial report](#same-code-as-initial-report)
  - [With "arbitrary\_types\_allowed=True"](#with-arbitrary_types_allowedtrue)
    - [Conversion fail (no conversion str -\> pd.Timestamp)](#conversion-fail-no-conversion-str---pdtimestamp)
    - [Validation success (passing a pd.Timestamp value)](#validation-success-passing-a-pdtimestamp-value)
  - [Workaround to achieve validation and conversion (manually convert the string to pd.Timestamp)](#workaround-to-achieve-validation-and-conversion-manually-convert-the-string-to-pdtimestamp)
- [Tested version](#tested-version)


# Tests with V2
## Same code as initial report
~~~python
import pandas as pd
from pydantic import BaseModel, ConfigDict

object_sample = {"created_at": "2023-02-13T20:14:00.936721506Z"}


class SamplePandasTimestamp(BaseModel):
    created_at: pd.Timestamp

    # def __init__(self, **data):
    #     data["created_at"] = pd.Timestamp(data["created_at"])
    #     super().__init__(**data)


instance_object = SamplePandasTimestamp(**object_sample)
if isinstance(instance_object.created_at, pd.Timestamp):
    print("Success!")
else:
    print("Failure")
~~~
Output: 
~~~shell
❯ python timestamp_bug_validation.py
Traceback (most recent call last):
  File "/Users/pichurri/pydantic_bug/timestamp_bug_validation.py", line 7, in <module>
    class SamplePandasTimestamp(BaseModel):
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 173, in __new__
    complete_model_class(
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 463, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/main.py", line 549, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 426, in generate_schema
    return self._generate_schema_for_type(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 458, in _generate_schema_for_type
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 528, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 528, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 848, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 900, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1586, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1550, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 689, in _generate_schema
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 776, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 375, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'pandas._libs.tslibs.timestamps.Timestamp'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.1.1/u/schema-for-unknown-type
❯
~~~

## With "arbitrary_types_allowed=True"
- [ ] Works for conversion (as it does when passing a string with an int to an int property)
- [X] Works for validation, only accepts objects with field of the right type
### Conversion fail (no conversion str -> pd.Timestamp)
~~~python
import pandas as pd
from pydantic import BaseModel, ConfigDict

object_sample = {"created_at": "2023-02-13T20:14:00.936721506Z"}


class SamplePandasTimestamp(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    created_at: pd.Timestamp

    # def __init__(self, **data):
    #     data["created_at"] = pd.Timestamp(data["created_at"])
    #     super().__init__(**data)


instance_object = SamplePandasTimestamp(**object_sample)
if isinstance(instance_object.created_at, pd.Timestamp):
    print("Success!")
else:
    print("Failure")
~~~
Output:
~~~shell
❯ python timestamp_bug_validation.py
Traceback (most recent call last):
  File "/Users/pichurri/pydantic_bug/timestamp_bug_validation.py", line 17, in <module>
    instance_object = SamplePandasTimestamp(**object_sample)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic/main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SamplePandasTimestamp
created_at
  Input should be an instance of Timestamp [type=is_instance_of, input_value='2023-02-13T20:14:00.936721506Z', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1/v/is_instance_of
~~~
### Validation success (passing a pd.Timestamp value)
~~~python
import pandas as pd
from pydantic import BaseModel, ConfigDict

object_sample = {"created_at": pd.Timestamp("2023-02-13T20:14:00.936721506Z")}


class SamplePandasTimestamp(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    created_at: pd.Timestamp

    # def __init__(self, **data):
    #     data["created_at"] = pd.Timestamp(data["created_at"])
    #     super().__init__(**data)


instance_object = SamplePandasTimestamp(**object_sample)
if isinstance(instance_object.created_at, pd.Timestamp):
    print("Success!")
else:
    print("Failure")
~~~
Output:
~~~shell
❯ python timestamp_bug_validation.py
Success!
~~~

## Workaround to achieve validation and conversion (manually convert the string to pd.Timestamp)
~~~python
import pandas as pd
from pydantic import BaseModel, ConfigDict

object_sample = {"created_at": "2023-02-13T20:14:00.936721506Z"}


class SamplePandasTimestamp(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    created_at: pd.Timestamp

    def __init__(self, **data):
        data["created_at"] = pd.Timestamp(data["created_at"])
        super().__init__(**data)


instance_object = SamplePandasTimestamp(**object_sample)
if isinstance(instance_object.created_at, pd.Timestamp):
    print("Success!")
else:
    print("Failure")
~~~
Output:
~~~shell
❯ python timestamp_bug_validation.py
Success!
~~~

# Tested version
~~~python
>>> print(pydantic.version.version_info())
             pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/pichurri/pydantic_bug/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:58:31) [Clang 14.0.6 ]
                     platform: macOS-13.5-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
~~~
What would be more proper fix/workaround?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
