### ISSUE TITLE
[feature request] Support annotated_types.Predicate

### ISSUE THREAD

**Issue by ddneilson** [pydantic/pydantic#5054]
I'd like to request that pydantic V2 & pydantic-core add support for `annotated_types.Predicate`. Though the functionality can be achieved with the `@validator` decorator, the motivation for including it is the same as supporting the length, and value-comparison annotations -- it lets the developer see the validations that they need to know about for a field without going through the whole model class' implementation.

i.e. A model like the following should be possible:

```python
import sys
from pydantic import BaseModel
from annotated_types import Predicate

if sys.version_info < (3,9):
    from typing_extensions import Annotated
else:
    from typing import Annotated

def lookup_dynamic_length_constraint():
    return 20

func = lambda s: len(s) < lookup_dynamic_length_constraint()

class ErrorModel(BaseModel):
    attr: Annotated[str, Predicate(func)]
```

It currently raises an error:
```
# pydantic-2.0.0.dev0 - hash: ef3cc495a9c86553b62a95a6052fd9b6ebc045e9

pydantic_core._pydantic_core.SchemaError: Invalid Schema:
typed-dict -> fields -> attr -> schema -> str -> func
  Extra inputs are not permitted [type=extra_forbidden, input_value=<function <lambda> at 0x7fda9156aee0>, input_type=function]
```

Ideally, it would support multiple Predicates in an annotation:
```
class ErrorModel(BaseModel):
    attr: Annotated[str, Predicate(lambda x: ...), Predicate(lambda x: ...), ... etc]
```

It looks like this support would need to be added in pydantic-core, hence the ticket in this tracker rather than the main pydantic one.

A pydantic-core reproducer for the exception above follows:

```python
from pydantic_core import SchemaValidator

func = lambda s: True
inner_schema = {'type': 'typed-dict', 'fields': {'attr': {'schema': {'type': 'str', 'func': func}, 'required': True}}, 'return_fields_set': True, 'ref': '__main__.ErrorModel'}
core_config = {'title': 'ErrorModel', 'typed_dict_extra_behavior': 'ignore', 'allow_inf_nan': True, 'populate_by_name': False, 'str_strip_whitespace': False, 'str_to_lower': False, 'str_to_upper': False, 'strict': False, 'ser_json_timedelta': 'iso8601', 'ser_json_bytes': 'utf8'}

SchemaValidator(inner_schema, core_config)

# pydantic-core-0.8.2

# Traceback (most recent call last):
#   File "testannotation.py", line 36, in <module>
#     SchemaValidator(inner_schema, core_config)
# pydantic_core._pydantic_core.SchemaError: Invalid Schema:
# typed-dict -> fields -> attr -> schema -> str -> func
#   Extra inputs are not permitted [type=extra_forbidden, input_value=<function <lambda> at 0x7fda9156aee0>, input_type=function]
```

**Comment by samuelcolvin** [comment]
Moving this to pydantic as I don't think it relates to `pydantic-core` particularly.

**Comment by dmontagu** [comment]
Is `Predicate` equivalent to `pydantic.functional_validators.PlainValidator`? If so, it should be straightforward to support by doing something analogous to `pydantic.functional_validators.PlainValidator.__get_pydantic_core_schema__`.

**Comment by adriangb** [comment]
Support was added in https://github.com/pydantic/pydantic/commit/4985c179d8b9e6488310c77ce71b13cffc942cf7#diff-86a65771e6ad3cc8717cf45416efa0a988c12ddf9224afc222e5317e3a287291. I somewhat arbitrarily made it an `AfterValidator`, I guess it could have just as easily been a `Plain` validator. I don't think `Before` makes much sense and `Wrap` straight up would not work. I'm open to changing it to `Plain` if anyone feels strongly about it.
