### ISSUE TITLE
Add a method like __repr__ or __str__

### ISSUE THREAD

**Issue by Harry-Jing** [pydantic/pydantic#5057]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

It can personalize the output when debugging. Becauese sometimes the data is too large that I don't want is for output to much.

Thist's probably what it means
```python
class Model(BaseModel)
    class config:
        custom_repr = lambda cls: f'<Model[(a={cls.a}, b={cls.b:2})]>'

```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [X] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Why don't you override `__repr__` and `__str__`?

**Comment by Harry-Jing** [comment]
But how?

```python
class Surround(BaseModel):
    name: str
    
    def __repr__(self) -> str:
        return self.name

print(Surround(name='Harry'))
```
```
>>> name='Harry'
```

**Comment by hramezani** [comment]
You need to override `__str__` to see your desired output in the `print` statement output.

You can use [repr builtin function](https://docs.python.org/3/library/functions.html#repr) to print the representation of an object
```python
>>> class Surround(BaseModel):
...     name: str
...     
...     def __repr__(self) -> str:
...         return self.name
...     def __str__(self) -> str:
...         return self.name
... 
>>> print(Surround(name='Harry'))
Harry
>>> print(repr(Surround(name='Harry')))
Harry
```

**Comment by Harry-Jing** [comment]
Thanks a lot
