### ISSUE TITLE
Hypothesis plugin not working with alias and special characters

### ISSUE THREAD

**Issue by galbino** [pydantic/pydantic#5062]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hi, I have a schema that uses an alias containing `$` within its name and it seems that, on that case, hypothesis can't generate input values for it and it raises the following error:

```
>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for ExampleSchemaBad
E   $example
E     field required (type=value_error.missing)

pydantic/main.py:342: ValidationError

FAILED tests/unit/test_pylint.py::test_dollar_sign - pydantic.error_wrappers.ValidationError: 1 validation error for ExampleSchemaBad
```

Apparently the issue isn't only with the dollar sign, but with all special characters

### Example Code

```Python
import hypothesis
import pydantic
from hypothesis import strategies as st


class ExampleSchemaBad(pydantic.BaseModel):
    example: str = pydantic.Field(alias="$example")


class ExampleSchemaGood(pydantic.BaseModel):
    example: str = pydantic.Field(alias="other")


@hypothesis.given(
    request=st.builds(
        ExampleSchemaBad,
    )
)
def test_dollar_sign(
    request: ExampleSchemaBad,
) -> None:
    pass


@hypothesis.given(request=st.builds(ExampleSchemaGood))
def test_clean(
    request: ExampleSchemaGood,
) -> None:
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
               python version: 3.10.5 (main, Oct  3 2022, 09:43:47) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-13.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by galbino** [comment]
As a possible workaround, for some of you that might be facing the same issue, something like:
`@hypothesis.given(st.builds(ExampleSchemaBad, **{"$example": st.text()}))`
seems to work.

**Comment by hramezani** [comment]
Hi @galbino,

Thanks for reporting the issue and for the workaround.

I can confirm the problem. I think it can't get a fix in `v1`. 
@samuelcolvin Do you have any idea how to fix the problem? or even do we want to fix it in `V2`?

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
