### ISSUE TITLE
Consider ad-hoc code generation

### ISSUE THREAD

**Issue by westandskif** [pydantic/pydantic#5066]
`pydantic` has few places with loops over e.g. `cls.model_fields.items()`
Such cases could benefit from ad-hoc code generation at the expense of time, spent on the code generation.

Should you find a case where you see a room for these "plan once - execute multiple times" stages, please consider me as a resource (I have a library which could help):

```python
fields = ["a", "b", "c"]
data = {"a": 1, "b": 2, "c": 3}

In [15]: %timeit {f: data[f] for f in fields}
179 ns ± 0.179 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

from convtools import conversion as c
converter = c({f: c.item(f) for f in fields}).gen_converter()  # ad-hoc converter
In [16]: %timeit converter(data)
127 ns ± 0.0657 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

# But as I mentioned, at the expense of:
In [18]: %timeit c({f: c.item(f) for f in fields}).gen_converter()
61.3 µs ± 135 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

# and under the hood it generates:
In [19]: c({f: c.item(f) for f in fields}).gen_converter(debug=True)
def converter(data_):
    try:
        return {"a": data_["a"], "b": data_["b"], "c": data_["c"]}
    except __exceptions_to_dump_sources:
        __convtools__code_storage.dump_sources()
        raise

Out[19]: <function _convtools.converter(data_)>
```

**Comment by adriangb** [comment]
Can you point to some specific areas? Most of the heavy lifting in v2 is done in Rust, there should be no or few loops over `model_fields`. The only one I see is in `model_construct`, which is already fast enough.

**Comment by westandskif** [comment]
> `model_construct`, which is already fast enough

I see, no need then. And yes, you've pointed at a right one.
