### ISSUE TITLE
Broken Link in the Documentation - pydantic/utils.py doesn't exist anymore

### ISSUE THREAD

**Issue by mrmammadov** [pydantic/pydantic#5071]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

There is a broken link in Pydantic Doc - [Data Binding part](https://docs.pydantic.dev/usage/models/#data-binding)
The link that refers to `GetterDict` in `utils.py` doesn't exist anymore in _main_ branch and seems like `utils.py` is moved to `_internal/_utils.py` but still `GetterDict` doesn't exist there as well. 

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
pydantic compiled: True
install path: /Users/gulumammadli/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pydantic
python version: 3.10.0 (default, Jan 20 2022, 00:04:12) [Clang 12.0.5 (clang-1205.0.22.11)]
                     platform: macOS-11.6-x86_64-i386-64bit
optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by mrmammadov** [comment]
The url should be changed to [https://github.com/pydantic/pydantic/blob/v1.10.5/pydantic/utils.py](url)
I can take this over if needed @samuelcolvin

**Comment by samuelcolvin** [comment]
Pr welcome to fix this.

**Comment by hramezani** [comment]
Fixed in https://github.com/pydantic/pydantic/commit/314abcabbde0936ec2e8e5ff6532d64a221210c5
