### ISSUE TITLE
v2 JSON schema — parsing vs. serialization

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5072]
In https://github.com/pydantic/pydantic/issues/1511 there is some discussion about what schema should be generated for Decimal. One of the points that has been brought up is the idea that you could produce a schema based on what is accepted/"validated", and you could produce a schema based on what is "serialized", and these could be different. (Most commonly, if multiple types pass validation, the serialization schema would be just one of those types.)

I want to dive into the implications of this a bit so we can come up with a plan for how we want to handle this, as it may be relevant for more types than just Decimal — basically any time the serialization and validation schemas are different for any reason.

--------

First, I'll note that when producing an OpenAPI spec with FastAPI, at least in the clients I've generated, the same definitions are used as "inputs" to API calls where appropriate, and as "outputs" from API calls where appropriate. This means that if a model is used as both an input and an output to (possibly different) API endpoints, there are significant practical benefits if the JSON schema produced for it works both for server-side parsing ("validation" from the perspective of pydantic) and client-side parsing ("serialization" from the perspective of pydantic). (Otherwise you could run into type errors when the generated client handles the server responses.)

When the serialization and validation schemas differ for a model, I see at least four choices that could make sense depending on how the model is used:
* "Validation": Produce a JSON schema based on the validation schema. I consider this the "naive" approach, and is how I've been proceeding so far with #5029
* "Serialization": Produce a JSON schema based on the serialization schema. This may be more appropriate for use with server responses, considering the server will know exactly how something will be serialized, even if different formats are allowed as inputs.
* "Intersection": Try to produce a JSON schema compatible with _both_ serialization and validation; in practice, this is likely to just be the serialization schema in most cases where it is sensible.
* "Union": Try to produce a JSON schema that represents all allowed validation inputs _and_ serialization outputs, even if they are different. Code written to handle the "union" as a response from the server will put some additional burden on the client to check the type of returned values even though in practice only one of the forms will be returned. But this would be the most convenient way to define a single model that was compatible with all possible representations.

Now, in principle, it should be possible to generate JSON schema in accordance with whichever of the above we want, and we could even add a flag for this. In particular, I think we _could_ do something where we pass a flag through to the JSON schema generation on a per-model (or even per-model-occurrence?) basis for whether to use the "validation" or "serialization" schema. And FastAPI/similar could handle this automatically depending on whether an annotation was for an input argument, or the return type of the endpoint.

**However**, I think there is a practical downside to this fine-grained approach, even if FastAPI takes full responsibility for using the "validation" schema for input parameters and "serialization" schema for return values: many APIs include endpoints that accept an object of a certain type, and return an object of the same type, and it is often preferable to use the same struct type in client code for both. If we were to produce different JSON schemas for inputs and outputs of the same model, I think this may cause some challenges in getting a generated OpenAPI client to use the same struct for both input and output.

--------

I am interested to get other people's thoughts about the best way to handle this, especially @tiangolo as I think this will have significant implications for FastAPI.

Some things for us to consider:
* Should we make it a configuration option of what type of schema should be generated (serialization vs. validation)?
    * If not, which should be preferred?
* Should it be possible to generate different schema "variants" for the same model? (E.g., by adding an argument to `model_json_schema` indicating whether to produce the "validation" or the "serialization" schema)
    * (Note this may have the above-described implications for OpenAPI specs, etc.)
* Should we just make it easy to configure the JSON schema used for Decimal and ignore all of this validation vs. serialization complexity? (Maybe Decimal is the only type where this will be a "common" issue?)

**Comment by adriangb** [comment]
One semi obvious solutions is to do the "union" of input types and output types. So for Decimal it might be `str, float, int`. One immediate issue with this is that it is _gross_ for clients/consumers: they have to handle all three cases even though in practice we always serialize Decimal` as a string. But it gets even worse: for our Json type the input is always a string and the output is always an object. So if we did `object,str` we would be saying we accept an object but we don't, it would always fail.

**Comment by adriangb** [comment]
> we want to add an attribute to GenerateJsonSchema saying whether the generated schema should be used for parsing (inputs, generally laxer) or serialization (generally stricter).

Is `GenerateJsonSchema` the public API? The point is, FastAPI _knows_ if a model is being used as an input, output or both and should be able to generate both the input/output schemas (e.g. by setting a parameter on whatever it needs to call to build the schemas) and then comparing them to see if they are the same or not (and if they are not, include them both with an `{ModelName}Input` and `{ModelName}Output` suffix or something like that).

**Comment by dmontagu** [comment]
Yes, `GenerateJsonSchema` is meant to be public (and overridden by users as desired). I think the idea would be that we create a new argument (meant to represent validation-vs.-serialization; not sure what to call it) to `model_json_schema` that gets passed through directly into the `__init__` call to `GenerateJsonSchema`, and stored as an instance attribute. Then that instance attribute would be used in the method calls in GenerateJsonSchema where necessary to build the schema
