### ISSUE TITLE
V1: invalid validation error's field path with `__root__` type being a `list`

### ISSUE THREAD

**Issue by kamichal** [pydantic/pydantic#5078]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Ways to reproduce:

Define an object type with a custom `__root__` being a `list` and do not provide a default factory for it, e.g.:

```python
class AList(BaseModel):
    __root__: List[int]
```

If this is used as a field of any other data object, then a `ValidationError` does not tell for which field of parent did the validation fail.

The error message from the example below is:
```
Traceback (most recent call last):
  File "xxx/scratches/pydantic_error.py", line 21, in <module>
    Root(aggregate={"list_a": [], "list_b": []})
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Root
aggregate -> __root__
  field required (type=value_error.missing)
```

## The problem:

The field path provided by this error message  is `aggregate -> __root__`

## Expected result
It is supposed to be `aggregate -> list_c` 

In this example this is simple to get the cause, but for sophisticated data structures it's impossible to determine it.

### Example Code

```Python
from typing import List

from pydantic import BaseModel, Field


class AList(BaseModel):
    __root__: List[int]  # no default factory


class AnAggregate(BaseModel):
    list_a: AList = Field(default_factory=AList)
    list_b: AList = Field(default_factory=AList)
    list_c: AList = Field(default_factory=AList)


class Root(BaseModel):
    aggregate: AnAggregate = Field(default_factory=AnAggregate)


# list_c is missing, which causes the error
Root(aggregate={"list_a": [], "list_b": []})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 install path: xxx/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
                     platform: Linux-5.15.93-1-MANJARO-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Root types aren't designed to be used as fields/children, although I know people do.

While this behaviour might seem annoying, we really can't change it in v1 - someone somewhere will have code which expects this behaviour.

This is why we need a new major release which fixes edge cases like this, in this case `__root__` is being dropped completely, and replaced by support for validating and recognised type directly.

**Comment by kamichal** [comment]
> someone somewhere will have code which expects this behaviour.

What? Someone is expecting a malformed error message? It doesn't contain the actual information, do you think that anybody will be disappointed if you fix it and in place of `__root__` - `list_c` appears?
