### ISSUE TITLE
Document pydantic's private/protected names

### ISSUE THREAD

**Issue by badge** [pydantic/pydantic#5079]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Today I wrote a container class in Pydantic, which I needed to be an iterable. I wrote something like this:

```python
class ThingContainer(BaseModel):
    __root__: List[Thing]
    _iter: Any = PrivateAttr(default=None)

    def __iter__(self):
        self._iter = iter(self.__root__)
    def __next__(self):
        return next(self._iter)
```

This lead to a confusing error message about `_iter` not being callable, and I messed around with my model until I finally looked at the `BaseModel` definition and found that `_iter` was a private method and I needed to name my variable something else.

At the time of writing, there are [14,608](https://github.com/search?q=next%28self._iter%29&type=Code) code results for `next(self._iter)` on GitHub. It'd be nice if the pydantic documentation had somewhere that documented `BaseModel`'s private/protected method and attribute names so that people aren't similarly tripped up.

I'm happy to contribute a PR if there's agreement that this would be useful, and direction on where in the docs it should go!

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Happy to add a section to the docs for V1 to list and explain the private methods.

In V2, every private or dunder method will be named `_pydantic_*`, and we'll have documentation which says

> If you interfere without anything starting `__pydantic_*`, you're on your own, it's your own funeral

**Comment by samuelcolvin** [comment]
I should add that I totally agree it's confusing, hence the changes in V2.
