### ISSUE TITLE
union type order matters in pydantic coercions

### ISSUE THREAD

**Issue by tnielens** [pydantic/pydantic#5080]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The order of the types in a union type seems to influence the type coercion in a surprising way. In the example bellow, depending on the order, the argument is coerced or isn't.

### Example Code

```Python
from datetime import datetime
from pydantic import StrictStr, validate_arguments

@validate_arguments
def pydantic_test_datetime_first(dt: datetime | StrictStr):
    return dt

@validate_arguments
def pydantic_test_str_first(dt: StrictStr | datetime):
    return dt

print(pydantic_test_datetime_first("2022-01-01T00:00:00+00:00").__repr__())
print(pydantic_test_str_first("2022-01-01T00:00:00+00:00").__repr__())

# prints
# datetime.datetime(2022, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
# '2022-01-01T00:00:00+00:00'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 install path: /mydir/env/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Aug 17 2022, 12:10:28) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-13.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
For what it's worth, this is a [documented behavior](https://docs.pydantic.dev/usage/types/#unions) and is by design. (There is a "Smart Union" option, but I'm not sure it will help with this example.)

There will be more that could be done with tagged unions and function-discriminators in pydantic v2 to better handle this, but may be a little while before that functionality is well-documented (we'll need to release v2 first, for starters).

**Comment by tnielens** [comment]
My bad for missing that obvious doc section. I'll give the `Config.smart_union` option a try. Thanks!
