### ISSUE TITLE
KeyError: '__dict__'

### ISSUE THREAD

**Issue by samstratton13** [pydantic/pydantic#5082]
Hello I am getting the following error and haven't been able to resolve it. Does anyone know what is causing this/how to fix it? 

  File "lib\site-packages\pandas\io\pickle.py", line 208, in read_pickle
    return pickle.load(handles.handle)
  File "pydantic\main.py", line 417, in pydantic.main.BaseModel.__setstate__
KeyError: '__dict__'

**Comment by hramezani** [comment]
Hello @samstratton13.
Could you please close this one and open a new bug by following the [bug report](https://github.com/pydantic/pydantic/issues/new?assignees=&labels=bug%2Cunconfirmed&template=bug.yml) template?

**Comment by Kludex** [comment]
Given @hramezani instructions, I'll be closing this issue. Please feel free to open a new issue following those instructions.
