### ISSUE TITLE
mypy tests are taking minutes (literally)

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5083]
What's going on with mypy tests, they're taking an incredibly long time, see [this recent build](https://twitter.com/wes321/status/1627718493691838478).

Slow tests:

```
62.41s call     tests/mypy/test_mypy.py::test_mypy_results[pyproject-plugin-strict.toml-plugin_success.py-plugin-success-strict.txt]
59.77s call     tests/mypy/test_mypy.py::test_mypy_results[mypy-plugin-strict-no-any.ini-dataclass_no_any.py-None]
56.15s call     tests/mypy/test_mypy.py::test_mypy_results[pyproject-default.toml-success.py-None]
54.15s call     tests/mypy/test_mypy.py::test_mypy_results[mypy-plugin-strict.ini-plugin_success.py-plugin-success-strict.txt]
51.63s call     tests/mypy/test_mypy.py::test_mypy_results[mypy-default.ini-success.py-None]
51.50s call     tests/mypy/test_mypy.py::test_mypy_results[pyproject-plugin.toml-plugin_success.py-None]
49.02s call     tests/mypy/test_mypy.py::test_mypy_results[mypy-plugin.ini-plugin_success.py-None]
1.41s call     tests/mypy/test_mypy.py::test_mypy_results[pyproject-default.toml-fail4.py-fail4.txt]
1.31s call     tests/mypy/test_mypy.py::test_mypy_results[mypy-plugin-strict.ini-plugin_fail_baseConfig.py-plugin-fail-strict-baseConfig.txt]
0.67s call     tests/mypy/test_mypy.py::test_mypy_results[pyproject-default.toml-fail3.py-fail3.txt]
```

This wasn't the case until a recent upgrade of mypy.

Any suggestions on how to fix it?

**Comment by koxudaxi** [comment]
> see [this recent build](https://twitter.com/wes321/status/1627718493691838478).

:thinking: 
It's only 1 min.

**Comment by koxudaxi** [comment]
What mypy version did you say?
I tested some versions without mypy cache in the main branch.
The latest version improved the speed.
`coverage run -m pytest --durations=10 tests/mypy `

```bash
tail -n3 mypy*.log 
==> mypy0.961.log <==
Results (136.28s):
        38 passed
         5 xfailed

==> mypy0.982.log <==
Results (286.70s):
        38 passed
         5 xfailed

==> mypy1.0.0.log <==
Results (75.57s):
        38 passed
         5 xfailed

==> mypy1.0.1.log <==
Results (75.38s):
        38 passed
         5 xfailed

```

**Comment by samuelcolvin** [comment]
thanks for that @koxudaxi, so it looks like upgrading to the latest mypy should help quite a lot.

PR welcome.

**Comment by koxudaxi** [comment]
@samuelcolvin 
Mypy 1.0.0 is improved performance than the old version.
I posted the detail to the PR https://github.com/pydantic/pydantic/pull/5086
Thank you.

**Comment by samuelcolvin** [comment]
Closing this for now, but we might need to investigate further.

**Comment by samuelcolvin** [comment]
thanks so much @koxudaxi for working on this.

**Comment by dmontagu** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/35119617/220482105-39b090a7-9500-4b5d-a018-1817742c0ee7.png">
this is brutal

**Comment by antonagestam** [comment]
I suspect this is not isolated to internal type-checking. I've been [experimenting with using the new custom type facilities](https://github.com/antonagestam/immoney/pull/35) and when running mypy with Pydantic @ 580f75d7afe39ae43d0bebb90efa1bdd5719167f, it wouldn't finish after 5+ minutes (usually a sub-second invocation).

I have an unfounded suspicion that this is due to the large unions in `pydantic_core.core_schema`.

**Comment by dmontagu** [comment]
@antonagestam I think we've gotten explicit confirmation from the mypy devs that that is the source of the issue (combined with the fact that the relevant types are generally recursive). Unfortunately I'm not sure there is a great solution to this at this time but it is something that we are hoping to get improved (and/or help improve) in a future version of mypy.

(For what it's worth, pyright does not struggle in the same way.)

**Comment by antonagestam** [comment]
OK, is there any plan to address this somehow for V2? I found my way to the mypy issue now, and to tack on [this comment](https://github.com/python/mypy/issues/14034#issuecomment-1307163745):

> it's still not really acceptable for either CI or new contributors for mypy to take minutes.

I think it's also not really acceptable for Pydantic users, and neither is switching from mypy. FWIW, PyCharm has seemed to run extremely CPU intensive now as well, I'm thinking it might not be a coincidence.

**Comment by samuelcolvin** [comment]
see [PyCharm 2023.1 EAP 5](https://blog.jetbrains.com/pycharm/2023/03/2023-1-eap-5/), and specifically [PY-56541](https://youtrack.jetbrains.com/issue/PY-56541).

**Comment by samuelcolvin** [comment]
for anyone coming to this. The cause of the massive slowdown is `core_schema.py` in pydantic-core, even with `--disable-recursive-aliases`, it increases the time to typecheck pydantic (or a minimal example of code using pydantic) from <1s to ~28s.

The ultimate solution is for mypy to do something to improve the way the inspect unions.

We have two potential hacky workarounds though, #5195 by me (not good) and https://github.com/pydantic/pydantic-core/pull/445 - good solution all things considered.

I'll also create an issue on mypy about this soon.

**Comment by adriangb** [comment]
I think we've resolved this between the changes in core schema and speedups in mypy itself
