### ISSUE TITLE
@validator ignored when annotated with @classmethod

### ISSUE THREAD

**Issue by ddeibert** [pydantic/pydantic#5087]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Issue #1415 identified that annotating a validator with @classmethod causes the validator to be ignored.

This forces a deviation from normal python coding practices.

Can a warning be added to https://docs.pydantic.dev/usage/validators/ to clarify that the @classmethod annotation should not be used with validators?  Also, are there other pydantic decorators that fall into this category?

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by piscesvivian** [comment]
Second!  `cls` will be warn in pycharm `Usually first parameter of a method is named 'self' `

**Comment by samuelcolvin** [comment]
This is fixed on main and v2 should work as expected.

Btw, you can use the pydantic plugin in pycharm which will avoid this warning.
