### ISSUE TITLE
JSON schema: Callable

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5096]
(This was left over from https://github.com/pydantic/pydantic/pull/5029)

We should resolve the xfailure of the following test:

https://github.com/pydantic/pydantic/blob/73373c3e08fe5fe23e4b05f549ea34e0da6a16b7/tests/test_json_schema.py#L1145-L1173

I don't have an opinion about what we _should_ do; I would be happy to keep backwards compatibility or break it, I would guess this is a pretty rare edge case.

I could also see it making sense to do things differently depending on whether there was a default value.

**Comment by dmontagu** [comment]
I've got something in the works that I think will solve this and other issues — an annotation you can add that just conveniently lets you override the "base" JSON schema to use for the field. That way, you don't have to subclass `GenerateJsonSchema` just to say "ignore this field".

The main thing I'm still trying to figure out is a clean API for omitting the field/etc. from the JSON schema, which I think we should also be able to do.

**Comment by adriangb** [comment]
Can we make `__get_pydantic_json_schema__` return `None | JsonSchemaValue`?

**Comment by dmontagu** [comment]
The main nuisance to that is the `__modify_schema__` function used to be supposed to return None (and modify the value in place). So I think it will be a common mistake to keep the logic doing that, which might more-silently misbehave than it currently would (since it will warn you now, and do what you intended).

I know we could have the behavior depend on the name of the function, but I think some people will still do the migration wrong at first. I could be convinced to make the change anyway, but another option is to introduce a new exception that should be raised, which I think wouldn't have any potential for conflict with existing APIs.

I have written some code that does that, but I could be convinced to just have `None` means omit.

**Comment by dmontagu** [comment]
@adriangb I added a comment on #5788 which I just opened about returning `None | JsonSchemaValue` — it's also easy to accidentally not return anything and then get slightly different behavior. Doesn't mean we can't make the change, but I view it as another potential minor source of confusion.

I think that omitting fields is a pretty rare thing to want to do, whereas forgetting to return something from your function (while quickly developing/prototyping) is probably more common, so it might be unfortunate if we make that behave differently. That said, I don't know what we do now and maybe it's not any better. (Of course we could fix that, but 🤷 adding an exception just for omitting fields also feels .. meh..)

**Comment by adriangb** [comment]
OK yeah that makes sense, I’m convinced. Can we re-use the existing Omit
error?

**Comment by dmontagu** [comment]
@adriangb do you mean the `pydantic_core.PydanticOmit` error? I'm good with that but in that case I would suggest that we re-export it from pydantic. Does that sound good to you?

**Comment by adriangb** [comment]
Yep
