### ISSUE TITLE
Attribute error for `functools.partial`

### ISSUE THREAD

**Issue by JensHeinrich** [pydantic/pydantic#5101]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Using a `partialmethod`or `partial` as a `validator` or `root_validator` creates an unhelpful `AttributeError`:
```
tests/conftest.py:14: in <module>
    class TestClass(BaseModel):
tests/conftest.py:17: in TestClass
    _custom_validate = validator("name")(validate)
pydantic/class_validators.py:93: in pydantic.class_validators.validator.dec
    ???
pydantic/class_validators.py:150: in pydantic.class_validators._prepare_validator
    ???
E   AttributeError: 'functools.partial' object has no attribute '__qualname__'
```

The problem is rooted at [this code](https://github.com/pydantic/pydantic/blob/314abcabbde0936ec2e8e5ff6532d64a221210c5/pydantic/class_validators.py#L150).

IMO an try except block with a test for partial methods would be useful here, telling the User to supply the "allow_reuse" parameter for partials.

### Example Code

```Python
from functools import partial

from pydantic import validator, BaseModel
from pydantic.main import ModelMetaclass
from pydantic.utils import GetterDict

def custom_validator(additional_stuff: str, cls: ModelMetaclass, values: GetterDict):
    print(additional_stuff)
    return values

validate = partial(custom_validator, "TEXT")

class TestClass(BaseModel):
    name: str

    _custom_validate = validator("name")(validate)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 install path: XXX/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
                     platform: Linux-5.19.0-31-generic-x86_64-with-glibc2.36
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @JensHeinrich for reporting this issue.

I can confirm the issue. `partial()` returns an instance, not a class or function.

it may fix by accessing the function in the following line. I mean replacing `f_cls.__func__.__qualname__` with `f_cls.__func__.func.__qualname__` in case of `partial`

https://github.com/pydantic/pydantic/blob/73373c3e08fe5fe23e4b05f549ea34e0da6a16b7/pydantic/_internal/_decorators.py#L204

Would you like to open a PR?

**Comment by JensHeinrich** [comment]
I am already working on a PR, but at the moment I just add a better error

**Comment by JensHeinrich** [comment]
Even if the `ref` is created in a better way (or the check just skipped by using `allow_reuse=True`) another `AttributeError` is raised [here](https://github.com/pydantic/pydantic/blob/10b8ec7dde62f5e4948a09b9114c5ac64d786ded/pydantic/class_validators.py#L170)

**Comment by JensHeinrich** [comment]
Alos signature creation doesn't work on it

**Comment by hramezani** [comment]
> Even if the `ref` is created in a better way (or the check just skipped by using `allow_reuse=True`) another `AttributeError` is raised [here](https://github.com/pydantic/pydantic/blob/10b8ec7dde62f5e4948a09b9114c5ac64d786ded/pydantic/class_validators.py#L170)

This one also can be fixed by the same change that I mentioned before.

> I am already working on a PR, but at the moment I just add a better error

I think we can make it work at least on `1.10.x` but I am not sure about `V2`.

@samuelcolvin Do you think we should prevent using `functools.partial` as a validator?

**Comment by JensHeinrich** [comment]
TBH I feel `functools` is broken here and we are just adding a workaround.
Even a `lambda` gets an `__qualname__`

**Comment by samuelcolvin** [comment]
> TBH I feel `functools` is broken here and we are just adding a workaround. Even a `lambda` gets an `__qualname__`

agreed. Feel free to create an issue on cpython and copy me into it, I'd be interest to see what they say.

Also, can you create a PR against main to see if this is working there?

**Comment by hramezani** [comment]
This one can be related https://bugs.python.org/issue34475

**Comment by JensHeinrich** [comment]
I created an issue  python/cpython#102323

**Comment by dmontagu** [comment]
I personally find the responses in the last two referenced issues reasonable; it seems we should just not assume that `__qualname__` definitely exists.

**Comment by JensHeinrich** [comment]
I'm good with using a default value instead, too.

**Comment by JensHeinrich** [comment]
I am working on a PR for v1.10 already

**Comment by JensHeinrich** [comment]
I would only allow those with `reuse=True`. Would you support that @samuelcolvin @dmontagu ?

**Comment by dmontagu** [comment]
(responded on the PR; overall I am fine with the change)

**Comment by Kludex** [comment]
This was solved in https://github.com/pydantic/pydantic/pull/5362 for V2.
