### ISSUE TITLE
Disable description generation for jsonschema

### ISSUE THREAD

**Issue by VakarisZ** [pydantic/pydantic#5106]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

[The docs](https://docs.pydantic.dev/usage/schema/) say that description for jsonschema is generated from the comments of the model. However, it's not possible to turn this behavior off if I don't want to generate descriptions for fields based on comments. 
For example if I have following structure:
```
class OtherModel(BaseModel):
    """
    blah blah
    """
    pass

class SomeModel(BaseModel):
    foo: OtherModel = Field(title="Credential collectors")
```
There's no way to get a schema without descriptions.
I should be able to do something like `SomeModel(foo=OtherModel()).schema(generate_descriptions=False)` or at least be able to `Field(description="")`.

It should also be pretty easy to implement that:
```
def model_process_schema(
    model: TypeModelOrEnum,
    *,
    by_alias: bool = True,
    generate_descriptions: bool = True,
    model_name_map: Dict[TypeModelOrEnum, str],
    ref_prefix: Optional[str] = None,
    ref_template: str = default_ref_template,
    known_models: TypeModelSet = None,
    field: Optional[ModelField] = None,
) -> Tuple[Dict[str, Any], Dict[str, Any], Set[str]]:
...
if doc and generate_descriptions:
    s['description'] = doc
...
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
We won't make this change in V1, since V1 is only recieving bug fixes now.

In V2 this is already possibly (since #5029 was merged a couple of days ago), by editing `model_json_schema_metadata`:

https://github.com/pydantic/pydantic/blob/ae481b99b3ce85802751770b523e89c6e3f51c12/pydantic/main.py#L385-L400

**Comment by VakarisZ** [comment]
Wow, thanks for a lightning fast response @samuelcolvin 
Could you suggest me a temporary solution? Do you know when a version 2 will be released? Thanks!

**Comment by samuelcolvin** [comment]
Temporary solution would probably be a function which recursively goes through the JSON Schema as a python object and removes `description`.

We're aiming for a alpha/beta release of V2 by the end of March, see #4887.

**Comment by VakarisZ** [comment]
That won't do as some descriptions I explicitly provided in `Field(description="My description")` and I want them to stay. By the time python object is generated it's not possible to distinguish between descriptions generated from comments vs generated from `description` parameter. 

For now I straight up just overrode the `model_process_schema` method.

**Comment by samuelcolvin** [comment]
I don't think we generate description from comments anywhere, do you mean docstrings?
