### ISSUE TITLE
Unable to reproduce behaviour in docs

### ISSUE THREAD

**Issue by montelius** [pydantic/pydantic#5107]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hey all! 👋 

I have done my best to find an explanation to this but I really can't. I haven't worked _a lot_ with pydantic before, so bare with me.

I'm currently reading the docs to see whether pydantic is a good choice for my implementation, and I'm not able to reproduce the behaviour described in the documentation for [Data Conversion](https://docs.pydantic.dev/usage/models/#data-conversion). If I understand the docs correctly, pydantic should successfully cast floats to ints, strings to floats, and ints to strings. I'm not able to do any of that.

Expected output according to documentation:
`{'a': 3, 'b': 2.72, 'c': '123'}`

Actual output:
```
Traceback (most recent call last):
  File "<masked>/test.py", line 10, in <module>
    print(Model(a=3.1415, b=' 2.72 ', c=123).dict())
  File "<masked>/python_libs/pydantic/pydantic/main.py", line 161, in __init__
    values, fields_set = __pydantic_self__.__pydantic_validator__.validate_python(data)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Model
a
  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=3.1415, input_type=float]
b
  Input should be a valid number, unable to parse string as an number [type=float_parsing, input_value=' 2.72 ', input_type=str]
c
  Input should be a valid string [type=string_type, input_value=123, input_type=int]
```

The code below is an exact copy from the linked documentation.

### Example Code

```Python
from pydantic import BaseModel


class Model(BaseModel):
    a: int
    b: float
    c: str


print(Model(a=3.1415, b=' 2.72 ', c=123).dict())
#> {'a': 3, 'b': 2.72, 'c': '123'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
pydantic compiled: True
install path: /Users/annamontelius/.pyenv/versions/3.10.6/envs/game-data-api/lib/python3.10/site-packages/pydantic
python version: 3.10.6 (main, Sep  9 2022, 10:03:50) [Clang 13.1.6 (clang-1316.0.21.2.5)]
platform: macOS-12.4-arm64-arm-64bit
optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [X] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Hi @montelius,

Seems you are running the example on `Pydantic V2`(main branch). based on the traceback that you provided it is the `main` branch.

This
```
  File "<masked>/python_libs/pydantic/pydantic/main.py", line 161, in __init__
    values, fields_set = __pydantic_self__.__pydantic_validator__.validate_python(data)
```
refers to 
https://github.com/pydantic/pydantic/blob/ae481b99b3ce85802751770b523e89c6e3f51c12/pydantic/main.py#L161

[The Data Conversion will change in V2](https://docs.pydantic.dev/blog/pydantic-v2/#formalised-conversion-table). So, that's why you get an error.

**Comment by samuelcolvin** [comment]
Thanks @hramezani
