### ISSUE TITLE
BaseSettings classes created invalid json file

### ISSUE THREAD

**Issue by elayos** [pydantic/pydantic#5114]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Deriving from BaseSettings class created invalid JSON (**bolded**)

{'title': 'MySettings', 'description': 'Base class for settings, allowing values to be overridden by environment variables.\n\nThis is useful in production for secrets you do not wish to save in code, it plays nicely with docker(-compose),\nHeroku and any 12 factor app design.', 'type': 'object', 'properties': {'id': {'title': 'Id', **'env_names': {'Id'}**, 'type': 'string'}, 'secret': {'title': 'Secret', **'env_names': {'secret'}**, 'type': 'string'}}, 'required': ['id', 'secret'], 'additionalProperties': False}

### Example Code

```Python
import json

class MySettings(BaseSettings):
    id: str
    secret: str

schema = MySettings.schema()

json.dump(schema, sys.stdout)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /Users/.../venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Feb 12 2023, 06:26:18) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [x] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
You may need to use `schema_json()`:

```python
class MySettings(BaseSettings):
    id: str
    secret: str

schema = MySettings.schema_json()
print(schema)
```

**Comment by adamjanovsky** [comment]
I've experienced a similar issue. If what @hramezani  suggests is a resolution, than docs are misleading IMO. See the example in [Top-level schema generation](https://docs.pydantic.dev/usage/schema/#top-level-schema-generation)

```python
# showing just excerpt, both Model and Bar are BaseModel classes

top_level_schema = schema([Model, Bar], title='My Schema')
print(json.dumps(top_level_schema, indent=2))
```

Would any of `Model`, `Bar` be a `BaseSetting` instance, the json serialization would not work. As `BaseSetting` is a child class of  `BaseModel`, I would expect this example to work (unless state oterwise).

Would you please consider clarifying in the documentation? Also, what's the preferred way to json serialize `BaseSettings` class along with some other class?

Thanks a lot for this project :heart:
