### ISSUE TITLE
(🐞) Mypy plugin doesn't work with positional arguments on `dataclasses`

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#5117]
On main [6267ae3](https://github.com/pydantic/pydantic/commit/6267ae3538cf7237ff6769174b4c340415e0f444)
```py
import pydantic

@pydantic.dataclasses.dataclass
class A:
    a: str

A("")  # error: Too many positional arguments for "A"  [misc]
```

See this: https://github.com/pydantic/pydantic/pull/5077#issuecomment-1445703011

**Comment by samuelcolvin** [comment]
Thanks for reporting. 

See further discussion on #5077.

Happy to accept fixes for v1, or v2 once we get dataclasses working.

**Comment by cdce8p** [comment]
Opened #5120 to remove the `kw_only_default` argument.

Guess it was originally added because `BaseModel` only excepts keyword arguments and it was used there - copy-paste error.
