### ISSUE TITLE
make `dataclass` type compatible with SQLAlchemy `dataclass_callable`

### ISSUE THREAD

**Issue by Evan6998** [pydantic/pydantic#5118]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

In SQLAlchemy 2.0 we can Integrate dataclass creation with ORM Declarative classes, like:
```python
from sqlalchemy.orm import DeclarativeBase, MappedAsDataclass
from pydantic.dataclasses import dataclass

class Base(MappedAsDataclass, DeclarativeBase, dataclass_callable=dataclass):
    pass
```

In SQLALchemy, the type of `dataclass_callable` is `Callable[..., Type[Any]]`, which seems reasonable.

However, `dataclass` in `pydantic` is of type `Callable[..., DataclassClassOrWrapper]`, 

`DataclassClassOrWrapper = Union[Type['Dataclass'], 'DataclassProxy']`
the `DataclassProxy ` is incompatible with `Type[Any]` and `pylance` complains with this.

I'm not sure which side should address this problem.

Versions

OS: MacOS 12.3
Python: Python 3.10.9
SQLAlchemy: 2.0.4
pyright: 1.1.295

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [X] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
@samuelcolvin can we address this with our approach to dataclasses in v2?

**Comment by samuelcolvin** [comment]
Quite possibly, there's even a chance it "just works™️".

**Comment by zikphil** [comment]
For reference: https://github.com/sqlalchemy/sqlalchemy/issues/9354

**Comment by zikphil** [comment]
Hello

Any ideas on a dirty patch that would make it work pending v2?

**Comment by dmontagu** [comment]
@zikphil Is this just producing mypy errors? Or does it result in runtime behavior issues?

If it's just type errors, you can just use `if TYPE_CHECKING:` to lie to mypy about what `pydantic.dataclasses.dataclass` is, something like:
```python
if typing.TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass
```

If that doesn't work for some reason (e.g., related to the pydantic plugin), I think the most sensible thing might be to just use `# type: ignore`.

If it's causing bigger issues that can't be resolved neatly with either of the above suggestions, please share more detail about what's going wrong.

**Comment by dmontagu** [comment]
Given the above responses, I'm going to close this now for the sake of cleaning up our open issues, but please comment if you want it reopened or still have issues in v2 and we can revisit.
