### ISSUE TITLE
`FilePath` with regex pattern

### ISSUE THREAD

**Issue by bendichter** [pydantic/pydantic#5121]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

Thanks for all the hard work on this project!

I'd like to be able to specify a field that is a `FilePath` and follows a specific regex pattern. The most common use-case of this would be to specify a suffix.

The context is I am using these as type hints, generating a json schema, and then using that to produce forms in the browser. I'd like to be able to inform a file selector modal what forms of files to accept.

Desired syntax:

```python
constr(regex=r'\.bin$', format="file-path")
```
json:
```json
{"pattern": "\\.bin$", "format": "file-path"}
```

or you might be able to go the other way somehow, using the `FilePath` type with a "pattern" arg.

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by bendichter** [comment]
Thanks for looking into this, @dmontagu! I was not aware of those approaches so thanks, this is helpful. This would work if you only wanted to affect the json-schema, but you might also want to leverage the FileType checker, which calls `validate_file`:

https://github.com/pydantic/pydantic/blob/73373c3e08fe5fe23e4b05f549ea34e0da6a16b7/pydantic/types.py#L352-L357

Could something like this work?

```python
from typing import Annotated
from pydantic import constr, FilePath

BinPath = Annotated[constr(pattern=r'\.bin$'), FilePath]
```

**Comment by dmontagu** [comment]
Given how flexible pydantic v2 is, I'm sure there should be a way to make this work. For now I would suggest using a validator but once we are closer to releasing (or after we've released) v2, I'd be happy to revisit this if you don't figure out how to achieve something equivalent in the meantime. (You might have to ping us again about this but I'll be happy to look at it once the "big" v2 issues have been addressed.)

**Comment by bendichter** [comment]
got it. Thanks!
