### ISSUE TITLE
Incorrect unpacking of value in object

### ISSUE THREAD

**Issue by themrinalsinha** [pydantic/pydantic#5122]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

In a specific scenario, there is an issue where unpacking a dictionary into a base model results in an incorrect output:

```python
Python 3.11.2 (main, Feb  8 2023, 14:49:25) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pydantic import BaseModel

In [2]: class Test(BaseModel):
   ...:     a: dict | list | None
   ...:     b: str
   ...: 

In [3]: data = {"a": [1, 2, 3], 'b': 'ball'}

In [4]: Test(**data)
Out[4]: Test(a=[1, 2, 3], b='ball')  ✅

In [5]: data = {"a": [{'ids': [1, 2, 3]}, {'ids': [4, 5, 6]}], 'b': 'ball'}

In [6]: Test(**data)
Out[6]: Test(a=[{'ids': [1, 2, 3]}, {'ids': [4, 5, 6]}], b='ball') ✅

In [7]: data = {"a": [{'id': 1, 'value': 1}, {'id': 2, 'value': 2}], 'b': 'ball'}

In [8]: Test(**data)
Out[8]: Test(a={'id': 'value'}, b='ball') ## INCORRECT ❌
```

But, when I change the sequence of attribute `a` with `list | dict | None` it works fine.
```python
In [9]: class Test(BaseModel):
   ...:     a: list | dict | None
   ...:     b: str
   ...: 

In [10]: data = {"a": [{'id': 1, 'value': 1}, {'id': 2, 'value': 2}], 'b': 'ball'}

In [11]: Test(**data)
Out[11]: Test(a=[{'id': 1, 'value': 1}, {'id': 2, 'value': 2}], b='ball') 
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
pydantic compiled: False
install path: /home/xxxx/.cache/pypoetry/virtualenvs/xxxxxx-zBsOJE54-py3.11/lib/python3.11/site-packages/pydantic
python version: 3.11.2 (main, Feb  8 2023, 14:49:25) [GCC 11.3.0]
platform: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
You need to enable [smart_union](https://docs.pydantic.dev/usage/model_config/#smart-union) like:

```python
from pydantic import BaseModel

class Test(BaseModel):
    a: dict | list | None
    b: str

    class Config:
        smart_union = True
```
