### ISSUE TITLE
Using custom metaclass raises metaclass conflict

### ISSUE THREAD

**Issue by codectl** [pydantic/pydantic#5124]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am getting the following error:

```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

### Example Code

```Python
class MetaBase(type):
    def __new__(mcs, name, bases, attrs):
        cls = type.__new__(mcs, name, bases, attrs)
        return cls

class User(BaseModel, metaclass= MetaBase):
    id: int
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 install path: /Users/renato/Library/Caches/pypoetry/virtualenvs/apispec-plugins-c17nWIz5-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ]
                     platform: macOS-13.0-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [ ] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [ ] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [X] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by codectl** [comment]
This could be solved if ```ModelMetaclass``` was made public. As per current version, ```pydantic.main``` has the this definition ```__all__ = 'BaseModel', 'create_model', 'validate_model'``` and ```ModelMetaclass``` is not part of it.

**Comment by hramezani** [comment]
It's because `BaseModel` has a metaclass `ModelMetaclass`.

> This could be solved if ModelMetaclass was made public. As per current version, pydantic.main has the this definition __all__ = 'BaseModel', 'create_model', 'validate_model' and ModelMetaclass is not part of it.

Could you please elaborate on this? how this will solve the problem?

**Comment by codectl** [comment]
@hramezani right now we have the following:

```python
class CustomMetaClass(type):
    pass


class User(BaseModel, metaclass=CustomMetaClass):
    id: str
```

this raises:

```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

To solve it, one could inherit the ```metaclass``` from ```pydantic```:

```python
from pydantic import BaseModel
from pydantic.main import ModelMetaclass


class CustomMetaClass(ModelMetaclass):
    pass


class User(BaseModel, metaclass=CustomMetaClass):
    id: str
```

This would solve the issue but the class ```ModelMetaclass``` is set to "private" since it's not part of the ```__all__``` declaration in the module ```pydantic.main```.

**Comment by hramezani** [comment]
Then I think we will lose the functionality of Pydantic.
I've tried it locally in my local clone of Pydantic:

```python
class CustomMetaClass(ModelMetaclass):
    def __new__(mcs, name, bases, attrs):
        print('I am in __new__')
        cls = type.__new__(mcs, name, bases, attrs)
        return cls


class User(BaseModel, metaclass=CustomMetaClass):
    id: str

    @validator('id')
    def id_validator(cls, v):
        print('I am in validator')
        if v < 0:
            raise ValueError('Invalid ID')

print(User(id='-1'))
```

And here is the output and `ValueError` doesn't raise:

```
I am in __new__


```

@samuelcolvin What do you think?

**Comment by codectl** [comment]
In your example, the following would work:

```python
class CustomMetaClass(ModelMetaclass):
    def __new__(mcs, name, bases, attrs):
        print('I am in __new__')
        cls = super().__new__(mcs, name, bases, attrs)
        # do something meaningful here ...
        return cls


class User(BaseModel, metaclass=CustomMetaClass):
    id: str

    @validator('id')
    def id_validator(cls, v):
        print('I am in validator')
        if int(v) < 0:
            raise ValueError('Invalid ID')


print(User(id='-1'))
```

That will get us this the result we want:

```
pydantic.error_wrappers.ValidationError: 1 validation error for User
id
  Invalid ID (type=value_error)
```

The main point here is that some of us - ```pydantic``` users - might want to enhance the ```ModelMetaclass``` behavior which seems like it is currently discouraged by not making it **exportable**.

**Comment by hramezani** [comment]
ah, forgot to call `super().__new__`. Yes, you are right.

Then let's wait for @samuelcolvin.

**Comment by dmontagu** [comment]
@codectl Can I ask what you are trying to do with a custom metaclass?

We could make `ModelMetaclass` public, but I think there is a non-trivial argument against doing so: If we do make it public, it means that some of the hairier implementation details of how BaseModels work may now be considered "public", and therefore prevent us from doing certain refactors for any of a variety of reasons (performance, bugfixes, features) in the future.

@samuelcolvin not sure if you have different thoughts on this

**Comment by codectl** [comment]
@dmontagu certainly !

I am working on a ```PydanticPlugin``` for the ```apispec``` standard for the project [apispec-plugins](https://github.com/codectl/apispec-plugins). I have recently migrated my schemas from ```marshmallow``` to ```pydantic``` schemas and so far I haven't regretted one bit. One challenge that I face is that ```marshmallow``` keeps a class registry that I can lookup to easily retrieve registered schemas. ```pydantic``` does not provide that and for that reason I am looking to add a ```metaclass``` that would do that for me. It would look something like this:

```python
from pydantic.main import ModelMetaclass  # <-- 'private' class


class RegistryMixin(type):
    _registry = {}

    def __new__(mcs, name, bases, attrs):
        cls = type.__new__(mcs, name, bases, attrs)
        mcs._registry[cls.__name__] = cls
        return cls

class BaseMetaclass(ModelMetaclass, RegistryMixin):
    """Enhancing pydantic metaclass"""


class User(BaseModel, metaclass=BaseMetaclass):
    id: str
    ...
```

**Comment by samuelcolvin** [comment]
@dmontagu's solution looks great, I'd prefer not to make the metaclass public unless absolutely necessary.

**Comment by codectl** [comment]
@dmontagu issue with the suggested approach is that you must initialize your class to trigger ```__init_subclass__```. I don't particularly need an instantiated class since I can do stuff like ```UserModel.schema()``` without the need to have an object for that.

**Comment by codectl** [comment]
Ended up with the following:

```python
from pydantic import BaseModel
...

class BaseMetaclass(type(BaseModel), RegistryMixin):
    """Enhancing pydantic metaclass"""

...
```

Win win: no need to make ```ModelMetaclass``` public while still being able to tune it.

**Comment by dmontagu** [comment]
@codectl I don't think you need to instantiate anything:
```python
class A:
    def __init_subclass__(cls, **kwargs):
        print("Run A.__init_subclass__")

class B(A):
    pass

# prints 'Run A.__init_subclass__'
```

**Comment by dmontagu** [comment]
@codectl Also, if you are willing to inherit from `type(BaseModel)`, you might as well just import `ModelMetaclass` (which is exactly the same thing). It can be imported from `pydantic.main`:

```python
from pydantic import BaseModel
from pydantic.main import ModelMetaclass

assert ModelMetaclass is type(BaseModel)  # no error gets raised
```

To be clear, unless @samuelcolvin were to say otherwise (and given his message above I strongly suspect he would not), I would _not_ treat `ModelMetaclass` as a stable/public API, and would strongly encourage you to avoid modifying `ModelMetaclass` if you care about reducing the probability of your code breaking in future versions of pydantic. (@samuelcolvin I'm wondering if it might make sense to move the `ModelMetaclass` into an `_internal` module for this reason. Maybe it's already "too public" from v1..)

The use case you've described of adding all subclasses to a registry is _exactly_ the kind of thing `__init_subclass__` was created for, I do think that approach should work for you.

**Comment by codectl** [comment]
Thank you, ```__init_subclass__``` is enough for my use case.

**Comment by ozgeneral** [comment]
How about [this](https://stackoverflow.com/a/79328847/3413092):

```
class X(type):
    def __getattribute__(cls, key):
        if key in ["model_fields", "__dict__"]:
            return super().__getattribute__(key)
        if key not in cls.model_fields:
            return super().__getattribute__(key)
        print(f"accessing {key}")
        # do your thing here, for example:
        return cls.model_fields[key].default

class Y(X, type(BaseModel)):
    pass

class Z(BaseModel, metaclass=Y):
  a: int = 2
  b: str = "k"
  c: str

Z.a
# accessing a
# Out[5]: 2

Z.b
# accessing b
# Out[6]: 'k'

Z.c
# accessing c
# Out[7]: PydanticUndefined

Z.d
# throws AttributeError: d

Z(a=3, c="C").a
# 3

Z(a=3, c="C").c
#'C'

Z(a=3)
# throws  c Field required [type=missing, input_value={'a': 3}, input_type=dict]
```
