### ISSUE TITLE
PostgreDSN to inherit from SecretStr

### ISSUE THREAD

**Issue by ocardia** [pydantic/pydantic#5131]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io) and still think this feature is missing

### Description

There are some [URLs Field Types](https://docs.pydantic.dev/usage/types/#urls) that may take advantage of the [Secret Types](https://docs.pydantic.dev/usage/types/#secret-types) features.

While I'm personally interested in `PostgresDsn`, others schemes support sensible data such as passwords. To be honest, even if the password wasn't there, leaking something similar in logs, error management system, you name it, doesn't seem the best option.

Thus, we usually prefer `SecretStr` in `PostgresDsn` stead, and eventually write a small validator for the schema we're interested in.

I was wondering whether it'd be possible to have `PostgresDsn` leverage `SecretStr` peculiarities.

I'll better look into the codebase in the following weeks, 🎗️ but having a quick understanding of possible _no-go_ rationales would be great. Thanks! 🙏🏻 

### Affected Components

- [ ] [Compatibility between releases](https://pydantic-docs.helpmanual.io/changelog/)
- [X] [Data validation/parsing](https://pydantic-docs.helpmanual.io/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://pydantic-docs.helpmanual.io/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://pydantic-docs.helpmanual.io/usage/schema/)
- [ ] [Dataclasses](https://pydantic-docs.helpmanual.io/usage/dataclasses/)
- [ ] [Model Config](https://pydantic-docs.helpmanual.io/usage/model_config/)
- [X] [Field Types](https://pydantic-docs.helpmanual.io/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://pydantic-docs.helpmanual.io/usage/validation_decorator/)
- [ ] [Generic Models](https://pydantic-docs.helpmanual.io/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://pydantic-docs.helpmanual.io/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://pydantic-docs.helpmanual.io/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by yezz123** [comment]
Hello, @ocardia Thank you for bringing up this interesting topic about URL Field Types and Secret Types features.

I completely agree with you that sensitive information like passwords should be kept secure and not exposed in logs or error management systems. It's essential to protect such information from potential attacks and ensure the privacy and security of users' data.

The only thing I try to understand is what you mean by inherit from `SecretStr`, cause already you can have some sort of validation already, here is a simple Example.

## Example:

Let's say we have a simple web application that requires a PostgreSQL database for storage. We can use pydantic to define a data model for the PostgreSQL database URL, which includes the database hostname, port number, database name, username, and password.

```py
from pydantic import BaseModel, PostgresDsn, SecretStr

class DatabaseConfig(BaseModel):
    url: PostgresDsn # can handle PostgreSQL database URLs
    password: SecretStr # the SecretStr field type for the password to keep it secure
    max_connections: int = 10
    min_connections: int = 1
    
    class Config:
        env_prefix = "DB_" # optional
```

we define a `DatabaseConfig` model that has a url field of type `PostgresDsn` and a password field of type `SecretStr`.

The `PostgresDsn` field type can handle PostgreSQL database URLs, and the `SecretStr` field type will automatically encrypt the password and prevent it from being accidentally logged or exposed.

we can use this `DatabaseConfig` model to create a database connection object:

```py
import asyncpg

async def create_database_connection(config: DatabaseConfig) -> asyncpg.Connection:
    connection = await asyncpg.connect(
        dsn=config.url,
        user=config.url.username,
        password=config.password.get_secret_value(),
        max_size=config.max_connections,
        min_size=config.min_connections,
    )
    return connection
```

We extract the necessary connection parameters from the url field, and the password is retrieved using the `get_secret_value()` method of the `SecretStr` field type.


Hope if this is the Idea you try to provide mainly.

**Comment by ocardia** [comment]
Yes, the example you're exposing makes perfect sense and is a working alternative. 👍🏻 

Yet, sometimes you may get the URI already embedding username and password, as it's one of the supported schema.
In that case, it'd be great to have something that allows for (reusing your example)
```py
import asyncpg

from pydantic import BaseModel, PostgresDsn, SecretStr

class DatabaseConfig(BaseModel):
    uri: PostgresDsn
    max_connections: int = 10
    min_connections: int = 1

async def create_database_connection(config: DatabaseConfig) -> asyncpg.Connection:
    connection = await asyncpg.connect(
        dsn=config.uri.get_secret_value(),
        max_size=config.max_connections,
        min_size=config.min_connections,
    )
    return connection
```

We now do something close to this, leveraging `SecretStr` instead of `PostgresDsn`.

It just feels that having the URI as a secret string—both the whole URI and some/all of its fields—may allow people to choose at which level they need to get the secret. For example, one could then access them in any of these forms depending on the usage.
```py
config.uri.get_secret_value()
config.uri.username.get_secret_value()
config.uri.password.get_secret_value()
```

Note that since there are workable solutions (e.g., ours with a mere `SecretStr`, yours with a dedicated `SecretStr` for the password, you name it) this I'm proposing looks like a nice-to-have. In other words, I'm totally fine with a "we don't see value in implementing this," and closing this issue. I just wanted to sparkle the conversation and better understand the underlying rationale. 💪🏻

**Comment by yezz123** [comment]
I agree that it could be useful to have the URI as a secret string, especially when the URI already embeds the username and password.

This approach would allow people to choose at which level they need to get the secret and access the URI, username, and password values separately if needed.

> this may be a nice-to-have rather than a necessity. Ultimately, the decision to implement this feature would depend on the specific `use case` and the potential benefits it would bring.

From my own perspective, I can't see any reasonable part to use it in that way, especially since we already have the ability to control where and how we use environment variables.

Furthermore, using `SecretStr` to store the URI as a secret string could potentially add unnecessary complexity to the code, without providing any significant security benefits.

Ultimately, it's up to the specific use case and the level of security required, but I would recommend sticking to the standard practice.

**Comment by ocardia** [comment]
Totally aligned, especially because of this
>could potentially add unnecessary complexity to the code, without providing any significant security benefits.

Thanks for the clarification. 💪🏻 🚀

**Comment by dmontagu** [comment]
@ocardia I generally agree with @yezz123's assessment that you can go down a rabbit-hole of secret-storing/presenting behavior that ultimately may not have a major impact on security, BUT, if for some reason you really want to get a specific behavior, I think in v2 you'll be able to subclass `pydantic.types.SecretField` with your own logic about how values are parsed/presented.

Given how team-specific opinions can be about handling this sort of thing, I think it probably doesn't make sense for us to commit to an opinion about how it should be done and incorporate concrete types directly into pydantic, but our goal is that the library should be flexible enough that if you need to achieve a particular approach to data handling, it should be possible to achieve it through your own code.

**Comment by ocardia** [comment]
> I think in v2 you'll be able to subclass `pydantic.types.SecretField` with your own logic about how values are parsed/presented.

Lovely! To speak the truth, doing `SecretStr[PostgresDsn]` was one of the first things I tried in my code even before digging deeper. 😂 

I understand your reasoning and thanks for taking the time to comment further. 👏🏻

**Comment by dwlocks** [comment]
Note from the future, I believe that this tiny bit of code satisfies the original request of @ocardia 

```
class SecretPostgresDsn(SecretStr, PostgresDsn)
    pass
````
