### ISSUE TITLE
Memory leak in v2 (possibly PyO3 issue?)

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5136]
While investigating the generic caching misbehavior in #5125, I discovered (with @adriangb's significant help!) what appears to be a memory leak. Here's a fairly minimal reproduction of the issue in the context of `pydantic`:

```python
import gc
from weakref import WeakValueDictionary

from pydantic import BaseModel
# BaseModel = object   # <--- uncomment this line to show expected behavior

cache = WeakValueDictionary()

def create_and_del() -> None:
    class A(BaseModel):
        pass

    cache[id(A)] = A


for _ in range(100):
    create_and_del()

gc.collect(0)
gc.collect(1)
gc.collect(2)

print(len(cache))
```
The above code prints 100, indicating that the models are not being cleaned up. If I uncomment the line `BaseModel = object` (right after the import from pydantic near the top), it prints 0, indicating that this is an issue with `BaseModel`.

-----

I am still investigating exactly what is going on on the pydantic side, But with @adriangb's help I was able to put together a pretty minimal example of misbehavior that seems to be stemming from circular references that bridge across PyO3.

Adding the following struct to `pydantic_core` (for reference, I've shared the relevant code via [this branch](https://github.com/pydantic/pydantic-core/tree/python-reference-holder), specifically, [this commit](https://github.com/pydantic/pydantic-core/commit/0cf3de5bbe84490d3e5438aa08248c77581c387d)):
```rust
#[pyclass(module = "pydantic_core._pydantic_core")]
pub struct PythonReferenceHolder {
    #[pyo3(get)]
    pyobj: Py<PyAny>
}

#[pymethods]
impl PythonReferenceHolder {
    #[new]
    pub fn py_new(pyobj: Py<PyAny>) -> Self {
        Self { pyobj }
    }
}
```
You can reproduce the weakref issue with the following script:
```python
import gc
from weakref import WeakValueDictionary

from pydantic_core import PythonReferenceHolder


class Meta(type):
    def __new__(cls, *args, **kwargs):
        result = super().__new__(cls, *args, **kwargs)
        result.ref = PythonReferenceHolder(result)
        # result.ref = result  # <-- uncomment this line to fix cache purging, i.e., print 0
        return result


cache = WeakValueDictionary()


def create_and_del() -> None:
    class A(metaclass=Meta):
        pass

    cache[id(A)] = A


for _ in range(100):
    create_and_del()

gc.collect(0)
gc.collect(1)
gc.collect(2)

print(len(cache))
```
As is, the above will print 100. If you uncomment the line right below the creation of the `PythonReferenceHolder` the script prints 0.

(Note that although I added `PythonReferenceHolder` to `pydantic_core` for convenience, as far as I can tell the issue demonstrated above should not be specific to `pydantic` or `pydantic_core` whatsoever.)

@davidhewitt if you have any insights here they would be very much appreciated. Let me know if you'd like me to create an issue in PyO3.

(The reason this is an issue is because we've had problems with memory leaks of generic models before, and I think the memory-leak-related behavior shown above is likely to cause at least as much of an issue as the previous issues with generic models in v1, and actually seems to currently affect even non-generic models.)

**Comment by dmontagu** [comment]
Just a bit more investigation — adding 
```python
for r in gc.get_referrers(next(cache.values())):
    print(r, end="\n\n")
```
at the end of my minimal pyo3 example above produces:
```
(<class '__main__.create_and_del.<locals>.A'>, <class 'object'>)

<attribute '__weakref__' of 'A' objects>

<attribute '__dict__' of 'A' objects>
```

The first item there looks to be exactly like `A.__mro__`, and we noticed that was the same referrer that seems to remain for `BaseModel` subclasses. (I.e., in the pydantic version of the example, when creating subclasses of BaseModel the first referrer is the subclass's `__mro__`.)

@davidhewitt not sure if pyo3 does anything interesting with the `__mro__` if you create a reference to a type, or if something else completely unrelated might be producing that tuple, but figured it might be helpful context for someone who knows more.

**Comment by dmontagu** [comment]
A little more pydantic-specific investigation: this seems to be coming specifically from the `__pydantic_serializer__`. Changing this line:

https://github.com/pydantic/pydantic/blob/565c9b603ac1a19dfed8474fa2bb1bcaee090ca0/pydantic/_internal/_model_construction.py#L188

to either of the following resolves the issue:
* `    cls.__pydantic_serializer__ = (outer_schema, core_config)`
* `    cls.__pydantic_serializer__ = SchemaSerializer(inner_schema, core_config)`

whereas changing it to:
* `    cls.__pydantic_serializer__ = PythonReferenceHolder((outer_schema, core_config))`
does not resolve the issue.

Note that to detect that the issue is "resolved", you need to change the loop counter from `for _ in range(100):` to `for _ in range(1000):` in the script shared above. There is an lru_cache in `typing.Annotated` that will retain 128 references, so you need to create more than 128 BaseModel subclasses for it to start purging them out of the WeakValuesDictionary.

To be more explicit, when I say "resolves the issue" above, I mean that the script will print `128` instead of `1000` (with the loop range maximum increased to 1000).

**Comment by dmontagu** [comment]
My conclusion from this is that the problem is that:
* PyO3 objects with circular references to types do not get cleaned up by the garbage correctly properly
*  `cls.__pydantic_serializer__` is a PyO3 object (`SchemaSerializer`) that contains a reference to `cls`

@samuelcolvin I'm not sure if it is possible/reasonable to try to remove the circular reference to `cls` in the `__pydantic_serializer__`; clearly it would be better if the PyO3 types weren't causing garbage collection issues but I'm just thinking it might be possible for us to remove the cyclic reference in the `SchemaSerializer` more easily/quickly than to resolve the PyO3 issue. But I don't know much about how the `__pydantic_serializer__`  works, so maybe that's not a viable option.

**Comment by davidhewitt** [comment]
To deal with circular references you'll need the relevant containers to implement `__traverse__`, has that been done?

Sorry for short reply writing from my phone, about to do baby bath & bedtime...

**Comment by dmontagu** [comment]
I see: https://pyo3.rs/v0.13.1/class/protocols.html#garbage-collector-integration -- I think I can continue investigating from here.

**Comment by dmontagu** [comment]
@samuelcolvin After looking into this briefly, I'll plan to defer to you (or at least get your help) to proceed with the garbage collection stuff since the `CombinedSerializer`, which I think is the thing we need to visit, is defined by a fairly complex macro and I think you'll have better insight into what the best approach is here.

**Comment by davidhewitt** [comment]
Note the link you send above is very out of date - https://pyo3.rs/v0.18.1/class/protocols.html#garbage-collector-integration is current, just for clarity.

**Comment by samuelcolvin** [comment]
Unfortunately `SchemaValidator` and `SchemaSerializer` hold references to python objects which are not `Option` - e.g. we can't just set those references to `None` in `__clear__` as suggested by the docs.

I think the fundamental problem is this:
* a pydantic `BaseModel` has a `SchemaValidator` attribute, namely `__pydantic_validator__`
* the rust struct backing `SchemaValidator` has a `CombinedValidator` member which in turn holds a reference to a python object which has a reference to the original `BaseModel` - perhaps directly, perhaps via some circuitous route

Thus there really is a circular reference.

I have no idea about how python's `gc` normally manages to identify these closed reference loops and clean them up, but I guess we need to somehow hook into that same logic.

E.g. how is the `gc` able to identify and collect the following "garbage"

```py
a = []
a.append(a)
```

?

**Comment by davidhewitt** [comment]
While I don't know the full detail of the GC's implementation, the model I have in my head is that if `__traverse__` is implemented then that's sufficient for the Python GC to detect cycles. If there is a cycle, then _at least one_ of those types must implement `__clear__` so that the cycle can be broken. E.g. [tp_clear docs](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_clear) demonstrate `tuple` as an example - because it's immutable, it cannot possibly contain a cycle with itself, and cannot implement `tp_clear`. It does implement `__traverse__` so that any cycles which contain tuples can be found.

> which in turn holds a reference to a python object which has a reference to the original BaseModel

It could be worth implementing traversal for `SchemaValidator` and `CombinedValidator`, and see if this improves the situation. The "other python object" may well implement `tp_clear`, and this may be enough.

**Comment by dmontagu** [comment]
@davidhewitt Thank you very much for pointing us in the right direction. I have a hacky tweak to `pydantic_core` in https://github.com/pydantic/pydantic-core/pull/415 that I have confirmed resolves the issue brought up in this ticket, and I think we have a sense of how to proceed.

Will definitely be interested in your review before it's done.

**Comment by samuelcolvin** [comment]
🧙 amazing.

**Comment by adriangb** [comment]
> While I don't know the full detail of the GC's implementation, the model I have in my head is that if __traverse__ is implemented then that's sufficient for the Python GC to detect cycles. If there is a cycle, then at least one of those types must implement __clear__ so that the cycle can be broken.
> It could be worth implementing traversal for SchemaValidator and CombinedValidator, and see if this improves the situation. The "other python object" may well implement tp_clear, and this may be enough.

It seems like indeed we can just implement traverse. I guess the Python class implements `tp_clear`. So not too bad to fix!
