### ISSUE TITLE
Inconsistent behavior of `root_validator` `values`

### ISSUE THREAD

**Issue by lowercase00** [pydantic/pydantic#5143]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

While using `root_validator` it seems that there's a specific situation where the `values` arg on the validator returns different values: in one case it returns a `dict` and in other a `str`. It seems the first validator has the `dict`, and the second the `str`. I couldn't find anything in the documents regarding this specific behavior. As this can be considered inconsistent (same argument, same feature, returning different results), I'm thinking this _might_ be a bug.

### Example Code

```Python
from pydantic import BaseModel, root_validator
from typing import Optional


class Test(BaseModel):
    a: Optional[str] = None
    b: Optional[str] = None

    @root_validator
    def x(cls, values):
        print(f"Starting `x` root validator. Values are of type: {type(values)}")
        if values.get('a'):
            return values.get('a')
        return None

    @root_validator
    def y(cls, values):
        print(f"Starting `y` root validator. Values are of type: {type(values)}")
        if not values.get("b"):
            return None
        return values.get("b")


a = Test(a="Test A Var", b="a")
```

```python
Starting `x` root validator. Values are of type: <class 'dict'>
Starting `y` root validator. Values are of type: <class 'str'>
Traceback (most recent call last):
  File ".../test.py", line 25, in <module>
    a = Test(a="Test A Var", b="a")
  File "pydantic/main.py", line 340, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1103, in pydantic.main.validate_model
  File ".../test.py", line 19, in y
    if not values.get("b"):
AttributeError: 'str' object has no attribute 'get'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 install path: .../.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Sep 20 2022, 13:35:01) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-11.7.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Well yes, the root validators are called in turn, with the value from the last one, and your first root validator is returning a str, not dict.

**Comment by samuelcolvin** [comment]
No problem, glad you fixed it.
