### ISSUE TITLE
Better log messages for __root__ fields

### ISSUE THREAD

**Issue by JensHeinrich** [pydantic/pydantic#5144]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

No change to the (user) code needed.

When using Union or Nested Mapping types it quickly becomes hard to distinguish which `__root__` is meant:
```bash
E     expected string or buffer (type=type_error)
E   __root__ -> get -> queryString -> __root__ -> __root__
```
It would be better to have informoation like
```bash
E     expected string or buffer (type=type_error)
E   __root__@ModelA -> get -> queryString -> __root__@ModelB -> __root__@ModelC
```

Logging is a basic feature of pydantic itself, so implementing it in a library would be rather hard (unless there is a better way to do so with monkeypatching).

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by JensHeinrich** [comment]
Maybe this could be backported too, as it is not a "real" feature changing external compability?

**Comment by dmontagu** [comment]
@samuelcolvin may be something to keep in mind as we implement `RootModel`

**Comment by dmontagu** [comment]
We've now dropped the display of the `root` field entirely in `RootModel` in pydantic v2:
```python
from pydantic import BaseModel, RootModel

class MoreInner(BaseModel):
    y: str

class Inner(RootModel):
    root: MoreInner

class Parent(BaseModel):
    x: Inner

Parent.model_validate({'x': {'y': 1}})
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Parent
x.y
  Input should be a valid string [type=string_type, input_value=1, input_type=int]
"""
```
I think this error makes more sense for API consumers, though I could see an argument that it would be nice to see more detail during development.

If anyone has objections, feel free to open a new issue raising an objection to the behavior in v2, I am going to close this now though as it only relates to v1 and we are not going to change the behavior of v1 now.
