### ISSUE TITLE
add `memray` tests

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5146]
Probably here and in pydantic-core.

Do we add checks to all tests, or just a few tests designed specifically?

**Comment by dmontagu** [comment]
This is about to get closed by merging generics; should we open a similar issue on pydantic core? I don't have a strong opinion.

**Comment by adriangb** [comment]
I think if we have the memory tests here that should be enough. I think there's a 50/50 chance of bugs happening here vs. in core and here we can catch both.
