### ISSUE TITLE
Compat with mypy 1.1.1

### ISSUE THREAD

**Issue by g-as** [pydantic/pydantic#5148]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Mypy 1.1.1 was just [released](https://mypy-lang.blogspot.com/2023/03/mypy-111-released.html) (main highlight is support for dataclass_transform).

Signature for `Model.__init__` appears to be broken with this latest mypy version when `Config.allow_population_by_field_name=True`.

### Example Code

```Python
class Model(pydantic.BaseModel):

    toto: str = pydantic.Field(alias="tata")

    class Config:
        allow_population_by_field_name = True


Model(toto="toto")  # error: Unexpected keyword argument "toto" for "Model"  [call-arg]
Model(tata="tata")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 install path: [...]/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by zeshuaro** [comment]
Also got into the same issue with the code below when running mypy, which I think it's related:

```python
from pydantic import BaseSettings, Field


class Settings(BaseSettings):
    class Config:
        env_file = ".env.test", ".env"
        env_file_encoding = "utf-8"

    token: str = Field(..., env="token")


Settings()  # Missing named argument "token" for "Settings"  [call-arg]
```

**Comment by cdce8p** [comment]
Version `1.10.6` was released a few hours ago. https://github.com/pydantic/pydantic/releases/tag/v1.10.6
To restore the previous behavior, you might need to add the `pydantic.mypy` plugin to your mypy config.

https://docs.pydantic.dev/mypy_plugin/

**Comment by samuelcolvin** [comment]
👍 thanks @cdce8p for all your work.

**Comment by g-as** [comment]
All good on my part. Thanks!
