### ISSUE TITLE
Support validation of extra fields

### ISSUE THREAD

**Issue by sommd** [pydantic/pydantic#515]
# Feature Request

It would be nice if validators could be called for extra fields when `Config.extra` is `allow`:

```py
class Foo(BaseModel):
    class Config:
        extra = "allow"

    a: int

    @validator("*", extra=True)  # Possible API, could be opt-out instead but that might be a breaking change
    def extra_validator(...):
        ...

Foo(a=1, b={}) # extra_validator gets called for both a and b
```

My specific use case for this is that I want to transform extra dict fields to objects:

```py
class Foo(BaseModel):
    class Config:
        extra = "allow"

    @validator("*", extra=True)
    def convert_extra(cls, value, field): # Not sure how field would work, but the name needs to be passed somehow
        return Foo.parse_obj(value)
```

**Comment by samuelcolvin** [comment]
Agree it would be useful.

Perhaps `@validator('__extra__')` would be clearer?

Happy to accept a PR.

**Comment by lsorber** [comment]
I'm in favour of `@validator("__extra__")`, but I would have expected `@validator("*")` also applies to `extra` fields. Do you agree @samuelcolvin?

**Comment by samuelcolvin** [comment]
That would need to wait for v2, but yes.

**Comment by KoenCuijp** [comment]
I ran into this use case today as well. I'm parsing a JSON response that contains a dict with keys & values that are defined by user-input and they can therefore potentially change for each request made.

Would using [`@root_validator(pre=True)`](https://pydantic-docs.helpmanual.io/usage/validators/#root-validators) be a reasonable workaround though? It seems like it would cover the use case.

**Comment by samuelcolvin** [comment]
Yes, root validators would be a good worksaround for now.

**Comment by efisoft-elt** [comment]
Coming back into this. An idea could be to *also*  use the `__extra__` inside Model class definition : 

```python
class Numbers(BaseModel):
    x: float = 0.0
    y: float = 0.0
    __extra__:  float 
```

**Comment by adriangb** [comment]
As per discussion above `@root_validator`/`@model_validator` works well for this. We are considering adding an option for this specifically, but in the interest of keeping the API simple have any of you found a situation in which using a root/model validator did not do the job?

**Comment by dmontagu** [comment]
I'm going to close this now because the issue is stale and Adrian provided a suggested solution, but feel free to open a new issue if desired and/or request that we reopen this issue.

**Comment by Kevin-Mc-Callister** [comment]
Did this make it to v2?
