### ISSUE TITLE
Improve performance of union validation by inferring a discriminator

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5163]
In cases where a field is comprised of a union of types that each have a literal field that is incompatible with the other types in the union, it may be (significantly) more performant to use the TaggedUnionSchema validation logic to perform validation, as it will ensure that the item is validated against the correct schema within the union choices immediately, and also ensures that no time is wasted validating against other schemas when checking the discriminator is enough to know validation is going to fail.

Today, this can be achieved by explicitly assigning/annotating the attribute with `Field(discriminator='kind')` (or similar). However, it may be straightforward to automatically infer a discriminator for a union type, reducing the need for explicit description by users, and improving performance even for users who are unaware of this functionality.

(We could go even farther than looking for Literal attributes, and produce more involved discriminators that would look for specific attributes only defined on one of the cases, but I think this may quickly get into the realm of unnecessary implementation complexity or producing validation error messages that are more-confusing/difficult-to-debug.)

Creating this issue for tracking purposes. @adriangb @samuelcolvin please comment if there's anything you wanted to add/emphasize/alter relative to what I've said above.

**Comment by dmontagu** [comment]
@samuelcolvin I believe we looked into what typescript does at PyCon, and when multiple interfaces are present in a union with a shared literal attribute, it does seem to infer that a discriminator should be used.

I think it would be straightforward to handle many common cases automatically (namely, where every member of the union has a field of literal type with non-overlapping values). While one could argue that _in theory_ this might result in some confusing error messages in the case where you meant to pass data for one case but used the literal for another, I think _in practice_ this pretty universally improves the understandability of the error messages involved.

If there's consensus that inferring a discriminator in such cases is a good thing, I would be happy to attempt to implement this (I think it should be a fairly small and self-contained modification to `pydantic._internal._generate_schema.GenerateSchema._union_schema`).

**Comment by derbasti381** [comment]
Hello David,
I'm not sure if this is the right place for my report, but hope you can have a look at it.

I adapted my code regarding Unions from v1 validators to v2 discriminated Unions, which worked well in v2.0b3. With v2.0 I get `TypeError: `discriminator` can only be used with `Union` type with more than one variant`. This was temporarily also thrown in v2.0b3, but after I removed all v1 validators and added the Literals to my `type` attributes, everything worked well.

This is my Dict with Annotated objects as values which all have `type: Literal['nameXY']` attributes.
```
objects: Dict[
    str,
    Annotated[
        EthernetInterface |
        VlanInterface |
        IPInterface |
        DNS |
        WireGuardPeer |
        RoutingTable |
        PolicyRoute |
        Route |
        Service |
        InterfaceAddress |
        DhcpInterfaceAddress |
        BondingInterface |
        WireGuardInterface |
        BridgeInterface |
        PppoeInterface |
        Gateway |
        DhcpGateway |
        Host |
        Network |
        NatRule |
        FirewallRule |
        NetworkGroup |
        ServiceGroup |
        User |
        X509Certificate,
        Field(discriminator='type')
]]
```
Do you have any idea why this breaks with an update from v2.0b3 to v2.0?

Thanks a lot for this wonderful piece of software!
Peace
Bastian

**Comment by dmontagu** [comment]
@derbasti381 that definitely sounds like a regression, and/or a bug we'd be happy to fix. I have some ideas, but it would be helpful if you could try to put together a self-contained example of it failing.

I tried:
```python
from typing import Annotated, Literal

from pydantic import BaseModel, Field


class Obj1(BaseModel):
    type: Literal['obj1']


class Obj2(BaseModel):
    type: Literal['obj2']


class Obj3(BaseModel):
    type: Literal['obj3']


class Model(BaseModel):
    objects: dict[
        str,
        Annotated[
            Obj1 |
            Obj2 |
            Obj3,
            Field(discriminator='type')
        ]]


print(Model(objects={'a': {'type': 'obj1'}}))
#> objects={'a': Obj1(type='obj1')}
```
But the code above executes without issue, so I'm not sure how to reproduce the problem

**Comment by derbasti381** [comment]
@dmontagu Thanks for your swift reply. To reproduce, I took some of the stuff from my code. I didn't say, that I'm also using BaseSettings and then have an ObjectStore where this Dict is in.

```
from typing import Annotated, Literal

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings
import uuid

class Object (BaseModel):
    id: Annotated[str, Field(default_factory=lambda: str(uuid.uuid4()), allow_mutation=False)]
    name: str

class ServiceObject(Object):
    ...
class NetworkObject(Object):
    ...

class Service(ServiceObject):
    type: Literal['Service']

    srcport: str = "1-65535"
    dstport: str = ""
    status: bool = 1

class DNS (NetworkObject):
    type: Literal['DNS']
    hostname: str = ''
    status: bool = 1

class ObjectStore(BaseModel):
    objects: dict[
        str,
        Annotated[
            Service |
            DNS,
            Field(discriminator='type')
    ]]

class Confd(BaseSettings):
    socket: str = "/var/run/confd"
    objectstore: ObjectStore = None

config_from_json = {
    "socket": "/var/run/confd",
    "objectstore": {
        'uuid1': {'type': 'DNS', 'hostname': 'dnstest.sebode.de', 'name': 'Sebode Test record'},
        'uuid2': {'type': 'Service', 'dstport': '22', 'name': 'SSH'}
    }
}

print(Confd(**config_from_json))
```
It works with v2.0b3 and all versions of pydantic-settings and pydantic-core. But not with v2.0 and any of settings/core. Thanks again.
Bastian

**Comment by dmontagu** [comment]
@derbasti381 I can confirm that the issue is present on the v2.0 release, but is resolved in the current main branch. I suspect we will get a 2.0.1 release of pydantic out in the next day or two, at which point your issue should be resolved.
