### ISSUE TITLE
`validate_arguments` coerces collections into iterators if annotated as `Iterable`

### ISSUE THREAD

**Issue by z33kz33k** [pydantic/pydantic#5166]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

`validate_arguments` decorator coerces input collections into their iterators, if they were annotated as `typing.Iterable` in a function's signature.

I know that

`pydantic currently leans on the side of trying to coerce types rather than raise an error if a type is wrong` 

but I don't think this is the case here. It's tough to consider the input type as _wrong_ and it's easier to consider the resultant iterator object as such (as it can happen to be consumed on first iteration and then gone - behavior not at all expected from collections).

### Example Code

```Python
from pydantic import validate_arguments
from typing import Iterable, List, Set, Dict, Tuple

@validate_arguments
def foo_iter(arg: Iterable[str]):
    print(f"Type of arg is: {type(arg)}")

@validate_arguments
def foo_lst(arg: List[str]) -> None:
    print(f"Type of arg is: {type(arg)}")

@validate_arguments
def foo_set(arg: Set[str]) -> None:
    print(f"Type of arg is: {type(arg)}")

@validate_arguments
def foo_tuple(arg: Tuple[str, str]) -> None:
    print(f"Type of arg is: {type(arg)}")

@validate_arguments
def foo_dict(arg: Dict[int, str]) -> None:
    print(f"Type of arg is: {type(arg)}")

>>> foo_lst(["foo", "bar"])
Type of arg is: <class 'list'>

>>> foo_set({"foo", "bar"})
Type of arg is: <class 'set'>

>>> foo_tuple(("foo", "bar"))
Type of arg is: <class 'tuple'>

>>> foo_dict({1:"foo", 2:"bar"})
Type of arg is: <class 'dict'>

>>> foo_iter(["foo", "bar"])
Type of arg is: <class 'list_iterator'>

>>> foo_iter({"foo", "bar"})
Type of arg is: <class 'set_iterator'>

>>> foo_iter(("foo", "bar"))
Type of arg is: <class 'tuple_iterator'>

>>> foo_iter({1:"foo", 2:"bar"})
Type of arg is: <class 'dict_keyiterator'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
pydantic compiled: False
install path: C:\Users\(...snip...)\.temp\venv\Lib\sitepackages\pydantic
python version: 3.7.5rc1 (tags/v3.7.5rc1:4082f600a5, Oct  1 2019, 20:28:14) [MSC v.1916 64bit (AMD64)]
platform: Windows-10-10.0.19041-SP0
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
@z33kz33k thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by z33kz33k** [comment]
@lig the type of the input collection is still morphed, but this time into:

```python
>>> foo_iter(["foo", "bar"])
Type of arg is: <class 'pydantic_core._pydantic_core.ValidatorIterator'>
```

I checked both `validate_arguments()` and `validate_call()` on:
```
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=true
install path: /home/(...snip...)/venv/lib/python3.10/site-packages/pydantic
python version: 3.10.5 (main, Jun  4 2023, 22:15:56) [GCC 11.3.0]
platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
related packages: typing_extensions-4.8.0
```
