### ISSUE TITLE
`field` argument to `@validator`

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5170]
In V1 we supported arguments called `config` and `field`.

Since `config` is now a dict instead of a class (https://github.com/pydantic/pydantic/pull/4921) we cant' (easily) be backwards compatible.  I propose we just can this argument altogether and make users access the config dict from `info`. I'm planning on doing this in #5153 

The `field` argument is a bit trickier. It used to be a `ModelField` which is a class that doesn't exist anymore in V2. Since we can't provide an argument of the same type, I propose we add a `field` attribute to `ValidationInfo`. We should try to have it contain approximately the same information as the original `ModelField` but it doesn't need to be a 1:1 match since it's a breaking change anyway. But if we are going to put some sort of `FieldInfo` object in `pydantic-core`, where does that leave the `FieldInfo` that exists in our Python side? I get the feeling that `FieldInfo` was ported over from V1 and is sorta used, but not every attribute is used? Could we come up with a stripped down `FieldInfo` that we can stick into `pydantic-core` and pass into validators?

**Comment by samuelcolvin** [comment]
I think everything on`FieldInfo` is used.

My preference would be to make `info.field` a `str`, then if you want more info you can do `cls.model_fielda[info.field]`.

**Comment by adriangb** [comment]
Completed in #5153 and #5205
