### ISSUE TITLE
V2: Support forward references in recursive types

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5171]
Example:

```python
JSON = Union[str, int, float, bool, None, Mapping[str, 'JSON'], List['JSON']]
```

Given how popular this feature request was for MyPy ([https://github.com/python/typing/issues/182](https://github.com/python/typing/issues/182)), I think it would be nice if it "just worked" for Pydantic. Since `pydantic-core` already supports recursive types, it's just a matter of properly handling the recursive forward references.

@dmontagu I wonder if we could use similar work to what you did with generics for these sorts of recursive references? Ultimately I think we need to convert this into a `DefinitionReference` core schema, but I suspect we'll have to do a bit of smart stuff like your generics but with the forward references to detect the recursive forward reference and not just try to "resolve" it.

**Comment by dmontagu** [comment]
Even if we don't support this, we almost certainly need a better error message:
```python
from typing import List, Mapping, Union

from pydantic import BaseModel

JSON = Union[str, int, float, bool, None, Mapping[str, 'JSON'], List['JSON']]


class A(BaseModel):
    x: JSON
    model_config = dict(arbitrary_types_allowed=True)
```

```
Traceback (most recent call last):
  File "/Users/davidmontague/Library/Application Support/JetBrains/PyCharm2023.1/scratches/scratch_8.py", line 8, in <module>
    class A(BaseModel):
  File "/Users/davidmontague/Programming/pydantic/pydantic/pydantic/main.py", line 124, in __new__
    _model_construction.complete_model_class(
  File "/Users/davidmontague/Programming/pydantic/pydantic/pydantic/_internal/_model_construction.py", line 185, in complete_model_class
    cls.__pydantic_validator__ = SchemaValidator(inner_schema, core_config)
pydantic_core._pydantic_core.SchemaError: Error building "typed-dict" validator:
  SchemaError: Field "x":
  SchemaError: Error building "nullable" validator:
  SchemaError: Error building "union" validator:
  SchemaError: Error building "function" validator:
  SchemaError: Error building "dict" validator:
  SchemaError: Error building "nullable" validator:
  SchemaError: Error building "union" validator:
  SchemaError: Error building "function" validator:
  SchemaError: Error building "dict" validator:
  SchemaError: Error building "is-instance" validator:
  SchemaError: 'cls' must be valid as the first argument to 'isinstance'
```

**Comment by dmontagu** [comment]
Some notes on this, taken from a comment I just made on [a discussion](https://github.com/pydantic/pydantic/discussions/5779#discussioncomment-5921877).

* Once the type alias syntax introduced in this PEP https://peps.python.org/pep-0695/#generic-type-alias is introduced, I think that will be the obvious way to handle it, though that will require python 3.12+.
* Also, it looks like there is active work toward backporting the TypeAliasType into typing_extensions, and once it is added, I think that will be the obvious way to support it in earlier python versions. See https://github.com/python/typing_extensions/issues/159 and https://github.com/python/typing_extensions/pull/160 for reference.
* For what it's worth, I think the pydantic implementation may end up looking similar to this: https://github.com/pydantic/pydantic/commit/ef5dd26c36e90a331fdb6a0a920c3ce619094366. I later reworked this to try to automatically infer the alias name. Ultimately that was a lot more complicated and likely would have perf and other implications, but fortunately `TypeAliasType` is similar _enough_ to the type `RecursiveType` type I introduced in that commit that I think the same implementation/tests/etc. should work.

(@adriangb seems you are already on top of this, and I'm happy to defer to your plan here if you had a different implementation in mind, just adding a comment here before I forget.)
