### ISSUE TITLE
Coalescing schema building logic

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5174]
We currently have a lot of logic for `BaseModel` e.g. to deal with recursive models and generics.
Since we plan to add a `Validator` (#5145) and we also want to support recursive and generic non-model things (e.g. #5138) we are going to end up with quite a bit of logic duplication.

We should be thinking about how we can coalesce this. I'm thinking our goal should be to have a function or functions that take in an arbitrary type and spit out everything we need about that type (core schema, validator, serializer). Then `BaseModel` and `Validator` would just call that (`BaseModel` passing it's own class as the argument). Of course `BaseModel` can still do things in it's metaclass (or `__init_subclass__` or wherever) to keep track of things that will later be needed when building the schema, validator and serializer (like keeping track of `@validator` calls and such).

**Comment by dmontagu** [comment]
@adriangb I'm closing this as I think it's a bit abstract and we have a couple months worth of tweaks/improvements to this code.

But feel free to reopen if you think it makes sense.
