### ISSUE TITLE
APIs for accessing model data from field validators

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5175]
Currently we support this:

```python
class UserModel(BaseModel):
    password1: str
    password2: str

    @validator('password2')
    def passwords_match(cls, v, values, **kwargs):
        if 'password1' in values and v != values['password1']:
            raise ValueError('passwords do not match')
        return v
```

This works but has several issues:
1. `values` is untyped.
2. Validation order depending on field order [can be confusing to users](https://github.com/pydantic/pydantic/issues/3990).
3. It's hard to understand if `passwords_match` will even get called in `password1` fails to validate.

Some ideas for alternative APIs follow

## Allow access to `self` and intercept access to non-validated attributes
We'd allow a `self` argument in the validator and raise an error if you try to access a field that hasn't been validated yet or failed validation.
This would totally solve the typing issue and would at least make the other two easier because the error message will be better than a `KeyError`.

```python
class UserModel(BaseModel):
    password1: str
    password2: str

    @validator('password1')
    def passwords_match1(self, v: str):
        self.password2  # raises an error saying that you can't access password2 in password1's validator

    @validator('password2')
    def passwords_match2(self, v: str):
        if v != self.password1:  # raises an error if `password1` didn't pass validation
            raise ValueError('passwords do not match')
        return v
```

This also has the advantage of keeping the signature for the validators static and keeping the semantics of validating fields in order (the latter could be a disadvantage performance wise, see https://github.com/pydantic/pydantic-core/issues/433).

## Same as above but keeping `values`

Same idea as above but using the untyped `values` dict. This at least makes the errors nicer, but it doesn't do anything for typing.

## FastAPI-like dependancies between validators

```python
class UserModel(BaseModel):
    password1: str
    password2: str

    @validator('password1')
    def passwords_match1(self, v: str, password2: str) -> str:  ...

    @validator('password2')
    def passwords_match2(self, v: str, password1: str) -> str: ...
```

We would detect that `passwords_match2` accepts `password1` as a keyword argument and pass the validated value in. In this case there’s also a circular dependency, we can detect that and error at model definition time.

This lets users add a type for `password1` but unfortunately it can't be derived from the field's type, although our mypy plugin might be able to at least enforce that they match.

The big advantage of this approach is that we can know at build time which fields depend on which other fields. That means we could move away from validating in order and enable optimizations like https://github.com/pydantic/pydantic-core/issues/433. I also think this would be less confusing to users since they have to be explicit about what fields they depend on and won't be surprised or even have to think about the validation order.

It is also relatively clear that `passwords_match2` won't be called if `password1` did not pass validation.

One of the cons of this approach is that it makes the validator's signature dynamic. We'd have to introspect it and pass the result of that introspection along to `pydantic-core` so that it can dynamically build the right kwargs dict to call the validator with.

### Calling `passwords_match2` when `password1` did not pass validation.

If we wanted to allow this we could introduce some annotations or types to mark this as desired:

```python
@dataclass
class Validated(Generic[T]):
    value: T

MaybeValidated= Union[Validated[T], ValidationError]

@validator('password2')
def passwords_match2(self, v: str, password1: MaybeValidated[str]) -> str: ...
````

**Comment by dmontagu** [comment]
I think this can be closed now thanks to `@model_validator` etc., but I'll leave it to you to confirm?

**Comment by adriangb** [comment]
Sorta. There is still no way to get _typed_ values for other parameters in a field validator. Part of me wants to remove the `values` option from `@field_validator` and encourage people to use `@model_validator` if they need to access other fields.

**Comment by samuelcolvin** [comment]
I do think it makes sense to be able to access `values`, even though it's untyped.

**Comment by adriangb** [comment]
Happy to just close this but what scenarios does that cover that a model validator doesn’t also cover?

**Comment by samuelcolvin** [comment]
I don't think any scenarios that are only possible with `field_validator`, but you have to be a bit more careful about raising a  `ValidationError` directly and setting the `loc` of the error, rather than just raising a `ValueError` or `PydanticCustomError` and letting pydantic take care of setting the `loc` correctly.

But more generally I do think there are cases where the current behaviour from V1 which is replicated in V2 is the easiest and clearest way to do some things.

As mentioned before, it's more important that pydantic is easy to use, than typing correct IMHO.
