### ISSUE TITLE
Override json encoder for individual field

### ISSUE THREAD

**Issue by pavelschon** [pydantic/pydantic#5178]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I would like to be able to override JSON encoder for individual fields, instead for the whole model.
The following example is not possible, or I could not realize how to achieve that based on [documentation](https://docs.pydantic.dev/usage/exporting_models/#custom-json-deserialisation). 

Example:
```
from pydantic import BaseModel
from decimal import Decimal
from functools import partial

class Foo(BaseModel):
    price: Decimal = Field(encode=partial(round, ndigits=2))
    size: Decimal = Field(encode=partial(round, ndigits=1))

Foo(price=Decimal('1.11111111'), size=Decimal('2.222222')).json()  # want: '{"price": 1.11, "size": 2.2}' 
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [x] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by yezz123** [comment]
You can define a custom `DecimalEncoder` class that inherits from the `json.JSONEncoder` class and overrides the `default()` method to handle `Decimal` objects by converting them to `floats`.

Then, in the `json` method of the `Foo` class, we pass an instance of `DecimalEncoder` as the `cls` argument to `json.dumps()` to use the custom encoder.

### Example

```py
import json

class DecimalEncoder(json.JSONEncoder):
    """
    Custom JSON encoder that can handle Decimal objects.
    """
    def default(self, obj: Any) -> Any:
        if isinstance(obj, Decimal):
            return float(obj)
        return super().default(obj)
```

### Understanding how to override `JSON` encoder for individual fields

In this part, you need to define a custom  `json` method that first calls `self.dict()` to get a dictionary of the model's fields and values. 

Then, for each field, you can check if a custom encoder function has been defined using the encoding parameter of the `Field()` class. If so, you apply the encoder to the field's value.

Finally, you serialize the modified dictionary to a JSON formatted string using `json.dumps()`.

```py
import json
from typing import Any
from pydantic import BaseModel, Field
from decimal import Decimal
from functools import partial

class Foo(BaseModel):
    price: Decimal = Field(encode=partial(round, ndigits=2))
    size: Decimal = Field(encode=partial(round, ndigits=1))

    def json(self, *args: Any, **kwargs: Any) -> str:
        """
        Serialize the model to a JSON formatted string.
        """
        data = self.dict()
        for field_name, field in self.__fields__.items():
            if field_name in data:
                # Apply the custom encoder to the field
                encode_func = field.field_info.extra.get('encode')
                if encode_func:
                    data[field_name] = encode_func(data[field_name])

        return json.dumps(data, cls=DecimalEncoder, *args, **kwargs)
```

you can define the price and size fields with the `encode` parameter set to `partial(round, ndigits=X)`, where `X` is the desired number of digits to round to.

Then define the custom `DecimalEncode`r class and the `json` method of the `Foo()` class in the same way as before.

Now you can run your example around and get the desired result:

```py
foo = Foo(price=Decimal('1.11111111'), size=Decimal('2.222222')).json()

print(foo) # {"price": 1.11, "size": 2.2}
```

Hope this can help you

**Comment by pavelschon** [comment]
Thanks, your solution will actually work.
I wish this is a feature of the framework, maybe in the planned Pydantic V2.
What's your opinion on that?

**Comment by samuelcolvin** [comment]
This is already possible in pydantic-core and is already partially implemented in `main`.

There are two solutions, both shown here.

```py
def custom_int_serialising(value: int, info):
    return f'custom serializer 1: {value}'

# this makes CustomInt reusable, 
# but you could also put this code directly into the model on the "x: " line
CustomInt = Annoated[int, CustomSerializer(custom_int_serialising)]

class MyModel(BaseModel):
    x: CustomInt
    y: int

    @serializer('y')
    def custom_serializer(self, info):
        return f'custom serializer 2: {self.y}'
```

Both are WIP, but should be fully supported  when we release V2.

I'll close this since you have a fix for now.
