### ISSUE TITLE
Description changes when you use pydantic.dataclasses twice

### ISSUE THREAD

**Issue by codectl** [pydantic/pydantic#5217]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Considering the following example:

```python
from dataclasses import dataclass
import pydantic.dataclasses as pydc


@dataclass
class Foo:
    arg1: str
    arg2: str
    

print(pydc.dataclass(Foo).__pydantic_model__.schema())
print(pydc.dataclass(Foo).__pydantic_model__.schema())
```

Results in:

```bash
{'title': 'Foo', 'type': 'object', 'properties': {'arg1': {'title': 'Arg1', 'type': 'string'}, 'arg2': {'title': 'Arg2', 'type': 'string'}}, 'required': ['arg1', 'arg2']}
{'title': 'Foo', 'description': 'Foo(arg1: str, arg2: str)', 'type': 'object', 'properties': {'arg1': {'title': 'Arg1', 'type': 'string'}, 'arg2': {'title': 'Arg2', 'type': 'string'}}, 'required': ['arg1', 'arg2']}
```

If you notice, in the second run, the ```description``` attribute contains a strange value.

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.6
            pydantic compiled: True
                 install path: /Users/renato/Library/Caches/pypoetry/virtualenvs/apispec-plugins-c17nWIz5-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ]
                     platform: macOS-13.0-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by yvalencia91** [comment]
I believe it's been addressed in this PR https://github.com/pydantic/pydantic/pull/5009

**Comment by dmontagu** [comment]
That PR was for v2 so would not have resolved it.

There is a one line fix that I think should be safe:
```diff
diff --git a/pydantic/dataclasses.py b/pydantic/dataclasses.py
index 86bad1e..b9f22ab 100644
--- a/pydantic/dataclasses.py
+++ b/pydantic/dataclasses.py
@@ -223,6 +223,7 @@ def dataclass(
         should_validate_on_init = default_validate_on_init if validate_on_init is None else validate_on_init
         _add_pydantic_validation_attributes(cls, the_config, should_validate_on_init, dc_cls_doc)
         dc_cls.__pydantic_model__.__try_update_forward_refs__(**{cls.__name__: cls})
+        dc_cls.__doc__ = dc_cls_doc
         return dc_cls
```

If someone wants to open a PR for it (though I'm not sure we'd do a release just for this). That said, I would generally advise against applying the dataclass decorator multiple times anyway.

**Comment by lig** [comment]
Pydantic V2 uses `TypeAdapter` for generating JSON Schema of dataclasses. See [Migration Guide / Changes to dataclasses](https://docs.pydantic.dev/2.0/migration/#changes-to-dataclasses).

The following code is the original example ported to Pydantic V2. The issue doesn't reproduce in Pydantic V2.

```py
    import pydantic.dataclasses
    import pydantic.json_schema

    @pydantic.dataclasses.dataclass
    class Foo:
        """Description"""
        arg1: str
        arg2: str
    
    first_schema = TypeAdapter(Foo).json_schema()
    second_schema = TypeAdapter(Foo).json_schema()

    assert first_schema['description'] == second_schema['description']
```
