### ISSUE TITLE
Using Optional with typing.Annotated

### ISSUE THREAD

**Issue by AlexanderPodorov** [pydantic/pydantic#5218]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

See example code.
Keeping in mind that V2 will use `typing.Annotated` really heavily, this could be the issue too.
`con*` functions return type itself, and we can't say we want it to be optional.

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Annotated

# no validation error raised (not OK):

TestType = Annotated[str, Field(min_length=1, max_length=4)]

class TestModel(BaseModel):
    f: TestType | None

t = TestModel(f='12345')

# validation error is raised (OK):

TestType = Annotated[str | None, Field(min_length=1, max_length=4)]

class TestModel(BaseModel):
    f: TestType

t = TestModel(f='12345')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: True
                 
               python version: 3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.0.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I'm confused, are you saying this is a bug in Vl1 or V2?

**Comment by AlexanderPodorov** [comment]
Hi @samuelcolvin ! Sorry for confusing you.
The issue I mentioned in the example code is related to V1.
I also wanted to note we need to make sure we won't get this behavior in V2 as well, for instance:
```python
# V2 code
from pydantic.types import constr
from pydantic import BaseModel

class TestModel(BaseModel):
    field: constr(max_length=4) | None  # if a string is provided, we need to validate it against configured constr
```
The type specified inside `Annotated` should be just `str`, not `str | None`.
Let me know if something is still unclear. Thanks!

**Comment by samuelcolvin** [comment]
Doubt we can change this in v1 now.

In V2, the first case should work fine.

The second case is a bit more tricky, it involves passing constraints down through an `Optional` to the non-none branch of the union. I'm pro doing this, but I know some had reservations about it.

@AlexanderPodorov might be worth trying it on V2 and seeing how it works, if it's working as you expect, please submit a PR to add tests these cases.

**Comment by AlexanderPodorov** [comment]
Yes, first case should work fine. Based on https://github.com/pydantic/pydantic/blob/main/tests/test_types.py
Second case generally does not need to be supported, we are good with just first use case. I just wanted to give you both examples for reference, it would be much better if V1 could support 1st case instead of 2nd :)
But since V2 will come soon, it does not make sense to fix that in V1. I'm closing the issue. Thanks!
