### ISSUE TITLE
Custom type subclassed `str` used as type in a pydantic model's field becomes of type `str` instead of the custom type after the model is instantiated.

### ISSUE THREAD

**Issue by jymchng** [pydantic/pydantic#5220]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Custom type subclassed `str` used as type in a pydantic model's field becomes of type `str` instead of the custom type after the model is instantiated.

I have a custom type called `EthereumAddress(str)` which subclass the in-built `str`, it has comparison dunder-interface methods `__ne__` and `__eq__` implemented to compare if two `EthereumAddress` are the same (e.g. if the comparison is done between a `str` and an `EthereumAddress`, it is compared case-insensitively). Suppose a pydantic model uses `EthereumAddress` as one of its fields' type, once instantiated, an instance of the model will have this field of type `str` instead of type `EthereumAddress`.

This affects the usage of the pydantic model because if a field is annotated with a custom type, it is assumed that the value of the field of that instance of the pydantic model will have that custom type instead of some other type. E.g. the comparison between two `str` types and that of `str` and `EthereumAddress` are implemented different and would give different results.

### Example Code

```Python
import pydantic

# implementation of `EthereumAddress`

class EthereumAddress(str):

    def __new__(cls, value: str) -> 'EthereumAddress':
        instance = super().__new__(cls, cls.validate_ethereum_address(value.lower()))
        return instance

    @classmethod
    def validate_ethereum_address(cls, v: str) -> str:
        if not v.startswith("0x") or len(v) != 42:
            raise ValueError('Invalid Ethereum address')
        return v

    @classmethod
    def __get_validators__(cls) -> 'CallableGenerator':
        yield cls.validate_ethereum_address

    def __eq__(self, other: object) -> bool:
        if isinstance(other, EthereumAddress):
            return str(self) == str(other)
        elif isinstance(other, str):
            return str(self) == other.lower()
        else:
            return False
        
    def __ne__(self, other: object) -> bool:
        if isinstance(other, EthereumAddress):
            return str(self) != str(other)
        elif isinstance(other, str):
            return str(self) != other.lower()
        else:
            return False

    def __repr__(self) -> str:
        return f'EthereumAddress("{self}")'

    def __str__(self) -> str:
        return super().__str__()

# codes that show comparison between `str` and `EthereumAddress` is done case-insensitively
# no assertion error raised
assert EthereumAddress('0xd6d88aa34dfba00efcfb564b95bbf20a9c8de545') == '0xD6d88aA34DfBA00efCfb564B95bbF20A9C8de545'

# pydantic model

class EthereumAccount(BaseModel):
    ethereum_address: EthereumAddress

# two `EthereumAccount`s are instantiated

acct = EthereumAccount(ethereum_address='0xd6d88aa34dfba00efcfb564b95bbf20a9c8de545')
acct_two = EthereumAccount(ethereum_address=EthereumAddress('0xd6d88aa34dfba00efcfb564b95bbf20a9c8de545'))

# look at their types of the field `ethereum_address`

type(acct.ethereum_address), type(acct_two.ethereum_address)

# ... (str, __main__.EthereumAddress)

# taking the field `ethereum_address` and compared it with a `str`
acct.ethereum_address == '0xD6d88aA34DfBA00efCfb564B95bbF20A9C8de545'
# False
acct_two.ethereum_address == '0xD6d88aA34DfBA00efCfb564B95bbF20A9C8de545'
# True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: C:\User\AppData\Local\Programs\Python\Python310\Lib\site-packages\pydantic
               python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by jymchng** [comment]
Hi, how is it going?

**Comment by samuelcolvin** [comment]
I don't understand, as shown in your code `type(acct_two.ethereum_address)` is `EthereumAddress`.

I've also run your code and found the same thing, so I'm not sure what the question is.

If you're wondering why `acct.ethereum_address` is a `str`, not a `EthereumAddress`, it's because your `validate_ethereum_address` method returns the raw input value, not necessarily an `EthereumAddress`

**Comment by jymchng** [comment]
@samuelcolvin Thank you Samuel for replying and answering my question. Indeed, under `validate_ethereum_address` I should have returned `cls(v)`, i.e. an instance of `EthereumAddress` instead of merely `v`.
