### ISSUE TITLE
GenericModel doesn't take into account the value of `copy_on_model_validation` config

### ISSUE THREAD

**Issue by igor-chernikov** [pydantic/pydantic#5227]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Please see the code example below for details. 

### Example Code

```Python
from typing import Sequence, TypeVar, Generic

from pydantic import BaseModel
from pydantic.generics import GenericModel


T = TypeVar('T', bound=BaseModel)


class Foo(BaseModel):
    foo: str

    class Config:
        copy_on_model_validation = 'none'


class SimpleBar(BaseModel):
    foo: Foo


class GenericBar(GenericModel, Generic[T]):
    foo: T


f = Foo(foo='1')

b1 = SimpleBar(foo=f)
print(id(f) == id(b1.foo))  # True

b2 = GenericBar(foo=f)
print(id(f) == id(b2.foo))  # False
```

### Python, Pydantic & OS Version

```Text
❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"
             pydantic version: 1.10.6
            pydantic compiled: True
                 install path: /path/to/virtualenv/python-3.10.0/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Mar  4 2022, 11:29:07) [Clang 13.0.0 (clang-1300.0.27.3)]
                     platform: macOS-13.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
I'm looking into this now, but for what it's worth it does work if you parametrize the model:
```python
b2 = GenericBar[Foo](foo=f)
print(id(f) == id(b2.foo))  # True
```

**Comment by dmontagu** [comment]
This doesn't seem to be specific to generics:
```python
class SimpleBar(BaseModel):
    foo: T


f = Foo(foo='1')

b1 = SimpleBar(foo=f)
print(id(f) == id(b1.foo))  # False
```

I haven't used `copy_on_model_validation` before, but I'm assuming what's going on here is that the type needs to be inspected from the field for it to be used properly.

Does the `GenericBar[Foo]` approach work for you?

@samuelcolvin is there a way to control this behavior for a field of type `Any`? Also, is there anything analogous in v2?

**Comment by dmontagu** [comment]
Oops, I've just realized it does the right thing for `Any`, but _not_ for `T` where `T` is a TypeVar... looking into it more..

**Comment by dmontagu** [comment]
Okay, I think I've actually figured out what's going on:

* `T` here has a bound of `BaseModel`. When you have an unparametrized generic like this, it will use the bound to produce the validator. In this case, it's using the logic that `BaseModel` uses for validation, which won't respect the `copy_on_model_validation` value.
  * This is actually important; you don't necessarily want subclasses to be able to override the copying logic. At least, that would be a feature request, which I see arguments against.
* To resolve this, you want to set the bound of `T` to be something that sets `copy_on_model_validation` in its config.
  * However, if you do this, you need to be careful to use that as a parent class of anything you are going to pass in as T, or else it will end up re-parsed.

For example, the following works:
```python
from typing import TypeVar, Generic

from pydantic import BaseModel
from pydantic.generics import GenericModel


class CopyOnModelValidationModel(BaseModel):
    class Config:
        copy_on_model_validation = 'none'


T = TypeVar('T', bound=CopyOnModelValidationModel)


class Foo(CopyOnModelValidationModel):
    foo: str


class SimpleBar(BaseModel):
    foo: Foo


class GenericBar(GenericModel, Generic[T]):
    foo: T


f = Foo(foo='1')

b1 = SimpleBar(foo=f)
print(id(f) == id(b1.foo))  # True

b2 = GenericBar(foo=f)
print(id(f) == id(b2.foo))  # True
```

I'll also note for clarity around how generics work, using `T` as the annotation as you did, if you don't parametrize the generic model, its essentially equivalent to:
```python
class SimpleBar(BaseModel):
    foo: BaseModel
```
which I think makes it less surprising why it is behaving this way.

----

Given the above, I'm going to close this issue, but I think a feature request making it possible to not copy _any_ model would be reasonable. However, I think this behavior is not likely to be changed prior to v2, and I don't know if v2 might be changing how this works. (@samuelcolvin might have more insight..)

**Comment by samuelcolvin** [comment]
We have `revalidate` on either config or `model-schema` which does effectively the same thing, we might need to rename it.

Not sure it'll work on generics as it requires an exact type match.
