### ISSUE TITLE
Model creation fails if a default value uses a subclass of datetime

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#5236]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

It seems that for subclasses of `datetime`, pydantic performs a `smart_deepcopy` which fails:

<details>

<summary>Error</summary>

```
../../Library/Caches/pypoetry/virtualenvs/pythonproject3-nIT-Z9on-py3.9/lib/python3.9/site-packages/pydantic/fields.py:570: in _set_default_and_type
    default_value = self.get_default()
../../Library/Caches/pypoetry/virtualenvs/pythonproject3-nIT-Z9on-py3.9/lib/python3.9/site-packages/pydantic/fields.py:439: in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
../../Library/Caches/pypoetry/virtualenvs/pythonproject3-nIT-Z9on-py3.9/lib/python3.9/site-packages/pydantic/utils.py:693: in smart_deepcopy
    return deepcopy(obj)  # slowest way when we actually might need a deepcopy
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/copy.py:172: in deepcopy
    y = _reconstruct(x, memo, *rv)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = UtcDateTime(2023, 3, 21, 9, 38, 3, 64733, tzinfo=datetime.timezone.utc)
memo = {4389379920: datetime.timezone.utc, 4390543888: datetime.timedelta(0), 4401450304: [datetime.timedelta(0)]}
func = <class 'test_datetime.UtcDateTime'>
args = <generator object _reconstruct.<locals>.<genexpr> at 0x106706350>
state = None, listiter = None, dictiter = None
deepcopy = <function deepcopy at 0x105008dc0>

    def _reconstruct(x, memo, func, args,
                     state=None, listiter=None, dictiter=None,
                     deepcopy=deepcopy):
        deep = memo is not None
        if deep and args:
            args = (deepcopy(arg, memo) for arg in args)
>       y = func(*args)
E       TypeError: __new__() missing 1 required positional argument: 'day'

/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/copy.py:264: TypeError
```

</details>

The problem IMO is this check which does not check fo

```py
    obj_type = obj.__class__
    if obj_type in IMMUTABLE_NON_COLLECTIONS_TYPES:
        return obj  # fastest case: obj is immutable and not collection therefore will not be copied anyway
```

First, `datetime` could be added to `IMMUTABLE_NON_COLLECTIONS_TYPES`. This would save a deepcopy cycle which is not necessary. However, it does not solve the problem I am facing. 
Is there a reason that we are not treating subclasses of the types in `IMMUTABLE_NON_COLLECTIONS_TYPES` the same way we are treating the types themselves?

Would you consider a PR which 
a) adds `datetime` to the constant
b) applies the same semantics to subclasses and not only the classes themselves? 

### Example Code

```Python
from datetime import datetime, timezone

from pydantic import BaseModel


class UtcDateTime(datetime):
    def __new__(
        cls,
        year: int,
        month: int,
        day: int,
        hour: int = 0,
        minute: int = 0,
        second: int = 0,
        microsecond: int = 0,
        tzinfo: datetime.tzinfo = None,
        *,
        fold: int = 0
    ):
        if tzinfo and tzinfo != 0:
            raise TypeError("timezone must be UTC")
        return super().__new__(
            cls, year, month, day, hour, minute, second, microsecond, timezone.utc,
            fold=fold
        )


def test_subclass():
    # fails
    class Default(BaseModel):
        created: UtcDateTime = UtcDateTime.now()

    assert Default()


def test_datetime():
    # works
    class Default(BaseModel):
        created: UtcDateTime = datetime.now()

    assert Default()
```

### Python, Pydantic & OS Version

```Text
❯ python -c "import pydantic.utils; print(pydantic.utils.version_info())"

             pydantic version: 1.10.6
            pydantic compiled: False
                 install path: /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/pythonproject3-nIT-Z9on-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by chbndrhnns** [comment]
I have not much looked into the changes coming with v2 so I can only speak about my expectations for v1:

If I subclass an immutable type, I expect pydantic to treat my subclass like it treats the super type.

What do you find confusing about the expected behaviour?

**Comment by samuelcolvin** [comment]
well:
1. You're setting the default value here, not the input value to validation, without customisation, the default value isn't validated.
2. There are two cases `UtcDateTime` as the field type, and `UtcDateTime` as the input value, and the cross products of these two choices, which are you trying to do?
3. Here your field type is `UtcDateTime`, but the default value (which I assume you're thinking of as somehow equivalent to the validation input value) is a `datetime`, which is a super-class, not a subclass of `UtcDateTime`, e.g. `isinstance(datetime.now(), UtcDateTime) is False`

Hence I'm somewhat unclear what you're trying to do.

**Comment by chbndrhnns** [comment]
> You're setting the default value here, not the input value to validation, without customisation, the default value isn't validated.

And although it's not validated, pydantic is unable to even instanciate it unless I use `pydantic.Field(default_factory=UtcDateTime.now)`. My understanding is that `default_factory` is mainly for mutable types which `datetime` is not.

> There are two cases UtcDateTime as the field type, and UtcDateTime as the input value, and the cross products of these two choices, which are you trying to do?

I think all of them.
I'd like to see `UtcDateTime` as the target type for the field and whatever I pass in is coerced if valid (that is how v1 work, right?).

> Here your field type is UtcDateTime, but the default value (which I assume you're thinking of as somehow equivalent to the validation input value) is a datetime, which is a super-class, not a subclass of UtcDateTime, e.g. isinstance(datetime.now(), UtcDateTime) is False

The default value is of type `UtcDateTime` here. And yes, it's a subclass of `datetime`.

```py
def test():
    assert isinstance(UtcDateTime.now(), UtcDateTime)
    assert isinstance(UtcDateTime.now(), datetime)
```

**Comment by samuelcolvin** [comment]
Your error with defaults is just because your type fails on deepcopy, you just need to add

```py
    def __deepcopy__(self, _memo):
        return self
```
