### ISSUE TITLE
V2: bug in EnumStr validators

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5242]
https://github.com/pydantic/pydantic/blob/84d0acf6882958993a6e0d984969030e31f16dc0/tests/test_validators.py#L1234-L1253

**Comment by adriangb** [comment]
@samuelcolvin looking at this again I do really think it's a bug, but you had mentioned this might be the behavior we want. Like the comment says if we just compare with `==` instead of `is` things work. Do you think this is an intended behavior change or a bug?

**Comment by dmontagu** [comment]
I personally would consider this a bug, if it's annotated as having an enum literal, it would be reasonable to expect that you could access `my_foo.barfiz.value` for example; if the current behavior is to set `my_foo.barfiz` to `'barfiz'`, you wouldn't get a type error but would get a runtime error trying to access `my_foo.barfiz.value`.

**Comment by adriangb** [comment]
I’ll fix tonight/tomorrow
