### ISSUE TITLE
serialize decorators don't work without `info`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5269]
If you try to use the following

```py
class WithCustomEncoders(BaseModel):
    dt: datetime

    @serializer('dt')
    def serialize_dt(self, dt: datetime):
        return dt.timestamp()
```

You get an error about `SerializationInfo` doesn't have a `timestamp()` method.

If you change the signature to `def serialize_dt(self, dt: datetime, info):`, it works fine.

**Comment by adriangb** [comment]
Resolved
