### ISSUE TITLE
Can't use `__all__` for dicts

### ISSUE THREAD

**Issue by mike0sv** [pydantic/pydantic#5301]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When using `__all__` to include/exclude in nested list fields it works as expected, but does not work for dicts. 
It seems that `__all__` only gets special treatment for lists and tuples in `ValueItems`'s constructor

### Example Code

```Python
from typing import Dict, List

from pydantic import BaseModel


class Hobby(BaseModel):
    name: str
    info: str


class User(BaseModel):
    d: Dict[str, Hobby]
    l: List[Hobby]


user = User(
    d={"A": Hobby(name='Programming', info='Writing code and stuff')},
    l=[Hobby(name='Programming', info='Writing code and stuff')]
)

print(user.dict(include={'l': {'__all__': {'info'}}}))  
# {'l': [{'info': 'Writing code and stuff'}]}
print(user.dict(include={'d': {'__all__': {'info'}}}))
# {'d': {}}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: False
                 install path: /Users/mike0sv/mambaforge/envs/evidently/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)  [Clang 14.0.6 ]
                     platform: macOS-13.0.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by mike0sv** [comment]
As a workaround, I used this code like this
```python
class AllDict(dict):
    def __init__(self, value):
        super().__init__()
        self._value = value

    def __contains__(self, item):
        return True

    def get(self, __key):
        return self._value

    def __repr__(self):
        return f"{{'__all__':{self._value}}}"

    def __bool__(self):
        return True
 
 print(user.dict(include={'d': AllDict({'info'})}))
 ```
 Btw, something similar could be used internally for lists too (instead of copying config for each element)

**Comment by hramezani** [comment]
It's working as expected in `V2`.

`dict()` is deprecated in `V2`, you  can use `model_dump()` instead.
