### ISSUE TITLE
Reuse validator cannot use same method name to define

### ISSUE THREAD

**Issue by unights** [pydantic/pydantic#5307]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have two validator factories to create reuse validators for custom fields. 

But if two wrapper methods have the same name, only the last validator will work.

For example

```python
from typing import Optional

from pydantic import BaseModel, validator


def func1(*field: str):
    def wrapper(v):
        print(type(v))
        return v or None

    return validator(*field, pre=True, allow_reuse=True)(wrapper)


def func2(*field: str):
    def wrapper(v):
        print(type(v))
        return 1 if v else 2

    return validator(*field, allow_reuse=True)(wrapper)


class Model(BaseModel):
    val: Optional[int] = None

    _v1 = func1("val")
    _v2 = func2("val")


print(Model(val="").val)
```

I got an error. The first validator has no effect.

```python
Traceback (most recent call last):
  File "D:\Projects\test.py", line 30, in <module>
    print(Model(val="").val)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Model
val
  value is not a valid integer (type=type_error.integer)
```

But if I change the method name, such as

```python
def func2(*field: str):
    def wrapper2(v):  # change from 'wrapper' to 'wrapper2'
        print(type(v))
        return 1 if v else 2

    return validator(*field, allow_reuse=True)(wrapper2)
```

Both validators are working fine

```python
<class 'str'>
<class 'NoneType'>
2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: D:\Projects\venv\Lib\site-packages\pydantic 
               python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
@unights thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by unights** [comment]
> @unights thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

@lig No, there is no such problem in v2.

```python
from typing import Optional

from pydantic import BaseModel, field_validator


def func1(*field: str):

    @classmethod
    def wrapper(cls, v):
        print(type(v))
        return v or None

    return field_validator(*field, mode='before')(wrapper)


def func2(*field: str):

    @classmethod
    def wrapper(cls, v):
        print(type(v))
        return 1 if v else 2

    return field_validator(*field)(wrapper)


class Model(BaseModel):
    val: Optional[int] = None

    _v1 = func1("val")
    _v2 = func2("val")


print(Model(val="").val)
```

The output is 

```python
<class 'str'>
<class 'NoneType'>
2
```

And I guess it is caused by the wrong setting of `field.class_validators` in v1.

```python
# If both are "wrapper"

print(Model.__fields__['val'].class_validators)
# {'wrapper': <pydantic.class_validators.Validator object at 0x0000021090D22720>}
```

```python
# If one is "wrapper" and the another is "wrapper2"

print(Model.__fields__['val'].class_validators)
# {'wrapper': <pydantic.class_validators.Validator object at 0x00000151A62F9130>, 'wrapper2': <pydantic.class_validators.Validator object at 0x00000151A6582860>}
```

I hope this can help you.

**Comment by lig** [comment]
@unights Tank you! I'm closing this as completed as it is fixed in Pydantic v2
