### ISSUE TITLE
`schema_json` generates invalid json schema with `$ref` adjacent to `definitions` property when model references itself

### ISSUE THREAD

**Issue by DetachHead** [pydantic/pydantic#5316]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

when a pydantic model has a property that references itself, it the generated json schema has the `definitions` property on the same level as the `$ref` property. this causes a crash when attempting to resolve the refs with [`json-refs`](https://github.com/whitlockjc/json-refs). i initially raised an issue there but was told that the json schema is invalid. https://github.com/whitlockjc/json-refs/issues/206#issuecomment-1490488122

> The issue here is that at the root of your document, you have an invalid JSON Reference because `$ref` cannot be adjacent to any other properties

### Example Code

```Python
from __future__ import annotations

from pydantic import BaseModel


class Foo(BaseModel):
    b: Foo | None = None


print(Foo.schema_json())
```
```json
{
  "$ref": "#/definitions/Foo",
  "definitions": {
    "Foo": {
      "title": "Foo",
      "type": "object",
      "properties": { "b": { "$ref": "#/definitions/Foo" } }
    }
  }
}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.5
            pydantic compiled: False
                 install path: C:\Users\[user]\AppData\Local\pypoetry\Cache\virtualenvs\[project name]-n2-MipS8-py3.11\Lib\site-packages\pydantic
               python version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by DetachHead** [comment]
`BaseModel.schema_json` and `schema_json_of` seem to behave differently, sometimes `schema_json_of` generates these invalid schemas while `BaseModel.schema_json` does not:
```py
from pydantic import BaseModel, schema_json_of


class Foo(BaseModel):
    b: int


print(Foo.schema_json())
"""
{
  "title": "Foo",
  "type": "object",
  "properties": { "b": { "title": "B", "type": "integer" } },
  "required": ["b"]
}
"""

print(schema_json_of(Foo))
"""
{
  "title": "ParsingModel[Foo]",
  "$ref": "#/definitions/Foo",
  "definitions": {
    "Foo": {
      "title": "Foo",
      "type": "object",
      "properties": { "b": { "title": "B", "type": "integer" } },
      "required": ["b"]
    }
  }
}
"""
```

**Comment by samuelcolvin** [comment]
Interesting is it right on main/V2?

Happy to reveal fix for V1 if it's not too convoluted.

**Comment by DetachHead** [comment]
it seems to work correctly in v2, however it's hard to fully test as there seem to be other issues with v2 in our codebase that i don't have time to investigate atm
