### ISSUE TITLE
BaseModel.parse_raw changed bool value to int for type `Union[ int, bool]` 

### ISSUE THREAD

**Issue by honglei** [pydantic/pydantic#5318]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Like following code, if use give `value=True`, the result Filter object's field should be  `value=True`,not `value=1`
```
class Filter(BaseModel):
    field: str =Field()
    value: Union[int, bool]
```

### Example Code

```Python
import json
from typing import Union
from pydantic import BaseModel, Field
class Filter(BaseModel):
    field: str =Field()
    value: Union[int, bool]
    
class Filter2(BaseModel):
    field: str =Field()
    value: Union[bool,int]
    
obj = {
       "field": "success",
       "value": True
}

result = Filter.parse_raw( json.dumps(obj) )
print (f"{result=}")
# result: Filter(field='success', value=1)    # Wrong: bool->int

result2 = Filter2.parse_raw( json.dumps(obj) )
print (f"{result2=}")
# result2: Filter2(field='success', value=True) # Right
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: C:\Python311\Lib\site-packages\pydantic
               python version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['devtools', 'dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Yup, this is a  known problem with V1, there are many issues explaining that we try union choices in the order they're set in the `Union`.

Solution in V1 is to use [smart union](https://docs.pydantic.dev/usage/model_config/#smart-union).

This is fixed by default in v2.
