### ISSUE TITLE
Import time and deferred imports

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5349]
See #1127 for prior-art.

Once V2 code / `main` is more settled, we need to do a proper analysis with tuna or similar and see which imports we should defer to keep import time to a minimum.

**Comment by samuelcolvin** [comment]
This is great, thank you.

We should have a quick hack and see if we can defer import of
* `pydantic._internal._dataclasses`
* all the extra stuff in `pydantic.types`
* maybe even `core_schema`

Basically see if some small changes could cause a big reduction in time.

**Comment by samuelcolvin** [comment]
@art049 is there a way to use codspeed to profile this using valgrind so we can run it on CI?

**Comment by Kludex** [comment]
I'm sorry, my previous results from Pydantic V1 were wrong...

This is the right one for V1:

![image](https://user-images.githubusercontent.com/7353520/231439516-e7fce528-ccf6-4672-a6d8-eb453c354501.png)

and this is for V2:

![image](https://user-images.githubusercontent.com/7353520/231439575-acb30362-89aa-43f8-ae09-61273fc74373.png)

Same commands:
```bash
❯ python -X importtime -c 'import pydantic' 2> import.log
❯ tuna import.log
```

I guess the difference is not that much now...

**Comment by Kludex** [comment]
I'm sorry, my previous report on V1 was wrong (see on the graph that we don't have any pydantic import)...

This is the right one for V1:

![image](https://user-images.githubusercontent.com/7353520/231440038-ba7b3767-be6a-4880-8650-ee562dfdde60.png)

And this is for V2:

![image](https://user-images.githubusercontent.com/7353520/231440101-aca9382c-a64d-46c4-93df-4dee52de5045.png)

The difference is not huge now.

The commands used were the same:
```bash
❯ python -X importtime -c 'import pydantic' 2> import.log
❯ tuna import.log
```

**Comment by dmontagu** [comment]
Might be able to trim some of the fat from v2 by deferring imports related to deprecated functionality.

**Comment by art049** [comment]
> @art049 is there a way to use codspeed to profile this using valgrind so we can run it on CI?

Yes I think it should be possible! 
I'll draft a small preview so we can have a look to the data.

**Comment by samuelcolvin** [comment]
Thanks @art049, that sounds amazing.

**Comment by Kludex** [comment]
Given the report on https://github.com/pydantic/pydantic/issues/5349#issuecomment-1505087649, I'll be closing this issue.
