### ISSUE TITLE
Remove requirement that callables have `__qualname__` attribute

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5352]

**Comment by samuelcolvin** [comment]
please can you check this is fixed, see #5126 for some context.

**Comment by dmontagu** [comment]
I don't believe this is currently resolved, but I will just point out that in most places where `.__qualname__` is accessed directly, it seems to me that either `pydantic._internal._core_utils.get_type_ref` or something very similar could be used instead.

**Comment by adriangb** [comment]
I'll point out that despite the test in the original issue `paritalmethod` doesn't work at all
