### ISSUE TITLE
Support Final in v2

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5359]
(This was the original tracking issue: https://github.com/pydantic/pydantic/issues/4667 but that covered other things besides `Final`, so I made a new issue.)

Currently in v2, we don't support fields annotated with `Final` like we do in v1.

Some issues with implementation:
* We don't have a way to indicate in a `FieldInfo` that a field is `Final`. (This may be easily solved by just re-adding this attribute though.)
* The process of determining `Final`-ness of a field may relate to unpacking annotations, which may be more a part of building the CoreSchema today, but `Final`-ness doesn't really seem to me to be a concern of `pydantic_core`, just `pydantic`. So I think it _may_ require a slightly different code path than we use for other attributes like this. (E.g., frozen fields, which are closely related but _are_ represented in the core schema.)
* We may need to add explicit support for final to pydantic_core if we want a different error message than the frozen-field error message if you try to assign an attribute (or validate a different value) to a Final field. This would resolve the note above about how things are a little more complicated due to lack of tracking final-ness in pydantic core, but obviously will require a more ambitious implementation effort if it requires changes to pydantic core.

**Comment by samuelcolvin** [comment]
fixed by #5366
