### ISSUE TITLE
`schema_json` does not output None as null in unions

### ISSUE THREAD

**Issue by xremming** [pydantic/pydantic#5365]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

`None`s get dropped from JSON schema when used in a union of any kind but work correctly when alone. Seems to be related to #4619 but a bit more extensive than described in just that issue. It would also be quite nice for this to be the documented behavior in 1.x if it won't/can't be fixed.

### Example Code

```Python
from typing import Optional, Union

from pydantic import BaseModel

class Foo(BaseModel):
    a0: dict[str, None]
    a1: dict[str, Optional[str]]
    a2: dict[str, Union[str, None]]
    a3: dict[str, str | None]

    b0: list[None]
    b1: list[Optional[str]]
    b2: list[Union[str, None]]
    b3: list[str | None]


print(Foo.schema_json(indent=2))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /usr/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by xremming** [comment]
It should be noted that `Literal[None]` does not work either. 😞
Could it be possible for 1.x to support `Literal[None]` as a _hack_ for this specific case?

```python
from typing import Literal, Optional, Union

from pydantic import BaseModel


class Foo(BaseModel):
    a0: dict[str, None]
    a1: dict[str, Optional[str]]
    a2: dict[str, Union[str, None]]
    a3: dict[str, str | None]
    a4: dict[str, str | Literal[None]]

    b0: list[None]
    b1: list[Optional[str]]
    b2: list[Union[str, None]]
    b3: list[str | None]
    b4: list[str | Literal[None]]


print(Foo.schema_json(indent=2))
```

**Comment by dmontagu** [comment]
I'll just note that this should be fixed in v2.

**Comment by hramezani** [comment]
As @dmontagu mentioned it fixed in V2
