### ISSUE TITLE
Add Import type

### ISSUE THREAD

**Issue by cjw296** [pydantic/pydantic#537]
# Feature Request

Would there be interest in adding an `Import` type so you could do things like:

```
class AppConfig(BaseModel):
    middleware: List[Import] = []

config = AppConfig(middlewear=['diary.api:make_session'])

...

config.make_session()
```

I have a prototype [here](https://github.com/cjw296/diary/blob/dcfe5da44bef834a9780696393fb8ca000baeb1a/backend/diary/config.py#L11-L29) and I'm happy to work it up into a PR, but thought I'd check if there was interest first.

**Comment by tiangolo** [comment]
@cjw296 Sorry I forgot to mention `PyObject` in Exotic Types: https://pydantic-docs.helpmanual.io/#exotic-types

It might help with that.

**Comment by samuelcolvin** [comment]
`PyObject` is for exactly this.

**Comment by cjw296** [comment]
@samuelcolvin - thanks, would you be up for re-opening this issue to better document `PyObject`? I mean, I looked in the exotics section and managed to totally miss it.

**Comment by samuelcolvin** [comment]
yes, totally. Might deserve it's own section.

**Comment by ybressler** [comment]
Related issue: https://github.com/pydantic/pydantic/issues/4803 (Does Github allow linking of issues?)

Also, can you assign to me? I'd like to take a stab at documenting this. @samuelcolvin

**Comment by samuelcolvin** [comment]
Thanks so much, done.

**Comment by samuelcolvin** [comment]
Just so you're aware, `PyObject` was renamed to `ImportString` on main in preparation for V2. From memory, I think it's functionality changed a bit too.

**Comment by ybressler** [comment]
Appropriately so.

**Comment by ybressler** [comment]
I have a branch with changes ready to go. Can you give me permission to push + open a PR? @samuelcolvin

**Comment by ybressler** [comment]
PR is open for this issue: https://github.com/pydantic/pydantic/pull/4893

**Comment by ybressler** [comment]
I'm not sure if `ImportString` supports colon referencing, will need to experiment with specific use case... Ex: `diary.api:make_session`
