### ISSUE TITLE
TypeError: __root__ models are no longer supported in v2; a migration guide will be added in the near future

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5387]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I've used __root__ models for different things in v1.

### Paths from v1
As an example take the definition of the "paths" 'dictionary' in OpenAPI description document, a str/path is the key, a PathItem the value.
Additional properties - keys prefixed with "x-" are allowed.

```python
class Paths(BaseModel):
    __root__: Dict[str, "PathItem"] = Field(default_factory=dict)

    _paths: object
    _extensions: object

    @property
    def paths(self):
        return self._paths
        
    @root_validator(pre=True)
    def validate_A(cls, values):
        assert set(values.keys()) - frozenset(["__root__"]) == set([])
        p = {}
        e = {}
        for k, v in values.get("__root__", {}).items():
            if k[:2] == "x-":
                e[k] = v
            else:
                p[k] = PathItem(**v)
        return {"_paths": p, "_extensions": e}
```   

### Type forwarding

```python
class RuntimeExpression(ObjectBase):
     """
     .. Runtime Expression: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/.0.3.md#runtime-expressions
     """
     __root__: str = Field(...)
```

### dynamic generated classes

The examples do not include the Config section which is used/required for the __root__ classes.

#### oneOf
[v1 code](https://github.com/commonism/aiopenapi3/blob/990438c1d80ba6e6c3d061cd88f9204be6e1cafa/aiopenapi3/model.py#L96-L109)

```python
class X(BaseModel):
    __root__ : Union[*classes]
```
#### Arrays
[v1 code](https://github.com/commonism/aiopenapi3/blob/990438c1d80ba6e6c3d061cd88f9204be6e1cafa/aiopenapi3/model.py#L242-L243)
```python
class X(BaseModel):
    __root__ : List[str]
```

#### objects with additionalProperties
[v1 code](https://github.com/commonism/aiopenapi3/blob/990438c1d80ba6e6c3d061cd88f9204be6e1cafa/aiopenapi3/model.py#L244-L265)
```python
class X(BaseModel):
  __root__ : Dict[str, class]
```

## v2?
I'm asking for the v2 way to get things done.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
@commonism Here is a test where I believe I have got it working the same as `__root__` models in v1, just the field was renamed from `__root__` to `root`: https://github.com/pydantic/pydantic/blob/2b9459f20d094a46fa3093b43c34444240f03646/tests/test_parse.py#L95-L113

You can see some other examples of root models surrounding that; note the `@root_validator`, `@model_serializer`, and `model_modify_json_schema` are exactly the same for all of them.

If there is any behavior that this approach doesn't address for you, please let us know and I'll be happy to work on providing a migration path.

**Comment by commonism** [comment]
model_serializer changes the behaviour of … something and `late init` does not work for the types:

```python
from typing import List, Dict

from pydantic import BaseModel, root_validator, model_serializer


class A(BaseModel):
    model_config = dict(undefined_types_warning=False)
    data: List["C"]


class C(BaseModel):
    model_config = dict(undefined_types_warning=False)
    root: Dict[str, "A"]

    @root_validator(pre=True)
    @classmethod
    def populate_root(cls, values):
        return {'root': values}

    @model_serializer(mode='wrap') # comment to make it work
    def _serialize(self, handler, info):
        data = handler(self)
        if info.mode == 'json':
            return data['root']
        else:
            return data

    @classmethod
    def model_modify_json_schema(cls, json_schema):
        return json_schema['properties']['root']


ns = {"A":A, "C":C}

for i in ns.values():
    i.model_rebuild(_localns=ns)
```

```
pydantic_core._pydantic_core.SchemaError: Error building `function-wrap` serializer:
  SchemaError: Duplicate ref: `__main__.C:94406663503920`
```

**Comment by samuelcolvin** [comment]
To be clear, the proper replaced for root validators is [`AnalysedType`](https://github.com/pydantic/pydantic/blob/4930970963acc5a5c7bd291b7dc258088af2299d/pydantic/analyzed_type.py#L100).

**Comment by commonism** [comment]
I've seen you mentioning AnalysedType, so far I have no idea how make it work for my use case(s).
The model_serializer workaround allowed me to get my OpenAPI description document parser working again.
For the dynamic code generation, which relied on \_\_root\_\_ heavily, I'm currently stuck.

How would you create a pydantic model from a json-schema definition?
I used to define dynamic classes via types.new_class - is there some new possibilities with pydantic_core?

**Comment by samuelcolvin** [comment]
The idea of `AnalysedType` (we might change its name if we can come up with a better name) is that it's used like this

```py
from pydantic import AnalysedType

t = AnalysedType(Union[*classes])  # doesn't have to be a Union - can be anything which we can validate
raw_validated_data = t.validate_python(input_data)
# or
raw_validated_data = t.validate_json(raw_json)

# you can then dump with 
t.dump_python(raw_validated_data)
```

Basically it gives all the same functionality as models with `__root__`, without all the overheads.

**Comment by dmontagu** [comment]
@commonism to be clear I think the error you are hitting here is not necessarily specific to root models; thank you for sharing. Very interestingly, the schema works to create a SchemaValidator, but not a SchemaSerializer. Here is the schema that produces the error for reference:
```python
    schema: {
        'type': 'model',
        'cls': <class '__main__.C'>,
        'schema': {
            'type': 'function-before',
            'function': {
                'type': 'general',
                'function': <function make_v1_generic_root_validator.<locals>._wrapper1 at 0x101561900>,
            },
            'schema': {
                'type': 'typed-dict',
                'fields': {
                    'root': {
                        'type': 'typed-dict-field',
                        'schema': {
                            'type': 'dict',
                            'keys_schema': {
                                'type': 'str',
                                'metadata': {
                                    'pydantic_js_modify_function': None,
                                },
                            },
                            'values_schema': {
                                'type': 'model',
                                'cls': <class '__main__.A'>,
                                'schema': {
                                    'type': 'typed-dict',
                                    'fields': {
                                        'data': {
                                            'type': 'typed-dict-field',
                                            'schema': {
                                                'type': 'list',
                                                'items_schema': {
                                                    'type': 'definition-ref',
                                                    'schema_ref': '__main__.C:5157077232',
                                                    'metadata': {
                                                        'pydantic_js_modify_function': None,
                                                    },
                                                },
                                                'metadata': {
                                                    'pydantic_js_modify_function': None,
                                                },
                                            },
                                            'required': True,
                                            'metadata': {
                                                'pydantic_js_modify_function': (
                                                    <function GenerateSchema._common_field_schema.<locals>.<lambda> at
                                                    0x101561a20>
                                                ),
                                            },
                                        },
                                    },
                                    'return_fields_set': True,
                                },
                                'config': {
                                    'title': 'A',
                                    'allow_inf_nan': True,
                                    'populate_by_name': False,
                                    'str_strip_whitespace': False,
                                    'str_to_lower': False,
                                    'str_to_upper': False,
                                    'strict': False,
                                    'ser_json_timedelta': 'iso8601',
                                    'ser_json_bytes': 'utf8',
                                    'from_attributes': False,
                                    'loc_by_alias': True,
                                    'revalidate_instances': 'never',
                                    'validate_default': False,
                                },
                                'ref': '__main__.A:5157069872',
                                'metadata': {
                                    'pydantic_js_modify_function': <bound method BaseModel.model_modify_json_schema of <class '__main__.A'>>,
                                },
                            },
                            'metadata': {
                                'pydantic_js_modify_function': None,
                            },
                        },
                        'required': True,
                        'metadata': {
                            'pydantic_js_modify_function': <function GenerateSchema._common_field_schema.<locals>.<lambda> at 0x101561fc0>,
                        },
                    },
                },
                'return_fields_set': True,
            },
        },
        'config': {
            'title': 'C',
            'allow_inf_nan': True,
            'populate_by_name': False,
            'str_strip_whitespace': False,
            'str_to_lower': False,
            'str_to_upper': False,
            'strict': False,
            'ser_json_timedelta': 'iso8601',
            'ser_json_bytes': 'utf8',
            'from_attributes': False,
            'loc_by_alias': True,
            'revalidate_instances': 'never',
            'validate_default': False,
        },
        'ref': '__main__.C:5157077232',
        'metadata': {
            'pydantic_js_modify_function': <bound method C.model_modify_json_schema of <class '__main__.C'>>,
        },
        'serialization': {
            'type': 'function-wrap',
            'function': {
                'type': 'general',
                'function': <function C._serialize at 0x101561870>,
            },
        },
    } (dict) len=7
```
And the error:
```
pydantic_core._pydantic_core.SchemaError: Error building `function-wrap` serializer:
  SchemaError: Duplicate ref: `__main__.C:5241343408`
```
@samuelcolvin this error doesn't seem right because there is only one ref to `__main__.C:5241343408` in the schema (though there is also a schema_ref to it), which makes me think either SchemaSerializer is somehow duplicating the schemas while initializing itself, or it's somehow considering schema_ref a duplicate. (I'll investigate a bit more.)

------

@commonism that said, any additional information about how the proposed set of tweaks doesn't behave the same for you as in v1 would be appreciated (in particular, I don't know what you meant by "model_serializer changes the behaviour of … something").

(I think we'll be able to fix the late init thing, if by that you mean the `model_rebuild` call erroring.)

**Comment by commonism** [comment]
You are right - the model_serializer property breaking model_rebuild was what I was referring to with the "late init" note.

AnalyzedType requires all types to resolve at definition time and lacks `model_rebuild(_localns) capabilities.
I think I need this.
When creating models dynamically, you do not care about ForwardRefs resolving when defining them, it would require the schema to be defined & parsed & processed in a special but unknown order. And even if the required order of processing was known, the semantics of the same model are different when used plain or as part of a discriminated union as the discriminator property is a Literal. In python/pydantic it looks all the same when defining the models directly, but when coming from schema definition the Dog models pet_type is not "Literal".
E.g. `pet: Union[Cat, Dog, Lizard] = Field(..., discriminator='pet_type')` uses different models for Dog & Cat than `animal: Dog` due to the discriminator Literal required in the model when used as part of a discriminated union. 
So - you just create them, ForwardRef everything, once you are done defining the models, iterate all of them recursively, "learn them" by name.
Next, "model_rebuild" them with the localns of all the models known.
Special care for the discriminated union classes, they need to be initialized as well - so they have the proper Literals.

I propose TypedModel for AnalyzedType.

**Comment by Jerry-Ma** [comment]
> The idea of `AnalysedType` (we might change its name if we can come up with a better name) is that it's used like this
> 
> ```python
> from pydantic import AnalysedType
> 
> t = AnalysedType(Union[*classes])  # doesn't have to be a Union - can be anything which we can validate
> raw_validated_data = t.validate_python(input_data)
> # or
> raw_validated_data = t.validate_json(raw_json)
> 
> # you can then dump with 
> t.dump_python(raw_validated_data)
> ```
> 
> Basically it gives all the same functionality as models with `__root__`, without all the overheads.

Hi,
I am also struggling to understand how to use `AnalyzedType` to replace the ``__root__`` models that I used to have in v1. Those models are used as submodels and carry their own custom methods. Here is what I have in V1 and my attempts to convert it to V2:

```python
from pathlib import Path
from typing import ClassVar

from pydantic import AnalyzedType
from pydantic import BaseModel as _BaseModel
from pydantic import ConfigDict, Field


class BaseModel(_BaseModel):
    model_config = ConfigDict(validate_default=True, frozen=True)


class Nested(BaseModel):
    path0: Path = Field(default="a")


# V1:


# class Nested1(BaseModel):
#     __root__: list[Nested]
#
#     def __iter__(self):
#         return iter(self.__root__)
#
#     def __getitem__(self, item):
#         return self.__root__[item]
#
#     def do_something(self):
#         for item in self:
#             print(item)
#
# V2:
class Nested1(BaseModel):
    """
    * Should this subclass BaseModel at all?

    * What to do here to set the validation of this model to use
    AnalyzedType[list[Nested]]?

    """

    _validate_list_of_nested: ClassVar = AnalyzedType(list[Nested])

    # how to expose the list API and any custom API?
    # def __iter__(self):
    #     return iter(self.__root__)
    #
    # def __getitem__(self, item):
    #     return self.__root__[item]
    #
    # def do_something(self):
    #     for item in self:
    #         print(item)


class Nested2(BaseModel):
    # this does not work because it expect input to be dict type
    # nested: Nested1

    # this works but it skips the Nested1 model, where we want to
    # have custom methods like `do_something`.
    nested: list[Nested]


def test_nested():
    # Nested2.update_forward_refs(Nested1=Nested1, Nested=Nested)
    m = Nested2.model_validate({"nested": [{}]})

    # print(f"m.model_json_schema:\n{json.dumps(m.model_json_schema(), indent=2)}")
    print(f"m:\n{m}")
    print(f"m.model_dump:\n{m.model_dump_json(indent=2)}")

    # usage
    assert m.nested[0].path0
    assert m.nested[0].path0 == Path("a")

    assert hasattr(m.nested, "do_somehting")


test_nested()

```

Any help would be highly appreciated!

**Comment by Jerry-Ma** [comment]
@commonism thanks for the insights. I was able to use the custom `model_validator` and `model_serializer` to mimic the behaviour of `__root__`. I guess my main question is to the comment on AnalyzedTypes by @samuelcolvin , which sounds like I should use AnalyzedTypes to achieve this.

In any case, `model_validator` works great for me.

**Comment by dmontagu** [comment]
@Jerry-Ma please take a look at #5498 (or anyone else following this issue) and let us know if you have any requests about the API for RootModel.

**Comment by Kludex** [comment]
I'll close this, since on V2 we have [`RootModel`](https://docs.pydantic.dev/latest/usage/models/#rootmodel-and-custom-root-types). 🙏
