### ISSUE TITLE
mypy stuck with pydantic v2

### ISSUE THREAD

**Issue by luolingchun** [pydantic/pydantic#5391]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

mypy stuck with pydantic v2.

```
mypy test_pydantic.py
```

Will mypy still be supported in the future?

### Example Code

```Python
from pydantic import BaseModel


class Test(BaseModel):
    a: int
    b: str


print(Test(a=1, b="string"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
install path: D:\workspace\test\venv\Lib\site-packages\pydantic
python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
platform: Windows-10-10.0.22621-SP0
optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
It’s very slow when analyzing pydantic core. @samuelcolvin @adriangb I can’t remember did we have an idea of how to put something in place so it wasn’t slow by default? (I’m assuming we didn’t do this yet)

**Comment by samuelcolvin** [comment]
Ye mypy is still supported, but it has know performance issues, you need to always run with `--disable-recursive-aliases`.

You can get further performance improvements by adding the following to you config:

https://github.com/pydantic/pydantic/blob/0cd57b3e0c75d9622012de542e5ddc110fe55743/.mypy-configs/fast.toml#L32-L34

You can remove the "devtools" bit, it's pydantic-core that's killing the performance.
