### ISSUE TITLE
{'type': 'null'} should be {'type': None} in model_json_schema

### ISSUE THREAD

**Issue by luolingchun** [pydantic/pydantic#5394]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

There seems to be a small error in the `model_json_schema` result.

{'type': 'null'} should be {'type': None}

It influenced the construction of [`Schema`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object) in `OpenAPI`.

### Example Code

```Python
from typing import Optional

from pydantic import BaseModel


class MyModel(BaseModel):
    x: str

    type: Optional[str] = None


_json = MyModel.model_json_schema()

print(type(_json))
# <class 'dict'>
print(_json)
# {'title': 'MyModel', 'type': 'object', 'properties': {'x': {'type': 'string', 'title': 'X'}, 'type': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Type'}}, 'required': ['x']}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
install path: D:\workspace\test\venv\Lib\site-packages\pydantic
python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
platform: Windows-10-10.0.22621-SP0
optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
I'm not so sure about this. I'm finding some evidence saying that OpenAPI 3.1, which should be fully compatible with JSON schema draft 2020-12 (which is what we are using), wants the `'type'` field to have the string literal value `'null'`. I'm looking for a clearer source on this though.

**Comment by dmontagu** [comment]
Okay, as far as I can tell, `"null"` should appear as a string when it is in the type field. So I think our current implementation is correct, at least for OpenAPI 3.1. @luolingchun I realize you linked to OpenAPI 3.0 docs, but I would prefer to be compliant with OpenAPI 3.1 if possible over 3.0 given its newer but still multiple years old. (And follows JSON schema 2020-12, which we have also decided as the version with which we will comply)

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#data-types
> Data types in the OAS are based on the types supported by the [JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.2.1). Note that integer as a type is also supported and is defined as a JSON number without a fraction or exponent part. Models are defined using the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schemaObject), which is a superset of JSON Schema Specification Draft 2020-12.

https://json-schema.org/draft/2020-12/json-schema-core.html#name-assertions-and-instance-pri
> ```
> {
>     "type": ["string", "null"],
>     "maxLength": 255
> }
> ```

https://json-schema.org/understanding-json-schema/reference/null.html#null
> { "type": "null" }

**Comment by dmontagu** [comment]
Given this, I'm going to close this issue, but can re-open if there is still debate about what we should do.
