### ISSUE TITLE
`GenerateJsonSchema` should take `config` and use it for at least title

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5395]
if you set title via `config` on a dataclass or `valdiate_call`, it should be respected in the JSON schema.

@dmontagu we can discuss later.

**Comment by dmontagu** [comment]
I am in favor of better support for this, and we can definitely do it for pydantic dataclasses today by reading the value off of `__pydantic_config__`, but I think this would require some bigger changes to AnalyzedType or similar. I'll work on a PR that at least uses the config title for dataclasses

**Comment by dmontagu** [comment]
Okay, looks like this is already working for dataclasses:
```python
from pydantic.dataclasses import dataclass
from pydantic import AnalyzedType


@dataclass(config={'title': 'abc'})
class Data:
    x: int


print(AnalyzedType(Data).json_schema())
#> {'type': 'object', 'properties': {'x': {'type': 'integer', 'title': 'X'}}, 'required': ['x'], 'title': 'abc'}
```

Will be happy to discuss what you have in mind for validate call / other ways GenerateJsonSchema might receive a config.
