### ISSUE TITLE
Importing pydantic._hypothesis_plugin creates .hypothesis directory

### ISSUE THREAD

**Issue by kerrick-js** [pydantic/pydantic#5400]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When you import `pydantic._hypothesis_plugin`, it creates the directory `.hypothesis` in the CWD. I think this is not good behavior; a module should never have side effects from just importing it.

### Example Code

```Python
venv=$(mktemp -u)
python3 -m virtualenv $venv
cd $venv
. $venv/bin/activate
pip install hypothesis==6.70.2 pydantic==1.10.7
python -c 'import pydantic._hypothesis_plugin'
ls .hypothesis
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /tmp/tmp.6fikc9J0aI/lib64/python3.8/site-packages/pydantic
               python version: 3.8.13 (default, Nov  8 2022, 17:19:05)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
                     platform: Linux-4.18.0-425.13.1.el8_7.jane1.x86_64-x86_64-with-glibc2.2.5
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
