### ISSUE TITLE
Inconsistent behavior in root validator + nested model + default value

### ISSUE THREAD

**Issue by zduvall** [pydantic/pydantic#5414]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I'm getting inconsistent behavior in a `root_validator` when used in conjunction with a nested model and default value. Sometimes the value shows up just a dictionary and sometimes as the instantiated nested `BaseModel` class.

If I don't pass a value for `field`, the default value is given to the root validator as just a plain dictionary. If I do pass a value for `field`, that value becomes the instantiated nested model by the time it gets to the `root_validator`. This leads to extra work inside the validator when the value can be multiple types.

See the printed `type(values['field'])` in the provided example.

Is this desired behavior?

### Example Code

```Python
from pydantic import BaseModel, root_validator

class NestedModel(BaseModel):
    val: int

class ParentModel(BaseModel):
    field: NestedModel = {'val': 1}

    @root_validator
    def print_type_of_field(cls, values):
        print(' ', type(values['field']))
        return values

print('\nParentModel()')
ParentModel()

print('\nParentModel.parse_obj({})')
ParentModel.parse_obj({})

print("\nParentModel(field={'val': 1})")
ParentModel(field={'val': 1})

print("\nParentModel.parse_obj({'field': {'val': 1}})")
ParentModel.parse_obj({'field': {'val': 1}})

# Output:
#
# ParentModel()
#   <class 'dict'>
# 
# ParentModel.parse_obj({})
#   <class 'dict'>
# 
# ParentModel(field={'val': 1})
#   <class '__main__.NestedModel'>
# 
# ParentModel.parse_obj({'field': {'val': 1}})
#   <class '__main__.NestedModel'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
pydantic compiled: True
install path: /Users/me/Desktop/test/.venv/lib/python3.10/site-packages/pydantic
python version: 3.10.8 (main, Nov 19 2022, 20:34:03) [Clang 14.0.0 (clang-1400.0.29.102)]
platform: macOS-13.2.1-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
Given we are treating v1 as in maintenance mode now, and I think any changes to this behavior are likely to break _someone's_ code, I think it doesn't make sense to change this behavior of `@root_validator` in pydantic v1 even if there might be some benefits in principle.

And since `@root_validator` is deprecated in v2 I will close this issue. That said, if you run into similar issues with `@model_validator` or `RootModel` in v2, I'll be happy to discuss more.
