### ISSUE TITLE
smart_union doesn't work with union of lists

### ISSUE THREAD

**Issue by rajeee** [pydantic/pydantic#5419]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

While smart_union helps resolve some unions, looks like a simple union of two lists is not parsed correctly.

### Example Code

```Python
from pydantic import BaseModel

class MyModel(BaseModel):
    val: list[str] | list[int]
    val2: str | int

    class Config:
        smart_union = True

m = MyModel(val=[1, 2, 3], val2=1)
print(m)
# val=['1', '2', '3'] val2=1
# val should have been [1, 2, 3]
# val2 is correct.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
pydantic compiled: True
install path: /Users/<username>/mambaforge/envs/buildstock_query/lib/python3.10/site-packages/pydantic
python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]
platform: macOS-12.6-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Interesting, does it work correctly with `2.0a1`?

**Comment by PrettyWood** [comment]
It's not a really a bug since it's explained in the documentation.

![Screenshot_2023-04-09-09-27-56-52_e4424258c8b8649f6e67d283a50a2cbc~2](https://user-images.githubusercontent.com/18406791/230760137-95b6712f-819c-4c79-b471-821a10841150.jpg)

Compound types are not handled properly in v1 in a lot of situations. But I believe v2 tackles this problem

**Comment by samuelcolvin** [comment]
Thanks @PrettyWood.

**Comment by rajeee** [comment]
Oops, I apologize. I thought I was being careful with reading the docs - somehow the dedicated section escaped me. 
And I can verify that this is resolved correctly in 2.0a1.

(Though float | int resoultion in 2.0a1 seems to still follow the whoever comes first resolution - but that's a separate issue)

**Comment by samuelcolvin** [comment]
> (Though float | int resoultion in 2.0a1 seems to still follow the whoever comes first resolution - but that's a separate issue)

It shouldn't, can you give an example?

**Comment by rajeee** [comment]
@samuelcolvin Here: https://github.com/pydantic/pydantic/issues/5422
