### ISSUE TITLE
Migration path for BaseSettings?

### ISSUE THREAD

**Issue by filipallberg** [pydantic/pydantic#5421]
Just a comment to consider:

With the v2 pre-release I wouldn't have minded a pre-release of `pydantic-settings` even if that had just been `BaseSettings` as-is alone.

Would've loved to test and use the pre-release on a project but sadly it also uses `BaseSettings` and as far as I can tell there is no decent way of depending on two versions of the same library.

**Comment by dmontagu** [comment]
@filipallberg we are working on getting `pydantic-settings` released, which will move `BaseSettings` into a different package. I'll let you know here once that is ready, which should allow you to use `BaseSettings` in v2.

**Comment by hramezani** [comment]
@filipallberg `pydantic-settings` is in alpha state and you can install it by `pip install pydantic-settings --pre`
Also, you can find updated documentation of `pydantic-settings` in https://github.com/pydantic/pydantic-settings/blob/main/docs/index.md
