### ISSUE TITLE
Float and Int resolution follows "whatever declared first"

### ISSUE THREAD

**Issue by rajeee** [pydantic/pydantic#5422]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When a type is defined as union of int and float,  int gets converted to float if float comes first in the union. This works properly in pydantic==1.10.7 with smart_union.

### Example Code

```Python
from pydantic import BaseModel

class MyModel(BaseModel):
    val1: int | float
    val2: float | int

m1 = MyModel(val1=1, val2=1)
m2 = MyModel(val1=1.0, val2=1.0)

print(m1)
print(m2)

# Output
# val1=1 val2=1.0  # val2 should have been int.
# val1=1.0 val2=1.0
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
install path: C:\Users\rajen\anaconda3\envs\pydantic\Lib\site-packages\pydantic
python version: 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19044-SP0
optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
Thanks for reporting, see https://github.com/pydantic/pydantic-core/pull/536 for a fix.

**Comment by rajeee** [comment]
Is it possible to resolve https://github.com/pydantic/pydantic/issues/5422 without preventing floats from accepting ints?
