### ISSUE TITLE
With `extra='allow'` and `from_attributes=True`, which attributes should be accessed when validating instances?

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5434]
Currently in `pydantic_core`, when `extra='allow'` and `from_attributes=True` in the model config, if you pass an `obj` into `.model_validate(obj)` it will attempt to access every attribute in `dir(obj)` and pass that as an attribute.

After some discussion, Adrian and I felt that we should only attempt to grab the attributes that correspond to fields, even with `extra='allow'`, rather than attempting to grab every field in `dir(obj)`.

We're planning to make this change, but wanted to create a tracking issue to described why this was the case (and give people a place to raise objections if they don't like this).

**Comment by samuelcolvin** [comment]
@tiangolo @vitalik @ormar @roman-right @art049 as maintainers of ORMs or similar built on pydantic - and therefore users of `from_orm` (now called `from_attributes`), do any of you have strong opinions on this?

Please reply asap if you don't want us to make this change.

More generally, if you have any feedback on pydantic V2 alphas, or wishes, please let us know - probably best via a new feature request issue.

**Comment by dmontagu** [comment]
> `from_orm` (now called `from_attributes`)

Just to be a bit more explicit here, I think we have dropped `.from_orm(...)` and replaced with use of `.model_validate(...)` (analogous to `.parse_obj(...)` in v1). The config setting `orm_mode` was renamed to `from_attributes`.

**Comment by tiangolo** [comment]
I don't have strong opinions about this, I think the proposed change is fine and makes sense. Thanks for pinging me (also on DM)!

**Comment by art049** [comment]
I don't have strong opinions either. It shouldn't create big problems on my side.

**Comment by roman-right** [comment]
This sounds reasonable. It will not make any problems for my project.

**Comment by dmontagu** [comment]
This is now implemented
