### ISSUE TITLE
OpenAPI Schema Generation is Broken for Nested Discriminated Unions

### ISSUE THREAD

**Issue by michaeligreenberg** [pydantic/pydantic#5436]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

OpenAPI schema generation for [nested discriminated unions](https://docs.pydantic.dev/usage/types/#nested-discriminated-unions) appears to be broken with Pydantic 1.x. As far as I can tell, the issue stems from the assumption that the discriminator will be a flat mapping of field name to schema name.

### Example Code

```Python
from enum import Enum
from typing import Literal, Union

from typing_extensions import Annotated

from pydantic import BaseModel, Field, ValidationError

class PetType(str, Enum):
    CAT = "cat"
    DOG = "dog"

class Color(str, Enum):
    WHITE = "white"
    BLACK = "black"

class BasePet(BaseModel):
    pet_type: PetType

class BaseCat(BasePet):
    pet_type: Literal[PetType.CAT]
    color: Color


class BlackCat(BaseCat):
    color: Literal[Color.BLACK]
    black_name: str


class WhiteCat(BaseCat):
    color: Literal[Color.WHITE]
    white_name: str


Cat = Annotated[Union[BlackCat, WhiteCat], Field(discriminator='color')]

class Dog(BasePet):
    pet_type: Literal[PetType.DOG]
    barks: float

Pet = Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]

class Model(BaseModel):
    pet: Pet
    n: int

print(Model.schema()['properties']['pet']['discriminator'])

"""
>>> {'propertyName': 'pet_type', 'mapping': {'cat': {'BlackCat': {'$ref': '#/definitions/BlackCat'}, 'WhiteCat': {'$ref': '#/definitions/WhiteCat'}}, 'dog': '#/definitions/Dog'}}

pydantic/main.py raises a validation_error when I ask for FastAPI to generate OpenAPI schema for these models:
pydantic.error_wrappers.ValidationError: 2 validation errors for OpenAPI
components -> schemas -> Model -> properties -> pet -> discriminator -> mapping -> cat
  str type expected (type=type_error.str)
components -> schemas -> Model -> $ref
  field required (type=value_error.missing)
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
       pydantic compiled: False
            install path: /usr/local/lib/python3.8/dist-packages/pydantic
          python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
                platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.29
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by michaeligreenberg** [comment]
My apologies, I had too many examples open and copied the wrong snippet. You're correct that the example nested discriminated union should be
`Pet = Annotated[Union[Cat, Dog], Field(discriminator='pet_type')]`
I'm going to update the issue's example.

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
