### ISSUE TITLE
`AnalyzedType.validate_python` for a TypedDict ignores `extra` config option

### ISSUE THREAD

**Issue by raman325** [pydantic/pydantic#5448]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Can't tell whether this is by designed or a bug, but to me it seems to be a bug based on my understanding of what the `extra` config option does. See the following example code and output. This happens even when I set `strict` to `False`. Is this by design?

### Example Code

```Python
"""Example of error."""
from typing import Literal, TypedDict

from pydantic import AnalyzedType, BaseModel, Extra


class EventData(TypedDict):
    """Event data."""

    name: str


class BaseEventModel(BaseModel):
    """Base model for an event."""

    class Config:
        """Config for BaseEventModel."""

        extra = Extra.ignore  # should be unnecessary since ignore is the default

    source: Literal["controller", "driver", "node"]
    event: EventData


AnalyzedType(BaseEventModel).validate_python(
    {"source": "controller", "event": {"name": "example", "extra": "extra"}}
)
```

### Output
```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    AnalyzedType(BaseEventModel).validate_python(
  File "venv/lib/python3.11/site-packages/pydantic/analyzed_type.py", line 151, in validate_python
    return self.validator.validate_python(__object, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for BaseEventModel
event.extra
  Extra inputs are not permitted [type=extra_forbidden, input_value='extra', input_type=str]
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.0a1
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Feb 16 2023, 02:51:42) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.6.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by dmontagu** [comment]
@raman325 yes xfail means we have a test for it that we know is failing; our goal is to make changes/fixes to the code to make it so that all xfail tests eventually pass.

That said, reporting issues like this will still draw our attention to them and help us prioritize what to fix first, so please do continue to report things that cause problems for you even if you find existing xfail tests for the functionality you want/need.

**Comment by adriangb** [comment]
`extra` does not propagate into fields, so setting `extra` on `BaseEventModel` will not impact `EventData`. In fact we do not currently support `extra` on TypedDict at all. I opened a feature request for that: 5584

**Comment by raman325** [comment]
thanks @adriangb so just to be clear, that feature request will add support for `extra` on `TypedDict`, but will it then work as I expect in the example above or will that still not work because `extra` will still not propagate into fields?

**Comment by adriangb** [comment]
You'll be able to (have to) do something like:

```python
from typing import Literal, TypedDict

from pydantic import ConfigDict

class EventData(TypedDict):
   model_config = ConfigDict(extra='allow')
```
