### ISSUE TITLE
AnalyzedType is not re-useable

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5454]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

AnalyzedType can not be used as field type for BaseModel properties:
`Unable to generate pydantic-core schema for <pydantic.analyzed_type.AnalyzedType object at 0x7fc012fa3c10>. Setting ``arbitrary_types_allowed=True`` in the model_config may prevent this error.`

or serve as type for AnalyzedType.
`Parameters to generic types must be types. Got <pydantic.analyzed_type.AnalyzedType object at 0x7fc012fa3c10>.`

This is a limitation which did not exist for \_\_root\_\_ models.

### Example Code

```Python
from typing import Union, List
import json

from pydantic import AnalyzedType, BaseModel

class A(BaseModel):
    data: str

class B(BaseModel):
    file: bytes

classes = tuple([A,B])

T = Union[classes]
t = AnalyzedType(T)

try:
    class D(BaseModel):
        data: t
except Exception as e:
    print(e)

try:
    l = AnalyzedType(List[t])
except Exception as e:
    print(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a1
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
I don't think `AnalyzedType` is meant to be used in this way; `AnalyzedType` is just meant to provide validation, serialization, JSON schema, etc. functionality for a type that isn't a BaseModel.

If you want to have generic behavior with a root field and/or use a root model as a field, as of now you'll need to use a BaseModel, and should be able to replicate the functionality of root models using `@root_validator`, `@model_serializer`, and `__pydantic_modify_json_schema__`, following the pattern I suggested in the migration guide / docs. (If there are still usage patterns that pattern can't be used to support, please let us know. We are planning to do an updated release today, hopefully in the next hour or so, that should address most/(hopefully?) all of the bugs you have reported with that approach so far.)

That said, to address this and other uses of `__root__` models, I think we are tentatively planning to add a class called something like `RootModel` which would be closely related to BaseModel but handle the boilerplate of defining those methods and have slightly different method signatures (e.g., `model_dump` will not be annotated as returning a `dict[str, Any]`).

**Comment by commonism** [comment]
I think `RootModel` is the way to go - best even using __root__ for it.
