### ISSUE TITLE
v2 performance numbers for processing the redfish openapi specification

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5466]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Using aiopenapi3/pydantic to parse/process DMTF-DSP8010/2022.2/openapi.yaml I see a 2x speedup:
v1: …  0:01:20.894002 (processing time)
v2: …  0:00:38.767936 (processing time)
**This is wrong, I messed up the numbers, they are swapped, v1 is faster**

Tracking things down using cProfile things get complicated.
The timings change a lot and v1 gets faster (~400s vs ~800s), making it difficult to compare. (**actually they make sense now**)

I noticed:
.parse_obj got faster (~x4)
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      404    0.005    0.000    5.646    0.014 /tmp/v2/aiopenapi3/openapi.py:157(_parse_obj)
vs
      404    0.005    0.000   27.622    0.068 /tmp/v1/aiopenapi3/openapi.py:157(_parse_obj)
```

types.new_class(BaseModel) has some slowdown 
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     4221    0.040    0.000   42.528    0.010 /tmp/v2/usr/lib/python3.10/types.py:69(new_class)
vs
     4221    0.043    0.000   26.451    0.006 /tmp/v1/usr/lib/python3.10/types.py:69(new_class)
```

the majority of the extra time time is spent in v2:model_rebuild when compared to v1:update_forward_refs
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.499    0.499  462.013  462.013 /tmp/v2/aiopenapi3/openapi.py:398(_init_schema_types)
     4221    0.224    0.000  403.314    0.096 /tmp/v2/openapi3/lib/python3.10/site-packages/pydantic/main.py:431(model_rebuild)
vs
        1    3.026    3.026   41.833   41.833 /tmp/v1/aiopenapi3/openapi.py:398(_init_schema_types)
     4221    0.031    0.000    2.318    0.001 /tmp/v1/pydantic/main.py:810(update_forward_refs)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a2
        pydantic-core version: 0.23.1 release build profile
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by samuelcolvin** [comment]
can you share your code and input?

**Comment by dmontagu** [comment]
@commonism if there is any way you could produce a flamegraph it might help us understand what is being slow about model_rebuild. Also, as Samuel noted, it would probably be helpful to see more of the code involved.

It doesn't surprise me that it is currently slower to build 4200 models, but certainly we'd like it to be less than 10x slower than v1. @samuelcolvin I'm thinking maybe this has something to do with the reduced caching of the core schema that came with the use of `__get_pydantic_core_schema__`, not totally sure.

**Comment by samuelcolvin** [comment]
yup, I'm sure reduced caching is a big part of it.

**Comment by commonism** [comment]
Let's start with a flamegraph.

![v2-redfish](https://user-images.githubusercontent.com/164513/231857159-5ef08ae4-905a-4f72-9f5e-806994cf727e.svg)


I'll update this with instructions to reproduce tomorrow.

**Comment by commonism** [comment]
To reproduce:

```
cd /tmp
python3 -m venv /tmp/rf
/tmp/rf/bin/pip install pydantic==v2.0.a2
git clone https://github.com/commonism/aiopenapi3.git
cd aiopenapi3
git checkout pydanticv2
/tmp/rf/bin/pip install -e .

mkdir /tmp/dd
cd /tmp/dd
wget https://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2022.2.zip
unzip DSP8010_2022.2.zip

cd /tmp

cat <<EOF>>help.py
import yaml

import pydantic

from aiopenapi3.plugin import Document

class RedfishDocument(Document):
    def __init__(self, url):
        self._url = url
        super().__init__()

    def loaded(self, ctx):
        return ctx

    def parsed(self, ctx):
        base = yaml.safe_load(
            f"""
            openapi: 3.0.1

            info:
              description: This contains the definition of a Redfish service.
              title: Redfish for '{ctx.url}'
              version: '2022.1'

            paths: {{}}
            """
        )
        base.update(ctx.document)
        ctx.document = base

        if str(ctx.url) == self._url:
            """
            this is the openapi.yaml description document with the PathItems
            """
            root = yaml.safe_load(
                """
                servers:
                    - url: /

                security:
                  - basicAuth: []
                """
            )

            root.update(ctx.document)
            root["components"].update(
                yaml.safe_load(
                    """
                securitySchemes:
                  basicAuth:
                    type: http
                    scheme: basic
                """
                )
            )

            ctx.document = root

        if "title" in ctx.document:
            del ctx.document["title"]

EOF

/tmp/rf/bin/aiopenapi3 --profile --profile-file /tmp/v2-redfish.prof -P /tmp/help.py:RedfishDocument -L /tmp/dd/openapi/ validate /tmp/dd/openapi/openapi.yaml

/tmp/rf/bin/pip install flameprof
/tmp/rf/bin/python -m flameprof /tmp/v2-redfish.prof > v2-redfish.svg
```

**Comment by samuelcolvin** [comment]
can you point me to where the pydantic models are defined?

**Comment by commonism** [comment]
I continued using v2 and noticed my initial numbers were swapped - v2 is slower.
This matches the profiling runs data.
I updated the script (…more than once…) to reproduce to include v1 numbers .

In another test where I got times to compare v2 does not perform better as well:

| test | v1 | v2 |
|:---:|:---:|:---:|
|parsing only| 15.878s | 14.454705 |
|all|  27,154s  |  72,176s |

**Comment by commonism** [comment]
> can you point me to where the pydantic models are defined?

the statics are here - basically in the v20/30/31 subdirs - eg:
https://github.com/commonism/aiopenapi3/blob/pydanticv2/aiopenapi3/v31/schemas.py

the dynamics come from here:
https://github.com/commonism/aiopenapi3/blob/pydanticv2/aiopenapi3/model.py#L148
and some late init around here
https://github.com/commonism/aiopenapi3/blob/pydanticv2/aiopenapi3/openapi.py#L398

**Comment by samuelcolvin** [comment]
I tried your code, and I get an error about root models.

A quick search shows a fair bit of usage of `__root__` models. I think we should wait to profile more until we have `RootModel` working.

**Comment by commonism** [comment]
I messed up the script to reproduce multiple times.
Give it a clean go, the (manual) last line in the script cleans up and will create fresh run.

It is not supposed to error.

I solved \_\_root\_\_ already via https://github.com/commonism/aiopenapi3/blob/24390e485da995f28523273b235e3b1431993f2d/aiopenapi3/pydanticv2.py#L42-L60

**Comment by dmontagu** [comment]
@commonism I'd be interested to hear what the runtime is now. I fear it may have gotten even longer now.. either way would be good to know where things stand.

When I run your script above locally (with pydantic v2.0b3 instead of the 2.0a2 or whatever is there) I get ~38s for the first two runs and ~60s for the last one during/after(?) the flameprof thing, but hard to say how much of that is explained by the hardware.

**Comment by dmontagu** [comment]
I'm also going to remove the "v2 bug" label as I'm trying to clean those up, but that's not to say that I don't think it's worth improvements on this if anyone can find places for them.

**Comment by commonism** [comment]
42s vs 74s for me, but let's consider this benchmark flawed, it does not really measure something which is a performance target.

I have an archive of YAML formatted RedFish data to benchmark with.
Currently the overhead of everything else outscales the pydantic times by a large margin. 
The actual data processing of v2 has gotten too fast for the measurements I used,  to proceed I need to change the way I gather the perf numbers.
I will get there, I will update this.

**Comment by commonism** [comment]
It's impressive.

```
   Ordered by: cumulative time

v1
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     2732    0.023    0.000    4.973    0.002 ~/venv/pydanticv1/lib/python3.10/site-packages/pydantic/main.py:517(parse_obj)

v2
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     2732    0.010    0.000    0.315    0.000 ~/workspace/pydantic/pydantic/main.py:225(model_validate)
```     

```
>>> 4.973/0.315
15.787301587301586
```

x15 confirmed.

#### v1
![v1-tin](https://github.com/pydantic/pydantic/assets/164513/6d0b4f67-123c-4f92-b9b7-49a1346347f6)

#### v2
![v2-tin](https://github.com/pydantic/pydantic/assets/164513/6314eb55-dab1-4fa2-8015-aad4959e7d8a)
