### ISSUE TITLE
Optional fields are required by default

### ISSUE THREAD

**Issue by oefe** [pydantic/pydantic#5481]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

In Pydantic v1, optional fields (i.e. fields of type `[Optional[some type]]` resp. `some type | None`) are optional (i.e. not required) unless they explicitly specify  `...` as default.

(Sorry about the two different meanings of optional in the same sentence.)

See [Required Optional Fields](https://docs.pydantic.dev/usage/models/#required-optional-fields) in the Pydantic v1 documentation.

In Pydantic v2, these fields are now required. To make them optional, one explicitly needs to specify `None` as default.

Maybe this is intentional, but I haven't seen this mentioned in the migration docs so far.

### Example Code

```Python
from pydantic import BaseModel


class Foo(BaseModel):
    name: str | None


Foo.model_validate(
    {},
    strict=False
)

# pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
name
#  Field required [type=missing, input_value={}, input_type=dict]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a2
        pydantic-core version: 0.23.1 release build profile
                 install path: /Users/moefelei/Repos/pydantic-sandbox/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by PrettyWood** [comment]
Hello @oefe 
It is indeed intentional. Pydantic v2 differentiates properly non required and nullable fields (see [Samuel's message](https://docs.pydantic.dev/blog/pydantic-v2/#required-vs-nullable-cleanup))
If that's not yet in the migration plan, it should be added

**Comment by samuelcolvin** [comment]
Thanks so much @PrettyWood, that's correct.

**Comment by oefe** [comment]
Makes sense. I think this is much more obvious, at least when using Python 3.10 `| None` syntax.

I didn't find it in mentioned in [migration.md](https://github.com/pydantic/pydantic/blob/main/docs/migration.md) or
[migration section of the alpha announcement](https://docs.pydantic.dev/blog/pydantic-v2-alpha/#migration-guide)
