### ISSUE TITLE
Create pydantic.PostgresDsn() needs None as first positional argument

### ISSUE THREAD

**Issue by jankatins** [pydantic/pydantic#5484]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I really like the PostgresDsn type and wanted to use it as typing info (instead of str) in function signatures (also saves me to reparse the URLs). During testing I want to create `PostgresDsn` types and they have a very strange constructor/`__new__`: 

I assumed that I could create them like I can usually use `PostgresDsn.build(...)` in validators, but `PostgresDsn(...)` errors with `TypeError: __new__() takes exactly 2 positional arguments (1 given)`. I can make it work if I add a `None`:  `PostgresDsn(None, ...)` (see example below). I wonder if there are nicer ways to create them directly. Without it:

```
    db_dsn = pydantic.PostgresDsn(
pydantic/networks.py:184: in pydantic.networks.AnyUrl.__new__
    ???
E   TypeError: __new__() takes exactly 2 positional arguments (1 given)
```

### Example Code

```Python
import pydantic
db_dsn = pydantic.PostgresDsn(
        # Without None: TypeError: __new__() takes exactly 2 positional arguments (1 given)
        # With: all is fine
        # None,
        scheme="postgresql",
        user="user",
        password="pw",
        host="localhost",
        path="/dbname",
        port="5432",
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /Users/jankatins/Library/Caches/pypoetry/virtualenvs/abc-service-JeB-l5pZ-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by adriangb** [comment]
We don't support building urls via keyword arguments in v2, you pass in the string directly. So I guess this is resolved via not supporting it anymore. We won't be fixing this in v1.
