### ISSUE TITLE
Should calls to pydantic dataclasses with invalid signature raise a ValidationError or TypeError?

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5487]
I noticed that now, instead of raising a `TypeError` when you call dataclasses with an invalid signature, we raise a `ValidationError`.

Are we happy with this? In v1 it raises a `TypeError`:

```python
import pydantic

@pydantic.dataclasses.dataclass
class X:
    x: int

X()

# V1 error:
# TypeError: X.__init__() missing 1 required positional argument: 'x'

# V2 error:
# pydantic_core._pydantic_core.ValidationError: 1 validation error for X
# x
#   Field required [type=missing, input_value=ArgsKwargs(()), input_type=ArgsKwargs]
```

**Comment by samuelcolvin** [comment]
I think it's much better now.

**Comment by dmontagu** [comment]
Main downside is the risk that someone had set up error handling for invalid calls. But I'm fine with this if you are. Feel free to just close the issue.

**Comment by adriangb** [comment]
@samuelcolvin any reason we can't do something like:

```python
from typing import Any

from pydantic import ValidationError


class ValidationTypeError(ValidationError):
    pass


def func(*args: Any, **kwargs: Any) -> Any:
    # some validation is happening
    if len(args) < 2:
        raise ValidationTypeError(
            'not enough args',
            errors=[],
        )

try:
    func(1)
except TypeError:
    print('okay')


try:
    func(1)
except ValidationError:
    print('okay')
```

**Comment by adriangb** [comment]
Since `ValidationError` currently inherits form `ValueError` it might be tricky (as in, require several macros) to make this work in Rust. It's doable but I'm not going to implement it unless we need / really want to.
