### ISSUE TITLE
Should setting `...` as the default make a dataclasses field required?

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5488]
In V1 dataclasses, setting a field default of `...` does not make the field required, but makes that the actual default value. This is the same behavior as standard dataclasses.

In V2 dataclasses, it makes the field required. Is this how it should work?

Standard + V1 behavior:
```python
from typing import Any
import dataclasses

import pydantic


@pydantic.dataclasses.dataclass
class PydanticDataclass:
    v: Any = ...


print(PydanticDataclass().v)
# > Ellipsis


@dataclasses.dataclass
class StandardDataclass:
    v: Any = ...


print(StandardDataclass().v)
# > Ellipsis
```
V2 behavior:
```python
from typing import Any

import pydantic


@pydantic.dataclasses.dataclass
class PydanticDataclass:
    v: Any = ...


print(PydanticDataclass().v)

#> pydantic_core._pydantic_core.ValidationError: 1 validation error for PydanticDataclass
#> v
#>   Field required [type=missing, input_value=ArgsKwargs(()), input_type=ArgsKwargs]
```

**Comment by samuelcolvin** [comment]
I'm kind of neutral.

Would be nice for BaseModel and dataclass to have the same behaviour.

Would be nice for a pydantic dataclass to match a vanilla dataclass.

Would be nice for v1 and V2 to have the same behaviour.

Choose two.

I guess we choose 2 and 3?

**Comment by adriangb** [comment]
Do we do the `...` doesn't count as a default value because of `foo: str = Field(...)`?

**Comment by samuelcolvin** [comment]
When I first started pydantic I didn't know about annotation only fields, so I chose ellipsis as meaning required. It's stuck until now.

Happy to change.

**Comment by adriangb** [comment]
Does that mean we can choose:

> Would be nice for BaseModel and dataclass to have the same behaviour.
> Would be nice for a pydantic dataclass to match a vanilla dataclass.

And change BaseModel to match vanilla dataclasses?

**Comment by samuelcolvin** [comment]
Any way we could use sourcegraph or GitHub search to see how much code would break?

We might need to keep the behaviour but add a deprecation warning, then remove in V3.

**Comment by r-richmond** [comment]
>I didn't know about annotation only fields, so I chose ellipsis as meaning required

as a personal antidote that was my initial understanding as well, I imagine that is not uncommon for new users of pydantic sit feels like the intended meaning.

>We might need to keep the behaviour but add a deprecation warning, then remove in V3.

Unsolicited user opinion: add a deprecation warning to the v1 series instead and remove in v2. You have a version bump coming might as well use the opportunity to make breaking improvements.

**Comment by samuelcolvin** [comment]
> Unsolicited user opinion: add a deprecation warning to the v1 series instead and remove in v2. You have a version bump coming might as well use the opportunity to make breaking improvements.

Can't do that I'm afraid:
1. Technically it would be very hard to do accurately in general.
2. It's a major change in behaviour in a minor release which breaks semvar.
3. It's not what everyone else does, so developers would find it very confusing.

**Comment by r-richmond** [comment]
> It's a major change in behaviour in a minor release which breaks semvar.

Do you consider v2 released / feature locked already?

**Comment by samuelcolvin** [comment]
No, not yet. But issuing warnings in v1 is a significant change.

**Comment by r-richmond** [comment]
>No, not yet. But issuing warnings in v1 is a significant change.

AFAIK according to semvar this is not a significant change & is the recommend path

[Source](https://semver.org/#how-should-i-handle-deprecating-functionality)
[Commit with link to original discussion](https://github.com/semver/semver/commit/e0f985a7266ac2fdbc4076f159e1008926c6fe1c)

**Comment by samuelcolvin** [comment]
Interesting, okay it wouldn't break semvar.

But my other points stand, it would also require duplicated work - V2 is close enough that many people will migrate straight from what they currently use to V2.

V1.11 would not negate the need for deprecation warnings in V2.

**Comment by dmontagu** [comment]
Yeah, I think this would affect a lot of existing code for minimal benefit.

I’m not sure what makes the most sense regarding the meaning of `…` (various arguments seem compelling to me), but I don’t think we should make breaking changes without a good bit of notice on this point.

**Comment by r-richmond** [comment]
>V1.11 would not negate the need for deprecation warnings in V2.

V1.11 would be the version with deprecation warnings. V2 wouldn't have deprecation warnings as the old behavior would already be deprecated.

>V2 is close enough that many people will migrate straight from what they currently use to V2.

>I’m not sure what makes the most sense regarding the meaning of … (various arguments seem compelling to me), but I don’t think we should make breaking changes without a good bit of notice on this point.

So my biggest sticking point here is that for `field` pydantic's [own docs](https://docs.pydantic.dev/usage/schema/#field-customization) say `Use ellipsis (...) to indicate the field is required.`

I would argue that being consistent in the meaning of `...` across Field defaults and defaults is better than the alternative. To that end I view the current behavior in v1 as a bug/inconsistent and the current behavior in v2 as fixed / consistent.

**Comment by samuelcolvin** [comment]
Okay, let's keep the behaviour unchanged in V2.

I think on dataclasses at least, and probably models we should change it in V3 we should make a default of `...` as a warning or error, but I want to minimise the breaking changes in v2 now.
