### ISSUE TITLE
Add `RootModel` to pydantic?

### ISSUE THREAD

**Issue by luolingchun** [pydantic/pydantic#5498]
**update by @samuelcolvin:** yes we should add this, but it needs to significantly rework `BaseModel` to use a core schema which is just the inner type. This might require some changes to pydantic-core.

---

### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

`__root__` Has been removed, but it is easier to use.

So, should we consider providing a convenience class (named `RootModel`) to pydantic to make it easier for users?

```python
class RootModel(BaseModel):
    @root_validator(pre=True)
    def populate_root(cls, _values):
        return {"root": _values}

    @model_serializer(mode="wrap")
    def _serialize(self, _handler, _info):
        data = _handler(self)
        if _info.mode == "json":
            return data["root"]
        else:
            return data

    @classmethod
    def model_modify_json_schema(cls, json_schema):
        metadata = {"title": cls.model_config.get("title", None) or cls.__name__, "description": getdoc(cls) or None}
        metadata = {k: v for k, v in metadata.items() if v is not None}
        return {**json_schema["properties"]["root"], **metadata}
```

```python

from pydantic import BaseModel, RootModel

class Sellout(BaseModel):
    a: str
    b: int


class SelloutList(RootModel):
    root: List[Sellout]


class SelloutDict(RootModel):
    root: Dict[str, Sellout]
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
Does anyone have objections to this API? If not, I think we could work toward implementing.

@samuelcolvin @commonism @Jerry-Ma

**Comment by samuelcolvin** [comment]
I'm pro adding it, but I don't want this API with a dict, it should work more like `AnalysedType` internally.

In particular `__init__` should take a single value, and the `SchemaValidator/Serialiser` should be for the actual type which `root` if annotated with.

**Comment by commonism** [comment]
It works, it's the only option so far, I use it.
Happy to evaluate any alternatives.

**Comment by samuelcolvin** [comment]
Great to have it here as a snippet, but if we add `RootModel` to pydantic (and I think we should), it should be implemented in the most efficient way.

**Comment by Kludex** [comment]
- Related https://github.com/pydantic/pydantic/issues/3852

**Comment by samuelcolvin** [comment]
First part of this - what's required in pydantic-core is done in https://github.com/pydantic/pydantic-core/pull/592.

The rest it still to do

**Comment by samuelcolvin** [comment]
`RootModel` should inherit from `BaseModel`

Ideally `RootModel` would be generic thus:

```py
class RootModel(BaseModel, Generic[T]):
    root: T

    def __init__(self, data: T):
        ...

    def model_dump(self, ...) -> T | dict[str, Any]:
        ...
```

But if the generic thing clashes with BaseModel generics, we can skip that for now. We use `T | dict[str, Any]` since `model_dump` will return a dict when `T` is a BaseModel or dataclass.

The following method (at least) will need to be changed:
* `__init__` signature `__init__(self, data: Any)`
* `model_dump` returns just `self.root` with the arguments applied
* `dict` must return `{'__root__': self.model_dump(...)}` to match V1
* anything else??

**Comment by lig** [comment]
Does subclass of `BaseModel` as a `root` type make sense? It seems just the same as a standalone `BaseModel` subclass.

**Comment by samuelcolvin** [comment]
I think so because a lot of logic will be reused.

I think start that way, and we can change later if it stops making sense.
