### ISSUE TITLE
Usage of Config.schema_extra causes examples to be overwritten

### ISSUE THREAD

**Issue by dmsfabiano** [pydantic/pydantic#5510]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The main issue I have is when creating a parent `BaseModel`, say `MyParentModel`, since `Config` is defined as a class variable, if any class Inherits `MyParentModel` and changes the `schema_extra` then it changes for all instances that inherit from `MyParentModel` specially with something as trivial as `example`

Let's take this simple example
```python
from pydantic import BaseModel, create_model
from typing import Dict, Any

from abc import ABC, abstractmethod


class ModelOutput(BaseModel, ABC):
    class Config:
        arbitrary_types_allowed = True
        schema_extra: Dict[str, Any] = {}

    @classmethod
    def custom_schema(cls) -> str:
        """Here, we can't use regular .schema_json because of arbitrary types,
        for simplicity, the code that casts arbitrary types to native ones is removed"""
        model = create_model(f"Dynamic{cls.__name__}", __base__=cls)

        model.Config.schema_extra["example"] = cls.example()
        return model.schema_json()

    @classmethod
    @abstractmethod
    def example(cls) -> Dict:
        ...

class MyModelOne(ModelOutput):
    my_pretty_field: str

    @classmethod
    def example(cls) -> Dict:
        return {"my_pretty_field": "this is a test!"}


class MyModelTwo(ModelOutput):
    my_ugly_field: str

    @classmethod
    def example(cls) -> Dict:
        return {"my_ugly_field": "this is a another test!"}


MyModelOne.custom_schema()
MyModelTwo.custom_schema()
print(ModelOutput.Config.schema_extra["example"])
```

Which the output is 
```{'my_ugly_field': 'this is a another test!'}```

In this example, it sort of fields as I am trap (or perhaps I am missing a different way). Because:
- We can't use `create_model` because it keeps the references of the old class (this may be the root problem here.)
- There is no way to explicitly pass the examples field when calling `.schema_json`
- If we do not use `.Config.schema_extra["example"]` integration with FastAPI breaks (no example shown)

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: C:\Users\dmsfa\code\.env\Lib\site-packages\pydantic
               python version: 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
The problem is here that you're changing the value of `model.Config.schema_extra["example"]` which is mutating the `schema_extra` dict which is defined once.

You should either:
* copy `schema_extra`, then change it
* call `model.schema_json()`, then update the returned dict
