### ISSUE TITLE
Pydantic doesn't instantiate proper type with subclassing

### ISSUE THREAD

**Issue by bluenote10** [pydantic/pydantic#5513]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

_(I tried to find related issues, but because it is hard to search, I couldn't really find anything. It is well possible that I just failed to search for the precise cause / description.)_

Pydantic seems to call the wrong object constructor when inheritance is involved:

The code below constructs the field `fancy_string` of type `str` although the base model specifies it as type `FancyString` (a subclass of `str`).

Actual output:

```
fancy_string='hello world'
<class 'str'>
```

Expected behavior: The assertion should not fail.

```
fancy_string='hello world'
<class 'FancyString'>
```

### Example Code

```Python
from pydantic import BaseModel

class FancyString(str):
    ...

class MyModel(BaseModel):
    fancy_string: FancyString

x = MyModel.parse_raw('{"fancy_string": "hello world"}')

print(x)
print(type(x.fancy_string))

# Should be an instance of FancyString, but isn't.
assert isinstance(x.fancy_string, FancyString)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.6
            pydantic compiled: True
                 install path: /home/user/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0]
                     platform: Linux-5.4.0-146-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
@bluenote10 I think most likely this won't be fixed in v1, but it is something I think we'd like to better-support out of the box in v2.

That said, the approach you commented above for creating a custom validator is probably the best way to handle this in v1, and is likely very closely related to what we'll do even in v2 (just we may attempt to do something like this automatically).

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
