### ISSUE TITLE
Union of models always uses first model

### ISSUE THREAD

**Issue by WilliamDEdwards** [pydantic/pydantic#5515]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

See subject.

### Example Code

In:

```Python
from pydantic import BaseModel
from typing import Union

class Germany(BaseModel):
  pass

class Netherlands(BaseModel):
  pass

class ContinentPart(BaseModel):
  country: Union[Netherlands, Germany]

print(ContinentPart(country=Germany()))
```

Out:

```Python
country=Netherlands()
```

Even though `country=Germany()` was passed.

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /Users/williamedwards/cluster-api/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.5-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
I think this behavior is probably set in stone for v1 (changes would likely break some existing code), but I'll note that:

* This _has_ been resolved in v2 (if you run the same exact code in v2 you will see `country=Germany()`)
* There is a config setting in v1 that will make this behave better called [smart_union](https://docs.pydantic.dev/usage/model_config/#smart-union):

  ```python
  from pydantic import BaseModel, Field
  from typing import Union
  
  class Germany(BaseModel):
      pass
  
  class Netherlands(BaseModel):
      pass
  
  class ContinentPart(BaseModel):
      country: Union[Netherlands, Germany]
  
      class Config:
          smart_union = True
  
  print(ContinentPart(country=Germany()))
  #> country=Germany()
  ```

**Comment by WilliamDEdwards** [comment]
`smart_union` does not work in unison with FastAPI responses.

When passing a Pydantic model to `response_model`, FastAPI does the following:

* Convert Pydantic model to dict (`response_content = ContinentPart(country=Germany()).dict()`)
* Create `pydantic.ModelField` (`field = create_response_field(name="foobar", type_=ContinentPart)`)
* Convert dict back to Pydantic model (`value, errors_ = field.validate(response_content, {}, loc=("response",))`)

The result of this process: the first model is used again, i.e. the correct value of the union is lost.

At first glance, the issue seems to be that `pydantic.ModelField` expects `model_config` (which should contain `smart_union` in my case), which FastAPI always sets to `pydantic.BaseConfig`.

**Comment by dmontagu** [comment]
I would suggest opening an issue with FastAPI for this; without diving into the details at all, my weak suspicion is that it's more likely that it would make sense to expose the ability to control the `model_config` on the FastAPI side than to change the default behavior in pydantic v1. And I think the timeline for FastAPI adopting pydantic v2 is going to be a bit longer (though hopefully not _too_ much longer) than the timeline for pydantic doing an official v2 release. So it may be more of a priority to enable such a fix within FastAPI itself.

**Comment by WilliamDEdwards** [comment]
> I would suggest opening an issue with FastAPI for this; without diving into the details at all, my weak suspicion is that it's more likely that it would make sense to expose the ability to control the `model_config` on the FastAPI side than to change the default behavior in pydantic v1. And I think the timeline for FastAPI adopting pydantic v2 is going to be a bit longer (though hopefully not _too_ much longer) than the timeline for pydantic doing an official v2 release. So it may be more of a priority to enable such a fix within FastAPI itself.

I agree. Sorry for the confusion, I just dumped that comment there for future readers. Thanks for your comments!
