### ISSUE TITLE
Union with str converts to str when not needed

### ISSUE THREAD

**Issue by Dreamsorcerer** [pydantic/pydantic#5521]
### Description

When using `int | str` an int is converted to a str.
The value was already valid, it should not be converted.

### Example Code

```Python
from typing import Sequence
from pydantic import parse_obj_as
parse_obj_as(Sequence[int | str], ("foo", 3))  # ('foo', '3')
```

### Affected Components

- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)

**Comment by samuelcolvin** [comment]
Please use the issue template.

This issue is reported approximately once a day when people fail to read the docs or do some research. If you're scenario is significantly different, please include those details.

It's fixed in V2, and in V1 using `smart_union`.

**Comment by samuelcolvin** [comment]
https://docs.pydantic.dev/usage/model_config/#smart-union
