### ISSUE TITLE
Should strictness be settable for fields of type Model? (And other config-related woes)

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5531]
Right now, you can't control the strictness of a field of a BaseModel which has a type which is another BaseModel:

```python
from pydantic import BaseModel, Field

class Inner(BaseModel):
    x: int

class Model(BaseModel):
    inner: Inner = Field(strict=True)  # Inner will not be treated as strict, as shown below:
    y: int = Field(strict=True)  # int will be treated as strict

print(Model(inner=Inner(x='1'), y=0))
#> inner=Inner(x=1)

Model(inner=Inner(x='1'), y='0')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
y
  Input should be a valid integer [type=int_type, input_value='0', input_type=str]
"""
```

However, I think changing this would lead to a lot of complexity related to the fact that refs only reflect the type, and we can't/shouldn't regenerate the type's intrinsic config as a consequence of being a field. We could have the ref be a function of the config, and that would mostly resolve this, but I also think there are a lot of questions about what the exact inheritance/field-affecting-ness behavior should be for each key in `config`.

Also it's important to consider what the behavior is of `AnalyzedType(<type>, config)`, when `<type>` has its own config vs. not. 

Adrian and I discussed all this at length today in the context of JSON schema ref handling and consistency (the problem being: you could have the same (core schema) ref multiple times with different config, and that would be a problem for the current JSON schema generation) and came to the conclusion that it's hard to answer, but wanted to track some of these issues.

**Comment by dmontagu** [comment]
I think if we want to have config stuff "contextually" affect fields, etc., we probably should have the aspects of config that aren't stored as part of the Model class's model_config explicitly stored separately as part of some sort of `ConfigContext` or similar, and that context needs to be reflected in the generation of (core schema) refs when building the CoreSchema.

**Comment by dmontagu** [comment]
Related, here's an example of something weird that could happen if you do have fields of type BaseModel reflecting the config of the parent models:
```python
from pydantic import BaseModel, ConfigDict

class A(BaseModel):
    x: int
    b: 'B'
    
class B(BaseModel):
    a: A | None
    
    model_config = ConfigDict(strict=True)

# If fields of type BaseModel inherited strictness from the parent model, this should be the behavior:
A(x='1', b=B(a=None)) # No error, since outer A is not strict
A(x='1', b=B(a=A(x='1', b=B(a=None))))  # Error, since inner A is strict (due to B being strict)

# Note, this would require the inner A to not be a definition reference to the outer A, 
# since it has different validation behavior
```
I think this could be resolved by ensuring the refs reflect the config settings that are effective for the field, but the important thing is we would need to change how `get_type_ref` works to reflect the config, or we'd introduce bugs.

**Comment by adriangb** [comment]
Here's another thought experiment:

```python
from typing import Annotated, List

from pydantic import AnalyzedType, Strict

# List validator behaves differently if it is strict or not
# in particular, it doesn't accept a tuple when validating Python
# in strict mode
AnalyzedType(List[int]).validate_python((1,), strict=True)

# So this should definitely generate two different refs
MyList = List[Annotated['MyList', Strict()]]

# In other words, this would be wrong:
{
    'type': 'list',
    'ref': '1',
    'items_schema': {
        'type': 'definitions-ref',
        'schema_ref': '1'
    }
}
# Because strict doesn't show up anywhere
# And the outer one should not be strict
# I think it should generate this
{
    'type': 'list',
    'ref': 'MyList-Lax',
    'items_schema': {
        'type': 'list',
        'strict': True,
        'ref': 'MyList-strict',
        'items_schema': {
            'type': 'definitions-schema',
            'schema_ref': 'MyList-Lax',
        }
    }
}
# or maybe
{
    'type': 'list',
    'ref': 'MyList-lax',
    'items_schema': {
        'type': 'list',
        'strict': True,
        'ref': 'MyList-Strict'
        'items_schema': {
            'type': 'definitions-schema',
            'schema_ref': 'MyList-Strict',
        }
    }
}
```
