### ISSUE TITLE
Support for Pulsar dsn

### ISSUE THREAD

**Issue by Evan6998** [pydantic/pydantic#5543]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

demo: adding a new network type PulsarDsn (Apache Pulsar is an open-source, distributed messaging and streaming platform).

```python
PulsarDsn = Annotated[
    MultiHostUrl, UrlConstraints(allowed_schemes=['pulsar', 'pulsar+ssl'], default_host='localhost', default_port=6650)
]
```

usage:
```python
from pydantic import BaseModel, PulsarDsn

class Model(BaseModel):
    a: PulsarDsn

m = Model(a='pulsar://localhost:6650')
print(str(m.a))

# >>> pulsar://localhost:6650
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @Evan6998 for this feature request.
As we have a separate [pydantic-extra-types](https://github.com/pydantic/pydantic-extra-types) for this kind of types please create the issue there.
