### ISSUE TITLE
Improving Contribution and Code Style docs

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5548]
### Description

After going around in search of a doc on a Code Style adopted in the Pydantic code base I have some suggestions to make.

- [x] Update outdated `make format` doc in the ``. We use `ruff` instead of `isort` now.
- [ ] Provide a Code Style policy for the entire code base in a separate section in [contributing.md](docs/contributing.md) or in a separate doc file.
- [ ] Specify an import organization policy in the Code Style doc. Consider for example imports in [_internal/_validators.py](pydantic/_internal/_validators.py#L9). There are direct imports from `typing` and at the same type `typing` is imported as a module.
- [ ] Maybe come up with some thing like `import pydantic_core as core` in the Code Style policy that should simplify the code while still providing an explicit namespace for the `pydantic_core` code.
- [ ] Define the policy on quotes being used to define string literals. There is already `skip_string_normalization=true` defined for `black`. I suggest using `'` for magic constants like dict keys, env var names, etc and `"` for human readable strings like console and error messages, logs, etc.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
Only some points from this issue are good for a first issue. I suggest working on those things separately creating new issues and referencing those here.

**Comment by Kludex** [comment]
Should we close this, or what is relevant here? @lig

**Comment by bL34cHig0** [comment]
Hey @lig, I'd like to work on this issue. 

Thank you

**Comment by lig** [comment]
cc: @dmontagu @samuelcolvin

**Comment by sydney-runkle** [comment]
Going to close this for now. We've added some more docs on core schemas, which I think help to contextualize things for devs.

Additionally, our adherence to pre-commit checks somewhat self-enforces code style + import styles, so there's no point in us explicitly writing out all of these rules.

I would say, pre-pycon or any other sprints, it'd be worth revisiting optimizing the startup time with contributing + collecting a few good first issues to have ready.
