### ISSUE TITLE
json-serializing models with only computed fields generates invalid json

### ISSUE THREAD

**Issue by jkgeyti** [pydantic/pydantic#5551]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Models with only a computed field renders invalid json when json-serialized. See example below, which generates the following output:

```
{},"b":"b"}
```

### Example Code

```Python
class A(BaseModel):
  @computed_field
  @property
  def b(self) -> str:
    return "b"

a = A()
print(A.model_dump_json(a))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
pydantic-core version: 0.25.0 release build profile
```

**Comment by adriangb** [comment]
@dmontagu please cut a release of `pydantic-core` and `pydantic` to use it.
