### ISSUE TITLE
1.10.7: test_generics_work_with_many_parametrized_base_models fails

### ISSUE THREAD

**Issue by mtelka** [pydantic/pydantic#5561]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

pydantic 1.10.7 test `test_generics_work_with_many_parametrized_base_models` fails on OpenIndiana:
```
____________ test_generics_work_with_many_parametrized_base_models _____________

    def test_generics_work_with_many_parametrized_base_models():
        cache_size = len(_generic_types_cache)
        params_size = len(_assigned_parameters)
        count_create_models = 1000
        T = TypeVar('T')
        C = TypeVar('C')

        class A(GenericModel, Generic[T, C]):
            x: T
            y: C

        class B(A[int, C], GenericModel, Generic[C]):
            pass

        models = [create_model(f'M{i}') for i in range(count_create_models)]
        generics = []
        for m in models:
            Working = B[m]
            generics.append(Working)

>       assert len(_generic_types_cache) == cache_size + count_create_models * 5 + 1
E       assert 5013 == ((13 + (1000 * 5)) + 1)
E        +  where 5013 = len(<WeakValueDictionary at 0x7fffaaf53b50>)
```
Please note that with pydantic 1.10.2 all tests passed when pydantic 1.10.2 was packaged back in December 2022.   Please also note that the pydantic 1.10.2 package for OpenIndiana was not  compiled.

### Python, Pydantic & OS Version

```Text
             pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /usr/lib/python3.9/vendor-packages/pydantic
               python version: 3.9.16 (main, Feb 19 2023, 15:42:40)  [GCC 10.4.0]
                     platform: SunOS-5.11-i86pc-i386-64bit-ELF
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by mtelka** [comment]
I suspect this fails only when there is `pytest-randomly` installed.  The failure of this test is not consistent.  Basically, with `pytest-randomly` some random tests could fail.

**Comment by Kludex** [comment]
@mtelka did you find where the issue is?

**Comment by mtelka** [comment]
Yes, when I run without `pytest-randomly` (or with `-p no:randomly`, to be precise) all tests pass.
