### ISSUE TITLE
Add migration documentation for filterwarnings/DeprecationWarning

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5571]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Having a list of all DeprecationWarning to use in pyproject/[tool.pytest.ini_options]/filterwarnings would allow taking care of things which actually break tests when moving to v2 and take care of the warnings once the real problems are resolved.

### Example Code

```Python
[tool.pytest.ini_options]
filterwarnings = [
# …
    # pydantic2
    'ignore:Support for "config" as "type" is deprecated and will be removed in a future version:DeprecationWarning',
    'ignore:Valid config keys have changed in V2:UserWarning',
    'ignore:The `update_forward_refs` method is deprecated; use `model_rebuild` instead.:DeprecationWarning',
    'ignore:The `parse_obj` method is deprecated; use `model_validate` instead.:DeprecationWarning',
    'ignore:The `construct` method is deprecated; use `model_construct` instead.:DeprecationWarning',
    'ignore:The `dict` method is deprecated; use `model_dump` instead.:DeprecationWarning',
    'ignore:`pydantic.config.Extra` is deprecated, use literal values instead .*$:DeprecationWarning',
    'ignore:Support for class-based `config` is deprecated, use ConfigDict instead.:DeprecationWarning',
    'ignore:The `__fields_set__` attribute is deprecated, use `model_fields_set` instead.:DeprecationWarning',
]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a2
        pydantic-core version: 0.23.1 release build profile
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-40-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
PR welcome if it's not too intrusive; would be best if there was a way to add a test for this that ensured we kept using it.

One possible thorn is that pycharm will show deprecation warning info in the hover popups _only_ if the first line of the deprecated function emits the warning with a string literal as the reason. So it will lightly degrade user experience to assign the error message to a variable and re-use it in the test etc.

**Comment by commonism** [comment]
Using sourcegraph I found there is tests for this already:
https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/pydantic/pydantic%24+DeprecationWarning&patternType=standard&sm=1&groupBy=path

https://github.com/pydantic/pydantic/blob/main/tests/test_deprecated.py

**Comment by gotmax23** [comment]
Would it be possible to create a custom PydanticDeprecationWarning subclass and have all of the warnings raise that instead of a plain DeprecationWarning? Projects that still need to support v1 and can't address all of the deprecations could just add something like `ignore::pydantic.PydanticDeprecationWarning`  and be on their way.

**Comment by samuelcolvin** [comment]
I think this would be a great idea, it would also allow us to customize printing to include a link to docs, like errors.
