### ISSUE TITLE
Allow passing additional pytest arguments to `make test` 

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5572]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Consider the following use case.

* A Contributor writes a test reproducing failing behavior.
* Contributor runs `make test` and confirms the new test is failing.
* At this point Contributor would like to play around with `pytest` parameters, i.e. `-x`, `--runxfail`, `-vv`, to speed up and simplify the development process.
* Now Contributor need to copy and paste the command from `Makefile` and modify it according to their needs.

This behavior effectively forks the workflow from the supported in `Makefile`. It is possible that next time Contributor will use a forked `pytest` command instead of the supported one that could change with time. This could lead to a confusion and an unexpected behavior.

It seems useful allowing passing additional `pytest` arguments to `make test` command to avoid such a confusing behavior and simplify the learning curve for a new contributor.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Just run `pytest` directly and add the arguments needed. `Makefile` has no way to pass arguments erganonically.
