### ISSUE TITLE
Renaming `AnalysedType`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5580]
As per my talk at [pycon 2023](https://slides.com/samuelcolvin/how-pydantic-v2-leverages-rust-s-superpowers), I think we should rename `AnalysedType`:

Usage  is:

```py
from pydantic import AnalyzedType

x = AnalyzedType(TheType)
d = x.validate_python(...)
d = x.validate_json(...)

x.dump_python(d)
x.dump_json(d)

x.json_schema()
```

Other name ideas:
* `PydanticTypeWrapper`
* `TypeValidator`
* some people suggested using "Model" in the name, but I think that's too confusing with `BadeModel` and `RootModel`

**Comment by sisp** [comment]
+1 for `TypeValidator`

**Comment by shufflebits** [comment]
Having played with this, it's still totally non-Mypy-useful.
```
class Foo(BaseModel):
    a:str

class Bar(BaseModel):
    b:str

AllTypes=Union[Foo, Bar, str]

ta = TypeAdapter(AllTypes).validate_python({"b": "bar"})
reveal_type(ta)
```
causes Mypy to output:
```
note: Revealed type is "typing._SpecialForm"
```
Where I was hoping for  `Union[Foo, Bar, str]`
I realise this is probably a Python typing deficiency, but I'm not sure where to report this to get it noticed. The ability to throw a chunk of payload at a discriminated union of all the payload types and just get the right one out is so cool - I was really sad when Mypy started complaining at `parse-obj-as()`
