### ISSUE TITLE
Document and improve API for custom errors

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#5586]
- Custom title on the main ValidationError
- Accept keyword argument for ValidationError? Currently only positional are supported
- Add docstrings to and rename InitErrorDetails

Maybe it makes sense to create Python functions to produce these rust structs. Also would make it easier to accept keyword arguments.

Current status: https://github.com/pydantic/pydantic/issues/734#issuecomment-1522182814

**Comment by Kludex** [comment]
@adriangb Should we close this?
