### ISSUE TITLE
Missing `Iterable` as `sequence_like` type 

### ISSUE THREAD

**Issue by kbespalov** [pydantic/pydantic#5594]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

We have to add `Iterable` into `sequence_like` check:

```py
def sequence_like(v: Any) -> bool:
    return isinstance(v, (list, tuple, set, frozenset, GeneratorType, deque))
```

1. According to Python `Iterable` protocol, only one method should be implemented - `__iter__`. 
2. The `list` constructor accepts `Iterable` as parameter: `list(items: Iterable)` is valid
3. Without adding `Iterable` into list of sequence like types there is no ability to validate user-defined collections  that implements `Iterable`.

### Actual problem:

The `from_orm` method does not work with `association_proxy` fields in SQLAlchemy, because SQLAlchemy returns `AssociationList[str]`, that implements `Iterable[str]`, but pydantic fails validation as `List[str]`.

`list(AssociationList())` works perfectly, so we have to fix `sequence_like` behavior.

PS 
No idea why `dequeue` or `GeneratorType` is valid List type in pydantic, but `Iterable` is not. 

### Example Code

```Python
from collections import deque
from types import GeneratorType
from typing import List, Iterator, Any


# Custom user-defined collection that implements Iterable
class MyListOfStrings:

    def __init__(self, strings: List[str]):
        self._strings = strings

    def __iter__(self) -> Iterator[str]:
        for string in self._strings:
            yield string
        return


def sequence_like(v: Any) -> bool:
    return isinstance(v, (list, tuple, set, frozenset, GeneratorType, deque))


if __name__ == '__main__':
    result = MyListOfStrings(["a", "b", "c"])
    print(sequence_like(result))  # False 
    print(list(result))  # OK
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /Users/kbespalov/workspace/api/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:14:58)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Gloweye** [comment]
I just ran into the exact same problem with SQLAlchemy AssociationProxy objects. I strongly agree with this suggestion.

In my case, I was able to make a workaround:
```python 
class MyModel(BaseModel):
    id: int
    names: list[str]

    @validator('names', pre=True)
    def convert_to_list(cls, value):
        return list(value)
```
But it's definitely ugly, and the validator error you get from not having this conversion going on does not lead to this solution at all. (it just claims the value is not a valid list).

My pydantic version is 1.10.4

**Comment by lig** [comment]
The following code now works in Pydantic v2.3.0

```py
from typing import Iterable, Iterator, List

from pydantic import BaseModel


# Custom user-defined collection that implements Iterable
class MyListOfStrings:
    def __init__(self, strings: List[str]):
        self._strings = strings

    def __iter__(self) -> Iterator[str]:
        for string in self._strings:
            yield string
        return


class Model(BaseModel):
    value: Iterable[str]


m = Model(value=MyListOfStrings(['a', 'b', 'c']))

assert list(m.model_dump()['value']) == ['a', 'b', 'c']
```
