### ISSUE TITLE
Unexpected `Sequence[str]` behavior

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5595]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Consider the following model class

```python
import pydantic
import typing

class Model(pydantic.BaseModel):
    str_sequence: typing.Sequence[str]
    str_value: str
```

Passing correct values works as expected

```python
m = Model(str_sequence=['a', 'b', 'c'], str_value='abc')
repr(m)  # "Model(str_sequence=['a', 'b', 'c'], str_value='abc')"
```

Passing a list of strings into a string property fails as expected

```python
Model(str_sequence='abc', str_value=['a', 'b', 'c'])
```
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
str_value
  Input should be a valid string [type=string_type, input_value=['a', 'b', 'c'], input_type=list]
```

Passing a string into a `Sequence[str]` property results in the `str` value being accepted as a valid `Sequence[str]` value

```
m = Model(str_sequence='abc', str_value='abc')
repr(m)
"Model(str_sequence='abc', str_value='abc')"
```

This doesn't match `list` behavior

```python
class Model1(pydantic.BaseModel):
    str_list: list[str]

m1 = Model1(str_list='abc')
```
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model1
str_list
  Input should be a valid list [type=list_type, input_value='abc', input_type=str]
```

Pydantic 1.10 also correctly raises a validation error in this case

```python
>>> import pydantic
>>> import typing
>>> class Model(pydantic.BaseModel):
...     str_sequence: typing.Sequence[str]
...     str_value: str
... 
>>> m = Model(str_sequence='abc', str_value='abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lig/workspace/pydantic/pydantic1/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Model
str_sequence
  value is not a valid sequence (type=type_error.sequence)
```

### Example Code

```python
from pydantic import BaseModel
from typing import Sequence

class Model(BaseModel):
    str_sequence: Sequence[str]
    str_value: str

m = Model(str_sequence='abc', str_value='abc')
repr(m)  # "Model(str_sequence='abc', str_value='abc')"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
               python version: 3.10.11 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230404 (Red Hat 13.0.1-0)]
                     platform: Linux-6.2.12-300.fc38.x86_64-x86_64-with-glibc2.37
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by Viicos** [comment]
I don't know if the different behavior between v1 and v2 is intentional, but in Python any string is considered a `Sequence[str]`. The potential confusion is a known issue (see https://github.com/python/typing/issues/256)

**Comment by Viicos** [comment]
> It looks like it's not only differs from Pydantic v1 but also from `list[str]` in the same v2.

Because `str` obviously doesn't match `list[str]`.

> IMO, the decision is there and this is just an erroneous behavior.

the _erroneous behavior_ is not from pydantic, but a general issue regarding Python typing. My assumption is that pydantic maintainers wanted `v2` to be in accordance with the behavior of `Sequence[str]` with `str`, but maybe `v2` could deviate from the intended typing behavior (model strictness may be related here)

**Comment by Viicos** [comment]
> if you do want to allow str, you can just annotate as str | Sequence[str] - much easier than specifically disallowing str via a validator

For the record, this is [how pytype behaves](https://github.com/python/typing/issues/256#issuecomment-902369240) for this use case. Maybe this could be indicated in docs? (or it's not that common to face this issue, and we avoid adding too much in docs)

**Comment by lig** [comment]
@Viicos documenting this behavior seems like a good idea to me.

Let me also share my view on the `str`/`Sequence[str]` topic.

I honestly believe that it is not `typing` and in general not the language responsibility to make `str` distinguishable from `Sequence[str]`. However, it is exactly why Pydantic exists and its job to help developers dealing with this behavior. Here is why.

There are three distinct levels here:
- Language
- Library
- Application

IMO, `typing` is on the Language layer as type annotations cannot lie about language features. And when the language says that distinguishing between `str` and `Sequence[str]` is the developer's job it doesn't necessarily means that it's an Application level's job. These common quality of life cases are exactly why there are libraries like `Pydantic` out there.

Thus, let's agree to leave this tedious job of making `if not isinstance(value, str)` check every time we write `Sequence[str]` to the Library level.
