### ISSUE TITLE
Unexpected behavior for `Sequence[int]` in Json Schema

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5597]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

- [X] Using `Sequence[int]` for json is inconsistent.
- [ ] `BaseModel.validate_json` should raise if `BaseModel.model_json_schema` raises. See below

Generating json schema via `BaseModel.model_json_schema()` raises `PydanticInvalidForJsonSchema` error which seems as a correct behavior.

However, calling `BaseModel.validate_json(...)` results in an attempt to validate passed json value while the validation schema is invalid.

### Example Code

```Python
>>> from pydantic import BaseModel
>>> from typing import Sequence
>>> class Model(BaseModel):
...     int_sequence: Sequence[int]
...     int_list: list[int]
... 
>>> Model.model_json_schema()
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (typing.Sequence)

>>> Model.model_validate_json('{"int_sequence": [1, 2, 3], "int_list": [1, 2, 3]}')
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
int_sequence
  Input should be an instance of Sequence [type=is_instance_of, input_value=[1, 2, 3], input_type=list]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
               python version: 3.10.11 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230404 (Red Hat 13.0.1-0)]
                     platform: Linux-6.2.12-300.fc38.x86_64-x86_64-with-glibc2.37
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by lig** [comment]
Reopening as one test in #5598 is still failing

**Comment by dmontagu** [comment]
@lig I'm not sure that test makes sense — see [this comment](https://github.com/pydantic/pydantic/pull/5598#issuecomment-1548507790) for more detail.

I think this might be coming from a misconception — the generated JSON Schema has nothing to do with actual validation, it is just a generated thing for use by web frameworks, etc.

So it's generally always possible that you have an invalid JSON schema and yet can successfully validate things, or vice versa, that you have a valid JSON schema but cannot actually validate anything. (Validation is done by the pydantic core schema.)

At any rate, I think we made `Sequence[int]` have a valid json schema (the same as `list[int]`), which also means that test is maybe no longer checking something meaningful.

Happy to discuss more if I'm misinterpreting something.
