### ISSUE TITLE
Regression: Assigning a value after creating an object no longer validates.

### ISSUE THREAD

**Issue by masasin** [pydantic/pydantic#5613]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

This used to work in 1.8.2. After an object is created, assigning to a variable no longer runs the validator, and no longer guarantees the type. I'd expect a ValidationError to be raised here.

### Example Code

```Python
from pydantic import BaseModel

class Foo(BaseModel):
    value: int

f = Foo(value=5)
f.value = "value is now a string"  # Should not happen
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /Users/jnassar-adimian/Library/Caches/pypoetry/virtualenvs/acer-ccc-lt-AmwmFq2i-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Nov  4 2022, 07:35:00)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
@masasin thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?

**Comment by masasin** [comment]
I can confirm it still exists in V2. It hasn't been relevant to me directly since I discovered the bug because I worked around it.

**Comment by lig** [comment]
@masasin thank you for the answer. In this case this is intended behavior. There is `validate_assignment` class parameter that enables the behavior you need. See https://docs.pydantic.dev/latest/usage/model_config/#validate-assignment

**Comment by masasin** [comment]
That is indeed what I was hoping for. Thank you!
