### ISSUE TITLE
Feature request: ValidateInstances annotation (replacement for `arbitrary_types_allowed`)

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5631]
As noted here: https://github.com/pydantic/pydantic/issues/809#issuecomment-1528008666,

I think it might make sense to deprecate the `arbitrary_types_allowed` config setting and introduce an annotation that results in the same behavior for the affected field (i.e., validatio only allows exact instances). So instead of:
```python
class MyModel:
    x: MyArbitraryType
    model_config = dict(arbitrary_types_allowed=True)
```
you'd do:
```python
class MyModel:
    x: Annotated[MyArbitraryType, pydantic.ValidateInstances]
```
or similar (maybe we could find a pithier name for this `ValidateInstances` thing).

There are a few significant upshots to this approach, IMO:
* you know (and can control) precisely which types it applies to, rather than potentially applying to any of the fields
* it ensures you don't miss the inheritance of the `arbitrary_types_allowed` config setting from parent classes.

(I don't intend to work on this soon, but I am opening an issue for discussion, and because I think it would be a relatively straightforward thing for someone new-ish to pydantic/pydantic_core to work on.)

**Comment by martinezmarcos** [comment]
Hi @dmontagu. I've been using `pydantic` for about a year now and looking to begin to contribute to `pydantic` and `pydantic-core`. I'd like to take on this issue, if that's okay. If so, any additional information and feedback would be appreciated.

**Comment by dmontagu** [comment]
It might make sense to wait to get confirmation from @samuelcolvin or other maintainers that this is something that we'd want to provide in the package.

If it is though (and I think it should be), I think the right approach would be to create a new type in `pydantic.annotated_arguments` with whatever name we want to use, and give it a method that is something like:
```python
    @classmethod
    def __get_pydantic_core_schema__(
        self, source_type: Any, handler: Callable[[Any], core_schema.CoreSchema]
    ) -> core_schema.CoreSchema:
        return core_schema.is_instance_schema(source_type)
```
This may require some minor tweaks to support generic types, unions, etc. You'll want to look in the codebase and tests for other implementations of `def __get_pydantic_core_schema__` and/or the `pydantic._internal._generate_schema.GenerateSchema` class to see how we generate schemas for other types.

This will also require some tests.

**Comment by martinezmarcos** [comment]
Yeah, I think this is definitely something I could handle. Thanks for the additional information @dmontagu. I'll dive into it and be on standby

**Comment by martinezmarcos** [comment]
Thanks @dmontagu. I'll follow here with any updates or questions

**Comment by dmontagu** [comment]
Yes, that’s approximately what I had in mind (I hadn’t thought about it deeply but you’ve done the right thing).

It may get a little more complicated when dealing with parsing json for more interesting types, I’m not sure (eg, do we let a field of type Annotated[Decimal, CheckIsInstance] be parsed from JSON at all?).

Regarding int, etc., I think if something is already an instance it doesn’t need any further validation. My comment was, for something that isn’t an instance, it _may_ make sense to attempt the regular validation. (Eg ‘1’ validating into 1 for a field of type int.) We could make this an option by making the CheckIsInstance a dataclass with an argument for whether to perform subsequent validation on failure or just reject non-instances.

**Comment by martinezmarcos** [comment]
Hi @dmontagu. I saw that there's a PR to address #5773. Are you still looking for contributions on this issue?

**Comment by martinezmarcos** [comment]
Hey @dmontagu, no worries at all! Thanks for all the help and info over this issue nonetheless. It was a great learning experience. I'll keep my eyes peeled for any other opportunities to help out
