### ISSUE TITLE
Document how to implement your own error template messages

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#5651]
- Inspired by https://github.com/pydantic/pydantic/issues/2713
- Related https://github.com/pydantic/pydantic/issues/322

We've changed our machinery around "how to change the error messages". On v1, we had the `error_msg_templates` config attribute, but on v2 it was removed.

I've created this issue so we can document how to implement the analogous idea on V2.

**Comment by wu-clan** [comment]
Any progress on this issue?
