### ISSUE TITLE
Use property docstrings as descriptions

### ISSUE THREAD

**Issue by rattrayalex** [pydantic/pydantic#5656]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

_Moving from [this comment](https://github.com/pydantic/pydantic/issues/2947#issuecomment-1067378353) on [a related issue](https://github.com/pydantic/pydantic/issues/2947), where people seemed interested in the feature._

I would like this:
```py
class Foo(BaseModel):
    bar: float
    """Short explanation."""
```

To be equivalent to this:

```py
class Foo(BaseModel):
    bar: float = Field(description="Short description.")
    """Short explanation."""
```

If you provide both, the `description` should win.

Reasons:

1. It's a nicer, cleaner, standard Pythonic syntax.
2. The docstring appears in hover in editors like VS Code, but the Field description does not (though note https://github.com/pydantic/pydantic/issues/638 would remove this limitation).

Would that be possible?

Note this feature request seems like the inverse of https://github.com/pydantic/pydantic/issues/638, where the docstrings are pulled from the description, which I think is also a good idea. Ideally we'd have both IMO, since this syntax 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by rattrayalex** [comment]
cc @dmontagu since you've been looking at the related issues recently

**Comment by samuelcolvin** [comment]
They're not docstrings, they're just strings afaik.

If they were official docstrings they would be available at runtime.

As I understand it, we access these strings, you're need to parse the last? But maybe I'm wrong.

Happy to review a PR to to add this if it's possible in an elegant way, but my suspicion is that it's not. Unless it's a very clear and reliable implementation, I think it should live in a separate library.

**Comment by rattrayalex** [comment]
Ah, my mistake. I haven't checked but I assume you're correct, and if so I agree that it belongs in a separate library.

**Comment by FynnBe** [comment]
For anyone visiting this issue and wondering if this is implemented somewhere already : [gist](https://gist.github.com/FynnBe/8ad2546c456f9ad95e2100badf80d099)

**Comment by rattrayalex** [comment]
Cool! My guess is that removing f-string support would be wise; otherwise I'm curious what @samuelcolvin thinks of this.
