### ISSUE TITLE
Default values are persisting in v2

### ISSUE THREAD

**Issue by anomam** [pydantic/pydantic#5672]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

First of all, thank you so much for this amazing library and the incredible work you're doing. I'm very excited about all the new features in v2!!

I noticed some change in behaviour with default values, and I was wondering if that was deliberate? It looks like default values are persisted between model instantiations in v2.

Running the code below with v2 prints:

```
[1]
[1]
```

But with v1, it prints:

```
[1]
[]
```

(feel free to rename the issue if the title is not great!)

### Example Code

```Python
from pydantic import BaseModel


class Model(BaseModel):
    field: list[int] = []


a = Model()
a.field.append(1)
print(a.field)


b = Model()
print(b.field)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a3
        pydantic-core version: 0.25.0 release build profile
                 install path: <...>lib/python3.10/site-packages/pydantic
               python version: 3.10.8 <...> [Clang 11.0.0 (clang-1100.0.33.12)]
                     platform: macOS-10.15.7-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by Kludex** [comment]
Thanks for the report. This does look like a bug.

**Comment by PrettyWood** [comment]
I know some people (including myself) wanted the deepcopy on default value to be removed, now that `default_factory` is officially part of the API.  This follows the `dataclass` implementation.
Don't know if this is one of the breaking changes of v2 or not (I have not read anything on it so you're probably right @Kludex)

**Comment by adriangb** [comment]
I agree with @PrettyWood on this one, if you want it to be regenerated every time that is easy enough to do with default factory. This seems like a change worth making.
