### ISSUE TITLE
Don't dump 'allow'-ed extra by default

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#5683]
In v1, if you had a model with `extra = 'allow'` in the model config, it would include the extra fields when dumping the model.

If we do this, we end up with the following (possibly strange/surprising?) behavior:
```python
def test_serialize_extra_allow_subclass_2() -> None:
    class Parent(BaseModel):
        x: int
        model_config = ConfigDict(extra='allow')

    class Child(Parent):
        y: int

    class Model(BaseModel):
        inner: Parent

    m = Model(inner=Child(x=1, y=2))
    assert m.inner.y == 2
    assert m.model_dump() == {'inner': {'x': 1}}
    assert json.loads(m.model_dump_json()) == {'inner': {'x': 1}}

    m = Model(inner=Parent(x=1, y=2))
    assert m.inner.y == 2
    assert m.model_dump() == {'inner': {'x': 1, 'y': 2}}
    assert json.loads(m.model_dump_json()) == {'inner': {'x': 1, 'y': 2}}
```

I would argue this is the correct behavior, because the `Child` class has said that `y` is one of its fields, not arbitrary extra, and we have decided (for FastAPI-security-related reasons) that when serializing, we use the schema of the type on which the method is called, rather than asking instance attributes how they want to be serialized.

----

However, because of the risk of accidentally converting instances to dicts and back at some point in whatever code a user might use to interact with their objects, I would go a step farther and make the argument that there is similar risk for security issues whenever we include allowed-extra attributes when serializing model instances.

Therefore, I think in v2, we should change the default behavior to _exclude_ any allowed extra attributes by default, though we can retain a flag to include them for backwards compatibility.

-----

One thing I foresee potentially being a feature request in the wake of these changes is the ability to make it so you _do_ ask field items how they want to be serialized. However, I _think_ we can implement that by using an `any` serialization schema, which I think can be done by way of an annotation. So I don't think we need to worry too much about that for now (though it may make sense to add this annotation to `annotated_arguments`).

**Comment by samuelcolvin** [comment]
we have `revalidate` which would avoid this issue by rebuilding `child` into `parent`.

In theory, if this became a problem we could detect a subclass in the model serializer, and do something complicate to work out which things are fields, and which are extra.

**Comment by dmontagu** [comment]
I think since we now have `SerializeAsAny` we can close this.
