### ISSUE TITLE
AttributeError: 'ValidatedEmail' object has no attribute 'normalized'

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5739]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The use of email-validator needs a version glue to fail better with mismatching versions.
having old (<2.0) email-validator installed does not update due to the optional dependency and fails for [Rename the email field of ValidatedEmail to normalized](
https://github.com/JoshData/python-email-validator/commit/99e51228e2d8d4b2befb3b803d895bbece1df84c)

@JoshData I do not see email-validator exporting a version string, so it'll be hasattr?

### Example Code

```Python
from pydantic import BaseModel, EmailStr

class A(BaseModel):
    m: EmailStr

A.model_validate({"m":"test@example.com"})
```

### Python, Pydantic & OS Version

```Text
>>> import pydantic.version; print(pydantic.version.version_info())
             pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: ~/venv/openapi3/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-40-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by JoshData** [comment]
> @JoshData I do not see email-validator exporting a version string, so it'll be hasattr?

Ah I hadn't thought of that! Would love a PR to add it if you're willing.

**Comment by dmontagu** [comment]
@commonism also feel free to open a PR adding a check for version compatibility in the `pydantic.networks.import_email_validator` function, with an appropriate error message if the version is incompatible.

**Comment by TonyMistark** [comment]
### pydantic v2.4.2: the same error
```
Python 3.11.3 (main, Apr  5 2023, 14:15:06) [GCC 9.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pydantic import BaseModel, EmailStr
   ...: 
   ...: class Model(BaseModel):
   ...:     email: EmailStr
   ...: 
   ...: print(Model(email='contact@mail.com'))
   ...: #> email='contact@mail.com'
   ...: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 6
      3 class Model(BaseModel):
      4     email: EmailStr
----> 6 print(Model(email='contact@mail.com'))
      7 #> email='contact@mail.com'

    [... skipping hidden 1 frame]

File ~/.virtualenvs/311/lib/python3.11/site-packages/pydantic/networks.py:403, in EmailStr._validate(cls, _EmailStr__input_value)
    401 @classmethod
    402 def _validate(cls, __input_value: str) -> str:
--> 403     return validate_email(__input_value)[1]

File ~/.virtualenvs/311/lib/python3.11/site-packages/pydantic/networks.py:688, in validate_email(value)
    683 except email_validator.EmailNotValidError as e:
    684     raise PydanticCustomError(
    685         'value_error', 'value is not a valid email address: {reason}', {'reason': str(e.args[0])}
    686     ) from e
--> 688 email = parts.normalized
    689 assert email is not None
    690 name = name or parts.local_part

AttributeError: 'ValidatedEmail' object has no attribute 'normalized'
```

**Comment by TonyMistark** [comment]
> ### pydantic v2.4.2: the same error
> ```
> Python 3.11.3 (main, Apr  5 2023, 14:15:06) [GCC 9.4.0]
> Type 'copyright', 'credits' or 'license' for more information
> IPython 8.7.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: from pydantic import BaseModel, EmailStr
>    ...: 
>    ...: class Model(BaseModel):
>    ...:     email: EmailStr
>    ...: 
>    ...: print(Model(email='contact@mail.com'))
>    ...: #> email='contact@mail.com'
>    ...: 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[1], line 6
>       3 class Model(BaseModel):
>       4     email: EmailStr
> ----> 6 print(Model(email='contact@mail.com'))
>       7 #> email='contact@mail.com'
> 
>     [... skipping hidden 1 frame]
> 
> File ~/.virtualenvs/311/lib/python3.11/site-packages/pydantic/networks.py:403, in EmailStr._validate(cls, _EmailStr__input_value)
>     401 @classmethod
>     402 def _validate(cls, __input_value: str) -> str:
> --> 403     return validate_email(__input_value)[1]
> 
> File ~/.virtualenvs/311/lib/python3.11/site-packages/pydantic/networks.py:688, in validate_email(value)
>     683 except email_validator.EmailNotValidError as e:
>     684     raise PydanticCustomError(
>     685         'value_error', 'value is not a valid email address: {reason}', {'reason': str(e.args[0])}
>     686     ) from e
> --> 688 email = parts.normalized
>     689 assert email is not None
>     690 name = name or parts.local_part
> 
> AttributeError: 'ValidatedEmail' object has no attribute 'normalized'
> ```

fixed by `pip install -U email-validator`
