### ISSUE TITLE
V1 inside V2 for migration purposes

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5771]

**Comment by samuelcolvin** [comment]
most recent tag inside V2, then update on future releases.

**Comment by tlambert03** [comment]
thanks @samuelcolvin, much appreciated

**Comment by caniko** [comment]
@tlambert03 I don't think this can solve the issue you raised in discussion. You don't have control over upstream packages when you install them, this solution is for those that are migrating.

I would just stick to v1 if I was you, it is much safer and easier for those in your situation.

**Comment by tlambert03** [comment]
thanks. perhaps i don't understand what's happening here then?  (I assumed this meant there would be a v1 namespace inside of v2 ... but maybe I'm wrong)

> I would just stick to v1 if I was you, it is much safer and easier for those in your situation. 

again, @caniko, I'm afraid this misses the point.  don't want to go through this again, but it doesn't matter whether a library (not an application) "sticks to v1" or not.  as soon as the end user pip installs another package with an incompatible version of pydantic into that same environment (i.e. if it was technically an "unsolvable" environment but pip installs it anyway), then the package using v1 is broken unless there is a "safe" v1 namespace that they can use.

@samuelcolvin, is that the goal here?

**Comment by samuelcolvin** [comment]
you have it right, you'll be able to import pydantic v1 from `pydantic.v1`.

**Comment by tlambert03** [comment]
Excellent.  Then this is exactly what I was asking for.  Much appreciated

**Comment by caniko** [comment]
You want to ensure that the enduser doesn't accidentally use the wrong version by installing the latest version of Pydantic. That is enabled by this.

This is not what I am referring to.

I am talking about packages that use v1 now that won't be migrated to v2 because they work fine for their intended use (paraphrasing you here). These packages also don't have upper bound semver. These packages would break in v2. That is what I am saying.

**Comment by caniko** [comment]
You still won't be able to bring this upstream. So the initial issue is unresolved.

**Comment by paddymul** [comment]
Are there any guides for library writers thinking of using pydantic?  I want to use it to do input validation, but don't expect any deep dependencies on PyDantic functionality.  Has there been a backport of the `v1` namespace?

would something like this be appropriate
```python

import pydantic
if pydantic.version.split('.')[0] < 2:
    pydanticv1 = pydantic
else:
    pydanticv1 = pydantic.v1
```

**Comment by tlambert03** [comment]
https://github.com/pyapp-kit/pydantic-compat was my attempt at a backport (name adapter)

It's not feature complete, or without issues, so if you're starting a new project, I'd suggest just stipulating support for v2+ only if at all possible.
