### ISSUE TITLE
Incorrect result when dumping nested model when allowing extra.

### ISSUE THREAD

**Issue by Jerry-Ma** [pydantic/pydantic#5784]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi,
It appears that `model_dump` of nested model gives incorrect result when `extra="allow"`. Here is a minimum working example that demonstrates the issue:

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, Field
from pydantic.version import version_info


class Inner(BaseModel):
    a: str = "a"


class Outer(BaseModel):
    # this cause the inner model incorrectly dumpped:
    model_config = ConfigDict(extra="allow")
    inner: Inner = Field(default_factory=Inner)


def test_dump():
    m = Outer.model_validate({})

    print(m.model_dump())


print(version_info())
test_dump()
```

Output:

```
             pydantic version: 2.0a4
        pydantic-core version: 0.31.0 release build profile
                 install path: /home/ma/.pyenv/versions/3.10.6_sys/envs/tolteca_v2/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.15.85-penguins-rule-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
/home/ma/.pyenv/versions/tolteca_v2/lib/python3.10/site-packages/pydantic/main.py:525: UserWarning: Pydantic serializer warnings:
  Expected `general-fields` but got `tuple` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
{'inner': ({'a': 'a'}, None)}
```

There is, for some reason, an extra tuple around the dumped inner model. The expected output should be `{'inner': {'a': 'a'}}`.

Let me know if you need more details. Thanks a lot!

**Comment by Jerry-Ma** [comment]
Update:
It appears that pydantic v2.0a3 and pydantic_core v0.30.0 does not have this issue.

**Comment by dmontagu** [comment]
@Jerry-Ma sorry — when you said 2.0a3 does not have this issue I thought you meant it was fixed in 2.0a3, I missed that it was reported in 2.0a4. We'll work on fixing it!

**Comment by Jerry-Ma** [comment]
Ah, I see. Sorry I didn't make it very clear. Much appreciated for all the work!

**Comment by dmontagu** [comment]
related — it also seems that the fact that the pydantic_extra is None is another bug

**Comment by Jerry-Ma** [comment]
I am glad that you are locating the cause of the issue so quickly. Looking forward to seeing this get fixed.
