### ISSUE TITLE
V2: compatibility shims for V1

### ISSUE THREAD

**Issue by yarikoptic** [pydantic/pydantic#5792]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This is pretty much a dedicated issue for an item in https://github.com/pydantic/pydantic/issues/4887#issuecomment-1468022094 where the issue no longer accepts comments .  

Even though there are plans for [automigration tool](https://github.com/pydantic/pydantic/issues/5013) which could help people migrate, I believe that providing shim and thus allowing for a smooth deprecation cycle would be of paramount help to the users where there might be an elaborate collection of dependencies which all could potentially use pydantic but would need to arrive to "migration" at different speeds. E.g. see how many of packages in our single project ecosystem use pydantic: https://github.com/dandi/dandi-schema/pull/178#issuecomment-1513374751 .

Thank you in advance

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
We more of less have this, see #5480.

More generally, we've tried to make V2 as compatible as possible with V1, we've also copied the V1 codebase into `pydantic.v1` so you can continue to use V1 while migrating to V2.

The remaining incompatibilities are mostly behavioural - e.g. we no longer coerce ints to strings, or lists to dicts. These things can't really be solved with a compatibility shim without a lot of work.

We'll continue to keep this under review and see how people find the migration process, if they find it particularly hard, we can add more support.

Hope this helps.
