### ISSUE TITLE
Numpy type annotations result in ValidatorIterator fields

### ISSUE THREAD

**Issue by flaport** [pydantic/pydantic#5811]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi,

Im currently using pydantic==2.0a4 and something weird is going on when using numpy type annotations. I have the following pydantic model:

```python
import numpy as np
from numpy.typing import NDArray
from pydantic import BaseModel, field_validator

class MyModel(BaseModel):
    x: int
    y: NDArray[np.float64]
    
    class Config:
        arbitrary_types_allowed=True
        
model = MyModel2(x='5', y=np.array([4.0]))
print(model)
```

which outputs

```
x=5 y=ValidatorIterator(index=0, schema=None)
```

I'm not sure what this ValidatorIterator is.

I also tried adding a custom validator to the y-field:

```python
class MyModel2(BaseModel):
    x: int
    y: NDArray[np.float64]
    
    @field_validator("y", mode='before')
    def validate_y(cls, y):
        return y
    
    class Config:
        arbitrary_types_allowed=True
```

But this did not solve anything.

Do you know what's going on?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: /home/flaport/.anaconda/envs/pyd/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
                     platform: Linux-6.3.2-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
`ValidatorIterator` is a generator which will validate members of the input as it's iterated.

You probably want to customize validation using an argument to annotated. I'm afk but I'll make sure to reply with an example on Monday. Unless someone else can help sooner?

**Comment by flaport** [comment]
Something like this seems indeed to work, but I'm not 100% sure if this is the recommended way of using this iterator...

```python
class MyModel(BaseModel):
    x: int
    y: NDArray[np.float64]
    
    @field_validator("y")
    def validate_y(cls, y):
        return np.float64(next(y))
    
    class Config:
        arbitrary_types_allowed=True
```

**Comment by dmontagu** [comment]
I suspect the issue here is that `NDArray` is caught as a subclass of Iterable, which we subsequently handle via producing a generator. @samuelcolvin I think this is rather unfortunate behavior to have as the default. I'll look into how we can improve this, given its ubiquity I do think it would be good if we could do a better job of handling NDArray out of the box, even if we don't want to add numpy as even a testing dependency of pydantic.

**Comment by dmontagu** [comment]
@flaport I don't think that will have quite the behavior you want.

I think this is closer, though perhaps still not quite ideal, but might get your code behaving closer to what you want:
```python
from typing import Type, Any, Iterable, Tuple, List, Annotated

import numpy as np
import numpy.typing as npt
from pydantic_core import CoreSchema, core_schema

from pydantic.types import TransformSchema


class _NdArrayAnnotation:
    @classmethod
    def __prepare_pydantic_annotations__(
        cls, _source: Type[Any], annotations: Iterable[Any]
    ) -> Tuple[Any, List[Any]]:
        def transform(schema: CoreSchema) -> CoreSchema:
            return core_schema.union_schema(
                [
                    core_schema.is_instance_schema(np.ndarray),
                    core_schema.no_info_after_validator_function(lambda v: np.ndarray(v), schema)
                ]
            )

        return list, list(annotations) + [TransformSchema(transform)]


# Use PydanticNdArray as the annotation in models for fields of type NDArray
PydanticNdArray = Annotated[npt.NDArray, _NdArrayAnnotation]
```
I will look into getting pydantic to handle this better without needing all of this boilerplate though.

**Comment by dmontagu** [comment]
@Sam

**Comment by dmontagu** [comment]
Okay, I think the right immediate-term solution to this is to not do this special handling of proper subclasses of Iterable (or Sequence). We've talked about this before and @adriangb did some work in this direction, and I think the behavior is better (especially for NDArray) with the simple change that forces you to add the `arbitrary_types_allowed=True` thing.

I'll open a PR for it.

**Comment by adriangb** [comment]
> @samuelcolvin @adriangb I'm thinking one thing it might make sense for us to do is export `pydantic._internal._std_types_schema.schema_function`. I know we've talked about this before and rejected it, but this would make it easier to register the schema function for a type, so that you can do something like:

I agree we should have something. I'd lean more towards allowing a callback with the same signature as `__get_pydantic_core_schema__` as part of `Config`. The advantages are:
- familiar API w/other usages of custom types
- lets you decide if you want to intercept before we look at the type or be a fallback
- lets you decided if you want to handle subclasses or only a specific type
