### ISSUE TITLE
Mention v2 in contributing to pydantic docs

### ISSUE THREAD

**Issue by mdavis-xyz** [pydantic/pydantic#5823]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I want to write a fix for a bug that affects v1 and v2.

I am wondering, is it worth me writing a fix? Will you accept a fix, or are you too busy working on V2? In [the blog](https://docs.pydantic.dev/latest/blog/pydantic-v2/) you said you'll close a lot of PRs for v1. So should I not bother?

Will fixes continue to be backported to V1? Which branch should I start with if I'm writing a fix for both?

I believe the answers to those questions should be listed on the["Contributing to pydantic"](https://docs.pydantic.dev/latest/contributing/) page.

### Example Code

```Python
N/A
```

### Python, Pydantic & OS Version

```Text
N/A
```

**Comment by samuelcolvin** [comment]
Fair point. @tpdorsey please include a note on this in your changes to the contribution guide.

We're only accepting bug fixes to v1, so submit a fix to v1, use the `1.10-fixes` branch.

If you have a fix that really applies to both branches, submit it to `main` and we have a bot which can backport the fix to v1.

**Comment by mdavis-xyz** [comment]
I was going to write a fix for #5821. But it looks like someone beat me to it.

(But it's still good to update the contribution guide.)

**Comment by tpdorsey** [comment]
Closed by https://github.com/pydantic/pydantic/pull/5855
