### ISSUE TITLE
Datetime with timezone type

### ISSUE THREAD

**Issue by tim-habitat** [pydantic/pydantic#5829]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be great to have a type that enforce timezone is included in a `datetime`
As an example:
```python
from pydantic import BaseModel, TimeZoneAwareDatetime
from datetime import datetime, timezone

class LoveTimeZone(BaseModel):
  dt: TimeZoneAwareDatetime["UTC"]

time_1 = LoveTimeZone(dt=datetime(2023,5,23, tzinfo=timezone.utc))  # ok
time_2 = LoveTimeZone(dt=dt=datetime(2023,5,23)  # fails
```

For accepted timezone, we could use `zoneinfo.available_timezones()` from [here](https://docs.python.org/3/library/zoneinfo.html#zoneinfo.available_timezones)

Currently i usually implement a `validator` to do this, but it feels like it would be a great addition to your fantastic library!

Let me know if i should detail more things.
Thanks

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by zyv** [comment]
This is implemented as `AwareDatetime`, is it not?

https://docs.pydantic.dev/latest/usage/types/datetime/

**Comment by zyv** [comment]
P.S. Oh, sorry, it seems you mean not just enforce the presence of the timezone, but also a specific timezone.

I guess the best way would be to implement the type as

```python
TimeZoneAwareDatetime[T] = Annotated[AwareDatetime, AfterValidator(lambda d: d.astimezone(typing.get_args(T)[0]))]

class LoveTimeZone(BaseModel):
    dt: TimeZoneAwareDatetime[Literal[datetime.UTC]]

```

You can tune the logic to your liking - normalise or error. Also, not sure the trip via `Literal` is really necessary, probably better use `TzInfo` type. It all needs some thinking, but you get the idea...

**Comment by adriangb** [comment]
Yup something like that is the way to go:

```python
from datetime import datetime, timezone
from typing import Annotated, TypeVar

from pydantic import TypeAdapter, AfterValidator
import pytz

T = TypeVar('T')

UTCDateTime = Annotated[datetime, AfterValidator(lambda d: d.astimezone(timezone.utc))]


ta = TypeAdapter(UTCDateTime)

print(ta.validate_python(datetime.now()))
#> 2023-07-25 11:19:34.082282+00:00
print(ta.validate_python(pytz.timezone('America/New_York').fromutc(datetime.now())))
#> 2023-07-25 13:20:56.483565+00:00
```
