### ISSUE TITLE
Field type Constrained Strings Attribute Error

### ISSUE THREAD

**Issue by wcrum** [pydantic/pydantic#5840]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When testing types from `BaseModel.__fields__[field].type_` to their corresponding type fails in constrained types. 

https://github.com/pydantic/pydantic/blob/bf875f67262b1536fdd376098fd03ac13c58ebe2/pydantic/v1/types.py#L465

Seems like `type` is generated and `ConstrainedStrValue` isn't a real Pydantic class. Is there any way to test types to the field types?

### Example Code

```Python
from pydantic import BaseModel
from pydantic import constr
from pydantic import types
from pydantic.types import ConstrainedStr

# Will fail
# from pydantic.types import ConstrainedStrValue

class MyModel(BaseModel):
    myString: str
    myConstrainedString: constr(regex="([ABC])")

model = MyModel(myString = "def", myConstrainedString = "A")

print(model.__fields__["myString"].type_ == str) # True
print(model.__fields__["myString"].type_ == constr) # False
print(model.__fields__["myString"].type_ == constr(regex="([ABC])")) # False
print(model.__fields__["myString"].type_ == ConstrainedStr) # False
# print(model.__fields__["myString"].type_ == ConstrainedStrValue) Doesnt exit
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.2
            pydantic compiled: False
                 install path: C:\Users\[REMOVED]\python-3.10.4.amd64\Lib\pydantic
               python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment]
AFAIK, there's no way to do what you want, and also, not sure what's the use case for that.

I'll be closing this since on V2 we've removed the `ConstrainedStr`, and `constr` is actually a well defined `Annotated[str, ...]` type.

**Comment by wcrum** [comment]
Thanks for the feedback. Realized I just need to move to `v2` anyway.
