### ISSUE TITLE
pydantic.mypy doesn't respect metaclass arguments.

### ISSUE THREAD

**Issue by cal-pratt** [pydantic/pydantic#5858]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

It seems like when using metaclass arguments for the base model (e.g. `class Foo(BaseModel, arg1=..., arg2=...)`) that pydantic.mypy ignores them. I found this out when setting `allow_population_by_field_name` this way. Note that I am running with the `init_typed=True` setting.

The options do appear to work at runtime, just not not during type checking.

As a workaround the `Config` nested class is still respected by pydantic.mypy, so this gets me out of hot water.

Apologies if this is a duplicate, after searching I couldn't find any matches. Feel free to close if so!

### Example Code

```Python
from pydantic import BaseModel, Field


class MypyCorrectError(BaseModel):
    i: int = Field(2, alias="j")

    class Config:
        allow_population_by_field_name = True


# error: Argument "i" to "MypyCorrectError" has incompatible type "None"; expected "int"  [arg-type]
MypyCorrectError(i=None)


class MypyWrongError(BaseModel, allow_population_by_field_name=True):
    i: int = Field(alias="j")


# error: Missing named argument "j" for "MypyWrongError"  [call-arg]
MypyWrongError(i=None)


class MypyFalsePositive(BaseModel, allow_population_by_field_name=True):
    i: int = Field(2, alias="j")


# No error listed for using None instead of int.
MypyFalsePositive(i=None)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
pydantic compiled: True
install path: /Users/.../lib/python3.10/site-packages/pydantic
python version: 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-13.3.1-arm64-i386-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment]
What's the mypy version you are using?

For `mypy==1.1.1`, I have the following:

```bash
❯ mypy main.py                      
main.py:12: error: Unexpected keyword argument "i" for "MypyCorrectError"  [call-arg]
main.py:20: error: Unexpected keyword argument "i" for "MypyWrongError"  [call-arg]
main.py:28: error: Unexpected keyword argument "i" for "MypyFalsePositive"  [call-arg]
Found 3 errors in 1 file (checked 1 source file)
```

Which seems alright?

**Comment by cal-pratt** [comment]
> What's the mypy version you are using?

```
$ pip freeze | grep mypy
mypy==1.3.0
mypy-extensions==1.0.0
```

I just tried resetting to `1.1.1` and still get the odd behavior:

```
$ mypy --version
mypy 1.1.1 (compiled: yes)
$ mypy test.py          
test.py:12: error: Argument "i" to "MypyCorrectError" has incompatible type "None"; expected "int"  [arg-type]
test.py:20: error: Missing named argument "j" for "MypyWrongError"  [call-arg]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by dmontagu** [comment]
@Kludex are you sure you had the plugin on?

It doesn't surprise me if this doesn't work, as I don't think we even try to collect the metaclass arguments currently, just look at the `class Config`.

I think this shouldn't be too hard to fix by editing `pydantic.mypy`, PR welcome, I will try to look at this when I get around to fixing mypy stuff. (I think a backport to v1 should be trivial if we fix it for v2, and I expect the same issue currently exists in v2.)

**Comment by cal-pratt** [comment]
@dmontagu Could you explain to me why I get the correct results when not specifying the plugin at all in my `mypy.ini` file? This part is really confusing me, as I thought without the plugin that we would not get generated constructor stubs?

**Comment by cal-pratt** [comment]
Oh, very interesting. Given that the metaclass arguments seem to be preserved in the default case, I wonder what other behavior happens when the plugin is enabled? At this point it would seem that enabling the plugin with no additional arguments causes a regression in mypy error detection. It would be probably be good to have the differences documented!

(P.S. I'm not against contributing, I can inquire about that internally 😄)

**Comment by dmontagu** [comment]
I don’t think the metaclass arguments are respected with the plugin off, I think it’s just that the only way it works has the behavior you want. I might be wrong about that.
