### ISSUE TITLE
Custom Data Type Example Fails with PydanticSchemaGenerationError

### ISSUE THREAD

**Issue by dominikbak** [pydantic/pydantic#5872]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Attempting to implement a custom data type following the documentation provided at https://docs.pydantic.dev/dev-v2/usage/types/custom/#classes-with-__get_validators__, causes an error, specifically PydanticSchemaGenerationError.

```
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class '__main__.PostCode'>. Setting `arbitrary_types_allowed=True` in the model_config may prevent this error.
```

### Example Code

```Python
import re

from pydantic import BaseModel

# https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation
post_code_regex = re.compile(
    r'(?:'
    r'([A-Z]{1,2}[0-9][A-Z0-9]?|ASCN|STHL|TDCU|BBND|[BFS]IQQ|PCRN|TKCA) ?'
    r'([0-9][A-Z]{2})|'
    r'(BFPO) ?([0-9]{1,4})|'
    r'(KY[0-9]|MSR|VG|AI)[ -]?[0-9]{4}|'
    r'([A-Z]{2}) ?([0-9]{2})|'
    r'(GE) ?(CX)|'
    r'(GIR) ?(0A{2})|'
    r'(SAN) ?(TA1)'
    r')'
)


class PostCode(str):
    """
    Partial UK postcode validation. Note: this is just an example, and is not
    intended for use in production; in particular this does NOT guarantee
    a postcode exists, just that it has a valid format.
    """

    @classmethod
    def __get_validators__(cls):
        # one or more validators may be yielded which will be called in the
        # order to validate the input, each validator will receive as an input
        # the value returned from the previous validator
        yield cls.validate

    @classmethod
    def __get_pydantic_json_schema__(cls, field_schema):
        # __get_pydantic_json_schema__ should mutate the dict it receives
        # in place, the returned value will be ignored
        field_schema.update(
            # simplified regex here for brevity, see the wikipedia link above
            pattern='^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
            # some example postcodes
            examples=['SP11 9DG', 'w1j7bu'],
        )

    @classmethod
    def validate(cls, v):
        if not isinstance(v, str):
            raise TypeError('string required')
        m = post_code_regex.fullmatch(v.upper())
        if not m:
            raise ValueError('invalid postcode format')
        # you could also return a string here which would mean model.post_code
        # would be a string, pydantic won't care but you could end up with some
        # confusion since the value's type won't match the type annotation
        # exactly
        return cls(f'{m.group(1)} {m.group(2)}')

    def __repr__(self):
        return f'PostCode({super().__repr__()})'


class Model(BaseModel):
    post_code: PostCode


model = Model(post_code='sw8 5el')
print(model)
print(model.post_code)
print(Model.model_json_schema())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: /opt/miniconda3/envs/***/lib/python3.10/site-packages/pydantic
               python version: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 19:01:19) [Clang 14.0.6 ]
                     platform: macOS-13.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by adriangb** [comment]
That looks like the V1 code. The link you posted (which is the latest V2 docs) currently has the following:

```python
import re
from typing import Any

from pydantic_core import PydanticCustomError, core_schema
from typing import Annotated

from pydantic import BaseModel, ValidationError
from pydantic.annotated import GetCoreSchemaHandler, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue

# https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation
post_code_regex = re.compile(
    r'(?:'
    r'([A-Z]{1,2}[0-9][A-Z0-9]?|ASCN|STHL|TDCU|BBND|[BFS]IQQ|PCRN|TKCA) ?'
    r'([0-9][A-Z]{2})|'
    r'(BFPO) ?([0-9]{1,4})|'
    r'(KY[0-9]|MSR|VG|AI)[ -]?[0-9]{4}|'
    r'([A-Z]{2}) ?([0-9]{2})|'
    r'(GE) ?(CX)|'
    r'(GIR) ?(0A{2})|'
    r'(SAN) ?(TA1)'
    r')'
)


class PostCodeAnnotation:
    """
    Partial UK postcode validation. Note: this is just an example, and is not
    intended for use in production; in particular this does NOT guarantee
    a postcode exists, just that it has a valid format.
    """

    @classmethod
    def __get_pydantic_core_schema__(
        cls, _source_type: Any, _handler: GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        return core_schema.no_info_after_validator_function(
            cls.validate,
            core_schema.str_schema(),
        )

    @classmethod
    def __get_pydantic_json_schema__(
        cls, schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        json_schema = handler(schema)
        json_schema.update(
            # simplified regex here for brevity, see the wikipedia link above
            pattern='^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
            # some example postcodes
            examples=['SP11 9DG', 'W1J 7BU'],
        )
        return json_schema

    @classmethod
    def validate(cls, v: str):
        m = post_code_regex.fullmatch(v.upper())
        if m:
            return f'{m.group(1)} {m.group(2)}'
        else:
            raise PydanticCustomError('postcode', 'invalid postcode format')


class Model(BaseModel):
    post_code: Annotated[str, PostCodeAnnotation]


model = Model(post_code='sw8 5el')
print(model)
#> post_code='SW8 5EL'
print(model.post_code)
#> SW8 5EL
print(Model.model_json_schema())
"""
{
    'type': 'object',
    'properties': {
        'post_code': {
            'type': 'string',
            'pattern': '^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
            'examples': ['SP11 9DG', 'W1J 7BU'],
            'title': 'Post Code',
        }
    },
    'required': ['post_code'],
    'title': 'Model',
}
"""
try:
    Model(post_code='invalid')
except ValidationError as e:
    print(e.errors())
    """
    [
        {
            'type': 'postcode',
            'loc': ('post_code',),
            'msg': 'invalid postcode format',
            'input': 'invalid',
        }
    ]
    """
```

Which works on 7bc9c6525a81680c0dd9df3558ed5f33345a77c2

**Comment by dominikbak** [comment]
> That looks like the V1 code. The link you posted (which is the latest V2 docs) currently has the following:
> 
> ```python
> import re
> from typing import Any
> 
> from pydantic_core import PydanticCustomError, core_schema
> from typing import Annotated
> 
> from pydantic import BaseModel, ValidationError
> from pydantic.annotated import GetCoreSchemaHandler, GetJsonSchemaHandler
> from pydantic.json_schema import JsonSchemaValue
> 
> # https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom#Validation
> post_code_regex = re.compile(
>     r'(?:'
>     r'([A-Z]{1,2}[0-9][A-Z0-9]?|ASCN|STHL|TDCU|BBND|[BFS]IQQ|PCRN|TKCA) ?'
>     r'([0-9][A-Z]{2})|'
>     r'(BFPO) ?([0-9]{1,4})|'
>     r'(KY[0-9]|MSR|VG|AI)[ -]?[0-9]{4}|'
>     r'([A-Z]{2}) ?([0-9]{2})|'
>     r'(GE) ?(CX)|'
>     r'(GIR) ?(0A{2})|'
>     r'(SAN) ?(TA1)'
>     r')'
> )
> 
> 
> class PostCodeAnnotation:
>     """
>     Partial UK postcode validation. Note: this is just an example, and is not
>     intended for use in production; in particular this does NOT guarantee
>     a postcode exists, just that it has a valid format.
>     """
> 
>     @classmethod
>     def __get_pydantic_core_schema__(
>         cls, _source_type: Any, _handler: GetCoreSchemaHandler
>     ) -> core_schema.CoreSchema:
>         return core_schema.no_info_after_validator_function(
>             cls.validate,
>             core_schema.str_schema(),
>         )
> 
>     @classmethod
>     def __get_pydantic_json_schema__(
>         cls, schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
>     ) -> JsonSchemaValue:
>         json_schema = handler(schema)
>         json_schema.update(
>             # simplified regex here for brevity, see the wikipedia link above
>             pattern='^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
>             # some example postcodes
>             examples=['SP11 9DG', 'W1J 7BU'],
>         )
>         return json_schema
> 
>     @classmethod
>     def validate(cls, v: str):
>         m = post_code_regex.fullmatch(v.upper())
>         if m:
>             return f'{m.group(1)} {m.group(2)}'
>         else:
>             raise PydanticCustomError('postcode', 'invalid postcode format')
> 
> 
> class Model(BaseModel):
>     post_code: Annotated[str, PostCodeAnnotation]
> 
> 
> model = Model(post_code='sw8 5el')
> print(model)
> #> post_code='SW8 5EL'
> print(model.post_code)
> #> SW8 5EL
> print(Model.model_json_schema())
> """
> {
>     'type': 'object',
>     'properties': {
>         'post_code': {
>             'type': 'string',
>             'pattern': '^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
>             'examples': ['SP11 9DG', 'W1J 7BU'],
>             'title': 'Post Code',
>         }
>     },
>     'required': ['post_code'],
>     'title': 'Model',
> }
> """
> try:
>     Model(post_code='invalid')
> except ValidationError as e:
>     print(e.errors())
>     """
>     [
>         {
>             'type': 'postcode',
>             'loc': ('post_code',),
>             'msg': 'invalid postcode format',
>             'input': 'invalid',
>         }
>     ]
>     """
> ```
> 
> Which works on [7bc9c65](https://github.com/pydantic/pydantic/commit/7bc9c6525a81680c0dd9df3558ed5f33345a77c2)

Yeah, it was updated in the meantime. Thanks
