### ISSUE TITLE
Support per field configuration where possible

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5881]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently it's impossible to define config parameters related to fields behavior on a per field basis.

It seems useful to be able to define field related configuration per field.

Instead of just:

```py
class Model(BaseModel):
    model_config = ConfigDict(allow_inf_nan=False)
    field_a: float
    field_b: float
```

It could be something like this:

```py
    model_config = ConfigDict(allow_inf_nan=False)
    field_a: float = Field(allow_inf_nan=True)
    field_b: float
```

In such a way that per field configuration overrides model configuration values.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [x] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by adriangb** [comment]
Should every option available in ConfigDict also be available in Field then? Seems like a good first step would be to allow ConfigDict in Annotated such that one can do:

```python
AllowInfOrNan = Annotated[FloatT, ConfigDict(allow_inf_or_nan=True)]

x: AllowInfOrNan[Annotated[float, Gt(0]] 
```

**Comment by lig** [comment]
Well, if those options could affect field behavior then yes. However, @samuelcolvin mentioned that not all of them make sense for a Field. Maybe it would be better to introduce a `FieldConfig` which is a subset of the `ConfigDict`.

**Comment by adriangb** [comment]
Seems then that we should have FieldConfig and ModelConfig with ModelConfig being a subclass of FieldConfig and where the field specific options apply to all of the fields in that model.

**Comment by adriangb** [comment]
Note that `ConfigDict` can't be the thing we put in `Annotated` since at runtime it's a plain dict and we would have no way of identifying it.

**Comment by Kludex** [comment]
Is this still relevant? @lig

**Comment by sydney-runkle** [comment]
I think it makes sense to close this for now. If there are specific config params we want to support on the field level, those can be addressed individually 👍
