### ISSUE TITLE
No AttributeError on attempt to delete nonexisting Model field (pypy3.7)

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#5899]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When attempting to delete a model attribute that doesn't exist on pypy3.7 there is no `AttributeError` raised.

### Example Code

```Python
from pydantic import BaseModel


class Model(BaseModel):
    some_field: str

m = Model(some_field='value')
assert not hasattr(m, 'other_field')

del m.other_field  # just passes without any error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.36.0 release build profile
               python version: 3.7.13 (7e0ae751533460d5f89f3ac48ce366d8642d1db5, Mar 29 2022, 06:03:31) [PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
                     platform: Linux-6.2.15-300.fc38.x86_64-x86_64-with-fedora-38-Thirty_Eight
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by samuelcolvin** [comment]
I'd call that a bug in pypy.

We didn't even used to test with pypy, it's very slow with pydantic-core and I suspect the download numbers are tiny.

**Comment by lig** [comment]
They don't even support Python 3.7 in latest releases. I've filed it for historic purposes only. I honestly believe there isn't much we can do here.

**Comment by lig** [comment]
Interestingly the bug doesn't reproduce for regular classes and dataclasses.

**Comment by samuelcolvin** [comment]
Good to find and log, let's not waste time on it.
