### ISSUE TITLE
FieldInfo does not unwrap and parse NewType

### ISSUE THREAD

**Issue by Goldziher** [pydantic/pydantic#5907]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi!

So I've started the process of adjusting [polyfactory](https://github.com/litestar-org/polyfactory/pull/222) to pydantic v2. This is a library to generate testing data from models, including pydantic models, and as such we are doing low level stuff that relies on internals. 

I have the following test:

```python
def test_constrained_new_types() -> None:
    ConBytes = NewType("ConBytes", conbytes(min_length=2, max_length=4))  # type: ignore[misc]
    ConStr = NewType("ConStr", constr(min_length=10, max_length=15))  # type: ignore[misc]
    ConInt = NewType("ConInt", conint(gt=100, lt=110))  # type: ignore[misc]
    ConFloat = NewType("ConFloat", confloat(lt=-100))  # type: ignore[misc]
    ConDecimal = NewType("ConDecimal", condecimal(ge=Decimal(6), le=Decimal(8)))  # type: ignore[misc]
    ConDate = NewType("ConDate", condate(gt=date.today()))  # type: ignore[misc]
    ConMyPositiveFloat = NewType("ConMyPositiveFloat", PositiveFloat)

    if pydantic_version == 1:
        ConList = NewType("ConList", conlist(item_type=int, min_length=3))  # type: ignore[misc]
        ConSet = NewType("ConSet", conset(item_type=int, min_length=4))  # type: ignore[misc]
        ConFrozenSet = NewType("ConFrozenSet", confrozenset(item_type=str, min_length=5))  # type: ignore[misc]
    else:
        ConList = NewType("ConList", conlist(item_type=int, min_length=3))  # type: ignore[misc]
        ConSet = NewType("ConSet", conset(item_type=int, min_length=4))  # type: ignore[misc]
        ConFrozenSet = NewType("ConFrozenSet", confrozenset(item_type=str, min_length=5))  # type: ignore[misc]

    class ConstrainedModel(BaseModel):
        conbytes_field: ConBytes
        constr_field: ConStr
        conint_field: ConInt
        confloat_field: ConFloat
        condecimal_field: ConDecimal
        condate_field: ConDate
        conlist_field: ConList
        conset_field: ConSet
        confrozenset_field: ConFrozenSet
        conpositive_float_field: ConMyPositiveFloat

    class MyFactory(ModelFactory):
        __model__ = ConstrainedModel

    result = MyFactory.build()

    # we want to make sure that NewType is correctly unwrapped retaining
    # original type and its attributes. More elaborate testing of constrained
    # fields is done in tests/constraints/
    assert isinstance(result.conbytes_field, bytes)
    assert 2 <= len(result.conbytes_field) <= 4

    assert isinstance(result.constr_field, str)
    assert 10 <= len(result.constr_field) <= 15

    assert isinstance(result.conint_field, int)
    assert 100 < result.conint_field < 110

    assert isinstance(result.confloat_field, float)
    assert result.confloat_field < -100

    assert isinstance(result.condecimal_field, Decimal)
    assert Decimal(6) <= result.condecimal_field <= Decimal(8)

    assert isinstance(result.condate_field, date)
    assert result.condate_field > date.today()

    assert isinstance(result.conlist_field, list)
    assert len(result.conlist_field) >= 3

    assert isinstance(result.conset_field, set)
    assert len(result.conset_field) >= 4

    assert isinstance(result.confrozenset_field, frozenset)
    assert len(result.confrozenset_field) >= 5

    assert isinstance(result.conpositive_float_field, float)
    assert result.conpositive_float_field > 0
```

This works in pydantic v1, but in pydantic v2 it fails. After debugging this I see that FieldInfo.metadata is None:

<img width="671" alt="Screenshot 2023-05-28 at 08 55 51" src="https://github.com/pydantic/pydantic/assets/30733348/7cf00e91-81d8-487e-8c05-5493e059e30e">

This suggests to me that the NewType is not unwrapped but treated as is. 

I would suggest that new types are always unwrapped. We have a helper in place for this:

```python
def is_new_type(annotation: Any) -> "TypeGuard[type[NewType]]":
    """Determine whether a given annotation is 'typing.NewType'.

    :param annotation: A type annotation.

    :returns: A typeguard.
    """
    return hasattr(annotation, "__supertype__")

def unwrap_new_type(annotation: Any) -> Any:
    """Return base type if given annotation is a type derived with NewType, otherwise annotation.

    :param annotation: A type annotation, possibly one created using 'types.NewType'

    :returns: The unwrapped annotation.
    """
    while is_new_type(annotation):
        annotation = annotation.__supertype__

    return annotation
```

### Python, Pydantic & OS Version

```Text
python 3.11.2
pydantic 2.04a
MacOs
```

**Comment by Goldziher** [comment]
Hi, thanks for looking into this @dmontagu and sorry for my latency. 

Pydantic does what is written on the box, that's not an issue. But I expected the `field.metadata` to be populated and usable, but it seems that with instances of `NewType` the metadata of the wrapped type is not parsed and made available on the field. This is problematic for libraries such as ours, because we rely on pydantic information - and in this case it's not externalized.

**Comment by samuelcolvin** [comment]
Maybe you could take a crack at a PR, to explain what you need, I'm definitely happy to review a PR.

**Comment by Goldziher** [comment]
> Maybe you could take a crack at a PR, to explain what you need, I'm definitely happy to review a PR.

If I find the time, I will. Its not likely though in the near future, I have litestar + my own nascant startup in the pipeline...

**Comment by dmontagu** [comment]
@Goldziher I don't think we understand what your issue is, and we can't run your code example; I don't think we will be able to help without more detail.

**Comment by Goldziher** [comment]
> @Goldziher I don't think we understand what your issue is, and we can't run your code example; I don't think we will be able to help without more detail.

I appreciate your willingness. Let me see if I can cook up a quick test demo later this evening that will illustrate the issue.

**Comment by lig** [comment]
@Goldziher Any news on this one?

**Comment by Goldziher** [comment]
> @Goldziher Any news on this one?

I simply bypassed the issue on my end. Sorry, Im afraid I have no capacity at present at all

**Comment by lig** [comment]
I'm closing this one as not enough has been provided to understand what to do here. If somebody has a similar issue and is willing to provide more info, please, open a new issue.
