### ISSUE TITLE
last `xfail` in documentation

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5911]
Following #5910, there's one remaining `xfail` in docs examples.

@dmontagu as the generics expert, could you take a look at it:

https://github.com/pydantic/pydantic/blob/e2c2121e4962d0e07b7d9ecc2ee406d7de0691c6/docs/usage/types/custom.md?plain=1#L164-L249

**Comment by adriangb** [comment]
Fixed in #5935
