### ISSUE TITLE
Unable to parse Unix time string

### ISSUE THREAD

**Issue by unights** [pydantic/pydantic#5914]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

According to the documentation for [datetime types](https://docs.pydantic.dev/dev-v2/usage/types/datetime/#datetime-types)  the following string types are acceptable:

- `YYYY-MM-DD[T]HH:MM[:SS[.ffffff]][Z[±]HH[:]MM]]]`
- `int` or `float` as a string (assumed as Unix time)

But currently the string of Unix time cannot be parsed as datetime.

### Example Code

```Python
from datetime import datetime

from pydantic import BaseModel

class M(BaseModel):
    tm: datetime


a = M(tm=0)
# tm=datetime.datetime(1970, 1, 1, 0, 0)

b = M(tm='1970-01-01 00:00:00')
# tm=datetime.datetime(1970, 1, 1, 0, 0)

c = M(tm=1672531200000)
# tm=datetime.datetime(2023, 1, 1, 0, 0)

d = M(tm='1672531200000')
# Input should be a valid datetime, invalid date separator, expected `-` [type=datetime_parsing, input_value='1672531200000', input_type=str]

e = M(tm='0')
# Input should be a valid datetime, input is too short [type=datetime_parsing, input_value='0', input_type=str]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4                       
        pydantic-core version: 0.30.0 release build profile
                 install path: D:\Projects\venv\Lib\site-packages\pydantic
               python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
Ye, I think the docs are wrong and we don't try to parse strings as unix timestamp.

Question is where we should support this it fix the docs?

**Comment by unights** [comment]
Well, we really don't think about implementing it? 

I think we can totally convert the string whose characters are all ascii digits to a float in `pydantic-core`.

**Comment by samuelcolvin** [comment]
Well, ideally it should be fixed in [speedate](https://github.com/pydantic/speedate), also should we parse only numeric strings to ints, or also support float parsing, e.g. `1672531200.123`?
