### ISSUE TITLE
FastAPI response_model when returning Pydantic models

### ISSUE THREAD

**Issue by tiangolo** [pydantic/pydantic#5921]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

In FastAPI, I allow returning Pydantic models or dicts (or other objects, e.g. DB ORM instances), and the data is filtered by the response model/type using Pydantic.

I do a lot of trickery in Pydantic v1 to recursively clone a whole tree of models and the models used in its fields to avoid the checks that allow `isinstance()` to pass as valid, because if there's a `UserBase` used as the response model, and then a `UserCreate` that contains a password, if `UserCreate` is accepted as valid, the password would be leaked in the response (see the example below).

In Pydantic v2, the same approach currently raises a validation error, or doing some tricks returns leaking the data. If I clone the top-level model to change the config, it only applies to that top level model, which means I would have to do the same fragileish recursive cloning trickery from v1. That might ultimately be the way to go, but I'm showing here the example use case to make it easier to track it.

---

There are a couple of possible approaches to try and handle the internals in FastAPI, always with a `TypeAdapter`, I'm not including that here as the approach might vary and evolve, I'm only including the FastAPI example with the expected/desired end result, as I think it's probably easier to think about the desired result without yet constraining it to specific implementation details (in case we find a better way to do it).

### Example Code

```Python
from fastapi import FastAPI
from pydantic import BaseModel
from fastapi.testclient import TestClient

app = FastAPI()


class UserBase(BaseModel):
    email: str


class UserCreate(UserBase):
    password: str


class UserDB(UserBase):
    hashed_password: str


class PetDB(BaseModel):
    name: str
    owner: UserDB


class PetOut(BaseModel):
    name: str
    owner: UserBase


@app.post("/users/", response_model=UserBase)
async def create_user(user: UserCreate):
    return user


# Expected:
# {"email": "string"}


@app.get("/pets/{pet_id}", response_model=PetOut)
async def read_pet(pet_id: int):
    user = UserDB(
        email="johndoe@example.com",
        hashed_password="secrethashed",
    )
    pet = PetDB(name="Nibbler", owner=user)
    return pet


# Expected:
# {
#   "name": "Nibbler",
#   "owner": {
#     "email": "johndoe@example.com"
#   }
# }


@app.get("/pets/", response_model=list[PetOut])
async def read_pets():
    user = UserDB(
        email="johndoe@example.com",
        hashed_password="secrethashed",
    )
    pet1 = PetDB(name="Nibbler", owner=user)
    pet2 = PetDB(name="Zoidberg", owner=user)
    return [pet1, pet2]


# Expected:
# [
#   {
#     "name": "Nibbler",
#     "owner": {
#       "email": "johndoe@example.com"
#     }
#   },
#   {
#     "name": "Zoidberg",
#     "owner": {
#       "email": "johndoe@example.com"
#     }
#   }
# ]

client = TestClient(app)


def test_create_user():
    response = client.post(
        "/users", json={"email": "johndoe@example.com", "password": "secret"}
    )
    # insert_assert(response.json())
    assert response.json() == {"email": "johndoe@example.com"}


def test_get_pet():
    response = client.get("/pets/1")
    # insert_assert(response.json())
    assert response.json() == {
        "name": "Nibbler",
        "owner": {"email": "johndoe@example.com"},
    }


def test_get_pets():
    response = client.get("/pets/")
    # insert_assert(response.json())
    assert response.json() == [
        {"name": "Nibbler", "owner": {"email": "johndoe@example.com"}},
        {"name": "Zoidberg", "owner": {"email": "johndoe@example.com"}},
    ]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.36.0 release build profile
                 install path: /Users/user/code/pydantic/pydantic
               python version: 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

**Comment by samuelcolvin** [comment]
Thanks, added to #5919

**Comment by samuelcolvin** [comment]
after discussion:
* we're going to provide a "validation time" `from_attributes` argument which takes priority over `from_attributes` config switch
* we're going to remove the strict behaviour of pydantic models, [here](https://github.com/pydantic/pydantic-core/blob/3bd718cf1764a96ea4ac0bf24af7f003eb51d770/src/validators/model.rs#L154-L160)

**Comment by tiangolo** [comment]
For completeness, here's a comparable example in pure Pydantic (no FastAPI):

```Python
from pydantic import BaseModel, ConfigDict, TypeAdapter


class UserBase(BaseModel):
    email: str


class UserCreate(UserBase):
    password: str


class UserDB(UserBase):
    hashed_password: str


class PetDB(BaseModel):
    name: str
    owner: UserDB


class PetOut(BaseModel):
    name: str
    owner: UserBase


def test_create_user():
    user_base_ta = TypeAdapter(UserBase)
    user = UserCreate(email="johndoe@example.com", password="secret")
    result = user_base_ta.dump_python(user_base_ta.validate_python(user))
    assert result == {"email": "johndoe@example.com"}


def test_get_pet():
    pet_out_ta = TypeAdapter(PetOut)
    user = UserDB(
        email="johndoe@example.com",
        hashed_password="secrethashed",
    )
    pet = PetDB(name="Nibbler", owner=user)
    result = pet_out_ta.dump_python(pet_out_ta.validate_python(pet))
    assert result == {
        "name": "Nibbler",
        "owner": {"email": "johndoe@example.com"},
    }


def test_get_pets():
    list_pet_out_ta = TypeAdapter(list[PetOut])
    user = UserDB(
        email="johndoe@example.com",
        hashed_password="secrethashed",
    )
    pet1 = PetDB(name="Nibbler", owner=user)
    pet2 = PetDB(name="Zoidberg", owner=user)
    result = list_pet_out_ta.dump_python(list_pet_out_ta.validate_python([pet1, pet2]))
    assert result == [
        {"name": "Nibbler", "owner": {"email": "johndoe@example.com"}},
        {"name": "Zoidberg", "owner": {"email": "johndoe@example.com"}},
    ]
```

## Subclass

Note that currently the first test works and passes, because `UserCreate` is a subclass of `UserBase`.

The other tests fail with an error like:

```
ValidationError: 1 validation error for UserBase
  Input should be a valid dictionary [type=dict_type, input_value=UserCreate(email='johndoe...com', password='secret'), input_type=UserCreate]
    For further information visit https://errors.pydantic.dev/0.36.0/v/dict_type
```

...nevertheless, for the first test, for `CreateUser`, it doesn't really require a dict, it takes an instance of the subclass without complaints (even though it doesn't have `from_attributes=True`).

But it fails in the same way if `UserDB` doesn't inherit from `UserBase`:

```diff
class UserBase(BaseModel):
    email: str


- class UserCreate(UserBase):
+ class UserCreate(BaseModel):
+     email: str
    password: str


```

## `from_attributes`

The last two tests fail with the error above, but if `from_attributes` is set to `True` in `PetOut`, both tests pass:

```diff
class PetOut(BaseModel):
    name: str
    owner: UserBase

+    model_config = ConfigDict(from_attributes=True)
```

Notice that the tests pass even though `UserBase` doesn't have `from_attributes=True`, again because `UserDB` inherits from `UserBase`, which seems to have some special handling (despite not being a dict).

But if it no longer inherits but shares the same fields:

```diff
class UserBase(BaseModel):
    email: str


class UserCreate(UserBase):
    password: str


- class UserDB(UserBase):
+ class UserDB(BaseModel):
+    email: str
    hashed_password: str
```

...then the same validation error expecting a dict shows up.

```
ValidationError: 1 validation error for PetOut
owner
  Input should be a valid dictionary [type=dict_type, input_value=UserDB(email='johndoe@exa...password='secrethashed'), input_type=UserDB]
    For further information visit https://errors.pydantic.dev/0.36.0/v/dict_type
```

Notice that in the second test, the top level type is a list, and a list wouldn't have a way to have it configured with `from_attributes` at that level, so a "validation time" override for `from_attributes` would definitely work there.

**Comment by tiangolo** [comment]
This was solved by https://github.com/pydantic/pydantic/pull/5983 🎉
