### ISSUE TITLE
'color' is not recoginized by the IDE and type checkers.

### ISSUE THREAD

**Issue by Goldziher** [pydantic/pydantic#5924]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I encounter the issue in both the IDE and using pyright:

```shell
error: "color" is not a known member of module "pydantic" (reportGeneralTypeIssues)
```

It suggests that color is not declared. 

### Python, Pydantic & OS Version

```Text
python 3.11
pydantic 2.0a4
```

**Comment by samuelcolvin** [comment]
You probably mean `Color`.

@Kludex can you take a look.

Honestly I think we should deprecate `Color` and suggest people use `pydantic-extra-types`.

**Comment by Goldziher** [comment]
> You probably mean `Color`.
> 
> @Kludex can you take a look.
> 
> Honestly I think we should deprecate `Color` and suggest people use `pydantic-extra-types`.

No, i import `from pydantic.color import Color`

**Comment by samuelcolvin** [comment]
then something else must be wrong, with your setup, `from pydantic.color import Color` works fine for me on 2.0a4

**Comment by Goldziher** [comment]
> then something else must be wrong, with your setup, `from pydantic.color import Color` works fine for me on 2.0a4

there is nothing wrong with my setup, the issue is that color is not defined in `__all__` top level, and `Color` is not defined in all inside `color` and hence both the IDE and type checkers complain.

**Comment by samuelcolvin** [comment]
there is no `__all__` defined in `pydantic.color`, so that shouldn't be a problem.

**Comment by Goldziher** [comment]
> there is no `__all__` defined in `pydantic.color`, so that shouldn't be a problem.

And yet it is. As you can see from the pyright error - the issue its complaining about is that color is not a known member of pydantic, because its not declared in `__all__` top level. 

You can deprecate it of course, but thats a different thing.

**Comment by samuelcolvin** [comment]
modules shouldn't be defined in the top level `__init__.py::__all__` AFAIK.

If you think there's something wrong that can be fixed, please create a PR.

**Comment by Kludex** [comment]
I'm using `strict` mode on the IDE, and I'm running `pyright 1.1.310` and I can't reproduce with neither. How can I reproduce it with `pyright`?

**Comment by Goldziher** [comment]
> I'm using `strict` mode on the IDE, and I'm running `pyright 1.1.310` and I can't reproduce with neither. How can I reproduce it with `pyright`?

you can see it here: https://github.com/litestar-org/polyfactory/pull/222

**Comment by Goldziher** [comment]
ok, this is my bad - i didnt pin to v2 in my linting setup. Apologies.

**Comment by Kludex** [comment]
No problem. Thanks for coming back and letting us know. 🙏
