### ISSUE TITLE
from_attributes and optional fields

### ISSUE THREAD

**Issue by vitalik** [pydantic/pydantic#5937]
I'm experiencing different behaviour with the following code on pydantc1 and pydantic2:

```Python

class SomeModel(BaseModel):
    a: int
    b: int = None

    class Config:
        orm_mode = True
        from_attributes = True


class SomeObj:
    def __init__(self, a: int, b: int = None):
        self.a = a
        self.b = b


obj = SomeObj(a=1)
data = SomeModel.from_orm(obj).dict()
print(data)

```

pydantic1 prints:
```
{'a': 1, 'b': None}
```

while pydantic2 gives validation error:
```
  File "/tmp/.venv2/lib/python3.9/site-packages/pydantic/main.py", line 321, in model_validate
    return cls.__pydantic_validator__.validate_python(obj, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SomeModel
b
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/0.30.0/v/int_type
```

this works as epxeted btw
```Python
print(SomeModel(a=1).dict())
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: /tmp/.venv2/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  6 2022, 21:16:57)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
You need to define your field as an`Optional` field to get the right behavior in `V2`:

```
class SomeModel(BaseModel):
    a: int
    b: Optional[int] = None
```

**Comment by samuelcolvin** [comment]
we no longer convert `b: int = None` to `b: Optional[int] = None` implicitly in V2 - matching dataclass behaviour static typing expectations.

**Comment by vitalik** [comment]
@samuelcolvin but it's kinda inconsistent...

why this works:
```
SomeModel(a=1).model_dump()
```

but this not:
```
SomeModel.model_validate(obj)
```

I know this not the perfect way of typing, but that's the reality - many django-ninja and fastapi projects I see adopted marking optional values wihtout `Optional[]`

From what it looks like django-ninja upgrade to pydantic2 will not have breaking changes for end users, but this validation behaviour would be a breaking change


@tiangolo how is it on your end ? how often do you see people not using `Optional[int]` but just marking a default with `x: int = None`

**Comment by samuelcolvin** [comment]
Whether you use `SomeModel(a=1)` or `SomeModel.model_validate(obj)` should make no difference.

**Comment by samuelcolvin** [comment]
Can you give a full code example.

**Comment by samuelcolvin** [comment]
Looking at your code, from above there's a difference between a value that's omitted, and a value that's present but none.

`b` has an `int` validator, so the input must be an int, very simple.

If `b` is omitted, the default is used, you don't have "validate default" set, so any value is allowed.

* `SomeModel(a=1)` does not specify `b` - no error, default is used
* `SomeModel.model_validate(obj)` does specify `b`, the value is not a valid input for `int`, error

---

I firmly believe, having thought about this for years, that this is the cleaning implementation all round.

I don't want to change it.

**Comment by vitalik** [comment]
@samuelcolvin I understand, but it just this thing is very silent, people will be pulling hairs trying to understand the problem migrating from v1 to v2, and first thing they will start reporting bugs to me :)

maybe there should be some exception or at least a `warn` giving a hint that `Optional` is required when `from_attributes=True`

**Comment by samuelcolvin** [comment]
PR welcome to add a warning for this, we'd need to review it and consider the impact.

If people report this to your forward them to us.
