### ISSUE TITLE
Regression in model_dump when working with subclasses

### ISSUE THREAD

**Issue by jayrahdevore** [pydantic/pydantic#5941]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hello!  Today I've been trying to build an ORM for a use case that heavily uses generic base classes.  I noticed that at some level, when an extended model pattern is used at two levels and then is contained by another model--the deepest level looses its data in `model_dump` .

In the following example, I get the response I expect when printing the object, but seem to be loosing data when using `model_dump`.  I don't notice this behavior when running pydantic 1.10.8 `json()`

This is my output
```
>>> print(model)
type='extended' params=ExtendedParams(number=1)
>>> print(model.model_dump())
{'type': 'extended', 'params': {'number': 1}} # This is fine, we'll contain this another level

>>> contained_model = Container(item=model)
>>>print(contained_model)
item=ExtendedItem(type='extended', params=ExtendedParams(number=1)) # this is what we expect
>>>print(contained_model.model_dump())
{'item': {'type': 'extended', 'params': {}}} # unexpected!!
```

### Example Code

```Python
from pydantic import BaseModel


class BaseParams(BaseModel):
    pass


class ExtendedParams(BaseParams):
    number: int = 1


class Item(BaseModel):
    type: str
    params: BaseParams


class ExtendedItem(Item):
    type: str = "extended"
    params: ExtendedParams


class Container(BaseModel):
    item: Item


model = ExtendedItem(params=ExtendedParams())

# this prints as expected
print(model)
# print(model.dict())

print(model.model_dump())  # for v2


contained_model = Container(item=model)

print(contained_model)
# print(contained_model.dict())

# Container.item.params is empty--this isn't as expected!
print(contained_model.model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: /home/username/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jun 14 2022, 14:20:57) [GCC 9.4.0]
                     platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by adriangb** [comment]
This is the intended behavior. See https://github.com/pydantic/pydantic/issues/5921 for reasoning

**Comment by dmontagu** [comment]
For what it's worth, I think this should be possible to work around through the use of a custom annotation to make it so the core schema uses `core_schema.any_schema()` for serialization. If this is important to you, let us know and we should be able to provide more guidance.

**Comment by jayrahdevore** [comment]
Thank you all for your responses.  At this point, I feel like I may be trying too hard to fit the pydantic into my use case (or perhaps I have a misunderstanding in the logic of how to map a domain into pydantic).  In the example given by @hramezani , the attribute type is changed and, as a result, it looses the original meaning of `ExtendedParams` that was important for my use case. 

@adriangb -- I'm a bit curious to know more about the linked issue; would you mind explaining a bit more?  I'm not having any issues with an error raised, pydantic drops my data when I dump the model

**Comment by dmontagu** [comment]
@jayrahdevore I played with this a bit; if you change the `Item` type to have the following field serializer, does it work for you?

```python
class Item(BaseModel):
    type: str
    params: BaseParams

    @field_serializer('params')
    def dump_params(self, v):
        return v.model_dump()
```
This is essentially telling pydantic that instead of serializing the normal way, it should ask the value how to serialize itself. For reasons related to reducing possible FastAPI security bugs, we're leaning heavily toward making duck-typed-serialization opt-in, but if this suggestion works for you I think we could maybe add some syntax sugar to make it a bit less verbose if you use this pattern frequently

**Comment by jayrahdevore** [comment]
@dmontagu That works perfectly; thanks!
