### ISSUE TITLE
TypedDict cannot be assigned to parameter "typeddict_cls" of type "Type[TypedDict]" in function "create_model_from_typeddict"

### ISSUE THREAD

**Issue by winstxnhdw** [pydantic/pydantic#5953]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Following the example code from [here](https://docs.pydantic.dev/latest/usage/models/#model-creation-from-namedtuple-or-typeddict), we get the following error.

```python
Argument of type "Type[User]" cannot be assigned to parameter "typeddict_cls" of type "Type[TypedDict]" in function "create_model_from_typeddict"
  "Type[User]" is incompatible with "Type[TypedDict]"
  Type "Type[User]" cannot be assigned to type "Type[TypedDict]"
```

I have no clue why this happens because looking into the source code, it looks fine and when I test the following in the same script, there are no issues.

```python
def test(can_accept_typedict: Type['TypedDict']):
    pass

test(User)
```

My guess is that `from typing import TypedDict` is somehow not equivalent to `from typing_extensions import TypedDict` (which is what `pydantic` uses).

### Example Code

```Python
from typing import TypedDict

from pydantic import create_model_from_typeddict


class User(TypedDict):
    name: str
    id: int


class Config:
    extra = 'forbid'


UserM = create_model_from_typeddict(User, __config__=Config)
```

### Python, Pydantic & OS Version

```Text
Python 3.11.3
Pydantic 1.10.8
Arch Linux
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @winstxnhdw for reporting.

I couldn't reproduce the error with `Python 3.11.3` and `Pydantic 1.10.8`

Could you provide more info?

**Comment by winstxnhdw** [comment]
Hey @hramezani,

I am using Pyright as my type checker.

**Comment by hramezani** [comment]
You can user `TypeAdapter` instead in `V2`:


```py
from typing_extensions import TypedDict

from pydantic import TypeAdapter

class User(TypedDict):
    name: str
    id: int



UserM = TypeAdapter(User)
user = UserM.validate_python({'name': 'foo', 'id': 1})
print(user)
# {'name': 'foo', 'id': 1}
```
