### ISSUE TITLE
condecimal: trailing decimal zeroes are NOT ignored by max_digits and decimal_places arguments

### ISSUE THREAD

**Issue by HYBRID-BEING** [pydantic/pydantic#5956]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Despite [what it says in the docs](https://docs.pydantic.dev/latest/usage/types/#arguments-to-condecimal), trailing decimal zeroes seem to be included in validation of _max_digits_ and _decimal_places_ arguments of _condecimal_ type. Leading zero is ignored for _max_digits_, though.

Last example does not actually contradict docs, but is it expected behavior? Technically, Decimal("6067576.27") has no more than 10 digits and no more than 4 decimal places, and this _whole_digits_ check is not expected.

### Example Code

```Python
>>> from pydantic import BaseModel, condecimal
>>> from decimal import Decimal

>>> class A(BaseModel):
...     d: condecimal(max_digits=4, decimal_places=4)
...
>>> A(d=Decimal("0.2704"))
A(d=Decimal('0.2704'))

>>> class B(BaseModel):
...    d: condecimal(max_digits=10, decimal_places=4)
...

>>> B(d=Decimal("123456.7891"))
B(d=Decimal('123456.7891'))

>>> B(d=Decimal("12345678.0000"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for B
d
  ensure that there are no more than 10 digits in total (type=value_error.decimal.max_digits; max_digits=10)

>>> B(d=Decimal("12345.00000"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for B
d
  ensure that there are no more than 4 decimal places (type=value_error.decimal.max_places; decimal_places=4)

>>> B(d=Decimal("1234567.0"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for B
d
  ensure that there are no more than 6 digits before the decimal point (type=value_error.decimal.whole_digits; whole_digits=6)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.8
            pydantic compiled: True
                 install path: %appdata%\Python\Python310\site-packages\pydantic
               python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @HYBRID-BEING for reporting this.

I can confirm the problem in both V1 and V2.

As you mentioned, we have a problem with validation of `max_digits` and `decimal_places`.

Pydantic does not have a problem with `float` numbers. So, `B(d=de)` works as expected.

I've created a [PR](https://github.com/pydantic/pydantic/pull/5962) to fix the problem on main.

Let's wait for others to review it

**Comment by HYBRID-BEING** [comment]
Looking at the new test in the [commit](https://github.com/pydantic/pydantic/pull/5962/commits/01a031f342568401b6b928c0fd3e431bfd4eaaef), i guess it means that _whole_digits_ check is working as intended (being `max_digits - decimal_places`)? After all, `Decimal('0000000000011111.700000')` has 6 digits, which conforms to _max_digits_ constraint, yet, still fails to validate, cause _decimal_places_ constraint is still 2 (despite Decimal having only a single significant decimal place).

**Comment by HYBRID-BEING** [comment]
Thanks, guess i interpeted it incorrectly. Maybe it could be elaborated in docs?
