### ISSUE TITLE
Cannot use length constraints with Union

### ISSUE THREAD

**Issue by BTripp1986** [pydantic/pydantic#5959]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I will keep this brief since it is a straightforward problem.  

When using a type of `Union[str, list]` with the `min_length` and `max_length` Field constraints an error is raised. I tried adding `extra = "allow"` to the ModelConfig as per the docs linked in the error, but it did not work.  

It seems that even if this is the desired behavior, or if this is some limitation that can't be overcome, that there could be a more clear error message since this error indicates that an extra field was given on a model with the `extra = "forbid"` option.

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Union


class Bar(BaseModel):
    baz: Union[str, list] = Field(min_length=5)

    class ModelConfig:
        extra = "allow"


try:
    print("THIS WILL NEVER PRINT")
    a = Bar(baz=[1, 2, 3, 4, 5, 6])
except:
    a = Bar(baz="123456")
```
will produce the following output:
```
Traceback (most recent call last):
  File "/home/ben/code/python3/pyplayground/pydantv2.py", line 5, in <module>
    class Bar(BaseModel):
  File "/home/ben/code/python3/pyplayground/.venv-pydantic-v2/lib/python3.10/site-packages/pydantic/main.py", line 176, in __new__
    _model_construction.complete_model_class(
  File "/home/ben/code/python3/pyplayground/.venv-pydantic-v2/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 211, in complete_model_class
    cls.__pydantic_validator__ = SchemaValidator(simplified_core_schema, core_config)
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.schema.model-fields.fields.baz.schema.union.min_length
  Extra inputs are not permitted [type=extra_forbidden, input_value=5, input_type=int]
    For further information visit https://errors.pydantic.dev/0.30.0/v/extra_forbidden
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0a4
        pydantic-core version: 0.30.0 release build profile
                 install path: /home/ben/code/python3/pyplayground/.venv-pydantic-v2/lib/python3.10/site-packages/pydantic
               python version: 3.10.5 (main, Jun 30 2022, 09:53:55) [GCC 9.3.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by BTripp1986** [comment]
Note: The behavior is the same even if `ModelConfig` is omitted.

**Comment by hramezani** [comment]
Thanks @BTripp1986 for reporting this.

It got fixed in `main` and will be available in next beta release (which is happening soon)

Please re-open the issue or create a new one if it is not fixed in next beta release.
