### ISSUE TITLE
[PYD-129] _private attrs 

### ISSUE THREAD

**Issue by vitalik** [pydantic/pydantic#5972]
Could you provide some info on the private model attributes, why it behaves differently when annotated or not:
```Python

class Foo(BaseModel):
    number: int
    _private_attr1: int = 42
    _private_attr2 = 42


x1 = Foo._private_attr1
x2 = Foo._private_attr2
print(x1, type(x1))
print(x2, type(x2))

# x1   ->  default=42 <class 'pydantic.fields.ModelPrivateAttr'>
# x2  ->  42 <class 'int'>

```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b1
        pydantic-core version: 0.38.0 release build profile
                 install path: .venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  6 2022, 21:16:57)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

<sub>[PYD-129](https://linear.app/pydantic/issue/PYD-129/private-attrs)</sub>

**Comment by dmontagu** [comment]
This looks like maybe a bug, I suspect we probably intended to handle 
```python
class Foo(BaseModel):
    number: int
    _private_attr1: int = 42
    _private_attr2 = 42
```
the same as 
```python
class Foo(BaseModel):
    number: int
    _private_attr1: int = 42
    private_attr2 = 42
```
which raises `pydantic.errors.PydanticUserError: A non-annotated attribute was detected: private_attr2 = 42.`

Would you object to us making it raise an error in this case? Right now it appears to me (having not checked the code) that it's being treated as equivalent to
```python
class Foo(BaseModel):
    number: int
    _private_attr1: int = 42
    _private_attr2: ClassVar[Any] = 42
```
so I think if one wanted to retain this behavior they could, but I don't think it was intentional on our part.

**Comment by vitalik** [comment]
@dmontagu what's is the reason pydantic2 transforms private attrs to ModelPrivateAttr ? as I see they are not validated nor showed in schema, but on the other hand private attrs can be used to add some under the hood flags...

BTW - if I make it two underscore private - then pylance highlights it as error:


```Python
class Foo(BaseModel):
    a: int
    __b: int = 2

    def _get_b(self):
        return self.__b

```
<img width="449" alt="SCR-20230602-oewa" src="https://github.com/pydantic/pydantic/assets/95222/5317559f-4760-4f35-a1e9-90725a1d0ac9">

**Comment by dmontagu** [comment]
I'd say that's a question for @samuelcolvin; I wouldn't be opposed to making them opt-in even for leading-`_` attributes, but  I haven't thought much about the potential negative implications. Probably we need to do the same thing that v1 does, though could maybe support a config flag for controlling this (I saw a request for that in another issue).

**Comment by samuelcolvin** [comment]
related, this docstring is wrong:

https://github.com/pydantic/pydantic/blob/7dd09c8fa8b18ba7a74e16904ded17349ad55729/pydantic/fields.py#L813
