### ISSUE TITLE
RootModel.__getattr__ redirect

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#5989]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I propose a `__getattr__` for RootModel to redirect property access to root.
It could even test for the property in `.root`.
Things would just work, without having to add `.root`

```python
from typing import List, Union

from pydantic import BaseModel, RootModel

class C(BaseModel):
   items: List[int]

class D(BaseModel):
    data: str

class A(RootModel[Union[C,D]]):
   def __getattr__(self, name):
       if not name.startswith("model_") and not name.startswith("__") and hasattr(self.root, name):
           return getattr(self.root, name)


data = {"items":[1,2,3]}
a = A.model_validate(data)
assert a.root.items == a.items
```

Link to [existing problems with basic inheritance wrt. to `__getattr__`](#5946) in BaseModel.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
We need to look into this. In my understanding this should just work already.

For instance, we have the following in tests and it works.

```py
    class Nested(RootModel):
        root: int = 42

    Model = RootModel[Nested]

    m = Model()
    assert m.root.root == 42
```

**Comment by dmontagu** [comment]
I don't think we should add this by default. The point is that when you create a `RootModel`, it's still a normal model with a field called `root`, it just happens to serialize and deserialize without an extra "container" layer. This `__getattr__` would change that behavior and makes it less consistent with how other models work.

That said, @commonism I wouldn't be opposed to adding some tests that if you do define this getattr, it works properly.

Also, @commonism, note that `__getattr__` is only called if you don't find the attribute the "normal" way and would otherwise get an AttributeError. So I don't think you actually need to check for the `"model_"` prefix, and depending on what you are doing you might be able to drop the `"__"` prefix as well:
```python
class A(RootModel[Union[C,D]]):
    def __getattr__(self, name):
        if hasattr(self.root, name):  # maybe: and not name.startswith("__")
            return getattr(self.root, name)
        raise AttributeError(name)
```

**Comment by lig** [comment]
Yeah, I've misunderstood the proposal. I agree with @dmontagu that RootModel is just a specially precooked `BaseModel` subclass that has the `root` field and just serializes slightly differently. I think that in Python in should behave like a Model with a field. There is no functional benefit in it mimicking the root field type except a syntax sugar. I see how this could complicate the debugging of the code.

Also, a potential implementation raises some questions:
- Should we prioritize `root` attributes (using `__getattribute__`) over `RootModel` own attributes?
- Is it an error to have the same attributes on `root` and `RootModel`?
- What should happen for `RootModel` that is an attribute of another `RootModel`?
- Should we pass comparison operations to the underlying type as well?
- Should we pass `__repr__` and/or `__str__` to the underlying type?

IMO, `RootModel` isn't the same as the `root` attribute type and shouldn't act like it.

**Comment by commonism** [comment]
`For now` I'll avoid entering this rabbit hole.
It starts with __getattr__, then there is __length__, __getitem__, __set{attr,item}__ and then there is too many questions to answer consistently.

For my own use the savings do not relate to the costs currently.
