### ISSUE TITLE
Union regression

### ISSUE THREAD

**Issue by vitalik** [pydantic/pydantic#5991]
I run this code on pydantic v1 and v2

```Python
class Data(BaseModel):
    just_date: date
    date_or_str: Union[date, str]


print(Data(just_date='2023-01-01', date_or_str='2023-01-01').dict())
```

v1:
```
{'just_date': datetime.date(2023, 1, 1), 'date_or_str': datetime.date(2023, 1, 1)}
```

v2:
```
{'just_date': datetime.date(2023, 1, 1), 'date_or_str': '2023-01-01'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b1
        pydantic-core version: 0.38.0 release build profile
                 install path: .venv2/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  6 2022, 21:16:57)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
This is an intended change - pydantic V1's behaviour of coercing a value to the first member of a union even when it exactly matches a latter member of the unions was one of the most common complaints about pydantic.

You should be able to get the behaviour you want here with a functional validator. Let us know if you have any more questions.

**Comment by vitalik** [comment]
@samuelcolvin ok, got it

do you already have some document page that outlines all the core validation changes ?

**Comment by samuelcolvin** [comment]
Migration guide is a WIP, this will definitely be included.
