### ISSUE TITLE
Validation regression

### ISSUE THREAD

**Issue by vitalik** [pydantic/pydantic#5993]
```Python
class Data(BaseModel):
    value: str


d = Data(value=42)
print(d)
```

this code was working on pydantic1, but does not on pydantic2:
```
.venv2/lib/python3.9/site-packages/pydantic/main.py", line 135, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Data
value
  Input should be a valid string [type=string_type, input_value=42, input_type=int]
    For further information visit https://errors.pydantic.dev/0.38.0/v/string_type
```

if that is intentional ? are there any higher level to to be able to achieve v1 behaviour ?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b1
        pydantic-core version: 0.38.0 release build profile
                 install path: .venv2/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  6 2022, 21:16:57)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by adriangb** [comment]
This is on purpose, we no longer "parse" `int` to `str`

**Comment by vitalik** [comment]
@adriangb  but what's the alternative to turn "parsing" ON globally ?

the thing is that when you validate data that comes from javascript (REST APIs) you are getting all sort of type mismatches (and usually strings represented as ints and vice versa is the most common). and if you have big nested model tree it's not very practical to mark every string value with `LaxStr`

**Comment by vitalik** [comment]
@samuelcolvin @adriangb 

This is the most confusing part for me:

```Python

class ThisWorks(BaseModel):
    value: int


class ThisNot(BaseModel):
    value: str


print(ThisWorks(value='42'))
print(ThisNot(value=42))

```
why `str->int` works, but `int->str` not ?  I could see this behaviour make sense when you set strict=True, but if not strict - that's a bit inconsistent

**Comment by dmontagu** [comment]
I think it's perhaps a reasonable feature request to request a way to do global overrides for schema generation. We used to have a clear (though private) way to do that; I imagine we could expose a public way to do that that is picked up by `GenerateSchema`. I'm not sure what the other maintainers think of this, but if that's something that would be of interest to you, I might suggest creating a new issue requesting that functionality.
