### ISSUE TITLE
Inconsistent constructor signature when using alias

### ISSUE THREAD

**Issue by saabeilin** [pydantic/pydantic#5996]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The constructor of a pydantic model expects arguments named as field aliases, not a actual field names, which is not consistent when accessing these fields in existing object by their real names, not aliases.

Expectation is that aliases are only used in, say, JSON representation.

Example use case of aliases is following `camelCase` convention in API schema and `snake_case` in python code.

### Example Code

```Python
class AgentPlan(BaseModel):
    agent_id: str = Field(..., alias="agentId")

AgentPlan(agent_id="agent-bob")  # error, agentId field is missing
AgentPlan(agentId="agent-mark")  # works, but should not 

# now we parse some payload:
agent_plan = AgentPlan.parse_obj(request.json)  # has agentId as per schema definition
agent_plan.agent_id  # accessible as `agent_id` as expected
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.8
            pydantic compiled: True
                 install path: /home/[REDACTED]/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
                     platform: Linux-6.2.0-1003-lowlatency-x86_64-with-glibc2.37
     optional deps. installed: ['email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by lig** [comment]
BTW, the behavior follows [PEP 681 – Data Class Transforms](https://peps.python.org/pep-0681/).

```
`alias` is an optional str parameter that provides an alternative name for the field. This alternative name is used in the synthesized `__init__` method.
```

**Comment by hramezani** [comment]
@saabeilin it is a config key. I am not very familiar with `datamodel-code-generator`. you can open an issue there
