### ISSUE TITLE
Strange behaviour with my model after going to v2

### ISSUE THREAD

**Issue by ManiMozaffar** [pydantic/pydantic#5997]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Ever since I've migrated to version 2, my code doesn't run up, saying this:

ads_id
  Field required [type=missing, input_value={'url': 'https://www.link...els.ON_SITE: 'on_site'>}, input_type=dict]
    For further information visit https://errors.pydantic.dev/0.38.0/v/missing

I am not sure how is that related, when i downgrade to 1 it's fine again. I made ads_id optional, still no helps. I wonder if even that's what causing error or the error is being caught wrongly.

### Example Code

```Python
from enum import Enum
from pydantic import BaseModel, AnyUrl


class JobModels(Enum):
    ON_SITE = "on_site"
    REMOTE = "remote"
    HYBRID = "hybrid"


class LinkedinURLData(BaseModel):
    url: AnyUrl
    country: str
    job_mode: JobModels
    ads_id: Optional[str]


class LinkedinData(BaseModel):
    ads_id: str
    location: Optional[str]
    country: str
    body: str
    company_name: Optional[str]
    title: str
    source: int = 1
    employement_type: Optional[JobModels]
    level: Optional[str]
    keywords: list = list()
```

### Python, Pydantic & OS Version

```Text
pydantic 2.0b2, Windows 11, python 3.9.16
```

**Comment by adriangb** [comment]
Can you give an example of how you're using the code? As far as I can tell from your model `ads_id` is required. It might also help to simplify your example by removing any fields / models unrelated the issue you are reporting.

**Comment by ManiMozaffar** [comment]
> Can you give an example of how you're using the code? As far as I can tell from your model `ads_id` is required. It might also help to simplify your example by removing any fields / models unrelated the issue you are reporting.

Full code is here:
https://github.com/ManiMozaffar/linkedIn-scraper/tree/main/worker

I have dragged all pydantic model i've used so far here, because I'm not sure if the issue is related to ads_id.
By making ads_id optional, still I'll get the error.
Note that I don't get any error, I guess it can be also because of using enums here, not sure.
Anyway, this is strange behaviour, I don't know how to repeat the environment.  Once I downgraded to 1.1, all fine again..., once back to 2, errors again :)

**Comment by hramezani** [comment]
Please provide a minimal example to reproduce the problem(probably a small model with a breaking test). It's really hard for us to check your project code to find the problem.

Take a look at [this issue which shows the bug very simple](https://github.com/pydantic/pydantic/issues/6000)

**Comment by Viicos** [comment]
I believe this is when the `LinkedinURLData` is built, `ads_id` wasn't provided.

In v1, `ads_id: Optional[str]` means `ads_id` can be `str`, `None` or `None` if not provided (that is it has a default value).

In v2, `ads_id: Optional[str]` means `ads_id` can be `str`, `None` but is still required.

See https://docs.pydantic.dev/latest/blog/pydantic-v2/#required-vs-nullable-cleanup (can't find the PR that implemented this, maybe when they decided to switch to `pydantic-core`).

**Comment by ManiMozaffar** [comment]
> I believe this is when the `LinkedinURLData` is built, `ads_id` wasn't provided.
> 
> In v1, `ads_id: Optional[str]` means `ads_id` can be `str`, `None` or `None` if not provided (that is it has a default value).
> 
> In v2, `ads_id: Optional[str]` means `ads_id` can be `str`, `None` but is still required.
> 
> See https://docs.pydantic.dev/latest/blog/pydantic-v2/#required-vs-nullable-cleanup (can't find the PR that implemented this, maybe when they decided to switch to `pydantic-core`).

Yeah exactly, that was the case. Just saying, if I pass the argument as None, it still works. so even if that is the case, shouldn't it also raises error when we pass it as none, as your goal is to achieve data match dataclasses?

```
from typing import Optional
from pydantic import BaseModel


class LinkedinData(BaseModel):
    ads_id: Optional[str]


obj = LinkedinData()  # Error
obj = LinkedinData(ads_id=None)  # No Error
```

**Comment by Viicos** [comment]
`ads_id: Optional[str]` is equivalent to `ads_id: str | None`, which means it can be either `str` or `None`, while still being required. So it does match your `None` parameter (last line). `Optional` is probably the most confusing thing introduced in Python typing 😅
