### ISSUE TITLE
alias field name acts as the field name in the generated schema of openapi.json

### ISSUE THREAD

**Issue by anandtripathi5** [pydantic/pydantic#6002]
### Discussed in https://github.com/pydantic/pydantic/discussions/6001

<div type='discussions-op-text'>

<sup>Originally posted by **anandtripathi5** June  5, 2023</sup>
I have a Pydantic Model in my Fastapi project like below:

```
class NameSchema(BaseModel):
    first_name: str
    id: int
    age: str
    profile_image: str | None = Field(alias="customer_profile_image")

    class Config:
        orm_mode = True
        json_loads = orjson.loads
        json_dumps = orjson_dumps
```
I want to populate `profile_image` from `customer_profile_image`. The response of the schema is coming fine and it is indeed populating profile_image from customer_profile_image. But the issue is with the automated generated schema in openapi.json.
The Schema is actually having `customer_profile_image` in the key instead of `profile_image`. 

Something like below

`{....., "customer_profile_image":{"title":"Customer Profile Image","type":"string"}}`</div>

**Comment by sydney-runkle** [comment]
I believe this can be solved using Pydantic V2. You can also explicitly set `serialization` and `validation` alias values, which is helpful 👍.
