### ISSUE TITLE
[PYD-138] TypeError: cannot pickle 'pydantic_core._pydantic_core.Url' object

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#6010]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Maybe this is more of a pydantic-core bug?

### Example Code

```Python
import pickle
import pydantic

class A(pydantic.BaseModel):
    url: pydantic.HttpUrl

a = A(url="https://github.com/pydantic/pydantic")
pickle.dumps(a)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: ~/workspace/pydantic/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-42-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

<sub>[PYD-138](https://linear.app/pydantic/issue/PYD-138/typeerror-cannot-pickle-pydantic-core-pydantic-coreurl-object)</sub>

**Comment by dmontagu** [comment]
@commonism if you wanted to take a stab at this on the rust side, you might follow the discussion in https://github.com/PyO3/pyo3/issues/100 and add the relevant methods to `pydantic_core._pydanic_core.Url`. If you aren't comfortable doing that, I would suggest opening a feature request on pydantic-core for making this type picklable.

@davidhewitt is there a better way to make the type picklable short of defining those methods? (`__getstate__` etc.)

**Comment by davidhewitt** [comment]
Not yet. Shortcuts to implement the dunder methods for `#[pyclass]` is something we're just exploring for PyO3 0.20, I'll make a note to consider if we can do something smart for pickling.

**Comment by commonism** [comment]
Have not had rust on my hands before, but … gave it a shot.
So far I got either compiles but does not work, or does not compile.

```rs
    fn __getstate__(&self) -> PyResult<String> {
        Ok(self.lib_url.to_string())
    }

    fn __setstate__(&mut self, url: &PyAny) -> PyResult<Self> {
… it'll look easy when done
    }
```

**Comment by adriangb** [comment]
Try implementing `__reduce__` and returning essentially `(type(self), str(self)`. In other words, serialize it as a string and rehydrate by calling the `Url` constructor.

**Comment by adriangb** [comment]
Seems like this was fixed in https://github.com/pydantic/pydantic-core/commit/0ff7563c3eeafbbbf9355352cc66b5868d52c359
