### ISSUE TITLE
extra=allow breaks Base64Str

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#6011]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

A model_config with extra:allow changes the behavior of a Base64Str attribute - the value is stored in `model_extra["data"]` instead of `data` and not encoded therefore.

### Example Code

```Python
from pydantic import BaseModel, Base64Str

# works
class GoodProperty(BaseModel):
    data: Base64Str

v = GoodProperty.model_construct(data="test")
assert v.model_dump() == {"data":'dGVzdA==\n'}

# fails
class BadProperty(BaseModel):
    model_config = dict(extra="allow")
    data: Base64Str

v = BadProperty.model_construct(data="test")
assert v.model_dump() == {"data":'dGVzdA==\n'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: ~/workspace/pydantic/pydantic
               python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
                     platform: Linux-5.19.0-42-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by dmontagu** [comment]
This seems to be related to a bigger issue that field serializers aren't getting called when extra='allow' — will look into this...

**Comment by dmontagu** [comment]
Turns out it was just a bug in `model_construct`. PR incoming.
