### ISSUE TITLE
Coersion results in unexpected type for an integer with scientific notation

### ISSUE THREAD

**Issue by me-ydv-5** [pydantic/pydantic#6018]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

```python
from pydantic import BaseModel

class Model(BaseModel):
    a: dict


print(Model(a={'foo': 2e+6}).dict())
```

This prints 

```
{'a': {'foo': 2000000.0}}
```

foo had value `2e+6` but it gets coerced to a float. It should be `2000000` instead.

If you try to change Model.a to `a:int` and then `print(Model(a=2e+6).dict())`, it works out just fine. 

```python
from pydantic import BaseModel

class Model(BaseModel):
    a: int


print(Model(a=2e+6).dict())

```

prints `{'a': 2000000}`

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.7
            pydantic compiled: True
                 install path: /Users/saya/Library/Caches/pypoetry/virtualenvs/pgpgpg-4QRh_G2A-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, May  1 2023, 13:47:19) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by commonism** [comment]
All working as intended, 2e+6 is float, you are missing coercion:
```python
>> 2e+6
2000000.0
```
so …
```python
from typing import Dict
import pydantic

from pydantic import BaseModel

class Model(BaseModel):
    a: Dict[str, int]


print(Model(a={'foo': 2e+6}).dict())
# {'a': {'foo': 2000000}}
```

**Comment by dmontagu** [comment]
@commonism is right — `2e+6` is more or less a float literal.

**Comment by me-ydv-5** [comment]
Thanks, yeah that is right. I'll figure out some other way then. :)
