### ISSUE TITLE
Cannot subclass from AnyUrl

### ISSUE THREAD

**Issue by samsja** [pydantic/pydantic#6020]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

With pydantic v1 I used to subclass the AnyUrl to slightly change its behavior in a custom class.

It seems that it is not possible anymore with pydantic v2. I literally cannot subclass it anymore.

Is this expected ?

### Example Code

```Python
from pydantic import AnyUrl

class A(AnyUrl):
    pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: /home/sami/snap/alacritty/common/.cache/pypoetry/virtualenvs/docarray-OI1ry5x2-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 (main, Jan 18 2022, 17:20:31)  [GCC 9.3.0]
                     platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by adriangb** [comment]
This is expected, it's a Rust class, you won't be able to subclass it. What is it you are trying to do that requires you to subclass it?

**Comment by samsja** [comment]
I am currently adapting docarray to pydantic v2. There we define a class that inherits AnyUrl and slightly change the behavior: https://github.com/docarray/docarray/blob/main/docarray/typing/url/any_url.py


But I guess that we will have to rewrite this base class ourselves and don't rely on the built-in AnyUrl (or maybe reuse it internally without inheriting from it).

**Comment by adriangb** [comment]
Yes and no: subclasses will have to override `__new__` instead of `__init__` for starters, which still makes a lot of use cases weird. Hence why I was asking @samsja what their actual goal was. I also think we should in general encourage composition over inheritance (especially when it can be done vía `Annotated`, which is almost always the case unless you need to add attributes, in which case you run into the `__new__` thing I mentioned above). Finally I don’t know what impact that has on the generated Rust code (David H would know for sure) but since it’s not the default I imagine it’s not zero.

that said, if you still feel it’s worth it I don’t mind merging it.

**Comment by samsja** [comment]
On my side basically what I am looking for is:

* being able to reuse some part of AnyUrl core logic. This can be done via composition over inheritance
* inheriting the serilization ability of AnyUrl. Pydantic know how to deal with AnyUrl but will not know out of the box how to deal with my new class. (Though it can be solved pretty easily)

Inheriting from the class seems like the "easiest" way to do what I want to do, but it is not 100% needed honestly. Tho if there are no downside on pydantic side it could be nice to have it

**Comment by adriangb** [comment]
FYI in V1 if you inherit from a class you inherit it’s validation and serialization. In V2 you do not.

**Comment by samsja** [comment]
> FYI in V1 if you inherit from a class you inherit it’s validation and serialization. In V2 you do not.

hmmm interesting. Is there a way to not have to copy past the validation/ser ability of the class when inheriting ?

**Comment by adriangb** [comment]
How about something like this?

```python
from typing import Any

from pydantic_core import CoreSchema, core_schema

from pydantic import AnyUrl, BaseModel, GetCoreSchemaHandler, GetJsonSchemaHandler
from pydantic.json_schema import JsonSchemaValue


class MyUrl:
    def __init__(self, url: AnyUrl) -> None:
        self._url = url

    @classmethod
    def validate(
        cls,
        value: AnyUrl,
    ) -> 'MyUrl':
        assert value.host == 'example.com', 'Url must be example.com'
        return MyUrl(value)

    @classmethod
    def serialize(
        cls,
        value: 'MyUrl',
        handler: core_schema.SerializerFunctionWrapHandler,
    ) -> Any:
        return handler(value._url)

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type: Any, handler: GetCoreSchemaHandler) -> core_schema.CoreSchema:
        url_schema = handler.generate_schema(AnyUrl)
        return core_schema.no_info_after_validator_function(
            cls.validate, url_schema, serialization=core_schema.wrap_serializer_function_ser_schema(cls.serialize)
        )

    @classmethod
    def __get_pydantic_json_schema__(cls, core_schema: CoreSchema, _handler: GetJsonSchemaHandler) -> JsonSchemaValue:
        return {'type': 'string', 'format': 'uri'}

    def __repr__(self) -> str:
        return f'MyUrl({self._url})'


class Model(BaseModel):
    url: MyUrl


print(Model(url='https://example.com'))
print(Model(url='https://pydantic.dev'))
#> 1 validation error for Model:
#> Assertion failed, Url must be example.com
```

Or depending on what you're trying to do you could use something like this:

```python
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import AfterValidator


def validate(
    value: AnyUrl,
) -> AnyUrl:
    assert value.host == 'example.com', 'Url must be example.com'
    return value

def serialize(
    value: AnyUrl,
) -> Any:
    return value.host

MyUrl = Annotated[AnyUrl, AfterValidator(validate), PlainSerializer(serialize, return_type=str)]


class Model(BaseModel):
    url: MyUrl


print(Model(url='https://example.com'))
print(Model(url='https://example.com').model_dump())
print(Model(url='https://pydantic.dev'))
#> 1 validation error for Model:
#> Assertion failed, Url must be example.com

```

**Comment by samsja** [comment]
Okay I see makes sense !

Btw where is the best way to get up to speed with pydantic v2 ? Reading your code showed me I am still missing some understanding of the new API of v2

**Comment by adriangb** [comment]
We're actively working on documentation. Tests are probably the best documentation right now.

**Comment by samsja** [comment]
okay thanks !
