### ISSUE TITLE
Smart Union is not working with parse_obj

### ISSUE THREAD

**Issue by potzenhotz** [pydantic/pydantic#6025]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hey,

I'm trying to load some objects from a config file (json, hocon etc). I load the config into a dict and want to parse the dict into a pydantic object.

**As I use an Union I need to use the pydantic(V1) option smart_union.
When parsing the dict to a pydantic object the smart_union option is not used.**

I even tried the current V2 beta with validate_json instead of parse_obj, still no luck.

Here is some adapted example code from your documentation(https://docs.pydantic.dev/latest/usage/model_config/#smart-union):

### Example Code

```Python
from typing import Union
from pydantic import BaseModel


class Foo(BaseModel):
    pass


class Bar(BaseModel):
    pass


class Model(BaseModel, smart_union=True):
    x: Union[str, int]
    y: Union[Foo, Bar]

#This works as in the documentation
print(Model(x=1, y=Bar()))

#Does not work
model_dict = {"x": "test", "y": {"Bar": {}}}
model = Model(**model_dict)
print(model)

#Does not work
x = Model.parse_obj(model_dict)
print(x)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.8
pydantic compiled: True
python version: 3.10.9 (main, Feb 21 2023, 20:27:36) [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-13.4-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @potzenhotz for reporting this and sorry for the late response 🙏 

As you may know, `Pydantic V2` is out and we are not working on `Pydantic V1`.


Your provided example is working in `Pydantic V2`. You don't need to pass `smart_union=True` on pydantic V2. Also, `parse_obj` is removed and you have to use `model_validate`

```py
from typing import Union
from pydantic import BaseModel


class Foo(BaseModel):
    pass


class Bar(BaseModel):
    pass


class Model(BaseModel):
    x: Union[str, int]
    y: Union[Foo, Bar]

#This works as in the documentation
print(Model(x=1, y=Bar()))

#Does not work
model_dict = {"x": "test", "y": {"Bar": {}}}
model = Model(**model_dict)
print(model)

#Does not work
x = Model.model_validate(model_dict)
print(x)
```

**Comment by dmontagu** [comment]
This is actually behaving the same in V2 and V1, but this isn't misbehavior in either case — we never expect the name of the model to be data used to determine which union case to use, that's not how smart union works. Smart union just made sure that if an input's data was valid for multiple union cases but was an instance of one, it would retain its type. In this case, since neither `Foo` nor `Bar` have any fields, any dict will be valid for both, and so will be validated into the first case, `Foo`.

You'd need to use some sort of field validator to ensure the class name was used to determine the type of the value to load the data into.
