### ISSUE TITLE
Support `transparent` Color

### ISSUE THREAD

**Issue by CollinHeist** [pydantic/pydantic#6026]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

From the docs, the `pydantic.color.Color` type is for storing CSS3 colors. Per the docs:

> You can use the Color data type for storing colors as per [CSS3 specification](http://www.w3.org/TR/css3-color/#svg-color).

As of CSS3, the `transparent` color is supposed to be supported in all colors, and is equivalent to `rgba(0, 0, 0, 0)`. From the CSS3 website:

> CSS3 extends the color value to include the ‘[transparent](https://www.w3.org/TR/css-color-3/#transparent-def)’ keyword to allow its use with all properties that accept a <color> value. This simplifies the definition of those properties in CSS3.
    _transparent_
    Fully transparent. This keyword can be considered a shorthand for transparent black, rgba(0,0,0,0), which is its computed value.

---

Adding support for this would be more consistent in Pydantic's parsing of color names.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by yezz123** [comment]
It would be great if you open this issue here [pydantic/pydantic-extra-types](https://github.com/pydantic/pydantic-extra-types) while color its deprecated in pydantic v2

**Comment by CollinHeist** [comment]
Sure, I wasn't aware Color was being deprecated. I'll open the issue there. Thanks!

**Comment by samuelcolvin** [comment]
Moved.
