### ISSUE TITLE
Documentation Sprint

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#6032]
This issue is to document our progress about the documentation.
Sure! Here's the updated table with an additional "reviewed" column:

| Filename                         | Pull Request | In Charge | Reviewed |
|----------------------------------|--------------|-----------|----------|
| api/alias_generators.md          |              |           |          |
| api/color.md                     |              |           |          |
| api/config.md                    |              |           |          |
| api/dataclasses.md               |              |           |          |
| api/errors.md                    |              |           |          |
| api/fields.md                    |              |           |          |
| api/functional_serializers.md    |              |           |          |
| api/functional_validators.md     |              |           |          |
| api/json_schema.md               |              |           |          |
| api/main.md                      |              |           |          |
| api/mypy.md                      |              |           |          |
| api/networks.md                  |              |           |          |
| api/pydantic_core_init.md        |              |           |          |
| api/pydantic_core_schema.md      |              |           |          |
| api/type_adapter.md              |              |           |          |
| api/types.md                     |              |           |          |
| api/validate_call.md             |              |           |          |
| errors/errors.md                 |              |           |          |
| index.md                         |              |           |          |
| install.md                       |              |           |          |
| integrations/datamodel_code_generator.md |        |           |          |
| integrations/devtools.md         |              |           |          |
| integrations/hypothesis.md       |              |           |          |
| integrations/mypy.md             |              |           |          |
| integrations/pycharm.md          |              |           |          |
| integrations/rich.md             |              |           |          |
| integrations/visual_studio_code.md |             |           |          |
| migration.md                     |              |           |          |
| usage/computed_fields.md         |              |           |          |
| usage/conversion_table.md        |              |           |          |
| usage/dataclasses.md             |              |           |          |
| usage/errors.md                  |              |           |          |
| usage/exporting_models.md        |              |           |          |
| usage/model_config.md            |              |           |          |
| usage/models.md                  |              |           |          |
| usage/postponed_annotations.md   |              |           |          |
| usage/pydantic_settings.md       |              |           |          |
| usage/schema.md                  |              |           |          |
| usage/types/booleans.md          |              |           |          |
| usage/types/bytesize.md          |              |           |          |
| usage/types/callables.md         |              |           |          |
| usage/types/custom.md            |              |           |          |
| usage/types/datetime.md          |              |           |          |
| usage/types/dicts_mapping.md     |              |           |          |
| usage/types/encoded.md           |              |           |          |
| usage/types/enums.md             |              |           |          |
| usage/types/extra_types/color_types.md |        |           |          |
| usage/types/extra_types/payment_cards.md |      |           |          |
| usage/types/file_types.md        |              |           |          |
| usage/types/json.md              |              |           |          |
| usage/types/list_types.md        |              |           |          |
| usage/types/number_types.md      |              |           |          |
| usage/types/secrets.md           |              |           |          |
| usage/types/sequence_iterable.md |              |           |          |
| usage/types/set_types.md         |              |           |          |
| usage/types/standard_types.md    |              |           |          |
| usage/types/string_types.md      |              |           |          |
| usage/validation_decorator.md    |              |           |          |
| usage/validation_errors.md       |              |           |          |
| usage/validators.md              |              |           |          |

**Comment by dmontagu** [comment]
Going beyond the table above — I think each of the "leaf" bullets in the following markdown need to be done:

```markdown
# Update existing documentation files:
* Landing Page
    * index.md

* Installation
    * install.md

* API docs - create file for all public modules missing file in `docs/api`

* Docstrings
    * Establish and document the requirements for public module docstrings in the contribution guidelines
    * Establish and document the requirements for internal module docstrings in the contribution guidelines

    * Ensure public docstrings meet the requirements:
        * alias_generators.py
        * color.py
        * config.py
        * dataclasses.py
        * errors.py
        * fields.py
        * functional_serializers.py
        * functional_validators.py
        * json_schema.py
        * main.py
        * mypy.py
        * networks.py
        * type_adapter.py
        * types.py
        * validate_call.py
        * version.py

    * Ensure private docstrings meet the requirements:
        * _internal/_annotated_handlers.py
        * _internal/_config.py
        * _internal/_core_metadata.py
        * _internal/_dataclasses.py
        * _internal/_decorators.py
        * _internal/_decorators_v1.py
        * _internal/_discriminated_union.py
        * _internal/_fields.py
        * _internal/_forward_ref.py
        * _internal/_generate_schema.py
        * _internal/_generics.py
        * _internal/_internal_dataclass.py
        * _internal/_known_annotated_metadata.py
        * _internal/_model_construction.py
        * _internal/_repr.py
        * _internal/_schema_generation_shared.py
        * _internal/_std_types_schema.py
        * _internal/_typing_extra.py
        * _internal/_utils.py
        * _internal/_validate_call.py
        * _internal/_validators.py

* Errors
    * errors/errors.md


* Integrations
    * integrations/datamodel_code_generator.md
    * integrations/devtools.md
    * integrations/hypothesis.md
    * integrations/mypy.md
    * integrations/pycharm.md
    * integrations/rich.md
    * integrations/visual_studio_code.md

* Migration
    * migration.md

* Usage
    * usage/computed_fields.md
    * usage/conversion_table.md
    * usage/dataclasses.md
    * usage/errors.md
    * usage/exporting_models.md
    * usage/model_config.md
    * usage/models.md
    * usage/postponed_annotations.md
    * usage/pydantic_settings.md
    * usage/schema.md
    * usage/types/booleans
    * usage/types/bytesize
    * usage/types/callables
    * usage/types/custom
    * usage/types/datetime
    * usage/types/dicts_mapping
    * usage/types/encoded
    * usage/types/enums
    * usage/types/extra_types
    * usage/types/extra_types
    * usage/types/file_types
    * usage/types/json
    * usage/types/list_types
    * usage/types/number_types
    * usage/types/secrets
    * usage/types/sequence_iterable
    * usage/types/set_types
    * usage/types/standard_types
    * usage/types/string_types
    * usage/validation_decorator.md
    * usage/validation_errors.md
    * usage/validators.md


# Improve documentation of previously-existing functionality

* Config inheritance in subclasses (https://github.com/pydantic/pydantic/issues/1019)
* BaseModel.model_construct (see https://github.com/pydantic/pydantic/issues/3471#issuecomment-1528162198)
* Non-hashable defaults get deepcopied during model instantiation (e.g., `x: list = []`)
* Document that we copy some things, and leave something unchanged (?? @adriangb)


# Document new functionality

* Serialization decorators
	* @field_serializer, @model_serializer, @computed_field

* Other serialization improvements
	* functional serializers (`Annotated[MyType, PlainSerializer(...)]`, etc.)
	* mode='json'

* TypeAdapter
	* Search issues for AnalyzedType, and convert to TypeAdapter

* RootModel

* JSON schema
	* Validation vs. Serialization
	* Subclassing `GenerateJsonSchema`

* Strict mode

* Custom Types
	* __get_pydantic_core_schema__, __get_pydantic_json_schema__, __prepare_pydantic_annotations__
	* using annotations to integrate with third-party types (see https://github.com/pydantic/pydantic/pull/5620)
	* creating custom generic containers (see https://github.com/pydantic/pydantic/issues/4161#issuecomment-1527960500 and https://github.com/pydantic/pydantic/issues/2274#issuecomment-1528082601)

* Validation context
	* Also, use in __init__ by way of a ContextVar (see https://github.com/pydantic/pydantic/issues/1549#issuecomment-1526632046)

* "Wrap"-mode validator decorators

* Special generic annotations in pydantic.types
	* SkipValidation, InstanceOf, TransformSchema, etc.

* New things in pydantic.fields.Field
	* E.g., validation_alias, serialization_alias

* `from_attributes` as a validation time parameter

* Recursive models cyclic reference detection

* AliasPath and AliasChoices


# Update the migration guide

(Maybe add to PR https://github.com/pydantic/pydantic/pull/6006)

* Generic protocol annotations may not preserve original type in some scenarios (see: https://github.com/pydantic/pydantic/pull/5744/files#r1191552815)
	* We guarantee validity of the output type, not preserving the input type

* __fields__ and __validators__ have been removed (see https://github.com/pydantic/pydantic/issues/5694)

* Generics improvements
	* Handling of generic dataclasses and TypedDict
	* Removal of GenericModel
	* Automatic model_rebuild for recursive models (generic or not)

* Serialization reflects type schema, rather than "duck typing" (can override with SerializeAsAny or whatever, as @adriangb suggested)

# Document backwards-compatibility promises

* Document the set of things we reserve the right to change in minor releases (e.g., error message text)
```
