### ISSUE TITLE
Typo in datetime types documentation

### ISSUE THREAD

**Issue by Phantom1472** [pydantic/pydantic#6038]
https://github.com/pydantic/pydantic/blob/main/docs/usage/types/datetime.md#L31

-2e10 is negative, 2e10 positive, so the expression:

`>=-2e10 OR <=2e10`
Includes all numbers.
Should be:
`>=-2e10 AND <=2e10`

Thanks.

**Comment by adriangb** [comment]
Would you like to submit a PR?

**Comment by Phantom1472** [comment]
> Would you like to submit a PR?

Yes, when i get home I'll submit a PR

**Comment by Phantom1472** [comment]
@adriangb PR is #6061

**Comment by Kludex** [comment]
- Closed by #6061
