### ISSUE TITLE
[PYD-128] discriminated unions lack type="object"

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#6056]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

It's valid for JSON Schemas to have no, a single or multiple types.
```python
    type: Optional[Union[str, List[str]]] = Field(default=None)
```

Schemas without a type match any type, `Union[int,str,…,'object']`.

But it's unfortunate as the JSON Schema of  Model without type - in pydantic terms - is a `RootModel[Union[str,int,float,bool,"Schema"]]`.
Pydantic creates such Schema but validates - in pydantic terms as a "Schema" directly (e.g. does not accept "10" as valid input for int).

For the example below, 
```python
RootModel[Union[str,int,float,RootModel[Annotated[Union[Cat, Dog], Field(..., discriminator='pet_type')]]]]
```
instead of
```python
RootModel[Annotated[Union[Cat, Dog], Field(..., discriminator='pet_type')]]
```

"10" or "abc" should be valid Pet, so there is a mismatch in the Schema exported and the data validation.
(Additionally resulting in indirection of access due to use of the extra RootModel[Union[]].)

Can be avoided by setting `type: object` for discriminated unions.

https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-7.6.1
https://stackoverflow.com/questions/47374980/schema-object-without-a-type-attribute-in-swagger-2-0

I think all Model Schemas should have type - in case there is others missing.

### Example Code

```Python
import json
from typing import Literal, Union
from pydantic import BaseModel, RootModel, Field


class Cat(BaseModel):
    pet_type: Literal['cat']
    meows: int


class Dog(BaseModel):
    pet_type: Literal['dog']
    barks: float


class Pet(RootModel):
    root: Union[Cat, Dog] = Field(..., discriminator='pet_type')

obj = Pet.schema_json()
print(obj)
obj = json.loads(obj)
assert "type" in obj and obj.get("type") == "object"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: ~/workspace/pydantic/pydantic
               python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
                     platform: Linux-5.19.0-42-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

<sub>[PYD-128](https://linear.app/pydantic/issue/PYD-128/discriminated-unions-lack-type=object)</sub>

**Comment by dmontagu** [comment]
I'm having trouble following what it is you want changed here.

Could you contrast what the schema currently is with what you want it to show?  The schema generated in your code sample seems reasonable to me considering it's a oneOf schema referencing definitions that have types.

Also, other than the horrible definition name, the schema generated for your complex RootModel example also seems reasonable at first glance:
```python
import json
from typing import Literal, Union, Annotated
from pydantic import BaseModel, RootModel, Field


class Cat(BaseModel):
    pet_type: Literal['cat']
    meows: int


class Dog(BaseModel):
    pet_type: Literal['dog']
    barks: float


obj = RootModel[Union[
    str, int, float, RootModel[Annotated[Union[Cat, Dog], Field(..., discriminator='pet_type')]]]].model_json_schema()
print(json.dumps(obj, indent=2))
"""
{
  "$defs": {
    "Cat": {
      "properties": {
        "meows": {
          "title": "Meows",
          "type": "integer"
        },
        "pet_type": {
          "const": "cat",
          "title": "Pet Type"
        }
      },
      "required": [
        "pet_type",
        "meows"
      ],
      "title": "Cat",
      "type": "object"
    },
    "Dog": {
      "properties": {
        "barks": {
          "title": "Barks",
          "type": "number"
        },
        "pet_type": {
          "const": "dog",
          "title": "Pet Type"
        }
      },
      "required": [
        "pet_type",
        "barks"
      ],
      "title": "Dog",
      "type": "object"
    },
    "RootModel_Annotated_Union_Cat__Dog___FieldInfo_annotation_NoneType__required_True__discriminator__pet_type____": {
      "discriminator": {
        "mapping": {
          "cat": "#/$defs/Cat",
          "dog": "#/$defs/Dog"
        },
        "propertyName": "pet_type"
      },
      "oneOf": [
        {
          "$ref": "#/$defs/Cat"
        },
        {
          "$ref": "#/$defs/Dog"
        }
      ]
    }
  },
  "anyOf": [
    {
      "type": "string"
    },
    {
      "type": "integer"
    },
    {
      "type": "number"
    },
    {
      "$ref": "#/$defs/RootModel_Annotated_Union_Cat__Dog___FieldInfo_annotation_NoneType__required_True__discriminator__pet_type____"
    }
  ]
}
"""
```

**Comment by dmontagu** [comment]
> Schemas without a type match any type, Union[int,str,…,'object'].

Is this true if it has a `oneOf` or `anyOf`? Doesn't that mean it has to match one of the specified schemas? All of the things referenced have a `type` field.

**Comment by samuelcolvin** [comment]
I think we need some more input from @commonism, I'm a bit lost on what's wrong here.

**Comment by commonism** [comment]
> > Schemas without a type match any type, Union[int,str,…,'object'].
> 
> Is this true if it has a `oneOf` or `anyOf`? 

Yes.

> Doesn't the presence of those keys mean it has to match one of the specified schemas? 

No - see https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-7.6.1 .

Executive Summary;
```
When the type of the instance is not of the type targeted by
the keyword, the instance is considered to conform to the assertion.
```

Or https://github.com/OAI/OpenAPI-Specification/issues/1388#issuecomment-339061316
```
type is not required by the OpenAPI spec, and much like JSON Schema, if it's omitted, it means any 
type can be used. As handrews kindly explained, any JSON Schema validation attributes that are 
being used, are logically applied only in the case their respective type is being used. 
JSON Schema Validation defines which type each validation keyword applies to.
```

> All of the things referenced have a `type` field.

Every schema should have a type field.
 
> It would maybe help if you could show an example of a JSON schema that pydantic is generating, and an example input that is valid for the JSON schema that pydantic has generated (according to the JSON schema draft 2020-12 or whatever), but where that example input should not be accepted (and is not accepted during validation by pydantic).

```python
import json
from typing import Literal, Union
from pydantic import BaseModel, RootModel, Field


class Cat(BaseModel):
    pet_type: Literal['cat']
    meows: int


class Dog(BaseModel):
    pet_type: Literal['dog']
    barks: float


class Pet(RootModel):
    root: Union[Cat, Dog] = Field(..., discriminator='pet_type')

obj = Pet.schema_json()
print(json.dumps(json.loads(obj), indent=True))
```

Schema without type:
```
{
 "oneOf": [
  {
   "$ref": "#/$defs/Cat"
  },
  {
   "$ref": "#/$defs/Dog"
  }
 ],
 "discriminator": {
  "propertyName": "pet_type",
  "mapping": {
   "cat": "#/$defs/Cat",
   "dog": "#/$defs/Dog"
  }
 },
 "$defs": {
  "Cat": {
   "type": "object",
   "properties": {
    "pet_type": {
     "const": "cat",
     "title": "Pet Type"
    },
    "meows": {
     "type": "integer",
     "title": "Meows"
    }
   },
   "required": [
    "pet_type",
    "meows"
   ],
   "title": "Cat"
  },
  "Dog": {
   "type": "object",
   "properties": {
    "pet_type": {
     "const": "dog",
     "title": "Pet Type"
    },
    "barks": {
     "type": "number",
     "title": "Barks"
    }
   },
   "required": [
    "pet_type",
    "barks"
   ],
   "title": "Dog"
  }
 }
}
```

Due to the missing type it does not have to be an object and therefore 1, "1", True would be valid inputs.
Every integer, string, boolean.

**Comment by dmontagu** [comment]
Reading through section 10 of your first link: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-10.2.1:

> [10.2.1.3](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-10.2.1.3).  oneOf
>
>   This keyword's value MUST be a non-empty array.  Each item of the
>   array MUST be a valid JSON Schema.
>
>   An instance validates successfully against this keyword if it
>   validates successfully against exactly one schema defined by this
>   keyword's value.

This seems to me like it's saying that it doesn't validate successfully if it doesn't match at least one. While I won't deny it's at least a little ambiguous in the draft, in context, I interpreted the sections you quoted as applying to "primitive" schemas that don't have a key like "oneOf" or "allOf" that would affect what validates.

Moreover, I tried many online JSON schema validators, and they _all_ behaved the way I've described above, where if you have a "oneOf" key, the value must match one of the listed schemas, or it fails validation (even without a "type" key).

Here's an example of what I mean using the [`jsonschema`](https://python-jsonschema.readthedocs.io/en/stable/) package in python:

```python
from jsonschema.exceptions import ValidationError
from jsonschema.validators import validate

oneof_non_nullable_schema = {"oneOf": [{"type": "string"}, {"type": "number"}]}

validate(instance='abc', schema=oneof_non_nullable_schema)
validate(instance=1, schema=oneof_non_nullable_schema)

try:
    validate(instance=None, schema=oneof_non_nullable_schema)
except ValidationError as e:
    print(e)
    """
    None is not valid under any of the given schemas
    
    Failed validating 'oneOf' in schema:
        {'oneOf': [{'type': 'string'}, {'type': 'number'}]}
    
    On instance:
        None
    """

# On the other hand, `None` will be accepted if it is one of the oneOfs:
oneof_nullable_schema = {"oneOf": [{"type": "string"}, {"type": "number"}, {"type": "null"}]}

validate(instance=None, schema=oneof_nullable_schema)
print("validated successfully")
#> validated successfully
```

Just to be thorough, I'll ask @julian to weigh in, as he is the authority on JSON schema as far as I'm aware.

**Comment by dmontagu** [comment]
Also, I can't find any JSON schema validators that are accepting `1` for the value you've provided in your example, here's a demonstration using the `jsonschema` package:

```python
from jsonschema.exceptions import ValidationError
from jsonschema.validators import validate

pydantic_schema = {
    "oneOf": [
        {
            "$ref": "#/$defs/Cat"
        },
        {
            "$ref": "#/$defs/Dog"
        }
    ],
    "discriminator": {
        "propertyName": "pet_type",
        "mapping": {
            "cat": "#/$defs/Cat",
            "dog": "#/$defs/Dog"
        }
    },
    "$defs": {
        "Cat": {
            "type": "object",
            "properties": {
                "pet_type": {
                    "const": "cat",
                    "title": "Pet Type"
                },
                "meows": {
                    "type": "integer",
                    "title": "Meows"
                }
            },
            "required": [
                "pet_type",
                "meows"
            ],
            "title": "Cat"
        },
        "Dog": {
            "type": "object",
            "properties": {
                "pet_type": {
                    "const": "dog",
                    "title": "Pet Type"
                },
                "barks": {
                    "type": "number",
                    "title": "Barks"
                }
            },
            "required": [
                "pet_type",
                "barks"
            ],
            "title": "Dog"
        }
    }
}

try:
    validate(instance=1, schema=pydantic_schema)
except ValidationError as e:
    print(e)
    """
    1 is not valid under any of the given schemas
    
    Failed validating 'oneOf' in schema:
        {'$defs': {'Cat': {'properties': {'meows': {'title': 'Meows',
                                                    'type': 'integer'},
                                          'pet_type': {'const': 'cat',
                                                       'title': 'Pet Type'}},
                           'required': ['pet_type', 'meows'],
                           'title': 'Cat',
                           'type': 'object'},
                   'Dog': {'properties': {'barks': {'title': 'Barks',
                                                    'type': 'number'},
                                          'pet_type': {'const': 'dog',
                                                       'title': 'Pet Type'}},
                           'required': ['pet_type', 'barks'],
                           'title': 'Dog',
                           'type': 'object'}},
         'discriminator': {'mapping': {'cat': '#/$defs/Cat',
                                       'dog': '#/$defs/Dog'},
                           'propertyName': 'pet_type'},
         'oneOf': [{'$ref': '#/$defs/Cat'}, {'$ref': '#/$defs/Dog'}]}
    
    On instance:
        1
    """
```

**Comment by Julian** [comment]
I too would need to read the ticket here to understand what the question is --

I see two things immediately, though I'm not sure how relevant they are, one being that the `discriminator` keyword is part of OpenAPI, not JSON Schema (though I suspect this isn't relevant and I know `pydantic` may generate OpenAPI schemas today)

The second thing I see just scanning is:

> Every schema should have a type field.

This certainly isn't true about JSON Schema. I'm not sure if this is meant to be a prescriptive comment ("pydantic should generate schemas with `type`") -- that.. may be but also seems unlikely. But it's certainly false in general, the type keyword is not required and indeed arbitrary JSON Schemas may contain keywords applying to different types, for better or worse.

I also seem to sense an assumption that `oneOf` only applies to objects, but yes that too isn't correct, `oneOf` is simply a keyword which applies multiple subschemas and passes if just one is valid against the instance.

If there's more than that that I can help with I can have a read through sometime later.

**Comment by dmontagu** [comment]
Also, in the [Swagger docs for these schemas](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) (which are OpenAPI-specific) none of them include a "type" field in the top-level schema, only in the referenced members of the `oneOf`. Which also makes me think that is how it is intended to be used.

**Comment by commonism** [comment]
> > Every schema should have a type field.
> 
> This certainly isn't true about JSON Schema. I'm not sure if this is meant to be a prescriptive comment

It was meant to be a prescriptive comment.

> "pydantic should generate schemas with `type`"

Better wording.

> I also seem to sense an assumption that `oneOf` only applies to objects, but yes that too isn't correct, `oneOf` is simply a keyword which applies multiple subschemas and passes if just one is valid against the instance.

I considered oneOf a keyword myself and due to 
https://github.com/OAI/OpenAPI-Specification/issues/1388#issuecomment-339051239

```
JSON Schema does not specify this because JSON Schema keywords do not have type implications. They work the other way around. If you have a schema like this:

{
    "required": ["foo"],
    "minItems": 4
}

Then {"foo": 1}, [1, 2, 3, 4] and "this is a string" are all valid, while {"bar": 2} and [1, 2, 3] are not. If the instance is an object, then it is required to have a field named "foo". If the instance is an array, then it must have at least 4 items. If the instance is any other type, then there are no constraints on it.

This may seem counter-intuitive, and this specific example would be strange to encounter, but it makes a lot more sense when you think about "type": ["object", "null"] where you want the object restrictions to apply when it is an object, but not to cause validation to fail on a null.
```

The provided example works fine with jsonschema:
```
from jsonschema.exceptions import ValidationError
from jsonschema.validators import validate

pydantic_schema = {
    "required": ["foo"],
    "minItems": 4
}

for i in  [{"foo": 1}, [1, 2, 3, 4], "this is a string"]:
    validate(instance=i, schema=pydantic_schema)


for i in [{"bar": 2}, [1, 2, 3]]:
    try:
        validate(instance=i, schema=pydantic_schema)
    except ValidationError as e:
        continue
    else:
        print(f"{i} should have failed")
```        

On the other hand - here is another answer which would indicate the root type is shared with the subschemas:
https://json-schema.org/understanding-json-schema/reference/combining.html#id11
```
Note that it’s possible to “factor” out the common parts of the subschemas. The following two schemas are equivalent.

{
  "oneOf": [
    { "type": "number", "multipleOf": 5 },
    { "type": "number", "multipleOf": 3 }
  ]
}

{
   "type": "number",
   "oneOf": [
     { "multipleOf": 5 },
     { "multipleOf": 3 }
   ]
 }
```

In jsonschema the type: of the root object overwrites the type of the subschemas during assertion.
```
from jsonschema.exceptions import ValidationError
from jsonschema.validators import validate

pydantic_schema = {
   "type": ["object","string"],
   "oneOf": [
     { "type":"number", "multipleOf": 5 },
     { "type":"string"}
   ]
 }


for i in  ["1",5]:
    validate(instance=i, schema=pydantic_schema)
```

```
Failed validating 'type' in schema:
    {'oneOf': [{'multipleOf': 5, 'type': 'number'}, {'type': 'string'}],
     'type': ['object', 'string']}

On instance:
    5
```

@Julian thanks for chiming in, for oneOf - the root will inherit the successful asserted subschemas type if not provided?

**Comment by Julian** [comment]
> In jsonschema the type: of the root object overwrites the type of the subschemas during assertion.

I wouldn't use the word "overwrite" here, at least in the context of JSON Schema in general (rather than say, using JSON Schema as a model definition language or something, which is only a secondary or tertiary use even)

If there's a `type` in the root, then the instance needs to be valid under it.

If there's a type in a subschema, then the instance needs to be valid under if the subschema sits inside some keyword which requires the subschema to be valid -- or if that keyword has more complicated behavior vis a vis the subschemas (as `oneOf` does, where the rule is "be valid under exactly one of these), then it needs to satisfy those.

But e.g.

```
{
    "not": {"type": "string"}
}
```

matches all all non-string instances, there's no root `type`, and the subschema's `type` needs to apply. Similarly

```
{"type": ["string", "integer"], "not": {"type": "string"}}
```

matches only integers -- and I again wouldn't personally use "override" here as a mental model, stuff is basically independent from each other, and here an instance needs to be valid both under `"type": "string" | "type": "integer"` *and* also be valid against the `not`, and well, logically that of course means it's an integer, but `type` and `not` aren't somehow collaborating here.

Let me know if I'm answering a different question than the one you're asking (but I at least understand now that you were/are making a recommendation to the `pydantic` team that they produce schemas looking a specific way rather than asserting a global truth -- I can't say I have thought hard enough to agree or disagree personally, but I'm happy to sit and think if y'all can't come to a decision).

**Comment by commonism** [comment]
Exactly what I intended to discuss.

oneOf is a validation keyword, it does not have a type implication, it logical applies (and) it's subschemas type to the root type. 
In case there no root type, any type (["string","object","number",…]) is used instead and logical combined.

```
pydantic_schema = {
    "oneOf": [
        { "type":"string","minLength": 5 },
        { "type":"number", "multipleOf": 5 },
    ]
}

for i in ["12345",12345]:
    validate(instance=i, schema=pydantic_schema)
```

Thanks for clarification.

**Comment by dmontagu** [comment]
Closing here since it was closed on github
