### ISSUE TITLE
Reloading a module that has a validator results in a duplicate-validator error

### ISSUE THREAD

**Issue by HarshTrivedi** [pydantic/pydantic#6079]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Reloading a module that has a validator results in a duplicate-validator error. See the minimal example code. I don't think this is an expected behavior.

### Example Code

```Python
# my_model.py
from pydantic import BaseModel, validator

class MyModel(BaseModel):
    field: int

    @validator("field")
    def validate_field(cls, value):
        return value
```

```python
# use.py
from importlib import reload
import my_model

reload(my_model)
```

Running use.py results in this error:

```
    @validator("field")
     ^^^^^^^^^^^^^^^^^^
  File "pydantic/class_validators.py", line 93, in pydantic.class_validators.validator.dec
  File "pydantic/class_validators.py", line 156, in pydantic.class_validators._prepare_validator
pydantic.errors.ConfigError: duplicate validator function "my_model.MyModel.validate_field"; if this is intended, set `allow_reuse=True`
```

It can be fixed by `@validator("field", allow_reuse=True)`. But still, the error is misleading as no actual reuse is happening.

```
### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.9
            pydantic compiled: True
                 install path: /Users/harshtrivedi/anaconda3/envs/api-sandbox/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Mar  1 2023, 12:49:28) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
We can't change this in v1, I believe it's fixed in V2.

If it's not fixed in V2, please let us know.
