### ISSUE TITLE
Add Automatic Updates for Computed_Fields

### ISSUE THREAD

**Issue by Haskely** [pydantic/pydantic#6085]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hello Pydantic developers,

I would like to propose the addition of automatic updates for computed_fields in Pydantic. Currently, if a computed_field depends on other fields that may change over time, we need to manually clear the cache to ensure that the computed_field is updated with the latest values. This can be cumbersome and error-prone, especially if multiple computed_fields are involved.

```python
from pydantic import BaseModel, computed_field


class Rectangle(BaseModel):
    width: int
    length: int

    @computed_field
    @cached_property
    def area(self) -> int:
        # LONG TIME CALC
        return self.width * self.length

rect = Rectangle(width=10, length=20)
print(rect.area)
rect.width = 100
print(rect.area)
```

I suggest adding a feature that automatically updates computed_fields whenever their dependencies change. This behavior is similar to what [MobX provides](https://mobx.js.org/computeds.html). With this addition, Pydantic users would no longer need to worry about manual cache clearing, thus simplifying their code and reducing the likelihood of bugs.

```python
from pydantic import BaseModel, computed_field


class Rectangle(BaseModel):
    width: int
    length: int

    @cached_computed_field(depends=["width", "length"]) # Or detect depends automatically by read code_str ?
    def area(self) -> int:
        # LONG TIME CALC
        return self.width * self.length

rect = Rectangle(width=10, length=20)
print(rect.area)
rect.width = 100 # Auto clean rect.area cache
print(rect.area) # rerun area method
```

I believe this feature would greatly enhance Pydantic's usability and make it even more powerful for building data models. Thank you for your consideration, and please let me know if there are any questions or concerns.

Best regards

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by orfisko** [comment]
Hm, I wasn't aware of the caching. This would definitely be an important feature for my usage. I would use computed fields mainly for implementing the typical getter/setter thing and not for actual computation. I have models where multiple attributes need to be changed when one is updated. The logic to update should be inside the model class itself. I really miss python properties in pydantic v1 right now :/

**Comment by Viicos** [comment]
> Hm, I wasn't aware of the caching. This would definitely be an important feature for my usage. I would use computed fields mainly for implementing the typical getter/setter thing and not for actual computation. I have models where multiple attributes need to be changed when one is updated. The logic to update should be inside the model class itself. I really miss python properties in pydantic v1 right now :/

To be clear if I'm not mistaken `computed_field` does not implement any caching by default, unless `@cached_property` is used.

**Comment by orfisko** [comment]
> > Hm, I wasn't aware of the caching. This would definitely be an important feature for my usage. I would use computed fields mainly for implementing the typical getter/setter thing and not for actual computation. I have models where multiple attributes need to be changed when one is updated. The logic to update should be inside the model class itself. I really miss python properties in pydantic v1 right now :/
> 
> To be clear if I'm not mistaken `computed_field` does not implement any caching by default, unless `@cached_property` is used.

I deleted my comment, apologies for polluting your request

**Comment by Viicos** [comment]
> > > Hm, I wasn't aware of the caching. This would definitely be an important feature for my usage. I would use computed fields mainly for implementing the typical getter/setter thing and not for actual computation. I have models where multiple attributes need to be changed when one is updated. The logic to update should be inside the model class itself. I really miss python properties in pydantic v1 right now :/
> > 
> > 
> > To be clear if I'm not mistaken `computed_field` does not implement any caching by default, unless `@cached_property` is used.
> 
> I deleted my comment, apologies for polluting your request

no worries + that wasn't my feature request ;)

**Comment by adriangb** [comment]
I'm not sure exactly how complex your real world code is, but maybe this can help:

```python
from functools import cached_property
from typing import Any

from pydantic import BaseModel, ConfigDict, ValidatorFunctionWrapHandler, computed_field, model_validator


class Rectangle(BaseModel):
    width: int
    length: int

    model_config = ConfigDict(validate_assignment=True)

    @computed_field
    @cached_property
    def area(self) -> int:
        # LONG TIME CALC
        return self.width * self.length

    @model_validator(mode='wrap')
    @classmethod
    def val_model(cls, value: Any, handler: ValidatorFunctionWrapHandler) -> Any:
        if isinstance(value, Rectangle):
            width, length = value.width, value.length
            value: Rectangle = handler(value)
            new_width, new_length = value.width, value.length
            if new_width != width or new_length != length:
                del value.area
            return value
        return handler(value)

rect = Rectangle(width=10, length=20)
assert rect.area == 200
rect.width = 100
assert rect.area == 2000
```

**Comment by adriangb** [comment]
I don't think Pydantic can do much more than that, it would get complicated to track dependencies between fields. Cache invalidation is a hard problem. The above should enable you to do that, you'll just have to implement that yourself.

**Comment by sydney-runkle** [comment]
Closing this, as we're not planning to add changes to this behavior.
