### ISSUE TITLE
model_dump methods fail for combination usage of BaseModel and RootModel

### ISSUE THREAD

**Issue by kmfarley11** [pydantic/pydantic#6113]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

My project does some pretty complex typing where I ultimately need a list of varying types. Some of which are unions of variants (unioned RootModels), and others are direct BaseModels. When trying to do model_dump and model_dump_json on the complex list, I get an error `'<Class>' has no attribute 'root'`.

If I convert all types unioned to be `RootModel`s, the dump works just fine. Same if I convert them all to BaseModels and rely on optional fields. The former is do-able for my use-case as it's just adding extra classes, but the latter would cause issues with some of the more complex typings we need to do and validate (without bloating a single BaseModel).

Please see the example code for a reproduction case. Note also that I reproduced this in two different environments and pasted both below as well.

Also please let me know if `RootModel | BaseModel` is not a supported use-case, thanks!

### Example Code

```Python
# Usage:
#   python -m venv .venv
#   . .venv/bin/activate  # or . .\.venv\Scripts\Activate.ps1
#   pip install git+https://github.com/pydantic/pydantic.git#egg=pydantic
#   pip freeze  # confirm pydantic commit is current tip of main
#   python model_dump_issues_pydv2.py
# pylint: disable=all
from pydantic import RootModel, BaseModel


class IdVariant1(BaseModel):
    id_str: str


class IdVariant2(BaseModel):
    id_int: int


class Id(RootModel):
    root: IdVariant1 | IdVariant2


class Name(BaseModel):
    name: str


class Items(RootModel):
    root: list[Id | Name]


def main():
    items = Items.model_validate([{"id_str": "id1"}, {"id_int": 2}, {"name": "number-three"}])  # ok
    print(items)  # ok
    print(items.model_json_schema())  # ok

    # this fails with:
    #   pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: AttributeError: 'Name' object has no attribute 'root'
    print(items.model_dump_json())


if __name__ == "__main__":
    main()
```

### Python, Pydantic & OS Version

```Text
> python -c "import pydantic.version; print(pydantic.version.version_info())"  # Windows
             pydantic version: 2.0b2
        pydantic-core version: 0.39.0 release build profile
                 install path: C:\Users\kmfarley11\.venv\Lib\site-packages\pydantic
               python version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']

$ python -c "import pydantic.version; print(pydantic.version.version_info())"  # WSL dev container
             pydantic version: 2.0b2
        pydantic-core version: 0.38.0 release build profile
                 install path: /home/vscode/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr 12 2023, 14:31:14) [GCC 10.2.1 20210110]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by lig** [comment]
@kmfarley11 Thank you for the feedback. This looks like a valid bug.

As for now, I'd suggest "wrapping" `Name` in a `RootModel`.

```py
class Items(RootModel):
    root: list[Id | RootModel[Name]]
```

**Comment by lig** [comment]
I can confirm that the issue reproduces

**Comment by lig** [comment]
@kmfarley11 Another workaround that works at the moment is to change the order of models in the annotation.

```py
class Items(RootModel):
    root: list[Name | Id]
```
