### ISSUE TITLE
Performance issue with pydantic's set[tuple[str,int]] validation

### ISSUE THREAD

**Issue by Haskely** [pydantic/pydantic#6140]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have identified a performance issue with pydantic's validation of the `set[tuple[str,int]]` data type. When compared to alternative methods of validating the same data, such as using `isinstance` or simply copying the data, pydantic's validation takes an order of magnitude longer to complete. 

To reproduce, run the following code:

```
from pydantic import BaseModel
import time 

class Foo(BaseModel):
    data_set: set[tuple[str,int]]

def time_p(func):

    def wrapper(*args, **kwargs):
        start_t = time.time()
        result = func(*args, **kwargs)
        end_t = time.time()
        print(f"{func.__name__} running {end_t - start_t} s")
        return result

    return wrapper

@time_p
def just_copy(data_set):
    return {x for x in data_set}

@time_p
def use_isinstance(data_set):
    return isinstance(data_set, set) and all([isinstance(x[0], str) and isinstance(x[1], int) for x in data_set])

@time_p
def use_pydantic(data_set):
    return Foo(data_set=data_set)

if __name__ == "__main__":
    _data_set = {("A"*32,i) for i in range(int(1e6))}
    just_copy(_data_set)
    use_isinstance(_data_set)
    use_pydantic(_data_set)
```

The output shows that pydantic's validation takes much longer than the other methods:

```
just_copy running 0.4252183437347412 s
use_isinstance running 0.381380558013916 s
use_pydantic running 3.4611337184906006 s
```

### Example Code

```Python
from pydantic import BaseModel
import time 

class Foo(BaseModel):
    data_set: set[tuple[str,int]]

def time_p(func):

    def wrapper(*args, **kwargs):
        start_t = time.time()
        result = func(*args, **kwargs)
        end_t = time.time()
        print(f"{func.__name__} running {end_t - start_t} s")
        return result

    return wrapper

@time_p
def just_copy(data_set):
    return {x for x in data_set}

@time_p
def use_isinstance(data_set):
    return isinstance(data_set, set) and all([isinstance(x[0], str) and isinstance(x[1], int) for x in data_set])

@time_p
def use_pydantic(data_set):
    return Foo(data_set=data_set)

if __name__ == "__main__":
    _data_set = {("A"*32,i) for i in range(int(1e6))}
    just_copy(_data_set)
    use_isinstance(_data_set)
    use_pydantic(_data_set)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.9
            pydantic compiled: True
                 install path: /home/zhangzixin/miniconda3/envs/rl/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]
                     platform: Linux-5.10.25-nvidia-gpu-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by dmontagu** [comment]
This is largely due to the way we do "validation" (kind of a misnomer in pydantic's vocabulary, but 🤷‍♂️), which applies conversions, not just checking instances. Obviously in this case such conversions aren't necessary, but I think having the capability already makes it a bit slower.

However, we have massively reduced the pydantic-imposed overhead in V2, despite keeping the functionality essentially the same. If I run your example in pydantic V2 I get:

```
just_copy running 0.0878448486328125 s
use_isinstance running 0.19887328147888184 s
use_pydantic running 0.23383116722106934 s
```

**Comment by Haskely** [comment]
I'm glad to hear that V2 will improve performance. The initial reason I submitted this issue was due to performance problems I encountered in certain situations. Upon investigation, I found that the bottleneck was caused by the Pydantic validation process, as demonstrated in the minimal reproducible example provided above.

Although the root cause of encountering sets with a quantity of 1e6 is related to some slight issues in the code's business logic, it was unexpected for Pydantic to be the first to suffer from a significant drop in performance. Looking forward to the stable release of V2.

**Comment by lig** [comment]
There is already Pydantic v2.3.0 has been released.

This version also has a reasonable performance in this case.

```
just_copy running 0.24861454963684082 s
use_isinstance running 0.24492645263671875 s
use_pydantic running 0.3858151435852051 s
```
