### ISSUE TITLE
Additional arguments

### ISSUE THREAD

**Issue by likecodingloveproblems** [pydantic/pydantic#6145]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

BaseModel remove additional fields silently, two solution proposed:

1. Raise on model creation
2. Add field to the model

Based on this [issue](https://github.com/pydantic/pydantic/issues/2285), it seems adding field is not allowed.

### Example Code

```Python
from pydantic import BaseModel

class User(BaseModel):
  name: str
  age: int

user = User(name='name', age=20, password='password')
user.password
# AttributeError: 'User' object has no attribute 'password'
```

### Python, Pydantic & OS Version

```Text
/home/mam/mycode/pydantic/pydantic/_migration.py:273: UserWarning: `pydantic.utils:version_info` has been moved to `pydantic.version:version_info`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
             pydantic version: 2.0b2
        pydantic-core version: 0.39.0 release build profile
                 install path: /home/mam/mycode/pydantic/pydantic
               python version: 3.9.16 (main, Feb 10 2023, 18:15:50)  [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)]
                     platform: Linux-6.3.6-100.fc37.x86_64-x86_64-with-glibc2.36
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by yezz123** [comment]
```py
from pydantic import BaseModel

class User(BaseModel):
    name: str
    age: int

    class Config:
        extra = "allow"

user_data = {
    "name": "name",
    "age": 20,
    "password": "password"
}

user = User(**user_data)
print(user.password)  # 'password'
```

add the `Config` class in case of extra fields

**Comment by hramezani** [comment]
@likecodingloveproblems The issue has `bug V1` label but it seems you are using the `V2` beta based on the information in `Python, Pydantic & OS Version` of the issue.

BTW, In `Pydantic V2`, [The default extra behavior is `ignore`](https://docs.pydantic.dev/dev-v2/usage/model_config/#extra-attributes). So, Pydantic Ignores any extra attributes.

You can change the behavior like:
```py
from pydantic import BaseModel, ConfigDict

class User(BaseModel):
    model_config = ConfigDict(extra='allow')

    name: str
    age: int

user = User(name='name', age=20, password='password')
print(user.password)
#> password
```
