### ISSUE TITLE
Type validation on default values

### ISSUE THREAD

**Issue by likecodingloveproblems** [pydantic/pydantic#6147]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Default value type is not validated!

### Example Code

```Python
from pydantic import BaseModel

class User(BaseModel):
  name: str = 1
  age: int = 'age'

user = User()
user.age #'age'
user.name #1
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b2
        pydantic-core version: 0.39.0 release build profile
                 install path: /home/mam/mycode/pydantic/pydantic
               python version: 3.9.16 (main, Feb 10 2023, 18:15:50)  [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)]
                     platform: Linux-6.3.6-100.fc37.x86_64-x86_64-with-glibc2.36
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by ezhang7423** [comment]
See https://github.com/pydantic/pydantic/issues/1280
