### ISSUE TITLE
Allow Mutation - Request to re-add

### ISSUE THREAD

**Issue by mark-todd** [pydantic/pydantic#6181]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hi all - first of all I'm very excited for the release of Pydantic V2! The features removed in general I think look like very good decisions. There was only one feature on the list that I felt I would miss - `allow_mutation`, in Config. I've used this in some projects before to allow users to modify large already generated models, then reinsert the modified version, rather than have to regenerate the model anew, which may have many attributes. I'd be interested to hear the reasons for its removal, or if there are any alternatives for this use case, that wouldn't involve reassigning all attributes of the model.

Here's a demonstration of the use case in V1 syntax:
```py
from pydantic import BaseModel
class NewBase(BaseModel):
    class Config:
         allow_mutation = True

class Submodel1(NewBase):
    attr1: str = 'test' # Imagine many more attributes here

class Submodel2(NewBase):
    attr2: str = 'test' # Imagine many more attributes here

class Wrapper(NewBase):
    sub1: Submodel1
    sub2: Submodel2

inst = Wrapper(sub1=Submodel1(), sub2=Submodel2())
f(inst) # Some Function
inst.sub1.attr1 = 'new'
f(inst) # Some Function
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
I think `allow_mutation ` is replaced by [`frozen`](https://docs.pydantic.dev/dev-v2/api/config/#pydantic.config.ConfigDict) config.

**Comment by mark-todd** [comment]
Ah yeah I think you're right! That's great - is it worth perhaps updating this to put "allow_mutation" in the renamed section? Small change I know: https://github.com/pydantic/pydantic/blob/main/docs/blog/pydantic-v2-alpha.md?plain=1#L136

**Comment by hramezani** [comment]
It's actually not renamed. it's a new config. because `allow_mutation=True` is not equal to `frozen=True`.

`allow_mutation=True` = `frozen=False`
`allow_mutation=False` = `frozen=True`

I am not totally against moving it to rename section but probably it would be better to mention using of `frozen` config in the same line.

**Comment by mark-todd** [comment]
Ah good point - this might be a bit too abstract: `allow_mutation -> ~frozen`

Perhaps: `allow_mutation -> frozen (inverse of current use)`

**Comment by hramezani** [comment]
`allow_mutation - This has been removed. You should be able to use frozen (inverse of current use)` sounds better to me.

Would you like to open a PR?

**Comment by mark-todd** [comment]
Sure! Sounds good
