### ISSUE TITLE
`model_dump()` not accurate return type 

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#6190]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Currently, if you have a `RootModel` that looks like the following, and then you call `model_dump()`, you'll not get a dict, but a list.

### Example Code

```Python
from typing import List

from pydantic import RotModel

MyRootModel = RootModel(List[str])

model = MyRootModel(root=["a", "b"])
model.model_dump()  # This returns a list[str], and not a dict
```

### Python, Pydantic & OS Version

```Text
v2
```

**Comment by lig** [comment]
In general RootModel.model_dump() doesn't return a `dict` unless the `root` type is `dict`.

**Comment by lig** [comment]
We could override the return type in RootModel and silence type checkers about that.

**Comment by Kludex** [comment]
That's only one case, I should also have mentioned that `@model_serializer` can also return something different than dict.

**Comment by dmontagu** [comment]
We've discussed this before, while it's true that model_serializer can return anything, I think having the return type of `model_dump` be `Any` is pretty unfortunate. I think what we should do is keep it as `dict[str, Any]` but document that you can override the return type in the signature in an `if TYPE_CHECKING:` block to get better type hinting if you do intend to return something that isn't a `dict[str, Any]`. And I think with `RootModel` we should use this with the generic type to get better type hinting. I'll see if it works..

**Comment by dmontagu** [comment]
This seemed to work, I opened PR #6290 to do this.
