### ISSUE TITLE
Discriminator key not being found

### ISSUE THREAD

**Issue by Joshuaalbert** [pydantic/pydantic#6198]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

This is a puzzling error. The below code speaks for itself. This is a simple case of trying to create an annotated discriminated type. Discriminators have always worked for me before. I'm unsure, it it's related to a backend update of pydantic; the version causing bug posted below. I have searched Google, SO, and even asked GPT4 for insight (which said it looks like good code, and that it might indicate a bug in pydantic).

```bash
class Baz(BaseModel):
  File "pydantic/main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 629, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 666, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 780, in pydantic.fields.ModelField.prepare_discriminated_union_sub_fields
  File "pydantic/utils.py", line 791, in pydantic.utils.get_discriminator_alias_and_values
pydantic.errors.ConfigError: Model 'Foo' needs a discriminator field for key '_type'
```

### Example Code

```Python
from typing import Annotated, Union, Literal

from pydantic import BaseModel, Field


class Foo(BaseModel):
    _type: Literal['foo'] = 'foo'


class Bar(BaseModel):
    _type: Literal['bar'] = 'bar'


Qux = Annotated[Union[Foo, Bar], Field(discriminator='_type')]

if __name__ == '__main__':
    class Baz(BaseModel):
        qux: Qux


    Baz(qux=Foo())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.4
            pydantic compiled: True
                 install path: /home/albert/miniconda3/envs/tha_py/lib/python3.10/site-packages/pydantic
               python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
                     platform: Linux-5.15.0-73-generic-x86_64-with-glibc2.31
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Joshuaalbert** [comment]
Also confirmed on `pydantic 1.10.9`. Seems to be an issue with default not being set. `Bar().json()` produces `{}` instead of `{"type": "bar"}`.

**Comment by Joshuaalbert** [comment]
Changing from `_type` to `type` fixes it.

**Comment by Joshuaalbert** [comment]
It this ^^ intended functionality?

**Comment by hramezani** [comment]
Yes, it is intended.

`_type` is not a field in `Pydantic V1`. That's why you get this error and you don't have an error when you remove `_` and replace it with `type`.

We have the same behavior in `Pydantic V2`. In `Pydantic V2`, `_type` will be considered as private attr, and for now, it is not possible to have a discriminator on private attr.

We may add support for private attr as a discriminator in the future. but for sure we will not support it in `V2` release.

**Comment by Joshuaalbert** [comment]
Could be an idea to give a more informative error message, if possible.

**Comment by hramezani** [comment]
We can add a note to [discriminated unions section of doc](https://docs.pydantic.dev/latest/usage/types/#discriminated-unions-aka-tagged-unions) about this.

Feel free to open a PR if you would like
