### ISSUE TITLE
BaseSettings parse_env_var classmethod no longer available

### ISSUE THREAD

**Issue by fredrikaverpil** [pydantic/pydantic#6234]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I’m not sure if this belongs in the migration guide but I got hit heavily by this change and didn’t find anything about it in he guide. So, figured I’d post about it here 😊

Reference: https://github.com/pydantic/pydantic-settings/issues/80#issuecomment-1602195212

The above issue also talks about the solution, which entails using custom settings sources.

### Python, Pydantic & OS Version

```Text
I’m on mobile and can fix this properly later, but here’s the versions from the pyproject.toml:


[tool.poetry.dependencies]
fastapi = {extras = ["all"], version = "^0.100.0b1", allow-prereleases = true}
pydantic = {version = "^2.0b3", allow-prereleases = true}
pydantic-settings = {version = "^2.0b1", allow-prereleases = true}
```

**Comment by hramezani** [comment]
I've just created a PR to include a note about it in migration doc
