### ISSUE TITLE
load_alias and dump_alias

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#624]
Just realised I've referenced this on a few different issues #477, #576, and #585, but there's no issue dedicated to it.

I suggest we have 3 alias options on a field:
* `alias` used for loading and dumping
* `load_alias` only used for loading, takes precedence over `alias`
* `dump_alias` only used for dumping (`.dict()` and `.json()`), takes precedence over `alias`

**Comment by jaheba** [comment]
Does this mean, we want to generally get to this behaviour:

     data == MyModel.parse_obj(data).dict()

even if aliases are used?

I.e., this breaks the current behaviour where dumping a model uses the internal names, is that correct?

**Comment by samuelcolvin** [comment]
yes.

**Comment by samuelcolvin** [comment]
technically this is backwards compatible so doesn't need to go in v1, but let's leave it here and see how we get on.

**Comment by eillarra** [comment]
Another possible approach: have a couple of new Config values: `export_json_by_alias` and `export_dict_by_alias` to set a default value for `by_alias` in the `.json()` and `.dict()` methods... instead of defining the load/dump per Field. Load can be solved with `allow_population_by_field_name` at a general level, so these to extra configs could solve dump.

The only change in the code that would be needed is in the definition of `.json()` and `.dict()`. Something like this:

```python
    ...
    def dict(
        self,
        *,
        include: Union['AbstractSetIntStr', 'DictIntStrAny'] = None,
        exclude: Union['AbstractSetIntStr', 'DictIntStrAny'] = None,
        by_alias: Optional[bool] = None,  # changes here
        skip_defaults: bool = None,
        exclude_unset: bool = False,
        exclude_defaults: bool = False,
        exclude_none: bool = False,
    ) -> 'DictStrAny':
        if not by_alias:
            by_alias = self.__config__.export_dict_by_alias
        ...
```

For backwards compatibility, the default value in Config would be `False`.

**Comment by victoraugustolls** [comment]
Hi! Is this expected to be implemented soon? Looking forward to this for my use case!

**Comment by samuelcolvin** [comment]
I keep meaning to get around to it, but haven't had time yet.

**Comment by victoraugustolls** [comment]
Hi @samuelcolvin ! Would you mind giving me some pointers so I can maybe help you with this? Thanks!

**Comment by nikhilgupta345** [comment]
I'd love this feature as well!

**Comment by samuelcolvin** [comment]
There should also be some simple way to to set the dump alias to "skip" or "exclude" which means that field is excluded when calling `dict()` or `json()`.

**Comment by PrettyWood** [comment]
> There should also be some simple way to to set the dump alias to "skip" or "exclude" which means that field is excluded when calling `dict()` or `json()`.

@samuelcolvin I just started to implement both options (see #1695) and I agree a way to exclude some fields from parsing would be nice. I'm just not sure what the expected API would be. Would you like some reserved names for `load_alias` option ? sunder / dunder ?

**Comment by wookiesh** [comment]
Hi, is there any news for this ? 
My use case is linked to mongodb, I'm getting object with "_id" key but as we have an interface to follow (fastapi based), I have to return objects with an "id" key, any smart way that I missed to do this ? :)

**Comment by JonasKs** [comment]
Samuel said in the Talk Python podcast that he intend to support this. (I wasn't aware there was an issue for this when I asked)

[Clip](https://youtube.com/clip/UgkxBloEvkrTHKK1RafIu-DaiWzQT44YNJTm) and [full podcast](https://youtu.be/URrUBgOFl6U). Highly recommend watching 😊

**Comment by suonto** [comment]
This feature would be useful.

Example:
Imagine that you have an AWS Lambda python application and it gets events from SQS, and pushes events to SQS.

Facts:
- Any python app probably wants the field names to be in snake case
- Boto3 expects you to provide data in CamelCase
- Sqs eventsource has a known feature to lowercase the first character of all the keys in the event https://github.com/boto/boto3/issues/2249

Therefore the ideal BaseModel to handle instance arns would look like this:
```
class BaseModel(BaseModel):
    instance_arn: str = Field(load_alias="instanceArn", dump_alias="InstanceArn")
```

With the current `alias` implementation, the only good option is to relax the snake_casing requirement for field names and therefore sacrifice code style consistency:
```
class BaseModel(BaseModel):
    InstanceArn: str = Field(alias="instanceArn")
```

Would be great to have this feature.

**Comment by JonasKs** [comment]
I started looking at this a bit, but I'm a bit confused.   
I realize the v2 rewrite is _in progress_, so I expected to see tests like [these](https://github.com/pydantic/pydantic/blob/main/tests/test_aliases.py#L112-L129), where they're marked with `xfail`. How ever, in the `alias` case, all tests are marked with `xfail`. Is `alias`-functionality not implemented/complete yet, if so, any pointers on what to wait for / see whether I can contribute?

**Comment by samuelcolvin** [comment]
aliases are implemented in pydantic-core - both load and dump aliases, also more more powerful load aliases, see tests [here](https://github.com/pydantic/pydantic-core/blob/fb69c39168e8f8df3860b7164d5cedfa64acc754/tests/validators/test_typed_dict.py#L512).

**Comment by JonasKs** [comment]
Oh wow, that's great news! Thanks for the resources and reply, I'll read up on it.

**Comment by dmontagu** [comment]
V2 now has validation_alias and serialization_alias 🚀
