### ISSUE TITLE
Cannot use proper subclass of `str` as input to a strict `str` field

### ISSUE THREAD

**Issue by dmontagu** [pydantic/pydantic#6261]
```python
from pydantic import BaseModel


class Model(BaseModel):
    model_config = {'strict': True}
    x: str


class MyString(str):
    pass


Model(x=MyString('foo'))
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x
  Input should be a string, not an instance of a subclass of str [type=string_sub_type, input_value='foo', input_type=MyString]
    For further information visit https://errors.pydantic.dev/0.41.0/v/string_sub_type
"""
```

In general, I don't think strict mode should prevent the use of strict subclasses as inputs to the, as this is at odds with the type system used by python type checkers.

I think the above example is also a legitimate scenario where you might want to support subclasses of `str` — otherwise, it's impossible to use strict mode if you might want to pass subclasses of `str`.

Also, as far as I can tell, no other field type works like this (e.g., `int`), which makes me question the value of having this failure mode for strict `str` — it seems like an inconsistency, and I don't see it adding much/any value.

It feels to me that in the rare scenario where this behavior is desirable, it would be better to use a custom validator to reject subclasses; this could be baked into a reusable type via:

```python
from typing import Any, Annotated

from pydantic import BaseModel, BeforeValidator


def is_exact_str(v: Any) -> str:
    if isinstance(v, str) and type(v) != str:
        raise ValueError('Must not provide a subclass of `str`')
    return v


ExactStr = Annotated[str, BeforeValidator(is_exact_str)]


class Model(BaseModel):
    x: ExactStr


class MyString(str):
    pass


Model(x=MyString('foo'))
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
x
  Value error, Must not provide a subclass of `str` [type=value_error, input_value='foo', input_type=MyString]
    For further information visit https://errors.pydantic.dev/0.41.0/v/value_error
"""
```

I feel somewhat strongly that this behavior should be changed, but am open to disagreement.

(Also, I guess this will need to be implemented in pydantic-core.)

**Comment by samuelcolvin** [comment]
I hadn't realised about this, I think it's caused strange behaviour:


```py
from typing import Annotated

from pydantic import BaseModel, StringConstraints

class MyStr(str):
    pass

class TestModel(BaseModel):
    test: str


m1 = TestModel.model_validate(dict(test=MyStr("test")))
print('m1 MyStr:', type(m1.test))

m2 = TestModel.model_validate(dict(test=MyStr("test")), strict=True)
print('m2 str:', type(m2.test))


class TestModel2(BaseModel):
    test: Annotated[str, StringConstraints(strip_whitespace=True)]



m3 = TestModel2.model_validate(dict(test=MyStr("test")))
print('m3 MyStr:', type(m3.test))

m4 = TestModel2.model_validate(dict(test=MyStr("testtest123")), strict=True)
print('m4 str:', type(m4.test))
```

Also different behaviour for `strict=True` means that `str | int` will retain subtype information while `str` will not.

**Comment by adriangb** [comment]
The cases with `StringConstraints` I expect. We always loose information when checking constraints. One could argue that if we're just checking length or something we should preserve the original input object but that is not possible here given that you are using `strip_whitespace`. 

The only one that surprised me is that the lax version without constraints doesn't retain the type. I presume we can change that. Then again we've made the promise in v2 that we give you the right output type, _not_ that we preserve the input type (which was kind of an implicit promise in v1). So if we can fix that to make it more consistent with low effort I think we should. But I wouldn't consider it a huge issue.

**Comment by samuelcolvin** [comment]
conversation moved to https://github.com/pydantic/pydantic-core/issues/786.
