### ISSUE TITLE
[PYD-137] v1 -> v2 - Getting default value during validation

### ISSUE THREAD

**Issue by vitalik** [pydantic/pydantic#6268]
If you [check this example ](https://django-ninja.rest-framework.com/guides/input/form-params/#mapping-empty-form-field-to-default) in v1 there was a way to get default value of the  in validation function 

basically the goal is if data that is passed equals to empty string - just change it to default value:

```Python
class MyModel(BaseModel)
    price: EmptyStrToDefault[int] = 10


obj = MyModel(price="")
assert obj.price == 10

obj = MyModel(price=20)
assert obj.price == 20
```

what's the way to get this default value in v2 ?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0b3
        pydantic-core version: 0.39.0 release build profile
                 install path: .venv2/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  6 2022, 21:16:57)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

<sub>[PYD-137](https://linear.app/pydantic/issue/PYD-137/v1-v2-getting-default-value-during-validation)</sub>

**Comment by Kludex** [comment]
Thanks @vitalik .

I didn't reply before, but I'm already looking into this, fyi.

**Comment by Kludex** [comment]
I'm trying to create the `EmptyStrToDefault`.

I was still not able to do it yet, but here is a way to do it with `field_validator`:

```py
from typing import Any

from pydantic import BaseModel, FieldValidationInfo, field_validator

class MyModel(BaseModel):
    price: int = 10

    @field_validator('price', mode='before')
    def empty_str_to_default(cls, v: Any, info: FieldValidationInfo) -> Any:
        if v == "":
            return cls.model_fields[info.field_name].default
        return v


print(MyModel(price=""))
#> price=10
print(MyModel(price=1))
#> price=1
```

I'll keep checking if there's a way. If not, we'll add more data to the `info`.

**Comment by samuelcolvin** [comment]
I think we should just add `.default` to `ValidationInfo`, we can make it `PydanticUndefined` if there's no default, and maybe add a `has_default -> bool` for convenience.

**Comment by samuelcolvin** [comment]
I *think* that would be possible with a change in pydantic-core alone, and it wouldn't be a breaking change as it's just a new attribute.

**Comment by samuelcolvin** [comment]
After a quick chat, we agreed the easiest and most correct route forward would be to create a new exception `PydanticReturnDefault` which is caught by the `ValidateDefault` validator and returns the default value.

I guess it should have the same signature as [`PydanticCustomError`](https://github.com/pydantic/pydantic-core/blob/424a2f80676efc83cc156203ab71dee21eb158d3/pydantic_core/_pydantic_core.pyi#L221) so if it's not caught it creates a good error in the `ValidationError`.

**Comment by vitalik** [comment]
@samuelcolvin ok, sounds good (not sure I completely understand :) ) - could you show some pseudo code how will it work ?

**Comment by adriangb** [comment]
```python
from typing import Any

from pydantic import BaseModel, FieldValidationInfo, PydanticReturnDefault , field_validator

class MyModel(BaseModel):
    price: int = 10

    @field_validator('price', mode='before')
    def empty_str_to_default(cls, v: Any, info: FieldValidationInfo) -> Any:
        if v == "":
            raise PydanticReturnDefault
        return v


print(MyModel(price=""))
#> price=10
print(MyModel(price=1))
#> price=1
```

**Comment by vitalik** [comment]
@adriangb well field_validator on model does not make sense here - I would like it to be fully implemented on a field class (`EmptyStrToDefault`)

**Comment by adriangb** [comment]
Ok, that would be:

```python
from typing import Annotated, Any, TypeVar

from pydantic import BaseModel, PydanticReturnDefault, ValidatorFunctionWrapHandler, WrapValidator

T = TypeVar('T')


def _empty_str_to_default(v: Any, handler: ValidatorFunctionWrapHandler) -> Any:
    if isinstance(v, str) and v == '':
        raise PydanticReturnDefault
    return handler(v)


EmptyStrToDefault = Annotated[T, WrapValidator(_empty_str_to_default)]


class MyModel(BaseModel):
    price: EmptyStrToDefault[int] = 10


print(MyModel(price=''))
# > price=10
print(MyModel(price=1))
# > price=1
```

**Comment by dmontagu** [comment]
@adriangb what if I want to return `2*<the default value>` when `v == ''`? Is that impossible?

**Comment by adriangb** [comment]
With this approach, yeah it would be impossible. If you always want to double it then you could do `foo: Annotated[EmptyStrToDefault[int], AfterValidator(lamdba x: x*2)]` but if you want to double it if and only if the default value is being used, but you don't want to just double the default value itself, then no with this approach that would not be possible.
