### ISSUE TITLE
Custom netmask for IPvAnyNetwork fields to ensure parity with ipaddress module

### ISSUE THREAD

**Issue by Lithimlin** [pydantic/pydantic#6278]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

In the pydantic implementation of the `IPvAnyNetwork` type it is impossible to set a custom net- or hostmask since the `strict` flag of the `ipaddress.IPvXNetwork` is always set to `True` and not adjustable:
https://github.com/pydantic/pydantic/blob/3e8b3b00e413cf737cb33dd60d15e69c6fd6b427/pydantic/networks.py#L340-L358

I am aware that it says right there that one should simply implement their own type, but I feel like an additional parameter in the constructor that is set to `True` by default would go a long way to ensure compatibility with the `ipaddress` module.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @lig

**Comment by commonism** [comment]
Why not use IPvAnyInterface if you need a cidr with host bits set in the address?

Besides - using ipaddress.{ip_network,ip_address,ip_interface} would allow getting rid of the v4/6 switch.
PR welcome?

**Comment by Lithimlin** [comment]
Mostly because it serves a different purpose. For example, an interface does not offer an automatic getter for the broadcast address of a network.

**Comment by commonism** [comment]
it does
```
>>> ipaddress.ip_interface("10.0.0.1/24").network.broadcast_address
IPv4Address('10.0.0.255')
```

strict=False changes the host address
```
>>> import ipaddress
>>> ipaddress.ip_network("10.0.0.1/24", strict=False)
IPv4Network('10.0.0.0/24')
```

Interface keeps it
```
>>> ipaddress.ip_interface("10.0.0.1/24").ip
IPv4Address('10.0.0.1')
```

**Comment by Lithimlin** [comment]
Ah, you're right. I hadn't considered that possibility. I suppose that's an appropriate solution.
