### ISSUE TITLE
v2 docs FR: use 3.9+ examples as the default

### ISSUE THREAD

**Issue by tuchandra** [pydantic/pydantic#6320]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

In the docs, when examples use generic collections, there are two panels: one marked 3.7+ (with `typing.List[int]`) and one marked 3.9+ (with `list[int]`). 

![image](https://github.com/pydantic/pydantic/assets/11623486/9035a96d-c786-481a-8b91-fa04974e1bc3)

My request is to switch the order of the examples. The 3.9+ examples, with standard collections, should be presented first / by default / without having to make an extra click. I'm not asking to drop support for anything, but I think enough time has passed since PEP 585 that the standard collections are a better default.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
Agreed, that makes sense to me

**Comment by tpdorsey** [comment]
Material for Mkdocs enables us to set a default tab. It should be 3.9+ or later, or the latest version for which we have an example tab? I will look into making this modification.

Note also that we have [linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs) enabled on the docs. Once you select a version tab, the docs should honor that selection for all other tabs for which there's an equivalent tab. I just tested on the latest release and can confirm it is working.

**Comment by adriangb** [comment]
> It should be 3.9+ or later, or the latest version for which we have an example tab?

If this was a question, I'd vote for 3.9+ or later. Hopefully, there won't be more tabs in the future.

**Comment by tpdorsey** [comment]
Relevant code is here: https://github.com/pydantic/pydantic/blob/1cf7cef3dcc01c849d78fc89c5bbf81888f80c81/docs/plugins/main.py#L105

As I see it, there are two ways address the issue of _not_ highlighting Python 3.7 by default. 

1. Around the above line, replace `===` with `===+` for the preferred default tab. This could be the highest version of Python, or just the tab for the version that's _not_ 3.7.
2. Create the tabs in reverse order, so the tabs go in decreasing order of Python version. In this case the highest version example would be selected by default by virtue of being first.

As noted above, the user's selected version will continue to be selected in other examples in which an equivalent tab exists.

**Comment by tpdorsey** [comment]
For additional background see: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
