### ISSUE TITLE
NameError: Field "model_id" has conflict with protected namespace "model_"

### ISSUE THREAD

**Issue by nuance1979** [pydantic/pydantic#6322]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The `NameError` about not allowing any field starting with "model_" is too restrictive because in machine learning applications, it is very common to have field name such as "model_id", "model_name", "model_path", etc.

I wonder if it is possible to warn, as opposed to raise, in this case.

### Example Code

```Python
from pydantic import BaseModel

class ModelParams(BaseModel):
    model_id: str

params = ModelParams(model_id="a")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /home/my_name/portable-python-env/envs/my_env/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
                     platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.17
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
@nuance1979 

You can opt out of the namespaces protection like this:

```python
from pydantic import BaseModel, ConfigDict


class ModelParams(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    model_id: str


params = ModelParams(model_id="a")
print(params)
#> model_id='a'
```
I will open a PR to improve the error message about this.

One thing we've discussed as a longer term plan is to provide a version of `BaseModel` (perhaps called `BareModel`) that doesn't have the methods so there is no risk of conflict (and we'll add free-standing functions like `dataclasses` does). But I think that's _probably_ not going to be a thing in the short term.

Open to suggestions about how we could handle this better.

**Comment by nuance1979** [comment]
Thanks @dmontagu for the quick reply! Good to know I can opt out like that. However, I still think it's way too heavy-handed to raise `NameError` in this case. I can understand if the field name is in direct conflict with, i.e., shadowing, a protected keyword.

I like the `BareModel` idea. Just hope it can happen faster. Meanwhile, my suggestions is to warn, not raise, unless the conflict will **actually** interfere with Pydantic features.

**Comment by nuance1979** [comment]
Anyway, I expect a lot of pain from the machine learning world because of this change.

**Comment by dmontagu** [comment]
I've opened a PR to make this a warning instead of an error, but I would like to get @samuelcolvin's opinions before moving forward with either path.

**Comment by nuance1979** [comment]
Is it possible to change the reserved namespace `model_` to `_pydantic_model_` in the future?

IMHO, reserving namespace `model_` infringes on the user's freedom of naming while the user can perfectly understand the reservation of `_pydantic_model_`.

**Comment by jinlow** [comment]
+1 for this issue, also using pydantic for machine learning applications and agree this makes pydantic’s use more limited because of this.

**Comment by sydney-runkle** [comment]
Closing this, as the message has been moved to a warning.
