### ISSUE TITLE
Should this be 'parameterized' or 'parametrized'?

### ISSUE THREAD

**Issue by jhcole** [pydantic/pydantic#6323]
The docs mention `model_parameterized_name`, but the method is actually named `model_parametrized_name` (missing the second 'e').  

https://github.com/pydantic/pydantic/blob/61b5998cdb8051f13f60c1edfdd40a30046a27b6/docs/usage/models.md?plain=1#L102

https://github.com/pydantic/pydantic/blob/61b5998cdb8051f13f60c1edfdd40a30046a27b6/pydantic/main.py#L377

Selected Assignee: @hramezani

**Comment by dmontagu** [comment]
Good catch. I believe I picked the spelling here, and was inspired on the spelling by `pytest.mark.parametrize`.

I think given v2 is released now, better to keep the method name the same and update the docs.
