### ISSUE TITLE
Meta: Badging for Pydantic v1 and v2

### ISSUE THREAD

**Issue by JacobCoffee** [pydantic/pydantic#6328]
It would be nice to have a badge for Pydantic to add them to repos, similar to Ruff's: https://github.com/astral-sh/ruff/blob/main/assets/badge/v2.json

Endpoints are documented here:
- https://shields.io/badges/dynamic-json-badge
- https://shields.io/badges/dynamic-yaml-badge

Examples:

[![Pydantic](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/JacobCoffee/482c716c1ee64bab9d073583c992503f/raw/2884be4b5144a284c9098d1f0abc28188ae1149a/pydantic.json)](https://pydantic.dev)

What the finished product to advertise might look like (URLs need updating once merge, i think?):
[![Pydantic v1](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/pydantic/pydantic/0e523a35483e17083161887f8f15a3612551a0be/docs/badge/v1.json)](https://pydantic.dev)
[![Pydantic v2](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/pydantic/pydantic/0e523a35483e17083161887f8f15a3612551a0be/docs/badge/v2.json)](https://pydantic.dev)

Related Gist:

https://gist.github.com/JacobCoffee/482c716c1ee64bab9d073583c992503f

Selected Assignee: @lig

**Comment by lig** [comment]
It looks like this one is resolved in #6329
