### ISSUE TITLE
.model_extra is non-None with extra="forbid"

### ISSUE THREAD

**Issue by aaraney** [pydantic/pydantic#6332]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Per the `model_extra` docs:

```python
@property
def model_extra(self) -> dict[str, Any] | None:
"""Get extra fields set during validation.

Returns:
    A dictionary of extra fields, or `None` if `config.extra` is not set to `"allow"`.
"""
```

I would expect when `config.extra="forbid"` `model_extra` would be `None`. However, that is not the case. 

Im happy to fix this and submit a PR if this is not the intended behavior!

### Example Code

```Python
from pydantic import BaseModel, ConfigDict

class Foo(BaseModel):
    model_config = ConfigDict(extra="forbid")

foo = Foo()
assert foo.model_extra is not None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: ~/home/user/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, Mar 24 2023, 12:31:28)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by dmontagu** [comment]
Might be a good idea to get @samuelcolvin's confirmation, but I agree it's preferable for it to be `None` rather than a dict in this case.

I've [opened a PR on pydantic-core](https://github.com/pydantic/pydantic-core/pull/725) that resolves this; I'll open a PR on pydantic adding your code as a test.
