### ISSUE TITLE
Inconsistent schema for condecimal and other constrained numeric types

### ISSUE THREAD

**Issue by RobertoPrevato** [pydantic/pydantic#6338]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi,
I suspect this is a bug, but I am not sure if this is not intentional.

`condecimal` and other numeric constrain types produce a different JSON schema. This changed in Pydantic v2 (I have a test in `blacksheep` about this).

For example if you look at the example I provide below, `confloat` generates a specific schema:

```json
        "positive_float": {
            "exclusiveMinimum": 0,
            "title": "Positive Float",
            "type": "number"
        }
```

While `condecimal` produces a `anyOf` schema that contemplates a string input:

```json
        "positive_decimal": {
            "anyOf": [
                {
                    "exclusiveMinimum": 0.0,
                    "type": "number"
                },
                {
                    "type": "string"
                }
            ],
            "title": "Positive Decimal"
        },
```

I would expect the `positive_decimal` to generate, like in Pydantic v1, something compatible with the others:

```json
        "positive_decimal": {
            "exclusiveMinimum": 0,
            "title": "Positive Decimal",
            "type": "number"
        }
```

### Example Code

```Python
from json import dumps
from pydantic import BaseModel
from pydantic.types import condecimal, confloat


class Example(BaseModel):
    positive_decimal: condecimal(gt=0)

    positive_float: confloat(gt=0)


print(dumps(Example.model_json_schema(), indent=4))

```

Produces this output:

```json
{
    "properties": {
        "positive_decimal": {
            "anyOf": [
                {
                    "exclusiveMinimum": 0.0,
                    "type": "number"
                },
                {
                    "type": "string"
                }
            ],
            "title": "Positive Decimal"
        },
        "positive_float": {
            "exclusiveMinimum": 0,
            "title": "Positive Float",
            "type": "number"
        }
    },
    "required": [
        "positive_decimal",
        "positive_float"
    ],
    "title": "Example",
    "type": "object"
}
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: ~/projects/github/blacksheep/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Oct 30 2022, 14:13:55) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by dmontagu** [comment]
Definitely a bug. @adriangb not sure, but I'm guessing your proposed change of using the python version of validators for the core schema might help fix this (or at least not hurt..)

**Comment by dmontagu** [comment]
Actually, I take it back.

Part of the problem is that the JSON schema you are seeing there is describing the inputs, and JSON schema only defines the `exclusiveMinimum` for number types. So I don't think it would be valid to say 
```
        "positive_decimal": {
            "exclusiveMinimum": 0.0,
            "anyOf": [
                {
                    "type": "number"
                },
                {
                    "type": "string"
                }
            ],
            "title": "Positive Decimal"
        },
```
However, I definitely don't think we want to drop `string` as a valid type for input, as that is the easiest way to make sure that there is no loss of precision induced by serialization to a number type. (Good JSON serialization/deserialization wouldn't cause that, but it's very easy to make a float conversion somewhere on accident and lose precision.)

So I actually think this is maybe not a bug but instead sort of a limitation of JSON schema. @adriangb defer to you on how you want to handle it.

**Comment by adriangb** [comment]
Indeed it’s not a bug, it’s a json schema limitation

**Comment by adriangb** [comment]
Does that confirmation solve the issue @RobertoPrevato or does the schema cause any real-world problems?

**Comment by RobertoPrevato** [comment]
@adriangb 
I only wanted to report that since v2 `condecimal` behaves in a different way than the other functions for numeric types, and this is probably not intentional.

Please read the output of the example I provided:

```python
from json import dumps
from pydantic import BaseModel
from pydantic.types import condecimal, confloat


class Example(BaseModel):
    positive_decimal: condecimal(gt=0)

    positive_float: confloat(gt=0)

    positive_int: conint(gt=0)


print(dumps(Example.model_json_schema(), indent=4))
```

Note the difference between the JSON schema produced for `condecimal(gt=0)` and the one of `confloat(gt=0)` and `conint(gt=0)`.

**Comment by adriangb** [comment]
The difference is because we accept strings as inputs to Decimal, even in strict mode, because there is no other way to transmit the data without loss of information.

**Comment by adriangb** [comment]
Use of the `con*` functions is also discouraged now

**Comment by RobertoPrevato** [comment]
I understand, thank you! 👍🏼
