### ISSUE TITLE
Remove `'allOf' JSON schema workarounds

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#6343]
https://github.com/pydantic/pydantic/pull/6336#issuecomment-1615801492

Selected Assignee: @hramezani

**Comment by dpeachey** [comment]
Hi,

Is this still planned to be implemented? I'm facing some issues because of the use of `allOf` with a single `$ref` in the JSON schema output which I think may well be resolved by the implementation of this (I assume removing `allOf` in favour of a single direct `$ref`). 

Thanks,

Dan
