### ISSUE TITLE
`ConfigDict.json_schema_extra` has type `Dict[str, object]`

### ISSUE THREAD

**Issue by TimDiekmann** [pydantic/pydantic#6348]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The `json_schema_extra` is defined as `dict[str, object] | JsonSchemaExtraCallable | None` so it's (theoretically) not possible to add a simple string->string mapping.

I would consider this as a bug as the functionality is working but the types are wrong and it should probably be `dict[str, Any]`

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: <REDACTED>
               python version: 3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by samuelcolvin** [comment]
PR welcome to make this

```py
JsonType = dict[str, list[JsonType] | JsonType | int | float | None]
```

**Comment by Marble879** [comment]
Hey, is it possible to work on this?

If so, I also want to ask if `JsonType = dict[str, int | float | None | JsonType | list[JsonType]]` is supposed to replace the properties defined for `json_schema_extra` in the config.py file, or just be added to the existing properties?

**Comment by Kludex** [comment]
It's supposed to replace everywhere that makes sense.

**Comment by vladNed** [comment]
Hi, is this issue still valid ? I can start working on this ?

**Comment by vladNed** [comment]
@samuelcolvin tried the `JsonType` you provided but it will have issues with `mypy` as its a recursive type. I would suggest to maybe add with my first approach in the PR above. 

```python
JsonType = Dict[str, Union[str, int, float, bool, None, List[Any], Dict[str, Any]]]
```

or leave it as 

```python
JsonType = Dict[str, Any]
```
