### ISSUE TITLE
Using multiple `Field`s in a single `Annotated` is broken

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#6353]
For BaseModel metadata gets dropped. For dataclasses we prohibit it, but I suspect we don't do a good job of detecting it in all cases.

```python
from typing import Annotated

from pydantic import Field, BaseModel


class Model(BaseModel):
    foo: Annotated[int, Field(description='xyz'), Field(title='abc')]


print(Model.model_json_schema())  # title gets dropped
```

Similarly with TypeAdapter:

```python
from typing import Annotated

from pydantic import Field, TypeAdapter


# all metadata ignored
print(
    TypeAdapter(
        Annotated[int, Field(description='xyz'), Field(title='abc')]
    ).json_schema()
)
```

(I think this last case is being fixed in https://github.com/pydantic/pydantic/pull/6336)

```python
from typing import Annotated

from pydantic import TypeAdapter, Field, dataclasses


@dataclasses.dataclass
class Model:
    foo: Annotated[int, Field(description='xyz'), Field(title='abc')]


print(TypeAdapter(Model).json_schema())  # TypeError: Field may not be used twice on the same field
```

I think we should figure out if we can merge `Fields` w/ some sort of semantics for overriding and support that everywhere.

Selected Assignee: @lig

**Comment by TimDiekmann** [comment]
In my head, it feels that the outer annotation `Field2` should have higher precedence:
```
assert Annotated[Annotated[T, Field1], Field2] == Annotated[T, Field1, Field2]
```

Typically, newer annotations probably have more information than older annotations (assuming they're constructed from the inside to the outside). The contextual information about the _thing_ is bigger. This also aligns with the reading flow by starting at the leftmost field and updating it with new occurrences.
