### ISSUE TITLE
PostgresDsn no longer has a 'build' attribute.

### ISSUE THREAD

**Issue by ollz272** [pydantic/pydantic#6355]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

We are no longer able to build using PostresDSN

### Example Code

```Python
@property
def uri(self) -> PostgresDsn:
    """Return uri for connection."""
    return PostgresDsn.build(
        scheme=self.scheme,
        user=self.user,
        password=self.password,
        host=self.host,
        port=str(self.port),
        path=f"/{self.dbname}",
        query=f"sslmode={self.sslmode}",
    )


However, we now get the following error:
`AttributeError: type object 'pydantic_core._pydantic_core.MultiHostUrl' has no attribute 'build'`
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /Users/oliver/Library/Caches/pypoetry/virtualenvs/sherlock-9z3yAd_C-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 15 2023, 07:55:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by ollz272** [comment]
I guess this is actually a pydantic core issue since this is now in core. https://github.com/pydantic/pydantic-core/blob/0d12efd1725ce190f13f9e51af3fd74b6cbab23e/src/url.rs#L158 would be my _guess_ on where its located.

**Comment by ollz272** [comment]
Yeah - It seems pydantic-core needs a 'Build' method on MultiHostUrl (or similar). Im not familiar with rust so would find this hard to fix, but happy to give it a go.

**Comment by adriangb** [comment]
Can you template into a string and call `PostgresDsn` with that string?

**Comment by ollz272** [comment]
@adriangb Yeah - I think thats what we'll have to do in the meantime, though the old connivance method was nice

**Comment by ezeparziale** [comment]
I had the same error with the `build` but I replaced with a manual url

```
    # Database
    POSTGRES_HOSTNAME: str
    POSTGRES_PORT: str
    POSTGRES_USER: str
    POSTGRES_PASSWORD: str
    POSTGRES_DB: str

    SQLALCHEMY_DATABASE_URI: Optional[PostgresDsn] = None

    @validator("SQLALCHEMY_DATABASE_URI", pre=True)
    def assemble_db_connection(cls, v: Optional[str], values: Dict[str, Any]) -> Any:
        if isinstance(v, str):
            return v
        scheme = "postgresql"
        user = values.get("POSTGRES_USER")
        password = values.get("POSTGRES_PASSWORD")
        host = values.get("POSTGRES_HOSTNAME")
        port = values.get("POSTGRES_PORT")
        path = f'/{values.get("POSTGRES_DB", "")}'

        url = f"{scheme}://{user}:{password}@{host}:{port}{path}"
        return PostgresDsn(url)
```

Finally, I used with unicode_string() when I created the sqlalchemy engine

`engine = create_engine(settings.SQLALCHEMY_DATABASE_URI.unicode_string())`

**Comment by ollz272** [comment]
I've created a PR https://github.com/pydantic/pydantic-core/pull/730 here in pydantic core. Im sure it needs some work, but seems to be good from what i can tell.

**Comment by ollz272** [comment]
This has been implemented, closing
