### ISSUE TITLE
Change in behaviour when a models property raises an attribute error.

### ISSUE THREAD

**Issue by ollz272** [pydantic/pydantic#6360]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Whilst trying to debug an error in my code, I kept getting an error telling me that my property doesn't exist. Code was something like:

```python
class Model(BaseModel):

    @property
    def some_thing()
        AClass.do_something()
```

The _actual_ error we had was that do_something didn't exist in AClass, however the error being raised was that some_thing didn't exist on model, which was weird. This seems to be a change since V2, now getattr is implemented on Base Model. 

Whilst maybe not a *bug*, it makes debugging other errors harder as the actual error isn't shown.

### Example Code

```Python
import pytest
from pydantic import BaseModel

from pydantic.v1 import BaseModel as BaseModelV1


def test_v1_attribute_error():

    class Model(BaseModelV1):

        @property
        def a_property(self):
            raise AttributeError("Internal Error")

    with pytest.raises(AttributeError, match="Internal Error"):
        Model().a_property


def test_v2_attribute_error():

    class Model(BaseModel):

        @property
        def a_property(self):
            raise AttributeError("Internal Error")

    with pytest.raises(AttributeError, match="Internal Error"):
        Model().a_property



test_v1_attribute_error()
test_v2_attribute_error()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /Users/oliver/Library/Caches/pypoetry/virtualenvs/sherlock-9z3yAd_C-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 15 2023, 07:55:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @ollz272 for reporting this.

Yes, In V2, we have `BaseModel.__getattr__` and it handles private and extra attrs.

Not sure how we are going to handle this case.

@samuelcolvin Do you have any idea?

**Comment by dmontagu** [comment]
Clever idea (combined with @hramezani's idea to check hasattr):
```python
                    if hasattr(self.__class__, item):
                        return super().__getattribute__(item)
```
seems to work to raise the underlying AttributeError. Suggested on @hramezani's PR
