### ISSUE TITLE
Support `json_encoders` in Pydantic v2

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#6375]
We deprecated `json_encoders` from Config in v2, but I'm not sure that there's a good replacement.

> Due to performance overhead and implementation complexity, we have now removed support for specifying `json_encoders` in the model config. This functionality was originally added to achieve custom serialization logic, and we think the new serialization decorators are a better choice in most common scenarios. However, if your usage of `json_encoders` is not compatible with the new serialization decorators, please create a GitHub issue letting us know. See [Custom data types](usage/types/custom.md) for further details.

Firstly, this config option is not equivalent to custom data types because a custom data type would require replacing that type everywhere, adding a lot of migration friction. I've tried migrating several libraries and this is one of the trickiest bits.

Second, I don't think the performance justification is valid: if you need to run Python code to serialize that's going to be the case even with custom types. I don't see any reason why we can't add a `PlainSerializerFunctionSerSchema` whenever we encounter a type that matches `json_encoders` statically while building the `CoreSchema` unless there's some dynamic runtime behavior in v1 that I'm not understanding.

Selected Assignee: @dmontagu

**Comment by adriangb** [comment]
We eventually want to support something similar for validation, perhaps allowing mapping `{pd.Timestamp: CustomPdTimestampType}`. I've seen `json_encoders` often used with `arbitrary_types_allowed`, allowing mapping to a custom type would be the right replacement for both.

We happen to [have a `serialization` field for definitions](https://github.com/pydantic/pydantic-core/blob/d285975d8634c793e2cf8809b4c7cd3ba013c3d2/python/pydantic_core/core_schema.py#L3634) so we can actually add serialization to any type without breaking references, but we can't do the same for validation in general. That is, there's no way to add a `greater than 0` constraint on a type without creating a new reference. In particular, if two libraries overrode a type in this way and they were both used within one model/schema we'd have no way to differentiate them unless we create two different references. That's a hard problem that we're not ready to solve yet.

**Comment by tuukkamustonen** [comment]
Commeting on a closed ticket but... so the support has been added back, but there's still the deprecation note.

Is there already a better solution (field specific serialization adds so much noise) or should we tolerate (or silence) the warning, and trust that reincarnation of the feature will appear in V3?

**Comment by WilliamStam** [comment]
running into this exact thing at the moment. since the depreciation warning is messing with pytest n stuff tried fixing it. 

used to use it for stuff like

```python
class BaseModel(ParentBaseModel):
    model_config = ConfigDict(
        use_enum_values=True,
        json_encoders={
            datetime: lambda value: value.strftime("%Y-%m-%d %H:%M:%S"),
            date: lambda value: value.strftime("%Y-%m-%d"),
            time: lambda value: value.strftime("%H:%M:%S"),
            Decimal: lambda value: float(value),
        },
    )
```

which worked great. 

now the "new" way is to go through and for every field add a field serializer. no global catch all to change dates to the required format type thing). is to use field_serializer but then the fastapi docs all break in openapi spec.
