### ISSUE TITLE
Object have Union property can not be quote. 

### ISSUE THREAD

**Issue by wgj8538** [pydantic/pydantic#6379]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

raise a TypeError:
TypeError: `discriminator` can only be used with `Union` type with more than one variant

### Example Code

```Python
from typing import Literal, Union
from pydantic import BaseModel, Field, ValidationError

class Base(BaseModel):
    t : str # the discriminator field!

class One(Base):
    t: Literal['one']

class Two(Base):
    t: Literal['two']

class Model(BaseModel):
    pet: Union[One, Two] = Field(..., discriminator='t') 

### Open this, a bug happen.
# class A(BaseModel):
#     m: Model

test = Model(**{'pet': {'t':'two'}}) 
print(test)
"""
TypeError: `discriminator` can only be used with `Union` type with more than one variant
"""
```

### Python, Pydantic & OS Version

```Text
Python 3.11.4
pydantic 2.0.1
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @wgj8538 

This is fixed on https://github.com/pydantic/pydantic/commit/1943e9da182de1d9172b40b165d64e720da4f041.

It will be available in the next release.

Please test it on the `main` branch.
