### ISSUE TITLE
ModelMetaclass can no longer be imported from pydantic.main

### ISSUE THREAD

**Issue by martinezpl** [pydantic/pydantic#6381]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

`ImportError: cannot import name 'ModelMetaclass' from 'pydantic.main'`

This change is not mentioned in the changelog nor in the migration guide.

The import now should be:

`from pydantic._internal._model_construction import ModelMetaclass`

### Example Code

```Python
from pydantic.main import ModelMetaclass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
pydantic-core version: 2.0.1 release build profile

python version: 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)]
platform: macOS-13.4.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
Thanks for the report @martinezpl 🙏 

For curiosity, may I know your use case with `ModelMetaclass`?

I'm unsure if we should make it public, or update the migration guide + letting people know when importing `ModelMetaclass` that we have removed it.

**Comment by martinezpl** [comment]
I use it to render fields optional without having None or default values. I find it useful for `PATCH` requests, where user updates only specific fields of an object. Is there another way of achieving this in V2?

```python
# metaclass to make all fields in a model optional, useful for PATCH requests
class _AllOptionalMeta(ModelMetaclass):
    def __new__(
        self, name: str, bases: Tuple[type], namespaces: Dict[str, Any], **kwargs
    ):
        annotations: dict = namespaces.get("__annotations__", {})

        for base in bases:
            for base_ in base.__mro__:
                if base_ is BaseModel:
                    break

                annotations.update(base_.__annotations__)

        for field in annotations:
            if not field.startswith("__"):
                annotations[field] = Optional[annotations[field]]

        namespaces["__annotations__"] = annotations

        return super().__new__(self, name, bases, namespaces, **kwargs)
```
 
An example of a resource. Most of these parameters are required for creation, but through `PATCH` request only one field can be provided, while the rest is not modified within the DB.
 
```python
class Vertical(BaseModel):
    id: str
    languageCode: str
    description: str
    tags: list
    name: str
    utterances: list
    utteranceCount: int = 0
    
    # ... validators ...
 
class VerticalUpdate(Vertical, metaclass=_AllOptionalMeta):

    @root_validator(pre=True)
    def remove_id(cls, values):
        """
        ID cannot be updated.
        """
        values.pop("id", None)
        return values
 ```

**Comment by dmontagu** [comment]
@martinezpl 

We did this on purpose because we want to be able to refactor the `ModelMetaclass` without it being considered a breaking change. This is helpful because it allows us to add functionality or address bugs without needing to preserve every little observable nuance of how the metaclass works.

To be clear, the metaclass was not intended to be a public API even in v1. (We refactored to make this more explicit in v2.) I think you are right that we should document this in the migration guide though.

I think if you are willing to take on the maintenance burden that comes with it being possible that the metaclass might break, you can still do `from pydantic._internal._model_construction import ModelMetaclass` and work with that. In general, looking at your code, I think it's pretty unlikely that we'll break your implementation, I just wouldn't want to promise that.

However, I think we are not likely to go out of our way to support a workflow like this that involves modifying the annotations programmatically in the metaclass because it would be very hard to get it to play nice with type checkers like mypy or pyright. In particular, in your `VerticalUpdate` class, no type-checker won't be able to detect that the fields are all optional. I do understand the utility of this for PATCH requests, but I think we don't want to add anything specific for this until we see if Python introduces anything like TypeScript's `Partial`.

I will also note that you may be able to achieve something similar with `create_model`, which wouldn't involve the use of private APIs. Given how little usage there probably is of a similar nature, it won't surprise me if you find bugs, but I do think we are more likely to try to address those bugs/feature requests than we are to promise that we won't make breaking changes to the `ModelMetaclass`.

**Comment by martinezpl** [comment]
Thank you for the comprehensive answer. 

I think it is totally reasonable why you'd prefer to have the metaclass private and I'm fine with the implications of using private API from now on. 

It probably should be mentioned at least in the changelog, that `ModelMetaclass` is now considered private and moved to `pydantic._internal._model_construction`.

**Comment by rm-minus-r-star** [comment]
Another use case, and the one that brought me here, is https://www.inwt-statistics.com/blog/pandas-data-frame-validation-with-pydantic-part-2. This was quite a nice decorator that lets me jump from pandas dataframe to sql. Is there a substitute class to inherit from?

**Comment by martinezpl** [comment]
`from pydantic._internal._model_construction import ModelMetaclass` in v2

**Comment by mbreemhaar** [comment]
@martinezpl 
I needed this for the same use case, but I solved it by adding this to my `BaseModel`:

```
@classmethod
    def all_optional(cls, name: str) -> type[Self]:
        """
        Creates a new model with the same fields, but all optional.

        Usage: SomeOptionalModel = SomeModel.all_optional('SomeOptionalModel')
        """
        return create_model(
            name,
            __base__=cls,
            **{name: (info.annotation, None) for name, info in cls.model_fields.items()}
        )
```

**Comment by silviumarcu** [comment]
@martinezpl Had the same issue/use case, this is my take on handling partial pydantic models

The only issue with this implementation is that mypy does not handle dynamic models which will require to ignore mypy in some cases.

```py
Model = typing.TypeVar("Model", bound=BaseModel)

class Partial(typing.Generic[Model]):
    """Generate a new class with all attributes optionals.

    Notes:
        This will wrap a class inheriting form BaseModel and will recursively
        convert all its attributes and its children's attributes to optionals.

    Example:
        Partial[SomeModel]
    """

    def __new__(
        cls,
        *args: object,  # noqa :ARG003
        **kwargs: object,  # noqa :ARG003
    ) -> "Partial[Model]":
        """Cannot instantiate.

        Raises:
            TypeError: Direct instantiation not allowed.
        """
        raise TypeError("Cannot instantiate abstract Partial class.")

    def __init_subclass__(
        cls,
        *args: object,
        **kwargs: object,
    ) -> typing.NoReturn:
        """Cannot subclass.

        Raises:
           TypeError: Subclassing not allowed.
        """
        raise TypeError("Cannot subclass {}.Partial".format(cls.__module__))

    def __class_getitem__(  # type: ignore[override]
        cls,
        wrapped_class: type[Model],
    ) -> type[Model]:
        """Convert model to a partial model with all fields being optionals."""

        def _make_field_optional(
            field: pydantic.fields.FieldInfo,
        ) -> tuple[object, pydantic.fields.FieldInfo]:
            tmp_field = copy.deepcopy(field)

            annotation = field.annotation
            # If the field is a BaseModel, then recursively convert it's
            # attributes to optionals.
            if type(annotation) is type(BaseModel):
                tmp_field.annotation = typing.Optional[Partial[annotation]]  # type: ignore[assignment, valid-type]
                tmp_field.default = {}
            else:
                tmp_field.annotation = typing.Optional[field.annotation]  # type: ignore[assignment]
                tmp_field.default = None
            return tmp_field.annotation, tmp_field

        return pydantic.create_model(  # type: ignore[no-any-return, call-overload]
            f"Partial{wrapped_class.__name__}",
            __base__=wrapped_class,
            __module__=wrapped_class.__module__,
            **{
                field_name: _make_field_optional(field_info)
                for field_name, field_info in wrapped_class.model_fields.items()
            },
        )
```

**Comment by atlantis-dsf** [comment]
Sorry to bother @silviumarcu, can you give an example of usage please?

**Comment by silviumarcu** [comment]
@atlantis-dsf Sure, here you go. What I forgot to mention in my answer is that this will create some mypy issues as mypy does not handle dynamic models.
```
class Item(BaseModel):
    name: str
    description: str
    price: float
    tax: float


@app.post("/items", response_model=Item)
async def post_item(item: Partial[Item]):
    ...
```

**Comment by vaidik** [comment]
@silviumarcu your response has been super helpful. Helped me out of a hairy situation with nested models. Thanks 👍

**Comment by simaphill** [comment]
Hi @silviumarcu , thanks for sharing your solution its super helpful!
any idea how i can remove validator functions from the partial class (so that they dont raise errors for fields that became optional)?

**Comment by aps08** [comment]
Anyone found the alternative to this `from pydantic.main import ModelMetaclass` import ? . I got a old project to maintain and we are using it the same way @martinezpl is [using](https://github.com/pydantic/pydantic/issues/6381#issuecomment-1618214335).

The altertive `pydantic._internal._model_construction import ModelMetaclass` is told not to use in this [issue](https://github.com/NRLMMD-GEOIPS/geoips/issues/1172).

So do we have to any alternative or we just to stop using it ?
