### ISSUE TITLE
field_validator and validator are "Untyped decorators" according to newest mypy version

### ISSUE THREAD

**Issue by KjeldSchmidt** [pydantic/pydantic#6386]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hey there!

I use pydantic and mypy in conjunction. With pydantic v2, there appears to be a problem with field validation.

The example code runs in this environment:

Python 3.10.11
Pydantic 2.0 (newest release, as of time of writing)
Mypy 1.4.1 (newest release, as of time of writing)

This is a virtual environment with no other dependencies or installed packages.

Running `mypy --strict --show-error-context --pretty Bar.py` results in this:

```
Ba.py:8: error: Untyped decorator makes function "validate_foo" untyped  [misc]
        @field_validator("foo")
```

The problem also exists with the now-deprecated `validator` decorator, but is not present with Pydantic Version 1.10.10.

I checked the migration guide and did not find any changes I needed to perform, other than using `field_validator` instead of `validator`.

Many thanks!

### Example Code

```Python
from pydantic.class_validators import field_validator
from pydantic.main import BaseModel


class Bar(BaseModel):
    foo: str

    @field_validator("foo")
    @classmethod
    def validate_foo(cls, value: str) -> str:
        return value
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
pydantic-core version: 2.0.1 release build profile
python version: 3.10.11 (main, Apr  7 2023, 07:31:31) [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-13.4.1-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

Selected Assignee: @dmontagu

**Comment by adriangb** [comment]
I'm not sure why but just changing the import fixes things:

```python
from pydantic import BaseModel, field_validator


class Bar(BaseModel):
    foo: str

    @field_validator("foo")
    @classmethod
    def validate_foo(cls, value: str) -> str:
        return value
```

I'm guessing it has to do with the mypy plugin.

**Comment by adriangb** [comment]
(sorry wrong button, but please close if that fixes it for you)

**Comment by dmontagu** [comment]
The reason why it doesn't work from `class_validators` is because the import is produced by a `module.__getattr__`, which mypy can't introspect. This is related to the fact that that import path is deprecated. So yes, I believe @adriangb's suggestion should fix the issue.

Also, to be clear,
```python
from pydantic.class_validators import field_validator
```
this will raise an import error as `field_validator` is not importable from `pydantic.class_validators`, which is probably also related to why this isn't working with mypy.

**Comment by KjeldSchmidt** [comment]
Sorry for the delayed response - this is the answer I was searching for, thanks a lot!
