### ISSUE TITLE
Faux immutability / `allow_mutation` has no effect on dataclass

### ISSUE THREAD

**Issue by gimbo** [pydantic/pydantic#639]
# Bug

* OS: MacOS Mojave 10.14.5
* Python version: 3.7.3
* Pydantic version: 0.29

Faux immutability / the `allow_mutation` flag seems to have no effect on dataclasses; I suppose this should either be fixed or made explicit in the documentation.

Example:

```py
from pydantic import BaseModel
from pydantic.dataclasses import dataclass


# BaseModel version, which works OK

class Foo(BaseModel):
    x: int
    class Config:
        allow_mutation = False

foo = Foo(x=1)

try:
    foo.x = 2
    print('Mutated Foo instance OK')
except TypeError as e:
    print('Failed to mutate Foo instance')
    print(e)



# dataclass version, which doesn't seem to work

class NoMutationConfig:
    allow_mutation = False

@dataclass(config=NoMutationConfig)
class Bar:
    x: int

bar = Bar(x=1)

try:
    bar.x = 2
    print('Mutated Bar instance OK')
except TypeError as e:
    print('Failed to mutate Bar instance')
    print(e)
```

Output; `BaseModel` version raises exception as expected, but `dataclass` version doesn't:

```shell
$ python ./pydcheck.py
Failed to mutate Foo instance
"Foo" is immutable and does not support item assignment
Mutated Bar instance OK
```

**Comment by samuelcolvin** [comment]
you should use [`frozen`](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass) on the dataclass.

But it should be possible for us to populate `frozen` from `allow_mutation` on the config. PR welcome.

**Comment by bruceadams** [comment]
To be concrete about using `frozen`, running this:

```python
from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class Bar:
    x: int

bar = Bar(x=1)
bar.x = 2
```

produces this:

```bash
$ python bug639.py
Traceback (most recent call last):
  File "bug639.py", line 8, in <module>
    bar.x = 2
  File "<string>", line 3, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'x'
```

One thing I really like about using `@dataclass(frozen=True)` is that `mypy`, by default, treats any attempt to set an instance variable as an error:

```bash
$ mypy bug639.py
bug639.py:8: error: Property "x" defined in "Bar" is read-only
Found 1 error in 1 file (checked 1 source file)
```

For me, this is a solid advantage for using Pydantic's baseclass instead of BaseModel. `mypy` does not recognize BaseModel/Config `allow_mutation = False`, meaning any bad code is only detected at runtime.

**Comment by dmontagu** [comment]
@bruceadams Once v1.0 is out I'll finalize work on the mypy plugin #722; it currently does detect `allow_mutation = False` and will cause mypy errors in the same way that `frozen=True` does on a dataclass

**Comment by bruceadams** [comment]
Very nice! I look forward to that @dmontagu! Thanks!

**Comment by samuelcolvin** [comment]
this is fixed on main and will be included in V2.
