### ISSUE TITLE
Getting TypeError when using a field with a reserved keyword

### ISSUE THREAD

**Issue by josecsotomorales** [pydantic/pydantic#6394]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Getting this error when migrating my project to Pydantic V2, I can use aliases to workaround this, but this works with Pydantic V1 so just wanted to make sure you guys are aware.

stack trace:
```
list: list[Any] | None = None
E   TypeError: 'NoneType' object is not subscriptable
```

### Example Code

```Python
from pydantic import BaseModel
from typing import Any

class MyModel(BaseModel):
    list: list[Any] | None = None
    datetime: datetime | None = None

MyModel.model_validate({'list': [1,2,3]})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
pydantic-core version: 2.0.1 release build profile install path: /Users/Jose/Workspace/TestProject/venv/lib/python3.11/site-packages/pydantic
python version: 3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
This doesn't seem to work on v1 as well:

```py
from pydantic import BaseModel
from datetime import datetime
from typing import Any


class MyModel(BaseModel):
    list: list[Any] | None = None  # You can't use `"list"` as field name
    d: datetime | None = None


MyModel(list=[1, 2, 3])
```

You are using `list` and `datetime` as attributes, which are the same as the types you are trying to use. You can change the field names, and it will work as expected.

**Comment by josecsotomorales** [comment]
All good with closing it, just figured out that's not actually the Pydantic version, it's related to nested models, see this example:

```
from pydantic import BaseModel
from datetime import datetime


class Child(BaseModel):
    list: list[int]
    datetime: datetime | None


class Parent(BaseModel):
    child: Child


Parent.model_validate({'child': {'list': [1, 2, 3, 4, 5], 'datetime': '2023-06-03 00:00:00'}})
```

**Comment by Kludex** [comment]
The above example is also working... What was supposed to happen?

**Comment by josecsotomorales** [comment]
See the example, of how I'm using the field names `list` and `datetime`, they don't throw a `TypeError: 'NoneType' object is not subscriptable` when the model is nested, if I do the same in the parent model it fails with that error.

**Comment by dmontagu** [comment]
To be clear, this is not a bug in pydantic — it's an issue with python:
```python
from datetime import datetime
from typing import Any


class MyModel:
    list: list[Any] | None = None
    datetime: datetime | None = None
"""
TypeError: 'NoneType' object is not subscriptable
"""
```
It seems the annotations get evaluated in the presence of the class namespace. And because pydantic needs to actually introspect them, it will error when building the model even if you try to do something like `list: 'list[Any] | None' = None`.

If you need this to be the field name, I would suggest using an alias:
```python
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class MyModel(BaseModel):
    l: list[Any] | None = Field(default=None, alias='list')
    d: datetime | None = Field(default=None, alias='datetime')


print(MyModel.model_validate({"list": [1, 2, 3]}).model_dump(by_alias=True))
#> {'list': [1, 2, 3], 'datetime': None}
```

**Comment by dmontagu** [comment]
Oh, better yet — if you just pre-assign an alias that won't conflict with the namespace in the class definition, it works as desired:
```python
from datetime import datetime
from typing import Any

from pydantic import BaseModel

List = list
Datetime = datetime


class MyModel(BaseModel):
    list: List[Any] = None
    datetime: Datetime = None


print(MyModel.model_validate({"list": [1, 2, 3]}))
#> list=[1, 2, 3] datetime=None
```

I think that's as good as you could possibly hope for given the fact that the original code example raises an error even if the class isn't a pydantic model.

**Comment by josecsotomorales** [comment]
Very impressive explanation @dmontagu! Thank you, it's definitely an edge case, addressed by using a pydantic alias similar to the example you posted above 🚀
