### ISSUE TITLE
Issue with Type inheritance

### ISSUE THREAD

**Issue by Fokko** [pydantic/pydantic#6403]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I've been working on upgrading to Pydantic 2.0 (thanks everyone for the great works!). But it seems that with the introduction of the `RootModel`, the hierarchy became more complicated. See the notebook below:

![image](https://github.com/pydantic/pydantic/assets/1134248/b12f3361-fe62-4940-891d-daf9c81ecb61)

Before with the `__root__` we could easily (de)serialize from a string instead of a dict. Now we have to define an actual type to make this work.

### Python, Pydantic & OS Version

```Text
(pyiceberg-0Eb0aXNo-py3.9) ➜  python git:(fd-bump-pydantic) python -c "import pydantic.version; print(pydantic.version.version_info())"

             pydantic version: 2.0
        pydantic-core version: 2.0.2 release build profile
                 install path: /Users/fokkodriesprong/Library/Caches/pypoetry/virtualenvs/pyiceberg-0Eb0aXNo-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.17 (main, Jun 20 2023, 18:00:22)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```
```


Selected Assignee: @davidhewitt

**Comment by adriangb** [comment]
I think we need to dig a bit more into the use case. I'm not sure what `RootBar` is supposed to be, I don't think we designed things for `RootModel` and `BaseModel` to be used as a base of a class at the same time.

> Before with the __root__ we could easily (de)serialize from a string instead of a dict. Now we have to define an actual type to make this work.

If you can have a plain `str` or an instance of `Bar` why not do `just_subclasses: str | Bar`?

**Comment by dmontagu** [comment]
@Fokko do you have a code example using pydantic v1 and `__root__` where things are working the way you want? That would probably help us better understand what you are trying to do.

**Comment by Fokko** [comment]
Hey everyone, and thanks for the quick response. Let me provide more context.

At PyIceberg we use Pydantic to (de)serialize the metadata. We really like it, and makes things much easier.

One of the important parts is the `Schema`:

```python
from typing import Type, TypeVar, List

from pydantic import BaseModel, Field

class IcebergType(BaseModel):
    pass


class ListType(IcebergType):
    type: str = "list"
    element_type: IcebergType = Field()


class StringType(IcebergType):
    __root__: str = "string"


class Schema(BaseModel):
    fields: List[IcebergType] = Field()
```

We use this to compose schema's:

![image](https://github.com/pydantic/pydantic/assets/1134248/48c3d745-4281-4ab9-a180-4de0ab35ca85)

This is a very simple example of a string primitive type (encoded as a `string`), and a List complex type (encoded as a `dict`).

**Comment by davidhewitt** [comment]
I think the following simplification illustrates a reduced version of the OP without needing `RootModel`:

```python
from pydantic import BaseModel

class IcebergType(BaseModel):
    pass

class IntType(IcebergType):
    type: str = "int"
    min: int | None = None
    max: int | None = None

class StringType(IcebergType):
    type: str = "str"
    min_length: int | None = None
    max_length: int | None = None

class Schema(BaseModel):
    fields: list[IcebergType]

print(IntType().model_dump_json())
# '{"type":"int","min":null,"max":null}'

StringType().model_dump_json()
# '{"type":"str","min_length":null,"max_length":null}'

Schema(fields=[IntType(), StringType()]).model_dump_json()
# '{"fields":[{},{}]}'
```

It seems to me that what the issue is about is that `Schema.model_dump_json` serializes all elements of `fields` as if they were `IcebergType` , i.e. just `{}`. What seems to be desired is that the fields get serialized as their concrete types. So the expected serialization should be:

```python
Schema(fields=[IntType(), StringType()]).model_dump_json()
# '{"fields": [{"type": "int", "min": null, "max": null}, {"type": "str", "min_length": null, "max_length": null}]}'
```

I can confirm that Pydantic V1 uses the subtypes for serialization. So this is either an intentional breaking change which needs to be documented, or a bug which needs resolution. 

@Fokko have I understood this correctly?

@dmontagu @adriangb what are your opinions on this?

**Comment by lig** [comment]
This works

```py
    class IcebergType(BaseModel):
        pass

    class IntType(IcebergType):
        type: str = 'int'
        min: int | None = None
        max: int | None = None

    class StringType(IcebergType):
        type: str = 'str'
        min_length: int | None = None
        max_length: int | None = None

    class Schema(BaseModel):
        fields: list[Union[IntType, StringType]]

    assert IntType().model_dump() == {'type': 'int', 'min': None, 'max': None}
    assert StringType().model_dump() == {'type': 'str', 'min_length': None, 'max_length': None}

    assert Schema(fields=[IntType(), StringType()]).model_dump() == {
        'fields': [{'type': 'int', 'min': None, 'max': None}, {'type': 'str', 'min_length': None, 'max_length': None}]
    }
```

Indeed, in Pydantic V2 we build schema entirely based on annotations provided. So, when it is `list[IcebergType]` it will be serialized using a serializer that corresponds to `IcebergType`.

Defining `list[Union[IntType, StringType]]` solves the issue for now. However, this is being done the same way as it would be for any two classes not necessarily having a common ancestor.

I think, allowing a subclass being used with a base class annotation is a fairly usable use case.

It means something like the following should work (it doesn't now).

```py
    class AModel(BaseModel):
        pass

    class BModel(AModel):
        value: int
    
    class Model(BaseModel):
        m: AModel
    
    assert Model(m=BModel(value=42)).model_dump() == {'m': {'value': 42}}
```

**Comment by Fokko** [comment]
Thanks everyone for digging into this. Unfortunately, we can't change the serialization from `"string"` to `{"type": "string"}`. This is part of the Iceberg specification: https://iceberg.apache.org/spec/#appendix-c-json-serialization

The `Union` would do it for me, but it feels a bit awkward.

![image](https://github.com/pydantic/pydantic/assets/1134248/c639917b-63f0-4a9e-84e9-2d3942ef35e1)

**Comment by davidhewitt** [comment]
From direct chat with @dmontagu and @adriangb I understand the serialization is an intended change, and you need to wrap your field with `SerializeAsAny` to opt-in to serializing inheritance.

So your schema should be updated to look like this:

```python
from typing import List

from pydantic import BaseModel, Field, RootModel, SerializeAsAny

class IcebergType(BaseModel):
    pass

class ListType(IcebergType):
    type: str = "list"
    element_type: SerializeAsAny[IcebergType] = Field()


class StringType(RootModel, IcebergType):
    root: str = "string"


class Schema(BaseModel):
    fields: List[SerializeAsAny[IcebergType]] = Field()
```

That then hopefully works as you intend:

```python
Schema(fields=[ListType(element_type=StringType())]).model_dump_json()
# '{"fields":[{"type":"list","element_type":"string"}]}'
```

**Comment by Fokko** [comment]
Hey @davidhewitt. I wasn't aware of `SerializeAsAny`. That seems to do the trick, thank you!

**Comment by Fokko** [comment]
I'm going to close this one, as it is solved from my side. Thanks everyone, much appreciated!
