### ISSUE TITLE
Support pattern constraint for List[str] as in V1

### ISSUE THREAD

**Issue by ringohoffman** [pydantic/pydantic#6409]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

It seems like the scope in which `pattern` can be applied in `V2` is dimished over its predecessor parameter to `pydantic.Field`, `regex`. IMO it makes sense that `pattern` is applicable as a constraint over both `str` and containers of `str` types, as in `V1`.

### Example Code

In V1:

```python
import pydantic

from typing import List

class CLIArg(pydantic.BaseModel):
    flags: List[str] = pydantic.Field(min_items=1, regex=r"^-{1,2}[a-zA-Z_\-0-9]+$")

CLIArg(flags=["-a", "--b", "--c-d", "bad-arg"])

"""
1.10:
ValidationError: 1 validation error for CLIArg
flags -> 3
  string does not match regex "^-{1,2}[a-zA-Z_\-0-9]+$" (type=value_error.str.regex; pattern=^-{1,2}[a-zA-Z_\-0-9]+$)
"""
```

In V2:

```python
import pydantic

from typing import List

class CLIArg(pydantic.BaseModel):
    flags: List[str] = pydantic.Field(min_length=1, pattern=r"^-{1,2}[a-zA-Z_0-9]+$")


CLIArg(flags=["-a", "--b", "--c-d", "bad-arg"])
"""
2.0:
TypeError: The following constraints cannot be applied to typing.List[str]: 'pattern'
"""
```

### Python, Pydantic & OS Version

```console
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /Users/ringo/opt/anaconda3/envs/glass38/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, Mar  1 2023, 21:19:10)  [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by samuelcolvin** [comment]
We decided in v2 to remove "magical push down" (field constraints (gt, lt, max_len, min_len etc.) automatically being applied to parameters of generics).

Right or wrong, this was by design.

You should use `List[Annotated[str, MinLen(1)]]`. `MinLen` is available from annotated-types.

We need to make sure there's an easy way to apply `pattern` this way.
