### ISSUE TITLE
AttributeError in class attribute access for validate_call

### ISSUE THREAD

**Issue by jaraco** [pydantic/pydantic#6419]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

https://github.com/pydantic/pydantic/pull/6406 introduced an AttributeError when accessing a method on a class (not instance):

```
 draft @ pip-run 'git+https://github.com/pydantic/pydantic' -- pyd2.py
Traceback (most recent call last):
  File "/Users/jaraco/draft/pyd2.py", line 14, in <module>
    assert Thing.c == Thing.c
           ^^^^^^^
  File "/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-o94_k6_k/pydantic/_internal/_validate_call.py", line 101, in __get__
    setattr(obj, self._name, result)
AttributeError: 'NoneType' object has no attribute 'c'
```

### Example Code

```Python
from pydantic import validate_call


class Thing:
    def a(self):
        pass

    c = validate_call(a)


thing = Thing()
assert thing.a == thing.a
assert thing.c == thing.c, f'{thing.c} != {thing.c}'
assert Thing.c == Thing.c
```

### Python, Pydantic & OS Version

```Text
draft @ pip-run 'git+https://github.com/pydantic/pydantic' -- -c 'import pydantic.version; print(pydantic.version.version_info())'
             pydantic version: 2.0
        pydantic-core version: 2.0.2 release build profile
                 install path: /private/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/pip-run-hek15lsq/pydantic
               python version: 3.11.4 (main, Jun 15 2023, 07:55:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by jaraco** [comment]
Tagging @dmontagu , author of the implicated change.

**Comment by Kludex** [comment]
We are working on this. 👍

**Comment by dmontagu** [comment]
Damn, thanks @jaraco. @Kludex let's make sure we add a test for classmethod/staticmethod as well

**Comment by jaraco** [comment]
I've confirmed this patch and the earlier one address all the concerns downstream. Thanks!

**Comment by dmontagu** [comment]
@jaraco there's still a huge performance overhead with the current implementation caused by the fact that it is rebuilding the validator every time the attribute is accessed on a new instance. In particular, this means for simple classes, `__init__` is about 50x slower on a normal class with `@validate_call` than it is on a `pydantic.BaseModel`. I'm going to try to resolve this, but hopefully the fact that you are no longer getting errors helps. 

Thanks for reporting this and please let us know if you run into any more issues!
