### ISSUE TITLE
Custom types using `Ge` raise an exception referring to undefined `P`.

### ISSUE THREAD

**Issue by Moisan** [pydantic/pydantic#6421]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When creating a custom type using `Annotated` and `annotated_types.Ge`, pydantic raises the following exception (for example):

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model1
x
  Input should be greater than or equal to P [type=greater_than_equal, input_value=datetime.timedelta(days=-1, seconds=85920), input_type=timedelta]
```
However, `P` is never defined. I believe the comparison value from the type should be shown instead of `P`.

### Example Code

```Python
from pydantic import BaseModel
from annotated_types import Ge
from typing import Annotated
from datetime import timedelta

PositiveTimedelta = Annotated[timedelta, Ge(timedelta(0))]

class Model1(BaseModel):
    x: PositiveTimedelta

Model1(x=timedelta(minutes=-8))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /private/tmp/testing_pydantic/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, Nov 18 2021, 11:15:02)  [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-13.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```
```


Selected Assignee: @davidhewitt

**Comment by Kludex** [comment]
It looks like a bug.

Ref.:

https://github.com/pydantic/pydantic-core/blob/d08d269b0999f07088a688e94e64f5e4ba856add/src/errors/types.rs#L397

https://github.com/pydantic/pydantic-core/blob/d08d269b0999f07088a688e94e64f5e4ba856add/src/errors/types.rs#L723-L729

**Comment by dmontagu** [comment]
I'll just note that it looks like it's trying to convert the object to a string and failing in some way, but I would argue that the error message should probably not include the ISO-serialized duration as the label, as I think most people aren't familiar reading those. Ideally it would just display the repr of the python-timedelta that could be created by converting the duration. Open to disagreement on this though.

**Comment by adriangb** [comment]
Fixed in https://github.com/pydantic/pydantic-core/pull/747
