### ISSUE TITLE
Build pydantic class based on python dataclass having default_factory fails

### ISSUE THREAD

**Issue by bitchikosanasai** [pydantic/pydantic#6430]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Have the below util function to build a pydantic data model based on the python dataclass.

```
from pydantic import create_model
from pydantic.dataclasses import dataclass as pydantic_dataclass
from typing import TypeVar
from dagster import Config
from dataclasses import is_dataclass, dataclass, field

T = TypeVar("T")


def dataclass_to_pyd(dc: T) -> T:
    def process_fields(fields):
        processed_fields = {}
        for k, v in fields.items():
            if is_dataclass(v.type_):
                processed_fields[k] = (
                    dataclass_to_pyd(v.type_), v.field_info)
            else:
                processed_fields[k] = (v.type_, v.field_info)
        return processed_fields

    pydc = pydantic_dataclass(dc)
    return create_model(  # type: ignore
        dc.__name__,
        **process_fields(pydc.__pydantic_model__.__fields__),
        __base__=Config,
    )

```

Have the below python dataclass 

```
@dataclass
class Sub2:
    b: int = 3


@dataclass
class Sub:
    b: int = 3
    lst: list[Sub2] = field(default_factory=lambda: [Sub2()])


@dataclass
class Root:
    a: int = 4
    s: Sub = Sub()
```

Trying to convert

```
TPyd = dataclass_to_pyd(Root)
```

Getting the error

```
Exception has occurred: TypeError
non-default argument 'lst' follows default argument
```

on the following line

`pydc = pydantic_dataclass(dc)`

where `dc` is the `Sub`.

Weird behaviour part is that, if i change to

```
@dataclass
class Sub:
    lst: list[Sub2] = field(default_factory=lambda: [Sub2()])
    b: int = 3
```

Then it works fine

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.9
            pydantic compiled: True
                 install path: /Users/B/Projects/sanas/student_model_training/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.16-x86_64-i386-64bit
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @lig

**Comment by lig** [comment]
@bitchikosanasai thank you for the bug report. Could you please confirm that the bug is still relevant in Pydantic v2?
