### ISSUE TITLE
Discriminated union used in a model that's used in another model fails validation

### ISSUE THREAD

**Issue by robert3005** [pydantic/pydantic#6435]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Model that contains a model that contains a discriminated union will fail initialization with 
```
    raise TypeError('`discriminator` can only be used with `Union` type with more than one variant')
```
Looks like the model initialization logic creates the Initial model which correctly converts discriminated union to tagged-union. Then when Derived model is initialized discriminator is applied again to the tagged-union which fails `== 'union'` check. From my naive understanding we should be able to skip applying discriminators if the schema is a `tagged-union`

I'm attaching a minimal repro

### Example Code

```Python
from typing import Annotated, Union, Literal, Optional

from pydantic import BaseModel, Field


class B(BaseModel):
    func: Literal["b"] = "b"


class A(BaseModel):
    func: Literal["a"] = "a"


ABC = Annotated[
    Union[A, B],
    Field(discriminator="func"),
]


class Initial(BaseModel):
    abc: Optional[ABC] = None


class Derived(BaseModel):
    initial: Initial


def main():
    Derived(initial=Initial(abc=A()))


if __name__ == "__main__":
    main()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
pydantic-core version: 2.0.1 release build profile
python version: 3.9.16 (main, May 19 2023, 13:47:57)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by dmontagu** [comment]
@robert3005 This is fixed on main, and I believe should be fixed in the `pydantic==2.0.1` release that just happened earlier today. Please let us know if you still have this issue.
