### ISSUE TITLE
Which ValidationError type for invalid enum?

### ISSUE THREAD

**Issue by gamaleonardo** [pydantic/pydantic#6439]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi,

I think you forgot to specify the "enum" ValidationError type in the documentation page:

https://docs.pydantic.dev/latest/usage/validation_errors

If it's the case I can contribute adding it to the page.

Best regards
Leonardo

### Example Code

```Python
class MyEnum(Enum):
     first = 1
     second = 2

class ExampleClass(BaseModel):
     number: MyEnum
     name: str = "Default"

try:
     my_example = MyClass(number = 3)
except ValidationError as e:
     print(repr(e.errors()[0]['type']))

'enum'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.1
        pydantic-core version: 2.0.2 release build profile
                 install path: /home/leonardo/.local/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, Dec  7 2022, 01:12:08)  [GCC 11.3.0]
                     platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @gamaleonardo for reporting this 🙏 

Would you like to open a PR for this?

**Comment by gamaleonardo** [comment]
Of course! I will do it. Thanks!

**Comment by gamaleonardo** [comment]
Hi @hramezani,

Getting the following error when trying to push:

```
remote: Permission to pydantic/pydantic.git denied to gamaleonardo.
fatal: unable to access 'https://github.com/pydantic/pydantic.git/': The requested URL returned error: 403
```

Any idea?
Thanks

**Comment by Kludex** [comment]
You can't push to pydantic, you need to push to your own fork.

**Comment by gamaleonardo** [comment]
Sorry, I forgot to fork the project. My bad!

**Comment by Kludex** [comment]
This is done. 👍
