### ISSUE TITLE
An option not to display URLs as part of str(ex)

### ISSUE THREAD

**Issue by simonw** [pydantic/pydantic#6441]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I'm using Pydantic 2 for validation inside a CLI tool powered by Click. My code looks like this:

```python
try:
    validated_options = dict(
        (key, value)
        for key, value in model.Options(**dict(options))
        if value is not None
    )
except pydantic.ValidationError as ex:
    raise click.ClickException(str(ex))
```

The resulting error message includes a URL to a page in the Pydantic documentation explaining the error.

That link doesn't make sense in the context of my tool. I couldn't find a way to disable the display of those URLs, is there a mechanism for that?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
Hey @simonw does the `include_url` kwarg achieve what you need (eg  https://github.com/pydantic/pydantic/blob/958f82a169594d0816bb0e449871ca0af04a3faa/tests/test_datetime.py#L223 ) . Otherwise I’ll be happy to look for a solution after the holiday (tomorrow).

**Comment by simonw** [comment]
Yes that looks like it! Thanks very much - I'll close this issue once I get a chance to try it out (not on my laptop right now).

**Comment by simonw** [comment]
OK, I tried that out:
```
(Pdb) ex.errors()
[{'type': 'extra_forbidden', 'loc': ('foo',), 'msg': 'Extra inputs are not permitted', 'input': 'bar', 'url': 'https://errors.pydantic.dev/2.0.1/v/extra_forbidden'}]
(Pdb) ex.errors(include_url=False)
[{'type': 'extra_forbidden', 'loc': ('foo',), 'msg': 'Extra inputs are not permitted', 'input': 'bar'}]
```
It looks like I have the raw materials I need to produce my own string version of the error message.

I think my feature request then is to have a mechanism that compiles a string version of the errors that's like the `str(ex)` implementation but that gives me a little bit more control over the format - like being able to use `include_url=False`.

**Comment by simonw** [comment]
Actually looking at this code:

https://github.com/pydantic/pydantic/blob/958f82a169594d0816bb0e449871ca0af04a3faa/pydantic/errors.py#L61-L77

Maybe I just want to use `.message` directly.

**Comment by adriangb** [comment]
Please feel free to offer any doc suggestions or API changes you feel would make this more discoverable!

**Comment by ornariece** [comment]
@adriangb can we re-open this? `ValidationError` doesn't inherit from `PydanticErrorMixin`, so i fail to see how this suggestion is a solution (fittingly, it seems @simonw went for a workaround in their usecase).
exposing the `__str__` method of `ValidationError` so that the user can use its logic with `.errors()` might be a solution. there could even be a `include_url` parameter to the exposed function, which i think would make sense.
