### ISSUE TITLE
Ints are not coerced into strings

### ISSUE THREAD

**Issue by mrenner-ML** [pydantic/pydantic#6446]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

In pydantic v1, when passing an int to a BaseModel attribute defined as str, the int is automatically coerced into str.
However, I am not getting the same behavior with pydantic v2 where not coercion happens and a validation error is thrown.

In the "Standard Library Types" documentation, it however says: "Strings are accepted as-is. **int, float, and Decimal are coerced using str(v).** bytes and bytearray are converted using v.decode()."

Is this a new behavior in pydantic v2 not yet reflected in the documentation? Or a bug?  

### Example Code

```Python
from pydantic import BaseModel

class A(BaseModel):
    a: int
    b: str
    
A(a="1", b=2)

>>> ValidationError: 1 validation error for A
>>> b
>>>   Input should be a valid string [type=string_type, input_value=2, input_type=int]
>>>   For further information visit https://errors.pydantic.dev/2.0.1/v/string_type
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.1
pydantic-core version: 2.0.2 release build profile
install path: C:\ProgramData\Anaconda3\envs\temp-pydantic\Lib\site-packages\pydantic
python version: 3.11.3 | packaged by Anaconda, Inc. | (main, May 15 2023, 15:41:31) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
It's a new behavior.

Please check https://github.com/pydantic/pydantic/issues/6045, and the [Conversion Table](https://docs.pydantic.dev/latest/usage/conversion_table/).
