### ISSUE TITLE
Schema output differs when `,` is present in model config title field

### ISSUE THREAD

**Issue by vigneshmanick** [pydantic/pydantic#6447]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When the model config has a `,` after the `title` field the schema output has the result inside an array. If the comma is not present then the output is a string. 

See output below.  Notice how `Bla1 Model` is inside a list and `Bla Model` is not.

```python
Python Version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
Pydantic Version: 1.10.9
{"title": "Bla Model", "type": "object", "properties": {"type": {"title": "Type", "type": "string"}}, "required": ["type"], "additionalProperties": false}
{"title": ["Bla1 Model"], "type": "object", "properties": {"type": {"title": "Type", "type": "string"}}, "required": ["type"], "additionalProperties": false}
```

Example code to reproduce is below.

### Example Code

```Python
from pydantic import BaseModel, Extra

class Model(BaseModel):
    class Config:
        anystr_strip_whitespace = True
        extra = Extra.forbid

class Bla(Model):
    type: str
    class Config:
        title = "Bla Model"

print(Bla.schema_json())

class Bla1(Model):
    type: str
    class Config:
        title = "Bla1 Model",

print(Bla1.schema_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.9
pydantic compiled: True
install path: /scratch/myprograms/miniconda3/envs/myenv/lib/python3.11/site-packages/pydantic
python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17 optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @davidhewitt

**Comment by Kludex** [comment]
The first is a string, the second a tuple. The output is expected.
```python
>>> a = "a",
>>> type(a)
<class 'tuple'>
>>> b = "b"
>>> type(b)
<class 'str'>
```
