### ISSUE TITLE
Unable to modify dictionary-like private attributes

### ISSUE THREAD

**Issue by TylerGrantSmith** [pydantic/pydantic#6458]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

In v2 I cannot update a dictionary private attribute in `__init_subclass__` , instead I receive a TypeError: `TypeError: 'ModelPrivateAttr' object does not support item assignment`.

This was a regression in behavior from v1 where the code worked.

### Example Code

```Python
from pydantic import BaseModel

class Model(BaseModel):
    _registry: dict[str,str] = {}

    def __init_subclass__(cls):
        cls._registry[cls.__name__] = cls

class SubModel(Model):
    pass

```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.1
        pydantic-core version: 2.0.2 release build profile
                 install path: <redacted>
               python version: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
It looks like you want a `ClassVar`, rather than a `PrivateAttr`:

```python
from typing import ClassVar

from pydantic import BaseModel

class Model(BaseModel):
    _registry: ClassVar[dict[str,str]] = {}

    def __init_subclass__(cls):
        cls._registry[cls.__name__] = cls

class SubModel(Model):
    pass
```

Annotations whose names start with a leading `_` are automatically converted to `ModelPrivateAttr`s, but that can be prevented by annotating as a ClassVar, and I think that's what you want here.

I'm going to close this issue but please let us know if the above change doesn't fix your problem.
