### ISSUE TITLE
Coercion of arbitrary types leads to error

### ISSUE THREAD

**Issue by michaelveloz1963** [pydantic/pydantic#6462]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

In pre 2.0 pydantic you could have a field whose type is arbitrary, such as a custom class, and pydantic would allow you to pass in a value to instantiate that field, without having to pass in an instance of the actual type. 

This does not appear to be allowed in 2.0.    Perhaps I'm missing something obvious in the docs?

This is sometimes problematic if you are trying to instantiate a model from a dictionary whose values just contain the values needed by the arbitrary types, and don't actually contain instances of the arbitrary types.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict

class MyId(int):
  ...

class Model(BaseModel):
  id: MyId
  model_config = ConfigDict(arbitrary_types_allowed=True)

# the following works in 1.x but not 2.0:

Model(id=3)

# in 2.0, it produces the error "Input should be an instance of MyId
# IE, this works:

Model(id=MyId(3))
```

### Python, Pydantic & OS Version

```Text
/opt/miniconda3/envs/foundry-dev-2/lib/python3.10/site-packages/pydantic/_migration.py:273: UserWarning: `pydantic.utils:version_info` has been moved to `pydantic.version:version_info`.
  warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
             pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /opt/miniconda3/envs/foundry-dev-2/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ]
                     platform: macOS-12.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by dmontagu** [comment]
This change is on purpose, and as you might imagine can provide useful/important validation in many cases.

However, V2 is easier to customize than V1, and I believe you can use the `PlainValidator` annotation as a way to get the same behavior as v1:

```python
from typing import Annotated

from pydantic import BaseModel, ConfigDict, PlainValidator


class MyId(int):
    ...


class Model(BaseModel):
    id: Annotated[MyId, PlainValidator(lambda v: v)]


my_id = Model(id=MyId(3)).id
print(my_id, type(my_id))
#> 3 <class '__main__.MyId'>

my_id = Model(id=3).id
print(my_id, type(my_id))
#> 3 <class 'int'>
```
(Note that you don't even need `arbitrary_types_allowed=True` in the model config with this change.)

However, I'll also note that you could make your custom type play nice with pydantic v2 as well:
```python
from typing import Any

from pydantic_core import core_schema

from pydantic import BaseModel, GetCoreSchemaHandler


class MyId(int):
    @classmethod
    def __get_pydantic_core_schema__(cls, source: Any, handler: GetCoreSchemaHandler) -> core_schema.CoreSchema:
        return core_schema.no_info_after_validator_function(MyId, handler.generate_schema(int))


class Model(BaseModel):
    id: MyId


my_id = Model(id=MyId(3)).id
print(my_id, type(my_id))
#> 3 <class '__main__.MyId'>

my_id = Model(id=3).id
print(my_id, type(my_id))
#> 3 <class '__main__.MyId'>
```

**Comment by dmontagu** [comment]
I'm going to close this issue as completed based on the above suggestion, but if you would prefer different behavior feel free to open a feature request with a description of what you'd like to exist or be changed.
