### ISSUE TITLE
Optional fields raise validation errors: Field required [type=missing...]

### ISSUE THREAD

**Issue by ybressler** [pydantic/pydantic#6463]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Optional fields are being ignored when I build a model. This is true for fields annotated with `Field()` function, and those that are not.

These errors are being raised when instantiating a model as a class `Model(...)` as well as  parsing from a dict: `Model.model_validate(...)`

**A workaround:** Set the default value of the field to be `None`. This is a breaking change of behavior from V1 and doesn't seem correct. (Unless it is, then it's not covered in the documentation.) 

I've provided a reproducible example below.

### Example Code

```Python
# main.py
from typing import Optional
from pydantic import BaseModel, Field


class MyModel(BaseModel):
    a: Optional[int]
    b: Optional[int] = Field(description="Optional int annotated with a field")
    c: Optional[str]
    d: Optional[str] = Field(description="Optional str annotated with a field")


# --------------------------

# test_main.py

from typing import Optional
import pytest

from main import MyModel


@pytest.mark.parametrize(
    ('a', 'b', 'c', 'd'),
    [
        (1, 2, 'one', 'two'),
        (1, None, 'one', None),
        (None, 2, None, 'two'),
        (None, None, None, None)
    ]
)
def test_model_with_values(
        a: Optional[int],
        b: Optional[int],
        c: Optional[str],
        d: Optional[str]
):
    """Model succeeds with explicit None for optional fields"""
    my_model = MyModel(a=a, b=b, c=c, d=d)


@pytest.mark.xfail
def test_model_with_some_values():
    """This raises an error, and it shouldn't"""
    my_model = MyModel(a=1)



@pytest.mark.parametrize(
    "data",
    [
        # These work if I explicitly set the values to None
        ({"a": 1, "b": 2, "c": "one", "d": "three"}),
        ({"a": 1, "b": None, "c": "one", "d": None}),
        ({"a": 1, "b": 2, "c": "one", "d": "three"}),
        ({"a": None, "b": 2, "c": None, "d": "three"}),
        ({"a": None, "b": None, "c": None, "d": None}),
        # But they fail if I am missing values - no default is set
        pytest.param({"a": 1, "c": "one"}, marks=pytest.mark.xfail),
        pytest.param({"b": 2, "d": "two"}, marks=pytest.mark.xfail),
        pytest.param({}, marks=pytest.mark.xfail)
    ]
)
def test_model_from_dicts(data):
    """Model fails when optional fields are missing"""
    my_model = MyModel.model_validate(data)

```
Here's an error I got:
```
test_main.py::test_model_with_some_values XFAIL                          [100%]
@pytest.mark.xfail
    def test_model_with_some_values():
        # This raises an error, and it shouldn't
>       my_model = MyModel(a=1)
E       pydantic_core._pydantic_core.ValidationError: 3 validation errors for MyModel
E       b
E         Field required [type=missing, input_value={'a': 1}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.0.1/v/missing
E       c
E         Field required [type=missing, input_value={'a': 1}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.0.1/v/missing
E       d
E         Field required [type=missing, input_value={'a': 1}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.0.1/v/missing

test_main.py:27: ValidationError
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /Users/yaakov/Documents/Code/pydantic-v2-messing-around/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 21:05:46) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by Kludex** [comment]
Yes, the behavior changed from V1 to V2.

It's documented on the [Required, Optional and Nullable fields](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields) section in the migration guide. 🙏

**Comment by ybressler** [comment]
LOL, I re-read [the documentation](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields:~:text=f2%3A%20Optional%5Bstr%5D%20%20%23%20required%2C%20can%20be%20None%20%2D%20same%20as%20str%20%7C%20None), and it looks like this is a `feature` not a bug:
<img width="680" alt="Screenshot 2023-07-05 at 5 09 18 PM" src="https://github.com/pydantic/pydantic/assets/40807730/7fe728b3-5648-4ff5-8871-dd38dd642b6b"> 

Given that this is a breaking change from V1, I think it should be made more explicit in the documentation. I'd be happy to add the info.

However, I'm a bit sad that `Optional[...]` doesn't really mean a field is optional... (I wish there was a way to configure this from `model_config` -> something like `optional_fields_auto_none`)

**Comment by ybressler** [comment]
Should I create a ticket to enhance this documentation? (Specifically to this point.)

**Comment by Kludex** [comment]
`Optional[T]` is an alias to `Union[T, None]` in Python, and on version 3.10+ you are able to use the `|` (pipe) operator instead of `Optional`, which makes it more visible that it's actually not "optional", but that "accepts None".

If you want to make the field _optional_ again, you should add the default value as `None`.

Suggestions on how to improve the documentation are welcome.
