### ISSUE TITLE
model_dump issuing UserWarning

### ISSUE THREAD

**Issue by fraenkel** [pydantic/pydantic#6467]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When I call m.model.dump(), I am getting the following error:
```
E       UserWarning: Pydantic serializer warnings:
E         Expected `Union[Id, Id2]` but got `Id2` - serialized value may not be as expected
```

I have found that tweaking the types can make the error disappear.
Also using the first type in the Union does not cause an issue.

### Example Code

```Python
import unittest
from typing import Literal, Union

from pydantic import BaseModel


class Id(BaseModel):
    id: str


class Id2(BaseModel):
    id: Literal[True]


class Top(BaseModel):
    x: Union[Id, Id2]


class TestFoo(unittest.TestCase):
    def test1(self):
        Top(x=Id(id="a")).model_dump()
        Top(x=Id2(id=True)).model_dump()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/xxx/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @hramezani

**Comment by eseglem** [comment]
I am seeing what I think may be the same issue, but could just be very similar. 

```python
from typing import Annotated, Literal, Generic, TypeVar
from pydantic import BaseModel, Field

class Base(BaseModel):
    type: str
    whatever: None = None

class Foo(Base):
    type: Literal["Foo"]

class Bar(Base):
    type: Literal["Bar"]

Stuff = Annotated[Foo | Bar, Field(discriminator="type")]

class Baz(BaseModel):
    stuff: Stuff

b = Baz(stuff={"type": "Foo"})
b.model_dump(exclude_unset=True)
```

Resulting in: 
```
pydantic/main.py:292: UserWarning: Pydantic serializer warnings:
  Expected `Union[Foo, Bar]` but got `Foo` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
{'stuff': {'type': 'Foo'}}
```

Note: it does not throw the error when `exclude_unset=False` which is extra strange, and may mean it is not the same issue. Figured it was worth adding here first though.

**Comment by adriangb** [comment]
Seems like this is related to https://github.com/pydantic/pydantic/issues/6422, https://github.com/pydantic/pydantic-core/pull/727 and probably various other bugs w/ serialization where we are either too strict or too lax on checking that the data to be serialized is what we expect.

**Comment by Kludex** [comment]
This doesn't reproduce anymore. We probably fixed in the last months. 🙏
