### ISSUE TITLE
__new__ in nested model init isn't called with arguments

### ISSUE THREAD

**Issue by CharlesPerrotMinotHCHB** [pydantic/pydantic#6474]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi!

I may have missed it (either in the migration doc, or close issue, or question), but I didn't find an answer to this behavior change with Pydantic V2. With Pydantic V1, we were able to overwrite the `__new__` method. I used it as a way to make the return of this function null in certain conditions, like when all fields need to not be null but we don't want the whole construct to fail, just return null. So I was checking all fields, instantiating if none were null, otherwise returning None (see code example).

This doesn't work any more with nested models. In that case, `__new__` seems to be called with neither args no kwargs, thus making the whole test there failing all the time. There's likely a better way to do this, more than happy to change my approach!

If I print the args / kwargs for that nested model (in the `__new__` method), I get the following output:
```
  __new__ args ()
  __new__ kwargs {}
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    Payload(**data)
  File "/opt/homebrew/lib/python3.9/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
AttributeError: 'NoneType' object has no attribute '__dict__'
```

### Example Code

```Python
from typing import Any, Optional
from pydantic import BaseModel

class Position(BaseModel):
  latitude: float
  longitude: float

  def __new__(cls, *args, **kwargs: dict[str, Any]) -> Optional["Position"]:
    print("__new__ args", args)
    print("__new__ kwargs", kwargs)
    if all(
      (
          kwargs.get("latitude"),
          kwargs.get("longitude"),
      )
    ):
      return object.__new__(cls)
    return None

class Payload(BaseModel):
  position: Optional[Position] = None

data = {
  "position": {
    "latitude": 40.2,
    "longitude": 50.2,
  },
}
result = Payload(**data)
```

### Python, Pydantic & OS Version

```Text
python3.9 -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /opt/homebrew/lib/python3.9/site-packages/pydantic
               python version: 3.9.17 (main, Jun 20 2023, 18:00:22)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by samuelcolvin** [comment]
This is not a bug, it's a change of behavior in v2.

The `__new__` method is called in rust to construct the class object as performantly as possible.

The solution is to use a `model_validator` and optionally return `None`. Let us know if you need a code example.

**Comment by CharlesPerrotMinotHCHB** [comment]
Thank you @samuelcolvin!
I thought about that, but the model_validator fails. Or at least my implementation of it :)

``` Python
from typing import Optional

from pydantic import BaseModel, model_validator


class Position(BaseModel):
    latitude: float
    longitude: float

    @model_validator(mode="before")
    @classmethod
    def validate_all_values(cls, values) -> Optional["Position"]:
        if all(
            (
                values.get("latitude"),
                values.get("longitude"),
            )
        ):
            return values
        return None


class Payload(BaseModel):
    position: Optional[Position] = None


data = {
    "position": {
        "latitude": 40.2,
        "longitude": None,
    },
}
Payload(**data)
```

I get:
```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    Payload(**data)
  File "/opt/homebrew/lib/python3.9/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Payload
position
  Input should be a valid dictionary or instance of Position [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.1.2/v/model_type
```

**Comment by samuelcolvin** [comment]
Try `mode='wrap'`?

**Comment by CharlesPerrotMinotHCHB** [comment]
Yep, it works!
```
@model_validator(mode="wrap")
@classmethod
def validate_all_values(cls, values, _handler, _info) -> Optional[dict[str, Any]]:
    if all(
        (
            values.get("latitude"),
            values.get("longitude"),
        )
    ):
        return values
    return None
```

Interesting that it requires the wrap mode, but thank you!

**Comment by samuelcolvin** [comment]
You should call `return handler(values)` to run validation and construct the model.

`mode='after'` would work too, but would mean validation was always run, even when you're throwing away the model.

**Comment by samuelcolvin** [comment]
You can also remove the `info` argument.

**Comment by CharlesPerrotMinotHCHB** [comment]
returning the model_construct also works, but thanks!
`Position.model_construct(**values)`

**Comment by CharlesPerrotMinotHCHB** [comment]
Howdy,
Sorry to reopen, but I believe this behavior has changed.
I simplified the validator to
```
    @model_validator(mode="wrap")
    @classmethod
    def validate_all_values(
        cls,
        kwargs: dict[str, Any],
        handler,
    ) -> Optional["Position"]:
        if all(kwargs.values()):
            return handler(kwargs)
        return None
```

But when I try to assert a Position object where one of the attributes is None, I get the following
```
assert result is None
E       AssertionError: assert <[AttributeError('__pydantic_extra__') raised in repr()] Position object at 0x1050ddd60> is Non
```
