### ISSUE TITLE
Optional Fields are treated as required

### ISSUE THREAD

**Issue by jwalls89** [pydantic/pydantic#6475]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Optional fields are treated are marked as "required" in v2.  Example code attached worked in v1.10.11.

### Example Code

```Python
from pydantic import BaseModel
from typing import Optional

class Foo(BaseModel):
    bar: Optional[str]

    
class TestPydantic:

    def test_foo(self):
        Foo() # passes with v1.10.11 but fails with v2.0.2
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/jwalls/.cache/pypoetry/virtualenvs/test-pyd-FJ7ITngQ-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by Kludex** [comment]
This is the expected behavior on V2. See [Required, optional, and nullable fields](https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields) for more details.

**Comment by pcotton-intech** [comment]
Thank you!
