### ISSUE TITLE
Undocumented behaviour change. When no field alias set, V1: FieldInfo.alias is field name, V2: None  

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6495]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Unsure whether intentional or side effect, but broke our code so maybe worth adding to migration guide. 

In V1, `__fields__[field_name].alias` would be the `field_name` when no alias is set, in V2 it's `None`. 

Edit: just found another usage of this assumption in a common fastapi snippet which I'm thinking is now incorrect with this change: https://github.com/tiangolo/fastapi/issues/2387. 

It would be useful to have a param on the `FieldInfo` that outputs a valid input field name, i.e. to cover having to migrate all usages of `.alias` to `.alias if .alias is not None else field_name`

### Example Code

```Python
from pydantic import BaseModel, Field

class BarNoAlias(BaseModel):
    bar: int = Field()

class BarWithAlias(BaseModel):
    bar: int = Field(alias="foo")

# V1:
print(BarNoAlias.__fields__["bar"].alias) # <--- "bar"
print(BarWithAlias.__fields__["bar"].alias) # <--- "foo"

# V2:
print(BarNoAlias.model_fields["bar"].alias) # <--- None
print(BarWithAlias.model_fields["bar"].alias) # <--- "foo"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @zakstucke for reporting this 🙏 

> Unsure whether intentional or side effect, but broke our code so maybe worth adding to migration guide.

I've created a PR to mention this change in the migration doc

> It would be useful to have a param on the FieldInfo that outputs a valid input field name, i.e. to cover having to migrate all usages of .alias to .alias if .alias is not None else field_name

Field info does not contain `field_name`. So, we can add field_name to the field info and then add a property to return alias or field name

**Comment by sydney-runkle** [comment]
@zakstucke,

Going to close this for now. Doesn't seem like there's much demand for a `field_name` property, and you can easily extract that information by `or` ing the `alias` and the name of the field itself.

Closing for now as not planned. We'd be happy to consider a PR if someone really wants this property implemented :).
