### ISSUE TITLE
TypeError when call create_model with __cls_kwargs__ (__init_subclass__() takes no keyword arguments)

### ISSUE THREAD

**Issue by m9810223** [pydantic/pydantic#6499]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Can not use `__cls_kwargs__` in `create_model`.

### Example Code

```Python
from pydantic import create_model

cls_kwargs = {'a': 'b'}
FooModel = create_model('FooModel', __cls_kwargs__=cls_kwargs)

# Traceback (most recent call last):
#   File "${PYDANTIC}/_.py", line 4, in <module>
#     FooModel = create_model('FooModel', __cls_kwargs__=cls_kwargs)
#                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "${PYDANTIC}/pydantic/main.py", line 1326, in create_model
#     return meta(__model_name, resolved_bases, namespace, __pydantic_reset_parent_namespace__=False, **kwds)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "${PYDANTIC}/pydantic/_internal/_model_construction.py", line 124, in __new__
#     cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
#                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "<frozen abc>", line 106, in __new__
# TypeError: FooModel.__init_subclass__() takes no keyword arguments
```

### Python, Pydantic & OS Version

```Text
pdm run python -c "import pydantic.version; print(pydantic.version.version_info())"
```

```text
             pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: ${PYDANTIC}/pydantic
               python version: 3.11.3 (main, Jun  2 2023, 01:36:07) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by m9810223** [comment]
- https://github.com/m9810223/pydantic/pull/1

**Comment by m9810223** [comment]
- Removing `**kwds` fixes it: https://github.com/m9810223/pydantic/pull/1

**Comment by m9810223** [comment]
Hi @runzhi214 

After tracking the source code, I fond that I misunderstand the [document of `__cls_kwargs__`](https://docs.pydantic.dev/latest/api/main/#pydantic.main.create_model). 
> A dictionary of keyword arguments for class creation.

If I want to set the class var thru `create_model`, just set `ClassVar` to field type [as same as the `BaseModel` inheritance](https://docs.pydantic.dev/latest/usage/models/#class-vars).

```py
from typing import ClassVar

from pydantic import create_model

cls_kwargs = {'a': (ClassVar[str], 'b')}
FooModel = create_model('FooModel', **cls_kwargs)
print(FooModel.__class_vars__)  # -> {'a'}
print(FooModel.a)  # -> b
```

---

Hi @Kludex. Maybe we should update the description in more detail or add an example in the documentation?

**Comment by dmontagu** [comment]
Just to be clear, `__cls_kwargs__ == {'a': 'b'}` means the same thing as:
```python
from pydantic import BaseModel

class FooModel(BaseModel, a='b'):
    pass
```
which raises the same error, as expected.

I'll defer to @Kludex about whether it makes sense to update docs or anything like that.

**Comment by Kludex** [comment]
Yeah, we can improve the `create_model` API reference (docstring).

PR welcome.

**Comment by sydney-runkle** [comment]
I don't think a major docs update is needed here, but I added a bit more clarification to the docstring as well as a link to the usage docs 👍.
