### ISSUE TITLE
Missing CSS for some routes

### ISSUE THREAD

**Issue by AleksaC** [pydantic/pydantic#6501]
Not sure if this repo is in use already as it's completely empty. Either way my issue doesn't fit the issue templates in the main repo and the name and description suggest that this is the place to open the issue.

https://docs.pydantic.dev/latest/usage/types/ returns v1 docs page without css.

The solution would probably be to return a redirect to https://docs.pydantic.dev/latest/usage/types/types/.

This is the page that pops up as a first result on google for a common query, so I guess a lot of users are experiencing this.

Selected Assignee: @davidhewitt

**Comment by hramezani** [comment]
I've transferred your issue to `pydantic` repo.
