### ISSUE TITLE
Invalid BaseSettings Error Doc Link

### ISSUE THREAD

**Issue by Ahmed-Abdou14** [pydantic/pydantic#6521]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I just migrated to Pydantic v2 and got the following error for using `pydantic.BaseSettings`:
```bash
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.
```

This page no longer exists https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings

### Example Code

```Python
from pydantic import BaseSettings

class Settings(BaseSettings):
   ...
```

### Python, Pydantic & OS Version

```Text
python 3.11
Pydantic v2
Ubuntu 22
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
@Ahmed-Abdou14 Thanks for the report. We are looking into it.

**Comment by samuelcolvin** [comment]
This is a mistake in URL generation, link should be

    https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings

E.g. the patch version should not be included in the URL.

**Comment by samuelcolvin** [comment]
We should fix the URL generation, and also try to set up a redirect so links in existing releases work.

**Comment by Ahmed-Abdou14** [comment]
Perfect, thank you @Kludex  & @samuelcolvin
Meanwhile, some of the error messages containing URLs still reference  https://docs.pydantic.dev/dev-v2 instead of https://docs.pydantic.dev/2.0
Maybe fix that too for the next release

**Comment by plannigan** [comment]
It also looks like there version number used in the URL is based on the [pydantic-core version](https://github.com/pydantic/pydantic-core/blob/0b317115a3bfeeeef333877ffb7d7854b7cdf733/src/errors/validation_exception.rs#L114) instead of the `pydantic` version.

```
>>> import pydantic, pydantic_core
>>> pydantic.__version__
'2.0.2'
>>> pydantic_core.__version__
'2.1.2'
>>> class Foo(pydantic.BaseModel):
...   bar: int
... 
>>> Foo(bar="one")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.8/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
bar
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='one', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/int_parsing
```

Seeing `2.1.2` confused me at first because I knew there wasn't a 2.1 release yet. Since `pydantic-core` is described as an implementation detail, it feels like the `pydantic` (user facing) version number should be used.

**Comment by Kludex** [comment]
> It also looks like there version number used in the URL is based on the [pydantic-core version](https://github.com/pydantic/pydantic-core/blob/0b317115a3bfeeeef333877ffb7d7854b7cdf733/src/errors/validation_exception.rs#L114) instead of the `pydantic` version.
> 
> ```
> >>> import pydantic, pydantic_core
> >>> pydantic.__version__
> '2.0.2'
> >>> pydantic_core.__version__
> '2.1.2'
> >>> class Foo(pydantic.BaseModel):
> ...   bar: int
> ... 
> >>> Foo(bar="one")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".venv/lib/python3.8/site-packages/pydantic/main.py", line 150, in __init__
>     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
> pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
> bar
>   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='one', input_type=str]
>     For further information visit https://errors.pydantic.dev/2.1.2/v/int_parsing
> ```
> 
> Seeing `2.1.2` confused me at first because I knew there wasn't a 2.1 release yet. Since `pydantic-core` is described as an implementation detail, it feels like the `pydantic` (user facing) version number should be used.

Right. Thanks. We are on it.
