### ISSUE TITLE
Replace `IPvAnyAddress` and related types with `Union[IPv4Address, IPv6Address]`

### ISSUE THREAD

**Issue by adriangb** [pydantic/pydantic#6522]
A solid 100LOC that looks buggy and like it could be 3 lines of code:

https://github.com/pydantic/pydantic/blob/12fde9c8b270cc5e73b0cf8bce1fb2aff718fd70/pydantic/networks.py#L266-L376

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
Main downside I see is if someone is creating instances of `IPvAnyAddress`, e.g., via something like `my_ip = IPvAnyAddress('127.0.0.1')`, this would break that code.

**Comment by bedlamzd** [comment]
Hi! I assume you are aware of this, but still want to point out that current implementation doesn't work well with type checkers and auto completion.

Consider this example

```python
import pydantic


class Test(pydantic.BaseModel):
    ip: pydantic.IPvAnyAddress


t = Test(ip=pydantic.IPvAnyAddress("127.0.0.1"))
# t.ip: ipaddress.IPv4Address
print(t.ip.version)
print(t.ip.is_private)
```

Running type cheker on that will result in

<details><summary>Mypy</summary>
<p>

```sh
tmp/pydantic_ip_any.py:12: error: "IPvAnyAddress" has no attribute "version"  [attr-defined]
tmp/pydantic_ip_any.py:13: error: "IPvAnyAddress" has no attribute "is_private"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

</p>
</details> 

<details><summary>pyright</summary>
<p>

```sh
tmp/pydantic_ip_any.py
  tmp/pydantic_ip_any.py:10:13 - error: Argument of type "IPv4Address | IPv6Address" cannot be assigned to parameter "ip" of type "IPvAnyAddress" in function "__init__"
    Type "IPv4Address | IPv6Address" cannot be assigned to type "IPvAnyAddress"
      "IPv4Address" is incompatible with "IPvAnyAddress" (reportArgumentType)
  tmp/pydantic_ip_any.py:12:12 - error: Cannot access member "version" for type "IPvAnyAddress"
    Member "version" is unknown (reportAttributeAccessIssue)
  tmp/pydantic_ip_any.py:13:12 - error: Cannot access member "is_private" for type "IPvAnyAddress"
    Member "is_private" is unknown (reportAttributeAccessIssue)
3 errors, 0 warnings, 0 informations 
```

</p>
</details> 

And obviously no hints and lots of complaints from IDE.

Not sure what the ideal way to solve it would be, but maybe it's worth at least adding stubs that mirror `Ipaddress._IPAddressBase`?

**Comment by sydney-runkle** [comment]
Marking as resolved, I've updated things with a type hint for now via https://github.com/pydantic/pydantic/pull/9640.

I think we will probably refactor URLs and might also change up network types in the near term, so things might be changed then as well.
