### ISSUE TITLE
Unable to serialize unknown type: IPv4Address for `model_dump_json`

### ISSUE THREAD

**Issue by Ahmed-Abdou14** [pydantic/pydantic#6529]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

`pydantic.IpvAnyAddress` is unserializable
Both pieces of code below produce similar errors regarding unserializable types

### Example Code

```Python
class IP(BaseModel):
    ip: IPvAnyAddress
def get_ip():
    ip = IP(ip=IPvAnyAddress("127.0.0.1"))
    return ip.model_dump_json()
```

```python
class IP(BaseModel):
    ip: IPvAnyAddress
def get_ip():
    ip = IP(ip=IPvAnyAddress("127.0.0.1"))
    return json.dumps(ip.model_dump()).encode()
```

```bash
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: IPv4Address('127.0.0.1')
```

### Python, Pydantic & OS Version

```Text
pydantic v2
python 3.11
Ubuntu 22
```

Selected Assignee: @dmontagu

**Comment by Ahmed-Abdou14** [comment]
When i used `fastapi.jsonable_encoder()` after using `model_dump` it works.
```python
json.dumps(jsonable_encoder(value.model_dump())).encode()
```

**Comment by dmontagu** [comment]
I'll note that you can get string encoding of the relevant types by doing:

```python
import json

from pydantic import BaseModel, IPvAnyAddress


class IP(BaseModel):
    ip: IPvAnyAddress


def get_ip():
    ip = IP(ip=IPvAnyAddress("127.0.0.1"))
    return json.dumps(ip.model_dump(), default=str).encode()


print(get_ip())
#> b'{"ip": "127.0.0.1"}'
```

I think @adriangb and/or @Kludex might have been looking into these types, and I saw https://github.com/pydantic/pydantic/issues/6522 about replacing it with a union, so maybe it's not necessary, but I did create a #6572 to fix the immediate issue with the schemas being generated.

**Comment by Ahmed-Abdou14** [comment]
Great, thank you @dmontagu

I also came up with a temporary solution until a fix is released

```python
class IP(BaseModel):
    ip: IPvAnyAddress

    @field_serializer("ip")
    def ip_to_str(self, v: IPvAnyAddress) -> str:
        return str(v)
```

**Comment by Kludex** [comment]
> I'll note that you can get string encoding of the relevant types by doing:
> 
> ```python
> import json
> 
> from pydantic import BaseModel, IPvAnyAddress
> 
> 
> class IP(BaseModel):
>     ip: IPvAnyAddress
> 
> 
> def get_ip():
>     ip = IP(ip=IPvAnyAddress("127.0.0.1"))
>     return json.dumps(ip.model_dump(), default=str).encode()
> 
> 
> print(get_ip())
> #> b'{"ip": "127.0.0.1"}'
> ```
> 
> I think @adriangb and/or @Kludex might have been looking into these types, and I saw #6522 about replacing it with a union, so maybe it's not necessary, but I did create PR #6572 to fix the immediate issue with the schemas being generated.

I'm fine with #6572 for now. @adriangb wdyt?
