### ISSUE TITLE
Parsing datetime string to datetime object failed

### ISSUE THREAD

**Issue by Tomerfi1210** [pydantic/pydantic#6537]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Hi,
When I create a class with field as datetime, and I try to parse it I get an error.

My tests are failing.

Thanks

### Example Code

```Python
class A(BaseModel):
     dt: datetime
  
 A(dt="2023-05-23T12:49:06.1926169+00:00")

 Input should be a valid datetime, second fraction value is more than 6 digits long [type=datetime_parsing, input_value='2023-05-23T12:49:21.2172687+00:00', input_type=str]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
pydantic-core version: 2.1.2 release build profile
```

Selected Assignee: @adriangb

**Comment by samuelcolvin** [comment]
The reason is explained right there in the error message.

As far as I know this marches iso8602 and rfc3339.

**Comment by samuelcolvin** [comment]
Duplicate of #6411
