### ISSUE TITLE
field_validator does not run when mode="before" if the field is not set

### ISSUE THREAD

**Issue by ashpreetbedi** [pydantic/pydantic#6539]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Thank you for building the most useful library in the world. 

I'm trying to use the `@field_validator` to set a default value dynamically (which I previously set using @validator(pre=True, always=True) but the field_validator does not run if the field is not set in the model.

In the example below, the `@field_validator` runs when `field_to_update_if_not_set` is set, but does not run when the field is not provided. I want to run the `@field_validator` always.

Thank you again!

### Example Code

```Python
from pathlib import Path
from typing import Optional, List, Any, Dict

from pydantic import BaseModel, field_validator, model_validator


class TestFieldValidatorRunOnBefore(BaseModel):
    name: Optional[str] = None
    field_to_update_if_not_set: Optional[str] = None
    field2_to_update_if_not_set: Optional[str] = None

    @field_validator("field_to_update_if_not_set", mode="before")
    def update_using_field_validtor(cls, v):
        print("update_using_field_validator")
        return "update_using_field_validator"

    @model_validator(mode='before')
    def update_using_model_validtor(cls, data):
        print("update_using_model_validator")
        data["field2_to_update_if_not_set"] = "update_using_model_validator"
        return data

print("--------------------")
test_model_without_field_set = TestFieldValidatorRunOnBefore()
print(test_model_without_field_set)
print("--------------------")
test_model_with_field_set = TestFieldValidatorRunOnBefore(field_to_update_if_not_set="test")
print(test_model_with_field_set)
print("--------------------")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: ..../venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, May  8 2022, 17:57:49)  [Clang 13.1.6 (clang-1316.0.21.2)]
                     platform: macOS-12.2.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by samuelcolvin** [comment]
Thanks. 

I think you need [`validate_default`](https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.Field).

Let me know how you get on.

**Comment by ashpreetbedi** [comment]
Thanks @samuelcolvin, using `Field(..., validate_default=True)` worked.

**Comment by samuelcolvin** [comment]
Amazing!

If you think you could improve the docs, PR welcome!

**Comment by ashpreetbedi** [comment]
Awesome, will put one up soon :)

**Comment by illpack** [comment]
Hi @ashpreetbedi I encountered the same problem - whilst the docs get updated, could you share a working example of your solution using `Field`? Thanks!

**Comment by ashpreetbedi** [comment]
@illpack this works for me:

```
class MyModel(BaseModel):
    my_field: Optional[bool] = Field(None, validate_default=True)
    ...
    ...

    @field_validator("my_field", mode="before")
    def update_my_field(cls, v, info: FieldValidationInfo):
        ...
        return updated_my_field
```

did you set mode="before" ?

**Comment by illpack** [comment]
Oh yes, that works fo course! 
Thanks @ashpreetbedi
