### ISSUE TITLE
use_enum_values doesn't seem to do anything at all

### ISSUE THREAD

**Issue by tlambert03** [pydantic/pydantic#6540]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

On b685d64c38f1d7abb3ed37bd30710b3e420dc86a (and on v2.0.2), setting `model_config = {'use_enum_values': True}` doesn't seem to do anything

The docs suggest:

> Whether to populate models with the value property of enums, rather than the raw enum. This may be useful if you want to serialize `model.model_dump()` later. Defaults to `False`.

However, in the  example code below, the output is the same either way:

```python
{'enum': <MyEnum.A: 1>}
{'enum': <MyEnum.A: 1>}
Traceback (most recent call last):
  File "/Users/talley/dev/forks/pydantic/x.py", line 23, in <module>
    assert Foo().model_dump() != Bar().model_dump()
AssertionError
```

am I misunderstanding?

### Example Code

```Python
from enum import Enum

from pydantic import BaseModel


class MyEnum(Enum):
    A = 1
    B = 2


class Foo(BaseModel):
    enum: MyEnum = MyEnum.A
    model_config = {'use_enum_values': True}


class Bar(BaseModel):
    enum: MyEnum = MyEnum.A
    model_config = {'use_enum_values': False}


print(Foo().model_dump())
print(Bar().model_dump())
assert Foo().model_dump() != Bar().model_dump()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/talley/dev/forks/pydantic/pydantic
               python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ]
                     platform: macOS-12.6.7-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @tlambert03 for the issue 🙏 

As you set the default value for `enum` field in the model definition and initialize the models without values, the validation does not happen. So, by adding the `validate_default` config you can see the difference.

```py
from enum import Enum

from pydantic import BaseModel, ConfigDict


class MyEnum(Enum):
    A = 1
    B = 2


class Foo(BaseModel):
    enum: MyEnum = MyEnum.A
    model_config = ConfigDict(use_enum_values=True, validate_default=True)


foo = Foo()
print(foo.enum, type(foo.enum)). # 1 <class 'int'>
print(foo.model_dump())  # {'enum': 1}


class Bar(BaseModel):
    enum: MyEnum = MyEnum.A
    model_config = ConfigDict(use_enum_values=False, validate_default=True)


bar= Bar()
print(bar.enum, type(bar.enum))  # MyEnum.A <enum 'MyEnum'>
print(bar.model_dump())  # {'enum': <MyEnum.A: 1>}
```

**Comment by tlambert03** [comment]
oh wow, I guess I did have a misunderstanding of what that actually did.  (even in v1)
somehow i had the impression that this was largely a `.dict` `.model_dump` thing... not changing the actual type of the value.  I'll show you what I used to do in v1 to achieve this to give you a better sense for what I was going for, and why I had this impression:

```python
from enum import Enum

from pydantic import BaseModel


class MyEnum(Enum):
    A = 1
    B = 2


class Foo(BaseModel):
    enum: MyEnum

foo = Foo(enum=MyEnum.A)
print(foo.enum, type(foo.enum), foo.dict())

Foo.Config.use_enum_values = True
print(foo.enum, type(foo.enum), foo.dict())

Foo.Config.use_enum_values = False
print(foo.enum, type(foo.enum), foo.dict())
```

prints
```
MyEnum.A <enum 'MyEnum'> {'enum': <MyEnum.A: 1>}
MyEnum.A <enum 'MyEnum'> {'enum': 1}
MyEnum.A <enum 'MyEnum'> {'enum': <MyEnum.A: 1>}
```

That ability to modify the dumped data without modifying the type on the object itself was really what I was after.  Do you know if that's possible anymore?

-------------

I know this is a new issue now, but `use_enum_values` totally breaks typing, no?

For example, if I did the following somewhere

```
foo.enum + 5
```

it would be just fine for pydantic, but mypy would not be happy:

```
x.py:17: error: Unsupported operand types for + ("MyEnum" and "int")
```

Similarly, if I am a consumer of a pydantic object and I would like to know what fields and types I should expect, I would look at `Foo.model_fields['enum']`, which would erroneously lead me to believe that `Foo.enum` would be of type `MyEnum`, not int.  There's nothing in the FieldInfo to say that the type is being mangled somewhere externally.

Do you know if there's been an issue around that?  That seems like a bigger concern

**Comment by hramezani** [comment]
I think this was the case in `pydantic V1` as well:

```py
from enum import Enum

from pydantic import BaseModel


class MyEnum(Enum):
    A = 1
    B = 2


class Foo(BaseModel):
    enum: MyEnum = MyEnum.A

    class Config:
        validate_all = True  # Renamed to `validate_default` in V2
        use_enum_values = True

foo = Foo()
print(foo.enum, type(foo.enum))  # 1 <class 'int'>
print(foo.dict())  # {'enum': 1}
```

You can change the field serialization behavior like:

```py
from enum import Enum

from pydantic import BaseModel, field_serializer


class MyEnum(Enum):
    A = 1
    B = 2

class Foo(BaseModel):
    enum: MyEnum = MyEnum.A

    @field_serializer('enum')
    def get_eunm_value(self, v, info) -> str:
        return str(v.value)


foo = Foo()
print(foo.model_dump())  # {'enum': '1'}
```

**Comment by tlambert03** [comment]
yep, I recognize it was the case in v1.  Thanks for the tip on the `field_serializer` for v2.

do you have any thoughts on the typing issue?  I can create a new issue for that if need be.

**Comment by hramezani** [comment]
I think the fix for mypy plugin is complicated.

So, I would recommend using `StrEnum` or `IntEnum`.

I close this issue for now.
