### ISSUE TITLE
`str` field `max_length` constraint panics on Unicode characters

### ISSUE THREAD

**Issue by KatantDev** [pydantic/pydantic#6542]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The new implementation with rust has broken the unicode handling, this is how the rust behaves when using max_length:

```python
pydantic_core._pydantic_core.ValidationErrorthread '<unnamed>' panicked at 'byte index 28 is not a char boundary; it is inside 'а' (bytes 27..29) of `'ааааааааааааааааааааааааа'`', src/errors/validation_exception.rs:384:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
: <exception str() failed>
```

### Example Code

```Python
from pydantic import BaseModel, Field


class Example(BaseModel):
    field1: str | None = Field(default=None, max_length=32)


Example(field1='а'*25) # Russian letter
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
pydantic-core version: 2.1.2 release build profile
python version: 3.10.7 (v3.10.7:6cc6b13308, Sep  5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)]
platform: macOS-13.2.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by KatantDev** [comment]
I think you can split it to:
1. max_length (O(1) - `string.len()`)
2. max_char_length (O(n) - `string.chars().count()`)

**Comment by lig** [comment]
I wasn't able to reproduce the crash in Pydantic either. Nevertheless, I'm fixing the unicode length handling.
