### ISSUE TITLE
Add `compute_on_init: bool` param to computed fields to run on init and output ValidationError(s)

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6545]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Sometimes it's easier to write a computed field with it's validation in-place, rather than pre-validating it. 

If the `@computed_field` could be written such as `@computed_field(compute_on_init=True)`, the strange looking `@model_validator` in the below example could be avoided.

```Python
from functools import cached_property
from pydantic import BaseModel, computed_field, model_validator


# Current workaround:
class Foo(BaseModel):
    baz: str

    @computed_field  # type: ignore[misc]
    @cached_property
    def bar(self) -> str:
        if self.baz == "invalid":
            raise ValueError("invalid!")

        return "bar"

    @model_validator(mode="after")  # type: ignore[arg-type]
    def compute_bar_on_init(self):
        self.bar
        return self


Foo(baz="invalid").bar

# Correct pydantic validation error:
"""
Traceback (most recent call last):
  File "mypy_playground.py", line 37, in <module>
    Foo(baz="invalid").bar
    ^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
  Value error, invalid! [type=value_error, input_value={'baz': 'invalid'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/value_error
"""

# Without the model_validator section, the error would occur after validation, and no longer stay in the pydantic context:
"""
Traceback (most recent call last):
  File "mypy_playground.py", line 18, in <module>
    Foo(baz="invalid").bar
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "mypy_playground.py", line 13, in bar
    raise ValueError("invalid!")
ValueError: invalid!
"""
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @samuelcolvin

**Comment by caniko** [comment]
I requested this when `computed_field` were being implemented, even set up a list of other ideas #4650; tbf, most of the points are implemented :)

**Comment by Gabgobie** [comment]
Was looking for exactly this functionality but I guess until there is any progress on this I'll yoink OPs code for precomputing. Thanks ;D

**Comment by Viicos** [comment]
I don't think we want to support such a pattern, considering the scope of `computed_field` is only to support serialization and the generated JSON Schema. Here are a couple ideas to implement workarounds:

- Using a `model_post_init`:

```python
from typing import Any, TypeVar

from pydantic_core import PydanticCustomError

from pydantic import BaseModel, computed_field

ModelT = TypeVar('ModelT', bound=BaseModel)


class BaseModelValidatesComputedField(BaseModel):
    def model_post_init(self, context: Any) -> None:
        for computed_field in self.model_computed_fields.keys():
            try:
                getattr(self, computed_field)
            except Exception:
                raise PydanticCustomError(
                    'invalid_computed_field',
                    "The computed field '{computed_field}' failed to validate",
                    {'computed_field': computed_field},
                )


class Test(BaseModelValidatesComputedField):
    a: int

    @computed_field
    @property
    def raises(self) -> int:
        raise ValueError('Error')
```

- With a model validator:

```python
from typing import TypeVar

from pydantic import BaseModel, computed_field, model_validator

ModelT = TypeVar('ModelT', bound=BaseModel)


def _validate_computed_fields(self: ModelT) -> ModelT:
    for computed_field in self.model_computed_fields.keys():
        getattr(self, computed_field)

    return self

class Test(BaseModel):
    a: int

    @computed_field
    @property
    def raises(self) -> int:
        raise ValueError('Error')

    _validate_computed_fields = model_validator(mode='after')(_validate_computed_fields)
```

- As a class decorator (implementation really not ideal):

```python
from typing import TypeVar

from pydantic import BaseModel, computed_field, model_validator
from pydantic._internal._decorators import DecoratorInfos

ModelT = TypeVar('ModelT', bound=BaseModel)


def _validate_computed_fields(self: ModelT) -> ModelT:
    for computed_field in self.model_computed_fields.keys():
        getattr(self, computed_field)

    return self


def validate_computed_fields(cls: type[ModelT]) -> type[ModelT]:
    cls._validate_computed_fields = model_validator(mode='after')(_validate_computed_fields)  # type: ignore
    cls.__pydantic_decorators__ = DecoratorInfos.build(cls)
    cls.model_rebuild(force=True)
    return cls


@validate_computed_fields
class Test(BaseModel):
    a: int

    @computed_field
    @property
    def raises(self) -> int:
        raise ValueError('Error')
```

**Comment by caniko** [comment]
@Viicos, Pydantic is used for so much more than just JSON serialization. To postulate that the only purpose of `computed_field` is to make serializing JSON less of a headache is just wrong.

The purpose of `computed_field` is to make `property` and `cached_property` compatible with `BaseModel`. These bells and whistles therefore make sense. Please reconsider.

**Comment by Viicos** [comment]
> Pydantic is used for so much more than just JSON serialization. To postulate that the only purpose of `computed_field` is to make serializing JSON less of a headache is just wrong.

It is wrong according to you. The [documentation states](https://docs.pydantic.dev/latest/concepts/fields/#the-computed_field-decorator) it is meant to be included during serialization (and thus by extension supported in the model JSON Schema).

I have to say I don't really find OP's example really convincing: he is doing validation for field `baz` in the `bar` property. Why not do:

```python
from typing import Annotated

from pydantic import BaseModel, AfterValidator, computed_field

def validate_bar(value: str) -> str:
    if value == "invalid":
        raise ValueError("invalid!")
    return value

class Model(BaseModel):
    baz: Annotated[str, AfterValidator(validate_bar)]

    @computed_field
    @property
    def bar(self) -> str:
        return "bar"
```

It is also pretty uncommon to raise exceptions in properties, especially `ValueError`'s (read: related to data sanity). Some frameworks make use of such a pattern ([DRF for instance](https://github.com/encode/django-rest-framework/blob/f593f5752c45e06147231bbfd74c02384791e074/rest_framework/serializers.py#L264)), but in a way where you know the property can safely be called after a set of previous operations (e.g. calling `is_valid()` for DRF). And even then, some people complain about the confusing API design.

---

I'd be happy to reopen the issue to get more visibility and gather feedback as a feature request for comments and upvotes if a convincing example can be provided.
Adding a new argument to `Field`/`computed_field` and such should be an informed decision, so we'll have to get more requests for it to be reconsidered.

**Comment by caniko** [comment]
@Viicos, I appreciate your input, but I think there's a bit of a misunderstanding here. My point wasn't solely about JSON serialization; rather, it was about making `property` and `cached_property` fully compatible with `BaseModel` through `computed_field`. By focusing only on serialization, you're committing a straw man fallacy—misrepresenting my argument to make it easier to refute. This overlooks the broader use case and functionality that `computed_field` offers.

To clarify, here's a quick example to illustrate the broader use:

```python
from typing import Annotated
from pydantic import BaseModel, AfterValidator, computed_field

def validate_name(value: str) -> str:
    if value == "invalid":
        raise ValueError("Name can't be 'invalid'!")
    return value

class UserModel(BaseModel):
    first_name: Annotated[str, AfterValidator(validate_name)]
    last_name: Annotated[str, AfterValidator(validate_name)]
    birth_year: int

    @computed_field
    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    @computed_field
    @property
    def age(self) -> int:
        return 2024 - self.birth_year  # Assume the current year is 2024

# Example usage
user = UserModel(first_name="John", last_name="Doe", birth_year=1990)
print(user.full_name)  # Outputs: John Doe
print(user.age)        # Outputs: 34
```

In this case, `computed_field` isn't just about serialization. It enables us to define derived properties like `full_name` and `age` that encapsulate logic and provide a clean API within the model itself. This is especially useful in real-world scenarios where models represent complex entities, and derived properties are essential.

I think this highlights the value of computed_field beyond just handling JSON. I'd love to keep the discussion open and see if others in the community share similar use cases.

**Comment by Viicos** [comment]
But then with the provided example, what would be the reason to have `full_name` and `age` validated/accessed on init? You are not performing any validation logic inside them.

**Comment by caniko** [comment]
The use of `computed_field` for properties like `full_name` and `age` in a Pydantic model goes beyond mere validation during initialization; it's about creating a clean, intuitive API. These computed properties encapsulate logic within the model, ensuring consistency, enhancing readability, and reducing redundancy. By providing derived values, they make the model more expressive and easier to work with, particularly for complex entities. While `computed_field` properties do not handle validation, their true value lies in offering a centralized, maintainable way to expose essential derived information.

The perspective that overlooks this approach is missing the point. The focus isn't on addressing issues related to serialization, validation, or JSON handling. Instead, the goal is to leverage the strengths of Pydantic's `BaseModel` for its clean and expressive API, and to replace it with standard `dataclass` where appropriate. This shift isn’t about improving validation or serialization but about adopting a more Pythonic approach to modeling complex entities, using `computed_field` to keep the logic well-encapsulated within the model itself.

**Comment by Viicos** [comment]
> The use of `computed_field` for properties like `full_name` and `age` in a Pydantic model goes beyond mere validation during initialization; it's about creating a clean, intuitive API.

I agree on that part. The main function of `computed_field` is to have properties-like serialized, but we can extend to provide a clean integration of them to Pydantic (one example is support for deprecated fields, where this was also added to computed fields). However, adding such added functionality needs to make sense.

> These computed properties encapsulate logic within the model, ensuring consistency, enhancing readability, and reducing redundancy. By providing derived values, they make the model more expressive and easier to work with, particularly for complex entities. While `computed_field` properties do not handle validation, their true value lies in offering a centralized, maintainable way to expose essential derived information.

I agree as well on that part, but this has nothing to do with computed fields. Plain properties fulfill the same requirements.

> The perspective that overlooks this approach is missing the point. The focus isn't on addressing issues related to serialization, validation, or JSON handling. Instead, the goal is to leverage the strengths of Pydantic's `BaseModel` for its clean and expressive API, and to replace it with standard `dataclass` where appropriate. This shift isn’t about improving validation or serialization but about adopting a more Pythonic approach to modeling complex entities, using `computed_field` to keep the logic well-encapsulated within the model itself.

I'm sorry but I still don't really understand what you mean, or to be exact how does this relate to this issue.

> The focus isn't on addressing issues related to [...] validation

It is. OP requested a `compute_on_init` argument to avoid doing the following:

```python
class Foo(BaseModel):
    baz: str

    @computed_field  # type: ignore[misc]
    @cached_property
    def bar(self) -> str:
        if self.baz == "invalid":
            raise ValueError("invalid!")

        return "bar"

    @model_validator(mode="after")  # type: ignore[arg-type]
    def compute_bar_on_init(self):
        self.bar
        return self
```

While the correct way to do this (as per my [previous comment](https://github.com/pydantic/pydantic/issues/6545#issuecomment-2322915929)) is:

```python
def validate_bar(value: str) -> str:
    if value == "invalid":
        raise ValueError("invalid!")
    return value

class Model(BaseModel):
    baz: Annotated[str, AfterValidator(validate_bar)]

    @computed_field
    @cached_property
    def bar(self) -> str:
        return "bar"
```

Now as I said, if you are able to provide an example where `compute_on_init` would make sense, I'll be happy to reopen. Only then, we'll have to gather more user requests to actually add the `compute_on_init` argument unless an alternative implementation can be found (avoiding the extra argument).
