### ISSUE TITLE
Model Dump behaviour for computed field

### ISSUE THREAD

**Issue by Shawe82** [pydantic/pydantic#6549]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

When a Pydantic model that contains a `computed_field` is created and an instance of that model is dumped using `model_dump(exclude_none=True)`, the computed field is always included in the output dictionary, even when it is None.

To me, it is not clear if this is wanted behavior or something that needs to be fixed. I was confused by this behavior hence opening this issue here.

### Example Code

```Python
from pydantic import BaseModel, computed_field
class M(BaseModel):
    @computed_field(alias="$android_app_version")
    @property
    def i_am_returned(self) -> str | None:
        return None
    
M().model_dump(exclude_none=True)
# Return {'i_am_returned': None}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/simon.hawe/code/data-distribution-python/app/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.7 (main, Oct 24 2022, 08:43:44) [Clang 15.0.3 ]
                     platform: macOS-13.3.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
@samuelcolvin No, I've just created a [PR](https://github.com/pydantic/pydantic/pull/6648) to add a xfailing test

**Comment by hramezani** [comment]
Fixed in https://github.com/pydantic/pydantic/commit/e75ffbd978aff64a57581e5c52e00f520f04fa40
