### ISSUE TITLE
Possible bug in `max_length` for `str | list[str]`

### ISSUE THREAD

**Issue by zebengberg** [pydantic/pydantic#6553]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

Running the example code below, I get the following validation error:

```
Value should have at most 4 items after validation, not 4 [type=too_long, input_value='abcd', input_type=str]
    For further information visit https://errors.pydantic.dev/2.1.2/v/too_long
```

The problem goes away if I replace the annotation `str | list[str]` with `str`. The problem also goes away if I set `max_length=5`.

### Example Code

```Python
from pydantic import BaseModel, Field


class Foo(BaseModel):
    field: str | list[str] = Field(max_length=4)


Foo(field="abcd")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:17) [GCC 12.2.0]
                     platform: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by lig** [comment]
This is already fixed and doesn't reproduce in Pydantic v2.1.1 which is latest version to date.
