### ISSUE TITLE
Getting error: 'Post' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by Iqueal** [pydantic/pydantic#6554]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

I am using:
```
pydantic==2.0.2
pydantic-extra-types==2.0.0
pydantic-settings==2.0.1
pydantic_core==2.1.2
```

with fastapi.

I am just copying and pasting the model from pydantic docs on which I am using `.model_dump()` method. It is throwinf that attribute error mentioned above.

```py

```

### Example Code

```Python
from fastapi import FastAPI
from pydantic import BaseModel

# Pydantic Post model
class Post(BaseModel):
    title: str
    desc: str
    draft: bool = False
    rating: int | None = None


app = FastAPI()

@app.post('/create-post')
async def create_post(post: Post):
    print(post.model_dump())
    return post
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/jon/Documents/code/psnal/fastapi-tut/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
What's the FastAPI version you are using?

**Comment by Iqueal** [comment]
> What's the FastAPI version you are using?

fastapi==0.100.0

**Comment by Iqueal** [comment]
> Here is the error:

  File "/Users/jon/Documents/code/psnal/fastapi-tut/main.py", line 33, in create_post
    print(post.model_dump())
          ^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'model_dump'

**Comment by Kludex** [comment]
I'm not able to reproduce it here. Can you create a repository with a MRE?

**Comment by Iqueal** [comment]
> I'm not able to reproduce it here. Can you create a repository with a MRE?

I have already attached the sample code above.

```py
from fastapi import FastAPI
from pydantic import BaseModel

# Pydantic Post model
class Post(BaseModel):
    title: str
    desc: str
    draft: bool = False
    rating: int | None = None


app = FastAPI()

@app.post('/create-post')
async def create_post(post: Post):
    print(post.model_dump())
    return post
```

**Comment by Iqueal** [comment]
Here is the repl on replit:

I am getting the same error here as well.

https://replit.com/@QurashiAkeel/fast
Navigate [here](https://fast.qurashiakeel.repl.co/docs#/default/create_post_create_post_post) to see the response.
Run the repl to see the error in the termina.

**Comment by Kludex** [comment]
You are not using the version you think you are.

**Comment by Iqueal** [comment]
No, I am sure that I am using fastApi version 0.100.0, I have installed it just now, ad I used pip freeze to make sure that i am using the appropriate version.

**Comment by Iqueal** [comment]
> > What's the FastAPI version you are using?
> 
> fastapi==0.100.0

I just copied it☝️ from pip freeze

**Comment by Kludex** [comment]
> I am sure that I am using fastApi version 0.100.0

You are not.

> BTW what is MRE?

https://stackoverflow.com/help/minimal-reproducible-example

Please create a GitHub repository with a `requirements.txt` so I can reproduce your issue.

**Comment by Viicos** [comment]
According to your [`pyproject.toml`](https://replit.com/@QurashiAkeel/fast#pyproject.toml) you are on `0.89.1`

**Comment by Iqueal** [comment]
> According to your [`pyproject.toml`](https://replit.com/@QurashiAkeel/fast#pyproject.toml) you are on `0.89.1`

That replit was just to quickly send some code and I used a template where the latest version was not insalled so now I sent my actual repository: https://github.com/Iqueal/fastapi-learn

**Comment by Kludex** [comment]
> > According to your [`pyproject.toml`](https://replit.com/@QurashiAkeel/fast#pyproject.toml) you are on `0.89.1`
> 
> That replit was just to quickly send some code and I used a template where the latest version was not insalled so now I sent my actual repository: [Iqueal/fastapi-learn](https://github.com/Iqueal/fastapi-learn) where I am using all the approprate versions which I mentiond earlier.

It works fine.

**Comment by Iqueal** [comment]
Hey Kludex, I found broken link to Pydantic .env support:
This Link: [highlighted text in fastapi docs](https://fastapi.tiangolo.com/advanced/settings/?h=environm#pydantic-settings:~:text=Pydantic%20Settings%3A%20Dotenv%20)

Broken href = https://pydantic-docs.helpmanual.io/usage/settings/#dotenv-env-support
Working link = https://docs.pydantic.dev/latest/usage/pydantic_settings/#dotenv-env-support
