### ISSUE TITLE
model_dump_json() throws Rust borrow error with model that has an extra field of its own class

### ISSUE THREAD

**Issue by DeadWisdom** [pydantic/pydantic#6571]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2 installed directly from the `main` branch, or equivalent

### Description

The following exception is raised given the example code below:

```
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: RuntimeError: Already mutably borrowed"
````

This only seems to be a problem with extra fields pointing to the same model. I tried with a model with a field pointing back to itself and I believe that worked.

Halp, rust is angry.

### Example Code

```Python
class Model(BaseModel):
    model_config = ConfigDict(extra="allow")

obj = Model(other=Model())
obj.model_dump_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/deadwisdom/Library/Caches/pypoetry/virtualenvs/relay-d7pu99de-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Dec 24 2022, 17:53:21) [Clang 12.0.5 (clang-1205.0.22.11)]
                     platform: macOS-11.7.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by runzhi214** [comment]
Confirmed.

mac + py3.11 + 2.0.2
```bash
conda create -n py311 python=3.11
pip install pydantic
```
```python
from pydantic import BaseModel,ConfigDict
class Model(BaseModel):
    model_config = ConfigDict(extra="allow")

obj = Model(other=Model())
obj.model_dump_json()
```

**Comment by Kludex** [comment]
I guess the generated JSON need to look like `{"other": {}}` 🤔

**Comment by davidhewitt** [comment]
That is indeed what I get after eliminating the error in https://github.com/pydantic/pydantic-core/pull/764

**Comment by Kludex** [comment]
> That is indeed what I get after eliminating the error in [pydantic/pydantic-core#764](https://github.com/pydantic/pydantic-core/pull/764)

Great!

This will be available on the next Pydantic release (current is 2.0.2) - since we need to upgrade the pin on `pydantic-core`.

Thanks for the report @DeadWisdom! :)

**Comment by DeadWisdom** [comment]
Thank you all, I really appreciate it!
