### ISSUE TITLE
`TypeAdapter` mutates input data with `model_validator(mode="before")`

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6590]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In the example, previously we were using a util based on `parse_obj_as` to perform something like `TypeAdaptor`. 

With `TypeAdaptor`, the common case of adding fields to `data` in a `model_validator` now modifies the input data, this caused a specific bug for us where a model was accidentally injected into the input data, meaning it was no long json compatable when used later. 

It's probably a side-effect, and could be argued is a fine change, but I personally think this will cause strange bugs for others as well.

Note: I understand this example could simply be instanstiated with `Foo(**orig_data)`, but this came up in a generic usage that takes other non model based types as well.

**Edit: feel free to close this if you want this behaviour, it seems this top level is the only scenario where this changes, it might be something desired to standardize expectations**

### Example Code

```Python
from pydantic import BaseModel, TypeAdapter, model_validator

class Foo(BaseModel):
    result: str

    @model_validator(mode="before")
    @classmethod
    def parse_zones(cls, data):
        data["result"] = "FOO"
        return data    

orig_data = {}
ta = TypeAdapter(Foo)
ta.validate_python(orig_data)
print(orig_data)
# <-- {'result': 'FOO'} (accidentally modified!)

# COMPARED TO V1
from pydantic.v1 import BaseModel, parse_obj_as, root_validator

orig_data = {}

class Foo(BaseModel):
    result: str

    @root_validator(pre=True)
    @classmethod
    def parse_zones(cls, data):
        data["result"] = "FOO"
        return data    
    
parse_obj_as(Foo, orig_data)
print(orig_data)
# <-- {} (unmodified)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @zakstucke for this issue 🙏 

Yes, you are right. `parse_zones` is a Python function and it's Python behavior. But we don't want to make a deep copy of the input object because it has overhead. So, you as a user of Pydantic have to care about this. like other Python functions.

You can change your validator function like:
```py
    @model_validator(mode="before")
    @classmethod
    def parse_zones(cls, data):
        return {**data, "result": "FOO"}    

```
