### ISSUE TITLE
Timezone handling in V2 differs from V1 and does not always work with pandas

### ISSUE THREAD

**Issue by sxooler** [pydantic/pydantic#6592]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I've updated my code to V2 and found an unexpected behaviour when working with pydantic objects (timezone-aware timestamps/datetimes) and pandas. I have a list of pydantic objects and I have to convert it to pandas DataFrame. When you run minimal reproducible example, both should work in V1 and V2. But both use different `tzinfo` and the final DataFrame is not able to handle it (lose the original data type).

Is it expected change of behavior? Or is it issue on pandas side?

### Details of running the code
**V1 version**

Output of `m1` (note `tzinfo=datetime.timezone.utc`)
`MyModel(ts=datetime.datetime(2023, 7, 1, 10, 0, tzinfo=datetime.timezone.utc))`

Everything preserve type:
```
d1.dtypes
# ts    datetime64[ns, UTC]
# dtype: object

d1.ts.dt.tz
# datetime.timezone.utc

df_concat.dtypes
# ts    datetime64[ns, UTC]
# dtype: object

df_concat.ts.dt.tz
# datetime.timezone.utc
```

**V2 version**

Output of `m1` (note `tzinfo=TzInfo(UTC)`)
`MyModel(ts=datetime.datetime(2023, 7, 1, 10, 0, tzinfo=TzInfo(UTC)))`

`d1` pandas type is correct, although the tz is different compared to results in V1. Concatenation does not preserve datetime type:
```
d1.dtypes
# ts    datetime64[ns, UTC]
# dtype: object

d1.ts.dt.tz
# TzInfo(UTC)

df_concat.dtypes
# ts    object
# dtype: object
```

### Example Code

```Python
import pandas as pd
from datetime import datetime
from pydantic import BaseModel


class MyModel(BaseModel):
    ts: datetime


m1 = MyModel(ts="2023-07-01T10:00:00Z")
m2 = MyModel(ts="2023-07-02T10:00:00Z")

# note: dict is used here instead of newer model_dump so this example runs in V1 as well
d1 = pd.DataFrame([m1.dict()])
d2 = pd.DataFrame([m2.dict()])

df_concat = pd.concat([d1, d2])
```

### Python, Pydantic & OS Version

```Text
V1:
pydantic version: 1.10.9
python version: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']

V2:
pydantic version: 2.0.2
pydantic-core version: 2.1.2 release build profile
python version: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
This is not reproducible on the latest Pydantic version. We must have fixed it on https://github.com/pydantic/speedate at some point.
