### ISSUE TITLE
Add json_schema_extra to computed_field

### ISSUE THREAD

**Issue by Galarzaa90** [pydantic/pydantic#6596]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Adding `json_schema_extra` to `@computed_field` would help in making better documentatiom for Pydantic models.

While I get that some fields that you might use for a field do not apply for a computed field, but there could be others that can be useful:

- `deprecated`: When you rename a property and you add a computed_field as an alias to keep backwards compatibility. Marking it as deprecated can be useful to let consumers know it will be removed in the future.
- `example`: Show example values for a computed field to have an idea on how it is computed respective to other fields.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
It's already possible!

```python
from typing_extensions import Annotated

from pydantic import BaseModel, Field, computed_field


class Model(BaseModel):
    @computed_field
    def foo(self) -> Annotated[str, Field(json_schema_extra={'description': 'Foo is great!'})]:
        raise NotImplementedError


print(Model.model_json_schema(mode='serialization'))
"""
{
  "properties": {
    "foo": {
      "description": "Foo is great!",
      "readOnly": true,
      "title": "Foo",
      "type": "string"
    }
  },
  "required": [
    "foo"
  ],
  "title": "Model",
  "type": "object"
}
"""
```

**Comment by Galarzaa90** [comment]
Ok, that works so it is fair.

I thought that since it already has `title` and `description` fields that are used for the JSON schema, it would make sense to also have `json_schema_extra` like `Field` so this can be done in a cleaner way than using `Annotated`.
