### ISSUE TITLE
Instance of Pydantic dataclass with `field(default_factory=..., init=False)` is missing this attribute

### ISSUE THREAD

**Issue by sisp** [pydantic/pydantic#6600]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The instance of a Pydantic dataclass with an `init=False` field and a default _factory_ is missing this attribute. It only occurs in this particular combination and this problem does not exist with a vanilla dataclass.

### Example Code

```Python
from dataclasses import dataclass, field

from pydantic.dataclasses import dataclass as pydantic_dataclass


@pydantic_dataclass
class Bad:
    x: int = field(default_factory=lambda: 1, init=False)


@pydantic_dataclass
class Good1:
    x: int = field(default=1, init=False)


@dataclass
class Good2:
    x: int = field(default=1, init=False)


@dataclass
class Good3:
    x: int = field(default_factory=lambda: 1, init=False)


assert hasattr(Bad(), "x") is False  # <-- BAD!
assert hasattr(Good1(), "x")
assert hasattr(Good2(), "x")
assert hasattr(Good3(), "x")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: .../.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Sep  2 2022, 22:36:50)  [GCC 9.4.0]
                     platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @sisp for reporting this 🙏 

I think you can use `pydantic.Field` when you are using `pydantic.dataclasses`. So the bellow code works as expected:

```py
from pydantic.dataclasses import dataclass as pydantic_dataclass
from pydantic import Field

@pydantic_dataclass
class Bad:
    x: int = Field(default_factory=lambda: 1, init=False)


assert hasattr(Bad(), "x")
```

**Comment by sisp** [comment]
Thanks for getting back so quickly, @hramezani &ndash; and with a minor workaround. :tada:

Do you have an intuition (or do you know) where the discrepancy between vanilla `field()` and Pydantic's `Field()` is coming from? It should be fixed for sure, but I'm not deeply familiar with Pydantic's internals. If you can narrow it down, I might be able to give it a try.

**Comment by hramezani** [comment]
I think we need to implement it. I don't have a clue right now.

**Comment by sisp** [comment]
Thanks for fixing this bug so quickly! :pray:

**Comment by hramezani** [comment]
Thanks @sisp for reporting 🙏
