### ISSUE TITLE
TypeAdapter[T] inferrence fails with mypy (quick fix)

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6615]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`TypeAdapter(T)` fails to infer `TypeAdapter[T]` with mypy. 

Adding `__init__` replicating the existing `__new__` type checking block in the `TypeAdapter` class fixes the issue.

Mypy 1.4.1

Will create PR if no objections.

### Example Code

```Python
import typing as tp
from pydantic import TypeAdapter


# Before change:
ta = TypeAdapter(float)  # ERR: Need type annotation for "ta"  [var-annotated] (mypy)
tp.reveal_type(ta)
# Revealed type is "pydantic.type_adapter.TypeAdapter[Any]" (mypy)

# After change:
ta = TypeAdapter(float)  # Mypy happy
tp.reveal_type(ta)
# Revealed type is "pydantic.type_adapter.TypeAdapter[builtins.float]" (mypy)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @zakstucke for this 🙏 

I can confirm the problem and also the fix that you provided.

**Comment by adriangb** [comment]
What happens with your change if you do `TypeAdapter(int | str)`?

**Comment by zakstucke** [comment]
Sadly same as your comment in PR: `pydantic.type_adapter.TypeAdapter[types.UnionType]`. But I think that's mypy's problem rather than pydantic's.

**Comment by zakstucke** [comment]
@adriangb I've used this as a workaround for unions in the past with mypy, but it would require the user to enter such as `TypeAdapter(Returns[str | float])`, which is probably not something you'd want to support.

```Python
# https://github.com/python/mypy/issues/9003
class Returns(typing.Generic[T]):
    if not typing.TYPE_CHECKING:

        def __class_getitem__(cls, item: object) -> object:
            """Called when Returns is used as an Annotation at runtime.
            We just return the type we're given"""
            return item
```

**Comment by MarcBresson** [comment]
does this fix only work for python3.11 ?

**Comment by Viicos** [comment]
> does this fix only work for python3.11 ?

Do you have a repro of the issue you are seeing, along with the pydantic version and the type checker you are using?
