### ISSUE TITLE
Unexpected Type from Union is used when a Field in SubModel requires conversion. 

### ISSUE THREAD

**Issue by eseglem** [pydantic/pydantic#6637]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When the type of a field is a combination of Models (or dict) and any input data needs conversion such as `str -> int` an unexpected model is picked. 

I initially noticed this when I did something like this: `foo: MyModel | dict` and it always ended up a `dict` despite the data being fine when passed directly to `MyModel`. I had expected the only time foo would be a `dict` is when `MyModel` threw a `ValidationError` but that is not the case. The data validates correctly, yet still ends up a `dict`. 

I dug through the docs to try and understand but did not find anything that seemed relevant. I could potentially see an argument that `dict` is the better match in that case, since no conversion needed to happen, but since `MyModel` is before `dict` in the union, and it is a valid `MyModel`, this was unexpected. So to test it further, I added a second Model to the union and it ends up that second model, despite not having any field overlap with it. Which is is even more unexpected. 

In the below examples it seemed to have multiple unexpected behaviors from my standpoint. I would have thought the following:
- If it is ambiguous pick the first one in the Union. Which is the case in `Bar` and `dict` but it always ends up a dict in the case of `Foo` and `dict`. 
- When choosing between two models I would think the one with more field overlap should be chose as long as it doesn't have an error. `Foo` has one field `i` and `Bar` has one field `s`. So when passing in `{"i": "1"}` I would hope `Foo` would be used no matter the order. 
- And if that isn't the case then they are still ambiguous, and should choose the first one in the Union. However that isn't what happens. `Bar` is always chosen over `Foo`. 

What appears to be happening is that since `i` would need to be converted from a string to an int to fit `Foo` it is skipped over and the next type is chosen. 

And yes, ideally the models would be less ambiguous and not have issues like this. But can't always guarantee the input data is perfect and wanted some leeway in dealing with it. Especially for testing and debugging. 

### Example Code

```Python
from typing import Any
from contextlib import suppress
import pytest
from pydantic import BaseModel, field_validator, ValidationError

DATA = {"a": {"i": "1"}}

class Foo(BaseModel):
    i: int  # `i` is an int, but passing in `i="1"` validates fine.

def test_foo() -> None:
    # This validates fine, since pydantic will convert the string to an int.
    foo = Foo(**DATA["a"])
    assert foo.i == 1

class Bar(BaseModel):
    # Doesn't really matter what is here as long as it doesn't break when we pass
    # in only `i="1"`.
    s: str | None = None

def test_bar() -> None:
    # Nothing surprising here. The data does not throw a ValidationError, so it
    # validates fine. It will ignore the extra `i` and `s` defaults to None.
    bar = Bar(**DATA["a"])
    assert bar.s is None
    assert bar == Bar()

# Test various combinations of types here to figure out behavior.
TypeCombinations = (
    Foo,  # Passes, as we would expect
    Foo | dict,  # Fails, type(a) == dict
    # Doesn't matter which order, it picks `Bar` over `Foo`
    Foo | Bar,  # Fails, type(a) == Bar
    Bar | Foo,  # Fails, type(a) == Bar
    # But order matters between `dict` and `Bar`
    Foo | dict | Bar,  # Fails, type(a) == dict
    Foo | Bar | dict,  # Fails, type(a) == Bar
)

@pytest.mark.parametrize("type_", TypeCombinations)
def test_combinations(type_: Any) -> None:
    # Iterate over the combinations and see what happens.
    class TestModel(BaseModel):
        a: type_

    t = TestModel(**DATA)
    assert isinstance(t.a, Foo)

@pytest.mark.parametrize("type_", TypeCombinations)
def test_validator(type_: Any) -> None:
    # Can make them all pass with a validator, but it doesn't seem this should be necessary.
    class TestModel(BaseModel):
        a: type_

        @field_validator("a", mode="before")
        def validate_a(cls, value: Any) -> Foo | Any:
            if isinstance(value, dict):
                with suppress(ValidationError):
                    return Foo(**value)
            return value

    t = TestModel(**DATA)
    assert isinstance(t.a, Foo)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0
        pydantic-core version: 2.0.1 release build profile
                 install path: /home/erik/.pyenv/versions/3.10.10/envs/iceap/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 (main, Feb 13 2023, 15:54:50) [GCC 9.4.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by eseglem** [comment]
Perhaps this example is a little more realistic. If you have a Base model and a Subclass of it that has more fields, you may want them to be options for the same field. Or perhaps two different SubClasses. 

```python
class MyBase(BaseModel):
    a: int

class MySub(MyBase):
    b: int

class MyModel(BaseModel):
    foo: MySub | MyBase

BValues = (
    2,  # Passes, type(foo) == MySub
    "2",  # Fails, type(foo) == MyBase
)

@pytest.mark.parametrize("b", BValues)
def test_my_model(b: Any) -> None:
    m = MyModel(**{"foo": {"a": 1, "b": b}})
    assert isinstance(m.foo, MySub)
```

It is also worth noting that I went back and tested against 1.10.11 and this is a change in behavior. 

I didn't mention it in my first post, but I did also consider that the checking was short circuiting because the data was already a `dict` and I attempted a few variations, including using `model_validate_json()` with a stringified version of the data as well. The behavior was always the same. Which led me to using the additional Model as well.

**Comment by dmontagu** [comment]
It is expected that there is a change in behavior; it comes from the fact that we try to pick the right member of the union when there is a union. In particular, if you annotate a field as `Model1 | Model2`, and they each have the same fields, and you pass an instance of `Model2`, it will remain a `Model2`.

However, I think you've found some good examples of weird behavior that we may want to modify. Right now I believe the way it works is it tries doing a strict-mode validation first (actually a bit stricter than "regular" strict mode), and if that passes for any of the types in the union, that's the one that gets used, which I think explains the behavior with MySub and MyBase above. But I think clearly there's some unintuitive stuff going on here that maybe we can improve. At any rate, I think we also need to modify the strict union case checking for other reasons related to serializing union members.

It's not immediately clear to me what the ideal logic should be for picking a model when data isn't a perfect match on field values, but I'll add this to our high-priority milestone.

@samuelcolvin for context

**Comment by eseglem** [comment]
Thank you for the prompt response. 

The changes in behavior are mostly expected, well documented, and intuitive. I just wanted to double check it was a change in behavior to ensure I was reporting something that was a new issue with 2.0 since I didn't find anything mentioning the behavior in the migration guide. It not being in the guide indicated to me that it was more likely to be an unknown / unintentional change in behavior. 

I am sure it isn't as easy as this, but the logic in my head is something along the lines of: 
```python
data = {"a": 1, "b": "2"}
possible_models = [Model1, Model2, Model3]
priority_order = sorted(possible_models, key=lambda m: data.keys() - m.model_fields.keys())
```
Where the model which will consume the most input keys and still validate would be best. 

Or perhaps its:
```python
priority_order = sorted(possible_models, key=lambda m: set(data.keys()).symmetric_difference(set(m.model_fields.keys()))
```
Where the model that most closely matches the input keys has the priority. 

Or perhaps the extra strict validation could not pass if there are extra input fields which it is ignoring? Then it would just go in order and skip any of the field logic. I am guessing there could be performance implications from that though.

**Comment by Tishka17** [comment]
AFAIK, `Union` in python does not guarantee any order of items in it by standard. Two unions with same types in them must be treated as the same union (Union[A, B] == Union[B, A]) 
So there is no way for any library to determine order of classes to try when parsing, moreover I'd say you should suppose that library can parse them in any order.
