### ISSUE TITLE
Add `mode="json"` to model_validate()

### ISSUE THREAD

**Issue by methane** [pydantic/pydantic#6644]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When using custom JSON decoder or JSON-like serializaer (e.g. msgpack, cbor, etc.), I want to use json-mode in `model_validate()`.

```py
from pydantic import BaseModel
from enum import IntEnum

class Choice(IntEnum):
    a = 1
    b = 2

class Item(BaseModel, strict=True):
    id: int
    choice: Choice

item = Item(id=42, choice=Choice.b)
print(item.model_validate(item.model_dump()))  # works
print(item.model_validate_json(item.model_dump_json()))  # works

print(item.model_validate(item.model_dump(mode="json"))) # doesn't work
```

```
id=42 choice=<Choice.b: 2>
id=42 choice=<Choice.b: 2>
Traceback (most recent call last):
  File "/Users/inada-n/work/sandbox/fastapi/mre.py", line 16, in <module>
    print(item.model_validate(item.model_dump(mode="json")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/inada-n/work/sandbox/fastapi/.venv/lib/python3.11/site-packages/pydantic/main.py", line 480, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Item
choice
  Input should be an instance of Choice [type=is_instance_of, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1.2/v/is_instance_of
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @davidhewitt

**Comment by davidhewitt** [comment]
There has been some related discussion in https://github.com/pydantic/pydantic-core/pull/717#issuecomment-1614217388
and https://github.com/pydantic/pydantic-core/pull/718 where we have considered this but the decision seems to be against it for now.

@adriangb as you're more familiar with the discussions around this functionality I'm going to pass this one over to you.

**Comment by samuelcolvin** [comment]
The problem is that it's impossible to get the same behaviour validating python "like JSON" as actually validating JSON. And offering partial support would just confuse people.

If you really want to validate a python object like it's JSON, dump to JSON, then validate that - in most cases the performance impact will be tiny.

The long term solution is custom rust implementations of the `Input` trait.

**Comment by samuelcolvin** [comment]
You could just set `strict=False` on that field.

**Comment by methane** [comment]
OK. Sorry for creating duplicated issue.
