### ISSUE TITLE
Default `None` for uuid property raises `AttributeError` (name collision)

### ISSUE THREAD

**Issue by hofrob** [pydantic/pydantic#6646]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Declaring a pydantic model with a property named `uuid` and type `uuid.UUID | None` and a default value of `None` raises `AttributeError: 'NoneType' object has no attribute 'UUID'`.

This is probably true for other import/property name collisions as well.

Work arounds:

- rename the property
- remove the default value
- change the import to `from uuid import UUID`

### Example Code

```Python
import uuid

import pydantic


class Foo(pydantic.BaseModel):
    uuid: uuid.UUID | None = None
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /project/path/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul 11 2023, 22:38:37) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by Viicos** [comment]
This isn't related to Pydantic, it has to do with how Python finds references to the type hints you are using. `Foo` has its own class scope, and when you are using the type hing `uuid.UUID`, it tries to resolve `uuid` in this class scope, which is set to `None` with the default value.

Either use `from uuid import UUID` or `uuid: "uuid.UUID | None" = None`

**Comment by samuelcolvin** [comment]
> This isn't related to Pydantic, it has to do with how Python finds references to the type hints you are using. `Foo` has its own class scope, and when you are using the type hint `uuid.UUID`, it tries to resolve `uuid` in this class scope, which is set to `None` with the default value.
> 
> Either use `from uuid import UUID` or `uuid: "uuid.UUID | None" = None`

Exactly 👍 .
