### ISSUE TITLE
URL types do not behave like strings

### ISSUE THREAD

**Issue by jhaydaman** [pydantic/pydantic#6654]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In pydantic V1 HttpUrl behaved like a string and could be used where strings are expected. In V2, this has changed. I can work around this with using an explicit validator that calls HttpUrl to validate but returns a native string:

```python
class V2Fixed(pydantic.BaseModel):
    url: str

    @pydantic.field_validator("url")
    def is_url(cls, v):
        pydantic.TypeAdapter(pydantic.HttpUrl).validate_python(v)
        return v
```

Is this expected and how I should fix it, or should constrained types behave like native types?

### Example Code

```Python
import pydantic
import pydantic.v1

class V1(pydantic.v1.BaseModel):
    url: pydantic.v1.HttpUrl

class V2(pydantic.BaseModel):
    url: pydantic.HttpUrl

url = "https://example.org"
v1 = V1(url=url)
v2 = V2(url=url)

assert v1.url == url
assert v2.url == url  # error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
pydantic-core version: 2.1.2 release build profile
python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4.1-arm64-arm-64bit
```

Selected Assignee: @lig

**Comment by hramezani** [comment]
Yes, this is expected. We already mentioned it in our [migration doc](https://docs.pydantic.dev/2.0/migration/#url-and-dsn-types-in-pydanticnetworks-no-longer-inherit-from-str)
