### ISSUE TITLE
`Json[type]` schema generated now returns `string` rather than `type`

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#6663]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

With `Json[]` the schema type is now always `string`, rather than the type inside `Json[]`.

In `V1` the example would produce:

```JSON
{
   "title":"Foo",
   "type":"object",
   "properties":{
      "foo":{
         "title":"Foo",
         "type":"integer"
      }
   },
   "required":[
      "foo"
   ]
}
```

In `V2` it produces:
```JSON
{
   "properties":{
      "foo":{
         "format":"json-string",
         "title":"Foo",
         "type":"string"
      }
   },
   "required":[
      "foo"
   ],
   "title":"Foo",
   "type":"object"
}
```

I may be wrong, but given `"format": "json-string"` is added for clarity, there's no reason to change the type to `"string"` and this is a bug?

If this is intended and shouldn't be changed, is there any easy way to opt out without overriding `__get_pydantic_json_schema__` everywhere? The use case is most of our endpoints come in as json strings which are decoded, so this currently breaks a lot of the schema and validation externally.

### Example Code

```Python
from pydantic import BaseModel, Json


class Foo(BaseModel):
    foo: Json[int]


Foo.schema()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @zakstucke for reporting this 🙏 

Isn't the `"type":"string"` correct? because the model accepts strings, not int.

```py
Foo(foo='1')  # Ok

Foo(foo=1)
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo
foo
  JSON input should be string, bytes or bytearray [type=json_type, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.0.3/v/json_type
"""
```

**Comment by zakstucke** [comment]
@hramezani I would say no given a few reasons:
- `"format": "json-string"` is specifically stating that this input is expected to be coming in as a a jsonified version of the data type
- As a user of the schema, the user/external software can no longer validate the data *inside* the jsonified string, to make sure it's of the correct type
- Example use case is a lot of my frontend's typing system has broken because of this, endpoint types have all converted to `string`, meaning the correct types are seen as invalid.

**Comment by hramezani** [comment]
Ok, I might be wrong.

Let's see what others think. @samuelcolvin @dmontagu

**Comment by dmontagu** [comment]
This is intended: in V2, we now have the ability to create validation and serialization JSON schemas separately:
```python
from pydantic import BaseModel, Json


class Foo(BaseModel):
    foo: Json[int]


print(Foo.model_json_schema(mode='validation')['properties']['foo'])  # mode='validation' is the default
#> {'format': 'json-string', 'title': 'Foo', 'type': 'string'}

print(Foo.model_json_schema(mode='serialization')['properties']['foo'])  # mode='validation' is the default
#> {'title': 'Foo', 'type': 'integer'}
```

If you are using pydantic/calls to the `model_json_schema` method directly, the above should give you a way to get what you want; if you are using FastAPI or similar and it's not producing the right schema, let us know. (I don't believe FastAPI has added support for `mode='serialization'` schemas quite yet, but having some reported issues like this might increase the urgency on that.)

**Comment by dmontagu** [comment]
Also, I'll note that if you are using a web framework that is generating the schema for you and you want a short-term hacky fix to tide you over, you can do the following:
```python
import pydantic.json_schema
from pydantic import BaseModel, Json
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaValue
from pydantic_core import core_schema


class Foo(BaseModel):
    foo: Json[int]


class MyGenerateJsonSchema(GenerateJsonSchema):
    def json_schema(self, schema: core_schema.JsonSchema) -> JsonSchemaValue:
        # don't special-case validation
        # if self.mode == 'validation':
        #     return {'type': 'string', 'format': 'json-string'}
        if 'schema' in schema:
            return self.generate_inner(schema['schema'])
        else:
            # No wrapped schema, so return the same thing we would for an Any schema
            return self.generate_inner(core_schema.any_schema())


pydantic.json_schema.GenerateJsonSchema.json_schema = MyGenerateJsonSchema.json_schema

print(Foo.model_json_schema(mode='validation')['properties']['foo'])
#> {'title': 'Foo', 'type': 'integer'}

print(Foo.model_json_schema(mode='serialization')['properties']['foo'])
#> {'title': 'Foo', 'type': 'integer'}
```

**Comment by zakstucke** [comment]
@dmontagu thanks, this workaround works very nicely to reproduce old behaviour. 

However, I'll admit I don't quite agree with your intended (once supported) usage of `serialization` instead of `validation`, in reality imo this doesn't make sense as the official workaround being use `serialization`, because:
- it just is still validation, aka we want to know the data coming in, and the format it needs to be, not serialisation (how the data will come back out from a model)
- Setting serialization could cause unintended consequences (think `Field(exclude=True)` etc). 

But I understand json here is a bit of a weird one, and both ways have downsides, I propose this as the new default `json_schema()`:

```Python
class MyGenerateJsonSchema(GenerateJsonSchema):
    def json_schema(self, schema: core_schema.JsonSchema) -> JsonSchemaValue:
        genned = self.generate_inner(schema["schema"]) if "schema" in schema else self.generate_inner(core_schema.any_schema())
        
        if self.mode == "validation":
            return {"type": "string", "format": "json-string", "contents": genned}
        
        return genned
```

Which would produce:
```JSON
{
   "contents":{
      "type":"integer"
   },
   "format":"json-string",
   "title":"Foo",
   "type":"string"
}
```

change the key as you wish, but this would prevent the default implementation just losing information at the very least. 
Can PR it if you like, otherwise close this as the override of `.json_schema` works globally so I'm happy :+1:

**Comment by zakstucke** [comment]
And for reference yes this is with `fastapi.openapi()`, that then gets passed into https://github.com/drwpow/openapi-typescript to produce typescript types from the schema. The hacky fix sorts it, but as said above I would personally use the hacky fix over the serialization method if it was in some way supported in Fastapi, just seems too strange.

**Comment by adriangb** [comment]
> it just is still validation, aka we want to know the data coming in, and the format it needs to be, not serialisation (how the data will come back out from a model). If my type is Json[Foo], the endpoint isn't going to accept any old json input, the external party needs to know the exact structure of Foo as normal, since V2 this is all lost by default.

Unless I'm misunderstanding I guess this is the issue: there is no way to express "nested" json in json schema. You can either express it as a string, and loose information as you point out, or as the actual schema and have something technically incorrect since you're being sent a json string of that data, not the actual data.

**Comment by zakstucke** [comment]
@adriangb yeah pretty much. The hack https://github.com/pydantic/pydantic/issues/6663#issuecomment-1635934848 sorts it, but I still think the default should be changed pydantic side in one of these ways (in order of what I persoanlly think would be best):
- V1, behaviour but now the `"format":"json-string"` is added, it could arguably seen as correct and completely valid, no breaking change from V1, schema/swagger etc unchanged from V1.
- My suggestion in https://github.com/pydantic/pydantic/issues/6663#issuecomment-1635992464 to just add the schema as a separate key, would still be breaking from V1, but less so than currently and probably as "correct" as it can be, no information is lost.
- Leave it as it is, but means lots of people will have to use this hack to get around it as jsonifying input params is quite a common use case, e.g. think when sending with `multipart/form-data`. The jsonifying bit is obvious and probably happening automatically, what's actually important is the structure of `Foo` inside `Json[Foo]`.

**Comment by zakstucke** [comment]
But on a less concrete note, whenever I've found a need to use `Json[Foo]`, it's always because of a implementation level restriction that is forcing the usage of a json string, rather than the json being something that's activitely chosen. In other words, In the schema and outside it, I've never cared / even known it gets to the endpoint as json, all that's been important is `Foo`, and why I feel most people would much prefer old behaviour.

**Comment by samuelcolvin** [comment]
@Julian @Relequestual any chance you could arbitrate here? I'm really not sure if including the full `Foo` schema and adding `"format": "json-string"` is correct JSON Schema?

My personal preference would be @zakstucke's second option - addthe `Foo` schema in a separate key, so we go outside JSON Schema but still provide the schema.

**Comment by Julian** [comment]
It's *valid* JSON Schema, though I suspect the number of tools that will do something with it is vanishingly tiny, I've never seen it before -- "it" being "a value of `json-string` being given to the "format" keyword -- the format keyword allows you to define your own formats and indeed having one that means "serialized JSON" seems reasonable, and is allowed by the spec, albeit again yeah, a tool consuming the schema would need to be taught that that's what the format means.

But your second option there actually exists! It's called [`contentSchema`](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-contentschema).

So you'd say `"contentMediaType": "application/json", "contentSchema": {"type": "integer"}` or whatever.

Be aware that that doesn't "do" anything from a validation perspective -- meaning if you give a JSON Schema validator the schema:

```
{
  "type": "string",
  "contentMediaType": "application/json",
  "contentSchema": {"type": "integer"}
}
```

and data `"\"37\"` (i.e. the JSON *string* `"37"` rather than integer) a JSON Schema validator must by default say "yup that's valid" even though clearly it doesn't match the content schema -- the reasons are mostly "because it's not safe in general to try to deserialize some random media type" IIRC.

But it does what you want, and more tools should certainly support doing this with some coercing.

**Comment by samuelcolvin** [comment]
Perfect, that's what we wanted. Let's switch to:


```json
{
  "type": "string",
  "contentMediaType": "application/json",
  "contentSchema": {"type": "integer"}
}
```
