### ISSUE TITLE
Inconsistent version numbers between github and python

### ISSUE THREAD

**Issue by davidlougheed** [pydantic/pydantic#6666]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It doesn't make much sense to go from 2.0.2 to 2.03 as seen in the git tags/release page, as these are different version number formats. It makes upgrading confusing.

### Python, Pydantic & OS Version

```Text
2.03 / 2.0.3
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
I’m not sure what you mean. That’s a pretty standard patch version increment

**Comment by hswong3i** [comment]
> I’m not sure what you mean. That’s a pretty standard patch version increment

The previous GIT tags are:
* https://github.com/pydantic/pydantic/releases/tag/v2.0
* https://github.com/pydantic/pydantic/releases/tag/v2.0.1
* https://github.com/pydantic/pydantic/releases/tag/v2.0.2 (showing `VERSION = '2.0.2'`, see https://github.com/pydantic/pydantic/blob/v2.0.2/pydantic/version.py#L6)

The latest release is now inconsistent:
* https://github.com/pydantic/pydantic/releases/tag/v2.03 (showing `VERSION = '2.0.3'`, see https://github.com/pydantic/pydantic/blob/v2.03/pydantic/version.py#L6)

**Comment by lmrlyv** [comment]
> I’m not sure what you mean. That’s a pretty standard patch version increment

Please pay attention to the missing dot character between the "minor" and the "patch" version numbers

**Comment by hswong3i** [comment]
> It just fixed https://github.com/pydantic/pydantic/releases/tag/v2.0.3

Shall we also have https://pypi.org/project/pydantic/2.0.3/?

**Comment by hramezani** [comment]
Yes, you will have it today

**Comment by adriangb** [comment]
Ah I see now thank you for reporting it

**Comment by hramezani** [comment]
[Pydantic 2.0.3](https://pypi.org/project/pydantic/2.0.3/) just released
