### ISSUE TITLE
IPv4Address/IPv6Address is not serializable when part of untyped dict

### ISSUE THREAD

**Issue by nss-csis** [pydantic/pydantic#6669]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi!

Great job on Pydantic V2 and the amount of work that has been poured into fixing minor issues here after release.

In the process of migrating from V1 to V2 I stumbled upon an issue which I am not sure is a bug or intended behaviour. When serializing a model to json with an untyped dict containing a value of `ipaddress.IPv4Address` or `ipaddress.IPv4Address` pydantic throws an `pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: IPv4Address('8.8.8.8')`.

This does not happen when serializing an untyped dict with a `datetime.datetime()` value as can be seen in the example code.

It is possible for us to explicitly convert the `ipaddress.IPv4Address` or `ipaddress.IPv4Address` to strings before using them in a model, so there is no urgency, but it would be nice to know whether this issue is a bug or not.

### Example Code

```Python
import datetime
import ipaddress

from pydantic import BaseModel

class Test(BaseModel):
    d: dict


test_with_datetime = Test(d={"datetime": datetime.datetime(2023, 7, 14, 6, 44, 24, 223091)})
print(test_with_datetime.model_dump_json())

# returns: {"d":{"datetime":"2023-07-14T06:44:24.223091"}}

test_with_ip_v4_address = Test(d={"ip": ipaddress.IPv4Address('8.8.8.8')})
print(test_with_ip_v4_address.model_dump_json())

# fails with pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: IPv4Address('8.8.8.8')

test_with_ip_v6_address = Test(d={"ip": ipaddress.IPv6Address('2001:218::')})
print(test_with_ip_v6_address.model_dump_json())

# fails with pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: IPv6Address('2001:218::')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/nss/.cache/pypoetry/virtualenvs/ifd-_AXDVEVR-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Feb 23 2023, 13:05:14) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @lig

**Comment by hramezani** [comment]
Hi @nss-csis ,

Thanks for this issue 🙏 

I think it is intended behavior and we've already mentioned it in the [migration doc](https://docs.pydantic.dev/2.0/migration/#changes-to-handling-of-standard-types).

With the `dict`, we don't have key type and the value type would be `Any`. So, Pydantic doesn't validate the values.

**Comment by nss-csis** [comment]
For me its just not clear why it works with `datetime.datetime` and not `ipaddress.IPv4Address`. Is this some weird quirk of how the two different classes are implemented?

**Comment by lig** [comment]
@nss-csis I believe that the json serializer being used by Pydantic just be able to serialize `datetime.datetime` without any additional machinery inside Pydantic.

So, with Pydantic json serializer `datetime.datetime` isn't a custom class, it could be serialized wherever `int` or `str` could.
