### ISSUE TITLE
Cython functions are considered non-annotated attributes

### ISSUE THREAD

**Issue by vkozmik** [pydantic/pydantic#6670]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When trying to migrate to V2 we see that Cython functions which are result of dependency injection library are considered attributes:

E   pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `xxx = <cyfunction AAA.xxx at 0x12d51ab50>`. All model fields require a type annotation; if `xxx` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
E
E   For further information visit https://errors.pydantic.dev/2.0.2/u/model-field-missing-annotation

### Example Code

```Python
from dependency_injector.wiring import Provide, inject
from pydantic import BaseModel

class AAA(BaseModel):
    @inject
    def xxx(self, service = Provide["service"]) -> Optional[Any]:
        pass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /Users/vaclavkozmik/PycharmProjects/tarandm-core/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 (main, Mar  3 2023, 16:18:00) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by dmontagu** [comment]
you'll want to add the relevant type to `model_config['ignored_types']`, and I think that should resolve this for you.

If you can do something like:
```python
class AAA(BaseModel):
    model_config = {'ignored_types': [type(<some cyfunction>)]}

    @inject
    def xxx(self, service = Provide["service"]) -> Optional[Any]:
        pass
```
I think it should work. Unfortunately I don't know a good way to get a `cyfunction`, but I suspect it should be possible to make this work.

If you can't find a way to make that happen, there's still hope; you can define an `__instancecheck__` on a custom metaclass that will return True for cyfunction, and create a class with that metaclass and add it to the `ignored_types`. More concretely, here's a code sample that achieves this:
```python
from pydantic import BaseModel


class _CyFunctionDetectorMeta(type):
    def __instancecheck__(self, instance):
        if repr(instance).startswith('<cyfunction '):
            return True
        return False


class _CyFunctionDetector(metaclass=_CyFunctionDetectorMeta):
    pass


class MockCyFunction:
    def __repr__(self):
        return f'<cyfunction at ...>'


class A(BaseModel):
    model_config = {'ignored_types': (_CyFunctionDetector,)}

    xxx = MockCyFunction()


print(A.model_fields)  # xxx is not a field
#> {}
```
I think if you used the above code and replaced `xxx = MockCyFunction()` with your
```python
    @inject
    def xxx(self, service = Provide["service"]) -> Optional[Any]:
        pass
```
it will probably stop having the problem.

**Comment by dmontagu** [comment]
Looking at the v1 code, I see that we had explicitly added some special handling for cython functions because v1 was being cythonized. To get effectively the same logic as is used in v1, I think you can use a modified version of my trick above just redefining the instancecheck method as

```python
    def __instancecheck__(self, instance):
        return type(instance).__name__ == 'cython_function_or_method'
```

**Comment by dmontagu** [comment]
Putting it all together:

```python
from pydantic import BaseModel


class _CyFunctionDetectorMeta(type):
    def __instancecheck__(self, instance):
        return instance.__class__.__name__ == 'cython_function_or_method'

class CyFunctionDetector(metaclass=_CyFunctionDetectorMeta):
    pass


class A(BaseModel):
    model_config = {'ignored_types': (CyFunctionDetector,)}

    @inject
    def xxx(self, service = Provide["service"]) -> Optional[Any]:
        pass

print(A.model_fields)  # xxx is not a field
#> {}
```

I think this should work, and you can set this `model_config` on a shared base class as appropriate for your needs.

I'll close this issue given this solution, but please let us know if it doesn't work for you.

**Comment by vkozmik** [comment]
Hi David, thanks a lot, this helps! Just for curiosity, why not include the relevant code in Pydantic itself? Given that it was there in 1.X versions...

**Comment by bertramr** [comment]
We are currently having this issue as well. As we are cythonizing our code and just are in the migration phase to pydantic v2

**Comment by dtczest** [comment]
@dmontagu would it make sense to add notes about cython support in the pydantic documentation, and include this workaround?
