### ISSUE TITLE
Postponed validation support

### ISSUE THREAD

**Issue by Bobronium** [pydantic/pydantic#668]
# Feature Request
What I'm talking about is not actual postponed validation itself, but the ability to create model with invalid data and then manually check for errors and decide what to do next.

Despite the fact that `validate_model` func actually has argument `raise_exc`, which could control this behavior, currently pydantic throws error on any invalid data and doesn't allow user to have any control on it. Moreover didn't find any place where this arg used.

```py
import datetime

from anystrenum import StrEnum
from pydantic import BaseModel

class Gender(StrEnum):
    male: str
    female: str
    other: str
    not_given: str

class User(BaseModel):
    id: int
    name: str
    gender: Gender
    registration_date: datetime.datetime

    class Config:
        postponed_validation = True

user = User(id='123', name='John Doe', gender='other than other', registration_date='broken')
if user.errors:
    print({error.vaule: error for error in user.errors})
    # {'other than other': 'value is not a valid enumeration member (type=type_error.enum)',
    #  'broken': 'invalid datetime format (type=type_error.datetime)'}

print(user.gender)
# other than other

user.raise_for_errors()

'''
Traceback (most recent call last):
...

pydantic.error_wrappers.ValidationError: 2 validation errors
gender
  value is not a valid enumeration member (type=type_error.enum)
registration_date
  invalid datetime format (type=type_error.datetime)
'''
```

**Comment by dmontagu** [comment]
You could do a try-catch around `model.parse_obj` with an exception handler for `ValidationError` that looks at the generated errors. I’ll update with an example shortly, but there are many like this in the pydantic tests.

**Comment by MrMrRobat** [comment]
Imagine we creating a models in different places and want to handle all errors in one place. In this place we don't know what was the initial data and can't access it, but need to figure out what value caused error.

For example imagine we have decorator which checking all models returned by some function:

```py
import functools
import logging

log = logging.getLogger('Bad data handler')

def handle_bad_data(raw_data_on_errors=True):
    def decorator(func):
        @functools.wraps(func)
        def inner(*args, **kwargs):
            model = func(*args, **kwargs)
            if model.errors:
                log.error('Model %s has bad values:\n%s' % (
                    model, ',\n'.join((f'    {error.value}: {error}' for error in model.errors))
                    )
                )
                if raw_data_on_errors:
                    return model.data
                model.raise_for_errors()
            return model
        return inner
    return decorator
```

**Comment by dmontagu** [comment]
Not to necessarily discourage the development of this feature, but for what it's worth I think that pattern could be handled in a relatively clean way by passing around `(model_type, raw_data)` pairs prior to successful parsing, and writing handler functions / decorators / etc that expect inputs of that shape. You could then use the ValidationError to determine which fields had problems and handle them however you like, with access to the raw data.

Also, you may be able to accomplish this in a reusable way through the use of generics:

```python
from typing import Any, Generic, TypeVar, Dict, Optional, Type
import datetime
from enum import Enum

from pydantic.generics import GenericModel
from pydantic import BaseModel, ValidationError, validator

T = TypeVar("T")


class Gender(Enum):
    male = 'male'
    female = 'female'
    other = 'other'
    not_given = 'not_given'


class User(BaseModel):
    id: int
    name: str
    gender: Gender
    registration_date: Optional[datetime.datetime]


class ErrorModel(GenericModel, Generic[T]):
    raw_data: dict
    parsed: Optional[T]
    errors: list

    @validator("parsed", pre=True, always=True)
    def parse_raw_data(cls, v: Optional[T], values: Dict[str, Any]) -> Optional[T]:
        type: Type[BaseModel] = cls.__fields__["parsed"].type_.__args__[0]
        try:
            v = type.parse_obj(values["raw_data"])
            values["errors"] = []
        except ValidationError as exc:
            v = None
            values["errors"] = exc.errors()
        return v

    @validator("errors", always=True, pre=True)
    def handle_errors(cls, v, values):
        return values["errors"]


user_data_1 = dict(id='123', name='John Doe', gender='other than other', registration_date='broken')
user_data_2 = dict(id='123', name='John Doe', gender='male')

error_model_1 = ErrorModel[User](raw_data=user_data_1)
error_model_2 = ErrorModel[User](raw_data=user_data_2)
print(error_model_1)
print(error_model_1.parsed)
print(error_model_1.errors)
'''
ErrorModel[User] raw_data={'id': '123', 'name': 'John Doe', 'gender': 'other than other', 'registration_d… errors=[{'loc': ('gender',), 'msg': 'value is not a valid enumeration member', 'type':… parsed=None
None
[{'loc': ('gender',), 'msg': 'value is not a valid enumeration member', 'type': 'type_error.enum'}, {'loc': ('registration_date',), 'msg': 'invalid datetime format', 'type': 'type_error.datetime'}, {'loc': ('registration_date',), 'msg': 'value is not none', 'type': 'type_error.none.allowed'}]
'''
print(error_model_2)
print(error_model_2.parsed)
print(error_model_2.errors)
'''
ErrorModel[User] raw_data={'id': '123', 'name': 'John Doe', 'gender': 'male'} errors=[] parsed=<User id=123 name='John Doe' gender=<Gender.male: 'male'> registration_date=Non…
User id=123 name='John Doe' gender=<Gender.male: 'male'> registration_date=None
[]
'''
```

**Comment by samuelcolvin** [comment]
Personally when I want to do this I've [used `validate_model(model, raw_data, raise_exc=False)`](https://github.com/samuelcolvin/aiohttp-toolbox/blob/master/atoolbox/utils.py#L97) directly.

This is why I added the `raise_exc` argument I think.

Personally I'm not that keen on this, however I agree it would be very simple to add a `raise_exc` property to config.

Let's leave this open and see if anyone else wants it.

**Comment by PrettyWood** [comment]
Linked to #1864

**Comment by MVrachev** [comment]
Even if you validate your object in its creation you could easily end up with an invalid object and
before you do something important as writing to a database/file you would want to verify what the 
fields of the objects you are writing are still valid.

Example:

```python

class User(BaseModel):
  email: StrictStr

  @validator('email')
  def validate_email(cls, email):
    # Some regular expression checks for a valid email here
    return email

  def change_email(self, new_email: StrictStr):
    self.email = new_email


class RepositoryManager(BaseModel):
  repositoryUsers: List[User]
  writer: object

  def write_users_to_file(self):

    for user in self.repositoryUsers:

      # Validate that user objects have valid fields before writing even if their email has changed.
      user.check() 
    
    self.writer.write_to_file(self.repositoryUsers)
   ```
    
My personal opinion is that `user.validate()` sounds like a more appropriate name, but that's not so important.

**Comment by adam-discover** [comment]
Is there any follow up on this? This feature would be very useful instead of relying on the undocumented methods.

**Comment by eddsalkield** [comment]
I've been doing some thinking about what an elegant solution to this problem might look like.  If I understand correctly, the essence of the issue is that we're looking for a way to create models with potentially invalid data, describing a resolution mechanism to decide what to do when validation fails.

Building upon @dmontagu's approach of passing around a `(model_type, raw_data)` pair, I've proposed a reusable construct called a `DynamicGenerator` in #2866 that takes some raw data and a validator, and can use the validator to decide what to do with the raw data.

I define a `DynamicGenerator` called `FirstSuccessfulOf`, which evaluates to its first argument that successfully validates.  We can use this to solve the first problem in this thread in a way that respects @MVrachev's note: that we must eventually end up with an object that succeeds in validation, or raise a `ValidationError`.

```python3
class Gender(StrEnum):
    male: str
    female: str
    other: str
    not_given: str

class User(BaseModel):
    id: int
    name: str
    gender: Gender
    registration_date: Optional[datetime.datetime]

user = User(
        id='123',
        name='John Doe',
        gender=FirstSuccessfulOf('other than other', 'not_given', log_non_fatal = True),
        registration_date=FirstSuccessfulOf('broken', None, log_non_fatal = True),
        __handle_non_fatal__ = print)
```

For both `gender` and `registration_date`, `FirstSuccessfulOf` will try each of its possible values in turn.  If none of the possible values validate successfully, then a `ValidationError` is raised.  We can inject behaviour to handle non-fatal errors in `__handle_non_fatal__` - in this case, we're simply printing them.

Other things I like about this approach include that is that it's nestable, and works with validators.  Consider the following example:

```python3
class A(BaseModel):
    ints: conlist(int, min_items=1)

a = A(ints = FirstSuccessfulOf(
        AllSuccessfulOf(None, lambda: None),
        AllSuccessfulOf(1, None, 3)
    ))

print(a)
# ints=[1, 3]
```

This expresses that the list `ints` should be generated through one of two mechanisms: either `AllSuccessfulOf(None, lambda: None)` or `AllSuccessfulOf(1, None, 3)`. The first, when evaluated, essentially returns the empty list: none of its arguments successfully validated as `ints`. Then `FirstSuccessfulOf` validates the result against the validators of `A.ints`, which fails because the conlist has `min_items=1`. Then the next mechanism is tried.

**Comment by eddsalkield** [comment]
Anyone willing to give some feedback on my feature request? :slightly_smiling_face:

**Comment by HelloEdit** [comment]
I don't know if this is relevant, but this feature would be greatly appreciated when working with [SQLModel](https://sqlmodel.tiangolo.com), which, when creating a model with `table=true`, disables data verification. It would be great to have a clean way to check the object data before trying to do a write to the database for example.

**Comment by dmontagu** [comment]
It's been a while, any updated thoughts on an API that you'd like for this? I think it could be done through something like a generator or weak attributes or similar, but now that we've had a few more years to play with pydantic and work around these sorts of issues, I'm thinking anyone who still cares might have more fleshed out ideas. (I haven't closely reviewed the comments above, maybe the suggestions are reasonable.)

**Comment by dmontagu** [comment]
I'm going to close this because it's stale; if anyone cares about this and wants this capability, please open a new feature-request issue with a proposed API
