### ISSUE TITLE
RecursionError (V2) or RuntimeError (v1) when giving default to field whose name is identical to nested class name

### ISSUE THREAD

**Issue by sndrtj** [pydantic/pydantic#6680]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi!

Apologies if I'm filing this under the wrong label. I didn't get an option for Both V1 and V2. 

When a field name in a model is identical to a nested class name, giving it a default with `pydantic.Field` errors out at declaration time, in both v1 and v2. 

On v1,  the declaration fails with 

```
Traceback (most recent call last):
  File "pydantic/validators.py", line 751, in pydantic.validators.find_validators
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sander/PycharmProjects/pydantictest/test.py", line 12, in <module>
    class C(pydantic.BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 758, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 808, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 760, in find_validators
RuntimeError: error checking inheritance of FieldInfo(default=PydanticUndefined, default_factory=<class 'list'>, extra={}) (type: FieldInfo)
```

On v2, however, a RecursionError is raised. Last couple lines from the stack trace there:

```
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
  File "/Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
  File "/Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic/fields.py", line 521, in __repr_args__
    yield 'annotation', _repr.PlainRepr(_repr.display_as_type(self.annotation))
  File "/Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 104, in display_as_type
    args = ', '.join(map(display_as_type, typing_extensions.get_args(obj)))
  File "/Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 95, in display_as_type
    return repr(obj)
  File "/Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 82, in __repr__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'
  File "/Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
RecursionError: maximum recursion depth exceeded

```

See the code snippet for a reproducible example. 

I agree that a field name and nested class name being identical is weird and potentially confusing. In my case I can't control the field name, and the class name happened to be the 'logical' three-letter acronym for the concept I tried to model. Nevertheless, I expected this to work. Changing the class name is of course the workaround here. 

This may be related to https://github.com/pydantic/pydantic/issues/3879 and https://github.com/pydantic/pydantic/issues/2798, but these seem slightly different. 

The suggestion in #2798 to substitute `list` for `typing.List` yields yet another error, this time identical in both v1 and v2. 

```
TypeError: Parameters to generic types must be types. Got FieldInfo(default=PydanticUndefined, default_factory=<class 'list'>, extra={}).
```

### Example Code

```Python
import pydantic


class A(pydantic.BaseModel):
    foo: str


class B(pydantic.BaseModel):  # works fine
    A: list[A]


class C(pydantic.BaseModel):  # errors out at declaration
    A: list[A] = pydantic.Field(default_factory=list)


print(B.parse_obj({"A": [{"foo": "bar"}]}))
print(C.parse_obj({"A": [{"foo": "bar"}]}))
```

### Python, Pydantic & OS Version

```Text
v1:


             pydantic version: 1.10.11
            pydantic compiled: True
                 install path: /Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

v2: 

```
             pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/sander/Library/Caches/pypoetry/virtualenvs/pydantictest-6LWAQG6C-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```
```


Selected Assignee: @hramezani

**Comment by dmontagu** [comment]
The reason you are getting `TypeError: Parameters to generic types must be types. Got FieldInfo(default=PydanticUndefined, default_factory=<class 'list'>, extra={}).` is because this is actually an issue with Python (before Python3.11 anyway), not pydantic-specific:

```python
from typing import List

class A:
    foo: str


class B:  # works fine
    A: List[A]


class C:  # errors out at declaration
    A: List[A] = 1
```
"""
TypeError: Parameters to generic types must be types. Got 1.
""""

The problem is that the type hint `List[A]` is being evaluated in the namespace where you've defined `A` to be `1`.

While I think we should provide something better than a RecursionError when this happens (PR to resolve that welcome, for what it's worth), I think fundamentally there is a problem doing this in Python, not just specific to Pydantic.

The solution is to not use the name of a type as the name of a field. This can be done through the use of a type alias:
```python
from typing_extensions import TypeAlias
import pydantic


class A(pydantic.BaseModel):
    foo: str
AliasForA: TypeAlias = A


class B(pydantic.BaseModel):  # works fine
    A: list[AliasForA]


class C(pydantic.BaseModel):  # errors out at declaration
    A: list[AliasForA] = pydantic.Field(default_factory=list)


print(B.model_validate({"A": [{"foo": "bar"}]}))
#> A=[A(foo='bar')]
print(C.model_validate({"A": [{"foo": "bar"}]}))
#> A=[A(foo='bar')]
```
(using the v2 method name there, but I think it will work in both v1 and v2)

If for some reason you can't guarantee a name that won't have a collision (e.g. if you are doing something programatically), I'll note that you can use a dictionary of types in the typehint as a way to ensure that there won't be naming collisions. (You can see an example related to this in `tests.test_forward_ref.test_rebuild_recursive_schema`.) However, I would recommend just using the TypeAlias solution shown above if possible, that should work unless you are doing something more advanced (in which case we can discuss more).

**Comment by sndrtj** [comment]
Thanks for the explainer! Of course it's a scoping issue. 

Sigh, after 10 years of working with Python I thought I understood scoping. I had expected the type hint to be evaluated before the classvar gets defined, not after. 

For anyone who comes across here, some more snippets:

```python
from typing import List


class A:
    foo: str


class B:
    A: List[A] = list


class C:
    a: List[A] = A()


print(A.__annotations__)
print(B.__annotations__)
print(C.__annotations__)
```

returns 

```python
{'foo': <class 'str'>}
{'A': typing.List[list]}
{'a': typing.List[__main__.A]}
```

So that means `List[A]` inside class `B` declaration only gets evaluated after `A` is defined to `list` inside the class scope. 

Closing this because it's not really a pydantic issue.
