### ISSUE TITLE
TzInfo: Unable to compare to UTC

### ISSUE THREAD

**Issue by HynekBlaha** [pydantic/pydantic#6690]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, I would like to test model was correctly parsed from json string.

In Pydantic V1, the **tzinfo** was of type `datetime.timezone`.
In Pydantic V2, the **tzinfo** is of type `TzInfo`. 

I am unable to import/find TzInfo(UTC) and to assert expected result.
Could you please tell me how should be such comparison made?

I would be also very interested in links to discussions where it was decided to leave python standard for timezones in favour of TzInfo. Was it because of higher performance?

Thank you, Hynek

### Example Code

```Python
from datetime import datetime

from pydantic import BaseModel
from pydantic_core._pydantic_core import TzInfo


def test_assert_datetime():
    class MyDatetimeModel(BaseModel):
        dt: datetime

    payload = '{"dt": "2022-10-23T21:00:08.784Z"}'
    result = MyDatetimeModel.model_validate_json(payload)

    # assert result is None
    # Expected :None
    # Actual   :MyDatetimeModel(dt=datetime.datetime(2022, 10, 23, 21, 0, 8, 784000, tzinfo=TzInfo(UTC)))

    assert result == MyDatetimeModel(dt=datetime(2022, 10, 23, 21, 0, 8, 784000, tzinfo=TzInfo(UTC))) # What here?
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/personal/Library/Caches/pypoetry/virtualenvs/sf-base-agent-JSLqnODd-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, May 19 2023, 13:45:23) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by adriangb** [comment]
```python
from datetime import datetime, timezone

from pydantic import BaseModel


def test_assert_datetime():
    class MyDatetimeModel(BaseModel):
        dt: datetime

    payload = '{"dt": "2022-10-23T21:00:08.784Z"}'
    result = MyDatetimeModel.model_validate_json(payload)

    assert result == MyDatetimeModel(dt=datetime(2022, 10, 23, 21, 0, 8, 784000, tzinfo=timezone.utc)) # What here?
    
test_assert_datetime()
```

**Comment by adriangb** [comment]
I believe we created a new type because we couldn't instantiate `datetime.timezone` from Rust without calling into Python which yes is a performance hit.

**Comment by HynekBlaha** [comment]
I am very surprised I haven't tried the most obvious solution. Thanks a lot, @adriangb! <3
