### ISSUE TITLE
2.0.3 pytest parameters are not recognized

### ISSUE THREAD

**Issue by dvzrv** [pydantic/pydantic#6691]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! When trying to package 2.0.3 for Arch Linux I ran into issue trying to test pydantic:

I'm installing pydantic into a temporary directory to test it using pytest: https://gitlab.archlinux.org/archlinux/packaging/packages/python-pydantic/-/blob/c3c3d14480382723577c6532a496b9b90bc808fd/PKGBUILD#L52-66

Unfortunately with 2.0.3 I am running into:

```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --benchmark-columns --benchmark-group-by group --benchmark-warmup on --benchmark-disable
  inifile: /build/python-pydantic/src/pydantic-2.0.3/pyproject.toml
  rootdir: /build/python-pydantic/src/pydantic-2.0.3
```

I have seen this with pydantic-core as well and there I had to manually `sed` the benchmark-related parameters out of the pyproject.toml. I'm a bit clueless as to why this fails though.

### Example Code

```Python
n/a
```

### Python, Pydantic & OS Version

```Text
I'm building from the 2.0.3 tarball from github.
```

Selected Assignee: @samuelcolvin

**Comment by samuelcolvin** [comment]
You need pytest-benchmark installed as per the  install instructions.

**Comment by dvzrv** [comment]
Oh, my bad... I didn't see that! Sorry.
