### ISSUE TITLE
(🎁) Icon for Idea plugin

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#6698]
Hi 👋,

I'm attempting to address this issue: 
- https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/435. 

I would like some advice from your media relations team regarding iconography, I wasn't able to find a press pack on any of your documentation.

This is how it will appear:
![image](https://github.com/pydantic/pydantic/assets/65446343/fa4c5131-4cbf-4da4-83a1-c2c285b22203)

We have the technology to support both a light and a dark icon.

## Random Ideas I have
white logo for dark theme (previous picture), and black logo for light theme.

White on pink (for light and dark theme):
![image](https://github.com/pydantic/pydantic/assets/65446343/59d955f1-f704-4550-b090-690afb2c8c17)
![image](https://github.com/pydantic/pydantic/assets/65446343/65ccb310-24c5-42ff-8eaf-4b1dc4781639)

# Thanking you 😊

Selected Assignee: @lig

**Comment by lig** [comment]
@samuelcolvin Could you please help with the branding of the Pydantic plugin?

**Comment by samuelcolvin** [comment]
Thanks so much for helping on this.

We need a proper brand kit, but the exact logo and how we use it is still developing.

My proposal would be the following:
* use [this pink penrose triangle](![pydantic-pink-square-border](https://github.com/pydantic/pydantic/assets/4039449/29c158bf-0584-4d3e-9893-50f2639e3306)) for both - bigger border than shown in your images
* ideally the pink will stand out both with a light background and a dark background
* if you to set a background color, use white on the light theme, and `#1D293B` on dark - in this case the triangle needs a border around it
* if no background color is required, you can have no border around the "triangle"

Does that make sense?

**Comment by KotlinIsland** [comment]
@samuelcolvin So you want me to make these svgs from scratch, or will you be providing them?

**Comment by sydney-runkle** [comment]
@KotlinIsland,

Thanks for your work on this! Here's the pink pydantic logo:

![pydantic-pink-square](https://github.com/pydantic/pydantic/assets/54324534/e439d8e4-f736-4dbf-b05c-4eecbcbc6712)

Feel free to ping me if you need anything else 😄.

**Comment by KotlinIsland** [comment]
![image](https://github.com/pydantic/pydantic/assets/65446343/15acfca6-d35e-4e3c-a2a2-fe5df73ec8ac)
![image](https://github.com/pydantic/pydantic/assets/65446343/cc20242c-3d56-4413-a750-d85a974544a9)
