### ISSUE TITLE
Can we handle lists with different types with tagged unions?

### ISSUE THREAD

**Issue by jacleggmsr** [pydantic/pydantic#6707]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I would like to be able to be able to have a list of attibutes where each element can be a different Tagged Union type.  Something like this:

```
from pydantic import dataclass, Field

@dataclass
class Thing1:
    name: str
    x: Literal["1"]

@dataclass
class Thing2:
    name: str
    x: Literal["2"]

@dataclass
class Container:
    things: list[Thing1 | Thing2] = Field(discriminator="x")
```

And then have a `test.json` file like this:

```
Container: {
    things: {
      {name: bob, x: "1"},
      {name: alice, x: "2"}
    }
}
```

Then when I load this in pydantic:

```
with open(test.json, "r") as fh:
    json_data = json.load(fh)
c = Container(**json_data)
isinstance(c.things[0], Thing1) == True
isinstance(c.things[1], Thing2) == True
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
Try:

```python
from typing import Annotated
from pydantic import dataclass, Field

@dataclass
class Thing1:
    name: str
    x: Literal["1"]

@dataclass
class Thing2:
    name: str
    x: Literal["2"]


Thing = Annotated[Thing1 | Thing2, Field(discriminator="x")]

@dataclass
class Container:
    things: list[Thing]
```

**Comment by jacleggmsr** [comment]
Thanks! That's just what I need.
