### ISSUE TITLE
`ValidationError` errors-context data fails with Mypy after using Pydantic V2

### ISSUE THREAD

**Issue by MarkusSintonen** [pydantic/pydantic#6712]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It seems typing of `ValidationError.errors()`->`list[ErrorDetails]` is not compatible with existing usage and V2s `PydanticCustomError` context argument. Below example shows an use-case where we encountered problems in typing of `ErrorDetails` when using eg `numpy` based validation and deeper dict to pass validation failure information forward.

This used to work in v1+Mypy. Now in v2 the code works but it fails with Mypy due to definition of `ErrorDetails` `ctx`. Can it be made to `dict[str, Any] | None` similar as in `PydanticCustomError`-`context` argument? Why is it now defined as just `ctx: _NotRequired[dict[str, str | int | float]]`?

### Example Code

```Python
from typing import TYPE_CHECKING

import numpy
from pydantic import BaseModel, ValidationError, field_validator
from pydantic_core import PydanticCustomError


def test_exception():
    class MyModel(BaseModel):
        my_field: list[int]

        @field_validator("my_field")
        @classmethod
        def validate_my_field(cls, values: list[int]) -> list[int]:
            values_array = numpy.fromiter(values, dtype="i8", count=len(values))
            bad_vals = numpy.array([5, 8, 14], dtype="i8")  # Its just a random example.
            bad_idx = numpy.where(numpy.isin(values_array, bad_vals))[0]
            if len(bad_idx) > 0:
                error = PydanticCustomError(
                    "my_error",
                    "My error message",
                    {"my_error_info": {"bad_indexes": bad_idx}}  # Here it works fine...
                )
                if TYPE_CHECKING:
                    # Revealed type is "Union[builtins.dict[builtins.str, Any], None]"
                    reveal_type(error.context)
                raise error
            return values

    MyModel(my_field=[0, 1, 4, 6, 10])

    try:
        MyModel(my_field=[0, 1, 4, 5, 6, 8, 10])
    except ValidationError as e:
        assert e.errors() and e.errors()[0]["type"] == "my_error"

        error_context = e.errors()[0]["ctx"]
        if TYPE_CHECKING:
            # Revealed type is "builtins.dict[builtins.str, Union[builtins.str, builtins.int, builtins.float]]"
            reveal_type(error_context)

        # error: Value of type "str | int | float" is not indexable  [index]
        # error: Invalid index type "str" for "str | int | float"; expected type "SupportsIndex | slice"  [index]
        failing_indexes = error_context["my_error_info"]["bad_indexes"]
        assert isinstance(failing_indexes, numpy.ndarray)
        assert failing_indexes.tolist() == [3, 5]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/markussintonen/Library/Caches/pypoetry/virtualenvs/leak-test-VvUvdXxD-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 20 2023, 17:00:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by AmanSal1** [comment]
@Kludex Hey is external contribution allowed in this repo ? I am new to open source and would like to contribute ?

**Comment by Kludex** [comment]
It looks like since the `context` `PydanticCustomError` receives is `dict[str, Any]`, then we need to change the `ctx` on `ErrorDetails`: https://github.com/pydantic/pydantic-core/blob/1382debe3e9ed622f312dc36f5dfcf165e2ae109/python/pydantic_core/__init__.py#L67-L72C9

**Comment by Kludex** [comment]
> @Kludex Hey is external contribution allowed in this repo ? I am new to open source and would like to contribute ?

It does allow. You can read our contribution guidelines: https://docs.pydantic.dev/latest/contributing/

**Comment by MarkusSintonen** [comment]
I opened a fix PR here https://github.com/pydantic/pydantic-core/pull/809

Can I ask you @Kludex to check it out? ^
