### ISSUE TITLE
TOML Parsing with Pydantic V2 fails with nested models

### ISSUE THREAD

**Issue by bernardcooke53** [pydantic/pydantic#6722]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am maintaining a Python project that loads configuration from a `pyproject.toml` file and uses Pydantic to do all the hard validation logic (:heart:) - if it would help you can see the full config description (using Pydantic V1) [here](https://github.com/python-semantic-release/python-semantic-release/blob/master/semantic_release/cli/config.py)

I'm going through the motions seeing what it would take to upgrade to V2 and am getting validation errors for seemingly valid input to my models (example code below).

There's a good chance I could be doing something wrong with `SerializeAsAny`, I've given it a go, though. With V1 I am using the model both to validate user configuration and to provide default values if they're missing and it works like a treat.

In addition to the Python code below, I set up the following for a minimal example:

```toml
# config.toml
[tool.tool_name.branches.main]
boolean_option = true
literal_option = "a"

[tool.tool_name.branches."another nested key"]
boolean_option = false
literal_option = "b"
```

```
# requirements.txt
tomlkit==0.11.8
pydantic==2.0.3
typing_extensions==4.7.1
```

Also the output of `pip freeze`:

```
annotated-types==0.5.0
pydantic==2.0.3
pydantic_core==2.3.0
tomlkit==0.11.8
typing_extensions==4.7.1
```

When I run the example python script (`python3 model.py`), I _expect_ I should be able to load the configuration into the `Config` model and access a single key, `"branches"`, which should map the next-level nested key to the structure underneath. I.e. the model equivalent of:
```python
{
    "branches": {
        "main" {
            "boolean_option": True,
            "literal_option": "a"
        },
        "another nested key" : {
            "boolean_option": False,
            "literal_option": "b"
        }
    }
}
```

However I get the following errors instead:

```
Traceback (most recent call last):
  File "model.py", line 27, in <module>
    main()
  File "model.py", line 23, in main
    Config.model_validate(loaded["tool"]["tool_name"])
  File "/home/bernard/bernardcooke53/pydantic-bug/.venv/lib/python3.8/site-packages/pydantic/main.py", line 480, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Config
branches.main.boolean_option
  Input should be a valid boolean [type=bool_type, input_value=True, input_type=Bool]
    For further information visit https://errors.pydantic.dev/2.0.3/v/bool_type
branches.main.literal_option
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='a', input_type=String]
    For further information visit https://errors.pydantic.dev/2.0.3/v/literal_error
branches.another nested key.literal_option
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='b', input_type=String]
    For further information visit https://errors.pydantic.dev/2.0.3/v/literal_error

```

### Example Code

```Python
# model.py
from __future__ import annotations

from typing import Dict

import tomlkit
from pydantic import BaseModel, SerializeAsAny
from typing_extensions import Literal


class ConfigFragment(BaseModel):
    boolean_option: bool = False
    literal_option: Literal["a", "b", "c"] = "c"


class Config(BaseModel):
    branches: Dict[str, SerializeAsAny[ConfigFragment]] = {"main": ConfigFragment()}


def main() -> None:
    with open("config.toml") as f:
        loaded = tomlkit.load(f)

    Config.model_validate(loaded["tool"]["tool_name"])


if __name__ == "__main__":
    main()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/bernard/bernardcooke53/pydantic-bug/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.13 (tags/v3.8.13:ea673213dd, Jul 23 2022, 17:35:04)  [GCC 11.2.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Thank you for an awesome library and in advance for the help :pray: 

Selected Assignee: @dmontagu

**Comment by hramezani** [comment]
Thanks @bernardcooke53 for this issue 🙏 

The reason is values fetched from toml file are not Python standard `bool` or `str`. They are `tomlkit.items.Bool` and `tomlkit.items.String`. 

You can convert them to valid python types before validation by `field_validator`.

```py
from __future__ import annotations

from typing import Dict

import tomlkit
from pydantic import BaseModel, SerializeAsAny, field_validator
from typing_extensions import Literal


class ConfigFragment(BaseModel):
    boolean_option: bool = False
    literal_option: Literal["a", "b", "c"] = "c"

    @field_validator('boolean_option', mode='before')
    @classmethod
    def boolean_option_value(cls, v):
        return bool(v)

    @field_validator('literal_option', mode='before')
    @classmethod
    def literal_option_value(cls, v):
        return str(v)


class Config(BaseModel):
    branches: Dict[str, SerializeAsAny[ConfigFragment]] = {"main": ConfigFragment()}


def main() -> None:
    with open("config.toml") as f:
        loaded = tomlkit.load(f)

    config = Config.model_validate(loaded["tool"]["tool_name"])
    print(config.model_dump())


if __name__ == "__main__":
    main()
```

**Comment by bernardcooke53** [comment]
Thank you for the advice @hramezani :tada: 

I tested locally and confirmed it works. Also `SerializeAsAny` isn't necessary in the type-hint for `Config.branches` in case anyone else finds this issue later.

So the issue was actually to do with no longer being able to coerce the `tomlkit` types into inbuilt Python types, not nesting the models?

In any case, I was also able to swap out `tomlkit` for `tomli` and `tomli-w` as TOML serialiser/deserialisers, as those libraries _do_ parse TOML into native Python types.

A small note - I was confused when looking at the validation error initially:

```
branches.another nested key.literal_option
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='b', input_type=String]
```

because I assumed `input_type=String` was something that `pydantic` contained internally (some `String` type), but I surmise from your response that that's actually the `tomlkit.items.String` type. I haven't poked around in the source code, but I'd hazard an educated guess that the error message is constructed using `<input type>.__name__`? In which case, perhaps using `<input type>.__qualname__` might make it just a touch easier to figure out what's going on, as then I'd expect the error message to look like:
```
branches.another nested key.literal_option
  Input should be 'a', 'b' or 'c' [type=literal_error, input_value='b', input_type=tomlkit.items.String]
```

Just a bit of food for thought :slightly_smiling_face: I will close the issue anyway. Thanks again for the help!
