### ISSUE TITLE
`PydanticSerializationError` for `re.Pattern`

### ISSUE THREAD

**Issue by Mr-Pepe** [pydantic/pydantic#6724]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I get 

`pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: re.compile('asd')` 

when running the following code snippet. 

It works fine when annotating `MyModel.p` as `dict[str, re.Pattern]`.
It also worked fine with v1.

### Example Code

```Python
import re
from pydantic import BaseModel

class MyModel(BaseModel):
    p: dict

a = MyModel(p={"pattern": re.compile("asd")})

a.model_dump_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
pydantic-core version: 2.3.0 release build profile
python version: 3.9.13 (main, Jul 18 2022, 09:11:04)  [GCC 12.1.0]
platform: Linux-6.4.3-arch1-2-x86_64-with-glibc2.37
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by Mr-Pepe** [comment]
The workaround we are using for now is to apply a custom serializer:

```Python
import re
from typing import Annotated

from pydantic import BaseModel, WrapSerializer


def dict_wrapper(p, _):
    for key, value in p.items():
        if isinstance(value, re.Pattern):
            p[key] = value.pattern
    return p


MyDict = Annotated[dict, WrapSerializer(dict_wrapper, when_used="json")]


class MyModel(BaseModel):
    p: MyDict


a = MyModel(p={"pattern": re.compile("asd")})

print(a.model_dump_json())

```

**Comment by hramezani** [comment]
Thanks @Mr-Pepe for this issue 🙏 

I think it's kinda a duplicate of https://github.com/pydantic/pydantic/issues/6669

**Comment by Mr-Pepe** [comment]
I think so, too. However, as a user, it's of course a bit annoying to lose functionality with a migration to v2. 

1. In my use case, the dictionary could hold all kinds of values and Pydantic v1 could handle all the ones that appeared in production so far. I thus don't want to restrict artificially restrict the allowed value types. Is there a type that I could use for such cases, `dict[str, PydanticOutOfTheBoxSupportedType]`?

2. Is there a reason for dropping support for stuff like `re.Pattern` and `ipaddress.IPv4Address` or has the new serialization engine just not caught up to the old one yet?

3. Is the workaround I posted the recommended approach for cases that are not natively supported by the serialization engine?

**Comment by hramezani** [comment]
> In my use case, the dictionary could hold all kinds of values and Pydantic v1 could handle all the ones that appeared in production so far. I thus don't want to restrict artificially restrict the allowed value types. Is there a type that I could use for such cases, dict[str, PydanticOutOfTheBoxSupportedType]?

No, you can use `union`  e.g.  `dict[str, Union[type1, type2, ...]]`

> Is there a reason for dropping support for stuff like re.Pattern and ipaddress.IPv4Address or has the new serialization engine just not caught up to the old one yet?

We didn't remove the support for these types. you still can have fields of these types and validate/serialize data. 

> Is the workaround I posted the recommended approach for cases that are not natively supported by the serialization engine?

You can use `field_serializer` as well:

```py
import re
from pydantic import BaseModel, field_serializer

class MyModel(BaseModel):
    p: dict

    @field_serializer('p')
    def serialize_dict(values):
        for key, value in values.items():
            if isinstance(value, re.Pattern):
                values[key] = value.pattern
        return values

a = MyModel(p={"pattern": re.compile("asd")})

print(a.model_dump_json())
```

**Comment by Mr-Pepe** [comment]
> We didn't remove the support for these types. you still can have fields of these types and validate/serialize data.

But not without explicitly annotating them, which was not required in v1. 

> You can use field_serializer as well

Awesome, thanks! That looks like a better solution :+1:
