### ISSUE TITLE
Appropriate replacement for json_encoders

### ISSUE THREAD

**Issue by xmatthias** [pydantic/pydantic#6726]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I used to have working code using json_encoders to encode and enforce datetime fields to an expected format.

With the removal of `json_encoders` - i'm now no longer sure how to accomplish this, as my model must be defined a bit vague intentionally.

in the below example, there's seemingly one `datetime` field - which i can probably easily convert with `@field_serializer`.

The problematic part is the `data: List[Any]` section - which can will be a list containing one or multiple datetimes (as well as multiple other types).

the expected output for `data` can be something around the following:

```
 [
    ['2017-11-26 08:50:00', 8.794e-05, 0, 1511686200000, None, None, None, None],
    ['2017-11-26 08:51:00', 8.794e-05, 0, 1511686200000, None, 'randomString', None, None]
    ['2017-11-26 08:51:00', 8.794e-05, 0, 1511686200000, None, None, None, '2017-11-26 08:50:00']
   # ....
]
```

in pydantic v1, json_encoders simply looked for all datetime types and serialized them as expected, but i see no real alternative for this in pydantic v2 without handling all serialization for the whole model (the actual model is a lot bigger than the below specified).

### Example Code

```Python
from pydantic import BaseModel, ConfigDict

DATETIME_PRINT_FORMAT = '%Y-%m-%d %H:%M:%S'

class CustomData(BaseModel):
    columns: List[str]
    data: List[Any]
    last_analyzed: datetime

    # TODO[pydantic]: The following keys were removed: `json_encoders`.
    # Check https://docs.pydantic.dev/dev-v2/migration/#changes-to-config for more information.
    model_config = ConfigDict(json_encoders={
        datetime: lambda v: v.strftime(DATETIME_PRINT_FORMAT),
    })
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 12 2023, 20:09:51) [GCC 13.1.1 20230429]
                     platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']

```

Might be related to #6375
```


Selected Assignee: @Kludex

**Comment by xmatthias** [comment]
@Kludex i'm not entirely sure on the process for this - does "Feedback wanted" mean there's still something missing from my side?

Personally, i'd not see this as a feature request but as a bug - as it's functionality that was removed in v2 without appropriate replacement...

**Comment by Kludex** [comment]
We are working on a fix here: https://github.com/pydantic/pydantic/pull/6737

**Comment by xmatthias** [comment]
@Kludex unfortunately, the fix does not seem to work (at least not in it's entirety).

The re-introduced json_encoders (now using pydantic 2.1.1) does work fine for explicitly defined fields (e.g. `last_analyzed` in the above sample) - but doesn't work for the anonymously typed "Any" list.

![image](https://github.com/pydantic/pydantic/assets/5024695/a38125e3-dbeb-4c52-b995-1ae0f7c9f003)

![image](https://github.com/pydantic/pydantic/assets/5024695/11b6e327-859b-4699-bd88-e604410704bc)

I suspect it's not descending into the sub-objects - but that's a suspicion withou real knowledge on how this worked under the hood before.

**Comment by adriangb** [comment]
Indeed. It’s not exactly a 1:1 reproduction of the v1 behavior. Reproducing that particular behavior would make serialization considerably slower for every case because we’d have to check every single value.

**Comment by xmatthias** [comment]
@adriangb That's fine (i'm not keen on using json_encoders anyway) - can you please suggest an alternative for this usecase, then? (where the sub-types are not actually known but need formatting based on their native type).

**Comment by adriangb** [comment]
You can use `Pydantic.SerialializeAsAny[datetime]`. I’ll look into making it “just work” for the case where json_encoders is used. Can you give me a MRE so I can be certain of the use case?
