### ISSUE TITLE
Enable access to `info.data` in the Annotated Validators

### ISSUE THREAD

**Issue by zyv** [pydantic/pydantic#6732]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

Pydantic V2 parses datetimes in UTC using its internal `TzInfo(0)` as timezone constant.

Unfortunately, this breaks our test assertions, because when we construct reference models, we use Python standard library, specifically `datetime.UTC`.

I guess this broke after datetime stuff was offloaded to Rust. There are even some tests codifying the "wrong" behaviour:

https://github.com/pydantic/pydantic-core/blame/33fea1e5ea1c70233dabb44390465cd097a1f8fa/tests/validators/test_datetime.py#L168

I hope that this glitch can be corrected, because otherwise I can only think of wrapping datetimes with some custom type to enforce the `tzinfo`, which is of course annoying and unpractical.

Thanks!

### Example Code

```Python
from pydantic import BaseModel
from datetime import UTC, datetime

class DtTest(BaseModel):
    dt: datetime

DtTest.model_construct(dt=datetime(2021, 8, 22, 10, 28, 16, tzinfo=UTC))
DtTest.model_validate({'dt':1629628096000})
```

```
# Construct
DtTest(dt=datetime.datetime(2021, 8, 22, 10, 28, 16, tzinfo=datetime.timezone.utc))

# Validate
DtTest(dt=datetime.datetime(2021, 8, 22, 10, 28, 16, tzinfo=TzInfo(UTC)))
```

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/zaytsev/.cache/pypoetry/virtualenvs/youtrack-sdk-xDu66pto-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
                     platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
What is actually broken for you? If you compare those models they should compare equal.

**Comment by adriangb** [comment]
In other words, this works:

```py
from datetime import datetime, timezone

from pydantic import BaseModel


class DtTest(BaseModel):
    dt: datetime

m1 = DtTest.model_construct(dt=datetime(2021, 8, 22, 10, 28, 16, tzinfo=timezone.utc))
m2 = DtTest.model_validate({'dt':1629628096000})

assert m1 == m2
```

**Comment by zyv** [comment]
Well, I'm getting the following error in my tests:

<img width="997" alt="Screenshot 2023-07-20 at 14 31 51" src="https://github.com/pydantic/pydantic/assets/607401/6ac1e0a2-666e-4b57-abd8-b526daa8a88e">

but I can't reproduce it with the minimal example at the moment:

```python
from datetime import UTC, datetime
from unittest import TestCase

from pydantic import BaseModel


class DtTest(BaseModel):
    dt: datetime


m1 = DtTest.model_construct(dt=datetime(2021, 8, 22, 10, 28, 16, tzinfo=UTC))
m2 = DtTest.model_validate({"dt": 1629628096000})


class TestDatetime(TestCase):
    def test_datetime(self):
        self.assertEqual(m1, m2)


if __name__ == "__main__":
    assert m1 == m2
```

I will try to reduce our test to a minimal reproducer.

**Comment by zyv** [comment]
@adriangb thank you for your patience - I think I've got to the bottom of it. You are right that even though the representation is different, the objects compare equal, so this is not why the unit test is failing.

The real problem is hidden in the rest of the text. We are using annotated validators, and even though they seem to receive the `info` argument, these objects are apparently corrupted. The `repr` works correctly, but `data` member is inaccessible causing an exception.

Here is the minimal reproducer:

```python
from datetime import UTC, datetime
from typing import Annotated

from pydantic import BaseModel, BeforeValidator
from pydantic_core.core_schema import FieldValidationInfo


def validate_datetime(value, info: FieldValidationInfo):
    print(info)
    assert info.data
    return value


ValidatedDatetime = Annotated[datetime, BeforeValidator(validate_datetime)]


class DtTest(BaseModel):
    dt1: datetime
    dt2: ValidatedDatetime


m = DtTest.model_validate(
    {
        "dt1": datetime(2021, 8, 22, 10, 28, 16, tzinfo=UTC),
        "dt2": 1629628096000,
    },
)

if __name__ == "__main__":
    assert m
```

The output for me is as follows:

```
$ python /home/zaytsev/src/youtrack-sdk/pydantic_v2.py 
ValidationInfo(config={'title': 'DtTest'}, context=None, data={'dt1': datetime.datetime(2021, 8, 22, 10, 28, 16, tzinfo=datetime.timezone.utc)})
Traceback (most recent call last):
  File "/home/zaytsev/src/youtrack-sdk/pydantic_v2.py", line 22, in <module>
    m = DtTest.model_validate(
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaytsev/.cache/pypoetry/virtualenvs/youtrack-sdk-xDu66pto-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 480, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaytsev/src/youtrack-sdk/pydantic_v2.py", line 10, in validate_datetime
    assert info.data
           ^^^^^^^^^
AttributeError: No attribute named 'data'

Process finished with exit code 1
```

**Comment by adriangb** [comment]
There is no `data` on Annotated validators since they are not attached to any specific model. That is encoded into the type hints: https://github.com/pydantic/pydantic/blob/76bf54fc2c1dc9a509a64129676a23919fc7007b/pydantic/functional_validators.py#L77C31-L77C31

**Comment by zyv** [comment]
> There is no `data` on Annotated validators since they are not attached to any specific model. That is encoded into the type hints.

Your link says

```python
func: core_schema.NoInfoValidatorFunction | core_schema.GeneralValidatorFunction
```

The definition of `core_schema.GeneralValidatorFunction` is as follows:

```python
GeneralValidatorFunction = Callable[[Any, ValidationInfo], Any]
```

This is why I tried it in the first place, so I don't quite understand your statement.

Also observe, that the info is indeed provided to the validator, and is even correct - just the `data` field is somehow not readable. I can parse `repr(info)` as string, but nobody seriously wants to do that.

You are right that the annotated validators are not attached to any specific model, but this is exactly why I want to use them.

In these validators I want use supplemental information provided about this specific field, and I want this logic to be bound to this field type, which is used in different models, instead of inheriting models which has nothing to do with each other, other than using some specific field type from a common mixin.

**Comment by adriangb** [comment]
Apologies if I was not being clear. `ValidationInfo` does not have a `data` attribute, `FieldValidationInfo` does: https://github.com/pydantic/pydantic-core/blob/f38bea601a5b81d73ee5a132242b7b97d24772ff/python/pydantic_core/core_schema.py#L148-L185.

We don't support access model data in Annotated validators, at least for now.

**Comment by zyv** [comment]
@adriangb ah, alright, thanks for the explanation! Now I understand what you meant with the reference to the type hints. It's super-confusing though, the data is there, but I can't access it in any way other that `repr`.

Is there any special reason, why it's not allowed? Are you against it in principle, or it just needs work to be implemented properly, which you would like first to invest elsewhere?

I want to understand what to do with this issue: either it can be converted into a feature request and I can edit the description if this helps, or it can be rejected.

Also depending on what your plans are, I can either build in a provisionary hack that pulls the information I need out of `repr` until `data` is properly accessible in future releases, or I must settle upon something else.

Unfortunately, the only thing that comes to mind is the following rather disappointing solution, which has the disadvantage, that one needs to remember to declare the validators every time a certain type is used, instead of encoding them into the type itself with your genius annotated feature, which is of course prone to errors - too easy to forget, but at least allows for some code reuse:

```python
from datetime import UTC, datetime

from pydantic import BaseModel, field_validator
from pydantic_core.core_schema import FieldValidationInfo


def validate_datetime(value, info: FieldValidationInfo):
    print(info.data)
    return value


class DtTest(BaseModel):
    dt: datetime
    dt_validator = field_validator("dt")(validate_datetime)


m = DtTest.model_validate({"dt": datetime(2021, 8, 22, 10, 28, 16, tzinfo=UTC)})

if __name__ == "__main__":
    assert m
```

**Comment by adriangb** [comment]
Having it in the repr was a bug. We're removing it.

As for a long term solution, the fundamental problem is that I'm not sure that it's sound to access model data from arbitrarily deep / nested models. If you have `field: Annotated[int, BeforeValidator(...)]` sure that makes sense. Maybe `field: Dict[str, List[Annotated[..., BeforeValidator()]]]` makes sense as well. But if you have `field: Dict[str, SomeTypedDict[Annotated[...]]]` I think it shouldn't get the fields of the outer model but rather of `SomeTypedDict`. What a "model" means is somewhat ambiguous, TypedDict's in particular weren't really models in v1 but they basically are in v2. Then there's other things like `TypeAliasType` that have a name but no concept of fields.

Hence the decision was to do the "safe" thing and deferr this functionality until later. But you're not the first one asking for it, and maybe this is a situation in which a 90% working feature that covers some common use cases but has some pitfalls is better than nothing.

@samuelcolvin any thoughts? It would be pretty simple to change this.

**Comment by zyv** [comment]
> Hence the decision was to do the "safe" thing and deferr this functionality until later. But you're not the first one asking for it, and maybe this is a situation in which a 90% working feature that covers some common use cases but has some pitfalls is better than nothing.
> 
> @samuelcolvin any thoughts? It would be pretty simple to change this.

Hi @adriangb,

Thanks a lot for the explanation! I think I understand your concerns better now... Our use case is as follows:

```python
class FieldType(BaseModel):
    type: Literal["FieldType"] = Field(alias="$type", default="FieldType")
    id: Optional[str] = None

class CustomField(BaseModel):
    type: Literal["CustomField"] = Field(alias="$type", default="CustomField")
    field_type: Optional[FieldType] = Field(alias="fieldType", default=None)

class ProjectCustomField(BaseModel):
    field: Optional[CustomField] = None

class IssueCustomField(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    project_custom_field: Optional[ProjectCustomFieldType] = Field(alias="projectCustomField", default=None)
    type: Literal["SimpleIssueCustomField"] = Field(alias="$type", default="SimpleIssueCustomField")
    value: Optional[YouTrackDatetime | StrictStr | StrictInt | StrictFloat] = None
    value_validator = field_validator("value")(validate_youtrack_datetime)  # since type-bound validator with `Annotated` can't access model data
```

In `YouTrackDatetime` we need to access the information from `project_custom_field.field.field_type.id` to decide whether this is really a `datetime` expressed as an `int` or maybe it's an `int`.

I guess I get the argument, that type-bound validators could be expected operate only on the data about their own fields and not the entire model, the model bound validators could access model data though... and I'm not sure if there is a nice way to express on type level that this type can only be used if the model has another field of another type, which the validation depends upon.

But in the end, it's depends on how you code the validation. It should just raise `RuntimeError` exception if the type is used wrongly, and if you allow re-use of bound validator functions, you could also just do it wrongly and attach it to a model, which doesn't fulfill it's usage pre-requisites.

If you ask me, I wouldn't artificially limit stuff for bound validators if you already allow it otherwise, but in the end it's a difficult decision without obvious "right way" for me. For now we will settle on the solution above for re-use.

Thanks for considering!

**Comment by zyv** [comment]
I think this is implemented now after `FieldValidationInfo` has been deprecated. At least is seems to be working for us... @adriangb ?

**Comment by adriangb** [comment]
Yes indeed

**Comment by zyv** [comment]
Thank you!
