### ISSUE TITLE
from pydantic.generics import GenericModel fails with ImportError: cannot import name 'GenericModel'

### ISSUE THREAD

**Issue by gotofritz** [pydantic/pydantic#6733]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using pydantic 2.0.3 with python 3.10.8. I have cleared the pip / pyenv cache 

```
>>> from pydantic.generics import GenericModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'GenericModel' from 'pydantic.generics' (./venv/lib/python3.10/site-packages/pydantic/generics.py)
```

Have generics been deprecated? I couldn't find any reference in the changelog. Thanks

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /__a__/__path__/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Jan 19 2023, 12:04:55) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by adriangb** [comment]
You can just use `BaseModel` now, there is no more need for `GenericModel`.

**Comment by gotofritz** [comment]
Yes, I worked it out in the ends, thanks, but it's not documented anywhere as far as I can tell

**Comment by ZipFile** [comment]
Shouldn't it be added to [MOVED_IN_V2](https://github.com/pydantic/pydantic/blob/a3f71c2f836d2c3587b34ae742434ea8541791bf/pydantic/_migration.py#L8C1-L8C12) then?

**Comment by adriangb** [comment]
Yeah I think it should
