### ISSUE TITLE
Can not use ValidataionError __init__ method

### ISSUE THREAD

**Issue by so1n** [pydantic/pydantic#6734]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Can not use ValidataionError __init__ method

### Example Code

```Python
>>> from pydantic import ValidationError
>>> ValidationError([])
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: No constructor defined
>>> from pydantic import ValidationError
>>>ValidationError(errors=[])
Traceback (most recent call last):
  File "/usr/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: No constructor defined
>>> from pydantic import ValidationError
>>> dir(ValidationError)
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'error_count', 'errors', 'from_exception_data', 'json', 'title', 'with_traceback']
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: .venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Nov  1 2022, 10:27:39)  [GCC 8.3.0]
                     platform: Linux-5.15.77-amd64-desktop-x86_64-with-Deepin-20.9-apricot
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by adriangb** [comment]
There is no `__init__`. You’ll have to use `from_err_details`

**Comment by so1n** [comment]
Thanks  for your reply, but I can't find the `from_err_details` method. Is it the `from_exception_data` method?

> ```python
> >>> from pydantic import ValidationError
> >>> dir(ValidationError)
> ['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', 'args', 'error_count', 'errors', 'from_exception_data', 'json', 'title', 'with_traceback']
> ```

**Comment by dineshbvadhia** [comment]
Hello. I get the same error (with V2 but not with V1) and don't understand what the fix is. Here is a sample code snippet:

```
from fastapi.exceptions import HTTPException, RequestValidationError
from pydantic import ValidationError

try:
    this = something('odd')
except:
    raise RequestValidationError(errors=[ValidationError(ValueError('Invalid oddness'), 'odd')])

TypeError: No constructor defined
```
What is the solution?

**Comment by adriangb** [comment]
Use `ValidationError.from_err_details`.

**Comment by dineshbvadhia** [comment]
@adriangb I think you meant to say use ValidationError.from_exception_data which gives a TypeError :(
```
from fastapi.exceptions import HTTPException, RequestValidationError
from pydantic import ValidationError

try:
    this = something('odd')
except:
    raise RequestValidationError(errors=[ValidationError.from_exception_data(ValueError('Invalid oddness'), 'odd')])

TypeError: argument 'line_errors': 'str' object cannot be converted to 'PyList'
```

**Comment by Kludex** [comment]
@dineshbvadhia Eh... I recommend setting up any kind of type checker on your setup.

The API documentation may help you: https://docs.pydantic.dev/latest/api/pydantic_core/#pydantic_core._pydantic_core.ValidationError.from_exception_data

**Comment by somnam** [comment]
I'm facing this error (`TypeError: No constructor defined`) when retrieving exception from a Celery task. The error is raised when a pickled `ValidataionError` is being unpickled.  I've found this issue in `pydantic-core` repo:
https://github.com/pydantic/pydantic-core/issues/959
Is it possible to have `__init__` method on `ValidataionError`?
