### ISSUE TITLE
TzInfo type doesn't provide proper dst

### ISSUE THREAD

**Issue by daAnis** [pydantic/pydantic#6735]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I've updated Pydantic from 1.10.11 to 2.0.3 and faced an error when trying to get a datetime object with the same timezone as Pydantic validated one.

### Example Code

```Python
from datetime import datetime
from pydantic import BaseModel

class MyModel(BaseModel):
    dt: datetime

my_model = MyModel(dt='2023-01-01T00:00:00.000000+01:00')
print(my_model)

now = datetime.now(tz = my_model.dt.tzinfo)
print(now)


Result:

dt=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=TzInfo(+01:00))
Traceback (most recent call last):
  File "/Users/me/Documents/test.py", line 10, in <module>
    now = datetime.now(tz = my_model.dt.tzinfo)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: fromutc: non-None dst() result required
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/me/Documents/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.2.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by hramezani** [comment]
@daAnis Thanks for reporting this 🙏 

The `tzinfo` type is `pydantic_core._pydantic_core.TzInfo` while `datetime.now` needs `tz` to be [datetime.timezone](https://docs.python.org/3/library/datetime.html#timezone-objects). You can make `datetime.timzone` like:

```py
from datetime import datetime, timezone
from pydantic import BaseModel

class MyModel(BaseModel):
    dt: datetime

my_model = MyModel(dt='2023-01-01T00:00:00.000000+01:00')

print(my_model.dt.tzinfo, type(my_model.dt.tzinfo))

now = datetime.now(tz = timezone(my_model.dt.tzinfo.utcoffset(my_model.dt)))
print(now)
```

**Comment by dmontagu** [comment]
@samuelcolvin Can I ask why we use a subclass of `datetime.tzinfo` in pydantic-core instead of a subclass of `datetime.timezone`? It seems that might fix this issue if it works:

```python
from datetime import datetime, timezone, timedelta
from pydantic import BaseModel


class MyModel(BaseModel):
    dt: datetime


my_model = MyModel(dt='2023-01-01T00:00:00.000000+01:00')

# Replace with a timestamp that uses a datetime.timezone rather than a datetime.TzInfo:
offset: timedelta = my_model.dt.tzinfo.utcoffset(my_model.dt)
fixed_tz = timezone(offset)
fixed_dt = my_model.dt.replace(tzinfo=fixed_tz)
my_model.dt = fixed_dt

# Works properly:
print(datetime.now(tz=my_model.dt.tzinfo))
#> 2023-07-26 20:17:42.553876+01:00
```

More generally I think this isn't the first reported issue related to the use of `TzInfo`. But I haven't looked into the speedate/pydantic-core side or even the differences between `datetime.timezone` and `datetime.tzinfo`, maybe it's more complicated than I'm giving it credit for.

**Comment by daAnis** [comment]
@hramezani, @dmontagu, thank you for your replies, I just thought it would be great to describe TzInfo type in docs and mention it in the migration guide.
