### ISSUE TITLE
No more parse_raw_as in Pydantic v2

### ISSUE THREAD

**Issue by remidebette** [pydantic/pydantic#6757]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Methods such as `parse_*` have been removed in pydantic v2.
The motivation for this change is that `<class>.model_validate()` has a similar behavior.

But one use case is not covered anymore, `parse_raw_as` when the type is not a Pydantic BaseModel.

For example, I don't know how to do this in v2

```python

from pydantic import BaseModel, parse_raw_as

class Env(BaseModel):
    name: str
    value: str

EnvList = list[Env]

my_list = parse_raw_as(EnvList, [{"name": "key1", "value": "value1"},{"name": "key2", "value": "value2"}])

```

Is there a function for this?

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by a5r0n** [comment]
in v1, this simple work:
```python
>>> pydantic.parse_raw_as('List[str]', '[1,2]')
['1', '2']
```

Anyway to get the same results with v2?

**Comment by adriangb** [comment]
`TypeAdapter(list[int]).validate_json(‘[1]`)`
