### ISSUE TITLE
model_dump_json removes (all) irrelevant milliseconds.

### ISSUE THREAD

**Issue by Qlas** [pydantic/pydantic#6761]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`model_dump_json` removes (all) irrelevant milliseconds. This is a bit annoying in testing, because I can't easily compare dicts.

- When I set 0 as the last digit of milliseconds, it will be removed
```python
class TestModel(BaseModel):
    created_at: datetime


model = TestModel(created_at="2023-07-19T19:45:32.712890")

print(model.model_dump_json()) # {"created_at":"2023-07-19T19:45:32.71289"}
```

- With the last digit other than 0 it will work perfectly correctly
```python
class TestModel(BaseModel):
    created_at: datetime


model = TestModel(created_at="2023-07-19T19:45:32.712801")

print(model.model_dump_json()) # {"created_at":"2023-07-19T19:45:32.712801"}

```

- In pydantic 1.x it gives the same results in both cases:
```python
class TestModel(BaseModel):
    created_at: datetime


model = TestModel(created_at="2023-07-19T19:45:32.712890")

print(model.json()) # {"created_at": "2023-07-19T19:45:32.712890"}

```
- datetime isoformat returns the same as pydantic 1.x
```python
date = datetime.strptime("2023-07-19T19:45:32.712890", "%Y-%m-%dT%H:%M:%S.%f")

print(date.isoformat()) # 2023-07-19T19:45:32.712890

```

### Example Code

```Python
from datetime import datetime

from pydantic import BaseModel


class TestModel(BaseModel):
    created_at: datetime


model = TestModel(created_at="2023-07-19T19:45:32.712890")

print(model.model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/qlass/.cache/pypoetry/virtualenvs/test-ejgCnITw-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, May 30 2023, 21:14:46) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
                     platform: Linux-6.3.6-200.fc38.x86_64-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by Qlas** [comment]
Thanks for the solution, but it looks like an ugly workaround (I will use it for now). Can I consider the default datetime serialization as bugged, or is this the expected behavior?

**Comment by samuelcolvin** [comment]
https://github.com/pydantic/pydantic-core/blob/608db7ba72e836380a39c716d651a06c745eb2cd/src/serializers/type_serializers/datetime_etc.rs#L15

We use [speedate](https://github.com/pydantic/speedate) for serialising.

I'd be happy change the logic to match python `isoformat`, but since what we have is rfc3339/iso8601 compliant, I wouldn't say this is a "bug".

**Comment by samuelcolvin** [comment]
PR welcome to fix this in speedate.

**Comment by albertodonato** [comment]
Hopefully the above PR should help

**Comment by Lawouach** [comment]
> I'd be happy change the logic to match python isoformat, but since what we have is rfc3339/iso8601 compliant, I wouldn't say this is a "bug".

Well @samuelcolvin I can appreciate that but then again this is a Python-targetting library and I think being aligned with what the `datetime` module produces by default is also a positive standard to follow, no? Or at least, maybe this should be clearly documented.

**Comment by davidhewitt** [comment]
As a follow-up to summarise for readers here, as of Pydantic 2.4 datetimes will emit milliseconds to 6 digits whenever you have milliseconds.

If you need to _always_ emit milliseconds, try the following:

```python
from typing import Annotated, Any, Type, Optional
from pydantic import GetCoreSchemaHandler
from pydantic_core import core_schema
import datetime

class FormatMillis:

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: Type[Any], handler: GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        schema = handler(source)
        schema['serialization'] = core_schema.format_ser_schema('%Y-%m-%d:%H:%M:%S.%f')
        return schema
    

class TestModel(BaseModel):
    created_at: Annotated[datetime.datetime, FormatMillis]

# or make a type alias
DatetimeFormatMillis = Annotated[datetime.datetime, FormatMillis]

class TestModel(BaseModel):
    created_at: Optional[DatetimeFormatMillis]


TestModel(created_at=datetime.datetime(2021, 1, 1)).model_dump_json()
#> '{"created_at":"2021-01-01:00:00:00.000000"}'
```
