### ISSUE TITLE
Support plugins

### ISSUE THREAD

**Issue by Kludex** [pydantic/pydantic#6765]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We want to be able to _know_ the "what", "when", and "how" things happens internally in Pydantic, and be able to perform some action according to it.

For that, we thought about a plugin system, using [entry points](https://packaging.python.org/en/latest/specifications/entry-points/), that will allow external packages (plugins) to _intercept_ events in Pydantic, like validation and schema creation.

### User side

Let's see an example on how this would look like for the Pydantic user's side:

```py
from pydantic import BaseModel

class Model(BaseModel, observe="all")
    a: int

Model.model_validate({"a": 1})
```

In this case, we allow `Model` to receive another class parameter called `observe`. On its hand, given this parameter, Pydantic will check if there's a plugin installed that uses this parameter, and the plugin will be able to execute the logic it wants, wrapping Pydantic events (like validation, and schema creation, as mentioned above).

### Pydantic side

On the Pydantic's side, we'll introspect the packages installed, looking for an entry point, similar as to what [flake8](https://flake8.pycqa.org/en/latest/plugin-development/index.html) and [pytest](https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html) are doing. If the entry point is found, we'll register that in a plugin list, and whenever an event happens, we'll check if the plugin wants to do something about it.

### Plugin side

On the plugin side, I imagine the implementation as simple as a callable. Let's see the minimal possible example:

```py
from typing import Any
from pydantic.plugin import Plugin, OnValidatePython


def enter(
    cls: type[Any],  # type: ignore
    json_data: str | bytes | bytearray,
    *,
    strict: bool | None = None,
    context: dict[str, Any] | None = None,
) -> None:
    print(cls)


plugin = Plugin(on_validate_python=OnValidatePython(enter=enter))
```

Also, they'll need to add the entry point on the `pyproject.toml`:

```toml
[project.entry-points."pydantic"]
observe = "pydantic_sdk.plugin:plugin"
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @davidhewitt

**Comment by jd-solanki** [comment]
I guess this will help mark the fields optional, Linking: https://github.com/pydantic/pydantic/issues/3120

**Comment by jd-solanki** [comment]
@Kludex It looks interesting but I didn't see much plugins can you please share few usecases?

**Comment by samuelcolvin** [comment]
We're building stuff with plugins at Pydantic, you'll find out more soon. 😉
