### ISSUE TITLE
Pydantic V2 fails to parse PostgresDSN with `#` in the password.

### ISSUE THREAD

**Issue by Mhs-220** [pydantic/pydantic#6773]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

I encountered a problem with the PostgresDSN type. If the password contains a `#`, it gives rise to a validation error (note that there is no issue if the `#` is in the username):

Error Message:
```
ValidationError: 1 validation error for Setting
pg
  Input should be a valid URL, invalid port number [type=url_parsing, input_value='postgres://postgres:Pass...0.0.1:5441/postgres', input_type=str]
    For further information visit https://errors.pydantic.dev/2.0.3/v/url_parsing
```

### Example Code

```Python
from pydantic import PostgresDsn
from pydantic_settings import BaseSettings

class Setting(BaseSettings):
    pg: PostgresDsn

Setting(pg="postgres://postgres:PasswordWith#Char@127.0.0.1:5441/postgres")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/mhs/EthicaDataProjects/general/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
                     platform: Linux-6.1.38-1-MANJARO-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by hramezani** [comment]
Hi @Mhs-220,

Thanks for reporting this bug 🙏 

I can confirm the bug.

**Comment by Tishka17** [comment]
Souldn't `#` symbol be escaped when it is a part of URI?
I see it in the list of "excluded" symbols as it is used as a delimeter in URIs
https://www.rfc-editor.org/rfc/rfc2396#section-2.4.3

**Comment by hramezani** [comment]
Based on [reply on  rust-url issue](https://github.com/servo/rust-url/issues/860#issuecomment-1644149655), seems it is by design and you need to escape the password
