### ISSUE TITLE
MongoDsn injects `port` value on `mongodb+srv://` URIs

### ISSUE THREAD

**Issue by heissonwillen** [pydantic/pydantic#6774]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

MongoDB URIs using the format `mongodb+srv://` [shouldn't contain a port number](https://www.mongodb.com/docs/manual/reference/connection-string/#dns-seed-list-connection-format). 

The default `MongoDsn` type automatically injects a `port` value. I'm working that around using my own `MongoDsn` type:
```python
MongoDsn = Annotated[
    MultiHostUrl,
    UrlConstraints(
        allowed_schemes=["mongodb", "mongodb+srv"],
    ),
]
```

It would be great to have Pydantic not injecting a value that will cause a database connection issue.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/my-user/Projects/my-project/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
Could you provide a more complete code example showing what is happening that you don't like, and what you want the behavior to be? I'm not familiar with the type involved, but I suspect there is at least an easy workaround, it would just help to see how you are running into the problem.

**Comment by dmontagu** [comment]
@heissonwillen does https://github.com/pydantic/pydantic/issues/6774 fix it for you?

**Comment by heissonwillen** [comment]
Yep! Thanks for taking a look! :)
