### ISSUE TITLE
Enable positional args for base models

### ISSUE THREAD

**Issue by GugelRobin** [pydantic/pydantic#6792]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When inheriting from `BaseModel` pydantic doesn't support passing field values as positional arguments to `__init__`.
In V1 there was a problem with non-annotated fields and reasoning about their order - in pydantic V2 fields must have an annotation so that problem doesn't occur no more.
I think passing field values as keyword arguments per default is reasonable, but I'd like to be able to enable passing them positionally.

My use-case are classes with lots of optional/default generated fields and 1-3 required, aka 'defining' fields. E.g. there's an IpAddress class where you may specify the MacAddress this IP resolves to, the network it belongs to, labels, etc... The 'value' field of the IP is the only required field. Being required to call `IpAddress(value=...)` instead being able to pass 'value' positionally is unwanted.

Using a custom `__init__` leads to worse error-messages for validation of unions of classes with common ancestors as pydantic needs to specifically call that custom `__init__`. I usually only got error messages for the first option of the union (my usecase is that I want to know if there's problem with extra-fields that aren't allowed and if so branch off)

I suggest checking the `kw_only` parameter for fields to see whether they should be allowed to be passed positionally.
A quick test revealed that the order of `model_fields` is consistent with how pyright would order the fields if it were a dataclass. 

For my code-base I've written a decorator which does just that and fools pydantic into thinking `__init__` wasn't overwritten as support for positional args is only reasonable for constructors in my opinion and not for parsing.

```python

def enable_positional_fields(for_model: type[_BaseModelT]) -> type[_BaseModelT]:

    if getattr(for_model, "__positional_args_enabled__", False):
        return for_model

    original_init = for_model.__init__
    _cache = {}
    def transform_positional_args_to_kwargs(__pydantic_self__: _BaseModelT, *args, **kwargs):
        if type(__pydantic_self__) not in _cache:
            _cache[type(__pydantic_self__)] = [
                name for name, value in __pydantic_self__.model_fields.items()
                if value.kw_only is False
            ]
        positional_fields = _cache[type(__pydantic_self__)]
        for name, value in zip(positional_fields, args):
            if name in kwargs:
                raise TypeError(
                    f"{for_model.__name__}.__init__ got multiple values for argument {name!r}"
                )
            kwargs[name] = value
        try:
            # `__tracebackhide__` tells pytest and other tools to omit this from tracebacks
            __tracebackhide__ = True  # pylint: disable=unused-variable
            original_init(__pydantic_self__, *args[len(positional_fields) :], **kwargs)
        except (TypeError, ValueError) as error:
            if len(positional_fields) > 0:
                error.add_note(
                    f"{type(__pydantic_self__).__name__!r} accepts the following fields as "
                    f"positional arguments (in that order): {positional_fields}"
                )
            raise error

    if not getattr(BaseModel.__init__, "__pydantic_base_init__", False):
        warnings.warn(
            "Pydantic changed how it determines whether a custom __init__ is defined. "
            "Usages of Unions of classes with @enable_custom_fields may have worse error reports. "
        )
    if getattr(original_init, "__pydantic_base_init__", False):
        transform_positional_args_to_kwargs.__pydantic_base_init__ = True
    for_model.__positional_args_enabled__ = True  # type: ignore
    for_model.__init__ = transform_positional_args_to_kwargs  # type: ignore
    return for_model
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @lig

**Comment by Viicos** [comment]
Similar request: https://github.com/pydantic/pydantic/discussions/6510

**Comment by lig** [comment]
There are no plans on implementing positional arguments support in `BaseModel.__init__`.

However, if you have a single attribute in a model you can use `RootModel` for simplifying the code.

```py
    from pydantic import RootModel

    class Model(RootModel):
        root: int

    m = Model(42)
    assert m.model_dump() == 42
```

See the [RootModel docs](https://docs.pydantic.dev/latest/api/root_model/) for details.

**Comment by HDembinski** [comment]
@lig What's the reason for rejecting this feature? Like OP, I am fine with the default, but why not add a ModelConfig to allow passing positional arguments. I've encountered that problem several times now in different libraries. There is always one BaseModel where passing positional arguments would be useful.

If, for instance, the BaseModel is something simple, like a fraction (not really my use-case, but for illustration).

```py
class Fraction(BaseModel):
    numerator: int
    denominator: int
```

In my particular use-case, I have a BaseModel that represents a document reference. Sometimes that reference points to a specific section in the document.

```py
class DocumentCode(BaseModel):
    @field_validator("code")
    @classmethod
    def validate_code(cls, v):
        if not isinstance(v, str) or not re.match(r"[a-zA-Z0-9]+\.\d+", v):
            exc = f"{v!r} is an invalid code"
            raise ValueError(exc)
        return v

    code: str
    section: PositiveInt | None = None
```

Would be great to use that in generic code which parses a list of text into a list[Any], where Any could be str, int, DocumentCode. For that to work, DocumentCode would have to callable as DocumentCode("ABC.XYZ").
