### ISSUE TITLE
Incompatibility of deprecated `.json` method not well documented

### ISSUE THREAD

**Issue by dhdaines** [pydantic/pydantic#6800]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Previously it was possible to pass the `ensure_ascii=False` argument to the `.json()` method to get JSON in UTF-8 instead of hideously ugly `\uNNN` escapes everywhere.  Now I get this unhelpful error:
```
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
```
The workaround is to switch to the new `model_dump_json` method which seems to output UTF-8 by default, but it would be nice if at least you could document this somewhere.

### Example Code

```Python
from pydantic import BaseModel
class Chose(BaseModel):
    truc: str
fafouin = Chose(truc="Allô! 你好！привет!")
print(fafouin.json(indent=2, ensure_ascii=False))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.2
        pydantic-core version: 2.1.2 release build profile
                 install path: /home/dhd/work/vdsa/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
                     platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by dhdaines** [comment]
Ah! You're right - I was confused about which version of Pydantic was actually installed in my venv.

On the other hand, the documentation is misleading, because `.json()` is a bit more than deprecated - frequently used arguments like `indent` and `ensure_ascii` now simply crash your program.  And this is not mentioned in the documentation

So I guess there are two solutions:

1. Update the migration guide to make clear that you can't pass any arguments to `.json()` anymore
2. Make sure `bump-pydantic` will update code to use `.model_dump_json()` instead of just crashing

**Comment by cirezd** [comment]
I agree, this should be mentioned somewhere in the documentation or part of the warning even.

**Comment by liebkne** [comment]
Killed my day.
