### ISSUE TITLE
Method to annotate `__get_pydantic_core_schema__` on arbitrary classes/types

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#6801]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description
Libraries such as NumPy, Pandas, Trimesh, Open3D, etc offer many functionalities; however, they come with their own arbitrary types. Having the will to work with them on Pydantic, and doing it right, my goal was to add Pyndatic support so that I wouldn't have to set `allow_arbitrary_types` to `True`.

I couldn't find a way to annotate my way to having Pydantic full support. A numpy array annotation looks like this, work in progress from `pydantic-numpy` for V2:
```python
def array_origin_and_data_type_validation_typing(target_datatype: DataType, dimensions: Optional[int] = None):
    return Annotated[
        Union[
            Annotated[
                np.ndarray[int_to_dim_type[dimensions] if dimensions else Any, np.dtype[target_datatype]],
                BeforeValidator(ensure_array_likeness),
            ],
            Annotated[FilePath, Strict(), AfterValidator(read_and_verify_numpy_file)],
        ],
        AfterValidator(validate_array_data_type(target_data_type=target_datatype)),
        numpy_array_serializer,
    ]
```
According to Pydantic, the output is still an arbitrary type, in my eyes, it isn't. Maybe I am missing something :)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by adriangb** [comment]
You'll want either https://docs.pydantic.dev/latest/usage/types/custom/#handling-third-party-types or #6737

**Comment by adriangb** [comment]
Sorry missed the details. What do you mean by “the output is still an arbitrary type”? That it requires the arbitrary types flag?

**Comment by adriangb** [comment]
Your example looks like it should work but since you posted the issue I'm guessing it doesn't. Can you give me the rest of the details in a MRE so I can test it? It would also help if you can remove any of the unions or complexity that are not causing the issue.

**Comment by caniko** [comment]
I got it working, thanks! Will send the repo soon! :)

**Comment by caniko** [comment]
Done! https://github.com/caniko/pydantic-numpy
