### ISSUE TITLE
Additional instance_of validation error (strict=False)

### ISSUE THREAD

**Issue by lord-haffi** [pydantic/pydantic#6805]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, when upgrading pydantic from 2.0.2 to 2.0.3 I get different behaviour in my unittest (example code below). Somehow, when provoking an error by using an input which is not convertable into `Decimal`, the validation raises now 2 `ValidationError`s (instead of 1):
```python
2 validation errors for Price
value.is-instance[Decimal]
  Input should be an instance of Decimal [type=is_instance_of, input_value='lululululu', input_type=str]
    For further information visit https://errors.pydantic.dev/2.0.3/v/is_instance_of
value.function-after[to_decimal(), union[float,int,constrained-str]]
  Input should be a valid decimal [type=decimal_parsing, input_value='lululululu', input_type=str]
```
Here, the first error is new in v2.0.3 (type=is_instance_of). I explicitly checked that my model is `strict=False`. When I use something like `Price(value="2.3")` this is executed without a problem. Therefore, this (now additional) error doesn't make that much sense to me.
Is this a bug or intended? And if it is intended, why?

### Example Code

```Python
import pytest
from pydantic import BaseModel, ValidationError

class Price(BaseModel):
    value: Decimal


def test_wrong_datatype(self) -> None:
    with pytest.raises(ValidationError) as excinfo:
        _ = Price(value="lululululu")  # type: ignore[arg-type]

    assert "1 validation error" in str(excinfo.value)
    assert "value" in str(excinfo.value)
    assert "type=decimal_parsing" in str(excinfo.value)
```

### Python, Pydantic & OS Version

```Text
Windows 11 (but appears on Unix as well), Python v3.11, pydantic v2.0.3
```

Selected Assignee: @hramezani

**Comment by adriangb** [comment]
This is expected. Realistically that should never be in the error message in the first place but generating clean error messages for complex custom validations (which is what Decimal is) is something we still need to work on.

For now I would consider this part (the error loc) of Pydantic an implementation detail.
