### ISSUE TITLE
`__post_init__` executes before `@model_validator(mode="after")`

### ISSUE THREAD

**Issue by Expurple** [pydantic/pydantic#6806]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Disclaimer: this may be a documentation issue and not a bug. But it's still an issue in that case.

### Expected behavior

When using a Pydantic `dataclass`, I expected to see the behavior documented in [Dataclasses documentation](https://docs.pydantic.dev/latest/usage/dataclasses/#initialization-hooks) and [migration guide](https://docs.pydantic.dev/latest/migration/#changes-to-dataclasses):

>  The `__post_init__` in Pydantic dataclasses is called after validation, rather than before.

> The `__post_init__` in Pydantic dataclasses will now be called after validation, rather than before. As a result, the `__post_init_post_parse__` method would have become redundant, so has been removed.

### Actual behavior

As the title says,  `__post_init__` executes before `@model_validator(mode="after")`. See the code example.

Interestingly, `__post_init_post_parse__` works as expected. It hasn't been removed and it's definitely not redundant yet.

### Additional info

[Documentation for `functional_validators`](https://docs.pydantic.dev/latest/api/functional_validators/#pydantic.functional_validators.AfterValidator) doesn't mention `__post_init__` or `__post_init_post_parse__`, it only states that

> validation should be applied **after** the inner validation logic.

Also, [documentation for `dataclasses`](https://docs.pydantic.dev/latest/usage/dataclasses/#difference-with-stdlib-dataclasses) recommends:

> When substituting usage of `dataclasses.dataclass` with `pydantic.dataclasses.dataclass`, it is recommended to move the code executed in the `__post_init__` to methods decorated with `model_validator`.

This is a valid workaround, but I wonder why is this the recommened way. IMO, validators should not mutate the object and `__post_init__` is a more idiomatic choice.

### Example Code

```Python
from pydantic import model_validator
from pydantic.dataclasses import dataclass

@dataclass
class ExampleDataclass:
    a: int
    b: int

    @model_validator(mode="after")
    def _validate_relationship_between_a_and_b(self) -> "ExampleDataclass":
        # The nature of the check doesn't matter.
        if self.a == self.b:
            raise ValueError("invalid combination of a and b")
        return self

    def __post_init__(self) -> None:
        # The nature of the computation doesn't matter,
        # but it raises an error with invalid combinations of a and b.
        # In this case, ZeroDivisionError.
        self._c = 42 / (self.a - self.b)

# Blows up with ZeroDivisionError instead of pydantic.ValidationError.
#
# If I rename __post_init__ to __post_init_post_parse__,
# raises pydantic.ValidationError as expected.
ExampleDataclass(1, 1)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/dima/code/games/smawg/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, May 30 2023, 17:45:26) [GCC 12.2.0]
                     platform: Linux-6.2.0-25-generic-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by Expurple** [comment]
@hramezani

> Based on the example above, the order is `before` validators, validation on fields, `__post_init__`, `after` validator.

No, this is not clear from the example. The example doesn't show the expected order of prints anywhere. I can run it locally and see the *actual* order of messages, but the actual order may be buggy, which is why I created this issue.
If the example contained something like this at the bottom, you'd be correct:

```python
user = User(**{'birth': {'year': 1995, 'month': 3, 'day': 2}})
#> ArgsKwargs((), {'birth': {'year': 1995, 'month': 3, 'day': 2}})
#> Birth(year=1995, month=3, day=2)
#> User(birth=Birth(year=1995, month=3, day=2))
```

Also, regardless of the example, the documentation should clearly state the 4 steps as you listed them, instead of

> The `__post_init__` in Pydantic dataclasses is called *after* validation, rather than before.

**Comment by hramezani** [comment]
@Expurple agree. I will create a PR to improve it.

**Comment by Expurple** [comment]
Thanks. This PR solves the issue with ambiguous code example, but what about the bits from documentation that I quoted in the original post? IMO, these are still ambiguous. And no rationale is given when recommending `@model_validator` over `__post_init__`

**Comment by hramezani** [comment]
@Expurple Thanks for pointing this.

I've removed that section because I think it doesn't make sense now

**Comment by Expurple** [comment]
@Kludex, thanks for your activity under the PR.

@hramezani Looks good to me now, I agree that the issue can be closed. Migration guide still unprecisely claims that `__post_init__` is called after validation, but it's not the main source of truth for dataclasses and the claim is mostly true, so I'm fine with that.
