### ISSUE TITLE
MaxLen annotation validator for custom sequences is incorrect

### ISSUE THREAD

**Issue by ImogenBits** [pydantic/pydantic#6808]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using an `annotated_type.MaxLen` annotation with a custom sequence it rejects sequences that have precisely the maximum length when it should only reject if they are greater.

I'm pretty sure this is because [the validator function](https://github.com/pydantic/pydantic/blob/6ef959fa69d1ab1aedf2778b6c8f452e0fee37b6/pydantic/_internal/_validators.py#L266C27-L266C27) used for custom sequences currently checks for strict inequality rather than less or equal.

### Example Code

```Python
from typing import Annotated
from annotated_types import MaxLen

from pydantic import BaseModel

class MySequence(BaseModel):

    inner: list[int]

    def __len__(self):
        return len(self.inner)

    def __getitem__(self, __key: int) -> int:
        return self.inner[__key]


class MyModel(BaseModel):
    seq: Annotated[MySequence, MaxLen(3)]


MyModel.model_validate({"seq": {"inner": [1, 2, 3]}})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
pydantic-core version: 2.3.0 release build profile
python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
optional deps. installed: ['typing-extensions'];
```

Selected Assignee: @davidhewitt

**Comment by hramezani** [comment]
Thanks @ImogenBits for reporting this 🙏 

Would you like to open a PR? Otherwise I will fix it.

**Comment by ImogenBits** [comment]
I made a PR
