### ISSUE TITLE
str(PrivateAttr) is default=value instead of just value in contrast to just value in v1

### ISSUE THREAD

**Issue by sla-te** [pydantic/pydantic#6818]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Is this intended new functionality or potentially a bug?

### Example Code

```Python
from pydantic import BaseModel

class Example(BaseModel):
    _my_private_attr: str = PrivateAttr(default="private_value")

e = Example()
print(e._my_private_attr)
>>> default='private_value'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /home/core/PycharmProjects/ecdb/pipelines/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 29 2023, 14:47:56) [GCC 13.1.1 20230429]
                     platform: Linux-6.4.4-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
I've tried to run your posted example but couldn't understand what is the problem. it prints nothing.

**Comment by hramezani** [comment]
I tested your updated snippet and the output is `private_value` not `default=private_value`

**Comment by hramezani** [comment]
@sla-te I am still cannot reproduce the behavior by you final updated example

**Comment by hramezani** [comment]
Ok, got it.

You shouldn't mix V1 and V2 together. 

`from pydantic import BaseModel` import the `BaseModel` from `V2` and you shouldn't use `PrivateAttr` from `V1`
