### ISSUE TITLE
Support of parsing strings with non-decimal integers

### ISSUE THREAD

**Issue by Bobronium** [pydantic/pydantic#682]
# Feature Request
I just realized that pydantic can't properly parse strings which contain non-decimal numbers:

```py
from pydantic import BaseModel

class M(BaseModel):
    b: int
    f: int

bin_number = '0b10'
hex_number = '0xFF'
print(int(hex_number, 16) is 255)  # True

M(b=bin_number, f=hex_number)
'''
Traceback (most recent call last):
    ...
    raise ValidationError(errors)
pydantic.error_wrappers.ValidationError: 1 validation error
a
  value is not a valid integer (type=type_error.integer)
'''
```
# Proposed solution
I don't know how to implement this yet, but this what first came in my mind:
```py
from pydantic import BaseModel, BinInt, HexInt

class M(BaseModel):
    b: BinInt
    f: HexInt

```
And then I thought what if we could generate type for integer with any base at runtime just like this:
```py
from pydantic import BaseModel, Int

class M(BaseModel):
    b: Int(2)
    f: Int(16)
# or
    b: Int[2]
    f: Int[16]

print(M(b='11', f='0xFF').f)
# Int(base=16): 0xFF (255)
```
What do you think about such feature?

**Comment by dmontagu** [comment]
I think rather than creating a new int type, this could be supported by making use of the following feature:
```python
print(int('0b100', base=0))  # 4
print(int('100', base=0))  # 100
print(int('0x100', base=0))  # 256
```

This would probably be a cheap extension to the existing int parser.

**Comment by samuelcolvin** [comment]
see https://github.com/samuelcolvin/pydantic/pull/683#discussion_r306730304

Personally I'd rather we did something like `IntBase[16]` etc.

**Comment by MrMrRobat** [comment]
Thanks for quick response @dmontagu.

Personally, I agree with @samuelcolvin here. I guess we don't want to slow down or break existing decimal int parsing. 

Also, it would be nice to have base-aware non-decimal ints, so they can be represented in self base (don't know how implement this yet):
> `print(M(b='11', f='0xFF').f)`
> `# Int(base=16): 0xFF (255)`

**Comment by dmontagu** [comment]
From @samuelcolvin's comment on #683

> my only concern is int('0780') (or -0780) which was previously okay but would now be illegal.

I think it would be a good idea to add these as test cases for the int parser in a PR for this feature -- my (admittedly slow 😬) modification that would have broken them did not fail any tests.

**Comment by samuelcolvin** [comment]
yes, I just happened to think of it when reading the docs on `int()`.

**Comment by arthurazs** [comment]
Hi! Just so I know if I'm following the conventions. I'd solve this issue by using custom data types?

Example:
```python
class HexInt(int):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, value):
        if isinstance(value, str):
            return cls(value, base=16)
        elif isinstance(value, int):
            return cls(value)
        raise TypeError('int or string required')

class Withdraw(pydantic.BaseModel):
    tx_id: HexInt
```

**Comment by Bobronium** [comment]
@arthurazs, while I don't see anything "illegal" here, this approach would mean that for each base, a separate type is needed.

So if I had to choose between `HexIng` and `IntBase[16]`, I personally would go with the later, since it covers all bases at once.

If that's something you crave and agree with my point above, but not sure how to implement it that way, I'm happy to help/collaborate on that!

Brainfart: it would also be nice for for custom type to retain information about its base.

**Comment by arthurazs** [comment]
Thanks for the response @Bobronium 

For now, `HexInt` is enough for me. But I understand your point, and I can see myself needing it someday.

I'm new to typing/pydantic; I tried figuring this new solution out but could not. Can you point me to some docs or keywords that might help me code `IntBase[16]`?

**Comment by Bobronium** [comment]
@arthurazs, so basically what you need to know generic side of things is: how to use construct a new class dynamically and how to make use of `getitem` syntax on class, rather than on its instance.

Keywords: `__class_getitem__` or `__getitem__` on metaclass, `typing.Generic`, `type(name, bases, namespace)`

Here's my implementation of `IntBase` for reference: https://github.com/Bobronium/pydantic-toolbox/blob/78bbbd91b0ffa32a81e12de5091997790eacd175/src/pydantic_toolbox/types.py#L80

@samuelcolvin, please, let me know if you still think that `IntBase` should be a part of pydantic, I would be happy to make a PR in that case.

**Comment by samuelcolvin** [comment]
In pydantic v2 this should be relatively easy using `Annotated` and [`BeforeValidator`](https://docs.pydantic.dev/latest/api/functional_validators/#pydantic.functional_validators.BeforeValidator)
