### ISSUE TITLE
Validation of Union of pydantic model and dict does not  behave the same way like V1's smart_union

### ISSUE THREAD

**Issue by IterableTrucks** [pydantic/pydantic#6837]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

V2 removed the model config `smart_union` as all unions are "smart". But if the field type is `Foo|dict` where Foo is a pydantic model, the validator will still coerce a dict value to the pydantic model. That is different from the validation result of V1 when smart_union is set True

### Example Code

```Python
#code in V2
class Foo(BaseModel):
    pass
class Profile(BaseModel):    
    name:str
    age:int
    param: Foo|dict
profile=Profile(name='Amy', age=12, param={"grade": 7})
assert profile.param==Foo()

#code in V1
class Foo(BaseModel):
    pass
class Profile(BaseModel):    
    name:str
    age:int
    param: Foo|dict
    class Config:
        smart_union=True
profile=Profile(name='Amy', age=12, param={"grade": 7})
assert profile.param=={"grade: 7"}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
               python version: 3.11.2 (main, Mar 29 2023, 02:33:33) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
                     platform: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.17
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by hramezani** [comment]
Thanks @IterableTrucks for reporting this.

Here is my assumption(not sure it is correct). `param` has type `Foo|dict` and you initialized param with `{"grade": 7}`. So, Pydantic first tries to make a `Foo` object by input `Foo(**{"grade": 7})` and created an instance of Foo successfully then uses it as a value for `param`.  If you change the order to `dict|Foo`, You will get the dictionary in `param`.

Also, if you have the same order `Foo|dict` but include `model_config = ConfigDict(extra='forbid')` in `Foo`, you will get the dict in the param.

**Comment by dmontagu** [comment]
I understand that this is a behavior change that might not be preferable, but I think it would be difficult to change and I think is likely preferable in at least some scenarios. So I think we aren't likely to change this without a broader demonstration of interest.

However, you can still get the v1-style behavior by using a wrap-validator for the field that will pass through dicts unmodified:

```python
from typing import Annotated

from pydantic import BaseModel, field_validator
from pydantic import WrapValidator


class Foo(BaseModel):
    pass


SmartDict = WrapValidator(lambda v, h: v if isinstance(v, dict) else h(v))


class Profile(BaseModel):
    name: str
    age: int
    param: Annotated[Foo | dict, SmartDict]


profile = Profile(name='Amy', age=12, param={"grade": 7})
assert profile.param == {"grade": 7}
```

You could also do this with `@field_validator('param', mode='wrap')`, but this gives you a more reusable type annotation.

**Comment by IterableTrucks** [comment]
I found that annotating pydantic model with InstanceOf also worked. 
```python
from pydantic import BaseModel, InstanceOf

class Foo(BaseModel):
    pass
class Profile(BaseModel):    
    name:str
    age:int
    param: InstanceOf[Foo] | dict
profile=Profile(name='Amy', age=12, param={"grade": 7})
assert profile.param=={"grade":7}
```

**Comment by dmontagu** [comment]
That's another good alternative, just note that it will probably still attempt to load data into the `Foo` class when loading from JSON with that approach (and I think that's the main functional difference relative to my suggestion). But depending on your usage that may be preferable and/or irrelevant.
