### ISSUE TITLE
Wrong number when parsing json float to Decimal

### ISSUE THREAD

**Issue by trecouvr** [pydantic/pydantic#6841]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi,

I have a field with Decimal type and try to parse a "json float", meaning it's a float value in the json string (ex : `{"value": 1.2}`). 

**What I am observing**

Using Pydantic `model_validate_json(json_string)` I get something that feels wrong `Decimal('1.1999999999999999555910790149937383830547332763671875')`.

Using Python `json.loads(json_string, parse_float=Decimal)` I get a `Decimal('1.2')`. 

**What I would expect**

I would expect both methods to return `Decimal('1.2')`.

**Extra**

Note : If use a "string float" in the json input (ex: `{"value": "1.2"}`), I get the result I am expecting.
Note : In Python, `Decimal(1.2)` returns `Decimal('1.1999999999999999555910790149937383830547332763671875')`.

### Example Code

```Python
from decimal import Decimal
import json
from pydantic import BaseModel

class DecimalStuff(BaseModel):
    value: Decimal

decimal_stuff_str = """{"value": 1.2}"""
print(DecimalStuff.model_validate_json(decimal_stuff_str))
# > value=Decimal('1.1999999999999999555910790149937383830547332763671875')
out = json.loads(decimal_stuff_str, parse_float=Decimal)
print(DecimalStuff.model_validate(out))
# > value=Decimal('1.2')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/chillingmonkey/.virtualenvs/pydantic-test/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr 13 2023, 17:18:59) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Hi @trecouvr 👋 

I think it's a duplicate of https://github.com/pydantic/pydantic/issues/6807 and got fixed in https://github.com/pydantic/pydantic/commit/53207640a308806373bdeb1f4dea432f9c005ce2. It will be available in next release(soon).

**Comment by trecouvr** [comment]
Indeed same issue. Reverting to 2.0.2 for now fix the issue. Sorry for the duplicate and thanks for the help. Closing the issue.
