### ISSUE TITLE
extend AwareDatetime with implicit timezone

### ISSUE THREAD

**Issue by sanderr** [pydantic/pydantic#6843]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The current `AwareDatetime` type allows to validate that a datetime field is timezone aware. However, it doesn't allow coercion. I see mentioned [here](https://github.com/pydantic/pydantic/discussions/3477#discussioncomment-3756267) that this wouldn't be safe but I disagree, under certain circumstances. As I see it, pydantic is mainly used on the boundary of a Python program and some form of external input. The API on this boundary would have a contract with its users. It doesn't seem too far-fetched to assume that this contract may specify an assumed timezone for timestamps without an explicit timezone (e.g. UTC). I would like to see an option to `AwareDatetime` that allows you to specify the implied timezone for any naive timestamps, so that they can be coerced to be timezone aware.

With pydantic v1 (which doesn't have `AwareDatetime` afaik) we've always used a custom validator for this. We could do the same for v2 but since this seems like a common use case to me I think it could be good to support it natively. The v1 validator we use at the moment looks as follows.

```python
    @pydantic.validator("time")
    @classmethod
    def time_timezone_aware(cls, v: datetime.datetime) -> datetime.datetime:
        """
        Make sure the time field is timezone-aware. Any naive inputs are interpreted as UTC.
        """
        return v if v.tzinfo is not None else v.replace(tzinfo=datetime.timezone.utc)
```

In case both this suggestion and #5829 are considered as an extra feature, they should probably be worked out in tandem to ensure the two options can be clearly distinguished while still presenting an intuitive interface.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
We'd need to use Annotated to allow it to be configured anyway, so why not just use it to create a new type?

```python
from datetime import datetime, timezone
from typing import Annotated, TypeVar

from pydantic import TypeAdapter, AfterValidator
import pytz

T = TypeVar('T')

UTCDateTime = Annotated[datetime, AfterValidator(lambda d: d.astimezone(timezone.utc))]


ta = TypeAdapter(UTCDateTime)

print(ta.validate_python(datetime.now()))
#> 2023-07-25 11:19:34.082282+00:00
print(ta.validate_python(pytz.timezone('America/New_York').fromutc(datetime.now())))
#> 2023-07-25 13:20:56.483565+00:00
```

**Comment by sanderr** [comment]
Thanks for your response. I must confess I'm still working mostly on pydantic v1 and I hadn't yet encountered the `AfterValidator` with `Annotated`, looks useful. For completeness sake I'll add that the snippet would need to be slightly modified for what I'm proposing, as `astimezone` assumes local time and converts to UTC, opposed to `replace(tzinfo=timezone.utc)`, but that's a minor detail. This approach is definitely more easily reusable than the custom validator one in my initial report.
