### ISSUE TITLE
cls.model_fields on __init_subclass__

### ISSUE THREAD

**Issue by mauro-andre** [pydantic/pydantic#6854]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When I use the new "model_field" in a `__init_subclass__`, It doesn't show me the child class attributes, it shows me only the mother class attributes.
But when I use `Child.model_fields` outside `__init_subclass__`, it works very well.
I have a lot of applications with Pydatic V1 that I use `cls.__fields__` inside the `__init_subclass__` and it works normally.

### Example Code

```Python
class Mother(BaseModel):
    id: str = None
    created_at: datetime = None
    updated_at: datetime = None
    
    def __init_subclass__(cls):
         print(cls)
         for key, value in cls.model_fields.items():
             print(key)
             print(value)


class Child(Mother):
    attr1: str
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/mauro/dev-projects/python_mongo_odm_pv2/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by dmontagu** [comment]
We introduced `__pydantic_init_subclass__` specifically to address this problem. See docstring here:

https://github.com/pydantic/pydantic/blob/3284a249794efc30ec1935a0095671263a175c4e/pydantic/main.py#L576-L593

It seems to me that that's all you should need but please let us know if this doesn't address your use case.

**Comment by mauro-andre** [comment]
@dmontagu Thanks!
it worked perfectly
