### ISSUE TITLE
Pydantic V2 stopped validating TypedDict under Python 3.11

### ISSUE THREAD

**Issue by mjurbanski-reef** [pydantic/pydantic#6860]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

So I was using pydantic v2 to validate some json using `typing.TypedDict` on python 3.11; for versions below that I was using `typing_extensions`.
Now here comes the kicker, after reinstalling the thing, which puller new MINOR version of pydantic v2 - which apparently included this: https://github.com/pydantic/pydantic/commit/41371ff32377f521b9d3396a7746e305bc677f35#diff-2ebfa892ec1d09440eefd4b22f488ec38c1cde365394e5a4cea6edb484827ba5R75 all "validations" starter throwing an error.
So while I know what to do on my side, I just would love to avoid such unpleasant surprises in the future.

I love pydantic, and I'm grateful for the hard work put into it, but if possible
1) please, as minimum, when introducing such breaking change mark them as such in CHANGELOG (ideal would be to use semver)
2) couldn't just requirement be just a recommendation? pydantic worked for on python3.11 just fine, so I don't see why the change couldn't just be in docs and let the code work if possible as it was and just let it error out. 

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.0
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true

#I'm working on a library with multiple python versions between 3.8 and 3.12
```

Selected Assignee: @davidhewitt

Selected Assignee: @adriangb

**Comment by dmontagu** [comment]
@mjurbanski-reef I can see why that would be frustrating, but that commit has been there since the first non-beta release of v2.0; that change was made during the pre-release betas.

I'll leave it to @adriangb to go into more detail about why we require 3.12+ for typing.TypedDict, but if I recall correctly it has something to do with being able to store attributes on the type properly (so that validators, etc. work).

**Comment by adriangb** [comment]
Like David said that change was fully SemVer compliant.

We added tracking of base classes to `TypedDict` in CPython 3.12 which allows us to use TypedDict just like you would a model. Previously you couldn't use `@field_validator` on it for example. If we didn't bump the required minor version we'd have complaints that people's validators were dropped on the floor (and we'd have no way of detecting that!).

I'm sorry it's been a problem for you but it was a necessary change.

**Comment by davidhewitt** [comment]
If I understand correctly, the state of play is that `typing.TypedDict` required 3.12+, but we support `typing_extensions.TypedDict` on all versions?

If that's the case, the documentation needs updating - https://docs.pydantic.dev/2.1/usage/types/dicts_mapping/#typeddict only suggests `typing_extensions.TypedDict` up to 3.8.

**Comment by adriangb** [comment]
Yep agreed I'll make a PR for that

**Comment by davidhewitt** [comment]
👍 For now I'll reopen this issue to serve as a reminder the docs need updating.
