### ISSUE TITLE
Broke FastAPI Annotate with 2.1

### ISSUE THREAD

**Issue by pbaletkeman** [pydantic/pydantic#6864]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In version 2.0.3 this code works fine
```
@router.get('/book-report/{id}', tags=['Results'])
def display_results(id: Annotated[int, Path(description="Results To Retrieve")]):
```
However, in 2.1.0 it throws an error at start up. Here is a work around
```
@router.get('/book-report/{id}', tags=['Results'])
def display_results(id: int):
```

Either FastAPI has a dependency on Pydantic 2.0.3 or FastAPI has a dependency on Annotated and Annotated has a dependency on Pydantic 2.0.3.
Regardless this is a breaking change.
I will also post on the FastAPI site about this.

### Python, Pydantic & OS Version

```Text
- Docker image (python:3.11-slim) 
- fastapi 0.100.0 (https://pypi.org/project/fastapi/)
  - pydantic 2.1.0
```

Selected Assignee: @samuelcolvin

**Comment by pbaletkeman** [comment]
Here is the FastAPI bug report
https://github.com/tiangolo/fastapi/discussions/9942

**Comment by dmontagu** [comment]
Have a fix ready https://github.com/pydantic/pydantic/pull/6862, will get it released as 2.1.1 ASAP.

Sorry for the hiccup. We'll work on putting a better process in place to make sure that we don't break FastAPI even if we do break some tests related to the exact specifics of schemas / validation errors.

**Comment by dmontagu** [comment]
Pydantic v2.1.1 should be live now and FastAPI's CI is passing with just some minor changes to the contents of some validation errors: https://github.com/tiangolo/fastapi/pull/9943

**Comment by pbaletkeman** [comment]
Thank you
