### ISSUE TITLE
Implicit int limits

### ISSUE THREAD

**Issue by ImogenBits** [pydantic/pydantic#6889]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Some of the older messaging around the move to v2 and the current data conversion table in the docs say that you use i64 values to internally represent python `int`. I expected this to lead to either error messages when trying to validate numbers outside of that range or (less ideally) have them be converted to the max/min. But running the code below just prints `True` every time. Is that the intended behaviour? Are you not using i64's internally anymore?

### Example Code

```Python
class MyModel(BaseModel):
    a: int

print(MyModel(a=2**70).a == 2**70)
print(MyModel.model_validate_json(f"""{{"a": {2**70}}}""").a == 2**70)

py_int = TypeAdapter(int)

print(py_int.validate_python(2**70) == 2**70)
print(py_int.validate_json(f"{2**70}") == 2**70)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
pydantic-core version: 2.3.0 release build profile
python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
optional deps. installed: ['typing-extensions'];
```

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
I think we recently fixed this to handle large numbers, up to the limits of python (which IIRC are ~4000 decimal digits). I think we use i64s when the value can fit, and otherwise convert to a python int.
