### ISSUE TITLE
[BUG] ValidationError not raised when validating a Pydantic model (with a missing required field)

### ISSUE THREAD

**Issue by marielejeune** [pydantic/pydantic#6901]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Validating a Pydantic model directly using the model object does not work as expected: no ValidationError when a required field is missing.

See the two following examples, using `model_validate` and `TypeAdapter`.

See Pull Request with changes suggestions and tests : https://github.com/pydantic/pydantic/pull/6902

### Example Code

```Python
# 1. `model_construct` then `model_validate`

from pydantic import BaseModel

class Model(BaseModel):
    x: str


obj = Model()  # ValidationError is raised: required field is missing (as expected)
obj = Model.model_construct()
obj.model_validate(obj, from_attributes=True)  # ValidationError should be raised but is not


# 2. `TypeAdapter`


from pydantic import TypeAdapter

class Model(BaseModel):
    x: str

validator = TypeAdapter(Model)
validator.validate_python({})   # ValidationError is raised: required field is missing (as expected)
m = Model.model_construct()
validator.validate_python(m, from_attributes=True) # ValidationError should be raised but is not
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/marie/Projects/pydantic/pydantic
               python version: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
                     platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.31
     optional deps. installed: ['devtools', 'email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by marielejeune** [comment]
Thanks for your answer.

I'm a bit surprised, as it means that you always assume that who manipulates a model does it correctly?

For example: 

```python
from pydantic import BaseModel

class User(BaseModel):
     name: str

user = User(name='a')  # Correctly validated
user.name = None   # No more valid
user.model_validate(user, from_attributes=True)  # ValidationError could be expected but not raised

```
Hence you would advise to add `model_config = ConfigDict(revalidate_instances='always')` in all cases where such a modification could happen?

**Comment by dmontagu** [comment]
Yes, we assume that you are using a type checker (like mypy or pyright) to detect and prevent errors like this in python code.

(Note that none of this is a change from the intent in V1.)

If you want attribute assignment like this to be validated though, there is an option for that as well: `model_config['validate_assignment'] = True`.

**Comment by lmignon** [comment]
@dmontagu  What do you recommend as pattern to construct a model from different 'sources'? The probable misuse of `model_construct` comes in our case from the way we implemented this behaviour as a classmethod...

```python

from pydantic import BaseModel

class Coordinate(BaseModel):
    lat: float
    lon: float

    @classmethod
    def from_x(cls, source: X):
        instance = cls.model_construct()
        instance.lat = source.latitude 
        instance.lon = source.longitude
        return instance

Class CoordinateWithName(Coordinate): 
    name:str

    @classmethod
    def from_x(cls, source: X):
        instance = super().from_x(source)
        instance.name = "..."
        return instance

```

I could call the constructor `cls(...)` in the `from_x` method of  my `Coordinate` class. But it will only work if the method is called on the `Coordinate` class not on subclass of `Coordinate` defining additional required fields.

**Comment by Kludex** [comment]
Using `validation_alias` with `from_attributes` would be the recommended way here, I guess:

```py
from pydantic import BaseModel, ConfigDict, Field

class Coordinate(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    lat: float = Field(validation_alias="latitude")
    lon: float = Field(validation_alias="longitude")


class CoordinateWithName(Coordinate):
    name: str = "..."

class Source:
    def __init__(self, name: str, latitude: float, longitude: float):
        self.name = name
        self.latitude = latitude
        self.longitude = longitude


print(CoordinateWithName.model_validate(Source(name="test", latitude=1.0, longitude=2.0)))
```

**Comment by lmignon** [comment]
But using `validation_alias` is for simple cases. In our cases, the mapping could be quite complex and require some logic...

**Comment by Kludex** [comment]
`model_validator` or `field_validator` then.

**Comment by dmontagu** [comment]
If your logic is significantly more complex, then it's hard for us to make suggestions without seeing something representative of that.

I'll note that the mypy plugin is capable of type checking `model_construct`, and the following would pass type checking with the plugin enabled, unlike your current implementation of the function:
```python
    @classmethod
    def from_x(cls, source: X):
        lat = source.latitude 
        lon = source.longitude
        return cls.model_construct(lat=lat, lon=lon)
```
And if you only use calls to `model_construct` that pass type checking like this, it should be safe. So this might be a safe way to avoid validation when desirable if instantiating from different sources where you need different logic.

But if you think there's any chance of issues coming from invalid calls to `model_construct` and want actual validation (like what FastAPI did with pydantic v1), the safest way would be to drop calls to `model_construct` entirely and, like @Kludex said, use a `@model_validator` (probably with `mode='before'`) where you check the type of the input value and prepare it appropriately.

**Comment by lmignon** [comment]
@marielejeune I think we this one should be closed.
