### ISSUE TITLE
defining fields with `pydantic.v1.Field()` causes pylint `no-member` warnings

### ISSUE THREAD

**Issue by tylerflex** [pydantic/pydantic#6909]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm using `pydantic.v1` to transition our codebase to pydantic 2.* but doing so has resulted in many pylint warnings due to the use of `pydantic.v1.Field()` in defining the fields of my class.

```
x : int = pydantic.v1.Field(...)`
```

it seems that pylint interprets `self.x` as a `ModelField` instead of an `int` and therefore creates many warnings throughout the entire codebase.

Note that this doesn't occur if I leave out the `pd.Field()` definition.

```
x : int
```

Any thoughts on how to get around this issue would be really appreciated! Code example below showing the issue.  

(I am running pylint-2.17.5 and Python 3.10.9)

Thanks

### Example Code

```Python
""" module docstring """
import pydantic.v1 as pydantic


class ClassA(pydantic.BaseModel):
    """Class A"""

    field_a : float


class ClassB(pydantic.BaseModel):
    """Class B"""

    # doesnt trigger pylint
    obj_a: ClassA

    # triggers Instance of 'FieldInfo' has no 'field_a' member (no-member) from below method
    obj_a: ClassA = pydantic.Field(...)

    def get_field_a(self):
        """Grab the 'field_a' from 'self.obj_a'."""
        return self.obj_a.field_a

# simple test to show that the method works as expected
FIELD_A = 1.0
obj_a = ClassA(field_a=FIELD_A)
obj_b = ClassB(obj_a=obj_a)
assert obj_b.get_field_a() == FIELD_A
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/twhughes/.pyenv/versions/3.10.9/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Dec 30 2022, 09:25:19) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.5.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
@adriangb and @Kludex since I'm not a vscode user so it's a bit hard for me to investigate, would one of you mind taking a look instead?

**Comment by adriangb** [comment]
I assume you're referring to https://github.com/pylint-dev/pylint, not the VSCode linter? I get no such errors with VSCode PyLint/Pyright or mypy (there is a duplicate field, but that's another thing).

**Comment by dmontagu** [comment]
Oops nevermind, I got confused and thought pylint was the vscode linter 🤦‍♂️. Maybe a bug with pylint?

**Comment by tylerflex** [comment]
@adriangb yes, pylint installed through `pip install pylint` which looks like it is that one.

Could be a bug there, except this same code snippet worked fine in pydantic 1.* so I'm assuming there's something in the new `pd.Field()` that makes pylint no longer recognize the field type properly 🤔

**Comment by adriangb** [comment]
Can you start by filing a bug there since it worked with other linters? Maybe they special case Pydantic.

**Comment by tylerflex** [comment]
sure, I made a ticket [there](https://github.com/pylint-dev/pylint/issues/8894) as well.

**Comment by tylerflex** [comment]
Hey @adriangb @dmontagu , if you check out the issue I made on pylint, they say that the no-member warning is actually desired behavior and how it worked in v1 was actually not correct. Apparently for
```py
var : MyType = pd.Field(...)
```
pylint registers `var` as a `ModelField` rather than `MyType`. Do you think this is reasonable?

**Comment by adriangb** [comment]
I'm not sure I agree with that behavior, every other type checker that I know of would keep it as `MyType` but give you a type error on that line for assigning the wrong type.

Since I don't think there's much for pydantic to do here (especially considering that it seems like they special cased Pydantic v1?) I'm going to close this as a wont fix.

**Comment by tylerflex** [comment]
@adriangb I agree, it's a shame that pylint won't fix this as we rely on that tool for our development. seems pylint-pydantic has the same issue. I assume other pydantic + pylint users will run into the same thing. 

I wonder if there's some way to trick pylint into recognizing the field as `MyType` in the `ModelField` internals?

Anyway, it makes it very hard to upgrade our codebase to pydantic v2 until this is resolved.

**Comment by adriangb** [comment]
`Field` already returns an `Any`: https://github.com/pydantic/pydantic/blob/2efd6655c75f132f186e569234f14606b90027d5/pydantic/fields.py#L684

Not sure what else we can do apart from that.

**Comment by tylerflex** [comment]
but I guess pylint parses this as a `ModelField` eventually (according to the warning message)? I wonder where they get that information from

**Comment by kamichal** [comment]
Related: https://github.com/pylint-dev/pylint/issues/10087
