### ISSUE TITLE
AnyUrl doesn't accept file URLs with implicit host 

### ISSUE THREAD

**Issue by honglei** [pydantic/pydantic#6929]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

https://github.com/pydantic/pydantic/issues/1983 appear again.

### Example Code

```Python
from pydantic import AnyUrl, FileUrl
from pydantic.main import BaseModel, Field

class MoveSharedUrl(AnyUrl):
    allowed_schemes=['smb', 'ftp','file' ]

class Test(BaseModel):
    url: MoveSharedUrl
    
    
Test(url = "file:///aaa/bbb/serverFile/recvFiles/")
Test(url= "smb://10.64.39.23/serverFile/recvFiles/")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.11
            pydantic compiled: True
                 install path: C:\Python311\Lib\site-packages\pydantic
               python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @hramezani

**Comment by hramezani** [comment]
Thanks @honglei for reporting this 🙏 

As you know, `Pydantic V2` is out and we are not working actively on `Pydantic V1`. 
We can consider an easy patch for fixing this problem on `V1` if you would like to prepare the patch.


BTW, the working example on V2 is:

```py
from typing_extensions import Annotated

from pydantic import AnyUrl, UrlConstraints
from pydantic.main import BaseModel


class Test(BaseModel):
    url: Annotated[AnyUrl, UrlConstraints(allowed_schemes=['smb', 'ftp','file'])]
    
    
Test(url = "file:///aaa/bbb/serverFile/recvFiles/")
Test(url= "smb://10.64.39.23/serverFile/recvFiles/")
```

**Comment by sydney-runkle** [comment]
We’re no longer actively developing Pydantic V1 (although it will continue to receive security fixes for the next year or so), so we’re closing issues solely related to V1. If you _really_ think this shouldn’t be closed, please comment or create a new issue 🚀.
