### ISSUE TITLE
Trying to make package compatible with both pydantic V1 and V2 broke autocompletion

### ISSUE THREAD

**Issue by VianneyMI** [pydantic/pydantic#6932]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I built a package based on pydantic v1 a few months ago: https://github.com/VianneyMI/monggregate

I recently migrated and attempted to make the package compatible with both pydantic v1 and v2. 
I found the task very challenging but I managed to it with the following trick:

```python
 # Standard Library imports
#----------------------------
from abc import ABC, abstractmethod
from typing import Any

# 3rd Party imports
# ---------------------------
import pydantic
if pydantic.__version__.startswith("1"):
    from pydantic import BaseModel as PydanticBaseModel, BaseConfig, ValidationError, Field, validator
else:
    from pydantic.v1 import BaseModel as PydanticBaseModel, BaseConfig, ValidationError, Field, validator
    
from humps.main import camelize



class BaseModel(PydanticBaseModel, ABC):
    """Mongreggate base class"""

    @classmethod
    def resolve(cls, obj:Any)->dict|list[dict]:
        """Resolves an expression encapsulated in an object from a class inheriting from BaseModel"""

        return resolve(obj)

    @property
    @abstractmethod
    def statement(self)->dict:
        """Stage statement absctract method"""

        # this is a lazy attribute
        # what is currently in generate statement should go in here

    def __call__(self)->dict:
        """Makes an instance of any class inheriting from this class callable"""

        return self.resolve(self.statement)

    class Config(BaseConfig):
        """Base configuration for classes inheriting from this"""

        allow_population_by_field_name = True
        underscore_attrs_are_private = True
        smart_union = True
        alias_generator = camelize
```

However, this is breaking autocompletion down the line.
For example if I have a class:

```python
class Point(BaseModel):
    x : int
    y : int
```

I no longer have autocompletion when I type:

`Point(`

See :
![image](https://github.com/pydantic/pydantic/assets/59029806/007676b5-cebd-4b5a-bb33-2f7601d7a3e5)

Any idea how I can solve this ?
I wonder how @tiangolo made FastAPI compatible with both.

PS : Importing BaseModel from pydantic solves the autocompletion issue but breaks everything else

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: C:\Users\viann\OneDrive\Bureau\Projects\monggregate\venv\Lib\site-packages\pydantic
               python version: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by dmontagu** [comment]
A couple other things to try:

```python
try:
    import pydantic.v1 as pydantic
except ImportError:
    import pydantic
...

class BaseModel(pydantic.BaseModel, ABC):
    ...
```

```python
import pydantic

if pydantic.__version__.startswith("1"):
    import pydantic.v1 as pydantic
...

class BaseModel(pydantic.BaseModel, ABC):
    ...
```

Not sure whether these will help any, but I think I've seen other people use tricks like this.

**Comment by VianneyMI** [comment]
Thanks the try/except approach did not work. 
However, the second approach kinda worked. I just had to slightly modify it.

I use the trick in one file, and everywhere I add to use pydantic feature, I am "re-importing" pydantic from that one file.
I am closing this but should I go ahead and create a PR to document this in the migration guide ?

**Comment by dmontagu** [comment]
@VianneyMI it would be very much appreciated if you did!
