### ISSUE TITLE
Protected namespaces warning cannot be disabled

### ISSUE THREAD

**Issue by willarmiros** [pydantic/pydantic#6941]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I just upgraded a project from Pydantic v1 -> v2 and everything seems to be going smoothly except that we get several warnings like the following:

```
/root/.cache/pypoetry/virtualenvs/project-9TtSrW0h-py3.11/lib/python3.11/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_count" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
```

I gather from the [Pydantic docs](https://docs.pydantic.dev/2.0/usage/model_config/#protected-namespaces) that the reason for this is because I have several field names like model_count and model_name that start with `model_` which triggers the warning. However those field names have good reason to start with `model_` (they are describing ML Models) and it would be a huge refactor to rename them all to something else.

So I have followed the recommendation in the warning messages and set `model_config: ConfigDict(protected_namespaces=())` on my classes. However this does not appear to do anything and the warning still appears! Any tips on how to fix this?

### Example Code

```Python
from pydantic import ConfigDict, BaseModel

class MLModelStorage(BaseModel):
    model_count: str
    model_version_id: int
    model_config: ConfigDict(protected_namespaces=())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/williamarmiros/protectai-code/radar-api/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
You need to change the model_config line to `model_config = ConfigDict(protected_namespaces=())`

replace `:` with `=`

**Comment by willarmiros** [comment]
🤦  @hramezani that fixed the warnings, thanks!
