### ISSUE TITLE
`BaseModel.model_validate` does not behave as former `BaseModel.parse_obj`

### ISSUE THREAD

**Issue by flxdot** [pydantic/pydantic#6944]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm currently migrating our code base over to Pydantic V2 and noticed a behaviour of `model_validate()`, which I can't quite understand. We use `parse_obj()` quite heavily to convert data between different Pydantic objects (even inherited ones).

In V1 `parse_obj()` would convert an given pydantic object to the model of my choice.

```python
from pydantic.v1 import BaseModel

class MyModel(BaseModel):
    a: int


class MyExtendedModel(MyModel):
    b: float


extended_model = MyExtendedModel(a=1, b="foo", c=3.14)
model = MyModel.parse_obj(extended_model)

print("model is of type: " + type(model).__name__)

# Expectations
assert not hasattr(model, "b"), f"model is of type {model.__class__.__name__} instead of MyModel"
```

With the V2 equivalent (`model_validate()`) these expectations are no longer met (see **Example Code**).

I can still achieve the original behavior by dumping the model and then validating again:

```python
model = MyModel.model_validate(extended_model.model_dump())
```

I know, that the old `parse_obj` method is still available until V3, but I wonder if we are misusing the `parse_obj()` method, or whether I overlooked something in the Migration guide?

I'm happy to hear from you.

Please keep up the good work on Pydantic! It's a major backbone for the solution we all love to work with. 

### Example Code

```Python
from pydantic import BaseModel

class MyModel(BaseModel):
    a: int


class MyExtendedModel(MyModel):
    b: float


extended_model = MyExtendedModel(a=1, b=3.14)
model = MyModel.model_validate(extended_model)

print("model is of type: " + type(model).__name__)

assert not hasattr(model, "b"), f"model is of type {model.__class__.__name__} instead of MyModel"
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/.../lib/py_qmulus_core/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by flxdot** [comment]
Another thing I just realized, is that the objects returned by the `model_validate` is the exact same object:

```python
# This is True
assert model is extended_model
```

Whereas `parse_obj` returned a new instance of the object.

The fix 
```python
model = MyModel.model_validate(extended_model.model_dump())
```

Also works, here, but then I would suggest updating the migration guide/docs to hint at that behavior.

**Comment by tcrasset** [comment]
I agree, I expected `MyModel.model_validate(my_dict)` to work similarly to `MyModel(**my_dict)`, as described in the documentation:

https://docs.pydantic.dev/dev-v2/usage/models/#extra-fields

**Comment by dmontagu** [comment]
I think the reasoning for this change is roughly as follows:
* When you have a model whose fields are themselves models, it is _much_ faster to just do an `isinstance` check than to revalidate the nested data. Therefore, there are cases where it is significantly beneficial to not revalidate model data — generally, once a model's data has been validated, it is safe to assume that it will always be valid, and there can be a significant performance benefit to doing so, e.g. if passing a nested attribute value around between different parent model types.
* For consistency with that behavior for fields, we use that same logic even when doing a `model_validate` at the top level. This does have significant performance benefits if the behavior is what you want, but I can understand how you might be more likely to take advantage of the old behavior when calling methods at the top level.

However, I'll note that there is the `model_config = {'revalidate_instances': 'always'}` option, which at least makes your code above behave the way I think you expected it to:
```python
from pydantic import BaseModel

class MyModel(BaseModel):
    model_config = {'revalidate_instances': 'always'}
    a: int


class MyExtendedModel(MyModel):
    b: float


extended_model = MyExtendedModel(a=1, b=3.14)
model = MyModel.model_validate(extended_model)

print("model is of type: " + type(model).__name__)
#> model is of type: MyModel

assert not hasattr(model, "b"), f"model is of type {model.__class__.__name__} instead of MyModel"
```

If you feel the documentation is not sufficient on this point, I think we can improve it, and would be interested in any suggestions.

**Comment by flxdot** [comment]
Thanks for the explanation. It's a very reasonable and desirable approach.

I did not know about the config value. Thank your for the hint!

Regarding the docs: I'll think about how this can be made more explicit.

**Comment by audiovention** [comment]
Just hit that behaviour, IMHO it is a bug and not very consistent. 
I use "ParentModel.model_validate(child_model_instance)" to convert a model to a base class model. As explained, this doesn't work and returns the same child_model_instance. 
Can you recommend what's the proper way to achieve that, I think it's a rather common use case. 
What bothers me in that scenario is that even if I set extra="forbid" on the ParentModel, this validation passes. 

I can understand that the validation logically passes, as the child_model_instance is already of type ParentModel, so there's nothing to validate. But I guess if that path is taken, then the docs should discourage inheriting models in the first place.

**Comment by slingshotvfx** [comment]
Just hit this same issue today.  I use various inherited Pydantic models to define return schemas from a fastAPI app.

I expected:

```python
UserRead.model_validate(AdminUserRead, from_attributes=True)
```
to return a type UserRead, but it doesn't, it returns AdminUserRead since it's a sublcass of UserRead.

Adding `model_config = {"revalidate_instances": "always"}` to the `UserRead` model does solve the problem, but that seems very obscure to me and isn't clear from the code what it's changing.

```python
UserRead.model_validate(AdminUserRead.model_dump())
```
works just fine, and is what I'm using for now.  But this could definitely be improved in the docs, or maybe there needs to be a new method like `UserRead.from_model(AdminUserRead)` or something that conforms one already-validated model to another.

I think this is a pretty common use case.

**Comment by flxdot** [comment]
That is weird. The solution https://github.com/pydantic/pydantic/issues/6944#issuecomment-1677999411 provided works as expected with FastAPI.

The [documentation of model_validate](https://docs.pydantic.dev/latest/concepts/models/#helper-functions) has also been updated. From my point of view the issue is solved.

## Example

```
pydantic >= 2.5.3
fastapi >= 0.108.0
```

```python
from fastapi import FastAPI
from pydantic import BaseModel


class MyModel(BaseModel):
    model_config = {"revalidate_instances": "always"}
    a: int


class MyExtendedModel(MyModel):
    b: float


extended_model = MyExtendedModel(a=1, b=3.14)
model = MyModel.model_validate(extended_model)

print("model is of type: " + type(model).__name__)

assert not hasattr(
    model, "b"
), f"model is of type {model.__class__.__name__} instead of MyModel"


app = FastAPI(
    docs_url="/docs",
)


@app.get("/", response_model=MyModel)
def root() -> MyModel:
    return extended_model

@app.get("/extended", response_model=MyExtendedModel)
def root() -> MyExtendedModel:
    return extended_model


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app)
```

As you can see from the output below both endpoints return the expected content.

<img width="612" alt="Screenshot 2024-01-05 at 19 30 52" src="https://github.com/pydantic/pydantic/assets/35657654/be7f9a2d-3c5e-4592-8922-13358c62f34b">

**Comment by flxdot** [comment]
@slingshotvfx Maybe your project is making use of the `responses` keyword argument? There is a seems to be a bug in FastAPI. I did not have time to search for issues/report an issue with FastAPI. It for example fails to serialize the `@computed_field` decorator.

## Example: 
```diff
app = FastAPI(
    docs_url="/docs",
)


- @app.get("/", response_model=MyModel)
- def root() -> MyModel:
+ @app.get("/",  responses={200: {"model": MyModel}})
+ def root():
    return extended_model
```

As you can see below the response indeed contains the field `b` which is not desired.

<img width="514" alt="Screenshot 2024-01-05 at 19 48 17" src="https://github.com/pydantic/pydantic/assets/35657654/0c317919-fd6b-45aa-97a1-27037ba03cb8">

**Comment by slingshotvfx** [comment]
After playing around a bit more my issue seems to stem from multi-level sub-classes:

```python
from pydantic import BaseModel


class Model(BaseModel):
    a: bool = True


class SubclassedModel(Model):
    b: bool | None = None


class SubSubclassedModel(SubclassedModel):
    c: bool | None = None


sub = SubclassedModel()
base = Model.model_validate(SubclassedModel, from_attributes=True)

assert type(base) == Model  # passes
assert not hasattr(base, "b")  # passes

subsub = SubSubclassedModel()
sub = SubclassedModel.model_validate(subsub, from_attributes=True)

assert type(sub) == SubclassedModel, f"model is {type(sub)}" # fails
assert not hasattr(sub, "c") # fails
```

```
assert type(sub) == SubclassedModel, f"model is {type(sub)}"  # fails
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: model is <class '__main__.SubSubclassedModel'>
```

That `Model.model_validate()` can return a model that is not `Model` (in some instances) is unexpected to me and not mentioned in the docs. 

Setting `revalidate_instances='always'` on `SubclassedModel` does pass the final two assertions. But again the documentation about `revalidate_instances='always'` isn't clear that it changes the resulting model type in those situations.
