### ISSUE TITLE
MongoDsn.build gives AttributeError

### ISSUE THREAD

**Issue by quizmoon** [pydantic/pydantic#6945]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using build on MongoDsn gives error:

    url = MongoDsn.build(scheme=scheme, username=username, password=password, host=host)
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1287, in __getattr__
    return getattr(self.__origin__, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 450, in __getattr__
    raise AttributeError(item)
AttributeError: build

### Example Code

```Python
url = MongoDsn.build(scheme=scheme, username=username, password=password, host=host)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.19.0-50-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by quizmoon** [comment]
Additionally, if build url using MultiHostUrl and then create instance of MongoDsn from it:

url = MultiHostUrl.build(scheme=scheme, username=username, password=password, host=host)
MongoDsn(url)

Will give the error:

MongoDsn(url)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 1261, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/typing.py", line 462, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union

**Comment by Kludex** [comment]
It doesn't look like you are in the latest version of Pydantic 🤔 

You sure you are using the version 2.1.1?
