### ISSUE TITLE
Annotations with BaseModel cause validation error

### ISSUE THREAD

**Issue by dirkkul** [pydantic/pydantic#6948]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to annotate a member of a BaseModel with another class using `Annotated[str, CLASS]`:
- When using a dataclass, it works and the additional annotated class is accessible through metadata
- When using a BaseModel, a validation error is thrown when instanciating the BaseModel. It looks like pydantic tryies to validate the real type as well as the annotated BaseModel resulting in the following error:
 
>  Input should be a valid dictionary or instance of Group_bm [type=model_type, input_value='test', input_type=str]

full code example is below.

Thank you so much for creating pydantic!

### Example Code

```Python
from pydantic import BaseModel
from dataclasses import dataclass
from typing import Annotated

@dataclass
class Group_dataclass:
    name: str

class User_dataclass(BaseModel):
    in_group: Annotated[str, Group_dataclass]

a = User_dataclass(in_group="test")  # works


class Group_bm(BaseModel):
    name: str

class User_bm(BaseModel):
    in_group: Annotated[str, Group_bm]

b = User_bm(in_group="test")  # Error => Input should be a valid dictionary or instance of Group_bm [type=model_type, input_value='test', input_type=str]
```

### Python, Pydantic & OS Version

```Text
(.venv) ➜  weaviate_grpc git:(pydantic_experiment) ✗ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/dirkkulawiak/Documents/weaviate/weaviate-python-client/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by lig** [comment]
This is intended as `Group_bm` in your case is Pydantic model it acts as a custom type providing [custom validation and serialization logic](https://docs.pydantic.dev/dev-v2/usage/types/custom/#customizing-validation-with-__get_pydantic_core_schema__) using `__get_pydantic_core_schema__` method. Thus, Pydantic uses this custom logic and requires the value to be a valid for validating as `Group_bm` instance.
