### ISSUE TITLE
Complex Enums raises TypeError

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#6953]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

json schema enum types are json documents - or "Any", this includes array and object types.

short demo of this using jsonschema:
```python
from jsonschema.exceptions import ValidationError
from jsonschema.validators import validate

schema = {
    "type": "array",
    "items": {
        "type": ["object"],
        "properties": {
            "A": {"type": "string"},
            "B": {"type":"integer"}
        },
        "enum": [
            {"A": "test", "B": 5},
            {"A": "test", "B": 4}, ]
    },
    "enum": [
        [{"A": "test", "B": 5}]
    ]
}

validate(instance=[{"A": "test", "B": 5}], schema=schema)

try:
    validate(instance=[{"A": "test", "B": 4}], schema=schema)
except ValidationError:
    pass
```

Currently it is not possible with pydantic to map complex enums
Example using a simple object:
```python
from typing import Literal
from pydantic import BaseModel

class A(BaseModel):
    b: Literal[{"a":1}]
```    

```
pydantic_core._pydantic_core.SchemaError: Error building "model" validator:
  SchemaError: Error building "model-fields" validator:
  SchemaError: Field "b":
  SchemaError: Error building "literal" validator:
  TypeError: unhashable type: 'dict'
```

This could raise something better than TypeError.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
> This could raise something better than TypeError.

What do you expect from that? It's not even a valid Python syntax. 🤔

**Comment by commonism** [comment]
As I said - just proposing to raise better than TypeError.
I do not expect pydantic to support this … gem.

**Comment by sydney-runkle** [comment]
Given that this isn't even valid python syntax, I'm going to close this as not planned.
