### ISSUE TITLE
`model_validate` leads to `RecursionError`

### ISSUE THREAD

**Issue by tcrasset** [pydantic/pydantic#6957]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The migration guide specifies to use `model_validate` in place of many methods such as `parse_obj`. However, when changing to `model_validate`, I still get a DeprecationWarning, saying I should use... `model_validate`.

Moreover, this introduces a `RecursionError`.

Offending line of code:

```python
    @classmethod
    @typing_extensions.deprecated(
        'The `model_validate` method is deprecated; use `model_validate` instead.', category=PydanticDeprecatedSince20
    )
    def model_validate(cls: type[Model], obj: Any) -> Model:  # noqa: D102
        warnings.warn('The `model_validate` method is deprecated; use `model_validate` instead.', DeprecationWarning)
        return cls.model_validate(obj)
```

I expect to see no deprecation warning, and no `RecursionError`.

Seems to be linked to `typing_extensions`.

### Example Code

```Python
from pydantic import BaseModel

class A(BaseModel):
    a: int

A.model_validate(dict(a=1))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/tom/.cache/pypoetry/virtualenvs/api-1Bf64r6x-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.17 (main, Jun  6 2023, 20:11:04)  [GCC 9.4.0]
                     platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
As far as I can tell, this code is not present anywhere in the repository:
```python
    @classmethod
    @typing_extensions.deprecated(
        'The `model_validate` method is deprecated; use `model_validate` instead.', category=PydanticDeprecatedSince20
    )
    def model_validate(cls: type[Model], obj: Any) -> Model:  # noqa: D102
        warnings.warn('The `model_validate` method is deprecated; use `model_validate` instead.', DeprecationWarning)
        return cls.model_validate(obj)
```

Did you do a find-and-replace that replaced parse_obj with model_validate even in the pydantic library code? That's the only way I can think that would have caused this to happen.

**Comment by tcrasset** [comment]
Errm, I feel like a fool, I indeed did that... Sorry for wasting your time.
