### ISSUE TITLE
numpy's float64 is treated wrong

### ISSUE THREAD

**Issue by xmatthias** [pydantic/pydantic#6963]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In my understanding, subclasses should serialize correctly as long as they're a valid subclass, even if the actual type is not explicitly defined (in this case, Any).

This doesn't seem to be true for numpy's float64 type - which IS a subtype of float - but raises a validation error.

```
...
    314 def model_dump_json(
    315     self,
    316     *,
   (...)
    325     warnings: bool = True,
    326 ) -> str:
    327     """Usage docs: https://docs.pydantic.dev/dev-v2/usage/serialization/#modelmodel_dump_json
    328 
    329     Generates a JSON representation of the model using Pydantic's `to_json` method.
   (...)
    343         A JSON string representation of the model.
    344     """
--> 345     return self.__pydantic_serializer__.to_json(
    346         self,
    347         indent=indent,
    348         include=include,
    349         exclude=exclude,
    350         by_alias=by_alias,
    351         exclude_unset=exclude_unset,
    352         exclude_defaults=exclude_defaults,
    353         exclude_none=exclude_none,
    354         round_trip=round_trip,
    355         warnings=warnings,
    356     ).decode()

PydanticSerializationError: Unable to serialize unknown type: -0.0034025669825439

```

This is obviously a simplified reproduction - i'm actually having this problem in a nested dict, where i can't currently type all keys, as not all are "properly" identified.

That same model works fine on V1 (using `.json()`) - so i assume this is a regression ? 
I did attempt `SerializeAsAny` - but it doesn't change behavior.

### Example Code

```Python
from typing import Any
import numpy as np
from pydantic import BaseModel

class TestModel(BaseModel):
    status: float
    status_any: Any


test = TestModel(status=np.float64(-22), status_any=np.float64(-0.0034025669825439))

print(f"isSubType {issubclass(np.float64, float)}")

print(test.model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/xmatt/.pyenv/versions/3.11.4/envs/trade_3114/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 12 2023, 20:09:51) [GCC 13.1.1 20230429]
                     platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']

```
```


Selected Assignee: @samuelcolvin

**Comment by adriangb** [comment]
cc @samuelcolvin

**Comment by ramedina86** [comment]
You beat me by 6 hours. Keen to follow this and find out whether support for numpy.float64 will be readded.

**Comment by samuelcolvin** [comment]
sorry for the delay in getting back to you on this - we had an offsite last week so were very busy.

I see the problem with `status_any` not being serialized successfully. I've proposed a fix in https://github.com/pydantic/pydantic-core/pull/860, please let me know if that fixes your problem.

**Comment by xmatthias** [comment]
no need to appologize - your response / reaction is WAY quicker than on some other projects :100: 

I'm ... unsure on how to actually test this if I'm honest - but assuming i did it right, then i think it's fixed.

I've installed the latest pydantic version (2.1.1) - and then installing "pydantic_core" from the tarball in CI on the linked PR over the top (so pydantic_core is now 2.4.0), and that seems to fix this, as well as the "nested dict" behavior with a numpy object in a `Dict[str, Any]` structure.

**Comment by samuelcolvin** [comment]
Thanks so much, that's about right, the other way to do it is to installed pydantic-core straight from the git branch, but what you did should have worked too.

I'll get that merged and released soon.
