### ISSUE TITLE
Add field_serializer to computed_field

### ISSUE THREAD

**Issue by andresliszt** [pydantic/pydantic#6964]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

A nice new feature in pydantic >= 2 is `computed_field` that includes properties into serialization methods. It would be nice, if possible, to use custom serializations in the properties as well. An example of desired versus actual behavior is shown below:

```python
from pydantic import BaseModel, field_serializer, computed_field
from pydantic import BaseModel, field_serializer, computed_field

class Model(BaseModel):
    foo: str

    @computed_field
    @property
    def dummy_property(self) -> str:
        return self.foo + " bar"

    @field_serializer("dummy_property")
    def serialize_dummy_property(self, value):
        return value.upper()


if __name__ == "__main__":
    model = Model(foo="foo")
    print(model.model_dump())
    # Expected: {'foo': 'foo', 'dummy_property': 'FOO BAR'}
    # Actual: pydantic.errors.PydanticUserError: Decorators defined with incorrect fields

```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
Fixed in #6965
