### ISSUE TITLE
Merging field level exclude and model_dump include \ exclude redefinition on instance

### ISSUE THREAD

**Issue by Medved2k** [pydantic/pydantic#6973]
### Discussed in https://github.com/pydantic/pydantic/discussions/6927

<div type='discussions-op-text'>

<sup>Originally posted by **Medved2k** July 28, 2023</sup>
What is expected behavior if you will call model_dump with include field which was constructed with exclude=True ?
doc section https://docs.pydantic.dev/2.0/usage/serialization/#model-and-field-level-include-and-exclude has only examples when field level exclude work with exclude in model_dump or field level include with model_dump include.

Code example:
```
class SideModel(BaseModel):
    id: int = Field(default=123, exclude=True)

model = SideModel()
print(model.model_dump(include={'id'}))
```

To achieve the same goal I've tried to change field exclude \ include on model instance, but result wasn't promising.
```
class SideModel(BaseModel):
    id: int = Field(default=123t, exclude=True)

model = SideModel()
print(model.model_dump(include={'id'}))  # expectations {'id': 123}, got {}
model.model_fields['id'].exclude = None 
print(model.model_dump())  # expectations {'id': 123}, got {}
model.model_fields['id'].exclude = False  
print(model.model_dump())  # expectations {'id': 123}, got {}
model.model_fields['id'].include = True  
print(model.model_dump())  # expectations {'id': 123}, got {}
```</div>

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
We need to improve that part of the documentation. I'll come back to this next week.

**Comment by Medved2k** [comment]
@Kludex you are welcome

**Comment by sydney-runkle** [comment]
I've added some improvements to these docs that resolve the confusion here 😄 
https://docs.pydantic.dev/2.4/concepts/serialization/#model-and-field-level-include-and-exclude
@Medved2k
