### ISSUE TITLE
Pydantic V2 does not allow declare field as subclass of recognized pydantic types

### ISSUE THREAD

**Issue by andresliszt** [pydantic/pydantic#6979]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I marked this as a bug because i could not find documentation on release notes for v2. With pydantic < 2 we can declare fields as subclass of recognized types by pydantic, like this 

```python

from pydantic import BaseModel

class NewInt(int):
    pass

class Model(BaseModel):
    x: NewInt

```
But in pydantic >=2 we get this error ``PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class '__main__.NewInt'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.``

Is it a desired behavior?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
pydantic-core version: 2.4.0
pydantic-core build: profile=release pgo=false mimalloc=true
python version: 3.9.17 (main, Jul  5 2023, 16:17:03)  [Clang 14.0.6 ]
platform: macOS-10.16-x86_64-i386-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
Yes this is by design. You need to implement `__get_pydantic_core_schema__` to tell Pydantic how to handle your type: https://docs.pydantic.dev/latest/usage/types/custom/
