### ISSUE TITLE
model_json_schema() not creating JSON schema when subclassed

### ISSUE THREAD

**Issue by piercsi** [pydantic/pydantic#7004]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In the code below if BaseModel is used rather than the MyBaseModel subclass, then the results are as expected, however with the code below, the JSON schema is not produced and no error is raised.

```
from __future__ import annotations
from pydantic import BaseModel


class MyBaseModel(BaseModel):
    pass


class B(MyBaseModel):
    b: A


class A(MyBaseModel):
    a: str


print(B.model_json_schema())
```

expected result:

`{'$defs': {'A': {'properties': {'a': {'title': 'A', 'type': 'string'}}, 'required': ['a'], 'title': 'A', 'type': 'object'}}, 'properties': {'b': {'$ref': '#/$defs/A'}}, 'required': ['b'], 'title': 'B', 'type': 'object'}`

(or an error advising the model hasn't been initialiased)

actual result:
`
{'properties': {}, 'title': 'MyBaseModel', 'type': 'object'}`

If MyBaseModel has any fields set then it also works ok, e.g. this works as expected:

```
class MyBaseModel(BaseModel):
    x: None
```
Appreciate this is an edge case but thought is worth noting if there's something that can be done.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1                                                                           
        pydantic-core version: 2.4.0                                                                           
          pydantic-core build: profile=release pgo=false mimalloc=true                                         
                 install path: ...s\Python\venv\Lib\site-packages\pydantic        
               python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0                                                       
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by dmontagu** [comment]
Thanks for reporting!

I believe I have found the source of the issue, and have opened a PR to resolve it #7020.
