### ISSUE TITLE
Allow partial parametrization of Generic classes

### ISSUE THREAD

**Issue by NicolaDonelli** [pydantic/pydantic#7006]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I believe this issue might be linked to #6980 and probably I am missing something, but I really do not get why the code below throws a TypeError:

```
TypeError: All parameters must be present on typing.Generic; you should inherit from typing.Generic[~KE, ~KD, ~E, ~D, ~Q] (bases=(<class '__main__.BaseGenericClass'>,))
```

I would expect that, as it happens for mypy ***and with pydantic<2.0.0***, having fixed to Dict[str,Any] and str the type variables D and Q in the ChildGenericClass it would become a Generic[KE, KD, E] and throws no error.

Can anyone explain me what I am missing (and maybe how to avoid this situation)?

### Example Code

```Python
from pydantic import BaseModel
from typing import Any, Dict, Generic, TypeVar

KE = TypeVar("KE") 
KD = TypeVar("KD")
E = TypeVar("E", bound=BaseModel)
D = TypeVar("D")
Q = TypeVar("Q")

class BaseGenericClass(Generic[KE, KD, E, D, Q], BaseModel):
    uid: str
    name: str
    
class ChildGenericClass(
    BaseGenericClass[KE, KD, E, Dict[str, Any], str],
):
    ...
```

### Python, Pydantic & OS Version

```Text
Python: 3.8.16
Pydantic: 2.1.1
OS: MacOS Ventura 13.4.1
```

Selected Assignee: @lig

**Comment by lig** [comment]
@NicolaDonelli thank you for the request. Currently Pydantic v2 requires full parametrization of a Generic models. Partial parametrization isn't supported yet.

This looks like a legitimate feature request to me. A PR solving this would be highly appreciated.

**Comment by dmontagu** [comment]
Putting the `Generic` _after_ `BaseModel` in the class declaration fixes this issue, as far as I can tell:
```python
from pydantic import BaseModel
from typing import Any, Dict, Generic, TypeVar

KE = TypeVar("KE") 
KD = TypeVar("KD")
E = TypeVar("E", bound=BaseModel)
D = TypeVar("D")
Q = TypeVar("Q")

class BaseGenericClass(BaseModel, Generic[KE, KD, E, D, Q]):
    uid: str
    name: str
    
class ChildGenericClass(
    BaseGenericClass[KE, KD, E, Dict[str, Any], str],
):
    ...
```
Is there a reason that you'd want to put `Generic` first? Otherwise, I would suggest that we just make a clearer error message if you try putting `Generic` before `BaseModel`.

**Comment by dmontagu** [comment]
Also, I'll just note that I believe this is a separate issue unrelated to #6980.

**Comment by yvalencia91** [comment]
> Putting the `Generic` _after_ `BaseModel` in the class declaration fixes this issue, as far as I can tell:
> 
> ```python
> from pydantic import BaseModel
> from typing import Any, Dict, Generic, TypeVar
> 
> KE = TypeVar("KE") 
> KD = TypeVar("KD")
> E = TypeVar("E", bound=BaseModel)
> D = TypeVar("D")
> Q = TypeVar("Q")
> 
> class BaseGenericClass(BaseModel, Generic[KE, KD, E, D, Q]):
>     uid: str
>     name: str
>     
> class ChildGenericClass(
>     BaseGenericClass[KE, KD, E, Dict[str, Any], str],
> ):
>     ...
> ```
> 
> Is there a reason that you'd want to put `Generic` first? Otherwise, I would suggest that we just make a clearer error message if you try putting `Generic` before `BaseModel`.

@dmontagu, I went with your suggestion. Hope this can help.

**Comment by sokolegg** [comment]
Guys, what are you doing, I don't understand.

I am migrating from pydantic 1.x to 2.x and that is craxy, I don't want this generic things and sctrict typing mode and few libraries for one line of code
