### ISSUE TITLE
`model_validator(mode="before")` decorated method on `Enum` is not being called

### ISSUE THREAD

**Issue by ivenw** [pydantic/pydantic#7037]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to use `pydantic.mode_validator` together with an `Enum` and am encountering unexpected behaviour.

With the example code I am expecting that I can validate `MyEnum` from a json string with the values `x` and `y`.

Instead, I am encountering the following error. 

`in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
enum
  Input should be 'a' or 'b' [type=enum, input_value='x', input_type=str]`

This indicates to me that the decorated `_validate()` method is not being called.

In my use case, the `_validate()` method serves to translate between two languages, which is maybe a bit exotic, so if this is intended behaviour I understand, it just looked like something that should work. (I used the same approach in the same code base to construct a `dataclass` from a string.)

If it is a bug, cheers for looking into this and congratulations on V2! 🎉

### Example Code

```Python
from enum import Enum
from typing import Any

import pydantic


class MyEnum(Enum):
    A = "a"
    B = "b"

    @pydantic.model_validator(mode="before")
    @classmethod
    def _validate(cls, v: Any) -> Any:
        if not isinstance(v, str):
            return v

        MAPPING = {
            "x": cls.A,
            "y": cls.B,
        }
        try:
            return MAPPING[v].value
        except KeyError:
            raise ValueError(
                f"Input must be one of {list(MAPPING.keys())}, but got '{v}'."
            )


class MyModel(pydantic.BaseModel):
    enum: MyEnum


MyModel.model_validate_json('{"enum": "x"}')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
               python version: 3.10.12 (main, Jun  7 2023, 00:48:25) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.6.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by adriangb** [comment]
This is not a bug, it's a feature request, we don't support `@model_valdiator` on Enums. And I don't think we'll be adding it anytime soon. Unrelated but in general I'd recommend you use `Literal` instead of enums for simple cases like this (string values).

If you want to always run some validation every time the enum gets validated I'd recommend something like `ValidatedMyEnum = Annotated[MyEnum, AfterValidator(<your logic>)]` and then using that type everywhere.

**Comment by ivenw** [comment]
Thanks for the reply. It wasn't really clear to me that this is not supported. I would not endorse this as a feature request myself actually. Will close.
