### ISSUE TITLE
Float default values can lead to unexpected warning (Expected `float` but got `int` - serialized value may not be as expected)

### ISSUE THREAD

**Issue by bluenote10** [pydantic/pydantic#7041]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A `BaseModel` with a `float` field that has a default can produce some unexpected serialization warnings. Let's assume we have a function with the signature `get_default_value() -> float` that defines the default. Note that from a type system perspective that function may return an `int`, i.e., this would be valid:

```py
def get_default_value() -> float:
    return 42

class MyModel2(BaseModel):
    x: float = get_default_value()
```

Trying to serialize an instance created of model warns with:

```
UserWarning: Pydantic serializer warnings:
  Expected `float` but got `int` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

Of course, there is a simple, but unexpected work-around by changing the definition to `x: float = float(get_default_value())`.

Especially if `get_default_value` comes from an external source this may be a bit fragile, because `get_default_value()` may work today, but if the externally defined changes to return an `int` instead of an actual `float` the warning could creep in.

For this reason it would be nice if the default value could be treated consistently with the case of passing the value in explicitly.

### Example Code

```Python
from pydantic import BaseModel

def get_default_value() -> float:
    return 42

class MyModel1(BaseModel):
    x: float

class MyModel2(BaseModel):
    x: float = get_default_value()

print("Serializing MyModel1")
print(MyModel1(x=get_default_value()).model_dump())

print("Serializing MyModel2")
print(MyModel2().model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/me/my_venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
                     platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by samuelcolvin** [comment]
Thanks for reporting.

It looks like there's very special logic for `float` and in, from [PEP 484](https://peps.python.org/pep-0484/#the-numeric-tower:~:text=when%20an%20argument%20is%20annotated%20as%20having%20type%20float%2C%20an%20argument%20of%20type%20int%20is%20acceptable):

> when an argument is annotated as having type `float`, an argument of type `int` is acceptable

I'll fix in pydantic.
