### ISSUE TITLE
different behavour of model_dump() and model_dump_json() with computed fields

### ISSUE THREAD

**Issue by Rossco8** [pydantic/pydantic#7048]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

when serialising a model with computed fields, there is different behavour between `model_dump(exclude_unset=True, exclude_none=True)` and `model_dump_json(exclude_unset=True, exclude_none=True)` when a computed field is None

### Example Code

```Python
from typing import Optional
from pydantic import BaseModel, computed_field

class Rectangle(BaseModel):
    width: int
    length: int
    cost_of_paint_per_unit_area: Optional[float | None] = None

    @computed_field(return_type=int|None)
    @property
    def area(self) -> int:
        return self.width * self.length

    @computed_field(return_type=float|None)
    @property
    def cost_to_paint(self) -> int:
        if self.cost_of_paint_per_unit_area is None:
            return None
        else:
            return self.area * self.cost_of_paint_per_unit_area
```

>>> print(Rectangle(width=3, length=2).model_dump(exclude_unset=True, exclude_none=True))
{'width': 3, 'length': 2, 'area': 6}
>>> print(Rectangle(width=3, length=2).model_dump_json(exclude_unset=True, exclude_none=True))
{"width":3,"length":2,"area":6,"cost_to_paint":null}

The computed field is excluded with model_dump() and included with model_dump_json()
```


### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/rossco/vs-projects/scratchpad/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.10 (main, Feb 16 2023, 02:46:59) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.6-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @lig

**Comment by harunyasar** [comment]
What I understood is that the `exclude_unset` argument only excludes fields that are explicitly set to `None`. The `cost_to_paint` field in your `Rectangle` model is not explicitly set to `None`, it is computed dynamically based on the values of the `area` and `cost_of_paint_per_unit_area` fields. Therefore, the `cost_to_paint` field is not excluded from the serialised output, even if it is `None`. In short, problem is not on argument `exclude_unset`, the problem is on `exclude_none` argument. Apparently, having a `computed_field` might have been overlooked somehow. For further reference you can check this https://github.com/pydantic/pydantic-core/pull/768 issue. What I can recommend is that just get rid of computed fields and rather use only properties. So, what I mean is that:

```python
class Rectangle(BaseModel):
    width: int
    length: int
    cost_of_paint_per_unit_area: Optional[float] = None

    @property
    def area(self) -> Optional[int]:
        return self.width * self.length

    @property
    def cost_to_paint(self) -> Optional[float]:
        if self.cost_of_paint_per_unit_area is None:
            return None
        else:
            return self.area * self.cost_of_paint_per_unit_area


r = Rectangle(width=10, length=10)

print(
    r.model_dump(exclude_none=True),
    r.model_dump_json(exclude_none=True),
    sep="\n",
)

# {'width': 10, 'length': 10, 'area': 100}
# {"width":10,"length":10,"area":100}
```

**Comment by Rossco8** [comment]
Yes it definitely appears that the `exclude_none` argument to `model_dump_json()` is ignored. Looking at the linked issue it should be picked up by that ticket

Thanks for the suggestion to just use a property instead of a computed field, regardless of any issue with model_dump_json() simply using a property would remove a layer of complexity.

**Comment by enricotagliani** [comment]
@Rossco8 I can confirm that the `model_dump_json(exclude_none=True)` case is not resolved yet. I've commented with details on https://github.com/pydantic/pydantic-core/pull/768 . Maybe it could be usefull to also reopen this issue?
