### ISSUE TITLE
HttpUrl should be assignable to str

### ISSUE THREAD

**Issue by conservative-dude** [pydantic/pydantic#7071]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I use https://github.com/encode/databases for database access and normally I would write something like:
```
class MyPydanticModelWithHttpUrlField(BaseModel):
    file_url: HttpUrl | None

async def add_all(self, models: list[MyPydanticModelWithHttpUrlField]):
    values = []
    for x in models:
        dump = x.model_dump()
        values.append({**dump})

    await self.db.execute_many(
        query="INSERT INTO mytable (file_url) VALUES (:file_url)",
        values=values
    )
```

This code works fine with pydantic v1 but since I've migrated to pydantic v2, I get the following error:
```
...
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $3: Url('https://myurl... (expected str, got Url)
```

I've just discovered that [Url and Dsn types in pydantic.networks no longer inherit from str](https://docs.pydantic.dev/2.0/migration/#url-and-dsn-types-in-pydanticnetworks-no-longer-inherit-from-str). 

I use HttpUrl in many places around database access layer, is there anything I can do to *not* invoke str() function every time I need its string representation?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: <redacted>/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.0-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```
```


Selected Assignee: @samuelcolvin

**Comment by ScrimForever** [comment]
@Kludex 

I have same problem. There is no road map to implement str to it ?

**Comment by samuelcolvin** [comment]
I really don't think conceptually it makes sense for the URL types to inherit from `str`.

Probably the best option would be to create your own type which uses an after validator to convert the value to a str.

I'm afk, but can give an example later if required.

**Comment by ScrimForever** [comment]
@samuelcolvin 
I apreciate your help. If is possible exemple i want to see.

**Comment by ScrimForever** [comment]
Update.

I used  .__str__()  on url field in schema on persist in database. 
@conservative-dude . 
Try this

**Comment by conservative-dude** [comment]
@ScrimForever thanks, but if you look in my code I posted initially, you'd see that I used automatic conversion and there's nowhere where I copy fields values manually. If now I have to always use `str`, it kinda ruins the idea of having very succinct code, not mentioning that I have to somehow check all usages of that type...

@samuelcolvin I ended up with using this type alias in my models:
```python
HttpUrlSerialisableToString = Annotated[
    HttpUrl, PlainSerializer(lambda x: str(x), return_type=str)
]
```

Though I don't fully get the benefits of HttpUrl (or any plain-looking type really) which is not serialisable to a string without tweaks ¯\_(ツ)_/¯

**Comment by paulcwatts** [comment]
I just ran into this while migrating my V1 app to V2. 

With all respect to @samuelcolvin (I love Pydantic), I would agree to disagree that URL types should inherit from `str`. In my mind, the URI [RFC](https://www.rfc-editor.org/rfc/rfc3986) defines URIs as "a sequence of characters." If a URI *is a* sequence of characters, OOP design would suggest inheritance to be a correct abstraction for an "is a" relationship. 

That said, even if the URL types were not to inherit from `str`, I don't know who would expect that the default serialization of these types would be `Url('https://....')`. Certainly I didn't.  To me, it violates the [Principal of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by paulcwatts** [comment]
For what it's worth, if you want a model that just contains a `str` that is validated as a URL, you can use the following:

```python
from typing import Annotated
from pydantic import BeforeValidator, AnyUrl as _AnyUrlBase, TypeAdapter

_AnyUrlAdapter = TypeAdapter(_AnyUrlBase)
AnyUrl = Annotated[str, BeforeValidator(lambda v: str(_AnyUrlAdapter.validate_python(v)))]
```

You can do similar with any of the other `*Url` types.

**Comment by senese** [comment]
Seeing that this issue is not so popular I don't think this should change (at least in the near future), but for me is pretty obvious that a URL should inherit from string. A URL can't be casted to int, dict, datetime or any other type, unless to a simply **string**.

With the current behavior, if you use Pydantic especially in your domain entities, you have to cast to string to every function or constructor that (imho) correctly assumes that a URL is a string: DB connections, HTTP requests, DTO's, File Descriptors, etc.

I know there is some workarounds, but as @paulcwatts says: it definitely violates the Principal of Least Astonishment.
