### ISSUE TITLE
Unexpected evaluation of Union

### ISSUE THREAD

**Issue by finswimmer** [pydantic/pydantic#7085]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hey,

when using `Union` for an attribute my expectation is, that `pydantic` prefers the models from left to right. Usually this works as expected :smile: 

Now I've found a situation where one of the models within the `Union` contains an attribute of type `datetime.date` and suddenly `pydantic` prefers the model that is more on the right site.

In the example code below I would expect, that `parent.child` would be of type `Child2`, but instead it is `Child1`. If I remove `attr4` from the `Child2` class, `parent.child` becomes a `Child2` type.

### Example Code

```Python
import datetime

from pydantic import BaseModel


class Child1(BaseModel):
    attr1: str
    attr2: str


class Child2(BaseModel):
    attr1: str
    attr2: str
    attr3: str
    attr4: datetime.date


class Parent(BaseModel):
    child: Child2 | Child1


child_data = {"attr1": "a", "attr2": "b", "attr3": "c", "attr4": "2023-08-11"}

child_1 = Child1.model_validate(child_data)
print(child_1)
# attr1='a' attr2='b'

child_2 = Child2.model_validate(child_data)
print(child_2)
# attr1='a' attr2='b' attr3='c' attr4=datetime.date(2023, 8, 11)

parent = Parent.model_validate({"child": child_data})
print(parent)
# child=Child1(attr1='a', attr2='b')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/finswimmer/tmp/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.7 (main, Sep 29 2022, 11:05:06) [GCC 9.4.0]
                     platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by finswimmer** [comment]
If `attr4` in the example above is not a String, but already a `datetime.date`, `pydantic` successfully choose the `Child2` model :thinking: 

```python
import datetime

from pydantic import BaseModel


class Child1(BaseModel):
    attr1: str
    attr2: str


class Child2(BaseModel):
    attr1: str
    attr2: str
    attr3: str
    attr4: datetime.date


class Parent(BaseModel):
    child: Child2 | Child1


child_data = {"attr1": "a", "attr2": "b", "attr3": "c", "attr4": datetime.date.fromisoformat("2023-08-11")}

child_1 = Child1.model_validate(child_data)
print(child_1)
# attr1='a' attr2='b'

child_2 = Child2.model_validate(child_data)
print(child_2)
# attr1='a' attr2='b' attr3='c' attr4=datetime.date(2023, 8, 11)

parent = Parent.model_validate({"child": child_data})
print(parent)
# child=Child2(attr1='a', attr2='b', attr3='c', attr4=datetime.date(2023, 8, 11))
```

**Comment by finswimmer** [comment]
Workaround: Add a `field_validator` that converts the String to a date:

```python
import datetime

from pydantic import BaseModel, field_validator


class Child1(BaseModel):
    attr1: str
    attr2: str


class Child2(BaseModel):
    attr1: str
    attr2: str
    attr3: str
    attr4: datetime.date

    @field_validator("attr4", mode="before")
    @classmethod
    def to_date(cls, value: str | datetime.date) -> datetime.date:
        if type(value) == str:
            value = datetime.date.fromisoformat(value)

        return value


class Parent(BaseModel):
    child: Child2 | Child1


child_data = {"attr1": "a", "attr2": "b", "attr3": "c", "attr4": "2023-08-11"}

child_1 = Child1.model_validate(child_data)
print(child_1)
# attr1='a' attr2='b'

child_2 = Child2.model_validate(child_data)
print(child_2)
# attr1='a' attr2='b' attr3='c' attr4=datetime.date(2023, 8, 11)

parent = Parent.model_validate({"child": child_data})
print(parent)
# child=Child2(attr1='a', attr2='b', attr3='c', attr4=datetime.date(2023, 8, 11))
```

**Comment by Kludex** [comment]
What's the real use case you have? Is it that one? I think the behavior is fine, but I'm going to ask the team.

**Comment by AlexanderFarkas** [comment]
Shouldn't it choose more specific option from the union?

**Comment by finswimmer** [comment]
> What's the real use case you have? Is it that one? 

Yes, the real use case is very similar to the minimal working example. I have two models, where one is an extended one of the first model (In fact `Child2` could inherit from `Child1` instead of defining all equal attributes again.) I receive the data for the two models as a dict and in case of the extended model, the date is given as a String.

> I think the behavior is fine, but I'm going to ask the team.

If that's the case, it would be helpful to understand the rational behind this :smiley:

**Comment by AlexanderFarkas** [comment]
I experience weird opposite behaviour:
```python
import enum
from typing import reveal_type

from pydantic import BaseModel, ConfigDict, RootModel


class IssueActionType(str, enum.Enum):
    MENTIONED = "mentioned"
    NOTE_ADDED = "note_added"
    RESOLVED = "resolved"
    REOPENED = "reopened"


class BaseDTO(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str


class IssueDTO(BaseDTO):
    model_config = ConfigDict(from_attributes=True)

    issue_action_type: IssueActionType
    issue_id: str


class SimpleDTO(BaseDTO):
    model_config = ConfigDict(from_attributes=True)


class NotificationDTO(
    RootModel
):
    root: IssueDTO | SimpleDTO


d = {
    'id': '1',
    'issue_action_type': 'reopened',
    'issue_id': '09f6d700-6d45-44fe-95bf-f064db1f153e',
}

dto = NotificationDTO.model_validate(d)
reveal_type(dto.root) # Runtime type is 'SimpleDTO'
```

For some reason, the least compatible type is selected

**Comment by AlexanderFarkas** [comment]
@Kludex Now it's impossible to return anyOf in FastAPI, if there is not discrimation key (it used to be possible, since the most specific option was selected)

**Comment by MarkusSintonen** [comment]
This is an interesting issue. This might be also an issue in Python itself. It doesnt unfortunately guarantee much about the ordering of type unions… https://github.com/python/cpython/issues/103749 Its also unfortunate that the behavior in PydanticV2 took turn to a ”worse” as PydanticV1 was better in a sense that it considered ordering of type unions. So from user perspective V1 made more sense on its coercion.

**Comment by finswimmer** [comment]
> Its also unfortunate that the behavior in PydanticV2 took turn to a ”worse” as PydanticV1 was better in a sense that it considered ordering of type unions.

As shown in my [workaround](https://github.com/pydantic/pydantic/issues/7085#issuecomment-1674300701) v2 consider ordering of type unions as well. But it seems something goes wrong when a type conversion comes in to play.

**Comment by samuelcolvin** [comment]
This should be solved by adding `dumb_union` as per https://github.com/pydantic/pydantic/issues/7097#issuecomment-1677134952.

With regard to the specific issues around `date`, could they be related to https://github.com/pydantic/pydantic/issues/7065?

**Comment by samuelcolvin** [comment]
> Why new opt-in parameter instead of making it work like before?

Because the "dumbness" of the union behaviour in V1 was one of the most common criticisms of V1, and I think what we have now, while not perfect, is much better than the V1 behaviour.

**Comment by rockisch** [comment]
Maybe I'm missing something, but isn't this issue solved by defining `child` as:
```py
child: Annotated[Union[Child2, Child1], Field(union_mode="left_to_right")]
```
?

Running on my machine, the last example returns `Child2`.
