### ISSUE TITLE
Inconsistent return types of `BaseModel.model_dump_json` and `TypeAdapter.dump_json` (`str` vs `bytes`)

### ISSUE THREAD

**Issue by bluenote10** [pydantic/pydantic#7088]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It looks like there is an inconsistency of the return types when dumping JSON with either `BaseModel` or `TypeAdapter`:

- [`BaseModel.model_dump_json`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_dump_json) returns a `str`
- [`TypeAdapter.dump_json`](https://docs.pydantic.dev/latest/api/type_adapter/#pydantic.type_adapter.TypeAdapter.dump_json) returns `bytes`.

This feels unintended and makes switching from one to the other slightly awkward.

Of course if there is a good reason for the inconsistency it would help to document it.

### Example Code

```Python
from pydantic import BaseModel, TypeAdapter

class MyModel(BaseModel):
    dummy: int

MyTypeAdapter = TypeAdapter(int)

# At runtime this will show:
# <class 'str'>
# <class 'bytes'>
print(type(MyModel(dummy=42).model_dump_json()))
print(type(MyTypeAdapter.dump_json(42)))

# The same can also be verified at type-checking-time, yielding:
# debug_dump_json_bytes_vs_str.py:13: note: Revealed type is "builtins.str"
# debug_dump_json_bytes_vs_str.py:14: note: Revealed type is "builtins.bytes"
reveal_type(MyModel(42).model_dump_json())
reveal_type(MyTypeAdapter.dump_json(42))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/ekf2abt/workspace/maploc/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
                     platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by kovaxis** [comment]
Why did the decision lean towards efficiency on `TypeAdapter` but ease of use on other models? It seems to me like they are completely separate concerns.
