### ISSUE TITLE
Input should be in a valid time format, input is too short

### ISSUE THREAD

**Issue by AlexanderFarkas** [pydantic/pydantic#7089]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It used to work in Pydantic 1.

Error:
`Input should be in a valid time format, input is too short [type=time_parsing, input_value='9:00', input_type=str]`

### Example Code

```Python
import datetime 
from pydantic import BaseModel

class MyModel(BaseModel):
  start_time: datetime.time
  
MyModel(start_time="9:00")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
pydantic-core version: 2.4.0
pydantic-core build: profile=release pgo=false mimalloc=true
install path: /Users/username/Library/Caches/pypoetry/virtualenvs/my_project-py3.10/lib/python3.10/site-packages/pydantic
python version: 3.10.4 (main, Jun 24 2022, 18:30:49) [Clang 13.1.6 (clang-1316.0.21.2.5)]
platform: macOS-13.0.1-arm64-arm-64bit
optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by Kludex** [comment]
Yeah, the output is correct.

You can check how we do the conversions on our [Conversion Table](https://docs.pydantic.dev/latest/usage/conversion_table/).

In your case, the following would already work:
```py
import datetime
from pydantic import BaseModel


class MyModel(BaseModel):
    start_time: datetime.time


MyModel(start_time="00:09:00")
```
