### ISSUE TITLE
type casting does not work with multiple attributes of the same custom type

### ISSUE THREAD

**Issue by hiaselhans** [pydantic/pydantic#7102]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I tried to upgrade a custom data type from pydantic v1 to v2.

It looks like the type casting works as long as there is only one attribute of the type assigned to a model.
When there are two, a validation error is raised:

``` python
ValidationError: 1 validation error for Test2
y
  Input should be a valid dictionary or instance of Numeric [type=model_type, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.1/v/model_type
```

I attached a minimal example down below.
Maybe the schema generation isn't done as it should be. I am happy to add some more documentation if someone guides me to the right solution for this example

### Example Code

```Python
from typing import Any, Self
import pydantic
from pydantic_core import CoreSchema, core_schema

class Numeric(pydantic.BaseModel):
    value: float
    unit: str = "m"

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: pydantic.GetCoreSchemaHandler
    ) -> CoreSchema:
        return core_schema.no_info_before_validator_function(cls.validate, handler(source_type))

    @classmethod
    def validate(cls, v: Any) -> dict[str, Any] | Self:
        if isinstance(v, (str, float, int)):
            return cls(value=v)
        elif isinstance(v, Numeric):
            if v.unit == cls.unit:
                return v
        elif isinstance(v, dict):
            return v

        raise ValueError(f"Invalid value for {cls}: {v}")

class Test1(pydantic.BaseModel):
    x: Numeric

class Test2(pydantic.BaseModel):
    x: Numeric
    y: Numeric

print("test1:", Test1(x=2))
print("test2:", Test2(x=2, y=2))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/xxx/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
                     platform: Linux-6.4.7-arch1-1-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by jakemoran** [comment]
Also experiencing this issue, very similar use case to the example shown above.

**Comment by dmontagu** [comment]
This definitely seems to me like a bug with the schema generation, though I'll note that I'm not surprised to see issues coming from overriding `BaseModel.__get_pydantic_core_schema__`. I suspect that there are some assumptions somewhere about the presence or values of `ref`s in the core schema. Not sure. CC @adriangb

At any rate, here is another approach that perhaps might work better for you using a `BeforeValidator` annotation:
```python
from typing import Any, Self, Annotated

import pydantic
from pydantic.functional_validators import BeforeValidator


class Numeric(pydantic.BaseModel):
    value: float
    unit: str = "m"

    @classmethod
    def validate(cls, v: Any) -> dict[str, Any] | Self:
        if isinstance(v, (str, float, int)):
            return cls(value=v)
        elif isinstance(v, Numeric):
            if v.unit == cls.unit:
                return v
        elif isinstance(v, dict):
            return v

        raise ValueError(f"Invalid value for {cls}: {v}")


NumericField = Annotated[Numeric, BeforeValidator(Numeric.validate)]


class Test1(pydantic.BaseModel):
    x: NumericField


class Test2(pydantic.BaseModel):
    x: NumericField
    y: NumericField


print("test1:", Test1(x=2))
print("test2:", Test2(x=2, y=2))
```

**Comment by adriangb** [comment]
Any reason not to use a `@model_validator` with `mode='before'`?

**Comment by hiaselhans** [comment]
@model_validator does work, thanks for the hint!

Nonetheless, this seems to be a bug in schema-generation.
Should i close the issue or leave it open?

**Comment by jakemoran** [comment]
My reasoning for not wanting to use `@model_validator` has to do with the fact that I have a bunch of models that make use of a field type defined like this, and I'd like to avoid repeating the same validator in each model if possible.

Using the `BeforeValidator` annotation would work, but I would prefer to have the field type annotation and the type the field is resolved to be the same. Using `__get_pydantic_core_schema__` seems like a nice solution because it just defines the schema on the type itself. That's a minor improvement at best though, and I understand that validator annotations are the general recommendation. It would still be nice to see this fixed, though.
