### ISSUE TITLE
Pydantic is serializing Decimals as string.

### ISSUE THREAD

**Issue by tanshu** [pydantic/pydantic#7120]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic v2 is serializing Decimals as strings and not numbers. It may have been done to overcome decimal to float conversion issues, but in the frontend, since the numbers are now strings, logic is affected.

Model
```
class Item(BaseModel):
   amount: Decimal
```
pydantic v1 .json() would dump Decimal as follows:
```
>>> print(Item(amount=100).json())
{"amount":100}
```
pydantic v2 .model_dump_json() dumps Decimal as follows:
```
print(Item(amount=100).model_dump_json())
>>> {"amount":"100"}
```

In the front end, all numbers are treated as string and operations fail. Is there a way to make sure that Decimals dump as numbers and not string?

Thanks

### Example Code

```Python
from decimal import Decimal
from pydantic import BaseModel
class Item(BaseModel):
   amount: Decimal
 
print(Item(amount=100).model_dump_json())
>>> {"amount":"100"}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/tanshu/.cache/pypoetry/virtualenvs/brewman-C3_Ccu4O-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
                     platform: Linux-6.2.0-27-generic-x86_64-with-glibc2.37
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by samuelcolvin** [comment]
This was requested many times in v1 and was therefore changed in v2 - it was intentional.

You can change the behavior with a custom serializer.

**Comment by Kos** [comment]
For future readers, here's a snippet that lets you restore the v1 behaviour:

```
class YourModel(BaseModel):
    value: Decimal

    model_config = ConfigDict(json_encoders={Decimal: decimal_encoder})
```

You'll also need to bring back the implementation of `decimal_encoder` from Pydantic v1, [see source here](https://github.com/pydantic/pydantic/blob/76222d2e7ed90c13816dff1b71bc0f3cf3d7c018/pydantic/deprecated/json.py#L33).

Hoping this will make your upgrade path to v2 smoother.
