### ISSUE TITLE
Schema generator generates duplicate** `SessionInput` and `SessionOutput` components

### ISSUE THREAD

**Issue by sebastianvitterso** [pydantic/pydantic#7125]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We're using FastAPI (0.101.0) and Pydantic (2.1.1), as well as [ferdikoomen/openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen) (0.25.0) for typescript API- and type-generation. 

We recently migrated our application from Pydantic v1 to v2, with all related changes, but didn't notice this change until yesterday: When running our code generator tool (which reads fastapi's openapi.json endpoint), two versions of every class gets a type.

We can't seem to figure out why this is, other than that it changed between v1 and v2, and I can't see any documentation directly using the terms `Input` and `Output` in verbatim.

Note that we use our domain models as input parameters for our requests, and also as the return type of some requests. The expected behaviour (from having a single Python-class) is to get a single OpenAPI component, and thus a single generated type from the generator.

** "Duplicate" isn't entirely true, as there is a slight difference between the classes when it comes to whether a property is required or not (in a nested object property). Note that we haven't explicitly made this difference in our class in Python, so it seems unintuitive that they should show up in the generated component.

### Example Code

See my second _comment_ to see python code.

### Python, Pydantic & OS Version

```Text
$ python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/SVIT/.pyenv/versions/3.11.2/envs/de4rm3.11.2/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Jun  5 2023, 14:05:12) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by hramezani** [comment]
@sebastianvitterso I didn't get what is the problem. do you have a duplicate item in the generated schema by `model_json_schema`?

Could you please explain the problem more by providing the wrong schema and what you expect

**Comment by sebastianvitterso** [comment]
Relevant (actual) Python code:

```python
AbstractSetIntStr = Set[int | str]
MappingIntStrAny = Mapping[int | str, Any]
IncEx = set[int] | set[str] | dict[int, Any] | dict[str, Any] | None

class BaseModelWrapper(BaseModel):
    """BaseModel wrapper class."""

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    def model_dump(
        self,
        *,
        mode: Literal["json", "python"] | str = "python",
        include: IncEx = None,
        exclude: IncEx = None,
        by_alias: bool = True,
        exclude_unset: bool = False,
        exclude_defaults: bool = False,
        exclude_none: bool = False,
        round_trip: bool = False,
        warnings: bool = True,
    ):
        """Override of Pydantic's model_dump method, with by_alias=True as default."""
        return super().model_dump(
            mode=mode,
            include=include,
            exclude=exclude,
            by_alias=by_alias,
            exclude_unset=exclude_unset,
            exclude_defaults=exclude_defaults,
            exclude_none=exclude_none,
            round_trip=round_trip,
            warnings=warnings,
        )


class Session(BaseModelWrapper):
    """Class that defines the Session object."""

    id: str = Field(..., alias="_id")
    name: str
    created_date: str
    last_updated: str
    status: str
    user: str
    workfolder: Workfolder
    steps: list[Step]
    inp_file_sets: list[InpFileSet] = []
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "_id": "dh2109",
                "name": "huehue",
                "createdDate": "1990-01-01 00:00:00",
                "lastUpdated": "1990-01-01 00:00:00",
                "status": "draft",
                "user": "Admin",
                "workfolder": {
                    "location": "/WORKFOLDERS/huehue_dh2109",
                },
                "steps": [
                    {
                        "index": StepIndex.SETUP,
                        "eclipseFilesPaths": {
                            "UNRST": "/WORKFOLDERS/huehue_dh2109/step1/test.UNRST",
                            "INIT": "/WORKFOLDERS/huehue_dh2109/step1/test.INIT",
                            "EGRID": "/WORKFOLDERS/huehue_dh2109/step1/test.EGRID",
                        },
                    }
                ],
            }
        }
    )

    # ... other methods


class Workfolder(BaseModelWrapper):
    """Helper class to represent the workfolder (base_location directory) we are working with."""

    location: Path
    base_directory_exists: bool = False

    @field_serializer("location")
    def serialize_location(self, location: Path, _info) -> str:
        """Serialize Path attribute location."""
        return str(location)

    def __init__(self, location: str, **kwargs):
        super().__init__(
            location=location, base_directory_exists=Path(location).is_dir()
        )

    # ... other methods

**Comment by hramezani** [comment]
I've tried to make your code runnable and check the `Session.model_json_schema()`. it doesn't contain `SessionInput` and `SessionOutput`.

Maybe something is wrong with your schema generator.

**Comment by sebastianvitterso** [comment]
Ok, so it seems that the problem (although related to Pydantic) was introduced in FastAPI 0.101.0, as described in this issue. I'll close this issue, and follow the related discussion in the FastAPI repo: tiangolo/fastapi/discussions/10019
