### ISSUE TITLE
model_validator(mode="before") is called twice and in different types

### ISSUE THREAD

**Issue by deivydaslipskis** [pydantic/pydantic#7135]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am migrating to pydantic v2 and when switching from `root_validator` to `model_validator` weird thing occurs. Here is an example of how I used `root_validator`:

```
from pydantic import BaseModel, root_validator


class Scores(BaseModel):
    first: int
    second: int
    third: int

    @root_validator
    def check_score_sum(cls, values: dict[str, int]) -> dict[str, int]:
        """
        Checks if all scores are not more than 100

        """
        print(values)
        print(f"Values type: {type(values)}")

        items = values.values()
        if values and sum(items) > 100:
            raise ValueError("Sum of values cannot be more than 100")
        return values

```

I have noticed from prints that it is called twice (it printed twice in the terminal). The type print shows type `<class 'dict'>`, which is intended and everything seems to work.

Now I have tried using `model_validator`:

```
from pydantic import BaseModel, model_validator


class Scores(BaseModel):
    first: int
    second: int
    third: int

    @model_validator(mode="before")
    def check_score_sum(cls, values: dict[str, int]) -> dict[str, int]:
        """
        Checks if all scores are not more that 100

        """
        items = values.values()
        if values and sum(items) > 100:
            raise ValueError("Sum of values cannot be more than 100")
        return values
```

But now an `AtributeError` occurs. `"Scores object has no attribute values"`. And only **second** print that prints type now prints `<class Scores>`. While first type print prints `<class 'dict'>`.

Is this intended in `model_validator`? Perhaps I am incorrectly using `model_validator` in this example? Also, why validation in both examples is called twice, is this intended?

### Example Code

```Python
from pydantic import BaseModel, model_validator


class Scores(BaseModel):
    first: int
    second: int
    third: int

    @model_validator(mode="before")
    def check_score_sum(cls, values: dict[str, int]) -> dict[str, int]:
        """
        Checks if all scores are not more than 100

        """
        items = values.values()
        if values and sum(items) > 100:
            raise ValueError("Sum of values cannot be more than 100")
        return values
```

### Python, Pydantic & OS Version

```Text
pydantic version - 2.1.0
OS - Ubuntu 22.04 LTS
python - 3.10
```

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
Yes — I think this is intentional. The `model_validator(mode='before')` will receive exactly what is passed to the field of the given type. So, for example, if otherwise unvalidated data is validated, the model_validator will receive a dict. But if you pass an existing `Scores` instance in for the field, the model validator will receive that scores instance.

If you want behavior like the old `root_validator`, I think you should be able to achieve that by dumping the model and/or using it's `__dict__`, depending on exactly the behavior you want. By that I mean, something like this:

```python
from pydantic import BaseModel, model_validator


class Scores(BaseModel):
    first: int
    second: int
    third: int

    @model_validator(mode="before")
    def check_score_sum(cls, values: Any) -> dict[str, int]:
        """
        Checks if all scores are not more than 100

        """
        if isinstance(values, Scores):
            values = values.model_dump()  # or values.__dict__
            # another reasonable option here might be just `return values`
        if not isinstance(values, dict):
            return values  # let the other validators deal with this surprising input
        items = values.values()
        if values and sum(items) > 100:
            raise ValueError("Sum of values cannot be more than 100")
        return values
```

Obviously you can tweak the implementation to your liking. Does that make sense?

**Comment by deivydaslipskis** [comment]
Thank you, this answers my question. Have a nice day!
