### ISSUE TITLE
Ability to pass a context object to the serialization methods

### ISSUE THREAD

**Issue by ornariece** [pydantic/pydantic#7143]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Similarly to how `.model_validate()` accepts a `context` parameter in order "to dynamically update the validation behavior during runtime", it would symmetrically be useful to pass a `context` object to `.model_dump()`/`.model_dump_json()` in order to dynamically update the serialization behavior during runtime.

I have found myself in need of this feature, yet have been stuck with incomplete workarounds.

- In v2, the closest feature is the `json_encoders` parameter of the model config, which allows us to customize the serialization per type. However, there are 2 problems with this approach:
  - The most evident one is the fact that the serialization customization is limited to a per-type approach; that's not flexible enough;
  - The second problem is that using the `json_encoders` is not dynamic, as it is done through the model config. If one were to dynamically customize the serialization, one would have to modify the `model_config.json_encoders` temporarily, and that is not what a model config is supposed to be used for; it's not handy, nor is it safe (what if the model is dumped by another process at while the `json_encoders` have been modified?).
  ```python
  import pydantic
  
  
  class MyCustomType:
      pass
  
  
  class MyModel(pydantic.BaseModel):
      x: MyCustomType
  
  
  m = MyModel(x=MyCustomType())
  # temporarily modify the json_encoders
  m.model_config.json_encoders = {MyCustomType: lambda _: "contextual serialization"}
  print(m.model_dump_json())
  #> {"x": "contextual serialization"}
  # reset the json_encoders
  m.model_config.json_encoders = {}
  ```
- In v1, the closest feature is the `encoder` parameter of `.json()`, which also allows us to customize the serialization per type. While the customization is still limited to a per-type approach, in this case the serialization customization is truly dynamic, in contrary to using `json_encoders`. However, there is another caveat that comes with it: the custom `encoder` function is only called **after** the standard types supported by the `json.dumps` have been dumped, which means one can't have a custom type inheriting from those standard types.
  ```python
  import pydantic
  import pydantic.json
  
  
  class MyCustomType:
      pass
  
  
  class MyModel(pydantic.BaseModel):
      x: MyCustomType
  
  
  m = MyModel(x=MyCustomType())
  
  
  def my_custom_encoder(obj):
      if isinstance(obj, MyCustomType):
          return "contextual serialization"
      return pydantic.json.pydantic_encoder(obj)
  
  
  print(m.json(encoder=my_custom_encoder))
  #> {"x": "contextual serialization"}
  ```

Hence why it would make sense to support passing a custom `context` to `.model_dump()`/`.model_dump_json()`, which would then be made available to the decorated serialization methods (decorated by `@field_serializer` or `@model_serializer`) and to the ``.__get_pydantic_core_schema__()`` method.

```python
import pydantic


class MyCustomType:
    def __repr__(self):
        return 'my custom type'


class MyModel(pydantic.BaseModel):
    x: MyCustomType

    @pydantic.field_serializer('x')
    def contextual_serializer(self, value, context):
        # just an example of how we can utilize a context
        is_allowed = context.get('is_allowed')
        if is_allowed:
            return f'{value} is allowed'
        return f'{value} is not allowed'


m = MyModel(x=MyCustomType())
print(m.model_dump(context={'is_allowed': True}))
#> {"x": "my custom type is allowed"}
print(m.model_dump(context={'is_allowed': False}))
#> {"x": "my custom type is not allowed"}
```

What are your thoughts on this?
I believe it makes sense to implement the possiblity of dynamic serialization customization. I believe that possibility is not yet (fully) covered with what's currently available to us.
What I'm still unsure of is: 
- Should that `context` also be made available to `PlainSerializer` and `WrapSerializer`? 
- In what form should this `context` be made available? While the decorated validation methods have access to such a `context` using their `info` parameter (which is of type `FieldValidationInfo`), the `FieldSerializationInfo` type does not have a `context` attribute;
- And ofc, how to implement it.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @lig

**Comment by dmontagu** [comment]
I've been waiting for someone to request this feature! I think it's 100% reasonable and would like to see it added.

I'm sure we'll get to this at some point, but PR would be very welcome. I think it might require getting hands dirty with pydantic-core and Rust though.

**Comment by davidhewitt** [comment]
#7242 could also benefit from this use-case.

**Comment by arvidfm** [comment]
I'd also be very interested in this. I have some configuration data that I want to serialise into a few different formats (JSON, YAML, environment variables, CLI flags), and some fields should be omitted from some of the formats, and some may have different behaviour or naming based on the target format and the metadata attached to the field.

For now I've decided to just stick to vanilla dataclasses since I found myself having to essentially reimplement the entire serialisation process myself anyway without Pydantic having any way of including context or dynamically omitting fields (at least without traversing the entire model yourself ahead of time to construct an `exclude` dict), but I'm definitely sad about losing out on the free, type-checked deserialisation that Pydantic provided.

**Comment by mjog** [comment]
The third problem with `json_encoders` is that it is ["deprecated and will likely be removed in the future"](https://docs.pydantic.dev/2.6/api/config/#pydantic.config.ConfigDict.json_encoders).

Hard +1 on this. There's a symmetry with custom validation that is currently broken by this. A custom validator can e.g. parse a string from the wire to a better structured type using context, but there is no way to serialise it using context to send it back to the wire.

**Comment by ornariece** [comment]
made a PR for this in pydantic-core: pydantic/pydantic-core#1215
