### ISSUE TITLE
Pickle-like serialization

### ISSUE THREAD

**Issue by danielniccoli** [pydantic/pydantic#7162]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I'm requesting a pickle-like serialisation.

There are cases where you want to pass Pydantic instances between web APIs. When the models are complex and contain `PrivateAttr` fields, or computed fields, `model_dump()` or `dict()` cannot be used to create a dictionary that contains all the fields e.g., `PrivateAttr` fields are not included in the dictionary, even if explicitly set via the `include=` parameter.

Furthermore, if passing the values manually to the `PrivateAttr` fields (`UserAccount.model_construct({"username": "jon_doe", "_guid": "1ec8609e-4", "_secret": "Pa$$w0rd"})`, all dunder names are ignored (complete samples below).

Pickling and unpickling solves this issue, but introduces other problems, that are very difficult to solve. For example, if you pass pickled instances from one app to another, there's a big chance you run into a `ModuleNotFoundError` due to the module structure being different, even if the models itself are 100% identical.

This can be solved by creating input/output models, where the input model takes the initial data, and the output model is used internally to pass data around unvalidated and without computed fields. However, this adds additional overhead to the model definition files that must be kept in sync. And `PrivateAttr` fields must still be "exported" manually anyway.

A solution would be to introduce an "import" function or similar, that would take dunder names and skip both `PrivateAttr(default=...)`, and `PrivateAttr(default_factory=...)` respectively.

This would also require an "export" method that includes `PrivateAttr fields`, but skips computed fields. This could also be achieved by a literal `"__export__"` that could be passed to a models `model_dump(include="__export__")`.

```python
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, PlainSerializer, PrivateAttr, computed_field

config = ConfigDict(
    extra="forbid", frozen=True, hide_input_errors=True, validate_assignment=True
)


class UserAccount(BaseModel):
    """A model shared between two web APIs"""

    model_config = config

    username: str
    _secret = PrivateAttr()
    _guid = PrivateAttr(default_factory=lambda: str(uuid4())[:10])

    @computed_field
    @property
    def guid(self) -> str:
        return self._guid


# User provided input on web API A
user_provided_data = {"username": "jon_doe"}
user1 = UserAccount(**user_provided_data)

# Create a super secure initial password
user1._secret = "Pa$$w0rd"


print(user1.model_dump())
# {'username': 'jon_doe', 'guid': '1ec8609e-4'}
print(user1.model_dump(include={"username"}))
# {'username': 'jon_doe'}
print(user1.model_dump(include={"guid"}))
# {'guid': '1ec8609e-4'}
print(user1.model_dump(include={"username", "guid"}))
# {'username': 'jon_doe', 'guid': '1ec8609e-4'}
print(user1.model_dump(include={"_guid"}))
# {}
print(user1.model_dump(include={"_secret"}))
# {}

# Manually constructing a model does not set `_secret` and passed `_guid` value is ignored.
user2 = UserAccount.model_construct({"username": "jon_doe", "_guid": "1ec8609e-4", "_secret": "Pa$$w0rd"})
print(user2)
# UserAccount(guid='08c729fc-d')
print(user2.model_dump())
# {'guid': '08c729fc-d'}

```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @lig

**Comment by danielniccoli** [comment]
Maybe it could be as simple as adding a `model_deconstruct()` method?

```python
UserAccount.model_construct(user1.model_deconstruct())
```

**Comment by lig** [comment]
@danielniccoli Thanks for answering this.

I think that the requested behavior could lead to various project specific nuances that is hard to support universally. I like the idea of having a `deconstruct` method but its implementation depends strongly on project specifics.

**Comment by lig** [comment]
After a discussion with the team the decision is that there is no plans introducing any way of serialization/deserialization apart from `BaseModel.__init__()`, `BaseModel.model_construct()`, and `BaseModel.model_validate()` in Pydantic in the new future.

It's fairly easy to implement something similar to the @danielniccoli's suggestion above that fits a specific case. However, dealing with private attributes outside of a class should always be considered a custom logic as all cases are different and it's hard to satisfy them all universally.
