### ISSUE TITLE
Add `Trim()` annotation for `str`

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#7164]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This should trim white space and limit max length of `name` to `63`.

```py
class Foobar(BaseModel):
    name: Annotated[str, MaxLen(63), Trim()]
```

See #2104 for more details.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @davidhewitt

**Comment by kashish52** [comment]
Hey @lig can you assign this issue to me. I am a beginner in open source and wanted to contribute so might need some help Thanks in advance.

**Comment by adriangb** [comment]
I mean we basically have this already:

```python
from typing import Annotated

from annotated_types import MaxLen

from pydantic import StringConstraints
from pydantic.main import BaseModel

Trim = StringConstraints(strip_whitespace=True)

class Model(BaseModel):
    x: Annotated[str, MaxLen(max_length=12), Trim]


print(Model(x='hello world     '))
```

**Comment by lig** [comment]
Maybe, it's worth actually including this Trim implementation in the Pydantic and then close these two?

**Comment by lig** [comment]
I think @kashish52 could try doing it. There should be tests for it as well.

@kashish52 there is no need to assign the issue but you can prepare a PR that adds Trim implementation suggested by @adriangb and test for it.

**Comment by adriangb** [comment]
I don't think it is.
