### ISSUE TITLE
Update the Pydantic home page

### ISSUE THREAD

**Issue by nobkd** [pydantic/pydantic#7169]
It just caught my eye that the home page https://pydantic.dev/#v2 still says that v2 is
> In active development now, and due to be released in Spring 2023

This is outdated information and therefore should be updated.

Selected Assignee: @dmontagu

**Comment by hramezani** [comment]
Thanks @nobkd for reporting this 🙏 

I've created a [PR](https://github.com/pydantic/pydantic-site/pull/15) to fix it

**Comment by nobkd** [comment]
I can't see the PR, because `pydantic/pydantic-site` isn't public, but thanks :heart:.

**Comment by nobkd** [comment]
Thank you for updating this 👍
