### ISSUE TITLE
Can I use aliases to nest fields?

### ISSUE THREAD

**Issue by omrihar** [pydantic/pydantic#717]
# Question

I noticed that I can use a schema to flatten nested fields. So, for example, this works:

```py
from pydantic import BaseModel, Schema

class Flatten(BaseModel):
    one: str
    two: str = Schema(..., alias='nested.two')

d = {
    'one': 'one',
    'nested': {'two': 'two'}
}

flattened = Flatten.parse_obj(d)  # or Flatten.from_orm(d) if orm_mode is set
>>> flattened == <Flatten one='one', two='two'>
```

I'm wondering whether it is also possible to de-flatten an input that is flat.
So, for example, 
```py

class Customer(BaseModel):
    name: str
    address: str

class Offer(BaseModel):
    offer_number: str
    customer: Customer
    ...

d = {
    'offer_number': '12345'
    'customer_name': 'alice',
    'customer_address': 'Springfield'
}

unflattened = Offer.parse_obj(d)  # This, of course, doesn't work. 
```

I'm also not sure whether there is a logical syntax to define here, but I did try setting a schema on the customer field, with no success.

**Comment by samuelcolvin** [comment]
I think not really, the closest we have (and I'm not sure it was a good design in the beginning) is [`DSN`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/types.py#L369) which builds a nested object by reading other fields during validation.

However this does require you to include the `custom_name` and `customer_address` field on `Offer`, which perhaps defeats the point.

**Comment by omrihar** [comment]
Thanks! I actually do not need this feature right now, but I was thinking of designing a nested model like this, since it can make it easier to transform a normalized table structure from the database to a nested JSON response in an API. 
Perhaps something like this would be conceivable?

```python
class Customer(BaseModel):
    name: str
    address: str

class Offer(BaseModel):
    offer_number: str
    customer: Customer = Schema(..., flattened_prefix="customer_")
    ...

d = {
    'offer_number': '12345'
    'customer_name': 'alice',
    'customer_address': 'Springfield'
}

unflattened = Offer.parse_obj(d) 
```

**Comment by samuelcolvin** [comment]
100% agree it would be useful.

I think rust's serde library has something like this I've used in the past.

**Comment by Akshay2Agarwal** [comment]
`from pydantic import BaseModel, Schema

class Flatten(BaseModel):
    one: str
    two: str = Schema(..., alias='nested.two')

d = {
    'one': 'one',
    'nested': {'two': 'two'}
}

flattened = Flatten.parse_obj(d)  # or Flatten.from_orm(d) if orm_mode is set
>>> flattened == <Flatten one='one', two='two'>`

While running the above snippet I am getting following:

`pydantic.error_wrappers.ValidationError: 1 validation error for Flatten
nested.two
  field required (type=value_error.missing)`

Is flattening of list really supported? If yes how can do it.

**Comment by samuelcolvin** [comment]
No it's not supported.

This is a discussion about a possible future feature.

**Comment by DrPyser** [comment]
@samuelcolvin @omrihar Hi!

I'm confused.

> I noticed that I can use a schema to flatten nested fields. So, for example, this works:
> ...
> I'm wondering whether it is also possible to de-flatten an input that is flat.

So flattening input data is currently *not* possible using `Field`(previously `Schema`)?

What would be the best way for a user to address this need currently in Pydantic?

**Comment by samuelcolvin** [comment]
Probably `root_validators`, pre or post.

**Comment by DrPyser** [comment]
Okay, thanks. 

I would add a +1 to the "flatten input data" feature described first(i.e. using `alias` with dot notations). I can't see a better API, other than a more general approach of a per-field custom getter function(a bit like `GetterDict` in orm mode).

**Comment by paloderosa** [comment]
With respect to flattening, I was facing a similar issue. I share the way I solved it, in case anybody cares. I had an input dictionary `d` that I wanted flattened to `Flatten`, just like those declared by @omrihar,
```
class Flatten(BaseModel):
    one: str
    two: str = Schema(..., alias='nested.two')

d = {
    'one': 'one',
    'nested': {'two': 'two'}
}
```

I used [**scalpl**](https://github.com/ducdetronquito/scalpl) to make such aliasing possible. This is a library that provides an API for navigating through nested dictionaries. So, I used
```
import typing as T

from scalpl import Cut
from pydantic import BaseModel, Field
from pydantic.utils import GetterDict


class ProxyGetterDict(GetterDict):
    def __getitem__(self, key: str) -> T.Any:
        try:
            return self._obj.get(key)
        except AttributeError as e:
            raise KeyError(key) from e
            
    def get(self, key: T.Any, default: T.Any = None) -> T.Any:
        return self._obj.get(key, default)
    
    
class Flatten(BaseModel):
    one: str
    two: str = Field(..., alias='nested.two')
        
    class Config:
        orm_mode = True
        getter_dict = ProxyGetterDict

d = {
    'one': 'one',
    'nested': {'two': 'two'}
}

proxy = Cut(d)     

Flatten.from_orm(proxy).dict()

>>> Flatten(one='one', two='two')
```

**Comment by JosXa** [comment]
@omrihar I can also see how this could come in handy for `BaseSettings`. Devs seem to enjoy nested JSON or YAML files for their app configuration and having (only a single) `Prefix` in the model's `Config` is somewhat limiting. In large monoliths with lots of settings, I would consider it a good practice to create extremely narrow settings models with only the relevant kv pairs for a particular use case. Thus when all you want to do is extract a few of many values from a field lower down the config hierarchy, the `property.access` saves one from writing many extra models.

**Comment by johtso** [comment]
Could the "unflattening" be similarly achieved by having a single field aliased to a list of field names?

**Comment by TheCleric** [comment]
It's not the fastest solution (about 20-25% slower than manually doing it), but I was able to unpack a flat dict into nest models by creating my own intermediate BaseModel that inherits from Pydantic's BaseModel and then I use as the base class for my models. Feel free to us it, or if you can improve on it, feel free as well:

```python
from typing import Any, Optional, Type, TypeVar

from pydantic.main import BaseModel as PydanticBaseModel

_Model = TypeVar('_Model', bound='BaseModel')

class BaseModel(PydanticBaseModel):
    @classmethod
    def parse_obj(cls: Type[_Model], obj: Any) -> Optional[_Model]:  # type: ignore[override]
        # Pydantic's BaseModel.parse_obj does not parse sub-objects from entries in a flat dict (such as a table row),
        # so we're overriding it to support this use case.
        if not isinstance(obj, dict):
            # Not a dict, let pydantic handle this. No need to test their code.
            return super().parse_obj(obj)  # pragma: no cover

        child_values = {}

        has_data = False

        # See if any of our fields have data in here
        # Loop through all of our fields and check to see if their alias is present in the dict passed via obj
        for member_name, field in cls.__fields__.items():
            if getattr(field.type_, 'parse_obj', None):  # Doing it this way is about 2-3x faster than issubclass(field.type_, BaseModel):
                # This field is a sub-object. Try to parse it in case obj has entries in it that map to this sub-object
                child_values[member_name] = field.type_.parse_obj(obj)
            else:
                # This is just a regular field. Get its alias and check to see if we have data
                alias = field.alias or field.name
                has_data = has_data or obj.get(alias) is not None

        # No data in any of our fields, so return None instead of an object with a bunch of empty fields.
        # Which is what we get back when we parse a dict with no fields to parse_obj
        if not has_data:
            return None

        obj.update(child_values)

        # We have data, go ahead and create our object
        result = cls(**obj)  # type: ignore[call-arg]

        return result
```

Example usage:

```python

class _TestChild(BaseModel):
    z: int

class _TestParent(BaseModel):
    a: _TestChild
    b: str


def test_nested_parse_obj() -> None:
    data = {'b': 'test', 'z': 1}

    model = _TestParent.parse_obj(data)

    assert model is not None

    assert model == {'b': 'test', 'a': { 'z': 1},}
```

This could also likely be modified to pass/receive a prefix like `user_` so that the child data could be namespaced.

**Comment by ra-martin** [comment]
@TheCleric Very helpful approach, thank you!

**Comment by ra-martin** [comment]
@TheCleric 
Alternative using root_validator:

```python
from typing import Optional, List
from pydantic import BaseModel, Field, root_validator


class BaseNestingSupport(BaseModel):

    @root_validator(pre = True)
    def traverse_sources(cls, values):
        for (name, field) in cls.__fields__.items():
            source_selector = field.field_info.extra.get("source")
            if source_selector is not None:
                source_path = source_selector.split(".")

                if not len(source_path) > 0:
                    raise ValueError(
                        f"Invalid source path in {cls.__name__}: {source_selector}"
                    )

                pointer = values
                for selector in source_path:
                    if not selector in pointer:
                        if not field.required:
                            pointer = None
                            break

                        raise ValueError(
                            f"{cls.__name__}: Field {selector} missing, path: '{source_selector}'"
                        )

                    pointer = pointer.get(selector)

                if pointer is not None:
                    values[name] = pointer

        return values

    class Config:
        extra = "ignore"


# Example:


class UserInterest(BaseNestingSupport):  # Child
    title: str = Field(source = "cool_title")
    ident: int = Field(source = "meta.id")
    priority: Optional[int] = Field(source = "meta.prio")


class User(BaseNestingSupport):  # Parent
    username: str = Field(source = "user.name")
    interests: List[UserInterest] = Field(source = "user.profile.interests")


# Imagine this came from some external API
inputObj = {
    "user": {
        "name": "iusearchlinux",
        "profile": {
            "interests": [
                { "cool_title": "Demoscene", "meta": { "id": 1337, "prio": -1 } },
                { "cool_title": "Puppies", "meta": { "id": 1234 } }
            ]
        }
    }
}

print(User.parse_obj(inputObj).json())


# {
#   "username": "iusearchlinux",
#   "interests": [
#     { "title": "Demoscene", "ident": 1337, "priority": -1 },
#     { "title": "Puppies", "ident": 1234, "priority": null }
#   ]
# }



```

**Comment by lowercase00** [comment]
@reformat0r can't thank you enough, this has saved me so many lines of code you have no idea, i'm a heavy user of different structures (nesting/flattening) and transformations (source_fn). Pretty awesome, thanks a lot!

@samuelcolvin would it be fair to consider this a new feature? Do you see any downside on adding this functionality to the source code?

**Comment by jo47011** [comment]
@TheCleric your code (inherting from BaseModel) works perfect.  Thanks 👍 

The only issue I have is using _validators_.  When instantiating an object with __TestParent.from_orm(...)_ I get different cases (depending on the alias_generator) of the attributes in the _validator_ compared to instantiating with __TestParent.parse_obj(...)_.

**Comment by septatrix** [comment]
Something similar is already possible for [`BaseSetting` using `env_nested_delimiter`](https://pydantic-docs.helpmanual.io/usage/settings/#parsing-environment-variable-values). Maybe the logic could be moved up to `BaseModel` (of which `BaseSettings` is a subclass) to have a consistent way of archiving this. The name of the config attribute would have to be adjusted to e.g. `nested_delimiter` and subsequently `env_nested_delimiter` might become an alias to the former with a deprecation notice.

**Comment by samuelcolvin** [comment]
Just FYI, this is supported by pydantic-core and will be fixed in V2, see [this test](https://github.com/pydantic/pydantic-core/blob/bcf799f0e8caa9774e839a2d8d30c7f4dd15852f/tests/validators/test_typed_dict.py#L550-L568) as an example

**Comment by johtso** [comment]
This is great news! Just found there's also a nice little section in the docs mentioning these upcoming improvements https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#more-powerful-aliases

**Comment by adriangb** [comment]
As per the above comments this will be supported by the new super powerful aliases in V2, which will be released soon. Closing this issue as completed 😄

**Comment by chriszs** [comment]
Forgive me if I'm missing something obvious. I see nested accessors in those examples, but do those allow the alias to nest the data as the OP was asking?

**Comment by samuelcolvin** [comment]
No sure exactly what you're asking, but we currently allow alias paths for validation but not for serialisation.

We might be able to support alias paths for serialisation in future, but that's a separate issue, if you need that, please create a new issue with details of your use case.

**Comment by chrisbouchard** [comment]
@samuelcolvin I know this issue is a couple months old, but could you please explain how to use aliases to accomplish OP's question? As far as I understand, aliases let a model reach _into_ the schema, but not outward. So I see how aliases can be used to create a flat model for a nested JSON schema, e.g.,

```python
class FlatModel(BaseModel):
  foo: int
  bar: int = Field(alias=AliasPath("nested", "bar"))

FlatModel.model_validate({"foo": 1, "nested": {"bar": 2}})
# FlatModel(foo=1, bar=2)
```

But OP (and others) are asking to go the _other_ way&mdash;to create a nested model for a flat JSON schema, e.g.,

```python
class NestedModel(BaseModel):
  bar: int  # What alias can we give here?

class NotFlatModel(BaseModel):
  foo: int
  nested: NestedModel  # Or here?

NotFlatModel.model_validate({"foo": 1, "bar": 2})
# Does not validate, but we want NotFlatModel(foo=1, nested=NestedModel(bar=2))
```

Sometimes the JSON schema doesn't line up with how we want to use the model in code, and it makes sense to pull part of it out to a sub-model. For example, a POST request may be a flat dictionary of fields from a form, but we want sub-objects that group the fields by domain so we can pass `request.user_info` to one function, and `request.vehicle_info` to another.

**Comment by karambaq** [comment]
@chrisbouchard 
Hey Chris, did you found a solution for this?

**Comment by samuelcolvin** [comment]
For @chrisbouchard's example you'd need to use a `model_validator` to alter the input data.

**Comment by namoshizun** [comment]
I found the following works for me:

```
class TemplateGraphEdge(BaseModel):
    source: UUID4 = Field(validation_alias=AliasPath("source", "cell"))
    target: UUID4 = Field(validation_alias=AliasPath("target", "cell"))


data = {
    "source": {
        "cell": "6cd85e72-911e-4fb4-af96-8e67df5b603c",
        "port": "6ec871a1-33ed-4f3b-bcc9-dc076c323168",
    },
    "target": {
        "cell": "f1e445fa-6e40-4b4f-bab9-80f66da490ec",
        "port": "4a69c829-05a4-45c3-b29f-a789edd37f64",
    },
}

TemplateGraphEdge(**data)
# TemplateGraphEdge(source=UUID('6cd85e72-911e-4fb4-af96-8e67df5b603c'), target=UUID('f1e445fa-6e40-4b4f-bab9-80f66da490ec'))

```

**Comment by karambaq** [comment]
> https://pydantic-docs.helpmanual.io/blog/pydantic-v2/#more-powerful-aliases

Can you please give me a hint where I can find minimal example of it?

All I need is:

```python

class NestedSchema(Schema):
    field: str

class MainSchema(Schema):
    nested: NestedSchema
```

And the usage is:

```python
MainSchema(field='some_str').model_dump() # {'nested': {'field': 'some_str'}}
```

**Comment by stellarose012** [comment]
Spotify Premium APK is mod unlocked hack version, comes with premium subscription for free Download Spotify crack and enjoy lifetime unlimited music[https://spotiepremium.com/](https://spotiepremium.com/)
