### ISSUE TITLE
Incorrect Parsing of bson.Int64 Values to int in Pydantic Models

### ISSUE THREAD

**Issue by roman-right** [pydantic/pydantic#7201]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When validating a model with an integer attribute using a `bson.Int64` value in Pydantic, the resulting value in the model instance doesn't match the original `bson.Int64` value.

### Example Code

```Python
from bson import Int64
from pydantic import BaseModel

class A(BaseModel):
    i: int

a = A.model_validate({"i": Int64(1136885225876639845)})

print(a.i)  # Expected: 1136885225876639845, Actual: 1136885225876639872
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.2.0
        pydantic-core version: 2.6.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/ro/Projects/OpenSource/beanie/venv37/lib/python3.7/site-packages/pydantic
               python version: 3.7.17 (default, Jun  6 2023, 20:10:09)  [GCC 11.3.0]
                     platform: Linux-6.2.0-26-generic-x86_64-with-Ubuntu-22.04-jammy
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by samuelcolvin** [comment]
Thanks so much for reporting. This was the result of an error in pydantic-core where we wrongly fallback to coercing to a float for subclasses of `int`, it's fixed in https://github.com/pydantic/pydantic-core/pull/914.

**Comment by Wolfhound905** [comment]
So glad this got fixed!
