### ISSUE TITLE
Add is_pydantic_dataclass to public API

### ISSUE THREAD

**Issue by GabrielCappelli** [pydantic/pydantic#7207]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We are incrementally changing our validators from mutiple other libs to pydantic. Part of our strategy depends on detecting which validator we need to use based on the "schema" that was provided. 

For pydantic dataclasses we would like to use `pydantic._internal._dataclasses.is_pydantic_dataclass`, but would rather not use a any internals that might be subject to breaking changes.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @samuelcolvin

**Comment by maxhuettenrauch** [comment]
Calling `pydantic.dataclasses.is_pydantic_dataclass` on pydantic dataclasses returns False due to `'__pydantic_validator__'` not being in `__cls.__dict__`. Anyone else facing the same problem?

**Comment by GabrielCappelli** [comment]
Seems to be working for me, how are you creating your Pydantic dataclass ?

```python
import pydantic

@pydantic.dataclasses.dataclass
class PydanticDataclass:
    bar: str

print(pydantic.dataclasses.is_pydantic_dataclass(PydanticDataclass))
# > True
```

**Comment by maxhuettenrauch** [comment]
That's odd, your code is working for me. However, the following is not

```
from pydantic.dataclasses import dataclass, is_pydantic_dataclass

@dataclass
class DummyDataClass:
    value : int = 0
    
dd = DummyDataClass()
print(is_pydantic_dataclass(dd))
```

**Comment by maxhuettenrauch** [comment]
Doh... I've called it on an object and not the class itself... Is there a function to check if an instance of a dataclass is a pydantic dataclass object?

**Comment by GabrielCappelli** [comment]
Sure, you can use the builtin `type` to get the class of any object. So, on your example you'd do:

```python
dd = DummyDataClass()
print(is_pydantic_dataclass(type(dd)))
```

**Comment by maxhuettenrauch** [comment]
I see, thanks. But maybe it's worth noting that Python's native `is_dataclass` function returns True for both, classes and instances of a dataclass.

**Comment by GabrielCappelli** [comment]
Seems stdlib checks if we are passing a class or an instance https://github.com/python/cpython/blob/4f04172c9287c507f1426e02ddfc432f1f3ade54/Lib/dataclasses.py#L1306

Might make sense to implement this on pydantic as well, I'd suggest you open a feature request
