### ISSUE TITLE
Union type coercion with defaults results in unexpected behavior

### ISSUE THREAD

**Issue by Narquadah** [pydantic/pydantic#7223]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using type coercion with a union and defaults, pydantic chooses the first type rather the one where a value has been set.

For now I am using validators as a workaround.

### Example Code

```Python
from pydantic import BaseModel, TypeAdapter

class A(BaseModel):
    field_a: str | None = None


class B(BaseModel):
    field_b: str | None = None

United = A | B

instance_a = TypeAdapter(United).validate_python({'field_a': 'test'})
instance_b = TypeAdapter(United).validate_python({'field_b': 'test'})
print(isinstance(instance_a, A)) # True
print(isinstance(instance_b, B)) # False
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.2.1
        pydantic-core version: 2.6.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/<user>/Library/Caches/pypoetry/virtualenvs/frogcloud-daemon-kMv5m2mx-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Feb 20 2023, 11:40:31) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.5-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by davidhewitt** [comment]
You can workaround the situation here by setting `extra = 'forbid'` in your model configuration. What is happening is that the `A` type is ignoring the field for `B` and then successfully validates by using the defaults.

I agree this is not ideal, and I've been working on improvements to union type inference in https://github.com/pydantic/pydantic-core/pull/867. I think the changes I have in mind would not solve this case.
