### ISSUE TITLE
Modifiable repr for fields

### ISSUE THREAD

**Issue by lmmx** [pydantic/pydantic#7234]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

From what I can see in the docs, we can switch on or off the repr for a field, but not modify it. When working with text data it's common to have awkward reprs

```py
from pydantic import BaseModel


class TextInfo(BaseModel):
    big_text_field: str = "a" * 1000


info = TextInfo()

print(f"Some info for you: {info!r}")
```

```sh
$ python demo.py 
Some info for you: TextInfo(big_text_field='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
```

What if there was instead a way to modify the repr?

I tried to do something like this manually by extracting the `str` field away into a root model and overriding its repr (or `__repr_str__`, or `__repr_args__`) but I seem to be doing it wrong, or the internal Representation is always used over any bound methods that try to to override.

My useless code trying various attempts at getting a custom field repr:

```py
from pydantic import BaseModel, Field, RootModel


def custom_repr(self) -> str:
    breakpoint()
    return self.__class__.__name


def custom_repr_args(self):
    breakpoint()


Field.__repr__ = custom_repr
Field.__str__ = custom_repr
Field.__repr_args__ = custom_repr_args


class AbbrevStr(RootModel):
    root: str = Field()

    def __repr_str__(self, join_str: str) -> str:
        return f"{self.root[:10]!r}"


class TextInfo(BaseModel):
    big_text_field: AbbrevStr = Field("a" * 1000)
```

If there's already a way to do this I've missed then great, but if not then I think adding it would make Pydantic even nicer for working with structured data! :smiley:

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @Kludex

**Comment by davidhewitt** [comment]
I think you're almost there with the `RootModel` idea; the following works fine for me:

```python
from pydantic import BaseModel, RootModel


class BigStr(RootModel):
    root: str

    def __repr__(self) -> str:
        return f"{self.root[:10]!r}"


class TextInfo(BaseModel):
    big_text_field: BigStr


info = TextInfo(big_text_field=("a" * 1000))

print(f"Some info for you: {info!r}")
#> Some info for you: TextInfo(big_text_field='aaaaaaaaaa')
```

**Comment by lmmx** [comment]
Ah apologies for that, somehow must have tried everything but that. Thanks :pray:
