### ISSUE TITLE
Generic type annotation breakes hashing at runtime

### ISSUE THREAD

**Issue by jgarvin** [pydantic/pydantic#7236]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

See the commented out line below -- switching the inheritance order will make the type unhashable and the script will fail with:

```
Traceback (most recent call last):
  File "/tmp/reproducer.py", line 18, in <module>
    print({B(x=2)})
          ^^^^^^^^
TypeError: unhashable type: 'B'
```

This seems undesirable since the base class is just a type annotation not actually intended to change runtime behavior, and the error message doesn't give you any hint what is wrong.

### Example Code

```Python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pydantic import BaseModel, ConfigDict
from typing import Generic, TypeVar

class Config(BaseModel):
    model_config = ConfigDict(frozen=True)

ConfigT = TypeVar("ConfigT", bound=Config)

# class B(Generic[ConfigT], BaseModel): # this order doesn't work!!!
class B(BaseModel, Generic[ConfigT]):
    x: int

    model_config = ConfigDict(frozen=True)

print({B(x=2)})
```

### Python, Pydantic & OS Version

```Text
$ python3.11 -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=true mimalloc=true
                 install path: /home/xxxxx/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0]
                     platform: Linux-5.18.12-051812-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by dmontagu** [comment]
Yeah, putting `Generic` before `BaseModel` causes other weird errors as well. I recently worked on an issue caused by that, but I guess it only updated the error message if it actually caused other misbehavior. We should probably just make it raise an error any time you have a generic `BaseModel` where `Generic` isn't the last thing.

@jgarvin do you _need_ the generic to not be the last item? Or would it be enough for us to just tell you to put it last if you don't (so you don't waste time on this in the future)? I think it might be a more challenging change to make everything work properly if `Generic` is not the last base class.

**Comment by jgarvin** [comment]
@dmontagu I don't need it to be but creating a minimal reproducer to figure out that this was the problem took a long time, so it would definitely be preferable to get a clear error message. Also though, I'm not sure users can deal with this if the requirement is that `Generic` only appear last in the MRO -- it would be pretty reasonable to have `class A(BaseModel, Generic[T])` and `class B(A, Generic[S])`, in which case `Generic` is in the hierarchy twice, and `Generic[T]` is in the "middle" from the POV of `B`, even though `A` listed it last.

**Comment by dmontagu** [comment]
I did some investigation, and the requirement isn't that Generic not appear last — it's that some BaseModel subclass needs to occur before generic. But I think there may be a better solution to this particular issue that doesn't require the class ordering. I will investigate a bit more and possibly open a PR to fix it if I see a good solution.
