### ISSUE TITLE
model_validator return value is ignored on the top level model

### ISSUE THREAD

**Issue by jeet-parekh** [pydantic/pydantic#7252]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a `BaseModel` has a `model_validator(mode="after")`, it behaves differently when it's used as a nested object. I hope the example would make it clear.

### Example Code

```Python
from pydantic import BaseModel
from pydantic.functional_validators import model_validator


class Child(BaseModel):
    name: str

    @model_validator(mode="after")
    def validate(self):
        pass


class Parent(BaseModel):
    name: str
    child: Child

    @model_validator(mode="after")
    def validate(self):
        pass


child_object = Child(name="child")
parent_object = Parent(name="parent", child=child_object)

print(child_object)
print(parent_object)

# OUTPUT:
# name='child'
# name='parent' child=None
```

- I believe `parent_object.child` is `None` because `Child.validate` function doesn't `return self`.
- But then, why does `child_object` have a value instead of `None`? That seems inconsistent, unless I'm missing something.
- Change the `Child.validate` function to `return self`. And now `parent_object.child` would have a value.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/jeet/miniconda3/envs/pydantic/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
                     platform: Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by adriangb** [comment]
You need to return the instance from `@model_validator(mode='after')`:

```python
from pydantic import BaseModel
from pydantic.functional_validators import model_validator


class Child(BaseModel):
    name: str

    @model_validator(mode="after")
    def validate_model(self):
        return self


class Parent(BaseModel):
    name: str
    child: Child

    @model_validator(mode="after")
    def validate_model(self):
        return self


child_object = Child(name="child")
parent_object = Parent(name="parent", child=child_object)

print(child_object)
print(parent_object)

```

Also the method name `validate` clobbers an existing symbol in the namespace, you'll want to use something else.

**Comment by jeet-parekh** [comment]
@adriangb 

> You need to return the instance from @model_validator(mode='after'):

I wrote that exact thing in the original explanation. My question is, why does it `child_object` when I am not returning something from the validator?

> Also the method name validate clobbers an existing symbol in the namespace, you'll want to use something else.

I don't think it matters for this issue that I'm trying to highlight. Change the name of the validation function and the issue still stays.

**Comment by adriangb** [comment]
You have `pass` which returns `None`, hence why the child object is `None`

**Comment by jeet-parekh** [comment]
> You have pass which returns None, hence why the child object is None.

But it's not `None`... `child_object` has a value. Try to run the code yourself

**Comment by jeet-parekh** [comment]
The three bullet points in my explanation highlights the problem.

When the validation function has `pass` / `return None`
- `child_object` has a value - WHY?
- `parent_object.child` does NOT have a value - as expected

When the validation function has `pass` / `return None`
- `child_object` has a value - as expected
- `parent_object.child` does also has a value - as expected

**Comment by adriangb** [comment]
The _real_ bug that may be lurking here is:

```python
from pydantic import BaseModel
from pydantic.functional_validators import model_validator


class Child(BaseModel):
    name: str

    @model_validator(mode="after")
    def validate_model(self) -> 'Child':
        return Child.model_construct(name='different!')

print(Child(name='foo'))
```

**Comment by loudblow** [comment]
I have the same problem: I wanted to change the instance in model_validator, but it ignores the return value.
I solved this problem by overriding the __new__ function, but it's annoying anyway.
Instead of this:
`from __future__ import annotations
from pydantic import BaseModel, model_validator


instances: dict[str, MyModel] = {}

class MyModel(BaseModel):
    name: str

    @model_validator(mode='after')
    def _check_dublicate(self) -> MyModel:
        if self.name in instances:
            self = instances[self.name]
        return self

    def register(self) -> None:
        if self.name not in instances:
            instances[self.name] = self

my_model = MyModel(name='foo')
my_model.register()
# returns False, it's not the same instance, 
# but class instance should be replaced in _check_dublicate
print(my_model is MyModel(name='foo'))`
I'm doing this:
`from __future__ import annotations
from pydantic import BaseModel, model_validator


instances: dict[str, MyModel] = {}

class MyModel(BaseModel):
    name: str

    def __new__(cls, *args, **kwargs) -> MyModel:
        if kwargs["name"] in instances:
            instance = instances[kwargs["name"]]
        else:
            instance = super().__new__(cls)
            instance.__init__(*args, **kwargs)
        return instance

    def register(self) -> None:
        if self.name not in instances:
            instances[self.name] = self

my_model = MyModel(name='foo')
my_model.register()
# returns True, it's the same instance
print(my_model is MyModel(name='foo'))`

**Comment by antoniojkim** [comment]
Are there any updates on this issue?

This issue is especially problematic when you want a frozen `BaseModel` and need to modify some value in a `model_validator`, e.g.
```python
In [  ]: class A(BaseModel):
    ...:     model_config = dict(frozen=True)
    ...:
    ...:     a: int
    ...:     b: Optional[int] = None
    ...:
    ...:     @model_validator(mode="after")
    ...:     def validate_b(self):
    ...:         print(id(self))
    ...:         if self.b is None:
    ...:             copy = self.model_copy(update=(dict(b=self.a)))
    ...:             print(id(copy))
    ...:             return copy
    ...:         return self
    ...:
    ...: a = A(a=3)
    ...: print(id(a))
    ...: a
139911912652528
139911912650048
139911912652528
Out[  ]: A(a=3, b=None)
```
In the above trivial example, `b` is supposed to have the same value as `a` if `b` is `None`. But because the model is frozen, there is no way to change the value of `b`.

It seems that regardless of what's being returned by the `model_validator`, as long as it isn't `None` it just uses the original object instead of the copy.

**Comment by sydney-runkle** [comment]
Working on fixing this issue for v2.9. Just a note to myself - I made some progress on debugging here - I think we need to change how we handle `self_instance` for functional validators in `pydantic-core`. Going to try to implement a fix this evening / tomorrow morning.

**Comment by sydney-runkle** [comment]
Alrighty, so the conclusion that @davidhewitt and I came to is that... perhaps we should not support return values from model validators, but instead enforce mutation of `self`.

I think we could do this in a relatively gentle breaking way, by continuing to "support" this (obviously, as seen above, it doesn't work at the top level model), but warn that said pattern is deprecated, to be removed in a future minor version. We'd of course have to change the type hints associated with model validators as a part of this process.

The challenge here is that `after` model validators are applied to core schemas by wrapping a `model` schema. `model` schemas perform special operations when it's detected that validation is occurring from within an `__init__` method of a `BaseModel` subclass (or dataclass, etc). This special logic performs validation as usual, then performs special `setattr` calls on the `self_instance` to make sure that the instance has been updated.

Things go awry when we have this after model validator - normal validation mutates the `self_instance`, in @adriangb's [case](https://github.com/pydantic/pydantic/issues/7252#issuecomment-1708966940) above, setting `name='foo'` on the instance. Then, the function after validator successfully returns a `Child` instance with `name='different!'`. That being said, the `self_instance` is unchanged by this validation, and thus we see `Child(name='different!')` returned by the validator, but the resulting instance is: `Child(name='foo')`.

At first, I thought that the right approach might be to introduce the complexities of mutating `self_instance` in functional validators as well, but that doesn't even solve the case above, when said functional validator returns an entirely new instance. Admittedly, this seems a bit far fetched from a use case perspective, but I think the point becomes more clear when we look at the initial example with nested models.

So again, the proposal would be to deprecate support for return values from model validators, and pushing users in the direction of modifying the `self` state if desired.

Before moving forward with this approach, I'd like to hear what @samuelcolvin and @Viicos think. @davidhewitt, feel free to elaborate / clarify here as you see fit!

**Comment by antoniojkim** [comment]
> pushing users in the direction of modifying the self state if desired.

What about for frozen models like the example I asked about? Will fields be allowed to be mutated whilst inside a validator even if `frozen=True`?

The way I've gotten around this for now is by introducing a decorator called `model_unfrozen`, e.g.
```python
from functools import wraps
from typing import Callable

from pydantic import BaseModel

def model_unfrozen(f: Callable):
    @wraps(f)
    def wrapped_f(*_a, **_k):
        if isinstance(_a[0], BaseModel):
            model_config = _a[0].model_config
        else:
            return f(*_a, **_k)
        try:
            orig = model_config["frozen"]
            model_config["frozen"] = False
            return f(*_a, **_k)
        finally:
            model_config["frozen"] = orig

    return wrapped_f

class A(BaseModel):
    model_config = dict(frozen=True)
    
    a: Optional[int] = None
    
    @model_validator(mode="after")
    @model_unfrozen
    def validate_a(self):
        if self.a is None:
            self.a = 1  # This only works with `model_unfrozen` decorator
        return self
```

Would you consider adding this as an option to say `model_validator`, i.e. `@model_validator(mode="after", frozen=False)`?

**Comment by sydney-runkle** [comment]
> What about for frozen models like the example I asked about? Will fields be allowed to be mutated whilst inside a validator even if frozen=True?

Good question - I think an argument like `unfreeze` could work, yes!

**Comment by sydney-runkle** [comment]
Alright, so just followed up with the team on this. We're going to:

* Raise a warning that recommends only mutating `self` when a model validator is taking effect from the top level `__init__` on a model.
* Tag this issue with a `v3` tag - we should revisit whether or not we support return values from `model_validator`s at that point, but we can't make a change that breaking in nature in a minor version.

In the 2nd case listed above, we would basically just support mutating `self`.

**Comment by sydney-runkle** [comment]
> Raise a warning that recommends only mutating self when a model validator is taking effect from the top level __init__ on a model.

Hmm, this is harder than it seems from the code. I wonder if simply documenting this is the way to go.

**Comment by davidhewitt** [comment]
> > What about for frozen models like the example I asked about? Will fields be allowed to be mutated whilst inside a validator even if frozen=True?
> 
> Good question - I think an argument like `unfreeze` could work, yes!

Not sure this is necessary; IMO this is probably just like `__init__` & `__post_init__` in dataclasses, where the known solution to frozen types is to fallback to `object.__setattr__()`. It's a little ugly, but I think we benefit from matching standard semantics.

**Comment by sydney-runkle** [comment]
On second thought, I'm going to tag this with v3. It'll be closed with the above issue, but we can revisit when we start `v3` development if it makes sense.
