### ISSUE TITLE
Custom type: Can't implement `__get_pydantic_core_schema__`

### ISSUE THREAD

**Issue by jochman** [pydantic/pydantic#7260]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When creating a wrapper for bson.ObjectId I need to implement `__get_pydantic_core_schema__`.

I've tried to use both [this approach](https://docs.pydantic.dev/latest/usage/types/custom/#as-an-annotation) and us the builtin `AfterValidator`. They both failed with `PydanticSchemaGenerationError`.

In my real code I've also implemented:

  * BeforeValidator
  * AfterValidator),
  * PlainSerializer
  * WithJsonSchema
 
Which works fine with `model_config = ConfigDict(arbitrary_types_allowed=True)`. But I want the full capacity of pydantic (also, I don't want things in the future just not work). What I did wrong?

### Example Code

```Python
from typing import Annotated

from bson import ObjectId
from pydantic import (
    AfterValidator,
    BaseModel,
)


PyObjectId = Annotated[
    ObjectId,
    AfterValidator(str),
]


class BaseMongo(BaseModel):
    id: PyObjectId
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
               python version: 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @dmontagu

**Comment by adriangb** [comment]
I don't know what errors your getting or exactly what the `ObjectId` class is / does but maybe you want something like this?

```python
from typing import Annotated

from pydantic import (
    BaseModel,
    InstanceOf,
)
from pydantic.functional_validators import BeforeValidator


class ObjectId(str):
    pass


PyObjectId = Annotated[
    InstanceOf[ObjectId],
    BeforeValidator(ObjectId),  # call the constructor
    BeforeValidator(str),  # make sure it's a string
]


class BaseMongo(BaseModel):
    id: PyObjectId


print(type(BaseMongo(id="123").id))
# <class '__main__.ObjectId'>
```

Then you can add `WithJsonSchema`, etc.

**Comment by jochman** [comment]
Thanks! I've changed the `pydantic.AfterValidator` to `pydantic.functional_validators.AfterValidator`! and it worked.

What is the difference between `pydantic.BeforeValidator` and `pydantic.functional_validators.BeforeValidator`?

**Comment by Viicos** [comment]
> What is the difference between `pydantic.AfterValidator` and `pydantic.functional_validators.AfterValidator`?

It's the same class, `AfterValidator` is reexported from `pydantic` as a shortcut, so you shouldn't get a different behavior

**Comment by dmontagu** [comment]
It sounds like this is resolved now, so I'll close it, but let us know if you still have issues.
