### ISSUE TITLE
Cannot override strict mode on a Path-like field

### ISSUE THREAD

**Issue by nabnux** [pydantic/pydantic#7268]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, I have this project where I'm enabling strict mode directly in the `ConfigDict` of my models. 
If I need to disable strictness for a specific field, I do it using `Field(strict=False)` like suggested in the [docs](https://docs.pydantic.dev/latest/usage/strict_mode/#strict-mode-with-configdict).

I've stumbled into this issue where passing `strict=False` to a `Path`-like field does not seem to work as expected:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
db_path
  Input should be an instance of Path [type=is_instance_of, input_value='./test', input_type=str]
    For further information visit https://errors.pydantic.dev/2.3/v/is_instance_of
```

See the provided minimal example below where disabling strict mode works for an `int` field, but not a `Path` one.

### Example Code

```Python
from pathlib import Path
from pydantic import BaseModel, ConfigDict, Field


class MyModel(BaseModel):
    model_config = ConfigDict(strict=True)

    num: int = Field(strict=False)
    db_path: Path = Field(strict=False)


MyModel(num='3', db_path='./test')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
               python version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.38
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @samuelcolvin

**Comment by hramezani** [comment]
Thanks @nabnux for reporting this bug 🙏 

I've created a PR to fix the bug.

**Comment by nabnux** [comment]
Thanks! Pydantic types  like [FilePath](https://docs.pydantic.dev/latest/usage/types/file_types/) seem to be affected to, will this PR fix the bug for those too?

**Comment by hramezani** [comment]
> Thanks! Pydantic types like [FilePath](https://docs.pydantic.dev/latest/usage/types/file_types/) seem to be affected to, will this PR fix the bug for those too?

Yes, It fixes them as well.
