### ISSUE TITLE
Field pattern matching does not respect type attribute.

### ISSUE THREAD

**Issue by YYYasin19** [pydantic/pydantic#7270]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I want to declare a field `urls` that takes in either a str or a list of str.
Declaring a type hint of `str | List[str]` makes the following `pattern` attribute on the `Field` interpret the values as a `str` and the pattern fail (see example code below)

The resulting error is:
```py
ValidationError: 1 validation error for MyModel
urls
  Input should be a valid string [type=string_type, input_value=['http://localhost:8000/g...alhost:8000/get/local2'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.3/v/string_type
```

Removing the `pattern` makes this work. Only passing a `str` makes this work.

I might be missing something in the documentation, so I'm thankful for every hint.
Otherwise it should be fairly easy to extent this such that each item in the list has to match the pattern, right?

### Example Code

```Python
from pydantic import Field, BaseModel
from typing import List

class MyModel(BaseModel):
    urls: str | List[str] = Field(None, pattern="")

# ⚠️ error
MyModel(urls=["http://localhost:8000/get/local1","http://localhost:8000/get/local2"])
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/yasin/micromamba/envs/quetz2/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @adriangb

**Comment by adriangb** [comment]
You need to do something like:

```python
from typing import Annotated
from pydantic import BaseModel, Field

Url = Annotated[str, Field(pattern=“abc”)]

class Model(BaseModel):
    urls: Url | list[Url]
```

**Comment by YYYasin19** [comment]
Nice, I also just found the alternative
```python3
urltype = pydantic.constr(pattern="^(http|https)://.+|None|^(\\[.*\\])+$")
class MyModel(BaseModel):
    urls: str | List[urltype] = Field(None)
```

Is there a structural/technical reason it won't work with just `List[str]` or is it just not implemented yet?

**Comment by adriangb** [comment]
Yes you’re original example is trying to apply a regex pattern to a list which doesn’t make sense. Consider if it was Dict[str, str]: does the pattern apply to the keys, the values or both?

**Comment by YYYasin19** [comment]
Makes sense, thanks 👍
