### ISSUE TITLE
frozen config with `model_validator(mode="after")`

### ISSUE THREAD

**Issue by lord-haffi** [pydantic/pydantic#7285]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `ConfigDict(frozen=True)` together with an validator decorated with `model_validator(mode="after")` it is not possible to mutate the attribute values (without hacks like `object.__setattr__(self, field_name, field_value)`). Is this desired?

Note: It would be inconvenient to use `mode="before"` because the validator I want to implement does something with datetimes and it would be a bit annoying to convert those strings by hand if pydantic already does it for me. `mode="wrap"` would totally work for me which is why I'm using it as a workaround but wanted to submit this issue anyway. If this behaviour is totally desired you can close this issue without any comment :) But it may be worth to document that behaviour though.

### Example Code

```Python
from pydantic import BaseModel, model_validator, ConfigDict


class A(BaseModel)
    x: str

    model_config = ConfigDict(frozen=True)

    @model_validator(mode="after")
    def mutate_x(self)
        self.x += " World!"


a = A(x="Hello")
print(a.x)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\...\.tox\dev\Lib\site-packages\pydantic
               python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @davidhewitt

**Comment by hramezani** [comment]
Thanks @lord-haffi for reporting this issue. 
Yes, it is the desired behavior because Pydantic runs after validators(validators in `mode='after'`) after it's own validator(in this case string validator). Then changing the value will raise the error.

As you've already mentioned `wrap` and `before` validators are work arounds. 

I don't think we need to document this behavior. But if you want to open a PR and provide a good example feel free to do it.

**Comment by chbndrhnns** [comment]
I stumbled across this problem now, as well. I think it's not very clear from the documentation when the freezing happens. I would also welcome a way to freeze an instance when all validations are finished.

**Comment by lord-haffi** [comment]
Pydantic "freezes" as soon as the object is initialized.
When setting a variable of a BaseModel instance, the "frozen" check is always done - see [here](https://github.com/pydantic/pydantic/blob/afa3d4c8ec8adf87ea18576f48d5295a609e843d/pydantic/main.py#L780).
This function just checks the config dict.

Actually, you will encounter the same problem when using wrap-validators. I created a [SO question](https://stackoverflow.com/questions/77007885/pydantic-v2-model-validatormode-wrap-how-to-use-modelwrapvalidatorhandl) but apparently no one could give a proper solution.

What you can always do (with frozen objects) to work around this issue: `object.__setattr__(self, attr_name, attr_value)`
