### ISSUE TITLE
decimal_encoder fails for Decimal('NaN')

### ISSUE THREAD

**Issue by oryba** [pydantic/pydantic#7289]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When trying to serialize the response in FastAPI that contains decimals, I'm getting the following error (the trace is cut to keep only meaningful part):

```
...
  File ".pyenv/versions/3.10.6/lib/python3.10/site-packages/fastapi/encoders.py", line 146, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
  File ".pyenv/versions/3.10.6/lib/python3.10/site-packages/pydantic/json.py", line 38, in decimal_encoder
    if dec_value.as_tuple().exponent >= 0:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

Here's the function that causes the problem (in `json.py`):
```python3
def decimal_encoder(dec_value: Decimal) -> Union[int, float]:
    """
    Encodes a Decimal as int of there's no exponent, otherwise float

    This is useful when we use ConstrainedDecimal to represent Numeric(x,0)
    where a integer (but not int typed) is used. Encoding this as a float
    results in failed round-tripping between encode and parse.
    Our Id type is a prime example of this.

    >>> decimal_encoder(Decimal("1.0"))
    1.0

    >>> decimal_encoder(Decimal("1"))
    1
    """
    if dec_value.as_tuple().exponent >= 0:
        return int(dec_value)
    else:
        return float(dec_value)
```

But actually `dec_value.as_tuple().exponent` returns `'n'` for `Decimal('NaN')`. 

So I believe makes sense handling NaN properly here. 

**P.S. I'm happy to contribute if you think this change is reasonable**

### Example Code

```Python
from decimal import Decimal
from pydantic.json import decimal_encoder

decimal_encoder(Decimal('NaN'))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.9
pydantic compiled: False
python version: 3.10.6 (main, May 10 2023, 12:42:36) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-x86_64-i386-64bit
optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @adriangb

**Comment by dmontagu** [comment]
I'll note that pydantic v1 is in maintenance mode only, and the relevant code in pydantic v2 has all been refactored, and if you intend to migrate it may be worth checking things behave there as well. (If you share a code snippet using FastAPI that demonstrates the failure we can test it out with v2).

However, we are still doing v1 bugfixes, and I'm happy to take a look at this.

Do you know if the following change resolve the issue?
```python
def decimal_encoder(dec_value: Decimal) -> Union[int, float]:
    """
    Encodes a Decimal as int of there's no exponent, otherwise float

    This is useful when we use ConstrainedDecimal to represent Numeric(x,0)
    where a integer (but not int typed) is used. Encoding this as a float
    results in failed round-tripping between encode and parse.
    Our Id type is a prime example of this.

    >>> decimal_encoder(Decimal("1.0"))
    1.0

    >>> decimal_encoder(Decimal("1"))
    1
    """
    exponent = dec_value.as_tuple().exponent
    if exponent == 'n':
        return float('nan')
    elif exponent >= 0:
        return int(dec_value)
    else:
        return float(dec_value)
```
(Namely, adding the check for `exponent == 'n'`.)
