### ISSUE TITLE
Field constraints fail when using None as generic argument for a Union candidate

### ISSUE THREAD

**Issue by andersfylling** [pydantic/pydantic#7291]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

From reading the documentation I figured SkipJsonSchema only affected openapi output, however it seems to cause validation errors in certain cases.

 - https://docs.pydantic.dev/latest/api/json_schema/#pydantic.json_schema.SkipJsonSchema

### Example Code

```Python
from pydantic import BaseModel, Field

class Bar(BaseModel):
    value: list[str] | None = Field(default=None, min_length=1)

class Foo(BaseModel):
    value: list[str] | SkipJsonSchema[None] = Field(default=None, min_length=1)

Bar(value=None)  # OK
Foo(value=None)  # TypeError: object of type 'NoneType' has no len()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/anders/dev/matchmakers/vector-embeddings/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun 19 2023, 17:18:20) [GCC 12.2.1 20230201]
                     platform: Linux-6.1.21-1-lts-x86_64-with-glibc2.37
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @hramezani

**Comment by Kludex** [comment]
I think the behavior should be consistent, but the bug is not with `SkipJsonSchema`.

The issue can be reproduced with the following code as well:

```py
from typing import TypeVar, Annotated
from pydantic import BaseModel, Field

T = TypeVar("T")

EmptyAnnotated = Annotated[T, ...]


class Bar(BaseModel):
    value: list[str] | EmptyAnnotated[None] = Field(default=None, min_length=1)


Bar(value=None)
```

Ideally, your model would look like this:

```py
from typing import TypeVar, Annotated
from pydantic import BaseModel, Field

T = TypeVar("T")

EmptyAnnotated = Annotated[T, ...]


class Bar(BaseModel):
    value: list[Annotated[str, Field(min_length=1)]] | EmptyAnnotated[None] = None


Bar(value=None)
```

The `min_length` is associated with the `str`.

That said, we want to be consistent here, so... It's a bug, just not on the `SkipJsonSchema`.

**Comment by sydney-runkle** [comment]
Closing this, as we've reported this issue in the docs [here](https://docs.pydantic.dev/latest/concepts/fields/#numeric-constraints) -- see the note on "constraints on compound types".

That being said, I do think a more clear error could be raised, which is being addressed in https://github.com/pydantic/pydantic/issues/8362
