### ISSUE TITLE
model_post_init not called on subclasses with a private attribute

### ISSUE THREAD

**Issue by jrapin** [pydantic/pydantic#7293]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In the example below, I would expect the `Model1.model_post_init` to be called when instantiating `Model2` but it is not.

On the other hand, `Model1.model_post_init` is called:
- when instantiating `Model1`
- when instantiating `Model1` even if I add a private attribute
- when instantiating `Model2` if I change `_private` into `private`
- when instantiating `Model2` if I add a `model_post_init` in `Model2` which calls `Model1.model_post_init`

Is this an expected behavior?
Thanks for your help!

Note: `Model2.__pydantic_post_init__` remains set to `'model_post_init'`

### Example Code

```Python
import pydantic

class Model1(pydantic.BaseModel):
    a: int = 12

    def model_post_init(self, __context) -> None:
        print("Post init", self.__class__)

class Model2(Model1):
    _private: bool = True

Model2() # does not trigger inherited post init
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/jrapin/Applications/miniconda3/envs/test_env/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul  5 2023, 15:02:25) [Clang 14.0.6 ]
                     platform: macOS-13.5.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Viicos** [comment]
This coming from:

https://github.com/pydantic/pydantic/blob/b9d2a98e8f66bb0c8aab77d1ed200a2769d7eca4/pydantic/_internal/_model_construction.py#L106-L120

In your case, `private_attributes` evaluates to `True`, but as you do not define `model_post_init` in `Model2`, it is not present in the `namespace`, and gets overridden by `init_private_attributes`.

Maybe something like this could fix it?

```python
def get_model_post_init(namespace: dict[str, Any], bases: tuple[type[Any], ...]) -> Any | None:
    if 'model_post_init' in namespace:
        return namespace['model_post_init']

    for base in bases:
        model_post_init = getattr(base, 'model_post_init')
        if model_post_init is not None:
            return model_post_init

# then in ModelMetaclass__new__...

            if private_attributes:
                original_model_post_init = get_model_post_init(namespace, bases)
                if original_model_post_init is not None:
                    # if there are private_attributes and a model_post_init function, we handle both

                    def wrapped_model_post_init(self: BaseModel, __context: Any) -> None:
                        """We need to both initialize private attributes and call the user-defined model_post_init
                        method.
                        """
                        init_private_attributes(self, __context)
                        original_model_post_init(self, __context)

                    namespace['model_post_init'] = wrapped_model_post_init
                else:
                    namespace['model_post_init'] = init_private_attributes
```

**Comment by dmontagu** [comment]
@Viicos I think you are on the right track. Would you like to open a PR for this? If not, we can get it across the line.

**Comment by Viicos** [comment]
> @Viicos I think you are on the right track. Would you like to open a PR for this? If not, we can get it across the line.

I'll try to submit a PR

**Comment by jrapin** [comment]
Thanks for the quick response and fix @Viicos and @dmontagu ! That's really appreciated and I can confirm that this worked on our side :)
