### ISSUE TITLE
Optional[Decimal] fails with Field option

### ISSUE THREAD

**Issue by notarious2** [pydantic/pydantic#7306]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic throws an error when I add constraint to Decimal optional field

`   class UpdateModelSchema(BaseModel):
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py:178: in __new__
    complete_model_class(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py:468: in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
/usr/local/lib/python3.11/site-packages/pydantic/main.py:557: in __get_pydantic_core_schema__
    return __handler(__source)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py:82: in __call__
    schema = self._handler(__source_type)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:448: in generate_schema
    schema = self._generate_schema(obj)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:689: in _generate_schema
    return self._model_schema(obj)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:519: in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:519: in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:853: in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:905: in _common_field_schema
    schema = self._apply_annotations(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:1610: in _apply_annotations
    schema = get_inner_schema(source_type)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py:82: in __call__
    schema = self._handler(__source_type)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:1704: in new_handler
    schema = self._apply_single_annotation(schema, annotation)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:1631: in _apply_single_annotation
    inner = self._apply_single_annotation(inner, metadata)
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:1653: in _apply_single_annotation
    maybe_updated_schema = _known_annotated_metadata.apply_known_metadata(metadata, schema.copy())
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_known_annotated_metadata.py:149: in apply_known_metadata
    raise ValueError(f'Unknown constraint {constraint}')
E   ValueError: Unknown constraint max_digits`

### Example Code

```Python
from pydantic import BaseModel, Field
from decimal import Decimal
from typing import Optional

class ProductCreateSchema(BaseModel):
    price: Decimal = Field(decimal_places=2, max_digits=12, gt=0)

class UpdateProductSchema(BaseModel):
    price: Optional[Decimal] = Field(decimal_places=2, max_digits=12, gt=0)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 25 2023, 23:57:27) [GCC 12.2.0]
                     platform: Linux-5.15.49-linuxkit-pr-x86_64-with-glibc2.36
     optional deps. installed: ['email-validator', 'typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Viicos** [comment]
See https://github.com/pydantic/pydantic/issues/6955:

```python
from typing import Annotated

class UpdateProductSchema(BaseModel):
    price: Annotated[Decimal, Field(decimal_places=2, max_digits=12, gt=0)] | None
    # The following should also work if you can't use new union syntax:
    # price: Optional[Annotated[Decimal, Field(decimal_places=2, max_digits=12, gt=0)]]
```

**Comment by notarious2** [comment]
> See #6955:
> 
> ```python
> from typing import Annotated
> 
> class UpdateProductSchema(BaseModel):
>     price: Annotated[Decimal, Field(decimal_places=2, max_digits=12, gt=0)] | None
>     # The following should also work if you can't use new union syntax:
>     # price: Optional[Annotated[Decimal, Field(decimal_places=2, max_digits=12, gt=0)]]
> ```

Thank you!
