### ISSUE TITLE
Refactor documentation

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#7322]
The docs are currently a bit of a mess in terms of their structure.

I think we should restructure the documentation into the following sections:
* **API docs** - which has virtually all the current content - details on how to use it, and some examples
* **Examples** - which is a grab bag of useful examples, a bit like [bootstrap examples](https://getbootstrap.com/docs/4.0/examples/) but just code
* **Concepts** - which will probably be quite small but will cover stuff that doesn’t fit above, e.g. more abstract ideas - this will be more long form and abstract and probably won't get that much coverage attention but good to have
* Existing sections which should remain mostly unchanged:
  * All the pages in the root left menu - "Why use Pydantic", "Help with Pydantic" etc.
  * Error messages
  * Integrations
  * Blog
  * Conversion table - should be put somewhere more prominent
  * Settings documentation, currently https://docs.pydantic.dev/latest/usage/pydantic_settings/ - I guess this could just go in the same file as the API documentation for `pydantic-settings?

We should work hard to cross link lots.

This is obviously a pretty big refactor, so might have to happen in stages.

We also need to make sure we have redirects for all pages that are being removed to the most appropriate new page.

TODO:
* [x] #3884
* [x] #7323

**Comment by Kludex** [comment]
We want the `Standard Library Types` being on the API documentation, so we can write about `str`, and other built-ins and standard library types over there.

**Comment by Kludex** [comment]
We need to remember to add redirects.

**Comment by Kludex** [comment]
We should also document [`annotated-types`](https://github.com/annotated-types/annotated-types) within Pydantic.

**Comment by Kludex** [comment]
I've created the `refactor-docs` branch. We should merge all future PRs there.

**Comment by sydney-runkle** [comment]
Closing this. We've implemented all of the changes requested above, with the exception of we could expand a lot on the examples page. I think we can create an independent issue for that, or just work on it as examples come up with issue reports and questions.
