### ISSUE TITLE
Performance tips docs page

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#7323]
Page in the docs with tips on using pydantic in the most performant way.

Should start with a big notice saying something like "In most cases pydantic won't be your bottle neck, only follow this if you're sure it's necessary blah blah blah".

1. Use `model_validate_json()` not `model_validate(json.loads(...))` (👀 FastAPI)
2. `TypeAdapter` instantiated once - generally avoid constructing validators and serializers more than necessary
3. `Sequence` vs `list`/`tuple` - `Mapping` vs `dict`
4. Don't do validation when you don't have to - use `Any` to keep the value unchanged
5. generally avoid recording extra information via subclasses of primatives
6. Use tagged union, not union
7. Use `Literal` not `Enum` (not sure how big this effect is)
8. use `TypedDict` over nested models
9. Avoid wrap validators if you really care about performance

Anything else?

Selected Assignee: @Kludex

**Comment by Burnsedia** [comment]
Another thing you can do I do the simple calculations first, only to the complicated once when you have to. another is object pooling arrays and time slicing.

**Comment by sydney-runkle** [comment]
Looks like this should have been closed by @Kludex's #7567 PR. Closing now, as the minimum reqs for this page have been met. I think we should open a new issue with new requests for this page if/when they're desired.
