### ISSUE TITLE
Expose Url variants from RUst Url library in HttpUrl Python object

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#7325]
As @mikelei8291 mentioned here https://github.com/pydantic/pydantic/issues/5267#issuecomment-1702510360 it looks like it should be possible to expose `Url` variants, i.e. `Domain`, `Ipv4`, `Ipv6`, in the `HttpUrl` type.

Selected Assignee: @samuelcolvin

**Comment by lig** [comment]
cc @mikelei8291

**Comment by samuelcolvin** [comment]
I think the reason I didn't expose this was https://github.com/servo/rust-url/issues/803 which means that the `Host` type is not always what you'd expect.
