### ISSUE TITLE
Pydantic's mypy plugin hides type violations

### ISSUE THREAD

**Issue by bodograumann** [pydantic/pydantic#7332]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When enabling the pydantic mypy plugin, type-checking errors for model class constructors will be ignored.
I tried enabling as much strictness config options as I could find, but no luck.
Without the plugin, the errors are shown fine.

You can find a reproduction here: https://github.com/bodograumann/pydantic-mypy-plugin-hides-errors
The expected error when running `mypy .` is:

```
src/pydantic_mypy_plugin_hides_errors/__init__.py:13: error: Argument "field" to "ModelB" has incompatible type "int"; expected "dict[str, str]"  [arg-type]
```

I also verified that this is not related to pydantic strict-mode.
These errors will not trigger during type-checking, but they will cause validation errors during runtime.

### Example Code

```Python
from pydantic import BaseModel

class ModelA(BaseModel):
    field: int

class ModelB(BaseModel):
    field: dict[str, str]

def type_violation(obj_a: ModelA) -> ModelB:
    return ModelB(field=obj_a.field)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/bodo/Reproductions/pydantic-mypy-plugin-hides-errors/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 26 2023, 07:22:50) [Clang 16.0.3 ]
                     platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38
     optional deps. installed: ['typing-extensions']
```

Selected Assignee: @Kludex

**Comment by Kludex** [comment]
I can reproduce it.

**Comment by bodograumann** [comment]
I found the mistake. We used `[pydantic-mypy]` in pyproject.toml instead of `[tool.pydantic-mypy]` :facepalm: 
Now the `init_typed` option leads to the type errors to appear again.

Without `init_tyed`, the documentation says, `__init__` parameters are typed as `Any`.
I guess this was a conscious decision. Do you know what the reason was?
