### ISSUE TITLE
Model instance field iterator

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#7334]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

`BaseModel` method that returns an iterator, that provides name of field and respective value on each iteratorion. This should be syntactic sugar that combines `model_fields_set` with their respective values. I would call the method `model_iter_field_name_value`; ideas are welcome.

Can make a PR once I get a green flag!

**Motivation**
#7333

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

Selected Assignee: @davidhewitt

**Comment by sydney-runkle** [comment]
The `BaseModel` class already implements the `__iter__` method. Here's a simple example of how you'd go about using that:

```
from pydantic import BaseModel

class Model(BaseModel):
    a: str

my_model = Model(a="hello world", b=100)

for field_name, value in iter(my_model):
    # whatever you want to do with the field names and values...
    pass
```

**Comment by davidhewitt** [comment]
(See also #6982 where I discuss potential drawbacks of `__iter__`.)
