### ISSUE TITLE
Assigning error to specific location

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#734]
Would be very useful if you could assign raise an exception in a validator but set it's location to something else.

Eg. I have a `whole=True` validator for a list of things, but once I've inspected the list I know the error is at item 4, I want to be able to raise `PydanticValueError(loc=('foobar', 4))`.

If we're doing `PydanticValueError` (or whatever it's called), it would also be useful to be able to add more info to `ctx` when raising the error.

Perhaps related to #729.

Leave this until v1.1, isn't needed for v1.

**Comment by dmontagu** [comment]
I brought this up in #729, but I think it might make sense to start including the associated model name in the `loc` (or as a separate field in the error) by default.

If we want to change the *default* value of `loc` it should probably be in 1.0. But if this is too extreme of a change then I'd be fine with just having the ability to override as desired.

------

@samuelcolvin I'm not sure how familiar you are with FastAPI, but the way errors are surfaced is that each dependency collects any validation errors that occur during its preparation, and they are all surfaced together (this happens [here](https://github.com/tiangolo/fastapi/blob/033bc2a6c9aec3a245eb1f1b4fadb2fbb7a514b8/fastapi/routing.py#L104)).

I don't think it would be unreasonable to view it as the responsibility of FastAPI to make its error messages more interpretable, but I *do* think including more information about the validation-failing model, or at least providing a supported means by which to update the error `loc` would be very useful for improving error messages there.

**Comment by frankie567** [comment]
Hey there 👋 

I was rightly searching for a way to manually set the error location, and found this issue. It looks like it didn't get lot of attention from the community, so I was wondering if it's something still considered? 🙂

It looks like that currently the `loc` is set *via* `ErrorWrapper`:

https://github.com/samuelcolvin/pydantic/blob/e9327b85fc5f3e14ae3efdd142c68478f6899dc9/pydantic/error_wrappers.py#L28-L42

Maybe a silly idea but could we imagine that if the `exc` has a `_loc` class var set, it could take precedence? Something like this:

```py
def loc_tuple(self) -> 'Loc':
    if hasattr(self.exc, 'loc'):
        loc = self.exc.loc
    else:
        loc = self._loc

    if isinstance(loc, tuple):
        return loc
    else:
        return (loc,)
```

Cheers!

**Comment by Danstiv** [comment]
Hi!

I am also interested in this feature.

fastapi does something similar under the hood, it adds body, query, etc... as the first element of the loc array.

Magic, as I understand it, happens [here](https://github.com/tiangolo/fastapi/blob/efc12c5cdbede6922a033a5234c70cb22c4d204a/fastapi/dependencies/utils.py#L585)

The problem is that fastapi constructs errors almost from scratch, which makes it impossible to easily reuse this code for some simple task in which you need to modify the error location.

**Comment by dmontagu** [comment]
This can be done in v2 by manually creating the desired validation error (possibly based on the errors from another); see this permalink for an example of usage: https://github.com/pydantic/pydantic/blob/ad909025f88d4f5ffae33d24d76d9b91f642c634/pydantic/main.py#L757-L763
