### ISSUE TITLE
"not a valid parameter name" error on aliases with spaces in them when using `dataclass` but not `BaseModel`

### ISSUE THREAD

**Issue by DetachHead** [pydantic/pydantic#7348]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

it seems there are different rules for alias names on dataclasses. i'm not sure which one is correct, but dataclasses seem to ban aliases with spaces in them whereas base models do not.

it would be nice if dataclasses allowed spaces, since i'm dealing with an api that returns keys with spaces in them

### Example Code

```Python
from pydantic import BaseModel, Field
from pydantic.dataclasses import dataclass


class Foo(BaseModel): # no error
    a: int = Field(alias="a b")


@dataclass  # ValueError: 'a b' is not a valid parameter name
class Foo:
    a: int = Field(alias="a b")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/user/Library/Caches/pypoetry/virtualenvs/project-ajyfNCZe-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.0.1-x86_64-i386-64bit
     optional deps. installed: ['devtools', 'typing-extensions'
```

**Comment by hramezani** [comment]
Thanks @DetachHead for reporting this 🙏 

I think it got fixed in the `main`. The fix will be available in the next release.

Could you please confirm the fix?
