### ISSUE TITLE
Partial update of nested model via dump -> copy -> parse doesn't work on v2

### ISSUE THREAD

**Issue by slafs** [pydantic/pydantic#7387]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

With v1, doing a partial update of a model instance from another instance could be done via
```py
data = input_model.dict(exclude_unset=True)
updated_model = model.copy(update=data)
```
(this is even a [recommended way in FastAPI docs](https://fastapi.tiangolo.com/tutorial/body-updates/?h=partial#using-pydantics-exclude_unset-parameter))

There's a caveat though. If those models had nested attributes/values (i.e. sub models),
the resulting `updated_model` will have a `dict` as a value instead of the sub model instance.

To fix/workaround this problem in v1 one could use this trick:
```py
updated_model = updated_model.parse_obj(updated_model)
```

In v2 this trick no longer works.

Is there any way to parse/validate nested values/objects like this?

### Example Code

```Python
from pydantic import BaseModel


class SubModel(BaseModel):
    foo: int


class Model(BaseModel):
    bar: str
    sub: SubModel


model = Model(bar="bar", sub={"foo": 0})

# check that foo on sub is 0
assert model.sub.foo == 0


class InputModel(BaseModel):
    sub: SubModel


input_ = InputModel(sub={"foo": 1})

input_data = input_.dict(exclude_unset=True)
updated_m = model.copy(update=input_data)

# now check that foo on sub is 1
# this will raise AttributeError
try:
    assert updated_m.sub.foo == 1
except AttributeError as ex:
    assert str(ex) == "'dict' object has no attribute 'foo'"
else:
    assert False, "were expecting AttributeError"

# trick in v1 to fix this
updated_m = updated_m.parse_obj(updated_m)
assert updated_m.sub.foo == 1
```

With v2, the above code still generates:

```
AttributeError: 'dict' object has no attribute 'foo'
```

This is even the case if we get rid of the deprecation warnings:

```diff
--- /tmp/model_update.py	2023-09-10 13:16:14
+++ /tmp/model_update_v2.py	2023-09-10 13:16:24
@@ -22,8 +22,8 @@
 
 input_ = InputModel(sub={"foo": 1})
 
-input_data = input_.dict(exclude_unset=True)
-updated_m = model.copy(update=input_data)
+input_data = input_.model_dump(exclude_unset=True)
+updated_m = model.model_copy(update=input_data)
 
 # now check that foo on sub is 1
 # this will raise AttributeError
@@ -35,5 +35,5 @@
     assert False, "were expecting AttributeError"
 
 # trick in v1 to fix this
-updated_m = updated_m.parse_obj(updated_m)
+updated_m = updated_m.model_validate(updated_m)
 assert updated_m.sub.foo == 1

```

Interestingly, if the `input_data` had invalid data (e.g. `"x"` instead of `1`),
calling `model_validate` would still pass.

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/slafs/.pyenv/versions/3.10.9/envs/tapper-core-pydantic-v2-py310/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Dec 21 2022, 11:47:15) [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-13.5.2-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @slafs for reporting this 🙏 

`copy` is deprecated in `Pydantic V2`. You can use `model_copy` instead. `model_copy` is simpler than `copy` in V1.
It makes a copy/deepcopy from the object and update the `__dict__` of object with `update` dict.

Here is a working code based on your provided example in `Pydantic V2`:

```py
from pydantic import BaseModel


class SubModel(BaseModel):
    foo: int


class Model(BaseModel):
    bar: str
    sub: SubModel


model = Model(bar="bar", sub={"foo": 0})

# check that foo on sub is 0
assert model.sub.foo == 0


class InputModel(BaseModel):
    sub: SubModel


input_ = InputModel(sub={"foo": 1})
updated_m = model.model_copy(update={'sub': input_.sub})

assert updated_m.sub.foo == 1
```

**Comment by slafs** [comment]
> Thanks @slafs for reporting this 🙏

Thanks for the reply 😃

> copy is deprecated in Pydantic V2. You can use model_copy instead.

Yes, I know. The issue is the same with `model_copy` (see my diff in the original description).

>  It makes a copy/deepcopy from the object and update the __dict__ of object with update dict.

Yep, thanks. I'm aware of this too.

> Here is a working code based on your provided example in Pydantic V2: [...]

Hmmm. Thanks. I feel like your proposal is focusing too much on my (simplified) MRE.

I've posted a minimal example, but I'm looking for a more general solution. I don't want to specify each of the attributes of `Model` in my `update` dict.

What if the `sub` attribute on `InputModel` and `Model` were different types? Or had slightly different validation?
What if there's no `InputModel` and I just have a bunch of nested dicts, that I want to apply to my model instance?

I guess with this issue I'm essentially raising 3 things:

1. With `.model_copy(update=...)` approach, you can represent an invalid state of `Model` and there seems to be no (easy) way to know that (e.g. revalidate the instance).
2. `model_validate` method from v2 in this case has a different behaviour than `parse_obj` from v1. The latter did revalidate the instance.
3. What's the general "pattern" for doing (efficient) partial updates on complex model instances like this? (again, dump with `exclude_unset` arg and then copy with `update` arg is the [recommended way in FastAPI docs](https://fastapi.tiangolo.com/tutorial/body-updates/#using-pydantics-exclude_unset-parameter))

**Comment by hramezani** [comment]
> 1. With .model_copy(update=...) approach, you can represent an invalid state of Model and there seems to be no (easy) way to know that (e.g. revalidate the instance).

Yes, the data passed by `update` is not validated.

> 2. model_validate method from v2 in this case has a different behaviour than parse_obj from v1. The latter did revalidate the instance.

Do you mean `model_copy`? Because `model_validate` will validate the data.

> 3. What's the general "pattern" for doing (efficient) partial updates on complex model instances like this? (again, dump with exclude_unset arg and then copy with update arg is the [recommended way in FastAPI docs](https://fastapi.tiangolo.com/tutorial/body-updates/#using-pydantics-exclude_unset-parameter))


Probably by updating the model dump and use `model_validate`(if your updated data is dict).

```py
from pydantic import BaseModel


class SubModel(BaseModel):
    foo: int


class Model(BaseModel):
    bar: str
    sub: SubModel


model = Model(bar="bar", sub={"foo": 0})

# check that foo on sub is 0
assert model.sub.foo == 0


class InputModel(BaseModel):
    sub: SubModel


input_ = InputModel(sub={"foo": 1})

input_data = input_.model_dump(exclude_unset=True)

updated_data = model.model_dump()
updated_data.update(input_data)

updated_m = Model.model_validate(updated_data)

# now check that foo on sub is 1
# this will raise AttributeError
assert updated_m.sub.foo == 1
```

**Comment by slafs** [comment]
> Yes, the data passed by update is not validated.

Right. I know this is documented, but I find it weird that one cannot tell in any way if that model copy is valid in general or not (in v1 this was possible with `parse_obj`)

> Do you mean model_copy?

No, I mean `model_validate` :)

> Because model_validate will validate the data.

Not when you've used `.model_copy(update=...)`
To narrow down the discussion let's get rid of `InputModel` and some assertion checks:

```py
from pydantic import BaseModel


class SubModel(BaseModel):
    foo: int


class Model(BaseModel):
    bar: str
    sub: SubModel


model = Model(bar="bar", sub={"foo": 0})

# check that foo on sub is 0
assert model.sub.foo == 0

input_data = {"sub": {"foo": "xxx"}}
updated_m = model.model_copy(update=input_data)

# I'd expect this to fail.
updated_m = updated_m.model_validate(updated_m)

# In v1, when using `updated_m.parse_obj(updated_m)`
# it does.
```

> Probably by updating the model dump and use model_validate(if your updated data is dict).

Yep. That's what I ended up with for now in my project (not using copy and merging dicts from the original object dump and the input dump).

This workaround obviously works, but that's not the purpose why I've opened this issue :).

**Comment by brycedrennan** [comment]
I ran into this same issue. My workaround for force validation to run:
```python
# doesnt run validation
new_prompt = self.model_validate(new_prompt)

# runs validation
new_prompt = new_prompt.model_validate({k: v for k, v in new_prompt})
```

**Comment by slafs** [comment]
Ahhhhh! Thanks @brycedrennan. So in my example this works:
```py
updated_m = updated_m.model_validate(updated_m.model_dump())
```

After reading [the docs](https://docs.pydantic.dev/2.3/usage/models/#helper-functions) this makes more sense now 😅
> model_validate: this is very similar to the __init__ method of the model, except it takes a dict rather than keyword arguments

Although, the docs also say:
> If the object passed is not a dict a ValidationError will be raised.

but, as you can see, in my example I'm passing that model instance to `model_validate` (not a dict) and no error is being raised 🤔. So maybe that's the bug here? 🤷‍♂️.

**Comment by brycedrennan** [comment]
I'm not sure what is supposed to happen but yeah I'd expect it to either error or validate the object.

**Comment by sydney-runkle** [comment]
> but, as you can see in my example, I'm passing that model instance to `model_validate` (not a dict) and no error is being raised 🤔. So maybe that's the bug here? 🤷‍♂️.

@slafs, I think this is behaving as expected - you're passing `updated_m.model_dump()`, which takes the form of a dict to `model_validate`.

Thanks @brycedrennan for providing this solution 😄.

**Comment by slafs** [comment]
> > but, as you can see in my example, I'm passing that model instance to `model_validate` (not a dict) and no error is being raised 🤔. So maybe that's the bug here? 🤷‍♂️.
> 
> @slafs, I think this is behaving as expected - you're passing `updated_m.model_dump()`, which takes the form of a dict to `model_validate`.

By "example", I meant this piece from [my previous comment](https://github.com/pydantic/pydantic/issues/7387#issuecomment-1714516510):
```py
# I'd expect this to fail.
updated_m = updated_m.model_validate(updated_m)
```

As @brycedrennan mentioned
> I'd expect it to either error or validate the object

And that doesn't fail nor validates the `updated_m` instance. I'm pretty sure that's a bug.

@sydney-runkle I feel like this issue should still be open.

**Comment by sydney-runkle** [comment]
@slafs, ah, gotcha! Happy to reopen and look into this further today. Thanks for clarifying!

**Comment by slafs** [comment]
Oh, this is not exactly that great as I initially thought.
When I change the snippet from https://github.com/pydantic/pydantic/issues/7387#issuecomment-1714516510 to:
```py
updated_m = updated_m.model_validate(updated_m.model_dump())
```
as mentioned earlier,
then I get a serialization warning (`Expected `SubModel` but got `dict` - serialized value may not be as expected`).

So to clear up the MRE confusion, here's the (v2 focused) problematic snippet:
```py
from pydantic import BaseModel


class SubModel(BaseModel):
    foo: int


class Model(BaseModel):
    bar: str
    sub: SubModel


model = Model(bar="bar", sub={"foo": 0})

# check that foo on sub is 0
assert model.sub.foo == 0


class InputModel(BaseModel):
    sub: SubModel


input_ = InputModel(sub={"foo": 1})

input_data = input_.model_dump(exclude_unset=True)
updated_m = model.model_copy(update=input_data)

# now check that foo on sub is 1
# this will raise AttributeError
try:
    assert updated_m.sub.foo == 1
except AttributeError as ex:
    assert str(ex) == "'dict' object has no attribute 'foo'"
else:
    assert False, "were expecting AttributeError"

# trick to fix this
new_input = updated_m.model_dump()
updated_m = updated_m.model_validate(new_input)
assert updated_m.sub.foo == 1
```

When run with `python -W error` it yells:
```text
Traceback (most recent call last):
  File "....py", line 38, in <module>
    new_input = updated_m.model_dump()
  File ".../lib/python3.10/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
UserWarning: Pydantic serializer warnings:
  Expected `SubModel` but got `dict` - serialized value may not be as expected
```

So now, the problem is again with how `.update` works I guess 🤷.

Versions:
```sh
pip freeze | grep pydantic
pydantic==2.4.2
pydantic-settings==2.0.2
pydantic_core==2.10.1
```

**Comment by sydney-runkle** [comment]
Hi @slafs,

Thanks for following up. I see 2 issues here, and both of them are in regards to `model_validate` behavior. As mentioned above in this thread and in the [docs](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_copy), the data passed to `update` of `model_copy` should be trusted, but I understand your desire to revalidate a model given the lack of validation on the update data.

1. When you call `updated_m = updated_m.model_validate(new_input)`, the error you're getting should not be raised. This is a bug 🐛, likely in `pydantic-core`. It seems as though we have a few bugs right now of that form ("Expected x but got y - serialized value may not be as expected").
2. Secondly, if you were to call `Model.model_validate(updated_m)`, either a `ValidationError` should be raised because the `sub` field is in the form of a dict, or a `Model` instance should be returned with `sub` in the form of a `SubModel`. Right now, the behavior is the following:

```py
updated_m = Model.model_validate(updated_m)
print(repr(updated_m))
#> Model(bar='bar', sub={'foo': 1})
```

Finally, as a side note, I think we need to update the [helper functions](https://docs.pydantic.dev/latest/concepts/models/#helper-functions) section of the docs, as the wording used to describe the acceptable input types to `model_validate` is a bit confusing.

Would you agree with these problems? We can work on fixes for all of the above this coming week.

**Comment by slafs** [comment]
Hey @sydney-runkle. Thanks for the summary. I agree, except that in 1. notice that the serialisation warning/error happens on `updated_m.model_dump()` hence my suggestion about "copy w. update" being the problem. Apart from that 👌.

**Comment by sydney-runkle** [comment]
@slafs,

Given that for 1. the warning occurs on `model_dump`, I don't think it's an issue actually. We've warned that `copy` with `update` is dangerous, and it's simply saying that when you're dumping `updated_m`, a `dict` is showing up where it expected a `SubModel`.

That being said, I still think 2. is a problem and the docs still need to be updated re the helper functions.

**Comment by sydney-runkle** [comment]
@slafs,

Looking into this further, it seems as though we missed a config param that solves our problem. We can use [`revalidate_instances`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.revalidate_instances) to get the desired behavior.

See this example as an MRE with said config param:

```py
from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    a: int

    model_config = ConfigDict(revalidate_instances='always')

m = Model(a=0)

# obviously not best practice, but just for demo purposes
m.a = "not an int"

m2 = Model.model_validate(m) # raises a ValidationError
```

And in your above MRE, you can use the following:
```py
class Model(BaseModel):
    bar: str
    sub: SubModel

    model_config = ConfigDict(revalidate_instances='always')
```

which guarantees that both of the following work:

```py
updated_m = Model.model_validate(updated_m)
updated_m = Model.model_validate(updated_m.model_dump())
```

Given this, I think it makes sense to close this issue once we merge a docs update PR. What are your thoughts?

**Comment by slafs** [comment]
Ah! Perfect! Yeah, that seems to be the missing bit 👍. Thank you! 🙇

**Comment by sydney-runkle** [comment]
@slafs

Sure thing. Thanks for following up with MREs and detailed explanations. Makes things much easier on our end 😄.
