### ISSUE TITLE
Mypy in PyCharm doesn't know about the PyDantic new functions

### ISSUE THREAD

**Issue by sombek** [pydantic/pydantic#7389]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using Mypy extension inside PyCharm 
it shows error for 
![image](https://github.com/pydantic/pydantic/assets/20394589/5de54d06-dcdf-4fa0-a4c7-a94ec0311e60)

![image](https://github.com/pydantic/pydantic/assets/20394589/f4c575c3-a5ab-4535-a6a3-c621e3367834)

But when I try to do mypy from cli it works just fine:
![image](https://github.com/pydantic/pydantic/assets/20394589/025a7365-3b11-4a49-a012-66a2993d6b0b)
* It shows expected errors - just to demo the bug - 

I am using the mypy plugin:
```
[mypy]
plugins = pydantic.mypy
```

I don't know where the bug exactly, is it related to mypy, PyCharm, or PyDantic?

### Example Code

```Python
class Model(BaseModel):
    model_config = {"from_attributes": True}
    age: int
    last_name: str | None = None
    signup_ts: datetime | None = None
    list_of_ints: list[int]


Model.parse_obj({"age": 1, "last_name": "a"})
Model.parse_raw(b'{"age": 1, "last_name": "a"}')
Model.model_validate({"age": 1, "last_name": "a"})
Model.model_dump()
Model.model_copy()
Model.model_json_schema()
Model.model_dump_json()
Model.model_rebuild()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/abdullahhashim/Projects/Job/REGA/rei-api/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by Kludex** [comment]
Well... It only works on instances of `BaseModel`. They are not `classmethod`s/`staticmethod`s.

If you instantiate a `Model` object, and try to run the methods, it should work as expected.

**Comment by sombek** [comment]
@Kludex How would I do it if I want to map ORM object to Pydantic object?
How would I instantiate without the mypy complaining?

**Comment by Kludex** [comment]
I'm not following your use case. The "methods" you are trying to use doesn't exist for the class, so mypy is correct.

**Comment by sombek** [comment]
@Kludex Thanks for you response 

I tried to instantiate a model. But still mypy is complaining:
<img width="531" alt="image" src="https://github.com/pydantic/pydantic/assets/20394589/0d130104-669e-4597-8b92-c833074db42b">

**Comment by dmontagu** [comment]
It's hard to be certain without seeing more details, but this appears to me to be a bug specifically with the PyCharm Mypy extension you are using. If you can reproduce those mypy errors using just the CLI (and not the PyCharm UI), we can look into it (though I will be surprised if you can, since I think this would be a very obvious issue with pydantic or mypy).

I also don't think this is a general-PyCharm issue as I use PyCharm (without the mypy extension) and don't have this issue, which is why I think it's probably an issue with the PyCharm mypy extension and/or your configuration of it. If that extension has a public GitHub or similar, it might make sense to report the issue there and see if they suggest anything.

**Comment by sombek** [comment]
Thanks for the heads up @dmontagu 
You are correct the extension was pointing to to different version for mypy not the one in the venv
It was pointing to:
/Library/Frameworks/Python.framework/Versions/3.11/bin/mypy
- Which could be the default behavior for the default configs for mypy-pycharm plugin - 

The fix:
/Users/user/Projects/my-project/venv/bin/mypy

Thanks,
Problem fixed 🙏
