### ISSUE TITLE
Assigning mutable value to new field appears to make copy

### ISSUE THREAD

**Issue by robcxyz** [pydantic/pydantic#7390]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I ran into this error upgrading to pydantic 2.0 where it appears that when I assign a mutable value to a field that it gets copied by default instead of hanging on to the reference.  I can confirm this code example passes in pydantic 1.x but fails in 2.3.0. 

### Example Code

```Python
from pydantic import BaseModel

class A(BaseModel):
    origin: dict[str, list]
    new_value: list = None

    def do(self):
        self.new_value = self.origin['a']
        self.new_value.append(1)

origin_input = {'a': [1, 2]}
a = A(origin=origin_input)
a.do()

try:
    # This works in pydantic 1.x but fails in 2.3
    assert origin_input['a'] == [1, 2, 1]
except AssertionError:
    raise
```

### Python, Pydantic & OS Version

```Text
pydantic 2.3 on ubuntu
```

**Comment by sydney-runkle** [comment]
Hi @robcxyz,

The issue here is not that assigning a mutable value to a new field makes a copy, but rather that the mutable field value is copied when the instance is created.

That being said, I don't think that this is clearly reflected in the docs, so I'll open a PR to make that more clear - I'll include a more in depth explanation there.

**Comment by sydney-runkle** [comment]
This is actually already in the docs and can be found [here](https://docs.pydantic.dev/latest/usage/models/#attribute-copies). Closing now given that the docs reflect this behavior appropriately + with an example.

**Comment by robcxyz** [comment]
@sydney-runkle - So you are correct, it is in the docs but not in the migration guide. Since this is IMO a pretty big change from 1.x (ie all values are copied now), then I think this should be emphasized more in https://docs.pydantic.dev/latest/migration/

Also updated example to be a little more clear - little convoluted before.

**Comment by robcxyz** [comment]
Also is there any way to avoid copying mutable values in 2.x and just passing a reference so that they can be mutated within a method on the model? Apologies, might be an adjacent question to this.

**Comment by sydney-runkle** [comment]
Hi @robcxyz,

> @sydney-runkle - So you are correct, it is in the docs but not in the migration guide. Since this is IMO a pretty big change from 1.x (ie all values are copied now), then I think this should be emphasized more in https://docs.pydantic.dev/latest/migration/

Good idea re adding this info to the migration guide. Would you be interested in opening a PR with documentation changes?

> Also is there any way to avoid copying mutable values in 2.x and just passing a reference so that they can be mutated within a method on the model? Apologies, might be an adjacent question to this.

I'm not sure of a workaround at the moment. Do you have a particular use case you're considering for this type of behavior? Perhaps I'd be better suited to come up with a solution given some more context. Thanks 😄.

**Comment by robcxyz** [comment]
Hi @sydney-runkle - Thanks for making the documentation change. Was out for a bit and was just about to do it but then saw you had made the change yourself. 

As for my use case for maintaining references, it is a bit non-standard so no further discussion needed. I pulled out pydantic from a big part of my project and only using it for validation purposes now knowing that all inputs are copied. By doing so, also increased performance of my tool significantly (~5x improvement) so anyways, inadvertently by using pydantic only how it should be used has been a big win.

Sorry for not getting to PR sooner and thanks again for your help.
