### ISSUE TITLE
Alternative API for checking if a field was set

### ISSUE THREAD

**Issue by RobertCraigie** [pydantic/pydantic#7395]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently the only way to check if a field was included in the model data is to use `model.model_fields_set` which works perfectly well but results in *slightly* awkward code when this is used in certain contexts, e.g.

```py
assert ("resource_id" in obj.model_fields_set) is False
```

Omitting the brackets here results in a bug due to the evaluation order
```py
assert "resource_id" in obj.model_fields_set is False
# evaluates to `assert False`
```

This footgun could be avoided if there was a method that could be called instead, e.g. something along these lines
```py
assert obj.model_field_is_set('resource_id') is False
```
Thoughts?

Note: you could write something like `obj.model_fields_set.__contains__('resource_id')` but that seems quite ugly to me and non-obvious.

---
Apologies if this has has been discussed before, I couldn't find anything.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
You could simply do `assert "resource_id" not in obj.model_fields_set`

**Comment by RobertCraigie** [comment]
Ahh yeah that is a good point 🤦
