### ISSUE TITLE
mypy thinks a config variable can never be `None` when nested in inherited BaseModel class

### ISSUE THREAD

**Issue by Greesb** [pydantic/pydantic#7399]
Hello,

I just switched a project to pydantic v2 and encountered a bug with mypy thinking that some variable can never be `None` when the typing and the default value clearly indicate otherwise.

Here's a minimal code that reproduce the error:
```python
 
import pydantic


class ModelNested(pydantic.BaseModel):
    my_var: str | None = pydantic.Field(default=None)


class Model(ModelNested):
    pass

m = Model()
if m.my_var is None:
    print("hello there")  # mypy thinks we can never go inside this if
```

Here's the mypy error: `test.py:14: error: Statement is unreachable  [unreachable]`

**Comment by hramezani** [comment]
related to https://github.com/pydantic/pydantic/issues/7398
