### ISSUE TITLE
Impossible to revalidation frozen instances that do not allow extra fields

### ISSUE THREAD

**Issue by FynnBe** [pydantic/pydantic#7403]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Arguably an edge case: model_validate fails to revalidate frozen instances that do not allow extra fields and have a private field.
The code example raises a ValidationError with "_internal_field: Extra inputs are not permitted".

note: The `TYPE_CHECKING`/`ClassVar` bit is only to pass pyright in strict mode. Suggestions to improve type annotations for this use case are highly welcome! 

### Example Code

```Python
from typing import TYPE_CHECKING, ClassVar

from pydantic import (
    BaseModel,
    model_validator,  # type: ignore
)


class MyModel(BaseModel, frozen=True, revalidate_instances="always", extra="forbid"):
    if TYPE_CHECKING:
        _internal_field: ClassVar[int]  # as ClassVar to hide _internal_field from __init__
    else:
        _internal_field: int

    @model_validator(mode="after")
    def set_internal(self):
        object.__setattr__(self, "_internal_field", 1)
        return self


MyModel.model_validate(MyModel())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\fbeut\mambaforge\envs\bio38\Lib\site-packages\pydantic
               python version: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19041-SP0
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @FynnBe for this issue 🙏 

`_internal_field` is a private attribute and  based on [private attributes docs](https://docs.pydantic.dev/2.3/usage/models/#private-model-attributes) the error seems correct.

> Attributes whose name has a leading underscore are not treated as fields by Pydantic, and are not included in the model schema. Instead, these are converted into a "private attribute" which is not validated or even set during calls to `__init__`, `model_validate`, etc.

Did I misunderstand the issue?

**Comment by sydney-runkle** [comment]
Hey @FynnBe,

Following up further - @hramezani was entirely correct to point out that private attributes aren't treated as fields by Pydantic. The issue that you're having is that you're not actually assigning a value to the private field correctly.

Two other approaches you could use would be:
```py
    @model_validator(mode="after")
    def set_internal(self):
        self._internal_field = 1
        return self
```
or
```py
    @model_validator(mode="after")
    def set_internal(self):
        self.__pydantic_private__['_internal_field'] = 1
        return self
```

Using either of these in place of your current `set_internal` function will not result in a validation error.

When you use the `__setattr__`, you're setting the `_internal_field` within the `__dict__` attribute of the instance. Private fields aren't actually stored here, which was causing your error.

**Comment by FynnBe** [comment]
Thanks! 
I expected to have to work around my instance being frozen 🤦
