### ISSUE TITLE
Standadize EmailStr validator __get_pydantic_core_schema__ method

### ISSUE THREAD

**Issue by aasay** [pydantic/pydantic#7407]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Currently the __get_pydantic_core_schema__ method for the EmailStr validator only accepts a single argument for "source".  All of the documentation for __get_pydantic_core_schema__ references that it should accept both a source and a handler argument.  This specifically is a problem when working with third party packages and knowing how many arguments to pass.

### Example Code

Current Code /pydantic/networks.py

```python
if TYPE_CHECKING:
    EmailStr = Annotated[str, ...]
else:

    class EmailStr:
        """Validate email addresses.

        Example:
            ```py
            from pydantic import BaseModel, EmailStr

            class Model(BaseModel):
                email: EmailStr

            print(Model(email='contact@mail.com'))
            #> email='contact@mail.com'
            ```
        """

        @classmethod
        def __get_pydantic_core_schema__(
            cls,
            source: type[Any]
        ) -> core_schema.CoreSchema:
            import_email_validator()
            return core_schema.general_after_validator_function(cls._validate, core_schema.str_schema())
```

Proposed

```python
if TYPE_CHECKING:
    EmailStr = Annotated[str, ...]
else:

    class EmailStr:
        """Validate email addresses.

        Example:
            ```py
            from pydantic import BaseModel, EmailStr

            class Model(BaseModel):
                email: EmailStr

            print(Model(email='contact@mail.com'))
            #> email='contact@mail.com'
            ```
        """

        @classmethod
        def __get_pydantic_core_schema__(
            cls,
            source: type[Any],
            handler: Callable[[Any], core_schema.CoreSchema] = None
        ) -> core_schema.CoreSchema:
            import_email_validator()
            return core_schema.general_after_validator_function(cls._validate, core_schema.str_schema())

```

**Comment by hramezani** [comment]
Thanks @aasay for this issue 🙏 
I've merged a [PR](https://github.com/pydantic/pydantic/commit/b46010bf4a73d439e3faf98e6e2e16e2faf7e6e2) to fix this.
