### ISSUE TITLE
Pydantic 2.x warning typing.Optional is not a Python type

### ISSUE THREAD

**Issue by russell310** [pydantic/pydantic#7410]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

UserWarning: typing.Optional is not a Python type (it may be an instance of an object), Pydantic will allow any object with no validation since we cannot even enforce that the input is an instance of the given type. To get rid of this error wrap the type with `pydantic.SkipValidation`.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /projects/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.5.2-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by Viicos** [comment]
Could you please provide an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? You're most likely using a type hint in a wrong way

**Comment by russell310** [comment]
```
from typing import Optional
from pydantic import BaseModel, EmailStr


class UserBase(BaseModel):
    email: Optional[EmailStr] = None
    is_active: Optional[bool] = True
    is_superuser: bool = False
    full_name: Optional[str] = None


class UserCreate(UserBase):
    email: EmailStr
    password: str


class UserUpdate(UserBase):
    password: Optional[str] = None


class UserInDBBase(UserBase):
    id: Optional[int] = None

    class Config:
        from_attributes = True


class User(UserInDBBase):
    pass


class UserInDB(UserInDBBase):
    hashed_password: str

```

**Comment by Viicos** [comment]
The example you gave is working as expected. You've most probably used `Optional` without any type. Try looking for a model where `arbitrary_types_allowed` is set to `True` and with a field typed as `Optional` without anything
