### ISSUE TITLE
Build: Pydantic python-ast broken dependency on Apple Silicon

### ISSUE THREAD

**Issue by heliocastro** [pydantic/pydantic#7413]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Current pydantic module has python-ast dependency target to version 1.4.3.
This version has a build issue on Mac Silicon machines that was solved on later releases. ( Tested with current 1.5.5 release )

On current status it renders impossible to install pydantic ( at least with poetry ) when wheel is attempt to be built.

### Python, Pydantic & OS Version

```Text
Python 3.10.13
pydantic 2.3
Mac OS 13.5.1
Clang version 14.0.0
```

**Comment by Kludex** [comment]
> Current pydantic module has python-ast dependency target to version 1.4.3.

Where do you see this? 🤔

**Comment by heliocastro** [comment]
I spend the morning doing the crosscheck with gcc, the issue is brought when you have older mypy deps, pulling the wrong code to build wheel.
Original cause was pyartifactory library, long time not updated on build dependencies, and upgrading to pydantic2 alone.

Sorry for the noise, i 'm closing down this as wrong target.
