### ISSUE TITLE
ValidationError is raised for using conint with both gt and le parameters.

### ISSUE THREAD

**Issue by desertear** [pydantic/pydantic#7420]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

With below codes which was working for pydantic==1.10.5, but is not working for v2. I think it's the simplest way of using conint, but don't know why it's not working.
The error raised by Pytest:
"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/xyan/projects/new_restapi/demo/backup, configfile: pytest.ini
plugins: metadata-2.0.4, hypothesis-6.84.3, xdist-3.3.1, html-3.2.0, reportportal-5.1.5
collected 1 item                                                                                                                                                                                                  

test_1.py::test_pydantic FAILED                                                                                                                                                                             [100%]

==================================================================================================== FAILURES =====================================================================================================
__________________________________________________________________________________________________ test_pydantic __________________________________________________________________________________________________

    @given(st.builds(FTMPush))
>   @settings(max_examples=20)
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for FTMPush
E   server_port
E     Input should be greater than 10 [type=greater_than, input_value=0, input_type=int]
E       For further information visit https://errors.pydantic.dev/2.3/v/greater_than

test_1.py:68: ValidationError
============================================================================================= short test summary info =============================================================================================
FAILED test_1.py::test_pydantic - pydantic_core._pydantic_core.ValidationError: 1 validation error for FTMPush
================================================================================================ 1 failed in 0.26s ================================================================================================
"

### Example Code

```Python
from pydantic import BaseModel, conint, validator, confloat
class FTMPush(BaseModel):
    status: Literal["enable", "disable"]
    server_port: conint(gt=10,le=65535)

@given(st.builds(FTMPush))
@settings(max_examples=20)
def test_pydantic(instance):
    assert 1 == 1
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/xyan/projects/venv/venv_rest_api_new/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

**Comment by desertear** [comment]
hypothesis==6.84.3

**Comment by sydney-runkle** [comment]
Hi - thanks for your question.

Based on this line of your validation error output, it looks like you're passing in a value of `0` for the `server_port` param. Thus, this error is expected, as `0` is not greater than `10`, as specified by `server_port: conint(gt=10,le=65535)`
```
Input should be greater than 10 [type=greater_than, input_value=0, input_type=int]
```

**Comment by desertear** [comment]
Thanks, then I think the issue comes from hypothesis side.
