### ISSUE TITLE
TypeAdapter for RootModel doesn't work with RootModel instance

### ISSUE THREAD

**Issue by adam-pawluczuk** [pydantic/pydantic#7426]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello!

It seems like the `TypeAdapter` doesn't work with instances of `RootModel`.

Let me demonstrate:
```py
from typing import Any, Generic, Literal, TypeVar, Union
from pydantic import Field, RootModel, BaseModel, TypeAdapter

_S = TypeVar("_S")

class Ok(BaseModel, Generic[_S]):
    success: Literal[True] = True
    result: _S


class Error(BaseModel):
    success: Literal[False] = False


class APIResult(RootModel[Union[Ok[_S], Error]]):
    root: Union[Ok[_S], Error] = Field(discriminator="success")


api_result = APIResult(Ok(result="result"))
adapter: TypeAdapter[Any] = TypeAdapter(APIResult[str])
adapter.validate_python(api_result, from_attributes=True)
```

This results in:
```sh
Traceback (most recent call last):
  File "/Users/apawlucz/src/scripts/test_pydantic_generics.py", line 67, in <module>
    adapter.validate_python(api_result, from_attributes=True)
  File "/Users/apawlucz/opt/anaconda3/envs/rd_310/lib/python3.10/site-packages/pydantic/type_adapter.py", line 209, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for APIResult[str]
  Unable to extract tag using discriminator 'success' [type=union_tag_not_found, input_value=APIResult(root=Ok(success=True, result='result')), input_type=APIResult]
    For further information visit https://errors.pydantic.dev/2.3/v/union_tag_not_found
```

After looking into this, this works when dumping the `RootModel` instance to dict first:
```py
adapter.validate_python(api_result.dict(), from_attributes=True)
```

I'd rather expect `validate_python()` to be working regardless if `dict` is being passed or actual model instance.

Docs for `TypeAdapter` don't mention the `RootModel`.

To give a little bit of context:

the snippets above are just an example how serialization/validation works in FastAPI:
```py
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def root() -> APIResult[str]:
    return APIResult(root="str")
```

So similarly this fixes the issue:
```py
@app.get("/")
def root() -> APIResult[str]:
    return APIResult(root="str").dict()
```

But of course `mypy` doesn't like it (which is correct).

And then when starting the FastAPI app and going to the `/` root path this is what I'm getting:
```
  ... [TRUNCATED]

  File "/Users/apawlucz/opt/anaconda3/envs/rd_310/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    content = await serialize_response(
  File "/Users/apawlucz/opt/anaconda3/envs/rd_310/lib/python3.10/site-packages/fastapi/routing.py", line 154, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'union_tag_not_found', 'loc': ('response',), 'msg': "Unable to extract tag using discriminator 'success'", 'input': APIResult(root=Ok(success=True, pet_type='cat', result='str')), 'ctx': {'discriminator': "'success'"}, 'url': 'https://errors.pydantic.dev/2.3/v/union_tag_not_found'}
```

So this stems from the fact how the FastAPI uses `TypeAdapter` to validate the model.

This is how FastAPI instantiates `TypeAdapter`:
* https://github.com/tiangolo/fastapi/blob/0.103.1/fastapi/_compat.py#L100-L103

And this is how it gets used:
* https://github.com/tiangolo/fastapi/blob/0.103.1/fastapi/_compat.py#L117-L121

At first I thought this is a FastAPI bug, but now I'm leaning towards thinking this is rather a Pydantic bug (though not 100% sure).

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/apawlucz/opt/anaconda3/envs/rd_310/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:24:27) [Clang 14.0.6 ]
                     platform: macOS-13.5.2-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']

FastAPI version: 0.103.1
```

**Comment by dmontagu** [comment]
Do you need the discriminator here? If you comment out the `= Field(discriminator="success")` the error goes away.

This makes sense because what's happening is it's trying to access the `.success` attribute to determine which case to validate as. The problem is that `APIResult[str]` wants to get an instance of `APIResult[str]`, but you've passed an instance of `APIResult`, which is actually a parent class of `APIResult[str]`. (With pydantic generics, unlike "regular" generics, `__class_getitem__` actually returns subclasses, not just GenericAliases. This is important because we store the validation logic in class attributes, and they need to be different for concrete parametrizations of the generic models.)

Because you are passing in an `APIResult`, which is not a subclass of `APIResult[str]`, it tries to look for the discriminator for validation, but of course `APIResult` doesn't have an attribute `success`, it just has `root`.

I'll note that if you do give it an instance of the correct subclass, the error goes away:
```python
from typing import Any, Generic, Literal, TypeVar, Union
from pydantic import Field, RootModel, BaseModel, TypeAdapter

_S = TypeVar("_S")

class Ok(BaseModel, Generic[_S]):
    success: Literal[True] = True
    result: _S


class Error(BaseModel):
    success: Literal[False] = False


class APIResult(RootModel[Union[Ok[_S], Error]]):
    root: Union[Ok[_S], Error] = Field(discriminator="success")


api_result = APIResult[str](Ok[str](result="result"))
adapter: TypeAdapter[Any] = TypeAdapter(APIResult[str])
adapter.validate_python(api_result, from_attributes=True)
```

**Comment by adam-pawluczuk** [comment]
This indeed works. Thank you!

**Comment by sydney-runkle** [comment]
Glad to hear that @dmontagu's solution worked for you!
