### ISSUE TITLE
Literal 

### ISSUE THREAD

**Issue by ImogenBits** [pydantic/pydantic#7427]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When validating a Literal field pydantic rejects any values of subclasses the standard library types even though the values are correct. This causes a lot of annoying problems when parsing data with libraries such as tomlkit that return richer data than just the standard library types.

If this is indented behaviour this should be mentioned in the docs I think and the current error message changed. The code below errors with "Input should be 1 [type=literal_error, input_value=1, input_type=MyInt]" when it should say that the type is the problem here, not the value.

### Example Code

```Python
from pydantic import TypeAdapter

class MyInt(int):
    pass

one = TypeAdapter(Literal[1])
one.validate_python(MyInt(1))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
pydantic-core version: 2.6.3
pydantic-core build: profile=release pgo=false     
python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0     
optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @ImogenBits,

Thanks for your question.

Currently, `mypy` doesn't allow this kind of behavior. See this similar example:
```py
from typing import Literal


class MyInt(int):
    pass


x: Literal[1] = MyInt(1)
```

Which raises this error:
```
Incompatible types in assignment (expression has type "MyInt", variable has type "Literal[1]")  [assignment]
```

Additionally, the [PEP Specification for Literal Types](https://peps.python.org/pep-0586/) doesn't suggest that this is a valid use of the `Literal` type. 
According to `mypy` and the PEP, we think the current behavior of Pydantic is as it should be.

That being said, this behavior doesn't necessarily have a right or wrong answer. Here's one workaround that you could use if you're hoping to still use this pattern:

```py
from dataclasses import dataclass
from typing import Annotated, Any

from pydantic_core import core_schema as cs

from pydantic import GetCoreSchemaHandler, TypeAdapter


@dataclass
class RuntimeLiteral:
    value: Any

    def __get_pydantic_core_schema__(self, _tp: Any, _handler: GetCoreSchemaHandler) -> cs.CoreSchema:
        def check_value(v: Any) -> Any:
            if v != self.value:
                raise ValueError(f'Expected a literal value of {self.value}, got {v}')
            return v

        return cs.no_info_plain_validator_function(check_value)


class MyInt(int):
    def __repr__(self) -> str:
        return f'MyInt({super().__repr__()})'


print(TypeAdapter(Annotated[int, RuntimeLiteral(42)]).validate_python(MyInt(42)))
# MyInt(42)
```

Let me know if you have any follow up questions! Thanks to @adriangb for the code sample.

**Comment by ImogenBits** [comment]
Oh yeah you're absolutely right, I was thinking about this in the wrong ways. In my mind I interpreted a literal field to basically perform the same casting rules as normal string/int/bool fields and then validate equality to one of the literal values. I didn't think about them as validating into the literal subtypes. My actual use case was essentially using `Literal["a", "b"]` as a quicker way to write a string enum, which probably is the nicer solution anyways so I just went with that now.

Thinking about it now this still feels somewhat unintuitive since it behaves very different from the str/int/bool types which coerce values of other types in lax mode. Would it be sensible to change literal validation to behave essentially like this?
```py
class IntLiteral:
    def __init__(self, num: int, *args: int) -> None:
        self.values = set(args)
        self.values.add(num)

    def __get_pydantic_core_schema__(self, source: type, handler: GetCoreSchemaHandler) -> CoreSchema:
        def validate(val: int) -> int:
            if val not in self.values:
                raise ValueError(f"Expected a literal value in {', '.join(str(self.values))}, got {val}")
            else:
                return val
        return no_info_after_validator_function(validate, handler(int))
```
That is, apply all the normal rules for coercing values and then check for equality. In strict mode this would behave as it does currently but in lax mode subclasses would be upcast to the builtin type. If this is something you think is reasonable I'd be happy to try and make a PR for it (though I'd have to get myself familiar with the pydantic-core codebase first).

**Comment by dmontagu** [comment]
@samuelcolvin @adriangb I feel like you guys might have opinions about this. Also I suspect there would be performance implications

**Comment by adriangb** [comment]
I don’t think the change is helpful, especially given that there is a simple custom solution given above. I certainly would not consider it unless there are many 👍 requesting it and no opposition: for all we know we implement that and then we’ll get both complaints about a breaking change and complaints about it being the wrong behavior.

**Comment by ImogenBits** [comment]
fair enough, I'll keep using enums then. thanks for the help!
