### ISSUE TITLE
model_dump returns incorrect type

### ISSUE THREAD

**Issue by sileht** [pydantic/pydantic#7431]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We recently migrated from pydantic V1 to V2, we have an issue with custom types that inherit from named tuple.

This was worked fine with pydantic V1, but since we migrate to V2 mode_dump is returning a simple tuple instead of our custom type.

I provided an example below.

### Example Code

```Python
import typing
from urllib import parse

import pydantic
import pydantic_core


class SecretUrl(parse.SplitResult):
    def __str__(self) -> str:
        return "secret string"

    __repr__ = __str__

    @classmethod
    def parse(cls, v: str | parse.SplitResult) -> typing.Self:
        if isinstance(v, parse.SplitResult):
            parsed = v
        else:
            parsed = parse.urlsplit(v)

        return cls(
            scheme=parsed.scheme,
            netloc=parsed.netloc,
            path=parsed.path,
            query=parsed.query,
            fragment=parsed.fragment,
        )

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: typing.Any, handler: pydantic.GetCoreSchemaHandler
    ) -> pydantic_core.CoreSchema:
        return pydantic_core.core_schema.no_info_plain_validator_function(cls.parse)


class Example(pydantic.BaseModel):
    url: SecretUrl


obj = Example(url="foo://user:pass@example.com/path")
print(type(obj.url))
print(type(obj.model_dump().get("url")))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/sileht/workspace/mergify/engine5/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.0-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sileht** [comment]
An even simplier example:
```
import typing

import pydantic


class SecretTuple(typing.NamedTuple):
    scheme: str
    netloc: str

    def __str__(self) -> str:
        return "secret"

    __repr__ = __str__


class Example(pydantic.BaseModel):
    url: SecretTuple


obj = Example(url=("foo", "example"))
print(obj.url)
print(obj.model_dump().get("url"))
print(type(obj.url))
print(type(obj.model_dump().get("url")))
```

This print in pydantic V2:
```
secret
('foo', 'example')
<class '__main__.SecretTuple'>
<class 'tuple'>
```

While in V1, we used:
```
print(obj.url)
print(obj.dict().get("url"))
print(type(obj.url))
print(type(obj.dict().get("url")))
```
And it prints
```
secret
secret
<class '__main__.SecretTuple'>
<class '__main__.SecretTuple'>
```

**Comment by sileht** [comment]
Sorry for the noise, we should have used:

print(type(dict(obj).get("url")))

**Comment by sileht** [comment]
I reopen it, shouldn't `obj.model_dump()` and `dict(obj)` to the same thing?

**Comment by sydney-runkle** [comment]
Hi - thanks for your question.

See the [dict(model)](https://docs.pydantic.dev/latest/usage/serialization/#dictmodel-and-iteration) documentation for an explanation of the differences between `model.model_dump()` and `dict(model)`.  These differences are intentional and explain your questions raised above :).

**Comment by sileht** [comment]
Thanks for pointing me the documentation, but it just talks about submodel not been converted. My example it not a submodel, it's a namedtuple. 

In pydantic V1 using `dict(obj)` or `obj.dict()` was returning the namedtuple. In V2 `dict(obj)` return the namedtuple, `obj.model_dump()` return a simple tuple.

**Comment by sileht** [comment]
A even more explicit example:

```
import typing

from pydantic import BaseModel as BaseModelV2
from pydantic.v1 import BaseModel as BaseModelV1


class Foo(typing.NamedTuple):
    url: str


class ModelV1(BaseModelV1):
    foo: Foo


class ModelV2(BaseModelV2):
    foo: Foo


objV1 = ModelV1(foo=Foo(url="https://example.com"))
print(type(dict(objV1).get("foo")))
print(type(objV1.dict().get("foo")))

objV2 = ModelV2(foo=Foo(url="https://example.com"))
print(type(dict(objV2).get("foo")))
print(type(objV2.dict().get("foo")))
```

It prints:
```
<class '__main__.Foo'>
<class '__main__.Foo'>
<class '__main__.Foo'>
/Users/sileht/workspace/mergify/engine1/toto.py:26: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.3/migration/
  print(type(objV2.dict().get("foo")))
<class 'tuple'>
<class 'tuple'>
```

**Comment by sileht** [comment]
@sydney-runkle I added another example to point to real issue, do you prefer me to open another clearer report?

**Comment by sydney-runkle** [comment]
Hi,

Thanks for following up with some more explicit examples. Looks like you were able to open a new issue and get some feedback. Linking that here for reference: https://github.com/pydantic/pydantic/issues/7433#issuecomment-1718219785

Just as a side note (I'm guessing you saw the deprecation warning in your output), `model.dict()` is deprecated in V2 in favor of `model.model_dump()`, which is documented in the migration docs [here](https://docs.pydantic.dev/2.3/migration/#changes-to-pydanticbasemodel).
