### ISSUE TITLE
Validate Protocol 

### ISSUE THREAD

**Issue by SylvainGuieu** [pydantic/pydantic#7446]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I am using Protocol in python and though the pydantic could accept Protocol as annotation 

```python
from typing_extensions import Protocol 
from pydantic import BaseModel 

class Getter(Protocol):
     def get(self):
         ...

class Model(BaseModel):
     getter: Getter 
``` 

In the exemple above it would means that getter is expected to be conform to the Getter Protocol, i.e. it should have the get method. 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Kludex** [comment]
You'll need to define a `__get_pydantic_core_schema__`, as mentioned in the error message. See [Customizing validation with `__get_pydantic_core_schema__`](https://docs.pydantic.dev/latest/usage/types/custom/#customizing-validation-with-__get_pydantic_core_schema__) for more information.

**Comment by adnanhd** [comment]
As far as I understand, `pydantic` focuses on runtime data validation, settings management, and serialization tasks. It utilizes Python type annotations to define schemas and performs validation during runtime based on these definitions. `pydantic` offers flexibility in handling data structures and settings, making it well-suited for scenarios where data validation and parsing are crucial, although it also supports type checking alongside its primary functionalities.

I guess your use case looks closer to `mypy`, which serves as a robust static type checker, prioritizing type safety and correctness during compilation. `mypy` encourages strict typing practices, ensuring that type-related errors are caught early in development. it integrates seamlessly with existing Python codebases, allowing for gradual adoption of type annotations. 

Considering a dummy example below, using the `dummy_validator` function ensures that the `Foo` and `Bar` classes conform to the `Getter` protocol.
```python
from pydantic import BaseModel
from typing import Protocol, Annotated, Callable, Any

class Getter(Protocol):
    def get(self) -> None:
        ...

class GetterModel:
    def get(self) -> None:
        pass

class NonGetterModel:
    ...

class AnyValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _type: type, _handler: Callable) -> dict[str, Any]:
        return {'type':'any'}

class Model(BaseModel):
    getter: Annotated[Getter, AnyValidation]

Model(getter=GetterModel()) # mypy works fine
Model(getter=NonGetterModel()) # mypy raises an error
```

Or another example below (which is more closer to my usecase :D)
```python
from typing import Protocol

class Getter(Protocol):
    def get(self) -> None:
        ...


def register_model(cls: type[Getter]) -> type[Getter]:
    return cls


@register_model
class Foo:
    def get(self) -> None:
        ...


@register_model  # Here mypy will raise an error
class Bar:
    ...
