### ISSUE TITLE
Pydantic v2 custom types not receiving all fields in info

### ISSUE THREAD

**Issue by matthewagee** [pydantic/pydantic#7448]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I want to use the `field_name` and `data` attributes of `info` when validating with my custom types. I tried multiple approaches following [the docs](https://docs.pydantic.dev/latest/usage/types/custom/#as-an-annotation) in my simplified example code and `info` is missing those fields for most of them. The output of the example code looks like:

```
Validating with_field_validator
Validating not_the_real_field_name
use_this='Has data' with_field_validator='Has data' with_annotated='No data' core_schema_gen_b4_method='No data' core_schema_plain_method='No data' core_schema_field_b4_method='Has data' core_schema_annotated='No data'
```

The one that comes closest to working uses `field_before_validator_function` in `__get_pydantic_core_schema__`. It has data defined correctly, but the `field_name` is whatever I feed into it and I can't find a way to figure out what the real `field_name` is inside `__get_pydantic_core_schema__`. 

Can you let me know what I'd need to do to get `info` with all the fields or, as a workaround, how I can figure out the `field_name` when I'm inside `__get_pydantic_core_schema__`?

### Example Code

```Python
from dataclasses import dataclass
from typing import Annotated, List, Any, Callable


from pydantic import ValidationError, BaseModel, Field, BeforeValidator, field_validator, GetCoreSchemaHandler
from pydantic_core import core_schema, CoreSchema


def fn(v: str, info: core_schema.ValidationInfo, *args, **kwargs) -> str:
    try:
        print(f'Validating {info.field_name}')
        return info.data['use_this']
    except AttributeError as err:
        return 'No data'


class AsPlainMethod(str):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        return core_schema.general_plain_validator_function(fn)


class AsB4Method(str):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        return core_schema.general_before_validator_function(fn, core_schema.str_schema())


class AsFieldB4Method(str):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler, *args, **kwargs
    ) -> CoreSchema:
        return core_schema.field_before_validator_function(fn, 'not_the_real_field_name', core_schema.str_schema())
    

@dataclass
class AsAnnotation:
    func: Callable[[Any], Any]

    def __get_pydantic_core_schema__(
        self, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        return core_schema.general_before_validator_function(
            self.func, handler(source_type)
        )


class MyModel(BaseModel):
    use_this: str

    # Works
    with_field_validator: str
    validate = field_validator('with_field_validator', mode='before')(fn)

    # Annotated does not work
    with_annotated: Annotated[str, BeforeValidator(fn)]

    # Core schema does not work
    core_schema_gen_b4_method: AsB4Method
    core_schema_plain_method: AsPlainMethod
    core_schema_field_b4_method: AsFieldB4Method  # Partially works
    core_schema_annotated: Annotated[str, AsAnnotation(fn)]


model = MyModel(**{
    'use_this': 'Has data', 
    'with_field_validator': 'a', 
    'with_annotated': 'b',
    'core_schema_gen_b4_method': 'c',
    'core_schema_plain_method': 'd', 
    'core_schema_field_b4_method': 'e', 
    'core_schema_annotated': 'f', 
})
print(model)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/magee1/Projects/venvs/test_env/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 28 2023, 18:33:55) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.2.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
Yes, this is by design since when you're defining the custom type, you can't guarantee that it will be used as a field within a model, therefor `field_name` and `data` might not be available.

We might revisit this in the future since I know it's a little restrictive, in the meantime you'll need to use `@field_validator`.

**Comment by matthewagee** [comment]
Ok I was hoping I could just modify my custom types in-place and avoid touching models, but sounds like I'll need to switch my models to using validators. I don't know how hard it would be to implement but any of making `field_name` and `data` populated on `info` when in a model, making the current `field_name` accessible in `__get_pydantic_core_schema__` or making `field_name` and `data` optional args (like the values and field args from v1) would all make this possible and make the v1 to v2 transition easier. I'll open a feature request around this

**Comment by samuelcolvin** [comment]
Reopening, and I'll discuss with the team on Monday.

I think in theory it's pretty easy to make them both both available, we had to implement specific logic to make them not available, the idea was to be more type safe, but I agree it's an unnecessary restriction.

**Comment by matthewagee** [comment]
Ok thanks. I was prepping a feature request so here's a code demo for the second option I mentioned. I think the first would be easiest to use but just in case second is easier to implement

<pre>
class AsFieldB4Method(str):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler, *args, **kwargs
    ) -> CoreSchema:
        return core_schema.field_before_validator_function(fn, <b>[source_type.field_name/kwargs['field_name']/some other way to access]</b>, core_schema.str_schema())
</pre>

Also not sure, but I think this feature request might be related #6794

**Comment by samuelcolvin** [comment]
Yes, it's the same root issue.

**Comment by ybressler** [comment]
Is this SO answer a solution for you in any way? @matthewagee https://stackoverflow.com/questions/77100890/pydantic-v2-custom-type-validators-with-info/77108459#77108459

Also, @samuelcolvin -> what are your thoughts on me updating the docs for how to add/create a custom field? (Seems to be a gap in new capabilities X what is documented.) --> I can create the ticket, but would need some guidance on where that info would live. (I would want to do an overview of how to approach certain problems, it will span domains of annotated validators, custom classes, and core_schema stuff – similar to the SO solution above.)

**Comment by ybressler** [comment]
(Created a ticket for updating docs: https://github.com/pydantic/pydantic/issues/7534)
