### ISSUE TITLE
Feature Request: Public metaclass for model classes

### ISSUE THREAD

**Issue by spchamp** [pydantic/pydantic#7450]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

## Overview

I'm updating the [models](https://github.com/fxtatools/pyfx_dispatch_oanda/tree/main/src/pyfx/dispatch/oanda/models) section of a codebase mentioned in #7447 to use Pydantic v2. This codebase was generated initially with the [OpenAPI python generator](https://openapi-generator.tech/docs/generators/python/). I've applied `pydantic-bump` to the v1 code, now working on revising some features of the local implementation.

In order to provide a centralized location for each class' `model_config`, I'd like to define a class structure like the following.

```python
from pydantic import ConfigDict, BaseModel, Field,  StrictInt, StrictStr
from pydantic.dataclasses import dataclass
from typing import Any, Dict, Tuple, Type
# imports abridged

class ApiModelClass(ModelMetaclass):

    @classmethod
    def default_model_config(cls):
        return ConfigDict(populate_by_name=True, validate_assignment=__debug__)

    def __new__(cls, name: str, bases: Tuple[Type[Any]], dct: Dict[str, Any],):
        overrides = dict()
        if "model_config" not in dct:
            overrides['model_config'] = cls.default_model_config()
        dct.update(overrides)
        return super().__new__(cls, name, bases, dct)
    

class ApiModel(BaseModel, metaclass = ApiModelClass):
    pass


@dataclass(frozen=True)
class AccountProperties(ApiModel):
    id: Optional[StrictStr] = Field(None, description="The Account's identifier")
    ## [sic]
```

This requires an import declaration, in Pydantic v2
```python
from pydantic._internal._model_construction import ModelMetaclass
```

## Feature Request

Would it be possible for this class `pydantic._internal._model_construction.ModelMetaclass` to be made available via a public namespace? 

## Rationale

Stylistically, I'm not heavily concerned about including a class from a _protected package name. In the interest of forward compatibility however, I thought it might be helpful to file a feature request for this feature. 

It seems that the class `ModelMetaclass` must be present in the method resolution order for any custom metaclass of a subclass of `BaseModel`. 

When implementing a custom model metaclass like above, I believe this would allow for, in effect:
- establishing a central location for `model_config` definition in the codebase
- ensuring the possibility of providing a custom `model_config` for any individual subclass of `ApiModel` - such that the subclass would use use a metaclass `ApiModelClass` - when simply defining the custom `model_config` variable in the class' source declaration

I believe that this approach would not negatively affect the `frozen` state of the implementing model dataclass.

I don't believe it would produce any side effects, if Pydantic `ModelMetaclass` was available in a _public package_ of Pydantic v2. 

In this feature request, I'm mainly concerned for ensuring forward compatibility for an application of this `_not._exactly.Public` class

### References

This is after reading up about metaclasses in Python, in [Class Metaprogramming from Luciano Ramalho's _Fluent Python_ (2nd ed.)](https://learning.oreilly.com/library/view/fluent-python-2nd/9781492056348/ch24.html)

### Limitations in Example

Considering the example in the previous,  after noticing a note in the [Pydantic @dataclasses documentation](https://docs.pydantic.dev/2.2/usage/dataclasses/),  I'm not sure if it's supported to use the Pydantic `@dataclasses` decorator on a class defined as an effective subclass of `BaseModel`.  These may represent two mutually exclusive approaches for a model class implementation?

The standard Python `@dataclasses` decorator may still be available, in this usage case.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Czaki** [comment]
Metaclass programming is not only to provide config. I do not even think about this use case. 

My example of usage is here https://github.com/4DNucleome/PartSeg/blob/293be196664baa4900a6cad642d0e52cf3d6aa28/package/PartSegCore/algorithm_describe_base.py#L375 
Where it introduces a shared register between each instance of a given class used later for UI generation.

**Comment by sydney-runkle** [comment]
Understood, but I think having this as private provides us the flexibility to significantly improve performance, etc on a minor release basis without breaking changes for many users. Feel free to use this private class, but just know it's subject to change.
