### ISSUE TITLE
Allow setting custom config values

### ISSUE THREAD

**Issue by berzi** [pydantic/pydantic#7455]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

With Pydantic 1's `Config` class I used to be able to set arbitrary fields as metadata for my models. With the new `model_config` TypedDict, this is no longer possible, since a TypedDict will not allow extra fields.

The only workaround I can currently think of is defining my own companion class inside my models, but that will not merge any such classes from superclasses, so it's quite inconvenient and a nightmare to maintain in a large codebase.

Making the type of `model_config` less specific and into a `dict[str, Any]` from `ConfigDict` would be a step back in terms of typing, but I can't think of a better alternative.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @berzi,

Thanks for your question - I have a few follow up questions. With some more info, I think we can come up with a good solution for you.
* Are you sharing the same additional config fields across all (or many) of your models?
* Would you be willing to provide a bit of example code? I think that might help give some more context regarding your specific use case.

**Comment by dmontagu** [comment]
One thing you can do is create a subclass of the `ConfigDict` typeddict and add the custom fields you want, then use that as the value of the config. I believe that is a way you can get extra fields without it being a type error, and I think it's how we handle this in `pydantic-settings`.

Let me know if that's not clear enough or doesn't work for your use case.

**Comment by berzi** [comment]
Ah, that is actually a good idea. For some reason I didn't think of it. 😅 What I ended up doing was simply defining classmethods for each of the (few) extra fields I needed on my base model class: I only ever need to read those values, not modify them.
