### ISSUE TITLE
hide_input_in_errors does not work in all cases

### ISSUE THREAD

**Issue by vitalik** [pydantic/pydantic#7461]
Configuration hide_input_in_errors is not respected in `error.json()` or `error.errors()`

if hides input only when printing error(repr)

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, ValidationError


class Data(BaseModel):
    model_config = ConfigDict(hide_input_in_errors=True)
    x: int


try:
    Data.model_validate({"y": "1"})
except ValidationError as e:
    print("errors:", e.errors())
    print("json  :", e.json())
    print("repr  :", e)
```

output:

```
errors: [{'type': 'missing', 'loc': ('x',), 'msg': 'Field required', 'input': {'y': '1'}, 'url': 'https://errors.pydantic.dev/2.3/v/missing'}]
json  : [{"type":"missing","loc":["x"],"msg":"Field required","input":{"y":"1"},"url":"https://errors.pydantic.dev/2.3/v/missing"}]
repr  : 1 validation error for DataPydantic
x
  Field required [type=missing]
    For further information visit https://errors.pydantic.dev/2.3/v/missing

```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /tmp/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  6 2022, 21:16:57)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.5.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @vitalik,

Thanks for your question!

The [documentation for this flag](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.hide_input_in_errors) explains that setting `hide_input_in_errors` to `True` hides inputs when **printing** errors. This behavior was intentional, as there's not an easy way to control the rendering of the exception, but you can manipulate the returned value of `e.json()` and `e.errors()` pretty easily.

We're inclined not to change the behavior of the `hide_input_in_errors` flag due to the breaking nature of such a change.

I think providing wrappers around the `.json()` and `.errors()` calls to filter out key/val pairs with the `input` key should work for your use case. We could also consider adding another field to the `ConfigDict` to remove the input information from the `.json()` and `.errors() results.

Let us know what you think!

**Comment by vitalik** [comment]
@sydney-runkle 

Well my thinking this is a bug.. especially in the area of secret-string and secret-bytes that pydantic provides

imagine you have some API and a secret string passed to it that you do not want to be logged:

```Python
from fastapi import FastAPI
from pydantic import BaseModel, SecretStr

api = FastAPI()


class Payload(BaseModel):
    secret: SecretStr  # <------ !!!!!!!!!!!!!!!!!


@api.post("/some")
def some(payload: Payload):
    return payload.model_dump()
```

now some user accidentally makes a typo in word "secret" -> "scret" - and the secret might  get logged in stdout:

```
$ http post "localhost:8000/some" scret=foo 
HTTP/1.1 422 Unprocessable Entity
content-length: 152
...

{
    "detail": [
        {
            "input": {
                "scret": "foo" # <------
            },
            "loc": [
                "body",
                "secret"
            ],
            "msg": "Field required",
            "type": "missing",
            "url": "https://errors.pydantic.dev/2.3/v/missing"
        }
    ]
}

```

while if all is correct - all accidental prints replaced with "*******"

```
$ http post "localhost:8000/some" secret=foo
HTTP/1.1 200 OK
content-length: 23
...

{
    "secret": "**********"
}
```

**Comment by sydney-runkle** [comment]
@vitalik - ah, I understand your line of thought here. I think an additional field to the `model_config` could be good here. I'll consult with the team on Monday.

Are you interested in contributing to the addition of this feature via a PR?

**Comment by samuelcolvin** [comment]
let's add this as an argument to `.errors()` and `.json()`first and see if that's sufficient.

**Comment by sydney-runkle** [comment]
> let's add this as an argument to `.errors()` and `.json()`first and see if that's sufficient.

Working on a PR now, hopefully will have up by EOD.

**Comment by sydney-runkle** [comment]
Hi @vitalik,

Just merged this PR in pydantic-core to add support for the `include_input` flag to `.errors()` and `.json()` calls on `ValidationError` instances. https://github.com/pydantic/pydantic-core/pull/973

This should become active with the next release.

**Comment by rafrafek** [comment]
`.errors()` has `include_input` set to `True` by default so `model_config = ConfigDict(hide_input_in_errors=True)` doesn't work it this case 🤔

**Comment by sydney-runkle** [comment]
@rafrafek,

Right, I think the idea is that the config setting is more general, but if you do want to hide input in the specific call to `errors()` you can control that at the lower level.

**Comment by rafrafek** [comment]
This issue starts with this line:

> Configuration hide_input_in_errors is not respected in error.json() or error.errors()

How is it different now? `hide_input_in_errors=True` is still not being respected because `.errors()` sets `include_input` to `True` anyway.

**Comment by vitalik** [comment]
@rafrafek yeah, not consistent to my taste as well :/

**Comment by sydney-runkle** [comment]
@rafrafek @vitalik,

I see what you're saying. PRs welcome to change the default of `include_input` in the calls to `.errors()` and `.json()` according to the config setting 👍

**Comment by sydney-runkle** [comment]
Thinking about this more, it might be difficult to access the config information from `.errors()` and `.json()`. I understand why the inconsistency is frustrating though, and am certainly open to a solution.
