### ISSUE TITLE
Mypy reports "Too many positional arguments" for RootModel subclass

### ISSUE THREAD

**Issue by Nnonexistent** [pydantic/pydantic#7463]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

1. Subclassing the `RootModel` to use list as a root
2. Instantiating this new model without keyword `root=`
   e.g. `ListRootModel(['qwe', 'asd'])` instead of `ListRootModel(root=['qwe', 'asd'])`
3. All is working fine in runtime
4. Mypy is reporting "Too many positional arguments for ListRootModel"

I understand, that that's a minor issue, but still it would be nice to have a bit cleaner code without compromising mypy analysis

### Example Code

```Python
from pydantic import RootModel

class ListRootModel(RootModel):
    root: list[str]

ListRootModel(['qwe', 'asd'])  # mypy: Too many positional arguments for "ListRootModel"  [misc]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/nik/.cache/pypoetry/virtualenvs/zia-api-python-PZ2SEBy0-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, May 15 2023, 09:03:45) [GCC 11.3.0]
                     platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi,

Thanks for your question. You should be able to use `ListRootModel.model_validate(['qwe', 'asd'])` without a `mypy` error.

See the docs on how we recommend using `RootModel` [here](https://docs.pydantic.dev/latest/usage/models/#rootmodel-and-custom-root-types).

Let us know if you have any other questions! 😄

**Comment by berzi** [comment]
@sydney-runkle An additional question about this. Let's say I have a root model based on a `dict` and I want to allow calling it with no arguments so that `root` gets a value of an empty `dict` by default, how would I do this? `model_validate` doesn't allow me to call it with no arguments and it's rather long compared to just `MyModel()`. Overriding `__init__` doesn't seem to change anything: mypy still tells me 'Missing named argument "root" for "MyModel"'.

**Comment by sydney-runkle** [comment]
Hi @berzi,

Thanks for following up - great question! The following works for me without any `mypy` issues, let me know if you're able to achieve the same.

```py
from typing import Dict

from pydantic import Field, RootModel


class MyModel(RootModel):
    root: Dict[str, str] = Field(default_factory=dict)


m = MyModel()  # no mypy problems
```

**Comment by sydney-runkle** [comment]
Another follow up about the original example - we can do the following with no type errors:

```py
from typing import List

from pydantic import RootModel


ListRootModel = RootModel[List[str]]
ListRootModel(['qwe', 'asd'])
```

**Comment by sydney-runkle** [comment]
@dmontagu, I know you've been working on some `mypy` fixes/changes, what are your thoughts on this? I'm going to reopen, as the inconsistency with the `mypy` errors (see the first example) is bugging me.
