### ISSUE TITLE
Specifying a model_validator(mode="after") on a BaseModel subclass breaks datetime.date serialization/validation in strict-mode

### ISSUE THREAD

**Issue by cryzed** [pydantic/pydantic#7468]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I attached example code with a minimal test-case of the issue I'm running into. I wanted to specify a `model_validator(mode="after")`-method to check if the instance's data is logically consistent after deserialization, but as soon as I tried to, I ran into a `ValidationError` for a field that previously parsed successfully (in strict-mode).

I expected my `Model.check()`-method to get the successfully parsed instance (just like before defining it), which I can then inspect and modify.

The only workarounds I have found are 1) setting `strict=False` for all the `datetime.date`-fields on my model or 2) specifiying a custom annotated type with a custom validator and using that instead of `datetime.date | None` directly, e.g.:

```python
def pydantic_validate_date(value: datetime.date | str | None) -> datetime.date | None:
    match value:
        case datetime.date():
            return value
        case str():
            return datetime.date.fromisoformat(value)
        case None:
            return None


PydanticDate = typing_extensions.Annotated[datetime.date | None, pydantic.BeforeValidator(_pydantic_validate_date)]
```

I hope I'm not doing something wrong!

### Example Code

```Python
import datetime

import pydantic


class Model(pydantic.BaseModel):
    date: datetime.date | None = pydantic.Field(default=None, strict=True)

    # If this method is commented out, the exception below isn't raised
    @pydantic.model_validator(mode="after")
    def check(self) -> "Model":
        return self


a = Model(date=datetime.date(2000, 1, 1))
a_json = a.model_dump_json()

Model.model_validate_json(a_json)
# Traceback (most recent call last):
#   File "/home/.../bug.py", line 16, in <module>
#     b = Model.model_validate_json(a_json)
#   File "/home/.../pydantic/main.py", line 531, in model_validate_json
#     return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
# pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
# date
#   Input should be a valid date [type=date_type, input_value='2000-01-01', input_type=str]
#     For further information visit https://errors.pydantic.dev/2.3/v/date_type
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/user/.cache/pypoetry/virtualenvs/my-project-V_ooIIwR-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 15 2023, 21:25:52) [GCC 13.1.1 20230429]
                     platform: Linux-6.5.3-arch1-1-x86_64-with-glibc2.38
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @cryzed,

Thanks for your question. One helpful reference you can use for questions like this is our [conversion table](https://docs.pydantic.dev/latest/usage/conversion_table/), which shows what type conversions are allowed (and under what conditions, like `strict=True` for example). This screenshot shows the part of the table that explains type conversion from `str` to `datetime` is not allowed when in strict mode (see row 5).

<img width="771" alt="Screenshot 2023-09-16 at 7 13 02 PM" src="https://github.com/pydantic/pydantic/assets/54324534/aed217fe-506c-4d98-a286-e990d2029700">

We can prove this is the case by attempting something like `b = Model(date="2000-01-01")`, for which we receive the same `ValidationError` that you mentioned above.

That being said, the case where you comment out the model validator + no longer experience the same `ValidationError` is interesting. Looking into this more now...

**Comment by samuelcolvin** [comment]
Thanks @cryzed, yes it's a bug and I can it's [here](https://github.com/pydantic/pydantic-core/blob/502fb9adfa96208236f0002b9e2d2cea8c7dd3d9/src/validators/function.rs#L103):

```rs
self._validate(validate, py, input.to_object(py).into_ref(py), state)
```

The point is that we covert the input to a python object before calling the validator, even for after validators. Since the input is then python, a string  input to a date field is not valid in strict mode, whereas it would be if the validator was receiving JSON.

Probably caused by https://github.com/pydantic/pydantic-core/pull/886

@cryzed if you fancy getting your hands dirty with some Rust, feel free to take a crack at fixing this?

Otherwise, @davidhewitt maybe you could take a look at this?

**Comment by cryzed** [comment]
I think @davidhewitt would be a better choice, I don't see myself jumping into a new programming language currently.

**Comment by davidhewitt** [comment]
Think https://github.com/pydantic/pydantic-core/pull/967 should fix it.
