### ISSUE TITLE
PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package.

### ISSUE THREAD

**Issue by amitsubhashchejara** [pydantic/pydantic#7472]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using the Chroma vector datastore and creating embeddings using OpenAI embedding. However, I am facing an error while imparting the Chroma database. 
<img width="776" alt="image" src="https://github.com/pydantic/pydantic/assets/125737375/bfb79260-43f7-4bad-8ace-4a21ad12f18b">

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\Amitk\AppData\Local\Programs\Python\Python311\Lib\site-packages\pydantic
               python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @amitsubhashchejara,

Thanks for your question. Looks like you've got a dependency conflict going on. If [this](https://github.com/chroma-core/chroma/tree/main) is indeed the package you're mentioning, its latest version requires Pydantic <2.0, whereas you have v2.30 installed. If you install Pydantic v1.10, this error should go away.
