### ISSUE TITLE
loc_by_alias is not reflecting alias names on integer validations

### ISSUE THREAD

**Issue by alkimake** [pydantic/pydantic#7481]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

if pydantic raises error types such as `less_than_equal` or `greater_than_equal`, `loc_by_alias` does not reflecting to the error definitions or `loc` value. 

Example code will print;

```
[{'ctx': {'le': 10},
  'input': 12,
  'loc': ('integer_value',),
  'msg': 'Input should be less than or equal to 10',
  'type': 'less_than_equal',
  'url': 'https://errors.pydantic.dev/2.3/v/less_than_equal'}]
```

here is the `loc` value should be `IntegerValue` instead of `integer_value`.

There might be many more error types that `loc_by_alias` might not work but I only tried for integer.

### Example Code

```Python
from pprint import pprint

import pydantic


class AliasClass(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        loc_by_alias=True,
        populate_by_name=True
    )
    integer_value: int = pydantic.Field(alias='IntegerValue', le=10, ge=1)

try:
    AliasClass(integer_value=12)
except pydantic.ValidationError as exc:
    pprint(exc.errors())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
               python version: 3.10.12 (main, Jun 26 2023, 20:42:23) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.2-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
`loc_by_alias` is perhaps a slight misnomer, although I don't know of a better name.

It means `loc` should always use the actual key provided in the data, rather than the field name.

I think therefore it's behaving as I would expect it to, although we should definitely improve the docs on this.

**Comment by alkimake** [comment]
Let's ignore the documentation for a moment, if there is no behavioral change why there is this option `loc_by_alias`? I am a bit confused actually.

if `loc` needs to be consistent with the key that is provided, having an option to populate the model with both alias and field name (`populate_by_name`) is enough. and `loc` will always return the given key. (it will ruin our man in the middle but that's my problem for sure). Therefor there is no need for `loc_by_alias` as far as I can see.

**Comment by hramezani** [comment]
> Let's ignore the documentation for a moment, if there is no behavioral change why there is this option loc_by_alias? I am a bit confused actually.

> `loc_by_alias` is for whether having `field_name` or `alias` in loc. 

This is the case when `loc_by_alias=True`. So, if `loc_by_alias=False`, and you pass `alias` when initializing a model, you will get `field_name` in error loc

**Comment by alkimake** [comment]
Perfect explanation thank you. So I would expect to get the `field_name` always when I use `loc_by_alias=False`, but I will get the same key that user gives when `loc_by_alias=True` is given. AFAIU

Therefor I would like to offer if its good to support all 3 cases by config.

`loc_by=alias`, `loc_by=field_name` and `loc_by=given` (or default). 

I have a good case I am working on right now. I am implementing an SDK that supports both alias and field name population because of various dynamic data sources. And I also want to give a feedback or manipulate error messages depends on `loc` key. This setting would really helpful.

Thanks for your time to explain in detail.

**Comment by vianmixtkz** [comment]
> Perfect explanation thank you. So I would expect to get the `field_name` always when I use `loc_by_alias=False`, but I will get the same key that user gives when `loc_by_alias=True` is given. AFAIU
> 
> Therefor I would like to offer if its good to support all 3 cases by config.
> 
> `loc_by=alias`, `loc_by=field_name` and `loc_by=given` (or default).
> 
> I have a good case I am working on right now. I am implementing an SDK that supports both alias and field name population because of various dynamic data sources. And I also want to give a feedback or manipulate error messages depends on `loc` key. This setting would really helpful.
> 
> Thanks for your time to explain in detail.

I agree. I would really use this feature right now.

Besides, when I read `loc_by_alias=True`, I would expect loc to only and always contain aliases whatever what was the provided key.

I think this issue should be reopen

**Comment by leavor** [comment]
> > Perfect explanation thank you. So I would expect to get the `field_name` always when I use `loc_by_alias=False`, but I will get the same key that user gives when `loc_by_alias=True` is given. AFAIU
> > Therefor I would like to offer if its good to support all 3 cases by config.
> > `loc_by=alias`, `loc_by=field_name` and `loc_by=given` (or default).
> > I have a good case I am working on right now. I am implementing an SDK that supports both alias and field name population because of various dynamic data sources. And I also want to give a feedback or manipulate error messages depends on `loc` key. This setting would really helpful.
> > Thanks for your time to explain in detail.
> 
> I agree. I would really use this feature right now.
> 
> Besides, when I read `loc_by_alias=True`, I would expect loc to only and always contain aliases whatever what was the provided key.
> 
> I think this issue should be reopen

Filling the 'loc' in error messages with alias is very useful, especially for users whose native language is not English. Using aliases to fill the 'loc' in exception messages will be very user-friendly
