### ISSUE TITLE
Recursion error when generating schema

### ISSUE THREAD

**Issue by astoff** [pydantic/pydantic#7490]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The definition below causes an infinite recursion involving `generate_schema`.

In this case I only care about validation logic, not the schema. Is it possible to disable it?

### Example Code

```Python
from typing import Union
from pydantic import BaseModel
A = Union[tuple[int, "A"], None]
class M(BaseModel):
    x: A
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/augusto/smartextract/gateway/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)]
                     platform: Linux-6.4.15-200.fc38.x86_64-x86_64-with-glibc2.37
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @astoff,

Are you looking for the following definition? This doesn't have any issues with recursion errors.

```py
from typing import Literal, Tuple, Union

from pydantic import BaseModel


A = Union[tuple[int, Literal["A"]], None]

class M(BaseModel):
    x: A
```
Let me know if this helps!

**Comment by astoff** [comment]
No no, I really meant a what I wrote :-). That is, a recursive definition of a linked list.

**Comment by sydney-runkle** [comment]
@astoff,

I see! I think the `TypeAliasType` usage as explained [in these docs](https://docs.pydantic.dev/latest/usage/types/custom/#named-type-aliases) should suit your needs.

Let me know if you have any other questions!

**Comment by sydney-runkle** [comment]
Here's an example:

```py
from typing import Union, Tuple
from typing_extensions import Annotated, TypeAliasType

from pydantic import BaseModel

A = TypeAliasType('A', Union[Tuple[int, "A"], None])


class M(BaseModel):
    x: A
```

**Comment by astoff** [comment]
Ah, great, thanks for the hint. This works.
