### ISSUE TITLE
Model config setting for SerializeAsAny

### ISSUE THREAD

**Issue by berzi** [pydantic/pydantic#7494]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I understand the reason serialisation was changed from v1 to not serialise as "duck types", and I find the solution of using `SerializeAsAny` ok, but I have a large project where I always need it wherever I have models as field types for other models.

Would it be possible to add a setting to `model_config` to imply `SerializeAsAny` automatically?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @berzi,

Thanks for your question. 2 potential solutions:
1. Create a subclass of `ConfigDict` where `SerializeAsAny` is always `True`, then use that as the config for all of your models.
2. Create a subclass of `BaseModel` with your desired config + use that as the parent class for all of your models for which you need these settings.

Let me know if neither of these work for you and we can figure out a better solution! 😄

**Comment by berzi** [comment]
> Hi @berzi,
> 
> Thanks for your question. 2 potential solutions:
> 
> 1. Create a subclass of `ConfigDict` where `SerializeAsAny` is always `True`, then use that as the config for all of your models.
> 2. Create a subclass of `BaseModel` with your desired config + use that as the parent class for all of your models for which you need these settings.
> 
> Let me know if neither of these work for you and we can figure out a better solution! 😄

[ConfigDict](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict) doesn't have `SerializeAsAny`, that's exactly what my proposal is. Right now it can only be applied to individual fields, so there's no way to have as default.

**Comment by sydney-runkle** [comment]
Ah, thanks for following up. I misunderstood your original question. We've had a few requests for this already, and we have an open issue re this discussion: #6423.

I'm going to close this in favor of continuing discussion on the mentioned issue 😃
