### ISSUE TITLE
Option to disable the "For further information ...."

### ISSUE THREAD

**Issue by lephuongbg** [pydantic/pydantic#7512]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We would like to have an option to disable the "For further information visit..." from the readable output of `ValidationError`.

The reason is we would like to reuse the readable output as error message for our API users, but without the "For further information visit https://docs.pydantic.dev/2.3/errors" part as it is not relevant to our API users.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @lephuongbg,

This seems like a good use case for using our [custom error](https://docs.pydantic.dev/latest/errors/errors/#customize-error-messages) functionality. Specifically, I think you could use a custom error handler to customize whatever error messages you'd like to provide.

Let me know if that answers your question! 😄
