### ISSUE TITLE
add SqliteDsn field type

### ISSUE THREAD

**Issue by lesinigo** [pydantic/pydantic#7515]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We already have support for [`PostgresDsn`, `MariaDBDsn` and other similar field types](https://docs.pydantic.dev/latest/usage/types/urls/), it would be useful to also have an `SqliteDsn` field type.

For example, an application using SQLAlchemy and supporting different database backends could validate the DSN like this:

```python
class Settings(BaseSettings):
    db_dsn: Union[PostgresDsn, MariaDBDsn, SqliteDsn]
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @lesinigo,

Sure thing! Would you be interested in contributing? Here's an example of a PR used to add some other [Dsn types](https://github.com/pydantic/pydantic/pull/4990), for reference.

**Comment by sydney-runkle** [comment]
Hi @lesinigo,

Given that SQLite databases can be written into a variety of file types, we think this is not a specific enough use case to justify adding a type. You can always use `FilePath` or `Annotated[Path, ...]` to perform validation on your SQLite files.

Closing for now - thanks for your request!

**Comment by Neko1313** [comment]
Guys, does it bother you that there are examples of DSNS for SQLite formats?:

1) sqlite://absolute/path/to/database.db
2) sqlite://./relative/path/to/database.db
3) sqlite:///:memory:
4) sqlite://

What to do with: memory: and temporary ?

**Comment by makukha** [comment]
Could we reopen this ticket? It's nice to support `sqlite://` prefix due to its wide use.
