### ISSUE TITLE
Support for numpy typing annotation  

### ISSUE THREAD

**Issue by SylvainGuieu** [pydantic/pydantic#7538]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Numpy  has a few typing annotation :

https://numpy.org/devdocs/reference/typing.html

Would be great if   ``ArrayLike`` and ``DTypeLike``  is supported natively by pydantic   

From the doc: 
```
numpy.typing.ArrayLike 

Among others this includes the likes of:

- Scalars.
- (Nested) sequences.
- Objects implementing the __array__ protocol.
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [X] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @SylvainGuieu,

Thanks for opening this feature request. We currently have an [open issue](https://github.com/pydantic/pydantic-extra-types/issues/31) on the `pydantic-extra-types` repository asking for these types. Contributions are welcome!

Closing in favor of discussion there.

**Comment by caniko** [comment]
Check out my package [`pydantic-numpy`](https://github.com/caniko/pydantic-numpy)
