### ISSUE TITLE
Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema

### ISSUE THREAD

**Issue by and-sm** [pydantic/pydantic#7539]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello. I'm facing the following error when using Fastapi 0.103.0 and Pydantic 2.3.0

```
File "/home/and/exp/.venv/lib/python3.11/site-packages/pydantic/json_schema.py", line 2041, in handle_invalid_for_json_schema

    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')

pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'general', 'function': <bound method BaseModel.validate of <class 'main.SampleRequest'>>})

For further information visit https://errors.pydantic.dev/2.3/u/invalid-for-json-schema
```

openapi.json can't be generated when I use **pydantic.v1**.

### Example Code

```Python
from fastapi import FastAPI
from pydantic.v1 import BaseModel

app = FastAPI()

class SampleRequest(BaseModel):
    id: int

@app.post("/")
async def root(request: SampleRequest):
    return {"status": "ok"}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0 python -c "import pydantic.version; print(pydantic.version.version_info())"
pydantic-core version: 2.6.3
pydantic-core build: profile=release pgo=true
install path: /home/and/exp/.venv/lib/python3.11/site-packages/pydantic
python version: 3.11.5 (main, Sep 18 2023, 10:59:23) [GCC 11.4.0]
platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
The error comes from https://github.com/tiangolo/fastapi/blob/master/fastapi/_compat.py which [assume you are using pydantic V2](https://github.com/tiangolo/fastapi/blob/46d1da08da73d8b4100e709edab9d84aa6b6a203/fastapi/_compat.py#L46). because you've installed Pydantic V2.

Probably you need to install V1

**Comment by sydney-runkle** [comment]
@and-sm, any luck using V1 instead of V2?

**Comment by and-sm** [comment]
> @and-sm, any luck using V1 instead of V2?

Unfortunately, it turned out that pydantic.v1 doesn't work with the latest versions of FastAPI

**Comment by sydney-runkle** [comment]
@and-sm,

Gotcha. Perhaps you could revert to an older version of FastAPI if you're dependent on Pydantic v1 and upgrade to the newer version when you're ready to migrate to v2?
