### ISSUE TITLE
Field with name uuid cannot be set as optional not required

### ISSUE THREAD

**Issue by vavroch2010** [pydantic/pydantic#7554]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If field name is "_uuid_" it cannot be used as Optional not required.
Python raises error during startup. 
> Traceback (most recent call last):
File "test.py", line 4, in <module>
     class Test(BaseModel):
  File "test.py", line 5, in Test
    uuid: uuid.UUID | None = None
          ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'UUID'

If name is set to "_aaa_" everything works as it should.

### Example Code

```Python
from pydantic import BaseModel, ValidationError
import uuid

class Test(BaseModel):
    uuid: uuid.UUID | None = None
    name: str

print(Test(name='test'))
```

### Python, Pydantic & OS Version

```Text
import pydantic.version; print(pydantic.version.version_info())
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /...../lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.2-x86_64-i386-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @vavroch2010,

2 potential solutions to this:
```py
from uuid import UUID, uuid4

from pydantic import BaseModel, ValidationError

class Test(BaseModel):
    uuid: UUID | None = None
    name: str

print(repr(Test(uuid=uuid4(), name='test')))
#> Test(uuid=UUID('33a865b2-8c8c-4cb4-bdff-7f95d6bade80'), name='test')

print(repr(Test(name='test')))
#> Test(uuid=None, name='test')
```

or:

```py
import uuid

from pydantic import BaseModel, ConfigDict, Field, ValidationError

class Test(BaseModel):
    uuid_: uuid.UUID | None = Field(default=None, alias="uuid")
    name: str

print(Test(uuid=uuid.uuid4(), name='test').model_dump(by_alias=True))
#> {'uuid': UUID('b39321db-5946-4386-9885-6d691a9b2a51'), 'name': 'test'}

print(Test(name='test').model_dump(by_alias=True))
#> {'uuid': None, 'name': 'test'}
```

Let me know if this helps!

**Comment by vavroch2010** [comment]
Hi, thanks for quick reply!!! 
I already solved that similar way like option 2. I am using it in fastapi framework as an input validation so I cannot really use option 1. 
Basically I think is kind of bug and should be solved either by documentation or code change. 
What do you think about that?

**Comment by Kludex** [comment]
This is not a bug. The problem is that the `uuid` when you are adding the type hint doesn't refer to the import statement, it refers to the model attribute.

It's a matter of namespace, and the fact that Pydantic uses type hints at runtime.

The suggestions that @sydney-runkle proposed are, in short, to avoid the naming conflict of `uuid`.
