### ISSUE TITLE
Bug, nested extra validator not working as expected

### ISSUE THREAD

**Issue by samsja** [pydantic/pydantic#7564]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

# Context

Hey all, first thanks for the great work on Pydantic v2.

I am trying to support the pattern with pydantic v2 where I have a "default" attribute.

```python
class MyModel(BaseModel):
     id: int
     text: str

data1 = TypeAdapter(User).validate_python(123) 
# would be equivalent to
data2 = TypeAdapter(User).validate_python({'id':123})
```

I actually don't like this pattern that much but since I introduced it already in [DocArray](https://github.com/docarray/docarray) I need to make it compatible with pydantic v2.

With Pydantic v1 it was quite easy I just needed to override the `validate()` function of `MyModel`: example [here](https://github.com/docarray/docarray/blob/0148e99c47ae9e1fc02c5bfc2ee717afa0633748/docarray/documents/text.py#L137)

Since if I understand correctly with pydantic v2 the validation is actually happening in rust world it is a bit different.

My current way of doing it is :

```python
class User(BaseModel):
    id: int

    @classmethod
    def __get_pydantic_core_schema__(cls, source, handler) -> core_schema.CoreSchema:
        schema = handler(source)
        return core_schema.general_wrap_validator_function(
            function=cls.custom_val, schema=schema
        )

    @classmethod
    def custom_val(cls, value, model_validator, _):
        if isinstance(value, int) or isinstance(value, str):
            value = {'id': value}
        print(f"hello: {value}")
        return model_validator(value)
```

And this is working fine **when I try to validate one model at a time**, but not when I tried to validate nested model.

the following is not working

```python
class MyModel(BaseModel):
    text1: User
    text2: User


data = MyModel(text1=123, text2=123)

>>>
Traceback (most recent call last):
  File "scratch.py", line 48, in <module>
    doc = MyModel(text1=123, text2=123)
  File "/home/sami/.cache/pypoetry/virtualenvs/docarray-OI1ry5x2-py3.8/lib/python3.8/site-packages/pydantic/main.py", line 166, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
text2
  Input should be a valid dictionary or instance of User [type=model_type, input_value=123, input_type=int]
    For further information visit https://errors.pydantic.dev/2.3/v/model_type
```

Funny enough this is not working as long as I have two field with the same class but if I have only one it is working

```python


class MyModel(BaseModel):
    text1: User
    hello: str

doc = MyModel(text1=User(id=123), hello="hello") # all fine
doc = MyModel(text1=123, hello="hello")
```

And this is working as well

```python
class MyModel(BaseModel):
    text1: User
    text2: User


doc = MyModel(text1=123, text2=(User(id=123)))
```

but as long as I have two times the direct value it is not working. Very weird.

It looks to me like a bug, maybe something related to the model validation graph or a caching mechanism. 

Thank you in advance for any suggestion.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path .cache/pypoetry/virtualenvs/docarray-OI1ry5x2-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.9 (default, Sep  7 2023, 11:27:28)  [GCC 10.5.0]
                     platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
Hey @samsja, Thanks for reporting this issue 🙏 

You probably can use [model_validator with mode='before'](https://docs.pydantic.dev/latest/concepts/validators/#model-validators)

```py
from pydantic import BaseModel, model_validator
from pydantic_core import

from typing import Any

class User(BaseModel):
    id: int
    
    @model_validator(mode='before')
    @classmethod
    def validate_model_before(cls, values: Any) -> dict[str, Any]:
        return {'id': values}

class MyModel(BaseModel):
    text1: User
    text2: User


data = MyModel(text1=123, text2=124)
print(data)
#> text1=User(id=123) text2=User(id=124)
```

**Comment by samsja** [comment]
let me take a look
