### ISSUE TITLE
Annotating a constr leads to validation being skipped 

### ISSUE THREAD

**Issue by andersfylling** [pydantic/pydantic#7572]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Discussed in https://github.com/pydantic/pydantic/discussions/7531

<div type='discussions-op-text'>

Hello! I noticed that wrapping a Annotated constr will disable the validation.

### Example Code

```Python
def test_validation() -> None:
    class Faulty(BaseModel):
        v: Annotated[str, constr(max_length=2)]

    large_str = "123"
    Faulty(v=large_str)  # OK

    class Working(BaseModel):
        v: constr(max_length=2)

    Working(v=large_str)  # ERROR
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/anders/.cache/pypoetry/virtualenvs/test-z00aGtA7-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  5 2023, 15:58:10) [GCC 13.1.1 20230429]
                     platform: Linux-6.4.10-arch1-1-x86_64-with-glibc2.38
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @andersfylling,

Thanks for your question + the example code. As explained in our [docs](https://docs.pydantic.dev/latest/usage/types/strict_types/#constrained-types), we recommend using `Annotated` with `str` and `StringConstraints` to achieve the same effect of using `constr` in a way that's more friendly to type checkers. In our upcoming release, we've updated the documentation for all of the `con...` types with a warning against using them. They'll be deprecated in Pydantic v3.

Here's an example (from said docs):
```py
from typing_extensions import Annotated

from pydantic import BaseModel, StringConstraints, ValidationError

FirstName = Annotated[
    str,
    StringConstraints(to_upper=True, pattern=r'[A-Z0-9]{3}-[A-Z0-9]{3}'),
]


class Model(BaseModel):
    license_plate: FirstName


try:
    Model(license_plate='XYZ')
except ValidationError as e:
    print(e)
    """
    1 validation error for Model
    license_plate
      String should match pattern '[A-Z0-9]{3}-[A-Z0-9]{3}' [type=string_pattern_mismatch, input_value='XYZ', input_type=str]
    """
m = Model(license_plate='ABC-123')
print(m)
#> license_plate='ABC-123'
```

**Comment by sydney-runkle** [comment]
Following up, the reason for this is that `constr` actually just returns an annotated `str` with the provided `StringConstraints` specifications. See that [here](https://github.com/pydantic/pydantic/blob/1546db3cae0179ac7ced4ec16dd723a61609c566/pydantic/types.py#L368).

**Comment by sydney-runkle** [comment]
Closing now, feel free to follow up if you have any other questions 😄
