### ISSUE TITLE
child class can't call function that uses model_dump in parent class

### ISSUE THREAD

**Issue by sam-hoffman** [pydantic/pydantic#7573]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

 I'm trying to create a parent class with a function that can be shared between all child classes
from pydantic import BaseModel

```

class Parent(BaseModel):
    def dump(self):
        return self.model_dump()


class Child(Parent):
    var1: str
    var2: int


if __name__ == "__main__":
    c = Child(var1="test", var2=1)
    print(c.dump())
```

This raises error 
```
    return self.model_dump()
AttributeError: 'Child' object has no attribute 'model_dump'
```

This works fine with dataclasses using `asdict(self)` instead of the `self.model_dump()` line

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.12
            pydantic compiled: True
                 install path: /Users/samhoffman/Library/Caches/pypoetry/virtualenvs/proton-dhsXds5v-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.2 (default, Aug 16 2023, 12:44:18)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.2.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/usage/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/usage/exporting_models/) - `.dict()` and `.json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/usage/schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/usage/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/usage/model_config/)
- [ ] [Field Types](https://docs.pydantic.dev/usage/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/usage/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/usage/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/usage/models/) - `construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @sam-hoffman,

Thanks for your question. `model_dump()` was introduced in V2. If you're still using V1, you'll have to use `dict()`.

See the migration guide ([specifically this section](https://docs.pydantic.dev/2.3/migration/#changes-to-pydanticbasemodel)) for changes to `BaseModel` associated with the V1 -> V2 migration.
