### ISSUE TITLE
Overloading attribute using computed_field causes unexpected behavior

### ISSUE THREAD

**Issue by raceychan** [pydantic/pydantic#7577]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

while trying to find a work around on  https://github.com/pydantic/pydantic/issues/7574
I find another potentially unexpected behavior of computed field, that:
within a same class, if an attribute is rewritten using computed field,  that attribute isn't needed for instantiation of the class.

### Example Code
The following code won't raise any error
```Python

from pydantic import BaseModel, computed_field

class Event(BaseModel):
    event_id:str
    
    @computed_field
    def event_id(self) -> str:
        return "random"

e = Event()
assert isinstance(e.event_id, property)
```
The following code would raise Attribute Error

```python
from dataclasses import dataclass

@dataclass
class T:
    name:str
    
    @property
    def name(self):
        return "name"
T()
AttributeError: property 'name' of 'T' object has no setter

```
```
### Python, Pydantic & OS Version

```Text
python version: sys.version_info(major=3, minor=10, micro=13, releaselevel='final', serial=0)
pydantic version: 2.3.0

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal


             pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/raceychan/miniconda3/envs/askgpt/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by caniko** [comment]
I like the idea of overriding `fields` with `computed_fields`, but would appreciate some sort of warning during runtime so that I know it is happening. After the warning, if I still want the behavior, there could a config attribute that for example lets me define a set of fields that can be overridden by `computed_field`

**Comment by raceychan** [comment]
Well from a abstract point of view, I think overriding an attribute/ field
with computed field follow the principle of dependency inversion, whether a
field is computed field is implementation detains, we should rather focus
on the abstract part: the shape of the model. As long as a computed field
returns the same type as
 its parent class’s field it should be fine to treat it the same way.

Also it might not work in dataclass due to limitation in it’s current
implementation, we see similar ideology in __slots__ attributes where
caller don’t need to worry about the implementation details of __slots__
attributes, but rather the shape of it.

**Comment by caniko** [comment]
> Well, from an abstract point of view, I think overriding an attribute/ field
with computed field follows the principle of dependency inversion, whether a
field is a computed field should be considered implementation detail, we should rather focus
on the abstract part

This framing goes against the current implementation of abstract classes in Python. There is no such thing as an abstract attribute in Python, but abstract methods. The current implementation of Pydantic is to stay idiomatic to Python, operating outside standards should be done with UX in mind, hence my earlier reasoning.

Don't get me wrong, I have also wanted some sort of smart exchange between abstract attributes and methods. We probably need a new PEP if we want to do it the right way.

**Comment by Aleksandr-Frolov** [comment]
I am facing a similar problem, I have an optional field for which I need to calculate a value if it is missing. Could you please advise me how to override the value for the optional field on  2.4.2 pydantic version:
```
class Foo(BaseModel):
    bar_1: int
    bar_2: int
    total_sum: int | None = Field(default=None)

    @computed_field
    @property
    def total_sum(self) -> int:
        return self.bar_1 + self.bar_2


test_1 = Foo(**{'bar_1': 1, 'bar_2': 2, 'total_sum': 5})
# ValueError: you can't override a field with a computed field


test_2 = Foo(**{'bar_1': 1, 'bar_2': 2})
# ValueError: you can't override a field with a computed field
```

**Comment by caniko** [comment]
You need to store the result in an attribute. I would make it a private attribute (note underscored attributes are not supported in V2 atm):
```python
class Foo(BaseModel):
    bar_1: int
    bar_2: int

    private_total_sum: int | None = None

    @computed_field
    @property
    def total_sum(self) -> int:
        if self.private_total_sum is None:
            self.private_total_sum = self.bar_1 + self.bar_2
        return self.private_total_sum 
```

**Comment by Aleksandr-Frolov** [comment]
> You need to store the result in an attribute. I would make it a private attribute (note underscored attributes are not supported in V2 atm):
> 
> ```python
> class Foo(BaseModel):
>     bar_1: int
>     bar_2: int
> 
>     private_total_sum: int | None = None
> 
>     @computed_field
>     @property
>     def total_sum(self) -> int:
>         if self.private_total_sum is None:
>             self.private_total_sum = self.bar_1 + self.bar_2
>         return self.private_total_sum 
> ```

Thank you very much) at the moment I'm using this method, but I didn't use overwriting the private element

**Comment by julian-irwin-tfs** [comment]
I'm exploring adoption of Pydantic for my team, we would be very interested in using computed fields to override model attributes. 

`from pydantic import BaseModel, computed_field

class Config(BaseModel):
    length: float = 0.0  # Legacy class is expecting inches, but new data source is in cm

    @computed_field
    def length(self) -> float:
        # Handle the unit conversion here
        return length / 2.54`

**Comment by nunamia** [comment]
<img width="561" alt="image" src="https://github.com/pydantic/pydantic/assets/137667281/66ce736c-87d0-4086-8521-47b30b822850">

**Comment by davidjb99** [comment]
It would be very useful to override base fields with computed fields...

**Comment by sydney-runkle** [comment]
I don't know if we'll get to this in the super short term, but I think what makes the most sense here is to:

a) try to be consistent with stdlib dataclasses
b) follow the behavioral guidelines we get from type checkers

**Comment by sydney-runkle** [comment]
Alrighty! Finally following up here.

So, we've decided to keep the behavior where `pydantic` raises an exception if you try to override a computed field. Here's an example of something that doesn't work, and notably, it's not endorsed by type checkers like Pyright (see an explanation from the maintainer [here](https://github.com/python/mypy/issues/4125#issuecomment-870112343)):

```py
from pydantic import BaseModel, computed_field


class Parent(BaseModel):
    some_field: str


class Child(Parent):
    @computed_field
    @property
    def some_field(self) -> str:
        return 'random'

    """
    Pyright: "some_field" overrides symbol of same name in class "Parent"
        "property" is not assignable to "str" PylancereportIncompatibleVariableOverride
    """


"""
TypeError: Field "some_field" of class "Child" overrides symbol of same name in "Parent".
This override with a computed_field is incompatible.
"""
```

(I'm opening a PR now to raise this new error instead of the old unhelpful `ValueError`, which I feel confident deeming as old and unhelpful given that I wrote it years ago, haha).

This behavior, though it fails in a slightly different manner, is also not supported by dataclasses:

```py
from dataclasses import dataclass

@dataclass
class Parent:
    some_field: str

@dataclass
class Child(Parent):    
    @property
    def some_field(self):
        return "random"
    
    """
    Pyright: "some_field" overrides symbol of same name in class "Parent"
        "property" is not assignable to "str"PylancereportIncompatibleVariableOverride
    """

child = Child("test")
"""
Traceback (most recent call last):
  File "/Users/sydney-runkle/Work/oss/pydantic/test1.py", line 18, in <module>
    child = Child("test")
  File "<string>", line 3, in __init__
AttributeError: property 'some_field' of 'Child' object has no setter
"""
```

I'd recommend the following pattern if you want to achieve something similar with the approval of standard Python practices:

```py
from abc import ABC, abstractmethod
from pydantic import BaseModel, computed_field


class Parent(ABC):
    @property
    @abstractmethod
    def some_field(self) -> str:
        raise NotImplementedError()


class Child(BaseModel, Parent):
    @computed_field
    @property
    def some_field(self) -> str:
        return 'random'


child = Child()
print(child.model_dump())
# > {'some_field': 'random'}
```

**Comment by pkit** [comment]
So in a nutshell: something that worked fine in V1 does not work anymore in V2 and you don't want to fix it?

**Comment by Viicos** [comment]
> So in a nutshell: something that worked fine in V1 does not work anymore in V2 and you don't want to fix it?

Something working in V1 doesn't mean it necessarily mean it should in V2. Caniko [explained](https://github.com/pydantic/pydantic/issues/7577#issuecomment-1741996176) clearly why this is an anti-pattern, and we don't want to implement non-standard features in Pydantic. This feature is something that comes up regularly (https://github.com/pydantic/pydantic/issues/11848, https://github.com/pydantic/pydantic/issues/8901 and more), but until this [gets standardized](https://discuss.python.org/t/67359) this will stay as is.
