### ISSUE TITLE
Fully typed field presence check

### ISSUE THREAD

**Issue by francipvb** [pydantic/pydantic#7578]
### Discussed in https://github.com/pydantic/pydantic/discussions/5579

<div type='discussions-op-text'>

<sup>Originally posted by **francipvb** April 25, 2023</sup>
Hello,

I have a problem where a pydantic model is used to update an entity. However, I want to check if a field has been provided in a type-checked way, I mean, with future refactoring and errors reporting support.

I thought about something like this:

```python
from pydantic import BaseModel, is_present

class Model(BaseModel):
    a: int|None=None
    b: float
    c: int|None

class B(BaseModel):
    x: int=5

a=A(b=45.5, c=None)
is_present(A.a, a) # -> False
is_present(A.c, a) # -> True
b=B(x=5)
c=B()
is_present(B.x, c) # -> False
is_present(A.a, c) # -> Error!

```

Is there a solution for this, I mean a type-safe way?
</div>

**Comment by francipvb** [comment]
I'm going to send a PR for this functionality.

I found it to be rater simple to do and I'm starting a feature branch.

**Comment by samuelcolvin** [comment]
Use`field_name in model.model_fields_set`.
