### ISSUE TITLE
Order of keys differs in schema output

### ISSUE THREAD

**Issue by vigneshmanick** [pydantic/pydantic#7580]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When a model is specified as a Field and the values are instantiated , the keys are output in sorted order. I would expect that the order of the keys be maintained.

See sample code below. The output of the class `Stepping` when executed standalone is 

```py 
print(Stepping(type="const", step=0.15, multi_step=True))
# type='const' step=0.15 multi_step=True
```

But when the class `Stepping` is used as a  field in another Model and the Field is instantiated then the output of the schema has the values sorted.  **_'default': {'multi_step': True, 'step': 0.15, 'type': 'const'}}},_**

```py
print(Movement.model_json_schema())

{'$defs': {'Stepping': {'properties': {'type': {'const': 'const',
     'title': 'Type'},
    'step': {'title': 'Step', 'type': 'number'},
    'multi_step': {'default': False,
     'title': 'Multi Step',
     'type': 'boolean'}},
   'required': ['type', 'step'],
   'title': 'Stepping',
   'type': 'object'}},
 'properties': {'type': {'const': 'movement',
   'default': 'movement',
   'title': 'Type'},
  'step_settings': {'allOf': [{'$ref': '#/$defs/Stepping'}],
   'default': {'multi_step': True, 'step': 0.15, 'type': 'const'}}},
 'title': 'Movement',
 'type': 'object'}
```

Is there a setting that would allow the retaining of the field order in the output? Or am i doing something wrong?

Thanks in advance.

### Example Code

```Python
from pydantic import BaseModel, Field
from typing import Literal

class Stepping(BaseModel):
    type: Literal["const"] = Field(
        ...,
    )
    step: float = Field(
        ...,
    )
    multi_step: bool = Field(
        default=False,
    )

print(Stepping(type="const", step=0.15, multi_step=True))

class Movement(BaseModel):
    type: Literal["movement"] = Field(
        default="movement"
    )
    step_settings: Stepping = Field(
        default=Stepping(type="const", step=0.15, multi_step=True)
    )

print(Movement.model_json_schema())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
pydantic-core version: 2.6.3
pydantic-core build: profile=release pgo=false
install path: /scratch/myprograms/miniconda3/envs/pydantic-v2/lib/python3.11/site-packages/pydantic
python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
                     platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.17
optional deps. installed: ['typing-extensions']
```

**Comment by vigneshmanick** [comment]
update , i checked the code and the source seems to be

https://github.com/pydantic/pydantic/blob/8f3ac4e30845957d79a12e8963fa37bfa0c9b811/pydantic/json_schema.py#L439

it would be nice to have a flag that also allows non sorted schema output. 

https://github.com/pydantic/pydantic/blob/8f3ac4e30845957d79a12e8963fa37bfa0c9b811/pydantic/json_schema.py#L389

### Some reasons:
- Order of fields in output is same as input
- with sorted output the git diff will be _indeterministic_ each time a new field is added or deleted. ( In addition to using pydantic we also generate documentation from the schema, the difference is apparent there)
- Also pydantic v1 the order was not sorted

**Comment by sydney-runkle** [comment]
Hi @vigneshmanick,

Thanks for looking into this! Seems like a reasonable feature request to me. Also related is #7424, enabling sorting for `model_dump` and friends.

Are you interested in opening a PR to help with this feature request? 😄

**Comment by vigneshmanick** [comment]
@sydney-runkle  sure, let me give it a try.

**Comment by adriangb** [comment]
Maybe I’m misunderstanding. The goal is to make json schemas determined to stick in the face of re-factoring. We should be sorting anything that does not have a natural order and keep the natural order on the things that do. Model fields have a natural order so they should never be sorted, if they are that’s a bug.

**Comment by adriangb** [comment]
Well that's a new test being added right? The goal of sorting is that schema generation is deterministic, e.g. when you migrate from v2 to v3 your tests don't break because the JSON schema output is different. Or if we refactor `pydantic/json_schema.py`. Without sorting we might accidentally change the order from e.g. `{"type": "string", "enum": ["one", "two", "three"]}` to `{"enum": ["one", "two", "three"], "type": "string"}` or `{"type": "string", "enum": ["three", "two", "one"]}`. Some of this is up for debate (e.g. should we sort enum values?) but I think the model fields have a natural order (the order they are defined in code) that we try to preserve elsewhere and should try to preserve in the json shcema.

**Comment by vigneshmanick** [comment]
yes, the order of model fields is sorted in the output which is the main issue i have with the schema output. 

e.g from the issue,  ` 'default': {'multi_step': True, 'step': 0.15, 'type': 'const'}}},` the fields are sorted.

**Comment by adriangb** [comment]
@sydney-runkle seems like a bug around https://github.com/pydantic/pydantic/blob/8f3ac4e30845957d79a12e8963fa37bfa0c9b811/pydantic/json_schema.py#L2227 then. Can you investigate and make a PR to fix?

**Comment by vigneshmanick** [comment]
Yes that works for me.

**Comment by LostInDarkMath** [comment]
In my case, https://github.com/pydantic/pydantic/pull/7817 does not fix my issue since I'm using `json_schema_extra`. Would it be possible to re-open https://github.com/pydantic/pydantic/pull/7767 which would fix my issue?

**Comment by adriangb** [comment]
I think we should just exclude `json_schema_extra` as well @sydney-runkle

**Comment by LostInDarkMath** [comment]
That would by great

/CC @Galaxy102

**Comment by sydney-runkle** [comment]
Sure thing. Can take a look at this after the Thanksgiving holiday 👍.

**Comment by LostInDarkMath** [comment]
Can you please re-open this to reduce the risk of forgetting this? ;)

**Comment by sydney-runkle** [comment]
@LostInDarkMath,

Could you provide an example of the schema that you're getting vs the schema that you're expecting when you're using `json_schema_extra`? Thanks!

**Comment by LostInDarkMath** [comment]
Here is a small example to reproduce the bug:

```python
from typing import Callable

from pydantic import BaseModel, Field, computed_field

MAP = {'2': 'hi', '1': 'hello', '3': 'world'}  # note the ordering


class FieldMetaData(BaseModel):
    values: Callable[[], list[str]] | None = Field(default=None, exclude=True)

    @computed_field
    def my_values(self) -> list[str]:
        return self.values() if self.values else None


class Bar(BaseModel):
    v: str = Field(default='42', json_schema_extra={'extra': FieldMetaData(values=lambda: MAP)})


if __name__ == '__main__':
    bar = Bar()
    json_schema = bar.model_json_schema()

    actual = json_schema['properties']['v']['extra']['my_values']
    assert actual == MAP
    assert actual.items() == MAP.items()

    for k, v in actual.items():
        print(k, v)   # prints in ordering 1, 2, 3

    assert str(actual.items()) == str(MAP.items())  # because order is wrong

```

**Comment by sydney-runkle** [comment]
So in some sense this is a different issue, which is sourced from the following call:
https://github.com/pydantic/pydantic/blob/667cd3776ee40e06018d0b7ff477c6cd0199b098/pydantic/_internal/_generate_schema.py#L2031

Which appears to sort the data, which isn't what we want.

**Comment by mwildehahn** [comment]
I confirmed sorting happens here: https://github.com/pydantic/pydantic/blob/667cd3776ee40e06018d0b7ff477c6cd0199b098/pydantic/json_schema.py#L442 `to_jsonable_python` doesn't sort the json_schema_extra.

_sort_json_schema currently avoids sorting some keys based on looking at the parent key, but that doesn't mean anything for schema extras. we could pass extras to that function and then inspect it or it seems easiest jsut to give people an option to opt out of sorting.

**Comment by sydney-runkle** [comment]
@mwildehahn,

Nice find - any interest in contributing a fix?

**Comment by sydney-runkle** [comment]
I've opened a PR to address this problem :) which we'll include in v2.10!

**Comment by spolloni** [comment]
> I've opened a PR to address this problem :)

thank you @sydney-runkle !!
