### ISSUE TITLE
Minor error in the documentation about field defaults

### ISSUE THREAD

**Issue by exhuma** [pydantic/pydantic#7582]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The description about field defaults contains a discrepancy between the type-hint and the default-factory in use.

The Python class attribute is typed as `int` but the factory uses a function that returns a `str`:

![image](https://github.com/pydantic/pydantic/assets/65717/ab216bf2-9b29-44f7-ac88-34a9a06110e3)

One of those two should be changed.

### Python, Pydantic & OS Version

```Text
The version of my local system is irrelevant. I noticed this in the docs of pydantic v2.3.0
```

**Comment by samuelcolvin** [comment]
Thanks, I've just checked and this is fixed by #7417 which I've just merged, should become the default docs tomorrow.
