### ISSUE TITLE
API to partially validate data (Alternative to `validate_model` in pydantic v1)

### ISSUE THREAD

**Issue by nayaverdier** [pydantic/pydantic#7586]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

In Pydantic v1, I was using `validate_model` to get the validated/coerced data for a subset of all fields defined.

The use case for this is for AWS DynamoDB indexes that use `KEYS_ONLY` or `INCLUDE` projections where a subset of attributes are copied into the index. In that specific scenario, I want to coerce/validate the fields provided, but ignore validation for all missing fields. At the same time, I don't want to define the other fields as Optional since in most cases (and especially when saving data) the validation should be checking all fields are present.

Relevant comment from a closed ticket: https://github.com/pydantic/pydantic/issues/1864#issuecomment-1654522179

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
In `Pydantic V2`, you can probably use [model_validate helper function](https://docs.pydantic.dev/2.3/usage/models/#helper-functions)

**Comment by nayaverdier** [comment]
@hramezani It looks to me like that function does the exact same validation as `__init__`, except takes in a dict/object instead of kwargs. Am I missing some way to make that return partially validated data without raising an exception?

**Comment by hramezani** [comment]
> @hramezani It looks to me like that function does the exact same validation as `__init__`, except takes in a dict/object instead of kwargs. Am I missing some way to make that return partially validated data without raising an exception?

@nayaverdier you are right. but you can wrap it in `try ... except` and then you probably need to loop over errors to ignore the errors that you don't want to raise

**Comment by nayaverdier** [comment]
@hramezani That was my first thought as well, but I don't think the partially validated/coerced data is included in the error right? I Even if all the errors are due to attributes missing, I would have to pass in valid values for them in order to get any actual data back from the validation (and then ignore the fields in the original error)

 The pydantic docs also say `loc` is subject to breaking changes in minor releases, but I'd need to parse that field in order to know which fields to handle differently.

**Comment by samuelcolvin** [comment]
I'm not sure this is the optimal way, but here's one solution:

```py
from pydantic import BaseModel, field_validator, ValidationError


class MyModel(BaseModel):
    a: int
    b: float
    c: str

    @field_validator('a', 'b', 'c', mode='wrap')
    def hacky_hacky_hack(cls, data, handler, info):
        # handler will raise ValidationError if the data is invalid
        v = handler(data)
        info.context[info.field_name] = v
        return v


context_one = {}
m = MyModel.model_validate({'a': '1', 'b': '2', 'c': '3'}, context=context_one)
print(context_one)


context_two = {}
try:
    MyModel.model_validate({'a': '1', 'b': 'wrong', 'c': '3'}, context=context_two)
except ValidationError as e:
    print(context_two)
```

Let me know if that works for you.

During validation we actually have a dict of valid data even when errors occur, we just ignore not it and return errors if there are any, so we could provide a config switch to return valid data even when there are errors, but I imagine it wouldn't be type safe.

**Comment by samuelcolvin** [comment]
Here's another option that's very un-typesafe, but more concise - choose your poison 😄 .

```
from pydantic_core import PydanticOmit

from pydantic import BaseModel, field_validator, ValidationError


class MyModel(BaseModel):
    a: int
    b: float
    c: str

    @field_validator('*', mode='wrap')
    def hacky_hacky_hack(cls, data, handler, info):
        # handler will raise ValidationError if the data is invalid
        try:
            return handler(data)
        except ValidationError:
            raise PydanticOmit()


m = MyModel.model_validate({'a': '1', 'b': '2', 'c': '3'})
print(m)
#> a=1 b=2.0 c='3'

m = MyModel.model_validate({'a': '1', 'b': 'wrong', 'c': '3'})
print(m)
#> a=1 c='3'
```

I also forgot the use of `'*'` as a field name to imply all fields in the first example.
