### ISSUE TITLE
you can generate json schema with non-unique keys

### ISSUE THREAD

**Issue by Pymann** [pydantic/pydantic#7593]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

following code does not throw an exception, although else alias is used two times.

jsonschema does not accept generated schema.

### Example Code

```Python
class Eval(BaseModel):
    stage: Literal["eval"]
    evals: Optional[Dict[str, List["Stage"]]] = Field(validation_alias=AliasChoices("else"))
    elist: Optional[List["Eval"]] = Field(validation_alias=AliasChoices("list"))
    eelse: Optional[List["Stage"]] = Field(validation_alias=AliasChoices("else"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Data\Projects\pyenv\Lib\site-packages\pydantic
               python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @Pymann,

Thanks for reporting this. The only issue that I see with the generated json schema is that there are duplicates in the `required` list of fields.

What specifically are you expecting to happen here - do you want an error to be raised, or the json schema to be different in some way?

Happy to help once we get some more info 😄.

**Comment by sydney-runkle** [comment]
@Pymann,

Thanks again for reporting. Any update on what you'd expect to happen here?

**Comment by sydney-runkle** [comment]
@Pymann closing for now due to inactivity. Happy to reopen if you have a suggestion / request for alternate behavior.
