### ISSUE TITLE
Add error location to "ValueError: Expected sequence to have exactly 1 generic parameter"

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#7595]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When I accidentally  write a model definition that is wrong, pydantic complains but it does not mention the model where the error occurs. It could be hard to find the place if there are lots of models in a project.

```py
from pydantic import BaseModel

class M(BaseModel):
        vals: list[float, float, float]

```

Take this example. The error I see is this:

```
ic_annotations
    raise ValueError('Expected sequence to have exactly 1 generic parameter')
ValueError: Expected sequence to have exactly 1 generic parameter
```

I would like the error to contain the model name, the dotted path to the model and the field which is incorrectly annotated.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @chbndrhnns,

Thanks for the suggestion! Would you be willing to create a PR to implement this feature request?

**Comment by sydney-runkle** [comment]
@adriangb, what are your thoughts on this?

**Comment by adriangb** [comment]
Can't you inspect the stack frame to see what model triggered the error? The stack will go all the way up to where the model was defined. For example, with your code:

```
Traceback (most recent call last):
  File "<some path>/test4.py", line 3, in <module>
    class M(BaseModel):
  File "<some path>/pydantic/_internal/_model_construction.py", line 184, in __new__
    complete_model_class(
  File "<some path>/pydantic/_internal/_model_construction.py", line 481, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/main.py", line 576, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 706, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 525, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 525, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 870, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 923, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 1564, in _apply_annotations
    res = self._get_prepare_pydantic_annotations_for_known_type(source_type, tuple(annotations))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_generate_schema.py", line 1545, in _get_prepare_pydantic_annotations_for_known_type
    res = gen(obj, annotations, self._config_wrapper.config_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<some path>/pydantic/_internal/_std_types_schema.py", line 405, in sequence_like_prepare_pydantic_annotations
    raise ValueError('Expected sequence to have exactly 1 generic parameter')
ValueError: Expected sequence to have exactly 1 generic parameter
```

In particular:

```
  File "<some path>/test4.py", line 3, in <module>
    class M(BaseModel):
```

**Comment by chbndrhnns** [comment]
@adriangb You are right, the model name appears in the stacktrace. It's a bit hidden but now that I know where to look for it, it's ok to me.
