### ISSUE TITLE
Add Base64Json type

### ISSUE THREAD

**Issue by bschoenmaeckers** [pydantic/pydantic#7598]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Extend the Base64Str/Base64UrlStr types with a Base64Json type that works the same as the existing Json type but encodes the value as base64 encoded string.

The following model would generate the json schema below:

```python
    class Model(BaseModel):
        a: Base64Json[List[int]]
```
```json
{
  "type": "object",
  "properties": {
    "a": {
      "type": "string",
      "contentMediaType": "application/json",
      "contentEncoding": "base64",
      "contentSchema": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    }
  }
}
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by bschoenmaeckers** [comment]
I am willing to make a PR for this feature if it would be accepted.

**Comment by sydney-runkle** [comment]
Hi @bschoenmaeckers,

Thanks for filing this issue 😄!

I think it might make more sense to instead create a `Base64Json` type that's annotated with a custom serializer. You can find an example [here in the docs](https://docs.pydantic.dev/latest/concepts/serialization/#custom-serializers). Specifically, I think annotating with a `PlainSerializer` would work well. Would this fit your use case?

If we were to go go about adding this new type to Pydantic, I think that's how we'd do it.

**Comment by sydney-runkle** [comment]
Hi @bschoenmaeckers,

Any luck using `Annotated` and `PlainSerializer` for your use case?

**Comment by sydney-runkle** [comment]
@bschoenmaeckers

I'm going to go ahead and close this for now, but we're certainly happy to reopen if there's more support / demand.

At this point I think something like this probably belongs in user code, but we could also consider adding it to `pydantic-extra-types`.
