### ISSUE TITLE
Pylint complains about E1123 unexpected-keyword-arg when using field aliases with Pydantic dataclasses

### ISSUE THREAD

**Issue by bjmc** [pydantic/pydantic#7604]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm not entirely sure if this is a Pylint bug or a Pydantic one, but it's unexpected behavior that I suspect could be resolved on the Pydantic end, so I'm reporting it here first.

I'm using the [dataclasses feature](https://docs.pydantic.dev/latest/usage/dataclasses/) in Pydantic v2.3.0 and I have a dataclass with an aliased field, like so:

```python
from pydantic import Field
from pydantic.dataclasses import dataclass

@dataclass
class Example:
    number: int = Field(alias='n')


example = Example(n=5)
```

This is valid code and runs just fine, but pylint complains with the following

`E1123: Unexpected keyword argument 'n' in constructor call (unexpected-keyword-arg)`

For reference:
```
$ pylint --version
pylint 2.17.5
astroid 2.15.6
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```

If anyone can point me in the right direction, I'm happy to try putting together a PR to resolve this.

### Example Code

```Python
from pydantic import Field
from pydantic.dataclasses import dataclass

@dataclass
class Example:
    number: int = Field(alias='n')


example = Example(n=5)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/bjmc/.cache/pypoetry/virtualenvs/ska-tmc-cdm-Rgii95BG-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

**Comment by samuelcolvin** [comment]
I don't think this is a bug in pydantic, it's fundamental incompatibility between pydantic and pylint.

If you know of a fix, PR welcome, or please explain how it can be fixed.

It would obviously be great if pylint fix this, but I see that it's probably well outside their desire to fix.

Basically I think you need to mute the warning on lines like this unless you know of a better fix.

BTW, there have been other similar reports of compatibility problems with pylint in the past, might worth checking them.

**Comment by bjmc** [comment]
@samuelcolvin you're obviously in a better position than I am to evaluate this, but I'm surprised to hear it's a fundamental incompatibility because pylint somehow correctly handles the same scenario with native Pydantic models:

```python
from pydantic import Field, Model


class Example2(Model):
    number: int = Field(alias='n')


example = Example2(n=5)
```
The above code does _not_ trigger a `E1123: unexpected-keyword-arg` warning from pylint.

**Comment by bjmc** [comment]
For reference, possibly related https://github.com/pylint-dev/astroid/pull/1178

Maybe this is better resolved on the Pylint end...
