### ISSUE TITLE
`copy_on_model_validation` not mentioned in v2 migration guide

### ISSUE THREAD

**Issue by antazoey** [pydantic/pydantic#7608]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am migrating to pydantic v2 and it has been going pretty good so much! There are a few things here and there I am unsure of but otherwise I am quite satisfied.

**One small issue though**: there is no mention of the config removal of `copy_on_model_validation` in the guide.
The other config changes for me seemed to be in there, such as `underscore_attrs_are_private` and stuff, but I am having to track down what to do with `copy_on_model_validation`, as it warns me the item was removed. So far, I haven't quite accomplished my quest either.

### Example Code

```Python
echo I tried these:
w3m https://docs.pydantic.dev/2.3/migration/ -dump
w3m https://docs.pydantic.dev/2.3/usage/model_config/ -dump
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08)  [Clang 6.0 (clang-600.0.57)]
                     platform: Darwin-22.6.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @antazoey,

Thanks for your report of this! You're correct, we didn't include information about `copy_on_model_validation` being removed in V2. I'll update this later today 😄.

**Comment by antazoey** [comment]
@sydney-runkle OK thanks, but how do I handle it now that it is gone? It was preventing a pickling issue from happening, but now the pickling issue has returned.

Is there a migration strategy for `copy_on_model_validation=False`?

**Comment by antazoey** [comment]
maybe via `self.default_factory`?  but it may be worth including a migration tip for this config some how

**Comment by Dartt0n** [comment]
> maybe via `self.default_factory`? but it may be worth including a migration tip for this config some how

I encountered the same issue today (I wish to copy by reference explicitly). Could you please provide more details on how this can be implemented using `default_factory`?

**Comment by sydney-runkle** [comment]
Hey folks! You could use a custom validator for said type and manually copy it before validation (use a validator with mode `"before"`.

**Comment by pirate** [comment]
@sydney-runkle can you help provide an example of your suggested workaround? I just tried creating a `@field_validator('abc', mode=before)` on the field I want left as-is and it didn't work, the field default value was still deep-copied when the model was next validated.

**Comment by sydney-runkle** [comment]
Sure thing!

```py
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any

# case 1: you're revalidating instances, you can fix this by setting revalidate_instance = 'never' (the default)
class Inner(BaseModel):
    model_config = ConfigDict(revalidate_instances='always')

    field: int

class Model(BaseModel):
    inner: Inner

inner = Inner(field=42)
model = Model(inner=inner)

print(inner is model.inner)
#> False

# case 2: you're using a type that pydantic copies during validation, eg a list
class Model(BaseModel):
    inner: list[int]

inner = [1, 2, 3]
model = Model(inner=inner)

print(model.inner is inner)
#> False

class Model(BaseModel):
    inner: Inner

inner = Inner(field=42)
model = Model(inner=inner)

# you can fix case 2 with a custom validator:
class Model(BaseModel):
    inner: list[int]

    @field_validator('inner', mode='plain')
    def no_copy_inner(v: Any) -> list[int]:
        # {some custom validation, don't copy the list}
        return v

inner = [1, 2, 3]
model = Model(inner=inner)

print(model.inner is inner)
#> True

```

**Comment by pirate** [comment]
Thanks for the helpful example. I actually settled on a different approach in the end, this one is working well for me:

```python
class InnerModel(BaseModel):
    # ...
    pass

class OuterModel(BaseModel):
    # I dont think this specific config is needed but here's the one I'm using in case it's relevant:
    model_config = ConfigDict(revalidate_instances="always", extra='forbid', arbitrary_types_allowed=True, populate_by_name=True, from_attributes=True, validate_defaults=False, validate_assignment=False)

    inner_list: List[InstanceOf[InnerModel]] = Field(default=[])
    
 
    @model_validator(mode='after')
    def validate(self) -> Self:
        # preserve references to original default objects
        # (pydantic usually deepcopies mutable defaults, which breaks any references)
        # see https://github.com/pydantic/pydantic/issues/7608
        self.inner_list = self.model_fields['inner_list'].default

        return self
```
