### ISSUE TITLE
Pydantic computed field documentation dissapeared in 2.4 update

### ISSUE THREAD

**Issue by robertofd1995** [pydantic/pydantic#7610]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Working: https://docs.pydantic.dev/2.3/usage/computed_fields/ 
Not working: https://docs.pydantic.dev/2.4/usage/computed_fields/

I did not saw any reason in the changelog that could imply the removal of this feature

### Python, Pydantic & OS Version

```Text
pydantic version: 2.0.3
        pydantic-core version: 2.3.0 release build profile
                 install path: /Users/XXX/.pyenv/versions/3.9.16/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, May 17 2023, 18:30:21)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.3-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @robertofd1995 for reporting this 🙏 

It has to be redirected to https://docs.pydantic.dev/2.4/api/fields/#pydantic.fields.computed_field
