### ISSUE TITLE
deviated model with optional entries only

### ISSUE THREAD

**Issue by Pymann** [pydantic/pydantic#7612]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When following model is user for type deviation, the schema wont work.

### Example Code

```Python
class Logged(BaseModel):
    project: Optional[str]
    variant: Optional[str]
    logtag: Optional[str]
    target: Optional[str]
    logfolder: Optional[str]
    ex_raise: Optional[str]
    final_raise: Optional[str]
    logging: Optional[str]
    show: Optional[str]
    cd: Optional[str]
    sdir: Optional[str] = Field(alias="dir")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: C:\Data\Projects\pyenv\Lib\site-packages\pydantic
               python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @Pymann,

What do you mean by "the schema won't work?" If you could provide a bit more details regarding what you're expecting vs what's being produced, we can help out.

Also, [see this section of the docs](https://docs.pydantic.dev/2.3/migration/#required-optional-and-nullable-fields) regarding `Optional` usage.

**Comment by cepedus** [comment]
Out of pure guessing are you trying to use the field name and "it breaks"? You need to add `populate_by_name=True` on the model's config ([docs](https://docs.pydantic.dev/2.3/usage/model_config/#populate-by-name)).

**Comment by sydney-runkle** [comment]
Hey @Pymann,

Were you able to resolve this issue? Anything we can help with?

**Comment by sydney-runkle** [comment]
Closing as we haven't gotten enough info to help.
