### ISSUE TITLE
Pydantic V2.4.0 Known Bugs -- WIP

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#7617]
Known bugs in Pydantic v2.4.0 that we need to fix:

- [x] #7613 
- [x] #7611 
- [x] #7618
- [x] Fix version offset on docs page
- [x] Fix Conversion Table on Concepts page (see #7614)
- [x] #7630
- [x] #7638

**Comment by samuelcolvin** [comment]
Let's do a patch release once these are fixed unless anything else is added.

**Comment by hramezani** [comment]
I closed this issue, as all the bugs got fixed.
