### ISSUE TITLE
Convenience method for pretty "loc" output

### ISSUE THREAD

**Issue by troyswanson** [pydantic/pydantic#7621]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The `loc` property in the `ErrorDetails` describes where a validation error was found, but since it is a Python tuple, it's difficult to effectively represent it as a string when returning to a client.

I've written an exceedingly simple function that attempts to satisfy the spec defined here:
https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto#L173-L209

The goal is to convert this `("items", 1, "baz")` to this `items[1].baz`

```python
from pydantic import BaseModel, ValidationError


def loc_to_dotsep(loc: tuple) -> str:
    path = ""
    for i, x in enumerate(loc):
        if isinstance(x, str):
            if i > 0:
                path += "."
            path += x
        else:
            path += f"[{x}]"
    return path


def test_loc_to_dotsep():
    class TestNestedModel(BaseModel):
        key: str
        value: str

    class TestModel(BaseModel):
        items: list[TestNestedModel]

    data = {"items": [{"key": "foo", "value": "bar"}, {"key": "baz"}]}

    try:
        TestModel.model_validate(data)
    except ValidationError as e:
        loc = e.errors()[0]["loc"]
        assert loc_to_dotsep(loc) == "items[1].value"
```

Might be handy for others. Note that my overly simplistic solution may not cover all use cases.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by troyswanson** [comment]
Hi @sydney-runkle -- Thanks for the response 😄

I can try, but I won't have time for the next few weeks.

The main issue for me to write this up is that I don't understand the validation system well enough to ensure that the guidance won't introduce pitfalls from some edge case. If others from the community can confirm that the function I provided will always work, I'd be more comfortable writing something up.

**Comment by troyswanson** [comment]
Looking at the type hints for the `loc` property, it appears that it is meant to be constrained to just `str` and `int` types, which would make the function that I wrote exhaustive. That said, I refactored it a bit to throw a TypeError if something else is provided.

```python
def loc_to_dotsep(loc: tuple[str, int]) -> str:
    path = ""
    for i, x in enumerate(loc):
        match x:
            case str():
                if i > 0:
                    path += "."
                path += x
            case int():
                path += f"[{x}]"
            case _:
                raise TypeError("Unexpected type")
    return path
```

**Comment by sydney-runkle** [comment]
Hi @troyswanson,

Thanks for digging into this a bit more. I'd be more than happy to add this to our docs - it's a super helpful example 😄.

Stay tuned for a PR. I'll assign you as a reviewer.
