### ISSUE TITLE
model_dump malfunctions when serializing Sub-models 

### ISSUE THREAD

**Issue by raceychan** [pydantic/pydantic#7622]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

According to the offical api doc of model_dump:

https://docs.pydantic.dev/latest/concepts/serialization/#modelmodel_dump
> model.model_dump(...)
> This is the primary way of converting a model to a dictionary. Sub-models will be recursively converted to dictionaries.

#### **When a sub-model being serialized via model.model_dump, it would be serialized as its parent model, thus, all attributes other than the ones defined in its parent class would be ignored after serialization, leading to information/data lost**

This issue would be better described by code, see the simple example below

### Example Code

```Python
import typing
from pydantic import BaseModel

class Person(BaseModel):
    name: str
    friend: typing.Optional["Person"] = None


class RichPerson(Person):
    money: int


def test_issue():
    from rich import print

    p = Person(name="John", friend=RichPerson(name="Jane", money=20))

    assert isinstance(p.friend, RichPerson)
    assert not p.model_dump()["friend"].get("money")

    print(p)
    print(p.model_dump())


test_issue()
```
output from terminal
```bash
person object:
Person(name='John', friend=RichPerson(name='Jane', friend=None, money=20))
person object dumped: 
{'name': 'John', 'friend': {'name': 'Jane', 'friend': None}}
```

**Here when constructing Person object, RichPerson object is successfully stored as an attribute.
however, when model_dump, RichPerson object is parsed as its parent class, Person, which does not contain the money attribute**
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/raceychan/miniconda3/envs/askgpt/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by raceychan** [comment]
here is the same code running using pydantic.v1

```python
def test_issue():
    from rich import print

    p = Person(name="John", friend=RichPerson(name="Jane", money=20))

    assert isinstance(p.friend, RichPerson)
    assert not p.model_dump()["friend"]['money'] == 20

    print("person object:", p)
    print("person object dumped: ", p.dict())

```
```bash
person object:
Person(name='John', friend=RichPerson(name='Jane', friend=None, money=20))
person object dumped: 
{'name': 'John', 'friend': {'name': 'Jane', 'friend': None, 'money': 20}}
```

**Comment by adriangb** [comment]
This is by design, in particular, to avoid leaking secrets in API response models. You can use `pydantic.SerializeAsAny` to get the previous behavior.
