### ISSUE TITLE
Setattribute with Extra.allow is hiding method when it's defined on class.

### ISSUE THREAD

**Issue by vendito-david** [pydantic/pydantic#7631]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When setting an attribute, it is saving it with \_\_setattr\_\_ into \_\_pydantic\_extra\_\_ (https://github.com/pydantic/pydantic/blob/b403666455bae4fdc62404236c45c1b9939f96fa/pydantic/main.py#L802). 
On the other hand, when getting an attribute, it is running the \_\_getattr**ibute**\_\_ implementation, which is basically looking for the object dict, then the class hierarchy then the \_\_getattr\_\_ implementation afterwards only. 
If Extra.allow is set, the setattr is saving it to a place which is not accessed in the same order by default. See the example code. It prints the "1,1,patched" instead of "1,patched,patched".

### Example Code

```Python
from pydantic import BaseModel, Extra

class LookupPython():
    id: int

    def __init__(self, id) -> None:
        self.id = id

    def func(self):
        return self.id

class LookupPydantic(BaseModel, extra=Extra.allow):
    id: int

    def func(self):
        return self.id
    
lookups = [ LookupPython(id=1), LookupPydantic(id=1) ]

for lookup in lookups:
    print( type(lookup) )
    print( repr(lookup) )
    print( lookup.func() )
    lookup.func = lambda: "patched"
    print( repr(lookup) )
    print( lookup.func() )
    lookup.__dict__["func"] = lambda: "patched"
    print( repr(lookup) )
    print( lookup.func() )
    print( "" )
```
Output:
```
<class '__main__.LookupPython'>
<__main__.LookupPython object at 0x7ff7c92ba5d0>
1
<__main__.LookupPython object at 0x7ff7c92ba5d0>
patched
<__main__.LookupPython object at 0x7ff7c92ba5d0>
patched

<class '__main__.LookupPydantic'>
LookupPydantic(id=1)
1
LookupPydantic(id=1, func=<function <lambda> at 0x7ff7c8e54cc0>)
1
LookupPydantic(id=1, func=<function <lambda> at 0x7ff7c8e54cc0>)
patched
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/kali/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.8 (main, Oct 24 2022, 10:07:16) [GCC 12.2.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0 fastapi-0.85.0 typing_extensions-4.3.0 email-validator-1.1.2
```

**Comment by mullerdavid** [comment]
Hi, this is david-vendito on my non-corporate user. I made an issue instead of PR because i am not that familiar with the new pydantic v2 and your conventions yet.

**Comment by sydney-runkle** [comment]
Hi @vendito-david (@mullerdavid ),

No worries at all. I'll work on a fix for this + update here with progress 😄.
