### ISSUE TITLE
Dumped model will not be serialized if has AnyHttpUrl

### ISSUE THREAD

**Issue by atompie** [pydantic/pydantic#7632]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When attempting to save or transmit a model (with AnyHttpUrl type), we encounter an error indicating that the URL cannot be serialized. This essentially obstructs the use of any URL when there is a downstream function that requires a simple dictionary for serialization.

model.model_dump() will not produce a serializable object: 

This is how dump looks like.  

```json
{'url': Url('http://www.google.com/')}
```

And simple json serialization fails. Some downstream libraries have also other types of serializations that can not handle it.  

```
print(json.dumps(dump))

# TypeError: Object of type Url is not JSON serializable
```

### Example Code

```Python
import json

from pydantic import BaseModel, AnyHttpUrl


class EventRedirect(BaseModel):
    url: AnyHttpUrl


a = EventRedirect(url="http://www.com.com")
dump = a.model_dump()

# dump = {'url': Url('http://www.com.com/')}

print(json.dumps(dump))

# TypeError: Object of type Url is not JSON serializable
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/risto/PycharmProjects/tracardi/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.4.0-163-generic-x86_64-with-glibc2.31
             related packages: email-validator-2.0.0.post2 pydantic-settings-2.0.3 typing_extensions-4.6.3 pydantic-extra-types-2.1.0 fastapi-0.103.1
```

**Comment by sydney-runkle** [comment]
Hi @atompie,

You can use do this instead, note the `mode=json` flag. Also, see more docs on the `model_dump` method [here](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_dump).
```py
dump = a.model_dump(mode='json')
#> {'url': 'http://www.com.com/'}
```

or:
```py
a.model_dump_json()
#> '{"url":"http://www.com.com/"}'
```

**Comment by atompie** [comment]
@sydney-runkle Well it does indeed works for json but not for other sterilizers. I am sending data to elastic search and it can save it due to unserializable URL.

**Comment by sydney-runkle** [comment]
Hi @atompie,

Thanks for following up. Does the case of `a.model_dump(mode='json')` not work for your use case?

This still returns a dict...

**Comment by atompie** [comment]
Sorry I misinterpreted the result of your code. W checked it and it indeed returns dict not json as mode indicates.

**Comment by sydney-runkle** [comment]
Awesome! No worries. Glad that works 😄
