### ISSUE TITLE
Problem with union type serialization when custom model serializer is used.

### ISSUE THREAD

**Issue by pevny** [pydantic/pydantic#7642]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

During migration of legacy codebase to Pydantic V2 we've hit an issue with the serialization of union types that consist of combination of `Item` type and list of said `Item` when custom serializer is defined using `@model_serializer` decorator. 

It seems that once `model_dump` is called, Pydantic tries to directly apply the serializer defined in `Item` to the list, instead of recursively applying it to individual items. The instantiation of the model works as expected (we are getting list of `Item` at that point) - the problem only occurs once we try to serialize the model.

When we change the order of types in the union (list first), the serialization starts to behave as expected.

Error output of attached reproducer:

```
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: PydanticSerializationError: Error calling function `dump`: AttributeError: 'list' object has no attribute 'id'
```

### Example Code

```Python
from typing import Any
from pydantic import BaseModel, model_serializer


class Item(BaseModel):
    id: int

    @model_serializer
    def dump(self) -> dict[str, Any]:
        return {"id": self.id}

class ItemContainer(BaseModel):
    item_or_items: Item | list[Item]


def test_dump_json() -> None:
    items = [Item(id=i) for i in range(5)]
    ItemContainer(item_or_items=items).model_dump_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/work/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 27 2023, 21:38:47) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @pevny,

Thanks for reporting this. I think this is the same issue reported in #6830 + identified as a confirmed bug. I'm removing the `unconfirmed` label to make sure this is addressed.

**Comment by sydney-runkle** [comment]
Closing this as a duplicate, but we'll be sure to include a test case like this one in our test suite once we resolve the bug mentioned in this issue and #6830.

**Comment by sydney-runkle** [comment]
Looking closer at this, I think it's slightly different than the issue linked above, so I'm going to reopen until we fix 👍
