### ISSUE TITLE
Inconsistencies in model_json_schema with custom fields

### ISSUE THREAD

**Issue by Phoetaim** [pydantic/pydantic#7686]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

## Situation
As a user, I have a pydantic model with multiple fields which use, or not custom JSON fields. The type of theses fields is a custom type with custom JSON fields. I want to use `.model_json_schema()` to export my instantiated model

## Expected Result
Each attribute has it's own in custom fields and the custom fields of the type. If there is a conflict, the custom fields of the attribute takes precedence.

## Actual Result
 - If the attribute has no custom fields: the custom fields of the custom class will be used
 - If the attribute overwrite the custom fields of the custom class: only the custom fields of the attribute will be used
 - If the attribute use a new custom field: only the custom fields of the attribute will be used

### Additional information
 - I tried to use `json_schema_extra` in `Field` and to define it as `Field(custom_field='foo',  ...)`
 - 'Normal' arguments in fields foes not seem to affect the result (I tried with `alias`)

### Example Code

```Python
from typing import Annotated

from pydantic import (
    BaseModel,
    Field,
)

StrWithFields = Annotated[
    str,
    Field(json_schema_extra={
        'custom_field': True,
        'other_field': 'other_field'
    }),
]


class Model(BaseModel):
    my_field: StrWithFields = Field('foo')
    my_field_with_overwrite: StrWithFields = Field('bar',
                                                   custom_field=False)
    my_field_with_other_field: StrWithFields = Field(
        'bar',
        new_field='my_field'
    )


print(Model().model_json_schema())
# Gives
# {
#     'properties': {
#         'my_field': {
#             'custom_field': True,
#             'default': 'foo',
#             'other_field': 'other_field',
#             'title': 'My Field',
#             'type': 'string'
#         },
#         'my_field_with_overwrite': {
#             'custom_field': False,
#             'default': 'bar',
#             'title': 'My Field With Overwrite',
#             'type': 'string'
#         },
#         'my_field_with_other_field': {
#             'default': 'bar',
#             'new_field': 'my_field',
#             'title': 'My Field With Other Field',
#             'type': 'string'
#         }
#     },
#     'title': 'Model',
#     'type': 'object'
# }
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0

pydantic-core version: 2.6.3

pydantic-core build: profile=release pgo=false

python version: 3.11.3 (main, Jun  9 2023, 09:44:01) [Clang 14.0.0 (clang-1400.0.29.202)]

platform: macOS-12.6.6-x86_64-i386-64bit
```

**Comment by sydney-runkle** [comment]
Hi @Phoetaim,

Thanks for reporting this. Just for clarity's sake, could you include an example of what you'd expect the result of `model_json_schema()` to be compared to what is currently produced?

Thanks for the detailed explanation thus far.

**Comment by Phoetaim** [comment]
Hi @sydney-runkle I would expect this json:
```
{
    'properties': {
        'my_field': {
            'custom_field': True,
            'default': 'foo',
            'other_field': 'other_field',
            'title': 'My Field',
            'type': 'string'
        },
        'my_field_with_overwrite': {
            'custom_field': False,
            'default': 'bar',
            'other_field': 'other_field',
            'title': 'My Field With Overwrite',
            'type': 'string'
        },
        'my_field_with_other_field': {
            'custom_field': True,
            'default': 'bar',
            'new_field': 'my_field',
            'other_field': 'other_field',
            'title': 'My Field With Other Field',
            'type': 'string'
        }
    },
    'title': 'Model',
    'type': 'object'
}
```

Thanks for the quick response

**Comment by sydney-runkle** [comment]
Hi @Phoetaim,

Thanks for the example + comments. I have some time later today to check this out in detail and will get back to you 😄.

**Comment by sydney-runkle** [comment]
Hi @Phoetaim,

After looking into this a bit further, I'm a bit concerned about the breaking nature of this change. Theoretically, there could be some users counting on the fact that specifying `json_schema_extra` later on in a field completely overrides that specified in earlier defined fields. I don't think it makes sense to introduce an additional flag to allow your requested behavior, but rather we should just have one policy for the behavior of how multiple `json_schema_extra` specifications behave.

Notably, there's not a super clear way to enforce an inclusion / overriding pattern with `json_schema_extra` specifications that are `Callable` types. Whereas with `dict` type specifications we can easily merge, there's not such an obvious solution with `Callable` types.

I think it might make sense to implement this change if there's a larger volume of community support, but I think for now it might make sense to stick with the current behavior. I think that you can still achieve the result that you want, you'll just have to specify a few extra fields at the final `Field` level.

Let me know what you think about all of this - I'm excited to get your feedback.

**Comment by Phoetaim** [comment]
Hi @sydney-runkle,

Oh indeed, I didn't think far enough, it seemed the natural way to do it but it might not be for everyone. I didn't know about `Callable` type `json_schema_extra`, I'll look into it later.

I hope it will receive enough support then :).

Have a good day!

**Comment by sydney-runkle** [comment]
Hi @Phoetaim,

No worries - I didn't consider all of the permutations at first either. Sounds great. Excited to hear more about what you think.

We can leave this issue open in the meantime to see what kind of support / demand there is for it 😄.

Hope you have a good day as well.
