### ISSUE TITLE
validate_call on instance method cause memory leak

### ISSUE THREAD

**Issue by xbanke** [pydantic/pydantic#7687]
### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

A class with instance method decorated by `validate_call`, the instance created by this class can not been deleted once this method been called.

### Example Code

```Python
import objgraph
from pydantic import validate_call, BaseModel


class Foo(BaseModel):
    foo: int = 3

    @validate_call
    def get_foo(self, a: int) -> int:
        return self.foo * a
        
    def __del__(self) -> None:
        print('deleted.')


##########################################

foo = Foo()
del foo  # deleted.


##########################################

foo = Foo()
a = foo.get_foo(3)
del foo  # nothing out
objgraph.by_type('Foo')  # [Foo(foo=3)]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/xxxx/.conda/envs/py311/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
                     platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @xbanke,

Thanks for reporting this. I believe this is related to #7466.

We have an open PR trying to address this issue, but it's still in draft state. The issue is that when we wrap a function with the `validate_call` wrapper, we mutate the `__dict__` of said instance. We're looking for workarounds.

Let me know if you think this is a different issue!

**Comment by xbanke** [comment]
Thanks for your quick reply.
If apply the decorator after the class been created, can partially solve the problem:
```py
from typing import Callable, TypeVar
from dataclasses import dataclass
from pydantic import validate_call
from pydantic._internal._validate_call import ValidateCallWrapper


_C = TypeVar('_C', bound=type)


@dataclass()
class Foo:
    m: int = 2

    def get_foo(self, a: int) -> int:
        return self.m * a

    def __del__(self) -> None:
        print('deleted.')


Foo.get_foo = validate_call(Foo.get_foo)
foo = Foo()
foo.get_foo('3')  # 6
del foo  # deleted.
```
But, there still some other problems:
```py
from typing import Callable, TypeVar
from dataclasses import dataclass
from pydantic import validate_call
from pydantic._internal._validate_call import ValidateCallWrapper


_C = TypeVar('_C', bound=type)


def validate_methods(*fnames: str) -> Callable[[_C], _C]:
    def wrapper(cls: _C) -> _C:
        for name in fnames:
            f = getattr(cls, name, None)
            if callable(f) and not isinstance(f, ValidateCallWrapper):
                # print(f'{name} validated.')
                f = validate_call(f)
                setattr(cls, name, f)
        return cls
    return wrapper


@validate_methods('get_foo')
@dataclass()
class FooA:
    m: int = 2

    def get_foo(self, a: int) -> int:
        return self.m * a

    def __del__(self) -> None:
        print('deleted.')


@validate_methods('get_foo')
@dataclass()
class FooB(FooA):  # TypeError: attribute name must be string, not 'NoneType'
    ...
```
It looks like the descriptor lost the owner.

```py
@dataclass()
class FooA:
    m: int = 2

    @validate_call
    def get_foo(self, a: int) -> int:
        return self.m * a

    def __del__(self) -> None:
        print('deleted.')


@dataclass()
class FooB(FooA):
    ...


FooB.get_foo # TypeError: attribute name must be string, not 'NoneType'
```
This will raise `TypeError`:
```
File ~/.conda/envs/py311/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py:120, in ValidateCallWrapper.__get__(self, obj, objtype)
    118         object.__setattr__(obj, self._name, result)
    119     else:
--> 120         object.__setattr__(objtype, self._name, result)
    121 return result

TypeError: can't apply this __setattr__ to type object

```

**Comment by dmontagu** [comment]
@xbanke in your example, the reason it looks like there is a memory leak is just that garbage collection hasn't been called before the end of the process. If you manually trigger the garbage collection after calling `del` but before the `objgraph` call, you'll see that it does in fact get cleaned up:

```python
import objgraph
from pydantic import validate_call, BaseModel


class Foo(BaseModel):
    foo: int = 3

    @validate_call
    def get_foo(self, a: int) -> int:
        return self.foo * a

    def __del__(self) -> None:
        print('deleted.')


##########################################

foo = Foo()
del foo  # deleted.

##########################################

foo = Foo()
a = foo.get_foo(3)
del foo  # nothing out

import gc
gc.collect(0)
gc.collect(1)
gc.collect(2)

print(objgraph.by_type('Foo'))  # []
```
Does that make sense?

**Comment by xbanke** [comment]
> @xbanke in your example, the reason it looks like there is a memory leak is just that garbage collection hasn't been called before the end of the process. If you manually trigger the garbage collection after calling `del` but before the `objgraph` call, you'll see that it does in fact get cleaned up:
> 
> ```python
> import objgraph
> from pydantic import validate_call, BaseModel
> 
> 
> class Foo(BaseModel):
>     foo: int = 3
> 
>     @validate_call
>     def get_foo(self, a: int) -> int:
>         return self.foo * a
> 
>     def __del__(self) -> None:
>         print('deleted.')
> 
> 
> ##########################################
> 
> foo = Foo()
> del foo  # deleted.
> 
> ##########################################
> 
> foo = Foo()
> a = foo.get_foo(3)
> del foo  # nothing out
> 
> import gc
> gc.collect(0)
> gc.collect(1)
> gc.collect(2)
> 
> print(objgraph.by_type('Foo'))  # []
> ```
> 
> Does that make sense?

It does make sense in `2.5.2`
