### ISSUE TITLE
create_model does not inherit the description in the new schema

### ISSUE THREAD

**Issue by JoanFM** [pydantic/pydantic#7692]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The schema of a dynamically created Model does not inherit the description from the parent as it used to do in Pydantic v1.

### Example Code

```Python
from pydantic import BaseModel, create_model

class MyModel(BaseModel):
    """This is my description"""
    text: str

new_model = create_model(MyModel.__name__, __base__=MyModel)

print(f'{MyModel.schema()}')
print(f'{new_model.schema()}')
```

In V2:

```
{'description': 'This is my description', 'properties': {'text': {'title': 'Text', 'type': 'string'}}, 'required': ['text'], 'title': 'MyModel', 'type': 'object'}
{'properties': {'text': {'title': 'Text', 'type': 'string'}}, 'required': ['text'], 'title': 'MyModel', 'type': 'object'}
```

In V1:

```
{'title': 'MyModel', 'description': 'This is my description', 'type': 'object', 'properties': {'text': {'title': 'Text', 'type': 'string'}}, 'required': ['text']}
{'title': 'MyModel', 'description': 'This is my description', 'type': 'object', 'properties': {'text': {'title': 'Text', 'type': 'string'}}, 'required': ['text']}
```

### Python, Pydantic & OS Version

```Text
2.4.0
```

**Comment by sydney-runkle** [comment]
Hi @JoanFM,

Thanks for reporting this. This is different from V1, so I wouldn't mind adding a note to the migration guide or the `create_model` section of the docs.

That being said, I think that the new behavior is better, as subclassing shouldn't entail equivalent parent and child class descriptions.  Subclasses don't inherit descriptions from their parent classes when subclassing normally, hence the lack of this behavior in the dynamic case.

Are you interested in opening a PR to reflect this?

**Comment by JoanFM** [comment]
How can I add the description when the model is created from the parent model then?

**Comment by JoanFM** [comment]
Where should I open this PR? in the docs? If you point me where I can do this yes

**Comment by sydney-runkle** [comment]
@JoanFM,

Thanks! Yep you can add an update in the `docs` folder, either in the `migration.md` file or in the `concepts/models.md` under the `dynamic model creation` section. I think the latter would make more sense.

Does this method of adding a description work for your use case?

```py
from pydantic import BaseModel, create_model


class MyModel(BaseModel):
    """This is my description"""

    text: str


NewModel = create_model("NewModel", __base__=MyModel, __doc__=MyModel.__doc__)

print(NewModel.model_json_schema())
"""
{'description': 'This is my description',
 'properties': {'text': {'title': 'Text', 'type': 'string'}},
 'required': ['text'],
 'title': 'NewModel',
 'type': 'object'}
"""
```

**Comment by JoanFM** [comment]
> ```python
> __doc__=MyModel.__doc__
> ```

It works for this specific case, but what if the description is added with the Config as in v1 was possible? or is not possible anymore?

**Comment by JoanFM** [comment]
But I also need to be able to set it from a description I get from a schema.

Let me tell the use case, I have a service reading the schema of another service and creating dynamically the class based on that schema. And I would like to mantain as much infromation possible from the old schema

**Comment by sydney-runkle** [comment]
@JoanFM,

Thanks for providing the use case. Could you provide an example schema from this other service that you're creating the class based on?

**Comment by JoanFM** [comment]
This is an example:

```
{'description': 'Here I have the description of the class', 'properties': {'id': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'description': 'The ID of the BaseDoc. This is useful for indexing in vector stores. If not set by user, it will automatically be assigned a random value', 'example': 'e76b71464f2c5dc0c2b4d175e8f8223d', 'title': 'Id'}, 'a': {'another_extra': 'I am another extra', 'examples': ['Example here'], 'title': 'A', 'type': 'string'}}, 'required': ['a'], 'title': 'CustomDoc', 'type': 'object'}
```

**Comment by JoanFM** [comment]
Well, actually @sydney-runkle ,

The main question is if there is another way to pass the `description` to the Model created (beyond from `__doc__`). I can handle when it comes from `__doc__`, but how would it happen if it is in the description?

**Comment by sydney-runkle** [comment]
@JoanFM, maybe I'm oversimplifying, but could you just use the param:
`__doc__=incoming_schema['description']` in your call to `create_model`?

**Comment by JoanFM** [comment]
Okey, I have checked the code ,and it seems that the only source of `description` is actually the `__doc__` and `docstring`, therefore I think the soloution you provided is enough.

Thank you for the support again @sydney-runkle !

**Comment by psychedelicious** [comment]
@sydney-runkle 
I'm getting a runtime warning when using `__doc__` in `create_model()`:
```py
from pydantic import create_model

Model1 = create_model('Model1', __doc__="My docstring")
-->
RuntimeWarning: fields may not start with an underscore, ignoring "__doc__"
  warnings.warn(f'fields may not start with an underscore, ignoring "{f_name}"', RuntimeWarning)
```

The docstring is set correctly, despite the warning that the field will be ignored. All bark, no bite!

I can set `__doc__` on the created model with no complaints, which I suppose makes sense as this is a not a pydantic-managed attribute by this time:
```py
Model2 = create_model('Model2')
Model2.__doc__ = "My docstring"
```

I suppose the field name validation logic might need a change for stuff like `__doc__`?

**Comment by sydney-runkle** [comment]
Hi @psychedelicious,

Thanks for reporting this! Could you create a new `feature-request` issue asking that we add support for the `__doc__` arg to create model? I think docstring specification is certainly something that we should support more explicitly 😄.

**Comment by psychedelicious** [comment]
Sure thing, here tis #7841
