### ISSUE TITLE
Bug with exclude_unset=True?

### ISSUE THREAD

**Issue by jesumyip** [pydantic/pydantic#7700]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using Pydantic v2.4.2.

```
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional

class MyClass(BaseModel):
    model_config = ConfigDict(extra='allow')
    field1: Optional[str] = Field(default = None, alias="field1_alias")

data = {"field1" : "somevalue"}
my_instance = MyClass(**data)
print(my_instance.model_dump(exclude_unset=True, by_alias=True))

```

It doesn't seem correct that this produces the following output?

`{'field1_alias': None, 'field1': 'somevalue'}`

Why is the alias included? I would expect the output to be:

`{"field1" : "somevalue"}` 

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/<redacted>/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: fastapi-0.100.0 typing_extensions-4.7.1
```

**Comment by foarsitter** [comment]
Experiencing also an issue with `exclude_unset=True` in combination with Literals/Constants. Do you think it is related? 
```
from typing import Literal

from pydantic import BaseModel


class Store(BaseModel):
    id: int
    name: Literal["Shop"] = "Shop"


def test_exclude_unset():
    my_store = Store(id=99)

    assert my_store.model_dump(exclude_unset=True) == {'id': 99, 'name': 'Shop'}
```

**Comment by sydney-runkle** [comment]
Hi @jesumyip & @foarsitter,

Thanks for reporting this. I can confirm that this is unexpected behavior + will work on a fix. Stay tuned 😄.

**Comment by sydney-runkle** [comment]
@foarsitter,

When I run your snippet of code, I get the expected result, which is the following:

```py
from typing import Literal

from pydantic import BaseModel


class Store(BaseModel):
    id: int
    name: Literal["Shop"] = "Shop"


my_store = Store(id=100)
print(my_store.model_dump(exclude_unset=True))
#> {'id': 100}
```

**Comment by sydney-runkle** [comment]
Hi @jesumyip,

Following up on your question. I've modified the example a bit to show some more output that helps to explain this behavior:

```py
from pydantic import BaseModel, Field, ConfigDict
from typing import Optional


class MyClass(BaseModel):
    model_config = ConfigDict(extra='allow')
    field1: Optional[str] = Field(default=None, alias="field1_alias")
    field2: Optional[str] = Field(default=None, alias="field2_alias")


# setting field1 as an extra field, thus field1 itself is unset
# setting field2 via the field2 alias
data = {"field1": "some value", "field2_alias": "some other value"}
my_instance = MyClass(**data)

print(my_instance.model_dump(exclude_unset=True, by_alias=True))
#> {'field1_alias': None, 'field2_alias': 'some other value', 'field1': 'some value'}

print(my_instance.model_fields_set)
#> {'field1', 'field2'}

print(my_instance.model_extra)
#> {'field1': 'some value'}
```

What's happening here is that both `field1` and `field2` are added to the `model_fields_set` property on the instance. This is the property that is used to decide which fields to include vs exclude when `exclude_unset=True` is used with `model_dump`.

I'll discuss this issue with the team and see how we want to move forward with a solution. A cleaner solution, obviously, would be to not name your extra field the same thing as one of your fields, but I understand your concern here in general.

**Comment by foarsitter** [comment]
@sydney-runkle thanks for looking into it! 

In my opinion a non optional literal could never be unset so I would expect `{'id': 100, 'name': 'Shop'}` as outcome.

**Comment by sydney-runkle** [comment]
@foarsitter,

Sure thing. We consider any value that wasn't set during model construction (validation) to be unset, and `name` falls under this criteria in your example. You could consider using `exclude_none` or `exclude_defaults` if you're looking for a different kind of behavior.

**Comment by sydney-runkle** [comment]
Hi @jesumyip,

After thinking about this more, I think this is more a case of "if you try hard enough, you can break anything". Any issues that you're having regarding your example can be fixed by not adding an extra field that has the same name as an existing field.

Let me know if you have any follow up questions! Thanks for your question. 😄

Also, just wanted to make sure that you're aware of the [`populate_by_name`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name) config variable that can be used with constructing models with fields that have aliases.
