### ISSUE TITLE
Pydantic memory leak when reusing same Model with wrap validator

### ISSUE THREAD

**Issue by pedro-iatzky** [pydantic/pydantic#7707]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It seems that when I reuse the same model (in my case named `APIResponseField`) for validating two nested lists that have the same schema inside of a json value and also I apply a wrap `field_validator`, the memory usage can be quite high, if the lists have many fields.
But, if I just split the model into two different ones (in my case `APIResponseFieldDimension` and `APIResponseFieldMeasure`) the processing is much more efficient, taking less time to complete and using much less memory.

I would expect the code to work equally efficiently in both cases.

### Example Code

```Python
from typing import List, Optional

from pydantic import BaseModel, FieldValidationInfo, field_validator


class MyBaseModel(BaseModel):
    @field_validator("*", mode="wrap")
    @classmethod
    def return_none_if_none(cls, value, handler, info: FieldValidationInfo):
        """
        If value is None, and the field is not required, return None,
        no matter the type specified.
        This is a functionality removed in Pydantic v2
        """
        field = cls.model_fields[info.field_name]
        if value is None and field.is_required() is False:
            # finish the validation
            return None
        # else, execute the other validators
        return handler(value)


class APIResponseField(MyBaseModel):
    name: str = None
    type: str = None

class APIResponse(MyBaseModel):
    dimensions: List[Optional[APIResponseField]] = None
    measures: List[Optional[APIResponseField]] = None


order = 500000

test_value = {
    "dimensions": [{"name": f"myDimension", "type": "string"} for _ in range(order)],
    "measures": [{"name": f"myMeasure", "type": "float"} for _ in range(order)],
}

## This is not efficient
APIResponse(**test_value)

## Distributing the class into 2 makes it run efficiently ##

class APIResponseFieldDimension(MyBaseModel):
    name: str = None
    type: str = None


class APIResponseFieldMeasure(MyBaseModel):
    name: str = None
    type: str = None


class APIResponse(MyBaseModel):
    dimensions: List[Optional[APIResponseFieldDimension]] = None
    measures: List[Optional[APIResponseFieldMeasure]] = None

APIResponse(**test_value)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
install path: <my_path>\Lib\site-packages\pydantic
python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
platform: Windows-10-10.0.22621-SP0
related packages: email-validator-1.3.1 typing_extensions-4.6.1
```

**Comment by sydney-runkle** [comment]
I'll note - if you're using `None` as the default value for all of the fields you've listed, there's no reason for the wrap validator you have (as you're not using the `validate_default=True` flag). That being said, the significant discrepancy between validation time for your two examples is odd.

@adriangb, do you know what might be causing this performance discrepancy?

**Comment by pedro-iatzky** [comment]
@adriangb These are my results for the same script you run:
First, using the same class for both lists:
```
28.1 s ± 3.31 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
peak memory: 6478.13 MiB, increment: 3726.38 MiB
```
Second, dividing into two different classes:
```
5.47 s ± 426 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
peak memory: 1648.13 MiB, increment: 608.11 MiB
```
I guess it might be my OS (Windows) or the python version (3.8.10).


@sydney-runkle in Pydantic v1 if we had this

```python
class APIResponseField(BaseModel):
    name: str = None
    type: str = None
```
Then, the validation passed for this case:
```python
{
  "name": "foo",
  "type": None
}
```
But, in pydantic v2 I have this error
```
ValidationError: 1 validation error for APIResponseField
type
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
```
I can solve this by just making the type Optional
```python
class APIResponseField(BaseModel):
    name: str = None
    type: Optional[str] = None
```
But, we have lots of models, and for the migration, I wanted to avoid changing all of them for now.
Is there some other elegant way to do it?

**Comment by sydney-runkle** [comment]
@pedro-iatzky,

Yeah, the migration guide talks about some of the breaking changes you're referring to [here](https://docs.pydantic.dev/dev-v2/migration/#required-optional-and-nullable-fields). I'd recommend modifying your type specifications `Optional[str] = None` to adhere to best practice.

That being said, even when using Python 3.11 vs Python 3.8, I'm also experiencing a significantly slower runtime for the validation against the first version of `APIResponse` vs the 2nd version.

**Comment by adriangb** [comment]
I tested on 3.11. So 3.8 is what is slower for you?

**Comment by sydney-runkle** [comment]
Testing with 3.8 and 3.11 were both slow (approx 10x for both)

**Comment by sydney-runkle** [comment]
@adriangb interestingly, when I egglink install the lastest (dev) version of `pydantic-core`, I no longer experience the discrepancy.

With `pydantic-core` 2.10.1, I'm seeing a runtime of ~60s for the first version of `APIResponse` and ~5s for the second version.

With the latest dev version of `pydantic-core`, I'm getting ~15s for both versions of `APIResponse`.

**Comment by pedro-iatzky** [comment]
If it helps somehow, running this code is also equivalent to the 2nd case (in both runtime and memory usage) to me:
```python
class APIResponseFieldDimension(MyBaseModel):
    name: str = None
    type: str = None


class APIResponseFieldMeasure(APIResponseFieldDimension):
    pass


class APIResponse(MyBaseModel):
    dimensions: List[Optional[APIResponseFieldDimension]] = None
    measures: List[Optional[APIResponseFieldMeasure]] = None
```
@sydney-runkle independently of this issue, I think I will apply your recommendation and get rid of the wrap validation because even with the second case, I'm adding overall complexity to the validation.

**Comment by sydney-runkle** [comment]
Hi @pedro-iatzky,

Thanks for the feedback. I'm glad that updating the type hints will help you with the speedup.

That being said, this performance issue is still something that we wanted to make sure to solve 😄. As confirmed by the equal performance I observed when using our latest version of `pydantic-core` (the development version), we do have a fix for this performance discrepancy introduced in this [commit](https://github.com/pydantic/pydantic-core/commit/a8fb1e3f46598498b2f01d2a5949ae501739717f).

This change should come across the line with `pydantic` v2.4.3 and `pydantic-core` v2.10.2`.
