### ISSUE TITLE
The return type hint of `model.model_dump` is mismatched with the runtime type

### ISSUE THREAD

**Issue by eggplants** [pydantic/pydantic#7708]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There is a problem where the type hint returned by `model.model_dump` is not matched with runtime type.

### Example Code

The following code is modified from: <https://github.com/eggplants/locloc/blob/0d1d2d8bca01d8d254c72533e164f34776df9899/locloc/loc.py>

```Python
from pydantic import BaseModel, RootModel

class Total(BaseModel):
    lines: int
    blanks: int
    code: int
    files: int
    comments: int


TotalByLanguageDict = RootModel[dict[str, Total]]

res = TotalByLanguageDict.model_validate({
    "python": {
        "lines": 0,
        "blanks": 0,
        "code": 0,
        "files": 0,
        "comments": 0,
    },
}).model_dump()  # typed as dict[str, Total], but `dict[str, dict[str, int]]` at runtime

total = res["python"]  # `total` is typed as `Total`, but `dict[str, int]` at runtime

total["code"]  # no error at runtime, but with `mypy --strict`:
               # error: Value of type "Total" is not indexable

total.code     # no error with mypy, but at runtime:
               # AttributeError: 'dict' object has no attribute
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/eggplants/.cache/pypoetry/virtualenvs/locloc-OwGFgZ83-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.17 (main, Jun 25 2023, 05:19:53)  [GCC 11.3.0]
                     platform: Linux-6.2.0-33-generic-x86_64-with-glibc2.35
             related packages: fastapi-0.103.2 mypy-1.5.1 typing_extensions-4.7.1
```
```

**Comment by hramezani** [comment]
Thanks @eggplants for creating this issue 🙏 

I think your expectation is wrong. Based on [model_dump doc](https://docs.pydantic.dev/latest/concepts/serialization/#modelmodel_dump), It converts the a model and its sub models to a dictionary. So, you shouldn't expect a `dict[str, Total]`

**Comment by eggplants** [comment]
I expect res should be typed as `dict[str, dict[str, int]]`.

**Comment by hramezani** [comment]
Sorry, I didn't understand you.

For `RootModel` we decided the change the return type in https://github.com/pydantic/pydantic/commit/add972469cf457b69d6f25e7958b5b01bf58b63f to address https://github.com/pydantic/pydantic/issues/6190.

You can [Overriding the return type when dumping a model](https://docs.pydantic.dev/latest/concepts/serialization/#overriding-the-return-type-when-dumping-a-model)

**Comment by eggplants** [comment]
`Overriding the return type` you suggested is what I'm looking for. Thank you.
