### ISSUE TITLE
`PYDANTIC_DISABLE_PLUGINS`: env var to disable all plugins

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#7709]
Should be fairly simple to setup.

**Comment by samuelcolvin** [comment]
maybe configurable, so:
* `PYDANTIC_DISABLE_PLUGINS=__all__` disables all, same for `PYDANTIC_DISABLE_PLUGINS=1`
* `PYDANTIC_DISABLE_PLUGINS=foobar` disables just the plugin from the `foobar` package
* `PYDANTIC_DISABLE_PLUGINS=foobar,span` disables the plugins from the `foobar` and `spam` packages

**Comment by geospackle** [comment]
@samuelcolvin @Kludex

I could pick this up!

**Comment by sydney-runkle** [comment]
@geospackle,

That'd be great! Thanks. I've assigned the issue to you :).

**Comment by geospackle** [comment]
Will be able to work on this next week.

**Comment by geospackle** [comment]
@sydney-runkle 
I am unable to load a plugin following the [docs](https://docs.pydantic.dev/latest/concepts/plugins/). Copying the code to my_plugin.py and adding it to pyproject.toml.

Checking it at the [plugin loader](https://github.com/pydantic/pydantic/blob/main/pydantic/plugin/_loader.py) and there is no entry point for the plugin I added.

**Comment by geospackle** [comment]
Found the [test plugin](https://github.com/pydantic/pydantic/tree/main/tests/plugin). That also fails, the log is empty.

```
pydantic version: 2.6.0
pydantic-core version: 2.16.1
pydantic-core build: profile=release pgo=true
python version: 3.12.1 (main, Dec 12 2023, 11:43:12) [GCC 9.4.0]
platform: Linux-6.0.12-76060012-generic-x86_64-with-glibc2.31
related packages: typing_extensions-4.9.0 email-validator-2.1.0.post1 mypy-1.1.1 pydantic-settings-2.1.0 pydantic-extra-types-2.5.0
commit: 5fc166c0
```

**Comment by hramezani** [comment]
@geospackle 

1. Create a new environment
2. Create a new directory and copy [pyproject.toml](https://github.com/pydantic/pydantic/blob/main/tests/plugin/pyproject.toml) and [example_plugin.py](https://github.com/pydantic/pydantic/blob/main/tests/plugin/example_plugin.py) from [plugin directory](https://github.com/pydantic/pydantic/tree/main/tests/plugin) to it
3. Install the current project and pedantic in editable mode. run the `pip install -e .` in the new directory that you've created in previous step and run `pip install -e <pydantic directory in your local machine>`
4. Now, you can create a pedantic model and check the plugin events
```py
from pydantic import BaseModel

class MyModel(BaseModel):
    x: int
    y: str

m = MyModel(x='10', y='hello')
assert m.x == 10
assert m.y == 'hello'
```

**Comment by sydney-runkle** [comment]
@geospackle,

Apologies for the delay in response! Was a bit tied up with the patch release last week. Feel free to also tag @Kludex if you have any other questions re this issue.

@hramezani, thanks for the guidance on getting started with this :).

**Comment by geospackle** [comment]
thanks @hramezani

for some reason the test fails with pdm's env even though the plugin is installed. I can proceed with a fresh environment.

**Comment by hramezani** [comment]
@sydney-runkle can we close this as the PR got merged?

**Comment by hramezani** [comment]
Done in https://github.com/pydantic/pydantic/pull/8767
