### ISSUE TITLE
Problem of pydantic model as request payload

### ISSUE THREAD

**Issue by WilliamQue** [pydantic/pydantic#7711]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I use pydantic model as payload of request.
```
from datetime import datetime as dt

class DataLog(BaseModel):
    id: int
    data1: datetime | None = None
    data2: datetime | None = None

    model_config = ConfigDict(
        validate_assignment=True,
        from_attributes=True,
        json_encoders={
            dt: convert_datetime_to_str
        }
    )

class DataLogIn(BaseModel):
    sig: str
    data: list[DataLog] | None = None


o = DataLog(id=1,data1=dt.now,data2=dt.now)
payload = DataLogIn(sig='aaa',data=[o])
```

the following codes will be correct.
```
resp = requests.post(url, json=json.loads(payload.model_dump_json()))
```

but another way will report:
ERROR:root:<starlette.requests.Request object at 0x000002437B1B8810>: [{'type': 'json_invalid', 'loc': ('body', 185), 'msg': 'JSON decode error', 'input': {}, 'ctx': {'error': 'Unterminated string starting at'}}]
```
resp = requests.post(url, data=playload.model_dump_json())
```

I don't know what's the difference.

### Python, Pydantic & OS Version

```Text
2.4.2
```

**Comment by sydney-runkle** [comment]
Hi @WilliamQue,

Thanks for reporting this. @Kludex, when you have a chance, could you take a look at this? Thanks 😄

**Comment by Kludex** [comment]
Can you show me your Starlette/FastAPI endpoint? Also, please provide all imports, and code related so I don't need to recreate functions, please.

**Comment by sydney-runkle** [comment]
@WilliamQue,

Do you still need help with this issue? 😄

**Comment by sydney-runkle** [comment]
@WilliamQue closing this for now, but feel free to reopen with an MRE 😄 at any point + we'll help you address this!
