### ISSUE TITLE
Expose regex_engine flag

### ISSUE THREAD

**Issue by guyariely** [pydantic/pydantic#7714]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

pydantic-core 2.10.0 added a new flag `regex_engine` (https://github.com/pydantic/pydantic-core/pull/983).

Can you please also expose it in pydantic?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by davidhewitt** [comment]
I will aim to eventually get around to this, if anyone wants to pick this up in the interim and submit a PR please just ping to say you're claiming it!

**Comment by davidhewitt** [comment]
Possibly only question is what exactly the API in `pydantic` looks like. I don't think that should be too hard to figure out.

**Comment by utkini** [comment]
Hey, I would like to try to solve this problem

**Comment by davidhewitt** [comment]
@utkini please go ahead. I think the plumbing might already be in place such that if you just add `regex_engine: Literal['rust-regex', 'python-re']` to the `ConfigDict` type then the whole feature just works. If that's the case, then the rest of the task is about adding some documentation to explain how to use this and why.

**Comment by davidhewitt** [comment]
Feel free to ping me if you need more details, or push a draft PR and we can collaborate.

**Comment by nocturn9x** [comment]
Is there any way to use this, even in a hacky way, for now? I need to construct a bunch of pydantic models at runtime using a provided schema which I then parse and turn into a dictionary of fields. I've seen others use field validators and `re.match()`, but that requires me to store the pattern to match in a separate, private field (which is ugly) because I don't have the literal at hand (it's provided by an external service)

**Comment by utkini** [comment]
Hi @davidhewitt ,
Am I understanding correctly that I should wait for the next version of pydantic-core package?

**Comment by davidhewitt** [comment]
@utkini yes, I plan to do the release on Monday.

**Comment by mecampbellsoup** [comment]
Hey @davidhewitt would love to make use of this as we're migrating from Pydantic v1 to v2 and we have some look-behinds I'd rather not have to figure out how to rewrite 😅 do you know if this is going to be released soon?

**Comment by utkini** [comment]
Hi @mecampbellsoup !

I checked pydantic dependencies and it seems now I can prepare a solution :)

**Comment by nocturn9x** [comment]
That would be lovely
