### ISSUE TITLE
TypeAdapter.dump_python on a subclass ignores extra="allow" on the parent class

### ISSUE THREAD

**Issue by EclipsedSolari** [pydantic/pydantic#7726]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When creating a TypeAdapter for a parent class with `extra="allow"`, then calling `type_adapter.dump_python` or `type_adapter.dump_json` on a subclass, the subclass's fields are ignored despite `extra="allow"` on the parent class. Although it's not a direct comparison, dumping the subclass model directly via `.model_dump` does respect the `extra="allow"` on the parent class.

<details>
<summary>Additional info if desired, since the actual use case is more complex</summary>

My real-world use is in FastAPI. I have HTTP endpoints which can return either 200 OK with an empty JSON object (`{}`) as the body or a HTTP error code with a JSON body that describes the error (`{"error_code": 3, "error_description": "Something went wrong"}`).

My first approach used a Union of response model types, but because the success response model is empty, it's always eligible for selection as the first/best matching model even if there's an error.

```
from fastapi import FastAPI
from hypercorn.asyncio import serve
from pydantic import BaseModel
from typing import Union
import asyncio
import hypercorn


app = FastAPI()


class SuccessResponse(BaseModel):
    pass


class ErrorResponse(BaseModel):
    error_code: int


success_response: SuccessResponse = SuccessResponse()
error_response: ErrorResponse = ErrorResponse(error_code=1)


@app.get("/success")
async def get_success() -> Union[SuccessResponse, ErrorResponse]:
    return success_response


@app.get("/error")
async def get_error() -> Union[SuccessResponse, ErrorResponse]:
    return error_response


if __name__ == "__main__":
    config: hypercorn.Config = hypercorn.Config()
    asyncio.run(serve(app, config))
```

GET /success returns `{}` as expected.
GET /error returns `{}` as well, despite `error_code` being populated. If I reverse the order of Union members, i.e. `Union[ErrorResponse, SuccessResponse]`, I get the expected error body back.

Relying on model order in a Union seems fragile to me, so I took a different approach: a shared empty superclass with `extra="allow"`. The return types aren't as self-explanatory, but I don't need to worry about model ordering.

```
from fastapi import FastAPI
from hypercorn.asyncio import serve
from pydantic import BaseModel, Extra
import asyncio
import hypercorn


app = FastAPI()


class BaseResponse(BaseModel, extra=Extra.allow):
    pass


class SuccessResponse(BaseResponse):
    pass


class ErrorResponse(BaseResponse):
    error_code: int


success_response: SuccessResponse = SuccessResponse()
error_response: ErrorResponse = ErrorResponse(error_code=1)
base_response: BaseResponse = BaseResponse(extra_field="abcde")


@app.get("/success")
async def get_success() -> BaseResponse:
    return success_response


@app.get("/error")
async def get_error() -> BaseResponse:
    return error_response


@app.get("/base")
async def get_base() -> BaseResponse:
    return base_response


if __name__ == "__main__":
    config: hypercorn.Config = hypercorn.Config()
    asyncio.run(serve(app, config))
```

With FastAPI (0.103.2) calling Pydantic v1 (1.10.13),
GET /success returns `{}`, as expected
GET /error returns `{"error_code": 1}`, as expected
GET /base returns `{"extra_field": "abcde"}`, as expected

With FastAPI (0.103.2) calling Pydantic v2 (2.4.2),
GET /success returns `{}`, as expected
GET /error returns `{}`, **not** expected
GET /base returns `{"extra_field": "abcde"}`, as expected

FastAPI's Pydantic v2 call flows through a TypeAdapter that's set up with BaseResponse type information, and I'm guessing only the BaseResponse fields (nothing) are being marked for serialization. I'm a little surprised that `extra="allow"` is being ignored, though, especially since it's respected when I serialize a BaseResponse directly.

</details>

### Example Code

```Python
from pydantic import BaseModel, Extra, TypeAdapter
from pydantic.fields import FieldInfo
from typing import Annotated


class BaseResponse(BaseModel, extra=Extra.allow):
    pass


class ErrorResponse(BaseResponse):
    error_code: int


error_response: ErrorResponse = ErrorResponse(error_code=1)
base_response: BaseResponse = BaseResponse(extra_field="abcde")

print("Calling model_dump:")
print(error_response.model_dump(mode="json"))
print(base_response.model_dump(mode="json"))

print()

field_info: FieldInfo = FieldInfo(annotation=BaseResponse)
type_adapter: TypeAdapter = TypeAdapter(Annotated[field_info.annotation, field_info])

print("Calling type_adapter.dump_python:")
print(type_adapter.dump_python(error_response, mode="json"))
print(type_adapter.dump_python(base_response, mode="json"))
```

Expected output:
```
Calling model_dump:
{'error_code': 1}
{'extra_field': 'abcde'}

Calling type_adapter.dump_python:
{'error_code': 1}
{'extra_field': 'abcde'}
```

Actual output:
```
Calling model_dump:
{'error_code': 1}
{'extra_field': 'abcde'}

Calling type_adapter.dump_python:
{}
{'extra_field': 'abcde'}
```

```
### Python, Pydantic & OS Version
Works under:
pydantic version: 1.10.13
pydantic compiled: True
install path: /home/<User>/Programming/Python/virtualenv/fastapi-repro/lib/python3.10/site-packages/pydantic
python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
platform: Linux-5.19.5-051905-generic-x86_64-with-glibc2.35
optional deps. installed: ['typing-extensions']

Doesn't work under:
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=true
install path: /home/<User>/Programming/Python/virtualenv/fastapi-repro/lib/python3.10/site-packages/pydantic
python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
platform: Linux-5.19.5-051905-generic-x86_64-with-glibc2.35
related packages: typing_extensions-4.8.0 fastapi-0.103.2
```

**Comment by Kludex** [comment]
Thanks for the report. It does look like a bug.

**Comment by sydney-runkle** [comment]
Hi @EclipsedSolari,

This is actually the expected behavior. If you're using a type adapter with a parent class to dump a child class, it's expected that the parent class fields will be dumped, but not those of the child class.

If you want to achieve the behavior that you're expecting, you can take advantage of Pydantic's `SerializeAsAny` type. See the example below:

```py
from pydantic import BaseModel, Extra, SerializeAsAny, TypeAdapter

class BaseResponse(BaseModel, extra=Extra.allow):
    pass


class ErrorResponse(BaseResponse):
    error_code: int


error_response: ErrorResponse = ErrorResponse(error_code=1)
base_response: BaseResponse = BaseResponse(extra_field="abcde")

print("Calling model_dump:")
print(error_response.model_dump(mode="json"))
#> {'error_code': 1}
print(base_response.model_dump(mode="json"))
#> {'extra_field': 'abcde'}

type_adapter: TypeAdapter = TypeAdapter(SerializeAsAny[BaseResponse])

print("Calling type_adapter.dump_python:")
print(type_adapter.dump_python(error_response, mode="json"))
#> {'error_code': 1}
print(type_adapter.dump_python(base_response, mode="json"))
#> {'extra_field': 'abcde'}
```

Let me know if you have any questions / if there's anything else we can help with 😄.

**Comment by sydney-runkle** [comment]
You can imagine a case like this where said behavior would be important:

```py
from pydantic import BaseModel, ConfigDict, SerializeAsAny, TypeAdapter


class User(BaseModel):
    name: str

    model_config = ConfigDict(extra='allow')


class UserInfo(User):
    password: str


user = User(name='sydney')
user_info = UserInfo(name='sydney', password='secret_password')

type_adapter = TypeAdapter(User)
print(type_adapter.dump_python(user_info, mode="json"))
#> {'name': 'sydney'}

type_adapter_modified = TypeAdapter(SerializeAsAny[User])
print(type_adapter_modified.dump_python(user_info, mode="json"))
#> {'name': 'sydney', 'password': 'secret_password'}
```
