### ISSUE TITLE
Not able to use .dict() for Pydantic model conversion to dict

### ISSUE THREAD

**Issue by hritik-peak** [pydantic/pydantic#7728]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In our project we are not able to use .dict() to convert pydantic models to a python dictionary. It is giving error related to MappingProxy. This feature is really required and essential for our Project. Please help with some solution. We tried migration guide also but still many of our things were not working.

Thanks in advance.

### Example Code

```Python
payload: XYZSerializer(Our Pydantic Model)
payload = payload.dict() (Conversion)
error : "mappingproxy " (Not Working)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/anivesh.consultant/Documents/GitHub/master-service/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.6 (default, May  7 2023, 23:32:45)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.1-x86_64-i386-64bit
             related packages: email-validator-2.0.0.post2 typing_extensions-4.8.0 pydantic-settings-2.0.3 fastapi-0.103.2
```

**Comment by hritik-peak** [comment]
We tried that, it is also not working.

**Comment by Kludex** [comment]
> We tried that, it is also not working.

Can you post a minimal, reproducible example? Otherwise, it gets a bit difficult for us to help you.

**Comment by hritik-peak** [comment]
it is solved thanks for the help.
