### ISSUE TITLE
When using optional list parameter with Fastapi, the field is not treated as a list

### ISSUE THREAD

**Issue by theviajero** [pydantic/pydantic#7730]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'll put the same example that's in the Fastapi documentation. Basically, `q` is not treated as a proper list. Even in the /docs the field appears as a string, there's list input, just string input.

[https://imgur.com/a/9feO3jb](https://imgur.com/a/9feO3jb)

With the following requirements **doesn't** work:

```requirements.txt
annotated-types==0.5.0
anyio==3.7.1
click==8.1.7
exceptiongroup==1.1.3
fastapi==0.103.2
h11==0.14.0
idna==3.4
pydantic==2.4.2
pydantic_core==2.10.1
sniffio==1.3.0
starlette==0.27.0
typing_extensions==4.8.0
uvicorn==0.23.2
```

With this one it works:

```requirements.txt
anyio==4.0.0
click==8.1.7
exceptiongroup==1.1.3
fastapi==0.100.0
h11==0.14.0
idna==3.4
pydantic==1.10.13
sniffio==1.3.0
starlette==0.27.0
typing_extensions==4.8.0
uvicorn==0.23.2
```

### Example Code

```Python
from typing import Annotated

from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/items/")
async def read_items(q: Annotated[list[str] | None, Query()] = None):
    query_items = {"q": q}
    return query_items
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/torvic/workspace/venv_temp_2/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jul 25 2023, 14:14:38) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.0-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 fastapi-0.103.2


That's the version, however this also happens in linux.
```

**Comment by Francisca96** [comment]
I also have this issue! Please help!!!

**Comment by ruimartinsptl** [comment]
Same here 🙋‍♂️

I was using FastAPI `0.99.1`, and everything was working as expected, when I updated to version 100.x I started having the same issue, all `list[]` query parameters start being treated as one string

**Comment by Kludex** [comment]
This is a FastAPI issue. You can read more about it here: https://github.com/tiangolo/fastapi/pull/9873.
