### ISSUE TITLE
Field(alias="") not working as expected

### ISSUE THREAD

**Issue by gontovnik** [pydantic/pydantic#7731]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We are trying to migrate from Pydantic 1.9.0 to 2.3.0

We have the following code that works perfectly in 1.9.0:
```py
class HistoryMessage(BaseModel):
    sender: Sender = Field(alias="from")
    text: Text = ""
```

However, upon migration to 2.3.0, it no longer works and basic code like this fails:
```py
EMPTY_MESSAGE = HistoryMessage(
    sender=Sender.user,
    text=" ",
)
```

With the following error: 
```py
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for HistoryMessage
E   from
E     Field required [type=missing, input_value={'sender': <Sender.user: 'user'>, 'text': ' '}, input_type=dict]
E       For further information visit https://errors.pydantic.dev/2.3/v/missing
```

I would really appreciate any help with this one

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/danilgontovnik/workspace/projects/engine/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.16 (main, Dec  7 2022, 10:06:04)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.0-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @gontovnik,

Thanks for your question. You'll need to add a config setting that allows population of fields by their name, not their alias. See [this part of the docs](https://docs.pydantic.dev/2.3/api/config/#pydantic.config.ConfigDict.populate_by_name) regarding how to do that.

**Comment by sydney-runkle** [comment]
Here's an example from the docs:
https://docs.pydantic.dev/2.3/usage/model_config/#populate-by-name

**Comment by lclbm** [comment]
Maybe it should be added to the doc
https://docs.pydantic.dev/latest/concepts/fields/#validation-alias

> When the 'alias' keyword argument is specified, even if you set populate_by_name to True in the [Model Config](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name), VSCode will show a warning when instantiating a model using the field name (though it will work at runtime) — in this case, 'name':

And the description of the alias is `An alternative name for the attribute.`
![image](https://github.com/pydantic/pydantic/assets/54730982/91ceaf6a-4354-47a3-b31d-be2970181bdd)

**Comment by sydney-runkle** [comment]
@lclbm,

What specifically do you want to add to the docs? Feel free to create a PR with your suggested change and I can review 👍
