### ISSUE TITLE
Empty dict with model_dump() after sqlalchemy commit

### ISSUE THREAD

**Issue by davidjb99** [pydantic/pydantic#7734]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, 

When calling `model_dump` on a pydantic model which contains a sqlalchemy session object the data within the sqlalchemy object disappears if you commit the session. 

If you flush the session, and don't commit, the data is present as you would expect. 
If you call an attribute within the the session object the data is present as you would expect for the object you call only.
If you call `session.refresh(orm_object)` the data is present within the object, the problem is when you have many objects you need to refresh this becomes problematic/inefficient. 

This behaviour also occurs with FastAPI when returning a pydantic model and specifying a `response_model`.

```
AFTER FLUSH
{'name': 'foo', 'parents': [{'name': 'john', 'id': 1}]} 

AFTER COMMIT                         
{'name': 'foo', 'parents': [{}]}.                                                          
```

I've tried adding `model_config = ConfigDict(from_attributes=True)` onto `SomeOtherModel` in the below example but this also does not work.

The behaviour is confusing as it is dependent on if you have accessed the object or committed/flushed.  In v1 this worked and committed data was not lost with `.dict()`.

### Example Code

```Python
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Mapped, mapped_column
from sqlalchemy.ext.declarative import declarative_base
from pydantic import ConfigDict, BaseModel

engine = create_engine("sqlite:///:memory:")
Session = sessionmaker(bind=engine)
session = Session()
Base = declarative_base()


class Parent(Base):
    __tablename__ = "parent"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]


class ParentDB(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    name: str
    id: int


class SomeOtherModel(BaseModel):
    name: str
    parents: list[ParentDB]


Base.metadata.create_all(bind=engine)
some_other_model = SomeOtherModel(name="foo", parents=[])


# WORKING WITHOUT COMMIT
new_parent = Parent(name="john")
session.add(new_parent)
session.flush()
print("new_parent", new_parent)

some_other_model.parents.append(new_parent)
print(some_other_model.model_dump())
# {'name': 'foo', 'parents': [{'name': 'john', 'id': 1}]}

# NOT FULLY WORKING WHEN CALLING new_parent_2.name
new_parent_2 = Parent(name="steve")
session.add(new_parent_2)
session.flush()
session.commit()

print("new_parent_2", new_parent_2)
print("new_parent_2", new_parent_2.name)

some_other_model.parents.append(new_parent_2)
print(some_other_model.model_dump())
# {'name': 'foo', 'parents': [{}, {'id': 2, 'name': 'steve'}]}

# NOT WORKING
new_parent_3 = Parent(name="bill")
session.add(new_parent_3)
session.flush()
session.commit()

print("new_parent_3", new_parent_3)

some_other_model.parents.append(new_parent_3)
print(some_other_model.model_dump())
# {'name': 'foo', 'parents': [{}, {}, {}]}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  3 2023, 02:57:16) [GCC 12.2.0]
                     platform: Linux-6.3.13-linuxkit-x86_64-with-glibc2.36
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @davidjb99,

Thanks for reporting. I'm inclined to think this is an issue regarding SQLAlchemy state management policy. You can read more about that [here](https://docs.sqlalchemy.org/en/20/orm/session_state_management.html#when-to-expire-or-refresh).

What happens when you run `session.commit()` after a line like `some_other_model.parents.append(new_parent_3)` instead of before?

**Comment by davidjb99** [comment]
> What happens when you run `session.commit()` after a line like `some_other_model.parents.append(new_parent_3)` instead of before?

If you call `commit` after you have appended the session object you get the same empty dict.

```
new_parent_3 = Parent(name="bill")
session.add(new_parent_3)
session.flush()

some_other_model.parents.append(new_parent_3)
session.commit()

print(some_other_model.model_dump())
# {'name': 'foo', 'parents': [{}, {}, {}]}

```

I think you are right about the session state management 

```
new_parent_3 = Parent(name="bill")
session.add(new_parent_3)
session.flush()
# session.commit()

print("new_parent_3", new_parent_3.__dict__)
# new_parent_3 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fb623dafb30>, 'name': 'bill', 'id': 3}
session.commit()
print("new_parent_3", new_parent_3.__dict__)
# {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fb623dafb30>}

```

If you call a value after commit it seems to use an internal cache to get the value

```
print("new_parent_3", new_parent_3.name)

# new_parent_3 {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7fa485b67ad0>}
# 2023-10-04 12:20:01,551 INFO sqlalchemy.engine.Engine BEGIN (implicit)
# 2023-10-04 12:20:01,552 INFO sqlalchemy.engine.Engine SELECT parent.id AS parent_id, parent.name AS parent_name
# FROM parent
# WHERE parent.id = ?
# 2023-10-04 12:20:01,552 INFO sqlalchemy.engine.Engine [cached since 0.00249s ago] (3,)
# new_parent_3 bill
```

If I run this in pydantic v1 with `.dict` instead of `model_dump` I get 
```
{'name': 'foo', 'parents': [<__main__.Parent object at 0x7f4144da61d0>, <__main__.Parent object at 0x7f4144db6f50>, <__main__.Parent object at 0x7f4144db7910>]}
```
It looks like in v2 the `.__dict__` method on the orm class is called when using `model_dump` resulting in a lost object. Would it be possible to exclude calling `model_dump` on sqlalchemy objects (which is what I think happens in v1) or try to access the values via the session cache?

The behaviour in v1 is preferable as you don't loose the object tracking till you've returned the pydantic model in FastAPI and as such can work with the object again if required.

**Comment by sydney-runkle** [comment]
Hi @davidjb99,

Thanks for following up promptly. Just to check - I assume `dict(some_other_model)` doesn't work? Could you verify this?

I'll look into this bug further, just wanted to check on this first.

**Comment by davidjb99** [comment]
`dict(some_other_model)` does actually result in the same behaviour as v1.

```
new_parent_3 = Parent(name="bill")
session.add(new_parent_3)
session.flush()
session.commit()

print("new_parent_3", new_parent_3)

some_other_model.parents.append(new_parent_3)
print(dict(some_other_model))
#  {'name': 'foo', 'parents': [<__main__.Parent object at 0x7fbb57ea9610>, <__main__.Parent object at 0x7fbb579c0c90>, <__main__.Parent object at 0x7fbb579a98d0>]}
```

Returning `dict(some_other_model)` does not work in FastAPI with the more complex/nested models we have.

```
    return dict(client_objs)
           ^^^^^^^^^^^^^^^^^
ValueError: dictionary update sequence element #0 has length 5; 2 is required
```

**Comment by sydney-runkle** [comment]
Huh, ok. This does look like a but and I'll work on a fix 😄. Stay tuned! 👍

**Comment by sydney-runkle** [comment]
Hi @davidjb99,

Looks like this is actually not a bug. If you modify your code to the following, everything works swimmingly. What's happening is that `Parent` objects are not of type `BaseModel` like `ParentDB` is, and when you simply append `Parent` objects to the `some_other_model.parents` array, said objects are not being converted to `ParentDB` objects.

`from_attributes=True` does help to solve this problem.

```py
from typing import List

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Mapped, mapped_column
from sqlalchemy.orm import declarative_base

from pydantic import ConfigDict, BaseModel


engine = create_engine("sqlite:///:memory:")
Session = sessionmaker(bind=engine)
session = Session()
Base = declarative_base()


class Parent(Base):
    __tablename__ = "parent"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str]


class ParentDB(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    name: str
    id: int


class SomeOtherModel(BaseModel):
    name: str
    parents: List[ParentDB]


Base.metadata.create_all(bind=engine)
some_other_model = SomeOtherModel(name="foo", parents=[])


new_parent = Parent(name="john")
session.add(new_parent)
session.flush()

some_other_model.parents.append(ParentDB.model_validate(new_parent))
print(some_other_model.model_dump())
# {'name': 'foo', 'parents': [{'name': 'john', 'id': 1}]}
```

**Comment by sydney-runkle** [comment]
I might also suggest the following cleaner example, though I'm not sure if you need to be able to append values or not:
```py
new_parent = Parent(name="john")
session.add(new_parent)
session.flush()

some_other_model = SomeOtherModel(name="foo", parents=[new_parent])
print(some_other_model.model_dump())
# {'name': 'foo', 'parents': [{'name': 'john', 'id': 1}]}
print(some_other_model.parents)
# [ParentDB(name='john', id=1)]
```

**Comment by davidjb99** [comment]
> Hi @davidjb99,
> 
> Looks like this is actually not a bug. If you modify your code to the following, everything works swimmingly. What's happening is that `Parent` objects are not of type `BaseModel` like `ParentDB` is, and when you simply append `Parent` objects to the `some_other_model.parents` array, said objects are not being converted to `ParentDB` objects.
> 

I see that `model_validate` at least gets you the dict values, you do of course loose the ORM tracking of the object when you call `model_validate` which is unfortunate.

Hard to see how such different behaviour based on the session state is not a bug tbh.

I would suggest you at least document this behaviour as its both confusing and difficult to debug and a change from v1. 

I hope you add the previous, clean and simple, behaviour from v1 back.

**Comment by sydney-runkle** [comment]
Hi @davidjb99,

I might also suggest that you look into using [SQLModel](https://sqlmodel.tiangolo.com/), which seems to fit your use case pretty well. You might find that there's greater detail given to session state management with that library. We're not currently suited to add logic to `pydantic` that handles `sqlalchemy` state directly, as we don't want to rely on said lib as a dependency.

We welcome PRs with docs updates - I'd be happy to review one if you'd like to add some changes! We currently do have the change in behavior from v1 -> v2 documented in the migration guide in terms of the recommendation to use `from_attributes` and `model_validate` as a replacement from `from_orm`.

I think the debugging was specifically difficult for your use case due to the nature of the append you're using, which doesn't trigger any sort of validation.

Let me know if you have any follow up questions or if there's anything I can help with 😄.

**Comment by davidjb99** [comment]
I'm pretty sure the models are validated when appending as I've seen validation errors in the past.

Anyway SQLModel doesn't support v2, it appears as they are having some of the same issues I was 👀

https://github.com/tiangolo/sqlmodel/pull/632

**Comment by sydney-runkle** [comment]
Hi @davidjb99,

Models aren't validated when appending, as seen in this example:

```py
from typing import List

from pydantic import BaseModel


class Model(BaseModel):
    int_list: List[int]


m = Model(int_list=[])
m.int_list.append(1)
m.int_list.append("a str")
print(repr(m))
#> Model(int_list=[1, 'a str'])
```

Yep, hopefully SQLModel supports V2 soon. Using their models at that point could help 😄.
