### ISSUE TITLE
Cannot initialise StringConstraints object

### ISSUE THREAD

**Issue by manulera** [pydantic/pydantic#7745]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Following the deprecation of constr, I wanted to switch from using `constr(pattern=r'^[A-Z]+$')` to `Annotated[str, StringConstraints(pattern=r'^[A-Z]+$')]` as suggested in the deprecation docstring:

https://github.com/pydantic/pydantic/blob/fe758e58dbc28364bd23387e3cd791ac3cae2043/pydantic/types.py#L726-L732

However, I get the following error:

```
TypeError: StringConstraints() takes no arguments
```

### Example Code

```Python
from pydantic import BaseModel, StringConstraints
from typing import Annotated


class Person(BaseModel):
    name: Annotated[str, StringConstraints(pattern=r'^[A-Z]+$')]
    age: int
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/manu/Documents/Projects/ShareYourCloning/ShareYourCloning_backend/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.8.0 fastapi-0.103.2
```

**Comment by manulera** [comment]
I also get the same error when using constr as indicated in the docs:

```python
from pydantic import BaseModel, constr


class Person(BaseModel):
    name: constr(pattern=r'^[A-Z]+$')
    age: int

```

**Comment by hramezani** [comment]
Thanks @manulera there should be something wrong with your envs.

see https://github.com/pydantic/pydantic/issues/7544#issuecomment-1733738457

You are using `Python 3.9.7` and you need to update your Python to the latest version of `3.9`(e.g. 3.9.16) or a higher version.

**Comment by manulera** [comment]
Hi @hramezani, thank you so much for the quick response. Did not see that one coming, I thought it would be something to do with pydantic. I close the issue then.

Thanks again, I love pydantic by the way! you folks do a great job.

**Comment by dbzix** [comment]
Still seeing the same error:
- Python = 3.12.7
- Pydantic = 2.9.7
- Pyright = 1.1.384
