### ISSUE TITLE
Annotated with a Seriliazer should not raise `Unable to generate pydantic-core schema`

### ISSUE THREAD

**Issue by samsja** [pydantic/pydantic#7746]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a custom Python class for which I added a custom serializer using the Annotated API.

When I try to use it inside a pydantoc model I get the error that Pydantic is unable to `generate pydantic-core schema`. I thought that the whole point of adding a serializer with Annotated was to avoid this problem without touching the initial class.

A fix would be to add `arbitrary_types_allowed=True` in my config. But I am not happy with it because I still want to be sure that anything that I put in my Pydantic BaseModel will be able to get serialized. 

(thanks again for pydantic v2 !)

### Example Code

```Python
from typing import Annotated

from pydantic import BaseModel, PlainSerializer

class MyClass:
    ...

class MyModel(BaseModel):
    my_class: Annotated[MyClass, PlainSerializer(lambda x: 'hello')]


data = MyModel(my_class=MyClass())
```

```shell
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class '__main__.MyClass'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/sami/Documents/workspace/perso/pydantic_tensor/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.10 (main, Jan 18 2022, 17:20:31)  [GCC 9.3.0]
                     platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.31
             related packages: mypy-1.5.1 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @samsja,

Thanks for your question. The annotation with the `PlainSerializer` isn't what's causing the issue here. You get the same error if you don't use the annotation / custom serializer:

```py
from pydantic import BaseModel


class MyClass:
    ...


class MyModel(BaseModel):
    my_class: MyClass


data = MyModel(my_class=MyClass())
"""
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class '__main__.MyClass'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.4/u/schema-for-unknown-type
"""
```

As the first line of the error suggests, you can add `arbitrary_types_allowed=True` to your `model_config`, or you can implement `__get_pydantic_core_schema__` in your `MyClass` definition.

**Comment by samsja** [comment]
Thank you for your quick answers :)

I don't think it fixed my issue tho.

As I mentioned above yes I could use `arbitrary_types_allowed=True` to remove the error message. And that is why I opened the ticket, I don't think it is necessary.

My point is that I would have expected that the annotation of a class with a sterilization should lift off the error message by itself since it is a way to provide a serialization without touching to original class. 

The way I see it is that the Annotated[MyClass, Serlizer()] is equivalent of adding the `__get_pydantic_core_schema__` to my original class. But the good point of it is that I can let my class untouched or even use classes from another library that I cannot change.

**Comment by sydney-runkle** [comment]
Hi @samsja,

Thanks for following up. I still think the `arbitrary_types_allowed` flag is necessary in this case, as the there is no schema generated to support validation against `MyClass` in your example.

**Comment by samsja** [comment]
It seems that even when adding a validator it is not working :cry: 

```python
from typing import Annotated

from pydantic import BaseModel, PlainSerializer
from dataclasses import dataclass
from typing import Any, Callable

from pydantic_core import CoreSchema, core_schema
from typing_extensions import Annotated

from pydantic import BaseModel, GetCoreSchemaHandler


@dataclass
class MyAfterValidator:
    func: Callable[[Any], Any]

    def __get_pydantic_core_schema__(
        self, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        return core_schema.no_info_after_validator_function(
            self.func, handler(source_type)
        )


class MyClass:
    ...

class MyModel(BaseModel):
    my_class: Annotated[MyClass, PlainSerializer(lambda x: 'hello'), MyAfterValidator(str.lower)]


data = MyModel(my_class=MyClass())
```


```
If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
```


It looks like a bug to me. I would really expect that if I have a custom class Annotated with a Serilizaer and a validator it should work without `arbitrary_types_allowed=True`. This would allow the use type from an external library (for which I cannot change the code to add the `__get_pydantic_core_schema__`.

**Comment by samsja** [comment]
Okay seems that I did not see [that part of the documentation](https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types). This will probably solve most of my problems. 

I will take a look and report if it fixed my issue.

Thanks for the support !

**Comment by samsja** [comment]
yes it fixed my issue, closed issue now

**Comment by sydney-runkle** [comment]
Glad to hear it! Sure thing. Glad the 3rd party types docs could be helpful 😄.
