### ISSUE TITLE
use_enum_values gives different result on model_dump when default value is set

### ISSUE THREAD

**Issue by alkimake** [pydantic/pydantic#7757]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If we use `use_enum_values=True` on a model and field has a default value, setting the value on model creation results a different model dump. 

In the example `model1 = SomeModel(some_enum=SomeEnum.BAR)` gives the value of enum but `print(model2.model_dump())` gives the enum itself. As it can be seen on the print.

### Example Code

```Python
from enum import Enum
from typing import Optional

import pydantic


class SomeEnum(Enum):
    FOO = 'foo'
    BAR = 'bar'

class SomeModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        use_enum_values=True
    )
    some_enum: Optional[SomeEnum] = pydantic.Field(default=SomeEnum.FOO)

model1 = SomeModel(some_enum=SomeEnum.BAR)
print(model1.model_dump())
# Prints; {'some_enum': 'bar'}

model2 = SomeModel()
print(model2.model_dump())
# Prints; {'some_enum': <SomeEnum.FOO: 'foo'>}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: <path-to-venv>/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Jun 26 2023, 20:42:23) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5.2-arm64-arm-64bit
             related packages: mypy-1.5.1 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @alkimake,

Thanks for reporting this! This does seem to be a bug 🐛. I'll look into a fix and keep you updated on this thread 😄.

**Comment by sydney-runkle** [comment]
Hi @alkimake,

I think the issue here is that `use_enum_values` takes effect when we're validating an object, and default values aren't validated by default. Instead, you could use the following to get the result you're expecting:

```py
from enum import Enum
from typing import Optional

import pydantic


class SomeEnum(Enum):
    FOO = 'foo'
    BAR = 'bar'

class SomeModel(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        use_enum_values=True, validate_default=True
    )
    some_enum: Optional[SomeEnum] = pydantic.Field(default=SomeEnum.FOO)

model1 = SomeModel(some_enum=SomeEnum.BAR)
print(model1.model_dump())
# Prints; {'some_enum': 'bar'}

model2 = SomeModel()
print(model2.model_dump())
# Prints; {'some_enum': 'foo'}
```

Similarly, you can see here that if you don't validate assignment (which is the default setting), enums could slip through the cracks instead of enum values:

```py
# with `validate_assignment=False` (the default)
model3 = SomeModel()
model3.some_enum = SomeEnum.FOO
print(model3.model_dump())
#> {'some_enum': <SomeEnum.FOO: 'foo'>}

# with `validate_assignment=True` set on `model_config`
model3 = SomeModel()
model3.some_enum = SomeEnum.FOO
print(model3.model_dump())
#> {'some_enum': 'foo'}
```

Does this make sense? Feel free to let me know if you have any follow up questions.
The main reason that we don't validate default values automatically is that it's time consuming and costly, but we recognize that there's definitely a need in some cases, hence the configurable setting.

Hope this helps 😄

**Comment by sydney-runkle** [comment]
#2010 reports the same issue from V1, with a similar solution.

Going to close this given that it's the expected behavior + has been reported before, but feel free to follow up with any questions you might have 😄.

**Comment by alkimake** [comment]
Hello @sydney-runkle 

Thanks for taking care of the issue.

I believe validation and translation completely 2 different process and it feels weird to me that translation depends on validation. I will fix my issue by adding `validate_default=True` but this might raise unwanted results or conflicts for other cases or users of pydantic. The user is being pushed to validate all models that just to get proper translation on `model_dump`. Not to mention this will have a performance hit. 

Best,
Ake

**Comment by sydney-runkle** [comment]
Hi @alkimake,

Thanks for following up. I can understand the confusion regarding this behavior. However, for an enum set during model initialization, the value is extracted during validation (and later when `model_dump` is called, the value of the enum is already assigned to the field in question) so we must handle the case of the default at validation as well.

Perhaps a documentation update regarding this behavior could be helpful, as it has come up for many people. I'll open a PR later this week with a docs update 😄.
