### ISSUE TITLE
`HttpUrl` allows some invalid links 

### ISSUE THREAD

**Issue by ilija-lazoroski** [pydantic/pydantic#7758]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When validating a http url in pydantic V2, we have noticed that some previously invalid URLs are valid.

Per docs and issues, I understand that now pydantic uses rust `url` crate which uses RFC 3986. After some investigation, I can see that two of those examples below are valid per RFC 3986 but one is not and pydantic v2 still validates it.

The regex for RFC 3986 (I think this is the one) is https://regex101.com/r/vNXgYM/1

<img width="483" alt="image" src="https://github.com/pydantic/pydantic/assets/15820737/eafa0a0a-04f7-449f-b92c-00e766e5e34c">

I am just curious to what actually changed in `HttpUrl` and if should we remove these cases from our tests?
Also why RFC 3986 doesn't validate `http://example.com/\" onclick=\"alert('XSS!')` but `HttpUrl` does?

### Example Code

```Python
from pydantic import BaseModel, HttpUrl, ValidationError

class MyModel(BaseModel):
    url: HttpUrl

# All three of these doesn't raise ValidationError
m = MyModel(url="http://example.com/\" onclick=\"alert('XSS!')")
m = MyModel(url="hTTps:/localhost.com")
m = MyModel(url="http://$(some_malicious_command).com")


# Pydantic V1
from pydantic.v1 import BaseModel, HttpUrl

class MyModel(BaseModel):
    url: HttpUrl

# These raises ValidationError
m = MyModel(url="http://example.com/\" onclick=\"alert('XSS!')")
m = MyModel(url="hTTps:/localhost.com")
m = MyModel(url="http://$(some_malicious_command).com")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/mcus/monkey-types-env/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:48) [GCC 11.3.0]
                     platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0 mypy-1.5.1 email-validator-2.0.0.post2
```

**Comment by ilija-lazoroski** [comment]
First thanks for the quick response. 

Then thanks for clarifying this, it helps. I think just providing a reference to RFC 3986 along with examples or/and the actual regex will be enough in the documentation.

As far as I am concerned we can close this issue. 👍

**Comment by sydney-runkle** [comment]
Sounds good. I'll go ahead and close this issue + leave the other URL documentation issues open until we get that documentation update pushed.

> Then thanks for clarifying this, it helps. I think just providing a reference to RFC 3986 along with examples or/and the actual regex will be enough in the documentation.

I'll be sure to add these things in the docs update 👍

Thanks as well for your prompt responses. Have a wonderful weekend 😄.

**Comment by Tom-Camp** [comment]
Using Pydantic 2.7.1 HttpUrl accepts URLs without TLDs. 
```python
from pydantic import BaseModel, HttpUrl, ValidationError
class MyModel(BaseModel):
    url: HttpUrl
    
m = MyModel(url="http://www.example")
print(m.url)
http://www.example/
```
From the Pydantic code comment: 
A type that will accept any http or https URL.

*** TLD required**
* Host required
* Max length 2083

**Comment by Tom-Camp** [comment]
Oops, saw that this was closed. Will open new issue.

**Comment by racinmat** [comment]
Hi, why is this closed? The issue still persists, and from this discussion I don't see what should I use to validate the links correctly, in a way invalid links would not be allowed.
