### ISSUE TITLE
`RuntimeError: Unable to apply constraint strict to schema lax-or-strict` when trying to set strictness on enum fields

### ISSUE THREAD

**Issue by lovetheguitar** [pydantic/pydantic#7759]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

To allow "enum matching" from json input, I depend on setting enum field validation to `strict=False`.

This worked fine with pydantic 2.1.0. 

Expectation would be that this works for enums. 😄 

Thanks for your great work.

### Example Code

```Python
import enum
from pydantic import BaseModel, ConfigDict, Field


class Demo(enum.Enum):
    A = 0
    B = 1


class User(BaseModel):
    model_config = ConfigDict(strict=True)
    name: str
    age: int = Field(strict=False)
    this_works: Demo
    this_does_not: Demo = Field(strict=False)  # comment this to make it work
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\UserName\AppData\Local\pypoetry\Cache\virtualenvs\package-name-oKTDepZE-py3.8\Lib\site-packages\pydantic
               python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @lovetheguitar,

Thanks for reporting this! This does seem to be a bug 🐛. I'll look into a fix and keep you updated on this thread 👍.

**Comment by sydney-runkle** [comment]
@lovetheguitar sure thing! Thanks again for the bug report 😄.

We generally have been adding new releases approximately monthly, but if you want to use our latest version (with the bug fix), you can pull down our latest changes from the main branch.

You can see more about our release timeline [here](https://github.com/pydantic/pydantic/releases).
