### ISSUE TITLE
Orjson feature. Orjson give very good perfomance for example in FASTAPI 2 codes

### ISSUE THREAD

**Issue by shurshilov** [pydantic/pydantic#7769]
Orjson give very good perfomance for example in FASTAPI 2 codes
This with orjson
![image](https://github.com/pydantic/pydantic/assets/11828278/8e7da8c9-32d5-45cc-8136-886ab9b11d73)
![image](https://github.com/pydantic/pydantic/assets/11828278/c66683f4-6c6a-489f-a337-23392d0ac5bd)

And this without
![image](https://github.com/pydantic/pydantic/assets/11828278/888d2c63-2ef6-4ac2-be53-f16ebcdc4df9)
![image](https://github.com/pydantic/pydantic/assets/11828278/2b8241a9-56f2-4541-9dab-97a98c737376)
810 vs 583 resuests/second
892 vs 643 MB  per 10seconds
~20% speedup
So... how use orjson inside pydantic?
Because if we use this 
![image](https://github.com/pydantic/pydantic/assets/11828278/600b5e48-a60b-40da-adfd-0d721d57099d)
![image](https://github.com/pydantic/pydantic/assets/11828278/c64ba844-6acc-43e2-9ae6-d7027a0eec9f)

I think pydantic use slowly serelize by default...
P.S.
tools for testing _autocannon 127.0.0.1:81 -d 10 -c 30 -w 3_
start fastapi uvicorn 1 worker

_Originally posted by @shurshilov in https://github.com/pydantic/pydantic/discussions/6388#discussioncomment-7211179_

**Comment by samuelcolvin** [comment]
Have you read the orjson code, or understood what it's doing?

Please come back to us when you've reviewed all the orjson serialization code and are confident that all use of `unsafe` in Rust is safe.

The short answer is no, is not possible to use orjson for serialization, we can slowly make pydantic's serialization faster in Rust, but it's hard work.

**Comment by shurshilov** [comment]
I think that in 99.9% of cases speed is more important than security) it's strange that you choose 0.01%. Because of this, people are leaving for node.js)))think about it.

**Comment by samuelcolvin** [comment]
What OS & arch are you using?

I would imagine a 10% speed improvement shouldn't be too hard to find, but I really don't think we can use orjson.

**Comment by shurshilov** [comment]
> What OS & arch are you using?
> 
> I would imagine a 10% speed improvement shouldn't be too hard to find, but I really don't think we can use orjson.

Test was windows 10 x64  and production will be linux in docker python slim i think (as i remember its ubuntu 64))

**Comment by mastercoms** [comment]
This used to be covered by #714 but was removed without note in Pydantic v2.
