### ISSUE TITLE
@nathan-chappell off the top of my head I'd like to see a minimal repro so I can think this through. Please share in a new issue so that we can have that conversation in its own space.

### ISSUE THREAD

**Issue by nathan-chappell** [pydantic/pydantic#7773]
@nathan-chappell off the top of my head I'd like to see a minimal repro so I can think this through. Please share in a new issue so that we can have that conversation in its own space.

_Originally posted by @davidhewitt in https://github.com/pydantic/pydantic/issues/7093#issuecomment-1751432340_

**Comment by samuelcolvin** [comment]
Please use a clear/concise description of the question/issue in the issue title and explain in detail what you're asking in the body, please complete the questions set out in the issue template.

**Comment by davidhewitt** [comment]
@nathan-chappell to clarify I was hoping (as samuel requests) that you'd open it as a fresh issue with a new code reproduction of what is not behaving as you'd like, so readers with the same question as you have a full discussion all in one page.

**Comment by nathan-chappell** [comment]
> @nathan-chappell to clarify I was hoping (as samuel requests) that you'd open it as a fresh issue with a new code reproduction of what is not behaving as you'd like, so readers with the same question as you have a full discussion all in one page.

Sure, I was trying to edit this issue when it got closed.  Please see #7774
