### ISSUE TITLE
Generic Type Inference on parse

### ISSUE THREAD

**Issue by nathan-chappell** [pydantic/pydantic#7774]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There is a surprising behavior when type-inference mixes with pydantic's handling of generics.
It works beautifully until it starts interacting with "type inference."  In the case below, the generic-argument to `ItemBound` can be inferred from the constructor arguments, so it is surprising when the serialized model returns no values.  Whatever the explanation for the behavior, it's surprising that by removing a bound on a type-variable things "start to work."

### Example Code

```Python
from typing import TypeVar, Generic
from pydantic import BaseModel

TBound = TypeVar("TBound", bound=BaseModel)
TNoBound = TypeVar("TNoBound")

class IntValue(BaseModel):
    value: int

class ItemBound(BaseModel, Generic[TBound]):
    item: TBound

class ItemNoBound(BaseModel, Generic[TNoBound]):
    item: TNoBound

item_bound_inferred = ItemBound(item=IntValue(value=3))
item_bound_explicit = ItemBound[IntValue](item=IntValue(value=3))
item_no_bound_inferred = ItemNoBound(item=IntValue(value=3))
item_no_bound_explicit = ItemNoBound[IntValue](item=IntValue(value=3))

print(f"# inferred and bound: {str(item_bound_inferred.model_dump()):26} {item_bound_inferred.__class__.__name__} -> {item_bound_inferred.item.__class__.__name__}")
print(f"# explicit and bound: {str(item_bound_explicit.model_dump()):26} {item_bound_explicit.__class__.__name__} -> {item_bound_explicit.item.__class__.__name__}")
print(f"# inferred, no bound: {str(item_no_bound_inferred.model_dump()):26} {item_no_bound_inferred.__class__.__name__} -> {item_no_bound_inferred.item.__class__.__name__}")
print(f"# inferred, no bound: {str(item_no_bound_explicit.model_dump()):26} {item_no_bound_explicit.__class__.__name__} -> {item_no_bound_explicit.item.__class__.__name__}")

# inferred and bound: {'item': {}}               ItemBound -> IntValue
# explicit and bound: {'item': {'value': 3}}     ItemBound[IntValue] -> IntValue
# inferred, no bound: {'item': {'value': 3}}     ItemNoBound -> IntValue
# inferred, no bound: {'item': {'value': 3}}     ItemNoBound[IntValue] -> IntValue
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.0
        pydantic-core version: 2.10.0
          pydantic-core build: profile=release pgo=true
                 install path: /home/nchappell/programming/py/casa-chatbot/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.17 (main, Jun  6 2023, 20:11:21)  [GCC 11.3.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: fastapi-0.103.1 mypy-1.5.1 typing_extensions-4.8.0
```

**Comment by nathan-chappell** [comment]
#7093 @davidhewitt

**Comment by davidhewitt** [comment]
Thanks for elaborating on this issue. So I agree I think that having the bound on the type parameter change runtime behaviour is not helpful here. I'm sure there are reasons why we looked at the bound, cc @dmontagu do you have a sense of this?

I think your second example, while it looks related to the bound, is probably actually strongly related to of #6895, where `make_holder` is using a generic placeholder but `make_holder2` is using a concrete target type.

**Comment by sydney-runkle** [comment]
This seems related to #7703

**Comment by nathan-chappell** [comment]
> @nathan-chappell any interest in opening a PR with documentation updates based on your experiences / what you would have liked to have documented?
> 
> Thanks for flagging this issue + your feedback 😄.

Don't threaten me with a good time. I do have an interest, I'll take a look and see if I can pin it down over the next couple days...

**Comment by sydney-runkle** [comment]
@nathan-chappell,

Running your example with `v2.4.2` I get the following:

```py
# inferred and bound: {'item': {'value': 3}}     ItemBound -> IntValue
# explicit and bound: {'item': {'value': 3}}     ItemBound[IntValue] -> IntValue
# inferred, no bound: {'item': {'value': 3}}     ItemNoBound -> IntValue
# inferred, no bound: {'item': {'value': 3}}     ItemNoBound[IntValue] -> IntValue
```

I think we fixed this based on the problem brought up in #7562.

**Comment by sydney-runkle** [comment]
@nathan-chappell,

Regarding your second example, I don't think it makes sense to use a generic placeholder to parametrize `Holder`, when said Generic has already been specified within the class definition. That being said, now that the bug related to your first example has been fixed, you're free to instantiate the `Holder` class with or without the explicit parameter type, and all should run as expected. 

I do think that your first example shows in great detail the various permutations of allowed instantiation patterns, so I'll pull a version of that over to use in the docs 😄.

**Comment by nathan-chappell** [comment]
@sydney-runkle I'm a a bit confused about the chronology of things, but I don't think that one of the more important points I was trying to make came through in the dev-docs I'm looking at.  I'm pretty sure that's the case, because now the docs state: 

> Note, **you may run into a bit of trouble if you don't parametrize a generic** when the case of validating against the generic's bound could cause data loss. See the example below:

```
print(ItemHolder(**loaded_data).model_dump())  
#> {'item': {}}

print(ItemHolder[IntItem](**loaded_data).model_dump())  
#> {'item': {'value': 1}}
```

The point is: **you may run into a bit of trouble even if you do parametrize a generic**
Please consider my original example:

```python
from typing import TypeVar, Generic
from pydantic import BaseModel

TItem = TypeVar("TItem", bound="ItemBase")

class ItemBase(BaseModel):
    ...

class IntItem(ItemBase):
    value: int

class ItemHolder(BaseModel, Generic[TItem]):
    item: TItem

class ItemHolderFactory(Generic[TItem]):
    def __call__(self, vals: dict) -> ItemHolder[TItem]:
        # THIS IS IMPORTANT
        return ItemHolder[TItem](**vals)

class RealItemHolderFactory(Generic[TItem]):
    def __init__(self, item_type: type[TItem]) -> None:
        self.item_type = item_type

    def __call__(self, vals: dict) -> ItemHolder[TItem]:
        # SO IS THIS
        return ItemHolder[self.item_type](**vals)


loaded_data = {"item": {"value": 1}}

# THIS FACTORY FAILS
print(ItemHolderFactory[IntItem]()(loaded_data).model_dump())   # {'item': {}}
# THIS FACTORY SUCCEEDS
print(RealItemHolderFactory(IntItem)(loaded_data).model_dump()) # {'item': {'value': 1}}
```

I just reran this with
```
Python 3.12.0
pydantic==2.4.2
pydantic_core==2.10.1
```

The `return` statements in the `__call__` method are both subtly different, but in **both** cases we *parametrized the generic*.  The problem is that when we parameterize it with the bound `TypeVar` `TItem`, pydantic couldn't use this bound at runtime to properly serialize the model (that's because that information is not available at runtime - it is only available to the typechecker).  So it's not just about parameterizing the Generic models, it's about parameterizing them with the *right* information.

Maybe someone thinks that this case I've demonstrated is convoluted or something, but the point is that this can happen anywhere a `TypeVar` is bound by the typechecker and used in context where it is not the "real" type information.

**Comment by sydney-runkle** [comment]
@nathan-chappell,

Sorry that we had a bit of a miscommunication on what was most important to include in the docs update. I'd be more than happy to revisit this so that we can make sure the docs are clear.

I understand your point about passing in the right information at runtime, as the type information available at runtime vs the type checker can be a bit confusing.

I suppose I was a bit hesitant to include your second example, as we don't suggest parametrization of a generic model via a `TypeVar` anywhere in the documentation (to my knowledge, please correct me if I've missed something), and I thought the more involved example might be more confusing than helpful. The `RealItemHolderFactory` approach seems more intuitive to me. This feels to me more like something to have as a helpful issue that others can reference if they run into this specific use case rather than something to include on the `BaseModel` section of the concepts page of the docs.

That being said, I do think that the first example you gave regarding information loss as a consequence of different parametrization patterns was super helpful and informative, and I'm glad to have that as a part of the docs ⭐.

Let me know your thoughts on this - and thanks for helping us improve `pydantic` 😄. If this is something you'd still like to emphasize that we include in the docs, maybe it'd be more appropriate to add to the `examples` section 👍

**Comment by nathan-chappell** [comment]
Thanks for the clarification. I'm going to defer to your judgment on this -
I'm happy I was able to contribute to the docs.

Cheers

**Comment by sydney-runkle** [comment]
@nathan-chappell,

Sounds great. Let's leave your second example as an issue for people to reference for now. If we see lots of people struggling with that concept, we can add something to the docs.

Thanks very much for your contribution 👍 it was super helpful! 🌟

**Comment by mmzeynalli** [comment]
Is @nathan-chappell's solution still the only way to be able to serialize TypeVar fields?

**Comment by mmzeynalli** [comment]
I have similar problem, but I also want to enable type hinting. I decided to write here before writing this as separate issue:

```Python
class BaseApiRequest(Generic[BT]):
    session: aiohttp.ClientSession

    def __init__(self, client_name: str, logger_name: str):
        self.base_url: str
        self.path: str
        self.verb: Optional[str] = None
        self.headers: dict = {}
        self.body: dict = {}

        #
        self.client_name = client_name
        self.logger = logfire.with_tags(logger_name)

        self.resp_model: type[BaseModel]
        self.accept_status_codes: list[int] = [200, 201, 204]

    @property
    def url(self):
        return urljoin(self.base_url, self.path)

    async def prep_data(self):
        raise NotImplementedError(
            'Either this function should be implemented, or verb should be valid value'
        )

    async def api_call(self, *args, **kwargs):
        async with self.session.request(
            self.verb,
            self.url,
            data=self.body,
            headers=self.headers,
        ) as resp:
            resp.body = await resp.json()

            if not resp.ok:
                self.logger.error(
                    f'{self.client_name} failed. Status code was {resp.status}. '
                    f'Content => {resp.body}'
                )
            elif resp.status not in self.accept_status_codes:
                self.logger.error(
                    f'{self.client_name} response is not in {self.accept_status_codes}. '
                    f'Status: {resp.status}, body: {resp.body}'
                )

           #return ApiResponseFactory2[self.resp_model]()(resp)
            return ApiResponseFactory(self.resp_model)(resp)

    async def __call__(self, *args, **kwargs):
        return await self.api_call(*args, **kwargs)

```

In another file, I have:

```python
from typing import Generic, TypeVar

import aiohttp
from pydantic import BaseModel

AT = TypeVar('AT')


class ApiResponse(BaseModel, Generic[AT]):
    ok: bool
    status: int
    headers: dict
    body: AT


class ApiResponseFactory2(Generic[AT]):
    def __call__(self, resp: aiohttp.ClientResponse) -> ApiResponse[AT]:
        return ApiResponse[AT].model_validate(resp, from_attributes=True)


class ApiResponseFactory(Generic[AT]):
    def __init__(self, item_type: type[AT]) -> None:
        self.item_type = item_type

    def __call__(self, resp: aiohttp.ClientResponse) -> ApiResponse[AT]:
        return ApiResponse[self.item_type].model_validate(resp, from_attributes=True)
```

I want to define the type in subclass, as follows:

```python
class EPointSaveCardResponseSchema(BaseModel):
    status: EPointResponseStatus
    redirect_url: str
    card_id: str

class EPointSaveCardRequest(BaseApiRequest[EPointSaveCardResponseSchema]):
    def __init__(self):
        super().__init__()
        self.path = '/api/1/card-registration'
        self.verb = 'POST'
        self.resp_model = EPointSaveCardResponseSchema
```

The problem is:

With `ApiResponseFactory`, code works, however, type hinting does not work properly. With `ApiResponseFactory2` its vice-versa, type hinting works perfect, but, code does not work, as `body: T` is not being validated/serialized correctly. I can do:

```python
return ApiResponseFactory[BT](self.resp_model)(resp)
```

Which makes both type-hinting and code work, however, it also means, I repeat myself: I define the pydantic class both as typevar in class inheritance `class EPointSaveCardRequest(BaseApiRequest[EPointSaveCardResponseSchema])` and as storing it as variable in `self.resp_model`. I would like clearer solution, if there are any

**Comment by nathan-chappell** [comment]
@mmzeynalli Could you please show the definition of `BT`?

**Comment by nathan-chappell** [comment]
@mmzeynalli Hey there, I tried using this simplified version of the code above:

```py
from typing import Any, Generic, TypeVar
from pydantic import BaseModel

BT = TypeVar("BT")


class BaseApiRequest(Generic[BT]): ...


class ItemSchema(BaseModel):
    card_id: str


class ItemRequest(BaseApiRequest[ItemSchema]):
    def __init__(self):
        super().__init__()
        self.resp_model = ItemSchema


AT = TypeVar("AT")
ClientResponse = dict[str, Any]


class ApiResponse(BaseModel, Generic[AT]):
    status: int
    body: AT


class ApiResponseFactory2(Generic[AT]):
    def __call__(self, resp: ClientResponse) -> ApiResponse[AT]:
        response = ApiResponse[AT].model_validate(resp, from_attributes=True)
        print(f"[ApiResponseFactory2] {response}")
        return response


class ApiResponseFactory(Generic[AT]):
    def __init__(self, item_type: type[AT]) -> None:
        self.item_type = item_type

    def __call__(self, resp: ClientResponse) -> ApiResponse[AT]:
        response = ApiResponse[self.item_type].model_validate(resp, from_attributes=True)
        print(f"[ApiResponseFactory] {response}")
        return response


api_response_factory = ApiResponseFactory(item_type=ItemSchema)
api_response = api_response_factory({"status": 200, "body": {"card_id": "xxx"}})
print(api_response.model_dump())
api_response.body.card_id

# output:
# [ApiResponseFactory] status=200 body=ItemSchema(card_id='xxx')
# {'status': 200, 'body': {'card_id': 'xxx'}}
```

That output is about what I'd expect, and the type hinter helps me out with the body field as well:

![image](https://github.com/user-attachments/assets/9eb172c6-15a5-405c-8a08-305ef8194f24)

Did I miss something?  It seems like you are certainly having similar issues to those pointed out in this issue, but it also seems like they've been resolved.  I tested on `pydantic==2.8.2` `pydantic_core==2.20.1`

**Comment by mmzeynalli** [comment]
I think the problem is with type hinting a class attribute, in main class, for subclasses. I cannot type hint it correctly, so, the function return is "calculated" correctly for type.

**Comment by mmzeynalli** [comment]
Yes, I tested it, and it turns out, this problem occurs if I do it within class, trying to give type later in subclass. I edited your example code, and here is what I get:

```python
from typing import Any, Generic, TypeVar

from pydantic import BaseModel


class ItemSchema(BaseModel):
    card_id: str


AT = TypeVar('AT')
ClientResponse = dict[str, Any]


class ApiResponse(BaseModel, Generic[AT]):
    status: int
    body: AT


class ApiResponseFactory(Generic[AT]):
    def __init__(self, item_type: type[AT]) -> None:
        self.item_type = item_type

    def __call__(self, resp: ClientResponse) -> ApiResponse[AT]:
        response = ApiResponse[self.item_type].model_validate(resp, from_attributes=True)
        print(f'[ApiResponseFactory] {response}')
        return response


class MyClass:
    def __init__(self) -> None:
        self.item_class: type[AT]

    def resp(self):
        factory = ApiResponseFactory(item_type=self.item_class)

        return factory({'status': 200, 'body': {'card_id': 'xxx'}})


class MySubClass(MyClass):
    def __init__(self) -> None:
        super().__init__()
        self.item_class = ItemSchema


resp = MySubClass().resp()


print(resp.model_dump())
print(resp.body.card_id)

# Output
# [ApiResponseFactory] status=200 body=ItemSchema(card_id='xxx')
# {'status': 200, 'body': {'card_id': 'xxx'}}
# xxx
```

Code works, but not type hinting:

![image](https://github.com/user-attachments/assets/ce8d3580-9e63-4ddd-9ee7-a38203e78e82)

**Comment by nathan-chappell** [comment]
@mmzeynalli In your code I get a complaint from the type checker on line 31:

![image](https://github.com/user-attachments/assets/fd3de84f-2fb3-4bd3-91f3-d268ef560f2a)

It looks like a typo, I'm guessing you intended to bind it with `Generic[AT]` in the base class list.  If that's the case, then maybe something like this evil is what you are looking for?

```py
class MyClass(Generic[AT]):
    def __init__(self) -> None:
        self.item_class: type[AT] = get_args(self.__class__.__orig_bases__[0])[0]  # type: ignore
        # ...But you don't ignore!  You fix this and make it better or check for violations of assumptions!

    def resp(self):
        factory = ApiResponseFactory(item_type=self.item_class)

        return factory({"status": 200, "body": {"card_id": "xxx"}})


class MySubClass(MyClass[ItemSchema]):
    pass
```

*as complete code*

```py
from typing import Any, Generic, TypeVar, get_args

from pydantic import BaseModel


class ItemSchema(BaseModel):
    card_id: str


AT = TypeVar("AT")
ClientResponse = dict[str, Any]


class ApiResponse(BaseModel, Generic[AT]):
    status: int
    body: AT


class ApiResponseFactory(Generic[AT]):
    def __init__(self, item_type: type[AT]) -> None:
        self.item_type = item_type

    def __call__(self, resp: ClientResponse) -> ApiResponse[AT]:
        response = ApiResponse[self.item_type].model_validate(resp, from_attributes=True)
        print(f"[ApiResponseFactory] {response}")
        return response


class MyClass(Generic[AT]):
    def __init__(self) -> None:
        self.item_class: type[AT] = get_args(self.__class__.__orig_bases__[0])[0]  # type: ignore
        # ...But you don't ignore!  You fix this and make it better or check for violations of assumptions!

    def resp(self):
        factory = ApiResponseFactory(item_type=self.item_class)

        return factory({"status": 200, "body": {"card_id": "xxx"}})


class MySubClass(MyClass[ItemSchema]):
    pass


resp = MySubClass().resp()


print(resp.model_dump())
print(resp.body.card_id)

# Output
# [ApiResponseFactory] status=200 body=ItemSchema(card_id='xxx')
# {'status': 200, 'body': {'card_id': 'xxx'}}
# xxx
```

**Comment by mmzeynalli** [comment]
Yep, this works as I want it to work. Even if it is an evil way to do it, at least, it's better than repeating myself)) Thanks a lot!
