### ISSUE TITLE
Alias Generator not working with Validation Alias 

### ISSUE THREAD

**Issue by eawd123wadd4354as243df** [pydantic/pydantic#7781]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using an `alias_generator` and a `validation alias`, the `alias_generator` does not override the serialization alias (which is **not** set)[^1].
This is very unintuitive, since if a normal alias is set, it overrides default value for serialization alias as well[^2]. 
Setting `alias_priority=1` on every field fixes this, but it also removes the `validation alias`[^3].

My suggestion would be making making `alias_generator` override both unset `validation_alias` and unset `serialization_alias`. Additionally there should be a `default_alias_priority` field added to the `model_config`, so that even when adding a `serialization_alias`, a common style can be guaranteed.

**Why is this needed?**
In our FastApi project, we want to return a JSON object, with CamelCase. In python we want to use snake case though. We get some data from another api, so I added a `validation_alias` to Model. This however broke our API, since the resulting JSON was not in CamelCase anymore.

[^1]: See `foo_bar1`
[^2]: See `foo_bar2`.
[^3]: See `foo_bar3`.
[^4]: See https://docs.pydantic.dev/latest/concepts/alias/#alias-priority

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, Field
class Foo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
        alias_generator=lambda name: ''.join(word.capitalize() for word in name.split('_'))
    )

    foo_bar0: str
    foo_bar1: str = Field(validation_alias='foo_baz1')
    foo_bar2: str = Field(validation_alias='foo_baz2', alias='foo_bra2')
    foo_bar3: str = Field(validation_alias='foo_baz3', alias_priority=1)


foo = Foo(foo_bar0='foo0',  # no validation_alias set
          foo_baz1="foo1",  # validation_alias works correctly
          foo_baz2="foo2",  # validation_alias works correctly
          foo_bar3="foo3")  # validation_alias doesn't work because it's overriden

print(foo.model_dump(by_alias=True))
# {
#   'FooBar0': 'foo0',      # Works correctly 
#   'foo_bar1': 'foo1',     # Doesn't work (!! unexpected)
#   'foo_bra2': 'foo2',     # Works, but doesn't apply generator (as expected?)
#   'FooBar3': 'foo3'       # Works correctly
#   }
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.5.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: C:\Users\jsi\PycharmProjects\TESTS\venv\Lib\site-packages\pydantic
               python version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by davidhewitt** [comment]
Seems reasonable to me that serialization alias should be set from the generator for `foo_bar1`.

**Comment by sydney-runkle** [comment]
Hey @eawd123wadd4354as243df,

Any interest in opening a PR to address this feature request? 😄 Thanks for filing the request!
