### ISSUE TITLE
[minor] typing issue when using deprecated __fields__ or __fields_set__

### ISSUE THREAD

**Issue by slafs** [pydantic/pydantic#7790]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There's a small typing issue when using the (already deprecated) `__fields__` or `__fields_set__` properties of a model class.

At runtime I properly get the deprecation warning:
```
PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
```

But when running mypy on such code, I get a surprising error saying:
```
error: "Callable[[BaseModel], dict[str, FieldInfo]]" has no attribute "__iter__" (not iterable)  [attr-defined]
```

Apparently mypy doesn't properly recognise the type of the deprecated property.

This might be problematic for folks (like us) trying to ignore the deprecation warnings
and only fix them later after the switch to v2.

Note that the problem doesn't occur on model _instances_ (only on a class).

### Example Code

```Python
from pydantic import BaseModel


class Model(BaseModel):
    foo: int
    bar: str


print(
    [f for f in Model.__fields__]
)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/slafs/.pyenv/versions/3.10.9/envs/.../lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (main, Dec 21 2022, 11:47:15) [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-13.5.2-x86_64-i386-64bit
             related packages: email-validator-2.0.0.post2 mypy-1.5.1 typing_extensions-4.8.0 fastapi-0.103.2 pydantic-settings-2.0.2
```

**Comment by Viicos** [comment]
I can't reproduce on latest `mypy`. If it is still the case, this is probably an issue with mypy, as pyright gets it correctly.
