### ISSUE TITLE
Generic method to create Strict<type> fields

### ISSUE THREAD

**Issue by haizaar** [pydantic/pydantic#780]
# Feature Request

This is a followup from https://github.com/tiangolo/fastapi/issues/453#issuecomment-523746120

## Description
We'd like have a general way to create Strict<anything> field classes, e.g. StrictInt, StrictFloat, etc. that do value instance type checking during validation phase.

## Rationale
My usecase for this feature is to be able properly support Unions for native types. Today if you have a field coming from JSON data that can be either `bool`, `str`, or `int`, you can't define a model in pydantic that will keep original data field's type.

Here is an example:

```python
class MyModel(BaseModel):
    field: Union[int, bool, str]
```
The above will:
* parse `{"field": "1"} as integer
* parse `{"field": "foo"}` as boolean, since `bool` "eats" anything (as well as `str`)

I.e. `MyModel(**json.loads('{"field": "foo"}')).json() != '{"field": "foo"}'`

## Implementation
@dmontagu [suggested](https://github.com/tiangolo/fastapi/issues/453#issuecomment-523746120) two approaches to implement this.

### Creator function
```python
T = TypeVar("T")

def strict_type(type_: Type[T]) -> Type[T]:
    class StrictType(type_):
        @classmethod
        def __get_validators__(cls) -> Generator[Callable[[Any], T], None, None]:
            yield cls.validate

        @classmethod
        def validate(cls, v: Any) -> T:
            if not isinstance(v, type_):
                raise TypeError(f"Expected instance of {type_}, got {type(v)} instead")
            return v
    return StrictType

StrictInt = strict_type(int)
```

It works just fine. However mypy does not like dynamic types and prints errors for the above code:
```
/tmp/foo.py:10: error: Variable "type_" is not valid as a type
/tmp/foo.py:10: error: Invalid base class "type_"
/tmp/foo.py:27: error: Variable "union2.StrictInt" is not valid as a type
```

### Generic class
```python
T = TypeVar("T")

class StrictType(Generic[T]):
    type_: ClassVar[Type[T]]
    def __get_validators__(cls) -> Generator[Callable[[Any], T], None, None]:
        # yield int_validator
        yield cls.validate

    @classmethod
    def validate(cls, v: Any) -> T:
          if not isinstance(v, cls.type_):
              raise TypeError(f"Expected instance of {type_}, got {type(v)} instead")
        return v

class StrictInt(StrictType[int]):
    type_ = int
```
This version is mypy friendly but is less convenient to the user - requires to create classes in a bit of a magical manner.

**Comment by samuelcolvin** [comment]
I'm happy with `StrictInt` and `StrictFloat` and also a generic version. I'm not sure it'll always be acceptable to simply use `isinstance()`, for instance: `isinstance(True, int) == True`; we'll need other specific checks for some types. For performance reasons it would therefore be best to have custom types for common types

**However I would note the following:**
* these changes won't be adopted until v1 at the earliest. With v1 `"foo"` will no longer be eaten by `bool` which has got stricter, see #617
* With v1 you should also be able to use `descriminator` as per #619 to aid Union validation.

**Comment by samuelcolvin** [comment]
> Will you accept PR for explicit implementations for StrictInt and StrictFloat to complement existing Strict* implementations or will it have to wait till v1 as well?

We're working on v1 now. Only bugs are being released until we get v1 out. I will accept a PR for `StrictInt` and `StrictFloat` to be included in v1.

`descriminator` could be a function, it won't need to be a field name, in fact it might always be a function. We need to discuss more how it'll work, but in theory it should be able to accomplish what you want here.

**Comment by DerRidda** [comment]
I did a PR that addresses this issue in some respect: https://github.com/samuelcolvin/pydantic/pull/799

**Comment by skewty** [comment]
Whatever solution is accepted for #1060 may affect this so linking here.

**Comment by and-semakin** [comment]
Is there a way to create strict types using `Field()` object?

For example this is completely what I want but `mypy` can't parse it correctly and I would avoid using `# type: ignore`:

```python
class Kek(BaseModel):
    value: conint(strict=True, ge=0, le=10)  # type: ignore
```

Is it possible to do it using `Field` or in some other way just to create strict int and avoid `# type: ignore` comments?

```python
class Kek(BaseModel):
    value: int = Field(..., strict=True, ge=0, le=10)  # doesn't work, just an example/suggestion
```

**Comment by PrettyWood** [comment]
If this can help there is a possible solution here https://github.com/samuelcolvin/pydantic/issues/2079#issuecomment-720118099

**Comment by tuukkamustonen** [comment]
An alternative view on this: Developers are most likely split into two camps:

1. Those who want strict parsing _everywhere_, and
2. those who don't.

Field-specific ability to enable strict parsing might be useful to some,but  I _believe_ masses would just want to toggle "strictness" on and write:

```py
class Kek(BaseModel):
    f1: str
    f2: bool
    f3: int
```

Rather than more explicit:

```py
class Kek(BaseModel):
    f1: StrictStr
    f2: StrictBool
    f3: conint(strict=True)  # mypy will nag about this, btw.
```

Latter looks ugly and kludgy. On a big project, multiply that by 100-1000+ and you have lots of wasted characters (and clarity).

**Comment by Kludex** [comment]
On V2, you can use the `Strict` metadata. Check how it's done internally:

https://github.com/pydantic/pydantic/blob/f50ae9f282c29e460563829d40d9eeffcf87e479/pydantic/types.py#L82-L92
