### ISSUE TITLE
model_json_schema should not serialize the corresponding value or provide a json_encoder option

### ISSUE THREAD

**Issue by so1n** [pydantic/pydantic#7807]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The object returned by model_json_schema is a dict, but the value in the dict is serialized, which is very strange.  

In this scenario, when one of the extra parameters is a Python object, it causes the `model_json_schema` execution to fail, e.g:
```python
from pydantic import BaseModel, Field, version

class Faker(object):

    def __str__(self):
        return 1

class Demo(BaseModel):
    aaa: int = Field(example=Faker())

print(version.VERSION)
print(Demo.model_json_schema())
```
Under normal circumstances model_json_schema should not serialize the returned dict, if you must do so, you should provide a json_encoder option.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @so1n,

Thanks for adding this feature request.

the `model_json_schema` function returns a jsonable dict of python data. So if you call `json.dumps(m.model_json_schema)`, you'll get a valid `json` string. As mentioned in your related issue #7772, I'll add a docs update today to make this behavior more clear, as it has confused a few people.

You can see other examples of where this comes into play on these issues:
#7042
#7609

If you desire to customize the json schema generation, you can reference [this section](https://docs.pydantic.dev/dev/concepts/json_schema/#customizing-the-json-schema-generation-process) of the docs regarding how to do that (I think this fits your request for a custom json encoder, effectively).

Let us know if you have any questions 😄.

**Comment by sydney-runkle** [comment]
Also, as you mentioned in your comment [here](https://github.com/pydantic/pydantic/issues/7772#issuecomment-1752469650), you can sort of game the `json_schema_extra` with a callable to inject the value you're desiring.

Just note, you're violating the json serializable nature then of the result:

```py
import json
from pydantic import BaseModel, Field


class Faker(object):
    value = 1


class Demo(BaseModel):
    aaa: int = Field(json_schema_extra=lambda v: v.update({"example": Faker()}))


print(json.dumps(Demo.model_json_schema()))
"""
TypeError: Object of type Faker is not JSON serializable
"""
```

**Comment by so1n** [comment]
@sydney-runkle 
The `model_json_schema` returns a serialized dict, which is a very strange thing to do.

I think `model_json_schema` should return a serialized json string and add a new `model_json_schema_dict` method to return a dict that will not be serialized.

**Comment by sydney-runkle** [comment]
Hey @so1n,

Thanks for following up. I've added a docs update to clarify the nature of the value returned from `model_json_schema` [here](https://github.com/pydantic/pydantic/pull/7816).

Modifying the behavior of `model_json_schema` in such a way would be a pretty significant breaking change, so that isn't something we can do at the moment. However, as shown with the workarounds above, if you need to, you should be able to inject python objects in your schema where desired.

We discuss the different JSON Schema related functions in the [docs](https://docs.pydantic.dev/latest/concepts/json_schema/) in more detail.
