### ISSUE TITLE
`validate_call` does not support `|` correctly

### ISSUE THREAD

**Issue by slorg1** [pydantic/pydantic#7813]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

After a brand new fresh install of Pydantic 2, I got an issue with the use of `| None` and `validate_call`:

The error happens at JIC time (not run time).

It does work if I replace the `| None` with `Optional`.

I boiled down the issue to these few lines:
![image](https://github.com/pydantic/pydantic/assets/5043518/41e63f88-753c-4d59-b085-d1154a2089ed)

### Example Code

```Python
from pydantic import ConfigDict, validate_call

class TestClass:
    ...

@validate_call(config=ConfigDict(strict=True, arbitrary_types_allowed=True), validate_return=True)
def test(test: TestClass | None):
    print("this is a test")
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/lpgros/.virtualenvs/env3-exp/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, May 12 2023, 09:21:14)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.0-x86_64-i386-64bit
             related packages: email-validator-2.0.0.post2 typing_extensions-4.7.1
```

**Comment by sydney-runkle** [comment]
Hi @slorg1,

Thanks for reporting this. I think the problem is that python==3.9.12 doesn't support defining `Union` types with `|`.
