### ISSUE TITLE
Using the `coerce_numbers_to_str` configuration option allows boolean values for string fields.

### ISSUE THREAD

**Issue by nwgreenl** [pydantic/pydantic#7820]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello! 👋 

When using the `coerce_numbers_to_str` configuration option in "lax" mode on dataclasses, boolean values are accepted for string fields and set as their string representation (e.g `"True"`).

This seems to be unexpected behavior per the docs [here](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.coerce_numbers_to_str) , as I wouldn't think that a boolean would be considered a number type.

> If True, enables automatic coercion of any Number type to str in "lax" (non-strict) mode.

### Example Code

```Python
from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


@dataclass(config=ConfigDict(coerce_numbers_to_str=True))
class Foo:
    id: str

foo_true = Foo(id=True)
print(foo_true.id)
# => 'True'

foo_false = Foo(id=False)
print(foo_false.id)
# => 'False'


@dataclass
class Bar:
    id: str

bar = Bar(id=True)  # raises
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
python version: 3.8.17 (default, Sep 11 2023, 10:50:19)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.6-arm64-arm-64bit
```

**Comment by sydney-runkle** [comment]
Hi @nwgreenl,

Thanks so much for reporting this. This is indeed a bug 🐛 on the `pydantic-core` side of things. I'll work on a fix + post updates on this issue thread 😄.
