### ISSUE TITLE
Postponed annotations in dynamically created models

### ISSUE THREAD

**Issue by flying-sheep** [pydantic/pydantic#7824]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I want to dynamically create models that reference each other, but there doesn’t seem to be a way to handle postponed annotations in this way.

The following code illustrates this (of course I could write the example’s code in declarative form, but not my actual code).
Running it results in an error:

```py
import sys
from typing import ForwardRef
from types import ModuleType

from pydantic import create_model

mod = sys.modules['test_mod'] = ModuleType('test_mod')
mod.A = create_model('A', b_seq=(ForwardRef('tuple[B, ...]', module='test_mod'), ()))
mod.B = create_model('B', a_seq=(ForwardRef('tuple[A, ...]', module='test_mod'), ()))
```

Ideally, `create_model` would gain an argument like `__defer__: bool` which could be used to defer the whole content of the if branch in the meta class until the user runs it.

https://github.com/pydantic/pydantic/blob/cde930fcd6ed3561a536e44c3d2c6d0530202c6e/pydantic/_internal/_model_construction.py#L97

That could look something like this:

```py
...
mod.A = create_model('A', __defer__=True, b_seq=(ForwardRef('tuple[B, ...]', module='test_mod'), ()))
mod.B = create_model('B', __defer__=True, a_seq=(ForwardRef('tuple[A, ...]', module='test_mod'), ()))

mod.A.finalize()
mod.B.finalize()
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by flying-sheep** [comment]
Whoops, seems like my example doesn’t actually result in the behavior I described.

I’ll come up with an actual reproducer tomorrow.

**Comment by sydney-runkle** [comment]
Hi @flying-sheep,

Does specifying `__config__=ConfigDict(defer_build=True)` in your `create_model` work for your use case?

**Comment by sydney-runkle** [comment]
@flying-sheep,

Going to close this for now. Happy to reopen if you come up with an MRE 👍

**Comment by flying-sheep** [comment]
Yeah, sorry about that! We changed our approach and the new one doesn’t suffer from this. I’ll add a MRE if we run into it again.
