### ISSUE TITLE
Warn when `Field(alias=...)` is used as nested `Annotated` metadata

### ISSUE THREAD

**Issue by un-def** [pydantic/pydantic#7828]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Consider the following models:

```python
class AnnotatedOptional(BaseModel):
    field: Annotated[Optional[int], Field(alias='field_alias', gt=0)]


class OptionalAnnotated(BaseModel):
    field: Optional[Annotated[int, Field(alias='field_alias', gt=0)]]
```

The only difference is the order of `Optional` and `Annotated`.

`AnnotatedOptional` works as expected:

```python
# OK
AnnotatedOptional(field_alias=1)
# OK
AnnotatedOptional(field_alias=None)
# ValidationError: Input should be greater than 0
AnnotatedOptional(field_alias=-1)
```

On the other hand, `OptionalAnnotated` ignores `alias`:

```python
# The alias is ignored: ValidationError: Field required
OptionalAnnotated(field_alias=1)
# OK if the field name is used
OptionalAnnotated(field=1)
```

Strangely enough, _some_ `Field` parameters are respected, e.g., `gt` works as expected:

```python
# ValidationError: Input should be greater than 0
OptionalAnnotated(field=-1)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: [redacted]/virtualenvs/pydantic-optional-annotated-bug/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 (main, Oct  5 2023, 13:09:34) [GCC 11.4.0]
                     platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0
```

**Comment by un-def** [comment]
In regard to `gt` in `OptionalAnnotated`, it makes sense since this constraint is only applicable to the wrapped `int` type, that is,  `Optional[Annotated[int, Field(alias='field_alias', gt=0)]]` is roughly translated to `PositiveInteger | NoneType`. `alias` is a different beast — it is a property of the field as a whole, not a property of one of the applicable types, hence non-top-level `alias`, in my understanding, is simply (and _silently_) ignored:

```python
class TwoAliases(BaseModel):
    field: Annotated[str, Field(alias='string')] | Annotated[int, Field(alias='integer')]

# OK
TwoAliases(field='foobar')
# OK
TwoAliases(field=123)
# ValidationError: Field required
TwoAliases(string='foobar')
# ValidationError: Field required
TwoAliases(integer='foobar')
```

**Comment by sydney-runkle** [comment]
Hi @un-def,

Thanks for reporting this 😄. You're correct, the `gt` specification is still applied to the int type, but the `alias` must be applied to the outermost level of the `field` specification. You can see the differences in the data attached to each version of your `field` with the following:

```py
print(AnnotatedOptional.model_fields)
#> {'field': FieldInfo(annotation=Union[int, NoneType], required=True, alias='field_alias', alias_priority=2, metadata=[Gt(gt=0)])}

print(OptionalAnnotated.model_fields)
#> {'field': FieldInfo(annotation=Union[Annotated[int, FieldInfo(annotation=NoneType, required=True, alias='field_alias', alias_priority=2, metadata=[Gt(gt=0)])], NoneType], required=True)}
```

Note that in the first case, `alias='field_alias'` is a property of the `field`'s `FieldInfo` object, whereas in the second case, it's nested within the `FieldInfo` attached to the `int`. 

The first approach, that of the `AnnotatedOptional` class seems like the right approach to me. Here's another example of why we only use the `alias` at the highest level:

```py
from typing import Annotated, List, Optional, Union, TypeVar
from pydantic import BaseModel, Field
from pprint import pprint


A = TypeVar("A", bound=str)
B = TypeVar("B", bound=int)


class Model(BaseModel):
    some_field: List[Annotated[Union[A, B], Field(..., union_mode='left_to_right', alias='some_field_alias')]] # <-- take note


# still works, wouldn't work if we specified the alias at the `some_field` level as we should
m = Model(some_field=['a', 'b', 'c', 1, 2, 3])
print(m.some_field)
```

In the above example, specifying the alias within the `Annotation` of the `Union` does nothing for our `some_field`. We want the alias to apply to `some_field`, not the `Union` within the list.

Does that explanation make sense? Happy to discuss more if not 👍

**Comment by un-def** [comment]
Thanks for the explanation, it confirms my assumption. I completely agree that the current behavior is sane. I realized this only after I opened the issue, hence my first comment.

This is not a bug, but it would be great if `pydantic` emitted a warning (or even threw an exception after a transitional period) when alias–related `Field` parameters are used in nested (non–top–level) annotations. If this feature is hard to implement or expensive for the runtime, at least it is worth mentioning this caveat in the documentation (probably in [this section](https://docs.pydantic.dev/2.4/concepts/alias/)). There is at least one example of `Optional[Annotated[..., Field(...)]]` in the documentation: [Numeric Constraints](https://docs.pydantic.dev/2.4/concepts/fields/#numeric-constraints) (the warning box; [source](https://github.com/pydantic/pydantic/blob/d7872225cdb8a3744cfdc808282f59b805e684f8/docs/concepts/fields.md?plain=1#L420)). Maybe it's just me, but, at first glance, it is not obvious why it is OK to use such an annotation for constraints (`gt`, `min_length`, etc.), but not for `alias`.

Also, there is a potential for subtle bugs. Imagine that someone created the following model:

```python
class Job(BaseModel):
    model_config = ConfigDict(extra='ignore')  # or 'allow'

    completed: bool
    progress: Annotated[int, Field(ge=0)]
    progress_percent: Annotated[int, Field(ge=0, le=100, alias='percent')]


print(repr(Job(completed=False, progress=27, percent=54)))
#> Job(completed=False, progress=27, progress_percent=54)
```

Then they realized that progress can be `null` and updated the model accordingly:

```python
class Job(BaseModel):
    model_config = ConfigDict(extra='ignore')  # or 'allow'

    completed: bool
    progress: Optional[Annotated[int, Field(ge=0)]] = None
    progress_percent: Optional[Annotated[int, Field(ge=0, le=100, alias='percent')]] = None


print(repr(Job(completed=False, progress=27, percent=54)))
#> Job(completed=False, progress=27, progress_percent=None)
```

`progress` still works, but `progress_percent` is silentry broken, the value is always `None`.

**Comment by sydney-runkle** [comment]
Hi @un-def,

Thanks for the response (with a great example). I completely agree that the docs could use an update regarding a warning against this kind of `alias` specification. I'd be happy to open a PR this week to make that addition 👍.

As far as a warning / exception goes when a user specifies an `alias` via some lower level field specification, I think a warning would be appropriate.

We'd certainly more than welcome a PR implementing such a change. Are you interested in opening a PR to add this behavior? If not, no worries - I can mark with a `help-wanted` label and we can add this to the feature request list 😄.

**Comment by un-def** [comment]
Great! I'm not familiar with `pydantic` internals at all, I'm just taking the first steps with the library, so I'm not ready for such a task yet. Anyway, this is by no means a high priority feature.

**Comment by alexmojaki** [comment]
While investigating this issue I found this test:

```python
def test_annotated_field_info_not_lost_from_forwardref():
    from pydantic import BaseModel

    class ForwardRefAnnotatedFieldModel(BaseModel):
        foo: 'Annotated[Integer, Field(alias="bar", default=1)]' = 2
        foo2: 'Annotated[Integer, Field(alias="bar2", default=1)]' = Field(default=2, alias='baz')
```

That last line with two different `Field`s is completely invalid, right?

**Comment by nix010** [comment]
@sydney-runkle I would like to work on this.
