### ISSUE TITLE
Tries to parse non-pydantic metadata from `Annotated` as model data (and fails)

### ISSUE THREAD

**Issue by chbndrhnns** [pydantic/pydantic#7833]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When adding metadata to `Annotated` that pydantic does not understand, I expect it to ignore it. It seems, in the example, pydantic tries to parse the incoming data based on the `Metadata` model.

Here is the error:

```
tests/test_.py:13 (test_)
def test_():
        data = {"state": 2}
>       assert Model.model_validate(data)
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
E       state
E         Input should be a valid dictionary or instance of Metadata [type=model_type, input_value=2, input_type=int]
E           For further information visit https://errors.pydantic.dev/2.4/v/model_type

test_.py:16: ValidationError
```

PEP 593 states:

> "If a library (or tool) encounters a typehint Annotated[T, x] and has no special logic for metadata x, it should ignore it and simply treat the type as T.|

I do not see this happening here.

### Example Code

```Python
from typing import Annotated

from pydantic import BaseModel


class Metadata(BaseModel):
    ...


class Model(BaseModel):
    state: Annotated[int, Metadata()]


def test_():
    data = {"state": 2}
    assert Model.model_validate(data)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/cleancoder/Library/Caches/pypoetry/virtualenvs/xxx-sT27uenX-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Feb 20 2023, 14:56:22)  [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-13.4.1-arm64-arm-64bit
             related packages: email-validator-2.0.0.post2 pydantic-extra-types-2.1.0 typing_extensions-4.7.1 pydantic-settings-2.0.3 fastapi-0.103.2
```

**Comment by chbndrhnns** [comment]
My workaround (so far) is to use a pydantic v1 model as metadata which seems to be ignored correctly.

**Comment by chbndrhnns** [comment]
Thanks for the reply!

My use case is having metadata for describing metadata related with a database to describe indexed fields and the primary key. It looks similar to this example:

```py
import pydantic as p

class FieldAnnotation(p.BaseModel):

    idx_name: t.Optional[str] = None
    unique: bool = False

    class Config:
        """Model config"""

        frozen = True


class Indexed(FieldAnnotation):
    ...

class PrimaryKey(FieldAnnotation):

    idx_name: str = DEFAULT_PK_INDEX_NAME
    unique: bool = True
    auto_increment: bool = False
```

Can you think of a way to make pydantic ignore my annotations for parsing?
I have no intention to override schema generation for `Model`. 
It seems pydantic completely ignores the `int` annotation in the original post.

**Comment by sydney-runkle** [comment]
@chbndrhnns,

Sure thing. Hmm how do you access / reference that metadata later on? Could it be something you pass into `json_schema_extra`?

**Comment by chbndrhnns** [comment]
I am collecting the annotations and then I post-process the ones that I am interested in, like in 

```py
class Parser:
    def _parse_model_field(self, field_name, arg):
        if not isinstance(arg, FieldAnnotation):
            return
        # do something if the annotation is a subclass of `FieldAnnotation`

```

**Comment by sydney-runkle** [comment]
@chbndrhnns,

Yeah, I wonder if it'd make sense to do something like [this](https://docs.pydantic.dev/latest/concepts/fields/#customizing-json-schema):

```py
from typing import Annotated

from pydantic import BaseModel, Field


class Metadata(BaseModel):
    field_1: str = "something"
    field_2: int = 0


class Model(BaseModel):
    state: int = Field(..., json_schema_extra=Metadata().model_dump())


m = Model(state=2)
print(m.model_fields)
#> {'state': FieldInfo(annotation=int, required=True, json_schema_extra={'field_1': 'something', 'field_2': 0})}
```

Would that work for your use case?

**Comment by chbndrhnns** [comment]
Your workaround feels quite clunky to me and I would need to explain this approach to my colleagues, as well. For the time being, I prefer using v1 models which give me the same semantics. Maybe using dataclasses would be another option.

What is it that makes pydantic assume I would want to override schema generation by specifying some metadata instance? I guess it just eats all instances of `BaseModel` it finds. That's a bit surprising to me. 

If I am using pydantic here in a way that you do not want support, please let me know.

**Comment by sydney-runkle** [comment]
Hi @chbndrhnns,

Thanks for your reply. I'd agree, that workaround is indeed clunky. Another potential workaround, though albeit still a bit clunky, would be to do something like the following:
```py
state: Annotated[int, {'metadata': Metadata()}]
```

As mentioned above, [this section](https://docs.pydantic.dev/latest/concepts/json_schema/#modifying-the-schema) of the JSON schema docs details the usefulness of overriding schema via `Annotated` metadata specifications.

That being said, having the same function (`__get_pydantic_core_schema__`) used for pulling schema data out of `Annotated` metadata as well as general schema generation can be a bit problematic, as seen by this specific use case. Perhaps in V3 we could introduce support for another function that would help to decouple the two use cases.

**Comment by adriangb** [comment]
> That being said, having the same function (__get_pydantic_core_schema__) used for pulling schema data out of Annotated metadata as well as general schema generation can be a bit problematic, as seen by this specific use case. Perhaps in V3 we could introduce support for another function that would help to decouple the two use cases.

Agreed that just naming it differently in v3 might be a good idea.

Could you override `__get_pydantic_core_schema__` on FieldAnnotation to be a no-op? Something like:

```python
if cls is not source_type: 
    return handler(source_type)
return super().__get_pydantic_core_schema__(source_type, handler)
```

**Comment by sydney-runkle** [comment]
Thanks @adriangb for that suggestion.

Here's an example of how you could implement that suggestion for your use case:

```py
from typing import Annotated

from pydantic import BaseModel, GetCoreSchemaHandler
from pydantic_core import CoreSchema


class Metadata(BaseModel):
    foo: str = "metadata!"
    bar: int = 100

    @classmethod
    def __get_pydantic_core_schema__(cls, source_type: type[BaseModel], handler: GetCoreSchemaHandler) -> CoreSchema:
        if cls is not source_type:
            return handler(source_type)
        return super().__get_pydantic_core_schema__(source_type, handler)


class Model(BaseModel):
    state: Annotated[int, Metadata()]



m = Model.model_validate({"state": 2})
print(repr(m))
#> Model(state=2)
print(m.model_fields)
#> {'state': FieldInfo(annotation=int, required=True, metadata=[Metadata(foo='metadata!', bar=100)])}
```

**Comment by chbndrhnns** [comment]
Thanks very much, the no-op version is exactly what I was looking for. 

I find it worth adding such notice to the docs. The docs that you linked here say:

> [...] Annotated metadata [...] can modify or override the generated schema by implementing __get_pydantic_core_schema__.

I believe that's not precise. If being a subclass of `BaseModel`, they DO override the schema as the magic method is implemented implicitly. There is no way around it, as we saw here unless you add the `if` statement.

**Comment by sydney-runkle** [comment]
Agreed, a docs update would be nice. I'll add one this week 👍
