### ISSUE TITLE
Request: supporting getting of `Field`s directly from `BaseModel`

### ISSUE THREAD

**Issue by jamesbraza** [pydantic/pydantic#7836]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

```python
from pydantic import BaseModel, Field
from pydantic.fields import FieldInfo

class Foo(BaseModel):
    bar: int = Field(default=1, description="text")

bar_field: FieldInfo = Foo.model_fields["bar"]
bar_field: FieldInfo = Foo["bar"]  # Proposal
```

It would be cool if one could do `Foo["bar"]` instead of `Foo.model_fields["bar"]` as a nifty shorthand.  What do you think?

I think it remains intuitive, and `BaseModel` doesn't have a `__getitem__` implemented yet

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by un-def** [comment]
`__class_getitem__` ([PEP 560](https://peps.python.org/pep-0560/)) is specifically designed [for generics]( https://docs.python.org/3/reference/datamodel.html#object.__class_getitem__). Your idea is doable (there is no runtime restrictions in regard to the type of the return value), but is discouraged:

> Using `__class_getitem__()` on any class for purposes other than type hinting is discouraged.

Static type checkers wouldn't like it either.

<sup>(I am not a `pydantic` developer)</sup>

**Comment by jamesbraza** [comment]
Oh wow I didn't know you can change font size in GitHub haha cool.  And you're right, since it's on the class one would need to use `__class_getitem__`, thanks for that correction.

The quote you provided comes from here: https://docs.python.org/3/reference/datamodel.html#the-purpose-of-class-getitem.  Also, https://github.com/python/mypy/issues/11501 has some relevant debate.

**Comment by sydney-runkle** [comment]
Hi @jamesbraza,

Thanks for your issue report ⭐!

We already implement the `__class_getitem__` function for `BaseModel` subclasses here:

https://github.com/pydantic/pydantic/blob/d7872225cdb8a3744cfdc808282f59b805e684f8/pydantic/main.py#L622-L684

**Comment by alexmojaki** [comment]
Is there a reason why `Foo.bar` doesn't work?

**Comment by jamesbraza** [comment]
@alexmojaki I think that doesn't work, for some reason `Foo.bar` is giving an `AttributeError`.  I had the same thought at first.

```python
In [1]: from pydantic import BaseModel, Field
   ...: from pydantic.fields import FieldInfo
   ...:
   ...:
   ...: class Foo(BaseModel):
   ...:     bar: int = Field(default=1, description="text")
   ...:

In [2]: Foo.bar
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 Foo.bar

File ~/code/play/venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py:216, in ModelMetaclass.__getattr__(self, item)
    213         if rebuilt_validator is not None:
    214             # In this case, a validator was built, and so `__pydantic_core_schema__` should now be set
    215             return getattr(self, '__pydantic_core_schema__')
--> 216 raise AttributeError(item)

AttributeError: bar
```

And @sydney-runkle oh I see, though I think that `__class_getitem__` currently only services type information (unless I am misunderstanding).  Any thoughts on extending it to be able to return `FieldInfo` objects?

**Comment by alexmojaki** [comment]
Right, I was asking if pydantic intentionally doesn't support it.

**Comment by jamesbraza** [comment]
Ah I see, yeah I am wondering the same.  I updated the name of this issue to better match

**Comment by jamesbraza** [comment]
I realized we should be using descriptor protocol for this, so this can be implemented with `ModelMetaclass.__get__`: https://github.com/pydantic/pydantic/blob/v2.4.2/pydantic/_internal/_model_construction.py#L216

```python
            try:
                return self.model_fields[item]
            except KeyError as exc:
                raise AttributeError(item) from exc
```

No need to mess with `__class_getitem__`

**Comment by alexmojaki** [comment]
`__get__` is indeed part of the descriptor protocol, but I think you mean `__getattr__` which is what you linked to.

**Comment by jamesbraza** [comment]
Ha thanks @alexmojaki I need to get some more sleep these days...

What do you think of that idea though? It seems like the only one using `ModelMetaclass` in v2 is `BaseModel`

**Comment by jamesbraza** [comment]
Okay testing it out, it seems that change leads to [`collect_model_fields`](https://github.com/pydantic/pydantic/blob/v2.4.2/pydantic/_internal/_fields.py#L67) throws a warning for non-`Field` class variables:

```python
UserWarning: Field name "x" shadows an attribute in parent "test_alias_generator_parent.<locals>.Parent";
```

So what I posed doesn't work, it's sadly not that simple 😆 

I do think thought that `pydantic` models should be able to just do `Foo.bar` or `Foo["bar"]` to easily access a `FieldInfo`

**Comment by sydney-runkle** [comment]
As of now, I don't think this is a feature request that makes it onto our road map.

In general, I think extracting field info directly from the model ends up being more confusing than helpful in regards to its similarity to accessing fields on an instance. If I hear otherwise from anyone else on the team re our desire to implement this kind of a change, we can certainly reopen 👍
