### ISSUE TITLE
Show param values in validation error messages

### ISSUE THREAD

**Issue by sscherfke** [pydantic/pydantic#784]
# Feature Request

This originates from https://github.com/tiangolo/fastapi/issues/473:

The error messages created by the parameter validation are like `"msg": "value is not a valid integer"`.

It would be helpful for debugging if they contained the actual value of that parmeter: `"msg": f"value '{param}' is not a valid integer"` -> `"msg": "value 'spam' is not a valid integer"`

**Comment by samuelcolvin** [comment]
I disagree. What if the value is a string of 5000 characters? Should we show the entire thing in the error message.

However I think we could do with improving the data available about errors, for example we should make sure the provided value is always available in `ctx` and that all error `types` are unique, so completely custom logic and error message translations work properly.

**Comment by sscherfke** [comment]
If the string is too long, we might abbreviate it like this?
```python
str_val = str(value)
if len(str_val) > 15:
    str_val = f'{str_val[:8]}...{str_val[-4:]}'
```

But I would be hapy with anything that improves the error message (and thus, debugging). :)

**Comment by samuelcolvin** [comment]
debugging would be fixed by adding the original value to `ctx` which would then be shown in the `str()` method of `ValidationError` and therefore python's standard error printing.

**Comment by pawelad** [comment]
Can I somehow help with this?

**Comment by JosXa** [comment]
Mentioning #1938 for another use-case/problem that arises from this issue.

**Comment by Fireclunge** [comment]
First of all, absolutely love the package, thanks for making something so magical @Pydantic crew.

This was doing my absolute head in as i'm working with some incredibly complex nested dataclasses, so you can do the following for a quick fix until it gets patched in:

---------------

Version: pydantic==1.6.1

**validators.py**
_Modify the error call for the validator you want to change so that is passes the value, v_

`raise errors.AnyStrMaxLengthError(limit_value=min_length)`

becomes...

`raise errors.AnyStrMaxLengthError(value=v, limit_value=min_length)`


**errors.py**
_Follow the function call and edit the __init__ function so it takes the value and adds it to the Super() init_

```
class AnyStrMaxLengthError(PydanticValueError):
    code = 'any_str.max_length'
    msg_template = 'ensure this value has at most {limit_value} characters'

    # def __init__(self, *, limit_value: int) -> None:
    #   super().__init__(limit_value=limit_value)

    def __init__(self, *, value, limit_value: int) -> None:
        super().__init__(value=value, limit_value=limit_value)
```

It should now show up inside the ctx value in e.errors()

{'ctx': {'value': 'abcdefghijklmnopqrs', 'limit_value': 15}  ヽ( ヅ )ノ

**Comment by JosXa** [comment]
@Fireclunge sounds like we got a PR on our hands 😜

**Comment by tek08** [comment]
Hallo.  If this is actually of interest to have in Pydantic, I'm (somewhat) happy to make the [PR](https://github.com/tek08/pydantic/pull/1).  Have one in progress.  Many unit tests to update.  Before I go on what could be a fool's errand and continue working on tweaking each and every unit test, would there be objection to surfacing more info in `ctx` for each `ValidationError`?

**Comment by johtso** [comment]
Just to check.. I'm currently struggling with the fact that I don't get a traceback to the offending line of code when there's an exception in custom validation, just the validation error that includes the original exception. Would this possibly help with that?

**Comment by tek08** [comment]
Nope -- My in-progress change's only delta is to include the offending value for ValidationErrors.

**Comment by amjltc295** [comment]
Look forward for this feature

**Comment by jdavidheiser** [comment]
The ability to capture the inputs in the context would be a killer feature for me.  It sounds like this is planned for version 2, but does anyone have a workaround to get that functionality with the current version?

**Comment by flikier** [comment]
+1, I agree it's needed.

We shall take into consideration that value could be very long, and could use some formating to avoid it ( for example `lambda value: str(value)[:20]`)

**Comment by thorin-schiffer** [comment]
Use this little utility to extract the value from a validation error:

```python
def value_from_validation_error(d: Dict, ex: ValidationError):
    values = {}
    for error in ex.errors():
        loc = error["loc"]
        value = d
        for field in loc:
            if field == "__root__":
                break
            value = value[field]
        values[".".join([str(location) for location in loc])] = value
    return values

```

**Comment by PushUpek** [comment]
No, we need context. What if the error is thrown by external library? I don't have anything to debug my problem. Ba, what if the library is do loop. How i can find the value that cause the error?

**Comment by dogweather** [comment]
> Use this little utility to extract the value from a validation error:
> 
> ```python
> def value_from_validation_error(d: Dict, ex: ValidationError):
>     values = {}
>     for error in ex.errors():
>         loc = error["loc"]
>         value = d
>         for field in loc:
>             if field == "__root__":
>                 break
>             value = value[field]
>         values[".".join([str(location) for location in loc])] = value
>     return values
> ```

Where do we get the `d: Dict` argument from?

**Comment by thorin-schiffer** [comment]
> @thorin-schiffer wrote:
> 
> > Use this little utility to extract the value from a validation error:
> > ```python
> > def value_from_validation_error(d: Dict, ex: ValidationError):
> >     values = {}
> >     for error in ex.errors():
> >         loc = error["loc"]
> >         value = d
> >         for field in loc:
> >             if field == "__root__":
> >                 break
> >             value = value[field]
> >         values[".".join([str(location) for location in loc])] = value
> >     return values
> > ```
> 
> Where do we get the `d: Dict` argument from?

it's the data you supply to the pydantic model

**Comment by markovevgeniy** [comment]
We really need to add this functionality in configuration of pydantic model

**Comment by adriangb** [comment]
As per https://github.com/pydantic/pydantic/issues/784#issuecomment-1136873433 this will be supported in V2 which will be released in the next couple of weeks. Closing this issue as completed 😄.

**Comment by sshishov** [comment]
If it is not difficult to backport or implement similar functionality in V1, it would be great to see it. I do not think that all the people will be able witthout problems move to V2 in short period of time. But having this issue is something frustrating...
