### ISSUE TITLE
Support `__doc__` argument in `create_model()`

### ISSUE THREAD

**Issue by psychedelicious** [pydantic/pydantic#7841]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When using `create_model()`, providing a `__doc__` argument results in warning. However the resultant model *does* have the docstring specified.

```py
from pydantic import create_model

Model = create_model('Model', __doc__="My docstring")
# > RuntimeWarning: fields may not start with an underscore, ignoring "__doc__"

print(Model().__doc__)
# > My docstring
```

Can we get "proper" support for `__doc__` as an argument?

Related: In `create_model()`, it appears the warning is issued but then it continues along and happily creates fields with names that start with underscores - the behaviour for `__doc__` is not unique.

Related issue: #7692

### Workaround

It's trivial to work around the warning:

```py
Model = create_model('Model')
Model.__doc__ = "My docstring"
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @psychedelicious,

Thanks for writing out this feature request. I think this is something that we'd certainly support 👍. If no one else gets to this within the week, I can open a PR adding support.
