### ISSUE TITLE
Warn about inheriting from Generic before BaseModel 

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/pydantic#7845]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Inheriting from `(Generic[T], BaseModel)` instead of `(BaseModel, Generic[T])` results in confusing behaviour, as seen in e.g. https://github.com/pydantic/pydantic/issues/7829. I also made this mistake recently and was confused for a bit, although I don't remember the exact context.

`ModelMetaclass.__new__` is still called either way, and there's already code in there that looks at whether `bases` contains `Generic`. It seems reasonable to log a warning (assuming that throwing an exception would be too disruptive) if the order looks wrong, at least sometimes. Is there any situation where putting `Generic` first is desirable?

### Example Code

```Python
from typing import Generic, TypeVar

from pydantic import BaseModel

T = TypeVar("T")


class M1(BaseModel, Generic[T]):
    x: T


class M2(Generic[T], BaseModel):
    x: T


for M in [M1, M2]:
    print(M[int])
    print(type(M[int]))
    print(type(M[int](x=1)))
    print()

"""
<class '__main__.M1[int]'>
<class 'pydantic._internal._model_construction.ModelMetaclass'>
<class '__main__.M1[int]'>

__main__.M2[int]
<class 'typing._GenericAlias'>
<class '__main__.M2'>
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/alex/work/pydantic/pydantic
               python version: 3.11.5 (main, Sep  9 2023, 21:35:25) [GCC 7.5.0]
                     platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.7.1 email-validator-2.0.0.post2 mypy-1.1.1 pydantic-extra-types-2.1.0 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
Hi @alexmojaki,

Thanks for reporting this. I would agree - a warning could be helpful. I think a docs update would help many people as well.

**Comment by alexmojaki** [comment]
I'll take a look.

**Comment by alexmojaki** [comment]
Found some more cases where the wrong order caused bugs and this warning would have helped:

- https://github.com/pydantic/pydantic/issues/7236
- https://github.com/pydantic/pydantic/issues/7006

But then I found https://github.com/pydantic/pydantic/issues/6994 which suggests that it *might* sometimes be justified to use that order, waiting for confirmation.
