### ISSUE TITLE
model_dump ignores sub class attributes

### ISSUE THREAD

**Issue by SergeyHein** [pydantic/pydantic#7849]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

model_dump ignores sub class attributes. Consider a minimalistic code below.

Generared Output: {'item': {'key': '1'}}
Expected Output : {'item': {'key': '1', 'model': 'VW'}}

![image](https://github.com/pydantic/pydantic/assets/6217324/07ce251e-0e9b-4d84-8391-808e10b2039c)

### Example Code

```Python
from pydantic import BaseModel, version
from sys import version_info

print(version_info)
print(version.version_info())

class ItemBase(BaseModel):
    key : str
class ItemCar(ItemBase):
    model : str    

class ItemHolder(BaseModel):
    item : ItemBase

h =     ItemHolder(item = ItemCar(key = "1", model = "VW"))
h.model_dump()
```

### Python, Pydantic & OS Version

```Text
sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: xxxxx py3.8\Lib\site-packages\pydantic
               python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: mypy-1.6.0 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @SergeyHein,

Thanks for reporting this. This is the expected behavior. You can check out [this section](https://docs.pydantic.dev/latest/concepts/serialization/#serializing-with-duck-typing) of the docs to learn more about serialization with duck typing, which is the behavior I think you're looking for.

Here's an example of how you could get the results you're looking for using `SerializeAsAny`:
```py
from pydantic import BaseModel, SerializeAsAny


class User(BaseModel):
    name: str


class UserLogin(User):
    password: str


class OuterModel(BaseModel):
    as_any: SerializeAsAny[User]
    as_user: User


user = UserLogin(name='pydantic', password='password')

print(OuterModel(as_any=user, as_user=user).model_dump())
"""
{
    'as_any': {'name': 'pydantic', 'password': 'password'},
    'as_user': {'name': 'pydantic'},
}
"""

```

**Comment by sydney-runkle** [comment]
@SergeyHein,

Sure thing! Glad I could be of help 😄
