### ISSUE TITLE
UPdate to pydantic 2.4.2 makes fastAPI docs fail

### ISSUE THREAD

**Issue by atompie** [pydantic/pydantic#7856]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm currently facing an issue that affects both documentation and Pydantic models, and I'm uncertain which part of the project is responsible for it.

Upon upgrading from Pydantic version 2.3.0 to 2.4.0, I observed that endpoints using `arbitrary_types` in the documentation were causing errors and not rendering correctly. Downgrading to 2.3.0 solved the issue.

This issue is particularly noticeable in the `BaseModel` example provided below:

```python
class FlowGraph(BaseModel):
    description: Optional[str] = None
    response: Optional[FlowResponse] = FlowResponse()
    model_config = ConfigDict(arbitrary_types_allowed=True)
```

The `FlowResponse` class is defined as follows:

```python
class FlowResponse(Dict[str, dict]):

    def __init__(self, *args, **kwargs):
        dict.__init__(self, *args, **kwargs)

    def __setitem__(self, key, value: dict):
        if not isinstance value, dict:
            raise ValueError("FlowResponse only accepts dict objects as values.")

        dict.__setitem__(self, key, value)
```

When I use this as a parameter in any endpoint, I encounter a red alert indicating that `openapi.json` cannot be created.

Here are the versions of the installed packages:

- `pydantic` 2.4.2
- `pydantic_core` 2.10.1
- `pydantic-extra-types` 2.1.0
- `pydantic-settings` 2.0.3
- `fastapi` 0.103.2"

### Example Code

```Python
from typing import Optional, Dict
from fastapi import FastAPI
from pydantic import BaseModel
from pydantic import ConfigDict


class FlowResponse(Dict[str, dict]):

    def __init__(self, *args, **kwargs):
        dict.__init__(self, *args, **kwargs)

    def __setitem__(self, key, value: dict):
        raise ValueError("FlowResponse only accepts dict objects as values.")


class FlowGraph(BaseModel):
    id: Optional[str] = None
    response: Optional[FlowResponse] = FlowResponse()

    model_config = ConfigDict(arbitrary_types_allowed=True)


app = FastAPI()


@app.get("/")
async def root(flow: FlowGraph):
    return {"message": "Hello World"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("app.main:app", host="0.0.0.0", port=8181, log_level='info', workers=1)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/risto/PycharmProject/pythonProject/testErrorKasuj/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.4.0-164-generic-x86_64-with-glibc2.31
             related packages: fastapi-0.103.2 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
@Kludex, could you take a look at this issue when you have a chance? Thanks!

**Comment by Kludex** [comment]
I think this should be on FastAPI.

```bash
    raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'main.FlowResponse'>)
```

**Comment by sydney-runkle** [comment]
@atompie,

> I think this should be on FastAPI.

Closing this for now given @Kludex's above comments. Happy to reopen if it's determined that this is on `pydantic` to fix. Thanks again for reporting this issue!
