### ISSUE TITLE
Doc: One example of `'class-not-fully-defined'` doesn't seem to raise the correct exception

### ISSUE THREAD

**Issue by rahmatnazali** [pydantic/pydantic#7869]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Referring to this particular section of the documentation on [Class not fully defined](https://github.com/pydantic/pydantic/blob/main/docs/errors/usage_errors.md#:~:text=Or%20when%20the%20type%20has%20been%20defined%20after%20usage%3A), from what I can understand, the supplied example code should deliberately raise a `PydanticUserError` exception, in which the code would then explicitly assert that the exception `code` should equal `'class-not-fully-defined'`.

However, running the example code  both on my machine and on the in-browser feature of the documentation site doesn't seem to raise the exception.

As far as my knowledge goes with how pydantic works, the way how the `Foo` and `Bar` classes being declared here seem to be fine, which probably results in no exception being raised at all. If this is true, then I think the example code needs to be updated.

I probably should fire a PR instead, but I may be the one that doesn't get the docs, so let me put this as an issue for now.

### Example Code

```Python
from typing import Optional

from pydantic import BaseModel, PydanticUserError


class Foo(BaseModel):
    a: Optional['Bar'] = None


class Bar(BaseModel):
    b: 'Foo'


try:
    foo = Foo(a={'b': {'a': None}})
except PydanticUserError as exc_info:
    assert exc_info.code == 'class-not-fully-defined'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/rahmat/PycharmProjects/pydantic/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0]
                     platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.29
             related packages: typing_extensions-4.8.0 email-validator-2.0.0.post2
```

**Comment by hramezani** [comment]
Thanks @rahmatnazali for reporting this. Yes, you are right.
Please create a PR and update the example code.

**Comment by sydney-runkle** [comment]
I'd be happy to push a fix for this today. @rahmatnazali, Thanks for reporting this!
