### ISSUE TITLE
`-` is parsed as a valid date

### ISSUE THREAD

**Issue by Harry-Lees** [pydantic/pydantic#7872]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A single `-` is parsed as a valid datetime, it produces 0 UNIX time. From looking at the documentation, I couldn't see anything that indicates `-` should be a valid datetime, since `-` doesn't parse as a valid float or integer either.

In my example below, I used `datetime.date`, but this also happens when using `datetime.datetime`.

### Example Code

```Python
>>> from datetime import date
>>> from pydantic import BaseModel
>>> class Foo(BaseModel):
...     bar: date
...
>>> Foo.model_validate({"bar": "-"})
Foo(bar=datetime.date(1970, 1, 1))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: /Users/harrylees/Documents/test/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.5-arm64-arm-64bit
     optional deps. installed: ['email-validator', 'typing-extensions']
```

**Comment by hramezani** [comment]
Thanks @Harry-Lees for reporting this.

`pydantic-core` uses [speedate](https://github.com/pydantic/speedate) for parsing data and datetime.
I am not sure whether it is a bug or intended behavior.
@samuelcolvin any idea?

**Comment by samuelcolvin** [comment]
Thanks for reporting.

Looks like a bug in speedate, I think speedate should probably use `lexical-core` to parse timestamps using JSON semantics.
