### ISSUE TITLE
Getting `unsupported operand type(s) for |: 'PydanticRecursiveRef' and 'NoneType'` with PEP 604 formatting and recursive classes

### ISSUE THREAD

**Issue by pengelsman7** [pydantic/pydantic#7875]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We recently started using pyupgrade for formatting in a repo with complex pydantic models to switch from `Optional[type]` to `type | None` but one of our models now throws an error at runtime. The strange thing about this is, in the example code, if the typing in `Foo` for `bar`, `bar: Bar[Baz] | None = None`, is changed to use `Union` like `bar: Union[Bar[Baz], None] = None` the code no longer throws an error. So I think there is likely a bug in how Union vs UnionType is handled in recursive references.

### Example Code

```Python
from __future__ import annotations

from pydantic import BaseModel
from typing import TypeVar, Generic


class Foo(BaseModel):
    id: int
    bar: Bar[Baz] | None = None

_T = TypeVar("_T")

class Bar(BaseModel, Generic[_T]):
    name: str
    parent: Foo | None = None

class Baz(BaseModel):
    name: str | None

Foo.model_rebuild()
Bar.model_rebuild()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /fn/lib/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Oct 16 2023, 01:57:50) [GCC 10.2.1 20210110]
                     platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.31
             related packages: typing_extensions-4.8.0 mypy-1.6.0
```

**Comment by alexmojaki** [comment]
Here's a fix that you can patch in right away:

```python
from pydantic._internal._forward_ref import PydanticRecursiveRef
from typing import Union


def __or__(self, other):
    return Union[self, other]


PydanticRecursiveRef.__or__ = __or__
```

**Comment by sydney-runkle** [comment]
@pengelsman7,

Thanks for reporting this. This does seem like a bug, and might be related somewhat to #7873.

**Comment by pengelsman7** [comment]
Thank you for the quick response! I'll give the patch a try while we wait for the new version.
