### ISSUE TITLE
Stream parser against JSON schema

### ISSUE THREAD

**Issue by wellhowtosay** [pydantic/pydantic#7879]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

LLM plugin Frameworks like Langchain require model to genearte a function call which is basically a json string, include fields like function_name, params, so that LLMs can extent their abilities to real world applications. However, LLMs generate the json string without any constraint related to the json schema of function definition, which cases some challenges to this LLM plugin idea. for example , LLMs may call a function that doesn't exist !
Projects like [clownfish](https://github.com/newhouseb/clownfish#hallucinating-the-code-you-want-to-see-in-the-world) provides a stream json parser which can constrain LLMs to follow given JSON schema during generating the JSON string. However this project only supports very few features in pydantic and I deeply doubt it's perfermance. And I do believe you are  the best to provide with this feature! I do believe this can be a great contribution to LLM community.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@samuelcolvin has implemented this in `pydantic-core`, and this should be released with 2.7, our upcoming minor release 🚀. Thus, marking this as closed :).

**Comment by samuelcolvin** [comment]
I think this is fixed in https://github.com/pydantic/pydantic-core/pull/1240 - once we've done a pydantic-core release, you'll be able to do

```py
import pydantic_core

print(pydantic_core.from_json('{"a": 1, "b": 2, "c', allow_partial=True))
#> {'a': 1, 'b': 2}
```

**Comment by wellhowtosay** [comment]
thanks you gays are amazing !
