### ISSUE TITLE
Get all audio from saved audios

### ISSUE THREAD

**Issue by vsharm29** [pydantic/pydantic#7887]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

People usually use Instagram from mobile. whenever I like an audio I mark it as save.

To fully automate the reel uploading feature with audio. There should be a function to get all saved audio. This will help the automation expert to randomly select the audio using code and upload the reel accordingly as per schedule. 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @vsharm29,

Thanks for your post. Perhaps I'm misunderstanding, but I don't think this feature request is relevant to `pydantic`. If you think it is, please elaborate more so we can help!

**Comment by sydney-runkle** [comment]
Closing for now - I don't think this feature request is relevant to `pydantic`. Happy to reopen if anyone knows otherwise.
