### ISSUE TITLE
SDXL automatic1111 cant use V2

### ISSUE THREAD

**Issue by DennisBalkan** [pydantic/pydantic#7901]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

(venv) C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>pip install pydantic==2.4.2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==2.4.2
  Downloading pydantic-2.4.2-py3-none-any.whl.metadata (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.6/158.6 kB 1.3 MB/s eta 0:00:00
Collecting annotated-types>=0.4.0 (from pydantic==2.4.2)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.10.1 (from pydantic==2.4.2)
  Downloading pydantic_core-2.10.1-cp310-none-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\ai\sdxlbeta\stable-diffusion-webui\venv\lib\site-packages (from pydantic==2.4.2) (4.8.0)
Downloading pydantic-2.4.2-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.8/395.8 kB 3.1 MB/s eta 0:00:00
Downloading pydantic_core-2.10.1-cp310-none-win_amd64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 6.0 MB/s eta 0:00:00
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Installing collected packages: pydantic-core, annotated-types, pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.13
    Uninstalling pydantic-1.10.13:
      Successfully uninstalled pydantic-1.10.13
Successfully installed annotated-types-0.6.0 pydantic-2.4.2 pydantic-core-2.10.1

(venv) C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>deactivate
C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>activate

(venv) C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>pip install pydantic==1.10.13
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==1.10.13
  Downloading pydantic-1.10.13-cp310-cp310-win_amd64.whl.metadata (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.9/150.9 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.2.0 in c:\ai\sdxlbeta\stable-diffusion-webui\venv\lib\site-packages (from pydantic==1.10.13) (4.8.0)
Downloading pydantic-1.10.13-cp310-cp310-win_amd64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.0 MB/s eta 0:00:00
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.4.2
    Uninstalling pydantic-2.4.2:
      Successfully uninstalled pydantic-2.4.2
Successfully installed pydantic-1.10.13

### Example Code

```Python
(venv) C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>pip install pydantic==2.4.2
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==2.4.2
  Downloading pydantic-2.4.2-py3-none-any.whl.metadata (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.6/158.6 kB 1.3 MB/s eta 0:00:00
Collecting annotated-types>=0.4.0 (from pydantic==2.4.2)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.10.1 (from pydantic==2.4.2)
  Downloading pydantic_core-2.10.1-cp310-none-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\ai\sdxlbeta\stable-diffusion-webui\venv\lib\site-packages (from pydantic==2.4.2) (4.8.0)
Downloading pydantic-2.4.2-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.8/395.8 kB 3.1 MB/s eta 0:00:00
Downloading pydantic_core-2.10.1-cp310-none-win_amd64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 6.0 MB/s eta 0:00:00
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Installing collected packages: pydantic-core, annotated-types, pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.13
    Uninstalling pydantic-1.10.13:
      Successfully uninstalled pydantic-1.10.13
Successfully installed annotated-types-0.6.0 pydantic-2.4.2 pydantic-core-2.10.1

(venv) C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>deactivate
C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>activate

(venv) C:\AI\SDXLbeta\stable-diffusion-webui\venv\Scripts>pip install pydantic==1.10.13
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting pydantic==1.10.13
  Downloading pydantic-1.10.13-cp310-cp310-win_amd64.whl.metadata (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.9/150.9 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.2.0 in c:\ai\sdxlbeta\stable-diffusion-webui\venv\lib\site-packages (from pydantic==1.10.13) (4.8.0)
Downloading pydantic-1.10.13-cp310-cp310-win_amd64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.0 MB/s eta 0:00:00
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.4.2
    Uninstalling pydantic-2.4.2:
      Successfully uninstalled pydantic-2.4.2
Successfully installed pydantic-1.10.13
```

### Python, Pydantic & OS Version

```Text
after crush revet back to v1
```

**Comment by sydney-runkle** [comment]
Hi @DennisBalkan,

Could you provide information as to what error you experienced that caused the crash? If you can provide more detailed error information or some sort of MRE, we'd be happy to help.
