### ISSUE TITLE
Serialization Warning when using self referencing model and union

### ISSUE THREAD

**Issue by gmetzker** [pydantic/pydantic#7905]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I get the following error when serializing some models:
```
UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], list[definition-ref]]` but got `list` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

After some experimentation I have the following example that is close enough to my real code to generate the same warning.

**Note**:  that sometimes `items` will be a list of `Foo` and other times they might be any class derived from `Bar` (preferably serializing as the child type of `Bar` rather than only dumping `Bar` fields)

## Primary Example

```python
from typing import Union
from pydantic import BaseModel

class Bar(BaseModel):
    bar_id: int

class Baz(Bar):
    baz_id: int

class Foo(BaseModel):
    name: str
    items: Union[list[Foo], list[Bar]]

foo = Foo(name="foo", items=[Baz(bar_id=42, baz_id=99)])

print(f"dumped={foo.model_dump()})

```
Output
```
UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], list[definition-ref]]` but got `list` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
dumped: {'name': 'foo', 'items': [{'bar_id': 42, 'baz_id': 99}]}
```

It appears to serialize correctly.  

The error seems to be related to either the self referencing `Foo` in `items`, or using the child class instead of the parent class in `items`.

The two tweaks below might add better context as to what is causing the issue, but I actually need something closer to the **Primary Example**.  

## Tweak1
If I use only `Bar` items in the list the error goes away (but usually I need the child type `Baz` in the list)
```python
class Bar(BaseModel):
    bar_id: int

class Baz(Bar):
    baz_id: int

class Foo(BaseModel):
    name: str
    items: Union[list[Foo], list[Bar]]

foo = Foo(name="foo", items=[Bar(bar_id=42)])

print(f"dumped={foo.model_dump()})

```

Output
```
dumped: {'name': 'foo', 'items': [{'bar_id': 42}]}
````

## Tweak2

Or if I drop the self reference Foo->items(Foo) I don't get the warning, but `items` will no longer serialize as their child types `Baz`, but only serialize as the parent type `Bar`
```python

class Bar(BaseModel):
    bar_id: int

class Baz(Bar):
    baz_id: int

class Foo(BaseModel):
    name: str
    items: list[Bar]

foo = Foo(name="foo", items=[Baz(bar_id=42, baz_id=99)])

print(f"dumped={foo.model_dump()})
```

Output:
```
dumped: {'name': 'foo', 'items': [{'bar_id': 42}]}
````

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/gary.metzker/Library/Caches/pypoetry/virtualenvs/foresee-rules-engine-8hxqKW_T-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.13 (main, Jun 28 2022, 15:40:31)  [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.7-arm64-arm-64bit
             related packages: typing_extensions-4.7.1
```

**Comment by sydney-runkle** [comment]
Hi @gmetzker,

Thanks so much for reporting this. This is indeed a bug - `pydantic-core` has some issues right now with serializing `Union` types (and selecting the right type within a `Union` to use for serialization). The specificity of your examples is great - we can use all of them as tests when we make this bug fix.

Given the number of reports of this bug, I'll prioritize working on this fix. 👍

**Comment by sydney-runkle** [comment]
Hi @gmetzker,

One solution that you can use for this currently is using a `SerializeAsAny` wrapper around the `items` annotation. Ex:

```py
from typing import Union
from pydantic import BaseModel, SerializeAsAny

class Bar(BaseModel):
    bar_id: int

class Baz(Bar):
    baz_id: int

class Foo(BaseModel):
    name: str
    items: SerializeAsAny[Union[list[Foo], list[Bar]]]

foo = Foo(name="foo", items=[Baz(bar_id=42, baz_id=99)])

print(f"dumped={foo.model_dump()})
```

I'm still looking into how we might change this behavior in `pydantic-core`, but that should work for now as a bandaid.

**Comment by gmetzker** [comment]
@sydney-runkle the `SerializeAsAny` worked!  And it removed the warning  The one thing I would like to point out, and I missed this in the documentation:  **the serialization behavior of child classes in V2 does not work the same as v1.**  

For reference this is spelled out in the [v2 documentation here](https://docs.pydantic.dev/latest/concepts/serialization/#subclass-instances-for-fields-of-basemodel-dataclasses-typeddict) 

> The default behavior is to serialize the attribute value as though it was an instance of the annotated type, even if it is a subclass. More specifically, only the fields from the annotated type will be included in the dumped object

My confusion was, in my particular scenario it actually was serializing the child class attributes.  This is what I needed but apparently not how V2 was designed. 

@sydney-runkle I saw your PR and tests, which I suppose will further restrict the serialization of the child fields.  When the new pydantic-core is baked in can I assume `SerializeAsAny` will continue to work in my case?  Might be worth an extra test case.

Thanks again I appreciate the help 👍

**Comment by Elastica534** [comment]
@gmetzker https://pythoner.space/questions/what-is-the-best-way-to-find-the-nearest-datetime-object-within-a-list
