### ISSUE TITLE
Signature of inherited dataclass does not include subclass field

### ISSUE THREAD

**Issue by shinaji** [pydantic/pydantic#7906]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, I found that the signature of inherited dataclass seems to have only its superclass fields.  Is this expected behavior at pydantic v2?  Due to this, FastAPI seems to ignore the subclass field value.

### Example Code

```Python
from pydantic.dataclasses import dataclass

@dataclass
class A:
    a: int

@dataclass
class B(A):
    b: int

# In [4]: B.__signature__
# Out[4]: <Signature (a: int) -> None>  # "b: int" is missing
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
               python version: 3.9.13 (main, Sep 17 2022, 22:53:18)  [Clang 14.0.0 (clang-1400.0.29.102)]
                     platform: macOS-13.6-arm64-arm-64bit
             related packages: email-validator-2.0.0.post2 pydantic-extra-types-2.1.0 mypy-1.3.0 typing_extensions-4.8.0 fastapi-0.104.0 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
Hi @shinaji,

Thanks for reporting this. Looks like a bug with the pydantic dataclass signature generation. I've marked this with the `good first issue` tag, if anyone wants to help!

**Comment by sydney-runkle** [comment]
This should be helpful:

https://github.com/pydantic/pydantic/blob/f645f196b063843865b34bd696e4b85bae9c034c/pydantic/_internal/_dataclasses.py#L188-L193

**Comment by howsunjow** [comment]
@sydney-runkle I've contributed a fix in a PR. Not sure how exactly to assign a reviewer though.

**Comment by sydney-runkle** [comment]
@howsunjow awesome, thanks! I just submitted a review. Thanks for your contribution 👍 ⭐
