### ISSUE TITLE
Use ruff for formatting

### ISSUE THREAD

**Issue by Luca-Blight** [pydantic/pydantic#7914]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Can I implement this upgrade in the CI? What package is currently being used?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Luca-Blight** [comment]
More on the tool: https://astral.sh/ruff

FASTAPI implemented it in their codebase today. It uses Rust for performance gains.

**Comment by sydney-runkle** [comment]
Hi @Luca-Blight,

Thanks for your inquiry! We use `black` and `ruff` already - see this section of our [contributing docs](https://docs.pydantic.dev/latest/contributing/#check-out-a-new-branch-and-make-your-changes).

Thanks for the proposal though, `ruff` is great 😄. We very much enjoy using it.

**Comment by PrettyWood** [comment]
@sydney-runkle I think @Luca-Blight meant to use ruff instead of black since it [is now able to format](https://astral.sh/blog/the-ruff-formatter)
FastAPI [already made the move](https://github.com/tiangolo/fastapi/pull/10517)

**Comment by samuelcolvin** [comment]
Happy to switch to just ruff, PR welcome.

**Comment by Luca-Blight** [comment]
Excellent,  I'll create PR for it today.
