### ISSUE TITLE
Please make v2 compatible with v1 （langchain use v1, while fastapi use v2）

### ISSUE THREAD

**Issue by mokeyish** [pydantic/pydantic#7919]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Please make v2 compatible with v1 （langchain use v1, while fastapi use v2）. they can't work together.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/www/.conda/envs/tmpenv/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0]
                     platform: Linux-5.10.0-26-amd64-x86_64-with-glibc2.31
             related packages: typing_extensions-4.8.0 fastapi-0.103.1
```

**Comment by Luca-Blight** [comment]
Seems like the onus is on langchain.

**Comment by sydney-runkle** [comment]
Hi @mokeyish,

Thanks for submitting this issue. I agree with @Luca-Blight, this is simply a case of conflicting dependencies. You could use an earlier version of `fastapi` that uses `pydantic` V1 until `langchain` upgrades to supporting v2.

Any `fastapi` versions before `0.100.0` should use V1.

**Comment by mokeyish** [comment]
I found that it also not compatiable with deepspeed. Each library has its own dependencies, and many of them now conflict with each other.

**Comment by sydney-runkle** [comment]
@mokeyish,

You can use different versions of each library to make sure the versions are compatible. The burden of resolving version conflicts isn't on `pydantic`, here.

**Comment by mokeyish** [comment]
Currently, fastapi/lmdeploy use v2, langchain/deepspeed use v1. 

Don’t learn from Google, learn from Facebook. As I known, Google has two incompatible upgraded products, angular(v1->v2) and tensorflow(v1->v2). Facebook's react and pytorch have always been very compatible, even from pytorch v1 to v2.

`pydantic` is not an app and you can freely choose dependent versions. `pydantic` is a library that is used by many downstream libraries, some use v2, and some are still using v1. Incompatible upgrades will cause many problems.

**Comment by mokeyish** [comment]
I'm not the only one having this problem. 

https://github.com/tiangolo/fastapi/issues/10360

https://github.com/langchain-ai/langserve/pull/10
