### ISSUE TITLE
Types are not JSON serializable

### ISSUE THREAD

**Issue by bluenote10** [pydantic/pydantic#7921]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The documentation on [`typing.Type`](https://docs.pydantic.dev/latest/api/standard_library_types/#typingtype) suggest that storing types / class references is supported.

However, trying to serialize that example to JSON currently fails. Depending on the type the error is either:
- `Unable to serialize unknown type: <class 'type'>`
- `Error serializing to JSON: TypeError: 'mappingproxy' object cannot be converted to 'PyDict'`

After reading the documentation my assumption was that the serialization stores a fully qualified name of the class, and the deserialization tries to import/load the class from that package/module.

If not supporting type serialization is by design, it would be nice to extend the documentation in a way to clarify that `typing.Type` is only partly supported, e.g. saying that it can be stored in a model, but not serialized in general.

### Example Code

```Python
from pydantic import BaseModel

# Example 1 (failing with: Unable to serialize unknown type: <class 'type'>)

class Foo:
    ...

class Example1(BaseModel):
    some_foo_subclass: type[Foo]

Example1(some_foo_subclass=Foo).model_dump_json()

# Example 2 (failing with: Error serializing to JSON: TypeError: 'mappingproxy' object cannot be converted to 'PyDict')

class Example2(BaseModel):
    some_basemodel_subclass: type[BaseModel]

class SomeBaseModel(BaseModel):
    ...

Example2(some_basemodel_subclass=SomeBaseModel).model_dump_json()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /path/to/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
                     platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
             related packages: mypy-1.6.1 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @bluenote10,

Thanks for reporting this. I think that supporting json serialization for type `Type` fields is a bit of a can of worms. That being said, I think we could raise a more clear / helpful error when a user attempts this.

That being said, I do think a documentation update is merited here.

Additionally, I noticed that using `model_dump` on an instance of a `BaseModel` class with a `Type[BaseModel]` fails with 
```
TypeError: 'mappingproxy' object cannot be converted to 'PyDict'
```

Which I do think is a bug that we should fix.

Thanks again for the report. Do you have any interest in helping with this fix? I'd be more than happy to review a PR 😄.

**Comment by ldacey** [comment]
Hi - do you think this is related?

If I install pydantic 2.4 then I can no longer use model_json_schema() due to the polars and pyarrow types causing serialization issues:

```python
    signature_type: str = Field(
        json_schema_extra={
            "polars_type": pl.Categorical,
            "pyarrow_type": pa.dictionary(pa.int8(), pa.string()),
            "original_names": ["SIGNATURE TYPE", "SIGNATURE_TYPE"],
        }
```

If I downgrade to 2.3.0, it works again. I have a large set of these models which are used to map the dataset schemas and provide OpenLineage metadata

**Comment by ldacey** [comment]
I wanted to follow up on this. Is there a recommended way to define custom attributes such as the polars_type and pyarrow_type below?

```python
    lead_id: str | None = Field(
        validation_alias=AliasChoices("Lead_Id", "LEAD_ID"),
        json_schema_extra={"polars_type": pl.Utf8, "pyarrow_type": pa.string()},
    )
```

If I use `list(cls.model_json_schema(by_alias=False)["required"])` I run into this error:

 │     pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'polars.datatypes.classes.DataTypeClass'>  [106, 1]

**Comment by aknopper** [comment]
+1 on the `Error serializing to JSON: TypeError: 'mappingproxy' object cannot be converted to 'PyDict'` issue. 

```
File "relocations.py, line 593, in _trust_to_non_enet
    l3_sw_obj = current_site.wan_switch.model_dump(
  File ".venv/lib/python3.10/site-packages/pydantic/main.py", line 314, in model_dump
    return self.__pydantic_serializer__.to_python(
TypeError: 'mappingproxy' object cannot be converted to 'PyDict'
```

Function:
```
l3_sw_obj = current_site.wan_switch.model_dump(
            exclude={
                "wan_interfaces": True,
                "tunnels": True,
                "mgmt_interfaces": True,
                "routing": True,
                "global_config": {"netflow"},
            }
        )
``` 
where `wan_switch` is another model.
```
class WANSwitch(BaseModel):
    hostname: str
    model: str
    os: str
    system_image: str
    vendor: VENDOR
    mgmt: ipaddress.IPv4Address
    global_config: GlobalConfig
    security: Optional[Security] = None
    role: str
    date_created: str
    global_config: WANGlobalConfig
    ports: Optional[int]
    stack_num: Optional[int]
    wan_interfaces: dict[str, Interface]
    svis: dict[str, Interface]
    tunnels: Optional[list] = None
    mgmt_interfaces: list[Loopback]
    vlans: list[int]
    routing: Routing
    role: str = "wan"
 
    class Config:
        use_enum_values = True
```
