### ISSUE TITLE
No conversion of default enum when use_enum_values is true

### ISSUE THREAD

**Issue by primalmachina** [pydantic/pydantic#7937]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Case 1 (my case) - Setting a value as default enum.
```
from enum import Enum
from pydantic import BaseModel, ConfigDict

class MyEnum(Enum):
    A = 1
    B = 2

class Foo(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    enum: MyEnum = MyEnum.A

foo = Foo()

print(foo)
```
Outputs
```
enum=<MyEnum.A: 1>
```

Case 2 - No default value, use_enum_values = True works fine.
```
class Foo(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    enum: MyEnum

foo = Foo(enum=MyEnum.A)

print(foo)
```
Outputs
```
enum=1
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/bonaparte/miniconda3/envs/lucca-api/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
                     platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hey @primalmachina,

Thanks for your question. We recently added an update to the docs re this behavior, as it has confused a few people in the past. You can read more about that [here](https://docs.pydantic.dev/dev/api/config/#pydantic.config.ConfigDict.use_enum_values). The behavior has been reported before in #7791 and #7757.

I can see an argument for changing this behavior in the future, but right now, this behavior is expected 👍.

Feel free to let me know if you have any other questions. Happy to help!
