### ISSUE TITLE
Optional[date] behaviour is weird

### ISSUE THREAD

**Issue by saber-solooki** [pydantic/pydantic#7945]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm reporting this issue on V2 but I see weird behavior also in v1
I'll make different examples to explain it clearly.
The problem is: How can I define a non-required optional date field in my model? (I made an equivalent example for int and it works)
In theory, this can be achieved like this:
```
class LegitimateDateModel(BaseModel):
    date: Optional[date] = None
```
But I get a Validation error when I pass a value to the model

### Example Code

```Python
from datetime import date
from typing import Optional

from pydantic import BaseModel

class LegitimateDateModel(BaseModel):
    date: Optional[date] = None

class LegitimateIntModel(BaseModel):
    x: Optional[int] = None

class LegitimateDateNotRequiredModel(BaseModel):
    x: Optional[int]

LegitimateDateModel(date=date(2020, 1, 1))  # ValidationError: Input should be None. I got same error in v1 as-well
LegitimateDateModel()  # date is None and everything is OK
LegitimateIntModel(x=1)  # x = 1. Everything is OK
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/sabersolooki/.pyenv/versions/3.11.4/envs/pydanticplay-v2/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 16:51:49) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-12.4-x86_64-i386-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @saber-solooki,

Thanks for reporting this. The problem here is that your field `date` is named the same as the type `date`. You can fix this with the following change, or some similar modification:

```py
from datetime import date
from typing import Optional

from pydantic import BaseModel

class LegitimateDateModel(BaseModel):
    date_: Optional[date] = None
```

or
```py
from datetime import date as date_
from typing import Optional

from pydantic import BaseModel

class LegitimateDateModel(BaseModel):
    date: Optional[date_] = None
```

**Comment by saber-solooki** [comment]
@sydney-runkle Thanks it works. I thought it might be a bug since it is working in v1

**Comment by KabirZFW** [comment]
from datetime import datetime
from typing import Optional

class MyModel(BaseModel)
    issue_date = Optional[datetime]
    

Above code in v2 raises error :
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `issue_date = typing.Optional[datetime.datetime]`. All model fields require a type annotation; if `issue_date` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
