### ISSUE TITLE
Remove the `__pydantic_self__` edge case in model constructor

### ISSUE THREAD

**Issue by ariebovenberg** [pydantic/pydantic#7948]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The first argument of the `BaseModel` signature is `__pydantic_self__`, to ensure a key named `self` can exist. While `__pydantic_self__` is of course unlikely to occur in the wild, it nonetheless is a gap in the logic of "extra keys will be discarded".

```python
from pydantic import BaseModel

class Foo(BaseModel):
    a: int = 0

Foo(**{"arbitrary string": 4})   # ✅ passes, extra key is discarded
Foo(**{"a": "invalid data"})     # ✅ ValidationError
Foo(**{"__pydantic_self__": 4})  # 🧨 TypeError
```

An additional problem is that this raises `TypeError`, instead of `ValidationError` which you might expect. The result: parsing arbitrary JSON can result in unexpected exceptions, which could crash your app.

The fix is really straightforward:

```python
# instead of...
def __init__(__pydantic_self__, **data): ...

# ...do this:
def __init__(*args, **data):
    __pydantic_self__ = args[0]  # raise exception if more than one
```

Of course, I'm more than happy to submit a PR if you agree 🙂 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @ariebovenberg,

Thanks for submitting this feature request 🙏. At a first glance this seems like an ok change to me, but there might be something I'm missing. I'll get back to you first thing on Monday once I can take a bit of a closer look 👍

**Comment by ariebovenberg** [comment]
One wrinkle I could think of: in the naive solution, a typechecker wouldn't flag positional arguments anymore:

```python
MyModel(arg1, foo=4)
#       ^^^^-----raises TypeError yes, but should *also* be flagged by typechecker
```

However, this can be fixed with something like this:

```python
if TYPE_CHECKING:
    def __init__(self, **data: Any) -> None: ...
else:
    def __init__(*args, **data) -> None:
         ...  # actual constructor implementation
```

since the existing constructor already has `type: ignore`, this won't result in less typechecking 'coverage'.

**Comment by samuelcolvin** [comment]
Better solution, wait until we drop 3.7, probably next few weeks, then use

```py
def __init__(self, /, **data: Any) -> None:
    ...
```

**Comment by ariebovenberg** [comment]
If dropping 3.7 is on the table — it doesn't get any better than that ☝️

**Comment by ariebovenberg** [comment]
@sydney-runkle will dropping 3.7 make it into the next release?

In any case, I'd be happy to submit a PR once 3.7 is dropped.

**Comment by sydney-runkle** [comment]
@ariebovenberg, it won't be dropped for 2.5.0, but it should be for 2.6.0. Feel free to submit a PR :). I think we have a PR up for dropping 3.7 support that I can work on next week (once we get 2.5.0 out).

**Comment by ariebovenberg** [comment]
PR created. I'm still leaving it in draft until I can rebase it on a 3.8+ main branch. Feel free to have a look of course.
