### ISSUE TITLE
Functional Validators break model_json_schema()

### ISSUE THREAD

**Issue by decision-dev** [pydantic/pydantic#7957]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

V2's Functional Validators are fantastic!  We are using them to associate validation with many basic types which are then reused broadly across many different BaseModel subclasses. 

However, this appears to break model_json_schema():

File "/lib/python3.11/site-packages/pydantic/json_schema.py", line 2069, in handle_invalid_for_json_schema raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.PlainValidatorFunctionSchema ({'type': 'no-info', 'function':  at 0x1145948>})

Is there additional information that we should include in our Annotated types so model_json_schema knows to treat them as the underlying type?

### Example Code

```Python
from typing_extensions import Annotated

from pydantic import BaseModel, PlainValidator

MyInt = Annotated[int, PlainValidator(lambda v: int(v) + 1)]

class Model(BaseModel):
    a: MyInt

print(Model(a='1').a)
print(Model(a='1').model_json_schema())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=true
install path: /home/dev/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic
python version: 3.11.5 (main, Sep  9 2023, 14:29:23) [GCC 10.2.1 20210110]
platform: Linux-6.1.42+-x86_64-with-glibc2.31
related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
@decision-dev,

Thanks for reporting this. This definitely looks like a bug 🐛 . I'll look into this!

**Comment by sydney-runkle** [comment]
@decision-dev

Ok actually, after looking into this a bit more, I don't think this is a bug. Here's how to achieve what you're looking for:

```py
from typing_extensions import Annotated

from pydantic import BaseModel, PlainValidator, WithJsonSchema

MyInt = Annotated[int, PlainValidator(lambda v: int(v) + 1), WithJsonSchema({'type': 'int'})]


class Model(BaseModel):
    a: MyInt


print(Model(a='1').a)
#> 2

print(Model(a='1').model_json_schema())
#> {'properties': {'a': {'title': 'A', 'type': 'int'}}, 'required': ['a'], 'title': 'Model', 'type': 'object'}
```

And this section of the [JSON Schema](https://docs.pydantic.dev/latest/api/json_schema/#pydantic.json_schema.WithJsonSchema) docs as well as this section of the [Types](https://docs.pydantic.dev/latest/concepts/types/#adding-validation-and-serialization) docs help to better explain this logic.

**Comment by decision-dev** [comment]
That worked!!  Thank you VERY much.  I really appreciate the fast reply.

If I may, I have two suggestions:
1)  Add something in the docs in the Functional Validators section.  Maybe it's just me, but I did a lot of searching through the docs and did not find WithJsonSchema.
2)  Automatically treat Annotated types as the underlying type. In other words if you have an Annotated[T, x] and pydantic knows how to handle type T, then model_json_schema should treat it as type T. 

Here's a little more explanation:
In the example I gave above, it is pretty trivial to just add ```WithJsonSchema('{'type': 'int'})```, but in our real use case, we have lots of functional validators, for example:

```
DateTime = Annotated[datetime, PlainValidator(partial(_validate_datetime_types, datetime)), WithJsonSchema({'format': 'date-time', 'type': 'string'})]
Date = Annotated[date, PlainValidator(partial(_validate_datetime_types, date)), WithJsonSchema({'format': 'date', 'type': 'string'})]
Time = Annotated[time, PlainValidator(partial(_validate_datetime_types, time)), WithJsonSchema({'format': 'time', 'type': 'string'})]
```

For each one, I am going to a BaseModel subclass that uses it, changing the type to the underlying, unannotated type, running model_jscon_schema(), getting the right schema, adding the appropriate WithJsonSchema, and then changing the type back to the Annotated type.  Suggestion 2 above would obviate the need for this by letting people rely on pydantic to just know the right Json schema.  

Thank you again for the fix.  I really appreciate it.  Hopefully my suggestions are useful.

**Comment by sydney-runkle** [comment]
@decision-dev,

Sure thing. Would you be interested in submitting a PR for the docs changes that you suggested? I agree, those would be quite helpful.

Re your second suggestion, the issue comes from attempting to create a json schema for the `PlainValidatorFunctionSchema`, not the underlying type. One potential issue with this approach is that the underlying type might not match that of the type used for serialization (see [this example](https://docs.pydantic.dev/latest/concepts/types/#adding-validation-and-serialization)). I'm not entirely opposed to the idea though. Feel free to submit a PR!

**Comment by decision-dev** [comment]
I'm not sure that I have the skills, but I will give it a shot!

**Comment by decision-dev** [comment]
After some digging, I found that this is unique to Annotated types with PlainValidators.  It works just as I proposed above for BeforeValidators, AfterValidators. 
The core schema for the other validators looks like this:
```
{
    "type": "model-field",
    "schema": {
        "function": {
            "type": "no-info",
            "function": "<function _validate at 0x78f58ade84a0>"
        },
        "schema": {
            "type": "int",
            "metadata": {
                "pydantic.internal.needs_apply_discriminated_union": false
            }
        },
        "type": "function-after"
    },
    "metadata": {
        "pydantic_js_functions": [],
        "pydantic_js_annotation_functions": [
            "<function GenerateSchema._common_field_schema.<locals>.json_schema_update_func at 0x78f58a6f7ec0>"
        ]
    }
}
```

whereas the core schema for the PlainValidator is missing the inner schema with the underlying type:
```
{
    "type": "model-field",
    "schema": {
        "type": "function-plain",
        "function": {
            "type": "no-info",
            "function": "<function _validate at 0x78f58ade84a0>"
        }
    },
    "metadata": {
        "pydantic_js_functions": [],
        "pydantic_js_annotation_functions": [
            "<function GenerateSchema._common_field_schema.<locals>.json_schema_update_func at 0x78f58a6d5620>"
        ]
    }
}
```

Do you know if this is intentional?  Is there something specific to PlainValidators that they should behave differently?  If not, I am going to go ahead and try to make the changes to add the inner schema to PlainValidators so they behave just like the others.

**Comment by sydney-runkle** [comment]
Hi @decision-dev,

Thanks for following up. Apologies for the delayed response.

I would say that this is not intentional, and we could certainly improve the way in which json schema is generated with `PlainValidators`. The following diff offers one potential solution to this, though I feel like this is a relatively unclean approach.

Also, as a side note, I'll be opening a PR shortly to update the docs on `WithJsonSchema`.

```
diff --git a/pydantic/functional_validators.py b/pydantic/functional_validators.py
index d6d2a1a8..fd21eebd 100644
--- a/pydantic/functional_validators.py
+++ b/pydantic/functional_validators.py
@@ -13,9 +13,10 @@ from pydantic_core import core_schema as _core_schema
 from typing_extensions import Annotated, Literal, TypeAlias
 
 from . import GetCoreSchemaHandler as _GetCoreSchemaHandler
-from ._internal import _core_metadata, _decorators, _generics, _internal_dataclass
-from .annotated_handlers import GetCoreSchemaHandler
+from ._internal import _core_metadata, _core_utils, _decorators, _generics, _internal_dataclass
+from .annotated_handlers import GetCoreSchemaHandler, GetJsonSchemaHandler
 from .errors import PydanticUserError
+from .json_schema import JsonSchemaValue
 
 if sys.version_info < (3, 11):
     from typing_extensions import Protocol
@@ -153,13 +154,21 @@ class PlainValidator:
     func: core_schema.NoInfoValidatorFunction | core_schema.WithInfoValidatorFunction
 
     def __get_pydantic_core_schema__(self, source_type: Any, handler: _GetCoreSchemaHandler) -> core_schema.CoreSchema:
+        core_schema_for_js = handler.generate_schema(source_type)
+
+        def get_js_schema(s: _core_utils.CoreSchemaOrField, js_handler: GetJsonSchemaHandler) -> JsonSchemaValue:
+            return js_handler(handler.generate_schema(core_schema_for_js))
+
+        metadata = _core_metadata.build_metadata_dict(js_functions=[get_js_schema])
         info_arg = _inspect_validator(self.func, 'plain')
         if info_arg:
             func = cast(core_schema.WithInfoValidatorFunction, self.func)
-            return core_schema.with_info_plain_validator_function(func, field_name=handler.field_name)
+            return core_schema.with_info_plain_validator_function(
+                func, field_name=handler.field_name, metadata=metadata
+            )
         else:
             func = cast(core_schema.NoInfoValidatorFunction, self.func)
-            return core_schema.no_info_plain_validator_function(func)
+            return core_schema.no_info_plain_validator_function(func, metadata=metadata)
 
 
 @dataclasses.dataclass(frozen=True, **_internal_dataclass.slots_true)

```

**Comment by sydney-runkle** [comment]
I think it'd be reasonable to open a new issue asking for better json schema generation logic for these types of validators 👍
