### ISSUE TITLE
Using Field(le) on integer fields is semi-broken

### ISSUE THREAD

**Issue by criemen** [pydantic/pydantic#7960]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The attached sample code fails with
```
pydantic_core._pydantic_core.SchemaError: Error building "model" validator:
  SchemaError: Error building "model-fields" validator:
  SchemaError: Field "score":
  SchemaError: Error building "int" validator:
  TypeError: Expected int, got <class 'float'>
```

I believe that to be a mistake, as the type for `le` is `float | None`. Using an integer (ie setting `le=10`) works, but as the type annotation specifically calls for a float, this seems to be a bug.

### Example Code

```Python
from __future__ import annotations

from pydantic import Field, BaseModel


class Test(BaseModel):
    score: int = Field(le=10.0)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/corni/projects/githubkit/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
                     platform: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @criemen,

Thanks for reporting this. I'm working on a mac, but using the `pydantic`, `pydantic-core`, and `python` versions that you specified, I'm not able to reproduce this error.

**Comment by criemen** [comment]
Fascinating, I can't reproduce this myself anymore, either on Linux or on mac.
Sorry for bothering you! I'll come back if I have a whole lockfile with dependencies that shows this error :/
