### ISSUE TITLE
Mention `pydantic-numpy` in the docs

### ISSUE THREAD

**Issue by caniko** [pydantic/pydantic#7980]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I noticed that pydantic-extra-types is mentioned in the docs, and think [pydantic-numpy](https://github.com/caniko/pydantic-numpy) should be mentioned in the same fashion.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@caniko

Thanks for the suggestion. I wonder if it makes more sense to integrate the logic you've designed in `pydantic-numpy` into `pydantic-extra-types`.

There's an open issue for numpy type support: https://github.com/pydantic/pydantic-extra-types/issues/31

Is this something you'd be interested in?

**Comment by caniko** [comment]
Beyond the expected Pydantic field support, `pydantic-numpy` also introduces the `NumpyModel` which extends `BaseModel`.

I could split the package for better integration, moving `NumpyModel` into its own repo. While this seemed reasonable initially, there's a concern: by doing so, I would end up sharing the namespace with unrelated fields, potentially complicating the package's identity and clarity.

I am leaning towards keeping this specific aspect of the Pydantic ecosystem in the current repository.

What do you think?

**Comment by sydney-runkle** [comment]
@caniko,

That makes sense. Maybe we can create a page in the docs that links to common OS libs that use `pydantic` 😄. We could add `pydantic-numpy` to that, as well as libraries like `fastapi`, `langchain`, etc 👍

**Comment by caniko** [comment]
OK

Moreover, I would also suggest mentioning it in the [types](https://docs.pydantic.dev/latest/concepts/types/) section within the docs.

**Comment by sydney-runkle** [comment]
I think this makes sense to include on https://github.com/Kludex/awesome-pydantic. Feel free to open a PR there, and I can review!
