### ISSUE TITLE
Path: Expand User Home Path

### ISSUE THREAD

**Issue by miili** [pydantic/pydantic#7990]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

On `Path`, `FilePath` and `DirectoryPath` user home `~/` is not expanded and results in a `ValidationError`.

Can we introduce an annotation to expand the user's path during validation?

```py
class Model(BaseModel):
    my_path: Annotated[Path, ExpandHomePath]
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @miili,

I'm able to reference the home path without a validation error. Does the following work for you?

```py
from pydantic import BaseModel
from pydantic.types import Path


class Model(BaseModel):
    my_path: Path


m = Model(my_path="~/")
print(repr(m))
#> Model(my_path=PosixPath('~'))
```

**Comment by miili** [comment]
Hi @sydney-runkle,

the `Path` is not expanded to `/home/whoever`. Running the following with pydantic's `DirectoryPath` will fail.

```py
from pydantic import BaseModel, DirectoryPath


class Model(BaseModel):
    my_path: DirectoryPath


m = Model(my_path="~/")
print(repr(m))
```

```pytb
Traceback (most recent call last):
  File "/tmp/test.py", line 8, in <module>
    m = Model(my_path="~/")
        ^^^^^^^^^^^^^^^^^^^
  File "/home/whoever/.pyenv/versions/3.11.2/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
my_path
  Path does not point to a directory [type=path_not_directory, input_value='~/', input_type=str]
```

**Comment by sydney-runkle** [comment]
Hi @miili,

I see what you mean. Unfortunately, making this change to `pydantic` would have a breaking nature for some users. There are a variety of cases where I could imagine this would be an issue, but here are 2:

1. The below example works on the main branch, but not on your branch:
```py
import os
from pathlib import Path

from pydantic import BaseModel, FilePath

home = Path('~').expanduser()
os.chdir(str(home))

Path('~').mkdir(exist_ok=True)
Path('~/my_file.txt').write_text('hello-world')


class MyModel(BaseModel):
    x: FilePath


assert MyModel(x=f'~/my_file.txt').x.read_text() == 'hello-world'


Path('~/my_file.txt').unlink()
Path('~').rmdir()
```

2. This exposes somewhat of a security issue - it exposes information about the user's directory that might need to remain private. Ex - the example below results in `#> Model(my_path=PosixPath('/Users/my_user'))`, but you can imagine a case where one wouldn't want to expose user information.

One workaround that you could use is the following:
```py
from pathlib import Path

from typing_extensions import Annotated

from pydantic import AfterValidator, BaseModel
from pydantic.types import PathType

DirectoryPath = Annotated[Path, AfterValidator(lambda v: v.expanduser()), PathType('dir')]


class Model(BaseModel):
    my_path: DirectoryPath


m = Model(my_path="~/")
print(repr(m))
#> Model(my_path=PosixPath('/Users/my_user'))
```

You could use a similar pattern with `Annotated` for `FilePath`. I hope this explanation makes sense. Let me know if you have any follow up questions.

I appreciate your willingness to create the PR - you were definitely on the right track in terms of introducing the `expanduser` logic for the behavior you are desiring, but the pattern you suggested is not something that we can adopt because of its breaking nature.

**Comment by miili** [comment]
Gotcha!

Can introduce a short handle for the user expansion in `.types`?

**Comment by sydney-runkle** [comment]
Hi @miili,

I think this probably makes sense to keep in user code for now. If there's more broad support for this kind of feature (say 5 or so likes on this thread), then I think it makes more sense to add it to `.types`. Thank you for the offer, though!

**Comment by sydney-runkle** [comment]
Going to close this for now, but happy to revisit (as mentioned above) if there's a greater demand for this kind of behavior. Thanks again for the report :).

**Comment by fer-rum** [comment]
I ran into a similar issue. While I see how this breaks code, `pydantic` could offer these required type aliases as shortcuts or maybe add a hint about this in the documentation, maybe as an FAQ entry or a cookbook section, so it is easier to find when looking stuff up?

**Comment by fer-rum** [comment]
As a side note: `PathType` is not part of your public interface, and using it as suggested in your fix would be considered bad practise.

Pycharm, for example, warns the user about that [similar to this case](https://stackoverflow.com/questions/61165807/what-does-this-warning-mean-not-declared-in-all).
