### ISSUE TITLE
RecursionError when using a date field with the name "date"

### ISSUE THREAD

**Issue by Maxyme** [pydantic/pydantic#7994]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Creating a pydantic BaseModel with property "date" and type "date" creates a Recursion Error in Pydantic 2.4.2

Note: renaming the field to something else than "date" solves the issue.

### Example Code

```Python
from datetime import date
from pydantic import BaseModel, Field

class Test(BaseModel):
    date: date = Field()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/mjacques/Library/Caches/pypoetry/virtualenvs/foresight-84sJgwcM-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.0-arm64-arm-64bit
             related packages: email-validator-2.0.0.post2 typing_extensions-4.8.0 pydantic-settings-2.0.3
```

**Comment by sydney-runkle** [comment]
Hi @Maxyme,

Thanks for the report. This has been reported before, similar to this issue: https://github.com/pydantic/pydantic/issues/7945. The onus is on the user here to prevent the namespace conflict for `date`
