### ISSUE TITLE
Default object when a pydantic model has a hash function

### ISSUE THREAD

**Issue by Gabe1203** [pydantic/pydantic#7996]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In order to use pydantic models in a set we've noticed that we have to add a hash function to that model. However, when we do this we noticed some weird behavior when creating default versions of objects after creating an initial version of that model. 

In example A below where we don't have a hash function the output is:
>> myStats=MyStats(stats=0)
>> myStats=MyStats(stats=1)
>> myStats=MyStats(stats=0)

In example B below where we do have a hash function the output is:
>> myStats=MyStats(stats=0)
>> myStats=MyStats(stats=1)
>> myStats=MyStats(stats=1)

We don't understand why providing a hash leads to creating a default version of that object where stats is initialized to 1. Not 100% that this is a bug but would like to at least understand what is going on here, as this doesn't happen with normal objects in python when using a hash function with those objects.

Any insight into this would be very helpful - thanks in advance! 

### Example Code

```Python
from pydantic import BaseModel

# Example A
class MyStats(BaseModel):
    stats: int = 0
    
class MyModel(BaseModel):
    myStats: MyStats = MyStats()

my_model = MyModel()

print(my_model)
my_model.myStats.stats = 1
print(my_model)
my_model = MyModel()
print(my_model)

# Example B
class MyStats(BaseModel):
    stats: int = 0
    
    def __hash__(self) -> int:
        return self.stats.__hash__()
        
class MyModel(BaseModel):
    myStats: MyStats = MyStats()
    
my_model = MyModel()

print(my_model)
my_model.myStats.stats = 1
print(my_model)
my_model = MyModel()
print(my_model)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=false
python version: 3.9.16 (main, Dec  7 2022, 10:02:13)  [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-13.5.1-arm64-arm-64bit
```

**Comment by alexmojaki** [comment]
https://docs.pydantic.dev/latest/concepts/models/#fields-with-non-hashable-default-values

> A common source of bugs in python is to use a mutable object as a default value for a function or method argument, as the same instance ends up being reused in each call.

> The dataclasses module actually raises an error in this case, indicating that you should use the default_factory argument to dataclasses.field.

> Pydantic also supports the use of a [default_factory](https://docs.pydantic.dev/latest/concepts/models/#fields-with-dynamic-default-values) for non-hashable default values, but it is not required. **In the event that the default value is not hashable, Pydantic will deepcopy the default value when creating each instance of the model**

The presence of `__hash__` makes pydantic think that `MyStats()` is immutable and safe to reuse as a default object. This is because a mutable object shouldn't have a `__hash__` because it's not safe to put it in a dict/set and then mutate it:

```python
from pydantic import BaseModel


class MyStats(BaseModel):
    stats: int = 0

    def __hash__(self) -> int:
        return self.stats.__hash__()


my_stats = MyStats()

lst = [my_stats]
s = {my_stats}
assert my_stats in lst
assert my_stats in s

my_stats.stats = 1
assert my_stats in lst
assert my_stats in s  # fails
```

The typical correct approach in pydantic is to set `frozen=True` in the model config: https://docs.pydantic.dev/latest/concepts/models/#faux-immutability

This makes the model 'immutable' and also adds a `__hash__` method for you. The line `my_model.myStats.stats = 1` will raise an error, but that's a good thing.

**Comment by Gabe1203** [comment]
Awesome - thanks for the response this is helpful!
