### ISSUE TITLE
[Discussion] Recoverable fields

### ISSUE THREAD

**Issue by DerRidda** [pydantic/pydantic#800]
# Feature Request

I want to discuss the idea of potentially having a recoverable type or recovery mechanic for invalid fields in pydantic.

The specific use case is, that we have data with a ton of optional fields that may be provided to us with invalid data. We want to detect and report about these invalid fields but without discarding everything else that is valid.

I have tried several approaches of bolting this kind of logic on top of the library as purely a user of it but ended up with hacky and incomplete solutions that at a bare minimum always lose the location information ("loc") field of the invalid data.

Any solution to be truly viable for us needs to still include the loc field and it needs to be collectable in a structured fashion, e.g. a method to retrieve these errors on the parsed object or via warnings (though capturing warnings is a thread-safety issue).

I wasn't sure if that was really in line with the idea of pydantic but since I read that pydantic is actually a parsing library instead of validation I would say, that this is aligns with that idea.

**Comment by samuelcolvin** [comment]
I'm pro this.

I think some kinds of error (eg. `const` maybe?) have `given_value` in the context on each error.

I would suggest we add `given_value` (perhaps better name if possible) to `ctx` of all errors.

Would this suit your purpose?

**Comment by DerRidda** [comment]
I don"t think it would serve my person and I do believe I didn't quite make my intention clear.
Let me just draft a pseudo-code example of what I imagine:

```python
from typing import List
from pydantic import BaseModel, recoverable

class NestedModel(BaseModel):
    int_value: recoverable(int, recover_value=None)
    # recover_value would be the value that is applied when the field is invalid


class Model(BaseModel):
    float_value: float
    nested: NestedModel


data = {"float_value": 13.56 ,"nested": { "int_value": "not an int"}}

m = Model(**data)  # Does not raise a ValidationError

assert m.float_value == 13.56 # passes
assert m.nested.int_value == None # also passes

warnings = m.warnings() # This would contain list or similar of ValidationError that wasn't thrown but
                                       # raised by recoverable values

assert w[0].loc == ("nested", "int_value",) # location information is still resent

`¨

I hope I get the idea across. This of course is by no means the way this functionality would necessary look like.

**Comment by samuelcolvin** [comment]
I see what you mean, makes more sense.

Personally I think the warning/recoverable think is too esoteric.

How about a `Config` setting for keeping a reference to the original data:
* that original data would be available in the sub-model, so you could do something like `m.nested.original['int_value']`
* you could setup validators or custom data types to achieve custom parsing/validation logic on `int_value`

The other approach would be to create a custom data types (e.g. `RecoverableInt`) which stores the original value and the int value if possible. This would be achievable now without any changes to pydantic or waiting for v1.

I'm open to more suggestions here, I see the problem but I'm but sure we've quite got to the best solution yet.

**Comment by samuelcolvin** [comment]
For reference, here's a demo of `RecoverableInt`

```py
from typing import Any, Optional
from pydantic import BaseModel
from pydantic.validators import int_validator

class RecoverableInt:
    def __init__(self, int_value: Optional[int], raw_value: Any):
        self.int = int_value
        self.raw = raw_value

    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        try:
            int_v = int_validator(v)
        except (ValueError, TypeError):
            int_v = None
        return cls(int_v, v)

    def __eq__(self, other):
        return other == self.int

    def __add__(self, other):
        return self.int + other

    def __sub__(self, other):
        return self.int - other

    def __str__(self):
        return str(self.int)

    def __repr__(self):
        return repr(self.int)

class NestedModel(BaseModel):
    int_value: RecoverableInt

class Model(BaseModel):
    nested: NestedModel

m = Model(nested={'int_value': 'not an int'})
print(repr(m))
# <Model nested=<NestedModel int_value=None>>
print(repr(m.nested.int_value))
# None
print(repr(m.nested.int_value.raw))
# 'not an int'
assert m.nested.int_value == None
assert m.nested.int_value.raw == 'not an int'

m = Model(nested={'int_value': '42'})
print(repr(m))
# <Model nested=<NestedModel int_value=42>>
print(repr(m.nested.int_value))
# 42
print(repr(m.nested.int_value.raw))
# '42'
assert m.nested.int_value == 42
assert m.nested.int_value.raw == '42'
```

A few limitations:
* you'd technically you'd need to implement all the operator methods on `RecoverableInt`
* `m.nested.int_value is None` won't work
* `RecoverableInt` behaving "a bit like" `Union[int]` but not entirely could be confusing, you might want to remove all the operator, str, repr methods and just access `.int` directly

Still I think there are places where this approach would be helpful.

**Comment by DerRidda** [comment]
I agree that the entire thing is fairly esoteric, as naturally it's a business requirement and not a tech one. ;)

I actually went back to my original gist where I experimented with these warnings and what actually truly kept me from doing this simply as a library user was the fact that the actual loc of a field that has an error is only created when the errors are being flattened.

Within the model and its field there is no awareness of the nested location, only the alias.

If I had the actual loc at the moment of validation plus being able to override the "root loc" of a model I could make this gist do 100% of what I need: https://gist.github.com/DerRidda/e4b1a5195db48f9a334ab96b02437314 by simple wrapping up the "recoverable field" like that.

But the way it is now I can't really get at the true nested loc without insane amounts of hacking.

So maybe these two things would be better and more manage features:

- Add a Config setting to override the root loc of a model
This could be useful beyond my use case for people that only want to validate a sub-dict of a nested dict but would like the error messages to refer to the entire dict for better error reporting or automated steps on errors.
- Add an attribute to Filed that contains the current loc
- Make sure the nesting gets automatically propagated to nested models and their fields

**Comment by samuelcolvin** [comment]
I guess in theory it might be possible to add `loc` as an optional argument to a validator (either decorator or custom type). Would that solve your problem?

The problem is that (as you say) the `loc` isn't currently generated until after an error has been raised, it would add extra processing to the hot path to always generate the loc for all fields.

**Comment by DerRidda** [comment]
The processing overhead could be avoided by not doing anything if that Config setting isn't set.
But I get that this might be too complex to do.

**Comment by samuelcolvin** [comment]
while working on #803 I noticed it shouldn't be that hard to add `loc` as an optional argument to validators.

Would that resolve your problem?

Might have to wait until after v1 is released since it should be a backwards compatible change.

**Comment by DerRidda** [comment]
If it's genuine full loc it would 100% solve my problem.

**Comment by samuelcolvin** [comment]
yes, I believe it will be.

**Comment by DerRidda** [comment]
> while working on #803 I noticed it shouldn't be that hard to add `loc` as an optional argument to validators.
> 
> Would that resolve your problem?
> 
> Might have to wait until after v1 is released since it should be a backwards compatible change.

Wouldn't loc as an optional keyword only parameter in a validator already be a backwards compatible change?

I don't want to rush you, as you are obviously busy enough already but I don't see API stability being an issue in this case.

**Comment by samuelcolvin** [comment]
yes, it should be backwards compatible, hence why I'm not bothering with it until after v1.

I'm working to get v1 done, and thus ignoring everything that doesn't block v1.

**Comment by DerRidda** [comment]
Oh, alright. I simply misunderstood.

**Comment by DerRidda** [comment]
Hello @samuelcolvin, I would like to know what your idea was to passing the actual loc into the validator. I see a relatively near future where I would like to have that and instead of waiting for somebody else to do it I wouldn't mind implementing it myself and since you seem to have a very concrete idea on how to do it I would like to hear it and try to implement it.

**Comment by samuelcolvin** [comment]
> I wouldn't mind implementing it myself

Great.

At:
https://github.com/samuelcolvin/pydantic/blob/151143deb4eaf6a5e2dce4532659e5ee9e2e4713/pydantic/fields.py#L618-L623

We have `loc`, we need to pass that to the `validator`. Then in `class_validators.py` we need to modify `_generic_validator_cls` and `_generic_validator_basic` to add `loc` as a possible argument.

----

_(This doesn't need to prevent @DerRidda adding the `loc` argument, I'm just curious)_

**Question:**

Currently to keep validators as fast as possible when executed, we define separate lambda functions for each permutation of arguments to the validator.

This is ugly and repetitive and it makes adding more arguments progressively harder.

Is there any way of generating those functions programmatically without having to write out each case?

**Comment by DerRidda** [comment]
There could be a lookup dictionary that is generated once at runtime to frontload the cost and.

Here is the first spark of that idea:
```python
from pprint import pprint
from itertools import combinations

all_kwargs = {'values', 'field', 'config', 'loc'}

validator_arg_map = {}
for i in range(len(all_kwargs)):
    prod = combinations(all_kwargs, i+1)
    for permutation in prod:
        s = frozenset(permutation)
        validator_arg_map[s] = True

pprint(validator_arg_map, indent=2)

value = validator_arg_map.get(frozenset({'config', 'loc', 'values'}))

pprint(value)
assert value == True
```

The next step would be creating the callables.

**Comment by samuelcolvin** [comment]
that's fine, but how would we create the lambda function? I assume using `eval()` wouldn't not work with cython or at least slow it down a lot.

**Comment by dmontagu** [comment]
@samuelcolvin I'm wondering if there isn't some magic we could do inside the `@validator` decorator that will modify the decorated method to accept (and do nothing with) the unused keyword arguments, so we could drop the lambdas entirely, and just always pass all keyword arguments to validators.

Hard for me to guess at the performance implications (and I think good performance would depend heavily on an optimized implementation), but would the benchmark as currently implemented offer a good test if I were to try tweaking this implementation?

**Comment by dmontagu** [comment]
Okay, yeah, nevermind. I looked at the cython-generated C code for the lambdas, and there's probably no way to achieve that efficiency without leaving the realm of python:
<details>
<summary>Click to expand</summary>
<p>

```c
/* Python wrapper */
static PyObject *__pyx_pw_8pydantic_16class_validators_22_generic_validator_cls_8lambda9(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyMethodDef __pyx_mdef_8pydantic_16class_validators_22_generic_validator_cls_8lambda9 = {"lambda9", (PyCFunction)(void*)(PyCFunctionWithKeywords)__pyx_pw_8pydantic_16class_validators_22_generic_validator_cls_8lambda9, METH_VARARGS|METH_KEYWORDS, 0};
static PyObject *__pyx_pw_8pydantic_16class_validators_22_generic_validator_cls_8lambda9(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_cls = 0;
  PyObject *__pyx_v_v = 0;
  PyObject *__pyx_v_values = 0;
  PyObject *__pyx_v_field = 0;
  PyObject *__pyx_v_config = 0;
  PyObject *__pyx_r = 0;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("lambda9 (wrapper)", 0);
  {
    static PyObject **__pyx_pyargnames[] = {&__pyx_n_s_cls,&__pyx_n_s_v,&__pyx_n_s_values,&__pyx_n_s_field,&__pyx_n_s_config,0};
    PyObject* values[5] = {0,0,0,0,0};
    if (unlikely(__pyx_kwds)) {
      Py_ssize_t kw_args;
      const Py_ssize_t pos_args = PyTuple_GET_SIZE(__pyx_args);
      switch (pos_args) {
        case  5: values[4] = PyTuple_GET_ITEM(__pyx_args, 4);
        CYTHON_FALLTHROUGH;
        case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
        CYTHON_FALLTHROUGH;
        case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
        CYTHON_FALLTHROUGH;
        case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
        CYTHON_FALLTHROUGH;
        case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
        CYTHON_FALLTHROUGH;
        case  0: break;
        default: goto __pyx_L5_argtuple_error;
      }
      kw_args = PyDict_Size(__pyx_kwds);
      switch (pos_args) {
        case  0:
        if (likely((values[0] = __Pyx_PyDict_GetItemStr(__pyx_kwds, __pyx_n_s_cls)) != 0)) kw_args--;
        else goto __pyx_L5_argtuple_error;
        CYTHON_FALLTHROUGH;
        case  1:
        if (likely((values[1] = __Pyx_PyDict_GetItemStr(__pyx_kwds, __pyx_n_s_v)) != 0)) kw_args--;
        else {
          __Pyx_RaiseArgtupleInvalid("lambda9", 1, 5, 5, 1); __PYX_ERR(0, 278, __pyx_L3_error)
        }
        CYTHON_FALLTHROUGH;
        case  2:
        if (likely((values[2] = __Pyx_PyDict_GetItemStr(__pyx_kwds, __pyx_n_s_values)) != 0)) kw_args--;
        else {
          __Pyx_RaiseArgtupleInvalid("lambda9", 1, 5, 5, 2); __PYX_ERR(0, 278, __pyx_L3_error)
        }
        CYTHON_FALLTHROUGH;
        case  3:
        if (likely((values[3] = __Pyx_PyDict_GetItemStr(__pyx_kwds, __pyx_n_s_field)) != 0)) kw_args--;
        else {
          __Pyx_RaiseArgtupleInvalid("lambda9", 1, 5, 5, 3); __PYX_ERR(0, 278, __pyx_L3_error)
        }
        CYTHON_FALLTHROUGH;
        case  4:
        if (likely((values[4] = __Pyx_PyDict_GetItemStr(__pyx_kwds, __pyx_n_s_config)) != 0)) kw_args--;
        else {
          __Pyx_RaiseArgtupleInvalid("lambda9", 1, 5, 5, 4); __PYX_ERR(0, 278, __pyx_L3_error)
        }
      }
      if (unlikely(kw_args > 0)) {
        if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, pos_args, "lambda9") < 0)) __PYX_ERR(0, 278, __pyx_L3_error)
      }
    } else if (PyTuple_GET_SIZE(__pyx_args) != 5) {
      goto __pyx_L5_argtuple_error;
    } else {
      values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      values[4] = PyTuple_GET_ITEM(__pyx_args, 4);
    }
    __pyx_v_cls = values[0];
    __pyx_v_v = values[1];
    __pyx_v_values = values[2];
    __pyx_v_field = values[3];
    __pyx_v_config = values[4];
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("lambda9", 1, 5, 5, PyTuple_GET_SIZE(__pyx_args)); __PYX_ERR(0, 278, __pyx_L3_error)
  __pyx_L3_error:;
  __Pyx_AddTraceback("pydantic.class_validators._generic_validator_cls.lambda9", __pyx_clineno, __pyx_lineno, __pyx_filename);
  __Pyx_RefNannyFinishContext();
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_r = __pyx_lambda_funcdef_lambda9(__pyx_self, __pyx_v_cls, __pyx_v_v, __pyx_v_values, __pyx_v_field, __pyx_v_config);

  /* function exit code */
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

static PyObject *__pyx_lambda_funcdef_lambda9(PyObject *__pyx_self, PyObject *__pyx_v_cls, PyObject *__pyx_v_v, PyObject *__pyx_v_values, PyObject *__pyx_v_field, PyObject *__pyx_v_config) {
  struct __pyx_obj_8pydantic_16class_validators___pyx_scope_struct_4__generic_validator_cls *__pyx_cur_scope;
  struct __pyx_obj_8pydantic_16class_validators___pyx_scope_struct_4__generic_validator_cls *__pyx_outer_scope;
  PyObject *__pyx_r = NULL;
  __Pyx_RefNannyDeclarations
  __Pyx_RefNannySetupContext("lambda9", 0);
  __pyx_outer_scope = (struct __pyx_obj_8pydantic_16class_validators___pyx_scope_struct_4__generic_validator_cls *) __Pyx_CyFunction_GetClosure(__pyx_self);
  __pyx_cur_scope = __pyx_outer_scope;
  __Pyx_XDECREF(__pyx_r);
  if (unlikely(!__pyx_cur_scope->__pyx_v_validator)) { __Pyx_RaiseClosureNameError("validator"); __PYX_ERR(0, 278, __pyx_L1_error) }
  __pyx_t_1 = PyTuple_New(2); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 278, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_1);
  __Pyx_INCREF(__pyx_v_cls);
  __Pyx_GIVEREF(__pyx_v_cls);
  PyTuple_SET_ITEM(__pyx_t_1, 0, __pyx_v_cls);
  __Pyx_INCREF(__pyx_v_v);
  __Pyx_GIVEREF(__pyx_v_v);
  PyTuple_SET_ITEM(__pyx_t_1, 1, __pyx_v_v);
  __pyx_t_2 = __Pyx_PyDict_NewPresized(3); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 278, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_2);
  if (PyDict_SetItem(__pyx_t_2, __pyx_n_s_values, __pyx_v_values) < 0) __PYX_ERR(0, 278, __pyx_L1_error)
  if (PyDict_SetItem(__pyx_t_2, __pyx_n_s_field, __pyx_v_field) < 0) __PYX_ERR(0, 278, __pyx_L1_error)
  if (PyDict_SetItem(__pyx_t_2, __pyx_n_s_config, __pyx_v_config) < 0) __PYX_ERR(0, 278, __pyx_L1_error)
  __pyx_t_3 = __Pyx_PyObject_Call(__pyx_cur_scope->__pyx_v_validator, __pyx_t_1, __pyx_t_2); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 278, __pyx_L1_error)
  __Pyx_GOTREF(__pyx_t_3);
  __Pyx_DECREF(__pyx_t_1); __pyx_t_1 = 0;
  __Pyx_DECREF(__pyx_t_2); __pyx_t_2 = 0;
  __pyx_r = __pyx_t_3;
  __pyx_t_3 = 0;
  goto __pyx_L0;

  /* function exit code */
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_XDECREF(__pyx_t_3);
  __Pyx_AddTraceback("pydantic.class_validators._generic_validator_cls.lambda9", __pyx_clineno, __pyx_lineno, __pyx_filename);
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}
/* … */
  /*else*/ {
    __Pyx_XDECREF(__pyx_r);
    __pyx_t_3 = __Pyx_CyFunction_NewEx(&__pyx_mdef_8pydantic_16class_validators_22_generic_validator_cls_8lambda9, 0, __pyx_n_s_generic_validator_cls_locals_la, ((PyObject*)__pyx_cur_scope), __pyx_n_s_pydantic_class_validators, __pyx_d, NULL); if (unlikely(!__pyx_t_3)) __PYX_ERR(0, 278, __pyx_L1_error)
    __Pyx_GOTREF(__pyx_t_3);
    __pyx_r = __pyx_t_3;
    __pyx_t_3 = 0;
    goto __pyx_L0;
  }
```

</p>
</details>

It looks to me like it is building as close to a zero-cost call to the underlying python function as I could imagine, and based on googling it looks like there isn't really a way to programatically generate a function call like this without adding a layer to the callstack.

So, I guess the real question would be how much slower it actually is to wrap the call in some sort of `**kwargs`-leveraging wrapper.

**Comment by samuelcolvin** [comment]
I think the wrapper approach was what was used before. This approach was my attempt to speed it up, I think it worked fairly well.

I think the benchmarks should be a good proxy for performance since that validator code is called when checking very value.

The c you show is very interesting, it's roughly what I had been imagining without ever actually checking.

I agree that improvements are probably not possible.

**Comment by dmontagu** [comment]
Yeah, okay I tried replacing it with:
```python
    param_indices = {"values": 0, "field": 1, "config": 2}
    param_indices = {k: v for k, v in param_indices.items() if k in sig.parameters.keys()}
    param_names = [x for x in list(sig.parameters.keys())[2:] if x != "kwargs"]
    arg_indices = [param_indices[name] for name in param_names]
    def _validator_cls(cls, v, *args_):
        all_kwargs = {name: args_[index] for name, index in zip(param_names, arg_indices)}
        return validator(cls, v, **all_kwargs)
```
and got 20% slower performance on the benchmark. I'm sure this could be made marginally faster, but it at least confirms for me we are getting *substantial* gains out of the current lambda-based approach.

**Comment by DerRidda** [comment]
@samuelcolvin Working on this again now and trying to be clean from start I have linting issues with the complexity of the `_make_generic_validator_cls` and `_make_generic_validator_basic`

```
pydantic/class_validators.py:262:1: C901 '_generic_validator_cls' is too complex (19)
pydantic/class_validators.py:314:1: C901 '_generic_validator_basic' is too complex (19)
```

This complexity is inherent in inevitable when adding any new argument to these functions when choosing the same approach. Please advise how you want this handled.

**Comment by samuelcolvin** [comment]
no problem, just add `# noqa: C901 (ignore complexity)` as is done elsewhere in the code

**Comment by dmontagu** [comment]
It should now be possible to do this using `@field_validator(mode='wrap')` or `@model_validator(mode='wrap')`, and catch (and handle) the error raised by handler.

(If this description is not helpful enough, please comment here asking for more info.)

**Comment by pedrohgmacedo** [comment]
> It should now be possible to do this using `@field_validator(mode='wrap')` or `@model_validator(mode='wrap')`, and catch (and handle) the error raised by handler.
> 
> (If this description is not helpful enough, please comment here asking for more info.)

Is there an example of a @model_validator(mode='wrap') in the documentation, used to recover from errors?
