### ISSUE TITLE
ValidationError on Optional Field

### ISSUE THREAD

**Issue by TheTechromancer** [pydantic/pydantic#8006]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am running into an error with `Optional` fields, where unless a default is set for the field, a `ValidationError` is thrown, declaring that the field is required.

### Example Code

```Python
from typing import Optional
from pydantic import BaseModel

class person(BaseModel):
    name: str
    title: Optional[str]

n = person(name="bob")
```

Result:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    n = person(name="bob")
        ^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for person
title
  Field required [type=missing, input_value={'name': 'bob'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missin
```

The error will not trigger if a default is set for the field, e.g.:

```python
title: Optional[str] = ""
```

... but this causes the default value to show up in `.dict()`:

```json
{"name": "bob", "title": ""}
```

The desired behavior is for the field to be omittable and not present in the serialized output.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/user/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
                     platform: Linux-6.5.7-arch1-1-x86_64-with-glibc2.38
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @TheTechromancer,

Check out our migration guide section on `Optional` types: https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields

Also, check out our docs on excluding default values from serialized data: https://docs.pydantic.dev/latest/concepts/serialization/#model-and-field-level-include-and-exclude

Let me know if you have any other questions!

**Comment by TheTechromancer** [comment]
Thanks @sydney-runkle, that's good information.

But I don't see how it's possible to recreate the original functionality. If I do:

```python
title: Optional[str] = None
```

Then the result of `.dict()` is:

```
{"name": "bob", "title": None}
```

How can I get it to be this, like it originally was:

```
{"name": "bob"}
```

**Comment by sydney-runkle** [comment]
I'd recommend you use `model_dump` with `exclude_default=True` or `exclude_none=True`.

**Comment by TheTechromancer** [comment]
Thank you! That is perfect! 🙏
