### ISSUE TITLE
Inconsistent handling of enum values with smart union

### ISSUE THREAD

**Issue by ml-evs** [pydantic/pydantic#8017]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I've come across what I believe to be another inconsistency along the lines of #7097, involving enum values. Passing a string value for an enum seems to lead to the smart union preferring a raw dictionary over a compatible pydantic model.

Below is a stripped down version of something I ran into when migrating to v2 (with our workaround here: https://github.com/Materials-Consortia/optimade-python-tools/pull/1844)

### Example Code

```Python
from enum import Enum
from typing import Annotated, Any, Union

from pydantic import BaseModel, Field, __version__


class ResourceType(Enum):
    link = "link"
    image = "image"


class ResourceAttributes(BaseModel):
    name: Annotated[str, Field()]
    media_type: Annotated[ResourceType, Field()]


class Resource(BaseModel):
    attributes: Annotated[ResourceAttributes, Field()]


class Wrapper(BaseModel):
    data: Annotated[Union[Resource, dict[str, Any]], Field()]


class Wrapper2(BaseModel):
    data: Annotated[Union[Resource, dict[str, Any]], Field(union_mode="left_to_right")]

class Wrapper3(BaseModel):
    data: Resource


if __name__ == "__main__":
    print(f"{__version__=}")
    test_data = {"data": {"attributes": {"name": "123", "media_type": "link"}}}

    d = Wrapper(**test_data)
    print(d)

    d2 = Wrapper2(**test_data)
    print(d2)

    d3 = Wrapper3(**test_data)
    print(d3)

    test_data["data"]["attributes"]["media_type"] = ResourceType.link
    d = Wrapper(**test_data)
    print(d)

```

Running the above yields:

```
__version__='2.4.2'
data={'attributes': {'name': '123', 'media_type': 'link'}}
data=Resource(attributes=ResourceAttributes(name='123', media_type=<ResourceType.link: 'link'>))
data=Resource(attributes=ResourceAttributes(name='123', media_type=<ResourceType.link: 'link'>))
data=Resource(attributes=ResourceAttributes(name='123', media_type=<ResourceType.link: 'link'>))
```

i.e., in the second case, the test data is perfectly able to fit into the model, but unless `union_mode` is set to `left_to_right`, the smart mode (first case) prefers a dictionary. In the 3rd case, I have removed the union altogether, and the enum is correctly handled. Finally, if I explicitly set `media_type` using the enum (fourth case), then smart mode works fine.

Is this expected behaviour?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/mevans/.local/miniforge3/envs/pydantic_test/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
                     platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0
```

**Comment by CasperWA** [comment]
Note: Should be `Wrapper3()` for `d3` above.

**Comment by ml-evs** [comment]
> Note: Should be `Wrapper3()` for `d3` above.

Well-spotted, doesn't change the output thankfully ;)

**Comment by sydney-runkle** [comment]
Hi @ml-evs,

Thanks for reporting this. As of now, this is indeed how the smart union mode works. @adriangb mentioned in a different issue:
> v2 does multiple passes on unions. the first without coercion and if none of the options match it does another pass with coercion.

Your safest bet for now is to use one of the other three alternatives that you have listed. This PR in `pydantic-core` has the potential to change this behavior: https://github.com/pydantic/pydantic-core/pull/867.

I think it probably makes sense to close this issue for now, given that this is the expected behavior. That being said, we can certainly use this as a test case if / when we make changes to `pydantic-core` that support the behavior you're expecting.

**Comment by ml-evs** [comment]
Thanks for the detail @sydney-runkle -- agree this should be closed. From that PR, it seems that https://github.com/pydantic/pydantic/issues/7110 is the real base issue tracking this (apologies -- I should have done a broader search before raising this -- 'smart union enum' was too niche)
