### ISSUE TITLE
Functions decorated with `validate_call` are not detected by `inspect.isfunction`

### ISSUE THREAD

**Issue by yarnabrina** [pydantic/pydantic#8019]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If a function is decorated with the `pydantic.validate_call` decorator, it is being considered as an instance of `pydantic._internal._validate_call.ValidateCallWrapper`. Thus, trying to list all functions present in a function or package using `inspect.getmembers` with predicate `inspect.isfunction` is failing.

### Example Code

```Python
>>> 
>>> import pydantic
>>> 
>>> @pydantic.validate_call
... def f(x: int) -> int:
...     return x
... 
>>> 
>>> import inspect
>>> 
>>> inspect.isfunction(f)
False
>>>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
pydantic-core version: 2.10.1
pydantic-core build: profile=release pgo=true
install path: /home/anirban/conda-environments/packaging/lib/python3.10/site-packages/pydantic
python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
related packages: typing_extensions-4.7.1 mypy-1.6.1 pyright-1.1.334
```

**Comment by samuelcolvin** [comment]
Well technically `validate_call` is implemented as a class.

I'm not convinced this is a bug as we don't claim otherwise, and it should be relatively simple to add some custom logic to detect `validate_call` decorated items.

Is there a particular problem this is causing.

**Comment by yarnabrina** [comment]
Thanks for the quick response.

What I was trying to do is list all members in a package (and recursively in sub-packages not all of which uses `pydantic` because of different authours etc.), and then create functions, classes, etc. as boolean labels (based on the `inspect.is*` functions) and few other details. This will then be used to create a dataset for a langchain use case.

Having detected these as function simply would have made this labelling easier.

**Comment by samuelcolvin** [comment]
makes sense, I can imagine it's annoying.

I definitely don't think we can change this in a minor release as others will already be relying on the current implementation.

I would suggest this is the way to detect a `validate_call` decorated method:

```py
from pydantic import validate_call

# Get the type to use later to detect a `validate_call` decorated function
ValidateCallType = type(validate_call(lambda x: x))


@validate_call
def my_function(a: int, b: str) -> int:
    return a + len(b)


print(isinstance(my_function, ValidateCallType))  # True
```

For anyone who thinks that looks like an ugly hack, it's exactly [how the `types` module of CPython works](https://github.com/python/cpython/blob/0fb18b02c8ad56299d6a2910be0bab8ad601ef24/Lib/types.py#L11-L12).
