### ISSUE TITLE
No constructor defined for ValidationError

### ISSUE THREAD

**Issue by saber-solooki** [pydantic/pydantic#8026]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm trying to mimic some behavior on my test and when I try to create an object of ValidationError, I'll get an error:
```
TypeError: No constructor defined
```
This is not an issue in version one.
As I checked ValidationError is inherited from ValueError which is Exception. In my understanding, it makes sense to create an object of the Exception class.

### Example Code

```Python
from pydantic import ValidationError
ValidationError()

TypeError: No constructor defined
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/sabersolooki/.pyenv/versions/3.10.6/envs/myproject/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Nov 25 2022, 12:24:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.4-x86_64-i386-64bit
             related packages: mypy-1.6.1 typing_extensions-4.8.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
Hi @saber-solooki,

Thanks for your question. As answered in this issue: https://github.com/pydantic/pydantic/issues/6734, you'll have to use `ValidationError.from_exception_data`.

You can read more in the docs here: https://docs.pydantic.dev/latest/api/pydantic_core/#pydantic_core._pydantic_core.ValidationError.from_exception_data
