### ISSUE TITLE
Helper functions for `JsonValue` common use cases

### ISSUE THREAD

**Issue by alexmojaki** [pydantic/pydantic#8038]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I'm thinking about the use cases for the new https://docs.pydantic.dev/dev/api/types/#pydantic.types.JsonValue

The new docs recommend using `adapter = TypeAdapter(JsonValue)`, `adapter.validate_python`, and `adapter.validate_json`.

I imagine that the main use case to cater for - the thing that users will probably want the vast majority of the time - is something similar to the standard `json.loads` and `json.dumps`, but with the added benefits of:

1. A nice return type (`JsonValue`) when loading
2. Nice validation errors when dumping something unserializable
3. Better speed in both cases

It seems the best way for a user to accomplish this based on the docs is:

```python
import json

from pydantic import JsonValue, TypeAdapter

adapter = TypeAdapter(JsonValue)

def my_json_loads(s) -> JsonValue:
    return adapter.validate_json(s)

def my_json_dumps(x):
    try:
        return json.dumps(x)
    except TypeError:
        adapter.validate_python(x)
```

If they dig a bit deeper they might come up with this faster version of `my_json_dumps`:

```python
def my_json_dumps(x):
    try:
        return adapter.dump_json(x).decode()
    except pydantic_core.PydanticSerializationError:
        adapter.validate_python(x)
```

(Even knowing that the above is possible, a user might assume that `json.dumps` is faster than `adapter.dump_json` in the happy path because it looks simpler)

This is faster still:

```python
def my_json_dumps(x):
    try:
        return pydantic_core.to_json(x).decode()
    except TypeError:
        adapter.validate_python(x)
```

This seems like the fastest way to load:

```python
def my_json_loads(s) -> JsonValue:
    return cast(JsonValue, pydantic_core.from_json(s))
```

On the flip side, a user might do this which is way slower than the stdlib `json`:

```python
def my_json_loads(s) -> JsonValue:
    adapter = TypeAdapter(JsonValue)
    return adapter.validate_json(s)
```

Overall, if we expect that the main thing users will use `JsonValue` for (apart from just a type hint) is the use case I'm describing, then it seems best for pydantic to directly provide functions with the right interface and the ideal implementation. I might be overthinking this and I don't know if it's worth blocking releasing 2.5, but it seems that ideally pydantic would provide and recommend 'the right way' to do things the first time, and avoid a future where 2.6 has a note saying "We showed you how to do this in 2.5, but now you should do this instead". `TypeAdapter(JsonValue)` can still be documented for more exotic use cases, without implicitly recommending using it directly for the main use case where it's an implementation detail at best.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by alexmojaki** [comment]
Thinking about this some more, I may have been looking at it too narrowly. The equivalent of `json.loads/dumps` is probably not that useful to pydantic users who are generally trying to work with nice structured models and similar objects rather than raw dicts etc. I now think that the most common use for `JsonValue` may just be as the type of a field in a larger model containing a mix of structured and unstructured data, e.g:

```python
class Model(BaseModel):
    id: int
    name: str
    other_data: JsonValue  # previously this would likely have been `Any`
```

If that intuition sounds correct then this issue probably isn't very important. But then I'd suggest that the documentation gives an example like the above using a model, rather than a `TypeAdapter` which is more advanced/obscure (is it even mentioned under the Concepts docs?) and which users may have no interest in.

**Comment by sydney-runkle** [comment]
@alexmojaki,

I think the main use case here will be that described in your second comment. I'll add an example using a `BaseModel` instead for consistency and clarity.

Thanks for the feedback on the clarity of the docs - always happy to improve on that front.

We used to have `TypeAdapter` in the `Usage` section, but now all of that info is in the `API Documentation` section. I do think it would be valuable to add a section back to the `Concepts` docs, which is where we moved a lot of the `Usage` info.

**Comment by sydney-runkle** [comment]
Added an issue here: https://github.com/pydantic/pydantic/issues/8051 for the `TypeAdapter` changes. Will address the `JsonValue` requests with this issue.

**Comment by alexmojaki** [comment]
That sounds good. I didn't mean for my second comment to completely replace the initial suggestion though - do you think it's best to discard the idea of providing something like these functions?

```python
def my_json_loads(s) -> JsonValue:
    return cast(JsonValue, pydantic_core.from_json(s))

def my_json_dumps(x):
    try:
        return pydantic_core.to_json(x).decode()
    except TypeError:
        adapter.validate_python(x)
```

The speed, validation errors, and return type still seem nifty and useful, even if it's not the main purpose of pydantic or `JsonValue`.

**Comment by sydney-runkle** [comment]
I see. At a first glance, I think the functions that you've outlined could be helpful for some use cases. I'm going to focus on the docs updates for 2.5 re `JsonValue`, but would be happy to discuss your helper functions after we get the new version across the line!

**Comment by sydney-runkle** [comment]
Addressed the docs request here: https://github.com/pydantic/pydantic/pull/8042

**Comment by dmontagu** [comment]
@alexmojaki I think you make reasonable points about the JSON loading functions, but I think the use of `JsonValue`/`JsonDict` will likely remain niche enough that it's not worth adding special functions for higher performance typed loading of those objects.

We used to have utils files and a tools package where it might have made sense to put things like this, but we intentionally removed those (in part I think to try to be a bit more narrow about the scope of what belongs in pydantic), and I think there are comments from Samuel in the code indicating we should do our best to not add anything more in those files. (And I don't disagree.)

On balance my opinion is that it probably doesn't make sense to add such functions, _unless_ there is significant user interest (e.g., an issue about this with ~5+ thumbs ups would convince me to reconsider).

**Comment by sydney-runkle** [comment]
@alexmojaki, would you like us to keep this issue open in the meantime?

**Comment by alexmojaki** [comment]
No. The original docs caused me to think too much in terms of `TypeAdapter(JsonValue)` and the functions were meant as an alternative to that. After we moved away from `TypeAdapter` then it was clear that this was at best *maybe hypothetically* useful and I just wanted to check what you guys think. @dmontagu's answer covered that well, happy to keep things focused until there's a real user request.
