### ISSUE TITLE
Validation fails with TypeError: datetime.date annotation with pandas.NaT input

### ISSUE THREAD

**Issue by hottwaj** [pydantic/pydantic#8039]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Validation fails with a TypeError (instead of ValidationError) when a pandas.NaT value is passed as input to any field with datetime.date annotation

It seems under the hood pydantic interprets pandas.NaT as a float, tries to convert that to an int (presumably to treat it as a year or similar) and raises a TypeError during the process

Exception raised is:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[33], line 7
      4 class TestSchema(BaseModel):
      5     date: datetime.date
----> 7 TestSchema(**{'date': pandas.NaT})

File ~/.../site-packages/pydantic/main.py:164, in BaseModel.__init__(__pydantic_self__, **data)
    162 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    163 __tracebackhide__ = True
--> 164 __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)

TypeError: 'float' object cannot be interpreted as an integer
```

I noticed that the using `float('nan')` as input works as expected (i.e. produces ValidationError, not TypeError), so pandas.NaT must be a special type of float-like value that does not get caught by existing nan-detection logic.

Thanks :)

### Example Code

```Python
import datetime
import pandas
from pydantic import BaseModel
class TestSchema(BaseModel):
    date: datetime.date

TestSchema(**{'date': pandas.NaT})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.2.0
        pydantic-core version: 2.6.0
          pydantic-core build: profile=release pgo=true mimalloc=true
               python version: 3.10.2 (main, Jan 28 2022, 16:19:08) [GCC 10.3.0]
                     platform: Linux-5.15.0-87-generic-x86_64-with-glibc2.31
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
Hi @hottwaj,

Thanks for reporting this. That behavior is a bit odd - given that we aren't going to build in logic to check against pandas types within `pydantic`, I think the best solution here is to add a field validator on your `date` field that checks for input of type `pandas.NaT` and converts that to `float('nan')` or something similar.

**Comment by rmnldwg** [comment]
I just ran into this issue, too. It took me quite some time to figure out what was going on, given the unspecific and misleading error message. I understand that you won't check against pandas types, but shouldn't the error message still be informative of *what* went wrong?

In general, if pydantic receives and instance of the wrong type for a field, it says so. For example:

```python
from pydantic import BaseModel, PastDate

class MyType:
    """Some type pydantic obviously won't explicitly check against."""
    pass

class MyModel(BaseModel):
    """A normal model."""
    foo: PastDate

# this will throw a very clear and informative error
MyModel(foo=MyType())
#> foo
#>   Input should be a valid date [type=date_type, input_value=<__main__.MyType object at 0x7d1bb50d6380>, input_type=MyType]
#>     For further information visit https://errors.pydantic.dev/2.11/v/date_type
```

Why does this not work with pandas' `NaT`? And shouldn't it?

For a little more context: If the type annotation is something basic like `int`, then passing `pandas.NaT` is not a problem and *will* throw the correct and helpful error. So, this seems to only happen with the validation logic of dates.
