### ISSUE TITLE
TypeAdapter performs strict type checking by default and regardless of strict argument

### ISSUE THREAD

**Issue by aidanm96** [pydantic/pydantic#8057]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We are in the process of updating the dependencies of our API (which uses fastapi) including migrating from pydantic v1 to v2. After making the necessary changes we noticed type coercion of our request bodies (which use pydantic models) appears to be strictly enforced. From what I have read of the pydantic documentation, it appears strict enforcement is not the intended default behaviour. I looked into [how fastapi is performing the validation](https://github.com/tiangolo/fastapi/blob/480620372a662aa9025c47410fbc90a255b2fc94/fastapi/_compat.py#L125) and it appears to be using a `TypeAdapter`.

The minimal example I have included results in the following error regardless of whether the `strict=False` argument is or is not included:
```
    output = type_adapter.validate_python(input, strict=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidan/Development/experiment/pydantic-demo/venv/lib/python3.11/site-packages/pydantic/type_adapter.py", line 283, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for dict[str,str]
age
  Input should be a valid string [type=string_type, input_value=27, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
```

My expectation is that by default (and with the `strict=False` argument included) I would expect the `int` to be coerced to a `str` rather then resulting in a `ValidationError`. Am I misunderstanding the intended behaviour?

### Example Code

```Python
from pydantic import TypeAdapter

type_adapter = TypeAdapter(dict[str, str])

input = {"age": 27}

output = type_adapter.validate_python(input, strict=False)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/aidan/Development/experiment/pydantic-demo/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Jul 28 2023, 16:05:56) [GCC 11.3.0]
                     platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0
```

**Comment by Viicos** [comment]
You probably need to set `coerce_numbers_to_str`: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.coerce_numbers_to_str

**Comment by sydney-runkle** [comment]
Exactly right, @Viicos!
