### ISSUE TITLE
Inferred nested generic fails validation.

### ISSUE THREAD

**Issue by zakstucke** [pydantic/pydantic#8071]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When nesting generic models, unless the inner model's type is also concretely typed the outer validation fails. 

It's trivial to fix for this simple example, but for more complex/dynamic cases I haven't found any way of getting round this without coming up with something outside of pydantic.

```
Runtime type is 'Inner'
Traceback (most recent call last):
  File "repo/ptest.py", line 41, in <module>
    fails = Holder[int](inner=inferred)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repo/venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Holder[int]
inner
  Input should be a valid dictionary or instance of Inner[int] [type=model_type, input_value=Inner(inner=1), input_type=Inner]
    For further information visit https://errors.pydantic.dev/2.4/v/model_type
```

### Example Code

```Python
import typing as tp

from pydantic import BaseModel

T = tp.TypeVar("T")


class Inner(BaseModel, tp.Generic[T]):
    inner: T


class Holder(BaseModel, tp.Generic[T]):
    inner: Inner[T]


inferred = Inner(inner=1)
tp.reveal_type(inferred)  # Type of "inferred" is "Inner[int]" (Pylance)

works = Holder[int](inner=Inner[int](inner=1))
fails = Holder[int](inner=inferred)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: repo/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.1-arm64-arm-64bit
             related packages: mypy-1.6.1 pyright-1.1.335 typing_extensions-4.8.0 email-validator-2.1.0 fastapi-0.103.2
```

**Comment by sydney-runkle** [comment]
Hi @zakstucke,

Thanks for reporting this. I'm inclined to think this is not a bug due to the fact that `typing` generics don't support `isinstance` or `issubclass` checks, so `pydantic` doesn't support these either.

From the `pydantic` docs on [generic models](https://docs.pydantic.dev/dev/concepts/models/#generic-models):
> While it may not raise an error, we strongly advise against using parametrized generics in isinstance checks.
For example, you should not do isinstance(my_model, MyGenericModel[int]). However, it is fine to do isinstance(my_model, MyGenericModel). (Note that, for standard generics, it would raise an error to do a subclass check with a parameterized generic.)
If you need to perform isinstance checks against parametrized generics, you can do this by subclassing the parametrized generic class. This looks like class MyIntModel(MyGenericModel[int]): ... and isinstance(my_model, MyIntModel).

For example, in your use case:
```py
print(isinstance(Inner(inner=1), Inner[int]))
#> False
```
helps to explain why you're getting the validation error that you are.

The initial (ish) decision to not support this kind of behavior is discussed here: https://github.com/pydantic/pydantic/pull/4970#issuecomment-1405342820.

Happy to discuss further, but for now, the behavior you're seeing can be explained by the fact that `pydantic` has mirrored the support / behavior of standard `typing` generics.

**Comment by zakstucke** [comment]
Hi @sydney-runkle, whilst the links you referenced are likely the cause of the internal behaviour, I do believe this is a bug / undesirable behaviour. 

A perfectly valid datastructure fails because a manual type was not added to `Inner`, where `Inner` could infer the type itself from it's attribute `inner`. 

To put it another way, this also works:
```Python
Holder[int](inner=Inner(inner=1).model_dump())
```

Which continues to show the strangeness of `Inner(inner=1)` failing. 

In my use case, `Inner` objects come in externally and are validated without static knowledge of the type, only at `Holder` creation is static knowledge of the type known, meaning statically typing `Inner` in my scenario is not just verbose but also not possible.  Removing the generic is also not possible as type hinting on the nested object from the `Holder` is required.

At the minute the only solution I can come up with that doesn't cause a performance hit is converting `Inner` to a dataclass to avoid pydantic validation.

**Comment by zakstucke** [comment]
@sydney-runkle I also forgot to mention this is a regression from V1, the same example in 1.10.13 works fine:
```Python
import typing as tp

from pydantic.generics import GenericModel as BaseModel

T = tp.TypeVar("T")


class Inner(BaseModel, tp.Generic[T]):
    inner: T


class Holder(BaseModel, tp.Generic[T]):
    inner: Inner[T]


inferred = Inner(inner=2)
tp.reveal_type(inferred)  # Type of "inferred" is "Inner[int]" (Pylance)

works = Holder[int](inner=Inner[int](inner=1))
works = Holder[int](inner=inferred)
```

**Comment by sydney-runkle** [comment]
Hi @zakstucke,

Indeed, this behavior was different in V1. We changed the behavior of generic models a bit as to more closely match that of standard (`typing`) generics.

In the case of standard generics, it makes more sense to not support `isinstance` and `issubclass` checks, as the behavior of a type `List[int]` object is no different than that of a type `List` object.

However, in our case, parametrized generics are subclasses. Thus, there can be different behavior attached to a parametrized generic model, say `MyModel[int]` compared to the unparametrized `MyModel`. I understand, thus, your desire to support `isinstance` and `issubclass` checks here. As your case shows, a `ValidationError` is raised when this kind of check fails.

Also to your point, it's a bit counterintuitive that the dumped data validates correctly compared to that which is also valid, but stored in an unparametrized `Inner` instance.

One thing that has been mentioned by the team thus far is that a change in this behavior could wait until V3 when we can restructure some of the Generic behavior in a more significant way. That being said, I have noticed that many people have requested this kind of change take place in V2 (which is what I assume you're asking for). 

Happy to explore more what a solution to this might look like, keeping in mind that we want to keep changes as performant and non-breaking as possible.

**Comment by zakstucke** [comment]
I was actually thinking of a slightly different behaviour to what I understand you to be saying: inferring `Inner[int]` subclass from the `T` value passed into `Inner` when `Inner` is unparameterized, before taking into account the `Holder`. I suppose I'm saying how static analysers handle the shown example, rather than how pydantic follows the run time semantics currently as you say. However I can imagine there could be a lot of edge cases and might not be the best approach after thinking more deeply and your comments. 

If there was a way to get around it concisely in my case where `Inner[T]` isn't known until later that would be awesome, I spent a while battling it yesterday and came to the conclusion I had to revert to a dc and forgo validating `T` to the outer `Holder`.  (external users operate on this type so the `model_dump()` workaround isn't something I could use either)

**Comment by dmontagu** [comment]
The reason that this worked in v1 but not in v2 is that in v2 we explicitly disallow non-subclass model instances, whereas in v1 we would just dump the data and revalidate it in that case.

You can replicate this behavior with validators, here is an example of how you could use a reusable base class to get this behavior for your generics:
```python
import typing as tp

from pydantic import BaseModel, model_validator, ValidationError

T = tp.TypeVar("T")


class LaxGeneric(BaseModel):  # Could rename this.. not sure what the best name is.
    @model_validator(mode='wrap')
    @classmethod
    def dump_on_non_subclass(cls, values, handler):
        """
        This validator is used to revalidate the dumped data if you get a non-parametrized generic
        as an input to a parametrized input field of a type that is a subclass of `LaxGeneric`. 
        """
        # The approach used here assumes that validation won't have side-effects, so it's safe to attempt to run twice.
        # If that is wrong, you should use the logic from the exception handler below prior to the first attempt to use
        # the handler.
        try:
            return handler(values)
        except ValidationError as exc:
            if not isinstance(values, BaseModel):
                # If a basemodel wasn't passed, validation didn't fail due to a non-parametrized generic instance
                raise

            if not any(e['type'] == 'model_type' and e['loc'] == () for e in exc.errors()):
                # Only try to handle errors that are model_type errors
                # (Might need to tweak the condition a bit... but this worked/made sense to me)
                raise

            origin = cls.__pydantic_generic_metadata__.get('origin')  # the non-parametrized version of this class
            if origin is None:
                # This is just to handle the case where you accidentally create a subclass of this that is not generic
                # and attempt to instantiate it. You could drop this branch if you won't ever do that.
                raise
            if not isinstance(values, origin):
                # This means the input data was not an instance of a subclass of the non-parametrized version of this
                # class, so it probably makes sense to just raise the error. If you wanted to be even more lax, you
                # could drop this condition (and most of the logic related to generic origins, etc.) and it will
                # always attempt to revalidate the dumped data.
                raise

            # This assumes that validating dumped data is idempotent, but if it isn't, it's not clear to me what you'd
            # want to do here anyway. But you could change the logic as necessary for your use case.
            return handler(values.model_dump())


class Inner(LaxGeneric, tp.Generic[T]):
    inner: T


class Holder(LaxGeneric, tp.Generic[T]):
    inner: Inner[T]


inferred = Inner(inner=2)
tp.reveal_type(inferred)  # Type of "inferred" is "Inner[int]" (Pylance)
#> Runtime type is 'Inner'


works = Holder[int](inner=Inner[int](inner=1))
works = Holder[int](inner=inferred)
print(works)
#> inner=Inner[int](inner=2)
```

There are different ways we could make this work better but likely involve changes in pydantic-core for performance reasons. Also will likely interact closely with any changes that make generics behave more like standard library typing generics (e.g., not using different subclasses for different parametrizations).

So I don't know that I can give a timeline for improving this behavior at the library level, other than I'd hope that we can improve it as part of the v3 release at the latest (but that is currently unplanned).

**Comment by zakstucke** [comment]
@dmontagu I can confirm this works as a solution for my current use case. Thanks!

**Comment by sydney-runkle** [comment]
@zakstucke, would you like to leave this issue open? We could mark it with a `v3` tag to reflect the fact that we'll likely make some changes to generic behavior in v3.

**Comment by nilsso** [comment]
Seems static/class method constructor-helpers have the same issue, except where explicit typing doesn't solve it.

```python
from typing import reveal_type
from pydantic import BaseModel


class Foo[T](BaseModel):
    value: T

    @staticmethod
    def new(value: T):
        return Foo[T](value=value)


foo1 = Foo[int](value=1)
# Pyright shows: 👍 "Type of 'foo1' is 'Foo[int]'"
#        Prints: 👍 "Runtime type is 'Foo[int]'"
reveal_type(foo1)

foo2 = Foo[int].new(1)
# Pyright shows: 👍 "Type of 'foo2' is 'Foo[int]'"
#        Prints: 👎 "Runtime type is 'Foo'"
reveal_type(foo2)


class Bar(BaseModel):
    foo: Foo[int]


Bar(foo=foo1)  # 👍
Bar(foo=foo2)  # 👎 "foo: Input should be a valid dictionary or instance of Foo[int]"
```

Only solution in this case is for `Foo` to subclass that `LaxGeneric` example.

**Comment by alita-moore** [comment]
I just don't use pydantic when there are generics involved because it's too aggressive and the error messages offer little to no insights.

**Comment by rmorshea** [comment]
I would suggest adding and documenting `LaxGeneric` in V2 until this is ironed out in V3. My users are scientists who've had a pretty hard time understanding this behavior. As a result, I've had to apply `LaxGeneric` to all my user-facing models.
