### ISSUE TITLE
(🐞)  `RecursionError` with recursive type (annotation, dataclass, BaseModel, TypeAdapter)

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#8073]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Affects both 2.4.2 and  2.5.0b1

### Example Code

```Python
from pydantic import TypeAdapter

Recursive = list["Recursive"] | int

TypeAdapter(Recursive)
```

### Python, Pydantic & OS Version

```Text
👉 python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.5.0b1                                                                    
        pydantic-core version: 2.14.1                                                                     
          pydantic-core build: profile=release pgo=true                                                   
                 install path: C:\Users\KotlinIsland\projects\test-python\.venv\Lib\site-packages\pydantic
               python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: basedmypy-2.2.1 typing_extensions-4.8.0
```
```

**Comment by Viicos** [comment]
Assuming you meant `TypeAdapter(Recursive)`, see https://github.com/pydantic/pydantic/issues/8021

**Comment by KotlinIsland** [comment]
@Viicos Could pydantic show [this link](https://docs.pydantic.dev/latest/concepts/types/#named-recursive-types) in an error message?

Maybe the mypy plugin could warn about it?

Also, could this be resolved so that native recursive type aliases work?

**Comment by Viicos** [comment]
> Could pydantic show [this link](https://docs.pydantic.dev/latest/concepts/types/#named-recursive-types) in an error message?

This sounds like a great idea as it was reported a couple times now and `TypeAliasType` is brand new and still unknown to most people.

> Also, could this be resolved so that native recursive type aliases work?

I think the reason it is not supported is it will require some work to find the forward reference to `"Recursive"`

**Comment by Danipulok** [comment]
Have the same issue with following code:

```python
from pydantic import BaseModel

JsonType = None | int | str | bool | list["JsonType"] | dict[str, "JsonType"]

class Response(BaseModel):
    data: JsonType = None
```

I will just leave this here, since this issue is open and related.
This leads to a `RecursionError: maximum recursion depth exceeded` too on the latest pydantic version `2.10.1`.
Just one more use case for when (or if) it gets resolved to test against this code too.

**Comment by Viicos** [comment]
We will track this in https://github.com/pydantic/pydantic/issues/10873. Note that we strongly recommend using `TypeAliasType` instead (as suggested in https://github.com/pydantic/pydantic/issues/8021). Supporting this kind of alias is:
- hard if not impossible
- can lead to confusing results (see https://github.com/pydantic/pydantic/issues/10873#issuecomment-2494330240).
