### ISSUE TITLE
Documentation showing use of deprecated conlist function

### ISSUE THREAD

**Issue by calswbin** [pydantic/pydantic#8076]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Documentation cites the use of conlist https://docs.pydantic.dev/dev/api/types/#pydantic.types.conlist

This function has however been deprecated, referencing an open github issue in the exception.

### Example Code

```Python
from pydantic import BaseModel, conlist

class Foo(BaseModel):
    bar: conlist(str, unique_items=True)
```

### Python, Pydantic & OS Version
```
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
               python version: 3.11.2 (main, Feb 22 2023, 16:37:15) [GCC 11.3.0]
                     platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.0.3 typing_extensions-4.8.0 fastapi-0.104.0
```

**Comment by sydney-runkle** [comment]
Hi @calswbin,

Thanks for catching this. I'll make an update to the docs today 👍. We appreciate the report :).

**Comment by calswbin** [comment]
My pleasure :) thanks for the speedy response!

**Comment by sydney-runkle** [comment]
Hey @calswbin,

Taking a closer look at this, it looks like the `unique_items` field has been deprecated, but not the `conlist` type. Given this, what part of the docs are you requesting we change?

**Comment by calswbin** [comment]
Ah yes! Exactly. My apologies
