### ISSUE TITLE
Constrainted datetime based on timezone offset / UTCDateTime 

### ISSUE THREAD

**Issue by bram-tv** [pydantic/pydantic#8088]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This is basically the same request as #4385 but that was closed as duplicate of #4330 (which is closed now too) but several things have changed since then so creating a new issue.

Summary of the request: being able to add a constraint on the timezone offset of an AwareDatetime.

Support for constraining the timezone offset was added in pydantic-core in May 2023 with 
 https://github.com/pydantic/pydantic-core/pull/653

So far I can see two ways to achieve this:

- Levering the `tz_constraint` option from pydantic-core by extending from AwareDatetime and overriding `__get_pydantic_core_schema__`,
<details>
  <summary>Example code</summary>

```python
from typing import Any
from datetime import datetime, timezone, timedelta
from pydantic import BaseModel, AwareDatetime
from pydantic_core import core_schema

# Load GetCoreSchemaHandler via try/except because it was made public in v2.4.0
try:
    from pydantic.annotated_handlers import GetCoreSchemaHandler
except:
    from pydantic._internal._annotated_handlers import GetCoreSchemaHandler


class UTCAwareDatetime(AwareDatetime):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: type[Any], handler: GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        if cls is source:
            # used directly as a type
            return core_schema.datetime_schema(tz_constraint=0)
        else:
            schema = handler(source)
            _check_annotated_type(schema["type"], "datetime", cls.__name__)
            schema["tz_constraint"] = 0
            return schema

    def __repr__(self) -> str:
        return "UTCAwareDatetime"


class TestModel(BaseModel):
    created_at: UTCAwareDatetime


now = datetime.now(tz=timezone(timedelta(seconds=1800)))

model = TestModel(created_at=now)
print(model.model_dump_json())
```

</details>

- Using an `AfterValidator` to do the extra validation
<details>
  <summary>Example code</summary>

```python
from typing_extensions import Annotated
from datetime import datetime, timezone, timedelta
from pydantic import BaseModel, AwareDatetime
from pydantic.functional_validators import AfterValidator


def check_tz(v: datetime):
    assert v.utcoffset() == timedelta(seconds=0)
    return v


UTCAwareDatetime = Annotated[AwareDatetime, AfterValidator(check_tz)]


class TestModel(BaseModel):
    created_at: UTCAwareDatetime


now = datetime.now(tz=timezone(timedelta(seconds=1800)))

model = TestModel(created_at=now)
print(model.model_dump_json())
```
</details>

In both cases there is validation error (as expected), and the error from pydantic-core is superior.

Now back to the future request: Make it easier to use the `tz_constraint` option of pydantic-core to restrict the tz offset of a datetime.
Could be via:
- an extra type? (UTCDatetime? RestrictedTzOffsetAwareDatetime?)
- extend `Field` to support `tz_constraint`?
- ...

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
I think we could make use of annotated-types' [`Timezone`](https://github.com/annotated-types/annotated-types#timezone) constraint. It might already be supported, but I can't find any reference in Pydantic docs

**Comment by samuelcolvin** [comment]
I'm happy to add this via full support for the annotated-types type.

@bram-tv by the way, you can use custom errors to make the errors nicer.

**Comment by sydney-runkle** [comment]
@bram-tv,

Any interest in opening a PR to add support for this?

**Comment by Zidane786** [comment]
I would appreciate it if @sydney-runkle , @bram-tv  could provide me with some context regarding the implementation of this Feature. Specifically, I am interested in understanding the various Cases that need to be covered and the desired outcomes we aim to achieve by implementing these constraint types.

**Comment by hirotasoshu** [comment]
@Zidane786  @samuelcolvin  @bram-tv It would be great if this constraint will support not only specifying one specific timezone, but also specifying a UTC offset range or a list of supported timezones. Example of use: postgres supports timezones with UTC offset from -12:00 to +13:00. If we pass a datetime with a utc offset that goes beyond this limit, we get an error. For myself, so far I've done something like this
```python
from datetime import datetime, timedelta
from typing import Annotated

from pydantic import AfterValidator


def check_timezone_utcoffset_range(v: datetime) -> datetime:
    utc_offset = v.utcoffset()
    if utc_offset is not None and (
        utc_offset < timedelta(days=-1, seconds=43200)
        or utc_offset > timedelta(seconds=46800)
    ):
        raise ValueError("timezone utc offset should be in range from -12:00 to +13:00")

    return v


DatetimeRestrictedUtcOffset = Annotated[
    datetime, AfterValidator(check_timezone_utcoffset_range)
]
```

**Comment by ChrisPappalardo** [comment]
At PyCon2024, taking a look at this.

**Comment by sydney-runkle** [comment]
@Zac-HD,

We're looking at adding support for the `Timezone` class from `annotated-types`. I see that type doesn't support integer time offsets - what would you think about adding support for that to `annotated-types`? Would it make more sense to add that in a new offset type? Thanks for your feedback!

Also happy to chat in person if you'd like, we're in room 321.

**Comment by sydney-runkle** [comment]
Here's the approach we talked about :). This is a super cool way to combine 

```py
from pydantic import TypeAdapter, GetCoreSchemaHandler
from typing_extensions import Annotated
from datetime import datetime
from pydantic._internal._core_utils import pretty_print_core_schema
from dataclasses import dataclass
from typing import Any
from pydantic_core import CoreSchema, core_schema
from functools import partial


def my_validator_function(tz_constraint: str, value: datetime, handler):
    # pre logic

    validated_dt = handler(value)

    # post logic

    return validated_dt


@dataclass(frozen=True)
class MyDatetimeValidator:
    tz_constraint: str

    def __get_pydantic_core_schema__(self, source_type: Any, handler: GetCoreSchemaHandler) -> CoreSchema:
        return core_schema.no_info_wrap_validator_function(
            partial(my_validator_function, self.tz_constraint), handler(source_type)
        )


ta = TypeAdapter(Annotated[datetime, MyDatetimeValidator('UTC')])
print(pretty_print_core_schema(ta.core_schema))
"""
{
    'type': 'function-wrap',
    'function': {
        'type': 'no-info',
        'function': functools.partial(<function my_validator_function at 0x104a73d90>, 'UTC')
    },
    'schema': {'type': 'datetime', 'microseconds_precision': 'truncate'}
}
"""

my_dt = ta.validate_python(datetime.now())
print(my_dt)
# > 2024-05-20 14:42:15.066963
```

**Comment by Zac-HD** [comment]
> We're looking at adding support for the `Timezone` class from `annotated-types`. I see that type doesn't support integer time offsets - what would you think about adding support for that to `annotated-types`? 

Offsets are not timezones, so I'd oppose such a change.

> Would it make more sense to add that in a new offset type?

...and offsets are _very very very rarely_ the right solution to a problem, making an Offset type into [an attractive nuisance of an interface](https://blog.ganssle.io/articles/2023/01/attractive-nuisances.html).  I'd oppose adding one to `annotated-types`, and would recommend that Pydantic require would-be users of offsets to implement that for themselves.

------

> It would be great if this constraint will support not only specifying one specific timezone, but also specifying a UTC offset range or a list of supported timezones. Example of use: postgres supports timezones with UTC offset from -12:00 to +13:00. If we pass a datetime with a utc offset that goes beyond this limit, we get an error.

IMO this is a nasty bug in Postgres; [there are timezones with a +14 UTC offset](https://en.wikipedia.org/wiki/Time_in_Kiribati), and other historical examples still might need to be represented in a database.  I recommend reporting a bug to your database vendor.

More generally, supporting only some timezones is somewhere between an attractive nuisance and a code smell.  If you really really need to, you can use a union of types: `Annotated[datetime, Timezone("Australia/Sydney")] | Annotated[datetime, Timezone("America/Los_Angeles")] | ...` - the inelegant syntax accurately reflects underlying design problems.

**Comment by sydney-runkle** [comment]
Going to close this as completed now - the given example does a great job at showing how to get the desired behavior.
