### ISSUE TITLE
Mypy field typing error (Untyped fields disallowed) since pydantic V2

### ISSUE THREAD

**Issue by mickael-ousset-wmx** [pydantic/pydantic#8089]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, I recently upgraded pydantic to version 2.4.2, using pydantic-core 2.10.2. Since then, I have had an error with mypy (Untyped fields disallowed). When I type an attribute in a superclass, I get a type error when initializing this attribute in the child class, as if mypy couldn't understand that the typing had already been done. Retyping this attribute in the subclass corrects the problem but I wanted to know if there wasn't a cleaner way of doing it?
Thanks in advance !

### Example Code

```Python
from pydantic import BaseModel


class A(BaseModel):
    value: int


class B(A):
    value = 5
```

### Python, Pydantic & OS Version

```Text
pydantic 2.4.2
pydantic-core 2.10.2
mypy 1.7.0
```

**Comment by Viicos** [comment]
As the raised error says:

`pydantic.errors.PydanticUserError: Field 'a' defined on a base class was overridden by a non-annotated attribute. All field definitions, including overrides, require a type annotation.`

You need to provide annotations for all your fields

**Comment by mickael-ousset-wmx** [comment]
How do you achieve this? When I run mypy I only get the message error: `Untyped fields disallowed [pydantic-field]` without any further information. What I'm having trouble understanding is that this isn't a replacement of the variable but just an assignment. Do you know if this is a documented change in the new version? I didn't have this problem with pydantic V1.

**Comment by mickael-ousset-wmx** [comment]
I have found [what I was looking for](https://docs.pydantic.dev/latest/errors/usage_errors/#model-field-overridden), thanks for your help. I'm always interested to know which command you used to get the error information!

**Comment by Viicos** [comment]
Just run your code snippet, you'll get the error as soon as you define `B`. Of course mypy isn't a runtime tool so you won't get the Pydantic exception by just running it.

> Do you know if this is a documented change in the new version?

I don't find anything about this in the [migration guide](https://docs.pydantic.dev/latest/migration/), you can open a PR to add an entry if you'd like to.

**Comment by mickael-ousset-wmx** [comment]
Ok thank you for everything ! Yes I have read it, it seems my problem wasn't really linked with the V2 because I have found the explanation elsewhere.
