### ISSUE TITLE
Allowing to raise validation errors with a custom location

### ISSUE THREAD

**Issue by sinaatalay** [pydantic/pydantic#8092]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I would like to raise exceptions with a custom location.

An example use case:
```python
from pydantic import BaseModel, Field, model_validator, ValidationError
from typing import Literal


class MyModel(BaseModel):
    uppercase_value: Literal["A", "B"]


class AnotherModel(BaseModel):
    lowercase_value: Literal["a", "b"]
    another_field: MyModel

    @model_validator(mode="after")
    def validate_value_1_of_mymodel(cls, model):
        if model.lowercase_value == "a":
            if model.another_field.uppercase_value != "A":
                raise ValueError("uppercase_value must be A if lowercase_value is a")
        elif model.lowercase_value == "b":
            if model.another_field.uppercase_value != "B":
                raise ValueError("uppercase_value must be B if lowercase_value is b")

        return model


my_data = {"lowercase_value": "a", "another_field": {"uppercase_value": "B"}}
try:
    AnotherModel(**my_data)
except ValidationError as e:
    error_dict = e.errors()[0]
    location = error_dict["loc"]
    print(f"Error in {location}") # Error in ()
```

In the example above, I raise an exception for the data in the position `another_field.uppercase_value`. However, Pydantic doesn't know about this position since I do this check in the model validator of `AnotherModel`. I have to do that check there because I need `lowecase_value` to check `another_field.uppercase_value`. So, to Pydantic, the location of this error message is the root. However, it's not for this specific case.

I parse error messages of Pydantic to point the users to the problematic location directly. I cannot do this in these kinds of validations without specifying the location manually in the error message. Something like this would be very nice:

```python
raise PydanticCustomError("error message", loc="another_field.uppercase_value")
```

Which can overwrite the default `loc` that Pydantic computes.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @sinaatalay,

Great question. We provide support for customizing error messages. If you check out our docs on customzing error messages [here](https://docs.pydantic.dev/dev/errors/errors/#customize-error-messages), you'll find an example on how to customize the `loc` presentation. Though this isn't exactly your use case, I think it provides some good context as to how you could implement this request!

Perhaps you could attach a flag value to your `ValueError` that you check for when modifying the `errors()` output...

Let me know if you have any other questions 😄.

**Comment by hail-pas** [comment]
> Hi @sinaatalay,
> 
> Great question. We provide support for customizing error messages. If you check out our docs on customzing error messages [here](https://docs.pydantic.dev/dev/errors/errors/#customize-error-messages), you'll find an example on how to customize the `loc` presentation. Though this isn't exactly your use case, I think it provides some good context as to how you could implement this request!
> 
> Perhaps you could attach a flag value to your `ValueError` that you check for when modifying the `errors()` output...
> 
> Let me know if you have any other questions 😄.

Hi @sydney-runkle

**Comment by hail-pas** [comment]
> Hi @sinaatalay,
> 
> Great question. We provide support for customizing error messages. If you check out our docs on customzing error messages [here](https://docs.pydantic.dev/dev/errors/errors/#customize-error-messages), you'll find an example on how to customize the `loc` presentation. Though this isn't exactly your use case, I think it provides some good context as to how you could implement this request!
> 
> Perhaps you could attach a flag value to your `ValueError` that you check for when modifying the `errors()` output...
> 
> Let me know if you have any other questions 😄.

Hi @sydney-runkle,
I have checked the docs, seems there isn't a way to modify the loc value, such as use field title as loc value. examples:
`python
from pydantic import BaseModel, Field, ValidationError

class User(BaseModel):
    username: str = Field(..., min_length=3, max_length=50, title="用户名", description="用户名")

try:
    User(username="12")
except ValidationError as e:
    print(e.errors())

"""
[{'type': 'string_too_short', 'loc': ('username',), 'msg': 'String should have at least 3 characters', 'input': '12', 'ctx': {'min_length': 3}, 'url': 'https://errors.pydantic.dev/2.7/v/string_too_short'}]
"""
`

How can I change the **'loc': ('username', )**  to **'loc': ('用户名')**

Thanks a lot!

**Comment by sydney-runkle** [comment]
This is pretty hacky, and I don't think I would recommend this as a best practice, but the general idea would be that you want to pull information out of the `User.model_fields` data in order to transform the errors:

```py
from typing import Any, Dict, List, Tuple, Union

from pydantic import BaseModel, Field, ValidationError

class User(BaseModel):
    username: str = Field(..., min_length=3, max_length=50, title="用户名", description="用户名")

def loc_to_dot_sep(loc: Tuple[Union[str, int], ...]) -> str:
    path = ''
    for i, x in enumerate(loc):
        if isinstance(x, str):
            path += User.model_fields[x].title
        elif isinstance(x, int):
            path += f'[{x}]'
        else:
            raise TypeError('Unexpected type')
    return path


def convert_errors(e: ValidationError) -> List[Dict[str, Any]]:
    new_errors: List[Dict[str, Any]] = e.errors()
    for error in new_errors:
        error['loc'] = loc_to_dot_sep(error['loc'])
    return new_errors

try:
    User(username="12")
except ValidationError as e:
    print(convert_errors(e))

"""
[{'type': 'string_too_short', 'loc': '用户名', 'msg': 'String should have at least 3 characters', 'input': '12', 'ctx': {'min_length': 3}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_short'}]"""
```

Probably a better approach would be to use custom errors: https://docs.pydantic.dev/dev/errors/errors/#custom-errors.

**Comment by hail-pas** [comment]
> This is pretty hacky, and I don't think I would recommend this as a best practice, but the general idea would be that you want to pull information out of the `User.model_fields` data in order to transform the errors:
> 
> ```python
> from typing import Any, Dict, List, Tuple, Union
> 
> from pydantic import BaseModel, Field, ValidationError
> 
> class User(BaseModel):
>     username: str = Field(..., min_length=3, max_length=50, title="用户名", description="用户名")
> 
> def transform_loc(loc: Tuple[Union[str, int], ...]) -> str:
>     path = ''
>     for i, x in enumerate(loc):
>         if isinstance(x, str):
>             path += User.model_fields[x].title
>         elif isinstance(x, int):
>             path += f'[{x}]'
>         else:
>             raise TypeError('Unexpected type')
>     return path
> 
> 
> def convert_errors(e: ValidationError) -> List[Dict[str, Any]]:
>     new_errors: List[Dict[str, Any]] = e.errors()
>     for error in new_errors:
>         error['loc'] = transform_loc(error['loc'])
>     return new_errors
> 
> try:
>     User(username="12")
> except ValidationError as e:
>     print(convert_errors(e))
> 
> """
> [{'type': 'string_too_short', 'loc': '用户名', 'msg': 'String should have at least 3 characters', 'input': '12', 'ctx': {'min_length': 3}, 'url': 'https://errors.pydantic.dev/2.8/v/string_too_short'}]"""
> ```
> 
> Probably a better approach would be to use custom errors: https://docs.pydantic.dev/dev/errors/errors/#custom-errors.

Thanks for the reply, but what I want is a global change, not for a single field. This means I have to raise a custom error for every field, and that's a lot of work.

**Comment by sydney-runkle** [comment]
@hail-pas,

Thanks for your feedback - I don't know of a way at the moment. I'll chat with the team tomorrow, and see what they think. It's possible that this merits a new feature request issue, but I'll keep you updated.

**Comment by hail-pas** [comment]
> @hail-pas,
> 
> Thanks for your feedback - I don't know of a way at the moment. I'll chat with the team tomorrow, and see what they think. It's possible that this merits a new feature request issue, but I'll keep you updated.

Thank you for the hard work you all have done.  I'll keep following

**Comment by sydney-runkle** [comment]
Alright, I opened https://github.com/pydantic/pydantic/issues/9686 which should cover this case.
