### ISSUE TITLE
`CallableDiscriminator` isn't in the docs -- note in release notes (it's `Discriminator`)

### ISSUE THREAD

**Issue by psychedelicious** [pydantic/pydantic#8095]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It's a trap!

The release notes for 2.5.0 say `CallableDiscriminator`, but the class was renamed to `Discriminator` before release - so searching the docs for "CallableDiscriminator" doesn't find it.

Maybe worth a note in the line of the release notes to indicate it is now called `Discriminator` to direct users to this cool new feature.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @psychedelicious,

Thanks for bringing this up. I'll have a fix up for this tomorrow!

**Comment by sydney-runkle** [comment]
I've fixed the `HISTORY.md` file here: d7384e58239bfd41dfb4ba5a46d2bc72dc382421.

I also fixed the release notes to include this 👍. Going to go ahead and close this, but marking this as an issue that's part of our 2.5.1 milestone 👍.
