### ISSUE TITLE
Overridden untyped ClassVar get an `error_untyped_fields` with mypy plugin

### ISSUE THREAD

**Issue by vincent-hachin-wmx** [pydantic/pydantic#8107]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Untyped overridden fields are forbidden and an error is thrown on execution and in mypy. However, untyped ClassVar are allowed in a BaseModel, but it seems that this case is not properly handeled by the mypy plugin [here](https://github.com/pydantic/pydantic/blob/4a2a5bb66e168bd1c882facc105f0c18a60a517b/pydantic/mypy.py#L660) .

The example code below run fine, but a mypy error `error: Untyped fields disallowed` is thrown.

### Example Code

```Python
from typing import ClassVar
from pydantic import BaseModel

class Abstract(BaseModel):
    class_id: ClassVar

class Foo(Abstract):
    class_id = 1

print(Foo())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/vincent.hachin/.pyenv/versions/3.11.6/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  9 2023, 17:58:53) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.0-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 mypy-1.7.0
```

**Comment by sydney-runkle** [comment]
Hi @vincent-hachin-wmx,

Thanks for reporting this. This does look like a bug. Looks like you may have found the source of the problem. Are you interested in contributing a PR with a fix?

**Comment by vincent-hachin-wmx** [comment]
Hi, 
Sure I'll do a PR.

**Comment by vincent-hachin-wmx** [comment]
Hi @sydney-runkle,

I made a PR but I couldn't figure out how to add unit tests for the mypy plugin.
I guess the test should be added around here: https://github.com/pydantic/pydantic/blob/eb90b59e708ff8b22a0ac40fdb805236c81362de/tests/mypy/modules/plugin_fail_baseConfig.py#L95-L108

How to specify that a line should pass or throw a specific mypy error ?
