### ISSUE TITLE
Union of custom classes with pydantic 2.5 new smart union implementation

### ISSUE THREAD

**Issue by ogunoz** [pydantic/pydantic#8111]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We have two custom classes (not pydantic base model) that we use in pydantic models. We implemented `__get_pydantic_core_schema__` for those classes and we are defining them in a union e.g., `field: A | B`. We expect that the validations will be done from left to right so that correct one can be picked, but after the new smart union implementation it started failing in the first validator without checking the next one. If it is the expected behavior then i am kindly asking if anyone knows how to change the way we should implement `__get_pydantic_core_schema__`

I tried using plain or after validators instead of wrap validator in `__get_pydantic_core_schema__` however couldn't resolve it.

### Example Code

```Python
from pydantic import BaseModel
from typing import Any

class A:
    def __init__(self, uri: str):
        self._uri = uri

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: type[Any], handler: Callable[[Any], core_schema.CoreSchema]
    ) -> core_schema.CoreSchema:
        return core_schema.no_info_wrap_validator_function(
            cls._validate,
            core_schema.str_schema(),
            serialization=core_schema.to_string_ser_schema(),
        )

    @classmethod
    def _validate(cls, v: Any, _: Any) -> "A":
        if isinstance(v, A):
            return v
        if isinstance(v, str):
            cls._raise_for_wrong_schema(v)
            return cls(uri=v)
        else:
            raise TypeError("A or string required")

# Class B is the same where _raise_for_wrong_schema differs

class Model(BaseModel):
    a_field: A | B

model = Model(a_field=B("correct-schema-for-b"))

# Throws TypeError: A or string required
# Without even trying the validator of B
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.0
        pydantic-core version: 2.14.1
          pydantic-core build: profile=release pgo=true
                 install path: /SOME_PATH_HERE/.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:39:07) [Clang 11.1.0 ]
                     platform: macOS-13.2-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 fastapi-0.103.2
```

**Comment by FlorianWilhelm** [comment]
I got a similar problem with connection with "@model_validator(mode='wrap')".

**Comment by dmontagu** [comment]
I think the problem here is that in v2 we always bubble `TypeError`s up to the top. This change, along with its motivation, is documented in the migration guide here: https://github.com/pydantic/pydantic/blob/main/docs/migration.md#typeerror-is-no-longer-converted-to-validationerror-in-validators.

I think prior to this v2.5 release we were actually (unintentionally) mishandling this in the union validator — it shouldn't have been suppressing the raising of `TypeError` any more than if you had attempted to validate an `A` directly:

```python
from pydantic_core import core_schema

from pydantic import TypeAdapter
from typing import Any, Callable


class A:
    def __init__(self, uri: str):
        self._uri = uri

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: type[Any], handler: Callable[[Any], core_schema.CoreSchema]
    ) -> core_schema.CoreSchema:
        return core_schema.no_info_wrap_validator_function(
            cls._validate,
            core_schema.str_schema(),
            serialization=core_schema.to_string_ser_schema(),
        )

    @classmethod
    def _validate(cls, v: Any, _: Any) -> "A":
        if isinstance(v, A):
            return v
        if isinstance(v, str):
            cls._raise_for_wrong_schema(v)
            return cls(uri=v)
        else:
            raise TypeError("A or string required")


TypeAdapter(A).validate_python(1)
```
```
TypeError: A or string required
```
Note that if you change the `raise TypeError("A or string required")` to `raise ValueError("A or string required")` in the `_validate` method in this snippet, you get an actual `ValidationError`:
```python
pydantic_core._pydantic_core.ValidationError: 1 validation error for function-wrap[_validate()]
  Value error, A or string required [type=value_error, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/value_error
```

If you can change the `TypeError` to a `ValueError` I think this will resolve your issue. If this is problematic for some reason, we can try to find another workaround, but I think with your code as is, pydantic is behaving as intended.

@FlorianWilhelm this also explains why you are running into this with `@model_validator` — any time a `TypeError` is raised during validation, we raise it all the way up.

------

For anyone that wants to reproduce this, here's a self-contained version of @ogunoz's snippet:

```python
from pydantic_core import core_schema

from pydantic import BaseModel
from typing import Any, Callable


class A:
    def __init__(self, uri: str):
        self._uri = uri

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: type[Any], handler: Callable[[Any], core_schema.CoreSchema]
    ) -> core_schema.CoreSchema:
        return core_schema.no_info_wrap_validator_function(
            cls._validate,
            core_schema.str_schema(),
            serialization=core_schema.to_string_ser_schema(),
        )

    @classmethod
    def _validate(cls, v: Any, _: Any) -> "A":
        if isinstance(v, A):
            return v
        if isinstance(v, str):
            cls._raise_for_wrong_schema(v)
            return cls(uri=v)
        else:
            raise TypeError("A or string required")


class B:
    def __init__(self, uri: str):
        self._uri = uri

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source: type[Any], handler: Callable[[Any], core_schema.CoreSchema]
    ) -> core_schema.CoreSchema:
        return core_schema.no_info_wrap_validator_function(
            cls._validate,
            core_schema.str_schema(),
            serialization=core_schema.to_string_ser_schema(),
        )

    @classmethod
    def _validate(cls, v: Any, _: Any) -> "B":
        return B(v)


class Model(BaseModel):
    a_field: A | B


model = Model(a_field=B("correct-schema-for-b"))


# Throws TypeError: A or string required
# Without even trying the validator of B
```

**Comment by FlorianWilhelm** [comment]
Thanks @dmontagu, this resolved my problem too! It seems I forgot that point when I migrated and since it worked for the versions prior to 2.5, I forgot about it. I just checked the docs, it's well documented.

**Comment by sydney-runkle** [comment]
Thanks @dmontagu for this super helpful response 😄. Will certainly reference this issue in the future if others have similar questions 🌟
