### ISSUE TITLE
`|`-style union in `ConfigDict` raises TypeError when used as annotation on versions below 3.10

### ISSUE THREAD

**Issue by waterfountain1996** [pydantic/pydantic#8134]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic's `ConfigDict` uses `|` style unions for type annotations, which is only available in Python 3.10 and above, therefore a `TypeError` exception is raised when I try to use it as an annotation of a `pydantic.dataclasses.dataclass` field.

### Example Code

```Python
from pydantic import ConfigDict
from pydantic.dataclasses import dataclass


@dataclass
class X:
    config: ConfigDict


x = X(config={})

#  ...
#   File "/home/***/tmp/venv/lib/python3.8/site-packages/pydantic/_internal/_fields.py", line 51, in get_type_hints_infer_globalns
#     return get_type_hints(obj, globalns=globalns, localns=localns, include_extras=include_extras)
#   File "/home/***/tmp/venv/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py", line 366, in get_type_hints
#     value = typing._eval_type(value, base_globals, base_locals)  # type: ignore
#   File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
#     return t._evaluate(globalns, localns)
#   File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
#     eval(self.__forward_code__, globalns, localns),
#   File "<string>", line 1, in <module>
# TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/***/tmp/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.18 (default, Sep 30 2023, 12:49:48)  [GCC 13.2.1 20230801]
                     platform: Linux-6.1.62-1-lts-x86_64-with-glibc2.34
             related packages: typing_extensions-4.8.0 mypy-1.6.1
```

**Comment by sydney-runkle** [comment]
Hi @waterfountain1996,

Thanks for reporting this. This hasn't been an issue in the past because we haven't seen a case of `ConfigDict` being used as an annotation. What's the use case here for using it as a field type?

**Comment by waterfountain1996** [comment]
Hello @sydney-runkle, 

I'm trying to write sort of a codegen tool to generate Pydantic models and the example is taken from one of the AST objects. It's not something critical, I could get away by using a simple `Dict` annotation, but it feels weird that the library supports versions 3.8 and above, but this class has incompatible type annotations with said versions. Now I do realize that my case is exceptional and `ConfigDict` was not meant to be used this way, but it looks like a simple fix, although if you guys decide that it's not worth it to rewrite it - that is fine with me.

I've also tested it with stdlib's `dataclass` - works fine, and with `pydantic.BaseModel` which fails due to the same error as above.

If needed, I'd be happy to submit a PR for this

**Comment by sydney-runkle** [comment]
Hi @waterfountain1996,

Makes sense! Feel free to submit a PR with a fix 😄, I'd be happy to review! 🌟

**Comment by sydney-runkle** [comment]
Closing - as mentioned in the PR, circular imports prevent the usage of `ConfigDict` as an annotation.
