### ISSUE TITLE
Error generating JsonSchema for numpy.float64 field

### ISSUE THREAD

**Issue by JeronimoMendes** [pydantic/pydantic#8151]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi there!

I'm currently in the process of migrating a project to pydantic V2 and have come across an issue related to the JsonSchema generation for a field with type `numpy.float64`.

This is the V1 code: 
```
from pydantic import BaseModel
import numpy as np


class FooV1(BaseModel):
    name: str
    age: np.float64

    class Config:
        arbitrary_types_allowed = True

foo = FooV1(name="test", age=np.float64(14.64))
foo.schema()
```

which produces the following

```
{'title': 'Test',
 'type': 'object',
 'properties': {'name': {'title': 'Name', 'type': 'string'},
  'age': {'title': 'Age', 'type': 'number'}},
 'required': ['name', 'age']}
 ```
 
However, in the migrated V2 code, using the `model_json_schema()` method, I encounter a `PydanticInvalidForJsonSchema` error:
 
 ```
 from pydantic import BaseModel, ConfigDict
import numpy as np


class FooV2(BaseModel):
    name: str
    age: np.float64

    model_config = ConfigDict(arbitrary_types_allowed=True)

foo = FooV2(name="test", age=np.float64(14.64))
foo.model_json_schema()
```

The error message is: `PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'numpy.float64'>)`.

I have attempted to address this by adding a json_encoder that converts `np.float64` to `float`. Unfortunately, this doesn't resolve the issue.

Could you kindly help me understand if there's something incorrect in my V2 migration code? Additionally, considering that we are dealing with the same `np.float64` type in both versions, is this behavior intended for the new version of pydantic? If so, is there a recommended way to generate a Json Schema for fields with `numpy.float64` type?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/jeronimo/[redacted]/env/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.0-arm64-arm-64bit
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @JeronimoMendes,

Great question. You can use `Annotated` along with `WithJsonSchema` to support the json schema generation for this arbitrary type. Consider the following:

```py
from typing_extensions import Annotated

from pydantic import BaseModel, ConfigDict, WithJsonSchema
import numpy as np


np_float64 = Annotated[np.float64, WithJsonSchema({'type': 'float'})]

class FooV2(BaseModel):
   name: str
   age: np_float64

   model_config = ConfigDict(arbitrary_types_allowed=True)

foo = FooV2(name="test", age=np.float64(14.64))
print(repr(foo))
#> FooV2(name='test', age=14.64)
print(foo.model_json_schema())
#> {'properties': {'age': {'title': 'Age', 'type': 'float'}, 'name': {'title': 'Name', 'type': 'string'}}, 'required': ['name', 'age'], 'title': 'FooV2', 'type': 'object'}
```

Let me know if you have any follow up questions :)
