### ISSUE TITLE
More things to document

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8160]
I've been doing some in depth stuff with pydantic and discovered we don't have great documentation for:
* `WithJsonSchema` - needs to be talked about on the JSON Schema page, with an example, link to docs
* `__get_pydantic_json_schema__` - on same page, needs an example

**Comment by Viicos** [comment]
Unless I'm mistaken, I haven't found any reference to `computed_field` in concepts (apart from a note in [Serialization](https://docs.pydantic.dev/latest/concepts/serialization/)). It might be beneficial to have a dedicated section? What do you think?

**Comment by sydney-runkle** [comment]
@Viicos,

Good call - probably makes sense to have a section in the `Fields` concepts section. I can add that as well 😄

**Comment by sydney-runkle** [comment]
Also `json_schema_extra` with a callable 😄

**Comment by sydney-runkle** [comment]
Taking a closer look at the JSON schema page now. I think it could help to do a bit of a conceptual overview / rewrite that touches on all of the various ways to modify schema, and the use cases for each. Will include that in this PR.
