### ISSUE TITLE
Can't pass `tuple[T, ...]` into `Sequence[T]` parameter when using strict mode

### ISSUE THREAD

**Issue by ThirVondukr** [pydantic/pydantic#8173]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic raises validation error when you're trying to pass tuple into a sequence field when using `strict=True`, even though tuple is a sequence:
```py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    Model(items=(1, 2, 3))
  File ".venv\Lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Model
items
  Input should be a valid list [type=list_type, input_value=(1, 2, 3), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type
```

This makes it pretty much impossible to use abstract types/collections with strict mode 🤔 

### Example Code

```Python
from collections.abc import Sequence

from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    model_config = ConfigDict(strict=True)

    items: Sequence[int]


Model(items=(1, 2, 3))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
pydantic-core version: 2.14.3
pydantic-core build: profile=release pgo=true
install path: .venv\Lib\site-packages\pydantic
python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
related packages: mypy-1.7.0 pydantic-settings-2.1.0 typing_extensions-4.8.0
```

**Comment by ThirVondukr** [comment]
At the same time passing a list into strict model works:
```py
Model(items=[1, 2, 3])
```

**Comment by sydney-runkle** [comment]
@ThirVondukr,

This is expected behavior according to our Conversion Table in the docs: https://docs.pydantic.dev/latest/concepts/conversion_table/#__tabbed_1_1. See the rows with `Sequence` as the field type:

<img width="856" alt="Screenshot 2023-11-19 at 10 23 47 PM" src="https://github.com/pydantic/pydantic/assets/54324534/d9738f1c-474d-41dc-93f2-b58e6c4e89e7">

**Comment by ToBeReplaced** [comment]
I am following up on this in a discussion here: https://github.com/pydantic/pydantic/discussions/8786
