### ISSUE TITLE
Lazy loading of computed fields

### ISSUE THREAD

**Issue by oyvinev** [pydantic/pydantic#8174]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I have a use case where I would like to lazily compute an expensive `computed_field` - that is, only compute on either direct access or when dumped.

Specific use case is for computing md5sum of potentially large files (GBs), and I would love a solution like this:

```
import hashlib
from pydantic import BaseModel, FilePath, computed_field


class PydanticFile(BaseModel):
    path: FilePath

    @computed_field(lazy=True) # <--- This is the magic keyword
    def md5sum(self) -> str:
        hash = hashlib.md5()
        with open(self.path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                hash.update(chunk)
        return hash.hexdigest()

f = PydanticFile(path="/foo/bar/x.tar.gz") # md5sum not computed or validated
print(f) # md5sum not computed or validated

print(f.md5sum) # md5sum computed (and validated?)
print(f.model_dump()) # md5sum computed
print(f.model_dump_json()) # md5sum computed
```

This would obviously work well in tandem with `cached_property`.

I couldn't find any issue targeting this. I apologize if this is already possible - if so, I would very much appreciate a pointer in the right direction.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I'm afk right now.

Are you sure `computed_field` isn't already lazy?

There are some issues with `cached_property`, I'm sure you can find it with a quick search.

**Comment by oyvinev** [comment]
Oh my god, you're right. I don't know how I missed it. The following achieves what I wanted:

```
import hashlib
from functools import cached_property

from pydantic import BaseModel, FilePath, computed_field


class PydanticFile(BaseModel):
    path: FilePath

    @computed_field(repr=False)
    @cached_property
    def md5sum(self) -> str:
        print("!!! Computing md5sum")
        hash = hashlib.md5()
        with open(self.path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                hash.update(chunk)
        return hash.hexdigest()


print("Initiating")
f = PydanticFile(path="/tmp/foo.txt")
print("str(f)")
print(str(f))
print("f.model_dump()")
print(f.model_dump())
print("f.model_dump_json()")
print(f.model_dump_json())
print("f.md5sum")
print(f.md5sum)
```

Outputs:
```
Initiating
str(f)
path=PosixPath('/tmp/foo.txt')
f.model_dump()
!!! Computing md5sum
{'path': PosixPath('/tmp/foo.txt'), 'md5sum': 'd41d8cd98f00b204e9800998ecf8427e'}
f.model_dump_json()
{"path":"/tmp/foo.txt","md5sum":"d41d8cd98f00b204e9800998ecf8427e"}
f.md5sum
d41d8cd98f00b204e9800998ecf8427e
```

Sorry for the inconvenince, and thank you for the quick reply. No issue encountered with `cached_property` either :+1:

**Comment by pirate** [comment]
Is there any way to do this without adding underscores to the real underlying fields?

It would be awesome to have lazy fields that recompute on every `.__getattr__()` or `.model_dump()` without needing so much duplication in the model definition.
