### ISSUE TITLE
`validate_call` with `config.extra='ignore'` still raises `ValidationError`

### ISSUE THREAD

**Issue by igordertigor** [pydantic/pydantic#8178]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am trying to use to `validate_call` decorator with injected arguments that may or may not be used by the decorated function. My understanding was that setting `config=ConfigDict(extra='ignore')` would just ignore the extra arguments if they are not used. However that doesn't seem to work. Running the below example, I still get
```
Traceback (most recent call last):
  File "/home/***/isolate.py", line 9, in <module>
    func(1, y=2)
  File "/home/***/.venv/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py", line 113, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for func
y
  Unexpected keyword argument [type=unexpected_keyword_argument, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/unexpected_keyword_argument
```
This behaviour seems to differ from the documentation linked in the exception traceback.

### Example Code

```Python
from pydantic import validate_call, ConfigDict


@validate_call(config=ConfigDict(extra='ignore'))
def func(x: float) -> float:
    return x*x


func(1, y=2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/***/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0]
                     platform: Linux-5.15.0-10075-tuxedo-x86_64-with-glibc2.31
             related packages: typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @igordertigor,

Thanks for reporting this. You're correct - looks like we're not properly supporting `extra` specifications for the `validate_call` decorator. PRs welcome to add support for this this feature!

**Comment by andresliszt** [comment]
Hello! This PR would work: https://github.com/pydantic/pydantic-core/pull/1094

**Comment by sydney-runkle** [comment]
A bit delayed, but looks like @andresliszt's PR works quite well to fix this :).

Thanks for your contribution! Closing this as completed.
