### ISSUE TITLE
`model_validator` with `mode` set to `after` raises `RecursionError` when `validate_assignment` is set to `True`

### ISSUE THREAD

**Issue by Viicos** [pydantic/pydantic#8185]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Follow up of https://github.com/pydantic/pydantic/discussions/7704:

```python
from pydantic import BaseModel, model_validator

class Model(BaseModel):
    a: int
    b: int

    @model_validator(mode="after")
    def validate_model(self):
        if self.b == 2:
            self.a = self.b
        return self

    model_config = {"validate_assignment": True}
```

Raises `RecursionError: maximum recursion depth exceeded while calling a Python object` (obviously because assigning `self.a` will trigger validation, resulting in an endless loop of `vaidate_model` calls).

@pedrolopes-basecone found a solution using a `wrap` validator but a bit less readable.

I don't know if preventing validation inside validators could be a viable solution? Otherwise I think a better error message could be great.

## Workaround

Using `field_validator` and making use of `ValidationInfo.data`, but not recommended because fields need to be correctly ordered. 

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
               python version: 3.10.13 (main, Oct 16 2023, 15:57:15) [GCC 11.4.0]
                     platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0 mypy-1.7.0 pydantic-settings-2.1.0
```

**Comment by Viicos** [comment]
@sydney-runkle What would be the way of fixing this? Do you think disabling assignment validation in validators is the way to go? If so I'll work on this so that I can unblock my current work

**Comment by samuelcolvin** [comment]
humm, I don’t think we want to make this work, there are other situations in validators where we want `validate_assignment` to be applied.

I also think `RecursionError` is a fair error to be raised - it does describe well what's going on.

Of course, if there was a cheap way detect this and raise a more description error, great, but I wouldn’t say it’s a priority for us.

**Comment by Viicos** [comment]
@samuelcolvin thanks for the answer. Having a `RecursionError` wasn't obvious at first for me but yes if you just think a bit about it it makes sense, so I think leaving it as is is fine.

What would you recommend in this case? I've added a workaround in my first post, and others could be:
- using properties (not ideal in my case as I have this validation logic for multiple fields and it will quickly become hard to manage)
- using the workaround provided in the linked discussion

**Comment by Viicos** [comment]
Went for the following:

```python
def _set_skip_validation(self, name: str, value: Any) -> None:
    """Workaround to be able to set fields without validation."""
    attr = getattr(self.__class__, name, None)
    if isinstance(attr, property):
        attr.__set__(self, value)
    else:
        self.__dict__[name] = value
        self.__pydantic_fields_set__.add(name)
```

Essentially, a subset of what `BaseModel.__setattr__` that can be called from the model validator (made private as it should only be called from a trusted source, in my case the validator I've defined).

Closing but open for better alternatives.

**Comment by Jylpah** [comment]
At least I use `@model_validator` to set field values based on other field values and this `RecursionError` comes up often when refactoring V1 code to V2. If you agree this is quite common use case for `@model_validator`, maybe this could be added to Pydantic itself?

**Comment by couling** [comment]
I think the root problem here is that validators have historically been used for more than just validation:

> At least I use @model_validator to set field values based on other field values

This use case only causes infinite recursion because the `@model_validator` _**always**_ sets that field. It's not validating anything, its calculating a value.

I think most of these use cases are better achieved in pydantic v2 with [@computed_field](https://docs.pydantic.dev/2.0/usage/computed_fields/)  and a `@property` or `@cached_property`.

The handful that remain also have an obvious work around of checking if the computed field is already correct and only setting it if it's not. IE validate the computed field, don't just blindly set it.
