### ISSUE TITLE
`.model_dump()` fails for frozen models nested in `set`

### ISSUE THREAD

**Issue by igordertigor** [pydantic/pydantic#8187]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a pydantic model that contains a `set` of instances of another pydantic model. Because `set` requires hashable elements, I set the child model's config to `frozen=True`. This works well during instantiation, but fails during calls to `.model_dump()`:
```
Traceback (most recent call last):
  File "/home/***/isolate2.py", line 15, in <module>
    Parent(children={Child(x=1)}).model_dump()  # Fails
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/***/.venv/lib/python3.11/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

I expected that `.model_dump()` would work as it does with other models and that a child (with all hashable properties) would properly behave as a hashable class even during `.model_dump()`.

I currently work around this more or less manually (sketched  in the Example Code as well).

### Example Code

```Python
from typing import Any
from pydantic import BaseModel, ConfigDict


class Child(BaseModel):
    model_config = ConfigDict(frozen=True)

    x: int


class Parent(BaseModel):
    children: set[Child]


Parent(children=set()).model_dump()  # Ok
Parent(children={Child(x=1)}).model_dump()  # Fails


# Current workaround


def safe_dump(model: BaseModel) -> dict[str, Any]:
    dumped = dict(model)
    dumped['children'] = [child.model_dump() for child in dumped['children']]
    return dumped


safe_dump(Parent(children={Child(x=1)}))  # Ok, but not working in general case
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/***/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0]
                     platform: Linux-5.15.0-10075-tuxedo-x86_64-with-glibc2.31
             related packages: typing_extensions-4.8.0
```

**Comment by alexmojaki** [comment]
Seems like a duplicate of https://github.com/pydantic/pydantic/issues/8016

**Comment by igordertigor** [comment]
@alexmojaki , at least quite similar. I'm using `BaseModel` #8016 uses data classes.

Also, I found a pretty general, although not very performant solution to model dump:
```
import json
from functools import wraps
from pydantic import BaseModel

class SetModelBase(BaseModel):
    @wraps(BaseModel.model_dump)
    def model_dump(self, **kwargs):
        return json.loads(BaseModel.model_dump_json(self, **kwargs))
```
Using this as an alternative `BaseModel` will support fields with sets of other models (at the cost of using serializing to json and deserializing).

**Comment by alexmojaki** [comment]
What about `.model_dump(mode='json')`?

**Comment by igordertigor** [comment]
Fair point. That works. Does that mean that this is the suggested way to work with sets and tuples of pydantic models?

**Comment by sydney-runkle** [comment]
@igordertigor,

I'd say so. We'll leave #8016 open as a feature request for a more specific error / suggestion.

As mentioned in that issue, you can also use `dict(model)` if you don't intend for the results to all be JSON serializable.

**Comment by mshavliuk** [comment]
### Workaround

You could use `children: Annotated[set[Child], PlainSerializer(tuple)]` to make properties serializable, see complete example in https://github.com/pydantic/pydantic/issues/8016#issuecomment-3809490852
