### ISSUE TITLE
Depending on email-validator>=2 is backwards incompatible

### ISSUE THREAD

**Issue by marcuslimdw** [pydantic/pydantic#8196]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic v1 has code to check whether the installed version of `email-validator` is 1 or 2 and act accordingly. On the other hand, Pydantic v2 only works with `email-validator>=2`, which is a backwards incompatible change that is not in the [migration guide](https://docs.pydantic.dev/latest/migration/), which seems like a bug to me. IMO, there're two possible resolutions to this issue:

1. Add code to make Pydantic v2 able to handle `email-validator<2` (and therefore drop the constraint in the optional dependency)
2. Change the docs to note that if you had `email-validator<2` installed and upgraded to Pydantic 2, your code will break

This is not directly relevant, but I would really prefer 1, because currently I have Airflow, FastAPI, and Pydantic 2 installed in the same `pyproject.toml`. Airflow is preventing me from updating `email-validator`, and FastAPI's `/docs` endpoint is not displaying because it depends on Pydantic 2's `EmailStr`, which breaks with `email-validator<2`.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=false
                 install path: <redacted>/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, May 29 2023, 14:51:39)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.1.1-arm64-arm-64bit
             related packages: email-validator-1.3.1 typing_extensions-4.8.0 pyright-1.1.329 fastapi-0.104.1
```
```

**Comment by Viicos** [comment]
Version was bumped because of https://github.com/pydantic/pydantic/issues/3772.

> Airflow is preventing me from updating `email-validator`

I'm not sure I understand, I don't see any dependency to `email-validator` in airflow?

**Comment by marcuslimdw** [comment]
@Viicos it's a transitive dependency; Airflow depends on `Flask-AppBuilder`, which depends on `email-validator`.

**Comment by Viicos** [comment]
Best would be to have `Flask-AppBuilder` loosen their dependencies. I see they put hard caps on almost every library which isn't really a good practice. But as it is not one of your direct dependencies it might be hard to have the change reflected on your environment even if a new release of `Flask-AppBuilder` gets out :/

**Comment by marcuslimdw** [comment]
@Viicos you're definitely right - not really looking for `pydantic` to change anything on the code side here, but IMO it would be really good to note this in the migration guide, above and beyond the PR you mentioned, because if the problematic code is only run in an obscure code path that is not tested, it may be hard to debug

**Comment by sydney-runkle** [comment]
Also related: https://github.com/pydantic/pydantic/pull/6033.

Can clean that up and work on getting that across the line today.
