### ISSUE TITLE
Configure Pydantic V2 schema to load dictionary as python object like in Pydantic V1 

### ISSUE THREAD

**Issue by ssandr1kka** [pydantic/pydantic#8199]
### Discussed in https://github.com/pydantic/pydantic/discussions/8198

<div type='discussions-op-text'>

<sup>Originally posted by **ssandr1kka** November 22, 2023</sup>
Hello, so in Pydantic V1 there was a builtin load-data function converting dict to python object. Any class level setups that will help us to achieve the same behavior in V2?

For example, here is one of many alike serializers that we use throughout the project. It is supposed to receive both dicts and python objects and return url for each `current_profile_pic`. It no longer works when we send dictionary
```
class ProfileSchema(BaseModel):
    ...
    current_profile_pic: str = None
    current_profile_cover_pic: str = None
    
    @field_validator(current_profile_pic)
    @staticmethod
    def resolve_current_profile_pic(obj) -> str:
        return current_profile_pic.x1080.url
    ...
```</div>

**Comment by sydney-runkle** [comment]
@ssandr1kka,

You should be able to use `ProfileSchema.model_validate(**your_dict_here**)`.

Could you please provide the code that you're using to initialize an instance of `ProfileSchema` and the error that you're getting?

**Comment by sydney-runkle** [comment]
You should be able to use 
```py
[ProfileSchema.model_validate(obj) for obj in profile_instances]
```
assuming `profile_instances` is a list of dictionaries. You could also do the same with 
```
[ProfileSchema(*obj) for obj in profile_instances]
```

You don't need a config setting to allow validation from a dict. Indeed, all validators are called with `model_validate`.

**Comment by ssandr1kka** [comment]
I believe introducing such configuration will make things run faster, since with the proposed way, data goes through Pydantic serializer twice: 
1- First time is when we call `ProfileSchema.model_validate(obj)`
2- Second time is when the rest framework initiates the default behavior and sends data to ProfileSchema, 
`response={200: List[ProfileSchema],}`

As for the other concern, field validators are still throwing `'dict' object has no attribute 'current_profile_pic'` for 
`ProfileSchema(*obj)` Meaning 
```
    @field_validator(current_profile_pic)
    @staticmethod
    def resolve_current_profile_pic(obj) -> str:
        return current_profile_pic.x1080.url
```
is receiving dictionary not python object.

Running tests on 
Run tests on ProfileSchema.model_validate(obj) - will update the status in a bit

**Comment by sydney-runkle** [comment]
If you could provide a MRE with your model, your input dict, and the exact error, this will be easier for us to help you with!

**Comment by ssandr1kka** [comment]
Second one failed too, as I understand this is the flow of model_validate():
 Validates all the fields -> Return python model
But since my @field_validator looks for attributes and encounters dictionary it fails the process midway

**Comment by ssandr1kka** [comment]
Dict
```
{'current_profile_cover_pic': '/media/profile_media/default_covers/c2ceb668-bbbc-45d0-83b9-099e5505d1e9/x1080.jpeg',
 'current_profile_pic': '/media/profile_media/default_avatars/78d3d9d5-4a9e-4250-ab14-881562916c32/x1080.jpeg',
 'id': 'a231b99b-eab8-4fa0-a208-aa72e4e60d88',
 'profile_name': 'Johnathan Wick',
```


Code that works in V2
```
class ShortProfileSchema(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: uuid.UUID
    profile_name: str
    current_profile_pic: str = None
    current_profile_cover_pic: str = None

    @field_validator("current_profile_pic", ("current_profile_cover_pic"))
    @classmethod
    def resolve_current_profile_pic(cls, field_value) -> str:
        try:
            return field_value.x1080.url
        except AttributeError:
            return field_value
```

Code that worked in V1
```
class ShortProfileSchema(BaseModel):

    id: uuid.UUID
    profile_name: str
    current_profile_pic: str = None
    current_profile_cover_pic: str = None
    
    class Config:
        allow_population_by_field_name = True

    @field_validator("current_profile_pic", ("current_profile_cover_pic"))
    @classmethod
    def resolve_current_profile_pic(cls, field_value) -> str:
        return field_value.x1080.url
```

So in V1 I did not need to handle dictionary values separately like I do in V2. I believe it was largely due to the fact that V1 had built in data-loading tool, converting dicts into python object as data was loaded + `allow_population_by_field_name = True` was populating fields accordingly. 
In V2 there is no built in data-loaders that convert dicts into python objects as data is loaded, nor there is any class based config that would allow us to make that happen. Instead extra handling is needed for different data types. 
Pydantic is amazingly fast, but if we will have to handle all the differentiating types of data, the performance drops will come from python code itself and that is why I was suggesting to add class based config setting to do so.
The only option I think is to split schemas and have dedicated dict schemas / dedicated python object schemas

**Comment by sydney-runkle** [comment]
@ssandr1kka,

Please provide a code example that shows the entirety of the behavior that you're discussing  - please include import statements, input data, etc.

Marking this as closed for now bc I don't see a problem with the `field_validator` behavior. Happy to continue to help you find the issue, but I don't think this is a bug in `pydantic`.
