### ISSUE TITLE
Assertion error when using model_json_schema() in __init_subclass__

### ISSUE THREAD

**Issue by guillaume-alliander** [pydantic/pydantic#8201]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

What I did was a misguided attempt I believe (trying to enforce that a subclass override a field defined in a parent class) so what I am actually trying to do is probably not relevant, and I'm not blocked by this. 

What I did expect, though, is not to get an exception from pydantic telling me: `AssertionError: this is a bug! please report it` 😃  

The full error is as follows:

```
Traceback (most recent call last):
  File "/home/gui/pydanticbug.py", line 10, in <module>
    class B(A):
  File "/home/gui/.conda/envs/gb311/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 117, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 106, in __new__
  File "/home/gui/pydanticbug.py", line 7, in __init_subclass__
    print(cls.model_json_schema())
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gui/.conda/envs/gb311/lib/python3.11/site-packages/pydantic/main.py", line 385, in model_json_schema
    return model_json_schema(
           ^^^^^^^^^^^^^^^^^^
  File "/home/gui/.conda/envs/gb311/lib/python3.11/site-packages/pydantic/json_schema.py", line 2157, in model_json_schema
    assert '__pydantic_core_schema__' in cls.__dict__, 'this is a bug! please report it'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Example Code

```Python
from pydantic import BaseModel


class A(BaseModel):
    def __init_subclass__(cls, /, **kwargs):
        print(cls.model_json_schema())


class B(A): 
    ...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/gui/.conda/envs/gb311/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
                     platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: pyright-1.1.336 fastapi-0.104.1 typing_extensions-4.8.0
```

**Comment by Viicos** [comment]
You can use [`__pydantic_init_subclass__`](https://github.com/pydantic/pydantic/blob/64ce5b983da760526932c33950d12ddf12f1d1a2/pydantic/main.py#L605-L623) to be able to access `model_json_schema` (and others, that are only available once `ModelMetaclas` computed everything related to fields)

**Comment by sydney-runkle** [comment]
@guillaume-alliander,

Thanks for reporting! Indeed, I think the use of `__pydantic_init_subclass__` here would be appropriate instead.

I don't see a real issue here, so going to close for now. If you think otherwise, please lmk and we can reopen!

**Comment by guillaume-alliander** [comment]
Not a real issue I totally agree, except then for the error message which is a bit misleading. But looking at the code, I do not see an obvious way to make it better.
