### ISSUE TITLE
Feature Request: More pythonic/uniform way of working with JSON loading and dumping

### ISSUE THREAD

**Issue by danielniccoli** [pydantic/pydantic#8206]
### Discussed in https://github.com/pydantic/pydantic/discussions/7644

<div type='discussions-op-text'>

<sup>Originally posted by **danielniccoli** September 26, 2023</sup>
The current alias implementation is not very pythonic in my opinion. I would expect that while working in Python, I work with snake case variables and properties and when moving into the JSON world and back, I would work with camel case (or whatever the other side requires). But instead, it is a wild mix that requires verbosity at every step. But slowly...

Variables in python follow snake case convention. A Pydantic model would typically look like this

```py
class User(BaseModel):
    display_name: str
```

be created instantiated like this

```py
user = User(display_name="Jon Doe")
```

and be converted to a dict like this

```py
user.model_dump()
```

I know that ECMA-404 "does not impose any restrictions on the strings used as names", and therefore neither to camel case, nor snake case, nor any other convention. However, as JavaScript's convention is to use camel case for variables, that is what's widely used in the area. To being able to work in both worlds, Pydantic offers an `alias_generator` configuration that helps generally setting a model to whatevery you like, in this case `to_camel`.

With the aforementioned in mind, I would argue that loading and dumping from/to JSON should always accept/output whatever is defined as the `alias_generator`. But instantiating programmatically should always accept the explicit names as per PEP-8.

I would expect this to work:

```py
from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

config = ConfigDict(
    extra="forbid",
    frozen=True,
    hide_input_errors=True,
    validate_assignment=True,
    alias_generator=to_camel,
)


class User(BaseModel):
    model_config = config
    display_name: str


# Programmatically via parameters
user = User(display_name="Jon Doe")
user_dict = dict(user)
assert user_dict["display_name"] == "Jon Doe"

# Loading/Dumping JSON
user = User('{"displayName": "Jon Doe"}')
assert user.model_dump_json() == '{"displayName": "Jon Doe"}'
```
 
But actually it throws exceptions in lines 19 and 26 because it expects the parameter to be camel case, and the JSON output to be in snake_case. **I find this highly confusing, because my thought process is - as explained before - the Python world is in snake_case and exchange with the outside world (JSON) is in whatever convention I defined - (`to_camel`) in this case.

I know that `model_dump_json()` accepts a parameter `by_alias=`, but why must it be that verbose? And why do I need `by_alias=True` in `model_dump_json()` to output it as `displayName` but `User('{"displayName": "Jon Doe"}')` is perfectly fine? Or better explained the other way, why does `User()` accept camel case, but `model_dump_json()` outputs snake_case?

I would prefer and suggest that Pydantic offer a way where loading/dumping JSON always follows a dev-defined convention in a uniform fashion, while programmatic creation/access (`User(display_name="Jon Doe").display_name`) follows the explicit variable name (that should be PEP-8 conform snake case).

</div>

**Comment by danielniccoli** [comment]
Overthinking the above, aliases aren't really the place where this behaviour should be defined.

> I would prefer and suggest that Pydantic offer a way where loading/dumping JSON always follows a dev-defined convention in a uniform fashion, while programmatic creation/access (User(display_name="Jon Doe").display_name) follows the explicit variable name (that should be PEP-8 conform snake case).

Programmatic access should always follow the variable naming convention used in the Python code, which of course should be follow PEP-8 guidelines and be in `snake_case`.

Input convention and output convention should be independent from aliases, perhaps with a new `ConfigDict` property `json_naming_convention=`. This way we could introduce the new uniform property capitalization settings without introducing a breaking change, while also preserving alias generation.

**Comment by sydney-runkle** [comment]
Hi @danielniccoli,

I've made 2 small modifications to the example from your first comment:

```py
from pydantic import BaseModel, ConfigDict
from pydantic.alias_generators import to_camel

config = ConfigDict(
    extra="forbid",
    frozen=True,
    populate_by_name=True, # <-- this is the important one
    hide_input_errors=True,
    validate_assignment=True,
    alias_generator=to_camel,
)


class User(BaseModel):
    model_config = config
    display_name: str


# Programmatically via parameters
user = User(display_name="Jon Doe")
user_dict = dict(user)
assert user_dict["display_name"] == "Jon Doe"

# Loading/Dumping JSON
user = User.model_validate_json('{"displayName": "Jon Doe"}')
assert user.model_dump_json(by_alias=True) == '{"displayName":"Jon Doe"}' # <-- using by_alias
```

The `populate_by_name` is key here, as it adds support for initializing a `User` instance with either `display_name` or `displayName`.

Regarding the discrepancy in behavior with validation / serialization and aliases, I understand the inconsistency you're pointing out, but at this point, changing this behavior would be a **significant** breaking change, so it's not on our roadmap.

This might not address all of your questions, but it does address the errors that you mentioned having in your first example.

**Comment by danielniccoli** [comment]
@sydney-runkle

> The populate_by_name is key here, as it adds support for initializing a User instance with either display_name or displayName.

This adds ambiguity which is not always wanted.

>  changing this behavior would be a significant breaking change

Where exactly would be the breaking change? I described how to work around any breaking change. If you speak specifics, I will address them.

**Comment by samuelcolvin** [comment]
I think it might make sense to make `by_alias` an argument at validation time, replacing `populate_by_name`. I guess we could add `by_alias` as a non breaking change, but it's a lot of work to do it in a way that doesn't affect performance.

Btw, @danielniccoli your manner is not open in an open source discussion, please be friendlier.
