### ISSUE TITLE
BeforeValidator sometimes ignored for Annotated types

### ISSUE THREAD

**Issue by RS-Credentive** [pydantic/pydantic#8215]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have defined a validation function for a custom flavor of bool that can be 
True or "true" or 1 or "1"
- or -
False or "false" or 0 or "0"

I have an annotated type with a before validator that either accepts one of those inputs and coerces it into the appropriate bool or raises a Value Error. See the code listing below for a minimal example.

It only seems to work if I pass in a False (python bool) or 0. Every other value comes back as "true" even if the value is not any of the acceptable options for true or false. If I pass the same value directly to the validation function, it works as expected.

### Example Code

```Python
from pydantic import BeforeValidator

from typing import Annotated, Any

def validate_bool(v: Any) -> bool:
    if isinstance(v, str):
        if v == "true" or v == "1":
            return True
        elif v == "false" or v == "0":
            return False
        else:
            raise ValueError
    elif isinstance(v, int):
        if v == 1:
            return True
        elif v == 0:
            return False
        else:
            raise ValueError
    elif isinstance(v, bool):
        return v
    else:
        raise ValueError


CustomBool = Annotated[bool, BeforeValidator(validate_bool)]


print(validate_bool(0))  # False
print(CustomBool(0))  # False

print(validate_bool(1))  # True
print(CustomBool(1))  # True

print(validate_bool(False))  # False
print(CustomBool(False))  # False

print(validate_bool(True))  # True
print(CustomBool(True))  # True

print(validate_bool("false"))  # False
print(CustomBool("false"))  # True

print(validate_bool("0"))  # False
print(CustomBool("0"))  # True

print(validate_bool(3))  # Raises ValueError
print(CustomBool(3))  # True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=false
                 install path: /home/vscode/.local/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun  7 2023, 19:03:45) [GCC 10.2.1 20210110]
                     platform: Linux-6.4.16-linuxkit-aarch64-with-glibc2.31
             related packages: email-validator-2.1.0.post1 typing_extensions-4.8.0
```

**Comment by Viicos** [comment]
You have to use Pydantic `BaseModel` or `TypeAdapter` at some point. At runtime, `CustomBool = Annotated[bool, BeforeValidator(validate_bool)]` is just `bool` (see [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated)). In other words, `Annotated[type, metatadata]` has no effect unless a library (such as Pydantic) inspects the type hints to perform the validation. In your case:

```python
from typing import Annotated

from pydantic import BeforeValidator, TypeAdapter

def validate_bool(...): ...

CustomBool = Annotated[bool, BeforeValidator(validate_bool)]

TypeAdapter(CustomBool).validate_python(...))

```

**Comment by RS-Credentive** [comment]
That was it. Thanks for the tip! I usually use the annotated types in the context of a model, but for unit testing, I wanted to create the naked instances. I will use TypeAdapter or create a simple testing model for my unit tests.
