### ISSUE TITLE
merge_field_infos to override default with default_factory

### ISSUE THREAD

**Issue by kevin-paulson-mindbridge-ai** [pydantic/pydantic#8216]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be nice to be able to use default_factory to override the default with default_factory.

This is the current behaviour:
```python
from uuid import uuid4
from pydantic import BaseModel, Field
from typing import Optional


class User(BaseModel):
    id: Optional[str] = None


x = Field().merge_field_infos(
    User.model_fields["id"], Field(default_factory=lambda: uuid4().hex)
)
# Traceback (most recent call last):
#   File "/home/kpaulson/temp.py", line 10, in <module>
#     x = Field().merge_field_infos(
#         ^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/kpaulson/.venv/lib/python3.11/site-packages/pydantic/fields.py", line 415, in merge_field_infos
#     field_info = FieldInfo(**new_kwargs)
#                  ^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/kpaulson/.venv/lib/python3.11/site-packages/pydantic/fields.py", line 194, in __init__
#     raise TypeError('cannot specify both default and default_factory')
# TypeError: cannot specify both default and default_factory
```

Basically the above code would not error and `x` would be a field with a default_factory as indicated.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @kevin-paulson-mindbridge-ai,

I don't love this alternative, it feels a little bit dirty, but here's one approach you could take:

```py
from datetime import date
from typing import Optional

from pydantic import BaseModel, Field
from pydantic.fields import FieldInfo

from pydantic_core import PydanticUndefined

class OtherClass(BaseModel):
    pass

class GeneratedModel(BaseModel):
    field_one: Optional[OtherClass] = Field(None, alias="fieldOne")
    field_two: Optional[date] = Field(
        None,
        alias="fieldTwo",
        description="Some description here.",
    )

class MyItem(GeneratedModel):
    field_one: OtherClass = FieldInfo.merge_field_infos(
        GeneratedModel.model_fields["field_one"],
        default=PydanticUndefined,  # used as a sentinel
        default_factory=lambda: OtherClass(),  # used as an override
    )
    field_two: date = FieldInfo.merge_field_infos(
        GeneratedModel.model_fields["field_two"],
        Field(default=date(date.today().year, 12, 31)),
    )

print(MyItem.model_fields["field_one"].default)
#> PydanticUndefined
print(MyItem.model_fields["field_one"].default_factory)
#> <function MyItem.<lambda> at 0x1059b0310>
print(repr(MyItem()))
#> MyItem(field_one=OtherClass(), field_two=datetime.date(2023, 12, 31))
```

I came up with this solution based on the fact that the `merge_field_infos` function supports overrides, which are by nature a bit hacky:

https://github.com/pydantic/pydantic/blob/b430e5aa9d1061e65753301ee014278eab66c437/pydantic/fields.py#L375

**Comment by kevin-paulson-mindbridge-ai** [comment]
Thank you @sydney-runkle , this works well for me!
