### ISSUE TITLE
Add examples for custom serializers in API docs

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#8234]
For `PlainSerializer`, `model_serializer`, and `field_serializer`.

**Comment by debakarr** [comment]
What about the documentation here: https://docs.pydantic.dev/latest/concepts/serialization/#custom-serializers

**Comment by sydney-runkle** [comment]
@debakarr,

Right, but we want to have examples in the API docs as well

**Comment by hungtsetse** [comment]
@sydney-runkle,

I've opened a PR and I managed to document examples consistently for 3 of them.
Hope it make sense.

**Comment by sydney-runkle** [comment]
Also, let's add an example for `WrapSerializer` to round out the additions to `functional_serializers.py`.

**Comment by sydney-runkle** [comment]
Closed by https://github.com/pydantic/pydantic/pull/8546
