### ISSUE TITLE
Create Decimal annotated types

### ISSUE THREAD

**Issue by ahmedabdou14** [pydantic/pydantic#8246]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

`condecimal()` will be soon deprecated in Pydantic 3.

It would be a great feature to add common `Decimal` annotated types just like float and int

```python
class Model(BaseModel):
    a: StrictInt
    b: PositiveInt
    c: NegativeInt
    d: NonNegativeInt
    e: FiniteFloat
    f: StrictFloat
    g: PositiveFloat
    h: NegativeFloat
    i: NonPositiveInt
    j: NonNegativeFloat
    k: NonPositiveFloat

    # to be supported
    l: PositiveDecimal
    m: NegativeDecimal
    n: NonNegativeDecimal
    o: NonPositiveDecimal
    p: InfiniteDecimal
    q: StrictDecimal
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@ahmedabdou14,

Sounds good to me! I'll review your PR here shortly 👍!

**Comment by sydney-runkle** [comment]
See PR for reasoning.
