### ISSUE TITLE
Can no longer parse str() of timedelta

### ISSUE THREAD

**Issue by brasie** [pydantic/pydantic#8248]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In V1, one could parse the a `str()`ed timedelta:

    parse_obj_as(timedelta, str(timedelta(hours=3)))

But the equivalent in V2 breaks:

    TypeAdapter(timedelta).validate_python(str(timedelta(hours=3)))

This seems simply because the V2 parser is more strict about a leading zero in the hours part of the timedelta, i.e. `3:00:00` is rejected (as output by `timedelta.str`), but `03:00:00` is ok.

It would be nice to preserve the ability to parse the result of `timedelta.str`

### Example Code

```Python
import datetime

import pydantic

class Foo(pydantic.BaseModel):
    td: datetime.timedelta

# Works
Foo.model_validate({"td": str(datetime.timedelta(hours=10))})
Foo.model_validate({"td": str(datetime.timedelta(days=3, hours=10))})
Foo.model_validate({"td": str(datetime.timedelta(days=3, hours=10, minutes=5, seconds=10))})

# Fails
Foo.model_validate({"td": str(datetime.timedelta(days=3, hours=9, minutes=5, seconds=10))})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /.../pypoetry/virtualenvs/...-ldZDDfYB-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
                     platform: Linux-6.5.9-arch2-1-x86_64-with-glibc2.38
             related packages: mypy-1.7.1 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
Hi @brasie,

Thanks for reporting this. Pydantic now uses `speedate` for date/time related parsing.

The Pydantic v1 -> v2 migration guide provides [this table](https://docs.pydantic.dev/latest/usage/conversion_table/) with information about how Pydantic converts data during validation.

The table also illustrates that when you pass a `str` in for a timedelta field, it's assumed to be in [ISO8601 format](https://docs.rs/speedate/latest/speedate/). Taking the `str` of a `datetime.timedelta` doesn't necessarily conform to that, as seen in your example.

If you still want to be able to validate data in this format, I'd recommend a custom field validator. Here's an example I threw together quite quickly, there might be some oversights here re behavior with days / without days included in the timedelta:

```py
import datetime
import json

from pydantic import BaseModel, field_validator


class Foo(BaseModel):
    td: datetime.timedelta

    @field_validator('td', mode='before')
    def td_to_timedelta(cls, v):
        if isinstance(v, datetime.timedelta):
            return v
        elif isinstance(v, str):
            dt = datetime.datetime.strptime(v, '%d days, %H:%M:%S') if 'days' in v else datetime.datetime.strptime(v, '%H:%M:%S')
            return datetime.timedelta(days=dt.day, hours=dt.hour, minutes=dt.minute, seconds=dt.second)
        else:
            return v


# Works
Foo.model_validate({'td': str(datetime.timedelta(hours=10))})
Foo.model_validate({'td': str(datetime.timedelta(days=3, hours=10))})
Foo.model_validate({'td': str(datetime.timedelta(days=3, hours=10, minutes=5, seconds=10))})
Foo.model_validate_json(json.dumps({'td': str(datetime.timedelta(days=3, hours=9, minutes=5, seconds=10))}))
```
An even cleaner approach would be to just pad the hours if a single digit it used.

Closing for now, as this is more of a question than a bug. Thanks!

**Comment by brasie** [comment]
I see, I suppose; Thanks for the explanation.

It's just, you're already parsing more than ISO8601, assuming my understanding is correct that ISO8601 does not include a `datetime.timedelta.str`-like `[D days,] HH:MM:SS` format.  Pydantic V1 also supported reading a `datetime.timedelta.str`-like format, but unlike Pydantic V1, V2 no longer supports all ways that `datetime.timedelta.str` outputs.

Hence why it seemed bug-like.

But if it is expected behavior on your side, then perhaps this is more of a feature request for `speedate`.

**Comment by samuelcolvin** [comment]
I think it makes sense to support all timedelta str representations in speedate.

**Comment by rafrafek** [comment]
In my case v1 serialised `datetime.timedelta` to:
```python
"session_expiry": 10800,
```
and v2 serialises it to:
```python
"session_expiry": "PT10800S",
```

**Comment by igoose1** [comment]
@rafrafek, thanks! I would notice that your solution can give an unexpected answer as `timedelta.seconds` are always less than 1 day and don't include microseconds. You probably want to use `.total_seconds()` instead.

Example:

```python
>>> td = datetime.timedelta(days=4, seconds=20, microseconds=69)
>>> td.seconds
20
>>> td.total_seconds()
345620.000069
```

So this code can be re-written in this to avoid issues:
```python
@field_serializer("session_expiry", mode="plain")
def session_expiry_to_seconds(self, session_expiry: datetime.timedelta) -> float:  # now it returns a float
    return session_expiry.total_seconds()  # now it returns all seconds
```
