### ISSUE TITLE
computed_fields have inconsistent behaviour between model_dump and model_dump_json

### ISSUE THREAD

**Issue by Samreay** [pydantic/pydantic#8250]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There seems to be inconsistent behaviour between `model_dump` and `model_dump_json` with computed fields.

### Example Code

```Python
from pydantic import BaseModel, computed_field


class Example(BaseModel):
    x: int
    y: int | None

    @computed_field
    def computed(self) -> None:
        return None


if __name__ == "__main__":
    e = Example(x=1, y=None)

    print(e.model_dump(exclude_none=True))
    # {'x': 1}

    print(e.model_dump_json(exclude_none=True))
    # {"x":1,"computed":null}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/sam/arenko/trade-selector/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  4 2023, 13:46:25) [GCC 11.3.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: fastapi-0.104.1 typing_extensions-4.8.0 mypy-1.7.0 pydantic-settings-2.1.0
```

**Comment by Samreay** [comment]
I believe this may be related to https://github.com/pydantic/pydantic/issues/5827, however I am unsure if under the hood the explicit `exclude` is tied to `exclude_none` or if there's a different handler.

**Comment by sydney-runkle** [comment]
Found a fix for this in `pydantic-core`, will have a PR up shortly. This should be fixed in our next minor release 👍.

**Comment by AndreaPiccione** [comment]
Hi Sydney, I thought this would have been part of the next minor release. I can't see it in pydantic 2.5.3
