### ISSUE TITLE
Missing API documentation for `pydantic_extra_types.mac_address`

### ISSUE THREAD

**Issue by eonu** [pydantic/pydantic#8254]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The API documentation page for [`pydantic_extra_types.mac_address`](https://docs.pydantic.dev/latest/api/pydantic_extra_types_mac_address/) is empty.

### Python, Pydantic & OS Version

```Text
N/A
```

**Comment by sydney-runkle** [comment]
Fixed, thanks!
