### ISSUE TITLE
Unexpected inconsistent behaviour when using 'model_construct'

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [pydantic/pydantic#8266]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I came across something unexpected / inconstistent when passing extra values to `model_construct`.

```
class A(BaseModel):
    attribute: int

a = A.model_construct(another_attribute=":(")
```

In the documentation, it says:
> [...] Creates a new model setting __dict__ and __pydantic_fields_set__ from trusted or pre-validated data. Default values are respected, but no other validation is performed. Behaves as if Config.extra = 'allow' was set since it adds all passed values

When inspecting the created object, the attribute doesn't seem to be present:
```
a  # A()
a.model_dump()  # {}
a.model_extra  # None
```

Then, however, I discovered, that the attribute is indeed present and can (must) be accessed directly as it doesn't show up in the dump result:
```
a.another_attribute  # ':('
```

This is somehow unexpected, because I thought the attribute would also appear in the `repr` and `model_dump` result. 

What I found to be inconsistent is the following sentence:
> Behaves as if Config.extra = 'allow' was set since it adds all passed values

When I manually set `extra="allow"`, the extra values to `model_construct` show up as expected:
```
class B(BaseModel):
    model_config = ConfigDict(extra="allow")
    attribute: int


b = B.model_construct(another_attribute=":)")

b  # B(another_attribute=':)')
b.another_attribute  # ':)'
b.model_dump()  # {'another_attribute': ':)'}
b.model_extra  # {'another_attribute': ':)'}
```

But this somehow contradicts the statement, that `model_construct` just behaves as if "Config.extra = 'allow' was set" as it actually takes into account the current configuration.

A notice of this behavior in the documentation would be nice.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict


class A(BaseModel):
    model_config = ConfigDict(extra="forbid")  # ignore behaves the same

    attribute: int


a = A.model_construct(another_attribute=":(")

a  # A()
a.another_attribute  # ':('
a.model_dump()  # {}
a.model_extra  # None


class B(BaseModel):
    model_config = ConfigDict(extra="allow")
    attribute: int


b = B.model_construct(another_attribute=":)")

b  # B(another_attribute=':)')
b.another_attribute  # ':)'
b.model_dump()  # {'another_attribute': ':)'}
b.model_extra  # {'another_attribute': ':)'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=false
                 install path: /opt/homebrew/Caskroom/mambaforge/base/envs/test/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ]
                     platform: macOS-14.1.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 pydantic-settings-2.1.0
```

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

Agreed, this is inconsistent! PRs welcome to either clean up the docs on this concept or (better) change the behavior of `model_construct` to reflect the current expectation set by the docs!

**Comment by StrawHatDrag0n** [comment]
@sydney-runkle I can work on this.

**Comment by StrawHatDrag0n** [comment]
@sydney-runkle 

What should be the expected output for the function ?
Should this be same as a class with `model_config['extra '] = allow` ?

I am able to recreate the same output by calling `model_rebuild` with `model_config['extra'] = 'allow'` but then this changes the initial `model_config`.

```
cls.model_config['extra'] = 'allow'
cls.model_rebuild(force=True)
````

**Comment by sydney-runkle** [comment]
@StrawHatDrag0n and @ThomasMarwitzQC,

You both have good points. One other note - the concepts portion of the docs says the following, which is consistent with the current behavior, but not the claim that `model_construct` always behaves as if `Config.extra = 'allow'` was set:

> For models with model_config['extra'] == 'allow', data not corresponding to fields will be correctly stored in the __pydantic_extra__ dict.

I'm inclined to have us:
1. Add an update to the docs to make sure we're clearly explaining the behavior of `model_construct`
2. Add an `extra` parameter to the `model_construct` function to allow more fine tuned customization of the `model_construct` behavior with extra value arguments.

I think it's valuable for us to try to avoid introducing any breaking changes for users who might be depending on the current behavior of `model_construct` logic.

A few more details on this `extra` parameter behavior:
* If `extra` isn't specified in the call to `model_construct`, I think we should observe the current behavior
* If `extra='allow'` is specified in the call to `model_construct`, follow the path of behavior taken when `extra='allow'` on the model
* If `extra='ignore'`, I don't think it makes sense for us to store the `extra` values in the `__dict__` of the newly created model. I could also be convinced that it doesn't make sense for us to store these values in `__dict__` by default (as is the current behavior), as this doesn't occur with `__init__`, but this would be a breaking change.
* If `extra='forbid'`, follow a pattern similar to that of said case in `__init__`.

Excited to hear your thoughts on this. Happy to review your PR :). Thanks for your help on this!

**Comment by ThomasMarwitzQC** [comment]
@sydney-runkle 

Regarding `1.`, adding an update to the docs sounds like a good idea!

Regarding the proposed `extra` parameter for `model_construct`: 
 - It sounds reasonable to not introduce breaking changes. 
 - `extra = None` (unspecified): this sounds fine
 - `extra = 'ignore'`: I know to little about the current behaviour in `__init__`, but I would stick with your initial suggestion that if explicitely setting `instance.model_construct(extra='ignore')`, we should not add these values to \_\_dict__. 
 - `extra = 'forbid'`: Same as 'ignore'? This case doesn't really make sense as the whole point of `model_construct` is to not perform validation and 'forbid' somehow implies that an Exception should be raised if the attribute was present.
 - `extra = 'allow'`: I quickly checked the behaviour if I just include the passed values in `_extra` during `model_construct`. This leaves me with the problem that when `model_config.extra = ignore | forbid`, `repr(instance)` works as expected, `instance.model_extra` also works as expected, but `instance.model_dump` doesn't:
 ```
extra = ["allow", "ignore", "forbid"]:

    class Foo(BaseModel, extra=extra):
        x: int

    model = Foo.model_construct(x=1, y=2)
    assert model.x == 1
    assert model.y == 2

    assert model.model_extra == {'y': 2}
    assert 'y=2' in repr(model)
    assert model.model_dump() == {'x': 1, 'y': 2} # This fails for extra='forbid' or 'ignore'
```

So to fix that, we might need to do sth like @StrawHatDrag0n suggested, but that would interfere with the normal `model_config`. If there is no easy fix to this, we should either note this inconsistent behaviour or rethink the use of this new `extra` parameter at all, or maybe change its value range (as `forbid` already doesn't make sense in these particular circumstances).

Please let me know, if anything I said is unclear to you - I'm happy to elaborate :)

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

All good points. Yeah, I'd agree that an `extra='forbid'` setting doesn't really make sense in the context of `model_construct`.

Consider this snippet:

```py
from pydantic import BaseModel

for extra in ["allow", "ignore"]:
    class Foo(BaseModel, extra=extra):
        x: int

    # using __init__
    f = Foo(x=1, y=2)

    print(extra)
    print(f"__dict__: {f.__dict__}")
    print(f"model_extra: {f.model_extra}")
    print(f"model_dump: {f.model_dump()}")
    print("\n")

"""
allow
__dict__: {'x': 1}
model_extra: {'y': 2}
model_dump: {'x': 1, 'y': 2}

ignore
__dict__: {'x': 1}
model_extra: None
model_dump: {'x': 1}
"""

for extra in ["allow", "ignore"]:
    class Foo(BaseModel, extra=extra):
        x: int
    
    # using model_construct
    f = Foo.model_construct(x=1, y=2)

    print(extra)
    print(f"__dict__: {f.__dict__}")
    print(f"model_extra: {f.model_extra}")
    print(f"model_dump: {f.model_dump()}")
    print("\n")

"""
allow
__dict__: {'x': 1}
model_extra: {'y': 2}
model_dump: {'x': 1, 'y': 2}

ignore
__dict__: {'x': 1, 'y': 2}  # <-- y is not ignored, I think we should change this
model_extra: None
model_dump: {'x': 1}
"""
```

I'd agree that if we use the new `extra` param, we should narrow its scope of allowed values. `ignore` and `allow` should be fine.

I'm currently leaning:
* Default to model's `extra` setting
* If `ignore`, we should model the behavior of `__init__`, ie not adding the extra values to the `__dict__`
* If `allow`, we can keep the current behavior on said branch, which models the `__init__` behavior

I think it's important to note in the docs that the default setting for a model's `config.extra` is `ignore`, so if `extra` is not set on the model config nor on the call to `model_construct`, then `ignore` would be used here. Though this does seem a bit counterintuitive to me because of the nature of the `model_construct` method, this is sort of the current behavior.

One thing I haven't considered - what if the model's `extra` setting is `forbid`?

**Comment by ThomasMarwitzQC** [comment]
To be honest, the naming is already pretty confusing for me. How about renaming the attribute to `behaviour` (or something like `behaviour_extra`) with values `old`, `keep`, `discard` (and potentially more / other options).

For the `keep` option however, we currently cannot over a really consistent behaviour (even if the modification I suggested above is implemented):
 - On the one hand, additional attributes **are** shown in `repr()` and `model_extra` 
 - On the other hand, additional attributes are **not** shown in `model_dump`.
 
@sydney-runkle I guess the `model_dump` behaviour is written in Rust? At least I couldn't find the Python implementation. Would it be possible to change its behaviour s.t. attributes contained in `model_extra` are serialized even when `config.extra = forbid | ignore` or would that be a breaking change?

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

> @sydney-runkle I guess the model_dump behaviour is written in Rust? At least I couldn't find the Python implementation. Would it be possible to change its behaviour s.t. attributes contained in model_extra are serialized even when config.extra = forbid | ignore or would that be a breaking change?

This would be a breaking change, and isn't one that we want to implement. You might want to look into the `SerializeAsAny` annotation for behavior like this.

Re your other questions - I'll chat with our team on Monday morning and get back to you then 👍.

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

Sorry for delay in responding here. I'm planning on opening a PR early next week with a docs update / slight change in the behavior of `model_construct`. Stay tuned for a fix!

Thanks again for bringing this to our attention.

**Comment by ThomasMarwitzQC** [comment]
@sydney-runkle Thank you so much :)

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

Apologies for the delay - finally got around to this PR :).
