### ISSUE TITLE
How to overwrite a Field definition in a child class?

### ISSUE THREAD

**Issue by OlgaRabodzei** [pydantic/pydantic#8278]
### Discussed in https://github.com/pydantic/pydantic/discussions/8276

<div type='discussions-op-text'>

<sup>Originally posted by **OlgaRabodzei** December  1, 2023</sup>
Hi! I want to separate my business model from the UI model. As the UI model should contain all the fields from the business model, I want to avoid code duplication and not list the same fields definitions again. In the UI model, I just want to add extra attributes into `json_schema_extra`, these attributes will allow me to control the UI representation.

For example, let's consider a business model called ModelA:

```
from pydantic import Field, BaseModel

class ModelA(BaseModel):
    name: str = Field(
        ...,
        description="""The name of the entity. Should contain only lowercase letters, numbers, - and _""",
        pattern=r"^[a-z_\-0-9]*$",
        max_length=100,
    )
```
Now, suppose I want to create a UI model that defines the UI representation on an edit form, where the name should be read-only. According to the Pydantic documentation, I can overwrite the field by providing a full definition again:
```
class ModelAEdit(ModelA):
    name: str = Field(
        ...,
        description="""The name of the entity. Should contain only lowercase letters, numbers, - and _""",
        pattern=r"^[a-z_\-0-9]*$",
        max_length=100,
        json_schema_extra={
            "schema_ui": {"readOnly": True},
        }
    )
 ```
 **Question**: How to avoid attributes duplication in the child class?
 
 It would be really nice to have something like:
 ```
 class ModelAEdit(ModelA):
    name: str = Field(
        ModelA.model_fields["name"],
        json_schema_extra={
            "schema_ui": {"readOnly": True},
        }
    )
 ```
 But currently such code will loose some attributes like `pattern`.</div>

**Comment by sydney-runkle** [comment]
@OlgaRabodzei,

Thanks for your question! One option is the following:

```py
import json

from pydantic import Field, BaseModel
from pydantic.fields import FieldInfo


class ModelA(BaseModel):
    name: str = Field(
        ...,
        description="""The name of the entity. Should contain only lowercase letters, numbers, - and _""",
        pattern=r"^[a-z_\-0-9]*$",
        max_length=100,
    )


class ModelAEdit(ModelA):
    name: str = FieldInfo.merge_field_infos(
        ModelA.model_fields['name'],
        json_schema_extra={
            "schema_ui": {"readOnly": True},
        }
    )

print(json.dumps(ModelA.model_json_schema(), indent=2))
"""
{
  "properties": {
    "name": {
      "description": "The name of the entity. Should contain only lowercase letters, numbers, - and _",
      "maxLength": 100,
      "pattern": "^[a-z_\\-0-9]*$",
      "title": "Name",
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  "title": "ModelA",
  "type": "object"
}
"""

print(json.dumps(ModelAEdit.model_json_schema(), indent=2))
"""
{
  "properties": {
    "name": {
      "description": "The name of the entity. Should contain only lowercase letters, numbers, - and _",
      "maxLength": 100,
      "pattern": "^[a-z_\\-0-9]*$",
      "schema_ui": {
        "readOnly": true
      },
      "title": "Name",
      "type": "string"
    }
  },
  "required": [
    "name"
  ],
  "title": "ModelAEdit",
  "type": "object"
}
"""
```

That being said, this is a question that comes up quite often, and I think it'd be helpful if we came up with a recommended approach (or 2) that we include in the `Field` concepts docs. I've made a note of this on the above ^^ `Field` docs update issue.

Let me know if you have any questions!
