### ISSUE TITLE
I can no longer concatenate urls with str

### ISSUE THREAD

**Issue by rafrafek** [pydantic/pydantic#8281]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I can no longer concatenate urls with str:
```
TypeError: unsupported operand type(s) for +: 'pydantic_core._pydantic_core.Url' and 'str'
```

It was working fine in v1.

### Example Code

```Python
from pydantic import AnyHttpUrl, HttpUrl, TypeAdapter

url_1 = TypeAdapter(AnyHttpUrl).validate_python("https://www.example.com")
print(url_1 + "/foo")

url_2 = TypeAdapter(HttpUrl).validate_python("https://www.example.com")
print(url_2 + "/foo")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=false
                 install path: /Users/user_name/repo_name/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Aug 28 2023, 10:35:19)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.1.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 email-validator-2.1.0.post1
```

**Comment by StrawHatDrag0n** [comment]
@sydney-runkle I can work on this.

**Comment by sydney-runkle** [comment]
@StrawHatDrag0n,

Fantastic! Ping me whenever you need a review :)

**Comment by StrawHatDrag0n** [comment]
@sydney-runkle I think this is related to the `pydantic-core` as the base `Url` class seems to be defined there. I think I need to add `__add__` and `__radd___` for this to work.

**Comment by GautamDhiman** [comment]
Hey @sydney-runkle ,

Greetings, just wanted to know if this issue is still open for assignment, I express my interest to resolve this issue as my first open source contribution.
Although @StrawHatDrag0n has done half of the work by telling us what needs to be done.

Thanks

**Comment by sydney-runkle** [comment]
@GautamDhiman,

Go for it! Happy to review a PR :).

**Comment by GautamDhiman** [comment]
Hey @sydney-runkle ,
I have created the changes on local, and have no idea how to test it.
Also, while pushing the changes, I am getting below error and would like your help here

```
ERROR: Permission to pydantic/pydantic-core.git denied to GautamDhiman.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by sydney-runkle** [comment]
@GautamDhiman,

You'll have to create a fork of the repository and push your changes there.

Additionally, for testing, you can follow the trends we have in the `tests` folder in `pydantic-core`. You'll want to set up a virtual environment and run `make test` to run through all of the tests and verify that everything is still passing.

**Comment by GautamDhiman** [comment]
@sydney-runkle ,

I think I have to modify the code in _**src/url.rs**_, Can you please confirm if I am on the right track? 
FYI:  this will be my first time writing code in rust

**Comment by sydney-runkle** [comment]
@GautamDhiman, sounds correct!

**Comment by GautamDhiman** [comment]
@sydney-runkle ,
Running into some issue when committing the change, Lint Rust fails in pre-commit.

using 
```
rustc==1.74.0 
cargo==1.74.0
```


```
Lint Rust................................................................Failed
- hook id: lint-rust
- exit code: 2

cargo fmt --version
Unrecognized option: 'version'
```

**Comment by samuelcolvin** [comment]
Very weird if they've removed the `--version` flag. Maybe skip pre-commit, create the pr and we can look at that separately.

**Comment by sydney-runkle** [comment]
@GautamDhiman and @rafrafek,

We've decided to close this issue, on account of the fact that there is no clear answer to supporting the type returned from `Url + str` types (should it be `Url` or `str`)?

Right now, the user can decide with the following:
`str(some_url) + str_url` for a `str`, and `Url(str(some_url) + str_url)` for a `Url`.

I'll tag this with the V3 label in case we make a final decision resulting in a change for V3.

**Comment by davidhewitt** [comment]
Just to add a thought for V3, one possible solution might be to have `Url` inherit from `str` again, though we might need to make some changes in PyO3 to support that. Then IMO the right answer would be to return a Url from the concatenation, but a Url would also be a str, making everyone happy 😉

**Comment by Bickio** [comment]
One option is to copy [PathLib's `/` operator](https://docs.python.org/3/library/pathlib.html#operators), and allow `some_url / "sub/path/whatever"`, producing a `Url`
