### ISSUE TITLE
Classes that are generic in stubs but not at runtime causes TypeError

### ISSUE THREAD

**Issue by butvinm** [pydantic/pydantic#8291]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The use of generic classes in stubs but not at runtime, as mentioned in the [mypy docs](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime), within Pydantic models can lead to a TypeError.

**Code Example:**
> Sorry, but I fall to provide some reproducible example without third-party dependencies
 
Consider the following code snippet:

```python
from __future__ import annotations
from asyncpg import Connection, Record

class Test(BaseModel):
    a: Connection[Record]
```

**Error Output:**
The resulting error output is as follows:

```
 File "/home/butvinm/Dev/app/api_v1/routes/tables.py", line 24, in <module>
    class Test(BaseModel):
  File "/home/butvinm/Dev/assignment/.venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 181, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/butvinm/Dev/.venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 426, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/butvinm/Dev/.venv/lib/python3.12/site-packages/pydantic/_internal/_fields.py", line 120, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/butvinm/Dev/.venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/butvinm/Dev/.venv/lib/python3.12/site-packages/pydantic/_internal/_typing_extra.py", line 224, in eval_type_lenient
    return typing._eval_type(value, globalns, localns)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/butvinm/.pyenv/versions/3.12.0/lib/python3.12/typing.py", line 393, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/butvinm/.pyenv/versions/3.12.0/lib/python3.12/typing.py", line 900, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
TypeError: type 'Connection' is not subscriptable
```

**Motivation:**
The ability to use such types is crucial in certain scenarios and cannot be circumvented. For example, when such a type is employed in a FastAPI path operation.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/butvinm/Dev/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 (main, Nov 19 2023, 10:38:13) [GCC 13.2.1 20230801]
                     platform: Linux-6.6.2-1-MANJARO-x86_64-with-glibc2.38
             related packages: fastapi-0.104.1 mypy-1.7.1 typing_extensions-4.8.0
```

**Comment by Viicos** [comment]
Not much Pydantic can do here (stubs are purely decoupled from runtime). Anyway, you would have to define a custom type to perform validation as Pydantic does not know about the `Connection` class. So I think you could make it work by [creating a subclass](https://docs.pydantic.dev/latest/concepts/types/#customizing-validation-with-__get_pydantic_core_schema__) specific for Pydantic.

**Comment by butvinm** [comment]
@Viicos, appreciate your advice! I'll explore addressing this issue through custom validation, as you suggested. However, I'm curious: given that TypeError on stubs-only generics can be disabled using from __future__ import annotations, is there a way to leverage this in the internals of Pydantic?

**Comment by Viicos** [comment]
I think on the Pydantic side we could catch `TypeError`s in `eval_type_lenient` and maybe raise a warning, but in any case you will have to either set `arbitrary_types_allowed` to `True` or define a custom pydantic type. I will look into this to see if catching the `TypeError` is doable.

**Comment by anagorko** [comment]
I ran into this problem when using networkx library with types-networkx stubs from typeshed.

My solution that seems to be working so far was to add

nx.DiGraph.__class_getitem__ = classmethod(lambda cls, item: 'nx.DiGraph')

after importing networkx as nx.

**Comment by mlsimon734** [comment]
> I ran into this problem when using networkx library with types-networkx stubs from typeshed.
> 
> My solution that seems to be working so far was to add
> 
> ```
> nx.DiGraph.__class_getitem__ = classmethod(lambda cls, item: 'nx.DiGraph')
> ```
> 
> after importing networkx as nx.

For others who have this exact issue with modern type checkers (i.e. `basedpyright`), you may just need to add
```python
from futures import __annotations__
```
Even if your python version already natively supports type annotations, importing `__annotations__` allows for more liberal use of brackets to fill in generic types among other QOL development benefits
