### ISSUE TITLE
model_dump but get not standared json format

### ISSUE THREAD

**Issue by lucasjinreal** [pydantic/pydantic#8296]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

           pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\miniconda\Lib\site-packages\pydantic
               python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: fastapi-0.103.1 typing_extensions-4.7.1

### Example Code

```Python
'choices': [{'index': 0, 'delta': {'role': 'assistant', 'content': ''}, 'finish_reason': None}], 'created': 1701677440110}


json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\miniconda\Lib\site-packages\pydantic
               python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: fastapi-0.103.1 typing_extensions-4.7.1
```

**Comment by lucasjinreal** [comment]
the doc says `model_dump` did same way like `model_dump_json`, but it not says their are actually different on final result!

**Comment by Viicos** [comment]
The examples given in docs should be pretty self explanatory
