### ISSUE TITLE
More details on `TypeError: 'type' object is not subscriptable`

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8307]
if you use python 3.10+ types like `list` with python <3.8, you get a very ugly error like:

```
env38/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py:542: in _model_schema
    computed_fields=[
env38/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py:543: in <listcomp>
    self._computed_field_schema(d, decorators.field_serializers)
env38/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py:1518: in _computed_field_schema
    return_type = _decorators.get_function_return_type(d.func, d.info.return_type, self._types_namespace)
env38/lib/python3.8/site-packages/pydantic/_internal/_decorators.py:776: in get_function_return_type
    hints = get_function_type_hints(
env38/lib/python3.8/site-packages/pydantic/_internal/_typing_extra.py:251: in get_function_type_hints
    type_hints[name] = typing._eval_type(value, globalns, types_namespace)  # type: ignore
../../.pyenv/versions/3.8.16/lib/python3.8/typing.py:270: in _eval_type
    return t._evaluate(globalns, localns)
../../.pyenv/versions/3.8.16/lib/python3.8/typing.py:518: in _evaluate
    eval(self.__forward_code__, globalns, localns),
<string>:1: in <module>
```

Problem is:
1. if doesn't tell you the link the error happened on
2. it doesn't tell you what type was wrong

It would be great if we could give more details in a custom error, ideally including the line number and typ repr.

@alexmojaki any thoughts as this might relate to your work automatically accepting these types.

**Comment by alexmojaki** [comment]
I think it's orthogonal to my work. I'll just look at the error message to guess it it's worth trying the backport.

In general I think it'd be good to show more info about *any* exception thrown here. It looks pretty easy to make a message containing the function name/lineno/filename, the parameter `name`, and maybe the source code in a ForwardRef.

**Comment by alexmojaki** [comment]
I don't think I can get to this any time soon, but it'd be a good first issue.

**Comment by Viicos** [comment]
Related: https://github.com/pydantic/pydantic/issues/8291

**Comment by Viicos** [comment]
I believe this was fixed thanks to Alex's work.
