### ISSUE TITLE
`ValidationError` exceptions are not roundtrippable via `pickle`

### ISSUE THREAD

**Issue by kezabelle** [pydantic/pydantic#8313]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This might be a pydantic-core issue rather than pydantic proper, I'm afraid I don't know the division or the library well enough to know 🤷 

It is currently not possible to (de-)serialise a `ValidationError`[^1] raised when failing to construct a `BaseModel` correctly.

This "normally" doesn't present a problem, but there are circumstances where it's "necessary" to be able to serialize & deserialize the data. Specifically as one example, and the case in which I've found it, I've got a [Django](https://www.djangoproject.com/) app; Django's test runner is able to split work over N processes, and when an exception is encountered, it attempts to resolve it using the venerable [tblib](https://pypi.org/project/tblib/) transparently by relying on the [pickleability of the error](https://github.com/django/django/blob/66d58e77de3196404e0820a6fef0a6144186015a/django/test/runner.py#L179-L185) (see also `check_picklable` further down)

The inability to pickle the exception is _kinda_ a showstopper for me (selfishly, personally) introducing `pydantic` to such a codebase, because the additional friction introduced by potentially needing to re-run the test suite serially would just gum things up, unfortunately.

[^1]: And potentially others? I've no idea.

### Example Code

```python
from pydantic import BaseModel
import pickle

class A(BaseModel):
    b: str

try:
    A(b=None)
except Exception as exc:
    pickle.loads(pickle.dumps(exc))
```
yields:

```
TypeError: No constructor defined
```

The **dumped** bytestring looks like:
```python
b'\x80\x04\x957\x00\x00\x00\x00\x00\x00\x00\x8c\x1cpydantic_core._pydantic_core\x94\x8c\x0fValidationError\x94\x93\x94)R\x94.'
```

The representation (using `pickletools.dis`) looks like:

```
    0: \x80 PROTO      4
    2: \x95 FRAME      55
   11: \x8c SHORT_BINUNICODE 'pydantic_core._pydantic_core'
   41: \x94 MEMOIZE    (as 0)
   42: \x8c SHORT_BINUNICODE 'ValidationError'
   59: \x94 MEMOIZE    (as 1)
   60: \x93 STACK_GLOBAL
   61: \x94 MEMOIZE    (as 2)
   62: )    EMPTY_TUPLE
   63: R    REDUCE
   64: \x94 MEMOIZE    (as 3)
   65: .    STOP
highest protocol among opcodes = 4
```

The `tblib` machinery that can also end up triggered for this is [`unpickle_exception`](https://github.com/ionelmc/python-tblib/blob/master/src/tblib/pickling_support.py#L27-L35) which would ultimately require that `ValidationError(*args)` works OK.

### Further remarks

Replacing:
```python
from pydantic import BaseModel
```
with:
```python
from pydantic.v1 import BaseModel
```
allows for the `pickle.loads(pickle.dumps(...))` dance to complete successfully.  So that's kinda unfortunate, it seems to be related to the new version (and possibly the built extension module? Total guess!)

### Python, Pydantic & OS Version

```Text
        pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=true
                 install path: /path/to/python/lib/python3.10/site-packages/pydantic
               python version: 3.10.2 (main, Mar  7 2022, 09:21:29) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-12.6.1-arm64-arm-64bit
             related packages: typing_extensions-4.7.1 mypy-1.7.1
```

**Comment by sydney-runkle** [comment]
@kezabelle,

Thanks for bringing this to our attention. I do believe that changes would be made in `pydantic-core` to support pickling of `ValidationError`s.

@davidhewitt, how hard would a change like this be to implement?
