### ISSUE TITLE
Surprising difference in validation between collections.abc.Sequence and typing.Sequence

### ISSUE THREAD

**Issue by jenshnielsen** [pydantic/pydantic#8321]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I was upgrading some code to drop python 3.9 support and ran into a validation error when replacing `typing.Sequence` with `collections.abc.Sequence` in the example below the basemodel fail to validate without `arbitrary_types_allowed` if `collections.abc.Sequence` is used without subscript (which normally would be equivalent to `collections.abc.Sequence[Any]`

```
PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'collections.abc.Sequence'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.5/u/schema-for-unknown-type
```

The same issue (with a slightly different error message) happens in v1

### Example Code

```Python
from collections.abc import Sequence
from typing import Sequence as TSequence
from pydantic import BaseModel

class DoesNotWork(BaseModel):
    bar: Sequence = [1,2,3]

class Works1(BaseModel):
   bar: TSequence = [1,2,3]

class Works2(BaseModel):
   bar: Sequence[Any] = [1,2,3]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\jenielse\Miniconda3\envs\qcodespip311\Lib\site-packages\pydantic
               python version: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: mypy-1.7.1 typing_extensions-4.8.
```

**Comment by Kludex** [comment]
Yes, at least the error message should be more precise. But I think `collections.abc.Sequence` should just work.

**Comment by sydney-runkle** [comment]
Indeed, this is not the behavior that one would expect. I recently fixed a bug with respect to `Sequence` validation.

When this issue is addressed, I think we should revisit the refactor I've suggested in this PR: https://github.com/pydantic/pydantic/pull/8614
