### ISSUE TITLE
Pydantic Field

### ISSUE THREAD

**Issue by x4zx** [pydantic/pydantic#8339]
### Discussed in https://github.com/pydantic/pydantic/discussions/8338

<div type='discussions-op-text'>

<sup>Originally posted by **x4zx** December  9, 2023</sup>
Is there any way to pass child keys to pydantic?

Example, there is this json:
```json
"author": {
        "avatars": {
            "url_list": ["http://example.com/avatar.jpg"],
            "uri": "9b85m23y5b9034n76n43n9376"
        }
    }
```
And the task is to define for a field in our model the path to the first element of the list or just any other key in the dictionary. It will look like this:
```py
class MyModel(BaseModel):
    avatar_url: str = Field(alias='author.avatars.url_list.0')
    avatar_uri: str = Field(alias='author.avatars.uri')

# Example of use
data = {
    "author": {
        "avatars": {
            "url_list": ["http://example.com/avatar.jpg"],
            "uri": "9b85m23y5b9034n76n43n9376"
        }
    }
}

model = MyModel(**data)
print(model.avatar_url) # http://example.com/avatar.jpg
print(model.avatar_uri) # 9b85m23y5b9034n76n43n9376
```</div>

**Comment by Viicos** [comment]
I've answered in the original discussion (no need to open an issue for questions)
