### ISSUE TITLE
ConfigDict > `frozen=True` does not seem to work

### ISSUE THREAD

**Issue by GrosLalo** [pydantic/pydantic#8342]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

i am expecting that setting `frozen=True` on the configuration of a model (e.g A in code below) will prevent the updating of a field on an instance of the model. I am expecting similar behavior to `@dataclass(frozen=True)` on dataclasses (from stdlib). Code below illustrates the objective and problem

Note, I understand that one can leverage `Field(..., frozen=True)` but, I would like this to be the default behavior for all fields such that one can also create immutable instances of sub-classes to the model.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict
from dataclasses import dataclass

class A(BaseModel):
    _model_config = ConfigDict(
        frozen=True,
    )    
    x: str

@dataclass(frozen=True)
class B:
    x: str

a = A(x="hello")
assert a.x == "hello"
a.x = "bye"  # This should have been an issue
assert a.x == "bye" 

b = B(x="hello")
assert b.x == "hello"
# b.x = "bye" # Raises a FrozenInstanceError
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/glalo/.pyenv/versions/3.11.4/envs/eac/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Nov 22 2023, 09:26:48) [GCC 13.2.0]
                     platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.38
             related packages: typing_extensions-4.8.0 mypy-1.7.1
```

**Comment by samuelcolvin** [comment]
`model_config` shouldn't have the underscore.

Where did you see it with an underscore?

**Comment by GrosLalo** [comment]
Yes. i had a typo in my code. Thanks
