### ISSUE TITLE
JSON serialization issue with ipaddress classes as alternative

### ISSUE THREAD

**Issue by mathiasertl** [pydantic/pydantic#8343]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

JSON serialization seems to have an issue when a value is typehinted with `ipaddress` classes as an alternative - interestingly this seems to depend on the order of declaration.

As the pasted code example shows, a value typehinted as `bool | ipaddress.IPv4Address` serializes differently from `ipaddress.IPv4Address | bool`. Note how the value is (incorrectly) converted to a `str` in the `BadModel` class.

### Example Code

```Python
import ipaddress

from pydantic import BaseModel


class GoodModel(BaseModel):
    value: bool | ipaddress.IPv4Address


class BadModel(BaseModel):
    value: ipaddress.IPv4Address | bool


# OKAY: {'value': True}
print(GoodModel(value=True).model_dump(mode="json"))

# ISSUE - value is str: {'value': 'True'} 
print(BadModel(value=True).model_dump(mode="json"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/mati/.pyenv/versions/3.11.1/envs/django-ca/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Jan 31 2023, 15:43:27) [GCC 11.3.0]
                     platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.8.0 mypy-1.7.1
```

**Comment by sydney-runkle** [comment]
@davidhewitt,

Could you take a look at this? I'm guessing this belongs in the category of `Union` serialization issues to be fixed in `pydantic-core`.

**Comment by davidhewitt** [comment]
Yes (do we have a tracking issue for all of these?)
