### ISSUE TITLE
serialization JSON Schema wrong (?) for computed fields

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8347]
Example

```py
from pydantic import BaseModel, computed_field


class MyModel(BaseModel):
    x: int

    @computed_field()
    def title(self) -> str:
        return f'Title {self.x}'


print(MyModel.model_json_schema(mode='serialization'))
```

shows `'readOnly': True` for `title, I don't think that makes sense for a serialization schema, but not that sure?

**Comment by sydney-runkle** [comment]
Chatting with @dmontagu more, I don't think this makes sense to change now. In a sense this property is `readOnly`, but I get your point that this isn't entirely relevant for a serialization schema. If we have a strong argument for removing it, could do this in v3 👍.

**Comment by dmontagu** [comment]
For reference (from [here](https://json-schema.org/understanding-json-schema/reference/annotations)):

> **New in draft 7**
>
> The boolean keywords `readOnly` and `writeOnly` are typically used in an API context. `readOnly` indicates that a value should not be modified. It could be used to indicate that a PUT request that changes a value would result in a 400 Bad Request response. `writeOnly` indicates that a value may be set, but will remain hidden. In could be used to indicate you can set a value with a PUT request, but it would not be included when retrieving that record with a GET request.

Given their example scenario — "It could be used to indicate that a PUT request that changes a value would result in a 400 Bad Request response" — seems to reasonably apply to this usage, I would argue that this usage does capture the intent, even if in principle you might have a different schema for validation vs. serialization when using this.

More generally, I think even though it's only produced in a serialization context, there's still some small value in indicating that a field comes from a property, even if you have to know it came from pydantic to know the full implications there.

I'll also note that if we wanted to produce a single schema even when computed fields are present (which I think has been a request in the past), making the field non-required and including the `readOnly: true` annotation seems like a good way to accomplish that.

At any rate, I think we should either consider it a breaking change, or have a good justification that including `readOnly: true` is semantically incorrect before making the change given it has behaved this way for some time now and some users might now have written code dependent on the current behavior.
