### ISSUE TITLE
`BaseModel` in JSON Schema is really ugly

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8348]
```py
from pydantic import BaseModel


class MyModel(BaseModel):
    x: BaseModel

print(MyModel.model_json_schema())
```

Shows the full docstring for `BaseModel` in the JSON Schema, I think we should specifically omit the description here

**Comment by dmontagu** [comment]
I'll just add here for future reference, that while it probably never makes sense to use a field of type `BaseModel` during validation, it _does_ make sense to me that you might want to use a field with that annotation for serialization, as a slightly more type-safe-in-python version of `Any`. (I guess it will have basically the same JSON schema as `Any` though.)

(I was initially confused by this and thought about it a bit, so I'm commenting it here in case anyone finds this and wonders, like I did, why this would ever be relevant.)
