### ISSUE TITLE
`default_factory` not respected by JSON Schema

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#8350]
```py
from pydantic import BaseModel, Field

class MyModel(BaseModel):
    x: list[int] = Field(default_factory=list)


print(MyModel.model_json_schema())
```

Here `x` does not have a `default` which it should

**Comment by sydney-runkle** [comment]
@samuelcolvin,

I'd consider this a change (we had a test in place confirming that the `default` wasn't included in the json schema if a `default_factory` was specified on a field), but I think it's a change we should make.

**Comment by sydney-runkle** [comment]
As of now, #5945 gives some good reasons to not implement this change. We also offer the ability to uncomment a small section of code to change the behavior, if desired: 

https://github.com/pydantic/pydantic/blob/59c617259da98f550cd83dadbceadd4e89904788/pydantic/json_schema.py#L982-L990

Happy to reconsider more if there's high demand for a change, and we can revisit when making V3 plans (as this is a breaking change). Closing as not planned... for now.
