### ISSUE TITLE
`model.model_copy(deep=True)` does not make a copy of `model_config`

### ISSUE THREAD

**Issue by phdowling** [pydantic/pydantic#8358]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pretty simple issue, I am not sure if this is intended (or documented) but it tripped me up today:

When I modify model_config on a deep-copied object, the original object's config is affected. I can work around this, but it seems unintentional - feel free to close if that is not the case.

### Example Code

```Python
from pydantic import BaseModel

class MyModel(BaseModel, frozen=True):
    a: int

m = MyModel(a=1)
m_for_editing = m.model_copy(deep=True)  # make a copy
m.model_config['frozen'] = False  # unfreeze the copy so we can make edits
m_for_editing.a = 2

assert m_for_editing.a == 2, 'copy was not updated'  # this passes as expected
assert m.a == 1, 'original was modified'  # of course this passes too
assert m.model_config['frozen'], "original was unfrozen"  # this fails
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /Users/<me>/Library/Caches/pypoetry/virtualenvs/collab-api-70QdxADe-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 (main, Nov 14 2023, 16:45:41) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.3-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 pydantic-settings-2.1.0 fastapi-0.104.1
```

**Comment by sydney-runkle** [comment]
@phdowling,

This does seem like a bug. Thanks for reporting this! I'll mark this as `good first issue` in case anyone wants to take this on in the next few days :). We'll make sure to include this in the next minor release.

**Comment by phdowling** [comment]
Thanks - another thing that tripped me up along the same lines: I expected model_config to be instance-local, but it seems to be shared across all models of the same type. In practice, this means that doing
`m.model_config['frozen'] = False`
on once instance un-freezes all objects of the same type. Would you consider that to be the same underlying bug?

**Comment by sydney-runkle** [comment]
`model_config` isn't meant to be instance local. Good question though. We could add a docs update to make that more clear 👍.

**Comment by NeevCohen** [comment]
@sydney-runkle I'll try taking a shot at this on the weekend

**Comment by phdowling** [comment]
Okay, if model_config is in fact not meant to be instance-local, then this isn't really a bug (i.e. neither of the two issues I described). So at most, a docs update is all that is needed here, right?

For clarity: there isn't a baked-in way in pydantic to selectively un-freeze a single instance of a model, right? It's not hard to implement by overriding __setattr__, I just want to be sure I'm understanding correctly.

**Comment by sydney-runkle** [comment]
@phdowling,

Good catch, I'd agree. Going to mark this as a docs issue. @NeevCoehn, feel free to still submit a docs update PR if you're willing :).
