### ISSUE TITLE
'NoneType' object has no attribute 'model_dump' error during  `model_validator` execution

### ISSUE THREAD

**Issue by NightSkySK** [pydantic/pydantic#8360]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Code is working once the `model_validation` is disabled. 
Once I send to api json like this
```json
{
  "is_occupied": false,
  "is_restricted": false,
  "rented_until": null
}
```
I get an error: 'NoneType' object has no attribute 'model_dump'
Once i put something like that:
```json
{
  "is_occupied": false,
  "is_restricted": false,
  "rented_until": "2024-12-31"
}
```
validator working and rising exception: "Storage must be occupied if rented_until is set" as intended

### Example Code

```Python
class StorageUpdate(BaseModel):
    is_occupied: bool = Field(False, example=False)
    is_restricted: bool = Field(False, example=False)
    rented_until: Optional[date] = Field(None, example="2025-12-31")

    @model_validator(mode="after")
    def is_occupied_validator(self) -> "StorageUpdate":
        rented_until = self.rented_until
        if rented_until is not None and self.is_occupied is False:
            raise ValueError("Storage must be occupied if rented_until is set")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: D:\mSpaceLock\mSpaceLock-www\env\Lib\site-packages\pydantic
               python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: email-validator-2.0.0.post2 fastapi-0.104.1 typing_extensions-4.8.0
```

**Comment by jevins09** [comment]
I believe you need to add a `return self` at the end of your `is_occupied_validator` method. I can confirm that your code works as expected after adding it.

This is also how the documentation on [Model Validators](https://docs.pydantic.dev/latest/concepts/validators/#model-validators) describes it.

**Comment by NightSkySK** [comment]
Indeed, that is a mistake on my side. Thank you very much for help,
