### ISSUE TITLE
Unexpected case change for to_camel alias generator

### ISSUE THREAD

**Issue by spacemanspiff2007** [pydantic/pydantic#8361]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a mixture of fields in `snake_case` and `camelCase.`
To align the field naming I want to use the to_camel alias generator.
However the alias generator does also change the existing `camelCase` names.

````python
from pydantic.alias_generators import to_camel

print(to_camel('myId'))
````

Outputs ``myid`` instead of ``myId``

### Python, Pydantic & OS Version

```Text
pydantic-core version: 2.14.5
pydantic-core build: profile=release pgo=true
python version: 3.10.9
```

**Comment by sydney-runkle** [comment]
@spacemanspiff2007,

Good question. The `to_camel` alias generator is used to convert a `snake_case` string to `camelCase`:
https://github.com/pydantic/pydantic/blob/2155e4d8759e80d8a21339e61c9939c6b042c11b/pydantic/alias_generators.py#L20-L21

To get the behavior you're looking for, you could define a custom generator that first returns `to_camel(to_snake(your_str))`.

**Comment by spacemanspiff2007** [comment]
@sydney-runkle 
Would it be possible to reopen this as a bug? `to_camel`should not change case when the name is already camelCase!
It should do nothing because it already is camelCase.
Or at least rename it to ``snake_to_camel``so it's clear that it can not be called on camelCase names

**Comment by sydney-runkle** [comment]
@spacemanspiff2007,

Sure, we can reopen with the general idea of renaming (with a period of deprecation warnings on the old function) to add clarity to these builtin functions.
