### ISSUE TITLE
Pydantic should parse simple yyyy-MM-dd for datetime

### ISSUE THREAD

**Issue by aersam** [pydantic/pydantic#8363]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

```python
from pydantic import BaseModel
from datetime import datetime
import json

datetime.fromisoformat("2021-01-01")  # this works fine


class Model(BaseModel):
    dt: datetime


Model.model_validate_json(json.dumps({"dt": "2021-01-01T00:00"})) # works, of course
Model.model_validate_json(json.dumps({"dt": "2021-01-01"})) # fails
```

I think pydantic is too strict here, especially since datetime.fromisoformat works without trouble.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@aersam,

Agreed, we will implement support for this in `pydantic-core` :).

**Comment by sydney-runkle** [comment]
@aersam,

Just added support for this, will be released in `2.6.0` :)

**Comment by miikka** [comment]
Hey, what's the best way to disable this new feature? We do not want to allow `yyyy-MM-dd` for datetimes.

**Comment by sydney-runkle** [comment]
@miikka,

You can use strict mode on that `datetime` type (or at the model level):

```py
from datetime import datetime, timezone
from typing import Annotated

from pydantic import BaseModel, Strict, ValidationError

StrictDatetime = Annotated[datetime, Strict()]

class Model(BaseModel):
    dt_strict: StrictDatetime
    dt_lax: datetime

try:
   m = Model(dt_strict='2021-01-01', dt_lax='2021-01-01')
   print(repr(m))
except ValidationError as e:
    print(e)
    """
    1 validation error for Model
    dt_strict
    Input should be a valid datetime [type=datetime_type, input_value='2021-01-01', input_type=str]
        For further information visit https://errors.pydantic.dev/2.6/v/datetime_type
    """
```

**Comment by miikka** [comment]
@sydney-runkle Thanks, that's neat! Unfortunately it turns out that doesn't help with FastAPI's path parameters coercion (which uses Pydantic under the hood with `TypeAdapter.validate_python` which does not accept strings at all for strict mode datetimes) but maybe that's better discussed somewhere else than in this issue.

**Comment by sydney-runkle** [comment]
@miikka,

Feel free to open another issue and we can continue discussion there!
