### ISSUE TITLE
Common mistakes docs section

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#8380]
Many of the issues we get are repeats of the same common questions / mistakes. We should create a small docs section logging said common mistakes and their solutions :).

**Comment by SohamG934** [comment]
Hello, I would like to work on this issue!

**Comment by sydney-runkle** [comment]
@SohamG934,

Great! Feel free to submit a PR and I'll review. A few common mistakes I can think of:

* Mixing up how `use_enum_values` is used (we have an example in the API docs)
* Mixing up how to add annotations to compound types (see https://github.com/pydantic/pydantic/issues/8362)

I'm sure there are many more that we could include - you could search on `duplicate` tags to see what issues have been reported the most frequently!

**Comment by SohamG934** [comment]
Hello, shall i make a single doc mentioning the title of the issue and then
linking the closed issue solution link for reference? If not, how do you
propose I solve this?

**Comment by sydney-runkle** [comment]
Hi @SohamG934,

I think we should create a new page for our documentation site that has various examples of common mistakes and ways to correct said mistakes. I don't see a reason to reference issues for the most part. You can create a fork of the pydantic repo and submit a PR with your changes 👍

**Comment by bL34cHig0** [comment]
> Hi @SohamG934,
> 
> I think we should create a new page for our documentation site that has various examples of common mistakes and ways to correct said mistakes. I don't see a reason to reference issues for the most part. You can create a fork of the pydantic repo and submit a PR with your changes 👍

Hi @sydney-runkle, is @SohamG934 still working on this issue? 

If not, I'd like to work on it. Thank you

**Comment by sydney-runkle** [comment]
@bL34cHig0,

I haven't seen a PR yet, so feel free to get started on this :). Thanks!

**Comment by sydney-runkle** [comment]
@bL34cHig0,

There's no template at the moment - I'd recommend combing through issues listed as duplicates to see what kind of issues come up often.
Could you please add this section to the `examples` section on a new page for now? Thanks!

**Comment by bL34cHig0** [comment]
@sydney-runkle 

I have started working on documenting the `common mistakes / questions`. So I wanted to ask if I am on the right track. 

Please see screenshot below. Thanks :)

![image](https://github.com/pydantic/pydantic/assets/133022207/16c7c4a7-7395-4046-8acc-b534d3d77a42)

Work done so far:

- Created a new branch called `common-mistakes-doc`
- Created a new page titled `common_mistakes.md` under the `examples` section.
- Wrote the first common question / mistake.

Please kindly review it and let me know if this structure is okay or not. Thanks again

**Comment by sydney-runkle** [comment]
@bL34cHig0,

The structure looks great. Nice work so far!

**Comment by sydney-runkle** [comment]
Here's another I think should be included: https://github.com/pydantic/pydantic/issues/8708

**Comment by sydney-runkle** [comment]
See https://github.com/pydantic/pydantic/pull/8759#issuecomment-1971737662 as the reason for closing this issue. I think this collection is more helpful to have as an issue than as an official docs page, despite my initial motivations for filing this issue.

A helpful collection of recommendations, thanks to @bL34cHig0: https://github.com/pydantic/pydantic/pull/8759

**Comment by sydney-runkle** [comment]
Below shows the relevant docs sections for explaining each of these questions:

> How to implement custom error messages?

https://docs.pydantic.dev/latest/errors/errors/#customize-error-messages

> Cannot use v1 model as type parameter in v2 generic model

https://docs.pydantic.dev/latest/migration/#changes-to-pydanticgenericsgenericmodel

> AnyUrl adds trailing slash (/) in URL validation

https://docs.pydantic.dev/latest/migration/#url-and-dsn-types-in-pydanticnetworks-no-longer-inherit-from-str
See updates here: https://github.com/pydantic/pydantic/issues/7186

> `TypeError` occurs when using Pydantic's Constraint Types

This one makes more sense to have reported + documented as an issue, which is explained well here:

This error occurs if you are using Python `3.9.7`. To prevent this, upgrade to Python `3.9.8` or higher as there is a
[bug](https://bugs.python.org/issue45081) in version `3.9.7`. Also, it is discouraged to use some of the
[**con**](https://docs.pydantic.dev/latest/api/types/#pydantic.types.conint) functions because they will be deprecated
in Pydantic **3.0**. So check out the **Discouraged** warning for alternative solution.

> `validate_call` decorator raises "AttributeError" when applied to an instance method of a class with `__slots__`

No longer an issue

> Two validators consecutively do not report all errors

Pydantic does not currently support exhaustive validation, so it stops after the first error on a given field and
reports that validation error. Relevant feature request, for tracking: https://github.com/pydantic/pydantic/issues/7476

> Can not use **ValidationError** `__init__` method

https://docs.pydantic.dev/latest/api/pydantic_core/#pydantic_core.ValidationError provides info on helpful static methods

> Pydantic does not allow Literal enum value discriminator to be initialized by string

A simple solution to this is to allow your class to inherit from both `str` and `Enum`. This is the one case where I do think we **could** use a docs update in the relevant section of the docs :).
