### ISSUE TITLE
coerce_numbers_to_str needs a per-field variant

### ISSUE THREAD

**Issue by jkugler** [pydantic/pydantic#8383]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We are migrating our code from Pydantic 1 to 2, and came across a situation where we do want some fields to coerce numbers to strings, but other fields in the model should not be coerced. As far as I can tell from the docs, `coerce_numbers_to_str` is an all-or-nothing thing, and will affect the entire model. Being able to specify fields would be nice. Maybe something like:
```
model_config = ConfigDict(coerce_numbers_to_str="field1,field2,field3")
```
I don't know if that's the best syntax, but that would serve our purposes.

If there is a way to work around this feature not being there, could it be added to https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.coerce_numbers_to_str ?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@jkugler,

Seems like a reasonable feature request 👍. I think we should still stick with `True` and `False` as the allowed settings, but we could support `Field(..., coerce_numbers_to_str=True)` or something along those lines.

**Comment by jkugler** [comment]
Seems perfectly reasonable. I'm a Pydantic newbie thrown in the deep end by migrating a project from v1 to v2, so will fully admit not being fully up to speed with the API.

**Comment by sydney-runkle** [comment]
@jkugler,

No worries. Let us know if there's anything else you need help with in terms of your migration, or if you notice anything missing from the migration guide.

**Comment by NeevCohen** [comment]
Hey @sydney-runkle, I was looking into this issue and I think I can work on this. I looked at the `StrValidator` in core, and saw that it only reads the `coerce_numbers_to_str` configuration from the [config](https://github.com/pydantic/pydantic-core/blob/193f5d7a8627c988b1c7fab9a3712c779afbbe94/src/validators/string.rs#L187). My thoughts were to add a `coerce_numbers` field to the `str_schema` and make `StrValidator` read that value from the schema as well as from the model config.

**Comment by sydney-runkle** [comment]
@NeevCohen,

Sounds great! Go for it - I think you have the right approach :). Maybe we stick with `coerce_numbers_to_str` as the name of the flag just to be consistent. Prioritize the field level setting, of course :).

**Comment by NeevCohen** [comment]
@sydney-runkle I opened a PR in core to support this - pydantic/pydantic-core#1249

**Comment by NeevCohen** [comment]
@sydney-runkle
Thanks for your help with the PR in core! Now that support was merged into core, I started looking into implementing the change in pydantic. I added a `coerce_numbers_to_str` option to `FieldInfo`, and I was wondering where would be the correct place to pass that value on to `str_schema()`. I thought maybe in [`GenerateSchema._common_field_schema`](https://github.com/pydantic/pydantic/blob/b30f44dbc2dd4f57b55fbfaeb6162a949504b048/pydantic/_internal/_generate_schema.py#L1037), I could inject it into the `schema` variable? Not 100% sure on that, perhaps you have a better idea?

**Comment by sydney-runkle** [comment]
@NeevCohen,

Hmm, I think here would probably be the most appropriate location: https://github.com/pydantic/pydantic/blob/477e0a2e23fa7262a1365129a99acb586ee3baa5/pydantic/_internal/_known_annotated_metadata.py#L159

**Comment by NeevCohen** [comment]
@sydney-runkle Thanks!

I Openend a PR #9137, but it can't be merged until a new version of core (with support for this) is released and the version is updated in pydantic.

**Comment by jkugler** [comment]
Brilliant, thanks!
