### ISSUE TITLE
Different behaviour depending on position of `Field` in `Annotated`

### ISSUE THREAD

**Issue by jurasofish** [pydantic/pydantic#8391]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The snippet of code below demonstrates different behaviour depending on the order of `Field`/`AfterValidator` inside `Annotated`.

When `Field` is first it's fine, while with `Field` last it's not.
It seems that when `Field` is first, pydantic skips checking the length of the value because it's null (which I understand to be how pydantic is intended to work based on my usage. However, I can't find anything authoritative to support this) whereas when `Field` is after the validator it blindly attempts to check its length and fails because it's None.

The snippet of code below fails with `TypeError: object of type 'NoneType' has no len()`, presumably because a value of None is being passed in for `x` which causes an error when pydantic attempts to check its length.

Is this the expected behaviour? Is there documentation or something I've missed that would have helped me anticipate this behaviour? Notably I can't see any discussion of this sort of behaviour in https://docs.pydantic.dev/2.5/concepts/validators/ or https://docs.pydantic.dev/2.5/concepts/fields/#using-annotated or anywhere else in the docs (I've searched the `/docs` dir for `order` and `annotated`)

```python
from pydantic import BaseModel, Field, AfterValidator
from typing import Annotated


class ModelOkay(BaseModel):
    x: Annotated[str | None, Field(max_length=30), AfterValidator(lambda x: x)]

class ModelNotOkay(BaseModel):
    x: Annotated[str | None, AfterValidator(lambda x: x), Field(max_length=30)]

ModelOkay(x=None)
ModelNotOkay(x=None)  # <-- errors
```

Full traceback

```
Traceback (most recent call last):
  File "...py", line 12, in <module>
    ModelNotOkay(x=None)
  File "...lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
  File "...lib/python3.11/site-packages/pydantic/_internal/_validators.py", line 267, in max_length_validator
    if len(x) > max_length:
       ^^^^^^
TypeError: object of type 'NoneType' has no len()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: ....../lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ]
                     platform: macOS-13.6.2-arm64-arm-64bit
             related packages: mypy-1.6.1 typing_extensions-4.8.0 pydantic-settings-2.0.3 fastapi-0.103.2 email-validator-2.1.0.post1
```

**Comment by Viicos** [comment]
Yes, see [here](https://github.com/pydantic/pydantic/issues/8362) for more context. An improvement to docs is planned.

**Comment by sydney-runkle** [comment]
Going to close this as a duplicate. This is a helpful use case that we should consider when updating the docs, but I don't think this is a separate issue.

Also, see this section re ordering of validators within `Annotated`: https://docs.pydantic.dev/latest/concepts/validators/#ordering-of-validators-within-annotated
