### ISSUE TITLE
Validation is broken when working with gevent

### ISSUE THREAD

**Issue by rafales** [pydantic/pydantic#8392]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

So I've been hunting down an issue with a small app I'm writing. It would randomly end up with one of:
- segfault / sigbus
- `SystemError: ../Objects/dictobject.c:1899: bad argument to internal function`
- `pyo3_runtime.PanicException: Already borrowed: PyBorrowMutError`
- when debug mode was enabled, additional errors started to show up, indicating that a dict was being accessed with is no longer in scope:
  - ```python: ./Include/internal/pycore_dict.h:169: _PyDict_NotifyEvent: Assertion `Py_REFCNT((PyObject*)mp) > 0' failed.```

It is probable that this is the same issue / similar issue to #7211, as I noticed that all of the reporters mention gevent.

Issue was present both on MacOS (M1) and Linux (WSL, 64bit).

Trying to hunt down the issue, I installed python with debug mode enabled, which started uncovering some issues - mainly attempts to access a dict (set item) with refcount decreased to 0.

Here are the versions I'm using:

* `gevent==23.9.1`
* `pydantic==2.5.2`
* `pydantic-core==2.14.5`

Note that in the field below it will show `pydantic-core 2.14.4` - this is because I compiled core with debugging enabled and for some reason I ended up with 2.14.4. But the issue happens on 2.14.5 as well.

I managed to narrow down the issue and it seems that this is the recipe:
* we're using `from_attributes=True`, which will call back to python code to get attributes from a model
* called python code uses gevent (we use sleep here, in real world scenario it was sqlalchemy loading a related object)
* this somehow results in broken objects / memory, probably freed before they should be

Code sample attached below is enough to trigger the issue every time on my computer. 

I am also attaching a trace from a core dump, generated by pystack. Typically the issue happens in \model_fields.rs:200`, probably because it's the method which calls into python.
[trace.txt](https://github.com/pydantic/pydantic/files/13697918/trace.txt)

### Example Code

```Python
import gevent
from pydantic import BaseModel, TypeAdapter


class MyObjectSchema(BaseModel):
    id: str
    name: str
    slug: str


class MyObject:
    @property
    def id(self) -> str:
        gevent.sleep(0)
        return "123"

    @property
    def name(self) -> str:
        gevent.sleep(0)
        return "hello world"

    @property
    def slug(self) -> str:
        gevent.sleep(0)
        return "hello-world"


ta = TypeAdapter(MyObjectSchema)


def worker() -> None:
    for _ in range(100):
        ta.validate_python(MyObject(), from_attributes=True)


def main() -> None:
    workers = [gevent.spawn(worker) for _ in range(5)]
    gevent.joinall(workers)


if __name__ == "__main__":
    main()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.4
          pydantic-core build: profile=debug pgo=false
                 install path: /home/rafal/Code/tap-backend/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 17 2023, 20:17:41) [GCC 11.4.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 mypy-1.7.1 email-validator-2.1.0.post1
```

**Comment by samuelcolvin** [comment]
I'm pretty sure this is the same as #7211.

This has to be some deep interaction between pyo3 and gevent. We don't yet know on which library is at fault, or both, or neither.

Thanks for the extra information here, @davidhewitt is working on identifying the root cause.

**Comment by samuelcolvin** [comment]
I'll reply on #7211, just to keep the discussion in one place.

**Comment by davidhewitt** [comment]
Just wanted to say thank you @rafales for this repro; I was able to simplify this to a pure-pyo3 repro without too much trouble, which saved me a lot of time 🙏
