### ISSUE TITLE
__init__.cpython-311-darwin.so  is an incompatible architecture (have 'x86_64', need 'arm64') in M1 mac mini

### ISSUE THREAD

**Issue by foresthuo** [pydantic/pydantic#8396]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Clone and run AutoGPT code from GitHub in M1 mac mini, I get an error:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/app/cli.py", line 8, in <module>
    from autogpt.logs.config import LogFormatName
  File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/logs/__init__.py", line 1, in <module>
    from .config import configure_chat_plugins, configure_logging
  File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/logs/config.py", line 18, in <module>
    from autogpt.core.configuration import SystemConfiguration, UserConfigurable
  File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/core/configuration/__init__.py", line 2, in <module>
    from autogpt.core.configuration.schema import (
  File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/core/configuration/schema.py", line 6, in <module>
    from pydantic import BaseModel, Field, ValidationError
ImportError: dlopen(/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so, 0x0002): tried: '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (no such file), '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

It shows the __init__.cpython-311-darwin.so in pydantic is link to x86_64, but need arm64.

![1702908885459](https://github.com/pydantic/pydantic/assets/3608796/23cc20b9-1d6e-475e-b9a5-642ee145f03d)

### Python, Pydantic & OS Version

```Text
I got the same import error when running the command:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so, 0x0002): tried: '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (no such file), '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by davidhewitt** [comment]
@foresthuo can you give more information about how you have installed Python and pydantic in your virtualenv? This looks like an issue compiling pydantic with mypyc or Cython, but this is not how we package pydantic v2.

**Comment by foresthuo** [comment]
> @foresthuo can you give more information about how you have installed Python and pydantic in your virtualenv? This looks like an issue compiling pydantic with mypyc or Cython, but this is not how we package pydantic v2.

Hi David, 

Thanks for your replay. This is what I did:

1. Install Python via Homebrew with the command: brew install python.
2. Install Poetry with the command: pipx install poetry.
3. Clone AutoGPT code from GitHub which use Poetry for the packaging and building
4. Open the AutoGPT project with PyCharm Pro and it will auto create the virtualenv and install the depandences
5. Run the project with the command: ./autogpt.sh --help
6. Then you will get the problem.

More Info: I have meet the same problem with the FastAPI project.

I'm not sure if the AutoGPT is using Pydantic V2 or V1, but I'm sure the FastAPI project use the Pydantic V2.

**Comment by samuelcolvin** [comment]
It's very hard to read the output since you haven't formatted it properly, so it's hard to know what's going on.

Furthermore, lots of people (myself included) run pydantic on M1 Mac, so I'm not sure how I can help.

Try installing pydantic directly with pip using a venv you create manually, and see if it works.

**Comment by Kola-Chao** [comment]
> ### Initial Checks
> * [x]  I confirm that I'm using Pydantic V2
> 
> ### Description
> Clone and run AutoGPT code from GitHub in M1 mac mini, I get an error: Traceback (most recent call last): File "", line 1, in File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/app/cli.py", line 8, in from autogpt.logs.config import LogFormatName File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/logs/**init**.py", line 1, in from .config import configure_chat_plugins, configure_logging File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/logs/config.py", line 18, in from autogpt.core.configuration import SystemConfiguration, UserConfigurable File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/core/configuration/**init**.py", line 2, in from autogpt.core.configuration.schema import ( File "/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/autogpt/core/configuration/schema.py", line 6, in from pydantic import BaseModel, Field, ValidationError ImportError: dlopen(/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/**init**.cpython-311-darwin.so, 0x0002): tried: '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/**init**.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/**init**.cpython-311-darwin.so' (no such file), '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/**init**.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
> 
> It shows the **init**.cpython-311-darwin.so in pydantic is link to x86_64, but need arm64.
> 
> ![1702908885459](https://private-user-images.githubusercontent.com/3608796/291309768-23cc20b9-1d6e-475e-b9a5-642ee145f03d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDQ4NDAsIm5iZiI6MTcwODk0NDU0MCwicGF0aCI6Ii8zNjA4Nzk2LzI5MTMwOTc2OC0yM2NjMjBiOS0xZDZlLTQ3NWUtYjlhNS02NDJlZTE0NWYwM2QuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTA0OTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E4NTQ2Njc5ZDY0YzcxM2JhMGRhNjRlMmQ5YTA0Zjc1MTg2YWZlNzBmN2Y3ZWFhNTkwZmEwZmMyYmMyM2I0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E7rvSxOzpU7gcs6nCFD9C_5eBuJIBP1tF5TB2XkGC5Y)
> 
> ### Example Code
> _No response_
> 
> ### Python, Pydantic & OS Version
> ```
> I got the same import error when running the command:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: dlopen(/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so, 0x0002): tried: '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (no such file), '/Users/foresthuo/Projects/learn/ai/autogpt/AutoGPT/autogpts/autogpt/.venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
> ```

get any solution?
