### ISSUE TITLE
cached_property is not ignored when a model is copied and updated

### ISSUE THREAD

**Issue by rdbisme** [pydantic/pydantic#8406]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

This is somehow a contrived situation, but we had it trigger in our business code. Basically when updating a model based on an existing one which has a subfield that is a dataclass with a cached_property, a validation is triggered because the dataclass `__dict__` contains the cached value. 

### Example Code

```Python
import dataclasses
from pydantic import BaseModel
from functools import cached_property

def test_cached_property():
    @dataclasses.dataclass(frozen=True)
    class A:
        name: str

        @cached_property
        def _name(self): 
            return "name"

    class MyModel(BaseModel, arbitrary_types_allowed=True, frozen=True, extra=Extra.forbid):
        scheduler: A

    models = {
        "AX": MyModel(scheduler=A("a")),
    }

    sched = A("sched")

    models_2 = {
        "AY": models["AX"].copy(update=dict(scheduler=sched)), 
    }

    models |= models_2

    models["AY"].scheduler._name
    MyModel.parse_obj(models["AY"].dict())
```

```
__pydantic_self__ = MyModel(), data = {'scheduler': test_cached_property.<locals>.A(name='sched')}, values = {}, fields_set = {'scheduler'}
validation_error = ValidationError(model='MyModel', errors=[{'loc': ('scheduler', '_name'), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}])

    def __init__(__pydantic_self__, **data: Any) -> None:
        """
        Create a new model by parsing and validating input data from keyword arguments.
    
        Raises ValidationError if the input data cannot be parsed to form a valid model.
        """
        # Uses something other than `self` the first arg to allow "self" as a settable attribute
        values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
        if validation_error:
>           raise validation_error
E           pydantic.error_wrappers.ValidationError: 1 validation error for MyModel
E           scheduler -> _name
E             extra fields not permitted (type=value_error.extra)

pydantic/main.py:341: ValidationError
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.13
            pydantic compiled: False
                 install path: /home/rdb/git/pydantic/pydantic
               python version: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.38
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@rdbisme,

Thanks for bringing this to our attention, and thanks a ton for contributing a fix!

**Comment by sydney-runkle** [comment]
Fixed by https://github.com/pydantic/pydantic/pull/8407
