### ISSUE TITLE
Debian/ubuntu packages for v2

### ISSUE THREAD

**Issue by francbartoli** [pydantic/pydantic#8416]
Is pydantic v2 released/maintained as a linux Debian/Ubuntu package?

**Comment by samuelcolvin** [comment]
I don't think so right now, I think pydantic V2 will be added to Ubuntu main soon.

**Comment by francbartoli** [comment]
Thanks @samuelcolvin for the feedback! Do you have any timeline for that? We are looking for it https://github.com/geopython/pygeoapi/pull/1366 once our dependency policy for pygeoapi release will be in place. Please let me know if it requires sponsoring

**Comment by sydney-runkle** [comment]
@francbartoli,

We don't yet have a concrete timeline for this change, but will update this issue when we get more info 👍

**Comment by sydney-runkle** [comment]
Update on this - you can track the addition of V1 to Ubuntu here: https://bugs.launchpad.net/ubuntu/+source/pydantic/+bug/2001699.

We haven't yet been notified of a timeline for when V2 will be added. Closing this issue, as tracking should be done via the above linked issue 👍

**Comment by cjwatson** [comment]
pydantic 2.8.2 is now in Debian testing (will be Debian 13) and Ubuntu oracular (will be Ubuntu 24.10).  I just uploaded 2.9.1 to Debian unstable to bring us completely up to date; it's likely too late for that to get into Ubuntu 24.10, but I'm sure it'll be in 25.04.
