### ISSUE TITLE
V2 fails to parse number from string with spaces

### ISSUE THREAD

**Issue by valq7711** [pydantic/pydantic#8419]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

see #6958 

Such behavior is inconsistent with python (see example)

@hramezani  
>this is an intended change in V2

Could you provide the reason please?

### Example Code

```Python
from pydantic import BaseModel

num = int(' 1 ')

assert num == 1

class Foo(BaseModel):
    num: int


foo = Foo(num=' 1 ')  # raises an error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: D:\AJOB3\data-cooking\.venv\Lib\site-packages\pydantic
               python version: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.19042-SP0
             related packages: typing_extensions-4.8.0
```

**Comment by hramezani** [comment]
@valq7711 We've added `strict` mode in Pydantic V2 and here is the [reason](https://docs.pydantic.dev/latest/blog/pydantic-v2/#strict-mode).

By default, strict mode is not enabled and you can provide a string for an int field. but strings with spaces can not be parsed to an int even in lax(non-strict) mode.

Pydantic V2 uses [pydantic-core](https://github.com/pydantic/pydantic-core) for validation/serialization, written in Rust. So, it might not be consistent with Python.

It's already mentioned in [conversion table](https://docs.pydantic.dev/latest/concepts/conversion_table/) that strings `Must be numeric only, e.g. [0-9]+.` to be parsed as an int

**Comment by valq7711** [comment]
@hramezani Thanks for your answer, but I still don't understand why not strip the string in lax-mode when converting to a number, doesn't Rust have such a feature? 
I just want to say that when we 
`num: int`
it intuitively means that it will work as `int(input_value)` because `int` is a native Python type, not a custom pydantic type with special behavior.
So why do we need to make extra moves to strip the input value, which will also reduce performance?

**Comment by valq7711** [comment]
if you want native behavior - use native type as is, 
if you want to change native behavior - use annotation + pre/post-validation
Why should it be the other way around?

**Comment by hramezani** [comment]
> @hramezani Thanks for your answer, but I still don't understand why not strip the string in lax-mode when converting to a number, doesn't Rust have such a feature?

For sure Rust does have it. probably it is Rust default behavior.

**Comment by omercotkd** [comment]
when you want to parse a string with spaces in Rust to an int, the following code will not work and will throw an error:

```rust
fn main() {
    let _: i32 = " 1 ".parse().unwrap();
}
```

you need to trim the string and then parse it:
```rust
fn main() {
    let _: i32 = " 1 ".trim().parse().unwrap();
}
```
So it seems it is not Rust default behavior when parsing a string to an int.

(the same result will happen if you use `String::from(" 1 ")`)

**Comment by valq7711** [comment]
@omercotkd Fine! So this could be easily fixed to make pydantic int/float behave like native python ones, because why should their behavior change based on implementation details without any significant reason?

**Comment by davidhewitt** [comment]
PR welcome to fix this in `pydantic-core` - I think it'd be just about introducing `.trim()` in the right places and adding tests. This'll probably want to be done for `int`, `float` and `decimal` validators, maybe more.

**Comment by hungtsetse** [comment]
Could I take this one. It will be a good opportunity for me to approach `pydantic-core` codebase which i'm interested in.

**Comment by samuelcolvin** [comment]
Go for it.

**Comment by davidhewitt** [comment]
Fixed in https://github.com/pydantic/pydantic-core/pull/1203 - thanks @hungtsetse
