### ISSUE TITLE
Use of stdlib dataclasses with BaseModel does not work as expected

### ISSUE THREAD

**Issue by kschwab** [pydantic/pydantic#8422]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The following Pydantic example, [Use of stdlib dataclasses with BaseModel](https://docs.pydantic.dev/latest/concepts/dataclasses/#use-of-stdlib-dataclasses-with-basemodel), fails to work as expected.

Specifically, the `ValidationError` for `file.filename input should be a valid string ...` does not occur. Is this expected behavior?

### Python, Pydantic & OS Version

```Text
$ python3 -c "import pydantic.version; print(pydantic.version.version_info())"
              pydantic version: 2.5.2
         pydantic-core version: 2.14.5
           pydantic-core build: profile=release pgo=true
                  install path: /usr/local/lib/python3.12/site-packages/pydantic
                python version: 3.12.0 (main, Oct  2 2023, 00:00:00) [GCC 13.2.1 20230918 (Red Hat 13.2.1-3)]
                      platform: Linux-6.2.9.valarch.master.1.1-x86_64-with-glibc2.38
              related packages: pydantic-settings-2.1.0 typing_extensions-4.9.0
```

**Comment by Kludex** [comment]
Yes. We need to add `model_config = ConfigDict(revalidate_instances='always')` to the `Foo` model to reproduce the expected behavior.

**Comment by baohuamap** [comment]
Hi @Kludex , I can work on this issue.

**Comment by sydney-runkle** [comment]
@baohuamap,

Go for it! I can review a PR.

**Comment by patelnets** [comment]
Sorry for taking this, but I saw that baohuamap above hadn't submitted a PR yet and it's been 5 days so I assumed it was fair game to create one. 

Here is a PR for it https://github.com/pydantic/pydantic/pull/8491

**Comment by baohuamap** [comment]
Hi @patelnets, I've been waiting for any members to assign me this ticket to start working on it. But if you have done it, It's fine by me.

**Comment by patelnets** [comment]
Ahh sorry about that!
