### ISSUE TITLE
Cannot import ENCODERS_BY_TYPE

### ISSUE THREAD

**Issue by mcleantom** [pydantic/pydantic#8426]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am migrating my code from V1 to V2. In my V1 code, I modified ENCODERS_BY_TYPE to turn bson ObjectIds. I can no longer import ENCODERS_BY_TYPE, how should I fix this issue?

### Example Code

```Python
from pydantic.json import ENCODERS_BY_TYPE
from bson import ObjectId
ENCODERS_BY_TYPE[ObjectId] = lambda v: str(v)
```

### Python, Pydantic & OS Version

```Text
"
             pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /home/tom/miniconda3/envs/routingdeploy2/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
                     platform: Linux-6.1.11-76060111-generic-x86_64-with-glibc2.35
             related packages: email-validator-2.0.0.post2 typing_extensions-4.8.0 pydantic-settings-2.1.0 fastapi-0.105.0
```

**Comment by Kludex** [comment]
As a direct replacement, you can do the following on V2:

```py
from bson import ObjectId
from pydantic import BaseModel, ConfigDict

BaseModel.model_config["json_encoders"] = {ObjectId: lambda v: str(v)}


class Item(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    id: ObjectId


item = Item(id=ObjectId("5ff1e194b6a9d7a5f9a2741c"))
print(item.model_dump_json())
```

I'll leave this issue open till we document it. 🙏

**Comment by bL34cHig0** [comment]
> As a direct replacement, you can do the following on V2:
> 
> ```python
> from bson import ObjectId
> from pydantic import BaseModel, ConfigDict
> 
> BaseModel.model_config["json_encoders"] = {ObjectId: lambda v: str(v)}
> 
> 
> class Item(BaseModel):
>     model_config = ConfigDict(arbitrary_types_allowed=True)
> 
>     id: ObjectId
> 
> 
> item = Item(id=ObjectId("5ff1e194b6a9d7a5f9a2741c"))
> print(item.model_dump_json())
> ```
> 
> I'll leave this issue open till we document it. 🙏

Hi, I'd like to work on this documentation issue. Thank you

**Comment by sydney-runkle** [comment]
@bL34cHig0,

Go for it! Thanks! I'll review your work.

**Comment by bL34cHig0** [comment]
> @bL34cHig0,
> 
> Go for it! Thanks! I'll review your work.

@sydney-runkle Thank you for assigning me this issue. 

Just for clarification, do I add the workaround code to the `Migration Guide` in the **docs**?

```from bson import ObjectId
from pydantic import BaseModel, ConfigDict

BaseModel.model_config["json_encoders"] = {ObjectId: lambda v: str(v)}


class Item(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    id: ObjectId


item = Item(id=ObjectId("5ff1e194b6a9d7a5f9a2741c"))
print(item.model_dump_json())

**Comment by sydney-runkle** [comment]
@bL34cHig0,

Yep, the migration guide would be an appropriate location for this!

**Comment by bL34cHig0** [comment]
@sydney-runkle 

I appended the workaround code to the `Migration Guide` with a little explanation.

Could you please take a look before submitting a PR?

![image](https://github.com/pydantic/pydantic/assets/133022207/6f7af70a-eca4-4702-be97-05a5a000d3b7)

**Comment by mcleantom** [comment]
@bL34cHig0 The explanation should be a general explanation for replacing `ENCODERS_BY_TYPE` rather than the specific example for instances of `ObjectId`

**Comment by sydney-runkle** [comment]
@bL34cHig0,

Looks good overall! Feel free to open a PR and I can provide some more detailed feedback there 👍. Thanks!

**Comment by bL34cHig0** [comment]
Thanks @sydney-runkle, will do that right away!
