### ISSUE TITLE
Adopt PEP 585 and PEP 604

### ISSUE THREAD

**Issue by bswck** [pydantic/pydantic#8434]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I suggest adopting (either by adding [a dependency](https://github.com/bswck/modern_types#readme) or, more safely, incorporating into pydantic internally) a [PEP 585](https://peps.python.org/pep-0585/) (allow subscripting built-in generic types, e.g. `dict[str, int]`) and [PEP 604](https://peps.python.org/pep-0604/) (`X | Y` union type syntax) backport for Python <3.10 **runtime type evaluation**, so that the freshest type hinting style can be used for pydantic models, without having to import [the deprecated type aliases from `typing`](https://docs.python.org/3/library/typing.html?highlight=deprecated#deprecated-aliases).

If this feature request is accepted, the developers that use pydantic, could ditch the old, **confusing for Python beginners**, type hinting format:

```py
import collections.abc
from typing import DefaultDict, Dict, FrozenSet, List, Set, Tuple, Optional, Union

from pydantic import BaseModel

class Foo(BaseModel):
    a: Dict[str, int]
    b: List[int]
    c: Set[int]
    d: Optional[Tuple[int, ...]]
    e: FrozenSet[int]
    f: DefaultDict[str, int]
    g: Optional[str]
    h: Union[str, int]
    i: Optional[Union[str, int]]
    j: str
    k: collections.abc.Mapping[str, int]
    l: Optional[collections.abc.Mapping[str, int]]
    m: Optional[collections.abc.Mapping[str, Optional[int]], float]
```

and use the **newest, prettiest & recommended** one:

```py
import collections.abc
from collections import defaultdict

from pydantic import BaseModel

class Foo:
    a: dict[str, int]
    b: list[int]
    c: set[int]
    d: tuple[int, ...] | None
    e: frozenset[int]
    f: defaultdict[str, int]
    g: str | None
    h: str | int
    i: str | int | None
    j: str
    k: collections.abc.Mapping[str, int]
    l: collections.abc.Mapping[str, int] | None
    m: collections.abc.Mapping[str, int | None] | float | None
```

in **Python 3.8 and 3.9**.

The new fashion of type hints is broadly used for example in [pandas](https://github.com/pandas-dev/pandas/blob/dc37a6d035474c25932d805cfe50a47b04916a83/pandas/core/frame.py#L683-L690) (`pandas.DataFrame.__init__`—very likely people would see it often), [poetry](https://github.com/python-poetry/poetry/blob/3d7b75cc13adc99f759d2b58920702972251f22b/src/poetry/console/application.py#L100-L101), [FastUI](https://github.com/pydantic/FastUI/blob/106d6c500acc40d051fcf4ea817ff717c1b1e0c7/src/python-fastui/fastui/generate_typescript.py#L64) and many, many more modern projects.

I am suggesting it mainly because [I know it is doable](https://github.com/bswck/modern_types#readme) by altering the namespaces used by ForwardRef's with the help of AST—and would love to see it as a default behavior of pydantic. I could work on it, document it and test it against built-in types and [pydantic extra types](https://github.com/pydantic/pydantic-extra-types).

Merry Christmas! 🎄

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by bswck** [comment]
I tried to suggest this as a feature for [typing_extensions](https://github.com/python/typing_extensions/issues/315), but I don't think it would be accepted any soon, if ever.

**Comment by samuelcolvin** [comment]
It's already a WIP, see #8209.

**Comment by bswck** [comment]
> It's already a WIP, see #8209.

Thanks, I completely missed this! I will see if I can help.
