### ISSUE TITLE
Inconsistent JSON serialization of None keys ("None" instead of "null")

### ISSUE THREAD

**Issue by Saare** [pydantic/pydantic#8438]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

During migration from v1 to v2 we discovered a change of behavior when serializing `None` keys in a dictionary to JSON.

Since non-string keys are invalid in JSON, both V1 and Python's `json.dumps` opt to serialize `None` to `"null"`. This makes a lot of sense considering that JS's deserialization does translate `"null"` to a regular null (`JSON.parse('{"null": 123}') # => {null: 123}`).
In V2, they are serialized as `"None"`.

This is an undocumented change that can cause unexpected problems due to the deviation from the old behavior that aligns with Python's and JS's implementations.

This may be a breaking change for implementations where Pydantic is used alongside JS, which is often the case with FastAPI../

### Example Code

```Python
class MyModel(BaseModel):
    a: dict[Optional[str], int]

m = MyModel(a={None: 123})

# V1
print(m.json()) # {"a": {"null": 123}}

# V2
print(m.model_dump_json()) # {"a":{"None":123}}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: ....../pypoetry/virtualenvs/api-service-VIUyjLw7-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 24 2023, 22:36:46) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.4.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 mypy-1.7.1 pydantic-settings-2.1.0 fastapi-0.104.1 email-validator-2.1.0.post1
```

**Comment by samuelcolvin** [comment]
Since JSON only allows strings for object keys, anything we use is going to be weird and opinionated.

From memory, we made the change to use `str(key)` for all non string keys, I see the change is confusing, but I think overall the new behaviour makes more sense.

**Comment by Saare** [comment]
Hey @samuelcolvin,
Although I don't agree with the solution (considering that it deviates from Python's and V1's behaviors), I can see where this is coming from.
With that being said, I suggest to document this change of behavior in the migration manual.

**Comment by samuelcolvin** [comment]
PR welcome to add a note to the documentation.
