### ISSUE TITLE
SecretField other than str and bytes

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [pydantic/pydantic#8441]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hi, I'm interested in marking some fields as PII using SecretFields. This means handling other types of data such as dates and enums. (see [resource](https://www.osec.doc.gov/opog/privacy/pii_bii.html))
I've seen the implementation for `_SecretField` to try to implement my own but it's asserting that if it's not a string, then it must be bytes (see [link](https://github.com/pydantic/pydantic/blob/19fa86cbfcc7b64c5d59c04c38fa80b497f275a2/pydantic/types.py#L1481))
Is there any way to handle dates and enums as a secret field?

Thanks!

### Affected Components

- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`

**Comment by sydney-runkle** [comment]
@conradogarciaberrotaran,

Great question! We don't currently support the handling of fields that aren't `str` or `bytes` types as secret. I do think this is a valuable feature request, though!

**Comment by conradogarciaberrotaran** [comment]
Hi @sydney-runkle, thank you for your reply.
I went ahead and tried to implement it, with some difficulties, but the basic functionality is working. I may have some things missing.
https://github.com/pydantic/pydantic/pull/8519

is there anyone who can assist me?

Thanks!

**Comment by conradogarciaberrotaran** [comment]
Hi @expobrain! I saw your contribution creating the generic _SecretType. Would you be interested in helping out?

**Comment by expobrain** [comment]
@conradogarciaberrotaran sure! I made this PR https://github.com/pydantic/pydantic/pull/3717 back in the days of Pydantic 1.x to be able to freely extend the secret type to beyond the ones provided by Pydantic. 

I reckon we can re-apply the same concept again.
