### ISSUE TITLE
coerce_numbers_to_str raising a Validation Error

### ISSUE THREAD

**Issue by gabrielmongalo** [pydantic/pydantic#8443]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, I'm currently working on a project migrating from v1 to v2. I wanted to leverage `ConfigDict(coerce_numbers_to_str=True)`.  I noticed in the [repl](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.coerce_numbers_to_str) for the following example:  `Model(value=42)` doesn't convert it to str, rather continues to keep it as a `Number` type.

I noticed this when using it within my own implementation where i was prompted with  the following ValidationError.  ```Input should be a valid string [type=string_type, input_value=51, input_type=int]``` 

### Example Code

```Python
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, ValidationError

class Model(BaseModel):
    model_config = ConfigDict(coerce_numbers_to_str=True)

    value: str

print((Model(value=42).value))

# returns 42 as a number type and not as a string
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
pydantic-core version: 2.14.6
python version: 3.11.3 
platform: macOS-13.6.3-x86_64-i386-64bit
related packages: fastapi-0.105.0 typing_extensions-4.9.0 pydantic-extra-types-2.2.0 pydantic-settings-2.1.0 email-validator-2.1.0.post1
```

**Comment by omercotkd** [comment]
`from pydantic import BaseModel, ConfigDict, ValidationError

class Model(BaseModel):
    model_config = ConfigDict(coerce_numbers_to_str=True)

    value: str

if __name__ == '__main__':
    assert Model(value=42).value == '42'`
    
   It seems fine to me with Python 3.10.2.
   when you print the type of the `value` field what does it show?

**Comment by omercotkd** [comment]
```
from pydantic import BaseModel, ConfigDict, ValidationError

class Model(BaseModel):
model_config = ConfigDict(coerce_numbers_to_str=True)

value: str
if name == 'main':
assert Model(value=42).value == '42'
```

It seems fine with Python 3.10.2.
when you print the type of the value field what does it show?

**Comment by Kludex** [comment]
As @omercotkd said, it looks like the behavior is fine. `Model(value=42).value` is a string.

That said, I'll be closing the issue. Please let me know if there is something I didn't see.
