### ISSUE TITLE
AnyUrl not serialized as expected

### ISSUE THREAD

**Issue by Leobouloc** [pydantic/pydantic#8444]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using `AnyUrl` fields with `model_dump`, the output is of type `pydantic_core.Url` and not `str` as expected. Trying to jsonify the result leads to an error as `Url` is not serializable. 

This problem does not occur when using `model_dump_json`.

This seems like a bug, as the documentation states that _**The .model_dump_json() method serializes a model directly to a JSON-encoded string that is equivalent to the result produced by .model_dump()**_  and defines serializing as transforming models _**into a less structured form comprised of Python built-ins**_.

### Example Code

```Python
import json
from pydantic import BaseModel, AnyUrl
from pydantic_core import Url


class MyModel(BaseModel):
    url: AnyUrl

my_model = MyModel(url="http://example.com/")

# model_dump does not provide python built-ins
assert isinstance(my_model.model_dump()["url"], Url)

# trying to write the result leads to an error
try:
    json.dumps(my_model.model_dump())
except TypeError as err:
    assert err.args[0] == 'Object of type Url is not JSON serializable'

# there is no problem when using model_dump_json
assert isinstance(json.loads(my_model.model_dump_json())["url"], str)

# all assertions are true
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
pydantic-core version: 2.14.6
pydantic-core build: profile=release pgo=true
install path: /usr/local/lib/python3.12/site-packages/pydantic
python version: 3.12.0 (main, Nov 29 2023, 03:23:09) [GCC 12.2.0]
platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.36
related packages: mypy-1.7.1 pydantic-settings-2.1.0 fastapi-0.105.0 typing_extensions-4.9.0 email-validator-2.1.0.post1
```

**Comment by Kludex** [comment]
You can do:

```py
json.dumps(my_model.model_dumps(mode="json")
```

See https://github.com/pydantic/pydantic/issues/7632 for more details.
