### ISSUE TITLE
Wrong negative timedelta string parsing

### ISSUE THREAD

**Issue by gusutabopb** [pydantic/pydantic#8450]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic v1.10 is incorrectly parsing negative timedelta strings in the format `-HH:MM:SS` when `MM` is non-zero.

### Example Code

```python
import datetime
from pydantic import BaseModel

class MyModel(BaseModel):
    td: datetime.timedelta

print(MyModel(td="-01:30:00").td.total_seconds() / 3600)
print(MyModel(td="-02:15:00").td.total_seconds() / 3600)
print(MyModel(td="-03:06:00").td.total_seconds() / 3600)
print(MyModel(td="-04:00:00").td.total_seconds() / 3600)
```

Pydantic v2.5.3 output
```
-1.5   # correct
-2.25  # correct
-3.1   # correct
-4.0   # correct
```

Pydantic v1.10.13 output
```
-0.5    # off by 1 hour
-1.75   # off by 30 minutes
-2.9    # off by 12 minutes
-4.0    # only correct result
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.13
            pydantic compiled: True
                 install path: /home/gbezerra/ipynb/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  7 2023, 13:51:08) [GCC 11.3.0]
                     platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@gusutabopb,

We're not actively working on fixes for V1 anymore - given that this is fixed in V2, I'm going to close this issue as not planned. Thanks for your detailed report 👍
