### ISSUE TITLE
Pydantic support for dateutil.rrule

### ISSUE THREAD

**Issue by avivgood** [pydantic/pydantic#8451]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hi, so I had a use case where I needed to represent an event that reoccurred every X time for the duration of Y time, and I wanted to represent this event in my FastAPI + Pydantic stack. [This is the full use case](https://stackoverflow.com/questions/77705081/time-intervals-in-python). I concluded that implementing this on my own would require a lot of validation and parsing. I found out there is already a standard for it : [RFC 5545 - ICalender](https://datatracker.ietf.org/doc/html/rfc5545), which as far as I know, the rrule part of it is implemented in [dateuttil package]( https://dateutil.readthedocs.io/en/stable/rrule.html) However, while it is supported in many JS calendars, I couldn't find support for it, especially for rrule, as a "first citizen" Pydantic type. I will admit I am not very knowledgeable about how Pydantic is implemented, however, an rrule can't generate a pydantic-core schema (i.e the error:
`pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <module 'dateutil.rrule' from '<...>/dateutil/rrule.py'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.`
And therefore I can't use it in my swagger and API.
I know the dateutil package it third-party, and most of the types supported by Pydantic are not, however, since this is the calendering standard, I do think Pydantic support would be helpful here.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
You should be able to add validation to `rrule`, see https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types.

We could perhaps add support for it to [pydantic-extra-types](https://github.com/pydantic/pydantic-extra-types), feel free to create an issue there.

**Comment by avivgood** [comment]
Added the issue to the correct repo.
