### ISSUE TITLE
Validation error while I am using relation for model , which has own relation

### ISSUE THREAD

**Issue by Zaskilovan** [pydantic/pydantic#8456]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a model, which has a relation model, which also has a relation model, and when I try to build the pydanticmodel, I get an error : pydantic_core._pydantic_core.ValidationError: 1 validation error for Page[TripResponseModel]
items.0.points.0.point_photo
  Input should be a valid list [type=list_type, input_value=<tortoise.fields.relation...t at 0x000001E77FD7E0D0>, input_type=ReverseRelation]
    For further information visit https://errors.pydantic.dev/2.5/v/list_type

### Example Code

```Python
from tortoise.contrib.pydantic import pydantic_model_creator

TripOut = pydantic_model_creator(Trip)
PointOut = pydantic_model_creator(Point)
PointPhotoOut = pydantic_model_creator(PointPhoto)

class PointOutRelation(PointOut):
    point_photo : List[PointPhotoOut]

class TripOutRelation(TripOut):
    points: List[PointOutRelation] 

#And when I try to get TripOutRelation , I see eror
#But if I try to get PointOutRelation , I have not error
```

### Python, Pydantic & OS Version

```Text
pydantic 2.5.3
python 3.11.4
```

**Comment by sydney-runkle** [comment]
@Zaskilovan,

Please provide a code snippet that is reproducible. Without a MRE, we aren't easily able to help you with your issue. Happy to reopen if you can provide such code 👍.
