### ISSUE TITLE
Issue between Pydantic v.2.5.3 and LangChain 0.0.148

### ISSUE THREAD

**Issue by lets-japa** [pydantic/pydantic#8458]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Pydantic has upgraded from v.1 to v.2 but LangChain is still using v.1, meanwhile, if I downgrade Pydantic, Gradio needs v.2 of Pydantic.
This is my error if I try to upgrade pydantic:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
langchain 0.0.148 requires pydantic<2,>=1, but you have pydantic 2.5.3 which is incompatible.

This is my error if I try to downgrade Pydantic:
gradio 4.12.0 requires pydantic>=2.0, but you have pydantic 1.8.2 which is incompatible.
openai 1.6.1 requires pydantic<3,>=1.9.0, but you have pydantic 1.8.2 which is incompatible.

Which version of Pydantic should I use, that is compatible with LangChain?

### Example Code

```Python
from pydantic.main import ModelMetaclass
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                
               python version: 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10)  [Clang 6.0 (clang-600.0.57)]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: fastapi-0.108.0 typing_extensions-4.8.0
```

**Comment by hramezani** [comment]
Thanks @lets-japa for reporting this.

You need to install a newer version of `langchain`. `langchain 0.0.353` is compatible with `Pydantic V2`.

**Comment by lets-japa** [comment]
Thanks a lot @hramezani ! 
Don't know how I missed that
