### ISSUE TITLE
2.5.3: benchmark tests still broken due to hash

### ISSUE THREAD

**Issue by dvzrv** [pydantic/pydantic#8459]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! :wave: 

When trying to package 2.5.3 for Arch Linux I ran tests and noticed, that the tests seemingly fixed in https://github.com/pydantic/pydantic/issues/8099 are unfortunately still broken.

The current downstram build script can be found in https://gitlab.archlinux.org/archlinux/packaging/packages/python-pydantic/-/blob/112a5d91046232962cc61ba464e5ed55d16e2db7/PKGBUILD

[python-pydantic-2.5.3-1-x86_64-build.log](https://github.com/pydantic/pydantic/files/13804613/python-pydantic-2.5.3-1-x86_64-build.log)

### Example Code

```Python
n/a
```

### Python, Pydantic & OS Version

```Text
Arch Linux, building 2.5.3 (with pydantic-core 2.14.6) from github source tarball.
```

**Comment by sydney-runkle** [comment]
This fix will be released with `2.6.0` 👍. Thanks for checking in!
