### ISSUE TITLE
2.5.3: tests/test_docs.py::test_docs_examples[docs/concepts/serialization.md:354-391] fails

### ISSUE THREAD

**Issue by dvzrv** [pydantic/pydantic#8460]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi! :wave: 

When building 2.5.3 on Arch Linux I noticed a new failing test:

```
=================================== FAILURES ===================================
__________ test_docs_examples[docs/concepts/serialization.md:354-391] __________
Print output changed code:
  --- before
  +++ after
  @@ -385,360 +385,360 @@
       date: DayThisYear


   m = FooModel(date=300)
   print(m.model_dump_json())
  -#> {"date":"2023-10-28"}
  +#> {"date":"2024-10-27"}
```

[python-pydantic-2.5.3-1-x86_64-check.log](https://github.com/pydantic/pydantic/files/13804624/python-pydantic-2.5.3-1-x86_64-check.log)

### Example Code

```Python
n/a
```

### Python, Pydantic & OS Version

```Text
Arch Linux, Python 3.11, building from github source tarball with pydantic-core 2.14.6
```

**Comment by hramezani** [comment]
Thanks @dvzrv for reporting this.

I've create a [PR](https://github.com/pydantic/pydantic/pull/8467) to fix this
