### ISSUE TITLE
Incorrect instance creation, not respecting the given input (being stupid in type detection)

### ISSUE THREAD

**Issue by ManiMozaffar** [pydantic/pydantic#8473]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Just for more context, see 3 Admin was created although I passed only one admin object :D  see the output that I highlighted, and the failing code!

<img width="1162" alt="Screenshot 2024-01-02 at 19 31 56" src="https://github.com/pydantic/pydantic/assets/86913668/3f229e07-cf49-4bf1-9b02-a59fc9ef014c">

This issue only happens in v1, not v2. i think that's due to bad implementation of smart union, but i couldn't update labels.

### Example Code

```Python
from pydantic import BaseModel


class User(BaseModel):
    name: str


class Admin(BaseModel):
    ...


class Employee(BaseModel):
    name: str


class Human(BaseModel):
    system_role: Admin | User | Employee


database = [
    Human(system_role=User(name="John")),
    Human(system_role=Admin()),
    Human(system_role=Employee(name="Alex")),
]

assert isinstance(database[0].system_role, User)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 1.10.13
            pydantic compiled: True
                 install path: /Users/manimozaffar/Library/Caches/pypoetry/virtualenvs/nl-newsletter-jp8XYiXN-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.3-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
             ```

**Comment by ManiMozaffar** [comment]
same bug exists in v1!

**Comment by ManiMozaffar** [comment]
Just for more context, see 3 Admin was created although I passed only one admin object :D


<img width="1162" alt="Screenshot 2024-01-02 at 19 31 56" src="https://github.com/pydantic/pydantic/assets/86913668/3f229e07-cf49-4bf1-9b02-a59fc9ef014c">

**Comment by nthe** [comment]
Hi @ManiMozaffar, 
it seems like the assert statement is correctly raising an exception.
It also seems like you wanted to assert the _system_role_ field `assert isinstance(database[0].system_role, User)`.

**Comment by ManiMozaffar** [comment]
> Hi @ManiMozaffar, it seems like the assert statement is correctly raising an exception. It also seems like you wanted to assert the _system_role_ field `assert isinstance(database[0].system_role, User)`.

Yep that's true. sorry I was tired. but still check the output in pydantic v1. i think that because smart union isn't used in v1?

**Comment by nthe** [comment]
Yes, as far as I know, the proper support for discriminated unions was added in the v2.

**Comment by sydney-runkle** [comment]
@ManiMozaffar,

Indeed, this is fixed in V2. We're no longer working on fixes for V1, so I'm going to close this issue as not planned.
