### ISSUE TITLE
Impossible to use validators in a way that passes Pyright 1.1.344 validation.

### ISSUE THREAD

**Issue by sherbang** [pydantic/pydantic#8477]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I wanted to raise awareness of [this issue](https://github.com/microsoft/pyright/issues/6875) here.

Currently, Eric is suggesting that defining the Protocols that do the typing for the decorators should be changed from `(self, cls, __value...` to `(self, __cls, __value...`.  However, the [conversation in the typing forum](https://discuss.python.org/t/ambiguities-about-positional-only-parameters/42328) also pointed out that the __ syntax for position-only parameters is only needed for py3.7 or earlier, and since 3.7 is EOL perhaps it makes sense to change to `(self, cls, value, /)`?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /path/to/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Dec 11 2023, 09:33:58) [GCC 11.4.0]
                     platform: Linux-6.6.6-76060606-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
@sherbang,

Thanks for reporting this + communicating with the `pyright` team regarding this issue. I agree with your proposed change, and will review your PR shortly :).
