### ISSUE TITLE
Support deserialisation from JSON5

### ISSUE THREAD

**Issue by MaxG87** [pydantic/pydantic#8481]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be great if pydantic could **parse** JSON5. This is a superset of JSON featuring a handful of improvements. I would be most interested in being able to use dangling commas.

My use case for that is that occasionally I place example data as test resources in JSON. When I then work with that, e.g. by adding more examples, I need to obey to some of the JSON obstacles. Being able to use JSON5 would be very convenient, but only if I could pass that directly to `pydantic`.

I do not think serialisation to JSON5 is necessary. After all, JSON5 is a superset, so if pydantic sticks to JSON it would be compatible with JSON5 already.

I am very surprised that seemingly no one before requested this. However, search all [Issues](https://github.com/pydantic/pydantic/issues) didn't reveal anything.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Writing a performant JSON5 parser in rust would be a pretty complex task, especially as it's less well defined than standard JSON.

Supporting this would require someone to take on the task, which I think is unlikely.

In future we intend to support pluggable rust based parsers which I think is a better solution.
