### ISSUE TITLE
`frozen` description equates it to `allow_mutation`, but it is the inverse

### ISSUE THREAD

**Issue by themattmorris** [pydantic/pydantic#8488]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Thanks for the awesome library! I recently migrated to v2 and am loving it. I did notice a very minor, though potentially important issue in the description of `frozen` config argument:

https://github.com/pydantic/pydantic/blob/c067c1b9d0e5ffdf5b0fd53bf0e138cb5924f750/pydantic/config.py#L128

Though the names are clear, one could potentially assume that they are equivalent based on this description. The docs clearly indicate that `frozen` is the invers of `allow_mutation`, perhaps could also indicate that on this line as well.

Something like "On V1, the inverse of this setting was called `allow_mutation`, and was `True` by default."

Let me know what you think, and then I can open a PR.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
               python version: 3.12.0 (main, Nov 29 2023, 03:32:06) [GCC 10.2.1 20210110]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
             related packages: typing_extensions-4.9.0
```

**Comment by sydney-runkle** [comment]
@themattmorris,

Sounds like a great change. Please open a PR and I'd be happy to review!
