### ISSUE TITLE
Generate evolvable JSONSchema with pydantic

### ISSUE THREAD

**Issue by tribunsky-kir** [pydantic/pydantic#8496]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hello!

I've tried using Pydantic to generate JSONSchema for messages in the Kafka schema registry but found out that I can't generate evolvable schemas. The `mode="validation"` setting doesn't help in this case. This problem affects not only complex schemas with nested definitions but also the simplest flat objects.

While researching the problem in issues of confluent schema registry I've found a great article about the compatibility of JSONSchema:  https://yokota.blog/2021/03/29/understanding-json-schema-compatibility/

The main issue is the possibility of adding the key `"additionalProperties"` and setting it to `False`. I ended up creating a custom child of `GenerateJsonSchema`, but it seems a bit clumsy.

First, I want to ask, what am I missing? Is there a way to generate evolvable schemas?
If not, what is the reason for this behavior? I'm not very familiar with the JSONSchema specification, so I might have missed something.
And if I'm correct, it seems like having this feature in the library out of the box would be beneficial.

### Example of original problem
```python
from typing import Optional

from pydantic import BaseModel, UUID4

# This is the event of version 1 which we are gonna to evolve later
class Event(BaseModel):
    id: UUID4

print(Event.model_json_schema())
"""
{'properties': {'id': {'format': 'uuid4', 'title': 'Id', 'type': 'string'}}, 'required': ['id'], 'title': 'Event', 'type': 'object'}
"""

# This is the event of version 2. We added a new field `path` to the event and by default it is None ('null'),
# which allows us to not break the reader
# That schema fails (HTTP code 409, with message about PROPERTY_ADDED_TO_OPEN_CONTENT_MODEL)
# against confluent schema registry because it is not compatible with the previous one
class Event(BaseModel):
    id: UUID4
    path: Optional[str] = None

print(Event.model_json_schema())
"""
{'properties': {'id': {'format': 'uuid4', 'title': 'Id', 'type': 'string'}, 'path': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Path'}}, 'required': ['id'], 'title': 'Event', 'type': 'object'}
"""
```

### Example of solution in user's code base
```python
from typing import Optional

from pydantic import BaseModel, UUID4
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaMode, JsonSchemaValue
from pydantic_core import CoreSchema


class JSONClosedModelGenerator(GenerateJsonSchema):
    def generate(self, schema: CoreSchema, mode: JsonSchemaMode = "validation") -> JsonSchemaValue:
        json_schema = super().generate(schema, mode=mode)
        key_additional_properties = "additionalProperties"
        key_definitions = "$defs"
        json_schema[key_additional_properties] = False
        definitions = json_schema.get(key_definitions, {})
        for definition in definitions:
            if definitions[definition].get("type") == "object":
                json_schema[key_definitions][definition][key_additional_properties] = False
        return json_schema


# This is the event of version 1 which we are gonna to evolve later
class Event(BaseModel):
    id: UUID4

print(Event.model_json_schema(schema_generator=JSONClosedModelGenerator))
"""
{'properties': {'id': {'format': 'uuid4', 'title': 'Id', 'type': 'string'}}, 'required': ['id'], 'title': 'Event', 'type': 'object', 'additionalProperties': False}
"""

# This schema will pass compatibility check and we can use it without the need of turning off the 
# compatibility check or schema deletion from schema registry
class Event(BaseModel):
    id: UUID4
    path: Optional[str] = None

print(Event.model_json_schema(schema_generator=JSONClosedModelGenerator))
"""
{'properties': {'id': {'format': 'uuid4', 'title': 'Id', 'type': 'string'}, 'path': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Path'}}, 'required': ['id'], 'title': 'Event', 'type': 'object', 'additionalProperties': False}
"""
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by commonism** [comment]
Hi,

you can control `addtionalProperties` via model_config/extra
https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra

**Comment by sydney-runkle** [comment]
@commonism,

Thanks for the answer. Going to mark this as closed for now, as I don't think there's a change needed on `pydantic`'s end.

You can also use `json_schema_extra` or custom json schema generators if you need more customizability.

**Comment by tribunsky-kir** [comment]
@commonism , @sydney-runkle , thanks for great answers!

Meanwhile, I have some concerns about current approach, maybe I just don't understand how 'additionalProperties' should work in JSONSchema.

Please, consider the next example:
```python
from pydantic import BaseModel, ConfigDict


class NestedModel(BaseModel):
    a: int
    b: str


class DefaultModel(BaseModel):
    field: NestedModel


print(DefaultModel.model_json_schema())
"""
{'$defs': {'NestedModel': {'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'title': 'B', 'type': 'string'}}, 'required': ['a', 'b'], 'title': 'NestedModel', 'type': 'object'}}, 'properties': {'field': {'$ref': '#/$defs/NestedModel'}}, 'required': ['field'], 'title': 'DefaultModel', 'type': 'object'}
"""

class AllowModel(BaseModel):
    model_config = ConfigDict(extra='allow')
    field: NestedModel


print(AllowModel.model_json_schema())
"""
{'$defs': {'NestedModel': {'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'title': 'B', 'type': 'string'}}, 'required': ['a', 'b'], 'title': 'NestedModel', 'type': 'object'}}, 'additionalProperties': True, 'properties': {'field': {'$ref': '#/$defs/NestedModel'}}, 'required': ['field'], 'title': 'AllowModel', 'type': 'object'}
"""

class ForbidModel(BaseModel):
    model_config = ConfigDict(extra='forbid')
    field: NestedModel


print(ForbidModel.model_json_schema())
"""
{'$defs': {'NestedModel': {'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'title': 'B', 'type': 'string'}}, 'required': ['a', 'b'], 'title': 'NestedModel', 'type': 'object'}}, 'additionalProperties': False, 'properties': {'field': {'$ref': '#/$defs/NestedModel'}}, 'required': ['field'], 'title': 'ForbidModel', 'type': 'object'}
"""

if __name__ == '__main__':
    dct = {'field': {'a': 1, 'b': '2'}, 'external_source_data': 'test'}
    
    m1 = DefaultModel(**dct)
    print(m1.model_dump())
    """
    {'field': {'a': 1, 'b': '2'}}
    """
    
    m2 = AllowModel(**dct)
    print(m2.model_dump())
    """
    {'field': {'a': 1, 'b': '2'}, 'external_source_data': 'test'}
    """
    
    m3 = ForbidModel(**dct)
    print(m3.model_dump())
    """
    Traceback (most recent call last):
    ...
    pydantic_core._pydantic_core.ValidationError: 1 validation error for ForbidModel
    external_source_data
      Extra inputs are not permitted [type=extra_forbidden, input_value='test', input_type=str]
        For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
    """    
```

From my perspective there are two problems in this outputs:
1. If I want to see `"additionalProperties": false` I need to keep in my code two models for input or output.
2. By default I need to handle all nested models by hand (or inherit all models from pre-configured models) to be sure that my (and _other_ developers) schemas will be always evolvable in the future.

My second question is about documentation: I couldn't find any mention of `addintionalProperties` through search in current version on [JSON Schema](https://docs.pydantic.dev/latest/api/json_schema/) or [extra](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra). Is it appropriate pages to add information there about the impact of `model_config` in the resulting schema?

**Comment by commonism** [comment]
I prefer to have json parsed by the machine and work with yaml when I need to:
Would be great if you could update your snippet with
```
print(yaml.dump(ForbidModel.model_json_schema()))
```


To my understanding the evolvable schema implies a version mismatch in the protocol with client & server.
Either using generated client code with a schema which is outdated, or a service which is outdated accessed with a more up to date client.

Not use cases I'd consider addressing.
Possibly evolvable, unlikely to be usable due to lack of tooling.

That said
I've seen version glue as this:
```yaml
components:
  schemas:
    Zone_Zone:
      anyOf:
      - $ref: /redfish/v1/Schemas/Zone.v1_6_1.yaml#/components/schemas/Zone_v1_5_0_Zone
      - $ref: /redfish/v1/Schemas/Zone.v1_6_1.yaml#/components/schemas/Zone_v1_6_1_Zone
      description: The Zone schema describes a simple fabric zone for a Redfish implementation.
      x-longDescription: This resource shall represent a simple fabric zone for a
        Redfish implementation.
title: '#Zone.Zone'
x-copyright: Copyright 2014-2023 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
x-owningEntity: DMTF
```
which will allow basic version compatibility (even though oneOf would have been the better choice).

For in/out, your models will have fields which are not writable, OpenAPI 3.1/JSONSchema does not know about readOnly any more.

**Comment by tribunsky-kir** [comment]
I've updated the snippet:

```yaml
# print(yaml.dump(ForbidModel.model_json_schema()))
$defs:
  NestedModel:
    properties:
      a:
        title: A
        type: integer
      b:
        title: B
        type: string
    required:
    - a
    - b
    title: NestedModel
    type: object
additionalProperties: false
properties:
  field:
    $ref: '#/$defs/NestedModel'
required:
- field
title: ForbidModel
type: object
```

I don't understand how I can apply provided example with zones in my context. I've faced with the schema evolution not in the context of pure client-server interaction (OpenAPI), but while working with confluent schema registry and kafka.

From the producer perspective of it would be great to generate schema, where the new fields can be introduced (common-understandable backward compatibility like in `avro` or `protobuf`) by default. 

Without `"additionalProperties": false` confluent schema registry returns strange error `PROPERTY_ADDED_TO_OPEN_CONTENT_MODEL` when the new field is added. As subject schema already describes the object which is intended to put and not directly related to OpenAPI Specification, I am not sure that using schema references is the simplest way to use. But looks like Schema Registry handles compatibility correctly.

From the perspective of consumer, that is true that usually the application can't handle new fields w/o changing the code anyway. But in case when we just unpack json to a pydantic model and have shared models via e.g. library, we will fail with `extra='ignore'` and can't reuse models.
