### ISSUE TITLE
__pydantic_config__ fails with mypy

### ISSUE THREAD

**Issue by trecouvr** [pydantic/pydantic#8514]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello,

Running mypy on my code using __pydantic_config__ throws an error.

`error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]`

I think it's the same as reported here : https://github.com/pydantic/pydantic/discussions/7737.

### Example Code

```Python
from typing import Optional

from typing_extensions import TypedDict

from pydantic import ConfigDict, TypeAdapter, ValidationError


# `total=False` means keys are non-required
class UserIdentity(TypedDict, total=False):
    name: Optional[str]
    surname: str


class User(TypedDict):
    __pydantic_config__ = ConfigDict(extra='forbid')

    identity: UserIdentity
    age: int


ta = TypeAdapter(User)

print(
    ta.validate_python(
        {'identity': {'name': 'Smith', 'surname': 'John'}, 'age': 37}
    )
)
#> {'identity': {'name': 'Smith', 'surname': 'John'}, 'age': 37}

print(
    ta.validate_python(
        {'identity': {'name': None, 'surname': 'John'}, 'age': 37}
    )
)
#> {'identity': {'name': None, 'surname': 'John'}, 'age': 37}

print(ta.validate_python({'identity': {}, 'age': 37}))
#> {'identity': {}, 'age': 37}


try:
    ta.validate_python(
        {'identity': {'name': ['Smith'], 'surname': 'John'}, 'age': 24}
    )
except ValidationError as e:
    print(e)
    """
    1 validation error for typed-dict
    identity.name
      Input should be a valid string [type=string_type, input_value=['Smith'], input_type=list]
    """

try:
    ta.validate_python(
        {
            'identity': {'name': 'Smith', 'surname': 'John'},
            'age': '37',
            'email': 'john.smith@me.com',
        }
    )
except ValidationError as e:
    print(e)
    """
    1 validation error for typed-dict
    email
      Extra inputs are not permitted [type=extra_forbidden, input_value='john.smith@me.com', input_type=str]
    """
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /.virtualenvs/arpilab/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr 13 2023, 17:18:59) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-14.1-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.100.0 mypy-1.7.1 pydantic-settings-2.0.2
```

**Comment by dmontagu** [comment]
Yes, this is because mypy doesn't allow class attributes on `TypedDict` subclasses.

If it were my own code base, I would just add `# type: ignore[misc]` to that line and be done with it, but you can do the following and it will pass mypy (and work just as well):
```python
...
class User(TypedDict):
    identity: UserIdentity
    age: int

setattr(User, '__pydantic_config__', ConfigDict(extra='forbid'))
...
```

Note that this approach has the benefit of also telling you if you've entered an invalid key into `ConfigDict`, e.g.:
```python
class User(TypedDict):
    identity: UserIdentity
    age: int

setattr(User, '__pydantic_config__', ConfigDict(extra='forbid', abc='def'))
# error: Extra key "abc" for TypedDict "ConfigDict"
```

Open to suggestions of how to improve this experience and/or the documentation.

**Comment by arvidfm** [comment]
It's worth noting that the recommended way to specify the config seems to violate [the specification](https://peps.python.org/pep-0589/#class-based-syntax):

> The class body should only contain lines with item definitions of the form key: value_type, optionally preceded by a docstring

Would be good to have an alternative like a class decorator or allowing the `config` parameter to `TypeAdapter` for a `TypedDict`.

**Comment by trecouvr** [comment]
Hello, thank you for your answer.

I tried both of your suggestions @dmontagu https://github.com/pydantic/pydantic/issues/8514#issuecomment-1881840504 : 

The first one, using `# type: ignore[misc]` does not work, because even if mypy does not complain on this specific line, it then complains everywhere I use the model because it expects the field `__pydantic_config__` to be present.

The second one works well 👍  The syntax is not ideal since a piece of information is outside of the model and can easily be lost. I am sure you will find a way to make it work with the nice syntax from the documentation in the future.

**Comment by thedomdom** [comment]
Please note that this solution is still not possible with mypy + black/ruff.

- As you said, when using `User.__pydantic_config__ = ConfigDict(extra='forbid', abc='def')`, mypy will complain (`error: "type[XXX]" has no attribute "__pydantic_config__"  [attr-defined]`).
- When using `setattr(User, '__pydantic_config__', ConfigDict(extra='forbid', abc='def'))`, black/ruff will format it back to the first approach.

Very tricky :(

**Comment by Sillocan** [comment]
@thedomdom  The `with_config` decorator was added to resolve this issue in pydantic v2.7.0. https://docs.pydantic.dev/2.7/concepts/config/#configuration-with-dataclass-from-the-standard-library-or-typeddict

**Comment by thedomdom** [comment]
Thank you very much! 
Here is the link to the latest documentation: https://docs.pydantic.dev/latest/api/config/#pydantic.config.with_config
