### ISSUE TITLE
Incorrect Type on constructor

### ISSUE THREAD

**Issue by HarryAnkers** [pydantic/pydantic#8515]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When attempting to convert a type with field_validator mypy warns that the input argument is wrong. Is this intended behaviour. I want to avoid a lot of mypy ignores. 
In the example attached it warns "123" should be a int not a string despite it working.

### Example Code

```Python
class TestA(BaseModel):
    test1: int

    @classmethod
    @field_validator("test1", mode="before")
    def test(cls, raw: str) -> int:
        return int(raw) * 2


def a() -> None:
    try:
        print(TestA(test1="123").test1)
    except Exception as error:
        print(error)
```

### Python, Pydantic & OS Version

```Text
Python 3.11.7, Pydantic 2.4.2, MacOS 14.2.1 (23C71)
```

**Comment by sydney-runkle** [comment]
@HarryAnkers,

What happens if you do

```py
class TestA(BaseModel):
    test1: int

    @field_validator("test1", mode="before")
    @classmethod
    def test(cls, raw: str) -> int:
        return int(raw) * 2


def a() -> None:
    try:
        print(TestA(test1="123").test1)
    except Exception as error:
        print(error)
```

With the `classmethod` listed 2nd?

**Comment by sydney-runkle** [comment]
Following up, using the following snippet with `pydantic` 2.5.3, I get no `mypy` errors.

```py
from pydantic import BaseModel, field_validator

class TestA(BaseModel):
    test1: int

    @field_validator("test1", mode="before")
    @classmethod
    def test(cls, raw: str) -> int:
        return int(raw) * 2


def a() -> None:
    try:
        print(TestA(test1="123").test1)
    except Exception as error:
        print(error)
```

Thus, I'll close this issue as resolved.

**Comment by HarryAnkers** [comment]
Are you sure you are using mypy correctly.
Here is a screenshot from my IDE
![Screenshot 2024-01-09 at 14 26 16](https://github.com/pydantic/pydantic/assets/32963840/bb6e83ac-c3ff-442c-8cf6-8885ae70ed07)

**Comment by HarryAnkers** [comment]
Tagging in @sydney-runkle as I see this is no longer open

**Comment by sydney-runkle** [comment]
Ah @HarryAnkers I see what you mean. Yes, I'd argue this is intended - you're passing a `str` to a field that has a type `int`, so a `mypy` error is appropriate here.
