### ISSUE TITLE
using validate_call on a function before calling the function

### ISSUE THREAD

**Issue by samsja** [pydantic/pydantic#8530]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hey all, first thanks for the great library.

I just came across the validate_call feature which is very useful. I was wondering if we could even go one step further and allow to validate the argument to a function **before** calling it. In my case I want to validate some configuration that contains kwargs for a function. This function is call in the middle of my code, but I would like to validate it that the parameter are good early in my code.

small example:
```python

class HeavyObjectConfig(BaseModel):
   ...



heavy_object = {"heavy": ...}
func_call_args:  {"func_call": ...}

heavy_object_config = HeavyObjectConfig(**heavy_object)

heavy_object  = load_heavy_object(heavy_object_config) # take half a hour

call(**func_call_args) # where call is function wrap into a `validate_call`
```

In this example I would be able to catch problem when calling the function, but only after waiting half an hour of loading my object. Whereas if I could create a validator object out of the function call, I could call it before loading my object and be sure that everything will be fine when calling the function.

Additionally we could even turn function signature into BaseModel that I could use into another nested BaseModel.

A solution right now is to  create BaseModel that copy the function signature, but this is done manually so it take time and is error prone.

Do you think this is something that pydantic could support ? Codewise it should be fairly easy to do, happy to contribute as well

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@samsja,

Thanks for suggesting this feature. What do you have in mind in terms of implementation? Adding an extra arg to `validate_call`, or something else?

**Comment by alexmojaki** [comment]
Here's an approach you can take right now:

```python
from pydantic import validate_call


@validate_call
def validate_foo(a: int, b: int):
    def foo():
        print("Inside foo")
        return a + b

    return foo

def main():
    foo = validate_foo(a=1, b=2)
    print("Before calling foo")
    print(foo())


main()
```

**Comment by mohamed-ali-halloul** [comment]
can you assign to me this issue please

**Comment by samsja** [comment]
thanks @alexmojaki and @sydney-runkle for the suggestion.

I end up implementing something like this


```python
def function_call_validator(
    __func: AnyCallableT | None = None,
    *,
    config: ConfigDict | None = None,
) -> SchemaValidator:
    validator_wrapper = _validate_call.ValidateCallWrapper(__func, config, False)
    return validator_wrapper.__pydantic_validator__
```

by looking at the code of the validation call.

I am not sure what would be the ideal API for the feature.

**Comment by samsja** [comment]
great, thanks !

**Comment by alexmojaki** [comment]
TBC I think it'd be better to document an example similar to https://github.com/pydantic/pydantic/issues/8530#issuecomment-1885573821 rather than suggesting people write code involving things like `__pydantic_validator__` which may not be a stable API.
