### ISSUE TITLE
Add a exclude_empty option to model_dump

### ISSUE THREAD

**Issue by kwint** [pydantic/pydantic#8536]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I would like to be able to remove empty list from the model bump. There is a ways to do this now, but they all have downsides:

1. `exclude_defaults=True` will remove all default values, and that is not always desirable
2. `exclude_unset=True` will remove list that have been appended to.

See this example:

```python
class Bar(BaseModel):
    value: str = "default"


class Foo(BaseModel):
    bars: list[Bar] = []
    name: str = "default"
    other_list: list[str] = []
    optional: int | None = None


foo = Foo()
foo.bars.append(Bar())
foo.bars.append(Bar(value="test"))

print("exclude_unset: ", foo.model_dump(exclude_unset=True, include={"bars"}))
print("exclude_none: ", foo.model_dump(exclude_none=True))
print("exclude_defaults: ", foo.model_dump(exclude_defaults=True))

"""
exclude_unset:  {}
exclude_none:  {'bars': [{'value': 'default'}, {'value': 'test'}], 'name': 'default', 'other_list': []}
exclude_defaults:  {'bars': [{}, {'value': 'test'}]}
"""
```

I want an output that keeps default values, removes None and empty list/sets/tuples
```
{'bars': [{'value': 'default'}, {'value': 'test'}], 'name': 'default'}
```

So I think adding a argument that checks for empty lists (len(attribute) == 0) would be great:

```
foo.model_dump(exclude_none=True, exclude_empty=True)
```

Another option would be something like `exclude_false` where all values that `bool(attribute) is False` are removed. (That would also remove `""` etc

Small note: is it correct that doing `.append` on a default value should still be discarded by the export? There is an zero-reply discussion about this here: https://github.com/pydantic/pydantic/discussions/5749

 

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@kwint,

Thanks for brining up this inquiry. I think that [custom serializers](https://docs.pydantic.dev/latest/concepts/serialization/#custom-serializers) will probably work best for implementing the logic you're requesting. Here's what that might look like: 

```py
from typing import Dict, Any

from pydantic import BaseModel, model_serializer

class Bar(BaseModel):
    value: str = "default"


class Foo(BaseModel):
    bars: list[Bar] = []
    name: str = "default"
    other_list: list[str] = []
    optional: int | None = None

    # model serializer to exclude empty lists
    @model_serializer
    def ser_model(self) -> Dict[str, Any]:        
        return {k: v for k, v in dict(self).items() if isinstance(v, (list, set, tuple)) and len(v) > 0}


foo = Foo()
foo.bars.append(Bar())
foo.bars.append(Bar(value="test"))

print("exclude_custom: ", foo.model_dump())

"""
exclude_custom:  {'bars': [{'value': 'default'}, {'value': 'test'}]}
"""
```

You can imagine a very similar check for the case of checking for `False` values. Feel free to reach out if you have any questions!

**Comment by sydney-runkle** [comment]
@kwint,

Right - the `exclude_none` logic is run before the custom serializer logic, which is why the above approach with the `field_serializer` doesn't work. I think that your best bet is to use the `model_serializer` in this case 👍 

Ah, the `PydanticOmit` annotation is used for JSONSchema generation, not dumping, which is why it doesn't work.

**Comment by kwint** [comment]
@sydney-runkle 

I see, thanks for the insights!

It is a little bit unfortunate, because in our case this is about a super large object that is serialized to a file. Using the performance of the pydantic serializer in rust would have been awesome for that.

**Comment by sydney-runkle** [comment]
@kwint,

Sure thing. Here's an approach that you can take that still uses the inner logic in rust :):

```py
from typing import Dict, Any

from pydantic import BaseModel, model_serializer

class Bar(BaseModel):
    value: str = "default"


class Foo(BaseModel):
    bars: list[Bar] = []
    name: str = "default"
    other_list: list[str] = []
    optional: int | None = None

    # model serializer to exclude empty lists
    @model_serializer(mode='wrap')
    def ser_model(self, handler) -> Dict[str, Any]:   
        result = handler(self)     
        return {k: v for k, v in result.items() if isinstance(v, (list, set, tuple)) and len(v) > 0}


foo = Foo()
foo.bars.append(Bar())
foo.bars.append(Bar(value="test"))

print("exclude_custom: ", foo.model_dump())

"""
exclude_custom:  {'bars': [{'value': 'default'}, {'value': 'test'}]}
"""
```

You can read more about wrap serializers in this section of the docs: https://docs.pydantic.dev/latest/concepts/serialization/#custom-serializers

**Comment by CaptainDriftwood** [comment]
Just out of curiosity @sydney-runkle , model_dump includes options for excluding none type and default values, what is the reasoning for not including an option for empty collection type fields?

**Comment by sydney-runkle** [comment]
@CaptainDriftwood,

We figured that folks could use custom serializers if they desired behavior beyond what we offered!
