### ISSUE TITLE
SQLAlchemy Imperative mapping dataclass not working.

### ISSUE THREAD

**Issue by trazola** [pydantic/pydantic#8543]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi. Our team develops microservices based on the DDD idea. Unfortunately, after switching to pydantic v2, we are not able to map domain objects imperatively to database models. Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File [~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3433](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3433), in Session.add(self, instance, _warn)
   [3432](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3432) try:
-> [3433](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3433)     state = attributes.instance_state(instance)
   [3434](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3434) except exc.NO_STATE as err:

AttributeError: 'User' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

UnmappedInstanceError                     Traceback (most recent call last)
Cell In[2], [line 2](vscode-notebook-cell:?execution_count=2&line=2)
      [1](vscode-notebook-cell:?execution_count=2&line=1) user = User(id=1, name="Joe")
----> [2](vscode-notebook-cell:?execution_count=2&line=2) session.add(instance=user)

File [~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3435](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3435), in Session.add(self, instance, _warn)
   [3433](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3433)     state = attributes.instance_state(instance)
   [3434](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3434) except exc.NO_STATE as err:
-> [3435](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3435)     raise exc.UnmappedInstanceError(instance) from err
   [3437](https://file+.vscode-resource.vscode-cdn.net/Users/dv30kj/predator/P25238-Predator/predator-copy/temp/~/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py:3437) self._save_or_update_state(state)

UnmappedInstanceError: Class '__main__.User' is mapped, but this instance lacks instrumentation.  This occurs when the instance is created before sqlalchemy.orm.mapper(__main__.User) was called.

### Example Code

```Python
from pydantic.dataclasses import dataclass
from sqlalchemy import Column, Integer, String, Table, create_engine
from sqlalchemy.orm import registry, sessionmaker


mapper_registry = registry()


@dataclass()
class User:
    id: int
    name: str


user_table = Table(
    "user",
    mapper_registry.metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String),
)


mapper_registry.map_imperatively(User, user_table)

engine = create_engine('sqlite:///users.db')
mapper_registry.metadata.create_all(engine)

Session = sessionmaker(bind=engine)
session = Session()

user = User(id=1, name="Joe")
session.add(instance=user)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /Users/developer/Library/Caches/pypoetry/virtualenvs/predator-mbIod4j2-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.2-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 mypy-1.8.0
```

**Comment by sydney-runkle** [comment]
@trazola,

Hmm. Not sure exactly what is going wrong here. Have you tried using [`SQLModel`](https://sqlmodel.tiangolo.com/)? That tool helps combine SQLAlchemy logic with pydantic models, accounting for any potentially confusing behavior under the hood.

**Comment by trazola** [comment]
@sydney-runkle 
We are interested in mapping dataclasses to existing tables in SQLAlchemy.
Aggregates in SQLModel can more serve as ORM objects rather than Domain objects.
In Pydantic V1 everything worked fine.

**Comment by sydney-runkle** [comment]
Closing as stale for now. I'd recommend looking at `SQLModel`'s adoption of Pydantic V2 in order to better understand how to work around this issue. You might also consider using `from_attributes` which could be useful!

**Comment by sydney-runkle** [comment]
We could also move this to a discussion if you want, I just don't think it falls under the category of a V2 bug, but rather an implementation / application question.
