### ISSUE TITLE
Alias system doesn't cover basic use case of renaming an `internal` field from `external` usage

### ISSUE THREAD

**Issue by bluenote10** [pydantic/pydantic#8551]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

This is somewhere in-between a feature request and a bug report, but judging from the systematic analysis below, it feels like something isn't quite right with the alias system.

Consider the most basic use case of renaming a field. The goals are:

- Within Python code the field should be named e.g. `internal` consistently. This includes field access `my_instance.internal` and the class constructor `MyModel(internal=42)`. Type checkers like mypy/pyright should consider `internal` as the correct identifier in all Python code.
- To the outside the field should be called e.g. `"external"`. This includes all the usages of `model_validate` + `model_validate_json` in validation direction and `model_dump` + `model_dump_json` in serialization direction.

This feels like a very fundamental use case, because it makes sense that a name is decoupled in code from its external form in the payload -- but consistent within the two worlds.

From my systematic assessment it looks like neither `alias="..."`, `serialization_alias="..."`, `validation_alias="..."` nor combinations with `populate_by_name` seem to cover this use case. The following demo code actually constructs all either possible combinations of using

- only `alias="external"`
- only `serialization_alias="external"`
- only `alias="external"`
- both `serialization_alias="external"` and `validation_alias="external"`

and combines them further with both variations of `populate_by_name` enabled and disabled. In none of the the 8 variations the above goals seems to be achievable. The output of the snippet is:

```
Checking: WithAlias
 ✓  works | WithAlias.model_validate({'external': 42})
 ✓  works | WithAlias.model_validate_json({'external': 42})
 🛇  fails | instance = WithAlias(internal=42)

Checking: WithSerializationAlias
 🛇  fails | WithSerializationAlias.model_validate({'external': 42})
 🛇  fails | WithSerializationAlias.model_validate_json({'external': 42})
 ✓  works | instance = WithSerializationAlias(internal=42)
          | instance.model_dump()      => {'internal': 42}
          | instance.model_dump_json() => {"internal":42}

Checking: WithValidationAlias
 ✓  works | WithValidationAlias.model_validate({'external': 42})
 ✓  works | WithValidationAlias.model_validate_json({'external': 42})
 🛇  fails | instance = WithValidationAlias(internal=42)

Checking: WithBoth
 ✓  works | WithBoth.model_validate({'external': 42})
 ✓  works | WithBoth.model_validate_json({'external': 42})
 🛇  fails | instance = WithBoth(internal=42)

Checking: WithAliasPopByName
 ✓  works | WithAliasPopByName.model_validate({'external': 42})
 ✓  works | WithAliasPopByName.model_validate_json({'external': 42})
 ✓  works | instance = WithAliasPopByName(internal=42)
          | instance.model_dump()      => {'internal': 42}
          | instance.model_dump_json() => {"internal":42}

Checking: WithSerializationAliasPopByName
 🛇  fails | WithSerializationAliasPopByName.model_validate({'external': 42})
 🛇  fails | WithSerializationAliasPopByName.model_validate_json({'external': 42})
 ✓  works | instance = WithSerializationAliasPopByName(internal=42)
          | instance.model_dump()      => {'internal': 42}
          | instance.model_dump_json() => {"internal":42}

Checking: WithValidationAliasPopByName
 ✓  works | WithValidationAliasPopByName.model_validate({'external': 42})
 ✓  works | WithValidationAliasPopByName.model_validate_json({'external': 42})
 ✓  works | instance = WithValidationAliasPopByName(internal=42)
          | instance.model_dump()      => {'internal': 42}
          | instance.model_dump_json() => {"internal":42}

Checking: WithBothPopByName
 ✓  works | WithBothPopByName.model_validate({'external': 42})
 ✓  works | WithBothPopByName.model_validate_json({'external': 42})
 ✓  works | instance = WithBothPopByName(internal=42)
          | instance.model_dump()      => {'internal': 42}
          | instance.model_dump_json() => {"internal":42}
```

Observations:

- None of the variants serializes the data under the alias name. Shouldn't that be the case for the variants that use `serialization_alias` and probably also for the basic `alias` variant?
- Some constructors calls work with the `internal` name (those without `validation_alias` and the ones with `populate_by_name`) at runtime, others fail. Curiously the type checkers don't get the runtime semantics right. See the necessary `# type: ignore` for things that mypy is complaining about and `# pyright: ignore` for usages only complained about by pyright. It looks like mypy only has false negatives, while pyright also sees some false positives.

Note that swapping the roles of `internal` and `external` also does not satisfy the renaming requirement, because then field access has to happen under the "wrong" name, i.e., the Python code doesn't use `internal` consistently.

### Example Code

```Python
from typing import Callable

from pydantic import BaseModel, ConfigDict, Field, ValidationError

# All combinations of `alias` variations and `populate_by_name`


class WithAlias(BaseModel):
    internal: int = Field(alias="external")


class WithSerializationAlias(BaseModel):
    internal: int = Field(serialization_alias="external")


class WithValidationAlias(BaseModel):
    internal: int = Field(validation_alias="external")


class WithBoth(BaseModel):
    internal: int = Field(serialization_alias="external", validation_alias="external")


class WithAliasPopByName(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    internal: int = Field(alias="external")


class WithSerializationAliasPopByName(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    internal: int = Field(serialization_alias="external")


class WithValidationAliasPopByName(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    internal: int = Field(validation_alias="external")


class WithBothPopByName(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    internal: int = Field(serialization_alias="external", validation_alias="external")


def check(model: type[BaseModel], factory: Callable[[], BaseModel]) -> None:
    name = model.__name__
    print(f"\nChecking: {name}")

    works = " ✓  works |"
    fails = " 🛇  fails |"
    dummy = " " * (len(works) - 1) + "|"

    data = {"external": 42}
    try:
        instance_deser = model.model_validate({"external": 42})
        print(f"{works} {name}.model_validate({data})")
    except ValidationError:
        print(f"{fails} {name}.model_validate({data})")

    data = {"external": 42}
    try:
        instance_deser = model.model_validate_json('{"external": 42}')
        print(f"{works} {name}.model_validate_json({data})")
    except ValidationError:
        print(f"{fails} {name}.model_validate_json({data})")

    try:
        instance = factory()
        print(f"{works} instance = {name}(internal=42)")
    except ValidationError:
        print(f"{fails} instance = {name}(internal=42)")
        return

    print(f"{dummy} instance.model_dump()      => {instance.model_dump()}")
    print(f"{dummy} instance.model_dump_json() => {instance.model_dump_json()}")


# Variants without `populate_by_name`
check(WithAlias, lambda: WithAlias(internal=42))  # type: ignore
check(WithSerializationAlias, lambda: WithSerializationAlias(internal=42))
check(WithValidationAlias, lambda: WithValidationAlias(internal=42))
check(WithBoth, lambda: WithBoth(internal=42))

# Variants with `populate_by_name`
check(WithAliasPopByName, lambda: WithAliasPopByName(internal=42))  # pyright: ignore
check(WithSerializationAliasPopByName, lambda: WithSerializationAliasPopByName(internal=42))
check(WithValidationAliasPopByName, lambda: WithValidationAliasPopByName(internal=42))
check(WithBothPopByName, lambda: WithBothPopByName(internal=42))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/me/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
                     platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
             related packages: typing_extensions-4.9.0 mypy-1.8.0
```

**Comment by sydney-runkle** [comment]
@bluenote10,

Thanks for your detailed write up. I think the issue we've filed here covers the main concern that you've observed: https://github.com/pydantic/pydantic/issues/8379.

I think that in the meantime, if you use `model_dump(by_alias=True)` and a similar form for your calls to `model_dump_json`, the issue of serialization with the alias is solved. However, we recognize that there are some inconsistencies in regards to whether an alias is used by default or not between validation and serialization.

If you feel as though the issue I've linked above describes the concern / inconsistency that you're voicing here, then I think we should close this as a duplicate. If I've missed something in your report, please let me know!

**Comment by bluenote10** [comment]
> Thanks for your detailed write up. I think the issue we've filed here covers the main concern that you've observed: https://github.com/pydantic/pydantic/issues/8379.

That seems to cover a main aspect, but I've the impression that there are more inconsistencies here, like the constructor semantics and that they type check incorrectly. Speaking of V3: In terms of semantics the relationship between `alias`, `serialization_alias`, and `validation_alias` remains rather unclear. For instance why is it possible to construct `WithSerializationAlias(internal=42)` but not `WithAlias(internal=42)`? The documentation doesn't mention anything about why any of the three field would affect constructor semantics.

> I think that in the meantime, if you use model_dump(by_alias=True) and a similar form for your calls to model_dump_json, the issue of serialization with the alias is solved.

Note that this is not really a viable work-around, because it requires to get **all** calls to `.model_dump()` and `.model_dump_json()` "right". In practice this is not possible to guarantee, because you cannot control all your user code, and if a user gets it wrong, they serialize it into something invalid. Therefore, without attaching the renaming logic to the class itself, the renaming feature is not very usable in V2 as is. Would it be possible to add something like `by_alias=True` to the `ConfigDict`, so that the behavior gets attached to the class itself, offering a viable work-around in V2?

**Comment by sydney-runkle** [comment]
@bluenote10,

> The documentation doesn't mention anything about why any of the three field would affect constructor semantics.

I think we should leave this issue open then as a docs issue, and close it when we resolve the above comment. I think #8379 covers the inconsistency between validation / serialization alias setting specification well enough.

> In practice this is not possible to guarantee, because you cannot control all your user code, and if a user gets it wrong, they serialize it into something invalid.

I see your point. This will also be addressed by #8379, as we'll implement a config setting for both validation alias setting and serialization alias setting.

In the meantime, you could use a custom model serializer if you have a need for serialization to occur with `by_alias` set to `True` in all cases.

**Comment by bluenote10** [comment]
>I think we should leave this issue open then as a docs issue, and close it when we resolve the above comment. I think https://github.com/pydantic/pydantic/issues/8379 covers the inconsistency between validation / serialization alias setting specification well enough.

Yep that sounds good, thanks!

**Comment by alexanderankin** [comment]
several people are saying this:
https://github.com/pydantic/pydantic/discussions/2889
https://github.com/pydantic/pydantic/issues/8551
https://github.com/pydantic/pydantic/issues/8379
https://github.com/pydantic/pydantic/discussions/8725

and some with "resolutions" (i think incomplete ones as this is advocating for the more general case):
https://github.com/pydantic/pydantic/issues/1366
https://github.com/pydantic/pydantic/issues/892

my search query: https://github.com/pydantic/pydantic/issues?page=1&q=internal+external+field+name

**Comment by sydney-runkle** [comment]
@bluenote10,

Revisiting this now. Are you interested in opening a PR with a docs update - I think you might have a better idea of what content you'd like to include...

**Comment by bluenote10** [comment]
> I think you might have a better idea of what content you'd like to include...

I think it would be best to first solve https://github.com/pydantic/pydantic/issues/8379 and then update the documentation accordingly. I don't think it makes much sense to document the current behavior, because it really looks like a bug. Once #8379 is fixed it will make more sense.

**Comment by sydney-runkle** [comment]
Alright, I think we should probably close this then (if there's no action item associated with it, given that we'll of course update the docs in accordance with #8379). That being said, I'm glad we've attached this issue to #8379, and we'll be sure to consider your notes when implementing the aforementioned issue.
