### ISSUE TITLE
Literal inside Annotated has no effect on a field

### ISSUE THREAD

**Issue by itsayellow** [pydantic/pydantic#8556]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

My understanding is that when using `Annotated`, Pydantic should be reading the metadata in the second argument to the `Annotated` type.  This doesn't seem to be happening when using `Literal` to restrict valid values for a field. 

With the example code attached, I would expect both `modela2 = ModelA(a=2)` **and** `modelb2 = ModelB(b=2)` to return an error, but in fact only `modelb2 = ModelB(b=2)` returns an error.  The output of the script is as follows:
```
> python3 annotate_literal_test.py
Traceback (most recent call last):
  File "/Users/mclapp/annotate_literal_test.py", line 15, in <module>
    modelb2 = ModelB(b=2)
              ^^^^^^^^^^^
  File "/Users/mclapp/venv311/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ModelB
b
  Input should be 0 or 1 [type=literal_error, input_value=2, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
```

My application for this is to coerce this field to be an `int` while still specifying it can only be one of the specified values.  I was hoping to use Literal so I could efficiently use a Union and a `discriminator` string.

### Example Code

```Python
from typing import Annotated, Literal

from pydantic import BaseModel

class ModelA(BaseModel):
    a: Annotated[int, Literal[0,1]]

class ModelB(BaseModel):
    b: Literal[0,1]

modela1 = ModelA(a=1)
modela2 = ModelA(a=2)

modelb1 = ModelB(b=1)
modelb2 = ModelB(b=2)

print(modela1)
print(modela2)
print(modelb1)
print(modelb2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /Users/mclapp/venv311/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 pydantic-settings-2.1.0 fastapi-0.104.1
```

**Comment by vadim-su** [comment]
Is it some type of user?
In this case, I recommend using `IntEnum`.

**Comment by sydney-runkle** [comment]
@itsayellow,

This is not currently something that Pydantic supports. I think an `IntEnum` would be an appropriate choice 👍.

**Comment by itsayellow** [comment]
The application is that I have an unfortunate API I'm accessing that returns a different structure (different fields present, hence different model) depending on the field `status` which is an integer.  I'm trying to do valid parsing as simply as possible, and was hoping to speed up discrimination by specifying the `status` field as the discriminator for a Discriminated Union.  But I'd also like the status number to be an integer despite it being returned a string of an integer by the API.

My main issue is that I was trying to use a Discriminated Union with `discriminator=<field_name_string>`, and that seems to only be able to use `Literal`.  So I was trying to figure out some way to use `Literal`.  But it seems incompatible with type coercion.

**Comment by vadim-su** [comment]
Hey @itsayellow  :wave:
I stacked with the same problem and resolved it using the Fallback Type

<details> 
  <summary>Fallback Type example</summary>

```python
import enum
from typing import Literal, Annotated

from pydantic import Field, BaseModel, TypeAdapter


class UserType(enum.IntEnum):
    ANONYMOUS = 0
    USER = 1


class BaseUserModel(BaseModel):
    type: UserType


class AnonymousUser(BaseUserModel):
    type: Literal[UserType.ANONYMOUS] = UserType.ANONYMOUS


class UserBaseUser(BaseModel):
    type: Literal[UserType.USER] = UserType.USER
    username: str
    email: str


class FallbackUser(BaseModel):
    type: int
    username: str = 'anonymous'
    email: str = ''


type User = Annotated[AnonymousUser | UserBaseUser, Field(discriminator='type')] | FallbackUser


if __name__ == '__main__':
    user_adapter = TypeAdapter(User)

    # Test AnonymousUser
    user = user_adapter.validate_python({'type': UserType.ANONYMOUS})

    assert isinstance(user, AnonymousUser)
    assert user.type == UserType.ANONYMOUS
    assert not hasattr(user, 'username')
    assert not hasattr(user, 'email')
    print(user)

    # Test UserBaseUser
    user = user_adapter.validate_python(
        {
            'type': UserType.USER,
            'username': 'john',
            'email': 'test@emaxmple.com',
        },
    )

    assert isinstance(user, UserBaseUser)
    assert user.type == UserType.USER
    assert user.username == 'john'
    assert user.email == 'test@emaxmple.com'
    print(user)

    # Test FallbackUser
    user = user_adapter.validate_python(
        {
            'type': 2,
            'username': 'john',
            'email': 'test@example.com',
        }
    )

    assert isinstance(user, FallbackUser)
    assert user.type == 2
    assert user.username == 'john'
    assert user.email == 'test@example.com'
    print(user)

``` 
</details>

In any case, pydantic has many ways to do this.

**Comment by vadim-su** [comment]
Also, you can create your validator

**Comment by itsayellow** [comment]
Hi @vadim-su , thanks so much for your help.

Here's what I currently do.  I want a different model based on field `status`, and I want it to coerce `status` to be an integer even if it's given as a string:
```python
from pydantic import BaseModel, Field, RootModel
                                                                                
class ItemNormal(BaseModel):                                                    
    status: int = Field(le=0, ge=0)
    time_since_creation: int

class ItemDeleted(BaseModel):
    status: int = Field(le=1, ge=1)
    time_deleted: int

class Item(RootModel):
    root: ItemNormal | ItemDeleted

# Works and coerces string "0" to integer 0 for status
my_item0 = Item.model_validate({"status":"0", "time_since_creation":10})
print(my_item0)
# Outputs:
# root=ItemNormal(status=0, time_since_creation=10)

# Works and coerces string "1" to integer 1 for status
my_item1 = Item.model_validate({"status":"1", "time_deleted":1011234})
print(my_item1)
# Outputs:
# root=ItemDeleted(status=1, time_deleted=1011234)
```

For the fields `status`, I wanted to **not** use the goofy `Field(le=0, ge=0)` syntax and instead use a `Literal[0]`.  But I can't figure out a way to do that and still coerce a string `"0"` to an integer `0`, for example.

My hope is that I could define Item something like this:

```python
class Item(RootModel):
    root: Union[ItemNormal, ItemDeleted] = Field(discriminator="status")
```

But it seems to do this I need to use `Literal` in both `ItemNormal` and `ItemDeleted`, and if I use `Literal` there then I give up being able to coerce a string for `status` into an integer automatically.

I know I can always write my own discriminator function, but that seems like way more complexity than I'm looking for, given that this already works.

Or is there something simpler that I'm missing?

**Comment by ReRubis** [comment]
@itsayellow 
You can use @field_validator to convert the value to int. 
But I'm not sure how to handle the cases when the string value is not convertable to integer, if such cases are possible in your logic. 


```py
from pydantic import BaseModel, Field, RootModel, field_validator


class BaseItem(BaseModel):

    @field_validator('status', mode='before', check_fields=False)
    def coerce_status(cls, v):
        return int(v)


class ItemNormal(BaseItem):
    status: int = Field(le=0, ge=0)
    time_since_creation: int


class ItemDeleted(BaseItem):
    status: int = Field(le=1, ge=1)
    time_deleted: int


class Item(RootModel):
    root: ItemNormal | ItemDeleted


my_item0 = Item.model_validate({"status": "0", "time_since_creation": 10})
print(my_item0)

my_item1 = Item.model_validate({"status": "1", "time_deleted": 1011234})
print(my_item1)
```

**Comment by vadim-su** [comment]
@itsayellow 
I'd do something like this

```py
import enum
from typing import Annotated, Literal
from pydantic import BaseModel, BeforeValidator, RootModel


class ItemStatus(enum.IntEnum):
    NORMAL = 0
    DELETED = 1


type LiteralStatus[ItemStatusT: ItemStatus] = Annotated[
    Literal[ItemStatusT],
    BeforeValidator(
        lambda value: ItemStatus(int(value)),
    ),
]


class BaseItem(BaseModel):
    status: ItemStatus


class ItemNormal(BaseModel):
    status: LiteralStatus[ItemStatus.NORMAL]
    time_since_creation: int


class ItemDeleted(BaseModel):
    status: LiteralStatus[ItemStatus.DELETED]
    time_deleted: int


class Item(RootModel):
    root: ItemNormal | ItemDeleted


# Works and coerces string "0" to integer 0 for status
my_item0 = Item.model_validate({'status': '0', 'time_since_creation': 10})
print(my_item0)
# Outputs:
# root=ItemNormal(status=<ItemStatus.NORMAL: 0>, time_since_creation=10)

# Works and coerces string "1" to integer 1 for status
my_item1 = Item.model_validate({'status': '1', 'time_deleted': 1011234})
print(my_item1)
# Outputs:
# root=ItemDeleted(status=<ItemStatus.DELETED: 1>, time_deleted=1011234)

**Comment by vadim-su** [comment]
I have prepared a few different methods for doing this:
Explicit annotated validators

```py
class ItemNormal(BaseModel):
    status: Annotated[Literal[ItemStatus.NORMAL], BeforeValidator(int)]
    time_since_creation: int


class ItemDeleted(BaseModel):
    status: Annotated[Literal[ItemStatus.DELETED], BeforeValidator(int)]
    time_deleted: int
```

or with `field_validator`:
```py
class BaseItem(BaseModel):
    status: ItemStatus

    @field_validator('status', mode='before')
    def coerce_status(cls, v):
        return ItemStatus(int(v))


class ItemNormal(BaseItem):
    status: Literal[ItemStatus.NORMAL]
    time_since_creation: int


class ItemDeleted(BaseItem):
    status: Literal[ItemStatus.DELETED]
    time_deleted: int
```

**Comment by itsayellow** [comment]
Thanks so much @vadim-su !  Nice to know what the options are.  In particular I didn't realize there was type `BeforeValidator` which seems very useful.

In general I'm aware of things like `@field_validator` to coerce things to int's myself.  I was just hoping there was a clean, easy way of doing it more natively, because the main reason I like to use Pydantic is that I don't have to do everything myself.  

Your `LiteralStatus` is a great way to at least make a reusable type and reduce boilerplate in my models 👍
