### ISSUE TITLE
Automatically switch to v1 when there is import exception, or change pypi namespace to pydanticv2

### ISSUE THREAD

**Issue by binary-husky** [pydantic/pydantic#8571]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

The v1 to v2 shift is impacting too many other packages. I am getting tired of dealing with them! 

It would be more responsible to ensure that users do not wake up to find broken dependencies everywhere!

Please, seriously consider:
- Automatically detect v1 import exception when there is import exception, and switch to v1-compat mode
- Change your pypi namespace to pydanticv2 to avoid pip install collision

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by binary-husky** [comment]
This reminds me of the mess of shit they made when tensorflow upgrades to v2

**Comment by adriangb** [comment]
We already use a namespace: the version number. End users should use a lock file to ensure they don't get major version bumps unnoticed.

**Comment by binary-husky** [comment]
Do you think it is funny that every user has to google `ImportError: cannot import name xxxx from 'pydantic'` ??

It is wasting everyone's time! 

It will not hurt pydantic to avoid such thing simply by handling these ImportErrors by doing `from pydantic import v1 as pydantic_v1` automatically and throw a big red warning!
