### ISSUE TITLE
Validate mutations of model fields, e.g. appending to a list field

### ISSUE THREAD

**Issue by SkandaPrasad-S** [pydantic/pydantic#8575]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

```python
import pydantic

class Test(pydantic.BaseModel):
    items: list[str] = pydantic.Field(default_factory=list, max_items=2)
    class Config:
        validate_assignment = True
        validate_default = True
        
        
    
def main():
    # will validate
    t = Test(items=['a', 'b'])
    print(t)
    
    # will not validate
    t = Test(items=['a', 'b'])
    print(t)
    t.items.append('c')
    #No validation accours at this point

    
if __name__ == '__main__':
    main()
```
Pydantic here is not throwing an error even though the value of the list is getting updated. Can someone help me on this? 

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: E:\Perfection\GoalsRankedBackEnd\myvenv\Lib\site-packages\pydantic
               python version: 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: email-validator-2.1.0.post1 fastapi-0.105.0 pydantic-settings-2.1.0 typing_extensions-4.9.0
```

**Comment by alexmojaki** [comment]
`.append()` is not assignment, and pydantic can't automatically detect it happening on a plain list. It *could* use a wrapper or subclass to detect such modifications, but that would be a significant new feature requiring a new config flag to opt in.

A simple workaround is to use an immutable tuple instead which requires actual assignment to update:

```python
import pydantic


class Test(pydantic.BaseModel):
    items: tuple[str, ...] = pydantic.Field(default=(), max_items=2)

    class Config:
        validate_assignment = True
        validate_default = True


t = Test(items=('a',))
t.items += ('b',)
print(t)  # items=('a', 'b')
t.items += ('c',)  # error
```

**Comment by SkandaPrasad-S** [comment]
Hey! thank you so much for your response! What workaround do I have to use it with a `List` at the moment?

**Comment by alexmojaki** [comment]
You'd have to create a subclass of list which stores the pydantic model instance and field and assigns itself back to the field when it's modified.

**Comment by sydney-runkle** [comment]
Somewhat similar issue: https://github.com/pydantic/pydantic/issues/2635

**Comment by geospackle** [comment]
@sydney-runkle 
This seems like an interesting problem and a useful feature, would be interested in working on this.

I can think of a solution where `BaseModel` is extended s.t. any mutable type gets assigned to a subclass of the same type. Subtypes reassign the mutated object back to the field on the instance.

I'm thinking:

1. Create validating subclasses for all mutable types
- any mutator method is extended to reassign on the model instance
2. Extend `BaseModel` s.t. mutable Python types get reassigned to corresponding validating subtypes.
3. Add config flag to opt in to this functionality. Can not really think of any other way than modifying the initializer of `BaseModel`.

@alexmojaki 
very interested in your thought on this!

**Comment by geospackle** [comment]
@alexmojaki 
[this](https://gist.github.com/geospackle/8f317fc19469b1e216edee3cc0f1c898) should address your comments

**Comment by geospackle** [comment]
Bummer. Learnt a lot tinkering around with this though! 

I will leave [this gist](https://gist.github.com/geospackle/8f317fc19469b1e216edee3cc0f1c898) up for anyone who stumbles here to implement themselves the rest of the way if they need this functionality.
