### ISSUE TITLE
getting int_parsing error

### ISSUE THREAD

**Issue by sandrodevdariani** [pydantic/pydantic#8576]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Im trying to call api "remove_tag_from_image" but imputed tag_id parsed as string and cannot figure out why. I'm getting this error : **Validation Error: [{'type': 'int_parsing', 'loc': ('path', 'tag_id'), 'msg': 'Input should be a valid integer, unable to parse string as an integer', 'input': 'remove_tag_from_image', 'url': 'https://errors.pydantic.dev/2.5/v/int_parsing'}]**

### Example Code

```Python
@router.delete("/tags/remove_tag_from_image")
def remove_image_tag(
    request: Request,
    image_hash: str,  
    tag_id: int,  
):
    # The query now checks for the specific tag_id within the array of tags
    query = {"image_hash": image_hash, "tag_id": tag_id}
    result = request.app.image_tags_collection.delete_one(query)
    
    # If no document was found and deleted, raise an HTTPException
    if result.deleted_count == 0:
        print("Tag or image hash not found!")
      
    return {"status": "success"}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.1
        pydantic-core version: 2.14.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/ssss/Desktop/repos/img-pipeline/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Apr 19 2023, 18:51:09) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.8.0 fastapi-0.101.1
```

**Comment by sydney-runkle** [comment]
@sandrodevdariani,

The error message shows that you're passing in the string `'remove_tag_from_image'` for the `tag_id` field. You'll have to pass a valid integer to resolve this issue.
