### ISSUE TITLE
Add `toml` and `yaml` parsing support to `pydantic-settings`

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#8584]
See https://github.com/pydantic/pydantic-settings/issues/210 for more detail.

**Comment by semihyonet** [comment]
I think the PR for this issue has been submitted as https://github.com/pydantic/pydantic-settings/pull/212/files

**Comment by hramezani** [comment]
There is a PR for this issue https://github.com/pydantic/pydantic-settings/pull/211

We've created the issue here to make it more visible for contributors

**Comment by egolias1** [comment]
Has this issue been resolved now?

**Comment by hramezani** [comment]
@egolias1 Yes.
