### ISSUE TITLE
HttpUrl docs example has type issues

### ISSUE THREAD

**Issue by daviddavis** [pydantic/pydantic#8591]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If you run the following example from the docs through mypy you get errors:

<https://github.com/pydantic/pydantic/blob/e131d53a07da080c2ba642775efa9e81cb2cf0ba/pydantic/networks.py#L117-L144>

Here are the mypy errors being raised:

```
test.py:8: error: Argument "url" to "MyModel" has incompatible type "str"; expected "Url"  [arg-type]
test.py:14: error: Argument "url" to "MyModel" has incompatible type "str"; expected "Url"  [arg-type]
test.py:24: error: Argument "url" to "MyModel" has incompatible type "str"; expected "Url"  [arg-type]
```

In pydantic v1, you'd use `parse_obj_as` to convert the url so I was looking for an example of how to handle this and unfortunately this example doesn't work. 

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/david/Projects/Compute-PMC/server/.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.15 (main, Dec  1 2022, 15:04:29)  [GCC 9.4.0]
                     platform: Linux-5.4.0-164-generic-x86_64-with-glibc2.31
             related packages: email-validator-2.1.0.post1 mypy-1.8.0 fastapi-0.108.0 typing_extensions-4.9.0 pydantic-settings-2.1.0 pyright-1.1.344

mypy version: 1.8.0
```

**Comment by sydney-runkle** [comment]
@daviddavis,

Thanks for your question. Indeed, `mypy` would prefer something along the lines of:

```py
m = MyModel(url=HttpUrl('http://www.example.com/'))
```

Even though with the code as it stands, the string is converted into a `HttpUrl` instance during the validation process.

I'll add an update to the example to reflect this. Thanks for bringing this to our attention :).

**Comment by sydney-runkle** [comment]
@daviddavis,

Just updated the docs with a note on this example 👍

**Comment by daviddavis** [comment]
@sydney-runkle awesome! thank you.

**Comment by jscheel** [comment]
`m = MyModel(url=HttpUrl('http://www.example.com/'))` does not work either, as it returns `"Annotated" cannot be instantiated`

**Comment by sydney-runkle** [comment]
If you try this against `main`, you don't get the error anymore. You can also test against v2.10.0b2 :)
