### ISSUE TITLE
factory function 

### ISSUE THREAD

**Issue by SylvainGuieu** [pydantic/pydantic#8594]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I have the filling that a simple builtin helper  `factory` factory  would be a good addition. 

```python
from pydantic import Field, BaseModel
from pydantic.fields import FieldInfo 
from typing import Callable, Any


def factory( factory: Callable[[], Any])->FieldInfo:
      return  Field( default_factory = factory )
```

Usage

```python 
from datetime import datetime 
class M(BaseModel):
     time: datetime =  factory( datetime.now )
 ```

Which is much more readable then : 

```python
class M(BaseModel):
     time: datetime =  Field( default_factory = datetime.now )
 ```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@SylvainGuieu,

Thanks for your request.

This pattern seems to be a pretty specific use case where a `Field` only takes the `default_factory` argument. Given that this is a relatively specific use case, I think a change like this should reside in user code.

Going to mark this as not planned, because I we're not likely to implement this API anytime soon.
