### ISSUE TITLE
Compact definition of dependent defaults

### ISSUE THREAD

**Issue by adonath** [pydantic/pydantic#8603]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I recently came across the use case, where a default value of one field depends on the value of another field. Currently  I can use a model validator for this, or overwrite `__init__`, both requires a lot of code to express a simple relationship:

```python3
from pydantic import BaseModel, Field, model_validator
from typing import Optional


# Works, but a lot of code
class MyModel(BaseModel):
    a: int
    b: Optional[int] = None

    @model_validator(mode="before")
    @classmethod
    def validate(cls, values):
        values.setdefault("b", 5 * values["a"])
        return values


# Works, but still a lot of code
class MyModel2(BaseModel):
    a: int
    b: Optional[int] = None

    def __init__(self, **kwargs):
        kwargs.setdefault("b", 5 * kwargs["a"])
        super().__init__(**kwargs)

print(MyModel(a=1))
print(MyModel2(a=2))
```

From a user perspective something like this would be much shorter to write:

```python
# What about something like this?
class MyModel3(BaseModel):
    a: int
    b: Optional[int] = Field(default_factory=lambda kw: 5 * kw["a"])
```
So the default factory can have an optional argument, which are the arguments the class is initialized with. Then it computes the depending default. The following pattern could also work, where init arguments are un-packed into the default factory function:

```python
class MyModel4(BaseModel):
    a: int
    b: int
    c: Optional[int] = Field(default_factory=lambda a, b:  a * b])
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by adonath** [comment]
Just for completeness, I found a more compact way of expressing this:

```python3
from typing import Annotated, Optional
from pydantic import AfterValidator, BaseModel, ConfigDict

def DependentDefault(type, func):
    return Annotated[Optional[type], AfterValidator(lambda v, values: func(v, values) if v is None else v)]

class MyModel(BaseModel):
    model_config = ConfigDict(validate_default=True)
    a: int
    b: DependentDefault(int, lambda v, info: 5 * info.data["a"]) = None


print(MyModel(a=1))
print(MyModel(a=1, b=10))
```
However I think it is still not as elegant as the default factory with arguments.

**Comment by sydney-runkle** [comment]
@adonath,

I think you've made some great suggestions here for your use case, but for most users, using the model validator approach is simple + compact enough that it meets their needs. The `DependentDefault` helper that you've defined is a great reference for others as well, looking to consolidate the same logic in a more intuitive way.

That being said, I have some reservations about whether the `default_factory` is the appropriate place to house this logic. `default_factory` values are passed all of the way to `pydantic-core`, and pulling validation logic into that area of processing feels misguided and messy.

If this issue gets a lot of traction (upvotes, comments, etc), we could revisit how to better implement support for dependent defaults in a clean manner. We'd need broader community interest and consensus on implementation details before moving forward with this, given that it would likely end up as a commonly used feature for which we couldn't easily change the API down the line.

**Comment by adonath** [comment]
Thanks for the comment @sydney-runkle! I think the `DependentDefault` is a good solution for now. I agree it makes sense to wait and see whether other users are interested in similar use cases.

**Comment by pmeier** [comment]
One disadvantage of the solution provided in https://github.com/pydantic/pydantic/issues/8603#issuecomment-1904939403 is that the static annotation is lost, because it is set at runtime. Running `mypy` on

```python
from typing import Annotated, Optional
from pydantic import AfterValidator, BaseModel, ConfigDict

def DependentDefault(type, func):
    return Annotated[Optional[type], AfterValidator(lambda v, values: func(v, values) if v is None else v)]

class MyModel(BaseModel):
    model_config = ConfigDict(validate_default=True)
    a: int
    b: DependentDefault(int, lambda v, info: 5 * info.data["a"]) = None

my_model = MyModel(a=2)

reveal_type(my_model.a)
reveal_type(my_model.b)
```

gives

```
...
main.py:20: note: Revealed type is "builtins.int"
main.py:21: note: Revealed type is "Any"
```

A solution that preserves the type is

```python
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Callable

from pydantic import BaseModel, model_validator


if TYPE_CHECKING:
    DependentDefaultField = Any
else:

    class DependentDefaultField:
        def __init__(
            self, make_default: Callable[[DependentDefaultModel], Any]
        ) -> None:
            self.make_default = make_default

        @classmethod
        def resolve(cls, model: DependentDefaultModel) -> None:
            for name, info in model.model_fields.items():
                value = getattr(model, name)
                if isinstance(value, cls):
                    setattr(model, name, value.make_default(model))


class DependentDefaultModel(BaseModel):
    @model_validator(mode="after")
    def _resolve_dependent_default_fields(self) -> DependentDefaultModel:
        DependentDefaultField.resolve(self)
        return self


class MyModel(DependentDefaultModel):
    a: int
    b: int = DependentDefaultField(lambda model: 5 * model.a)
```

**Comment by pmeier** [comment]
Improved version of https://github.com/pydantic/pydantic/issues/8603#issuecomment-2264988605 that also works with models that use `validate_default=True` by default, e.g. `pydantic_settings.BaseSettings`:

```python
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Callable

from pydantic import model_validator, Field
from pydantic_settings import BaseSettings


if TYPE_CHECKING:
    DependentDefaultField = Any
else:

    class DependentDefaultField:
        _RESERVED_PARAMS = ["default", "default_factory", "validate_default"]

        def __new__(
            cls,
            dependent_default: Callable[[DependentDefaultSettings], Any],
            **kwargs: Any,
        ) -> Field:
            if any(param in kwargs for param in cls._RESERVED_PARAMS):
                reserved_params = ", ".join(
                    repr(param) for param in cls._RESERVED_PARAMS
                )
                raise Exception(
                    f"The parameters {reserved_params} are reserved "
                    f"and cannot be passed"
                )

            self = super().__new__(cls)
            self.__dependent_default__ = dependent_default
            # We are not setting 'default' here, because otherwise Pydantic tries to
            # deepcopy this object down the line.
            return Field(default_factory=lambda: self, validate_default=False)

        @classmethod
        def resolve(cls, model: DependentDefaultSettings) -> None:
            for name, info in model.model_fields.items():
                value = getattr(model, name)
                if isinstance(value, cls):
                    setattr(model, name, value.__dependent_default__(model))


class DependentDefaultSettings(BaseSettings):
    @model_validator(mode="after")
    def _resolve_dependent_default(self) -> DependentDefaultSettings:
        DependentDefaultField.resolve(self)
        return self


class MySettings(DependentDefaultSettings):
    a: int
    b: int = DependentDefaultField(lambda model: 5 * model.a)
```

**Comment by Viicos** [comment]
This should land in 2.10, but we're tracking progress in https://github.com/pydantic/pydantic/issues/9789.

**Comment by Viicos** [comment]
This was implemented in https://github.com/pydantic/pydantic/pull/10678, and will be available in 2.10.

**Comment by milani** [comment]
@Viicos this is great. I'm wondering if `PrivateAttr`'s `default_factory` work the same way and accept a `data` argument?

**Comment by Viicos** [comment]
Yes, see https://github.com/pydantic/pydantic/pull/11685.
