### ISSUE TITLE
Validation error, missing field when using optional[any] with default None value

### ISSUE THREAD

**Issue by ahmet2mir** [pydantic/pydantic#8608]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello world,

I'm using pydantic `2.5.2`, and I got a strange issue (which i hadn't with pydantic v1).

If I use a Field as `Optional[Any]` and set inside the Field a default value to None, pydantic raise a field error.
If I remove the Field and set `None` directly it works.

I try to search on many places and also inside the documentation, but it "should" work, or I missed something ?

Thanks!

### Example Code

```Python
from typing import Optional,Any
from pydantic import BaseModel, Field

class Job(BaseModel):
    id: str
    result: Optional[Any] = Field(defaut=None)

# ko
Job(id="myid")

# ok
Job(id="myid", result=None)


# If I remove `Field` and set to None directly

class Job(BaseModel):
    id: str
    result: Optional[Any] = None

# ok
Job(id="myid")
```

### Python, Pydantic & OS Version

```Text
       pydantic version: 2.5.2
  pydantic-core version: 2.14.5
    pydantic-core build: profile=release pgo=true
           install path: /usr/local/myapp/.pex/installed_wheels/dd7271a4ebe824aa0a0c00700eaba0d43a826b49ccca6a270cdb6613f388af23/pydantic-2.5.2-py3-none-any.whl/pydantic
         python version: 3.9.5 (default, May 27 2021, 16:11:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
               platform: Linux-3.10.0-1160.105.1.el7.x86_64-x86_64-with-glibc2.17
       related packages: typing_extensions-4.9.0 fastapi-0.104.1 pydantic-settings-2.1.0
```

**Comment by davidhewitt** [comment]
You have a typo `defaut=None`, where it should be `default=None`

This definition works fine:

```python
class Job(BaseModel):
    id: str
    result: Optional[Any] = Field(default=None)  # note spelled correctly
```

**Comment by ahmet2mir** [comment]
Hi David,

I'm feeling so dumb  ... in french "default" is "défaut".

My model is composed with 15 Fields, all of them are "default" and just thoses 2 which are "any" had the typo.
That's why I didn't found anything about optional any and default :laughing: 

Thanks a lot :heart:
