### ISSUE TITLE
validate_call causes problems with `inspect.getmembers`

### ISSUE THREAD

**Issue by mroethke** [pydantic/pydantic#8610]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using the `validate_call` decorator in a base class, calling `inspect.getmembers` on a derived class raises a `TypeError`. I would expect this to not raise an Exception.

### Example Code

```Python
import inspect
import pydantic

class Test:
    @pydantic.validate_call
    def foobar():
        pass

class Test2(Test):
    pass

inspect.getmembers(Test2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /usr/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
                     platform: Linux-6.7.0-arch3-1-x86_64-with-glibc2.38
             related packages: typing_extensions-4.9.0
```

**Comment by alexmojaki** [comment]
Try with pydantic version 2.6.0b1. I'm not seeing an error when I run this locally and I think that's because I'm working with more recent code which in particular includes https://github.com/pydantic/pydantic/pull/8268.

**Comment by mroethke** [comment]
It does indeed work with 2.6.0b1, any idea when this will land in stable?

**Comment by mroethke** [comment]
awesome, and thank you for your quick response!
