### ISSUE TITLE
[docs] v2.5 Settings management section mentions `env_ignore_empty`, which is not available yet

### ISSUE THREAD

**Issue by lukapeschke** [pydantic/pydantic#8618]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The documentation of pydantic 2.5 mention `pydantic-settings`'s `env_ignore_empty` config setting (https://docs.pydantic.dev/2.5/concepts/pydantic_settings/#parsing-environment-variable-values) .

However, this setting has not been released yet: it was added on december 11th, and the latest pydantic-settings release (2.1) has been made on november 14th.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
       pydantic-core version: 2.14.6
         pydantic-core build: profile=release pgo=true
                install path: /home/lpeschke/work/toucan/dataset-service/.direnv/python-3.11/lib/python3.11/site-packages/pydantic
              python version: 3.11.6 (main, Nov 19 2023, 14:12:09) [GCC 13.2.1 20231011 (Red Hat 13.2.1-4)]
                    platform: Linux-6.6.12-200.fc39.x86_64-x86_64-with-glibc2.38
            related packages: typing_extensions-4.8.0 pydantic-settings-2.1.0 mypy-1.8.0 fastapi-0.109.0



Also, pydantic-settings is is in version 2.1.0
```

**Comment by sydney-runkle** [comment]
@lukapeschke,

Thanks for reporting this. @hramezani, could you take a look at this issue, please?

**Comment by lukapeschke** [comment]
@hramezani @sydney-runkle  thanks for the quick fix!
