### ISSUE TITLE
RootModel.model_dump type-hints its return as original input model object instead of json/dict

### ISSUE THREAD

**Issue by laundmo** [pydantic/pydantic#8620]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

while type checking, the return type of RootModel.model_dump is typed-hinted as RootModelRootType, which is the models type.

https://github.com/pydantic/pydantic/blob/3e871258bd5ea7caa7f18c0b810d8b1e915bd8f2/pydantic/root_model.py#L135

this is inconsistent with the non-typehinted implementation in BaseModel, where the return type is a dictionary

https://github.com/pydantic/pydantic/blob/3e871258bd5ea7caa7f18c0b810d8b1e915bd8f2/pydantic/main.py#L293

### Example Code

```Python
from typing import Any, reveal_type
import pydantic
from pydantic.dataclasses import dataclass

@dataclass()
class MyModel:
    i: int

def expects_json(json: dict[str, Any]):
    pass

m = MyModel(1)

json = pydantic.RootModel[MyModel](m).model_dump()
reveal_type(json) # Type of "json" is "MyModel"
expects_json(json) # Argument of type "MyModel" cannot be assigned to parameter "json" of type "dict[str, Any]"
```

### Python, Pydantic & OS Version

```Text
NOTE: this behaviour exists on main as of writing, see the linked lines above

             pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: C:\Users\...\Documents\python-projects\api_client\.venv\Lib\site-packages\pydantic
               python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: pydantic-extra-types-2.1.0 typing_extensions-4.8.0
```

**Comment by sydney-runkle** [comment]
@laundmo,

Indeed, this is expected. The specific case that you're witnessing is that because you use a `BaseModel` as the `RootModelType`, that data is dumped as well. Consider this more simple case:

```
from typing import Dict, List

from pydantic import RootModel

Pets = RootModel[List[str]]


print(Pets(['dog', 'cat']))
#> root=['dog', 'cat']

dumped = Pets(['dog', 'cat']).model_dump()
print(dumped)
#> ['dog', 'cat']

print(type(dumped))
#> <class 'list'>
```

As you can see, `model_dump` does return an object of type `List` for this case.

In your case above, `MyModel` is also being dumped because it has a core schema, though in general, the overridden type makes sense here.

**Comment by laundmo** [comment]
Thank you for the quick handling of this!

**Comment by sydney-runkle** [comment]
@laundmo,

Sure thing! Thanks for bringing it to our attention :).
