### ISSUE TITLE
`FieldInfo.__repr_args__` ignoring field's default value when set to `None` explicitly

### ISSUE THREAD

**Issue by Evenfire** [pydantic/pydantic#8629]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When running the associated example code, we get:
```
{'a': FieldInfo(annotation=str, required=False, default='ADEF', alias='A', alias_priority=2),
 'b': FieldInfo(annotation=int, required=True, alias='B', alias_priority=2),
 'c': FieldInfo(annotation=Union[str, NoneType], required=False, alias='C', alias_priority=2)}
```

Notice that
- for field `a`, we see the default value
- for field `b`, we don't see the default value which is alright since no default as been provided
- for field `c`, we don't see the default value set explicitly, which is `None`.

I would expect to get:

```
{'a': FieldInfo(annotation=str, required=False, default='ADEF', alias='A', alias_priority=2),
 'b': FieldInfo(annotation=int, required=True, alias='B', alias_priority=2),
 'c': FieldInfo(annotation=Union[str, NoneType], required=False, default=None, alias='C', alias_priority=2)}
```

This is more a quality of live improvement than anything else. With the proposed change, it's easier to inspect model definitions at a glance (and it's also less confusing)

Here is the code responsible for filtering out the `default` attribute  of `FieldInfo` when its value is `None` (as well as `PydanticUndefined`, which is well): [pydantic/fields.py](https://github.com/pydantic/pydantic/blob/3e871258bd5ea7caa7f18c0b810d8b1e915bd8f2/pydantic/fields.py#L581)

If there is no objection to the new behaviour, I'll open a pull request.

### Example Code

```Python
from pprint import pprint

import pydantic


class Foo(pydantic.BaseModel):
    a: str = pydantic.Field("ADEF", alias="A")
    b: int = pydantic.Field(..., alias="B")
    c: str | None = pydantic.Field(None, alias="C")


pprint(Foo.model_fields)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /myprojects/awesome/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Jan  7 2024, 10:09:49) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.103.2 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
@Evenfire,

This issue is quite related - https://github.com/pydantic/pydantic/issues/8634. Would you be interested in taking a stab at a fix for that one as well? Thanks for your help!

**Comment by Evenfire** [comment]
@sydney-runkle 

I'll open a PR for this issue as soon as I have few minutes.
