### ISSUE TITLE
Object has not attribute __pydantic_serializer__ when accessing a BaseModel field that contains a RootModel field

### ISSUE THREAD

**Issue by StephaneCapponi** [pydantic/pydantic#8635]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

There is a weird issue going on when I call model_dump of a BaseModel field that contains a RootModel field. I don't know if it's a real bug or something I don't understand. 

The error is the following:

`Traceback (most recent call last):
  File "C:\git-repos\connectivity\devops-main\test.py", line 40, in <module>
    print(integration.config.model_dump())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git-repos\connectivity\devops-main\venv\Lib\site-packages\pydantic\main.py", line 301, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git-repos\connectivity\devops-main\venv\Lib\site-packages\pydantic\main.py", line 726, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'IntegrationConfig' object has no attribute '__pydantic_serializer__'. Did you mean: '__pydantic_private__'?`

### Example Code

```Python
from __future__ import annotations

from pydantic import BaseModel, RootModel


class Integration(BaseModel):
    name: str
    config: IntegrationConfig


class IntegrationConfig(BaseModel):
    name: str
    submodules: SubmoduleRegistry


class SubmoduleRegistry(RootModel):
    root: list[Submodule]


class Submodule(BaseModel):
    name: str


integration = Integration(**{
        "name": "test",
        "config": {
            "name": "my_config",
            "submodules": [
                {"name": "a"},
                {"name": "b"},
            ]
        }
    }
)

print(integration.config.model_dump())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.1.1
        pydantic-core version: 2.4.0
          pydantic-core build: profile=release pgo=false mimalloc=true
                 install path: C:\git-repos\connectivity\devops-main\venv\Lib\site-packages\pydantic
               python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
     optional deps. installed: ['typing-extensions']
```

**Comment by alexmojaki** [comment]
I don't get an error. Pydantic 2.1.1 is quite old, can you try the latest version?

**Comment by StephaneCapponi** [comment]
@alexmojaki. I confirm the issue is no more present on the latest version. Thanks for the quick reply
