### ISSUE TITLE
`NameEmail` does not support parsing from json input

### ISSUE THREAD

**Issue by Holi0317** [pydantic/pydantic#8649]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Originate from https://github.com/pydantic/pydantic/issues/7720#issuecomment-1812475489. Turns out that is an issue with implementation of `NameEmail`.

Support matrix of `NameEmail` currently is:

| Type | Serialization/dump | Deserialization/validate |
| --- | --- | --- |
| Python | ✅ | ✅ |
| JSON | ✅ | ❌ |

Trying to validate a json with `NameEmail` in the model will raise following exception:

```
NotImplementedError: Cannot check isinstance when validating from json, use a JsonOrPython validator instead.
```

See example code below for parsing a `NameEmail` from json. These cases will be included in the PR's unit test.

### Example Code

```Python
import pydantic

class Model(BaseModel):
    v: NameEmail

Model.model_validate_json('{"v":{"name":"foo bar","email":"foobaR@example.com"}}')
Model.model_validate_json('{"v":"foo bar <foobaR@example.com>"}')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /Volumes/Projects/pydantic/pydantic
               python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 pydantic-extra-types-2.4.1 pydantic-settings-2.1.0 mypy-1.1.1 email-validator-2.1.0.post1
                       commit: b785d5b1
```

**Comment by sydney-runkle** [comment]
@Holi0317,

Ah yes, thanks for reporting this. Thanks a bunch for contributing a fix. I'll review your PR later today :). Great work!
