### ISSUE TITLE
`ByteSize.human_readable` with an optional separator (e.g. whitespace) between value and unit

### ISSUE THREAD

**Issue by jks15satoshi** [pydantic/pydantic#8668]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently, the return value of `ByteSize.human_readable` does not have any separator between the value and unit.

```python
>>> size = ByteSize(12345678)
>>> size.human_readable()
'11.8MiB'
```

It looks a little bit weird to me, and I think it could be better if there's a space separating the value and unit. Though there are many ways to handle this need, it may be a better idea to provide an optional argument with this method? For example:

```python
ByteSize.human_readable(decimal: bool = False, separator: bool = False) -> str
```

When I switch the `separator` on:

```python
>>> size = ByteSize(12345678)
>>> size.human_readable(separator=True)
'11.8 MiB'
```

It's probably easy to be implemented, so I can create a PR to implement this feature if it will be acceptable.

What do you think about it?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@jks15satoshi,

Go for it! Just makes sure that by default, the separator is `''` so that this isn't a breaking change. Thanks for the suggestion. Ping me when you need a review :).

**Comment by jks15satoshi** [comment]
@sydney-runkle,

Thanks. PR has been created :)
