### ISSUE TITLE
Timedelta string with hour value greater than 23 is not supported (breaking change)

### ISSUE THREAD

**Issue by gusutabopb** [pydantic/pydantic#8673]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In Pydantic v1, timedelta strings in the format `HH:MM:SS` with `HH` greater than 23 worked fine (i.e. the example code below works). This format is also supported by `pandas.Timedelta` by the way.

In Pydantic v2, the example code below fails with the following exception:

```
ValidationError: 1 validation error for MyModel
td
  Input should be a valid timedelta, hour value is outside expected range of 0-23 [type=time_delta_parsing, input_value='26:30:00', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/time_delta_parsing
```
As a workaround I have to change string to:
- `26:30:00` -> `PT26H30M` or `1 day 02:30`
- `24:00:00` -> `PT24H` or `1 day 00:00`

IMO, ideally `HH:MM:SS` with `HH` greater than 23 should be supported in Pydantic v2. Or at the very least, this should be documented as a breaking change in the [Migration Guide](https://docs.pydantic.dev/latest/migration/).

### Example Code

```Python
import datetime
import pydantic
from pydantic import BaseModel

class MyModel(BaseModel):
    td: datetime.timedelta

print(f"{pydantic.__version__=}")
assert MyModel(td="26:30:00").td == datetime.timedelta(days=1, seconds=9000)
assert MyModel(td="24:00:00").td == datetime.timedelta(days=1)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/gbezerra/ipynb/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 (main, Jun  7 2023, 13:51:08) [GCC 11.3.0]
                     platform: Linux-5.19.0-35-generic-x86_64-with-glibc2.35
             related packages: email-validator-2.0.0 typing_extensions-4.6.3 fastapi-0.83.0
                       commit: unknown
```

**Comment by gusutabopb** [comment]
It looks like Pydantic (speedate) tries to parse Durations in the format `HH:MM:SS` as "Time", thus the 0-23 limitation.

Relevant code: https://docs.rs/speedate/latest/src/speedate/duration.rs.html#262-280.

**Comment by sydney-runkle** [comment]
@gusutabopb,

Thanks for reporting this. I'll chat with the team tomorrow morning + we'll decide if we want to document this change in the migration guide or if we want to change the behavior of `speedate`.

**Comment by sydney-runkle** [comment]
@gusutabopb,

Indeed - this is something that we want to support, and I don't think this change would be breaking in nature. Feel free to submit a PR adding support for this!

**Comment by davidjb99** [comment]
having this issue too, would be good to get it fixed.

**Comment by sydney-runkle** [comment]
I've added this to our 2.8.0 milestone!

**Comment by nix010** [comment]
@sydney-runkle I can take this one. But just to clarify, should the change be in `pydantic-core` or `speedate`  ?

**Comment by sydney-runkle** [comment]
@nix010 fantastic! I believe the fix would be in speedate for this one!

**Comment by nix010** [comment]
@sydney-runkle gotcha !

**Comment by nix010** [comment]
@sydney-runkle silly question ! we only want `Duration` to support format `HH:MM:SS` with `HH` in range `99..00` ?

`101:20:20` is invalid and raise Err but `99:20:20` is ok ?

**Comment by gusutabopb** [comment]
@nix010 I don't think there should be any arbitrary limit on the number of digits of the `HH` component. 

pydantic/speedate with `PT` notation works fine with up to 6 digits `HH` components (it fails with 7 digits though)

```python
from pydantic import TypeAdapter
import datetime

TA = TypeAdapter(datetime.timedelta)
TA.validate_strings("PT123H00M")  # datetime.timedelta(days=5, seconds=10800)
TA.validate_strings("PT123456H00M")  # datetime.timedelta(days=5144)
TA.validate_strings("PT1234567H00M")  # throws a ValidationError, "duration is too large"
```

I think the support for `HH:MM:DD` should behave the same as when using `PT` notation (i.e. no arbitrary 3-digit limit for `HH`).

**Comment by nix010** [comment]
@gusutabopb oh I didn't noticed that. But tbh they are different format. Let's see how does @sydney-runkle decide!

**Comment by sydney-runkle** [comment]
@nix010,

Hmm, I think we'd want to mimic whatever worked in V1. I can ask @davidhewitt on Monday what he thinks!

**Comment by davidhewitt** [comment]
It looks like the V1 behaviour derives from Django, which itself derives from how Python's `datetime.timedelta` is formatted (using `str(my_timedelta)`).

However it looks like the `datetime.timedelta` normalizes itself to never have more than 23 hours (if it hits 24, it moves the value into "days"). So it's unclear to me whether Django accepted wider ranges deliberately or by accident.

@gusutabopb how are you generating these duration strings?

**Comment by gusutabopb** [comment]
@sydney-runkle If you modify the code sample in the and run it in Pydantic v1 (I just tried with 1.10.15), it works fine for 3~11 digits. 

```python
>>> MyModel(td="123456789:30:00").td
datetime.timedelta(days=5144032, seconds=77400)
```

We hit an `OverflowError` at some point though:
```python
>>> MyModel(td="99999999999:00:00").td
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1074, in pydantic.main.validate_model
  File "pydantic/fields.py", line 881, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1098, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1154, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 337, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/datetime_parse.py", line 248, in pydantic.datetime_parse.parse_duration
OverflowError: Python int too large to convert to C int
```


If Pydantic v1 compatibility is the goal, then there should be no arbitrary restriction on number of digits the `HH` component takes as suggested/asked by @nix010. Restrictions due to memory overflow, etc are understandable though.

**Comment by gusutabopb** [comment]
@davidhewitt I don't think "by typing on my keyboard" is the answer you are looking for (it is the literal answer though), so I assume you're asking about my original use case.

I needed to schedule jobs to be run at a given time (offset) after a reference date (probably not relevant, but I'm using [apscheduler](https://apscheduler.readthedocs.io/en/3.x/)). Some jobs were scheduled to run on the same date as the the reference date (e.g. offset = `14:30`), while some were on the next day (e.g. offset = `26:30`).

I use Pydantic mostly to validate configuration, and while migrating to Pydantic v2, I had to change dozens of time offsets in my config files (e.g. from `26:30` to `1d 02:30`). This is not a big deal but still a breaking change from Pydantic v1 behavior and lead me to raise this issue.

Thinking in terms of greater-than-24 hours to indicate T+1 times is quite handy when dealing with timezones, UTC offsets, etc and is actually extremely common [in some parts of the world]( https://www.quora.com/Is-Japan-the-only-country-to-use-25-00-to-indicate-1-00-am).

**Comment by davidhewitt** [comment]
Thanks, that's useful to understand.

I had a bit of a chat with the rest of the team, and we agreed that it does make sense to accept the v1 behaviour again. The format seems unambiguous, so while it's a little atypical to want to exceed `23:59:59` in this format, there's no good reason not to accept it.

That said, it looks like there's a workaround for now (even if it requires a bit of work), so we're unlikely to tackle this with any particular priority. If someone really wants this sooner than we can tackle it, a contribution would be gratefully accepted. 👍

**Comment by nix010** [comment]
ok! I will go ahead with the change.

**Comment by nix010** [comment]
@davidhewitt Hi, just curious so now the PR in speedate is merged. Does any changes needed on pydantic-core (or pydantic) also ? I imaging should be some dependancies version update!

**Comment by sydney-runkle** [comment]
@nix010,

We'll want to do a dependencies update in `pydantic-core`, but we'll have to do a `speedate` release first. I can handle that as we wind up for our 2.8 release this week :).

Thanks for your help here!

**Comment by sydney-runkle** [comment]
Marking this as resolved as the corresponding PR has been merged. For folks following along, we'll have this fix out hopefully by the end of the month.
