### ISSUE TITLE
Pydantic TzInfo(UTC) != datetime.UTC

### ISSUE THREAD

**Issue by gkoller** [pydantic/pydantic#8683]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A Pydantic model with a `datetime.datetime` attribute and initialized with an UTC timestamp fails to correctly compare its `.tzinfo` attribute to `datetime.UTC` for equality.

### Example Code

```Python
import datetime

from pydantic import BaseModel


class Event(BaseModel):
    dt: datetime.datetime = None


event = Event(dt="2024-01-01T13:56:57.115Z")
print("This should be True:", event.dt.tzinfo == datetime.UTC)
# prints: This should be True: False
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /Users/guido/devel/alliander/grid-switch-state-service/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  9 2023, 06:06:18) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.6.3-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 mypy-1.7.1 pydantic-settings-2.1.0 fastapi-0.103.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@gkoller,

Thanks for reporting this. We use the `TzInfo` object from `pydantic_core`, which theoretically has performance benefits, though said benefits have been questioned, see: https://github.com/pydantic/pydantic/issues/7897.

There have also been reported issues with pandas compatibility, see https://github.com/pydantic/pydantic/issues/8195.

I'll chat with the team about these inquiries and get back to you tomorrow morning re next steps.

**Comment by andersk** [comment]
Note that Python’s own standard library has many different UTC zone objects: for example, `datetime.UTC`, `zoneinfo.ZoneInfo("UCT")`, `zoneinfo.ZoneInfo("UTC")`, `zoneinfo.ZoneInfo("Universal")`, `zoneinfo.ZoneInfo("Zulu")`, `zoneinfo.ZoneInfo("Etc/UCT")`, `zoneinfo.ZoneInfo("Etc/UTC")`, `zoneinfo.ZoneInfo("Etc/Universal")`, `zoneinfo.ZoneInfo("Etc/Zulu")` all compare as unequal. So equality comparison with `datetime.UTC` is not a reliable way to detect UTC.

**Comment by gkoller** [comment]
@andersk Thank you for pointing that out. Never knew that, never having bothered to use the `zoneinfo` module that is new as of Python 3.9.

Did have to check your claim though ;-)

```python
import datetime
import itertools
import zoneinfo

timezones: list[datetime.tzinfo] = [
    datetime.UTC,
    zoneinfo.ZoneInfo("UCT"),
    zoneinfo.ZoneInfo("UTC"),
    zoneinfo.ZoneInfo("Universal"),
    zoneinfo.ZoneInfo("Zulu"),
    zoneinfo.ZoneInfo("Etc/UCT"),
    zoneinfo.ZoneInfo("Etc/UTC"),
    zoneinfo.ZoneInfo("Etc/Universal"),
    zoneinfo.ZoneInfo("Etc/Zulu"),
]
tz_pairs = itertools.combinations(timezones, 2)
for tz1, tz2 in tz_pairs:
    print(f"{tz1} == {tz2} = {tz1==tz2}")
```
And indeed all compare as unequal:
```
UTC == UCT = False
UTC == UTC = False
UTC == Universal = False
UTC == Zulu = False
UTC == Etc/UCT = False
UTC == Etc/UTC = False
UTC == Etc/Universal = False
UTC == Etc/Zulu = False
UCT == UTC = False
UCT == Universal = False
UCT == Zulu = False
UCT == Etc/UCT = False
UCT == Etc/UTC = False
UCT == Etc/Universal = False
UCT == Etc/Zulu = False
UTC == Universal = False
UTC == Zulu = False
UTC == Etc/UCT = False
UTC == Etc/UTC = False
UTC == Etc/Universal = False
UTC == Etc/Zulu = False
Universal == Zulu = False
Universal == Etc/UCT = False
Universal == Etc/UTC = False
Universal == Etc/Universal = False
Universal == Etc/Zulu = False
Zulu == Etc/UCT = False
Zulu == Etc/UTC = False
Zulu == Etc/Universal = False
Zulu == Etc/Zulu = False
Etc/UCT == Etc/UTC = False
Etc/UCT == Etc/Universal = False
Etc/UCT == Etc/Zulu = False
Etc/UTC == Etc/Universal = False
Etc/UTC == Etc/Zulu = False
Etc/Universal == Etc/Zulu = False
```

And this means @sydney-runkle that what I reported as a bug, is not a bug after all. 

Though It is a change in behaviour from Pydantic V1 to V2 and probably should be documented as such somewhere in the [Migration Guide](https://docs.pydantic.dev/latest/migration). 

But once again @andersk remark stands:

> So equality comparison with datetime.UTC is not a reliable way to detect UTC.

And I agree now. Need to brush up my knowledge Python datetime handling. Thank you all, I learned something new today.

**Comment by samuelcolvin** [comment]
don't we just need to fix [`TzInfo::__richcmp__`](https://github.com/pydantic/pydantic-core/blob/42394acb0fdd9b7cb64ec56174be4ac3b9eca5c9/src/input/datetime.rs#L566-L568)?

**Comment by samuelcolvin** [comment]
Or add `__eq__`? cc @davidhewitt

**Comment by davidhewitt** [comment]
We could definitely implement comparisons for `pydantic_core.TzInfo` with fixed-offset `datetime.timezone`, which I think would fix  the UTC case.

I think for more advanced timezones which aren't fixed offset the ordering is not well defined, so I think we could only make this work for `datetime.timeonze`.

**Comment by samuelcolvin** [comment]
sounds good, PR welcome to add that.
