### ISSUE TITLE
Unexpected behaviour with attributes using `default` or `default_factory`

### ISSUE THREAD

**Issue by ThomasMarwitzQC** [pydantic/pydantic#8685]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I came across an unexpected behaviour when comparing two instances of the same model in my own `__eq__` method.

When using a `default` value or `default_factory`, the attribute name is contained in `model_fields_set` if the attribute is provided. If it is not provided, however, the attribute name doesn't appear in `model_fields_set`:

```python
class DummyModel(BaseModel):
    model_config = ConfigDict(extra="allow")

    plain: str
    default: str = "B"
    default_factory: str = Field(default_factory=lambda: "C")


model_a = DummyModel(
    plain="A",
    default="B",
    default_factory="C",
    extra="D",
)

print("fields_set", model_a.model_fields_set)
# fields_set {'default', 'extra', 'plain', 'default_factory'}

model_b = DummyModel(plain="A", extra="B")

print("fields_set", model_b.model_fields_set)
# fields_set {'extra', 'plain'}
```

After thinking about this, this is somewhat expected based on the documentation on `model_fields_set`:
> Returns the set of fields that have been explicitly set on this model instance.

So my approach to take a look at _all_ non-pydantic attributes (apart from `computed` attributes) is 
```python
set(vars(model_b).keys()) | model_b.model_fields_set
# {'default', 'plain', 'extra', 'default_factory'}

# vars(...) alone is not enough: 
set(vars(model_b).keys())
# {'default', 'default_factory', 'plain'} 
# misses the extra attribute
```

I'd favor a more explicit note in the documentation for someone like me that didn't think this whole explicit thing through. I'm happy to contribute a PR with a documentation update if you think that a note would be nice :) 

If you are aware of a better solution than mine, I would love to include that in the documentation as well!

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, Field


class DummyModel(BaseModel):
    model_config = ConfigDict(extra="allow")

    plain: str
    default: str = "B"
    default_factory: str = Field(default_factory=lambda: "C")


model_a = DummyModel(
    plain="A",
    default="B",
    default_factory="C",
    extra="D",
)

print("fields_set", model_a.model_fields_set)
# fields_set {'default', 'extra', 'plain', 'default_factory'}

model_b = DummyModel(plain="A", extra="B")

print("fields_set", model_b.model_fields_set)
# fields_set {'extra', 'plain'}

# vars(...) alone is not enough
print("vars", set(vars(model_b).keys()))
# {'default', 'default_factory', 'plain'}


print("vars | model_fields_set", set(vars(model_b).keys()) | model_b.model_fields_set)
{"default", "plain", "extra", "default_factory"}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /Users/thomasmarwitz/mambaforge/envs/test/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]
                     platform: macOS-14.1.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 pydantic-settings-2.1.0
```

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

Thanks for the detailed inquiry. I'm not entirely sure what you mean by "all non Pydantic attributes", but if your goal is to get the list of all of the values provided - both pydantic fields and extra values, I think the following approach might be the cleanest option. I've shown the yield of said union as well:

```py
set(model_b.model_extra) | set(model_b.model_fields)
#> {'extra', 'plain', 'default_factory', 'default'}
```

Let me know what you think about this solution! Then we can chat about a docs update 🚀. Thanks for your willingness to contribute!

**Comment by sydney-runkle** [comment]
@ThomasMarwitzQC,

I think that for now, this is a specific enough question / use case that it probably doesn't merit a docs update, so I'm going to close this as completed.

**Comment by ThomasMarwitzQC** [comment]
@sydney-runkle Hey, sorry for answering so late, I've been pretty busy lately. Your decision seems fine to me, especially, since this issue serves as a starting point for people who encounter the same problem :)
