### ISSUE TITLE
If the default value of the parameter is set, why set the type that allows the default value? Is it unnecessary?

### ISSUE THREAD

**Issue by jaxonister** [pydantic/pydantic#8686]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

```python
    class B(BaseModel):
        a: str = None
        b: int = 2


    model = B(a=None, b="111")
    print(model.dict())
```
The type of A is str and the default value is None. Is it possible to allow the type of A to be None by default?

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@jaxonister,

Not sure if I understand your question entirely. Much of the value from `pydantic` comes from the fact that specifying type annotations for fields in a model allows for reliable data validation and serialization.

You can read more about optional fields in V2 here: https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields.

The table in that section of the docs should answer your questions about what is required / not required when specifying a field with a default or a field that is optional.
