### ISSUE TITLE
Update Version 2.5.3 to 2.6.0 error -> LookupError: Could not find a ref for #/components/schemas/xpto . Maybe you tried to call resolve_ref_schema from within a recursive model?

### ISSUE THREAD

**Issue by MatheusVp2** [pydantic/pydantic#8689]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

After updating from pydantic 2.5.3 > 2.6.0, updating in my project, it broke all tests, with the problem of ```LookupError: Could not find a ref for #/components/schemas/xpto . Maybe you tried to call resolve_ref_schema from within a recursive model?```

### Example Code
```Py
import typing
from enum import Enum

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi
from pydantic import BaseModel, Field


class AllowedValues(str, Enum):
    VAL1 = 'Val1'
    VAL2 = 'Val2'


class ModelA(BaseModel):
    # Removing the max_length from the Field definition will make the code work
    modelA_1: AllowedValues = Field(..., max_length=60)


class ModelB(ModelA):
    modelB_1: typing.List[ModelA]


class ModelC(BaseModel):
    # Removing modelC_1 or modelC_2 and keeping only one of them will make the code work
    modelC_1: ModelB
    modelC_2: ModelB


class ModelD(BaseModel):
    modelD_1: typing.List[ModelC]


app = FastAPI(version='1.0.0')


@app.post('/route1', response_model=ModelD)
async def route1():
    raise NotImplementedError


schema = get_openapi(
    title='test',
    servers=[{"url": "https://test.com", "description": "desc"}],
    description='description',
    version='1.0.0',
    routes=app.routes)
print(schema)
```

_No response_

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/myuser/.pyenv/versions/3.9.14/envs/project/lib/python3.9/site-packages/pydantic
               python version: 3.9.14 (main, Dec  9 2022, 17:08:14)  [GCC 9.4.0]
                     platform: Linux-5.15.0-92-generic-x86_64-with-glibc2.31
             related packages: typing_extensions-4.9.0 fastapi-0.109.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@MatheusVp2,

Could you please provide a code snippet from which we can reproduce this error? Thanks!

**Comment by MatheusVp2** [comment]
I managed to debug the application here and found that when I call the function, `get_openapi` from `from fastapi.openapi.utils import get_openapi`, it breaks and throws the error

**Comment by Kludex** [comment]
We need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that we can run. Would you mind providing that? 🙏

**Comment by MatheusVp2** [comment]
Diving deeper into debugging, I found that there's an error occurring in the models that are enums. When looking at the example of an enum in the documentation and running it, there's an issue there as well, although it's not the same error. However, there might be a connection, I believe.
I still haven't been able to simulate an example for the error.

**Comment by MatheusVp2** [comment]
@Kludex  @sydney-runkle 
Added the minimum code example there to simulate the error. Emphasizing that it works in version 2.5.3.

**Comment by Kludex** [comment]
I can reproduce the issue on 2.6.

**Comment by dmontagu** [comment]
Somewhat simplified pure-pydantic reproduction of the issue:
```
import typing
from enum import Enum

from pydantic import BaseModel, Field


class AllowedValues(str, Enum):
    VAL1 = 'Val1'
    VAL2 = 'Val2'


class ModelA(BaseModel):
    # Removing the max_length from the Field definition will make the code work
    modelA_1: AllowedValues = Field(..., max_length=60)


class ModelB(ModelA):
    modelB_1: typing.List[ModelA]


class ModelC(BaseModel):
    modelC_1: ModelB


class Model(BaseModel):
    b: ModelB
    c: ModelC


Model.model_json_schema()
```

I had feared this was also introduced by #8526 but that doesn't _seem_ to be the case.

**Comment by sydney-runkle** [comment]
I've traced the source of this issue to here: https://github.com/pydantic/pydantic/commit/b2aa36a80904773d7db2e4c007fc00a5a4d7653b
