### ISSUE TITLE
computed_fields have inconsistent behaviour between model_dump and model_dump_json (part 2)

### ISSUE THREAD

**Issue by Samreay** [pydantic/pydantic#8691]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Was validating the changes made from https://github.com/pydantic/pydantic/issues/8250 and encountered a new issue.

The code submitted as a reproduction in the prior issue now works, so I've increased the complexity by one notch to reproduce a different failure. @sydney-runkle tagging you simply because you were so responsive on the prior issue and Im assuming this will have a similar fix :)

Importantly, the print output agrees between the two methods if you remove the `computed` function, *or* move it after `y_is_none`

I believe the issue is here: https://github.com/pydantic/pydantic-core/pull/1098/files#diff-9d4853412aaf93703485a5ed7c50c373184ec151d1d480a109e52430fedf9ca8R78

Where the code `returns` after the first None computed field, instead of simply moving onto the next field to check if it is None.

### Example Code

```Python
from pydantic import BaseModel, computed_field


class Example(BaseModel):
    x: int
    y: int | None

    @computed_field
    def computed(self) -> None:
        return None

    @computed_field
    def y_is_none(self) -> bool:
        return self.y is None


if __name__ == "__main__":
    e = Example(x=1, y=None)

    print(e.model_dump(exclude_none=True))
    # {'x': 1, 'y_is_none': True}

    print(e.model_dump_json(exclude_none=True))
    # {"x":1}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/sam/arenko/trade-selector/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jul  4 2023, 13:46:25) [GCC 11.3.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 fastapi-0.109.0 mypy-1.8.0 pydantic-settings-2.1.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Samreay,

Thanks for bringing this to our attention! Indeed, looks like this should be a pretty easy fix in `pydantic-core`.

Would you like to open a PR there with a fix, and we can get that change into our upcoming patch release of `pydantic`?

**Comment by sydney-runkle** [comment]
@Samreay,

I went ahead and opened that PR in core. I've verified that with the changes, here's the behavior in `pydantic`:

```py
from pydantic import BaseModel, computed_field


class Example(BaseModel):
    x: int
    y: int | None

    @computed_field
    def computed(self) -> None:
        return None

    @computed_field
    def y_is_none(self) -> bool:
        return self.y is None


if __name__ == "__main__":
    e = Example(x=1, y=None)

    print(e.model_dump(exclude_none=True))
    # {'x': 1, 'y_is_none': True}

    print(e.model_dump_json(exclude_none=True))
    # {"x":1,"y_is_none":true}
```

See the core PR here: https://github.com/pydantic/pydantic-core/pull/1187
