### ISSUE TITLE
__pydantic_config__ ignored in `TypeAdapter` for `TypedDicts`

### ISSUE THREAD

**Issue by evalott100** [pydantic/pydantic#8698]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When generating json schema with pydantic, `__pydantic_config__` is ignored in the outputted json, [contrary to what the docs explain](https://docs.pydantic.dev/2.6/errors/usage_errors/#type-adapter-config-unused).

In the below example I set `title`, however I've found it won't work with any `ConfigDict.json_schema_extra` either, which is really what I require for my uses.

### Example Code

```Python
from typing_extensions import TypedDict

from pydantic import ConfigDict, TypeAdapter


# Tested on both my system and the live runner https://docs.pydantic.dev/2.6/errors/usage_errors/#type-adapter-config-unused

class MyTypedDict(TypedDict):
    x: int

    # or `model_config = ...` for BaseModel
    __pydantic_config__ = ConfigDict(title="foobar")


type_adapter = TypeAdapter(MyTypedDict)
print(type_adapter.json_schema()) # The outputted json doesn't have the correct title.

# OUTPUT
# pydantic version: v2.6.0, pydantic-core version: v2.16.1
# {'properties': {'x': {'title': 'X', 'type': 'integer'}}, 'required': ['x'], 'title': 'MyTypedDict', 'type': 'object'}
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /scratch/twj43146/Programming/event-model-fork/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
                     platform: Linux-4.18.0-477.21.1.el8_8.x86_64-x86_64-with-glibc2.28
             related packages: typing_extensions-4.9.0 mypy-1.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@evalott100,

Thanks for reporting this issue. Could you please confirm whether this issue was introduced in 2.6, or if it has been a problem for a while?

**Comment by evalott100** [comment]
> @evalott100,
> 
> Thanks for reporting this issue. Could you please confirm whether this issue was introduced in 2.6, or if it has been a problem for a while?

@sydney-runkle Thanks for the fast reply!

We're updating some code from v1 to v2 just now so I'm unsure how long this problem has been there.

**Comment by sydney-runkle** [comment]
@evalott100,

I just checked. Looks like this is a V2 problem in general, not a v2.6 problem. Nonetheless, definitely something that we want to fix! Thanks for reporting this. We'll look into a fix and try to include that in 2.7.0 :).

**Comment by 13sin** [comment]
Hi @sydney-runkle & @evalott100 I was looking into this issue, I think, The `typed_dict_schema` function in `json_schema.py` is missing update for `title` and `json_schema_extra`. Can I create PR for this?

**Comment by sydney-runkle** [comment]
@13sin,

That'd be great, thanks!
