### ISSUE TITLE
Feature Request: Enhanced Support for Field Names Starting with Underscores

### ISSUE THREAD

**Issue by meer-khan** [pydantic/pydantic#8700]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Dear Pydantic Community,

I hope this message finds you well. I have been using Pydantic in conjunction with FastAPI and MongoDB and wanted to share a feature request that I believe would benefit many users in similar scenarios.

Currently, Pydantic treats fields starting with underscores as private and does not support field validators for such fields. In the context of FastAPI, MongoDB, and Pydantic, it is quite common to return document IDs as "_id" to the frontend. However, there is a need to convert this ID into a string instead of the default ObjectId.

My feature request is to enhance Pydantic's support for field names starting with underscores. Specifically, it would be valuable to:

Allow field names starting with underscores to be used without being automatically treated as private.
Provide the option to apply model and field validators on fields starting with underscores.
I believe this feature would offer more flexibility in scenarios where customization of field names is required, especially when working with external systems like MongoDB.

If there are existing functionalities in Pydantic that address this concern and I may have missed, I would greatly appreciate your guidance on this matter.

I am eager to hear your thoughts on this feature request and would love to discuss any potential considerations or alternatives.

Thank you for your time and contributions to the Pydantic community.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@meer-khan,

Thanks for the well thought out feature request. One question that I have - what functionality would be offered from this change that can't currently be achieved with the use of aliases?

Ex, if you want to have a field that's validated and dumped with the key `_id`:

```py
from pydantic import BaseModel, Field

class Person(BaseModel):
    name: str
    id_: int = Field(..., alias='_id')

p = Person(name='John', _id=42)
print(p.model_dump(by_alias=True))
#> {'name': 'John', '_id': 42}
```

At the moment, I'm leaning towards this approach as a solution. The nice thing about this is that you can customize validators, serializers, etc for any field, even if it has a leading underscore when validating and serializing.

I have some reservations about changing the behavior of fields that begin with `_` overall, as a large number of current users depend on this behavior, which is pretty consistent with Python's treatment of leading underscored fields as private.

**Comment by sydney-runkle** [comment]
Also, this is a duplicate of https://github.com/pydantic/pydantic/issues/2105

**Comment by meer-khan** [comment]
@sydney-runkle  Thank you for your prompt and detailed feedback! I appreciate your consideration of the alias approach.
I did not realize the use of aliases for such private fields but overall it is a good approach. 

using aliases is a viable option for many cases, the proposed change aims to provide a more streamlined and explicit syntax for handling fields with leading underscores. This could enhance code readability and reduce the need for additional configuration, but again it is up to the developers of Pydantic how they see it going, it was just a suggestion from my end. Again I appreciate your prompt response and giving me a good solution to tackle such fields. Apologise for appearing after a long time on this issue. Thank you

**Comment by lamnguyenx** [comment]
> [@meer-khan](https://github.com/meer-khan),
> 
> Thanks for the well thought out feature request. One question that I have - what functionality would be offered from this change that can't currently be achieved with the use of aliases?
> 
> Ex, if you want to have a field that's validated and dumped with the key `_id`:
> 
> from pydantic import BaseModel, Field
> 
> class Person(BaseModel):
>     name: str
>     id_: int = Field(..., alias='_id')
> 
> p = Person(name='John', _id=42)
> print(p.model_dump(by_alias=True))
> #> {'name': 'John', '_id': 42}
> 
> At the moment, I'm leaning towards this approach as a solution. The nice thing about this is that you can customize validators, serializers, etc for any field, even if it has a leading underscore when validating and serializing.
> 
> I have some reservations about changing the behavior of fields that begin with `_` overall, as a large number of current users depend on this behavior, which is pretty consistent with Python's treatment of leading underscored fields as private.
> 
> Excited to hear your thoughts.


This worked perfectly in my case: parsing Hydra config with _target_ field:
```
target__: str  = pdt.Field(..., description="Target class path for the Model", alias='_target_')
```

**Comment by aureliojargas** [comment]
Note that pydantic version 2.11 (March 2025) introduced a new model config so all aliased fields are serialized using their aliases by default:

- https://docs.pydantic.dev/latest/concepts/alias/#serialization
- https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.serialize_by_alias

No more `by_alias=True` needed in every `model_dump()` 🎉
