### ISSUE TITLE
model_serializer can receive or set exclude

### ISSUE THREAD

**Issue by jaxonister** [pydantic/pydantic#8707]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

https://github.com/pydantic/pydantic/issues/8687#issue-2109952704

```python
class AA(BaseModel):
    a: str = "123"

    @model_serializer(mode='wrap')
    def ser_model(self, handler):
        return handler(self)


class ABC(BaseModel):
    abc: AA = Field(from_attributes=True)


@pytest.mark.skip_conftest
def test_demo():
    model = ABC(abc={"a": "123"})
    print(model.model_dump(exclude={"a"}))
```
Setting exclude requires excluding other model fields, but it does not take effect. How should I set it? The underlying model settings cannot be uniformly excluded, because the requirement scenarios are different.

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@jaxonister,

You have to specify at which level you'd like the `a` field excluded, for example:

```py
from pydantic import BaseModel, Field, model_serializer


class AA(BaseModel):
    a: str
    b: str

    @model_serializer(mode='wrap')
    def ser_model(self, handler):
        return handler(self)


class ABC(BaseModel):
    abc: AA = Field(from_attributes=True)


model = ABC(abc={"a": "123", "b": "456"})
print(model.model_dump(exclude={"abc": {"a"}}))
#> {'abc': {'b': '456'}}
```
