### ISSUE TITLE
valid Pydantic model with fields having `required` attribute generates invalid JSON schema

### ISSUE THREAD

**Issue by kostunin** [pydantic/pydantic#8714]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have discovered that using `required` attribute in the field declaration brings to an invalid JSON schema generation.

Below two valid Pydantic models are defined:

```python
class ValidModel(pydantic.BaseModel):
    f: int = pydantic.Field(...)


class InvalidModel(pydantic.BaseModel):
    f: int = pydantic.Field(..., required=True)
```

Which produce following JSON schemas:

```json
{
  "properties": {
    "f": {
      "title": "F",
      "type": "integer"
    }
  },
  "required": [
    "f"
  ],
  "title": "ValidModel",
  "type": "object"
}

{
  "properties": {
    "f": {
      "required": true,
      "title": "F",
      "type": "integer"
    }
  },
  "required": [
    "f"
  ],
  "title": "InvalidModel",
  "type": "object"
}
```

One can see, that `InvalidModel` has an additional `required` attribute for the field `f`:

```json
    "f": {
      "required": true,
      "title": "F",
      "type": "integer"
    }
```

which will raise an exception from `jsonschema` when attempting to validate:

```python
jsonschema.validate(InvalidModel(f=1).dict(), InvalidModel.schema())
```

```
Traceback (most recent call last):
  File "/tmp/2.py", line 17, in <module>
    jsonschema.validate(InvalidModel(f=1).dict(), InvalidModel.schema())
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 930, in validate
    cls.check_schema(schema)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 294, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: True is not of type 'array'

Failed validating 'type' in metaschema['properties']['properties']['additionalProperties']['properties']['required']:
    {'default': [],
     'items': {'type': 'string'},
     'type': 'array',
     'uniqueItems': True}

On schema['properties']['f']['required']:
    True
```

The schema is indeed invalid (tested with `ajv-cli`)

Setting any other attribute will generate valid schema (I am not an expert in JSON schema specification, but probably it works for all non-reserved keywords):

```python
class InvalidModel(pydantic.BaseModel):
    f: int = pydantic.Field(..., other_attrib=True)
```

### Example Code

```Python
import pydantic
import jsonschema


class ValidModel(pydantic.BaseModel):
    f: int = pydantic.Field(...)


class InvalidModel(pydantic.BaseModel):
    f: int = pydantic.Field(..., required=True)


print(pydantic.version.version_info())
print(ValidModel.schema_json(indent=2))
print(InvalidModel.schema_json(indent=2))

try:
    jsonschema.validate(InvalidModel(f=1).dict(), InvalidModel.schema())
except jsonschema.exceptions.SchemaError as e:
    print(e)
```

### Python, Pydantic & OS Version

reproduced both with Pydantic 1.x and Pydantic 2.x

#### Pydantic 1.x

```Text
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/kostunin/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-5.14.0-1036-oem-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'typing-extensions']
```

#### Pydantic 2.x

```Text
             pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/kostunin/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-5.14.0-1036-oem-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 typing_extensions-4.5.0
                       commit: unknown
```

**Comment by semihyonet** [comment]
Hi, I believe you are using an incorrect label since you are using pydantic 1.9.0 . Can you update your issue with the newer version or attach a V1 Bug label?

**Comment by semihyonet** [comment]
Afaik, the required keyword of the Field class is unusable in V2 and can only be replicated by `Field(..., json_schema_extra={'required': ['t']})`.

**Comment by kostunin** [comment]
> Hi, I believe you are using an incorrect label since you are using pydantic 1.9.0 . Can you update your issue with the newer version or attach a V1 Bug label?

sorry, was messed with environment, the code above is also reproducible with Pydantic 2.x:

```
             pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/kostunin/.local/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-5.14.0-1036-oem-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 typing_extensions-4.5.0
                       commit: unknown
{
  "properties": {
    "f": {
      "title": "F",
      "type": "integer"
    }
  },
  "required": [
    "f"
  ],
  "title": "ValidModel",
  "type": "object"
}
{
  "properties": {
    "f": {
      "required": true,
      "title": "F",
      "type": "integer"
    }
  },
  "required": [
    "f"
  ],
  "title": "InvalidModel",
  "type": "object"
}
Traceback (most recent call last):
  File "/tmp/2.py", line 17, in <module>
    jsonschema.validate(InvalidModel(f=1).dict(), InvalidModel.schema())
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 930, in validate
    cls.check_schema(schema)
  File "/usr/lib/python3/dist-packages/jsonschema/validators.py", line 294, in check_schema
    raise exceptions.SchemaError.create_from(error)
jsonschema.exceptions.SchemaError: True is not of type 'array'

Failed validating 'type' in metaschema['properties']['properties']['additionalProperties']['properties']['required']:
    {'default': [],
     'items': {'type': 'string'},
     'type': 'array',
     'uniqueItems': True}

On schema['properties']['f']['required']:
    True

```

**Comment by sydney-runkle** [comment]
@kostunin,

Thanks for your question. Indeed, you can pass additional metadata to the `Field` function which ends up getting added to `json_schema_extra` and being attached to the JSON schema.

I'd consider it a case of user error here - we don't support `required` as an argument of `Field`, so it's on the user to only specify extra info for the JSON schema that they're confident will result in a valid JSON schema. Pydantic interprets which fields are required or not, and adds that information to a valid JSON schema, as you've noted as well.

See this section of the migration guide re various ways to indicate that a field is required: https://docs.pydantic.dev/dev/migration/#required-optional-and-nullable-fields

Feel free to let me know if you have any follow up questions!

**Comment by kostunin** [comment]
Dear @sydney-runkle, thanks for the prompt reply!

> I'd consider it a case of user error here - we don't support `required` as an argument of `Field`, so it's on the user to only specify extra info for the JSON schema that they're confident will result in a valid JSON schema. Pydantic interprets which fields are required or not, and adds that information to a valid JSON schema, as you've noted as well.

I agree that it is an user error (and this problem was indeed discovered this way), however appearance of such errors can be limited, e.g. by adding additional flag for strict/non-strict schema production, so these errors could be caught on earlier stages (if not explicitly allowed for that).

It would be great if such option is considered for the future versions.

**Comment by sydney-runkle** [comment]
Hmm,

Revisiting this. I don't think it's a priority for us to validate the extra values passed to JSON schema. Closing for now, and happy to reopen in the future if there's significant demand / justification for implementing this.
