### ISSUE TITLE
TypeAdapter defer_build not working as expected

### ISSUE THREAD

**Issue by commonism** [pydantic/pydantic#8716]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm with the client side of OpenAPI, create models dynamically using create_model after parsing a OpenAPI description document.
Creating models dynamically requires delayed initialization, which works fine for BaseModel/RootModel.

Using TypeAdapter delayed initialization does not work.
I was hoping to skip a RootModels .root reference (for nullable objects) when using the TypeAdapter instead.

### Example Code

```Python
import logging
from typing import ForwardRef, Optional, List

from pydantic import BaseModel, RootModel, TypeAdapter, ConfigDict, create_model

PYC = ConfigDict(defer_build=True, arbitrary_types_allowed=True)

class A_(BaseModel):
    model_config = PYC
    a: str

class B_(BaseModel):
    model_config = PYC
    la: List[ForwardRef('__types["A"]')]

types = {"__types":{"A":A_, "B":B_}}
A_.model_rebuild(_types_namespace=types)
B_.model_rebuild(_types_namespace=types)

E = create_model("E", __base__=(RootModel[Optional[ForwardRef("__types['A']")]],), __module__="debugging")
E.model_rebuild(_types_namespace=types)

# edit - this is what I want to do with the TypeAdapter instead
# assert E.model_validate(None).root is None

# we fail here
try:
  D = TypeAdapter(Optional[ForwardRef("__types['A']")], config=PYC)
except Exception as e:
    logging.exception(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: ~/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
             related packages: mypy-1.5.1
```

**Comment by sydney-runkle** [comment]
@commonism,

Thanks for reporting this. Indeed, this looks like a bug. I suspect that a fix for this issue might look like that which I've implemented here for a similar issue: https://github.com/pydantic/pydantic/pull/7736.

Any interest in opening a PR with a fix?

**Comment by commonism** [comment]
I think we both initially expected this to work.
Not being able to embed TypeAdapters in Models limit my interest in this feature anyway.
Therefore I'm fine with not taking care of this, but would be great if TypeAdapter could raise something when getting ConfigDict parameters not supported. 
Breaking the expectation early.

**Comment by adriangb** [comment]
TypeAdapter was never meant to be a field of a model. You’re supposed to just use the model, or a generic, for that.

I’m also confused by the `__types` thing. In particular I feel like there shouldn’t be a `__types` key. Like your forward ref should just be `”A”` and namespace should be `{“A”: A_}`

**Comment by adriangb** [comment]
Also, we could add a `types_namespace` argument to `TypeAdapter` pretty easily, does that solve it?

**Comment by commonism** [comment]
I'd need TypeAdapter to behave "as models" basically as container for generics, which is not intended use.
I think I'm not a customer for TypeAdapter due to the limitations wrt. use as Field / missing "model_build" equivalent for deferred build and will be better of not trying to force it to be something it is/was not intended to be and use models/generics instead.

Using __types prevents name lookup collisions/confusion during construction.

**Comment by sydney-runkle** [comment]
@commonism,

Given that, I think we can mark this issue as not planned, given that the features you're requesting are supported for `BaseModel` types.

Thanks for your feedback. Happy coding!
