### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by withlone** [pydantic/pydantic#8723]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

https://docs.pydantic.dev/latest/concepts/validators/#field-validators
In the code of this part, search by "UserModel(name='John Doe', id=1)" and you will see there are two appearance in the code with different behavior, which the second appearance should be "UserModel(name='John Doe', id="abc")" according to the comment.

### Python, Pydantic & OS Version

```Text
document error
```

**Comment by samuelcolvin** [comment]
Yup, something weird is definitely going on there. Thanks for reporting.

The weird thing is that these outputs are auto generated.

Weird error output:

```py
try:
    UserModel(name='John Doe', id=1)
except ValidationError as e:
    print(e)
    """
    1 validation error for UserModel
    id
      Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='abc', input_type=str]
    """
```

I assume that's what you meant?

**Comment by sydney-runkle** [comment]
@withlone,

Good catch. I'll open a PR shortly with a fix.

**Comment by sydney-runkle** [comment]
Tracked the issue to here: https://github.com/pydantic/pydantic/commit/8540b44d2be3adc806752f1858694a3ab8202a40
