### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by maksym-petrenko** [pydantic/pydantic#8724]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Custom initialization via `__init__` with further usage of `super()` doesn't work. It looks like this isn't my local problem as I have encountered an error in the corresponding [documentation](https://docs.pydantic.dev/latest/concepts/models/#model-signature): 

It's the second block of code in the section "Model signature".

### Example Code

```Python
import inspect

from pydantic import BaseModel


class MyModel(BaseModel):
    id: int
    info: str = 'Foo'

    def __init__(self, id: int = 1, *, bar: str, **data) -> None:
        """My custom init!"""
        super().__init__(id=id, bar=bar, **data)


print(inspect.signature(MyModel))
#> (id: int = 1, *, bar: str, info: str = 'Foo') -> None
```

### Python, Pydantic & OS Version

```Text
pydantic version: v2.6.0, pydantic-core version: v2.16.1
```

**Comment by maksym-petrenko** [comment]
It appears to be a problem with `super` initialization on it's own, not `__init__` customization, as the following [code](https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes):

```
from datetime import datetime
from random import randint

from pydantic import BaseModel, PrivateAttr


class TimeAwareModel(BaseModel):
    _processed_at: datetime = PrivateAttr(default_factory=datetime.now)
    _secret_value: str

    def __init__(self, **data):
        super().__init__(**data)
        # this could also be done with default_factory
        self._secret_value = randint(1, 5)


m = TimeAwareModel()
print(m._processed_at)
#> 2032-01-02 03:04:05.000006
print(m._secret_value)
#> 3
```

also doesn't work.

By the way, can I contribute to this issue? If yes, could you please guide me a bit, as I don't even know where the related logic is located?

**Comment by maksym-petrenko** [comment]
Fortunately, it's not a librarie's error, but documentation only. Locally everything works fine and the error there is weird.

**Comment by sydney-runkle** [comment]
@maksym-petrenko,

Thanks for reporting this. Could you please describe in more detail the issue that you're having? Both examples that you sent seem to be running smoothly to me.

**Comment by maksym-petrenko** [comment]
Hi @sydney-runkle. As I've mentioned in the last comments, the code works fine locally. I had a problem with similar code, but with private attributes and went to the documentation. The interpreter on the website didn't work for similar case, but it was a different problem. Right now there's an error:

```
pydantic version: v2.6.1, pydantic-core version: v2.16.2
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 144, in _parse_and_compile_gen
    mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 11
    """My custom init!"""
IndentationError: expected an indented block after function definition on line 10
```

which has nothing to do with library itself.

**Comment by maksym-petrenko** [comment]
> I had a problem with similar code

I locally had problems with private attributes. As I found out later, it was only because of names of fields and I already solved this. Sorry for misunderstanding, but the initial issue statement appears to irrelevant.

**Comment by sydney-runkle** [comment]
@maksym-petrenko,

Ah, thanks for clarifying. I'm having that issue as well. Will dig into this - not sure what the problem is at a first glance.

**Comment by sydney-runkle** [comment]
I think this issue might belong on https://github.com/samuelcolvin/mkdocs-run-code

**Comment by maksym-petrenko** [comment]
@sydney-runkle 

I can change the issue description, but it also makes sense to close it as the problem is likely in another repo.
What should I do?

**Comment by sydney-runkle** [comment]
@maksym-petrenko,

I think it makes sense to open an issue on https://github.com/samuelcolvin/mkdocs-run-code, and you can link this issue as part of the description 👍

**Comment by sydney-runkle** [comment]
Also as a side note, this could be related: https://github.com/mkdocstrings/pytkdocs/issues/117. Or not, haven't looked in much depth.
