### ISSUE TITLE
Error on validating instance with generic class

### ISSUE THREAD

**Issue by aeisenbarth** [pydantic/pydantic#8728]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Given an instance that conforms to a generic class and its type variables, it fails validation if it has been instantiated from the plain class. Upon inspection in the debugger, all constraints seem to be fulfilled.

On one side one can argue the object is actually not an instance of the parametrized class, but if the generic is only seen as a hint (not creating a new class) itshould only depend on the value of the attributes that are marked with a type variable.

A use case is when you are given already instantiated objects and want to check whether they also conform to a stricter or specific parametrized model.

### Example Code

```Python
from typing import Generic, TypeVar
import pydantic


class B(BaseModel):
    pass


T = TypeVar("T")


class A(BaseModel, Generic[T]):
    b: T


a1 = A(b=B())
a2 = A[B](b=B())

assert isinstance(a2, A)
A.model_validate(a2)

assert isinstance(a2, A[B])
A[B].model_validate(a2)

assert isinstance(a1, A[B]) # Fails
A[B].model_validate(a1)     # Fails
# a1 is an instance of A where attribute b is an instance of B
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
        pydantic-core version: 2.16.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/user/software/miniconda3/envs/my-env/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
             related packages: mypy-1.8.0 typing_extensions-4.9.0 pydantic-settings-2.1.0 email-validator-2.1.0.post1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@aeisenbarth,

Thanks for your question. The behavior that you're observing is expected, but can be a bit confusing. Here's some code with inline explanations:

```py
from typing import Generic, TypeVar

from pydantic import BaseModel


class B(BaseModel):
    pass


T = TypeVar("T")


class A(BaseModel, Generic[T]):
    b: T


a1 = A(b=B())
a2 = A[B](b=B())

assert isinstance(a1, A)
A.model_validate(a1)

assert isinstance(a2, A[B])
A[B].model_validate(a2)

# this is expected to fail; Pydantic creats a new class for A[B], so it's
# true that a1 is an instance of A, but it's not an instance of A[B]
assert isinstance(a1, A[B])

# this is also expected to fail, for a similar reason as above
A[B].model_validate(a1)

# this succeeds - because a1 has the b attribute set to an instance of B, revalidating it as an instance of A[B] by looking
# at indiivdual attributes will succeed
A[B].model_validate(a1, from_attributes=True)
```

One relevant section of the docs is [here](https://docs.pydantic.dev/latest/concepts/models/#generic-models).

> While it may not raise an error, we strongly advise against using parametrized generics in isinstance checks.
For example, you should not do isinstance(my_model, MyGenericModel[int]). However, it is fine to do isinstance(my_model, MyGenericModel). (Note that, for standard generics, it would raise an error to do a subclass check with a parameterized generic.)
If you need to perform isinstance checks against parametrized generics, you can do this by subclassing the parametrized generic class. This looks like class MyIntModel(MyGenericModel[int]): ... and isinstance(my_model, MyIntModel).

Given this advice, I'd recommend only performing `isinstance` checks on subclasses as recommended in the last line.

**Comment by sydney-runkle** [comment]
I think you'll find that @dmontagu has given a more in-depth explanation of this issue in his comments here, if you'd like to learn more: https://github.com/pydantic/pydantic/issues/7815

**Comment by aeisenbarth** [comment]
Thank you!
I figured out that for now, I can ensure instantiation is only done from the parametrized class, not the generic class. `from_attributes` will be useful.
