### ISSUE TITLE
Type of `examples` parameter is not checked, which may lead to invalid JSON schema generation

### ISSUE THREAD

**Issue by kostunin** [pydantic/pydantic#8732]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

According to [JSON schema specification](https://json-schema.org/understanding-json-schema/reference/annotations), `examples` attribute has an array type, which is reflected in Pydantic type annotation of [Field parameter](https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.Field). However, we have discovered, that the type is not checked, which may lead to an invalid JSON schema generation (e.g. when non-array is passed).

Surprisingly, [`ajv-cli`](https://github.com/ajv-validator/ajv-cli) considers such schema as valid, but Python `jsonschema` raises an exception (below output of example code).

**Valid schema (generated by Pydantic)**

```json
{
  "properties": {
    "f": {
      "examples": [],
      "title": "F",
      "type": "integer"
    }
  },
  "required": [
    "f"
  ],
  "title": "ValidModel",
  "type": "object"
}
```

**Invalid schema (generated by Pydantic)**

```json
{
  "properties": {
    "f": {
      "examples": {},
      "title": "F",
      "type": "integer"
    }
  },
  "required": [
    "f"
  ],
  "title": "InvalidModel",
  "type": "object"
}
```

**Exception message:**

```
{} is not of type 'array'

Failed validating 'type' in metaschema['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][4]['properties']['examples']:
    {'items': True, 'type': 'array'}

On schema['properties']['f']['examples']:
    {}
```

### Example Code

```Python
import pydantic
import jsonschema


class ValidModel(pydantic.BaseModel):
    f: int = pydantic.Field(..., examples=[])


class InvalidModel(pydantic.BaseModel):
    f: int = pydantic.Field(..., examples={})


print(pydantic.version.version_info())
print(ValidModel.schema_json(indent=2))
print(InvalidModel.schema_json(indent=2))

try:
    jsonschema.validate(InvalidModel(f=1).dict(), InvalidModel.schema())
except jsonschema.exceptions.SchemaError as e:
    print(e)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /tmp/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
                     platform: Linux-6.5.0-15-generic-x86_64-with-glibc2.38
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@kostunin,

I think this falls under the same umbrella as https://github.com/pydantic/pydantic/issues/8714.

That is, `pydantic` doesn't enforce the types of some of the json schema arguments at the moment. Doing so might be a breaking change for some users. Going to close this as not planned for now, but will also tag with a V3 label as something we could revisit down the line.

One potential option would be to add a config flag supporting stricter type checking on json-schema related field attributes, set that to false by default, and raise warnings / errors when that flag is enabled and strict json schema specifications are violated.

**Comment by sydney-runkle** [comment]
@kostunin,

I think this falls under the same umbrella as https://github.com/pydantic/pydantic/issues/8714.

That is, `pydantic` doesn't enforce the types of some of the json schema arguments at the moment. Doing so might be a breaking change for some users. Will also tag with a V3 label as something we could revisit down the line.

One potential option would be to add a config flag supporting stricter type checking on json-schema related field attributes, set that to false by default, and raise warnings / errors when that flag is enabled and strict json schema specifications are violated.

It'd also be valuable to see higher-demand from the community for support along these lines 👍.

**Comment by Viicos** [comment]
https://github.com/pydantic/pydantic/pull/10181 deprecated passing examples as a dict and added support for passing examples as a list. Marking the issue as closed, but I will create a separate issue regarding runtime validation of JSON Schemas.

**Comment by sydney-runkle** [comment]
Nice work @Viicos!
