### ISSUE TITLE
Known 2.6 Issues - WIP Fixes for `v2.6.2`

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#8741]
- [ ] https://github.com/pydantic/pydantic/issues/8729
- [ ] https://github.com/pydantic/pydantic/issues/8736

**Comment by HenriBlacksmith** [comment]
I am not sure wether there is already an Issue on this repo for this one, but it was reported on `mypy` side and I am facing a similar issue: https://github.com/python/mypy/issues/16858

**Comment by HenriBlacksmith** [comment]
Actually, it seems it was fixed in 2.6.1 by https://github.com/pydantic/pydantic/pull/8666, I will check in detail

**Comment by sydney-runkle** [comment]
@HenriBlacksmith,

We're following up on #8666 with https://github.com/pydantic/pydantic/issues/8729, just fyi!

**Comment by sydney-runkle** [comment]
Closing this in favor of a small milestone :).
