### ISSUE TITLE
Type error on initialization of classes derived from RootModel 

### ISSUE THREAD

**Issue by WarpedPixel** [pydantic/pydantic#8745]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`RootModel` classes should be able to take one argument of the root model type and initialize it that way. From [the docs](https://docs.pydantic.dev/2.5/concepts/models/#rootmodel-and-custom-root-types): "The root value can be passed to the model __init__ or model_validate via the first and only argument." 
Attempting to initialize a `FancyID` in the example with a simple string reports "expected 0 positional arguments". 

Note that the code works in all cases, however the type system (Pylance in this case) does not understand it correctly. Moreover, workarounds like the one in `HackyID` below, or only initializing `FancyID` with `model_validate()` also work.

In the example SimpleID and HackyID work and report nothing wrong, and FancyID also works but reports "Expected 0 positional arguments Pylance(reportGeneralTypeIssues)".

### Example Code

```Python
from pydantic import RootModel

SimpleID = RootModel[str]

class FancyID(RootModel[str]):
    def __str__(self) -> str:
        return self.root

class HackyID(RootModel[str]):
    def __init__(self, root: str):
        super().__init__(root=root)

    def __str__(self) -> str:
        return self.root

# from https://docs.pydantic.dev/2.5/concepts/models/#rootmodel-and-custom-root-types
# "The root value can be passed to the model __init__ or model_validate via the first and only argument."
foo = SimpleID('foo')
bar = FancyID('bar')    # Expected 0 positional arguments Pylance(reportGeneralTypeIssues)
hack = HackyID('hack')

print(foo)
print(bar)
print(hack)
assert str(bar) == 'bar'  # works just fine
assert str(hack) == 'hack'

bar = FancyID.model_validate('bar') # no type errors
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /Users/xxx/Library/Caches/pypoetry/virtualenvs/companion-mgXvcyvA-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-13.6.1-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 pydantic-extra-types-2.2.0 fastapi-0.108.0 pydantic-settings-2.1.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
@WarpedPixel,

Thanks for reporting this. Looks like we fixed this issue for the `mypy` case here: https://github.com/pydantic/pydantic/pull/7677.

@Viicos, any idea what we might be able to do here for a fix? I know you did some work recently with the dataclass_transform logic that might be relevant. Not sure if this is easily fixable, though.

**Comment by Viicos** [comment]
@WarpedPixel you are still on 2.5.x, where a positional argument to a `RootModel` was not allowed. https://github.com/pydantic/pydantic/pull/7677 fixed for mypy but for pyright as well. This is a [MRE](https://pyright-play.net/?pyrightVersion=1.1.350&pythonVersion=3.13&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDiApikSEgMYA0UAKokQGoCGINAJszMxQDbMBnAQH0YIZigHBcEAFCzaUALx0GLEAAoARLS0BKebIACnbn0EixEqTI0BrAO7CwKXnGHsiwZgFdeMJVoQHyIDcyEoAFkwT15IojN%2BIQ14BFCALlkobKgEC3lwgSgAIUEiaNiNCASeJIElCqI4msK9TJzc-PkTLlqLUXFJaRAIeycXNw8vX38lADFmXgFQ2UKoYQAlMDAYRubEiw09%2BIOhNqycvKFDNa2dvY1S5b2aYlJyCgBtWgBdGmrTvVNttdjEmic%2Bmd2jlwDt0nR5B1PMB1sJUEgYMJhBplrxgDQAPQ0WEweGKFQAORcRBoACpaaZmHooABaAB8UCppHhUAAxLAGPCkGgULgiBcOtkrgIbnUoAsUBQ4ABJAAiGjuoNinwEYh%2B5w60vkCqVau0%2BnkQA) for pyright, showing it is working fine.

Updating to 2.6 should solve the issue.

**Comment by WarpedPixel** [comment]
You are correct of course. Just verified with 2.6.1 and it works as expected.
