### ISSUE TITLE
`__getstate__` implementation assumes existence of `__pydanitc_private__` and `__pydantic_extra__`. 

### ISSUE THREAD

**Issue by nwilson314** [pydantic/pydantic#8758]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a use case where we are retrieving `SqlModel` instances from our databases and occasionally caching to minimize database hits. During the caching process, we are pickling the database results. However, as a byproduct of pickling the `__getstate__` method is called but the `__pydantic_private__` and `__pydantic_extra__` attributes do not exist on the model. 

This may ultimately be a problem with `SqlModel` and how it retrieves models, but I was curious if we actually _should_ be assuming that these attributes exist?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: 
.venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.5.2-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.108.0 pydantic-extra-types-2.5.0 pydantic-settings-2.1.0 mypy-0.942 email-validator-2.1.0.post1
                       commit: unknown
```

**Comment by volfpeter** [comment]
I believe this is definitely an `SQLModel` issue, it can be reproduced very simply, see [this test case](https://github.com/volfpeter/sqlmodelservice/blob/3a2fe7a9345b5fb3e6541acba0a26af5fafa27d1/tests/test_service.py#L75).

**Comment by volfpeter** [comment]
Here's my comment in an SQLModel discussion with a very minimal example that reproduces the bug: https://github.com/tiangolo/sqlmodel/discussions/761#discussioncomment-8418667

**Comment by nwilson314** [comment]
> Here's my comment in an SQLModel discussion with a very minimal example that reproduces the bug: [tiangolo/sqlmodel#761 (comment)](https://github.com/tiangolo/sqlmodel/discussions/761#discussioncomment-8418667)

Thank you @volfpeter. I should have included more specific information regarding the error. It does indeed seem to be an `SQLModel` issue. I will follow the thread you have linked.
