### ISSUE TITLE
Date string coerced to datetime infers timezone

### ISSUE THREAD

**Issue by davidhewitt** [pydantic/pydantic#8762]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Split from https://github.com/pydantic/pydantic/issues/8736#issuecomment-1931041611

Coercion of date strings to midnight datetimes, new in v2.6, infers a UTC timezone.

This is inconsistent with coercion of datetime strings to datetimes, which do not infer a timezone; they only add one when explicitly given.

I believe quite strongly that timezone should _not_ be inferred here, and this is a bug in the new date-to-midnight coercion.

### Example Code

```Python
from pydantic import TypeAdapter
from datetime import datetime

print(repr(TypeAdapter(datetime).validate_python("2021-01-01").tzinfo))
#> TzInfo(UTC)  # <-- this should be None to be consistent with the case below

print(repr(TypeAdapter(datetime).validate_python("2021-01-01T00:00:00").tzinfo))
#> None

print(repr(TypeAdapter(datetime).validate_python("2021-01-01T00:00:00Z").tzinfo))
#> TzInfo(UTC)

print(repr(TypeAdapter(datetime).validate_python("2021-01-01T00:00:00+01:00").tzinfo))
#> TzInfo(+01:00)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/david/.virtualenvs/pydantic-prod/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.38
             related packages: mypy-1.4.1 pydantic-settings-2.1.0 email-validator-2.0.0.post2 pyright-1.1.316 typing_extensions-4.6.3
                       commit: unknown
```

**Comment by Kxnr** [comment]
@davidhewitt Thanks for opening a new issue, Re: your comment on the previous issue:

> For what it's worth, Kxnr you can use pydantic.AwareDatetime to require a timezone instead of your own AfterValidator, might be a touch more efficient.

Thanks for the suggestion, we could likely use that and see some benefit. Our current solution is a quick port of a validator implemented for `v1` that also imposes additional constraints so I'm sure there are new features we could make better use of.

**Comment by eseglem** [comment]
This also came up for me with `AwareDatetime`. Seems related to both these issues, but it feels closer to this one.

```python
TypeAdapter(AwareDatetime).validate_python("2020-01-01")
# datetime.datetime(2020, 1, 1, 0, 0, tzinfo=TzInfo(UTC))
```

I mostly care about it not being aware, but it is also not a datetime.

**Comment by davidhewitt** [comment]
@eseglem that is absolutely 100% this same bug and yes it's hopefully to be fixed soon!

**Comment by sydney-runkle** [comment]
I'll see if I can get around to a fix for this tomorrow :).
