### ISSUE TITLE
AttributeError: '__pydantic_private__'

### ISSUE THREAD

**Issue by JonathanBrenner** [pydantic/pydantic#8778]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a quart app where I'm trying to use quart_auth (https://quart-auth.readthedocs.io/en/latest/index.html) and Beanie as my ODM (https://beanie-odm.dev/). Beanie relies on pydantic's BaseModel for it's Document class. I'm trying to create a user class that subclasses both AuthUser from quart_auth and the Document class from Beanie.

My code
```
from beanie import Document
from quart_auth import AuthUser, QuartAuth

class User(AuthUser, Document):
    discord_id: str

auth = QuartAuth()
auth.user_class = User
```

I'm seeing this error when trying to render a template from my base route.

```
  File ".../lib/python3.11/site-packages/quart_auth/extension.py", line 61, in __init__
    self._auth_id = auth_id
    ^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/main.py", line 776, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/pydantic/main.py", line 764, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
```

Any fixes or workarounds here? I need the functionality from both libraries for my user class. I've looked into moving the Document class into the User class as an attribute, but that does not work because I need to be able to get the Document class from the AuthUser when calling `quart_auth.current_user()` and I need to get the AuthUser class from the Document class when loading the user document from the database.

It looks like this closed issue is similar if that is at all helpful https://github.com/pydantic/pydantic/issues/7855

### Example Code

```Python
from beanie import Document
from quart_auth import AuthUser, QuartAuth


class User(AuthUser, Document):
    discord_id: str


user = User(1)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.0
pydantic-core version: 2.16.1
pydantic-core build: profile=release pgo=false
install path: /Users/jonathanbrenner/.pyenv/versions/3.11.2/envs/gamenight/lib/python3.11/site-packages/pydantic
python version: 3.11.2 (main, Feb 23 2023, 16:48:29) [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-14.2.1-x86_64-i386-64bit
related packages: typing_extensions-4.9.0 mypy-1.8.0
commit: unknown
```

**Comment by lmmx** [comment]
It looks like your traceback got modified when you sent it

```py
    if self.pydantic_private is None or name not in self.private_attributes:
```

That isn't in the Pydantic source code but this is

```py
                if self.__pydantic_private__ is None or name not in self.__private_attributes__:
```

If your terminal has removed underscores (perhaps using them as bold formatting!) that would be problematic for this bug report, because it would be hiding which were the private attributes.

**Comment by JonathanBrenner** [comment]
@lmmx Thank you for noticing that, I updated the traceback without the missing underscores! I think I copy and pasted it a couple times and somewhere along the way the underscores were removed somehow.

**Comment by JonathanBrenner** [comment]
> The details of those libraries are unclear to me but my impression is:
> 
>     * You are subclassing a Pydantic model
> 
>     * You are doing multiple inheritance with a non-Pydantic model class (`QuartAuth`)
> 
>     * The non-Pydantic model base class `QuartAuth` has a private attribute `_auth_id`
> 
>     * Private attributes must be declared with `PrivateAttr()` - [reference](https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.PrivateAttr) + [usage docs](https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes)
> 
> 
> Therefore you're seeing this error because `_auth_id` is being accessed but Pydantic won't let you do that (fields cannot begin with an underscore unless explicitly declared as private attributes upfront in this way).

@lmmx Thank you for help! These assumptions are all correct. I tried declaring `_auth_id` as a private attribute on my User class but that results in the same error. Do you have any suggestions?
```
from typing import Optional

from beanie import Document
from pydantic import PrivateAttr
from quart_auth import AuthUser, QuartAuth


class User(AuthUser, Document):
    _auth_id: Optional[str] = PrivateAttr()
    discord_id: str


user = User(1)

```

**Comment by lmmx** [comment]
I think your problem now is that you have 2 base classes but are presumably not initialising both... You definitely want to initialise the Pydantic model or you're not going to get that `PrivateAttr` set up correctly.

Er, you might solve this by manually `__init__`ing like the docs do. The fact you didn't get an error even trying to do this suggest to me it's possible but I'm not certain.

I find it pretty unorthodox to initialise a non-Pydantic model via multiple inheritance like this.

I would just let the other class be a private attribute too (or else I'd go on [grep.app](https://grep.app) and look for examples which do what you're doing).

I'd guess that you do this by

```py
from typing import Optional

from beanie import Document
from pydantic import PrivateAttr
from quart_auth import AuthUser, QuartAuth


class User(Document):
    _auth_id: Optional[str] = PrivateAttr()
    _user: AuthUser = PrivateAttr()
    discord_id: str

    def __init__(self, *args, **kwargs):
        auth_id = kwargs.get("auth_id")
        super().__init__(*args, **kwargs)
        self._auth_id = auth_id


user = User(discord_id="foo")
```

This doesn't work though, it gives a Beanie error (I'm not familiar with the library)

```
Traceback (most recent call last):
  File "/home/louis/lab/beanie/repro.py", line 19, in <module>
    user = User(discord_id="foo")
  File "/home/louis/lab/beanie/repro.py", line 15, in __init__
    super().__init__(*args, **kwargs)
  File "/home/louis/miniconda3/envs/jbrenner_repro/lib/python3.10/site-packages/beanie/odm/documents.py", line 189, in __init__
    self.get_motor_collection()
  File "/home/louis/miniconda3/envs/jbrenner_repro/lib/python3.10/site-packages/beanie/odm/interfaces/getters.py", line 16, in get_motor_collection
    return cls.get_settings().motor_collection
  File "/home/louis/miniconda3/envs/jbrenner_repro/lib/python3.10/site-packages/beanie/odm/documents.py", line 1084, in get_settings
    raise CollectionWasNotInitialized
beanie.exceptions.CollectionWasNotInitialized
```

This is downstream of `beanie` though so refer to I think you should refer to Beanie's docs now.

**Comment by JonathanBrenner** [comment]
I found a solution where instead of multiple inheritance I added the `Document` class as an attribute on my `AuthUser` subclass. I can see now that my original code is an odd pattern and am happy with my solution.
