### ISSUE TITLE
Support stateful usage of GenerateJsonSchema

### ISSUE THREAD

**Issue by RobertCraigie** [pydantic/pydantic#8798]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hi! I want to use `TypeAdapter` to generate a json schema for function arguments which works almost perfectly minus support for parsing function docstrings to extract descriptions for individual arguments.

So to implement this myself I can subclass `GenerateJsonSchema` and override `kw_arguments_schema` (and eventually others) but because I want to modify the json schema based off of information that's not contained directly within the pydantic core schema, I can't actually access that, without a hack using a global variable or such.

Note that I can achieve what I want at runtime by hacking in a `__call__` method but this is a hack

<details>
<summary>Example</summary>

```py
class GenerateJsonSchemaWithArgDescriptions(GenerateJsonSchema):
    def __init__(self, *, func: ToolFunc) -> None:
        super().__init__()
        self._func = func

    def __call__(self, *_args: Any, **_kwds: Any) -> Self:
        return self

adapter = ...
adapter.json_schema(schema_generator=GenerateJsonSchemaWithArgDescriptions(func=func))
```

</details>

So would it be possible to support passing an instance of `GenerateJsonSchema` as well as the class type itself? e.g.

```py
@overload
def json_schema(
    self,
    *,
    schema_generator: GenerateJsonSchema,
    mode: JsonSchemaMode = 'validation',
) -> dict[str, Any]:
    ...

@overload
def json_schema(
    self,
    *,
    by_alias: bool = True,
    ref_template: str = DEFAULT_REF_TEMPLATE,
    schema_generator: type[GenerateJsonSchema] = GenerateJsonSchema,
    mode: JsonSchemaMode = 'validation',
) -> dict[str, Any]:
    ...

def json_schema(
    self,
    *,
    by_alias: bool = True,
    ref_template: str = DEFAULT_REF_TEMPLATE,
    schema_generator: GenerateJsonSchema | type[GenerateJsonSchema] = GenerateJsonSchema,
    mode: JsonSchemaMode = 'validation',
) -> dict[str, Any]:
    schema_generator_instance = schema_generator if isinstance(schema_generator, GenerateJsonSchema) else schema_generator(by_alias=by_alias, ref_template=ref_template)
```

Or is there another way this problem should be approached that I've missed?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@RobertCraigie,

Is the relevant information that you need accessible if you use the `__get_pydantic_json_schema__` approach instead? https://docs.pydantic.dev/latest/concepts/json_schema/#implementing-__get_pydantic_json_schema__

**Comment by RobertCraigie** [comment]
@sydney-runkle I don't think so...

Sorry I should've included a more complete example:

```py
def get_nickname(location: str) -> str:
    """Get the nickname of a city

    Args:
        location: The full formed name of the location, spaces allowed.
    """

adapter = TypeAdapter(get_nickname)
adapter.json_schema(schema_generator=GenerateJsonSchemaWithArgDescriptions(func=get_nickname))
# outputs
{
  "type": "function",
  "function": {
    "name": "get_nickname",
    "description": "Get the nickname of a city\n\n    Args:\n        location: The full formed name of the location, spaces allowed.\n    ",
    "parameters": {
      "additionalProperties": False,
      "properties": {
        "location": {
          "description": "The full formed name of the location, spaces allowed.",
          "title": "Location",
          "type": "string"
        }
      },
      "required": [
        "location"
      ],
      "type": "object"
    }
  }
}
```

Unless I'm missing something I don't see where `__get_pydantic_json_schema__` could be implemented here?

**Comment by sydney-runkle** [comment]
@RobertCraigie,

Would something like this work?

```py
from pprint import pprint

from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema

def get_nickname(location: str) -> str:
    """Get the nickname of a city

    Args:
        location: The full formed name of the location, spaces allowed.
    """

class MyGenerateJsonSchema(GenerateJsonSchema):
    def generate(self, schema, mode='validation'):
        json_schema = super().generate(schema, mode=mode)
        doc = schema.get('function').__doc__
        json_schema['description'] = doc
        # whatever other processing you want to do with the docstring
        # to attach to arguments, etc...
        return json_schema

adapter = TypeAdapter(get_nickname)
pprint(adapter.json_schema(schema_generator=MyGenerateJsonSchema))
"""
{'additionalProperties': False,
 'description': 'Get the nickname of a city\n'
                '\n'
                '    Args:\n'
                '        location: The full formed name of the location, '
                'spaces allowed.\n'
                '    ',
 'properties': {'location': {'title': 'Location', 'type': 'string'}},
 'required': ['location'],
 'type': 'object'}
"""
```

**Comment by sydney-runkle** [comment]
Marking this as resolved for now, as I think you should be able to get whatever info you need about the function from the `schema` variable, as that has the core schema info, not just the json schema, as shown above. Feel free to ping me if you have any follow up questions!
