### ISSUE TITLE
Union type: No parameter named "extra" for `Field` (type hints, `TypeAdapter` / `Annotated`)

### ISSUE THREAD

**Issue by carol0801** [pydantic/pydantic#8813]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Currently static type checkers like mypy emit a type error, when using [`extra="forbid"`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra) to validate and properly resolve smart union types via `TypeAdapter` + `Annotated`. Otherwise this feature already works functionally, hence a fix could look similar to:
```python
def Field(
    ...
    extra: Literal["allow", "forbid", "ignore"] | None = _Unset,
    ...
```

### Example Code

```Python
from dataclasses import dataclass
from typing import Annotated

from pydantic import Field, TypeAdapter


@dataclass
class Foo:
    p1: list[str]


@dataclass
class Bar:
    p1: list[str]
    p2: int


## triggers 'No parameter named "extra"'
MyUnion = Annotated[Foo | Bar, Field(extra="forbid")]

## ... but works functionally:
## (variable) out: Bar | Foo
out = TypeAdapter(MyUnion).validate_python(Bar(p1=["a", "b"], p2=42))


## In contrast this wouldn't resolve properly:
## (variable) out: UnionType
# MyUnion = Foo | Bar
# out = TypeAdapter(MyUnion).validate_python(Bar(p1=["a", "b"], p2=42))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
pydantic-core version: 2.16.2
pydantic-core build: profile=release pgo=true
python version: 3.11.7
related packages: typing_extensions-4.9.0
commit: unknown
```

**Comment by sydney-runkle** [comment]
@carol0801,

I'm a bit confused about your report here - is this a feature request, or a bug report? We don't currently support `extra` specifications on a per-field basis. You can add an `extra` specification on a model via `ConfigDict`.

Perhaps what you're looking for is using a `RootModel`, see more docs here: https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types.

Going to close this as not planned for now, but happy to iterate more on what you're looking for / expecting here.

**Comment by carol0801** [comment]
Hi @sydney-runkle , thanks for the quick response.

> is this a feature request, or a bug report?

Let me try to answer this way: My original goal was being able to parse [smart unions](https://docs.pydantic.dev/latest/concepts/unions/#smart-mode) with `TypeAdapter` similar to [how discriminated unions are handled](https://github.com/pydantic/pydantic/discussions/4950#discussioncomment-6462134). Latter uses `discriminator=...` in combination with `Field`:
```python
...
Shape = Union[Square | Cube]
AnnotatedShape = Annotated[Shape, Field(discriminator="type")]
...
shape_adapter: TypeAdapter[Shape] = TypeAdapter(AnnotatedShape)
assert shape_adapter.validate_python(square_json) == square
```
Discriminators are not used in OP example. Instead https://github.com/pydantic/pydantic/issues/7223#issuecomment-1690623756 suggests to use `extra = 'forbid'` in the model config for non-tagged union types here. But I cannot use `BaseModel`, as types are external and not under my control. `TypeAdapter` would be the go-to solution given these requirements, hence my intention was to combine `extra=forbid` with `TypeAdapter`. 

And fortunately, type hints are already resolved properly (my environment uses pyright for static type checking). You can try it out and copy/paste OP example - including `extra` in `Field` results in `Bar | Foo` as expected. Otherwise this union isn't properly resolved and gets a wide `UnionType`. 

All in all it let me assume,  this feature would already exist and is just missing a type hint declaration for `extra` within the `Field` member. Marking it as bug report would then appropriate, please correct me otherwise. You're right this was trial and error and inferring from [the Field member](https://github.com/pydantic/pydantic/blob/332eac4/pydantic/fields.py#L632-L666) and I wasn't able to find documentation.

> Perhaps what you're looking for is using a RootModel, see more docs here: https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types.

I don't think, this would get the job done. My requirement is parsing/resolving non-tagged union types properly with `TypeAdapter`.

**Comment by Viicos** [comment]
@carol0801:

```python
out = TypeAdapter(MyUnion).validate_python(Bar(p1=["a", "b"], p2="hello"))
```

doesn't raise an error as `Bar` is already constructed (and because it is a stdlib dataclass, no validaton error was raised when doing so). Pydantic applies a simple `isinstance` validation check in this case I believe.
