### ISSUE TITLE
Unable to parse Unix Timestamp

### ISSUE THREAD

**Issue by FyZzyss** [pydantic/pydantic#8828]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Unable to parse unix timestamp to datetime. 

Pydantic v1 can handle it

### Example Code

```Python
from datetime import datetime

from pydantic import BaseModel


class UserReactionSchema(BaseModel):
    ts: datetime

print(UserReactionSchema(ts=1708008041006122940))  # should be datetime.datetime(2024, 2, 15, 14, 40, 41, 6123, tzinfo=datetime.timezone.utc)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3 (I also tried 2.6.1)
pydantic-core version: 2.14.6
pydantic-core build: profile=release pgo=true
python version: 3.10.12 (main, Jul 11 2023, 13:10:57) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.4.1-arm64-arm-64bit
related packages: typing_extensions-4.9.0 fastapi-0.109.0 mypy-1.8.0 pydantic-settings-2.1.0
```

**Comment by sydney-runkle** [comment]
Hi @FyZzyss,

Thanks for reporting this. See this issue for a more in depth conversation on the matter: https://github.com/pydantic/pydantic/issues/7940.

This section of the docs explains how `pydantic` infers whether to interpret a unix timestamp in s or ms: https://docs.pydantic.dev/latest/api/standard_library_types/#datetimedatetime

In your case, you can use an approach similar to this one to get the desired result: https://github.com/pydantic/pydantic/issues/7940#issue-1965428360.

Closing this as a duplicate for now.
