### ISSUE TITLE
Can't define a field as optional without Optional. Makes for a messy API doc.

### ISSUE THREAD

**Issue by shufflebits** [pydantic/pydantic#8829]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When you want a field that is optional, you can just use
`f1: str = None`
This will simply remove `f1` from the `required` list in the schema.
However, Mypy will complain that you are initialising a non-Optional value with None.
```
error: Incompatible types in assignment (expression has type "None", variable has type "str")  [assignment]
```

So, you make the declaration
`f1: Optional[str] = None`
Now you get an ugly `anyOf` between the type and `null`, which is hard to read.

So can we have a way to stop *type* | None being rendered using `anyOf`, and return to the 1.10 behaviour of using `required` always?

Output from the code for `optional_val` is
```
    "optional_val": {
      "default": null,
      "title": "Optional Val",
      "type": "string"
    },
```

For `optional_mypy_val we get
```
    "optional_mypy_val": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Optional Mypy Val"
    }
```

### Example Code

```Python
from typing import Optional
import json

from pydantic import BaseModel


class OptionalTest(BaseModel):
    mandatory_val: str
    optional_val: str = None
    optional_mypy_val: Optional[str] = None


print(json.dumps(OptionalTest.model_json_schema(), indent=2))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/hclark/Documents/DB-Import-LC/LC-format/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
                     platform: Linux-6.5.0-17-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0 mypy-1.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
This question was answered here: https://github.com/pydantic/pydantic/issues/7161.

Marking this as a duplicate + closing for now 👍.

**Comment by SovereignRemedy** [comment]
> This question was answered here: #7161.这个问题在这里得到了回答： #7161 。
> 
> Marking this as a duplicate + closing for now 👍.将此标记为重复+暂时关闭👍。

Whether pydantic v2 supports “s1:str = None” means not required but the default value is empty
