### ISSUE TITLE
Different validation error when using Literal of enums 

### ISSUE THREAD

**Issue by kamilglod** [pydantic/pydantic#8836]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using Enum as request body parameter (RequestBody) and passing invalid value I'm getting correct error with list of allowed values:
```
curl -X 'POST' \
               'http://localhost:8000/v4/example' \
               -H 'accept: application/json' \
               -H 'Content-Type: application/json' \
               -d '{
           "value": "aaaa"
         }' | jq
{
  "detail": [
    {
      "type": "enum",
      "loc": [
        "body",
        "value"
      ],
      "msg": "Input should be 'foo', 'bar' or 'baz'",
      "input": "aaaa",
      "ctx": {
        "expected": "'foo', 'bar' or 'baz'"
      }
    }
  ]
}
```
however, when I'm using Literal (RequestBody2) to limit the enum to some subset of values I'm getting:
```
curl -X 'POST' \
               'http://localhost:8000/v4/example' \
               -H 'accept: application/json' \
               -H 'Content-Type: application/json' \
               -d '{
           "value": "aaaa"
         }' | jq
{
  "detail": [
    {
      "type": "literal_error",
      "loc": [
        "body",
        "value"
      ],
      "msg": "Input should be <ExampleEnum.foo: 'foo'>, <ExampleEnum.bar: 'bar'> or <ExampleEnum.baz: 'baz'>",
      "input": "aaaa",
      "ctx": {
        "expected": "<ExampleEnum.foo: 'foo'>, <ExampleEnum.bar: 'bar'> or <ExampleEnum.baz: 'baz'>"
      },
      "url": "https://errors.pydantic.dev/2.6/v/literal_error"
    }
  ]
}
```
so it's strigified version of enum values. 

### Example Code

```Python
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel


class ExampleEnum(StrEnum):
    foo = "foo"
    bar = "bar"
    baz = "baz"


class RequestBody(BaseModel):
    value: ExampleEnum


class RequestBody2(BaseModel):
    value: Literal[ExampleEnum.foo, ExampleEnum.bar, ExampleEnum.baz]


@router.post("/example")
async def example_endpoint(body: RequestBody):
    return {"status": "ok"}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.4.2
        pydantic-core version: 2.10.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/kamil.glod/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep  8 2023, 09:38:47) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.3-arm64-arm-64bit
             related packages: typing_extensions-4.8.0 fastapi-0.103.2 mypy-1.7.0
```
```

**Comment by sydney-runkle** [comment]
@kamilglod,

I'm not entirely convinced that this is incorrect - could you please share what you think the output should be for the second case? Thanks!

**Comment by kamilglod** [comment]
@sydney-runkle I will expect to get the same error message as when using enum itself: 
```     
 "msg": "Input should be 'foo', 'bar' or 'baz'",
```
alternatively have an option to override the default message (or template) in an easy way.

**Comment by sydney-runkle** [comment]
@kamilglod,

I think it's correct here that the error message is different, though I can see your argument for otherwise. We have an issue open in `pydantic-core` to move `Enum` validation to rust, and we might be able to modify the error messages there when we do that: https://github.com/pydantic/pydantic-core/issues/1161.

As for a solution that works currently, you can create a custom error handler to modify error messages, as shown in these docs: https://docs.pydantic.dev/latest/errors/errors/.

Going to mark this as resolved for now, but feel free to keep track of the `pydantic-core` issue I mentioned above, which may or may not result in changes to the error messages for enums.

Happy coding!
