### ISSUE TITLE
Why does pydantic call a root validator when a field validator has already failed?

### ISSUE THREAD

**Issue by Felix-neko** [pydantic/pydantic#8844]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I have a complicated settings class made with `pydantic` (v. 1.10): a `BaseModel`-inherited class whose fields are also `BaseModel`-inherited classes.

I have root validators for both main settings class and its fields.

At first, root validators for fields should be called. After that (and only if the fields' root validators did not fail) the main settings class's root validator should be called.

And after that I have noticed that main settings class root validator is called even in case when the field validator has already failed.

How can I avoid calling of my main root validator when field's root validator has failed?

### Example Code

```Python
Here's a simple example:


from typing import Any, Dict, Optional

from pydantic import BaseModel, root_validator


class TableSettings(BaseModel):
    full_name: Optional[str] = None
    short_name: Optional[str] = None

    @root_validator(pre=True, skip_on_failure=False)
    def _check_name(cls, vals_dict):
        print("Checking a field: it will crash...")
        if "full_name" not in vals_dict and "short_name" not in vals_dict:
            raise ValueError("Either full_name or short_name should be set!")


class EtlSettings(BaseModel):
    table_settings: Dict[str, TableSettings]

    extra_options: Dict[str, Any] = {}

    @root_validator(pre=False)
    def _do_not_call_me_if_src_settings_are_invalid(cls, vals_dict):
        print("This validator should never be called in case of the fields have invalid data!!!!")
        print(vals_dict)

        # Here will be crash, that should be avoided because this validator should be callled
        # only if the fields are validated!
        print(vals_dict["table_settings"])


if __name__ == "__main__":
    raw_dict = {"table_settings": {"valid_table": {}}}  # It should crash on field's root validator
    
    
    etl_settings = EtlSettings(**raw_dict)
    # It crashes on field's root validator but root main validator is called too. WHY???
```

Here's what it prints:
```
Checking a field: it will crash...
This validator should never be called in case of the fields have invalid data!!!!
{'extra_options': {}}
Traceback (most recent call last):
  File "/home/felix/Projects/alfabank/fs_etl/fs_etl/mega_validation_fuss.py", line 31, in <module>
    etl_settings = EtlSettings(**raw_dict)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/home/felix/Projects/alfabank/fs_etl/fs_etl/mega_validation_fuss.py", line 26, in _do_not_call_me_if_src_settings_are_invalid
    print(vals_dict["table_settings"])
KeyError: 'table_settings'
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.11
            pydantic compiled: True
                 install path: /home/felix/Projects/alfabank/fs_etl/venv_py3.7/lib/python3.7/site-packages/pydantic
               python version: 3.7.17 (default, Jun  6 2023, 20:10:09)  [GCC 11.3.0]
                     platform: Linux-6.5.0-15-generic-x86_64-with-Ubuntu-22.04-jammy
     optional deps. installed: ['devtools', 'dotenv', 'email-validator', 'typing-extensions
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@Felix-neko,

Thanks for the reproducible + well explained example. You can achieve the behavior you're looking for by setting `skip_on_failure` to `True` for the `EtlSettings` `root_validator`. See the example below:

```py
from typing import Any, Dict, Optional

from pydantic.v1 import BaseModel, root_validator


class TableSettings(BaseModel):
    full_name: Optional[str] = None
    short_name: Optional[str] = None

    @root_validator(pre=True, skip_on_failure=False)
    def _check_name(cls, vals_dict):
        print("Checking a field: it will crash...")
        if "full_name" not in vals_dict and "short_name" not in vals_dict:
            raise ValueError("Either full_name or short_name should be set!")


class EtlSettings(BaseModel):
    table_settings: Dict[str, TableSettings]

    extra_options: Dict[str, Any] = {}

    @root_validator(pre=False, skip_on_failure=True)  # note the change here!!
    def _do_not_call_me_if_src_settings_are_invalid(cls, vals_dict):
        print("This validator should never be called in case of the fields have invalid data!!!!")
        print(vals_dict)

        # Here will be crash, that should be avoided because this validator should be callled
        # only if the fields are validated!
        print(vals_dict["table_settings"])


if __name__ == "__main__":
    raw_dict = {"table_settings": {"valid_table": {}}}  # It should crash on field's root validator
    
    etl_settings = EtlSettings(**raw_dict)
    # It crashes on field's root validator, now the main validator is not called :)
```

Let me know if you have any follow up questions :).
