### ISSUE TITLE
pydantic v1 throws exception present in v2 codebase

### ISSUE THREAD

**Issue by AnanthaHoma** [pydantic/pydantic#8856]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Hello Everyone, I am using `fhir.resources==6.0.0` to perform some data transformations. This version of  `fhir.resources` requires `pydantic<2.0`. Knowing this I have utilised the `v1` module present inside the latest release of pydantic in the internal code of the `fhir.resources` library.

There is one particular error that the code throws which I find peculiar as that error handling is only present in the `v2` codebase and not `v1`. 

The Error:
```  
File "/home/azureuser/.local/lib/python3.8/site-packages/fhir/resources/fhirabstractmodel.py", line 138, in __init__
    BaseModel.__init__(__pydantic_self__, **data)
  File "/home/azureuser/.local/lib/python3.8/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 10 validation errors for Claim
billablePeriod
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
identifier -> 0
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
insurance -> 0 -> claimResponse
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
insurance -> 0 -> coverage
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
insurer
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
patient
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
priority
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
provider
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
subType
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
type
  `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.6/u/removed-kwargs (type=type_error.pydanticuser; message=`const` is removed, use `Literal` instead; code=removed-kwargs)
```

This error code and the line are present in the `/home/azureuser/.local/lib/python3.8/site-packages/pydantic/fields.py` file on line `726`.

```   
const = extra.pop('const', None)  # type: ignore
if const is not None:
    raise PydanticUserError('`const` is removed, use `Literal` instead', code='removed-kwargs')
```

But I don't use the `v2` codebase anywhere and only use the `v1` functions hence find this error very odd. Could someone please shed some light on why this might be happening or is this a bug

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
pydantic-core version: 2.16.2
pydantic-core build: profile=release pgo=true
install path: /home/azureuser/.local/lib/python3.8/site-packages/pydantic
python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0]
platform: Linux-5.15.0-1045-azure-x86_64-with-glibc2.29
related packages: email-validator-2.1.0.post1 typing_extensions-4.9.0 email-validator-2.1.0.post1 typing_extensions-4.9.0
commit: unknown
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@AnanthaHoma,

Thanks for your question. This error will only be raised if you're using `Field` from `v2` and not from `v1`. For example, when running the following, I get no errors:

```py
from pydantic.v1 import BaseModel, Field

class User(BaseModel):
    category: str = Field(default="person", const=True)
    name: str

user = User(name="John Doe")
print(repr(user))
#> User(category='person', name='John Doe')
```

However, the following raises the error that you've mentioned (note, I'm no longer using `from pydantic.v1` in my import):

```py
from pydantic import BaseModel, Field

class User(BaseModel):
    category: str = Field(default="person", const=True)
    name: str

"""
pydantic.errors.PydanticUserError: `const` is removed, use `Literal` instead

For further information visit https://errors.pydantic.dev/2.7/u/removed-kwargs
"""
```

If a library you use truly depends on `v1`, you should install the latest `v1` version to avoid issues like the one you've raised.
