### ISSUE TITLE
Datetime parsed with YYYY-MM-DD format includes UTC tzinfo

### ISSUE THREAD

**Issue by alexh-jurrens** [pydantic/pydantic#8859]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When parsing a datetime of the format YYYY-MM-DD, Pydantic adds UTC as the timezone. This is inconsistent with how the datetime module in Python works, as well as ISO format. The expected behavior would be to parse as a naive datetime (i.e. without timezone info).
https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat

The current behavior is especially problematic when considering the NaiveDatetime and AwareDatetime type aliases, as it can cause an inappropriate ValidationError or lack thereof, respectively.

Additionally, Pydantic's documentation states that hours and minutes are required for a datetime, making this behavior increasingly unexpected and counterintuitive.
https://docs.pydantic.dev/2.6/api/standard_library_types/#datetimedatetime

Datetimes of the format YYYY-MM-DD should either be parsed without adding timezone info, or this feature should be reverted.

### Example Code

```Python
import pydantic
from datetime import datetime

adapter = pydantic.TypeAdapter(datetime)

print(repr(adapter.validate_python("2011-11-11")))
# > datetime.datetime(2011, 11, 11, 0, 0, tzinfo=TzInfo(UTC))
# The tzinfo part is unexpected

print(repr(adapter.validate_python("2011-11-11T11:11")))
# > datetime.datetime(2011, 11, 11, 11, 11)
# Note: No timezone when parsing a datetime without explicit timezone info
# This is the expected behavior

aware_adapter = pydantic.TypeAdapter(pydantic.AwareDatetime)

aware_adapter.validate_python("2011-11-11")
print("AwareDatetime does not error on YYYY-MM-DD")

try:
    aware_adapter.validate_python("2011-11-11T11:11")
except pydantic.ValidationError:
    print("AwareDatetime errors on YYYY-MM-DDTHH:MM")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
pydantic-core version: 2.16.2
pydantic-core build: profile=release pgo=true
```

**Comment by sydney-runkle** [comment]
Hi,

Thanks for reporting this. This has been fixed in `pydantic-core`, and will be released with our next version. See this duplicate issue: https://github.com/pydantic/pydantic/issues/8762
