### ISSUE TITLE
Validation fails with certain strings in place for a bool

### ISSUE THREAD

**Issue by Passer-Keenan** [pydantic/pydantic#8863]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I created a Pydantic model that had a field requiring to be a boolean. When writing a test I put in the string `"NO"` into the field, and validation passed. I would've expected this to fail since `"NO"` is a string, and it is not the coercion I would imagine most would expect (e.g. `"false"` -> `False`). `StrictBool` does act as expected, but for a string like `"NO"`, both `bool` and `StrictBool` should do the same thing (in my opinion). 

### Example Code

```Python
import pydantic
from pydantic import BaseModel, StrictBool, ValidationError

print(f"Using pydantic: {pydantic.__version__}\n\n")

class Thing(BaseModel):
    option1: bool
    option2: str
    option3: int

valid = {"option1": True, "option2": "hi", "option3": 5}
invalid = {"option1": "yikes this isn't right", "option2": "hi", "option3": 5}
valid_but_shouldnt_be = {"option1": "NO", "option2": "hi", "option3": 5}


def try_to_validate(data: dict):
    try:
        Thing(**data)
        print("That worked")
    except ValidationError as e:
        print(f"Error: {e}")

print("--------Valid--------")
try_to_validate(valid)
print("--------Invalid--------")
try_to_validate(invalid)
print("--------Valid But Shouldn't Be--------")
try_to_validate(valid_but_shouldnt_be)

print("\n\n\n\n\n")

class StrictThing(BaseModel):
    option1: StrictBool
    option2: str
    option3: int

def try_to_validate(data: dict):
    try:
        StrictThing(**data)
        print("That worked")
    except ValidationError as e:
        print(f"Error: {e}")

print("--------Valid--------")
try_to_validate(valid)
print("--------Invalid--------")
try_to_validate(invalid)
print("--------Now it's invalid!--------")
try_to_validate(valid_but_shouldnt_be)

# Output:
"""
Using pydantic: 2.5.3


--------Valid--------
That worked
--------Invalid--------
Error: 1 validation error for Thing
option1
  Input should be a valid boolean, unable to interpret input [type=bool_parsing, input_value="yikes this isn't right", input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/bool_parsing
--------Valid But Shouldn't Be--------
That worked






--------Valid--------
That worked
--------Invalid--------
Error: 1 validation error for StrictThing
option1
  Input should be a valid boolean [type=bool_type, input_value="yikes this isn't right", input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/bool_type
--------Now it's invalid!--------
Error: 1 validation error for StrictThing
option1
  Input should be a valid boolean [type=bool_type, input_value='NO', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/bool_type
"""
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /opt/homebrew/lib/python3.11/site-packages/pydantic
               python version: 3.11.2 (main, Mar 24 2023, 00:16:47) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0
```

**Comment by alexmojaki** [comment]
This is documented in https://docs.pydantic.dev/2.5/api/standard_library_types/#booleans:

> - a str which when converted to lower case is one of '0', 'off', 'f', 'false', 'n', 'no', '1', 'on', 't', 'true', 'y', 'yes'

> If you want stricter boolean logic (e.g. a field which only permits True and False) you can use [StrictBool](https://docs.pydantic.dev/2.5/api/types/#pydantic.types.StrictBool).

You say:

> but for a string like "NO", both bool and StrictBool should do the same thing (in my opinion).

I'm not sure why you feel that way, IMO it's useful to coerce strings like 'yes' and 'off', and it makes sense for bool to be less strict than StrictBool. Either way, changing this now would be a big problem for existing users. If you want some behaviour that's different from both bool and StrictBool, I suggest writing a custom validator.

**Comment by Passer-Keenan** [comment]
Thanks for clarifying @alexmojaki. To help you understand, it was the hidden logic behind `bool` that caught me off guard. 
Imagine typing a random string and it just so happens to match up with a keyword, the results can be a bit surprising.
But understandable you don't want to change this now, so all good here.
