### ISSUE TITLE
to_camel improvement (fix?) to properly convert field names with a single trailing underscore

### ISSUE THREAD

**Issue by skewty** [pydantic/pydantic#8864]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

```python
def to_camel_corrects_trailing_underscore(field_name: str) -> str:
    """Great for working around python reserved words and (VSCode + Pyright)'s dataclass alias= understanding"""
    return to_camel(field_name[:-1] if field_name[-1] == "_" else field_name)
```

Fixes field names like: `"from_"` -> `"from"`.  Currently it does: `"from_"` -> `"from_"`

Perhaps the matching should be improved with regex to something like `r'[A-Za-z0-9]_$'` or `r'[a-z]_$'`?
This would cause it to match only when the field name ends in a **single** underscore. 
I think I prefer the 2nd pattern as it works fine for all the reserved words it is likely to be used with.

I had to use this alias generator recently because a model that is understood properly in PyCharm w/ Pydantic Plugin is incorrectly understood by VScode. Without this special alias generator VScode couldn't be made happy when trying to populate by field name. 

```python
# From (Original with problem in VScode)
class Relation(BaseModel, alias_generator=to_camel, populate_by_name=True, frozen=True):
    from_: EntityRef = Field(..., alias="from")
    to_: EntityRef = Field(..., alias="to")
    type_: str = Field(..., alias="type")
    type_group: RelationTypeGroup
    
# To (Both VScode and PyCharm are happy)

class Relation(BaseModel, alias_generator=modified_to_camel, populate_by_name=True, frozen=True):
    from_: EntityRef
    to_: EntityRef
    type_: str
    type_group: RelationTypeGroup

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @skewty,

Thanks for reporting this. We won't change this in a minor version, as this would be a breaking change. For now, I think logic to strip the trailing underscore should reside in user code, but I've tagged this with our `V3` tag as something we could revisit down the line for a major release.

**Comment by AndrewUshakov** [comment]
Hi @sydney-runkle,

Could you please add similar functionality (in the future) to the to_pascal() function?
