### ISSUE TITLE
No ValidationError anymore when using 'yyyy-MM-DD' string with `AwareDatetime` type

### ISSUE THREAD

**Issue by davidhuser** [pydantic/pydantic#8867]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In pydantic 2.6.0 the support for `yyyy-MM-DD` string for datetimes was added ([issue](https://github.com/pydantic/pydantic/issues/8363) + [PR](https://github.com/pydantic/pydantic-core/pull/1124)). 

When using [`AwareDatetime`](https://docs.pydantic.dev/latest/api/types/#pydantic.types.AwareDatetime), no ValidationError is raised anymore in 2.6.0+. However, since no Timezone information is attached to a yyyy-MM-DD string, I would expect a ValidationError to be raised.

Potential workaround: As mentioned in [this issue](https://github.com/pydantic/pydantic/issues/8363#issuecomment-1921604135) a `StrictDatetime` could be possible, if so, how would a `StrictUTCDatetime` type work?

### Example Code

```Python
from datetime import timezone
from typing import Annotated

from pydantic import AfterValidator, AwareDatetime, BaseModel, ValidationError


def validate_utc(dt: AwareDatetime | None) -> AwareDatetime | None:
    """Validate that the pydantic.AwareDatetime is in UTC."""
    if dt:
        if dt.tzinfo.utcoffset(dt) != timezone.utc.utcoffset(dt):
            raise ValueError('Timezone must be UTC')
    return dt


DatetimeUTC = Annotated[AwareDatetime, AfterValidator(validate_utc)]


class UTCModel(BaseModel):
    dt_aware: DatetimeUTC


if __name__ == '__main__':
    try:
        m = UTCModel(dt_aware='2023-01-01')
        print(repr(m))
    except ValidationError as e:
        print(e)
    """
    UTCModel(dt_aware=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=TzInfo(UTC)))
    """
```

### Python, Pydantic & OS Version

```Text
poetry run python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/xxx/Library/Caches/pypoetry/virtualenvs/myrepo-fwpETFsa-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.2 mypy-1.8.0 email-validator-2.1.0.post1 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by davidhuser** [comment]
One solution could be as per [this comment](https://github.com/pydantic/pydantic/issues/8736#issuecomment-1929689552)

```python
class UTCModel(BaseModel):
    dt_aware: DatetimeUTC = Field(..., strict=True)
```

however, all the previously lax and valid formats will now fail as well, e.g.

```python
input_data = datetime.now(timezone.utc).isoformat()
```

**Comment by sydney-runkle** [comment]
@davidhuser,

Thanks for reporting this. I'm adding this to the 2.6.2 milestone! Will keep you updated as I work on a fix.

**Comment by sydney-runkle** [comment]
Ah, so this was actually fixed by my fix for this: https://github.com/pydantic/pydantic/issues/8867.

Going to mark this as resolved, and will work on the 2.6.2 release now!

**Comment by davidhuser** [comment]
thanks for looking into it. Your link self-references to this issue, out of curiosity where was the fix implemented?

**Comment by sydney-runkle** [comment]
Ah, meant to link to this issue: https://github.com/pydantic/pydantic/issues/8762. Should be out now with 2.6.2!
