### ISSUE TITLE
Poor schema naming in root model openapi json with union type

### ISSUE THREAD

**Issue by ManiMozaffar** [pydantic/pydantic#8869]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm having a model, which is Root model of a union discriminated type, so i can use the model as root model without having to write another class.
However the problem is naming the root model in openapi which is very weird.

<img width="1398" alt="Screenshot 2024-02-21 at 16 25 26" src="https://github.com/pydantic/pydantic/assets/86913668/35084939-7507-4c89-a5ca-318adb1a7cb4">

Maybe have a way to inject name in root model? 

Maybe this should have been a issue about feature
but basically my idea is 
Annotated[some_root_model, metadata]
not sure if that's possible tho. just an idea.

### Example Code

```Python
DiscriminatedInternalIncType = Annotated[
    Union[NoDataTransInternal, NoSymptomsInternal],
    Field(discriminator="type"),
]
DiscriminatedInternalIncModel = RootModel[DiscriminatedInternalIncType]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/manimozaffar/Library/Caches/pypoetry/virtualenvs/nl-rpm-CEMQou1J-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 pyright-1.1.351 pydantic-extra-types-2.5.0 fastapi-0.103.2 email-validator-2.1.0.post1 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @ManiMozaffar,

You can set the title via the `Field` constructor you're using, and that'll be used in the generated JSON schema:

```py
import json
from typing import Annotated

from pydantic import RootModel, Field


my_root = RootModel[Annotated[str | int, Field(..., description="A string or an integer", title="MyRootModel")]]
print(json.dumps(my_root.model_json_schema(), indent=2))
"""
{
  "anyOf": [
    {
      "type": "string"
    },
    {
      "type": "integer"
    }
  ],
  "description": "A string or an integer",
  "title": "MyRootModel"
}
"""
```

**Comment by sydney-runkle** [comment]
@ManiMozaffar,

You could also subclass from `RootModel`, and in this case, the new class name will be used as the `title` in the JSON schema:

```py
import json
from typing import Annotated

from pydantic import ConfigDict, Field, RootModel


class MyRootModel(RootModel):
    root: Annotated[str | int, Field(..., description="A string or an integer")]


print(json.dumps(MyRootModel.model_json_schema(), indent=2))
"""
{
  "anyOf": [
    {
      "type": "string"
    },
    {
      "type": "integer"
    }
  ],
  "title": "MyRootModel"
}
"""
```

Finally, you could add a `model_config` to this new class, and specify a new `title` in the `ConfigDict`.
