### ISSUE TITLE
Error with model_dump using abc.ABC recursive

### ISSUE THREAD

**Issue by iBuitron** [pydantic/pydantic#8873]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a ABC class

`class Values(BaseModel, ABC): ...`

using in: 

```
class HistogramValues(Values):
    x_value: str
    y_value: str
    color: str | None = None
    facet_col: str | None = None
    template: str = "seaborn"
```

When i create a 

```
    values = HistogramValues(
        x_value=x_axis,
        y_value=y_axis,
        color=color,
        facet_col=facet_col,
    )

values.model_dump()
This give me all the values as a dict (works fine)
```

But this class "HistogramValues" is part of

```
class Histogram(Chart):
    values: HistogramValues
    shape: HistogramShape | None = None

Note: Chart is also an ABC model
class Chart(BaseModel, ABC):
    values: dict[str, Any] | None | Values
    shape: dict[str, Any] | None | Shape
```

When i use 

`chart = Histogram(values=values, shape=shape)`

and them dump chart

`chart.model_dump()`

There is no data:
`{'chart': {'values': {}, 'shape': {}}`

If i change HistogramValues(Values) to HistogramValues(BaseModel) it works fine.

according to: https://docs.pydantic.dev/latest/concepts/serialization/ serialization is recursive, so this should work, but something is happened when use abc.ABC

### Python, Pydantic & OS Version

```Text
pydantic version: 2.3.0
        pydantic-core version: 2.6.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/reveur/python/environmental/quickBio-frontend/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Oct 23 2023, 22:48:54) [GCC 11.4.0]
                     platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
     optional deps. installed: ['typing-extensions']
```

**Comment by sydney-runkle** [comment]
@iBuitron,

Thanks for reporting this. Could you provide a MRE (minimal reproducible example) that we can use to observe this behavior? Thanks!

**Comment by sydney-runkle** [comment]
Closing for now until we get an MRE. Feel free to ping me when you have one, and I can reopen!
