### ISSUE TITLE
LateBind functionality and application thereof Subclasses wrapper

### ISSUE THREAD

**Issue by alex-orange** [pydantic/pydantic#8874]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I've been working on some code that uses inheritance a lot and was struggling to get subclasses to work automatically (i.e. without using a static Union of some classes I wanted, or all the existing subclasses). I was looking for a solution that would allow me to dynamically use the __subclasses__ method on a type to create a "runtime" Union of all the subclasses once all imports are done so as to allow the subclasses to be fully populated before building the model. I came up with the following patch that adds the ability to late bind a type and using that to define a Subclasses wrapper that on late bind returns a Union of all its subclasses:

```
diff --git a/pydantic/_internal/_generate_schema.py b/pydantic/_internal/_generate_schema.py
index e9fd34ab..5df09540 100644
--- a/pydantic/_internal/_generate_schema.py
+++ b/pydantic/_internal/_generate_schema.py
@@ -305,6 +305,20 @@ def _get_first_non_null(a: Any, b: Any) -> Any:
     return a if a is not None else b
 
 
+import abc
+class LateBind(abc.ABC):
+    @abc.abstractmethod
+    def bind(self):
+        pass
+
+class Subclasses(LateBind):
+    def __init__(self, type_):
+        self.type_ = type_
+
+    def bind(self):
+        return Union[*self.type_.__subclasses__()]
+
+
 class GenerateSchema:
     """Generate core schema for a Pydantic model, dataclass and types like `str`, `datetime`, ... ."""
 
@@ -757,6 +771,9 @@ class GenerateSchema:
         return schema
 
     def _generate_schema_inner(self, obj: Any) -> core_schema.CoreSchema:
+        if isinstance(obj, LateBind):
+            obj = obj.bind()
+
         if isinstance(obj, _AnnotatedType):
             return self._annotated_schema(obj)
 
```

The example I have of using this is:

```
import typing

import pydantic
import pydantic._internal._generate_schema

class BaseA(pydantic.BaseModel):
    a: int


class UseA(pydantic.BaseModel):
    a: pydantic._internal._generate_schema.Subclasses(BaseA)
    model_config = pydantic.ConfigDict(defer_build=True)


class A1(BaseA):
    type_ : typing.Literal["A1"]
    b: int

class A2(BaseA):
    type_ : typing.Literal["A2"]
    b: int

print(UseA(a={'type_': "A2", 'a':1, 'b':2}))
```

As you can see, the example uses the late binding subclasses wrapper together with a config of defer_build=True to work out the list of subclasses at use time instead of model definition time. The A1 and A2 classes didn't even exist at that point.

Obviously this won't work if you add a subclass after having already used UseA. However, I think this covers most of the cases of importing a bunch of modules in an arbitrary order, defining a bunch of classes and then finally starting to instantiate the classes.

P.S. Before anyone mentions it, yes, I know this probably isn't the place to put these classes, I just put them in the most convenient place to test the code and I'd be happy to relocate them to the proper module (once someone tells me what module that would be). Also I'm not married to the names, so if anyone has a better name for either of these classes feel free to offer it up.

P.P.S. I'm not entirely sure which components this will affect, so I've checked the 3 I think it might affect and I'll let someone more knowledgeable refine my selection if necessary.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [X] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@alex-orange,

Thanks for the request. I don't think I entirely understand your request, but the use case seems specific enough that I think the changes probably belong in user-code.

I'm going to mark this as not planned for now, but if you're able to provide greater clarification regarding the request, or if there's high demand / interest from the general community, we could certainly consider this!

**Comment by alex-orange** [comment]
@sydney-runkle I may be confused about where the line of user code versus pydantic code is, but specifically I'm asking for a change to `_generate_schema_inner` in class `GenerateSchema`. As far as I can tell there is not a way to do this in user code. If you want to suggest the `Subclasses` class that I gave as an example be put in user code, that's perfectly fine, but the functionality to allow it to exist needs to be added to `_generate_schema_inner`. If you can show me an alternative way of doing this that is a. not overly cumbersome and b. can be done from user code I'd be happy to take that route.

Just to clarify "a. not overly cumbersome". I have a solution that involves putting __init_subclass__ methods in the classes to be modified, using ForwardRefs to ForwardRefs multiple times over to confuse python into not resolving the ForwardRefs and finally rebuilding all the pydantic classes involved, the class referencing the parent class as well as all of the children. This is a horrible and unmaintainable way of doing this, hence why I'm looking for a more pleasant approach like the one given. (Also it seems this way is "tricking" the system into working and more brittle to possible changes).

**Comment by alex-orange** [comment]
@sydney-runkle poke. I am not clear at all how I can achieve what I'm calling late bind functionality without it being in pydantic. If I've missed something, please clarify, but I believe a change to pydantic's code is required to support this.
