### ISSUE TITLE
Postponed evaluation of annotation failure

### ISSUE THREAD

**Issue by mwalsh161** [pydantic/pydantic#8883]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

- Given a dataclass defined in a module with postponed annotations (`from __future__ import annotations`)
- then a function in a separate module  that uses `pydantic.validate_call` with said dataclass as an annotated argument
- that function errors on decoration due to pydantic trying to resolve annotations (guessing using the wrong scopes)

```
...
  File "/Users/mpwalsh/hrlconda/envs/quasar/lib/python3.8/site-packages/pydantic/_internal/_generate_schema.py", line 642, in _resolve_forward_ref
pydantic.errors.PydanticUndefinedAnnotation: name 'C' is not defined
```

- Worth noting that `typing.get_type_hints` is able to resolve, so expectation is that pydantic can too.

Apologies if I'm missing something in config to enable this!

### Example Code

```Python
""" Package structure:
foo/
  __init__.py
  a.py
  b.py
"""
# a.py
import pydantic
from foo import b

@pydantic.validate_call(config={"arbitrary_types_allowed": True})
def my_fun(val: b.B):
    ...

# b.py
from __future__ import annotations
import dataclasses

@dataclasses.dataclass
class B:
    attr: C

class C: ...

>>> import foo.a # Errors
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: .../lib/python3.8/site-packages/pydantic
               python version: 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:23:49)  [Clang 15.0.7 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 pyright-1.1.351 mypy-1.8.0 fastapi-0.104.1
```

**Comment by sydney-runkle** [comment]
@mwalsh161,

Thanks for reporting this. I believe this is fixed on main. Could you please try with the most recent code + let us know if this is still an issue?
