### ISSUE TITLE
Add a round_float validator

### ISSUE THREAD

**Issue by ollz272** [pydantic/pydantic#8903]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We have a couple of use cases in our code base where we have a pydantic model with a float field, which we want to be rounded. We have an implementation that looks something like:

```python
from pydantic import BaseModel, field_validator

class MyModel(BaseModel):

    my_field: float

    @field_validator("my_field")
    @classmethod
    def round_float(cls, v: float) -> float:
        """Round floats to 2 decimal places."""
        return round(v, 2)
```

This is okay but we need to repeat the validator on each model which becomes annoying. We then came up with:
```python
from typing import Callable, Annotated

from pydantic import AfterValidator, BaseModel


def round_float(round_to: int) -> Callable:
    def inner_round(v: float):
        return round(v, round_to)

    return inner_round


class MyModel(BaseModel):

    my_field: Annotated[float, AfterValidator(round_float(2))]
```

Which works well, however again we still need to have this boiler plate in our code, both defining the function and adding an after validator to each field. It would be amazing if this could be done within pydantic itself.. We noticed that there is the `decimal_places` option in fields however this only seems to be useable for `Decimal` instances. Would it be possible to:

1. Support floats with the decimal_places argument
2. Add a new API for rounding floats?

I imagine for 2 it would look like:

```python
from pydantic import Field, BaseModel


class MyModel(BaseModel):

    my_field: float = Field(round_places=2)
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
These both seem like reasonable feature requests, and I believe they'll require some work in `pydantic-core`! PRs welcome :).

**Comment by yfalomir** [comment]
Hi, I'd like to contribute on this issue (as my first contribution). Still trying to understand the whole architecture of the pydantic project.
Is there some documentation or examples I could follow to create a new validator?

**Comment by sydney-runkle** [comment]
@yfalomir,

Awesome! Hmm, yeah we'll have to decide on exactly what we want the API to look like regarding the rounding behavior. 

Before we do that, @Zac-HD, do you think there's any place for some sort of rounding annotation in `annotated-types`? If not, we can implement a solution purely in `pydantic`, but wanted to get your feedback first :).

**Comment by Zac-HD** [comment]
Let's start with just Pydantic, and then we can move it to annotated-types if there's wider demand for it and consensus on the semantics 🙂

**Comment by yfalomir** [comment]
How do you want to proceed about deciding what the API should look like?

Maybe I can make propositions if you point me to relevant chunks of codes to compare the issue with.

**Comment by sydney-runkle** [comment]
@yfalomir,

Ah, apologies for the delay, this notification got buried in my email. Why don't we start with an implementation that uses Python's `round` function (for simplicity, and also then the rounding behavior isn't dependent upon custom logic). What do you think about `round_to` as the setting name (takes an int)? I wouldn't worry too much about adding support for this to types like `confloat` for now...

I think the `decimal_places` support for floats is going to be more difficult, due to differing internal storage mechanisms on different machines.

**Comment by yfalomir** [comment]
Sorry for the delay, I will make a proposition this week.

**Comment by yfalomir** [comment]
I don't feel like I can give on informed opinion on the matter. @sydney-runkle maybe you could help me on this?

**Comment by sydney-runkle** [comment]
@yfalomir,

Yes, certainly! I'll review your PR and the above comments today!

**Comment by sydney-runkle** [comment]
@yfalomir,

Honestly, I agree with @Viicos. It'd be great to not set that precedent.

Closing this for now, as I think the above suggested approach is generally quite clean, and exactly how we expect annotated types to bring great value. Thanks for the feedback and effort, folks!

**Comment by shifenhutu** [comment]
hope can help someone:


## Overview
AutoDecimalModel is a Pydantic base model that automatically handles Decimal precision based on field configuration. It reads the decimal_places configuration from fields and automatically applies rounding to Decimal values.

## Key Features
**Automatic Precision Detection**: Automatically reads decimal_places configuration from fields

**Smart Rounding**: Uses banker's rounding (ROUND_HALF_UP) for decimal processing

**Seamless Integration**: Perfectly integrates with Pydantic validation pipeline






# code
```

from decimal import Decimal, ROUND_HALF_UP
from pydantic import BaseModel, model_validator, Field
from typing import Optional, Any
from pydantic.fields import FieldInfo


class AutoDecimalModel(BaseModel):
    """Base model that automatically handles Decimal precision based on Field configuration"""
    
    @model_validator(mode='before')
    @classmethod
    def round_decimal_fields(cls, data: Any) -> Any:
        """Automatically read Field configuration and process Decimal precision"""
        if not isinstance(data, dict):
            return data
            
        result = data.copy()
        
        for field_name, field_info in cls.model_fields.items():
            # Check if field has decimal_places configuration
            decimal_places = cls._get_decimal_places_from_field(field_info)
            if decimal_places is not None and field_name in result:
                result[field_name] = cls._process_decimal_value(
                    result[field_name], decimal_places
                )
                
        return result
    
    @classmethod
    def _get_decimal_places_from_field(cls, field_info: FieldInfo) -> Optional[int]:
        """Extract decimal_places configuration from Field info"""
        # Check json_schema_extra
        if hasattr(field_info, 'json_schema_extra'):
            extra = field_info.json_schema_extra
            if extra and 'decimal_places' in extra:
                return extra['decimal_places']
        
        # Check metadata (Pydantic 2.x way)
        if hasattr(field_info, 'metadata') and field_info.metadata:
            for metadata in field_info.metadata:
                if hasattr(metadata, 'decimal_places'):
                    return metadata.decimal_places
                elif isinstance(metadata, dict) and 'decimal_places' in metadata:
                    return metadata['decimal_places']
        
        return None
    
    @classmethod
    def _process_decimal_value(cls, value: Any, decimal_places: int) -> Any:
        """Process Decimal value rounding"""
        if value is None:
            return None
            
        try:
            decimal_val = Decimal(str(value))
            quantize_str = f"0.{'0' * decimal_places}" if decimal_places > 0 else "1"
            return decimal_val.quantize(Decimal(quantize_str), rounding=ROUND_HALF_UP)
        except (ValueError, TypeError, decimal.InvalidOperation):
            # If conversion fails, return original value for Pydantic validation
            return value


# Test
class TestModel(AutoDecimalModel):
    price: Decimal = Field(max_digits=50, decimal_places=3)

# Run tests
print("=== Starting Tests ===")
test_cases = ["12.3424242425", "113.4511111111"]
for case in test_cases:
    try:
        result = TestModel(price=case)
        print(f"Input: {case} -> Output: {result.price}")
    except Exception as e:
        print(f"Input: {case} -> Error: {e}")
```

# print
```

=== Starting Tests ===
Input: 12.3424242425 -> Output: 12.342
Input: 113.4511111111 -> Output: 113.451
```
