### ISSUE TITLE
Cannot pickle BaseModel containing typed generic BaseModel

### ISSUE THREAD

**Issue by Moisan** [pydantic/pydantic#8913]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It is currently possible to pickle a BaseModel which contains a generic type, for example
```python
class BaseClass1(BaseModel):
    a: int

class BaseClass2(BaseModel):
    a: int

T = TypeVar("T", BaseClass1, BaseClass2)
class MyClass(BaseModel, Generic[T]):
    x: list[T]
    y: int

obj = MyClass[BaseClass1](x=[BaseClass1(a=1), BaseClass1(a=2)], y=2)

with open("something.pkl", "wb") as file:
    pickle.dump(obj, file)
with open("something.pkl", "rb") as file:
    obj2 = pickle.load(file)
    print(obj2)
```

However, if this class (`MyClass` here) is used as a type in a `BaseModel` while being typed to a specific value (such as `BaseClass1`, for example 
```python 
class TopClass(BaseModel):
    first: MyClass[BaseClass1]
```
Then pickling `TopClass` raises
```
_pickle.PicklingError: Can't pickle <class '__main__.MyClass[BaseClass1]'>: attribute lookup MyClass[BaseClass1] on __main__ failed
```

Even weirder is that once `TopClass` is defined as done above, `MyClass` suddenly cannot be pickled anymore.

However note that if `TopClass` is generic too, there is no problem:
```python
class TopClass(BaseModel, Generic[T]):
    first: MyClass[T]
```

Switching the order of `Generic` and `BaseModel` in `MyClass` also fixes the pickling issue but raises a `GenericBeforeBaseModelWarning` warning from Pydantic stating that we shouldn't do that:
```python
class MyClass(Generic[T], BaseModel):
    x: list[T]
    y: int
```

I also tested this code by switching to Python `dataclass` instead of `BaseModel` and I see no issue related to pickling.

### Example Code

```Python
import pickle
from typing import Generic, TypeVar
from pydantic import BaseModel

class BaseClass1(BaseModel):
    a: int

class BaseClass2(BaseModel):
    a: int

T = TypeVar("T", BaseClass1, BaseClass2)
class MyClass(BaseModel, Generic[T]):
    x: list[T]
    y: int

class TopClass(BaseModel):
    first: MyClass[BaseClass1]

obj = MyClass[BaseClass1](x=[BaseClass1(a=1), BaseClass1(a=2)], y=2)
top_obj = TopClass(first=obj)

with open("something.pkl", "wb") as file:
    pickle.dump(obj, file)
with open("something.pkl", "rb") as file:
    obj2 = pickle.load(file)
    print(obj2)

with open("something2.pkl", "wb") as file:
    pickle.dump(top_obj, file)
with open("something2.pkl", "rb") as file:
    obj2 = pickle.load(file)
    print(obj2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/thierry.moisan/Library/Caches/pypoetry/virtualenvs/test-generic-we-Qc_jo-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-arm64-arm-64bit
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Moisan,

Hmph, that does look like a bug. Thanks for the thorough report! I'll dig into this...

**Comment by sydney-runkle** [comment]
@Moisan,

After digging into this a bit more, I've found the source of the behavior. So in Pydantic, when you parametrize a generic class, Pydantic creates a new class. This is done here: https://github.com/pydantic/pydantic/blob/575f473ac94d119261e2bb682bc76980734a8c13/pydantic/_internal/_generics.py#L116

Taking a closer look at this function, we see that if the model is parametrized in the global scope, then a global reference is created, which allows pickling:

https://github.com/pydantic/pydantic/blob/575f473ac94d119261e2bb682bc76980734a8c13/pydantic/_internal/_generics.py#L151-L160

That means in your case, if you make this slight modification, the code works:

```py
import pickle
from typing import Generic, TypeVar
from pydantic import BaseModel

class BaseClass1(BaseModel):
    a: int

class BaseClass2(BaseModel):
    a: int

T = TypeVar("T", BaseClass1, BaseClass2)
class MyClass(BaseModel, Generic[T]):
    x: list[T]
    y: int

MyParametrizedClass = MyClass[BaseClass1]

class TopClass(BaseModel):
    first: MyParametrizedClass

obj = MyParametrizedClass(x=[BaseClass1(a=1), BaseClass1(a=2)], y=2)
top_obj = TopClass(first=obj)

with open("something.pkl", "wb") as file:
    pickle.dump(obj, file)
with open("something.pkl", "rb") as file:
    obj2 = pickle.load(file)
    print(obj2)

with open("something2.pkl", "wb") as file:
    pickle.dump(top_obj, file)
with open("something2.pkl", "rb") as file:
    obj2 = pickle.load(file)
    print(obj2)
```

**Comment by sydney-runkle** [comment]
This is somewhat analogous to dynamic model creation, where the following tip [from the docs](https://docs.pydantic.dev/latest/concepts/models/#dynamic-model-creation) applies:

<blockquote>
To pickle a dynamically created model:

* the model must be defined globally
* it must provide` __module__`

</blockquote>

Given this, I think it's appropriate to close this as not planned. Let me know if you have any follow up questions! 😄
