### ISSUE TITLE
Change email validation errors to be user friendly

### ISSUE THREAD

**Issue by csirmazbendeguz** [pydantic/pydantic#8914]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

`email-validator` produces user friendly error messages, but Pydantic prepends the text `value is not a valid email address: `.
not sure what's the point, this can't be displayed to users, I suggest we remove it.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@csirmazbendeguz,

The prepended value is useful for a case like this one:

```py
from pydantic.networks import NameEmail
from pydantic import BaseModel

class User(BaseModel):
    name: str
    email: NameEmail

u = User(name='sydney', email='s@')
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
email
  value is not a valid email address: There must be something after the @-sign. [type=value_error, input_value='s@', input_type=str
"""
```

Closing this as not planned for now. Thanks!

**Comment by csirmazbendeguz** [comment]
Hey @sydney-runkle, thank you for answering. I'm sorry, I still can't see the value in having this text prefixed. IMO this is would be so much better:

```py
"""
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
email
  There must be something after the @-sign. [type=value_error, input_value='s@', input_type=str
"""
```

**Comment by sydney-runkle** [comment]
@csirmazbendeguz,

I think it gives helpful context - consider a case when the field name wasn't as clear, maybe `contact` or something like that. Especially in the case of a model that might have an abundance of fields, it provides useful information regarding the general category of validation that's failing.

**Comment by csirmazbendeguz** [comment]
I see, thanks @sydney-runkle.

The issue I'm trying to solve is, I'm using this in a FastAPI app, and I'm trying to display an error message to users. I'm doing this right now, so, I assume this is the correct way to handle this, can you confirm?

```py
class Email(EmailStr):
    @classmethod
    def _validate(cls, __input_value: str) -> str:
        try:
            super()._validate(__input_value)
        except PydanticCustomError as e:
            raise PydanticCustomError(
                e.type,
                "{reason}",
                e.context,
            )
```
