### ISSUE TITLE
Potential Bug in Handling Field Aliases in Pydantic Models

### ISSUE THREAD

**Issue by janbjorge** [pydantic/pydantic#8927]
Firstly, I want to express my deep appreciation for the Pydantic library and the incredible value it brings to the Python community. Your work has consistently made data validation and settings management both efficient and enjoyable. It's a wonderful tool that I use time and time again, and its robustness and versatility have significantly improved my projects' quality and development speed.

### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description
I've encountered an issue with Pydantic's handling of field aliases that may represent a bug. When defining a model with a field alias and attempting to create instances of this model, I noticed inconsistent behavior in how aliases are recognized and processed.

Here is a simplified example to illustrate the problem:

```python
from pydantic import BaseModel, Field

class Foo(BaseModel):
    schema_: str = Field(alias="$schema")
```

Attempts to create instances of `Foo` in various ways yield inconsistent results:

- Using `Foo.model_validate({"$schema": "This is fine"})` or `Foo(**{"$schema": "This is fine"})` works as expected, correctly interpreting the alias.
- However, attempting to directly instantiate the model with `Foo(schema_="Does not work")` does not behave as anticipated. The latter ignores the alias mapping.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/<revoked>/.pyenv/versions/3.10.13/envs/dataio/lib/python3.10/site-packages/pydantic
               python version: 3.10.13 (main, Nov 15 2023, 14:41:32) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: fastapi-0.110.0 pyright-1.1.350 typing_extensions-4.10.0 mypy-1.8.0 pydantic-settings-2.1.0 email-validator-2.1.0.post1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@janbjorge,

You'll have to use the `populate_by_name` config setting, as described here: https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name.

Thanks for your question!
