### ISSUE TITLE
validate_call makes an unexpected conversion

### ISSUE THREAD

**Issue by lpgros** [pydantic/pydantic#8930]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In this example:

```python
>>> from collections.abc import Set
>>> from pydantic import ConfigDict, validate_call
>>>
>>> @validate_call(config=ConfigDict(strict=True, arbitrary_types_allowed=True),)
... def my_test(a_set: Set[str],):
...     print(type(a_set), a_set)
...
>>> my_test({"1","2","3",})
<class 'frozenset'> frozenset({'1', '2', '3'})
>>> my_test(("1","2","3",))
<class 'frozenset'> frozenset({'1', '2', '3'})
>>>
```

You will notice that the `tuple` got turned into a `frozenset` instead of being rejected as an incompatible input (this is running in `strict=True` mode)

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=false
                 install path: .virtualenvs/env3/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 (main, Feb 21 2024, 09:32:09) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3.1-x86_64-i386-64bit
             related packages: email-validator-2.0.0.post2 pyright-1.1.350 typing_extensions-4.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@lpgros,

Pydantic doesn't natively offer support for the `Collection` type, which is why you have to use `arbitrary_types_allowed=True` in the config. If you want to add support for validating this type, you'll have to use a custom validator, or implement `__get_pydantic_core_schema__` on a custom subclass of `Collection`.

Marking as closed, as this is expected behavior, given the lack of support for this type.

**Comment by sydney-runkle** [comment]
Ah, this does seem like a bug, but isn't just for `validate_call`, but also this problem applies to general validation with `BaseModel`, pydantic dataclasses, etc (it's all the same logic, so this isn't surprising). We should revisit the set validation logic.
