### ISSUE TITLE
Add more properties to `Url.path` for granular access

### ISSUE THREAD

**Issue by Ravencentric** [pydantic/pydantic#8936]
### Initial Checks

- [x] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently, `Url.path` returns a string `/parent/sub/logo.png` given a url `https://example.com/parent/sub/logo.png`. I think it would nice addition to have a more granular access to the url path. Consdering it's sort of similar to a path on a system, I think mimicking pathlib **to a simplified extent** would be intuitive

```py
>>> from pydantic import BaseModel, HttpUrl
>>>
>>>
>>> class MyUrl(BaseModel):
...     url: HttpUrl
...
>>>
>>> site = MyUrl(url="https://example.com/parent/sub/logo.png")
>>> site.url
Url('https://example.com/parent/sub/logo.png')
>>> site.url.path
'/parent/sub/logo.png'
>>> site.url.path.name # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name
'logo.png'
>>> site.url.path.stem #https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem
'logo'
>>> site.url.path.parent # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parent
'/parent/sub'
>>> site.url.path.parent.parent # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parent
'/parent'
>>> site.url.path.parents # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parents
('/parent/sub','/parent', '/')
>>> site.url.path.parts # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.parts
('/', 'parent', 'sub', 'logo.png')
>>> site.url.path.suffix # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffix
'.png'
>>> site.url.path.suffixes # https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffixes
['.png']
>>> url.is_file() # https://docs.python.org/3/library/pathlib.html#pathlib.Path.is_file
True
```
Mimicking all of pathlib won't make sense so ive listed some in my example that would in my opinion make sense. I've also purposely deviated from pathlib in my examples where instead of returning a generator it's a simple tuple.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [x] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [x] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@Ravencentric,

Seems like a reasonable feature request! Feel free to submit a PR and ping me for a review :).

**Comment by alexeyt101** [comment]
@sydney-runkle 
Hi! I'd like to work on this :)

**Comment by sydney-runkle** [comment]
@alexeyt101,

Go for it!

**Comment by sydney-runkle** [comment]
Circling back here - I don't think this makes sense to add for now. We're basically using the `path` from the internal `rust` structure.

If you're looking for this sort of granularity, perhaps you could define your own class or function to extract said information from a `str` like url path + get it from there.

Marking as not planned for now.
