### ISSUE TITLE
Custom fields missing from fields.py

### ISSUE THREAD

**Issue by makquel** [pydantic/pydantic#8988]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

It's not really an issue, however, the latest, and also migration guide don't mention anything regarding the custom types that used to be defined on the `fields.py` file.

### Example Code

```Python
from pydantic.fields import (
    SHAPE_LIST,
    SHAPE_SET,
    SHAPE_SINGLETON,
    SHAPE_TUPLE,
    ModelField,
)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/mruedas/Library/Caches/pypoetry/virtualenvs/mlma-toolkit-z-80lxAU-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: mypy-0.931 typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@makquel,

Thanks for your question. Indeed, these references are no longer used in V2. The references are still present if you import from `pydantic.v1.fields`.
