### ISSUE TITLE
Alternative BaseSettings without enviromentvariables by BaseModel.model_validate_json_file

### ISSUE THREAD

**Issue by UHF** [pydantic/pydantic#8996]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I used BaseSettings for some time in my projects. But I see some security issues when I put something lika api_kesy on enviroment varibales.
They are just to easy to catch.
On the otherhand i like BaseModels for data validation.
So I changed to an approch using json files to load my BaseModels wich contain only default configuration.
The function I use works simmilar as BaseSettings. So if the file is not found it just skipps and return teh default data.
If the file is found the data is read and pased into the BaseModel object.
As result the Basemodel is avalible in only RAM and contains the needed settings.

This is how I extend the Basemodel.
```
class uhfPydanticBaseModel(BaseModel):
    def model_validate_json_file(self, file_path: str = None):
        try:
            with open(file=file_path, mode='r') as f:
                data = json.load(f)
            return self.model_validate(data)
        except Exception as error:
            pass
        return self

    def model_dump_json_file(self, file_path: str = None):
        with open(file=file_path, mode='w') as f:
            f.write(self.model_dump_json())
```

Usage in one of my projects
```
class AlpacaPaperConfig(uhfPydanticBaseModel):
    API_KEY:str=""
    # Put your own Alpaca secret here:
    API_SECRET:str=""
    # If you want to go live, you must change this. It is currently set for paper trading
    PAPER:bool= True

def get_alpaca_paper_config() -> AlpacaPaperConfig:
    config_path = f'{os.path.dirname(__file__)}/../../.env/alpaca_config.json'
    config = AlpacaPaperConfig().model_validate_json_file(config_path)
    return config
```

This may be not the best way to implement this feature but I think you get the idea.
Maybe this is also intreresting in future and I dont need to build my own class to do this.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by hramezani** [comment]
Thanks @UHF for the issue

>I used BaseSettings for some time in my projects. But I see some security issues when I put something lika api_kesy on enviroment varibales.
They are just to easy to catch.

Could you explain more the security issue?

**Comment by UHF** [comment]
Hi @hramezani,

Depending on wich OS you are working you can simply list all enviroment variables by e.g. executing SET in a terminal.
This will list all Enviroment variables and there Values.
If you work with more people on a project or may have others maintaining your server they can simply see all env.

If you have your secrets juts in the stack because they are member only in a object. They will be hard to find.
So Enviroment variables are not that save in general.

Regards
Falk
