### ISSUE TITLE
Url hostname is no longer validated

### ISSUE THREAD

**Issue by mardiros** [pydantic/pydantic#9000]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi everyone, I am currenlty migrating yet another codebase from pydantic 1 to pydantic 2 and have an issue
with Url validation that changed a lot (was a string, and now it is not but I can handle that).

My probleme is that in any url, a hostname can't starts with a `-` (other rules exists, such as segment size).

Here is a sample of code in pydantic v1 that works

```
Python 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydantic import BaseModel, AnyHttpUrl, Field, version
>>> print(version.version_info)
<cyfunction version_info at 0x7e17bc94e5a0>
>>> print(version.version_info())
             pydantic version: 1.10.13
            pydantic compiled: True
                 install path: /home/guillaume/.cache/pypoetry/virtualenvs/xxx-v1yMrRj-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
                     platform: Linux-6.7.4-arch1-1-x86_64-with-glibc2.39
     optional deps. installed: ['typing-extensions']
>>> from pydantic import BaseModel, AnyHttpUrl, Field, version
>>> class M(BaseModel):
...      u: AnyHttpUrl = Field()
...
>>> M(u="http://-x/")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for M
u
  URL host invalid (type=value_error.url.host)

```

while migrating a project to pydantic 2, I lost this check and let improper url enter in my database:

### Example Code

```Python
from pydantic import BaseModel, AnyHttpUrl, Field
class M(BaseModel):
  u: AnyHttpUrl = Field()

M(u=Url('http://-x/'))  # should raise a ValidationError, -x is not a valid hostname

```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/guillaume/.cache/pypoetry/virtualenvs/sequoia-base3-oGZ-ftSE-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
                     platform: Linux-6.7.4-arch1-1-x86_64-with-glibc2.39
             related packages: typing_extensions-4.7.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@mardiros,

Thanks for reporting this. Looks related to https://github.com/pydantic/pydantic/issues/7874. We use the [URL Rust Crate](https://github.com/servo/rust-url) which makes decisions based on the [URL Standard](https://url.spec.whatwg.org/).

Going to close this for now, but I'd recommend opening an issue there regarding your question about URL validity!

**Comment by mardiros** [comment]
For the update, from [rust-url](https://github.com/servo/rust-url/issues/913) and [whatwg-url](https://github.com/jsdom/whatwg-url/issues/271)

They consider themself has "parser" not "validator". So there will never check hostname format here.

Pydantic is a validator (a user data validation library), so the url host invalid is a regression from pydantic 1 that I can live with.
