### ISSUE TITLE
Mypy type checking not working properly for classes that inherit properties after v2.6.4

### ISSUE THREAD

**Issue by pengelsman7** [pydantic/pydantic#9007]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In v2.6.3 I had lines of code that rightfully needed type checking or mypy ignores for `union-attr` since the fields were typed like `<type> | None`. However, after I upgraded to v2.6.4 mypy is now telling me many of these type ignores are no longer necessary even though I didn't change my code at all. It seems to only be happening for classes that inherit from another model as you can see from my example. Anything that is just a `BaseModel` class seems to still require the type checking. I imagine its probably related to the change in this [PR](https://github.com/pydantic/pydantic/pull/8932)?

### Example Code

```Python
from pydantic import BaseModel


class Foo(BaseModel):
    id: int | None


class Bar(BaseModel):
    foo: Foo | None


class Baz(Bar):
    name: str


b = Bar(foo={"id": 1})
z = Baz(foo={"id": 1}, name="test")


assert z.foo.id == 1  # needed an ignore before
assert b.foo.id == 1  # type: ignore[union-attr]
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
                 install path: /fn/lib/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Mar 10 2024, 01:11:42) [GCC 10.2.1 20210110]
                     platform: Linux-6.5.13-orbstack-00122-g57b8027e2387-aarch64-with-glibc2.31
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by pengelsman7** [comment]
I am using mypy v1.9.0 and I am actually using `strict_optional=true`. Here is the whole config:

```
[tool.mypy]
pretty = true

color_output = true

show_column_numbers = true
show_error_context = true
show_error_codes = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

check_untyped_defs = true
no_implicit_optional = true
strict_optional = true

disallow_untyped_calls = true
disallow_untyped_defs = true

plugins = ["pydantic.mypy"]
```

**Comment by dmontagu** [comment]
Thank you for that info @pengelsman7, I was able to confirm locally that #9008 seems to fix your issue. It would be great if you could confirm if there are still any misbehaviors not addressed by that PR but even if you can't I think we'll merge and release it soon since it at least fixes some bugs.

**Comment by pengelsman7** [comment]
I just confirmed that your PR fixed all the issues I saw, thanks so much for the quick turn around!

**Comment by sydney-runkle** [comment]
Awesome! We'll get #9008 across the line before the 2.7.0b1 release, so this should be fixed soon!
