### ISSUE TITLE
Unable to use ValidationError.from_exception_data

### ISSUE THREAD

**Issue by builder555** [pydantic/pydantic#9010]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I think I'm missing something. Using the [API docs](https://docs.pydantic.dev/latest/api/pydantic_core/#pydantic_core._pydantic_core.ValidationError.from_exception_data) I came up with the following example. 
It's complaining "TypeError: ValueError: 'error' required in context", however there is no 'error' field anywhere that I can see.

Basically, what I'm trying to do is replicate the default ValidationError behaviour but in a custom `model_validator`. If I just raise a generic ValueError, it doesn't have `loc` specified.

### Example Code

```Python
from pydantic_core import InitErrorDetails
from pydantic import ValidationError

raise ValidationError.from_exception_data(
    title="Incorrect value specified", 
    line_errors=[InitErrorDetails(
            loc=("body", "field"), 
            input="Invalid value", 
            type="value_error"
        )]
)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/me/testapp/.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.0 (main, Oct  2 2023, 12:03:24) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@builder555,

You'll need to pass some additional information to the `ctx` parameter of the `InitErrorDetails` constructor. See https://github.com/pydantic/pydantic-core/blob/8db3a6f45b4af2e977a56af1f34099b8f5ff01eb/python/pydantic_core/__init__.py#L94 for more details on that class. 

In your case, you need to provide an `error` key / value pair to the `ctx` dict.
