### ISSUE TITLE
Validation not working for Annotated with conlist

### ISSUE THREAD

**Issue by eliasdorneles** [pydantic/pydantic#9011]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using `conlist` within `Annotated` isn't triggering validation -- is this expected?

### Example Code

```Python
from typing import Annotated
from pydantic import BaseModel, conlist

class MyModel(BaseModel):
    li: Annotated[list, conlist(int, min_length=2)]

print(MyModel(li=[]))  # I expected this to raise a validation error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /tmp/venv-XGP7/lib/python3.11/site-packages/pydantic
               python version: 3.11.0 (main, Nov 28 2022, 13:51:36) [GCC 11.3.0]
                     platform: Linux-6.5.0-18-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by lukasz-matter** [comment]
I have the same problem - `max_length` doesn't work either.

**Comment by eliasdorneles** [comment]
> conlist itself is an Annotated[list, ...], so you can just use conlist without the Annotated!:

Indeed that works, but then mypy fails. Should I report this as a mypy bug? :thinking:

**Comment by Viicos** [comment]
> Indeed that works, but then mypy fails. Should I report this as a mypy bug? 🤔

Function calls are not allowed by type checkers, hence the `con*` functions are discouraged (see the warning [here](https://docs.pydantic.dev/dev/api/types/#pydantic.types.constr)).

In your case, you can use instead:

```python
from typing import Annotated

from pydantic import BaseModel

from annotated_types import Len


class MyModel(BaseModel):
    li: Annotated[list[int], Len(2)]
```
