### ISSUE TITLE
Parsing of float as datetime changes depending on the deprecation warnings handling setting

### ISSUE THREAD

**Issue by Dlougach** [pydantic/pydantic#9018]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The result of parsing a float value into a datetime field appears to depend on the setting of `-W` flag for the python interpreter. Here is some explanation:

- `validate_datetime` method [uses](https://github.com/pydantic/pydantic-core/blob/9efbc163a7b1e99c9240959946df504a72dd67f0/src/input/input_python.rs#L670C19-L670C23) `extract_i64` which itself relies on `PyLong_AsLong` method
- In case the underlying object is not an integer but can be implicitly casted to int (such as with `float`), the return value [depends](https://github.com/python/cpython/blob/200762426b4b9878c33cdef620aa1a51631dd5df/Objects/longobject.c#L231) on the return value of `PyErr_WarnFormat` function.

This peculiar bug conveniently avoids being detected by automated tests, because most of those do run under `-Werror`.

### Example Code

```Python
from pydantic import BaseModel
from datetime import datetime

class TestModel(BaseModel):
    dt: datetime

# With `python -Werror`: datetime(2017, 5, 5, 19, 27, 24, 883309)
# With `python -Walways`: datetime(2017, 5, 5, 19, 27, 24) <- without microseconds
# Also shows the following warning:
#  DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
print(TestModel(dt=1_494_012_444.883_309))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: <redacted>
               python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by Dlougach** [comment]
Also I don't know whether it's related but handling of floats as strings for input is also a bit awkward:

```python
print(TestModel(dt="1494012444.883309"))
# dt=datetime.datetime(2017, 5, 5, 19, 27, 24, 883309, tzinfo=TzInfo(UTC))

print(TestModel(dt="1494012444883.309"))
# dt=datetime.datetime(2017, 5, 5, 19, 27, 25, 192082, tzinfo=TzInfo(UTC))
# Loss of precision?
```

**Comment by samuelcolvin** [comment]
Thanks @Dlougach for reporting. This could perhaps be related to https://github.com/PyO3/pyo3/pull/3742 cc @davidhewitt
