### ISSUE TITLE
Different output of V2 `model_dump_json` compared to V1 `json`

### ISSUE THREAD

**Issue by pkotnis** [pydantic/pydantic#9019]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When I read V2 migration guide, I did not expect major changes to how `model_dump_json` will work compared to V1's `json`. However, it seems like there's a difference in how the new method handles non-ASCII characters.

Is this expected behaviour?

Attached code produces different results for V2 and V1

```
V1 {"test": "\u00bfC\u00f3mo est\u00e1s?"}
V2 {"test":"¿Cómo estás?"}
```

### Example Code

```Python
from pydantic.v1 import BaseModel as BaseModelV1
from pydantic import BaseModel as BaseModelV2


class MessageV1(BaseModelV1):
    test: str


class MessageV2(BaseModelV2):
    test: str


message_v1 = MessageV1(test="¿Cómo estás?")
message_v2 = MessageV2(test="¿Cómo estás?")

print("V1", message_v1.json())
print("V2", message_v2.model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /Users/xxx/.local/share/virtualenvs/xxx-Fhklx5WJ/lib/python3.8/site-packages/pydantic
               python version: 3.8.17 (default, Nov  6 2023, 20:47:47)  [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.2.1-arm64-arm-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.0
```

**Comment by sydney-runkle** [comment]
I've also marked this with a documentation tag, and will open a PR later this week to update the migration guide with a note on this change :).

**Comment by pkotnis** [comment]
@sydney-runkle , thanks for the update.

Solution suggested in #8825 can indeed help, but won't work if your pydantic objects contains types that `json.dumps` cannot handle, such us `datetime` for example.

```python
import json
from datetime import datetime
from pydantic import BaseModel as BaseModel


class Message(BaseModel):
    text: str
    date: datetime


message = Message(text="¿Cómo estás?", date=datetime.now())
print(json.dumps(message.model_dump(), ensure_ascii=True))

# TypeError: Object of type datetime is not JSON serializable
```

The runtime flag/config setting that you mentioned would be a great addition. Cheers.

**Comment by sydney-runkle** [comment]
@pkontis,

You can use `model_dump(mode='json')` to make this work!

**Comment by iQiexie** [comment]
> model_dump(mode='json')

In this case I get `pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `sort_model`: TypeError: Object of type datetime is not JSON serializable`

**Comment by sydney-runkle** [comment]
@iQiexie, if you can provide a reproducible example, I'd be happy to help out!

**Comment by iQiexie** [comment]
> @iQiexie, if you can provide a reproducible example, I'd be happy to help out!

It just started working somehow... I think I was doing something wrong and now I can't find the code snipped I was getting this error on

Thank you for the willing to help!
