### ISSUE TITLE
False positive 'Invalid value for "Config.extra" [pydantic-config]'

### ISSUE THREAD

**Issue by Apakottur** [pydantic/pydantic#9021]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Consider this code:
```python
# test.py
from pydantic import BaseModel, ConfigDict

def condition() -> bool:
    return True

class MyModel(BaseModel):
    model_config = ConfigDict(extra="ignore" if condition() else "forbid")
```
```toml
# mypy.toml
[tool.mypy]
plugins = ["pydantic.mypy"]
```

Running `mypy --config mypy.toml test.py` gives
```
test.py:10: error: Invalid value for "Config.extra"  [pydantic-config]
Found 1 error in 1 file (checked 1 source file)
```

The error is incorrect, since the value is a valid literal in both cases, whicever branch of the condition is executed.

Might be related to https://github.com/pydantic/pydantic/issues/3481.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: .venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb 25 2024, 16:35:05) [GCC 11.4.0]
                     platform: Linux-6.1.79-060179-generic-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.2.1 mypy-1.9.0 pyright-1.1.353 typing_extensions-4.10.0 pydantic-extra-types-2.6.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Apakottur,

Hmm, thanks for reporting this. Seems like a bug, but a pretty minor one. Maybe @dmontagu has an idea for an easy fix...

**Comment by Viicos** [comment]
This has to do with how `mypy` handles union of types (see [playground](https://mypy-play.net/?mypy=latest&python=3.12&gist=23761de20dfe50a6b6f073561f98648d)). I don't think Pydantic can do much here.

For reference, pyright will handle this correctly as `"ignore" if condition() else "forbid"` is inferred as `Literal["ignore", "forbid"]`.

**Comment by dmontagu** [comment]
@Viicos is right; suggested approach compatible with mypy:
```python
# test.py
from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

def condition() -> bool:
    return True

_my_model_extra: Literal['ignore', 'forbid'] = "ignore" if condition() else "forbid"

class MyModel(BaseModel):
    model_config = ConfigDict(extra=_my_model_extra)
```

I haven't confirm this works but I think it should. If it doesn't, I am more confident the following would work:

```python
from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

def condition() -> bool:
    return True

def _get_my_model_extra() -> Literal['ignore', 'forbid']:
    if condition():
        return 'ignore'
    else:
        return 'forbid'

class MyModel(BaseModel):
    model_config = ConfigDict(extra=_get_my_model_extra())
```

**Comment by dmontagu** [comment]
@Apakottur thanks for the info, I see the problem — the issue is that we have additional checks in the plugin itself. I think I'm going to make this check more lax so it only errors if you use a string or member and it isn't the right value. If you use a conditional expression etc. it just won't type check the value (I think that's hard to do in a plugin, but if anyone knows a good way I will be happy to incorporate it), but note that if you use `ConfigDict` like you have' you'll get proper type checking from the usual non-plugin type checks, so this seems like a good solution.
