### ISSUE TITLE
Request: supporting tear down logic in `BaseModel` or `Field`

### ISSUE THREAD

**Issue by jamesbraza** [pydantic/pydantic#9032]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be cool if `BaseModel` or `Field`s had some sort of tear-down handler supported. That way one can clean up resources associated with the model or field as needed.

What I am seeing is a `BaseModel` working in a temporary directory, and it would be nice if the `BaseModel` could delete the temporary directory itself upon teardown.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@jamesbraza,

Thanks for your feature request. Could you provide a more explicit example of what you're looking for, perhaps with some code?

My initial thought is that you could probably achieve this with basic contextmanager that contains your desired teardown logic...

**Comment by jamesbraza** [comment]
Hi @sydney-runkle I agree in general one can have a higher level entity use a context manager, instead of a `BaseModel` itself housing tear-down logic.

My use case (I inherited) involves a temporary directory made by [`tempfile.mkstemp`](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) in a `default_factory`.

```python
import tempfile

from pydantic import BaseModel, Field


class SomeModel(BaseModel):
    directory: str = Field(
        default_factory=lambda: tempfile.mkstemp()[1]
    )
```

The "higher level" entity here (instantiator of the `BaseModel`) relies on the `BaseModel`'s default factory, so it's not looking to clean up the temporary directory. Thus, I would like the `BaseModel` itself to clean up the temporary directory.

As a workaround for teardown, what I can do is use `__del__`:

```python
import os
import tempfile

from pydantic import BaseModel, Field


class SomeModel(BaseModel):
    directory: str = Field(
        default_factory=lambda: tempfile.mkstemp()[1]
    )

    def __del__(self) -> None:
        os.remove(self.directory)
```

What I would like to do is not use `__del__`, but instead use an official Pydantic hook:

```python
import os
import tempfile

from pydantic import BaseModel, Field


class SomeModel(BaseModel):
    directory: str = Field(
        default_factory=lambda: tempfile.mkstemp()[1],
        teardown=lambda self: os.remove(self.directory)
    )
```

Let me know what you think, hopefully that clarifies things

**Comment by sydney-runkle** [comment]
@jamesbraza,

What's the use case for not using `__del__`? If there was a custom `pydantic` hook here, we'd just implement this as `__del__` on the model. Closing for now, as I think `__del__` is your best shot for controlling behavior upon garbage collection on instances.
