### ISSUE TITLE
Mypy plugin swallows type error when using incorrect object type

### ISSUE THREAD

**Issue by Apakottur** [pydantic/pydantic#9036]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The Pydantic mypy plugin seems to swallow a Mypy error.
Consider the following code:
```python
# test.py
from dataclasses import dataclass
from pydantic import BaseModel


@dataclass
class First:
    y: int


@dataclass
class Second:
    y: int


class MyModel(BaseModel):
    x: Second


_ = MyModel(x=First(y=1))
```

And the following config file:
```toml
# mypy.toml
[tool.mypy]
plugins = ["pydantic.mypy"]
```

Running `mypy test.py` gives the correct error:
```txt
test.py:20: error: Argument "x" to "MyModel" has incompatible type "First"; expected "Second"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

Running `mypy --config mypy.toml test.py` gives:
```txt
Success: no issues found in 1 source file
```

Am I missing something or is the Pydantic mypy plugin swallowing the error incorrectly?

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb 25 2024, 16:35:05) [GCC 11.4.0]
                     platform: Linux-6.1.82-060182-generic-x86_64-with-glibc2.35
             related packages: pydantic-settings-2.2.1 mypy-1.9.0 pyright-1.1.354 typing_extensions-4.10.0 pydantic-extra-types-2.6.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Apakottur,

Thanks for reporting this. @dmontagu is on the case :).

**Comment by dmontagu** [comment]
@Apakottur you need to add:
```
[tool.pydantic-mypy]
init_typed = true
```
to your mypy.toml.

See https://docs.pydantic.dev/latest/integrations/mypy/#configuring-the-plugin for more details.

The reason this isn't enabled by default is that it would result in type errors if you relied on Pydantic's field validation to change types (e.g., if you had a field of type `datetime` and were passing in a string), so we made it opt-in. When the mypy plugin was released, I think that was probably a more common pattern than it is today now that VSCode and other editors use `@dataclass_transform` for type checking (which will show a type error for such things).

Either way, setting the `init_typed = true` setting for the pydantic plugin should resolve your issue.

**Comment by Apakottur** [comment]
Thanks @dmontagu , setting `init_typed=true` fixes the issue for me.
