### ISSUE TITLE
In Pydantic v2, v1.BaseModel objects do not validate properly as fields of v2 models

### ISSUE THREAD

**Issue by ptomecek** [pydantic/pydantic#9038]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

As we have migrated to pydantic 2, we have discovered that when other libraries (outside our control) use v1.BaseModel to accomplish pydantic 2 compatibility, that these models do not validate properly as fields of our native pydantic 2 models. 

We have worked around this by adding an annotation around use of v1 models in v2 that implements the correct validation logic, but it would be nice if it worked natively.

### Example Code

```Python
from pydantic.v1 import BaseModel as BaseModelV1
from pydantic import BaseModel
class A(BaseModelV1):
    pass
class B(BaseModel):
    a: A
    
B(a=A())

# Workaround:
from pydantic import PlainValidator
from typing import Annotated
class C(BaseModel):
    a: Annotated[A, PlainValidator(A.validate)]
C(a=A())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /isilon/home/pt10597/.conda/envs/ccrt39-0.9.0/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)  [GCC 12.3.0]
                     platform: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
             related packages: typing_extensions-4.10.0 fastapi-0.110.0 pydantic-settings-2.2.1 mypy-1.7.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@ptomecek,

Thanks for your question. As reported in [the migration](https://docs.pydantic.dev/latest/migration/#changes-to-pydanticgenericsgenericmodel) guide:

> Mixing of V1 and V2 models is not supported which means that type parameters of such generic BaseModel (V2) cannot be V1 models.

Also, see this duplicate issue where we updated the docs to reflect this: https://github.com/pydantic/pydantic/issues/7637

**Comment by ptomecek** [comment]
@sydney-runkle My apologies! I had skipped that part of the docs at the time as we weren't planning to use v1 models, but clearly  it's relevant now that we have dependencies that do.
