### ISSUE TITLE
Support for validating an instance within a context.

### ISSUE THREAD

**Issue by DLukeNelson** [pydantic/pydantic#9065]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

We are using Fastapi and Pydantic to excellent effect. However, there are some validations that we perform that can not ([should not?](https://github.com/pydantic/pydantic/issues/1227#issuecomment-585723753)) be done in a pydantic validator. (Mostly database/world-state kinds of validations)

I think a concrete example is an easy way to show my situation. Given a `create_user` endpoint in FastAPI:
```
@router.post("/user", response_model=schema.UserOut)
def create_user(
    user: Annotated[schema.UserCreate, Body()],
    db: Annotated[Session, Depends(deps.db_session)],
):
    db_user: User | None = repository.get_user_by_email(db, email=user.email)
    if db_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    created_user = repository.create_user(db=db, user=user)
    return created_user
```
The first few lines are all related to checking data validity. To me, one of the biggest selling points of pydantic has been how smooth it is to implement data rules/constraints directly on the data model itself. Not shown in the snippet: The `UserCreate` model validates that:
* email addresses have the correct form
* usernames meet requirements such as min/max length, and supported characters
* etc.

The pain point for me is twofold:
1. Why does a uniqueness check have to be done separately? It feels like a very similar data constraint. I do see the difference, in being inherent to the data versus dependent on context, but it would feel really clean to be able to describe this in a validator that is implemented right on the data model.
2. I'd like to be able to provide "pydantic-style error messaging" for the above. Currently, it seems I have to implement myself a data structure that matches the schema of pydantic's error messaging. At least, I did not see in the docs a way to provide my own error messages (outside of the error messages raised in validators, which do not apply to this use case).

So, the feature request is for a pydantic model to have a `validate_in_context` method, which would change the above code to:
```
@router.post("/user", response_model=schema.UserOut)
def create_user(
    user: Annotated[schema.UserCreate, Body()],
    db: Annotated[Session, Depends(deps.db_session)],
):
    user.validate_in_context(db=db)  # raises 422 error
    created_user = repository.create_user(db=db, user=user)
    return created_user
```
And the `UserCreate` model may look like:
```
class UserCreate(BaseModel):
    # fields

    # old regular validators

    @context_validator
    def unique_email(self, context: Context) -> "UserCreate":
        db = context.get('db')
        db_user: User | None = repository.get_user_by_email(db, email=user.email)
        if db_user:
            raise ValueError(f"Email address '{self.email}' is already registered")
        return self
```

This is fairly similar to https://docs.pydantic.dev/latest/concepts/validators/#using-validation-context-with-basemodel-initialization but has a couple of key differences.
* `validate_in_context` is intended to be called directly on an instance of the model, with a parameter passed in for context. This accurately represents the use case: "Given a valid data instance, is it allowed in <some_context>." This enforces a separation between
    * validating/parsing the data as-provided
    * testing that a model is valid within a context.
* It makes testing very simple since it is easy to pass in mock objects as a context.
* Even if model instantiation is (somewhat) outside of my control (such as with FastAPI), I can take resulting instances and validate them within some context.
* By passing the context (which may do I/O) in to a created model, it sanctions this as a place where it is acceptable to do I/O based validations.

## Why should this be part of pydantic?
Data validation is the core purpose of pydantic. The ability to report on errors within the data in a clean and organized way is what makes it so powerful. The line between "valid data", and "inherently valid, but cannot exist in the intended context" (ie. a uniqueness violation) is blurry. Making `validate_in_context` a part of pydantic can clean up a lot of error handling around the creation of models, keep all of the data constraints in one place, and allow for seamless messaging of errors to clients.

This is something I would be interested in working on myself, although I would probably need some help. Regardless, I wanted to raise the request and see if this is something that would be in-line with future vision.

Thanks for consideration.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Marking this as not planned for now - I still think support for `context` in model validation / serialization calls fits most needs.
