### ISSUE TITLE
mypy plugin: `init_typed=False` does not work with `pydantic.v1`

### ISSUE THREAD

**Issue by aviau** [pydantic/pydantic#9067]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am using `pydantic.v1.BaseModel`  (which is in pydantic v2.. I hope I am reporting the bug at the right place).

And it looks like the `init_typed=False` setting of the mypy plugin does not work.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/alexandre.viau/git/flare/pyro/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 (main, Nov 28 2023, 10:03:48) [Clang 15.0.0 (clang-1500.0.40.1)]
                     platform: macOS-14.4-arm64-arm-64bit
             related packages: typing_extensions-4.10.0 mypy-1.7.0
                       commit: unknown
```
```

**Comment by sydney-runkle** [comment]
@dmontagu,

Could you please take a look?

**Comment by dmontagu** [comment]
Can you share your mypy config? You might need to add `pydantic.v1.mypy` to your list of mypy plugins instead of `pydantic.mypy` for v1 support.

**Comment by aviau** [comment]
My config was like so:
```
[mypy]
plugins = sqlalchemy.ext.mypy.plugin,
    pydantic.mypy

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
```

So I confirm that I was not using `pydantic.v1.mypy`!.

Would it make sense to document it here? https://docs.pydantic.dev/latest/integrations/mypy/#enabling-the-plugin

**Comment by sydney-runkle** [comment]
@aviau,

If you add the `pydantic.v1.mypy` plugin, does everything work as expected? Yep, we can definitely add a note to the docs.

**Comment by aviau** [comment]
Yep, I confirm it works!

**Comment by aviau** [comment]
Now that I know that there are two mypy plugins, I think it would even make sense to have a config for v1 and a different config for v2. It would support use cases where people used `init_typed=False` in v1 and would like to migrate to v2 using `init_typed=True`, but maybe this is outside of this bug.

I am happy closing this bug with just the doc update!

**Comment by sydney-runkle** [comment]
@aviau,

Would you be willing to open a PR with the docs update?

**Comment by aviau** [comment]
@sydney-runkle Sorry I couldn't get to it before you. Thank you for your help! :)
