### ISSUE TITLE
Unexpected error message while using properties with pydantic models

### ISSUE THREAD

**Issue by bcdurak** [pydantic/pydantic#9070]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello, 

I ran into an issue while using a property with a pydantic class which led to an unexpected error.

To reproduce this error, you can simply create a pydantic class, define a `property` in it, and raise an `AttributeError` inside the `property` function. Instead of displaying this error, the stack trace will say:

`AttributeError: 'MyModel' object has no attribute 'my_property'`

Important to note, that this is the case only if `extra` is set to `"allow"` in the corresponding `ConfigDict`. If this line is disabled, the code raises the right error.

While it seems simple to see what the root cause of the failure is here in the example code, in complicated cases (where the call on the property executes some logic that ultimately leads to an `AttributeError`), this can be problematic and confusing as this does not showcase the correct error.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict


class MyModel(BaseModel):

    @property
    def my_property(self):
        """A random property."""
        raise AttributeError("Original Error!")

    model_config = ConfigDict(extra="allow")


my_model = MyModel()
my_model.my_property
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
pydantic-core version: 2.16.3
pydantic-core build: profile=release pgo=false
install path: /Users/bariscandurak/.pyenv/versions/3.9.16/envs/zenml-temp/lib/python3.9/site-packages/pydantic
python version: 3.9.16 (main, Mar 11 2024, 18:29:02)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-13.5.1-arm64-arm-64bit
related packages: fastapi-0.110.0 typing_extensions-4.10.0 mypy-1.7.1 pydantic-settings-2.2.1
commit: unknown
```

**Comment by sydney-runkle** [comment]
@bcdurak,

Huh, that's odd! Thanks for reporting. Definitely a bug. Happens when you have the `computed_field` decorator over said property as well, which is even more concerning.

**Comment by NeevCohen** [comment]
@sydney-runkle I looked into this and it seems that the problem is in the [`Model.__getattr__()`](https://github.com/pydantic/pydantic/blob/e58134b876a340863ea417f6c7967c9ed14ec03b/pydantic/main.py#L767) method.

```python
try:
    pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
except AttributeError:
    pydantic_extra = None

if pydantic_extra is not None:
    try:
        return pydantic_extra[item]
    except KeyError as exc:
        raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
# ...
# Regular attribute handling continues here
```

When setting `extra=True` in `model_config`, `__pydantic_extra__` is defined as an empty dictionary. That means that execution will enter this `if` block and try to get the attribute from the `__pydantic_extra__` dict, which would be wrong.
I changed the `if` statement to be 

```python
if pydantic_extra:
```

That seems to fix the issue.

I opened a PR #9082

**Comment by bcdurak** [comment]
Thank you @NeevCohen @sydney-runkle!
