### ISSUE TITLE
Base64Bytes with newlines

### ISSUE THREAD

**Issue by jschlyter** [pydantic/pydantic#9072]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Under the hood, `Base64Bytes` use standard library `base64.encodebytes` that inserts a newline after every 76 bytes of output, as well as ensuring that there is a trailing newline. This makes some base64 decoders (e.g. iOS) sad. Fix is to use `b64encode()` instead of `encodebytes()`.

It is easy to work around by using a custom encoder, but IMHO there's no point in adding the newlines.

### Example Code

```Python
import os
from base64 import b64encode
from pydantic import Base64Bytes, BaseModel

class Foo(BaseModel):
    random: Base64Bytes

print(Foo(random=b64encode(os.urandom(32)).decode()).model_dump_json())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/jakob/Library/Caches/pypoetry/virtualenvs/uas-YdoMfBSh-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.4-arm64-arm-64bit
             related packages: typing_extensions-4.10.0 fastapi-0.109.2 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@jschlyter,

I'm concerned that implementing a change under the hood would cause breaking changes for existing users, and if it's easy enough to customize, I think this kind of change might be best in user code...

**Comment by jschlyter** [comment]
```
class Base64EncoderSansNewline(Base64Encoder):
    @classmethod
    def encode(cls, value: bytes) -> bytes:
        return base64.b64encode(value)


Base64Bytes = Annotated[bytes, EncodedBytes(encoder=Base64EncoderSansNewline)]
```

**Comment by jschlyter** [comment]
The questions is; who really want base64 with embedded newlines?

**Comment by sydney-runkle** [comment]
Right, I understand the sentiment, but given that it's easy to change on the user side of things with a custom encoder, I don't think this is a change we're going to make in the near future. Closing for now. Thanks for adding your workaround for others to reference!

**Comment by nioncode** [comment]
Can this please be added to the documentation somewhere? I thought I'm doing something wrong when newlines showed up in my serialized objects, which is very surprising. Could a non-newline version be added to pydantic to simplify onboarding of new users?

**Comment by sydney-runkle** [comment]
See https://docs.pydantic.dev/2.8/api/types/#pydantic.types.EncodedBytes for some more helpful docs!

**Comment by woodruffw** [comment]
Hey @sydney-runkle!

I can understand why this can't be immediately changed for compatibility reasons, but I wanted to add another datapoint here: this recently bit us pretty badly on PyPI's rollout of [PEP 740](https://peps.python.org/pep-0740/), which specifies base64-encoded objects that would have been silently mis-encoded with the current Pydantic APIs.

We got lucky and happened to catch the unexpected behavior right before it landed in production, but had we not caught it we would have had to do data migrations against PyPI itself for all projects that currently using Trusted Publishing to publish to PyPI, which includes [pydantic itself](https://github.com/pydantic/pydantic/blob/3a821f121c6b2dbf87f110944321f2ecf2ca4fbc/.github/workflows/ci.yml#L425-L458).

So, I suppose I have two questions here:

1. Will Pydantic consider making a behavioral change to this API in a future major release?
2. Could the docs be updated to additionally warn users (in scarier language than is currently present) that `{encode,decode}bytes` don't do "base64" in the sense that users conventionally understand? The docs currently only mention differences in the behavior w/r/t "URL safe" base64, which might lead users to believe that the current types are fine when they aren't for all use cases.

If (2) sounds appropriate, I'm happy to contribute those docs 🙂

**Comment by sydney-runkle** [comment]
Hey folks, thanks for following up. Will chat with our team tomorrow and get back to you.
