### ISSUE TITLE
model.model_copy doesn't transform dicts into models

### ISSUE THREAD

**Issue by ZackPlauche** [pydantic/pydantic#9077]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Nested models remain as dicts on nested data instead of being converted to their proper objects (see Example Code below)

This makes no sense and is unintuitive.

In the below example, you'd have to write:
```py
merged_model = ModelB.model_validate(model_b_1.model_copy(update=model_b_2.model_dump(include=['model_a']).model_dump())
```
Which even throws an warning:
```py
UserWarning: Pydantic serializer warnings:
  Expected `ModelA` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

### Example Code

```Python
from pydantic import BaseModel



class ModelA(BaseModel):
    name: str

model_a = ModelA(name='jeff')

class ModelB(BaseModel):
    name: str
    model_a: ModelA | None = None


model_b_1 = ModelB(name='bob')
model_b_2 = ModelB(name='frank', model_a=model_a)

merged_model = model_b_1.model_copy(update=model_b_2.model_dump(include=['model_a'])

assert isinstance(merged_model.model_a, ModelA)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\zackp\.virtualenvs\platform_automator--mWSu_5p\Lib\site-packages\pydantic        
               python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
                     platform: Windows-10-10.0.22621-SP0
             related packages: fastapi-0.110.0 typing_extensions-4.10.0
                       commit: unknown
```

There's just no way this is the only way to update a new model. Why convert it to a dict? Just put it back to it's object! Otherwise it's not a copy! 🤷‍♂️ It's altering the data within that model.

**Comment by chu-mirror** [comment]
An excerpt from doc string of model_copy,

>Args:
>    update: Values to change/add in the new model. Note: the data is not validated
>        before creating the new model. You should trust this data.
>    deep: Set to `True` to make a deep copy of the model.
>
>Returns:
>    New model instance.

it might be the behaviour rather than a bug according to _Note: the data is not validated before creating the new model_.

This works:
```
merged_model = model_b_1.model_copy(update={"model_a" : model_b_2.model_a})
```

So if you want to update a part of a model, validate that part first then pass it to the model to be updated.

**Comment by sydney-runkle** [comment]
@ZackPlauche,

As the `model_copy` API docs state, `model_copy`'s `update` argument expects trusted data, which is not revalidated: https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_copy. Thus, this behavior is as expected.

**Comment by sydney-runkle** [comment]
You can do the following instead:

```py
from pydantic import BaseModel

class ModelA(BaseModel):
    name: str

model_a = ModelA(name='jeff')

class ModelB(BaseModel):
    name: str
    model_a: ModelA | None = None


model_b_1 = ModelB(name='bob')
model_b_2 = ModelB(name='frank', model_a=model_a)

merged_model = model_b_1.model_copy(update={'model_a': model_a})
print(repr(merged_model))
#> ModelB(name='bob', model_a=ModelA(name='jeff'))

assert isinstance(merged_model.model_a, ModelA)
```

**Comment by ZackPlauche** [comment]
Ah ok! Got it, thanks! Wish the api had a way for revalidation there. Or a `model.update()` method to update a model's data from another one of the same model.
