### ISSUE TITLE
`default` values from `Field` being ignored in ThirdPartyType

### ISSUE THREAD

**Issue by saurookadook** [pydantic/pydantic#9083]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A few coworkers and I have been migrating from Pydantic v1 -> v2 in our application and have been running into issues with migrating our previous custom types for handling dates. 

We largely prefer to utilize instances of `Arrow` in our application code but also need to account for a number of scenarios when creating instances of various models, including but not limited to:
- receiving values of different types, primarily an ISO formatted `str` and a timestamp (_in seconds or milliseconds_) as an `int`
- optional fields may or may not be present on received data passed to the model but _should_  be present in the JSON-serialized output
- optional fields don't consistently have the same default values

The `ExampleRecord` class should hopefully summarize the different scenarios as code:
```python
class ExampleRecord(DeserializerModel):
    id: UUID
    description: Optional[str] = Field(...)
    published_on: DeserializerArrowType = Field(..., alias="publishedAt")
    published_date: Optional[DeserializerArrowType]
    completed_on: Optional[DeserializerArrowType] = None
    special_event_date: Optional[DeserializerArrowType] = Field(
        default=arrow.get(1970, 1, 1), alias="eventDate"
    )
```

Our implementation of the `DeserializerArrowType` class to handle these cases is _mostly_ getting the job done. However, we're encountering issues with the `default` values in `Field` being ignored.  We were hoping that we could access the details about the field being validated/serialized so that we could programmatically return the default type but the suggestions in the [Access to field names](https://docs.pydantic.dev/latest/concepts/types/#access-to-field-name) section of the Types doc didn't yield any results; in fact, adding a `__init__` to the class does nothing (_it doesn't even get called!_) and both `handler.field_name` and `info.field_name` are `None`.

I've delved through the docs to try to find examples/ideas of how this might be done but didn't find anything helpful; there are examples for all of the different "pieces" of our usage but there really aren't any examples of using a custom type with `Field` (_i.e. either `special_date: CustomDateType = Field(default=arrow.get(2000, 1, 1), alias="dawnOfNewAge")` or `special_date: Optional[CustomDateType] = Field(default="wut", alias="dawnOfNewAge")`_).

Our implementation is largely based off examples from:
- [Handling third-party types](https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types)
- #8737 

We actually also tried to utilize `Annotated` types but those wouldn't accept `Arrow`, either by itself or as part of a `Union`  🫠

I'm hoping that it'll be possible to access the `default` value within our class. In the case that it isn't, however, is there some other avenue you all would suggest we take?

### Example Code

```Python
# utils/pydantic_types.py
import arrow
from arrow import Arrow
from pydantic import (
    ConfigDict,
    BaseModel,
    GetCoreSchemaHandler,
    alias_generators
)
from pydantic_core import core_schema
from typing import Any


class DeserializerArrowType(arrow.Arrow):
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: GetCoreSchemaHandler,
    ) -> core_schema.CoreSchema:

        def validate_as_or_coerce_to_arrow(value, info):
            try:
                if isinstance(value, Arrow):
                    return value
                return arrow.get(value)
            except Exception:
                raise ValueError(
                    f"DeserializerArrowType: can not parse value {value} of type {type(value)}"
                )

        def arrow_serialization(value: Arrow, handler, info):
            if info.mode == "json" and value is not None:
                return int(value.int_timestamp * 1000)
            return value

        return core_schema.with_info_before_validator_function(
            function=validate_as_or_coerce_to_arrow,
            schema=core_schema.union_schema(
                [
                    core_schema.str_schema(),
                    core_schema.int_schema(),
                    core_schema.datetime_schema(),
                    core_schema.is_instance_schema(Arrow),
                ]
            ),
            serialization=core_schema.wrap_serializer_function_ser_schema(
                arrow_serialization, info_arg=True
            ),
        )


class DeserializerModel(BaseModel):
    model_config = ConfigDict(
        alias_generator=alias_generators.to_camel_case,
    )


# models/example.py
import arrow
from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID

from pydantic_utils import DeserializerArrowType, DeserializerModel


class ExampleRecord(DeserializerModel):
    id: UUID
    description: Optional[str] = Field(...)
    published_on: DeserializerArrowType = Field(..., alias="publishedAt")
    published_date: Optional[DeserializerArrowType]
    completed_on: Optional[DeserializerArrowType] = None
    special_event_date: Optional[DeserializerArrowType] = Field(
        default=arrow.get(1970, 1, 1), alias="eventDate"
    )
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
                 install path: /Users/some-guy/Development/Work/SubFolder/best-app-evar/server/.poetry-cache/virtualenvs/best-app-evar-dp-ODgI3-py3.9/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Nov  2 2023, 17:06:16)  [Clang 14.0.3 (clang-1403.0.22.14.1)]
                     platform: macOS-14.4-x86_64-i386-64bit
             related packages: typing_extensions-4.9.0 fastapi-0.109.1 mypy-1.4.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@saurookadook,

Thanks for the detailed question / bug report. Before we move forward, could you try pulling down the latest code from `main` and see if you're still experiencing this issues? I recall that we fixed some default value issues, which have yet to be released. Happy to help once we confirm that all of your concerns are still relevant!

**Comment by saurookadook** [comment]
@sydney-runkle welp, I was hoping that pulling the latest from `main` would be relatively easy but after a full day of fighting with Poetry and our Docker environment, I don't think I can reasonably test that the latest changes will solve the problem in the context of our application. 😅 

I _think_ we've figured out a workaround for now that we're ok with, despite it not being ideal. Do you have any idea when those recent changes will make it into the next release? I'd be happy to test it then!

**Comment by sydney-runkle** [comment]
@saurookadook,

Ah ok! We'll release the beta next week, and the official release the week after. I'll close this for now then, but feel free to ping me if you'd like to reopen later!

**Comment by saurookadook** [comment]
@sydney-runkle Sounds good 🙂 

And for anyone else having this issue, we ended up doing something like...

> NOTE: the following assumes the rest of the example provided in the issue description above

```python
def generic_validator_function_with_default(class_ref, value, info):
    return (
        value
        if value is not None
        else get_default_value_from_field_config(class_ref, info)
    )


def get_default_value_from_field_config(class_ref, info):
    field = class_ref.model_fields[info.field_name]
    return field.default_factory() if callable(field.default_factory) else field.default
    
class ExampleRecord(DeserializerModel):
    id: UUID
    description: Optional[str] = Field(...)
    published_on: DeserializerArrowType = Field(..., alias="publishedAt")
    published_date: Optional[DeserializerArrowType]
    completed_on: Optional[DeserializerArrowType] = None
    special_event_date: Optional[DeserializerArrowType] = Field(
        default=arrow.get(1970, 1, 1), alias="eventDate"
    )

    @field_validator("special_event_date", mode="before")
    @classmethod
    def handle_field_default(cls, value, info):
        return generic_validator_function_with_default(cls, value, info)

```

**Comment by rumbarum** [comment]
FYI, FastAPI compatable version is here,

```python
from typing import Any

import arrow
from pydantic import (
    GetCoreSchemaHandler,
    GetJsonSchemaHandler,
)
from pydantic.json_schema import JsonSchemaValue
from pydantic_core import core_schema


class ArrowPydantic(arrow.Arrow):
    @classmethod
    def __get_pydantic_core_schema__(
        cls,
        _source_type: Any,
        _handler: GetCoreSchemaHandler,
    ) -> core_schema.CoreSchema:
        def validate_by_arrow(value) -> arrow.Arrow:
            try:
                arr = arrow.get(value)
                return arr
            except Exception as e:
                raise ValueError(f"Arrow can not parse")

        def arrow_serialization(value: arrow.Arrow, _, info) -> str | arrow.Arrow:
            if info.mode == "json":
                return value.isoformat()
            return value

        return core_schema.no_info_before_validator_function(
            function=validate_by_arrow,
            schema=core_schema.union_schema(
                [
                    core_schema.str_schema(),
                    core_schema.datetime_schema(),
                    core_schema.is_instance_schema(arrow.Arrow),
                ]
            ),
            serialization=core_schema.wrap_serializer_function_ser_schema(
                arrow_serialization, info_arg=True
            ),
        )

    @classmethod
    def __get_pydantic_json_schema__(
        cls, core_schema: core_schema.CoreSchema, handler: GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        json_schema = handler(core_schema)
        json_schema = handler.resolve_ref_schema(json_schema)
        json_schema["examples"] = ["2024-02-06 13:38:18.000+00:00"]
        json_schema["type"] = "string"
        json_schema["format"] = "datetime"
        return json_schema

```
