### ISSUE TITLE
Add conversion from kebab-case to `to_snake` alias generator

### ISSUE THREAD

**Issue by maxkahan** [pydantic/pydantic#9084]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Some APIs return JSON with keys in kebab-case, which needs to be aliased to be usable as a field name in a Pydantic model.

It would be great to add conversion from kebab-case to the inbuilt alias generator `to_snake` (at least) so that when `__model_config__` is set, all fields in the model can be converted in this way.

Happy to be involved if that's helpful :)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@maxkahan,

One issue we've been running into with the built in alias generators recently is that there are some edge cases that various users disagree about regarding how a generator should behave.

Is there a specific case for why an alias generator such as `to_kebab` shouldn't reside in user code? That way, each user has the ability to fully customize said alias generator... I'm guessing you can just wrap a call to `to_snake` in `to_kebab` logic, like: `alias_generator = lambda x: to_snake(x).replace('_', '-'))` or something like that (syntax might not be perfect).

Closing for now, as I don't think it makes sense to add this behavior at this point.

**Comment by maxkahan** [comment]
@sydney-runkle I wasn't proposing a new alias generator, just to add replacement for kebab case strings into the `to_snake` [alias generator](https://github.com/pydantic/pydantic/blob/d6ca33337d34f0c57cc7a897b1821574d8631876/pydantic/alias_generators.py#L33) etc. So when I get a kebab-case response from an API, I can use `to_snake` to convert it the same way I would for APIs returning e.g. camel case. This should just be another line of regex substitution in the `to_snake` function?

I'm dealing with this myself in my own code, just thought it would be a nice-to-have if `to_snake` could deal with this case too. If you don't feel that's worth the addition then I'm happy for this to stay closed.

**Comment by sydney-runkle** [comment]
Ah I see. Feel free to submit a PR with this :) seems helpful!

**Comment by maxkahan** [comment]
@sydney-runkle sounds good, I'll put a PR for this on my to-do list 🙂
