### ISSUE TITLE
Float NaN to json serialization issue when used with Union

### ISSUE THREAD

**Issue by simonhoerdumbonde** [pydantic/pydantic#9086]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When creating a model with a union of two classes that each contain a field that use float('nan') as default value, then the json serialization is written as NaN and not null. The issue goes away when not using a Union of two classes, but only using a single class.
Having other floats, with float('nan') as default, present in the model leads to an inconsistent representation of the float nan value in the json serialization, since one is null and the other NaN, see example.

The issue might be related to #8440 and #8693, but is different since in those issues the fields are type hinted as Any, while in this issue the fields are floats.

### Example Code

```Python
from pydantic import BaseModel, Field

class Item1(BaseModel):
    Prop1: str = "Prop1"
    Value1: float = Field(default=float('nan'))

class Item2(BaseModel):
    Prop2: str = "Prop2"
    Value2: float = Field(default=float('nan'))

class MyModel(BaseModel):
    Value: float = Field(default=float('nan'))
    Item: Item1 | Item2

m = MyModel(Item=Item1())
print(m.model_dump_json())
# Output: {"Value":null,"Item":{"Prop1":"Prop1","Value1":NaN}}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/simon/PycharmProjects/pydantic_float_to_json_issue/venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Jan  8 2023, 15:07:12) [GCC 11.3.0]
                     platform: Linux-5.15.0-101-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@simonhoerdumbonde,

Thanks for the report. This definitely looks like a bug. I've added this to our 2.8 milestone, along with https://github.com/pydantic/pydantic/issues/8693, which has been bumped there.

**Comment by sydney-runkle** [comment]
Looks like this is fixed on `main`:

```py
from pydantic import BaseModel, Field

class Item1(BaseModel):
    Prop1: str = "Prop1"
    Value1: float = Field(default=float('nan'))

class Item2(BaseModel):
    Prop2: str = "Prop2"
    Value2: float = Field(default=float('nan'))

class MyModel(BaseModel):
    Value: float = Field(default=float('nan'))
    Item: Item1 | Item2

m = MyModel(Item=Item1())
print(m.model_dump_json())
# {"Value":null,"Item":{"Prop1":"Prop1","Value1":null}}
```

Feel free to ping me if you're still having trouble with this.
