### ISSUE TITLE
Only one validation output on constr mismatch

### ISSUE THREAD

**Issue by romanzdk** [pydantic/pydantic#9087]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

When I run example code below I would expect to get list of ALL validation errors that happened - ie. failed ZIP code and email address and potentially also second address of a User. However, I get only 1 error regarding the zip code - other errors are not shown. I tried using also Annotated/Field instead of constr but that did not help.

### Example Code

```Python
from datetime import date
from typing import List, Optional

from pydantic import BaseModel, EmailStr, ValidationError, constr, validator
from typing_extensions import Annotated


class Address(BaseModel):
    street: str
    city: str
    zip_code: constr(regex=r'^\d{5}$')
    # zip_code: Annotated[int, Field(pattern=r'^\d{5}$')]

class Profile(BaseModel):
    first_name: str
    last_name: str
    birth_date: date
    email: EmailStr
    addresses: List[Address]
    email_verified: bool = False  # Default value

    @validator('birth_date')
    def check_age(cls, v):
        today = date.today()
        age = today.year - v.year - ((today.month, today.day) < (v.month, v.day))
        if age < 18:
            raise ValueError('User must be at least 18 years old')
        return v

    @validator('email_verified', always=True)
    def check_email_verification(cls, v, values):
        if 'email' in values and not v:  # Checking if email is provided and not verified
            raise ValueError('Email must be verified')
        return v

# Example usage
try:
    user = Profile(
        first_name="John",
        last_name="Doe",
        birth_date="2000-01-01",	
        email="john.doe@example",
        addresses=[
            Address(street = "123 Main St", city = "Anytown", zip_code= "123456"),
            {"street": "124 Main St", "city": "Anytown", "zip_code": "54321"}

        ],
        email_verified=True
    )
    print(user)
except ValidationError as e:
    print(e.errors())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.14
            pydantic compiled: True
                 install path: /Users/romanzdk/Library/Caches/pypoetry/virtualenvs/python-project-Y8dcIiCp-py3.10/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Dec 22 2021, 10:27:42) [Clang 13.0.0 (clang-1300.0.27.3)]
                     platform: macOS-14.4-x86_64-i386-64bit
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Pydantic does not currently support exhaustive validation, so it stops after the first error on a given field and
reports that validation error. Relevant feature request, for tracking: https://github.com/pydantic/pydantic/issues/7476
