### ISSUE TITLE
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/pydantic/typing.cpython-39-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by dshwei** [pydantic/pydantic#9091]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

sql_eval openai 
args : Namespace(questions_file='data/questions_gen.csv', num_questions=10, model_type='oa', model='gpt-3.5-turbo-0613', adapter=None, url=None, num_beams=4, prompt_file=['prompts/prompt_openai.md'], output_file=['results/my_query_generator.csv'], parallel_threads=5, timeout_gen=30.0, timeout_exec=10.0, verbose=False)
Traceback (most recent call last):
  File "/demo/project/NL2SQL/sql-eval/main.py", line 29, in <module>
    from eval.openai_runner import run_openai_eval
  File "/demo/project/NL2SQL/sql-eval/eval/openai_runner.py", line 7, in <module>
    from query_generators.openai import OpenAIQueryGenerator
  File "/demo/project/NL2SQL/sql-eval/query_generators/openai.py", line 4, in <module>
    from openai import OpenAI
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/types/__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/types/edit.py", line 6, in <module>
    from .._models import BaseModel
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_models.py", line 33, in <module>
    from ._utils import (
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_utils/__init__.py", line 2, in <module>
    from ._utils import flatten as flatten
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_utils/_utils.py", line 22, in <module>
    from .._compat import is_union as _is_union
  File "/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_compat.py", line 55, in <module>
    from pydantic.typing import is_union as is_union
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/pydantic/typing.cpython-39-x86_64-linux-gnu.so)
srun: error: zibo-gpu-18: task 0: Exited with exit code 1

### Example Code

```Python
#/demo/miniconda3/envs/sqlcode/lib/python3.9/site-packages/openai/_compat.py
#openai  vesion is '1.14.2'
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Union, TypeVar, cast
from datetime import date, datetime

import pydantic
from pydantic.fields import FieldInfo

from ._types import StrBytesIntFloat

_ModelT = TypeVar("_ModelT", bound=pydantic.BaseModel)

# --------------- Pydantic v2 compatibility ---------------

# Pyright incorrectly reports some of our functions as overriding a method when they don't
# pyright: reportIncompatibleMethodOverride=false

PYDANTIC_V2 = pydantic.VERSION.startswith("2.")

# v1 re-exports
if TYPE_CHECKING:

    def parse_date(value: date | StrBytesIntFloat) -> date:  # noqa: ARG001
        ...

    def parse_datetime(value: Union[datetime, StrBytesIntFloat]) -> datetime:  # noqa: ARG001
        ...

    def get_args(t: type[Any]) -> tuple[Any, ...]:  # noqa: ARG001
        ...

    def is_union(tp: type[Any] | None) -> bool:  # noqa: ARG001
        ...

    def get_origin(t: type[Any]) -> type[Any] | None:  # noqa: ARG001
        ...

    def is_literal_type(type_: type[Any]) -> bool:  # noqa: ARG001
        ...

    def is_typeddict(type_: type[Any]) -> bool:  # noqa: ARG001
        ...

else:
    if PYDANTIC_V2:
        from pydantic.v1.typing import get_args as get_args
        from pydantic.v1.typing import is_union as is_union
        from pydantic.v1.typing import get_origin as get_origin
        from pydantic.v1.typing import is_typeddict as is_typeddict
        from pydantic.v1.typing import is_literal_type as is_literal_type
        from pydantic.v1.datetime_parse import parse_date as parse_date
        from pydantic.v1.datetime_parse import parse_datetime as parse_datetime
    else:
        from pydantic.typing import get_args as get_args
        from pydantic.typing import is_union as is_union
        from pydantic.typing import get_origin as get_origin
        from pydantic.typing import is_typeddict as is_typeddict
        from pydantic.typing import is_literal_type as is_literal_type
        from pydantic.datetime_parse import parse_date as parse_date
        from pydantic.datetime_parse import parse_datetime as parse_datetime


# refactored config
if TYPE_CHECKING:
    from pydantic import ConfigDict as ConfigDict
else:
    if PYDANTIC_V2:
        from pydantic import ConfigDict
    else:
        # TODO: provide an error message here?
        ConfigDict = None


# renamed methods / properties
def parse_obj(model: type[_ModelT], value: object) -> _ModelT:
    if PYDANTIC_V2:
        return model.model_validate(value)
    else:
        return cast(_ModelT, model.parse_obj(value))  # pyright: ignore[reportDeprecated, reportUnnecessaryCast]


def field_is_required(field: FieldInfo) -> bool:
    if PYDANTIC_V2:
        return field.is_required()
    return field.required  # type: ignore


def field_get_default(field: FieldInfo) -> Any:
    value = field.get_default()
    if PYDANTIC_V2:
        from pydantic_core import PydanticUndefined

        if value == PydanticUndefined:
            return None
        return value
    return value


def field_outer_type(field: FieldInfo) -> Any:
    if PYDANTIC_V2:
        return field.annotation
    return field.outer_type_  # type: ignore


def get_model_config(model: type[pydantic.BaseModel]) -> Any:
    if PYDANTIC_V2:
        return model.model_config
    return model.__config__  # type: ignore


def get_model_fields(model: type[pydantic.BaseModel]) -> dict[str, FieldInfo]:
    if PYDANTIC_V2:
        return model.model_fields
    return model.__fields__  # type: ignore


def model_copy(model: _ModelT) -> _ModelT:
    if PYDANTIC_V2:
        return model.model_copy()
    return model.copy()  # type: ignore


def model_json(model: pydantic.BaseModel, *, indent: int | None = None) -> str:
    if PYDANTIC_V2:
        return model.model_dump_json(indent=indent)
    return model.json(indent=indent)  # type: ignore


def model_dump(
    model: pydantic.BaseModel,
    *,
    exclude_unset: bool = False,
    exclude_defaults: bool = False,
) -> dict[str, Any]:
    if PYDANTIC_V2:
        return model.model_dump(
            exclude_unset=exclude_unset,
            exclude_defaults=exclude_defaults,
        )
    return cast(
        "dict[str, Any]",
        model.dict(  # pyright: ignore[reportDeprecated, reportUnnecessaryCast]
            exclude_unset=exclude_unset,
            exclude_defaults=exclude_defaults,
        ),
    )


def model_parse(model: type[_ModelT], data: Any) -> _ModelT:
    if PYDANTIC_V2:
        return model.model_validate(data)
    return model.parse_obj(data)  # pyright: ignore[reportDeprecated]


# generic models
if TYPE_CHECKING:

    class GenericModel(pydantic.BaseModel):
        ...

else:
    if PYDANTIC_V2:
        # there no longer needs to be a distinction in v2 but
        # we still have to create our own subclass to avoid
        # inconsistent MRO ordering errors
        class GenericModel(pydantic.BaseModel):
            ...

    else:
        import pydantic.generics

        class GenericModel(pydantic.generics.GenericModel, pydantic.BaseModel):
            ...
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.8
            pydantic compiled: True
                 install path: /mnt/ceph-dataset/weids/miniconda3/envs/sql_eval/lib/python3.8/site-packages/pydantic
               python version: 3.8.19 (default, Mar 20 2024, 19:58:24)  [GCC 11.2.0]
                     platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.17
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [X] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
I think you have pydantic V1 installed and OpenAI requires V2. Either way there's no evidence of a bug in pydantic here.

**Comment by dshwei** [comment]
if  I change   pydantic version to 2.0.1 ,the error take occure  again

**Comment by samuelcolvin** [comment]
No idea, it's not a bug with pydantic.

**Comment by tommylge** [comment]
same problem here, with `field_validator`:
`ImportError: cannot import name 'field_validator' from 'pydantic' (/opt/venv/lib/python3.11/site-packages/pydantic/__init__.cpython-311-x86_64-linux-gnu.so)`

No idea why it triggers this only into a docker container.
