### ISSUE TITLE
Improved smart union behaviour when `extra="allow"` or `extra="ignore"` and union members have no required fields

### ISSUE THREAD

**Issue by psychedelicious** [pydantic/pydantic#9095]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Initial Checks

- [x] I confirm that I'm using Pydantic V2

### Description

Smart union mode has some shortcomings when the union members are pydantic models with `extra="ignore"` or `extra="allow"`, and have no required fields.

```py
from pydantic import BaseModel, ConfigDict, Field

class Foo(BaseModel):
    foo: str = Field(default="foo")

    model_config = ConfigDict(extra="ignore")


class Bar(BaseModel):
    bar: str = Field(default="bar")

    model_config = ConfigDict(extra="ignore")


class MyModel(BaseModel):
    foo_or_bar: Foo | Bar = Field(union_mode="smart")

# extra="ignore"
print(repr(MyModel.model_validate({"foo_or_bar": {"bar": "bar"}})))
# MyModel(foo_or_bar=Foo(foo='foo'))

# extra="allow"
print(repr(MyModel.model_validate({"foo_or_bar": {"bar": "bar"}})))
# MyModel(foo_or_bar=Foo(foo='foo', bar='bar'))

# extra="forbid"
print(repr(MyModel.model_validate({"foo_or_bar": {"bar": "bar"}})))
# MyModel(foo_or_bar=Bar(bar='bar'))
```

In all cases, we expect an instance of `Bar`, but we only get it for `extra="forbid"`. While this behaviour is expected, it is unintuitive.

### Possible Solution

Perhaps the smart union could use `model_fields_set` for tie-breakers. I suppose this union logic exists in `pydantic-core`, but here's what I mean in python:

```py
scores = {}
for model in {Foo, Bar}:
    scores[model.__name__] = 0
    try:
        candidate_instance = model.model_validate({"bar": "bar"})
        for f in candidate_instance.model_fields_set:
            # A set field only gets a point if it's a known field for the model.
            # Without this check, models with `extra="allow"` award points for extra fields.
            if f in candidate_instance.model_fields:
                scores[model.__name__] += 1
    except ValidationError:
        pass
print(scores)
# {'Bar': 1, 'Foo': 0}
```

### Related issues

 #8690 appears to be similar, but I'm not sure if it's the same root issue.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@psychedelicious,

Same message :) - thanks for reporting. Definitely looks like a bug. Adding this to the union sprint to be addressed with 2.8.

**Comment by sydney-runkle** [comment]
I've fixed the case above for `extra='ignore'` via https://github.com/pydantic/pydantic-core/pull/1332.

Still not sure how we want to handle the `extra='allow'`case.

**Comment by sydney-runkle** [comment]
@psychedelicious,

I've opened a new PR to address this issue :).

**Comment by psychedelicious** [comment]
Thanks @sydney-runkle !
