### ISSUE TITLE
pydantic does not tips in pycharm, is why?

### ISSUE THREAD

**Issue by zdlay** [pydantic/pydantic#9109]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

是这样的，用pydantic也比较久了但pycharm一直没有提示很难受，但是dataclass是有的，但是dataclass没有pydantic这么成熟，希望得知如何才能有提示

### Example Code

```Python
from pydantic import BaseModel


class Test(BaseModel):
    nickname: str
    

test = Test()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.3                   
        pydantic-core version: 2.16.3                  
          pydantic-core build: profile=release pgo=true
                 install path: D:\develop\anaconda3\envs\glow\Lib\site-packages\pydantic
               python version: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by zdlay** [comment]
but dataclass haved tips

**Comment by sydney-runkle** [comment]
Might want to download the plugin: https://plugins.jetbrains.com/plugin/12861-pydantic

**Comment by zdlay** [comment]
OK,Thank you!

---- Replied Message ----
| From | Sydney ***@***.***> |
| Date | 03/27/2024 01:25 |
| To | pydantic/pydantic ***@***.***> |
| Cc | zdlay ***@***.***>,
Author ***@***.***> |
| Subject | Re: [pydantic/pydantic] pydantic does not tips in pycharm, is why? (Issue #9109) |

Might want to download the plugin: https://plugins.jetbrains.com/plugin/12861-pydantic
