### ISSUE TITLE
Pydantic changes type of passed argument when creating new instance

### ISSUE THREAD

**Issue by Mapiarz** [pydantic/pydantic#9132]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

See repro. The code will complete successfully without any assertion failures 🤡

### Example Code

```Python
import pydantic


class BookingReadyForCheckInPayload(pydantic.BaseModel):
    booking_id: str
    boat_name: str


class ExtraRequestedPendingApprovalPayload(pydantic.BaseModel):
    booking_id: str
    boat_name: str
    extra_definition_id: str
    extra_name: str


class NotificationPayload(pydantic.BaseModel):
    foo: BookingReadyForCheckInPayload | ExtraRequestedPendingApprovalPayload


test = ExtraRequestedPendingApprovalPayload(
    booking_id="foo",
    boat_name="bar",
    extra_definition_id="baz",
    extra_name="qwe",
)
assert type(test) == ExtraRequestedPendingApprovalPayload
payload = NotificationPayload(foo=test)
assert type(test) == ExtraRequestedPendingApprovalPayload
assert type(payload.foo) == BookingReadyForCheckInPayload
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.14
            pydantic compiled: True
                 install path: /workspace/backend/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb  7 2024, 22:38:59) [GCC 12.2.0]
                     platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.36
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Mapiarz** [comment]
Some further notes: Names of the properties matter, order of types in the `foo` union matters. Works as intended in V2.

**Comment by sydney-runkle** [comment]
We're no longer actively working on V1, so closing this as not planned. We'd consider a PR with a fix, but aren't going to prioritize this work. Thanks for the report!
