### ISSUE TITLE
Pydantic casts contructor arguments under the hood following field type hints

### ISSUE THREAD

**Issue by adubovik** [pydantic/pydantic#9149]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

The example code produces the following output:

```
<class '__main__.ConfigA'>
<class '__main__.ConfigB'>
True
config=ConfigB()
```

whereas, the expected output is:

```
<class '__main__.ConfigA'>
<class '__main__.ConfigA'>
True
config=ConfigA()
```

Pydantic V2 prints the expected output unlike V1.

### Example Code

```Python
from pydantic import BaseModel


class Config(BaseModel):
    pass


class ConfigA(Config):
    pass


class ConfigB(Config):
    pass


class Wrapper(BaseModel):
    config: ConfigB | ConfigA | None


def read_config() -> Wrapper:

    config = ConfigA()
    ret = Wrapper(config=config)

    print(type(config))
    print(type(ret.config))
    print(config == ret.config)

    return ret


if __name__ == "__main__":
    print(read_config())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.14
            pydantic compiled: True
                 install path: /opt/homebrew/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-13.3.1-arm64-arm-64bit
     optional deps. installed: ['dotenv', 'typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
We're no longer actively working on V1. Closing this as resolved, given that it's fixed in V2.
