### ISSUE TITLE
missing host_type attribute from Url

### ISSUE THREAD

**Issue by jochman** [pydantic/pydantic#9155]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The base `Url` object has no `host_type` attribute.

might be related to https://github.com/pydantic/pydantic/issues/6961

### Example Code

```Python
from pydantic import TypeAdapter, AnyUrl

url: AnyUrl = TypeAdapter(AnyUrl).validate_python("https://github.com/pydantic/pydantic")

url.host_type
```

Error:

```Python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'pydantic_core._pydantic_core.Url' object has no attribute 'host_type'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
               python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.4-arm64-arm-64bit
             related packages: mypy-1.9.0 fastapi-0.110.1 typing_extensions-4.10.0
```

**Comment by sydney-runkle** [comment]
I'm not sure if we actually want to add this, but seems like we've gotten an influx of Url related issues. Tagging as such.

**Comment by sydney-runkle** [comment]
`host_type` isn't included on the `rust` `Url` instance, so I don't think we can include it on the Python end either. What would you expect for the `host_type` in the case above?
