### ISSUE TITLE
JSON Wrapper results in Pyright Error

### ISSUE THREAD

**Issue by max-muoto** [pydantic/pydantic#9173]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When using the `JSON` type-wrapper, it's required that the type actually be that which lives within side the wrapper. Is there any reason to not just allow any string to be passed in? We could instead enforce the type-checker accept an string regardless of what the contained type is, which would mitigate this issue.

Not sure if the MyPy plugin mitigates this issue, but nonetheless, it would be nice to have this work with the native Python typing system.

### Example Code

Let's take this example from the documentation:

```Python


from typing import Any, List
from pydantic import BaseModel, Json, ValidationError


class AnyJsonModel(BaseModel):
    json_obj: Json[Any]


class ConstrainedJsonModel(BaseModel):
    json_obj: Json[List[int]]


print(AnyJsonModel(json_obj='{"b": 1}'))

# Argument of type "Literal['[1, 2, 3]']" cannot be assigned to parameter "json_obj" of type "Json[List[int]]" in function "__init__"
  "Literal['[1, 2, 3]']" is incompatible with "Json[List[int]]"
print(ConstrainedJsonModel(json_obj="[1, 2, 3]"))
```

### Python, Pydantic & OS Version

```Text
conda run python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.6.1
        pydantic-core version: 2.16.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/maxmuoto/mambaforge/envs/sm/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
                     platform: macOS-14.4-arm64-arm-64bit
             related packages: pyright-1.1.357 typing_extensions-4.7.1 pydantic-extra-types-2.5.0
```

**Comment by MuhammadNizamani** [comment]
@max-muoto  is this bug is confirm by maintainer ? if yes can I work on this issue or are you going to solve this issue ?

**Comment by max-muoto** [comment]
After thinking about this more, not sure it's possible to solve this within the constraints of the current Python typing system. Perhaps when dataclass converters, this could be reworked into something that's compatible with Pyright, which will have support for dataclass transform: https://peps.python.org/pep-0712/
