### ISSUE TITLE
Pyright/Pylance typing error when overriding `__pydantic_extra__` type

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [pydantic/pydantic#9187]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Similar to #9147 and #7094, but those seem to be focused on `TypeAdapter` and I'm unsure how closely those are related. Sorry if this is a duplicate.

See code below. Pylance warns that `__pydantic_extra__` should also be specified when instantiating the class. I believe this warning should not appear.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict


class Model(BaseModel):
    __pydantic_extra__: dict[str, int]

    a: int

    model_config = ConfigDict(extra="allow")


m = Model(a=1) # Argument missing for parameter "__pydantic_extra__" Pylance (reportCallIssue)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\Test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by Viicos** [comment]
This is unfortunate, as [`dataclass_transform`](https://docs.python.org/3/library/typing.html#typing.dataclass_transform) (which is used to make type checkers aware of `BaseModel` acting like a dataclass) does not provide any way to "ignore" fields from the synthesized `__init__` method.

A workaround is to define your model as:

```python
from pydantic import ConfigDict, Field


class MyModel(BaseModel):
    __pydantic_extra__: dict[str, int] = Field(init=False)

    a: int

    model_config = ConfigDict(extra="allow")
```

Ideally, this feature could have been implemented as a config value, e.g. `ConfigDict(extra_type=int)` or similar, but the current implementation (having to redefine `__pydantic_extra__` makes it nice as you get type checking support as well).

**Comment by blueTurtz** [comment]
@sydney-runkle I can pick this up.

**Comment by sydney-runkle** [comment]
@Viicos,

What do you think about this approach here (we might need some docs changes):

```py
from pydantic import BaseModel, ConfigDict
from pydantic.fields import PrivateAttr as _PrivateAttr


class Model(BaseModel):
    __pydantic_extra__: dict[str, int] = _PrivateAttr()

    a: int

    model_config = ConfigDict(extra="allow")


m = Model(a=1)
```

Thinking about this approach on the heels of https://github.com/pydantic/pydantic/pull/9293

**Comment by sydney-runkle** [comment]
Also, here's the relevant docs for reference: https://docs.pydantic.dev/latest/concepts/models/#extra-fields

**Comment by Viicos** [comment]
Looks good as a workaround, so the docs can probably be updated with the added `PrivateAttr`.

**Comment by blueTurtz** [comment]
https://github.com/pydantic/pydantic/issues/9187#issue-2231515683
Using mypy I found that the following issue is raised when using the `Example Code` from the link above

```zsh
(pydantic-env) ➜  tmp mypy 9187.py
9187.py:12: error: Missing named argument "__pydantic_extra__" for "Model"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by dmontagu** [comment]
When https://github.com/pydantic/pydantic/pull/9659 gets merged, I think the solution to this will be to do:

```python
from pydantic import BaseModel, Field


class MyModel(BaseModel, extra='allow'):
    __pydantic_extra__: dict[str, int] = Field(init=False)
```
or similar
