### ISSUE TITLE
Unexpected behaviour while initializing v2 models

### ISSUE THREAD

**Issue by bcdurak** [pydantic/pydantic#9188]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello there,

I ran into an issue while migrating our codebase to pydantic v2.

Previously in v1, we were using a logic similar to my example code. I just realized that this used to work as long as you added the `underscore_attrs_are_private = True` as a part of the configuration. Since this option is now removed and set to `True` for all v2 models, I thought I could migrate it as I displayed in the example.

Unfortunately, this fails with a `'MyClass' object has no attribute '__pydantic_private__'` error, and the error message itself is also a bit confusing. 

As a potential solution, I thought about moving the logic within the `__init__` call to a `model_validator` with the parameter `mode="before"` but I was not sure if this was the most optimal solution here. Moreover, I want to report this in case it indicates a bug in the code.

### Example Code

```Python
from pydantic import BaseModel


class MyClass(BaseModel):

    _hidden_param: int

    def __init__(self, hidden_param: int = None, **kwargs):
        # If hidden param is provided, overwrite the hidden value.
        if hidden_param:
            self._hidden_param = hidden_param

        super(MyClass, self).__init__(**kwargs)

    # ---- Only uncomment while testing it in v1 ----
    # class Config:
    #     underscore_attrs_are_private = True


a = MyClass()  # This works!

a._hidden_param = 4  # This works as well
print(f"The private value {a._hidden_param}")

print(f"Class vars: {MyClass.__class_vars__}")
print(f"Pydantic Private: {MyClass.__pydantic_private__}")
print(f"Private Attributes: {MyClass.__private_attributes__}")

MyClass(hidden_param=4)  # This fails in v2 with: 'MyClass' object has no attribute '__pydantic_private__'.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
pydantic-core version: 2.16.3
pydantic-core build: profile=release pgo=true
install path: /Users/bariscandurak/.pyenv/versions/3.10.11/envs/zenml/lib/python3.10/site-packages/pydantic
python version: 3.10.11 (main, Sep 28 2023, 17:25:26) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-14.4.1-arm64-arm-64bit
related packages: fastapi-0.110.0 typing_extensions-4.11.0 mypy-1.7.1 pydantic-settings-2.2.1
commit: unknown
```

**Comment by sydney-runkle** [comment]
@bcdurak,

Thanks for reporting your issue! Could you please submit the original code snippet that you were using in V1 as well?

**Comment by bcdurak** [comment]
Hey @sydney-runkle,

Not sure if I got the question correctly. In any case, if you are asking for the v1 version of the example code that I submitted, it is basically the same code snippet with the config class uncommented, which looks something like this:

```python
from pydantic import BaseModel


class MyClass(BaseModel):

    _hidden_param: int

    def __init__(self, hidden_param: int = None, **kwargs):
        # If hidden param is provided, overwrite the hidden value.
        if hidden_param:
            self._hidden_param = hidden_param

        super(MyClass, self).__init__(**kwargs)

    class Config: 
        underscore_attrs_are_private = True   # It only works if this is set 


a = MyClass()  # This works!
a._hidden_param = 4  
print(f"The private value {a._hidden_param}")

b = MyClass(hidden_param=5)  # This works as well
print(f"The private value {b._hidden_param}")
```

However, if you are asking how we used it in our original code, you can check out the [FileSyncModel](https://github.com/zenml-io/zenml/blob/46d40c4452c709bd8b7da0e9d42cd72cd8290412/src/zenml/utils/filesync_model.py#L29) in our repository.

**Comment by bcdurak** [comment]
Just realized that calling `super(MyClass, self).__init__(**kwargs)` before accessing the `_hidden_param` solves the issue in v2 as it helps to set up the pydantic built-in attributes.

**Comment by sydney-runkle** [comment]
Apologies for not following up earlier. Things were a bit hectic pre-Pycon! Settling into some solid development now 🚀 !
