### ISSUE TITLE
Defining a default factory for PrivateAttr changes equality behavior 

### ISSUE THREAD

**Issue by adonath** [pydantic/pydantic#9192]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Triggered by [this question on stackoverflow](https://stackoverflow.com/q/78287084/19802442) I came across the following unexpected behavior: defining a `default_factory` for a `PrivateAttr` will change how the model behaves, when checking for equality. See the example code below. 

### Example Code

```Python
from pydantic import BaseModel, PrivateAttr
import random


def random_int():
    return random.randint(0, 10000)


class A(BaseModel):
    f: int
    _pf: int = PrivateAttr()


class B(BaseModel):
    f: int
    _pf: int = PrivateAttr(default_factory=random_int)


a1 = A(f=1, _pf=1)
a2 = A(f=1, _pf=3)
assert a1 == a2 # Passes

b1 = B(f=1, _pf=1)
b2 = B(f=1, _pf=3)
assert b1 == b2 # Fails
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.2
        pydantic-core version: 2.14.5
          pydantic-core build: profile=release pgo=true
                 install path: /Users/adonath/software/mambaforge/envs/my-env/lib/python3.11/site-packages/pydantic
               python version: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
                     platform: macOS-14.2-arm64-arm-64bit
             related packages: fastapi-0.109.0 typing_extensions-4.8.0 email-validator-2.1.0.post1
```

**Comment by sydney-runkle** [comment]
@adonath,

Thanks for reporting this. Definitely seems like a bug. PRs welcome with a fix!

**Comment by adonath** [comment]
On further investigation the behavior seems actually correct:

- The docs state that [private attributes are not set on init](https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes).
- This means that passing the private attribute in init like `A(..., _pf=3)` has no effect!
- In the first case this leads to `_pf` being unset. And indeed `print(a1._pf)` fails, as the attribute is not set. The equality check passes because `_pf` is unset in both cases.
- In the second case the default factory sets `_pf` to a different random value for `b1` and `b2` and the equality check fails correctly.

So the misunderstanding here from my side was that the private attribute is not set, when passed to init.

**Comment by boholder** [comment]
Then let me paste the test code in that question to here (I'm the author of that SOF question):

```python
from pydantic import BaseModel, model_validator


class A(BaseModel):
    f: int
    _pf: int | None = None

    @model_validator(mode="after")
    def after(self):
        self._pf = random.choice(list(range(10000)))  # <-- just think this is some complex private logic that assign different values to _pf which belongs to different instances of class A

def test_a():
    a = A(f=1)
    b = A(f=1)
    assert a == b # <-- will fail due to a._pf != b._pf
```

**Comment by ManiMozaffar** [comment]
I see what you mean. The way you're asking the question is confusing. 

what you mean is why two instance of a model with different private attribute values should not be "equal" to each other, which is a good question, but i'm questioning if that should be the behavior?

> __eq__ in python checks for equality of objects values between two objects of the same class	

@sydney-runkle should I make PR to fix?

**Comment by sydney-runkle** [comment]
Hi folks (@ManiMozaffar and @adonath and @boholder),

Thanks for following up here. Indeed - private attributes aren't set during model init, good catch there.

I'm going to close this as resolved for now - we currently do check for private attributes in the `__eq__` method (which makes sense, given the examples we've seen above), and modifying this would qualify as a breaking change at this point.

I think this is the right behavior. If you think otherwise, I think the best route forward would be to open a new issue with the `V3` tag!

**Comment by boholder** [comment]
> __eq__ in python checks for equality of objects values between two objects of the same class	

Nice point, I'm convinced. 👏
But I'd like to know why pydantic hasn't provided a way to make pydantic ignores some fields... from designing perspective I mean. I'm not going to post a feature request about this, just out of curiosity...

**Comment by ManiMozaffar** [comment]
> But I'd like to know why pydantic hasn't provided a way to make pydantic ignores some fields... from designing perspective I mean. I'm not going to post a feature request about this, just out of curiosity...

Pydantic is a dataclass that comes with a parser and validator. 

> A data class refers to a class that contains only fields and crude methods for accessing them (getters and setters). These are simply containers for data used by other classes. These classes don't contain any additional functionality and can't independently operate on the data that they own. ref: refactoring guru

That's the reason you'd use a dataclass, a container for some data. Now the question is why you should ignore some data in that container? who you want to ignore it from?
You can still `exclude` while operating on the data (e.x dumping to json/dict)

**Comment by boholder** [comment]
> These classes don't contain any additional functionality and can't independently operate on the data that they own.

Thanks for explaining that solved my question, now I realize that the pydantic is for pure "Data (Transferring) Objects" (or "POJO", what we called it in Java). I was exactly going to make one of my BaseModel inherited class **contains logic that processing its inner data** (Thus it will become a "fat Data Object"). 👍
