### ISSUE TITLE
v2.7.0b1 `pydantic_core.from_json` throws EOF when run on the empty string and `allow_partial=True`

### ISSUE THREAD

**Issue by willbakst** [pydantic/pydantic#9195]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I would expect `pydantic_core.from_json` with `allow_partial=True` to return an empty object when `data=""`, but instead it throws EOF

### Example Code

```Python
from pydantic_core import from_json

obj = from_json("", allow_partial=True)
print(obj)
# Traceback (most recent call last):
# File "/Users/william/Mirascope/GitHub/mirascope/scratch.py", line 3, in <module>
#     obj = from_json("", allow_partial=True)
# ValueError: EOF while parsing a value at line 1 column 0
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0b1
pydantic-core version: 2.18.0
pydantic-core build: profile=release pgo=false
python version: 3.9.16 (main, Apr  2 2023, 22:08:02)  [Clang 14.0.0 (clang-1400.0.29.202)]
platform: macOS-14.2.1-arm64-arm-64bit
related packages: typing_extensions-4.10.0 fastapi-0.109.2 pydantic-extra-types-2.6.0 mypy-1.1.1 pydantic-settings-2.2.1
```

**Comment by samuelcolvin** [comment]
yup, makes sense. This will require a fix in Jiter but shouldn't be too hard.

**Comment by willbakst** [comment]
I also filed another bug about `allow_partial=True` truncates text too aggressively, but now I can't seem to find the issue I created.

Here is an example:

```python
from pydantic_core import from_json

obj = from_json(
    '{"description": "This has not yet finished streami',
    allow_partial=True,
)
print(obj)
# Actual: {}
# Expected: {"description": "This has not yet finished streami"}
```

Seems like something you would also need to update in Jiter?

**Comment by sydney-runkle** [comment]
Just to follow up here - we decided that we'll keep the current behavior, but that a more helpful error message should be raised. Leaving this issue open so that can be addressed!

**Comment by willbakst** [comment]
Ok! Empty string handling as-is with better error works, easy to handle that case on my end.

I'm curious about the additional partial string issue I also mentioned above?

**Comment by sydney-runkle** [comment]
@willbakst,

Which other partial string issue are you referring to?

**Comment by willbakst** [comment]
When streaming the JSON, sometimes there will be a field with a long string (e.g. description). With the current implementation, that field won't get parsed until it's finished streaming the entire string. For example:

```python
from pydantic_core import from_json

obj = from_json(
    '{"description": "This has not yet finished streami',
    allow_partial=True,
)
print(obj)
# Actual: {}
# Expected: {"description": "This has not yet finished streami"}
```

This reduces the "real-time" feel of the streaming. Would it be possible to parse these partial strings as they stream?

**Comment by Folyd** [comment]
I have the same issue:
```py
>>> from_json('{"message": "The **Chihuly Garden and Glass** is open at different times throughout the week. Here are', allow_partial=True)
{}
```

**Comment by willbakst** [comment]
I'm realizing that the original issue I posted for this follow-up discussion has been moved to `jiter` where it belongs, so I'm closing this and continuing the conversation there.

See: https://github.com/pydantic/jiter/issues/82
