### ISSUE TITLE
Multiple Computed Field(s) in single function call

### ISSUE THREAD

**Issue by SDAravind** [pydantic/pydantic#9203]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Why restrict computed field to one single computed field based on the function name? we can derive many things from single/mutiple field?

For example, in the below code, Circle can take single field value radius as input and other fields can be calculated such as diameter, circumference, area from single field, How can we do this within single function call without writing additional functions with computed field? 

I'm thinking of possible solution, if return statement returns a dict then consider keys as computed fields and model should be able access these computed fields directly. Any other ideas to acheive this behavior?

1. `Circle.diameter`
2. `Circle.circumference`
3. `Circle.area`

Below code will work but calculated fields are part of calulated_fields as dictionary. 

```python
from pydantic import BaseModel, computed_field


class Circle(BaseModel):
    radius: float

    @computed_field
    def calulated_fields(self) -> dict[str, float]:
        diameter = 2 * self.radius
        circumference = 2 * 3.14 * self.radius
        area = 3.14 * (self.radius**2)
        return {"diameter": diameter, "circumference": circumference, "area": area}



```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
I'm not sure I fully understand what is your feature request, but it seems that the following:

```python
from pydantic import BaseModel, computed_field


class Circle(BaseModel):
    radius: float

    @computed_field
    def diameter(self) -> float:
        return 2 * self.radius

    @computed_field
    def circumference(self) -> float:
        return 2 * 3.14 * self.radius

    @computed_field
    def area(self) -> float:
        return 3.14 * (self.radius**2)
```

Is not an ideal solution for you, and you'd like something more concise and dynamic?

I'd recommend sticking to the explicit way. Although more verbose (I guess your use case is involving a lot of computed fields), having something dynamic would result in no type checker/IDE support, and a really bad user experience.

If you are creating your models in an automated way or don't care about the explicitness and typing support, you could use `pydantic.create_model`, which could most probably be used to dynamically set computed fields.

**Comment by SDAravind** [comment]
yes, my usecase have lot of computed fields. Given the single list inputs(string/number) we need to derive various fields that would populate various computed fields based on single input. If it's a number we might need to create squares or cubes or square root and likewise. If it's a string, consider an email we would like seperate username and domain name in to multiple fields. This might get stored in a database or spreadsheet.

These are few usecases, there will be many when we look at various dataset. From financial data perspective, we need to derive from multiple columns of data to calculate %changes over 5 years, CAGR, various financial ratios. This will be cumbersome to write 100s of computed field. Hence the ask. 

Although, we can use pandas but for for few datapoints or streaming data it would be a huge package. If we have a model with all of it's formulas created in one place as derivaties would help the data and analytics world a lot.

Definetly I would need typing support with all the pydantic validation, perhaps I'm looking something like below but the computed fields are still under props instead I would like them to be part of parent model.

```python
class CircleProperties(BaseModel):
    diameter: float
    circumference: float
    area: float


class Circle(BaseModel):
    radius: float

    @computed_field
    def props(self) -> CircleProperties:
        # def props(self) -> dict[str, float]:
        diameter = 2 * self.radius
        circumference = 2 * 3.14 * self.radius
        area = 3.14 * (self.radius**2)
        circle = CircleProperties(
            diameter=diameter, circumference=circumference, area=area
        )

        return circle
```

**Comment by sydney-runkle** [comment]
I agree with @Viicos, I'd recommend the multiple computed field approach, or returning an object with all of said properties. Closing for now, as this isn't something we're going to focus on as a new feature!
