### ISSUE TITLE
.model_validate() fails to catch broader type when validating child (inherited) model

### ISSUE THREAD

**Issue by sashkent3** [pydantic/pydantic#9215]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Consider the example code below. I suppose Pydantic shouldn't allow overriding the types with more broad ones in child models, however, it looks like something a user might do. The problem here is that the code runs without any runtime errors thus producing an object which is technically an instance of `Parent` but has its `id` attribute set to `None`. The static type-checker I use is also fooled to assume `parent.id` to be of type `int` and not `int | None`.

### Example Code

```Python
from pydantic import BaseModel


class Parent(BaseModel):
    id: int


class Child(Parent):
    id: int | None


parent: Parent = Parent.model_validate(Child(id=None))
print(parent.id)
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=true
                 install path: /home/.../.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
                     platform: Linux-6.8.4-arch1-1-x86_64-with-glibc2.39
             related packages: typing_extensions-4.11.0 fastapi-0.110.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@sashkent3,

Thanks for your question. This is the expected behavior. If you'd like `pydantic` to error in this case, you can use the [`revalidate_instances`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.revalidate_instances) config setting:

```py
from pydantic import BaseModel, ConfigDict


class Parent(BaseModel):
    id: int

    model_config = ConfigDict(revalidate_instances='subclass-instances')


class Child(Parent):
    id: int | None


parent: Parent = Parent.model_validate(Child(id=None))
"""
id
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.7/v/int_type
"""
```
