### ISSUE TITLE
v2.7.0 TypeError in model_construct where field has a validation_alias with AliasChoices

### ISSUE THREAD

**Issue by twispt** [pydantic/pydantic#9216]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using `model_construct` on a model that has a field with AliasChoices for the `validation_alias` throws a TypeError exception. This issue is new to `v2.7.0`. Example code works with `v2.6.4`.

```
Traceback (most recent call last):
  File "/home/bryan/src/temp/pydantic-regression/my.py", line 6, in <module>
    FooBase.model_construct().dict()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/twispt/src/temp/pydantic-regression/.venv/lib/python3.11/site-packages/pydantic/main.py", line 228, in model_construct
    elif field.validation_alias is not None and field.validation_alias in values:
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'AliasChoices'
```

### Example Code

```Python
from pydantic import BaseModel, Field, AliasChoices

class FooBase(BaseModel):
  foo: str = Field(serialization_alias='bar', validation_alias=AliasChoices('bar', 'foo'))

FooBase.model_construct().dict()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/twispt/src/temp/pydantic-regression/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
                     platform: Linux-6.6.25-1-MANJARO-x86_64-with-glibc2.39
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by kevanpigott** [comment]
I am running into the same issue, and can confirm the code works on v2.6.4 but not on v2.7.0
in v2.6.4 i do not see a reference to field.validation_alias in model_consruct whereas the check occurs in v2.7.0

a potential solution would be to replace the line
```python
elif field.validation_alias is not None and field.validation_alias in values:
```

with
```
any(alias in values for alias in field.validation_alias.choices)
```
This checks if any alias choice is in the values field, but does not check if multiple choices are defined in the value field.

If that isnt checked elsewhere than i would use
```python
sum(alias in values for alias in field.validation_alias.choices) == 1:
```

**Comment by sydney-runkle** [comment]
@twispt,

Thanks for reporting this! We'll work on a fix and get a patch release out early next week!

**Comment by sydney-runkle** [comment]
I believe this was introduced with https://github.com/pydantic/pydantic/pull/9144

**Comment by sydney-runkle** [comment]
Working on a fix now and will have a PR up shortly!
