### ISSUE TITLE
FieldInfo Description Docstrings are not working

### ISSUE THREAD

**Issue by Antyos** [pydantic/pydantic#9218]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I can't get the automatic docstring detection from #6563 to work using the example code.

Just to make sure, I created a new virtual environment and installed only Pydantic, and still cannot get it to work. Even with the `use_attribute_docstrings=True`, it still won't use the attribute docstrings.

 I feel like I'm probably doing something wrong, but I'm stumped.

### Example Code

```Python
from pydantic import BaseModel, ConfigDict, Field

class Model(BaseModel):
    model_config = ConfigDict(use_attribute_docstrings=True)
    x: str
    """
    Example of an attribute docstring
    """
    y: int = Field(description="Description in Field")
    """
    Description in Field overrides attribute docstring
    """
print(Model.model_fields["x"].description)
# None
print(Model.model_fields["y"].description)
# 'Description in Field'
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\avg170002\Code\temp\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22621-SP0
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by Viicos** [comment]
Are you running this in an interactive terminal? If so, this won't work as Pydantic needs to have access to the source code of the class, as stated in [the docs](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.use_attribute_docstrings).

**Comment by julien-blanchon** [comment]
I can reproduce (1st is None 2nd is good) with 
```raw
pydantic==2.10.6
pydantic-core==2.27.2
```
