### ISSUE TITLE
AliasChoices Unhashable When Comparing Models

### ISSUE THREAD

**Issue by iambroadband** [pydantic/pydantic#9220]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

While upgrading from Pydantic v2.6.4 to v2.7.0 some of our tests comparing models started failing. My expectation here is that we'd be able to continue comparing models constructed in this way without any issue. The results here do not meet that expectation because we encounter a `TypeError` 

![image](https://github.com/pydantic/pydantic/assets/10965648/a07cb8a8-6b07-44d7-bd56-a0d16d4a0fdb)

### Example Code

```Python
from pydantic import AliasChoices, BaseModel, Field

class MyModel(BaseModel):
    data: str
    our_id: str | None = Field(
        default=None,
        validation_alias=AliasChoices("their_id", "theirId", "our_id", "id"),
    )

def test_cardmodel_eq():
    model1 = MyModel.model_construct(data="test data")
    model2 = MyModel.model_construct(data="test data")
    model3 = MyModel.model_construct(data="other data")
    assert model1 == model2
    assert not model1 == model3
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
pydantic-core version: 2.18.1
pydantic-core build: profile=release pgo=true
install path: /home/broadband/.cache/pypoetry/virtualenvs/scooze-iup8854z-py3.11/lib/python3.11/site-packages/pydantic
python version: 3.11.5 (main, Aug 26 2023, 21:51:13) [GCC 11.3.0]
platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
related packages: fastapi-0.110.1 pydantic-settings-2.2.1 typing_extensions-4.11.0
commit: unknown
```

**Comment by sydney-runkle** [comment]
Actually reopening, I think it's related but not the same!

**Comment by sydney-runkle** [comment]
@iambroadband,

I don't think your test as it stands should pass - model1 and model2 aren't equivalent, unless I'm missing something?

**Comment by iambroadband** [comment]
@sydney-runkle 

I see I have made a typo when writing my example code 🤦🏼I will fix it. Even when they _should_ be equivalent this test is failing on a TypeError, but it seems like #9223 is addressing that?
