### ISSUE TITLE
Inconsistent behaviour when parsing unions

### ISSUE THREAD

**Issue by Booplicate** [pydantic/pydantic#9224]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have 3 models: one base and two children, one of the children has an extra attribute. My API can accept either of the children.

Let's start from this example of code:
```py
from typing import TypeAlias

from pydantic import (
    BaseModel,
    RootModel,
    TypeAdapter,
)


class Base(BaseModel):
    foo: str

class A(Base):
    pass

class B(Base):
    bar: int

Something: TypeAlias = B | A


raw = {"bar": 225, "foo": "exists"}


ta = TypeAdapter(Something).validate_python(raw)
print(type(ta), ta)

rm = RootModel[Something].model_validate(raw)
print(type(rm.root), rm.root)

b = B.model_validate(raw)
print(type(b), b)
```

Output:
```
<class '__main__.B'> foo='exists' bar=225
<class '__main__.B'> foo='exists' bar=225
<class '__main__.B'> foo='exists' bar=225
```
Pydantic correctly parses into the model `B` using any of the tools provided 🚀 

Now let's change the `B.bar` field to `datetime.datetime` (this is my actual use case):
```py
import datetime
from typing import TypeAlias

from pydantic import (
    BaseModel,
    RootModel,
    TypeAdapter,
)


class Base(BaseModel):
    foo: str

class A(Base):
    pass

class B(Base):
    bar: datetime.datetime

Something: TypeAlias = B | A


raw = {"bar": "2024-04-10T00:00:00", "foo": "exists"}


ta = TypeAdapter(Something).validate_python(raw)
print(type(ta), ta)

rm = RootModel[Something].model_validate(raw)
print(type(rm.root), rm.root)

b = B.model_validate(raw)
print(type(b), b)
```

Output:
```
<class '__main__.A'> foo='exists'
<class '__main__.A'> foo='exists'
<class '__main__.B'> foo='exists' bar=datetime.datetime(2024, 4, 10, 0, 0)
```
Suddenly Pydantic fails to parse the union, but still can parse as `B` if asked directly 😕 

I read [the docs](https://docs.pydantic.dev/latest/concepts/unions/), which say Pydantic parses from left to right *and* tries to "rate" the match. That sounds cool and useful. But for some reason when your union has a model with a `datetime` field, it gets lower score even thought it matches *more* fields.

I'd try to test with the simple `left_to_right` mode, but there doesn't appear to be a way to specify the mode when parsing, only when you declare a `Field`, which I don't.

### Example Code

```Python
import datetime
from typing import TypeAlias

from pydantic import (
    BaseModel,
    RootModel,
    TypeAdapter,
)


class Base(BaseModel):
    foo: str

class A(Base):
    pass

class B(Base):
    bar: datetime.datetime

Something: TypeAlias = B | A


raw = {"bar": "2024-04-10T00:00:00", "foo": "exists"}


ta = TypeAdapter(Something).validate_python(raw)
print(type(ta), ta)

rm = RootModel[Something].model_validate(raw)
print(type(rm.root), rm.root)

b = B.model_validate(raw)
print(type(b), b)
```

### Python, Pydantic & OS Version

```Text
Python 3.11.4
pydantic 2.5.3
pydantic-core 2.14.6
```

**Comment by sydney-runkle** [comment]
@Booplicate,

Thanks for the detailed issue description. This indeed looks like a bug with how unions are validated. @davidhewitt might have some good initial insight here.

**Comment by Booplicate** [comment]
@sydney-runkle, np, let me know if I can help somehow else.

Today I encountered the issue again, this time without `datetime`, so I decided to experiment more:
```py
from typing import TypeAlias

from pydantic import (
    BaseModel,
    RootModel,
    TypeAdapter,
    Field,
)


class Base(BaseModel):
    foo: str

class A(Base):
    pass

class B(Base):
    bar: int

Something: TypeAlias = B | A


raw_good = {"bar": 225, "foo": "exists"}
raw_bad = {"bar": "225", "foo": "exists"}


for raw in (raw_bad, raw_good):
    print("Sample data:", raw)

    ta = TypeAdapter(Something).validate_python(raw)
    print("Did TypeAdapter work:", type(ta) is B)
    
    rm = RootModel[Something].model_validate(raw)
    print("Did RootModel work:", type(rm.root) is B)
    
    class CustomRootModel(RootModel[Something]):
        root: Something = Field(union_mode="left_to_right")
    crm = CustomRootModel.model_validate(raw)
    print("Did RootModel with simple union mode work:", type(crm.root) is B)
    
    b = B.model_validate(raw)
    print("Did Model work:", type(b) is B)

    print()
```
Output:
```
Sample data: {'bar': '225', 'foo': 'exists'}
Did TypeAdapter work: False
Did RootModel work: False
Did RootModel with simple union mode work: True
Did Model work: True

Sample data: {'bar': 225, 'foo': 'exists'}
Did TypeAdapter work: True
Did RootModel work: True
Did RootModel with simple union mode work: True
Did Model work: True
```

Model `B` requires an `int`. If the field was passed as an int, pydantic will do the right thing. However if the field was passed as a string (while still being a valid int), it won't.

I think it's a problem of priorities/weights: pydantic prefers a model with less matching fields than a model where it has to do a cast (for example `str`>`int` or `str`>`datetime`) even if that leads to a more "complete" model.

This behaviour can work for the strict mode in the case of `int`/`str`. However date and time are often dumped as strings in JSON (ISO format), so that logic doesn't work. Plus since I'm using the lax mode I'm expecting pydantic to implicitly cast `str` to `int` as it does with normal models.

I'd guess it's somewhere in smart mode handling or pydantic core unmarshalling logic, but I have little knowledge of pydantic internals to fix it on my own yet.
