### ISSUE TITLE
Pydantic version checking issue with v1.10.15

### ISSUE THREAD

**Issue by Felflare** [pydantic/pydantic#9225]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Pydantic v1.10.15 contains alias to the v1 version of Pydantic.
This creates issues for package developers who in the past relied on simple scripts as the one below to ensure their package is supported by a broad base of users (users of v1 and v2).

```python
try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore
```

Since the new version of pydantic v1.10.15 contains the v1 alias, this is causing issues elsewhere.
- https://github.com/cohere-ai/cohere-python/pull/452/files
- https://github.com/langfuse/langfuse/issues/1581
(More can be found if you search pydantic 1.10.15)

Since v1.10.15 is already Pydantic v1 by definition, should it even have this alias to the v1?

### Example Code

```Python
# support users with both pydantic v1 and v2
try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore

print(pydantic.json.ENCODERS_BY_TYPE)

# the following outputs

E   AttributeError: module 'pydantic.v1' has no attribute 'json'. Did you mean: 'Json'?
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.15
            pydantic compiled: True
                 install path: <....>/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@Felflare,

Thanks for bringing this to our attention. I'll bring this up with the team early next week and we'll chat about the best way to move forward!

**Comment by sydney-runkle** [comment]
@Felfare,

I think the best way forward is going to just be to check the version of pydantic directly, rather than depending on the success of the import above. Closing as resolved!
