### ISSUE TITLE
Upgrading from Pydantic 2.6.4 -> 2.7.0 throws ModuleNotFoundError.

### ISSUE THREAD

**Issue by mgsimpson-i2** [pydantic/pydantic#9226]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a project (managed via Poetry) that has Pydantic as a dependency; we've been using Pydantic 2.6.x for some time with no issues.

I updated my project dependencies (including Pydantic) this morning, which included pulling in Pydantic 2.7.0, and previously-running code now produces:

```
.venv/lib/python3.12/site-packages/pydantic/__init__.py:374: in <module>
    _getattr_migration = getattr_migration(__name__)
.venv/lib/python3.12/site-packages/pydantic/_migration.py:260: in getattr_migration
    from .errors import PydanticImportError
.venv/lib/python3.12/site-packages/pydantic/errors.py:6: in <module>
    from typing_extensions import Literal, Self
E   ModuleNotFoundError: No module named 'typing_extensions'
```

Environment is Python 3.12, and I've deleted and recreated the virtual environment and re-installed all dependencies to make sure there was nothing odd happening there.

### Example Code

```Python
from pydantic import BaseModel
```

### Python, Pydantic & OS Version

```Text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/msimpson/Desktop/Projects/i2ns/systems/insight/python/i2ns-insight-api/.venv/lib/python3.12/site-packages/pydantic/__init__.py", line 374, in <module>
    _getattr_migration = getattr_migration(__name__)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/msimpson/Desktop/Projects/i2ns/systems/insight/python/i2ns-insight-api/.venv/lib/python3.12/site-packages/pydantic/_migration.py", line 260, in getattr_migration
    from .errors import PydanticImportError
  File "/Users/msimpson/Desktop/Projects/i2ns/systems/insight/python/i2ns-insight-api/.venv/lib/python3.12/site-packages/pydantic/errors.py", line 6, in <module>
    from typing_extensions import Literal, Self
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by Viicos** [comment]
Could you give more info about how `pydantic` was installed in Poetry? `typing_extensions` is correctly specified as a dependency so something is probably wrong on your end

**Comment by fabio-gallotti-illimity** [comment]
Hello, I've encountered the same problem.
Seems like that installing pydantic@2.7.0 with poetry, it doesn't install also `pydantic_core` and `annotated_types`

**Comment by mgsimpson-i2** [comment]
Vilcos --

Poetry runs dependency tracking off of `pyproject.toml`; the relevant section of that file for my prokect looks like:

```
[tool.poetry.dependencies]
blessings = "^1.7"
email-validator = "^2.1.1"
icecream = "^2.1.3"
pydantic = "^2.6.4"
pyjwt = {extras = ["crypto"], version = "^2.8.0"}
python = "^3.12"
result = "^0.16.1"
```

The burn-it-down-and-reinstall-from scratch procedure I use involved removing the virtual environment created by Poetry, removing the Poetry lockfile, and then invoking `poetry install`, which triggers the dependency resolution and installation of the new virtual environment, e.g.:

```
$ rm -rf .venv
$ rm poetry.lock
$ poetry install
Creating virtualenv in .venv
Updating dependencies
Resolving dependencies... (20.8s)

Package operations: 65 installs, 0 updates, 0 removals

  • Installing certifi (2024.2.2)
  • Installing charset-normalizer (3.3.2)
  • Installing idna (3.7)
  • Installing markupsafe (2.1.5)
  • Installing urllib3 (2.2.1)
  • Installing alabaster (0.7.16)
  • Installing babel (2.14.0)
  • Installing docutils (0.20.1)
  • Installing imagesize (1.4.1)
  • Installing jinja2 (3.1.3)
  • Installing mdurl (0.1.2)
  • Installing packaging (24.0)
  • Installing pycparser (2.22)
  • Installing pygments (2.17.2)
  • Installing requests (2.31.0)
  • Installing six (1.16.0)
  • Installing snowballstemmer (2.2.0)
  • Installing sphinxcontrib-applehelp (1.0.8)
  • Installing sphinxcontrib-devhelp (1.0.6)
  • Installing sphinxcontrib-htmlhelp (2.0.5)
  • Installing sphinxcontrib-jsmath (1.0.1)
  • Installing sphinxcontrib-qthelp (1.0.7)
  • Installing sphinxcontrib-serializinghtml (1.1.10)
  • Installing asttokens (2.4.1)
  • Installing cffi (1.16.0)
  • Installing executing (2.0.1)
  • Installing markdown-it-py (3.0.0)
  • Installing parso (0.8.4)
  • Installing pbr (6.0.0)
  • Installing ptyprocess (0.7.0)
  • Installing pure-eval (0.2.2)
  • Installing setuptools (69.2.0)
  • Installing sphinx (7.2.6)
  • Installing traitlets (5.14.2)
  • Installing wcwidth (0.2.13)
  • Installing colorama (0.4.6)
  • Installing cryptography (42.0.5)
  • Installing decorator (5.1.1)
  • Installing dnspython (2.6.1)
  • Installing matplotlib-inline (0.1.6)
  • Installing nodeenv (1.8.0)
  • Installing pexpect (4.9.0)
  • Installing pluggy (1.4.0)
  • Installing prompt-toolkit (3.0.43)
  • Installing pyyaml (6.0.1)
  • Installing rich (13.7.1)
  • Installing sphinxcontrib-jquery (4.1)
  • Installing stack-data (0.6.3)
  • Installing stevedore (5.2.0)
  • Installing iniconfig (2.0.0)
  • Installing jedi (0.19.1)
  • Installing bandit (1.7.8)
  • Installing blessings (1.7)
  • Installing coverage (7.4.4)
  • Installing email-validator (2.1.1)
  • Installing icecream (2.1.3)
  • Installing ipython (8.23.0)
  • Installing pyjwt (2.8.0)
  • Installing pytest (8.1.1)
  • Installing result (0.16.1)
  • Installing ruff (0.3.7)
  • Installing semantic-version (2.10.0)
  • Installing sphinx-rtd-theme (2.0.0)
  • Installing pydantic (2.7.0)
  • Installing pyright (1.1.358)

Writing lock file
```

Hope that helps.

**Comment by mgsimpson-i2** [comment]
Also, just to note, if I lock the Pydantic dependency in `pyproject.toml` to 2.6.4, i.e. change:
```
pydantic = "^2.6.4"
```
to:
```
pydantic = "2.6.4"
```
everything starts working again.

**Comment by mgsimpson-i2** [comment]
Ah, interesting, my Poetry install is downrev'd (1.7.1) -- let me update that to current and see if things resolve.

**Comment by mgsimpson-i2** [comment]
Nope, same behavior -- let me do a test project with only Pydantic as a dependency and see what happens.

**Comment by mgsimpson-i2** [comment]
Fascinating. So with a new project, with current version Poetry and this `pyproject.toml` file:
```
$ cat pyproject.toml
[tool.poetry]
name = "miketest"
version = "0.1.0"
description = ""
authors = ["Mike Simpson <msimpson@internet2.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
I see these dependency pulls when I run `poetry install`:
```
$ poetry install
Creating virtualenv miketest in .venv
Updating dependencies
Resolving dependencies... (0.9s)

Package operations: 4 installs, 0 updates, 0 removals

  - Installing typing-extensions (4.11.0)
  - Installing annotated-types (0.6.0)
  - Installing pydantic-core (2.18.1)
  - Installing pydantic (2.7.0)

Writing lock file

Installing the current project: miketest (0.1.0)
```
So it's definitely pulling the deps that appear to be missing in my earlier runs in my main project ... let me experiment with adding the other deps in one at a time and see if there's some point where the behavior suddenly alters and drops those Pydantic deps, maybe there's some weird version conflict that's causing the problem.

**Comment by mgsimpson-i2** [comment]
Also, just to document it for posterity, I didn't know about this command, and it's great:
```
$ poetry show --tree
blessings 1.7 A thin, practical wrapper around terminal coloring, styling, and positioning
└── six *
email-validator 2.1.1 A robust email address syntax and deliverability validation library.
├── dnspython >=2.0.0
└── idna >=2.0.0
pydantic 2.7.0 Data validation using Python type hints
├── annotated-types >=0.4.0
├── pydantic-core 2.18.1
│   └── typing-extensions >=4.6.0,<4.7.0 || >4.7.0
└── typing-extensions >=4.6.1
```

**Comment by mgsimpson-i2** [comment]
Sigh. Found the problem -- well, at least I found the source of the problem for my originally-reported issue. We're using AWS CodeArtifact as our upstream default package source, with PyPi as the fallback, e.g. this configuration in `pyproject.toml`:
```
[[tool.poetry.source]]
name = "aws-codeartifact-i2ns-pypi"
url = "https://{**** elided ***}.us-east-1.amazonaws.com/pypi/pypi/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
priority = "supplemental"
```
That CodeArtifact repo is supposed to act as a transparent proxy back to PyPi, but the behavior I'm seeing is that with the above config, Pydantic 2.7.0 gets pulled but none of its dependencies. If I change the config so that we're pulling straight from PyPi (rather than pulling from PyPi "through" CodeArtifact) everything works correctly -- Pydantic 2.7.0 gets pulled along with its expected deps.

So for my case at least, this is an issue with the CodeArtifact cache of the upstream PyPi artifacts, I think.

@fabio-gallotti-illimity Are you doing something similar by any chance? If it's the same issue for both of us, I think we can blame AWS and close out this ticket, with my apologies to @Viicos for wasting his time. :)

**Comment by samuelcolvin** [comment]
Great investigation @mgsimpson-i2.

I wonder if CodeArtifact somehow ignores dependencies of packages that come from pypi (in this case because they're not yet cached in code artifact) but use dependencies from code artifact to, to guard against some kind of supply chain attack? Did you look at the hashes in the `poetry.lock` file?

I'll close this, but happy to reopen if anyone finds an issue with this project.

**Comment by mgsimpson-i2** [comment]
Just following up for the sake of completeness -- with PyPi configured as "primary", and CodeArtifact configured as "supplemental" -- so preferring direct PyPi pulls for dependencies, the `poetry.lock` entry for Pydantic looks like this:
```
[[package]]
name = "pydantic"
version = "2.7.0"
description = "Data validation using Python type hints"
optional = false
python-versions = ">=3.8"
files = [
    {file = "pydantic-2.7.0-py3-none-any.whl", hash = "sha256:9dee74a271705f14f9a1567671d144a851c675b072736f0a7b2608fd9e495352"},
    {file = "pydantic-2.7.0.tar.gz", hash = "sha256:b5ecdd42262ca2462e2624793551e80911a1e989f462910bb81aef974b4bb383"},
]
```
Flipping the config (preferring pulling through CodeArtifact for all deps) that entry changes to this:
```
[[package]]
name = "pydantic"
version = "2.7.0"
description = ""
optional = false
python-versions = "*"
files = [
    {file = "pydantic-2.7.0-py3-none-any.whl", hash = "sha256:9dee74a271705f14f9a1567671d144a851c675b072736f0a7b2608fd9e495352"},
    {file = "pydantic-2.7.0.tar.gz", hash = "sha256:b5ecdd42262ca2462e2624793551e80911a1e989f462910bb81aef974b4bb383"},
]
```
Interestingly, the hashes don't change, but some of the metadata fields are missing.

So, best working theory right now is that AWS CodeArtifact has a bad/partial/something version of Pydantic 2.7.0 cached in their PyPi mirror -- I tried to clear out my own CodeArtifact cache but it looks like AWS is maybe using a single big backing cache for all of those PyPi pulls, which would make sense in terms of efficiency.

My hope is that sometime in the next few days CodeArtifact will do some kind of TTL refresh and pull a good copy; failing that, for my project at least it's no real hassle to use PyPi as primary and CodeArtifact as supplemental for our locally-built artifacts.

**Comment by Viicos** [comment]
> with my apologies to @Viicos for wasting his time. :)

No time wasted, glad this is now documented as an issue. I'd be interested to know: what happens if you try installing these without Poetry? (e.g. pip or uv)

**Comment by mgsimpson-i2** [comment]
Testing in a new virtual environment, `pip` seems to run clean and as expected (dependencies get pulled). So there's a chance that this is some weird interaction between Poetry and AWS CodeArtifact; but the caveat is that I don't normally point `pip` at CodeArtifact -- I just tried it for the first time using some boilerplate from the AWS docs -- so I may not be doing an apples-to-apples comparison.

**Comment by Viicos** [comment]
Hum yeah you have options in `pip` with `--index-url` and `--extra-index-url` I believe, but hard to tell if the same behavior applies with Poetry :/

**Comment by Viicos** [comment]
Turns out this is a Poetry issue: https://github.com/python-poetry/poetry/issues/9301
