### ISSUE TITLE
Exclude private attributes (`PrivateAttr`) from dataclass constructor

### ISSUE THREAD

**Issue by idan22moral** [pydantic/pydantic#9234]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I came across #9192 while trying to find a clue as to why private attributes (`PrivateAttr`) are not excluded from the (BaseModel) constructor, just like how fields (`Field`) are excluded when setting `init=False`.

The [documentation](https://docs.pydantic.dev/2.7/concepts/models/#private-model-attributes) states that private attributes:
> are converted into a "private attribute" which is not validated or even set during calls to __init__, model_validate, etc.

So, in a slightly better world, when I have this class:
```py
class Person(BaseModel):
    _secret: str = PrivateAttr()
```
instantiation of `Person` in this form (with private attributes as parameters) should not be allowed:
```py
Person(_secret='boop')
```

My proposal is to simply remove the private attributes from the parameters passed to the `__init__` function.  

If there is a concern for backward-compatibility (assuming that users send value to private attributes in the constructor even though these values are ignored), the same concept from #8552 can be applied (adding `init=False` flag).  
Though I think this is a not-so-good idea and the change should break compatibility in favor of better interface and less unclear behavior.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\none\AppData\Roaming\Python\Python312\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.109.0 typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@idan22moral,

Thanks for the proposal here. I think a better route forward would probably be to emit a warning in this case, not to disallow it entirely. I think disallowing would have to wait for a major release. Feel free to open a PR adding the `warning` logic, if you'd like!

**Comment by idan22moral** [comment]
Thanks for your answer, @sydney-runkle 😊 

I've dug further into it, and it seems that besides the fact that pydantic allows private attributes in the `BaseModel` constructor, it does a good job of generating a clean constructor signature. We can see it in the `__signature__` field of the model, for example:
![image](https://github.com/pydantic/pydantic/assets/19193227/ee89a346-fb77-4396-80af-a88f3587d29c)

To be more clear, I'm using vscode, together with the Python (v2024.4.1), Pylance (v2024.4.1) and Ruff (v2024.16.0) extensions.  
What made me open this issue in the first place is the signature that Pylance showed me for the example above, which was:
![image](https://github.com/pydantic/pydantic/assets/19193227/cdfc8eee-44d5-43eb-bbf6-9431dd995aee)

As you can see, it's clearly much more verbose and confusing than the actual signature generated by pydantic (which is clear and correct).

So, while we can implement the `warning` logic as you said, I think I'll try to consult our friends over at [microsoft/pylance-release](https://github.com/microsoft/pylance-release) first.

**Comment by idan22moral** [comment]
@sydney-runkle After some more research, I think I've found a solution that's both backward-compatible and satisfies the type-checking needs.
It seems that the root cause of the bad signature that Pylance gives me is the fact that `PrivateAttr` is not considered a [field specifier](https://typing.readthedocs.io/en/latest/spec/dataclasses.html#field-specifiers).

So, to let the type checkers know that `PrivateAttr` is a "field" that should not be part of the `__init__` parameters, we need to:
1. make `PrivateAttr` a field specifier.
2. add an `init` parameter to the `PrivateAttr` function, _ideally_ (this is a topic for discussion, of course) with type `Literal[False]` to never allow private attributes in `__init__`.

According to the definition of [runtime behavior](https://typing.readthedocs.io/en/latest/spec/dataclasses.html#runtime-behavior) of `dataclass_transform` and the fact that Pydantic does not use `__dataclass_transform__`,  
we can safely say that these changes do not affect Pydantic, but it does affect type checkers.

I made a draft PR #9293 that applies my proposed changes. I think more work regarding the added `init` parameter is welcome. If we decide that `init` should not be `Literal[False]` (which is a fair decision), we can drop the dedicated commit that I made for that change.

**Comment by Pyrrha** [comment]
Hello,

I just encountered the same bug, but using `dataclass` from `pydantic.dataclasses`.
Should/can the same behavior be applied for this annotation as well?

**Comment by sydney-runkle** [comment]
Hi @idan22moral,

Thanks for looking into this with backwards compatibility in mind! Will take a look at your PR here shortly.

Curious to hear what @Viicos thinks about this approach, he seemed quite informed about all things `dataclass-transform` related :).
