### ISSUE TITLE
Provide support for using computed_field as Union discriminator 

### ISSUE THREAD

**Issue by weibeu** [pydantic/pydantic#9245]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This would allow to use the pydanatic models in following way:

```python
import enum
from pydantic import BaseModel, computed_field

class SpeciesType(enum.Enum):
    MAMMLE = "MAMMLE"

Class Cat(BaseModel):

    @computed_field
    @property
    def species_type(self) -> SpeciesType:
        return SpeciesType.MAMMLE
```

The information of cat being species should be available at runtime along with the instance of the Cat.
This is something equivalent to using a ClassVar as discriminator which doesn't works for now.

I could use ClassVar but it doesn't makes the species_type available within the instance.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Seems like a reasonable feature request, PRs welcome!

**Comment by NeevCohen** [comment]
I started working on this and it seemed a little strange to me.
Discriminating unions are based on literal values which are evaluated at model definition time.

In the following example, the connection between the `Cat` model and the `MAMMAL` species is made at the time the model is defined since it must be known before usage.

```python
class Cat(BaseModel):
    species: Literal['MAMMAL']
```

Using a computed field as a discriminator could perhaps look like so

```python
class Cat(BaseModel):
    @computed_field
    def species(self) -> Literal['MAMMAL']
        return 'MAMMAL'
```

That could work but seems a little strange to me since the return value of the computed field does not affect the result at all, just the type hint of the return type, which must be a literal anyways.

I hope explained myself clearly 😅 

@weibeu @sydney-runkle perhaps I'm missing something?

**Comment by weibeu** [comment]
It is not really really necessary to use computed_field to achieve our desired behaviour. This was more of a possiblity or hack I thought of.

The way really we should progress is that attempt to make the `species` field accessible as a class attribute as well as an instance attribute.

If we are able to provide some method or way to achieve the above point, then pydantic discriminator would get to work normally.

This intuition comes from the fact that any arbitrary Python class attribute is also accessible from its instance. Therefore in my opinion, it really makes sense to provide some special type hint, which would make the field `species` available to both class and the instance.

Only after this, we shall proceed forward to enable / consider this special class+instance attribute for the discriminator to consider for. This way it becomes easier and intuitive as well. As discriminator always works on some instance attribute (or should be made work for if doesn't).


A nice API could be:

```python
import enum
from typing import ClassVar

from pydantic import BaseModel, Field


class SpeciesType(enum.Enum):
    MAMMLE = "MAMMLE"
    REPTILE = "REPTILE"


class Cat(BaseModel):
    nickname: str
    species: ClassVar[SpeciesType] = Field(SpeciesType.MAMMLE, classvar=True)


class Snake(BaseModel):
    nickname: str
    species: ClassVar[SpeciesType] = Field(SpeciesType.REPTILE, classvar=True)


# The following should work.
>>> Cat.species is SpeciesType.MAMMLE
>>> True

# This should also work.
>>> mycat = Cat()
>>> mycat.species is SpeciesType.MAMMLE
>>> True

# Then later somewhere we could easily use this as a proper valid discriminator.


class PetShopCartItem(BaseModel):
    pet: Cat | Snake = Field(..., discriminator='species')


>>> cart_item = PetShopCartItem(
    **{
            "nickname": "sipu",
            "species": SpeciesType.REPTILE
        }
)

# Expected or desired behavior
>>> isinstance(cart_item.pet, Snake)
>>> True

**Comment by NeevCohen** [comment]
@weibeu so if I understand correctly, you want to be able to access the value of the discriminator from the class itself as well as the instance?

**Comment by weibeu** [comment]
@NeevCohen Right.

Apparently, this should be the expected behaviour as well in my opinion.

This way, it would be easy shot to make discriminator work for these cases.

**Comment by NeevCohen** [comment]
The problem with `ClassVar` is that they do not become fields on the model instances as per [the docs](https://docs.pydantic.dev/2.7/concepts/models/#class-vars)

> Attributes annotated with typing.ClassVar are properly treated by Pydantic as class variables, and will not become fields on model instances

So I'm not sure that's the correct way to go.

@sydney-runkle WDYT?

**Comment by weibeu** [comment]
Yep exactly. That's why I had assumed a special meta keyword to Field `classvar=True` to indicate a special behaviour where this certain attribute is a class attribute but also should be retained as a Field in the instance.

**Comment by NeevCohen** [comment]
@sydney-runkle bump

**Comment by sydney-runkle** [comment]
@NeevCohen,

Thanks for the bump. Honestly, I thought you did a great job explaining the complications associated with this request in your comment [here](https://github.com/pydantic/pydantic/issues/9245#issuecomment-2064921751).

Going to close this as not planned for now, as I think the demand is low, and the use case doesn't seem super compelling.

Great work on talking through the complexities for this feature request.
