### ISSUE TITLE
Base64Bytes field doesn't raises validation error for min_length constraint

### ISSUE THREAD

**Issue by kirillklimenko** [pydantic/pydantic#9251]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The validation should raise an error due to the minimum length constraint set for the `data` field in the `Test` model. However, no validation error is raised even though the `data` field is empty.

### Expected Behavior:
Passing empty data for the `data` field should raise a validation error due to the minimum length constraint set in the `Test` model.

### Actual Behavior:
No validation error is raised when passing empty data for the `data` field.

### Steps to Reproduce:

Define the provided models in a Pydantic-based Python script.
Attempt to validate input data where the `data` field is empty.
Notice that no validation error is raised even though the `data` field does not meet the minimum length constraint.
Additional Information:
This behavior was observed in Pydantic version `2.6.4`.

### Example Code

```Python
from pydantic import Base64Bytes, BaseModel, Field


class Test(BaseModel):
    data: Base64Bytes = Field(min_length=10)


test = Test(data=b"")  # no validation error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
pydantic-core version: 2.16.3
pydantic-core build: profile=release pgo=true
python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
platform: Windows-10-10.0.22631-SP0
```

**Comment by sydney-runkle** [comment]
@kirillklimenko,

Thanks for reporting, definitely a bug! PRs welcome with a fix!

**Comment by mikeleppane** [comment]
@sydney-runkle can I take a look at this?

**Comment by gitFire001** [comment]
I would like to take a look at it! Where should I start looking at?

**Comment by danbailo** [comment]
I wanna to contribute too, but, idk how to debug it, it's my first time trying to submit anything in this project. Any suggest?

**Comment by RektPunk** [comment]
I think this is related to encode, decode logic since even when converted `Base64Bytes` to `Base64Str`, there is no validation error too. We can avoid it by creating a custom validator, but I still don't know the exact cause. 🥲

**Comment by sydney-runkle** [comment]
I'd guess you could start with the core schema build - do we even attach the relevant metadata? Then, you might have to move into pydantic core to check the validation logic.
