### ISSUE TITLE
Nested Literals together with PEP-695 type statement are failed to produce json schema

### ISSUE THREAD

**Issue by AlexanderPodorov** [pydantic/pydantic#9269]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

See example code

### Example Code

```Python
from typing import Literal

from pydantic import BaseModel

type TestType0 = Literal["test1", "test2"]
type TestType1 = Literal[TestType0, Literal["test3"]]
type TestType2 = Literal[Literal["test1", "test2"], Literal["test3"]]


# TestType1 does not work
# TestType2 works
class Model(BaseModel):
    f: TestType1


print(Model.model_json_schema())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
               python version: 3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-13.0.1-arm64-arm-64bit
             related packages: typing_extensions-4.11.0 fastapi-0.110.1 pydantic-extra-types-2.6.0 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by Viicos** [comment]
I've raised [a discussion](https://discuss.python.org/t/literal-and-pep-695-type-aliases/69857) to clarify what should happen here. If this ends up being allowed, here is a list of tasks that should be tackled:
- Unify `Literal[<x>] | Literal[<y>]` as `Literal[<x>, <y>]`, to avoid unnecessarily constructing a union schema.
- In `_typing_extra.literal_values`, follow any `TypeAliasType` instance to fecth the literal values
