### ISSUE TITLE
AliasChoices/AliasPath incompatible with .model_construct()

### ISSUE THREAD

**Issue by gregouar** [pydantic/pydantic#9311]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In v2.7 was introduced the use of 'validation_alias' within .model_construct(). 
However, the current implementation suppose that validation_alias is of str type and not AliasChoices or AliasPath, resulting in an error trying to hash the validation_alias to use as key in the model_fields dict. 
I suggest that model_construct branches on instance type of validation_alias if not None.

### Example Code

```Python
import pydantic

class MyModel(pydantic.BaseModel):
    field: str = pydantic.Field(
        validation_alias=pydantic.AliasChoices("field", "Field"),
    )

MyModel.model_construct(Field="test")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\nag\OneDrive\Dev\Python\Cis\Main\cis_az_functions\.venv\Lib\site-packages\pydantic
               python version: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: email-validator-2.0.0.post2 fastapi-0.104.1 mypy-1.7.1 typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Should be fixed in 2.7.1!
