### ISSUE TITLE
An appropriate model cannot be created when using the IntEnum type in Python with values greater than 1<<63.

### ISSUE THREAD

**Issue by Jassy930** [pydantic/pydantic#9314]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

An appropriate model cannot be created when using the IntEnum type in Python with values greater than 1<<63.
which is allowed in pydantic v1.

I suspect the reason might be due to Rust's i64 type restrictions not supporting larger integer values, but it indeed feels inconsistent when using IntEnum for bitwise tagging.

### Example Code

```Python
from pydantic import BaseModel
from enum import IntEnum


class ColorEnum(IntEnum):
    RED = 1
    GREEN = 1 << 63
    BLUE = 1 << 64


class model(BaseModel):
    color: ColorEnum


print(ColorEnum.GREEN.name, ColorEnum.GREEN.value)
print(ColorEnum.BLUE.name, ColorEnum.BLUE.value)

model.model_validate({"color": ColorEnum.GREEN.value})
model.model_validate_json('{"color": 9223372036854775808}')

model.model_validate({"color": ColorEnum.BLUE.value})
model.model_validate_json('{"color": 18446744073709551616}')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: /opt/homebrew/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by Jassy930** [comment]
And I did not find anything in the migration documentation or elsewhere to suggest that this is an intentional difference after the migration, perhaps something that could usefully be added to the migration documentation.

**Comment by sydney-runkle** [comment]
@Jassy930,

Thanks for reporting this. Definitely doesn't seem intentional. Adding this to the 2.7 fixes milestone, as I think we could address this when we rewrite the int enum validator (hopefully soon).

**Comment by samuelcolvin** [comment]
Thanks for reporting @Jassy930, this should be fixed in https://github.com/pydantic/pydantic-core/pull/1297.
