### ISSUE TITLE
Make walk_core_schema public

### ISSUE THREAD

**Issue by rmorshea** [pydantic/pydantic#9320]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently [`pydantic._internal._core_utils.walk_core_schema`](https://github.com/pydantic/pydantic/blob/6b992fda730e1b123f2116d2a318faff636e1111/pydantic/_internal/_core_utils.py#L400) is private, but it has enough utility that it ought to be made public. I've found it extremely useful modifying Pydantic schemas in order to suite my needs. In particular https://github.com/pydantic/pydantic/issues/8279#issuecomment-2080327559, where I've managed to work around the issue described in that discussion by walking the schema and wrapping `is-instance` schemas in a `json-or-python` schema that implements custom validation/serialization logic for a set of known third party types.

The relatively stable nature of Pydantic V2's schemas means it would be possible for someone to implement their own version of this function (that's actually what I did before I discovered `walk_core_schema`) but it would be great to rely on one maintained in Pydantic.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @rmorshea,

Thanks for your feature request. The `walk_core_schema` logic is most definitely still under development, in terms of both performance improvements and logic modifications. I don't think it's likely that we'll make this a public utility anytime soon given the quite frequent changes that we currently make to it, and I think we want to reserve the right of privacy in order to guarantee the faster development cycles.

Glad you've been finding it helpful though!

**Comment by rmorshea** [comment]
I've released this as a separate package on PyPI: https://github.com/rmorshea/pydantic-walk-core-schema
