### ISSUE TITLE
Exclude with __all__ fails on Sequence fields

### ISSUE THREAD

**Issue by MatthieuSarter** [pydantic/pydantic#9328]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When trying to exclude subfields fields in model_dump_json on a model with fields defined as Sequence[something], serialization fails with "Error calling function `serialize_sequence_via_list`: ValueError: Negative indices cannot be used to exclude items on unsized iterables".

Types matching the Sequence generic type have a length and accepts negative indices according to Python doc: https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range

The serialization works fine when using list[something] instead of Sequence[something], but when using this mypy forbids to override with list[subclass of something] in subclasses of the model.

This was working fine with Sequence until updating from Pydantic 2.6.x to 2.7.1.

### Example Code

```Python
from typing import Sequence

from pydantic import BaseModel

exclude = {"releases": {"__all__": {"build": True}}}


class Release(BaseModel):
    version: str
    name: str
    desc: str


class BundleSeq(BaseModel):
    releases: Sequence[Release]


class BundleList(BaseModel):
    releases: list[Release]


r1 = Release(name="Foo", version="1.0", desc="Foo v1.0")
r2 = Release(name="Bar", version="2.0", desc="Bar v2.0")
b1 = BundleSeq(releases=[r1, r2])
b2 = BundleList(releases=[r1, r2])

try:
    print(b1.model_dump_json(exclude=exclude))
except Exception as e:
    print(e)

print(b2.model_dump_json(exclude=exclude))

# Output:
# Error serializing to JSON: PydanticSerializationError: Error calling function `serialize_sequence_via_list`: ValueError: Negative indices cannot be used to exclude items on unsized iterables
# {"releases":[{"version":"1.0","name":"Foo","desc":"Foo v1.0"},{"version":"2.0","name":"Bar","desc":"Bar v2.0"}]}
#
# Expected output:
# {"releases":[{"version":"1.0","name":"Foo","desc":"Foo v1.0"},{"version":"2.0","name":"Bar","desc":"Bar v2.0"}]}
# {"releases":[{"version":"1.0","name":"Foo","desc":"Foo v1.0"},{"version":"2.0","name":"Bar","desc":"Bar v2.0"}]}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\matth\AppData\Local\pypoetry\Cache\virtualenvs\[redacted]-py3.12\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: fastapi-0.110.2 mypy-1.10.0 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@MatthieuSarter,

Thanks for reporting this. Will work on a fix for 2.7.2!

**Comment by sydney-runkle** [comment]
Working on this now!

**Comment by sydney-runkle** [comment]
This is definitely a bug I introduced here: https://github.com/pydantic/pydantic/commit/477e0a2e23fa7262a1365129a99acb586ee3baa5. Blocked on a fix, going to chat with @davidhewitt about the right core schema to use here.
