### ISSUE TITLE
Confusing handling of badly defined `model_validator` 

### ISSUE THREAD

**Issue by TimChild** [pydantic/pydantic#9334]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

If there is a bad `model_validator` that forgets to return `self` then `SomeModel.model_validate(dict_obj)` returns `None`  while `SomeModel(**dict_obj)` continues to return the validated model. 

This makes it seem like there is an issue with the `.model_validate` method, but obviously it's because of the bad validator... 

This might have been the cause of #7055 (that's what I found when I first had the issue).

So, not quite a bug given that the code all works correctly if the user doesn't do something stupid... But, it would have been nice to be told I was stupid via a meaningful error or warning :)

### Example Code

```Python
from pydantic import BaseModel, model_validator, ValidationError


class SomeModel(BaseModel):
    a: int

    @model_validator(mode="after")
    def validate_a(self):
        if self.a == 10:
            raise ValueError("Bad")
        # Should return `self` here... but "accidentally" ommitting it to show confusing behaviour that results from this.

if __name__ == "__main__":
    # Confusing behaviour is that model_validate returns None while direct instantiation does not
    gets_none = SomeModel.model_validate({"a": 5})
    assert gets_none is None, "This is somewhat surprising (although obviously the result of a bad validator)"

    gets_value = SomeModel(**{"a": 5})
    assert isinstance(gets_value, SomeModel), "This confuses the matter by still returning a value..."

    # Both correctly raise validation errors still
    try:
        SomeModel.model_validate({"a": 10})
        print("Does not get to here")
    except ValidationError as e:
        print("Correctly raises validation")

    try:
        SomeModel(**{"a": 10})
        print("Does not get to here")
    except ValidationError as e:
        print("Correctly raises validation")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/tim/.cache/pypoetry/virtualenvs/backend-dvWTEZau-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.11.0 pydantic-settings-2.2.1 fastapi-0.109.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Agreed, a more helpful warning message would be helpful here. PR welcome with added support for this :).

**Comment by Viicos** [comment]
I'll probably work on this!

**Comment by Viicos** [comment]
Taking a look at it, we could error [here](https://github.com/pydantic/pydantic-core/blob/1cefeae57609a876842b29c3ccba9df14aeae9ad/src/validators/function.rs#L162-L177) on the pydantic-core side:

```rs
impl FunctionAfterValidator {
    fn _validate<'py, I: Input<'py> + ?Sized>(
        &self,
        call: impl FnOnce(&I, &mut ValidationState<'_, 'py>) -> ValResult<PyObject>,
        py: Python<'py>,
        input: &I,
        state: &mut ValidationState<'_, 'py>,
    ) -> ValResult<PyObject> {
        let v = call(input, state)?;
        let r = if self.info_arg {
            let info = ValidationInfo::new(py, state.extra(), &self.config, self.field_name.clone());
            self.func.call1(py, (v.to_object(py), info))
        } else {
            self.func.call1(py, (v.to_object(py),))
        };
        r.map_err(|e| convert_err(py, e, input))
        // Check if the value is `None`
    }
}
```

However, I'm unsure if the `FunctionAfterValidator` is also used in other places, e.g. with field validators where `None` would be a valid value returned by the validator?

As a side note, this can be prevented by using a type checker (and I'll implement a rule in `flake8-pydantic` soon), plus you will notice during development (as opposed to during runtime if adding an explicit check as suggested)

**Comment by antoniojkim** [comment]
@Viicos Is what you are saying that there is no way to differentiate between a `field_validator` and a `model_validator`?

Is there any situation where returning `None` in a `model_validator` makes sense? If not, it would be great to just assume that the user means `return self` if `None` is returned from `model_validator`. Better even would be to give users the option to configure it. That way, the user can choose to allow returning `None` in a `model_validator` if they _really_ want to.

> this can be prevented by using a type checker

This is nice and all, but we cannot enforce users to use a type checker. So, if they encounter this issue the outcome should be consistent.

This is especially prominent in a case like the following trivial example:
```python
class A(BaseModel):
    a: int

    @model_validator(mode="after"):
    def validate_a(self):
        if self.a > 10:
            raise ValueError("a must be less than 10")

class B(BaseModel):
    b: A

b = B(b=A(a=1))
print(b.b.a)
```
which leads to
```
AttributeError: 'NoneType' object has no attribute 'a'
```
This is especially problematic as `B.b` is not a nullable type and thus the user will not expect the value to be `None`. This only causes more confusion as the underlying issue (`model_validator` did not return `self`) is not at all apparent given the error message.

**Comment by sydney-runkle** [comment]
I think you make a good point here. We've added a new warning for this case:

```
UserWarning: A custom validator is returning a value other than `self`.
Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.
See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.
```

https://github.com/pydantic/pydantic/pull/10255

Going to mark as resolved for now.

**Comment by TimChild** [comment]
@sydney-runkle -- That's great! I'm sure it won't be long before that warning saves me lots of time :)
