### ISSUE TITLE
False-positive SchemaError for keyword-only arg ordering: non-default argument following default argument

### ISSUE THREAD

**Issue by rsokl** [pydantic/pydantic#9337]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Decorating a function -- that has a keyword-only non-default argument following a default argument -- with `@pydantic.validate_call` results in a `SchemaError`.

E.g. the following

```python
import pydantic

@pydantic.validate_call()
def foo(*, x: int = 1, y: str):
    print(x, y)
```

raises:

```
SchemaError: Error building "call" validator:
  SchemaError: Error building "arguments" validator:
  SchemaError: Non-default argument 'y' follows default argument
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\rsokl\miniconda3\envs\py312\Lib\site-packages\pydantic
               python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:26:13) [MSC v.1935 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: typing_extensions-4.8.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Yep, this is the expected behavior here!

Here's the source code in `pydantic-core` responsible for that error. An easy fix is to switch your argument order :).

https://github.com/pydantic/pydantic-core/blob/1cefeae57609a876842b29c3ccba9df14aeae9ad/src/validators/arguments.rs#L102

**Comment by rsokl** [comment]
While that might be how the validator was written, I still think it is a bug. Keyword-only arguments are position/orderless and should be treated as such -- the signature for `foo` is a perfectly valid Python function. What is the reason for pydantic not supporting it?

> An easy fix is to switch your argument order

I can't. I am applying this validator to already-defined functions at runtime and do not have the ability to change their signatures.

Additionally, there are cases like

```python
@dataclass(kw_only=True)
class B:
   b: int

@dataclass(kw_only=True)
class A(B):
    a: int = 1

# A.__init__ is: (a: int = 1, b: int)
```

where the composition of classes necessarily places a default-valued kw-only parameter before a param with no default.

**Comment by sydney-runkle** [comment]
@rsokl,

I'll chat with @davidhewitt tomorrow to learn more about why we wrote the validator in such a way in the first place. My guess is to model the behavior of dataclasses, but we shall see! I'll keep you posted here.

**Comment by rsokl** [comment]
And just to emphasize: dataclass _does_ permit fields with defaults before kw-only fields without (as do functions).

**Comment by davidhewitt** [comment]
I think this is classed as a bug, it's backwards-compatible to fix this IMO and makes sense to match normal function behaviour.

**Comment by sydney-runkle** [comment]
Sounds good, agreed!

**Comment by hb2638** [comment]
Thanks for reporting this. I started upgrading our code base tofrom pydantic 1.X to 2.X yesterday and hit this bug.
