### ISSUE TITLE
Allow a displayable name for a schema in pydantic.ValidationError loc tuple

### ISSUE THREAD

**Issue by psalvaggio** [pydantic/pydantic#9349]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I have some custom `Annotated` alternatives to `FilePath` and its siblings in my code base:
```py
class _my_validator(
    v: pathlib.Path,
    validator: core_schema.ValidatorFunctionWrapHandler,
    info: core_schema.ValidationInfo,
) -> pathlib.Path:
    ...

class PathType(pydantic.types.PathType):
    def __get_pydantic_core_schema__(
        self, source: ty.Any, handler: pydantic.GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        schema = super().__get_pydantic_core_schema__(source, handler)
        return core_schema.with_info_wrap_validator_function(_my_validator, schema)

FilePath = ty.Annotated[pathlib.Path, PathType("file")]
```
when I use this type in a `Union`, I get a `ValidationError` with a `loc` that looks like the following:
```py
("path", "to", "field", "function-wrap[_my_validator()]")
```
Would it be possible to specifiy a name for my schema that would allow this to look like:
```py
("path", "to", "field", "PathType")
```
I thought maybe `ref` could do this, but it does not appear to change anything.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@psalvaggio,

Good question! I'm not currently sure of a way to do this. Maybe @davidhewitt would know...

**Comment by dmontagu** [comment]
Try:
```python
from pydantic import Tag

FilePath = ty.Annotated[pathlib.Path, PathType("file"), Tag("FilePath")]
```
see the top of the docstring of `pydantic.types.Tag`:
```python
class Tag:
    """Provides a way to specify the expected tag to use for a case of a (callable) discriminated union.

    Also provides a way to label a union case in error messages.
    ...
```
If the dual purposes of this item cause conflicts for you or you otherwise run into issues with it, let us know!
