### ISSUE TITLE
Annotated PlainSerializer is ignored by model_json_schema for default field

### ISSUE THREAD

**Issue by GidVeo** [pydantic/pydantic#9352]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

See below code adapted from the example [provided here](https://docs.pydantic.dev/latest/api/standard_library_types/#datetimetimedelta).

I'm looking to serialize `timedelta` types as strings with millisecond precision suffixed with `"s"`, in line with [protobuf's JSON representation of duration](https://protobuf.dev/reference/protobuf/google.protobuf/#duration).

The model is dumped correctly using the defined serialization format. However, when a default is set on the field, the JSON Schema `'default'` field value appears to ignore custom serialization: `'PT8M20S'`.

### Example Code

```Python
from datetime import timedelta
from typing import Annotated

from pydantic import BaseModel, PlainSerializer

CustomDuration = Annotated[
    timedelta,
    PlainSerializer(
        lambda x: f"{x.total_seconds():.3f}s",
        return_type=str,
    ),
]

class Model(BaseModel):
    td: CustomDuration = CustomDuration(seconds=500)

m = Model(td=CustomDuration(seconds=1000))

print(m.model_dump())
print(m.model_json_schema())

# > {'td': '1000.000s'}
# > {'properties': {'td': {'default': 'PT8M20S', 'format': 'duration', 'title': 'Td', 'type': 'string'}}, 'title': 'Model', 'type': 'object'}
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: .venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3-arm64-arm-64bit
             related packages: mypy-1.10.0 typing_extensions-4.11.0 fastapi-0.110.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@GidVeo,

Thanks for reporting this. Definitely looks like a bug. Adding this to our upcoming milestone!
