### ISSUE TITLE
Mypy "Unexpected keyword argument" error when using alias

### ISSUE THREAD

**Issue by rzepinskip** [pydantic/pydantic#9354]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Using a Field with an alias results in following mypy issue:
```
$ mypy sample_v1.py
sample_v1.py:10: error: Unexpected keyword argument "foo" for "Sample"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```
When I use mypy plugin for pydantic the error changes to:
```
$ mypy sample_v1.py
sample_v1.py:10: error: Missing named argument "foo_alias" for "Sample"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

Feels similar to #5070 but occurs for nwere version of both pydantic and mypy - regression?

### Example Code

```Python
from pydantic import BaseModel, Field

class Sample(BaseModel, allow_population_by_field_name=True):
    foo: str = Field(alias="foo_alias")

Sample(foo="foo_value")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 1.10.13
            pydantic compiled: True
                 install path: /Users/pawelr/source/mypy_pydantic/dev_venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 09:09:08)  [Clang 12.0.5 (clang-1205.0.22.9)]
                     platform: macOS-14.4.1-arm64-arm-64bit
     optional deps. installed: ['typing-extensions']
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@rzepinskip,

Thanks for your question!

Check out this issue: https://github.com/pydantic/pydantic/issues/5893 and this [note in the docs](https://docs.pydantic.dev/latest/concepts/fields/#field-aliases) for more info.

Check out this section of the docs to learn how to enable the mypy plugin: https://docs.pydantic.dev/latest/integrations/mypy/#strict-optional.

We're no longer actively working on V1. Given that this is fixed in V2, closing this as resolved.
