### ISSUE TITLE
Fields with BaseModel type that contain an instance of a model that inherits from BaseModel do not get serialized correctly

### ISSUE THREAD

**Issue by dmach** [pydantic/pydantic#9378]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When I define a field with `BaseModel` type and assign an instance of a model that inherits from `BaseModel`, the value gets serialized as `{}`.

Actual result from the reproducer:
```
{'parent': {'data': 'DEFAULT'}, 'parent_base_model': {}}
```

Expected result:
```
{'parent': {'data': 'DEFAULT'}, 'parent_base_model': {'data': 'DEFAULT'}}
```
or a validation error while instantiating `Child` or setting `parent_base_model` field. I tried setting various `model_config` options and they did not have any impact (incl. `validate_assignment=True` and `c.parent_base_model=p`)

### Example Code

```Python
from pydantic import *


class Parent(BaseModel):
    data: str = Field(default="DEFAULT")


class Child(BaseModel):
    parent: Parent | None = Field(default=None)
    parent_base_model: BaseModel | None = Field(default=None)


p = Parent()
c = Child(parent=p, parent_base_model=p)
print(c.dict())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
        pydantic-core version: 2.16.3
          pydantic-core build: profile=release pgo=false
                 install path: /usr/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC]
                     platform: Linux-6.8.7-1-default-x86_64-with-glibc2.39
             related packages: email-validator-2.0.0.post2 mypy-1.9.0 typing_extensions-4.11.0
                       commit: unknown
```

**Comment by RajatRajdeep** [comment]
The `parent_base_model` attribute is of type `BaseModel`, and since `BaseModel` does not include a `data` attribute, the `data` attribute was ignored. You can refer to the documentation on extra fields for more information: [link](https://docs.pydantic.dev/latest/concepts/models/#extra-fields).

**Comment by sydney-runkle** [comment]
Hi @dmach,

You'll want to use the `SerializeAsAny` annotation if you want all of the data to be dumped for that second field. For example:

```py
from pydantic import BaseModel, Field, SerializeAsAny


class Parent(BaseModel):
    data: str = Field(default="DEFAULT")


class Child(BaseModel):
    parent: Parent | None = Field(default=None)
    parent_base_model: SerializeAsAny[BaseModel] | None = Field(default=None)


p = Parent()
c = Child(parent=p, parent_base_model=p)
print(c.model_dump())
#> {'parent': {'data': 'DEFAULT'}, 'parent_base_model': {'data': 'DEFAULT'}}
```

Ping me if you have any questions. You can learn more about that annotation [here](https://docs.pydantic.dev/dev/concepts/serialization/#serializeasany-annotation)!
