### ISSUE TITLE
Small error in the docs

### ISSUE THREAD

**Issue by paulmartin91** [pydantic/pydantic#9407]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

docs.concepts.dataclasses.md there is an example dataclass with the `@model_validator(mode='before')` decorator that does not use the `@classmethod` decorator. The @model_validator decorator docs state: "The first argument should be cls (and we also recommend you use @classmethod below @model_validator for proper type checking)".

### Example Code

```Python
@dataclass
class User:
    birth: Birth

    @model_validator(mode='before')
    def pre_root(cls, values: Dict[str, Any]) -> Dict[str, Any]:
        print(f'First: {values}')
        """
        First: ArgsKwargs((), {'birth': {'year': 1995, 'month': 3, 'day': 2}})
        """
        return values
```

### Python, Pydantic & OS Version

```Text
https://docs.pydantic.dev/latest/concepts/dataclasses/#initialization-hooks
```

**Comment by sydney-runkle** [comment]
Marking as resolved! Thanks!
