### ISSUE TITLE
Improve ValidationError messaging for default values (validate_default=True).

### ISSUE THREAD

**Issue by JohnHind** [pydantic/pydantic#9408]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This code sample, which contains a minor typo converting an intended default for an integer field into a tuple:

```
from pydantic import BaseModel, ConfigDict

class MyBaseModel(BaseModel):
    model_config = ConfigDict(validate_default=True)

class Command(MyBaseModel):
    chan: int = 0,
    val: int = 0

validated = Command(val = 'f')

```
Produces this output:
```
Traceback (most recent call last):
  File "/home/pi/blinka/BugTest.py", line 11, in <module>
    validated = Command(val = 'f')
                ^^^^^^^^^^^^^^^^^^
  File "/home/pi/blinka/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Command
chan
  Input should be a valid integer [type=int_type, input_value=(0,), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.7/v/int_type
val
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='f', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/int_parsing
```
This is hard to understand because the identifier 'chan' does not appear anywhere in the highlighted traceback (line 11). I suggest that the field identifier should be presented more verbosely, both in the case where it is taken from the constructor argument list and in the case where it is defaulted. Say, something like:
```
Field: chan (default value from Command schema)
  Input should be a valid integer [type=int_type, input_value=(0,), input_type=tuple]
    For further information visit https://errors.pydantic.dev/2.7/v/int_type
Field: val
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='f', input_type=str]
    For further information visit https://errors.pydantic.dev/2.7/v/int_parsing
```
Suggestion comes out of this thread:
https://github.com/pydantic/pydantic/issues/9389

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @JohnHind,

Thanks for the feature request. I think this is a reasonble feature request - effectively to be more clear about where the input value is coming from in the error message. That being said, I do find the error message to be quite clear in general, so I wouldn't say this is high on our list of priorities.

**Comment by sydney-runkle** [comment]
Marking this as not planned - after further review, I don't think this is something we're likely to change. You can use custom error handling if you need a more specialized display of the error.

See https://docs.pydantic.dev/latest/errors/errors/#custom-errors.
