### ISSUE TITLE
A variant of EmailStr that doesn't pass `check_deliverability=False`

### ISSUE THREAD

**Issue by tamird** [pydantic/pydantic#9416]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

See https://github.com/pydantic/pydantic/blob/07b64739a251760a71082324e358c9d8291b7ab6/pydantic/networks.py#L742. I would like to validate email addresses including rejection of unknown domains.

While we're at it, it would be nice to [normalize](https://github.com/JoshData/python-email-validator?tab=readme-ov-file#normalization) as well.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by samuelcolvin** [comment]
Generally we try to discourage doing networking within validation, mostly because there's no way to do `async` in a validator.

**Comment by sydney-runkle** [comment]
@tamird,

Seems reasonable re normalization, but I think it makes sense to move this feature request to `email-validator`. Closing as not planned here for now!

**Comment by tamird** [comment]
email-validator [already does normalization](https://github.com/JoshData/python-email-validator/blob/5cf49cf87478a421df21ffeff9a1c87e30470e09/email_validator/exceptions_types.py#L31). it is not possible to use it though with `EmailStr`.
