### ISSUE TITLE
`model_json_schema()` turns `float` type to `number` type

### ISSUE THREAD

**Issue by eitanturok** [pydantic/pydantic#9423]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello!

I'm trying to generate a JSON schema of my Pydantic model where one of my numbers is of type `float`. But everytime I run `model_json_schema()`, I get a JSON schema where my `float` is cast to type `number`. How can I make the outputted JSON schema keep the type of my number as `float`?

When `x` is of type `float`:
```python
class Foo(BaseModel):
    x: float

foo = Foo(x=1.0)
foo.model_json_schema()
```
this outputs
```python
{'properties': {'x': {'title': 'X', 'type': 'number'}},
 'required': ['x'],
 'title': 'Foo',
 'type': 'object'}
```
Notice that we have `{'x': {'title': 'X', 'type': 'number'}`. I'd like to have `{'x': {'title': 'X', 'type': 'float'}`.

However, when `x` is of type `int`:
```python
class Foo(BaseModel):
    x: int

foo = Foo(x=1.0)
foo.model_json_schema()
```
we get the output
```python
{'properties': {'x': {'title': 'X', 'type': 'int'}},
 'required': ['x'],
 'title': 'Foo',
 'type': 'object'}
```
Notice that here we have `{'x': {'title': 'X', 'type': 'int'}` and `int` is not replaced with `number`.

Thanks!

### Example Code

```python
class Foo(BaseModel):
    x: float

foo = Foo(x=1.0)
foo.model_json_schema()
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /mnt/workdisk/eitan/venvs/outlines-float/lib/python3.11/site-packages/pydantic
               python version: 3.11.7 (main, Dec  8 2023, 18:56:57) [GCC 9.4.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
             related packages: typing_extensions-4.11.0 fastapi-0.111.0
                       commit: unknown
```
Any help would be greatly appreciated!

**Comment by PrettyWood** [comment]
Hi
I don't understand `number` is the representation expected in the [json schema spec](https://json-schema.org/understanding-json-schema/reference/numeric)
You can override the default behavior but it won't be a valid one

**Comment by Viicos** [comment]
Yep, `float` is not a valid JSON Schema type, OP seems to have figured this in the linked PR of the other repo.

I'm also unable to reproduce the `int` type, this is what I get:

```python
{'properties': {'x': {'title': 'X', 'type': 'integer'}}, 'required': ['x'], 'title': 'Foo', 'type': 'object'}
```

**Comment by PrettyWood** [comment]
It's not a bug and the schema can be overridden as stated in the doc. If needed open a discussion not a bug issue

**Comment by eitanturok** [comment]
Got it, thanks for getting back to me!

Could you point me in the direction of documentation that shows how to override this default behavior? How would I override the schema to create a custom type `float` which represents only floats (in contrast to `number` which represents both floats and integers)?

Thanks!

**Comment by Viicos** [comment]
https://docs.pydantic.dev/latest/concepts/json_schema/#withjsonschema-annotation

Not tested, but should work:

```python
import json

from typing_extensions import Annotated

from pydantic import BaseModel, WithJsonSchema

MyFloat = Annotated[
    float,
    WithJsonSchema({'type': 'float'}),
]


class Model(BaseModel):
    a: MyInt

print(json.dumps(Model.model_json_schema(), indent=2))
```

**Comment by eitanturok** [comment]
Thanks, that is very helpful!
