### ISSUE TITLE
Input should be a valid datetime, invalid timezone sign

### ISSUE THREAD

**Issue by yutayouguan** [pydantic/pydantic#9430]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

"msg": [
    {
      "type": "datetime_parsing",
      "loc": [
        "create_at"
      ],
      "msg": "Input should be a valid datetime, invalid timezone sign",
      "input": "2024-05-13 17:21:32 CST",
      "ctx": {
        "error": "invalid timezone sign"
      },
      "url": "https://errors.pydantic.dev/2.5/v/datetime_parsing"
    },
    {
      "type": "datetime_parsing",
      "loc": [
        "update_at"
      ],
      "msg": "Input should be a valid datetime, invalid timezone sign",
      "input": "2024-05-13 17:21:32 CST",
      "ctx": {
        "error": "invalid timezone sign"
      },
      "url": "https://errors.pydantic.dev/2.5/v/datetime_parsing"
    }
  ]
}

### Example Code

```Python
class TimestampMixin(BaseModel):
    create_by: str | None = Field(default=None, max_length=20, description="创建人")
    create_at: datetime = Field(..., description="创建时间")
    update_by: str | None = Field(default=None, max_length=20, description="更新人")
    update_at: datetime = Field(..., description="更新时间")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
                 install path: /opt/homebrew/Caskroom/miniforge/base/envs/fastapi/lib/python3.12/site-packages/pydantic
               python version: 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:01:35) [Clang 16.0.6 ]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: typing_extensions-4.11.0 pydantic-extra-types-2.4.1 fastapi-0.110.2 fastapi-0.111.0 pydantic-settings-2.2.1
```

**Comment by sydney-runkle** [comment]
@antoni-jamiolkowski,

Good call, thanks for the explanation. Marking this as resolved!
