### ISSUE TITLE
Clarify documentation of strip_whitespace

### ISSUE THREAD

**Issue by johncarter-phntm** [pydantic/pydantic#9438]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The doc for `StringConstraints` `strip_whitespace` says "Whether to strip whitespace from the string." - to me that's unclear if it's stripping all whitespace or only leading/trailing (it's the latter I think).

I think it'd be clearer if it said "Whether to remove leading and trailing whitespace." which I think is the actual behaviour, and aligns with the doc for constr - https://docs.pydantic.dev/latest/api/types/#pydantic.types.constr

https://docs.pydantic.dev/latest/api/types/#pydantic.types.StringConstraints

Maybe this unit test should be updated to include a space inside of ABC to assert on that behaviour? https://github.com/pydantic/pydantic/commit/8bc104f47e52719b157d1be30b4635a5038cb3d1#diff-bd467a363c9f155a2e6a7716aeca0c351089135a53d09a66138cea4f16506ebdR5574

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/johnc/.cache/pypoetry/virtualenvs/gweb-play-points-perks-apac-DXkUH1xo-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Feb 21 2024, 14:32:06) [GCC 11.4.0]
                     platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@johncarter-phntm,

Feel free to open a PR with these changes - that sounds great!

**Comment by micheleAlberto** [comment]
@sydney-runkle I'll be happy to take this one
