### ISSUE TITLE
Add Python fractions as a natively supported type

### ISSUE THREAD

**Issue by etienne-monier** [pydantic/pydantic#9439]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hi,

[Python fractions](https://docs.python.org/3.12/library/fractions.html) belongs to the standard library and that would be great to have is as natively supported type.

Is there another way to implement it ? Using validators and serializers ?

Thanks for your help!

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @etienne-monier,

Seems like a great feature request, and sort of goes along with the complex number support request. PRs welcome - we'd want to add support in `pydantic` first, but probably add support in `pydantic-core` eventually!

**Comment by Masynchin** [comment]
@etienne-monier are you willing to make PR? Same issue happened to me, and if you don't want to add `Fraction` support, I may do it myself

**Comment by sydney-runkle** [comment]
@Masynchin,

Go for it!

**Comment by etienne-monier** [comment]
> @etienne-monier are you willing to make PR? Same issue happened to me, and if you don't want to add `Fraction` support, I may do it myself

I let you make this  @Masynchin. I've got so many (woodworking) projects to do before! :)

**Comment by sydney-runkle** [comment]
I walk back my previous comment here - we can start with an implementation in Python only. I'll take a stab at this.
