### ISSUE TITLE
exclude attribute of fields is ignored in model_dump

### ISSUE THREAD

**Issue by devkral** [pydantic/pydantic#9465]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

At least when specifying your own exclude in model_dump the exclude attribute of fields is ignored.
I worked around by injecting the field names manually in exclude.

It would be nice if the exclude attribute could be honored even when the exclude parameter is specified in model_dump

Note: I use FieldInfo directly, see the edgy db system or better the PR:

https://github.com/tarsil/edgy/pull/89

Note2: it would be even better to have the exclude attribute for ComputedFieldInfo, despite the unlogic in it (computed_field is used for including a method in a model_dump). But for library authors it improves the usability

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
        pydantic-core build: profile=release pgo=true
                 install path: /home/alex/.local/share/hatch/env/virtual/edgy/dfnzc1V2/test/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]
                     platform: Linux-6.8.9-arch1-2-x86_64-with-glibc2.39
             related packages: typing_extensions-4.11.0 pydantic-settings-2.2.1 mypy-1.9.0 pydantic-extra-types-2.7.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @devkral,

Could you please provide a minimally reproducible example for this? Happy to help once we have a more clear idea there.

**Comment by sydney-runkle** [comment]
Going to close this as not planned for now, but happy to reopen with an MRE!
