### ISSUE TITLE
ValidationError Input should be None when field is named as type inside Optional

### ISSUE THREAD

**Issue by tribunsky-kir** [pydantic/pydantic#9482]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I've encountered a strange `ValidationError` while using a model with a `bytes` field and an `Optional[bytes]` annotation.

Please consider the examples below. 

It seems the issue is not with using a built-in type as a field name (which is doubtful but okay), but rather with the fact that the field name and the type inside `Optional` are the same.

I've also seen closed https://github.com/pydantic/pydantic/issues/7871, but the problem presents in the latest version of `pydantic`.

### Example Code

```Python
from typing import Optional

from pydantic import BaseModel, ValidationError

# OK
class M1(BaseModel):
    payload: Optional[str] = None


m1 = M1(payload='123')

# OK
class M2(BaseModel):
    payload: Optional[bytes] = None


m2 = M2(payload=b'123')

# Bug
class M3(BaseModel):
    str: Optional[str] = None


try:
    m3 = M3(str='123')
except ValidationError:
    # pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
    # str
    #   Input should be None [type=none_required, input_value='123', input_type=str]
    #     For further information visit https://errors.pydantic.dev/2.7/v/none_required
    ...

# Bug
class M4(BaseModel):
    bytes: Optional[bytes] = None


try:
    m4 = M4(bytes=b'123')
except ValidationError:
    # pydantic_core._pydantic_core.ValidationError: 1 validation error for M4
    # bytes
    #   Input should be None [type=none_required, input_value=b'123', input_type=bytes]
    #     For further information visit https://errors.pydantic.dev/2.7/v/none_required
    ...

# OK
class M5(BaseModel):
    bytes: Optional[str] = None


m5 = M5(bytes='123')


class M(BaseModel):
    ...

# Bug
class M6(BaseModel):
    M: Optional[M] = None

try:
    m6 = M6(M=M())
except ValidationError:
    # pydantic_core._pydantic_core.ValidationError: 1 validation error for M6
    # M
    #  Input should be None [type=none_required, input_value=M(), input_type=M]
    #    For further information visit https://errors.pydantic.dev/2.7/v/none_required
    ...
```

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /Users/username/Library/Caches/pypoetry/virtualenvs/myproject-CgLqTrQN-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: mypy-1.9.0 typing_extensions-4.9.0 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by tribunsky-kir** [comment]
I've found two more interesting examples:
```python
class M7(BaseModel):
    my: bytes | None = None


m = M7(my=b'123')


class M8(BaseModel):
    bytes: bytes | None = None

# Not even trying to create an object:
# Traceback (most recent call last):
#   File ... in <module>
#     class M8(BaseModel):
#   File ... in M8
#     bytes: bytes | None = None
#            ~~~~~~^~~~~~
# TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
```

**Comment by Viicos** [comment]
This seems to be the same issue as: https://github.com/pydantic/pydantic/issues/7327, https://github.com/pydantic/pydantic/issues/8240, https://github.com/pydantic/pydantic/issues/7309 (see https://github.com/pydantic/pydantic/issues/6646#issuecomment-1633970358 for an explanation).

See also https://github.com/pydantic/pydantic/issues/9093#issuecomment-2017437245, could be the same issue you are facing

See also https://github.com/pydantic/pydantic/issues/9385#issuecomment-2116164387

**Comment by sydney-runkle** [comment]
Thanks @Viicos for collecting the relevant issues. I suppose the number of times that this has come up merits another docs update.

Changing this to a docs issue!

**Comment by mikeleppane** [comment]
Hey @sydney-runkle, I'd be interested in taking a look at this.

**Comment by sydney-runkle** [comment]
@mikeleppane,

Thanks for your interest! @dAIsySHEng1 has already opened a PR with a fix, but we'll certainly have other docs update issues coming in, so feel free to pick any of those up!
