### ISSUE TITLE
Weird Mypy error (arg-type) when using the Pydantic plugin

### ISSUE THREAD

**Issue by g0di** [pydantic/pydantic#9488]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Trying to build a library on top of Pydantic, I stumbled upon a very strange Mypy error when validating some code using my library. It happens only when my models inherit from `BaseModel` and when using the Mypy Pydantic plugin.

It's actually hard to describe so head to the example below.
> Note that I'm focusing only on typing behavior

Here is my Mypy config
```toml
[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
```

Here is the output of Mypy when running against the example

Running Mypy give the following output
```bash
$  mypy snippet2.py 
snippet2.py:24: error: List item 2 has incompatible type "None"; expected "int"  [list-item]
Found 1 error in 1 file (checked 1 source file)
```

### Example Code

```Python
from collections.abc import Iterable
from typing import Generic, TypeVar

from pydantic import BaseModel

_T = TypeVar("_T")


class Foo(BaseModel):
    value: int | None


class SubFoo(Foo):
    pass


class ColumnExpression(Generic[_T]):
    def in_(self, values: Iterable[_T]) -> None:
        pass


def col(value: _T) -> ColumnExpression[_T]:
    return ColumnExpression[_T]()


col(SubFoo.value).in_([1, 2, None]) # List item 2 has incompatible type "None"; expected "int"Mypylist-item
col(Foo.value).in_([1, 2, None]) # This pass mypy
```

So basically, when passing `SubFoo.value` instead of `Foo.value` in my `col` function, Mypy narrows the expected type of `in_` function by removing the `None` from the union. However, both `Foo.value` and `SubFoo.value` should resolve to the same type.
Removing inheritance from `BaseModel` resolves the error. Disabling the pydantic mypy plugin as well.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.6.4
pydantic-core version: 2.16.3
pydantic-core build: profile=release pgo=true
install path: C:\Users\TBEBGOD\Developement\DDF\...\.venv\Lib\site-packages\pydantic
python version: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
related packages: fastapi-0.109.2 mypy-1.10.0 pydantic-settings-2.0.3 typing_extensions-4.8.0
commit: unknown
```

**Comment by sydney-runkle** [comment]
@g0di,

Thanks for your question. I believe this is resolved in v2.7. We can reopen this if that's not the case!
