### ISSUE TITLE
Problem when serializing models with `SecretStr`s

### ISSUE THREAD

**Issue by bcdurak** [pydantic/pydantic#9491]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello there, 

We ran into an issue while trying to upgrade our codebase to `pydantic` v2. 

In ZenML, we are currently using a combination of `fastapi` and `pydantic` to define our API. In some of our models, we have configuration fields that **might or might not have** `SecretStr`s inside. Whenever our API tries to return a response model that features a secret string (but it is not explicitly defined as a `SecretStr` field because it is dynamic), the complete serialization fails leading to an internal server error. 

As far as I can understand from the `fastapi` source code, the same behavior can be observed in this very simplified version that I provided as an example. 

### Example Code

```Python
from typing import Any

from pydantic import BaseModel, SecretStr


# Successful case

class SuccessfulCase(BaseModel):
    some_value: SecretStr


s = SuccessfulCase(some_value="1")

print(f"Successful `model_dump_json` case: {s.model_dump_json()}")


# Failing case

class FailingCase(BaseModel):
    some_value: Any


f = FailingCase(some_value=SecretStr("1"))

f.model_dump_json()  # fails with a pydantic_core._pydantic_core.PydanticSerializationError
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
pydantic-core version: 2.18.2
pydantic-core build: profile=release pgo=true
install path: /Users/bariscandurak/.pyenv/versions/3.10.11/envs/zenml/lib/python3.10/site-packages/pydantic
python version: 3.10.11 (main, Sep 28 2023, 17:25:26) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-14.4.1-arm64-arm-64bit
related packages: fastapi-0.110.0 typing_extensions-4.11.0 mypy-1.7.1 pydantic-settings-2.2.1
commit: unknown
```

**Comment by sydney-runkle** [comment]
@bcdurak,

Thanks for reporting this. Indeed, I recall this being one of the implementation challenges with `SecretStr`. The challenge is that the `SecretStr` has no attached `__pydantic_serializer__` from which `pydantic_core` can infer its serialization behavior.

I'll think about ways that we could potentially resolve this in a non-breaking way. @adriangb or @davidhewitt, any thoughts? I recall we discussed this recently in the context of duck type serialization...

**Comment by adriangb** [comment]
Can't we add a serializer to it?

**Comment by bcdurak** [comment]
@sydney-runkle @adriangb Thank you for your response. As I mentioned above, this was an issue that we ran into while using our API powered by `pydantic` and `fastapi`. While researching and looking for some workarounds, I actually ran into a few more interesting cases that I wanted to share with you (in case they shed some additional light onto the situation):


```python
from typing import Annotated, Any

from pydantic import BaseModel, PlainSerializer, model_serializer


# Example class with `Any` annotation
class Example(BaseModel):
    some_value: Any


# Creating a custom class with a `model_serializer`
class MyModel(BaseModel):
    x: str = "random_string"

    @model_serializer
    def ser_model(self) -> str:
        return "always_serialize_to_MyModel"


f = Example(some_value=MyModel())
print(f.model_dump_json())  # dumps to "always_serialize_to_MyModel"

# Creating a custom annotation with a `plain_serializer`
MyString = Annotated[
    str,
    PlainSerializer(lambda _: "always_serialize_to_MyString", when_used="json")
]

f = Example(some_value=MyString("wrong_dump"))
print(f.model_dump_json())  # dumps to "wrong_dump"
```

Since the first case has worked, I was wondering whether I should implement our version of `SecretStr`s and also, I am still a bit confused about the outcome of the second case (not exactly sure if this is the expected behaviour).

**Comment by sydney-runkle** [comment]
@bcdurak,

Thanks a ton for the feedback - I'm going to take a deep dive into your PR. We really appreciate the detailed feedback on your migration process, both the good and the bad.

> Since the custom Pydantic class worked, I was wondering whether I should implement our version of SecretStrs.

That sounds like a good step forward for now, and we'll get a fix out for `SecretStr` in our next release!

Feel free to ping me anytime if you encounter any other pain points or questions!

**Comment by sydney-runkle** [comment]
@davidhewitt, I recall us discussing the fact that having `__pydantic_serializer__` checks in `pydantic-core` wasn't the best practice in terms of extremely tight coupling between the two libraries. Thoughts on if that has the potential to change any time soon?

**Comment by davidhewitt** [comment]
I don't know if we have a clear alternative, but IIRC the problem has two main arguments:
- `__pydantic_serializer__` is generally a `pydantic` implementation detail which `pydantic_core` has no business knowing about. It would be nice to not have this coupling or turn it around and call the thing `__pydantic_core_serializer__` which at least implies it's an implementation detail of core.
- Many types have `__get_pydantic_core_schema__` instead, such as `SecretStr`. Amazingly this is an implementation detail of `pydantic`, not of `pydantic_core`, but if anything it feels like something which is more suitable for `core` to use.

That said, I'm increasingly of the opinion that `pydantic_core` has no business being a standalone library and really it's an implementation detail of pydantic (or at least a lower-level layer which is allowed to be coupled to the higher level). We never stopped pinning `pydantic` to an exact `pydantic_core` version after V2 (even though we originally intended this).

**Comment by adriangb** [comment]
Agreed with that opinion I think pretending they are or will be separate libraries would be a mistake. That said I do think we can keep the coupling minimal e.g. via protocols and such so you _can_ use pydantic-core without pydantic.

**Comment by sydney-runkle** [comment]
cc @bcdurak, I've opened a PR that could potentially fix this :)
