### ISSUE TITLE
Allow for model discrimination without the creation of another BaseModel

### ISSUE THREAD

**Issue by MarcBresson** [pydantic/pydantic#9512]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Hello,

I want to select the right model based on user input. The user control the value of only one field, and the rest of the model is assumed to be supplied correctly. I read about [discriminated unions](https://docs.pydantic.dev/2.0/usage/types/unions/#nested-discriminated-unions) but the slight issue is that I'm forced to create a class to be able to type one attribute of this class with the actual type union I want.

What I was imagining was a function available in pydantic that does that. Here is my implementation:

```python
def discriminate_pydantic_unions(input: dict[str, Any], model_unions: type):
    """
    This function is purely a pydantic utilitarian function. Read
    https://github.com/pydantic/pydantic/issues/9512 for more context.

    Given a union of pydantic models, will output the one that matches
    with the input. It is based on the discriminated union principle
    https://docs.pydantic.dev/2.0/usage/types/unions/#nested-discriminated-unions
    """

    class Discri(BaseModel):
        results: model_unions

    return Discri(results=input).results


class G(BaseModel):
    one: str

class H(BaseModel):
    one: int
```

It yields:

```python
discriminate_unions({"one": "h"}, G | H)
>>> G(one="h")
discriminate_unions({"one": 3}, G | H)
>>> H(one=3)
```

Here is a more elaborate example:

```python
class LikelihoodA(BaseModel):
    likelihood: Literal["a"]
    regularization: Literal["None"]

class LikelihoodB(BaseModel):
    likelihood: Literal["b"]
    regularization: Literal["None"]

class RegularizationA(BaseModel):
    regularization: Literal["a"]

class RegularizationB(BaseModel):
    regularization: Literal["b"]


linear_regression_models = Annotated[
    LikelihoodA
    | LikelihoodB,
    Field(discriminator="likelihood"),
]
regression_models = Annotated[
    RegularizationA
    | RegularizationB
    | linear_regression_models,
    Field(discriminator="regularization"),
]

discriminate_pydantic_unions({"regularization": "a"}, regression_models)
>>> RegularizationA(regularization='a')
discriminate_pydantic_unions({"regularization": "b", "likelihood": "a"}, regression_models)
>>> RegularizationB(regularization='b')
discriminate_pydantic_unions({"regularization": "None", "likelihood": "a"}, regression_models)
>>> LikelihoodA(likelihood='a')
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by MarcBresson** [comment]
should not this be mentioned in https://docs.pydantic.dev/2.0/usage/types/unions/#nested-discriminated-unions? I feel like pydantic can do a lot, but sometimes we just do not know it can

**Comment by sydney-runkle** [comment]
@MarcBresson,

Feel free to open a PR with a docs update, I'd be happy to review! We already cover `TypeAdapters` in the docs, but you're right, we don't touch on them in the discriminated unions section.
