### ISSUE TITLE
Discriminator on non-Union types

### ISSUE THREAD

**Issue by azmeuk** [pydantic/pydantic#9521]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I build [a library](https://github.com/yaal-coop/pydantic-scim2) where I provide a bunch of pydantic Models which have a common behavior. Among the common behaviors shared between all the models is how to discriminate them.

As I find the `Discriminator` + `Tag` declaration a bit tedious, I provide a `tagged_union` method that does the job, so users of the library do not have to think about discriminators: they just provide models.

Here is how it looks like (though it is simplified, as the discriminator in my use case is not a litteral):

```python
from typing import Annotated
from typing import Generic
from typing import List
from typing import Literal
from typing import TypeVar
from typing import Union
from typing import get_args
from typing import get_origin

from pydantic import BaseModel
from pydantic import Discriminator
from pydantic import Tag


def tagged_union(*types):
    types = Union[types]
    types = get_args(types) if get_origin(types) == Union else [types]

    def get_discriminator_value(payload):
        return payload["discriminator"]

    def get_tag(type):
        discriminator, *_ = get_args(type.model_fields["discriminator"].annotation)
        return Tag(discriminator)

    tagged_resources = [Annotated[type, get_tag(type)] for type in types]
    return Annotated[
        Union[tuple(tagged_resources)], Discriminator(get_discriminator_value)
    ]


T = TypeVar("T")


class Foo(BaseModel):
    discriminator: Literal["foo"]


class Bar(BaseModel):
    discriminator: Literal["bar"]


class Model(BaseModel, Generic[T]):
    submodels: List[T]


foos_and_bars = Model[tagged_union(Foo, Bar)]
foos = Model[tagged_union(Foo)]
```

This last line raises a `TypeError` exception:

```python
TypeError: Discriminator must be used with a Union type, not <class '__main__.Foo'>
```

I suggest to make discriminators on non-union types to be possible, so `Model[tagged_union(Foo)].model_validate` would raise a `ValidationError` if passed a payload with non-matching discriminators.

This would make the behavior consistent between `Model`s, whether the type parameter is an `Union` or not.

What do you think?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@azmeuk,

Thanks for the feature request. I don't think this feature request fits into our pipeline at the moment - Pydantic's validation logic will already reject the incoming data if the discriminator doesn't match the expected value.

For now, we'd recommend just doing normal validation if you only have one model. If you really want to fail early with validation, you could write a custom wrap validator to fail early with said discriminator check 🚀.
