### ISSUE TITLE
@field_validator not working when wrapped with @classmethod

### ISSUE THREAD

**Issue by HomerusJa** [pydantic/pydantic#9539]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I was trying around with pydantic, when I came across this issue. None of my fields got validated. My error was, that I had put the classmethod decorator before the field_validator. After some thought on why Pydantic behaves like that, the reason for this issue is pretty clear to me, but it is a pitty for me either way. Is it possible to add support for this way of doing it?

### Example Code

```Python
from pydantic import BaseModel, field_validator


class Model(BaseModel):
    a: str

    @classmethod  # This causes that pydantic doesn't discover the field_validator
    @field_validator("a")
    def validate_a(cls, v: str) -> str:
        if v == "a":
            raise ValueError("a is not allowed")
        return v
    

if __name__ == "__main__":
    model = Model(a="b")  # This should work
    model2 = Model(a="a")  # This should raise a ValueError, but it doesn't
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\jakob\PycharmProjects\exp-coord-server\.venv\Lib\site-packages\pydantic
               python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: pydantic-settings-2.2.1 typing_extensions-4.12.0
                       commit: unknown
```

**Comment by andresliszt** [comment]
Hey hello!, `classmethod` must go below of `field_validator`. Internally pydantic when is building the model schema Iooks at all the decorators defined in the class, and through successive calls to `isinstance` method, it is able to identify `field_validators`, `model_validators` and all the special `pydantic` decorators. If you put `@classmethod` before `@field_validator` then due the way `pydantic` is built, this will be treated as just another class method with no special meaning. The docs say that `classmethod` must be placed below for typecheckers https://docs.pydantic.dev/latest/concepts/validators/#field-validators

**Comment by sydney-runkle** [comment]
Hi @HomerusJa,

Thanks for your question. See [this section](https://docs.pydantic.dev/latest/concepts/validators/#field-validators) of the docs for clarification.

> @field_validators are "class methods", so the first argument value they receive is the UserModel class, not an instance of UserModel. We recommend you use the @classmethod decorator on them below the @field_validator decorator to get proper type checking.

This isn't likely to be changed in the future, so we'd recommend using the `@field_validator` decorator first and the `@classmethod` decorator second.
