### ISSUE TITLE
ValidationError when using Generic constructor for subfield

### ISSUE THREAD

**Issue by FizzyAgent** [pydantic/pydantic#9546]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Encountered ValidationError while migrating a codebase from Pydantic v1 to v2. Identified the problem to be from a generic BaseModel constructor, which works on v1 but not v2. 

Example code below is a simplified version of the problematic use case in the current codebase. 

Wondering if there are any solutions or workarounds with minimal changes, ideally without having to define additional classes, as that will cause large amounts of code redundancy in the codebase.

### Example Code

```Python
from typing import Generic, TypeVar
from pydantic import BaseModel

A = TypeVar("A")

class Box(BaseModel, Generic[A]):
    value: A | None = None

class Storage(BaseModel):
    int_box: Box[int]

class BoxMaker(Generic[A]):
    @staticmethod
    def make_box() -> Box[A]:
        return Box[A]()

int_box = BoxMaker[int].make_box()
store = Storage(int_box=int_box)

print(store.dict())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=false
               python version: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
                     platform: macOS-14.4.1-x86_64-i386-64bit
```

**Comment by sydney-runkle** [comment]
@FizzyAgent,

Thanks for reporting this. I know this issue has been reported before, but I'm still digging around to find it.

In the meantime, here's a similar issue: https://github.com/pydantic/pydantic/issues/8071.

**Comment by sydney-runkle** [comment]
Other related issues:
* https://github.com/pydantic/pydantic/issues/9295
* https://github.com/pydantic/pydantic/issues/7096#issuecomment-1678031081
* https://github.com/pydantic/pydantic/issues/9414

Going to mark this as a duplicate and closer for now, but definitely something we'll want to revisit for V3. Great articulation of the issue!
