### ISSUE TITLE
TypeAdapter for collections.abc.MutableMapping fails when validate_python called on a  collections.UserDict in strict mode

### ISSUE THREAD

**Issue by hb2638** [pydantic/pydantic#9549]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

A type adapter for collections.abc.MutableMapping cannot validate instances of collections.UserDict in strict mode

I get the below error

```
C:\code\pipelines\scratch\venv\Scripts\python.exe C:\code\pipelines\scratch\devtools\pydantic_userdict.py 
Traceback (most recent call last):
  File "C:\code\pipelines\scratch\devtools\pydantic_userdict.py", line 6, in <module>
    adapter.validate_python(collections.UserDict())
  File "C:\code\pipelines\scratch\venv\Lib\site-packages\pydantic\type_adapter.py", line 260, in validate_python
    return self.validator.validate_python(object, strict=strict, from_attributes=from_attributes, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for dict[any,any]
  Input should be a valid dictionary [type=dict_type, input_value={}, input_type=UserDict]
    For further information visit https://errors.pydantic.dev/2.7/v/dict_type

Process finished with exit code 1
```

### Example Code

```Python
import collections.abc

import pydantic

config = pydantic.ConfigDict(arbitrary_types_allowed=True, strict=True)
adapter = pydantic.TypeAdapter(collections.abc.MutableMapping, config=config)
adapter.validate_python(collections.UserDict())
```

### Python, Pydantic & OS Version

```Text
python -c "import pydantic.version; print(pydantic.version.version_info())"
             pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\code\pipelines\scratch\venv\Lib\site-packages\pydantic
               python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19044-SP0
             related packages: typing_extensions-4.12.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@hb2638,

Thanks for reporting this. I can reproduce. Looks like a bug. Some more context:

```py
import collections.abc

import pydantic

config = pydantic.ConfigDict(arbitrary_types_allowed=True, strict=True)
adapter = pydantic.TypeAdapter(collections.abc.MutableMapping, config=config)

# adapter.validate_python(collections.UserDict())

print(isinstance(collections.UserDict(), collections.abc.MutableMapping))
#> True

print(isinstance(collections.UserDict(), dict))
#> False
```

**Comment by sydney-runkle** [comment]
Could be a good first issue if someone is looking to get their hands dirty with pydantic's internal validation logic. I think `MutableMapping` should probably be supporting some sort of isintance check...

**Comment by mikeleppane** [comment]
@sydney-runkle, I'm interested in taking a look at this.

BTW, can you unassign me from #9100?

**Comment by mikeleppane** [comment]
BTW, I'm having some issues getting the rust-analyzer up and running for the project: 

```
Failed to run build scripts of some packages.

cargo check failed to start: Cargo watcher failed, the command produced no valid metadata (exit code: ExitStatus(unix_wait_status(25856))):

   Compiling pydantic-core v2.18.4 (/home/mikko/dev/pydantic-core)

error: failed to run custom build command for `pydantic-core v2.18.4 (/home/mikko/dev/pydantic-core)`

note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:

  process didn't exit successfully: `/home/mikko/dev/pydantic-core/target/debug/build/pydantic-core-fafeb136866c450b/build-script-build` (exit status: 101)

  --- stdout

  cargo:rustc-cfg=Py_3_6

  cargo:rustc-cfg=Py_3_7

  cargo:rustc-cfg=Py_3_8

  cargo:rustc-cfg=Py_3_9

  cargo:rustc-cfg=Py_3_10
```

Any tips on how to overcome this?

**Comment by sydney-runkle** [comment]
@mikeleppane,

Thanks for your work on this!

> BTW, I'm having some issues getting the rust-analyzer up and running for the project.

Hmm, that is odd. Have you used `make install` locally to set everything up? I'm guessing you have `rust` installed locally already and have followed the `getting started` guide from [here](https://join.slack.com/t/pydanticlogfire/shared_invite/zt-2b57ljub4-936siSpHANKxoY4dna7qng), but that'd be good to do if you haven't yet!

>  Fixing the issue is easy. We can do it by supporting UserDict type (or Mapping type). But, do we want to do that? Is it aligned with the design?

This is what's concerning to me in terms of this failure:

```py
print(isinstance(collections.UserDict(), collections.abc.MutableMapping)) 
#> True
```

If this evaluates to true, I don't think validation should be failing. So, I'm inclined to add more robust support for `MutableMapping`. I'll also note, I'm a bit surprised at this failure, as we have attempted to incorporate some support for `MutableMapping`: https://github.com/search?q=repo%3Apydantic%2Fpydantic%20MutableMapping&type=code. I suppose we don't have an `isinstance` check where we need one.

> The following code does not raise an error even though strict=True.

That's interesting - what happens when you put the `strict` specification on the `keys` or `values` schema directly?

Just as a side note, we have a newly created `pydantic` slack if you're interested in joining + getting rapid feedback. Here's a link! https://join.slack.com/t/pydanticlogfire/shared_invite/zt-2b57ljub4-936siSpHANKxoY4dna7qng

**Comment by sydney-runkle** [comment]
In summary, I think the fix might actually be in `pydantic`, when we do the schema building. The way we do it is a bit wacky for `Sequence` and `Mapping` types, hence my recent complaints: https://github.com/pydantic/pydantic/issues/9340.

**Comment by mikeleppane** [comment]
> Hmm, that is odd. Have you used make install locally to set everything up? I'm guessing you have rust installed locally already and have followed the getting started guide from [here](https://join.slack.com/t/pydanticlogfire/shared_invite/zt-2b57ljub4-936siSpHANKxoY4dna7qng), but that'd be good to do if you haven't yet!

Yeah, I got that working. Apparently, I had an older version of `typing_extensions`. Yes, I originally ran the `make install` but needed to upgrade manually.

> If this evaluates to true, I don't think validation should be failing. So, I'm inclined to add more robust support for MutableMapping. I'll also note, I'm a bit surprised at this failure, as we have attempted to incorporate some support for MutableMapping: https://github.com/search?q=repo%3Apydantic%2Fpydantic%20MutableMapping&type=code. I suppose we don't have an isinstance check where we need one.

This evaluates to true because `UserDict` implements/inherits `collections_abc.MutableMapping`. However, note that `UserDict` is not a dict subclass. See: https://github.com/python/cpython/blob/7545b7cb63a7b27de2a829b626f546088b24de47/Lib/collections/__init__.py#L1117

```bash
>>> isinstance(UserDict(), MutableMapping)
True
>>> issubclass(UserDict, MutableMapping)
True
>>> isinstance(UserDict(), dict)
False
>>> issubclass(UserDict, dict)
False
```

**Comment by sydney-runkle** [comment]
> This evaluates to true because UserDict implements/inherits collections_abc.MutableMapping. However, note that UserDict is not a dict subclass. See: https://github.com/python/cpython/blob/7545b7cb63a7b27de2a829b626f546088b24de47/Lib/collections/__init__.py#L1117

Yep. I think we shouldn't just build a simple `dict` validator for a `MutableMapping` type hint - rather we should have some sort of chain schema that uses an isinstance check.

**Comment by YassinNouh21** [comment]
@sydney-runkle 
I noticed that the issue is currently open and actively discussed. I see that @mikeleppane has been assigned and has already started working on it.

Could you please confirm if additional help is needed on this, or should I look for another issue to work on?

Thank you!

**Comment by sydney-runkle** [comment]
@mikeleppane,

Would you like any assistance here?

**Comment by mikeleppane** [comment]
@sydney-runkle, @YassinNouh21, yeah you can unassign me. Sorry, I was not planning to implement this. I was more like debugging it to better understand w/o any other agenda. Moreover, I'm hands full with this one: https://github.com/pydantic/pydantic/issues/9559

**Comment by mikeleppane** [comment]
So, feel free to squash this one.
