### ISSUE TITLE
Serialization Warning when using Literal and model_dump

### ISSUE THREAD

**Issue by jobarjo** [pydantic/pydantic#9556]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I get the following error when serializing some models:

```
 UserWarning: Pydantic serializer warnings:
  Expected `str` but got `_LiteralGenericAlias` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
{'any_of_schemas': typing.Literal['ServiceType', 'object']}
```

Code example

```python
from pydantic import BaseModel, Field
from typing_extensions import Literal

class MyModel(BaseModel):
    any_of_schemas: List[str] = Field(default=Literal["ServiceType", "object"])

my_model = MyModel()
my_model.model_dump()
```

### Python, Pydantic & OS Version

```Text
>>> print(pydantic.version.version_info())

             pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: /Users/joel.barenco/Library/Caches/pypoetry/virtualenvs/product-page-wu9beR97-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, May 16 2024, 18:57:06) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: typing_extensions-4.12.1 fastapi-0.105.0 mypy-1.8.0 pydantic-settings-2.2.1
                       commit: unknown

```
```

**Comment by sydney-runkle** [comment]
@jobarjo,

This error is expected - `Literal["ServiceType", "object"]` is not a valid `List[str]`. If you use `validate_default=True` for said field, you'll get a validation error.

Marking as resolved - if you use ["ServiceType", "object"] as the default, you won't get an error 👍

**Comment by sydney-runkle** [comment]
@jobarjo,

Yep, this is still expected - `Literal` is used as a type hint, but isn't traditionally attached to values in this way. Here's how we'd typically expect it to be used:

```py
from pydantic import BaseModel, Field
from typing_extensions import Literal

class MyModel(BaseModel):
    a: Literal["something"] = Field(default="something", validate_default=True)  # correct
    b: Literal["something"] = Field(default=Literal["something"], validate_default=True)  # wrong way of using Literal
```

Let me know if you have any more questions!

**Comment by jobarjo** [comment]
> @jobarjo,
> 
> Yep, this is still expected - `Literal` is used as a type hint, but isn't traditionally attached to values in this way. Here's how we'd typically expect it to be used:
> 
> ```python
> from pydantic import BaseModel, Field
> from typing_extensions import Literal
> 
> class MyModel(BaseModel):
>     a: Literal["something"] = Field(default="something", validate_default=True)  # correct
>     b: Literal["something"] = Field(default=Literal["something"], validate_default=True)  # wrong way of using Literal
> ```
> 
> Let me know if you have any more questions!

Gotcha - thanks again :)
