### ISSUE TITLE
`SecretStr` fields throw type hint errors at user when passing a string

### ISSUE THREAD

**Issue by tim-quix** [pydantic/pydantic#9557]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I'm not sure if this is a bug per-se, but in both VSCode and Pycharm, I get type hint errors when passing a `str` to a `SecretStr` field:

![image](https://github.com/pydantic/pydantic/assets/136370015/7256073a-780e-4dd5-af95-ee9e2252c43f)

My understanding is that this is the intended pattern of usage (the documentation itself has an example like this), and so I would expect as a user to be able to just pass a string and it would interpret it as a valid argument.

Use case is an end user library where I don't want users to have to know about the Pydantic model under the hood (there are helper methods to dump the model fully plaintext). 

This type warning implies they need to import `SecretStr` from Pydantic and use it (unless of course they look it up and know how it works), which feels like a poor user experience.

There is a "workaround" using `Union[SecretStr, str]` but it feels rather flimsy and potentially dangerous (especially since `Union[str, SecretStr]` doesn't generate a secret).

I also attempted doing some things with `Secret[Annotated[str]]` but that resulted in other issues.

### Example Code

```Python
from pydantic import BaseModel, SecretStr


class Model(BaseModel):
    username: str
    password: SecretStr

m = Model(username='blah', password='blah')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.3
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
               python version: 3.8.17
                     platform: Linux-6.4.6-200.fc38.x86_64-x86_64-with-glibc2.34
             related packages: typing_extensions-4.8.0 pydantic-settings-2.3.0
```

**Comment by sydney-runkle** [comment]
@tim-quix,

Thanks for reporting this - if you use our `mypy` plugin, you shouldn't get this type error. That being said, there might be something internally that we can do with our typing to prevent this. I'll look into this!

**Comment by tim-quix** [comment]
Hey Syndey, thanks for the quick reply!

Just as an FYI, currently using `Pylance` for VSCode and only using whatever Pycharm uses by default (and the Pydantic plugin), and the issue does seem to similarly manifest in both.

Looking forward to the results of your investigation! Also, if you happen to think of a workaround, feel free to share. Thanks!

**Comment by sydney-runkle** [comment]
Hi @tim-quix,

After a bit more investigation, it seems as though there's not a great option for supporting this.

Another common example of this pattern is:

```py
from pydantic import BaseModel


class Model(BaseModel):
    id: int

m = Model(id='1')
"""
Pyright complains: Argument of type "Literal['1']" cannot be assigned to parameter "id" of type "int" in function "__init__"
"""
print(repr(m))
#> Model(id=1)
```

Going to close this as not planned for now, but we'll be sure to check in if we find a Pythonic way around this issue.

**Comment by AaronDMarasco** [comment]
I'm getting this even tho @sydney-runkle says above that I shouldn't if I'm using the `mypy` plugin.

Only other plugin is `numpy.typing.mypy_plugin` and `mypy` is version 1.19.0 (compiled).

Forced to ignore arg-type anywhere I have a password in my test suite.
