### ISSUE TITLE
Python regex flags are not supported

### ISSUE THREAD

**Issue by Reskov** [pydantic/pydantic#9568]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Look's like pydantic ignore regex compile flags like re.I, re.X, etc. https://docs.python.org/3/library/re.html#flags even if regex engine is set to 'python-re'. 

### Example Code

```Python
import re

from pydantic import BaseModel, ConfigDict, Field

verbose_regex = re.compile('abc', re.I)
print(verbose_regex.match("ABC")) # <re.Match object; span=(0, 3), match='ABC'>

class Model(BaseModel):
    model_config = ConfigDict(regex_engine='python-re')

    value: str = Field(pattern=verbose_regex)

print(Model(value='abc').value) # abc
print(Model(value='ABC').value) # Raises ValidationError
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.3
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: /.venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: typing_extensions-4.12.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Reskov,

Seems so! Bug fixes welcome!

**Comment by mikeleppane** [comment]
Hey,

When reading the `pattern` parameter, the system loses or ignores `RegexFlag` data. IMO, there are two ways to handle this. First, we could warn a user that using a compiled regular expression with some flag is not supported. The second option is much more involved. If I understand. We need to send information to `pydantic-core`. This is to support `RegexFlag`. This will require schema changes.

**Comment by Reskov** [comment]
Hi @mikeleppane 

Thanks for your suggestions, I've found a possible third option. The regex standard support flags inside the regex string itself. For example, `(?i)arb` is roughly the same as passing flags globally, such as `re.compile('arb', re.IGNORECASE)`. https://docs.python.org/3/library/re.html#re.IGNORECASE . So my solution is simple in-place global flags inside the pattern.

**Comment by mikeleppane** [comment]
> Hi @mikeleppane
> 
> Thanks for your suggestions, I've found a possible third option. The regex standard support flags inside the regex string itself. For example, `(?i)arb` is roughly the same as passing flags globally, such as `re.compile('arb', re.IGNORECASE)`. https://docs.python.org/3/library/re.html#re.IGNORECASE . So my solution is simple in-place global flags inside the pattern.

👍 Suggestion: do we need to call `extract_flagged_pattern` if there's no flag set for the compiled regular expression?

**Comment by mikeleppane** [comment]
Okay, it sets UNICODE flag implicitly. 

```python
regex = re.compile(r"(\d+)")
assert regex.flags == re.UNICODE

```

**Comment by sydney-runkle** [comment]
Marking as resolved by the above linked PRs!
