### ISSUE TITLE
No package metadata was found for email-validator

### ISSUE THREAD

**Issue by dwbelliston** [pydantic/pydantic#9579]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hey! Thanks for the work on this project. Been running well on version 1, just tried to upgrade to v2 and having some issues.

I am deploying to aws lambda and a very simple works.

Then when i try to use EmailStr and I get an issue saying i need to `pip install pydantic[email]`

Once i do that... i get an error:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'app.main': No package metadata was found for email-validator
```

I checked the code and the email-validator dep is in the lambda code. I have tried quite a few different approaches, but keep getting this metadata issue.

Would love suggestions on other ideas to debug this. Thanks!!

### Example Code

```Python
"""
API

Main entrypoint to API
"""

from pydantic import BaseModel, EmailStr

from fastapi import FastAPI
from mangum import Mangum


# Properties to receive via API on creation
class SampleModel(BaseModel):
    email: EmailStr


# Set up app
app = FastAPI(
    title="SAMPLE_NAME",
)


@app.get("/test", response_model=SampleModel)
async def trigger_error():

    return SampleModel(email="test@me.com")
    # division_by_zero = 1 / 0


# Wrap in ASGI to deploy on lambda
handler = Mangum(app)  # type: ignore
```

### Python, Pydantic & OS Version

```Text
running in aws lambda

runtime python 3.11
```

**Comment by sydney-runkle** [comment]
@dwbelliston,

Have you tried `pip install email-validator`? That should resolve the issue!

Marking as resolved for now, but feel free to ping me if you're still having trouble!

**Comment by dwbelliston** [comment]
Thanks for the help

Yes, I have put an email-validator in my requirements.txt for my deploy to AWS lambda. When I download the zip, I do see the email-validator package alongside pydantic.

`No package metadata` thats the issue I am getting. As opposed to module not found. So I do believe its being installed, something is off though and I have not been able to figure it out.

**Comment by sydney-runkle** [comment]
@dwbelliston,

Huh, that's quite odd. What happens when you run said code in a local environment?
