### ISSUE TITLE
Model validator is ignored during inheritance

### ISSUE THREAD

**Issue by FizzyAgent** [pydantic/pydantic#9582]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When I have a parent and child class that both implement `model_validator`, the parent's model validator is ignored in the child class. 

This can be a source of bugs as one might expect the parent's validation to run together with the child's validation.

### Example Code

```Python
from pydantic import BaseModel, model_validator

class Sub(BaseModel):
    positive: int

    @model_validator(mode="after")
    @classmethod
    def model_validator(cls, v):
        if v.positive <= 0:
            raise ValueError()
        return v

class Main(Sub):
    negative: int

    @model_validator(mode="after")
    @classmethod
    def model_validator(cls, v):
        if v.negative >= 0:
            raise ValueError()
        return v

# throws an error
sub = Sub(positive=-1)

# doesn't throw an error
main = Main(positive=-1, negative=-2)
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.3
pydantic-core version: 2.18.4
pydantic-core build: profile=release pgo=false
python version: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
platform: macOS-14.4.1-x86_64-i386-64bit
```

**Comment by gbatagian** [comment]
To add a bit context into this one because I ran into this issue after upgrading to Pydantic 2.
The problem arises when validator methods in **parent** and **child** models **share the same name** (`model_validator` in your example). 
If the validator method names are different, both will execute when you create a child instance, e.g. for your example:

```python
from pydantic import BaseModel, model_validator

class Sub(BaseModel):
    positive: int

    @model_validator(mode="after")
    @classmethod
    def sunb_model_validator(cls, v):
        if v.positive <= 0:
            raise ValueError()
        return v

class Main(Sub):
    negative: int

    @model_validator(mode="after")
    @classmethod
    def main_model_validator(cls, v):
        if v.negative >= 0:
            raise ValueError()
        return v

# throws an error
sub = Sub(positive=-1)

# also throws an error
main = Main(positive=-1, negative=-2)
```

This behavior did not exist in Pydantic 1, in which you could have `root_validator` methods with the same name in both parent and child and both would execute in child instance creations.

**Comment by sydney-runkle** [comment]
@FizzyAgent,

Hi! Thanks for your question.

I don't think I would classify this as a bug - given that the two validators are named the same thing, we'd expect an override in the sub class. If you want both to run, I'd suggest going the route of naming the validators differently.

One good next step could be adding a note to the docs in the model validators concepts section. I'd be happy to do that this week!

**Comment by FizzyAgent** [comment]
Wow never considered to try that, it works after I used different names for each validator. Thanks for the clarification!
