### ISSUE TITLE
HttpUrl doesn't require TLD

### ISSUE THREAD

**Issue by Tom-Camp** [pydantic/pydantic#9594]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Using Pydantic 2.7.1 HttpUrl accepts URLs without TLDs.

From the Pydantic code comment:
A type that will accept any http or https URL.

* TLD required
* Host required
* Max length 2083

### Example Code

```Python
>>>> from pydantic import BaseModel, HttpUrl, ValidationError
>>>> class MyModel(BaseModel):
...      url: HttpUrl
...
>>>> m = MyModel(url="http://www.example")
>>>> print(m.url)
http://www.example/
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/.../.cache/pypoetry/virtualenvs/.../lib/python3.11/site-packages/pydantic
               python version: 3.11.1 (main, Apr 18 2024, 14:47:59) [GCC 11.4.0]
                     platform: Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.11.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@Tom-Camp,

Thanks for reporting this. I think this is more of a docs bug, as we defer to the [URL Rust Crate](https://github.com/servo/rust-url) for URL validity decisions. I've added this to the current milestone as a docs issue.

**Comment by sydney-runkle** [comment]
Just as a side note, we'd recommend using a custom validator if you need to enforce the presence of a TLD!

**Comment by katybaulch** [comment]
@sydney-runkle, I think the docs also needed updating [here](https://docs.pydantic.dev/1.10/usage/types/#urls), as this still says that the TLD is required.

![Screenshot from 2024-08-12 12-13-44](https://github.com/user-attachments/assets/919f87d4-0185-4c7f-b212-d7bfb3b1397a)
