### ISSUE TITLE
Drop support for pytest 7.4

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [pydantic/pydantic#9597]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

@sydney-runkle Sorry for tagging you directly, but I thought we should get an issue raised so we can plan when best to make this switch.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@s-t-e-v-e-n-k,

Yep, agreed! We should probably check out download numbers for the different `pytest` versions.

**Comment by sydney-runkle** [comment]
@s-t-e-v-e-n-k,

Would you be willing to open a PR bumping the version and updating the tests that you modified in terms of warnings? As long as the pipeline is green, I think we can bump the version!

**Comment by sydney-runkle** [comment]
@s-t-e-v-e-n-k,

Going to work on getting v2.8 out soon - any chance you can pick this up in the next week or so?

**Comment by s-t-e-v-e-n-k** [comment]
@sydney-runkle I have been working on it as I can, I hope to finish it up this week.
