### ISSUE TITLE
__pydantic_extra__ value validators passed entire dict

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pydantic/pydantic#9603]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have this model:

```python
from __future__ import annotations
from openapi.types import BaseModel
from openapi.utils import serialize_int, validate_int
import pydantic
from pydantic import ConfigDict
from pydantic.functional_serializers import PlainSerializer
from pydantic.functional_validators import BeforeValidator
from typing import Dict
from typing_extensions import Annotated


class ObjWithComplexNumbersAdditionalProperties(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True, extra="allow")
    __pydantic_extra__:  Dict[str, Annotated[int, BeforeValidator(validate_int), PlainSerializer(serialize_int(True))]] = {}
    
    normal_field: Annotated[str, pydantic.Field(alias="normalField")]
```

which I instantiate like:

```python
ObjWithComplexNumbersAdditionalProperties(
    normal_field="normal",
    __pydantic_extra__={
        "key1": 1,
    },
)
```

This returns a `ValidationError` as so:

```
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for ObjWithComplexNumbersAdditionalProperties
E       __pydantic_extra__
E         Value error, Expected string [type=value_error, input_value={'key1': 1}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.7/v/value_error
```

This behaviour is at odds with validation of a dict in a normal field which works with the same annotation setup

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.3
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: /home/trist/.cache/pypoetry/virtualenvs/openapi-MeiyxmEW-py3.8/lib/python3.8/site-packages/pydantic
               python version: 3.8.19 (default, Mar 19 2024, 16:05:24)  [GCC 11.4.0]
                     platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
             related packages: typing_extensions-4.12.1
                       commit: unknown
```

**Comment by TristanSpeakEasy** [comment]
As an addition to this is looks like built in validators are also suffering

```python
class ObjWithDateAdditionalProperties(BaseModel):
    model_config = ConfigDict(populate_by_name=True, arbitrary_types_allowed=True, extra="allow")
    __pydantic_extra__:  Dict[str, date] = {}
    
    normal_field: Annotated[str, pydantic.Field(alias="normalField")]
```

produces

```
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for ObjWithDateAdditionalProperties
E       __pydantic_extra__
E         Input should be a valid date [type=date_type, input_value={'key1': datetime.date(2020, 1, 1)}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.7/v/date_type
```

**Comment by andresliszt** [comment]
I think that is not the way that `__pydantic_extra__` works. If you set `__pydantic_extra__:  Dict[str, date] = {}` means that any extra argument will be of type `date`. This is the way it works 

``` python
from typing import Annotated
from datetime import date
from pydantic import BaseModel, ConfigDict, Field

class Model(BaseModel):

    normal_field: Annotated[str, Field(alias="normalField")]
    __pydantic_extra__:  dict[str, date] = {}
    model_config = ConfigDict(extra="allow")

obj = Model(
    normalField="normal",
    extra=date.today(),
    other_extra = date.today(),
)

print(obj.__pydantic_extra__)
{'extra': datetime.date(2024, 6, 7), 'other_extra': datetime.date(2024, 6, 7)}
```
This gives validation error because `invalid_extra` is integer

``` python
from typing import Annotated
from datetime import date
from pydantic import BaseModel, ConfigDict, Field

class Model(BaseModel):

    normal_field: Annotated[str, Field(alias="normalField")]
    __pydantic_extra__:  dict[str, date] = {}
    model_config = ConfigDict(extra="allow")

obj = Model(
    normalField="normal",
    invalid_extra=1
)
Datetimes provided to dates should have zero time - e.g. be exact dates [type=date_from_datetime_inexact, input_value=1, input_type=int]
```
I don't know why you use __pydantic_extra__ in your initialization, but it'd be the right way

```python
class Model(BaseModel):

    normal_field: Annotated[str, Field(alias="normalField")]
    __pydantic_extra__:  dict[str, date] = {}
    model_config = ConfigDict(extra="allow")

obj = Model(
    normalField="normal",
    __pydantic_extra__=date.today()
)
```

I remark that i'm not sure if pass `__pydantic_extra__` in the constructor is appropiate
9 / 5.000
appropriate

**Comment by TristanSpeakEasy** [comment]
> I think that is not the way that `__pydantic_extra__` works. If you set `__pydantic_extra__: Dict[str, date] = {}` means that any extra argument will be of type `date`. This is the way it works
> 
> ```python
> from typing import Annotated
> from datetime import date
> from pydantic import BaseModel, ConfigDict, Field
> 
> class Model(BaseModel):
> 
>     normal_field: Annotated[str, Field(alias="normalField")]
>     __pydantic_extra__:  dict[str, date] = {}
>     model_config = ConfigDict(extra="allow")
> 
> obj = Model(
>     normalField="normal",
>     extra=date.today(),
>     other_extra = date.today(),
> )
> 
> print(obj.__pydantic_extra__)
> {'extra': datetime.date(2024, 6, 7), 'other_extra': datetime.date(2024, 6, 7)}
> ```
> 
> This gives validation error because `invalid_extra` is integer

I didn't show the code where we are initializing the object with `__pydantic_extra__: Dict[str, date]` but we are passing a date instance you can see that in there error

```
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for ObjWithDateAdditionalProperties
E       __pydantic_extra__
E         Input should be a valid date [type=date_type, input_value={'key1': datetime.date(2020, 1, 1)}, input_type=dict]
E           For further information visit https://errors.pydantic.dev/2.7/v/date_type
```
`input_value={'key1': datetime.date(2020, 1, 1)}`

But anyway we are setting the typing like this as we are modelling `additionalProperties` in JSONSchema which can be open ie `additionalProperties: true` or it can have a specific schema which is:

```
additionalProperties:
	type: date
```

and when it is specific it can only accept additional fields that match a particular type.

We also set it via the constructor like this, as we get typing errors (specifically pyright in vscode) if we just pass additional fields into the constructor but this also models the way we do similar things in other languages

**Comment by sydney-runkle** [comment]
@andresliszt is correct - I don't think we really support passing in data via `__pydantic_extra__`, but rather just extra arguments to a constructor call (or key/value pairs in a dict).

If you utilize type hinting with `__pydantic_extra__` and pass in additional values in ^^ this way, things should work as expected. Here are some docs on that: https://docs.pydantic.dev/latest/concepts/models/#extra-fields

Marking as resolved. Thanks @andresliszt for the in-depth explanation, and @TristanSpeakEasy for your questions!

**Comment by TristanSpeakEasy** [comment]
We get typing issue with the way you suggest and our CI/CD is not allowing us to set these like you suggest
![image](https://github.com/pydantic/pydantic/assets/108070248/1982cfc7-692b-4f6b-942d-cbb382614bf3)
![image](https://github.com/pydantic/pydantic/assets/108070248/b36d71f3-9ccd-49e5-8ec9-b018e0a36f42)

but this doesn't complain

![image](https://github.com/pydantic/pydantic/assets/108070248/45002e13-cc2b-460d-8771-3780929f542d)

**Comment by TristanSpeakEasy** [comment]
@sydney-runkle can you consider at least the typing issues we see as a bug?

I will try and play around with the way you suggest putting in ignore statements for the linter

**Comment by TristanSpeakEasy** [comment]
okay I can confirm it works if I just pass the extra fields in directly but the typing is definitely wrong here and that causes issues with a quality control tools

**Comment by sydney-runkle** [comment]
Yeah, here's one typing issue: https://github.com/pydantic/pydantic/issues/9187

**Comment by sydney-runkle** [comment]
<img width="745" alt="Screenshot 2024-06-07 at 12 20 26 PM" src="https://github.com/pydantic/pydantic/assets/54324534/317f9b40-6f6a-4360-82fe-2f682cd4a103">

**Comment by TristanSpeakEasy** [comment]
Great thanks Sydney

**Comment by sydney-runkle** [comment]
Sure thing! Thanks for your questions! I'll see what we can do about that typing issue soon.
