### ISSUE TITLE
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

### ISSUE THREAD

**Issue by midhun-soffy** [pydantic/pydantic#9609]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

I am using for my build
pydantic-2.7.3 
pydantic-core-2.18.4
python runtime - 3.12.4

The issue is that ForwardRef._evaluate() has added a new parameter 'recursive_guard' and this parameter is missing in the code pydantic/v1/typing.py (line 66). 

This could be solved by the following code snippet starting line 56

if sys.version_info < (3, 9):

    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        return type_._evaluate(globalns, localns)

elif sys.version_info < (3, 12, 4):

    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        # Even though it is the right signature for python 3.9, mypy complains with
        # `error: Too many arguments for "_evaluate" of "ForwardRef"` hence the cast...
        return cast(Any, type_)._evaluate(globalns, localns, set())

else:
    def evaluate_forwardref(type_: ForwardRef, globalns: Any, localns: Any) -> Any:
        # fixing error: `TypeError: ForwardRef._evaluate() missing 1 required 
        # keyword-only argument: 'recursive_guard'`
        return cast(Any, type_)._evaluate(globalns, localns, set(), recursive_guard=set())

### Example Code

```Python
from langchain_google_vertexai import VertexAI, HarmBlockThreshold, HarmCategory

def read():
    llm = VertexAI(model_name="gemini-1.0-pro", safety_settings=safety_settings())

def safety_settings() -> dict:
    return
    {
        HarmCategory.HARM_CATEGORY_UNSPECIFIED: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
        HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
    }
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.2
 pydantic-core version: 2.18.3
 pydantic-core build: profile=release pgo=false
 python version: 3.12.4
```

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by ellyx13** [comment]
I am using fastapi and pydantic v1 and got the same error. 
Pydantic version: 1.10.11
Fastapi version: 0.111.0

I checked and found it was similar to this issue:
https://github.com/python/cpython/issues/118418

And this commit in python 3.12 do not add the default None value to the recursive_guard parameters

**Comment by ellyx13** [comment]
My solution was to downgrade python to version 3.12.3 and it worked properly

**Comment by midhun-soffy** [comment]
> My solution was to downgrade python to version 3.12.3 and it worked properly
I have 3.12.2 on my local. However trying to test the deployment locally in docker the google alpha function deploy local always looks for the latest python environment even if I specify a lower runtime (their alpha function bug).

Thanks for fixing this

**Comment by sydney-runkle** [comment]
Closed by https://github.com/pydantic/pydantic/pull/9612

**Comment by ebrukadi** [comment]
How did you downgrade the version?

**Comment by imaliabdullah** [comment]
> My solution was to downgrade python to version 3.12.3 and it worked properly

It's also solve my problem

**Comment by ruoyiqiao** [comment]
For my case (venv with version 3.12.4), upgrading to the latest version 2.8.2 solved this issue.

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/78905878/13086128
