### ISSUE TITLE
Constant value in a Pydantic V2 field does not allow an object value

### ISSUE THREAD

**Issue by tteguayco** [pydantic/pydantic#9617]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

In version 1, I had a similar model to the following:

```python
class MyModel(BaseModel):
    name: User = Field(User(name="John Doe"), const=True)
```

When migrating to Pydantic V2, 'const' should be replaced by the use of 'Literal', but this:

```python
class MyModel(BaseModel):
    name: Literal(User(name="John Doe"))
```

outputs the following error:

```python
Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value
```

How should we specify fields with objects as constant values in Pydantic V2?

### Python, Pydantic & OS Version

```Text
             pydantic version: 2.7.3
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: C:\source\production\NAOSReporting\.venv\Lib\site-packages\pydantic
               python version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: fastapi-0.111.0 typing_extensions-4.12.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@tteguayco,

I think the best approach would be to use a custom `field_validator` on your `name` field that verifies whatever constraints you'd like to impose on that field!
