### ISSUE TITLE
unlucky md5 checksum value is parsed to inf

### ISSUE THREAD

**Issue by cnjr2** [pydantic/pydantic#9621]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I have a `File` model with an `md5` checksum. One of my files got a value of `20862292665203397e00089319024245`, which could be interpreted as an integer. I want to coerce it into a string, but somewhere it gets converted to `inf`. I believe this is related to #6045 and #5606. 

What should I do to get around this? 

Thank you for your help :bow:

### Example Code

```Python
from pydantic import BaseModel, ConfigDict


class File(BaseModel):
    model_config = ConfigDict(coerce_numbers_to_str=True)
    md5: str


File.model_validate_json('{"md5": 208622926}')
# >>> File.model_validate_json('{"md5": 208622926}')
# File(md5='208622926')

File.model_validate_json('{"md5": 20862292665203397e00089319024245}')
# >>> File.model_validate_json('{"md5": 20862292665203397e00089319024245}')
# File(md5='inf')
# 
# I would expect: File(md5='20862292665203397e00089319024245')
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /usr/local/lib/python3.10/site-packages/pydantic
               python version: 3.10.14 (main, May 14 2024, 08:46:25) [GCC 12.2.0]
                     platform: Linux-6.4.16-linuxkit-x86_64-with-glibc2.36
             related packages: mypy-0.991 email-validator-2.0.0.post2 typing_extensions-4.6.3 fastapi-0.101.1
                       commit: unknown
```

**Comment by mikeleppane** [comment]
Hey,

I think it fails because `20862292665203397e00089319024245` is a very huge floating point number. You could try:
```python 
File.model_validate_json('{"md5": "20862292665203397e00089319024245"}')
```

**Comment by cnjr2** [comment]
That would work - but unfortunately I do not have control over the json sent to the application.

**Comment by mikeleppane** [comment]
This works at least in this specific case:
```python
File.model_validate(json.loads('{"md5": 20862292665203397e00089319024245}', parse_float=str))
```

**Comment by cnjr2** [comment]
Thanks @mikeleppane :bow:

**Comment by sydney-runkle** [comment]
Marking as resolved for now, thanks @mikeleppane!

I think this is an infrequent enough issue that we can close.
