### ISSUE TITLE
Python 3.12 support in 1.10.x?

### ISSUE THREAD

**Issue by vfazio** [pydantic/pydantic#9622]
### Initial Checks

- [X] I have searched GitHub for a duplicate issue and I'm sure this is something new
- [X] I have searched Google & StackOverflow for a solution and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this is a bug
- [X] I am confident that the issue is with pydantic (not my code, or another library in the ecosystem like [FastAPI](https://fastapi.tiangolo.com) or [mypy](https://mypy.readthedocs.io/en/stable))

### Description

Right now, we have have users using pydantic on 3.12 despite no advertised support. Part of this is due to the python requirement being only 3.7 and without a cap.

A breaking change was introduced in 3.12.4, otherwise 1.10.15 seems to mostly play nice.

However, a number of changes are required to get tests to pass on python 3.12. 

This list is non-exhaustive:

* flake8>=6.1.0
* pycodestyle==2.11.1
* pyflakes==3.1.0
* flake8-quotes>=3.3.2
* ignore ast* warnings (or fix them)
* pytest >=7.3.2
* mypy>1.5
* setuptools needs to be added as a dependency (distutils is gone and cython doesn't add it)
* cython may need a bump for true 3.12 support however we're capped: https://github.com/pydantic/pydantic/commit/b9a316ed7583f78ceae1f4c53f9993aac1c37601

A number of tests still fail, likely due to string format changes between CPython and tools

```
      20 failed
         - tests/test_edge_cases.py:1877 test_cython_function_untouched
         - tests/test_generics.py:573 test_partial_specification_name
         - tests/test_generics.py:1423 test_parse_generic_json
         - tests/test_types.py:2712 test_secretfield
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-plugin.ini-plugin_success.py-None]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-plugin.ini-plugin_fail.py-plugin-fail.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-plugin-strict.ini-plugin_success.py-plugin-success-strict.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-plugin-strict.ini-plugin_fail.py-plugin-fail-strict.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-default.ini-success.py-None]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-default.ini-fail1.py-fail1.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-default.ini-fail2.py-fail2.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-default.ini-plugin_success.py-plugin_success.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-default.toml-success.py-None]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-default.toml-fail1.py-fail1.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-default.toml-fail2.py-fail2.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-plugin.toml-plugin_success.py-None]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-plugin.toml-plugin_fail.py-plugin-fail.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-plugin-strict.toml-plugin_success.py-plugin-success-strict.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[pyproject-plugin-strict.toml-plugin_fail.py-plugin-fail-strict.txt]
         - tests/mypy/test_mypy.py:57 test_mypy_results[mypy-plugin-strict.ini-plugin_default_factory.py-plugin_default_factory.txt]
       9 skipped
make: *** [Makefile:69: test] Error 1
```

In light of #9607, I think a 1.10.16 release should be tagged, but with python capped at <3.13.

If there is a desire to add python 3.12 support, it will take some discussion and some reworking of the tests. If we want python 3.12 support in 1.10.x, a subsequent series of commits can add that support. If we do _not_, we can tag 1.10.17 with python <3.12. 

This would allow users to pin their dependency on 1.10.16 if they need an immediate fix. This will also force a migration to pydantic v2.

But these are pre-caffinated ruminations, so open to thoughts.

@sydney-runkle 

### Python, Pydantic & OS Version

```Text
python 3.12, pydantic 1.10.15
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
> In light of https://github.com/pydantic/pydantic/issues/9607, I think a 1.10.16 release should be tagged, but with python capped at <3.13.

Agreed, I can work on this tomorrow once we get a fix out in `pydantic-core` as well.

> If there is a desire to add python 3.12 support, it will take some discussion and some reworking of the tests. If we want python 3.12 support in 1.10.x, a subsequent series of commits can add that support. 

Let's try for this!

> But these are pre-caffinated ruminations, so open to thoughts.

Haha, thanks for your work on this. Looking forward to collaborating more :).

**Comment by vfazio** [comment]
> > In light of #9607, I think a 1.10.16 release should be tagged, but with python capped at <3.13.
> 
> Agreed, I can work on this tomorrow once we get a fix out in `pydantic-core` as well.
> 
> > If there is a desire to add python 3.12 support, it will take some discussion and some reworking of the tests. If we want python 3.12 support in 1.10.x, a subsequent series of commits can add that support.
> 
> Let's try for this!
> 
> > But these are pre-caffinated ruminations, so open to thoughts.
> 
> Haha, thanks for your work on this. Looking forward to collaborating more :).


@sydney-runkle https://github.com/pydantic/pydantic-core/pull/1299 this ? or are other fixes necessary?

**Comment by sydney-runkle** [comment]
We'll include these:

* https://github.com/pydantic/pydantic-core/pull/1318
* https://github.com/pydantic/pydantic-core/pull/1323

**Comment by vfazio** [comment]
Also this? https://github.com/pydantic/pydantic-core/issues/1292

**Comment by vfazio** [comment]
So... I don't think we can get compiled pydantic without going to Cython 3... We basically need https://github.com/cython/cython/commit/03c498d3142ccee2da258c540e96f12c863159fc and maybe other things, but that is at least what's yelling at me now.

```
pydantic/__init__.c:1125:32: error: ‘_PyCFrame’ has no member named ‘use_tracing’
 1125 |      (unlikely((tstate)->cframe->use_tracing) &&\
      |                                ^~
pydantic/__init__.c:950:43: note: in definition of macro ‘unlikely’
  950 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
pydantic/__init__.c:1280:19: note: in expansion of macro ‘__Pyx_IsTracing’
 1280 |               if (__Pyx_IsTracing(tstate, 0, 0) && tstate->c_tracefunc && __pyx_frame->f_trace) {\
      |                   ^~~~~~~~~~~~~~~
pydantic/__init__.c:2642:3: note: in expansion of macro ‘__Pyx_TraceLine’
 2642 |   __Pyx_TraceLine(16,0,__PYX_ERR(0, 16, __pyx_L1_error))
```

Of course, after compiling it, I'm getting additional type errors. I'm able to coerce most of them, but jumping to cython3 was called out as "not happening" per https://github.com/pydantic/pydantic/blob/211910eccce116f0f25964e81c09e87fd98a351c/pydantic/config.py#L41

Plus, a lot of NameErrors from our friend `_evaluate`:

```
        AAModel = create_model(
            'AAModel', __base__=(TestGenericModel, Generic[T]), __cls_kwargs__={'orm_mode': True}, aa=(int, Field(0))
        )
>       result = AAModel[int](aa=1)

tests/test_create_model.py:223: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pydantic/generics.py:116: in __class_getitem__
    type_hints = get_all_type_hints(cls).items()
pydantic/typing.py:80: in pydantic.typing.get_all_type_hints
    return get_type_hints(obj, globalns, localns, include_extras=True)
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:2263: in get_type_hints
    value = _eval_type(value, base_globals, base_locals, base.__type_params__)
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:415: in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:943: in _evaluate
    self.__forward_value__ = _eval_type(
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:430: in _eval_type
    ev_args = tuple(
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:431: in <genexpr>
    _eval_type(
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:415: in _eval_type
    return t._evaluate(globalns, localns, type_params, recursive_guard=recursive_guard)
/home/vfazio/.pyenv/versions/3.12.4/lib/python3.12/typing.py:938: in _evaluate
    eval(self.__forward_code__, globalns, locals_to_pass),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
```

Unless we skip the requirement for compiled tests on 3.12, i'm guessing "full support" wont happen.

I'm going to limit further testing until there a discussion is had.

**Comment by sydney-runkle** [comment]
@vfazio,

Ahhhh. Good find. We'll stick to that commitment to not support `cython 3`, so we can halt progress on the 3.12 support for now. Thanks for your investigation here!!

Folks can sort of use it unofficially without the compiled packages, given that we fixed the internal typing stuff.

Going to close this PR and the related issue, given your findings. Great work!

**Comment by sydney-runkle** [comment]
> Folks can sort of use it unofficially without the compiled packages, given that we fixed the internal typing stuff.

To clarify - we'll support 3.12, just not compile for 3.12. We can probably add the bound re `<3.13` on the next patch release

**Comment by vfazio** [comment]
We cannot use CPython 3 for 1.10.x, but we _can_ get CPython 0.29.x to work on Python 3.12.

The thing that's "blocking" is the CI pipeline, which is requiring `build-trace`. AFAICT, we're only using tracing on these builds so we can confirm our coverage. Coverage on 3.7-3.11 should be sufficient to give us an idea that code is being exercised as expected.

We _should_ be able to `make build` and still pass the test suite (i tested this locally), so I'm going to propose isolating 3.12 into it's own job branch to trigger a build without tracing where coverage does not get uploaded so doesn't spoil the results.

**Comment by vfazio** [comment]
My PR has the cap for <3.13 in it, i'll push in a sec.

**Comment by vfazio** [comment]
> 
> The thing that's "blocking" is the CI pipeline, which is requiring `build-trace`. AFAICT, we're only using tracing on these builds so we can confirm our coverage. Coverage on 3.7-3.11 should be sufficient to give us an idea that code is being exercised as expected.

@sydney-runkle could you confirm this assumption? Do you cythonize the wheels that are generated? if so, is tracing enabled when they are built? If tracing is a requirement for cythonized wheels then it's all moot.

**Comment by michael-k** [comment]
> We can probably add the bound re <3.13 on the next patch release

But why?  I don't see the benefit of disallowing pip to install pydantic 1.10.17+ (unless `--ignore-requires-python`) on Python 3.13 while it'll happily install 1.10.16.  Regardless if upper bounds are in `install_requires` or for Python versions, they just cause pain and confusion for users, esp. if users don't have control over pydantic's version because some other package decided to add a upper bound and pin pydantic < 2.

**Comment by vfazio** [comment]
I don't really want to put words in theor mouth or answer for them, I'm not a maintainer, but preventing it allows _them_ to determine if support will be extended vs being strong armed into supporting it because thousands of users are able to install it and assume that if they can install it that its supposed to be supported. Its "explicit support" vs "implied support"

It may work in most usecases in 3.13. It may even pass the full test suite, though i have strong doubts on the cythonized builds working. In the end, just because it works doesn't mean its supported. 

It may be nontrivial to add full 3.13 support or maybe they don't want to be on the hook for dealing with another full life cycle of a release because there may be compatibility issues between bugfix versions like we just had with 3.12.4 and they need to focus developer time elsewhere, like pydantic v2 or a new product, instead of on a pydantic 1.10.x thats in maintenance mode.

I know #9613 is going to be an issue at some point.

My 2¢

**Comment by vfazio** [comment]
Going to tear this conversation off into a different issue, because it does seem pertinent and isn't straightforward
