### ISSUE TITLE
Request: built-in `TypeAlias` for a Pydantic serializable object

### ISSUE THREAD

**Issue by jamesbraza** [pydantic/pydantic#9626]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I have some Python 3.12 code like this for a `Field` that is serializable by native Pydantic v2:

```python
from typing import Annotated, TypeAlias

from pydantic import BaseModel, WrapSerializer

Serializable: TypeAlias = None | dict | list | int | float | str | bool | BaseModel


class SomethingSerializable(BaseModel):
    @staticmethod
    def _custom_serializer(value: Serializable, handler, info):  # noqa: ARG004
        if isinstance(value, BaseModel):
            return value.model_dump()
        return handler(value)

    serializable: Annotated[Serializable, WrapSerializer(_custom_serializer)]
```

It would be pretty useful if `Serializable` could be imported from Pydantic. Perhaps it can be a `Field` subtype

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @jamesbraza,

We have support for a `JsonValue` type in `pydantic`:

```py
JsonValue: TypeAlias = Union[
        List['JsonValue'],
        Dict[str, 'JsonValue'],
        str,
        bool,
        int,
        float,
        None,
    ]
```

So I think for your case, you could do something like:

```py
from typing import Annotated, TypeAlias

from pydantic import BaseModel, JsonValue, WrapSerializer

Serializable: TypeAlias = JsonValue | BaseModel


class SomethingSerializable(BaseModel):
    @staticmethod
    def _custom_serializer(value: Serializable, handler, info):  # noqa: ARG004
        if isinstance(value, BaseModel):
            return value.model_dump()
        return handler(value)

    serializable: Annotated[Serializable, WrapSerializer(_custom_serializer)]
```

Marking this as resolved for now - the `JsonValue` type covers the majority of these cases, and I think it can be the responsibility of the user to cover additional cases like `BaseModel`, or pydantic dataclasses, etc.

Thanks for your question!

**Comment by jamesbraza** [comment]
Oh TIL of `JsonValue`, thank you @sydney-runkle! Appreciate your detailed response, clears me up and I already adopted it 👍

**Comment by jamesbraza** [comment]
One interesting side effect is I discovered:

```python
from typing import TypeAlias

from pydantic import BaseModel, JsonValue

SerializableJsonValue: TypeAlias = JsonValue | BaseModel
SerializableDIY: TypeAlias = None | dict | list | int | float | str | bool | BaseModel
```

Pydantic will automatically do a deep copy of fields type hinted with `SerializableJsonValue`, whereas it will only do a shallow copy with `SerializableDIY`. So it's not exactly a drop-in replacement
