### ISSUE TITLE
Simple method to parse models from files

### ISSUE THREAD

**Issue by rboston628** [pydantic/pydantic#9634]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be nice if there were a simple, short method call that could wrap
``` python
    with open(filePath, "r") as f:
        obj = Model.model_validate_json(f.read())
```
so that I could call it in one single line such as 
``` python
    obj = Model.method_to_parse_the_file(filePath)
```
or possibly also something such as
``` python
    obj = method_to_parse_file_as(List[Model], filePath)
```
This would be instead of writing out the context manager block hundreds of times every time I want to read a json file.

This would be a really great feature that I'm sure users might, in the future, incorporate into approximately several thousand lines of their code base.

### Affected Components

- [X] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @rboston628,

Thanks for your feature request!

I think for now, this kind of method / helper belongs in user code. You could subclass `BaseModel` and add said helper method so that you could then call it on all of your `Model` classes from there.

If this issue gets a decent amount of traction / support, we'd be happy to reopen with the possibility of introducing support for file types directly, but that's sort of a different feature request.

Let me know if you have any other questions!
