### ISSUE TITLE
create_model; with complex Field definition

### ISSUE THREAD

**Issue by devamin** [pydantic/pydantic#9655]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Currently the only way to create dynamic model is by using create_model; 
```
from pydantic import PydanticUserError, create_model

try:
    create_model('FooModel', foo=(str, 'default value', 'more'))
except PydanticUserError as exc_info:
    assert exc_info.code == 'create-model-field-definitions'
```

Would be good to use Field, instead of the tuple, currently we cannot set many field params, and the order is confusing... 

Thank you

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
You can use a `Field` as the second tuple value:

```py
from pydantic import create_model, Field

FooModel = create_model('FooModel', foo=(str, Field(default='default value', json_schema_extra={'example': 'example value'})))
print(repr(FooModel()))
#> FooModel(foo='default value')

print(FooModel.model_json_schema())
#> {'properties': {'foo': {'default': 'default value', 'example': 'example value', 'title': 'Foo', 'type': 'string'}}, 'title': 'FooModel', 'type': 'object'}
```
