### ISSUE TITLE
InstanceOf does not dump fields in child classes when serializing

### ISSUE THREAD

**Issue by orfisko** [pydantic/pydantic#9665]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

InstanceOf is a great addition to pydantic v2. When dumping data though it only picks up fields which were specified in the parent model. Really annoying this, I want to use instance of instead of unions.

### Example Code

```Python
from pydantic import BaseModel, InstanceOf

class SubModel(BaseModel):
    field1: int

class ChildSubModel(SubModel):
    field2: int

class TestModel(BaseModel):
    subModel: InstanceOf[SubModel]


testmodel = TestModel(subModel=ChildSubModel(field1=5, field2=6))

print(testmodel.model_dump(mode="json"))
```
outputs:
{'subModel': {'field1': 5}}

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: home/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
                     platform: Linux-6.5.0-1023-oem-x86_64-with-glibc2.35
             related packages: pydantic-extra-types-2.6.0 typing_extensions-4.12.2 pydantic-settings-2.2.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @orfisko,

You can use the `SerializeAsAny` annotation to get he behavior you're looking for:

```py
from pydantic import BaseModel, InstanceOf, SerializeAsAny

class SubModel(BaseModel):
    field1: int

class ChildSubModel(SubModel):
    field2: int

class TestModel(BaseModel):
    subModel: SerializeAsAny[InstanceOf[SubModel]]


testmodel = TestModel(subModel=ChildSubModel(field1=5, field2=6))

print(testmodel.model_dump(mode="json"))
#> {'subModel': {'field1': 5, 'field2': 6}}
```
See the [docs](https://docs.pydantic.dev/latest/concepts/serialization/#serializing-with-duck-typing) for more details.

**Comment by orfisko** [comment]
Waw Sydney, thanks so much for picking this up! Should we not add this to documentation so that I lcan also land on this page when I look for InstanceOf tweaks and stuff. Seems like important information to me. I have been digging through the docs and could not connect these docs. It's my fourth year that I am using this lib quite intensively, so would make sense to add this. 
In any case, thanks !

**Comment by sydney-runkle** [comment]
@orfisko,

Feel free to open a PR with a docs update, I'd be happy to review! I think just a link to the serialize as any docs would be fine.

I don't think this is tightly coupled with the `InstanceOf` annotation though, it's more about serialization behavior with duck typing. Definitely one of the trickier settings to figure out!
