### ISSUE TITLE
Add citation information to Software Citation Station?

### ISSUE THREAD

**Issue by TomWagg** [pydantic/pydantic#9669]
Hi! Someone recently added a package to the Software Citation Station that depends on your package. We don't currently have your package listed but would love for it to be shown on our site.

The Software Citation Station is a simple web tool for quickly generating the necessary LaTeX/BibTeX to properly acknowledge the software used in research and ensure work is properly credited.

- [Add your software with this form](https://www.tomwagg.com/software-citation-station/?new-software=true)
- [Main website](https://www.tomwagg.com/software-citation-station/)
- [Read more in our paper](https://arxiv.org/abs/2406.04405)

**Comment by sydney-runkle** [comment]
Done, marking as resolved! Thanks!
