### ISSUE TITLE
How to use json_encoder for ModelConfig extra attributes

### ISSUE THREAD

**Issue by cute149q** [pydantic/pydantic#9675]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi, 

After transferring to PydanticV2, I found the json_encoders in model_config is not working for extra fields in the model. However, it is working in V1.

### Example Code

```Python
def trans_datetime(dt: datetime) -> datetime:
    # Test that the `add_utc_timezone` function works as expected
    return dt.isoformat()


class ConfigBaseModel(BaseModel):
    model_config = ConfigDict(frozen=True, json_encoders={datetime: trans_datetime}, extra="allow")

class TimeInfo(ConfigBaseModel):
    start_time: datetime

InstanceTime = TimeInfo(start_time = xxxx, end_time = xxxx)

# in this case, only the start time will be run json encoder
```

### Python, Pydantic & OS Version

```Text
sing python3.11 (3.11.4)
             pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
               python version: 3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.5-arm64-i386-64bit
             related packages: mypy-1.10.0 typing_extensions-4.12.2
```

**Comment by sydney-runkle** [comment]
Hi @cute149q,

Thanks for the question. We don't offer robust support for `json_encoders` anymore, see the docs:

```
This config option is a carryover from v1.
        We originally planned to remove it in v2 but didn't have a 1:1 replacement so we are keeping it for now.
        It is still deprecated and will likely be removed in the future.
```

I'd recommend using a type annotation in the `__pydantic_extra__` specification:

```py
from datetime import datetime
from typing import Annotated, Dict

from pydantic import BaseModel, ConfigDict, PlainSerializer, Field

def trans_datetime(dt: datetime) -> str:
    # Test that the `add_utc_timezone` function works as expected
    return dt.isoformat()

TransDatetime = Annotated[
    datetime,
    PlainSerializer(trans_datetime, when_used='json')
]

class TimeInfo(BaseModel):
    start_time: TransDatetime

    model_config = ConfigDict(frozen=True, json_encoders={datetime: trans_datetime}, extra="allow")
    __pydantic_extra__: Dict[str, TransDatetime] = Field(init=False)


InstanceTime = TimeInfo(start_time=datetime.now(), end_time=datetime.now())
print(InstanceTime.model_dump_json())
#> {"start_time":"2024-06-18T13:00:52.991797","end_time":"2024-06-18T13:00:52.991804"}
```

Marking as resolved for now, as I don't think we plan to expand support for `json_encoders` at the moment.

**Comment by cute149q** [comment]
> Hi @cute149q,
> 
> Thanks for the question. We don't offer robust support for `json_encoders` anymore, see the docs:
> 
> ```
> This config option is a carryover from v1.
>         We originally planned to remove it in v2 but didn't have a 1:1 replacement so we are keeping it for now.
>         It is still deprecated and will likely be removed in the future.
> ```
> 
> I'd recommend using a type annotation in the `__pydantic_extra__` specification:
> 
> ```python
> from datetime import datetime
> from typing import Annotated, Dict
> 
> from pydantic import BaseModel, ConfigDict, PlainSerializer, Field
> 
> def trans_datetime(dt: datetime) -> str:
>     # Test that the `add_utc_timezone` function works as expected
>     return dt.isoformat()
> 
> TransDatetime = Annotated[
>     datetime,
>     PlainSerializer(trans_datetime, when_used='json')
> ]
> 
> class TimeInfo(BaseModel):
>     start_time: TransDatetime
> 
>     model_config = ConfigDict(frozen=True, json_encoders={datetime: trans_datetime}, extra="allow")
>     __pydantic_extra__: Dict[str, TransDatetime] = Field(init=False)
> 
> 
> InstanceTime = TimeInfo(start_time=datetime.now(), end_time=datetime.now())
> print(InstanceTime.model_dump_json())
> #> {"start_time":"2024-06-18T13:00:52.991797","end_time":"2024-06-18T13:00:52.991804"}
> ```
> 
> Marking as resolved for now, as I don't think we plan to expand support for `json_encoders` at the moment.

Hi @sydney-runkle , thanks for the reply. However there is an error occurred if I ran the code. 

NameError: Fields must not use names with leading underscores; e.g., use 'pydantic_extra__' instead of '__pydantic_extra__'.

Any idea of how to solve this error?
