### ISSUE TITLE
[docs]: cannot leverage on alias_priority if alias_generator is not involved

### ISSUE THREAD

**Issue by AlessandroMiola** [pydantic/pydantic#9678]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi everybody,
first off, thank you for your amazing work on `pydantic` and on the other products!

I would like to point out a possible (I apologize if this is not the case and I'm missing something) inconsistency in the documentation at https://docs.pydantic.dev/latest/concepts/fields/#field-aliases, where the note specifies that 

> !!! note "Alias precedence and priority"
      In case you use `alias` together with `validation_alias` or `serialization_alias` at the same time,
      the `validation_alias` will have priority over `alias` for validation, and `serialization_alias` will have priority
      over `alias` for serialization.

> **You may also set `alias_priority` on a field to change this behavior.**

As far as I could experiment, there's no way you can leverage on `alias_priority` if you don't use an `AliasGenerator`. If that's effectively the case, IMO the final statement in the note might be somewhat misleading because the section does not deal with alias generators, whose _alias precedence_ behaviours are indeed well described at https://docs.pydantic.dev/latest/concepts/alias/#alias-precedence.

As a possible corroboration to that, tests at `pydantic/tests/test_aliases.py` do not reference `alias_priority` when an `AliasGenerator` is not involved (if not for testing that `alias_priority=2` by default when `repr`esenting a model).

### Example Code

```Python
from pydantic import BaseModel, Field


class Model(BaseModel):
    first_name: str = Field(
        alias="firstName",
        validation_alias="FIRST_NAME",
        serialization_alias="f_name",
        alias_priority=1
    )


model = Model(firstName="Pippo")   # ValidationError, no way to tweak alias_priority to be able to validate via plain_alias
print(model.model_dump())
print(model.model_dump(by_alias=True))   # Serialization via serialization_alias only
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.2
        pydantic-core version: 2.18.3
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\aless\AppData\Local\pypoetry\Cache\virtualenvs\pydantic-notes-o9e16XX9-py3.10\Lib\site-packages\pydantic
               python version: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
                     platform: Windows-10-10.0.22631-SP0
             related packages: typing_extensions-4.12.1
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@AlessandroMiola,

Great catch. This is definitely wrong. I'll open a fix in a sec.
