### ISSUE TITLE
`TypeAdapter` does not support V1 `BaseModel`

### ISSUE THREAD

**Issue by Aed3r** [pydantic/pydantic#9682]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

We are in the progress of migrating to Pydantic V2, and use a mix of V1 and V2 in the meantime. A class that previously only supported V1 type parsing using `parse_obj_as` should now support V2 models as well. From [the documentation](https://docs.pydantic.dev/latest/api/type_adapter/), the `TypeAdapter` appears to be the perfect solution to parse both version's `BaseModel` and non-`BaseModel` types. Unfortunately, it does not appear handle V1's `BaseModel` properly (see the code example below). Is this intended? Would it be possible to add support for this?

### Example Code

```Python
from pydantic import TypeAdapter
from pydantic.v1 import BaseModel


class Item(BaseModel):
    id: int
    name: str


item_data = [{"id": 1, "name": "My Item"}]

items = TypeAdapter(list[Item]).validate_python(item_data)
# Traceback (most recent call last):
#   File "./test.py", line 18, in <module>
#     items = TypeAdapter(list[Item]).validate_python(item_data)
#             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "pydantic/type_adapter.py", line 239, in validate_python
#     return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# TypeError: BaseModel.validate() takes 2 positional arguments but 3 were given
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=false
               python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [GCC 13.2.0]
             related packages: pydantic-settings-2.2.1 typing_extensions-4.11.0 mypy-1.10.0
```

**Comment by sydney-runkle** [comment]
@Aed3r,

Thanks for reporting this. We don't currently plan on adding support to `TypeAdapter` for V1 models - we're trying to reduce our V1 oriented changes given that V2 has now been out for about a year.

Going to close this as not planned for now.

If you're interested / think it'd be helpful, feel free to open a docs update PR that adds a note about this to the migration guide :).
