### ISSUE TITLE
Notes on Union Serialization Fixes

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9688]
Collecting some of my recent ramblings about improvements that can be made to improve union serialization behavior:

1. Create a tagged union serializer in `pydantic-core` to improve performance when serializing discriminated unions with simple `str` discriminators. I'd like to work on this in the short term, given my current familiarity with the union logic in core.
2. Potentially, tag validated instances at runtime with a `Tag` associated with the union member to which the data matched. This would improve both accuracy and performance on the serialization front.
3. (2) above will begin to fail when we serialize unvalidated data, which is possible. In this case, we may want to suffer a minor performance benefit, but revalidate at serialization time in order to select the best union member (effectively, doing (2) but at serialization time).
4. Support serialization discriminators, both of `str` type and of `callable` type. Off the top of my head I can't think of a case where the `str` type discriminator would be different for serialization vs validation, but whatever.

> Note: we'll want to be careful especially in regards to dealing with callable discriminators, because some of them might be not be idempotent, so any changes we make in this department would likely have to be opt-in to avoid breaking changes.

I think (1) and (2) above would be good first steps that help to address the majority of union serialization issues that I've collected in this [milestone](https://github.com/pydantic/pydantic/milestone/13).

These suggestions require a lot of work, and some of these requests probably deserve to reside in their own issues, but I think it makes sense to collect similar ideas here for now.

**Comment by sydney-runkle** [comment]
@davidhewitt and @dmontagu, please feel free to add your thoughts!

**Comment by davidhewitt** [comment]
I think (4) will be a more reliable (but slightly less performant) first step than 2 because it sidesteps the question of where to store tags. In a sense, the validated instance's type is likely a good "`Tag`" in many cases and `isinstance` checks are an easy way to retrieve this data.

**Comment by sydney-runkle** [comment]
Upon further reflection, I think just the combo of 1 and 4 will be a major improvement, and we can mark this issue as resolved once we (I write code to) achieve those goals.

**Comment by sydney-runkle** [comment]
I've opened the following to work on this issue:

* https://github.com/pydantic/pydantic-core/pull/1400
* https://github.com/pydantic/pydantic-core/pull/1398
* https://github.com/pydantic/pydantic-core/pull/1397

This should fix many of the cases for which folks are currently having issues. Issues like https://github.com/pydantic/pydantic/issues/9590 will need even mroe custom isinstance logic, which I'm not even sure we should implement. Will think more on that issue.

**Comment by sydney-runkle** [comment]
Though I think we could leave this issue open after the above PRs are merged in order to address cases like #9590, I'm satisfied with progress here for v2.9 🚀

**Comment by sydney-runkle** [comment]
In order to address cases like #9590, we're going to need to add some sort of slow `isinstance` check. I'm going to close this as resolved for now, but we can certainly reference these ideas when moving forward with said fixes. As mentioned above, our union serialization work is done for v2.9.
