### ISSUE TITLE
Documenting `create_model` with `description`

### ISSUE THREAD

**Issue by jamesbraza** [pydantic/pydantic#9691]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

https://docs.pydantic.dev/latest/concepts/models/#generic-models documents how to use `create_model` with types and defaults. However, it doesn't show an example how to instantiate with `description`. Can we add an example for use of `Field`?

It would be good to document because with `pydantic==2.7.4`, the below:

```python
from pydantic import Field, create_model
from pydantic.fields import FieldInfo

config: dict[str, tuple[type, FieldInfo]] = {
    "some_field": (int, Field(default=5, description="Some description."))
}
Model = create_model("Model", **config)
```

When run with `mypy==1.10.0`, will error:

```none
a.py:5:5: error: Dict entry 0 has incompatible type "str":
"tuple[type[int], int]"; expected "str": "tuple[type, FieldInfo]"  [dict-item]
        "some_field": (int, Field(default=5, description="Some description...
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...
a.py:7:9: error: No overload variant of "create_model"
matches argument types "str", "dict[str, tuple[type, FieldInfo]]"
[call-overload]
    Model = create_model("Model", **config)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.py:7:9: note: Possible overload variants:
a.py:7:9: note:     def create_model(str, /, *, __config__: ConfigDict | None = ..., __doc__: str | None = ..., __base__: None = ..., __module__: str = ..., __validators__: dict[str, classmethod[Any, Any, Any]] | None = ..., __cls_kwargs__: dict[str, Any] | None = ..., **field_definitions: Any) -> type[BaseModel]
a.py:7:9: note:     def [Model <: BaseModel] create_model(str, /, *, __config__: ConfigDict | None = ..., __doc__: str | None = ..., __base__: type[Model] | tuple[type[Model], ...], __module__: str = ..., __validators__: dict[str, classmethod[Any, Any, Any]] | None = ..., __cls_kwargs__: dict[str, Any] | None = ..., **field_definitions: Any) -> type[Model]
```

So it's unclear how to set up the typing here

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [X] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @jamesbraza,

We just use `Any` as the type of the field definitions and enforce that the appropriate information is present at runtime.

Pyright doesn't complain if you do:

```py
from typing import Any

from pydantic import Field, create_model

config: dict[str, Any] = {
    "some_field": (int, Field(default=5, description="Some description."))
}
Model = create_model("Model", **config)
```

**Comment by sydney-runkle** [comment]
I've added a PR with an extra note / example.
