### ISSUE TITLE
Expand breadth of benchmarks

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9711]
We have a robust benchmark test suite in `pydantic-core`, but are lacking similar coverage in `pydantic`.

Specifically, I'm interested in expanding this test suite in relation to our core schema build times, as we're looking to improve performance there in the short term. Secondarily, I'm interested in better benchmarking for our json schema generation. Benchmarks for validation and serialization are great, but we've already got pretty good coverage in `pydantic-core` for those, so I'm less concerned about such benchmarks.

This is a great first issue - you can help write tests that test a variety of use cases for `pydantic`, without having to delve into the internals of `pydantic` code to fix bugs or add new features.

Here are some cases for which I think we should expand our suite of benchmarks (assume these are for core schema generation, but you can write related tests for any of the above mentioned categories). As in, you could read the first bullet as "we need to write some tests showcasing how long schema building takes for models with custom validators".

- [x] custom validators (field and model, also before, wrap, after, and plain)
- [x] tagged and untagged unions
- [x] stdlib types
- [x] second class Pydantic types like `SecretStr` and `PositiveInt`
- [x] custom serializers (field and model, also before, wrap, after, and plain)
- [x] recursive model definitions -- need much more robust testing when defs / refs are involved
- [ ] third party, custom types

I wouldn't say these are necessary to close this issue, but one thing for more involved contributors to look at would be benchmarking specific parts of our core schema generation process in `pydantic`, such as:

- [ ] annotation application
- [ ] discriminator application
- [ ] schema cleaning (including defs / refs simplification)
- [ ] schema walking
- [ ] field acquisition / setup in `ModelMetaClass.__new__`

**Comment by siavashyj** [comment]
Do you have a plan on what general areas we want to focus on increasing benchmark coverage? (i.e. serialization, deserialization, import, validation, etc)

**Comment by sydney-runkle** [comment]
Any of these would be great. I'd say the most pressing category is model schema generation, but we'd more than welcome additional benchmarks for cases of validation and serialization varying in complexity. I'd say that JSON schema generation is lower priority, in general.

**Comment by sydney-runkle** [comment]
This probably needs more specific acceptance criteria - when are we done with this?

**Comment by AdolfoVillalobos** [comment]
Hello! @sydney-runkle, I created PR #10240 to handle this issue.

My idea was to create three separate test files to handle benchmarks for each of the following categories:

- Schema generation
- validations
- Serializations.

I hope this meets the issue's requirements. I am open to any corrections or suggestions you might have.

I created tests with an increasing degree of complexity. I got inspiration from the pydantic-core library.

**Comment by sydney-runkle** [comment]
I've added this to our current sprint - I'd like to add a few more benchmarks to round out this issue, but the work done above is a great start. @Viicos mentioned he might add some new ones related to defs / refs / schema cleaning as well.

**Comment by sydney-runkle** [comment]
Alright, I've designed some more helpful criteria here re how we can close this issue. I'll note (slightly correcting my previous statement), I'm less concerned about benchmarking validation / serialization, and more concerned about benchmarking core schema generation, and secondarily, json schema generation.

I'm going to update the description of this issue so that these criteria are obvious from the get go.

**Comment by AdolfoVillalobos** [comment]
> I've added this to our current sprint - I'd like to add a few more benchmarks to round out this issue, but the work done above is a great start. @Viicos mentioned he might add some new ones related to defs / refs / schema cleaning as well.

Yei! That was the idea. To have a first stab at the problem. 

I have more clarity on the scope now, so I'll submit a new PR concerning core schema generation in the cases you highlighted. 

Thanks for the guidance!

**Comment by AdolfoVillalobos** [comment]
I added PR #10249  just for custom field/model validators to ensure I understood the requirements correctly. Any suggestions/improvements are welcome ;)

**Comment by AdolfoVillalobos** [comment]
I saw #10247 . Nice!

**Comment by AdolfoVillalobos** [comment]
I submited pr #10362 handling two cases:

1. tagged/untagged unions
1. stdlib types

Let me know if there are any issues.  Cheers :)

**Comment by AdolfoVillalobos** [comment]
@sydney-runkle I am keen to keep contributing to close this issue. I submitted PR #10568 to handle pydantic custom types. However, I skiped the test since a decision was made to avoid cluttering the codspeed report.

I would appreciate some guidance on how to proceed in the remaining cases:

> * [x]  custom validators (field and model, also before, wrap, after, and plain)
> * [x]  tagged and untagged unions
> * [x]  stdlib types
> * [ ]  custom serializers (field and model, also before, wrap, after, and plain)
> * [ ]  recursive model definitions -- need much more robust testing when defs / refs are involved
> * [ ]  second class Pydantic types like `SecretStr` and `PositiveInt`
> * [ ]  third party, custom types

Could you provide some examples or guidance on the remaining points?:
1. For custom serializers, I already provided some benchmarks but I might be missing some important cases. Some of the provided benchmarks where also rejected.
2. Are there any particular use cases relevant to recursive definitions and third-party types? I can create my own in both cases if you think it is best.

Cheers!

**Comment by sydney-runkle** [comment]
> @sydney-runkle I am keen to keep contributing to close this issue.

Amazing! I've merged your PR #10568, and updated the checklist above.

> 1. For custom serializers, I already provided some benchmarks but I might be missing some important cases. Some of the provided benchmarks where also rejected.

All good, I've checked this off above.

> 2. Are there any particular use cases relevant to recursive definitions and third-party types? I can create my own in both cases if you think it is best.

Not any in particular - feel free to create your own. The more complex, the better, I suppose (for the recursive ones).

Looking forward to reviewing your last PR here. Great work!!

**Comment by AdolfoVillalobos** [comment]
@sydney-runkle Thanks for the feedback! I gave a first stab at the recursive case. Indeed, one could take many directions, so PR #10602  is a starting point.  I'm open to suggestions :)

**Comment by sydney-runkle** [comment]
I'm going to go ahead and mark this as resolved by #10602 🚀. Amazing work @AdolfoVillalobos on helping us gradually move this across the line.

Happy to accept more benchmarks in the future (we'd love continued contributions), but we've significantly upped our baseline here which is what we were looking for.

**Comment by AdolfoVillalobos** [comment]
That's so cool, thanks! I will contribute new benchmark PRs in the future. 

I'm also keen to continue contributing to other issues as I improve my knowledge of Pydantic's internals.

Cheers!
