### ISSUE TITLE
No package metadata was found for email-validator

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9716]
### Discussed in https://github.com/pydantic/pydantic/discussions/9588

<div type='discussions-op-text'>

<sup>Originally posted by **dwbelliston** June  5, 2024</sup>
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hey! Thanks for the work on this project. Been running well on version 1, just tried to upgrade to v2 and having some issues.

I am deploying to aws lambda and a very simple works.

Then when i try to use EmailStr and I get an issue saying i need to `pip install pydantic[email]`

Once i do that... i get an error:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'app.main': No package metadata was found for email-validator
```

I checked the code and the email-validator dep is in the lambda code. I have tried quite a few different approaches, but keep getting this metadata issue.

Would love suggestions on other ideas to debug this. Thanks!!

### Example Code

```Python
"""
API

Main entrypoint to API
"""

from pydantic import BaseModel, EmailStr

from fastapi import FastAPI
from mangum import Mangum


# Properties to receive via API on creation
class SampleModel(BaseModel):
    email: EmailStr


# Set up app
app = FastAPI(
    title="SAMPLE_NAME",
)


@app.get("/test", response_model=SampleModel)
async def trigger_error():

    return SampleModel(email="test@me.com")
    # division_by_zero = 1 / 0


# Wrap in ASGI to deploy on lambda
handler = Mangum(app)  # type: ignore
```

### Python, Pydantic & OS Version

```Text
running in aws lambda

runtime python 3.11
```
</div>

**Comment by sydney-runkle** [comment]
Reopening this as a bug until we can resolve the issue!

**Comment by Viicos** [comment]
IIRC this is an issue with AWS, not working as expected with `importlib.metadata`

**Comment by sydney-runkle** [comment]
Perhaps related: https://github.com/python-jsonschema/jsonschema/issues/628

**Comment by sydney-runkle** [comment]
Ah, see the solution here: https://github.com/pydantic/pydantic/pull/6033#issuecomment-1927020910
