### ISSUE TITLE
an uninformative error

### ISSUE THREAD

**Issue by ArtemIsmagilov** [pydantic/pydantic#9730]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description
pydantic version 2.7
I want to get more specific information about the error. For example, which field is missing, which field is superfluous, which field has not been checked. But instead of an exact error, I just get a link to an abstract error
example error.
```python
class PersonFilmRoles(BaseModel):
    id: str
    roles: list[str]

print(PersonFilmRoles(id='10', name='Bob'))
```
Result.
```python
pydantic_core._pydantic_core.ValidationError: 1 validation error for PersonFilmRoles
roles
  Field required [type=missing, input_value={'id': 'sad', 'name': ['sad']}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```
Example good message.
```python
pydantic_core._pydantic_core.ValidationError: 1 validation error for PersonFilmRoles
roles
  Fields required (roles, ...) [type=missing, input_value={'id': 'sad', 'name': ['sad']}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @ArtemIsmagilov,

The error you've printed does show which field is missing (`roles`). Consider this case that shows multiple missing fields:

```py
from pydantic import BaseModel, ValidationError

class Model(BaseModel):
    a: int
    b: int

try:
    Model()
except ValidationError as e:
    print(e)
    """
    2 validation errors for Model
    a
    Field required [type=missing, input_value={}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.8/v/missing
    b
    Field required [type=missing, input_value={}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.8/v/missing
    """
```

Closing this as not planned for now. If you'd like more custom information in your errors, these docs should be of help: https://docs.pydantic.dev/latest/errors/errors/#custom-errors

**Comment by ArtemIsmagilov** [comment]
Thank you for responding. Yes, I saw the lines with the omissions. They just aren't highlighted somehow
