### ISSUE TITLE
Get example= 

### ISSUE THREAD

**Issue by ex3lite** [pydantic/pydantic#9736]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

in Field add
example: Any | None = _Unset,

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [x] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi!

`Field` already has an examples parameter: https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.Field

Not really sure what you're requesting here, closing as not planned for now. Please follow up with a more detailed request if you still have questions!

**Comment by ex3lite** [comment]
> Hi!
> 
> `Field` already has an examples parameter: https://docs.pydantic.dev/latest/api/fields/#pydantic.fields.Field
> 
> Not really sure what you're requesting here, closing as not planned for now. Please follow up with a more detailed request if you still have questions!

“Examples” implies an array, when the variable “Example” can have “str”, which reduces the length of the text, “Example” itself works natively, since “Field” was inherited from “Query”, and “Query” itself has “Example” "
I don’t quite understand why they decided not to add “Example”😢

**Comment by ex3lite** [comment]
Example работает в Field, по тем же причинам наследования, но подсвечивает ошибку синтаксиса (Хотя это не так)

**Comment by ex3lite** [comment]
Example works in Field, for the same inheritance reasons, but highlights a syntax error (Even though it doesn't)
