### ISSUE TITLE
validate_default has no effect when attribute type is Literal

### ISSUE THREAD

**Issue by kwint** [pydantic/pydantic#9738]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When an field has an Enum value as its default value, then it is translated to a str when both `use_enum_values` and `validate_default` are set True, as is expected from the documentation.

However, when the type of the Field is a Literal of that enum, the validate_default doesn't seem to work. See code below.

The same happens when the type is `Literal[MyEnum.FOO, MyEnum.BAR]`

### Example Code

```Python
from enum import StrEnum, auto
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class MyEnum(StrEnum):
    FOO = auto()
    BAR = auto()


class MyModel(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    enum_field: MyEnum = Field(default=MyEnum.FOO, validate_default=True)


class MyModelLiteral(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    enum_field: Literal[MyEnum.FOO] = Field(default=MyEnum.FOO, validate_default=True)
                                                     # default="foo" gives same result


print(type(MyModel().enum_field))  # <class 'str'>
print(type(MyModelLiteral().enum_field))  # <enum 'MyEnum'>
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
                 install path: /home/kwint/.cache/pypoetry/virtualenvs/material-library-8A638HCG-py3.11/lib/python3.11/site-packages/pydantic
               python version: 3.11.8 (main, Feb 25 2024, 16:39:33) [GCC 11.4.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2 mypy-1.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@kwint,

Thanks for reporting this. Definitely looks like a bug. Going to mark this as a good first issue - should be fixable within `pydantic` alone.

If anyone is interested in taking a stab at this, feel free to ping me when you'd like a review or if you have questions!

**Comment by akshatvishu** [comment]
Hi @sydney-runkle,   I'd be happy to tackle this issue!

**Comment by sydney-runkle** [comment]
@akshatvishu,

Go for it!!

**Comment by kwint** [comment]
This is blocking me a bit so I gave it shot my self. Hope I didn't step on your toes @akshatvishu
