### ISSUE TITLE
Inconsistency handling constraints for `Optional[decimal.Decimal]` and other optional "primitive" types

### ISSUE THREAD

**Issue by lazyhope** [pydantic/pydantic#9748]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Currently, the following code raises a `ValueError`:
```python
from decimal import Decimal
from typing import Annotated

from pydantic import RootModel, Field

RootModel[Annotated[Decimal | None, Field(max_digits=2)]]
# ValueError: Unknown constraint max_digits
```
This issue has been reported in multiple (closed) issues: #6955, #7306, #7546, etc.

### Current Workaround

The current workaround is to apply constraints directly to `Decimal`:
```python
RootModel[Annotated[Decimal, Field(max_digits=2)] | None]
```

### Proposed Enhancement

I have noticed that for other commonly used types, such as `str`, `float`, and `date`, a similar code structure works without issue. For example:
```python
from datetime import date, datetime
from typing import Annotated

from pydantic import RootModel, Field

RootModel[Annotated[date | None, Field(le=datetime(2023, 1, 1))]](datetime(2023, 1, 1))
# RootModel[Annotated[Union[date, NoneType], FieldInfo(annotation=NoneType, required=True, metadata=[Le(le=datetime.datetime(2023, 1, 1, 0, 0))])]](root=datetime.date(2023, 1, 1))
```

Therefore, I propose that `decimal.Decimal` should be treated similarly to these special types. This can be achieved by adding a `DECIMAL_CONSTRAINTS` entry in the [_known_annotated_metadata.py](https://github.com/pydantic/pydantic/blob/b51e0aa5f8ed8a5f3b9471b7ef3a1915ba8ede71/pydantic/_internal/_known_annotated_metadata.py) file to allow automatic constraint mapping for the optional `decimal.Decimal` type.

I am interested in hearing your thoughts on this proposal and would be willing to submit a PR if this change is acceptable.

### Example Code

```Python
from decimal import Decimal
from typing import Annotated

from pydantic import RootModel, Field

RootModel[Annotated[Decimal | None, Field(max_digits=2)]]
# ValueError: Unknown constraint max_digits
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/XXX/miniconda3/envs/py311/lib/python3.11/site-packages/pydantic
               python version: 3.11.5 (main, Sep 11 2023, 08:19:27) [Clang 14.0.6 ]
                     platform: macOS-10.16-x86_64-i386-64bit
             related packages: fastapi-0.105.0 typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@lazyhope,

Feel free to submit a PR, I'd be happy to review. Thanks for outlining the issue so clearly + citing other relevant discussions from the past.

**Comment by lazyhope** [comment]
> @lazyhope,
> 
> Feel free to submit a PR, I'd be happy to review. Thanks for outlining the issue so clearly + citing other relevant discussions from the past.

You're welcome! PR created at #9754, please feel free to review!
