### ISSUE TITLE
BaseSettings seems failing

### ISSUE THREAD

**Issue by cute149q** [pydantic/pydantic#9756]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

When i create an instance for a BaseSetting class. it seems the value in the instance is always getting the value from env file.

### Example Code

```Python
class Environment(BaseSettings):
    table_name: str = Field(..., validation_alias="TABLE_NAME")

env = Environment(table_name="table")

print(env)
Expected: Enviroment{"table_name": "table"}

# However, if there is a env file, it will print the value in env file.
# If there is not an env file, it will raise  Field required Error.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=true
               python version: 3.11.4 (main, Jun 20 2023, 17:37:48) [Clang 14.0.0 (clang-1400.0.29.202)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: mypy-1.10.1 pydantic-settings-2.3.4 typing_extensions-4.12.2
```

**Comment by sydney-runkle** [comment]
Hi @cute149q,

Thanks for your question - this is the expected behavior. Going to close this, accordingly. `pydantic-settings` really just focuses on extracting data from environments / other settings sources. If you'd like pass data directly to a model, you should just use `BaseModel` from `pydantic`.

@hramezani is our local `pydantic-settings` expert - if you have any follow up questions, he is super helpful!

**Comment by Q-back** [comment]
I face the same issue. I try to override my `.env` file by initialising settings class with name argument according to [the pydantic docs](https://docs.pydantic.dev/latest/concepts/pydantic_settings/#field-value-priority)
```python
env = Environment(table_name="OVERRIDEN_TABLENAME")
```
But the `.env` file seems to have priority over the named argument `table_name` in contrary to the documentation.

Currently documentation states:
> Field value priority
In the case where a value is specified for the same Settings field in multiple ways, the selected value is determined as follows (in descending order of priority):
- If cli_parse_args is enabled, arguments passed in at the CLI.
- Arguments passed to the Settings class initialiser.
- Environment variables, e.g. my_prefix_special_function as described above.
- Variables loaded from a dotenv (.env) file.
- Variables loaded from the secrets directory.
- The default field values for the Settings model.

But the `Arguments passed to the Settings class initialiser` are not respected if `.env` is there.

**Comment by Q-back** [comment]
@sydney-runkle Should I create new issue or can we re-open this one?

**Comment by hramezani** [comment]
@Q-back  please create a new issue in https://github.com/pydantic/pydantic-settings
