### ISSUE TITLE
Suggestion: Add DefaultFactory.

### ISSUE THREAD

**Issue by yassun7010** [pydantic/pydantic#9769]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I propose `DefaultFactory` that can be assigned and given to default_factory.

Taking the following example. In this case, only when using default_factory,
Annotated cannot be used, and Field must be assigned.

```python
# Model Definition
class Item(BaseModel):
    id: Annotated[int, Field(title="Item ID")]
    label: Annotated[str | None, Field(title="Item Label") = None
    created_at: datetime.datetime = Field(title="Item Created At", default_factory=datetime.datetime.now)

# Ok: Static Analysis Success.
item = Item(id=1)
```

The reason why `Annotated` cannot be used when using `default_factory` is to avoid specifying a field with `default_factory` when initializing in the constructor.

I know that Pydantic clones the default value of `BaseMode` fields.
Also, I know that the introduction was postponed because the DefaultFactory was temporarily proposed and was not the subject of the [PR](https://github.com/pydantic/pydantic/pull/2176).

I like the notation using Annotated, but when using default_factory, I am in a situation where I cannot use it consistently.

My suggestion:

```python
# Model Definition
class Item(BaseModel):
    id: Annotated[int, Field(title="Item ID")]
    label: Annotated[str | None, Field(title="Item Label") = None
    created_at: Annotated[datetime.datetime, Field(title="Item Created At")] = DefaultFactory(datetime.datetime.now)

# Ok: Static Analysis Success.
item = Item(id=1)
```

### My Environment

Python: 3.12
Pydantic: 2.7.4
Pyright: 1.1.369

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @yassun7010,

Perhaps I'm misunderstanding your question - why does the following not suit your needs?

```py
import datetime
from typing import Annotated, Optional

from pydantic import BaseModel, Field

# Model Definition
class Item(BaseModel):
    id: Annotated[int, Field(title="Item ID")]
    label: Annotated[str | None, Field(title="Item Label")] = None
    created_at: Annotated[datetime.datetime | None, Field(title="Item Created At", default_factory=datetime.datetime.now)] = None

# Ok: Static Analysis Success.
item = Item(id=1)
```

**Comment by yassun7010** [comment]
@sydney-runkle 

Thanks for the response.

Yes. I could not find an existing way to dictate **required** and **default**, and made a suggestion.

If you have a good solution, I hope you will share it here m(_ _)m

**Comment by sydney-runkle** [comment]
Just to clarify - when you specify the `default_factory`, it's inferred that the field is not required. But I understand that it would be nicer to use the annotated syntax without a type checking issue.

In the meantime, you can use the approach I suggested above.

**Comment by yassun7010** [comment]
> but you prefer using Annotated consistently right? (I have to say I prefer using Annotated over = ... too)

Yes. I currently have a solution that does not use `Annotated`, but I prefer the Annotated writing style.

> So I don't think special-casing DefaultFactory is a good idea, as we would possibly get the same requests for a Default, Alias, Repr, Init, etc.

As far as I know, `DefaultFactory` is special.
For example, when targeting `Alias`, we can use Annotated with or without it.

```python
name: Annotated[str, Field(alias="NAME")]
name: Annotated[str, Alias("NAME")]
```

`Default` is also unnecessary. Because it can be specified by assignment (and it is properly cloned). 

```python
name: Annotated[str | None] = None
```

Pydantic seems to be promoting `Annotated`, but only in cases where `default_factory` only is not available.

**Comment by Viicos** [comment]
Imo seems best for now to have it defined in user code, considering it is a two-line function, but I don't have strong opinions on this

**Comment by yassun7010** [comment]
I see.

I would prefer to have this content in the main repository and documentation, but I will leave it to the development team to decide.

I will write this once in my code.

**Comment by sydney-runkle** [comment]
> Imo seems best for now to have it defined in user code

I agree with @Viicos here, let's stick with having this in user code for now. Going to close this as not planned.

If this idea gets lots of traction / support from the community, we can certainly consider reopening + adding something like `DefaultFactory` as a permanent fixture of `pydantic`
