### ISSUE TITLE
2.8.0 unexpectedly change `create_model()`arg `__model_name` to `model_name`

### ISSUE THREAD

**Issue by mudravrik** [pydantic/pydantic#9810]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hi!

Not sure if it is a bug or an intended change, but I could not find a mention of it in the release notes, so I'm reporting it anyway.

So essentially, we have some dynamic model generation running, looking like this:
```
def inject_default_from_instance(instance_w_defaults: BaseModel) -> Type[BaseModel]:
    model_w_defaults = create_model(
        __model_name=instance_w_defaults.__repr_name__() + "WithDefaults",
        __base__=type(instance_w_defaults),
        **{
            k: (
                instance_w_defaults.model_fields[k].annotation,
                FieldInfo.merge_field_infos(
                    instance_w_defaults.model_fields[k],
                    default=getattr(instance_w_defaults, k)
                )
            )
            for k in instance_w_defaults.model_fields.keys()
        }
    )
    return model_w_defaults
```

It's a bit hacky and is used to overcome limitations in a different framework, so it may not be the best example of pydantic usage.

Also (our bad, yeah) we have pydantic version set up as "pydantic>=2,<3", so today one of the pipelines picked up the new 2.8.0 version and failed during the test with
TypeError: create_model() missing 1 required positional argument: 'model_name'
from the above-mentioned snippet.

After some digging, I found a [change](https://github.com/pydantic/pydantic/pull/9479/files#diff-8708af8d26c26644976866f974e0b810b0940ede43ff487e457057d5a1f07999L1446) causing an error in the snippet. Looking at the description, I'm not perfectly sure if the change of the argument name was intended or not.
Probably, if the change is intended, it should be mentioned in the release notes, since it is technically a compatibility change of the public API.

Right now I'll fix the pydantic version more strictly to 2.7, but still would like to know if the change is intended, so I should change the create_model() call accordingly.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.0
pydantic-core version: 2.20.0
pydantic-core build: profile=release pgo=true
install path: /path/to/project/.venv/lib/python3.11/site-packages/pydantic
python version: 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)]
platform: macOS-14.5-arm64-arm-64bit
related packages: typing_extensions-4.10.0
commit: unknown
```

**Comment by mudravrik** [comment]
After some reading on topic I got to this [part](https://peps.python.org/pep-0570/#using-as-a-per-argument-marker) of PEP-570 explaining, that `__model_name` is a naming convetion meaning, that it is positional-only argument and should not be used with key at the first place.

So I assume, the whole problem can be addressed to our code which did call the function with this argument keyworded.

**Comment by sydney-runkle** [comment]
@mudravrik,

> After some reading on topic I got to this [part](https://peps.python.org/pep-0570/#using-as-a-per-argument-marker) of PEP-570 explaining, that __model_name is a naming convetion meaning, that it is positional-only argument and should not be used with key at the first place.

Indeed! Going to mark this as resolved, accordingly!
