### ISSUE TITLE
custom error details with a special exception

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#982]
# Feature Request

Based on #981

Customising `loc`  is definitely something I've wanted in the past, there are a number of situations where it might be useful but root validators is the most common.

I imagine the most sensible approach would be custom exceptions which let you customise `loc` as well as `msg`, `ctx` and `type`.

I don't think we need to maintain the distinction between `TypeError`, `ValueError` and `AssertionError`. Instead we'd have something like

```py
class PydanticError(Exception):
    def __init__(self, msg, ctx=None, loc=None, type='custom_error'):
        ...
```

**Comment by adriangb** [comment]
We are going to support this in V2: https://github.com/pydantic/pydantic/issues/734#issuecomment-1522182814

The API needs some love, we'll make it better before the final release.
