### ISSUE TITLE
Save models to the class

### ISSUE THREAD

**Issue by R5dan** [pydantic/pydantic#9820]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [x] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

All models are automatically (or manually) saved to the class like sql alchemy. This would let you simply import the model from another file or not have to save each instance of the model individually.

```python
import pydantic as p

class Foo(p.BaseModel):
    x:int
    y:str

Foo(x=3,y="bar").save()

print(Foo.filter_by(x=3,y="abc")[0])
"""
x=3, y="abc"
"""
```

This could also help plugins like FastAPI as it could then except GET requests

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [X] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
Hi @R5dan,

Thanks for your inquiry. This strikes me as something that belongs in user code, as you can easily extend your `BaseModel` subclasses with custom functionality.

Here's an example for your use case:

```py
from __future__ import annotations

import pydantic as p
from typing import ClassVar


class Foo(p.BaseModel):
    instances: ClassVar[list[Foo]] = []

    x: int
    y: str

    def save(self):
        self.instances.append(self)

    @classmethod
    def filter_by(cls, **kwargs):
        return [i for i in cls.instances if all(getattr(i, k) == v for k, v in kwargs.items())]


Foo(x=1, y='foo').save()
Foo(x=3, y='bar').save()
Foo(x=3, y='abc').save()

print(repr(Foo.filter_by(x=3)[1]))
"""
Foo(x=3, y='abc')
"""
```
