### ISSUE TITLE
model_fields is "not a field" when using @dataclass(slots=True)

### ISSUE THREAD

**Issue by senese** [pydantic/pydantic#9823]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I was testing the `slots` feature of `pydantic.dataclasses.dataclass` and stumble upon this error:

```
Traceback (most recent call last):
  File "/home/diego/test.py", line 5, in <module>
    @dataclass(slots=True)
     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/diego/python3.12/site-packages/pydantic/dataclasses.py", line 225, in create_dataclass
    cls = dataclasses.dataclass(  # type: ignore[call-overload]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1268, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1258, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1148, in _process_class
    cls = _add_slots(cls, frozen, weakref_slot)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dataclasses.py", line 1226, in _add_slots
    cls = type(cls)(cls.__name__, cls.__bases__, cls_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diego/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 93, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/home/diego/venv/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 406, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `model_fields = {'test': FieldInfo(annotation=str, required=True)}`. All model fields require a type annotation; if `model_fields` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
```

As the documentation says: 
> Keep in mind that pydantic.dataclasses.dataclass is not a replacement for pydantic.BaseModel.

So my thought is that I can work with dataclass decorator together with BaseModel heritage but Pydantic keeps throwing me this error like `models_fields` was a field that is not meant to be a field. I don't event know if that makes sense.

I also try to add `model_config = ConfigDict(extra='forbid')` or even @dataclass(slots=True, config=ConfigDict(extra='forbid') and both outputs the same error.

I don't know if this behavior is intended - and also don't know if dataclass and BaseModel should work together - but if it is intended, its not clear in the docs.

### Example Code

```Python
from pydantic.dataclasses import dataclass
from pydantic import BaseModel


@dataclass(slots=True)
class TestClass(BaseModel):
    test: str
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.1
        pydantic-core version: 2.18.2
          pydantic-core build: profile=release pgo=true
                 install path: /home/diego/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.3 (main, May  6 2024, 23:14:22) [GCC 11.3.0]
                     platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @senese,

Using v2.8.0, you get a more helpful error:

```py
from pydantic.dataclasses import dataclass
from pydantic import BaseModel


@dataclass(slots=True)
class TestClass(BaseModel):
    test: str

"""
pydantic.errors.PydanticUserError: Cannot create a Pydantic dataclass from TestClass as it is already a Pydantic model
"""
```

Marking this as resolved - mixing pydantic dataclasses and models in this way isn't supported.

**Comment by senese** [comment]
Thank you, @sydney-runkle. Althought this raised me a couple of doubts:

1.  You said "in this way". Do you have any example where mixing pydantic dataclasses and BaseModels is a good use case? The documentation is not very clear on this subject.
2. With BaseModels is there some way I can use dataclasses's `slots` feature?

**Comment by sydney-runkle** [comment]
> You said "in this way". Do you have any example where mixing pydantic dataclasses and BaseModels is a good use case? The documentation is not very clear on this subject.

To clarify - we don't support both decorating a class as a dataclass and inheriting from `BaseModel` . It should be the case that one or the other meets your needs, with `BaseModel` having more robust settings / configuration.

> With BaseModels is there some way I can use dataclasses's slots feature?

You can just define `__slots__` on your subclass of `BaseModel`, but you might have to include these values as well:

https://github.com/pydantic/pydantic/blob/b3ce47f38a906d0b957e0870a651da394b8461bc/pydantic/main.py#L177C5-L177C100
