### ISSUE TITLE
Optional value with Annotated Form defaulting to None

### ISSUE THREAD

**Issue by mhkamal1** [pydantic/pydantic#9835]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am calling the FastAPI endpoint below. 
The issue is, uploadedCV is defaulting to None even though the key is present in the form. 
<img width="759" alt="Screenshot 2024-07-03 at 9 36 24 PM" src="https://github.com/pydantic/pydantic/assets/124262740/88a0a396-2a08-4df3-9020-ed4b1dbafba4">
<img width="607" alt="Screenshot 2024-07-03 at 9 37 44 PM" src="https://github.com/pydantic/pydantic/assets/124262740/c4dce537-b89a-4a59-8b52-1a8ffdf9e369">

I have tested through my frontend and also through postman.

### Example Code

```Python
@router.post("/search/")
def create_search(
    user_id: Annotated[str, Form()],
    uploadedCV: Optional[Annotated[str, Form()]] = None 
    ):
    pass
```
```


### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.4
        pydantic-core version: 2.18.4
          pydantic-core build: profile=release pgo=false
                 install path: /Users/kamal/miniconda3/envs/jobhunt/lib/python3.8/site-packages/pydantic
               python version: 3.8.19 (default, Mar 20 2024, 15:27:52)  [Clang 14.0.6 ]
                     platform: macOS-14.4.1-arm64-arm-64bit
             related packages: fastapi-0.111.0 pydantic-settings-2.3.3 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi,

Could you please provide a minimal reproduction of this issue? Closing for now, as we're not able to repro this issue. Happy to help if you can provide more info!

**Comment by mhkamal1** [comment]
Had to specify it as ```Form(None``` then it works. 
Reference: https://github.com/tiangolo/fastapi/issues/854#issuecomment-573965912
