### ISSUE TITLE
Support array length specification in model_json_schema

### ISSUE THREAD

**Issue by PaulRudin** [pydantic/pydantic#9849]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

Using a model like:
```
from pydantic import BaseModel, conlist
class X(BaseModel):
     y: list[int] = conlist(int, min_length=3, max_length=3)
```
gives:

```
In [53]: X.model_json_schema()
/home/paul/repos/docs/api-docs/venv/lib/python3.12/site-packages/pydantic/json_schema.py:2158: PydanticJsonSchemaWarning: Default value typing.Annotated[typing.List[int], Len(min_length=3, max_length=3)] is not JSON serializable; excluding default from JSON schema [non-serializable-default]
  warnings.warn(message, PydanticJsonSchemaWarning)
Out[53]: 
{'properties': {'y': {'items': {'type': 'integer'},
   'title': 'Y',
   'type': 'array'}},
 'title': 'X',
 'type': 'object'}
```
But json schema allow array length constraints, so it would be great if they were supported by `model_json_schema()`

https://json-schema.org/understanding-json-schema/reference/array#length
### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by Viicos** [comment]
`conlist` is meant to be used as an annotation:

```python
from pydantic import BaseModel, conlist

class X(BaseModel):
     y: conlist(int, min_length=3, max_length=3)
```

However, it is discouraged to use the `con*` functions as they doesn't play well with type checkers. Instead consider using:

```python
from typing import Annotated

from annotated_types import Len
from pydantic import BaseModel

class X(BaseModel):
     y: Annotated[list[int]], Len(min_length=3, max_length=3)]
```
