### ISSUE TITLE
Incorporate annotated-types Unit into model_json_schema

### ISSUE THREAD

**Issue by ollyhensby** [pydantic/pydantic#9855]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When using the Unit from the annotated-types package, it would be great if the `unit` appeared in the `model_json_schema`.

For example:

```python
from annotated_types import Unit
from pydantic import BaseModel

Meters = Annotated[float, Unit("m")]

class Test(BaseModel):
    meter: Meters

Test.model_json_schema()
```

`model_json_schema` returns:

```json
{
  "properties": {
    "meter": {
      "title": "Meter",
      "type": "number"
    }
  },
  "required": [
    "meter"
  ],
  "title": "Test",
  "type": "object"
}
```

It would be cool if the `meter` property included the unit in the json schema. Following the example above, it would include `"unit": "m"`:

```json
{
  "properties": {
    "meter": {
      "title": "Meter",
      "type": "number",
      "unit": "m"
    }
  },
  "required": [
    "meter"
  ],
  "title": "Test",
  "type": "object"
}
```

Maybe this could be done by adding it to the `json_schema_extra` field of the pydantic model?

Cheers!

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@ollyhensby,

I think we should add direct support for this type, like we do for other annotated types :).

**Comment by aditkumar72** [comment]
@sydney-runkle Could you please assign this to me ?

**Comment by aditkumar72** [comment]
Hi @sydney-runkle 
I was investigating the solution for this issue. 

If we add:

`
elif isinstance(annotation, at.Unit):
            schema['unit'] = getattr(annotation, 'unit')
`

in _known_annotated_metadata.py

we are getting error:

`
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.schema.model-fields.fields.distance.schema.float.unit
  Extra inputs are not permitted [type=extra_forbidden, input_value='m', input_type=str]
    For further information visit
https://errors.pydantic.dev/2.10/v/extra_forbidden
`

Does this mean, we need changes in pydantic core as well or we are not doing the correct changes, could please help me understand this ?

**Comment by sydney-runkle** [comment]
Sure thing - this is tricker than I expected. The difficulty here is, you're expecting annotated metadata to apply to JSON schema, whereas most annotations apply to core schema.

I think the best route forward here would be to use `json_schema_extra` with your desired unit, as we've already got the infrastructure to support that at the moment:

```py
from pydantic import BaseModel, Field
from typing import Annotated

Meters = Annotated[float, Field(json_schema_extra={'unit': 'm'})]


class Test(BaseModel):
    meter: Meters


print(Test.model_json_schema())
#> {'properties': {'meter': {'title': 'Meter', 'type': 'number', 'unit': 'm'}}, 'required': ['meter'], 'title': 'Test', 'type': 'object'}
```

Going to close this as not planned for now. Happy to reconsider in the future if there's high demand for this.
