### ISSUE TITLE
Unwanted type constraint on generic model inheritance

### ISSUE THREAD

**Issue by azmeuk** [pydantic/pydantic#9858]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I am not sure if this is a wanted behavior or not. If it is, please excuse my noise.

I encountered a situation when two models `Foo` and `Bar` inherit from a same generic `Root` model, `Foo` has a type parameter and `Bar` don't, and `Foo` has a `Bar` attribute, then a `ValidationError` is raised. The following snippet produce this exception:

```python
pydantic_core._pydantic_core.ValidationError: 1 validation error for Foo[str]
bar
  Input should be a valid dictionary or instance of Bar[str] [type=model_type, input_value=Bar(), input_type=Bar]
    For further information visit https://errors.pydantic.dev/2.8/v/model_type
```

I would expect this code to pass, as `Foo.bar` is required to be `Bar` and not explicitly `Bar[str]`.

Note that this is a simplification of a real-world use case I met, where models may or may not have a type parameter, but there is no business logic for the different model type parameters to be the same.

What do you think?

### Example Code

```Python
from typing import Generic, Optional, TypeVar
from pydantic import BaseModel

T = TypeVar("T")


class Root(BaseModel, Generic[T]):
    pass


class Bar(Root):
    pass


class Foo(Root):
    bar: Bar


Foo[str].model_validate({"bar": Bar()})
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/eloi/.cache/pypoetry/virtualenvs/scim2-models-0KAbTKSX-py3.12/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522]
                     platform: Linux-6.9.7-arch1-1-x86_64-with-glibc2.39
             related packages: typing_extensions-4.12.2 pydantic-settings-2.3.4
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@azmeuk,

This is right - you have to explicitly parametrize `Bar` with `Bar[str]` in order for validation to pass here.
