### ISSUE TITLE
__get_attr__ can't access some properties when __pydantic_extra__ is populated

### ISSUE THREAD

**Issue by jmassucco17** [pydantic/pydantic#9862]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Due to the ordering of __get_attr__, it will sometimes miss class attributes when __pydantic_extra__ is populated. 

I changed https://github.com/pydantic/pydantic/blame/d654a0766c2f3c6fe0a12718f32aa3bf4d3ecc86/pydantic/main.py#L818 from `if pydantic_extra` to `if pydantic_extra and item in pydantic_extra` locally and it resolved my issue.

My repro case is pretty complex, but I'll work on a simple reproduction code example.

### Python, Pydantic & OS Version

```Text
pydantic version: 2.7.0
        pydantic-core version: 2.18.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/jmassucco/devel/monorepo/dist/export/python/virtualenvs/python-default/3.8.16/lib/python3.8/site-packages/pydantic
               python version: 3.8.16 (default, Jun  5 2024, 17:31:41)  [GCC 9.4.0]
                     platform: Linux-5.4.0-187-generic-x86_64-with-glibc2.2.5
             related packages: fastapi-0.110.1 pydantic-settings-2.2.1 typing_extensions-4.11.0 mypy-1.9.0 pydantic-extra-types-2.6.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@jmassucco17,

Good find - feel free to open a PR with said fix + a unit test. I'd be happy to review!

**Comment by jmassucco17** [comment]
Thanks @sydney-runkle ! This got lost, but I just ran into this bug again so I put up the fix: https://github.com/pydantic/pydantic/pull/10810

I had some trouble setting up the dev environment on my local machine per https://docs.pydantic.dev/latest/contributing/ so was unable to test locally, but the changes are very simple and hopefully CI will show they are a good fix. Appreciate your review and feedback when you have a chance!

**Comment by jmassucco17** [comment]
Closing this out in favor of #10821
