### ISSUE TITLE
Ability to override __getattr__

### ISSUE THREAD

**Issue by mtvx** [pydantic/pydantic#9873]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

```py
class Foo(BaseModel):
    field: str = "default"

    def __getitem__(self, item):
        print("getitem")

    def __getattr__(self, item):
        print("getattr")

    def __setattr__(self, item, value):
        print("setattr")
        super().__setattr__(item, value)

f = Foo()
f["field"]   # prints "getitem"
f.field = 2  # prints "setattr"
f.field      # no output?
```

I could add `RootModel` (or some custom wrapper) but then I'd lose typing capability (accesing `model.field` where `field` would be proxied to `model.root.field` but wouldn't exist as explicit type).

What's the way to override `__getattr__` in Pydantic V2? All the references I found suggest this worked in V1, but how about V2 then?

(Asking for https://github.com/pydantic/pydantic/discussions/9846, if anyone's curious.)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [X] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by tuukkamustonen** [comment]
So, `__getattribute__` actually works. I'm super duper sure I tried also that before, but uh, I guess I did something wrong back then.

So, this ticket can be closed.

**Comment by mtvx** [comment]
So, `__getattribute__` actually works. I'm sure I tried also that before, but uh, I guess I did something wrong back then.
