### ISSUE TITLE
Accept and handle AsyncIterators to facilitate streaming

### ISSUE THREAD

**Issue by rafalkrupinski** [pydantic/pydantic#9874]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

When validating json using pydantic like so:
```python
stream:  AsyncIterator[bytes]
model_iter: AsyncIterator[MyModel] = TypeAdapter(AsyncIterator[MyModel]).validate_json(stream)
```
I'd like Pydantic to return a `AsyncGenerator`.
Iterating over the returned generator should yield an instance of MyModel as soon as the stream provided at least enough data for a single item of the enclosing array.

This would potentially speed up processing responses received over a network, by allowing to process the data, while the event loop waits for the next chunk, for example with chunked encoding in HTTP

This has nothing to do with infinite generators, and would only apply to the data that's iterable at the top-level (since you couldn't return a model instance until you've read the entire document). 

Analogously, when using `dump_json()`
```python
data: AsyncIterator[MyModel]
stream: AsyncIterator[bytes] = TypeAdapter(AsyncIterator[MyModel]).dump_json(stream)
```

Conversely, handling AsyncIterator fields would be problematic, since Pydantic would need to consume the iterator field and leave the input object unusable.
EDIT: Actually models are often constructed for the sole purpose of sending them as JSON, so it might be useful.

PS. Probably should use new methods `adump_json` and `avalidate_json` instead.

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
While I do think lazier validation and serialization are in the works, I don't think we'll necessarily want to use this exact API.

I'll chat with the team about this proposal and get back to you after that.

**Comment by rafalkrupinski** [comment]
Thanks!
I'm not attached to this particular API

**Comment by adriangb** [comment]
This is a valuable and legitimate feature request, but it would require rewriting _a lot_ of Pydantic, in particular `pydantic-core`.

The current story for interop between async Python and async Rust is quite poor. Things are improving but I expect it will take a couple _years_ for things to settle properly, and even then we don't know if the interop will be good enough to make sense for this sort of implementation.

Because we won't be implementing this any time soon I'm going to close this as a wontfix 😞.
