### ISSUE TITLE
ValueError: Value not declarable with JSON Schema, field: name='params'

### ISSUE THREAD

**Issue by rushant001** [pydantic/pydantic#9886]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

pydantic version is 
bump-pydantic==0.8.0
openapi-schema-pydantic==1.2.4
pydantic==2.8.2
pydantic_core==2.20.1

code:

from pydantic import BaseModel, Field

class DetectBranchMergeInput(BaseModel):
    """
    检测分支合入主干的输入参数
    """
    repo_name: str = Field(..., description="代码库名称，格式是使用'/'分割的3段式，其他格式都是非法的", examples=["baidu/nlpqa/baidu-ai-platform"])
    group_id: int = Field(..., description="群组ID", examples=[1089976])
    sender: str = Field(..., description="发送者ID", examples=["renziyu01"])
    target_branch: str = Field(..., description="主分支名称", examples=["20240710"])
    main_branch: Optional[str] = Field('master', description="主分支名称", examples=["master"])
    version: Optional[str] = Field('', description="主分上发布的4位版本号", examples=["1.2.3.2"])

class DetectBranchMergeOutput(BaseModel):
    """
     检测分支合入主干的输出参数
    """
    success: bool

@tool
def detect_branch_merge(params: DetectBranchMergeInput) -> DetectBranchMergeOutput:
    """
    检测代码库中开发分支代码合入主干分支情况
    :param params: DetectBranchMergeInput对象，包含所需的输入参数
    :return: DetectBranchMergeOutput对象，包含成功与否的布尔值
    """
    branch_detect = BranchDetector(
        params.repo_name,
        params.main_branch,
        params.target_branch,
        params.group_id,
        params.sender,
        version=params.version
    )
    check_ok, check_msg_list = branch_detect.run()
    return DetectBranchMergeOutput(success=check_ok)

error info:

  File "/Users/xxx/D/mycode/baidu/nlp-qa/tools-factory/app/router/detector_api.py", line 66, in <module>
    def detect_branch_merge(params: DetectBranchMergeInput) -> DetectBranchMergeOutput:
  File "/usr/local/lib/python3.10/site-packages/langchain_core/tools.py", line 1173, in tool
    return _make_with_name(args[0].__name__)(args[0])
  File "/usr/local/lib/python3.10/site-packages/langchain_core/tools.py", line 1134, in _make_tool
    return StructuredTool.from_function(
  File "/usr/local/lib/python3.10/site-packages/langchain_core/tools.py", line 959, in from_function
    _args_schema = create_schema_from_function(
  File "/usr/local/lib/python3.10/site-packages/langchain_core/tools.py", line 291, in create_schema_from_function
    valid_properties = _get_filtered_args(inferred_model, func, filter_args=filter_args)
  File "/usr/local/lib/python3.10/site-packages/langchain_core/tools.py", line 149, in _get_filtered_args
    schema = inferred_model.schema()["properties"]
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 664, in schema
    s = model_schema(cls, by_alias=by_alias, ref_template=ref_template)
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/schema.py", line 188, in model_schema
    m_schema, m_definitions, nested_models = model_process_schema(
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/schema.py", line 581, in model_process_schema
    m_schema, m_definitions, nested_models = model_type_schema(
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/schema.py", line 622, in model_type_schema
    f_schema, f_definitions, f_nested_models = field_schema(
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/schema.py", line 255, in field_schema
    f_schema, f_definitions, f_nested_models = field_type_schema(
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/schema.py", line 527, in field_type_schema
    f_schema, f_definitions, f_nested_models = field_singleton_schema(
  File "/usr/local/lib/python3.10/site-packages/pydantic/v1/schema.py", line 951, in field_singleton_schema
    raise ValueError(f'Value not declarable with JSON Schema, field: {field}')
ValueError: Value not declarable with JSON Schema, field: name='params' type=DetectBranchMergeInput required=True

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=false
                 install path: /usr/local/lib/python3.10/site-packages/pydantic
               python version: 3.10.6 (main, Aug 30 2022, 05:12:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
                     platform: macOS-12.6-x86_64-i386-64bit
             related packages: fastapi-0.110.0 typing_extensions-4.12.2
                       commit: unknown
```

**Comment by Viicos** [comment]
Could you please provide a readable and formatted example?

**Comment by rushant001** [comment]
> Could you please provide a readable and formatted example?

`from typing import Optional, List
from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain_core.utils.function_calling import convert_to_openai_tool
from langchain_openai import ChatOpenAI
router = APIRouter(tags=['detector_chain'])


class DetectBranchMergeInput(BaseModel):
    """
    检测分支合入主干的输入参数
    """
    repo_name: str = Field(..., description="代码库名称，格式是使用'/'分割的3段式，其他格式都是非法的", examples=["baidu/nlpqa/baidu-ai-platform"])
    target_branch: str = Field(..., description="代码库开发分支名称", examples=["20240710"])
    main_branch: Optional[str] = Field('master', description="代码库主干分支名称", examples=["master"])
    version: Optional[str] = Field('', description="分支上4位数字组成的版本号", examples=["1.2.3.2"])

class DetectBranchMergeOutput(BaseModel):
    """
     检测分支合入主干的输出参数
    """
    success: bool = Field(..., description="检测结果通过或者不通过", examples=[True, False])
    msg: List[str] = Field([], description="检测汇总信息")

@tool
def detect_branch_merge(params: DetectBranchMergeInput) -> DetectBranchMergeOutput:
    """
    检测代码库中开发分支代码合入主干分支情况
    :param params: DetectBranchMergeInput对象，包含所需的输入参数
    :return: DetectBranchMergeOutput对象，包含成功与否的布尔值，检测信息
    """
    return DetectBranchMergeOutput(success=True, msg=[])


tool_maps = {"detect_branch_merge": detect_branch_merge}
tools = list(tool_maps.values())
#   /usr/local/lib/python3.10/site-packages/langchain_core/utils/utils.py:161: UserWarning: WARNING! proxy is not default parameter.
#                 proxy was transferred to model_kwargs.
#                 Please confirm that proxy is what you intended.
#   Client.__init__() got an unexpected keyword argument 'proxy' (type=type_error)
llm = ChatOpenAI(model="gpt-4o")
llm_with_tools = llm.bind_tools(tools)
res = convert_to_openai_tool(detect_branch_merge)
`

**Comment by rushant001** [comment]
> Could you please provide a readable and formatted example?

`from typing import Optional, List
from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain_core.utils.function_calling import convert_to_openai_tool
from langchain_openai import ChatOpenAI
router = APIRouter(tags=['detector_chain'])


class DetectBranchMergeInput(BaseModel):
    """
    检测分支合入主干的输入参数
    """
    repo_name: str = Field(..., description="代码库名称，格式是使用'/'分割的3段式，其他格式都是非法的", examples=["baidu/nlpqa/baidu-ai-platform"])
    target_branch: str = Field(..., description="代码库开发分支名称", examples=["20240710"])
    main_branch: Optional[str] = Field('master', description="代码库主干分支名称", examples=["master"])
    version: Optional[str] = Field('', description="分支上4位数字组成的版本号", examples=["1.2.3.2"])

class DetectBranchMergeOutput(BaseModel):
    """
     检测分支合入主干的输出参数
    """
    success: bool = Field(..., description="检测结果通过或者不通过", examples=[True, False])
    msg: List[str] = Field([], description="检测汇总信息")

@tool
def detect_branch_merge(params: DetectBranchMergeInput) -> DetectBranchMergeOutput:
    """
    检测代码库中开发分支代码合入主干分支情况
    :param params: DetectBranchMergeInput对象，包含所需的输入参数
    :return: DetectBranchMergeOutput对象，包含成功与否的布尔值，检测信息
    """
    return DetectBranchMergeOutput(success=True, msg=[])


tool_maps = {"detect_branch_merge": detect_branch_merge}
tools = list(tool_maps.values())
llm = ChatOpenAI(model="gpt-4o")
llm_with_tools = llm.bind_tools(tools)
res = convert_to_openai_tool(detect_branch_merge)`

**Comment by rushant001** [comment]
> Could you please provide a readable and formatted example?

`
from typing import Optional, List
from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain_core.utils.function_calling import convert_to_openai_tool
from langchain_openai import ChatOpenAI
router = APIRouter(tags=['detector_chain'])


class DetectBranchMergeInput(BaseModel):
    """
    检测分支合入主干的输入参数
    """
    repo_name: str = Field(..., description="代码库名称，格式是使用'/'分割的3段式，其他格式都是非法的", examples=["baidu/nlpqa/baidu-ai-platform"])
    target_branch: str = Field(..., description="代码库开发分支名称", examples=["20240710"])
    main_branch: Optional[str] = Field('master', description="代码库主干分支名称", examples=["master"])
    version: Optional[str] = Field('', description="分支上4位数字组成的版本号", examples=["1.2.3.2"])

class DetectBranchMergeOutput(BaseModel):
    """
     检测分支合入主干的输出参数
    """
    success: bool = Field(..., description="检测结果通过或者不通过", examples=[True, False])
    msg: List[str] = Field([], description="检测汇总信息")

@tool
def detect_branch_merge(params: DetectBranchMergeInput) -> DetectBranchMergeOutput:
    """
    检测代码库中开发分支代码合入主干分支情况
    :param params: DetectBranchMergeInput对象，包含所需的输入参数
    :return: DetectBranchMergeOutput对象，包含成功与否的布尔值，检测信息
    """
    return DetectBranchMergeOutput(success=True, msg=[])


tool_maps = {"detect_branch_merge": detect_branch_merge}
tools = list(tool_maps.values())
llm = ChatOpenAI(model="gpt-4o")
llm_with_tools = llm.bind_tools(tools)
res = convert_to_openai_tool(detect_branch_merge)
`

**Comment by rushant001** [comment]
> Could you please provide a readable and formatted example?

```
from typing import Optional, List
from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain_core.utils.function_calling import convert_to_openai_tool
from langchain_openai import ChatOpenAI
router = APIRouter(tags=['detector_chain'])


class DetectBranchMergeInput(BaseModel):
    """
    检测分支合入主干的输入参数
    """
    repo_name: str = Field(..., description="代码库名称，格式是使用'/'分割的3段式，其他格式都是非法的", examples=["baidu/nlpqa/baidu-ai-platform"])
    target_branch: str = Field(..., description="代码库开发分支名称", examples=["20240710"])
    main_branch: Optional[str] = Field('master', description="代码库主干分支名称", examples=["master"])
    version: Optional[str] = Field('', description="分支上4位数字组成的版本号", examples=["1.2.3.2"])

class DetectBranchMergeOutput(BaseModel):
    """
     检测分支合入主干的输出参数
    """
    success: bool = Field(..., description="检测结果通过或者不通过", examples=[True, False])
    msg: List[str] = Field([], description="检测汇总信息")

@tool
def detect_branch_merge(params: DetectBranchMergeInput) -> DetectBranchMergeOutput:
    """
    检测代码库中开发分支代码合入主干分支情况
    :param params: DetectBranchMergeInput对象，包含所需的输入参数
    :return: DetectBranchMergeOutput对象，包含成功与否的布尔值，检测信息
    """
    return DetectBranchMergeOutput(success=True, msg=[])


tool_maps = {"detect_branch_merge": detect_branch_merge}
tools = list(tool_maps.values())
llm = ChatOpenAI(model="gpt-4o")
llm_with_tools = llm.bind_tools(tools)
res = convert_to_openai_tool(detect_branch_merge)
```

**Comment by rushant001** [comment]
The code runs into an error with langchain-openai-0.1.15 but works fine with langchain-openai-0.0.6.

**Comment by sydney-runkle** [comment]
Hi @rushant001,

Thanks for the report. I think this issue should be opened on the `langchain` repo. Going to close for now.

**Comment by rushant001** [comment]
Update httpcore-1.0.5 httpx-0.27.0 ,the error solved.
