### ISSUE TITLE
Add "dependencies" field to `ComputedFieldInfo`

### ISSUE THREAD

**Issue by tlambert03** [pydantic/pydantic#9893]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

It would be nice to have a way to indicate that a given `computed_field` depends on the presence/values of other fields.  This could be used, for example, to indicate that a given computed (`readOnly`) field is likely to be stale if another field (on which it depends) has changed.  I'm not proposing that pydantic do anything with this info at the moment; just allow model creators to make it available to consumers in `ComputedFieldInfo`. 

This is also related (albeit somewhat indirectly) to the [`dependentRequired` concept in JSON Schema](https://json-schema.org/understanding-json-schema/reference/conditionals#dependentRequired) ... which allows you to specify that the presence of one field requires the presence of another field.

Taking the computed_field example in the docs, I'm proposing:

```python
class Box(BaseModel):
    width: float
    height: float = 1
    depth: float = 2

    @computed_field(dependencies=['width', 'height', 'depth'])
    def volume(self) -> float:
        return self.width * self.height * self.depth
```

in terms of a serialization schema, this would be similar to

```json
{
  "title": "Box",
  "type": "object",
  "properties": {
    "width": { "title": "Width", "type": "number" },
    "height": { "default": 1, "title": "Height", "type": "number" },
    "depth": { "default": 2, "title": "Depth", "type": "number" },
    "volume": { "readOnly": true, "title": "Volume", "type": "number" }
  },
  "required": ["width"],
  "dependentRequired": {
    "volume": ["width", "height", "depth"]
  }
}
```

### Alternative

Currently, if I'd like to know what fields a computed field might depend on, I'm mostly left to very error prone parsing of source code?

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [X] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by nix010** [comment]
hi @tlambert03 
I think for now, you can do it with [json_schema_extra](https://docs.pydantic.dev/latest/concepts/json_schema/#using-json_schema_extra)

```python
from pprint import pprint
from pydantic import computed_field, BaseModel, ConfigDict


class Box(BaseModel):
    width: float
    height: float = 1
    depth: float = 2
    model_config = ConfigDict(json_schema_extra={
        "dependentRequired": {
            "volume": ["width", "height", "depth"]
        }
    })

    @computed_field
    def volume(self) -> float:
        return self.width * self.height * self.depth


pprint(Box.model_json_schema())
"""
{'dependentRequired': {'volume': ['width', 'height', 'depth']},
 'properties': {'depth': {'default': 2, 'title': 'Depth', 'type': 'number'},
                'height': {'default': 1, 'title': 'Height', 'type': 'number'},
                'width': {'title': 'Width', 'type': 'number'}},
 'required': ['width'],
 'title': 'Box',
 'type': 'object'}
"""

```

**Comment by tlambert03** [comment]
Yes that's true... but is really only useful if I am both the creator and consumer of the model.  

I'm looking more for a documented convention/feature.  Something that different developers can use to communicate the design of their model (not something a developer can use to store some data in a place where only they know to look for it)

**Comment by tlambert03** [comment]
In other words: I'm actually a little less concerned about the json schema output (that was an additional explanatory example), and more interested in inspecting a runtime pydantic model created by someone else.

**Comment by nix010** [comment]
@tlambert03 Make sense. How about this?

The creator still need to list the `dependencies` for each `computed_field` so switch to a custom decorator is still an ok overhead. I think!

```python 
from functools import partial
from pprint import pprint
from pydantic import computed_field, BaseModel


def custom_computed_field(dependencies: list = None, **kwargs):
    key = 'dependencies'
    if not kwargs.get('json_schema_extra') and dependencies:
        kwargs['json_schema_extra'] = {key: dependencies}
    return partial(computed_field, **kwargs)


class Box(BaseModel):
    width: float
    height: float = 1
    depth: float = 2

    @custom_computed_field(dependencies=['width', 'height', 'depth'])
    def volume(self) -> float:
        return self.width * self.height * self.depth


pprint(Box.model_computed_fields)

"""
{'volume': ComputedFieldInfo(wrapped_property=<property object at 0x102de02c0>,
                             return_type=<class 'float'>,
                             alias=None,
                             alias_priority=None,
                             title=None,
                             field_title_generator=None,
                             description=None,
                             deprecated=None,
                             examples=None,
                             json_schema_extra={'dependencies': ['width',
                                                                 'height',
                                                                 'depth']},
                             repr=True)}

"""
```

**Comment by tlambert03** [comment]
Yep, that's what I'm doing at the moment :)

**Comment by Viicos** [comment]
Seems like your `dependencies` field is really specific to your use case, so I don't think having a `dependencies` argument to `computed_field` is a good idea (then someone could request a `foo` argument for some other needs, etc). So perhaps a `metadata` generic argument, typed as `dict[str, Any]`. I'll note that this isn't specific to `computed_field`, it could be used for normal fields as well.

**Comment by sydney-runkle** [comment]
I'm generally in support of this idea, for 2 key reasons:

1. I'd really like to stray away from using `metadata` throughout our library - though some might argue it's versatile and flexible, I'd rather implement more developed options with proven use cases. This particularly rubs me the wrong way at the moment because I'm unhappy with how we use `metadata` in our core schema generation.
2. This strikes me as similar (at least motivationally) to https://github.com/pydantic/pydantic/issues/9789 and https://github.com/pydantic/pydantic/issues/8603, which I think there's a lot of demand for.

**Comment by tlambert03** [comment]
I'd be happy to code up a working proof of principle if it would be helpful for the sake of discussion.  Just wanted to start the discussion before opening a PR (as per request 🙂 )

**Comment by sydney-runkle** [comment]
@tlambert03,

Sounds great!

One thing that I could imagine would be beneficial is if this could integrate nicely with type checkers, as I imagine folks willing to specify dependent fields are likely to also use more advanced type checking utilities.

**Comment by tlambert03** [comment]
happy to... but what sort of IDE experience are you envisioning?    Starting with the bare minimum here:

```python
class Square(BaseModel):
    width: float
    height: float

    @custom_computed_field(dependencies=['width', 'height'])
    def area(self) -> float: ...
```

everything is already fully typed, and there's not much to infer.  Should I look closer at #9789 and/or #8603 to see what you're picturing?

**Comment by sydney-runkle** [comment]
Great question. I guess my thought would be that if any of the dependencies are optional and not set during initialization, there would be some way to indicate that the computed field isn't set (or is set to `None`) on the instance as well.

But that might just be up to the developer to implement logically in the computed field definition.

**Comment by sydney-runkle** [comment]
Closing as not planned, see https://github.com/pydantic/pydantic/pull/9912 discussion for reasoning. @tlambert03, thanks for your patience here, and @Viicos, thanks for your input!

**Comment by Viicos** [comment]
I'll also note that a [`metadata`](https://docs.python.org/3/library/dataclasses.html#dataclasses.field) field already exists in stdlib dataclasses, so it might be a good idea to follow the same path.
