### ISSUE TITLE
NamedTuple with Field(title and description) in JSON Schema

### ISSUE THREAD

**Issue by kimwonj77** [pydantic/pydantic#9895]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

I want to annotate a named tuple with a title and description to ensure tuple types are correctly used. It's primarily for JSON schema.
```py
from typing import NamedTuple

from pydantic import BaseModel, Field


class cSection(NamedTuple):
    main: str = Field(title="Main Title", description="Main Title Description")
    description: str = Field(title="Content Description", description="Content Description")

class cTest(BaseModel):
    section: cSection = Field(title="Section", description="Section Description")

print(cTest.model_json_schema())
```
However, the output ignores `Field`. The result is:
```json
{
  "$defs": {
    "cSection": {
      "maxItems": 2,
      "minItems": 2,
      "prefixItems": [
        {
          "title": "Main",
          "type": "string"
        },
        {
          "title": "Description",
          "type": "string"
        }
      ],
      "type": "array"
    }
  },
  "properties": {
    "section": {
      "allOf": [
        {
          "$ref": "#/$defs/cSection"
        }
      ],
      "description": "Section Description",
      "title": "Section"
    }
  },
  "required": [
    "section"
  ],
  "title": "cTest",
  "type": "object"
}
```
Descriptions are ignored, and titles are overridden by the field name with a capitalized first character.

I want to annotate title and description in NamedTuple.

`pip freeze` for pydantic
```
pydantic==2.8.2
pydantic-core==2.20.1
```

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@kimwonj77,

Thanks for your request. I'd recommend using `TypedDict` instead of `NamedTuple`, as we don't offer full support for `NamedTuple` as model equivalents, and I don't think we plan to in the near future:

```py
from typing_extensions import Annotated, TypedDict

from pydantic import BaseModel, Field


class cSection(TypedDict):
    main: Annotated[str, Field(title="Main Title", description="Main Title Description")]
    description: Annotated[str, Field(title="Content Description", description="Content Description")]

class cTest(BaseModel):
    section: cSection = Field(title="Section", description="Section Description")

print(cTest.model_json_schema())
```
