### ISSUE TITLE
pydantic v2 slow import performance

### ISSUE THREAD

**Issue by mikedavidson-evertz** [pydantic/pydantic#9905]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I've noticed that since upgrading to Pydantic v2, the time it takes to import models has significantly increased. This problem is exacerbated if you have a large number of models. I've seen the import time slow down by an order of magnitude. It would be good to know if this problem is going to be addressed.

I figured a new issue to address this problem would be good, but it's already mentioned in this performance issue linked below.
- https://github.com/pydantic/pydantic/issues/8652#issuecomment-2039580032
- https://github.com/pydantic/pydantic/issues/8652#issuecomment-2227464857

## Demonstrate the problem
For example, generating a single python file that contains all Pydantic models from the Swagger API schemas below demonstrates this issue clearly. 

```
# generate V1 models:
datamodel-codegen --url https://github.com/kubernetes/kubernetes/raw/master/api/openapi-spec/swagger.json  > k8s_v1.py

# generate V2 models:
datamodel-codegen --url https://github.com/kubernetes/kubernetes/raw/master/api/openapi-spec/swagger.json  --output-model-type=pydantic_v2.BaseModel > k8s_v2.py
```

Then in 2 separate python files, time/profile importing them.
```
**pydantic_v1.py** (version 1.10.17)
import k8s_v1

**pydantic_v2.py** (version 2.8.2)
import k8s_v2
```

## Timing imports

`time python3.9 pydantic_v1.py`   -> **2.85s**
![image](https://github.com/user-attachments/assets/e1156195-7d3b-4e50-b66b-7fd95b04c2fe)

`time python3.9 pydantic_v2.py ` ->  **54.62s**
![Screenshot from 2024-07-16 09-31-18](https://github.com/user-attachments/assets/bf3e0513-5a87-45ad-8696-281547bb5bd3)

### Python, Pydantic & OS Version

```Text
python: 3.9.19
pydantic: 2.8.2
OS: Ubuntu 22.04.4 LTS

Specs:
11th Gen Intel i7-11800H (16) @ 4.600GHz 
32GB DDR4 Memory
```

**Comment by nix010** [comment]
[Pydantic v2 significantly slower than v1](https://github.com/pydantic/pydantic/discussions/6748)
It have been acknowledged and I think put in the v2.9.0 roadmap already.

**Comment by sydney-runkle** [comment]
Indeed, we're working on improvements now. @nix010, thanks for linking those!

I'll tag this with `performance` so that we can track this example as we make progress on import time.

**Comment by sydney-runkle** [comment]
I'm currently working on this issue and plan to hopefully push a fix for v2.9!

**Comment by sydney-runkle** [comment]
Hey folks - I've addressed this via https://github.com/pydantic/pydantic/pull/10113 as well. Let me know what sort of differences you get with local testing!

**Comment by Viicos** [comment]
2.11 (final released planned by the end of March) brings significant performance improvements related to constructing models, in particular core schema building [^1].

An alpha release (2.11.0a1) was released today and can be installed, so that you can try it out. Do not hesitate to provide feedback if this improved (or did not) performance on your side.

Note that memory consumption haven’t been really optimized yet in this alpha release. We have plans to optimize it before the final release.

[^1]: Pydantic defines a core schema whenever a Model is defined, read more [here](https://docs.pydantic.dev/latest/internals/architecture/)
