### ISSUE TITLE
get install the `eval_type_backport` error, though don't use new types syntax

### ISSUE THREAD

**Issue by sir-sigurd** [pydantic/pydantic#9910]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

I get this error:

> TypeError: You have a type annotation 'bool | None' which makes use of newer typing features than are supported in your version of Python. To handle this error, you should either remove the use of new syntax or install the `eval_type_backport` package.

with the code example.

I can't "remove the use of new syntax" as suggested because I don't use new syntax.
I looks like this happens because pydantic itself uses new syntax in `StringConstraints`:
https://github.com/pydantic/pydantic/blob/b3ce47f38a906d0b957e0870a651da394b8461bc/pydantic/types.py#L696-L702

Probable fixes are:

1. use `typing.Union` instead of new syntax
2. add dependency on `eval_type_backport` package on old Python versions

### Example Code

```Python
import pydantic

class M(pydantic.BaseModel):
    f: pydantic.StringConstraints
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=false
                 install path: /Users/sergey/dev/work/quiltdata/quilt/lambdas/s3hash/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.18 (default, Jan 18 2024, 12:23:57)  [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.5-arm64-arm-64bit
             related packages: typing_extensions-4.9.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@sir-sigurd,

What happens if you do:

```py
from __future__ import annotations

import pydantic

class M(pydantic.BaseModel):
    f: pydantic.StringConstraints
```

**Comment by Viicos** [comment]
`StringConstraints` is not meant to be used as a type annotation, but only within `Annotated` (see [docs](https://docs.pydantic.dev/latest/api/types/#pydantic.types.StringConstraints)). However, the error you're getting seems weird, I'll try to check why Pydantic doesn't error correctly.

**Comment by sir-sigurd** [comment]
> @sir-sigurd,
> 
> What happens if you do:
> 
> ```python
> from __future__ import annotations
> 
> import pydantic
> 
> class M(pydantic.BaseModel):
>     f: pydantic.StringConstraints
> ```

I get the same error.

> `StringConstraints` is not meant to be used as a type annotation, but only within `Annotated` (see [docs](https://docs.pydantic.dev/latest/api/types/#pydantic.types.StringConstraints)). 

You're right, I didn't read migration guide carefully 😅.
So I'm closing the issue because it seems there is nothing TBD.
