### ISSUE TITLE
PrivateAttr of a pydantic dataclass is included in fields 

### ISSUE THREAD

**Issue by julians111** [pydantic/pydantic#9918]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`PrivateAttr` of pydantic dataclasses are visible by `dataclasses.fields`. This seems to contradict the documentation which states "private attributes are not treated as fields" (see [link](https://docs.pydantic.dev/2.7/concepts/models/#private-model-attributes)) and I didn't expect this to happen as a user. 

### Example Code

```Python
from pydantic import dataclasses, PrivateAttr
from dataclasses import fields


@dataclasses.dataclass
class TimeAwareModel:
    _a: int = PrivateAttr(default=5)
    b: str = ""

    def __post_init__(self):
        self._a = 0


print(any(f.name == "_a" for f in fields(TimeAwareModel)))  # True
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: <redacted>
               python version: 3.10.10 (main, Jan 23 2024, 17:56:29) [GCC 11.4.0]
                     platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.10.0
                       commit: unknown
```

**Comment by sydney-runkle** [comment]
@julians111,

Hmm, thanks for the question. I'm not sure yet if this is a bug, given that private attributes in stdlib dataclasses are also included in `fields`:

```py
from pydantic import PrivateAttr
from pydantic.dataclasses import dataclass as pydantic_dataclass
from dataclasses import fields, dataclass


@pydantic_dataclass
class TimeAwareModelPDC:
    _a: int = PrivateAttr(default=5)
    b: str = ""

    def __post_init__(self):
        self._a = 0


print(any(f.name == "_a" for f in fields(TimeAwareModelPDC)))  # True

@dataclass
class TimeAwareModelDC:
    _a: int = 5
    b: str = ""

    def __post_init__(self):
        self._a = 0

print(any(f.name == "_a" for f in fields(TimeAwareModelDC)))  # True
```

**Comment by sydney-runkle** [comment]
Given that this behaves the same for stdlib dataclasses and pydantic dataclasses, I wouldn't consider this a bug. If you feel as though the docs could be improved for the case above, feel free to submit a PR with clarification and I'd be happy to review!

Thanks for the report!
