### ISSUE TITLE
Async context manager 'ModelPrivateAttr' doesn't implement __aenter__ and __aexit__

### ISSUE THREAD

**Issue by jamesbraza** [pydantic/pydantic#9921]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The sample code runs, but then running `pylint==3.2.5` on the sample code gives this failure:

```none
a.py:10:8: E1701: Async context manager 'ModelPrivateAttr' doesn't implement __aenter__ and __aexit__. (not-async-context-manager)
```

Note that I am also using the `pylint-pydantic==0.3.2` plug-in and have `load-plugins = "pylint_pydantic"` in my `pyproject.toml`.

I am not sure if this is a Pydantic bug or a `pylint` false positive

### Example Code

```Python
import asyncio

from pydantic import BaseModel, PrivateAttr


class SomeModel(BaseModel):
    _some_lock: asyncio.Lock = PrivateAttr(default_factory=asyncio.Lock)

    async def some_method(self) -> None:
        async with self._some_lock:
            await asyncio.sleep(1)


model = SomeModel()
asyncio.run(model.some_method())
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /path/to/venv/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (main, Jul  3 2024, 13:35:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
                     platform: macOS-14.3-arm64-arm-64bit
             related packages: mypy-1.10.1 typing_extensions-4.12.2 fastapi-0.111.1
                       commit: unknown
```

**Comment by Viicos** [comment]
Looks like an issue on the `pylint` side, `_some_lock` should be inferred as `asyncio.Lock` (and type checkers such as `mypy` and `pyright` will do so).

**Comment by jamesbraza** [comment]
Okay thank you @Viicos , I have opened https://github.com/pylint-dev/pylint/issues/9813
