### ISSUE TITLE
unittest.mock.autospec and hastattr()

### ISSUE THREAD

**Issue by manfredlift** [pydantic/pydantic#9927]
### Discussed in https://github.com/pydantic/pydantic/discussions/2853

<div type='discussions-op-text'>

<sup>Originally posted by **atskae** May 28, 2021</sup>
I was mocking out some Pydantic `BaseModel` classes in a `pytest` environment since some of the model's fields were objects from an external package. I learned that if I `autospec` a `BaseModel` *class* (not object), then `hasattr()` is always `False`. This is not the case for normal Python classes:

```
>>> from pydantic import BaseModel
>>> class Cat:
...     name = None
...
>>> class PydanticCat(BaseModel):
...     name: str
...
>>> cat = create_autospec(Cat)
>>> hasattr(cat, 'name')
True
>>> pydantic_cat = create_autospec(PydanticCat)
>>> hasattr(pydantic_cat, 'name')
False
```

If I pass in an object `pydantic_cat = create_autospec(PydanticCat(name='meowth'))`, then `hasattr()` works as expected. I was just curious if this design was intentional and whether it is bad practice to `autospec` a Pydantic `BaseModel` class in this way, or if it even makes sense. Thanks!</div>

**Comment by sydney-runkle** [comment]
Hi!

This is the expected behavior - the `cat` attribute is attached to the instance, not the class. If you'd like this to be reflected as an attribute of the class, you can use the `ClassVar` annotation.

Additionally, you can see that the `name` attribute is present on the instance and instance mock:

```py
from unittest.mock import create_autospec
from pydantic import BaseModel
from typing import ClassVar

class Cat(BaseModel):
    name: str

print(hasattr(Cat, 'name'))  # False

CatMock = create_autospec(Cat)
print(hasattr(CatMock, 'name'))  # False

class Cat2(BaseModel):
    name: ClassVar[str] = 'Cat2'

print(hasattr(Cat2, 'name'))  # True

CatMock2 = create_autospec(Cat2)
print(hasattr(CatMock2, 'name'))  # True


cat_instance = Cat(name='Belinda')
print(hasattr(cat_instance, 'name'))  # True

cat_instance_mock = create_autospec(cat_instance)
print(hasattr(cat_instance_mock, 'name'))  # True
```

Thanks for your question!

**Comment by mraesener-aubex** [comment]
hey everybody, 

why is Pydantic intentionally behaving differently to Python here?
Maybe I don't get this right but ClassVar is a different thing compared to just checking if a class Definition has a certain attribute.

In my case I'm trying to use it like so:

```python

class Process(BaseModel):
    Kunde: str
    Modell: str | None

# part of another (pydantic) class
def search(self, key: str, value: str) -> List[Process]:
    """
    Search for processes where the attribute `key` matches `value`.
    """
    if not hasattr(Process, key):
        raise ValueError(f"{key} is not a valid attribute of Process")
    return [process for process in self.processes if getattr(process, key) == value]
      
```

I guess I could solve this differently but just wanted to add this as "more context" to the issue.
