### ISSUE TITLE
Pydantic throws errors on its own 'alias' and 'validation_alias' attibutes in the Field module

### ISSUE THREAD

**Issue by alphaveneno** [pydantic/pydantic#9928]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

**System info** as per: poetry run python -c "import pydantic.version; print(pydantic.version.version_info())": 

see below

--------------------------------

Note: the errors I am about to show occur with both _pip_ and _poetry_.

**expected outcome:**

prints 'finished'

**actual results:**

Traceback (most recent call last):
  File "/home/ra/Documents/webCourses/TDD/pydantic/materials-python-pydantic-/rp_tut/rp_tut/main.py", line 13, in <module>
    Employee.model_validate({"name":"Chris DeTuma", "email":"cdetuma@example.com","date_of_birth":"1998-04-02","salary":123_000.00,"department":"IT","elected_benefits":False}, strict=False)
  File "/home/ra/.cache/pypoetry/virtualenvs/rp-tut-22AcObYS-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Employee
_birth_date_  (italics are mine)
  Field required [type=missing, input_value={'name': 'Chris DeTuma', ...lected_benefits': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
_compensation_  (italics are mine)
  Field required [_type=missing_, input_value={'name': 'Chris DeTuma', ...lected_benefits': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
    
**corrective action:**

removal of  **alias="birth_date"**  and **alias="compensation"** from the Field attributes does not give any errors, code runs as expected

**additional investigations:**

_validation_alias_ gives the same error
_serialization_alias_ does not give an error, code runs as expected

I assume the error message 'type=missing' indicates Pydantic does not know what type 'alias' and 'validation_alias' are. 

**Attempts to force a type on 'alias' with:**

Annotated[str, Field(alias=".*")]

do not work

**This corrective attempt gives a syntax error:**

date_of_birth: date = Field(alias: str | None="birth_date", repr=False, frozen=True)

**removal of this (actually unrequired) dependency:**

typing_extensions-4.12.2

does not make a difference

### Example Code

```Python
# two files

main.py:

from pydantic_models import Employee
from datetime import date

Employee(
    name="Chris DeTuma",
    email="cdetuma@example.com",
    date_of_birth="1998-04-02",
    salary=123_000.00,
    department="IT",
    elected_benefits=True,
    )
    
print('finished')

----------------------------------

pydantic_models.py:

from datetime import date
from enum import Enum
from typing import Self
from uuid import UUID, uuid4

from pydantic import (
    BaseModel,
    EmailStr,
    Field,
    field_validator,
    model_validator,
)

class Department(Enum):
    HR = "HR"
    SALES = "SALES"
    IT = "IT"
    ENGINEERING = "ENGINEERING"


class Employee(BaseModel):
    employee_id: UUID = Field(default_factory=uuid4, frozen=True)
    name: str = Field(min_length=1, frozen=True)
    email: EmailStr = Field(pattern=r".+@example\.com$")
    date_of_birth: date = Field(alias="birth_date", repr=False, frozen=True)
    salary: float = Field(alias="compensation", gt=0, repr=False)
    department: Department
    elected_benefits: bool

    @field_validator("date_of_birth")
    @classmethod
    def check_valid_age(cls, date_of_birth: date) -> date:
        today = date.today()
        eighteen_years_ago = date(today.year - 18, today.month, today.day)

        if date_of_birth > eighteen_years_ago:
            raise ValueError("Employees must be at least 18 years old.")

        return date_of_birth

    @model_validator(mode="after")
    def check_it_benefits(self) -> Self:
        department = self.department
        elected_benefits = self.elected_benefits

        if department == Department.IT and elected_benefits:
            raise ValueError(
                "IT employees are contractors and don't qualify for benefits."
            )
        return self

-------------------------------------------
replacing:

Employee(
    name="Chris DeTuma",
    email="cdetuma@example.com",
    date_of_birth="1998-04-02",
    salary=123_000.00,
    department="IT",
    elected_benefits=True,
    )

with this, to force 'strict=False':

Employee.model_validate({"name":"Chris DeTuma", "email":"cdetuma@example.com","date_of_birth":"1998-04-02","salary":123_000.00,"department":"IT","elected_benefits":False}, strict=False)

...makes no difference
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
pydantic-core version: 2.20.1
pydantic-core build: profile=release pgo=true
install path: /home/ra/.cache/pypoetry/virtualenvs/rp-tut-22AcObYS-py3.11/lib/python3.11/site-packages/pydantic
python version: 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0]
platform: Linux-6.1.0-23-amd64-x86_64-with-glibc2.36
related packages: typing_extensions-4.12.2 pydantic-settings-2.3.4
commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @alphaveneno,

You need to use the `populate_by_name` config setting to use the field name or alias during validation:

```py
from datetime import date

from datetime import date
from enum import Enum
from typing_extensions import Self
from uuid import UUID, uuid4

from pydantic import (
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    field_validator,
    model_validator,
)

class Department(Enum):
    HR = "HR"
    SALES = "SALES"
    IT = "IT"
    ENGINEERING = "ENGINEERING"


class Employee(BaseModel):
    employee_id: UUID = Field(default_factory=uuid4, frozen=True)
    name: str = Field(min_length=1, frozen=True)
    email: EmailStr = Field(pattern=r".+@example\.com$")
    date_of_birth: date = Field(alias="birth_date", repr=False, frozen=True)
    salary: float = Field(alias="compensation", gt=0, repr=False)
    department: Department
    elected_benefits: bool

    model_config = ConfigDict(populate_by_name=True)

    @field_validator("date_of_birth")
    @classmethod
    def check_valid_age(cls, date_of_birth: date) -> date:
        today = date.today()
        eighteen_years_ago = date(today.year - 18, today.month, today.day)

        if date_of_birth > eighteen_years_ago:
            raise ValueError("Employees must be at least 18 years old.")

        return date_of_birth

    @model_validator(mode="after")
    def check_it_benefits(self) -> Self:
        department = self.department
        elected_benefits = self.elected_benefits

        if department == Department.IT and elected_benefits:
            raise ValueError(
                "IT employees are contractors and don't qualify for benefits."
            )
        return self

Employee(
    name="Chris DeTuma",
    email="cdetuma@example.com",
    date_of_birth="1998-04-02",
    salary=123_000.00,
    department="IT",
    elected_benefits=True,
)
    
print('finished')
```

https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.populate_by_name

**Comment by alphaveneno** [comment]
Thank you
