### ISSUE TITLE
Incorrect "raises" documentation for `BaseModel.model_validate_json`

### ISSUE THREAD

**Issue by DimaCybr** [pydantic/pydantic#9944]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

The docs for `BaseModel.model_validate_json` state that it raises `ValueError` If `json_data` is not a JSON string (https://github.com/pydantic/pydantic/blob/main/pydantic/main.py#L592).
On the other hand, the `SchemaValidator.validate_json` method which it calls claims that it raises `ValidationError` and not `ValueError` (https://github.com/pydantic/pydantic-core/blob/main/python/pydantic_core/_pydantic_core.pyi#L160).
In reality, I see that calling `model_validate_json` with invalid json string raises `ValidationError` and not `ValueError`.

### Example Code

```Python
from pydantic import BaseModel

class Test(BaseModel):
    id: str

# all these examples raise ValidationError and not ValueError
Test.model_validate_json('{asdasd}')
Test.model_validate_json(None)
Test.model_validate_json("123")
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
pydantic-core version: 2.20.1
pydantic-core build: profile=release pgo=true
python version: 3.11.8 (main, Mar 31 2024, 12:22:16) [Clang 15.0.0 (clang-1500.3.9.4)]
platform: macOS-14.5-arm64-arm-64bit
related packages: fastapi-0.110.3 typing_extensions-4.12.2
commit: unknown
```

**Comment by sydney-runkle** [comment]
Hi @DimaCybr,

`ValidationError` is a subclass of `ValueError`, see the source: https://github.com/pydantic/pydantic-core/blob/cb696e261a799333097d9674b9c55500eac54b74/python/pydantic_core/_pydantic_core.pyi#L740

**Comment by sydney-runkle** [comment]
That being said, I agree with your correction. Could you please open a PR with a fix? I'd be happy to review. Thanks!
