### ISSUE TITLE
Nested Discriminated Union + TypeAdapter

### ISSUE THREAD

**Issue by hswanson13** [pydantic/pydantic#9955]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello I think I might of found a bug, unless there is something else I can do. Any help is appreciated!
The last line throws this error:

```
Traceback (most recent call last):
  File "/home/hayden/repos/mtd-etl-app/play.py", line 127, in <module>
    PetListAdapter = TypeAdapter(list(Pet))
  File "/home/hayden/anaconda3/envs/ETLapp/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/home/hayden/anaconda3/envs/ETLapp/lib/python3.9/typing.py", line 767, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/home/hayden/anaconda3/envs/ETLapp/lib/python3.9/typing.py", line 767, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/home/hayden/anaconda3/envs/ETLapp/lib/python3.9/typing.py", line 166, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got 0.
```

I have confirmed using List from typing also throws the same error. I hope it is not an issue with my Python version.

### Example Code

```Python
from typing import Literal, Union
from typing_extensions import Annotated
from pydantic import BaseModel, Field, ValidationError, TypeAdapter

class BlackCat(BaseModel):
    pet_type: Literal['cat']
    color: Literal['black']
    black_name: str

class WhiteCat(BaseModel):
    pet_type: Literal['cat']
    color: Literal['white']
    white_name: str

class Dog(BaseModel):
    pet_type: Literal['dog']
    name: str

Cat = Annotated[Union[BlackCat, WhiteCat], Field(discriminator='color')]
Pet = Annotated[Union[Dog, Cat], Field(discriminator='pet_type')]
PetAdapter = TypeAdapter(Pet)
PetListAdapter = TypeAdapter(list(Pet)) #throws error
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/hayden/anaconda3/envs/ETLapp/lib/python3.9/site-packages/pydantic
               python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0]
                     platform: Linux-6.5.0-44-generic-x86_64-with-glibc2.35
             related packages: email-validator-2.0.0.post2 typing_extensions-4.9.0 typing_extensions-4.7.1
                       commit: unknown
```

**Comment by kc0506** [comment]
Shouldn't you use `list[Pet]` instead of `list(Pet)`?

**Comment by hswanson13** [comment]
> I think you should use `list[Pet]` instead of `list(Pet)`.

Oh wow this worked, thank you, just out of curiosity, what is the difference? I am kind of new to this stuff.

**Comment by kc0506** [comment]
`list` is a class, so calling `list(x)` means to create a new list object. For example, `list([1, 2, 3])` will give you an instance object of `list`. 
On the other hand, `list[x]` is equivalent to `list.__class_getitem__(x)`, which represents a type annotation of "list containing x only". This kind of type is called "generic." Here is an example usage:
```py
a: list[int] = [1, 2, 3]
```
The subscripted type is also a class in the sens that you can do things like
```py
a = list[int]([1, 2, 3])  # [1, 2, 3]
```

The `TypeAdapter` class constructor expects an arg that is a type annotation, not a list object. There for `list[x]` is what will fit in this case. 

You can refer to [docs of generic alias type](https://docs.python.org/3.9/library/stdtypes.html#types-genericalias) and the [python typing docs](https://typing.readthedocs.io/en/latest/reference/generics.html) for more information.

**Comment by sydney-runkle** [comment]
@kc0506 thanks for explaining!

**Comment by hswanson13** [comment]
> `list` is a class, so calling `list(x)` means to create a new list object. For example, `list([1, 2, 3])` will give you an instance object of `list`. On the other hand, `list[x]` is equivalent to `list.__class_getitem__(x)`, which represents a type annotation of "list containing x only". This kind of type is called "generic." Here is an example usage:
> 
> ```python
> a: list[int] = [1, 2, 3]
> ```
> 
> The subscripted type is also a class in the sens that you can do things like
> 
> ```python
> a = list[int]([1, 2, 3])  # [1, 2, 3]
> ```
> 
> The `TypeAdapter` class constructor expects an arg that is a type annotation, not a list object. Therefore `list[x]` is what will fit in this case.
> 
> You can refer to [docs of generic alias type](https://docs.python.org/3.9/library/stdtypes.html#types-genericalias) and the [python typing docs](https://typing.readthedocs.io/en/latest/reference/generics.html) for more information.

Awesome explanation, I really appreciate the help! Hope you have a great day
