### ISSUE TITLE
Add class name to "has conflict" warnings

### ISSUE THREAD

**Issue by msabramo** [pydantic/pydantic#9962]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

This would make it easier to identify which class has the conflict when multiple classes are involved.

Before:

```
.../site-packages/pydantic/_internal/_fields.py:160:
UserWarning: Field "model_max_budget"
has conflict with protected namespace "model_".
```

After:

```
.../site-packages/pydantic/_internal/_fields.py:160:
UserWarning: Field "model_max_budget" in LiteLLM_BudgetTable
has conflict with protected namespace "model_".
```

I started working on this and will have a PR ready shortly...

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [ ] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [ ] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [ ] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [X] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by msabramo** [comment]
@sydney-runkle: Do I close this issue or is there some automation that will do that when #9964 appears in a release?

**Comment by sydney-runkle** [comment]
@msabramo we can close this issue, and the change will show up in release notes :).
