### ISSUE TITLE
(🐞) `Literal` with `Enum`s aren't validated consistently

### ISSUE THREAD

**Issue by KotlinIsland** [pydantic/pydantic#9968]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

`Literal` with `Enum`s aren't validated consistently
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for A
o2
  Input should be <E.A: 'aa'> [type=literal_error, input_value='aa', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/literal_error
```

### Example Code

```Python
from enum import Enum
from typing import Literal

from pydantic import BaseModel


class E(Enum):
    A = "aa"


class A(BaseModel):
    o1: E
    o2: Literal[E.A]


print(A(o1="aa", o2="aa"))
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: C:\Users\AMONGUS\projects\test\.venv\Lib\site-packages\pydantic
               python version: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-10-10.0.19045-SP0
             related packages: typing_extensions-4.12.2
                       commit: unknown
```

**Comment by kc0506** [comment]
In my opinion, this might not be a bug. Changing your code to 
```py
print(A(o1="aa", o2=E.A))
```
makes it work.

It seems when you annotate a field with `Literal`, pydantic's validator expectes **exactly same value**, not **value that can be parsed correctly**. 

For example, 
```py
class A(BaseModel):
    a: int
    b: Literal[123]

A(a='123', b='123')  # ❌ '123' is not the same as 123
A(a='123', b=123)  # ✅
```

Back to your code, the `o1` field is correct because `'aa'` can be parsed to `E` by `E('aa')`. But what `o2` wants is `E.A`, not `'aa'`. If you want to pass string for both fields, you can change the annotation to 

```py
# `E.A` is an object of type `E`
# `E.A.value` is 'aa'

class A(BaseModel):
    o1: E
    o2: Literal[E.A.value]
```

**Comment by sydney-runkle** [comment]
I agree with the analysis above by @kc0506. Closing this as resolved for now, thanks @kc0506 for the great explanation!

**Comment by kc0506** [comment]
@sydney-runkle 
I just came across #9791. Perhaps we should close it for the same reason?

Also, I opened #9989 on `StrEnum`, which is similar but slightly different from these issues.

**Comment by KotlinIsland** [comment]
I've updated the OP with a working solution, maybe some kind of utility could be added that can narrow literals without disabling conversion
