### ISSUE TITLE
[Documentation] `docs/errors/usage_errors.md` incorrectly reference `model_serializer` in the `field-serializer-signature` section

### ISSUE THREAD

**Issue by Anvil** [pydantic/pydantic#9987]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Hello Dear Pydantic maintainers. I hope you are well in this hot summer (if you're up north)

Something is bothering me with the documentation, I must say.

It seems to me that this section of the documentation https://docs.pydantic.dev/2.8/errors/usage_errors/#field-serializer-signature heavily mentions `model_serializer` while it should actually mention `field_serializer`.

If i interpret this section correctly, everything seems right *except* the term "model_serializer". 

Would a basic string replacement s/model_serializer/field_serializer/ be enough ?

Should I submit a patch in this way ?

Also, there's no such (valuable) information in the `model-serializer-signature` section.
Would you be interested in an another update to fill this blank ?

I have found a lot of documentation for the `model_serializer(mode='plain')`, but either the documentation does not give examples for `mode='wrap'`, either I did not find them.

If there is indeed some missing bits, would be interested in me contributing to this as well? 
It really bothered me a few weeks ago, because I had to look inside the source code to find the matching types for the `handler` and `info` parameters to satisfy mypy.

Thank you for your work, pydantic is really helpful to me on a day to day basis.

### Example Code

```Python
# Does not apply.
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.8.2
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: /home/anvil/.local/lib/python3.12/site-packages/pydantic
               python version: 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)]
                     platform: Linux-6.8.9-300.fc40.x86_64-x86_64-with-glibc2.39
             related packages: pyright-1.1.348 typing_extensions-4.9.0 email-validator-2.1.0.post1 mypy-1.10.0
                       commit: unknown

I was looking at the main branch, for what it's worth.
```

**Comment by Anvil** [comment]
For the record, here's the branch I'm working on. 
https://github.com/Anvil/pydantic/tree/mod-ser-doc

I'll amend the commits when I'll have more informations.

**Comment by sydney-runkle** [comment]
Ah yeah, we don't currently support passing the `info` down to the next handler (as I understand it).

So you'll have to just do:

```py
from pydantic import BaseModel, Field, model_serializer, SerializationInfo, SerializerFunctionWrapHandler
from typing import Any

class C(BaseModel):
    field: str = Field(default="asdf")

    @model_serializer(mode="wrap")
    def c_mod_ser(
        self, nxt: SerializerFunctionWrapHandler, info: SerializationInfo
    ) -> dict[str, Any]:
        return nxt(self)
```

**Comment by sydney-runkle** [comment]
I'm surprised by the type problems associated with the return. Go ahead and open the PR as is for now, and we can review together!
