### ISSUE TITLE
Coercion of `Literal` with `StrEnum` and `str` is not consistent

### ISSUE THREAD

**Issue by kc0506** [pydantic/pydantic#9989]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Even though we have `'a' == S.a`, only `'a'` is acceptable for `Literal[S.a]`, not vice versa. I believe this inconsistency to be confusing. The problem seems related to [literal validator](https://github.com/pydantic/pydantic-core/blob/main/src/validators/literal.rs#67). Should I open an issue in `pydantic-core`? 👀

Related to #9968, #9791, #9276

### Example Code

```Python
class S(StrEnum):
    a = 'a'

class A(BaseModel):
    a: Literal[S.a]

class B(BaseModel):
    a: Literal['a']

assert 'a' == S.a
assert hash('a') == hash(S.a)

A(a='a')  # ✅
B(a=S.a)  # ❌
```

### Python, Pydantic & OS Version

```Text
pydantic version: 2.9.0a1
        pydantic-core version: 2.20.1
          pydantic-core build: profile=release pgo=true
                 install path: D:\pydantic\pydantic
               python version: 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)]
                     platform: Windows-11-10.0.22631-SP0
             related packages: mypy-1.1.1 pydantic-extra-types-2.9.0 pydantic-settings-2.3.4 typing_extensions-4.12.2
                       commit: c53c5fb9
```

**Comment by sydney-runkle** [comment]
I'll note, I think this can be fixed by decoupling our `Literal` and `Enum` validators in `pydantic-core`.

**Comment by sydney-runkle** [comment]
^^ I'm guessing this will fall under the scope of v2.10
